S3F: s3f::s3fnet::Protocols Class Reference
s3f::s3fnet::Protocols Class Reference
Managing protocols.
#include <protocols.h>
Static Public Member Functions
static ProtocolSession * newInstance (char *classname, ProtocolGraph *graph)
The method is used by ProtocolGraph's config method to create protocol session instances from the DML description.
Protocol instantiation
The following field and method should be protected.
We made them public in order for them to work with S3FNET_REGISTER_PROTOCOL macro.
static S3FNET_POINTER_VECTOR * registered_protocols = 0
A list of protocols already registered.
static int registerProtocol (ProtocolSession *(*fct)(char *, ProtocolGraph *))
Called by the S3FNET_REGISTER_PROTOCOL macro to register a protocol session.
Detailed Description
Managing protocols.
The Protocols class is used to manage instantiation of protocol sessions of given class names. C++ lacks support for self-reflection and this class provides a mechanism for creating protocol sessions from their corresponding class string names read from the DML description. In particular, the class defines a macro called S3FNET_REGISTER_PROTOCOL. It has two parameters: the name of the protocol session class and the matching string to identify the protocol session class in DML. For example, if you create a MAC layer protocol "MyMACSession" and if you want to identify your protocol in DML with "mac.my-mac-session", you should put S3FNET_REGISTER_PROTOCOL(MyMACSession, "mac.my-mac-session") inside the source file where you define the protocol.
Definition at line 35 of file protocols.h.
Member Function Documentation
ProtocolSession * s3f::s3fnet::Protocols::newInstance (char * classname, ProtocolGraph * graph) static
The method is used by ProtocolGraph's config method to create protocol session instances from the DML description.
Definition at line 31 of file protocols.cc.
References registered_protocols, and s3f::s3fnet::S3FNET_VECTOR().
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), and s3f::s3fnet::ProtocolGraph::config_session().
 {
   // if the protocol class name matches, return a new instance
   if(!registered_protocols) return 0;
   for(S3FNET_VECTOR(void*)::iterator iter = registered_protocols->begin();
       iter != registered_protocols->end(); iter++) {
     void* fct = *iter;
     ProtocolSession* sess =
       (*(ProtocolSession*(*)(char*, ProtocolGraph*))fct)
       (classname, graph);
     if(sess) return sess;
   }
   return 0;
 }
int s3f::s3fnet::Protocols::registerProtocol (ProtocolSession *(*)(char *, ProtocolGraph *) fct) static
Called by the S3FNET_REGISTER_PROTOCOL macro to register a protocol session.
Definition at line 16 of file protocols.cc.
References registered_protocols, and s3f::s3fnet::S3FNET_VECTOR().
 {
   // allocate the global data structure if it's not there
   if(registered_protocols == 0) {
     registered_protocols = new S3FNET_VECTOR(void*);
     assert(registered_protocols);
   }
   // add the protocol constructor (WE DON'T HAVE DUPLICATION CHECK!)
   registered_protocols->push_back((void*)fct);
   // we need to return something so that S3FNET_REGISTER_PROTOCOL macro works
   return 0;
 }
Member Data Documentation
S3FNET_POINTER_VECTOR * s3f::s3fnet::Protocols::registered_protocols = 0 static
A list of protocols already registered.
Definition at line 53 of file protocols.h.
Referenced by newInstance(), and registerProtocol().
The documentation for this class was generated from the following files:
protocols.h
protocols.cc