S3F: s3f::s3fnet::OpenVZMessage Class Reference
s3f::s3fnet::OpenVZMessage Class Reference
Protocol message for the OpenVZEventSession.
#include <openVZEmu_message.h>
Public Member Functions
OpenVZMessage ()
the default constructor
OpenVZMessage (EmuPacket *packet)
the constructor with EmuPacket
virtual ProtocolMessage * clone ()
Clone the protocol message (as required by the ProtocolMessage base class).
virtual int type ()
Return the protocol type that the message represents.
virtual int packingSize ()
This method returns the number of bytes that are needed to pack this message.
virtual int realByteCount ()
Return the number of bytes used by the protocol message on a real network.
void carryPayload (ProtocolMessage *payload)
This method appends another protocol message to this protocol message and treats it as the payload.
virtual ProtocolMessage * dropPayload ()
If there is a payload, drop it from the linked list, then return it.
ProtocolMessage * payload ()
Returns the next header.
virtual void erase ()
This method is called to release the memory of this packet and its subsequent payload.
virtual void erase_all ()
int totalPackingSize ()
Returns the total byte count (in simulation) including the payload.
int totalRealBytes ()
Returns the total number of bytes of the protocol message including the payload in the real-world.
ProtocolMessage * getMessageByType (int type_code)
Given a protocol message type code, this method goes through the message chain starting from this message, and returns the first ProtocolMessage that has this type code.
unsigned int get_type ()
void inc_evts ()
int dec_evts ()
Static Public Member Functions
static int registerMessage (ProtocolMessage *(*fct)(), int type)
Called by S3FNET_REGISTER_MESSAGE macro to register a protocol message.
Public Attributes
EmuPacket * ppkt
Pointer to the EmuPacket carried in the message, containing the real packet.
int ifid
To support OpenVZEmu, the network interface to receive the packet in the VE proxy node in S3FNet, i.e.
Static Public Attributes
static S3FNET_INT2PTR_MAP * registered_messages = 0
A mapping between message type and message constructor.
Protected Member Functions
virtual ~OpenVZMessage ()
The destructor is protected to avoid direct deletion; erase() should be called upon reclaiming a protocol message.
Protected Attributes
unsigned int __type
int __evts
Detailed Description
Protocol message for the OpenVZEventSession.
Define the OpenVZMessage protocol message, which contains a pointer to the EmuPacket carried in the message and the the network interface to receive the packet in the VE proxy node in S3FNet (the interface of the VE that the packet will be delivered to).
Definition at line 25 of file openVZEmu_message.h.
Constructor & Destructor Documentation
s3f::s3fnet::OpenVZMessage::OpenVZMessage ()
the default constructor
Definition at line 17 of file openVZEmu_message.cc.
Referenced by clone().
 {}
s3f::s3fnet::OpenVZMessage::OpenVZMessage (EmuPacket * packet)
the constructor with EmuPacket
Definition at line 28 of file openVZEmu_message.cc.
References ifid, and ppkt.
 {
         ppkt = packet;
         ifid = 0;
 }
virtual s3f::s3fnet::OpenVZMessage::~OpenVZMessage () inline protected virtual
The destructor is protected to avoid direct deletion; erase() should be called upon reclaiming a protocol message.
Definition at line 42 of file openVZEmu_message.h.
 {}
Member Function Documentation
virtual ProtocolMessage* s3f::s3fnet::OpenVZMessage::clone () inline virtual
Clone the protocol message (as required by the ProtocolMessage base class).
Implements s3f::s3fnet::ProtocolMessage.
Definition at line 46 of file openVZEmu_message.h.
References OpenVZMessage().
 { return new OpenVZMessage(*this); }
virtual int s3f::s3fnet::OpenVZMessage::type () inline virtual
Return the protocol type that the message represents.
Implements s3f::s3fnet::ProtocolMessage.
Definition at line 49 of file openVZEmu_message.h.
References s3f::s3fnet::S3FNET_PROTOCOL_TYPE_OPENVZ_EVENT.
 { return S3FNET_PROTOCOL_TYPE_OPENVZ_EVENT; }
int s3f::s3fnet::OpenVZMessage::packingSize () virtual
This method returns the number of bytes that are needed to pack this message.
In particular, add the length of the EmuPacket.
Reimplemented from s3f::s3fnet::ProtocolMessage.
Definition at line 34 of file openVZEmu_message.cc.
References EmuPacket::len, s3f::s3fnet::ProtocolMessage::packingSize(), and ppkt.
 {
   // must add the parent class packing size
   int mysiz = ProtocolMessage::packingSize();
   // add the length of the message string (including the terminating null)
   mysiz += ppkt->len;
   return mysiz;
 }
virtual int s3f::s3fnet::OpenVZMessage::realByteCount () inline virtual
Return the number of bytes used by the protocol message on a real network.
Implements s3f::s3fnet::ProtocolMessage.
Definition at line 59 of file openVZEmu_message.h.
References EmuPacket::len, and ppkt.
 { return ppkt->len; }
int s3f::s3fnet::ProtocolMessage::registerMessage (ProtocolMessage *(*)() fct, int type) static inherited
Called by S3FNET_REGISTER_MESSAGE macro to register a protocol message.
Definition at line 96 of file protocol_message.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolMessage::registered_messages, and S3FNET_MAKE_PAIR.
 {
   // allocate the global data structure if it's not there
   if(!registered_messages)
   {
     registered_messages = new S3FNET_INT2PTR_MAP;
     assert(registered_messages);
   }
   // insert the mapping; check if duplicated
   if(!registered_messages->insert(S3FNET_MAKE_PAIR(type, (void*)fct)).second)
     error_quit("ERROR: duplicate protocol message types: %d\n", type);
   // we need to return something so that S3FNET_REGISTER_MESSAGE macro works
   return 0;
 }
void s3f::s3fnet::ProtocolMessage::carryPayload (ProtocolMessage * payload) inherited
This method appends another protocol message to this protocol message and treats it as the payload.
Definition at line 27 of file protocol_message.cc.
References s3f::s3fnet::error_retn(), and s3f::s3fnet::ProtocolMessage::next.
Referenced by s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::send(), and s3f::s3fnet::TCPSession::send_data().
 {
   // adjust the links, warning if found dangling nodes
   if(next)
   {
     error_retn("WARNING: ProtocolMessage::carryPayload(), overwrite pre-exist payload (may cause memory leak)!\n");
     delete next;
   }
   next = load;
 }
ProtocolMessage * s3f::s3fnet::ProtocolMessage::dropPayload () virtual inherited
If there is a payload, drop it from the linked list, then return it.
Return NULL if there is no payload.
Definition at line 38 of file protocol_message.cc.
References s3f::s3fnet::ProtocolMessage::next.
Referenced by s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::SimpleMac::pop(), and s3f::s3fnet::UDPSession::receive().
 {
   // sever the link between this node and the payload and return it
   ProtocolMessage* pmsg = next;
   next = 0;
   return pmsg;
 }
ProtocolMessage* s3f::s3fnet::ProtocolMessage::payload () inline inherited
Returns the next header.
Definition at line 103 of file protocol_message.h.
References s3f::s3fnet::ProtocolMessage::next.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::BufferFromPacket(), s3f::s3fnet::DataMessage::DataMessage(), s3f::s3fnet::NetworkInterface::emu_packet_modify_iface(), s3f::s3fnet::DataMessage::packingSize(), s3f::s3fnet::DataMessage::realByteCount(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::TCPSession::receiver_recv_sack(), and s3f::s3fnet::DataMessage::~DataMessage().
 { return next; }
void s3f::s3fnet::ProtocolMessage::erase () virtual inherited
This method is called to release the memory of this packet and its subsequent payload.
One must avoid deleting a protocol message object directly. This requirement is necessary for the support to optimizations such as the reference counter.
For better protection, the destructor of the protocol message (and its extended classes) should be defined as protected.
Reimplemented from Message.
Definition at line 46 of file protocol_message.cc.
Referenced by s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::OpenFlowSwitchSession::HandleControlInput(), and s3f::s3fnet::SimpleMac::pop().
 {
   //printf("ProtocolMessage erased, type = %d\n", this->type());
   delete this;
 }
void s3f::s3fnet::ProtocolMessage::erase_all () virtual inherited
Reimplemented from Message.
Definition at line 52 of file protocol_message.cc.
References s3f::s3fnet::ProtocolMessage::erase_all(), and s3f::s3fnet::ProtocolMessage::next.
Referenced by s3f::s3fnet::ProtocolMessage::erase_all(), s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::IPSession::handle_pop_pkt(), and s3f::s3fnet::DummySession::pop().
 {
         if(this->next) this->next->erase_all();
     //printf("ProtocolMessage deleted, type = %d\n", this->type());
         delete this;
 }
int s3f::s3fnet::ProtocolMessage::totalPackingSize () inherited
Returns the total byte count (in simulation) including the payload.
Definition at line 60 of file protocol_message.cc.
References s3f::s3fnet::ProtocolMessage::next, s3f::s3fnet::ProtocolMessage::packingSize(), and s3f::s3fnet::ProtocolMessage::totalPackingSize().
Referenced by s3f::s3fnet::ProtocolMessage::totalPackingSize().
 {
   // add them all
   if(next)
           return packingSize()+next->totalPackingSize();
   else
           return packingSize();
 }
int s3f::s3fnet::ProtocolMessage::totalRealBytes () inherited
Returns the total number of bytes of the protocol message including the payload in the real-world.
Definition at line 74 of file protocol_message.cc.
References s3f::s3fnet::ProtocolMessage::next, s3f::s3fnet::ProtocolMessage::realByteCount(), and s3f::s3fnet::ProtocolMessage::totalRealBytes().
Referenced by s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::IPSession::push(), and s3f::s3fnet::ProtocolMessage::totalRealBytes().
 {
   // add them all
   if(next)
           return realByteCount()+next->totalRealBytes();
   else
           return realByteCount();
 }
ProtocolMessage * s3f::s3fnet::ProtocolMessage::getMessageByType (int type_code) inherited
Given a protocol message type code, this method goes through the message chain starting from this message, and returns the first ProtocolMessage that has this type code.
If none is found, NULL is returned.
Definition at line 83 of file protocol_message.cc.
References s3f::s3fnet::ProtocolMessage::next, and s3f::s3fnet::ProtocolMessage::type().
 {
   ProtocolMessage* cur = this;
   while(cur)
   {
     if(cur->type() == t) return cur;
     cur = cur->next;
   }
   return 0;
 }
unsigned int Message::get_type () inline inherited
Definition at line 23 of file message.h.
References Message::__type.
 { return __type; }
void Message::inc_evts () inline inherited
Definition at line 28 of file message.h.
References Message::__evts.
Referenced by Event::Event().
 { __evts++; }
int Message::dec_evts () inline inherited
Definition at line 29 of file message.h.
References Message::__evts.
Referenced by Event::~Event().
 { return --__evts; }
Member Data Documentation
EmuPacket* s3f::s3fnet::OpenVZMessage::ppkt
Pointer to the EmuPacket carried in the message, containing the real packet.
Definition at line 62 of file openVZEmu_message.h.
Referenced by OpenVZMessage(), packingSize(), s3f::s3fnet::OpenVZEventSession::pop(), and realByteCount().
int s3f::s3fnet::OpenVZMessage::ifid
To support OpenVZEmu, the network interface to receive the packet in the VE proxy node in S3FNet, i.e.
the interface of the VE that the packet will be delivered to
Definition at line 68 of file openVZEmu_message.h.
Referenced by OpenVZMessage(), and s3f::s3fnet::OpenVZEventSession::pop().
S3FNET_INT2PTR_MAP * s3f::s3fnet::ProtocolMessage::registered_messages = 0 static inherited
A mapping between message type and message constructor.
Definition at line 158 of file protocol_message.h.
Referenced by s3f::s3fnet::ProtocolMessage::registerMessage().
unsigned int Message::__type protected inherited
Definition at line 31 of file message.h.
Referenced by Message::clone(), Message::get_type(), Message::Message(), and Message::operator=().
int Message::__evts protected inherited
Definition at line 32 of file message.h.
Referenced by Message::clone(), Message::dec_evts(), Message::inc_evts(), Message::Message(), and Message::operator=().
The documentation for this class was generated from the following files:
openVZEmu_message.h
openVZEmu_message.cc