S3F: s3f::s3fnet::SimpleMacMessage Class Reference
s3f::s3fnet::SimpleMacMessage Class Reference
Protocol message for the simple MAC layer.
#include <simple_mac_message.h>
Public Member Functions
SimpleMacMessage ()
The default constructor without any argument.
SimpleMacMessage (MACADDR src, MACADDR dest)
The constructor with the MACADDR field.
SimpleMacMessage (Mac48Address *_src, Mac48Address *_dst)
The constructor with the Mac48Address field.
SimpleMacMessage (const SimpleMacMessage &)
The copy constructor.
virtual ProtocolMessage * clone ()
Clone the protocol message (as required by the ProtocolMessage base class).
int type ()
Return the protocol type that the message represents.
virtual int packingSize ()
This method returns the number of bytes that are needed to pack this pseudo-mac header.
virtual int realByteCount ()
Returns the real size only for this protocol header.
void carryPayload (ProtocolMessage *payload)
This method appends another protocol message to this protocol message and treats it as the payload.
virtual ProtocolMessage * dropPayload ()
If there is a payload, drop it from the linked list, then return it.
ProtocolMessage * payload ()
Returns the next header.
virtual void erase ()
This method is called to release the memory of this packet and its subsequent payload.
virtual void erase_all ()
int totalPackingSize ()
Returns the total byte count (in simulation) including the payload.
int totalRealBytes ()
Returns the total number of bytes of the protocol message including the payload in the real-world.
ProtocolMessage * getMessageByType (int type_code)
Given a protocol message type code, this method goes through the message chain starting from this message, and returns the first ProtocolMessage that has this type code.
unsigned int get_type ()
void inc_evts ()
int dec_evts ()
Static Public Member Functions
static int registerMessage (ProtocolMessage *(*fct)(), int type)
Called by S3FNET_REGISTER_MESSAGE macro to register a protocol message.
Public Attributes
MACADDR src
The source MAC address of this frame.
MACADDR dest
The destination MAC address of this frame.
Mac48Address * src48
The source MAC address of this frame in IEEE 48-bit format.
Mac48Address * dst48
The destination MAC address of this frame in IEEE 48-bit format.
Static Public Attributes
static S3FNET_INT2PTR_MAP * registered_messages = 0
A mapping between message type and message constructor.
Protected Member Functions
virtual ~SimpleMacMessage ()
The destructor.
Protected Attributes
unsigned int __type
int __evts
Detailed Description
Protocol message for the simple MAC layer.
Define the simple MAC header protocol message, which simply contains the next hop address. We don't model MAC/PHY layers in detail for wired network simulation. For now, a next hop address will suffice. For more complicated link layer models, we would need more details.
Definition at line 28 of file simple_mac_message.h.
Constructor & Destructor Documentation
s3f::s3fnet::SimpleMacMessage::SimpleMacMessage ()
The default constructor without any argument.
Definition at line 14 of file simple_mac_message.cc.
Referenced by clone().
                                    :
                   src(0), dest(0), src48(NULL), dst48(NULL) {}
s3f::s3fnet::SimpleMacMessage::SimpleMacMessage (MACADDR src, MACADDR dest)
The constructor with the MACADDR field.
Definition at line 17 of file simple_mac_message.cc.
                                                              :
                   src(_src), dest(_dst), src48(NULL), dst48(NULL) {}
s3f::s3fnet::SimpleMacMessage::SimpleMacMessage (Mac48Address * _src, Mac48Address * _dst)
The constructor with the Mac48Address field.
Definition at line 20 of file simple_mac_message.cc.
References s3f::s3fnet::Mac48Address::CopyFrom(), dst48, and src48.
                                                                          :
                   src(0), dest(0){
         src48 = new Mac48Address();
         src48->CopyFrom(_src);
         dst48 = new Mac48Address();
         dst48->CopyFrom(_dst);
 }
s3f::s3fnet::SimpleMacMessage::SimpleMacMessage (const SimpleMacMessage & msg)
The copy constructor.
Definition at line 28 of file simple_mac_message.cc.
References s3f::s3fnet::Mac48Address::CopyFrom(), dst48, and src48.
                                                               :
                   ProtocolMessage(msg), // important!!!
                   src(msg.src), dest(msg.dest)
 {
         src48 = new Mac48Address();
         src48->CopyFrom(msg.src48);
         dst48 = new Mac48Address();
         dst48->CopyFrom(msg.dst48);
 }
s3f::s3fnet::SimpleMacMessage::~SimpleMacMessage () protected virtual
The destructor.
Definition at line 44 of file simple_mac_message.cc.
References dst48, and src48.
 {
         if(src48) delete src48;
         if(dst48) delete dst48;
 }
Member Function Documentation
ProtocolMessage * s3f::s3fnet::SimpleMacMessage::clone () virtual
Clone the protocol message (as required by the ProtocolMessage base class).
Implements s3f::s3fnet::ProtocolMessage.
Definition at line 38 of file simple_mac_message.cc.
References SimpleMacMessage().
 {
         //printf ("ProtocolMessage* SimpleMacMessage::clone()\n");
         return new SimpleMacMessage(*this);
 }
int s3f::s3fnet::SimpleMacMessage::type () inline virtual
Return the protocol type that the message represents.
Implements s3f::s3fnet::ProtocolMessage.
Definition at line 47 of file simple_mac_message.h.
References s3f::s3fnet::S3FNET_PROTOCOL_TYPE_SIMPLE_MAC.
 { return S3FNET_PROTOCOL_TYPE_SIMPLE_MAC; }
virtual int s3f::s3fnet::SimpleMacMessage::packingSize () inline virtual
This method returns the number of bytes that are needed to pack this pseudo-mac header.
This is for serialization.
Reimplemented from s3f::s3fnet::ProtocolMessage.
Definition at line 53 of file simple_mac_message.h.
References s3f::s3fnet::ProtocolMessage::packingSize().
   {
     //return 2*sizeof(MACADDR) + ProtocolMessage::packingSize();
     return 2*6 + ProtocolMessage::packingSize();
   }
virtual int s3f::s3fnet::SimpleMacMessage::realByteCount () inline virtual
Returns the real size only for this protocol header.
The default behavior is doing nothing except returning zero.
Implements s3f::s3fnet::ProtocolMessage.
Definition at line 61 of file simple_mac_message.h.
 { return 0; }
int s3f::s3fnet::ProtocolMessage::registerMessage (ProtocolMessage *(*)() fct, int type) static inherited
Called by S3FNET_REGISTER_MESSAGE macro to register a protocol message.
Definition at line 96 of file protocol_message.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolMessage::registered_messages, and S3FNET_MAKE_PAIR.
 {
   // allocate the global data structure if it's not there
   if(!registered_messages)
   {
     registered_messages = new S3FNET_INT2PTR_MAP;
     assert(registered_messages);
   }
   // insert the mapping; check if duplicated
   if(!registered_messages->insert(S3FNET_MAKE_PAIR(type, (void*)fct)).second)
     error_quit("ERROR: duplicate protocol message types: %d\n", type);
   // we need to return something so that S3FNET_REGISTER_MESSAGE macro works
   return 0;
 }
void s3f::s3fnet::ProtocolMessage::carryPayload (ProtocolMessage * payload) inherited
This method appends another protocol message to this protocol message and treats it as the payload.
Definition at line 27 of file protocol_message.cc.
References s3f::s3fnet::error_retn(), and s3f::s3fnet::ProtocolMessage::next.
Referenced by s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::send(), and s3f::s3fnet::TCPSession::send_data().
 {
   // adjust the links, warning if found dangling nodes
   if(next)
   {
     error_retn("WARNING: ProtocolMessage::carryPayload(), overwrite pre-exist payload (may cause memory leak)!\n");
     delete next;
   }
   next = load;
 }
ProtocolMessage * s3f::s3fnet::ProtocolMessage::dropPayload () virtual inherited
If there is a payload, drop it from the linked list, then return it.
Return NULL if there is no payload.
Definition at line 38 of file protocol_message.cc.
References s3f::s3fnet::ProtocolMessage::next.
Referenced by s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::SimpleMac::pop(), and s3f::s3fnet::UDPSession::receive().
 {
   // sever the link between this node and the payload and return it
   ProtocolMessage* pmsg = next;
   next = 0;
   return pmsg;
 }
ProtocolMessage* s3f::s3fnet::ProtocolMessage::payload () inline inherited
Returns the next header.
Definition at line 103 of file protocol_message.h.
References s3f::s3fnet::ProtocolMessage::next.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::BufferFromPacket(), s3f::s3fnet::DataMessage::DataMessage(), s3f::s3fnet::NetworkInterface::emu_packet_modify_iface(), s3f::s3fnet::DataMessage::packingSize(), s3f::s3fnet::DataMessage::realByteCount(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::TCPSession::receiver_recv_sack(), and s3f::s3fnet::DataMessage::~DataMessage().
 { return next; }
void s3f::s3fnet::ProtocolMessage::erase () virtual inherited
This method is called to release the memory of this packet and its subsequent payload.
One must avoid deleting a protocol message object directly. This requirement is necessary for the support to optimizations such as the reference counter.
For better protection, the destructor of the protocol message (and its extended classes) should be defined as protected.
Reimplemented from Message.
Definition at line 46 of file protocol_message.cc.
Referenced by s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::OpenFlowSwitchSession::HandleControlInput(), and s3f::s3fnet::SimpleMac::pop().
 {
   //printf("ProtocolMessage erased, type = %d\n", this->type());
   delete this;
 }
void s3f::s3fnet::ProtocolMessage::erase_all () virtual inherited
Reimplemented from Message.
Definition at line 52 of file protocol_message.cc.
References s3f::s3fnet::ProtocolMessage::erase_all(), and s3f::s3fnet::ProtocolMessage::next.
Referenced by s3f::s3fnet::ProtocolMessage::erase_all(), s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::IPSession::handle_pop_pkt(), and s3f::s3fnet::DummySession::pop().
 {
         if(this->next) this->next->erase_all();
     //printf("ProtocolMessage deleted, type = %d\n", this->type());
         delete this;
 }
int s3f::s3fnet::ProtocolMessage::totalPackingSize () inherited
Returns the total byte count (in simulation) including the payload.
Definition at line 60 of file protocol_message.cc.
References s3f::s3fnet::ProtocolMessage::next, s3f::s3fnet::ProtocolMessage::packingSize(), and s3f::s3fnet::ProtocolMessage::totalPackingSize().
Referenced by s3f::s3fnet::ProtocolMessage::totalPackingSize().
 {
   // add them all
   if(next)
           return packingSize()+next->totalPackingSize();
   else
           return packingSize();
 }
int s3f::s3fnet::ProtocolMessage::totalRealBytes () inherited
Returns the total number of bytes of the protocol message including the payload in the real-world.
Definition at line 74 of file protocol_message.cc.
References s3f::s3fnet::ProtocolMessage::next, s3f::s3fnet::ProtocolMessage::realByteCount(), and s3f::s3fnet::ProtocolMessage::totalRealBytes().
Referenced by s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::IPSession::push(), and s3f::s3fnet::ProtocolMessage::totalRealBytes().
 {
   // add them all
   if(next)
           return realByteCount()+next->totalRealBytes();
   else
           return realByteCount();
 }
ProtocolMessage * s3f::s3fnet::ProtocolMessage::getMessageByType (int type_code) inherited
Given a protocol message type code, this method goes through the message chain starting from this message, and returns the first ProtocolMessage that has this type code.
If none is found, NULL is returned.
Definition at line 83 of file protocol_message.cc.
References s3f::s3fnet::ProtocolMessage::next, and s3f::s3fnet::ProtocolMessage::type().
 {
   ProtocolMessage* cur = this;
   while(cur)
   {
     if(cur->type() == t) return cur;
     cur = cur->next;
   }
   return 0;
 }
unsigned int Message::get_type () inline inherited
Definition at line 23 of file message.h.
References Message::__type.
 { return __type; }
void Message::inc_evts () inline inherited
Definition at line 28 of file message.h.
References Message::__evts.
Referenced by Event::Event().
 { __evts++; }
int Message::dec_evts () inline inherited
Definition at line 29 of file message.h.
References Message::__evts.
Referenced by Event::~Event().
 { return --__evts; }
Member Data Documentation
MACADDR s3f::s3fnet::SimpleMacMessage::src
The source MAC address of this frame.
Definition at line 64 of file simple_mac_message.h.
MACADDR s3f::s3fnet::SimpleMacMessage::dest
The destination MAC address of this frame.
Definition at line 67 of file simple_mac_message.h.
Mac48Address* s3f::s3fnet::SimpleMacMessage::src48
The source MAC address of this frame in IEEE 48-bit format.
Definition at line 70 of file simple_mac_message.h.
Referenced by s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::OpenFlowSwitchSession::pop(), SimpleMacMessage(), and ~SimpleMacMessage().
Mac48Address* s3f::s3fnet::SimpleMacMessage::dst48
The destination MAC address of this frame in IEEE 48-bit format.
Definition at line 73 of file simple_mac_message.h.
Referenced by s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::OpenFlowSwitchSession::pop(), SimpleMacMessage(), and ~SimpleMacMessage().
S3FNET_INT2PTR_MAP * s3f::s3fnet::ProtocolMessage::registered_messages = 0 static inherited
A mapping between message type and message constructor.
Definition at line 158 of file protocol_message.h.
Referenced by s3f::s3fnet::ProtocolMessage::registerMessage().
unsigned int Message::__type protected inherited
Definition at line 31 of file message.h.
Referenced by Message::clone(), Message::get_type(), Message::Message(), and Message::operator=().
int Message::__evts protected inherited
Definition at line 32 of file message.h.
Referenced by Message::clone(), Message::dec_evts(), Message::inc_evts(), Message::Message(), and Message::operator=().
The documentation for this class was generated from the following files:
simple_mac_message.h
simple_mac_message.cc