S3F: s3f::s3fnet::SimInterface Class Reference
s3f::s3fnet::SimInterface Class Reference
The S3FNet simulation interface class.
#include <s3fnet.h>
Public Member Functions
SimInterface (int tl, int ltps, bool isOpenVZEmu, int openvz_emulation_type, int of_ctrl_type=0, int of_ctrl_model=0)
the constructor
virtual ~SimInterface ()
the destructor
void BuildModel (s3f::dml::dmlConfig *cfg)
to build the s3fnet simulation model based on the DML file
virtual void BuildModel (vector< string >)
There is no base class instantiation for BuildModel.
void InitModel ()
It is assumed that the call to BuildModel will create the objects needed in the simulation.
ltime_t advance (ltime_t)
Method advance is called to all the simulation to advance to the simulation time passed as an argument, using the method indicated by next_action.
ltime_t advance (next_action, ltime_t)
ltime_t advance (stop_cond, ltime_t)
ltime_t advance_body (next_action, ltime_t, stop_cond)
Direct the simulation to advance another t units of simulation time.
int get_log_ticks_per_sec ()
Retrieve the simulation clock timescale provided.
void put_log_ticks_per_sec (int ltps)
Place the simulation clock timescale provided.
Timeline * get_Timeline (unsigned int tl)
Fetch the address of the Timeline whose index is provided as an argument.
unsigned int get_numTimelines ()
Return the number of Timelines created for this simulation.
ltime_t clock ()
TimelineInterface * get_timeline_interface ()
void runtime_measurements ()
Return measurement including simulation time, total time, total events, etc.
Public Attributes
Net * topnet
pointer to the topnet object
int openflow_controller_type
int openflow_controller_model
Protected Member Functions
ltime_t full_exc_time ()
return the entire execution time (simulation + initialization/model-building)
ltime_t sim_exc_time ()
return the simulation time
Protected Attributes
vector< TimelineThread > __timeline_threads
keep a vector of every Timeline created
unsigned int __num_timelines
Total number of Timelines created.
ltime_t __clock
time to which the simulation has advanced
int __log_ticks_per_sec
Time-scale of clock tickc, log base 10 of number of clock ticks in a second.
TimelineInterface __tli
Pointer to the data structure created to interface with simulation Timelines.
ltime_t __start_build_time
time when BuildModel is called;
ltime_t __start_run_time
time when advance first called
ltime_t __end_run_time
time when advance finishes
ltime_t __srt_utime
ltime_t __srt_stime
ltime_t __acc_utime
ltime_t __acc_stime
Detailed Description
The S3FNet simulation interface class.
The S3FNet network simulation interface class for interacting with the underlying S3F API.
Definition at line 384 of file s3fnet.h.
Constructor & Destructor Documentation
s3f::s3fnet::SimInterface::SimInterface (int tl, int ltps, bool isOpenVZEmu, int openvz_emulation_type, int of_ctrl_type = 0, int of_ctrl_model = 0) inline
the constructor
Parameters
tl the number of simulation threads to create (pthreads).
ltps the time scale of the clock ticks in terms of log base 10 clock ticks per second.
isOpenVZEmu whether the OpenVZ-based emulation is supported. The true/false value is passed through DML (one of the top few lines).
openvz_emulation_type indicates the type of openvz-based emulation, local (single physical machine) or distributed.
of_ctrl_type indicates the type of simulated openflow controller. 0 means non-entity-based controller (default), interacting with simulated openflow switches through function calls; 1 means entity-based controller that aligned to a timeline like other S3F entity, and controller is a protocol session.
of_ctrl_model indicates the model of simulated non-entity-based openflow controller. 0 means no controller 1 means OF_LEARNING_SWITCH_CONTROLLER refer openflow_interface.h for more configuration
Definition at line 399 of file s3fnet.h.
                                                                                                                             :
            Interface(tl,ltps, isOpenVZEmu, openvz_emulation_type), openflow_controller_type(of_ctrl_type), openflow_controller_model(of_ctrl_model) {}
s3f::s3fnet::SimInterface::~SimInterface () virtual
the destructor
Definition at line 64 of file s3fnet.cc.
References topnet.
 {
         delete topnet;
 }
Member Function Documentation
void s3f::s3fnet::SimInterface::BuildModel (s3f::dml::dmlConfig * cfg)
to build the s3fnet simulation model based on the DML file
Definition at line 69 of file s3fnet.cc.
References s3f::s3fnet::Net::config(), s3f::s3fnet::Net::init(), Interface::InitModel(), MAIN_DUMP, RNGS::RngStream::nextState_lock, and topnet.
Referenced by main().
 {
   int i, j;
   /* initialize the RNG class mutex. This needed to
      make this class thread safe---every new instantiation
      modifies a state that creates the state of the next
      instantiation
   */
   pthread_mutex_init(&RNGS::RngStream::nextState_lock,NULL);
   // create top net
   MAIN_DUMP(printf("creating the top net.\n"));
   topnet = new Net(this);
   MAIN_DUMP(printf("configuring the top net.\n"));
   topnet->config(cfg);
   // initialize the entities (hosts)
   this->InitModel();
   MAIN_DUMP(printf("initializing the top net.\n"));
   topnet->init();
   // now it's safe to reclaim the dml tree
   delete cfg;
 }
void Interface::BuildModel (vector< string >) virtual inherited
There is no base class instantiation for BuildModel.
One must be crafted for the application or application domain. We imagine that the instantiated class will want access to the command line arguments, and so give a vector of strings as a way of passing these (or anything else).
Definition at line 259 of file interface.cc.
 {}
void Interface::InitModel () inherited
It is assumed that the call to BuildModel will create the objects needed in the simulation.
After these have been constructed the InitModel method is called. This visits every Timeline and calls the init() method for every Entity on every Timeline. These init()s can finish establishing connections between objects.
Definition at line 166 of file interface.cc.
References Timeline::__channels_at_minimum, Timeline::__entity_list, Timeline::__min_sync_cross_timeline_delay, Timeline::__num_timelines, Interface::__timeline_threads, Interface::__tli, Timeline::__window_size, Timeline::count_min_delay_crossings(), SimCtrl::emu_init(), SimCtrl::errcode2txt(), Timeline::initialize_appt(), TimelineInterface::isOpenVZEmu, LOOKAHEAD_ANN, LOOKAHEAD_NONE, Timeline::min_sync_all_timeline_delay(), Timeline::min_sync_cross_timeline_delay(), and TimelineInterface::sc.
Referenced by BuildModel(), and main().
{
 #ifdef OPENVZ_EMULATION
   //initialize openVZ emulation for the first time
   if(__tli.isOpenVZEmu == true)
   {
           int return_code;
 #ifdef OPENVZ_EMULATION_LOOKAHEAD
           return_code = __tli.sc->emu_init(LOOKAHEAD_ANN);
 #else
           return_code = __tli.sc->emu_init(LOOKAHEAD_NONE);
 #endif
           if(return_code != 0)
           {
                   printf("emu_init() error, error code = %s\n", SimCtrl::errcode2txt(return_code));
                   exit(-1);
           }
           else
           {
                   printf("emu_init() done\n");
           }
   }
 #endif
         unsigned int num_timelines = __timeline_threads.size();
         for(unsigned int t=0; t<num_timelines; t++) {
                 Timeline* tl = __timeline_threads[t].get_timeline();
                 for(unsigned int e = 0;  e< tl->__entity_list.size(); e++ ) {
                         tl->__entity_list[e]->init();
                 }
                 // tl->__in_appt.resize(num_timelines);
                 // tl->__out_appt.resize(num_timelines);
         }
         // This initialization process will have identified on each timeline
         // the value of the smallest cross-timeline minimum write time value.
         //  Find the smallest such
         //
         ltime_t mxtd = -1;
         ltime_t thrs;
         for(unsigned int t=0; t<__timeline_threads.size(); t++ ) {
                 Timeline* tl = __timeline_threads[t].get_timeline();
                 tl->min_sync_all_timeline_delay(-1); //compute min channel delay (all channels) per timeline
                 ltime_t thrs  = tl->min_sync_cross_timeline_delay(-1);
                 if( thrs != -1 && (mxtd < 0 || thrs < mxtd) ) mxtd = thrs;
         }
         // now mxtd has the minimum cross timeline delay among all connections.
         // as a heuristic, set the window threshold equal to the number
         // of timelines times this minimum
 #ifdef COMPOSITE_SYNC
         thrs = Timeline::__num_timelines*mxtd;
 #else
         thrs = 0;
 #endif
         // printf("true min x timeline delay is %ld, window size is %ld\n", mxtd, thrs);
         // for each timeline recompute it's minimum synchronous cross-timeline delay
         for(unsigned int t=0; t<__timeline_threads.size(); t++ ) {
                 Timeline* tl = __timeline_threads[t].get_timeline();
                 tl->__min_sync_cross_timeline_delay  = tl->min_sync_cross_timeline_delay(thrs);
                 tl->__window_size = thrs;
                 // initialize the composite synchronization structure using this threshold
                 //
                 tl->initialize_appt(true, thrs);
                 for(unsigned int e = 0;  e< tl->__entity_list.size(); e++ ) {
                         tl->__channels_at_minimum
                         = tl->count_min_delay_crossings(thrs);
                 }
         }
 }
ltime_t Interface::advance (ltime_t t) inherited
Method advance is called to all the simulation to advance to the simulation time passed as an argument, using the method indicated by next_action.
The return value describes how far in simulation time the simulation has advanced after processing the advance directive.
Definition at line 262 of file interface.cc.
References Interface::advance_body(), STOP_BEFORE_TIME, and STOP_ON_ANY.
Referenced by main().
{
         return advance_body(STOP_BEFORE_TIME, t, STOP_ON_ANY);
 }
ltime_t Interface::advance (next_action na, ltime_t t) inherited
Definition at line 266 of file interface.cc.
References Interface::advance_body(), STOP_BEFORE_TIME, and STOP_ON_ANY.
{
         return advance_body(STOP_BEFORE_TIME, t, STOP_ON_ANY);
 }
ltime_t Interface::advance (stop_cond sc, ltime_t t) inherited
Definition at line 270 of file interface.cc.
References Interface::advance_body(), and STOP_FUNCTION.
{
         return advance_body(STOP_FUNCTION, t, sc);
 }
ltime_t Interface::advance_body (next_action nxt_act, ltime_t t, stop_cond sc) inherited
Direct the simulation to advance another t units of simulation time.
When more than one simulation thread is involved, Cross-timeline constraints may inhibit this however, so the return value is how the simulation actually advanced nxt_act = STOP_BEFORE_TIME allows for time to advance as far as t when there is one simulation thread, nxt_act = SYNCH_WINDOW explicitly advances only as far as the window allows. nxt_act == GLOBAL advances
Definition at line 284 of file interface.cc.
References Interface::__acc_stime, Interface::__acc_utime, Interface::__clock, Interface::__end_run_time, Interface::__num_timelines, Interface::__srt_stime, Interface::__srt_utime, Interface::__start_run_time, Interface::__tli, Interface::clock(), SimCtrl::emu_done(), SimCtrl::errcode2txt(), TimelineInterface::get_stop_before(), get_wall_time(), TimelineInterface::isOpenVZEmu, TimelineInterface::put_next_action(), TimelineInterface::put_stop_before(), TimelineInterface::put_stop_cond(), and TimelineInterface::sc.
Referenced by Interface::advance().
{
         if( !__start_run_time ) {
                 __start_run_time = get_wall_time();
         }
         // measure system use now
         struct rusage use_data;
         getrusage(0, &use_data);
         timeval tim = use_data.ru_utime;
         __srt_utime = tim.tv_sec*1000000 + tim.tv_usec;
         tim = use_data.ru_stime;
         __srt_stime = tim.tv_sec*1000000 + tim.tv_usec;
         // set the interface up for the threads
         __tli.put_next_action( nxt_act );
         __tli.put_stop_before( clock()+t );
         __tli.put_stop_cond( sc );
         // Now release the threads to do the simulation
         // a synchronization window size
 #ifdef MUTEX_BARRIER
         __tli.window_barrier.wait((ltime_t)(-1));
 #endif
 #ifdef SCHED_YIELD_BARRIER
         __tli.window_barrier.wait(__num_timelines,(ltime_t)(-1));
 #endif
 #ifdef PTHREAD_BARRIER
         pthread_barrier_wait( &(__tli.window_barrier) );
 #endif
         // and wait for them to finish the window
 #ifdef MUTEX_BARRIER
         __tli.window_barrier.wait((ltime_t)(-1));
 #endif
 #ifdef SCHED_YIELD_BARRIER
         __tli.window_barrier.wait(__num_timelines,(ltime_t)(-1));
 #endif
 #ifdef PTHREAD_BARRIER
         pthread_barrier_wait( &(__tli.window_barrier) );
 #endif
 #ifdef OPENVZ_EMULATION
     // currently emulation_finish is called after one epoch
     // it is not the end of emulation and we can start emulation again for next epoch
         if(__tli.isOpenVZEmu == true)
         {
                 int return_code = __tli.sc->emu_done();
                 if (return_code)
                 {
                         printf("Interface::advance_body, emu_done() error, error code= %s\n",
                                 SimCtrl::errcode2txt(return_code));
                         exit(0);
                 }
         }
 #endif
 #ifndef PTHREAD_BARRIER
         __clock = __tli.window_barrier.get_min_value();
 #else
         //just set clock to epoch value as for now, do not want to use mutex here
         __clock = __tli.get_stop_before();
 #endif
         __end_run_time = get_wall_time();
         getrusage(0, &use_data);
         tim = use_data.ru_utime;
         ltime_t utime = tim.tv_sec*1000000 + tim.tv_usec;
         tim = use_data.ru_stime;
         ltime_t stime = tim.tv_sec*1000000 + tim.tv_usec;
         tim = use_data.ru_stime;
         __acc_utime += (utime - __srt_utime);
         __acc_stime += (stime - __srt_stime);
         return __clock;
 }
int Interface::get_log_ticks_per_sec () inline inherited
Retrieve the simulation clock timescale provided.
Definition at line 226 of file interface.h.
References Interface::__log_ticks_per_sec.
 { return __log_ticks_per_sec; }
void Interface::put_log_ticks_per_sec (int ltps) inline inherited
Place the simulation clock timescale provided.
Definition at line 229 of file interface.h.
References Interface::__log_ticks_per_sec.
 { __log_ticks_per_sec = ltps; }
Timeline * Interface::get_Timeline (unsigned int tl) inherited
Fetch the address of the Timeline whose index is provided as an argument.
Definition at line 242 of file interface.cc.
References Interface::__num_timelines, and Interface::__timeline_threads.
Referenced by MyInterface::BuildModel(), s3f::s3fnet::Net::config_host(), and Interface::runtime_measurements().
{
         if( __num_timelines <= tl ) return (Timeline*)NULL;
         return __timeline_threads[tl].get_timeline();
 }
unsigned int Interface::get_numTimelines () inline inherited
Return the number of Timelines created for this simulation.
Definition at line 235 of file interface.h.
References Interface::__num_timelines.
Referenced by Interface::runtime_measurements().
 { return __num_timelines; }
ltime_t Interface::clock () inline inherited
Definition at line 236 of file interface.h.
References Interface::__clock.
Referenced by Interface::advance_body().
 { return __clock; }
TimelineInterface* Interface::get_timeline_interface () inline inherited
Definition at line 237 of file interface.h.
References Interface::__tli.
Referenced by s3f::s3fnet::Net::config(), and s3f::s3fnet::sigproc().
 { return &__tli; }
void Interface::runtime_measurements () inherited
Return measurement including simulation time, total time, total events, etc.
Definition at line 372 of file interface.cc.
References Interface::__acc_stime, Interface::__acc_utime, Interface::__clock, Interface::__num_timelines, Interface::__tli, Interface::full_exc_time(), Timeline::get_executed(), TimelineInterface::get_log_ticks_per_sec(), Interface::get_numTimelines(), Timeline::get_sync_executed(), Interface::get_Timeline(), Timeline::get_work_executed(), and Interface::sim_exc_time().
Referenced by main().
{
         unsigned long sum_executed = 0;
         unsigned long work_executed = 0;
         unsigned long sync_executed = 0;
         for(unsigned int i=0; i<__num_timelines; i++) {
                 Timeline *tl = get_Timeline(i);
                 sum_executed  += tl->get_executed();
                 work_executed += tl->get_work_executed();
                 sync_executed += tl->get_sync_executed();
         }
         printf("-------------- runtime measurements ----------------\n");
         printf("Simulation run of %g sim seconds, with %d timelines\n",
                         ((double)__clock)/pow(10.0,__tli.get_log_ticks_per_sec()),
                         __num_timelines);
 #ifdef SAFE_EVT_PTR
         printf("\tconfigured with smart pointer events\n");
 #else
         printf("\tconfigured without smart pointer events\n");
 #endif
 #ifdef SAFE_MSG_PTR
         printf("\tconfigured with smart pointer activations\n");
 #else
         printf("\tconfigured without smart pointer activations\n");
 #endif
         printf("total run time is %g seconds\n", full_exc_time()/1e6);
         printf("simulation run time is %g seconds\n", sim_exc_time()/1e6);
         printf("accumulated usr time is %g seconds\n",
                         __acc_utime/(1e6*get_numTimelines()));
         printf("accumulated sys time is %g seconds\n", __acc_stime/1e6);
         printf("total evts %ld, work evts %ld, sync evts %ld\n",
                         sum_executed, work_executed, sync_executed);
         printf("total exec evt rate %g, work evt rate %g\n",
                         sum_executed*1e6/sim_exc_time(),
                         work_executed*1e6/sim_exc_time());
         printf("----------------------------------------------------\n");
 }
ltime_t Interface::full_exc_time () protected inherited
return the entire execution time (simulation + initialization/model-building)
Definition at line 368 of file interface.cc.
References Interface::__end_run_time, and Interface::__start_build_time.
Referenced by Interface::runtime_measurements().
{
         return( __end_run_time - __start_build_time );
 }
ltime_t Interface::sim_exc_time () protected inherited
return the simulation time
Definition at line 364 of file interface.cc.
References Interface::__end_run_time, and Interface::__start_run_time.
Referenced by Interface::runtime_measurements().
{
         return( __end_run_time - __start_run_time );
 }
Member Data Documentation
Net* s3f::s3fnet::SimInterface::topnet
pointer to the topnet object
Definition at line 409 of file s3fnet.h.
Referenced by BuildModel(), and ~SimInterface().
int s3f::s3fnet::SimInterface::openflow_controller_type
Definition at line 411 of file s3fnet.h.
int s3f::s3fnet::SimInterface::openflow_controller_model
Definition at line 413 of file s3fnet.h.
vector<TimelineThread> Interface::__timeline_threads protected inherited
keep a vector of every Timeline created
Definition at line 245 of file interface.h.
Referenced by Interface::get_Timeline(), Interface::InitModel(), Interface::Interface(), and Interface::~Interface().
unsigned int Interface::__num_timelines protected inherited
Total number of Timelines created.
Definition at line 246 of file interface.h.
Referenced by Interface::advance_body(), Interface::get_numTimelines(), Interface::get_Timeline(), and Interface::runtime_measurements().
ltime_t Interface::__clock protected inherited
time to which the simulation has advanced
Definition at line 247 of file interface.h.
Referenced by Interface::advance_body(), Interface::clock(), and Interface::runtime_measurements().
int Interface::__log_ticks_per_sec protected inherited
Time-scale of clock tickc, log base 10 of number of clock ticks in a second.
Definition at line 248 of file interface.h.
Referenced by Interface::get_log_ticks_per_sec(), and Interface::put_log_ticks_per_sec().
TimelineInterface Interface::__tli protected inherited
Pointer to the data structure created to interface with simulation Timelines.
Definition at line 249 of file interface.h.
Referenced by Interface::advance_body(), Interface::get_timeline_interface(), Interface::InitModel(), Interface::Interface(), and Interface::runtime_measurements().
ltime_t Interface::__start_build_time protected inherited
time when BuildModel is called;
Definition at line 250 of file interface.h.
Referenced by Interface::full_exc_time(), and Interface::Interface().
ltime_t Interface::__start_run_time protected inherited
time when advance first called
Definition at line 251 of file interface.h.
Referenced by Interface::advance_body(), Interface::Interface(), and Interface::sim_exc_time().
ltime_t Interface::__end_run_time protected inherited
time when advance finishes
Definition at line 252 of file interface.h.
Referenced by Interface::advance_body(), Interface::full_exc_time(), Interface::Interface(), and Interface::sim_exc_time().
ltime_t Interface::__srt_utime protected inherited
Definition at line 256 of file interface.h.
Referenced by Interface::advance_body().
ltime_t Interface::__srt_stime protected inherited
Definition at line 257 of file interface.h.
Referenced by Interface::advance_body().
ltime_t Interface::__acc_utime protected inherited
Definition at line 258 of file interface.h.
Referenced by Interface::advance_body(), Interface::Interface(), and Interface::runtime_measurements().
ltime_t Interface::__acc_stime protected inherited
Definition at line 259 of file interface.h.
Referenced by Interface::advance_body(), Interface::Interface(), and Interface::runtime_measurements().
The documentation for this class was generated from the following files:
s3fnet.h
s3fnet.cc