S3F: s3f::s3fnet::Mac48Address Class Reference
s3f::s3fnet::Mac48Address Class Reference
MAC address (48 bit IEEE addresses)
#include <mac48_address.h>
Public Member Functions
Mac48Address ()
Mac48Address (const char *str)
Mac48Address (const Mac48Address &addr)
void CopyFrom (const uint8_t buffer[6])
void CopyTo (uint8_t buffer[6]) const
void CopyFrom (const Mac48Address *addr)
bool IsBroadcast (void) const
bool IsGroup (void) const
int IsEqual (const Mac48Address *addr)
Check if two MAC addresses are the same *.
Static Public Member Functions
static Mac48Address * Allocate (void)
Allocate a new Mac48Address.
static Mac48Address GetBroadcast (void)
static Mac48Address GetMulticastPrefix (void)
static Mac48Address GetMulticast6Prefix (void)
Get the multicast prefix for IPv6 (33:33:00:00:00:00).
Private Attributes
uint8_t m_address [6]
Friends
bool operator< (const Mac48Address &a, const Mac48Address &b)
bool operator== (const Mac48Address &a, const Mac48Address &b)
bool operator!= (const Mac48Address &a, const Mac48Address &b)
std::istream & operator>> (std::istream &is, Mac48Address &address)
std::istream & operator>> (std::istream &is, Mac48Address *address)
Detailed Description
MAC address (48 bit IEEE addresses)
Definition at line 23 of file mac48_address.h.
Constructor & Destructor Documentation
s3f::s3fnet::Mac48Address::Mac48Address ()
Definition at line 36 of file mac48_address.cc.
References m_address.
Referenced by Allocate(), GetBroadcast(), GetMulticast6Prefix(), and GetMulticastPrefix().
 {
         std::memset (m_address, 0, 6);
 }
s3f::s3fnet::Mac48Address::Mac48Address (const char * str)
Parameters
str a string representing the new Mac48Address
The format of the string is "xx:xx:xx:xx:xx:xx"
Definition at line 47 of file mac48_address.cc.
References ASCII_a, ASCII_COLON, ASCII_ZERO, s3f::s3fnet::AsciiToLowCase(), and m_address.
 {
         int i = 0;
         while (*str != 0 && i < 6)
         {
                 uint8_t byte = 0;
                 while (*str != ASCII_COLON && *str != 0)
                 {
                         byte <<= 4;
                         char low = AsciiToLowCase (*str);
                         if (low >= ASCII_a)
{
                                 byte |= low - ASCII_a + 10;
                         }
                         else
{
                                 byte |= low - ASCII_ZERO;
                         }
                         str++;
                 }
                 m_address[i] = byte;
                 i++;
                 if (*str == 0)
                 {
                         break;
                 }
                 str++;
         }
         assert (i == 6);
 }
s3f::s3fnet::Mac48Address::Mac48Address (const Mac48Address & addr)
Definition at line 41 of file mac48_address.cc.
References CopyTo(), and m_address.
 {
         std::memset (m_address, 0, 6);
         addr.CopyTo(m_address);
 }
Member Function Documentation
void s3f::s3fnet::Mac48Address::CopyFrom (const uint8_t buffer[6])
Parameters
buffer address in network order
Copy the input address to our internal buffer.
Definition at line 78 of file mac48_address.cc.
References m_address.
Referenced by s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), s3f::s3fnet::LearningController::process_recv_packet(), s3f::s3fnet::LearningControllerSession::ReceiveFromSwitch(), s3f::s3fnet::OpenFlowSwitchSession::ReceivePortMod(), and s3f::s3fnet::SimpleMacMessage::SimpleMacMessage().
 {
         std::memcpy (m_address, buffer, 6);
 }
void s3f::s3fnet::Mac48Address::CopyTo (uint8_t buffer[6]) const
Parameters
buffer address in network order
Copy the internal address to the input buffer.
Definition at line 88 of file mac48_address.cc.
References m_address.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::FillPortDesc(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), Mac48Address(), s3f::s3fnet::operator<<(), s3f::s3fnet::LearningController::process_recv_packet(), and s3f::s3fnet::LearningControllerSession::ReceiveFromSwitch().
 {
         std::memcpy (buffer, m_address, 6);
 }
void s3f::s3fnet::Mac48Address::CopyFrom (const Mac48Address * addr)
Definition at line 83 of file mac48_address.cc.
References m_address.
 {
         memcpy(m_address, addr->m_address, 6);
 }
Mac48Address * s3f::s3fnet::Mac48Address::Allocate (void) static
Allocate a new Mac48Address.
Definition at line 93 of file mac48_address.cc.
References m_address, and Mac48Address().
Referenced by s3f::s3fnet::NetworkInterface::NetworkInterface().
 {
         static uint64_t id = 0;
         id++;
         Mac48Address* address = new Mac48Address();
         address->m_address[0] = (id >> 40) & 0xff;
         address->m_address[1] = (id >> 32) & 0xff;
         address->m_address[2] = (id >> 24) & 0xff;
         address->m_address[3] = (id >> 16) & 0xff;
         address->m_address[4] = (id >> 8) & 0xff;
         address->m_address[5] = (id >> 0) & 0xff;
         return address;
 }
bool s3f::s3fnet::Mac48Address::IsBroadcast (void) const
Returns
true if this is a broadcast address, false otherwise.
Definition at line 107 of file mac48_address.cc.
References GetBroadcast().
Referenced by s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::LearningController::process_recv_packet(), and s3f::s3fnet::LearningControllerSession::ReceiveFromSwitch().
 {
         return *this == GetBroadcast ();
 }
bool s3f::s3fnet::Mac48Address::IsGroup (void) const
Returns
true if the group bit is set, false otherwise.
Definition at line 111 of file mac48_address.cc.
References m_address.
 {
         return (m_address[0] & 0x01) == 0x01;
 }
Mac48Address s3f::s3fnet::Mac48Address::GetBroadcast (void) static
Returns
the broadcast address
Definition at line 116 of file mac48_address.cc.
References Mac48Address().
Referenced by IsBroadcast().
 {
         static Mac48Address broadcast = Mac48Address ("ff:ff:ff:ff:ff:ff");
         return broadcast;
 }
Mac48Address s3f::s3fnet::Mac48Address::GetMulticastPrefix (void) static
Returns
the multicast prefix (01:00:5e:00:00:00).
Definition at line 122 of file mac48_address.cc.
References Mac48Address().
 {
         static Mac48Address multicast = Mac48Address ("01:00:5e:00:00:00");
         return multicast;
 }
Mac48Address s3f::s3fnet::Mac48Address::GetMulticast6Prefix (void) static
Get the multicast prefix for IPv6 (33:33:00:00:00:00).
Returns
a multicast address.
Definition at line 128 of file mac48_address.cc.
References Mac48Address().
 {
         static Mac48Address multicast = Mac48Address ("33:33:00:00:00:00");
         return multicast;
 }
int s3f::s3fnet::Mac48Address::IsEqual (const Mac48Address * addr)
Check if two MAC addresses are the same *.
Returns
1 if equal, 0 otherwise
Definition at line 233 of file mac48_address.cc.
References m_address.
Referenced by s3f::s3fnet::SimpleMac::pop().
 {
         for(int i = 0; i < 6; i++)
         {
                 if(m_address[i] != addr->m_address[i])
                 {
                         return 0;
                 }
         }
         return 1;
 }
Friends And Related Function Documentation
bool operator< (const Mac48Address & a, const Mac48Address & b) friend
Definition at line 107 of file mac48_address.h.
 {
         return memcmp (a.m_address, b.m_address, 6) < 0;
 }
bool operator== (const Mac48Address & a, const Mac48Address & b) friend
Definition at line 99 of file mac48_address.h.
                 {
         return memcmp (a.m_address, b.m_address, 6) == 0;
                 }
bool operator!= (const Mac48Address & a, const Mac48Address & b) friend
Definition at line 103 of file mac48_address.h.
                 {
         return memcmp (a.m_address, b.m_address, 6) != 0;
                 }
std::istream& operator>> (std::istream & is, Mac48Address & address) friend
Definition at line 179 of file mac48_address.cc.
 {
         std::string v;
         is >> v;
         std::string::size_type col = 0;
         for (uint8_t i = 0; i < 6; ++i)
         {
                 std::string tmp;
                 std::string::size_type next;
                 next = v.find (":", col);
                 if (next == std::string::npos)
                 {
                         tmp = v.substr (col, v.size ()-col);
                         address.m_address[i] = AsInt (tmp);
                         break;
                 }
                 else
                 {
                         tmp = v.substr (col, next-col);
                         address.m_address[i] = AsInt (tmp);
                         col = next + 1;
                 }
         }
         return is;
 }
std::istream& operator>> (std::istream & is, Mac48Address * address) friend
Definition at line 206 of file mac48_address.cc.
 {
         std::string v;
         is >> v;
         std::string::size_type col = 0;
         for (uint8_t i = 0; i < 6; ++i)
         {
                 std::string tmp;
                 std::string::size_type next;
                 next = v.find (":", col);
                 if (next == std::string::npos)
                 {
                         tmp = v.substr (col, v.size ()-col);
                         address->m_address[i] = AsInt (tmp);
                         break;
                 }
                 else
                 {
                         tmp = v.substr (col, next-col);
                         address->m_address[i] = AsInt (tmp);
                         col = next + 1;
                 }
         }
         return is;
 }
Member Data Documentation
uint8_t s3f::s3fnet::Mac48Address::m_address[6] private
Definition at line 96 of file mac48_address.h.
Referenced by Allocate(), CopyFrom(), CopyTo(), IsEqual(), IsGroup(), Mac48Address(), s3f::s3fnet::operator!=(), s3f::s3fnet::operator<(), s3f::s3fnet::operator==(), and s3f::s3fnet::operator>>().
The documentation for this class was generated from the following files:
mac48_address.h
mac48_address.cc