S3F: Process Class Reference
Process Class Reference
The code that executes should be thought of as embedded in an instant of time.
#include <process.h>
Public Member Functions
Process (Entity *, void(Entity::*)(Activation))
constructor passes pointer to the Entity that "owns" this Process and a pointer to one of its methods, that will be used as a code body for the Process.
Process ()
Null constructor.
Entity * owner ()
Returns a pointer to the Entity owning this Process.
InChannel * activeChannel ()
When the Process body is executing, the Process can obtain using this method a pointer to the InChannel where an Activation arrival trigger the execution (if any).
unsigned int s3fid ()
Returns a unique Process identifier, indexed between 0 and the total number of Processes created.
Timeline * alignment ()
Returns a pointer to the Timeline of the Process owner.
Process (Entity *, string, void(Entity::*)(Activation))
A Process can be constructed and give a text name identifier to be used to look up the address of the Process, given the name.
int pri ()
Processes may be given priorities used to order the sequence of activations when a number of Processes are waiting on the same InChannel.
void set_pri (int pri)
set_pri() assigned the priority
Protected Member Functions
void put_activeChannel (InChannel *ac)
Record which InChannel caused the current Process activation.
Protected Attributes
Entity * __owner
Entity that owns this process.
void(Entity::* __func)(Activation)
the function pointer to use when process is called
InChannel * __active
InChannel that triggered activation (due to waitOn) or NULL if triggered by waitFor.
int __pri
priority that can be given to a process
unsigned int __s3fid
unique identifier
Timeline * __alignment
cached value of owner's timeline
Static Protected Attributes
static unsigned int __num_processes = 0
variable used to enumerate processes as created
static pthread_mutex_t process_class_mutex
mutex protection for access to Process state
Detailed Description
The code that executes should be thought of as embedded in an instant of time.
No time advances while it executes. When the routine exits via normal C+ runtime semantics, the Timeline scheduler may choose another Process to execute, with an associated timestamp that may be farther in the future. Simulation time advances with discrete leaps from the times of these various Process executions. Process code bodies may make calls to waitFor or waitOn. In the original version of SSF these cause the process code body to suspend. S3F does not. These are calls that schedule a future activation (waitFor) or attach Process to an InChannel to be activated when a message arrives. Normal C++ runtime semantics hold throughout. From the point of runtime behavior here is nothing special about calls to waitFor, or waitOn, and no assumptions or restrictions about where they may appear in the code (e.g. in SSF, they had to the last statements executed if the Process was "simple")
Definition at line 30 of file process.h.
Constructor & Destructor Documentation
Process::Process (Entity * owner, void(Entity::*)(Activation) func)
constructor passes pointer to the Entity that "owns" this Process and a pointer to one of its methods, that will be used as a code body for the Process.
S3F does assume (and cannot check, as far as I can tell) that the method is part of the Entity named as owner.
A Process always has an Entity owner and a pointer to a method associated with that owner. Without reflection there is no easy way to check this relationship. Optionally a string name may be given to identify the Process and look up its address.
Definition at line 23 of file process.cc.
References __alignment, __num_processes, Entity::__process_list, __s3fid, Entity::alignment(), Entity::entity_inst_mutex, and process_class_mutex.
                                                               :
 __owner(owner), __func(func),
 __active(0), __pri(Timeline::default_sched_pri) {
         __alignment = owner->alignment();
         // initialization above ensures that it does not appear as though
         // the Process was activated, and stores a default scheduling
         // priority
         // get the unique id, serialized by mutux
         pthread_mutex_lock(&process_class_mutex);
         __s3fid = __num_processes++;
         pthread_mutex_unlock(&process_class_mutex);
         // add this process to the list of processes maintained by the owning
         // entity, serialized by entity mutex
         pthread_mutex_lock(&owner->entity_inst_mutex);
         owner->__process_list.push_back(this);
         pthread_mutex_unlock(&owner->entity_inst_mutex);
 };
Process::Process () inline
Null constructor.
Definition at line 47 of file process.h.
 {};
Process::Process (Entity * , string , void(Entity::*)(Activation))
A Process can be constructed and give a text name identifier to be used to look up the address of the Process, given the name.
The name is unique to the Entity, but may be duplicated on other Entities.
Member Function Documentation
Entity* Process::owner () inline
Returns a pointer to the Entity owning this Process.
Definition at line 50 of file process.h.
References __owner.
Referenced by ProcessPri::ProcessPri(), Timeline::schedule(), and Timeline::sync_window().
 { return __owner;  }
InChannel* Process::activeChannel () inline
When the Process body is executing, the Process can obtain using this method a pointer to the InChannel where an Activation arrival trigger the execution (if any).
A return of NULL indicates that a waitFor triggered the execution, not a waitFor.
Definition at line 57 of file process.h.
References __active.
Referenced by s3f::s3fnet::Host::listen().
 { return __active; }
unsigned int Process::s3fid () inline
Returns a unique Process identifier, indexed between 0 and the total number of Processes created.
Definition at line 60 of file process.h.
References __s3fid.
 { return __s3fid; }
Timeline* Process::alignment () inline
Returns a pointer to the Timeline of the Process owner.
Definition at line 63 of file process.h.
References __alignment.
Referenced by InChannel::insertion_gateway().
 { return __alignment; }
int Process::pri () inline
Processes may be given priorities used to order the sequence of activations when a number of Processes are waiting on the same InChannel.
These priorities are the same as the scheduling priorities. pri() returns the priority.
Definition at line 82 of file process.h.
References __pri.
Referenced by InChannel::add_process(), InChannel::bind(), and set_pri().
 { return __pri; }
void Process::set_pri (int pri) inline
set_pri() assigned the priority
Definition at line 85 of file process.h.
References __pri, and pri().
 { __pri = pri; }
void Process::put_activeChannel (InChannel * ac) inline protected
Record which InChannel caused the current Process activation.
Definition at line 98 of file process.h.
References __active.
Referenced by Timeline::sync_window().
 { __active = ac;   }
Member Data Documentation
Entity* Process::__owner protected
Entity that owns this process.
Definition at line 104 of file process.h.
Referenced by owner().
void(Entity::* Process::__func)(Activation) protected
the function pointer to use when process is called
Definition at line 107 of file process.h.
Referenced by Timeline::sync_window().
InChannel* Process::__active protected
InChannel that triggered activation (due to waitOn) or NULL if triggered by waitFor.
Definition at line 110 of file process.h.
Referenced by activeChannel(), and put_activeChannel().
int Process::__pri protected
priority that can be given to a process
Definition at line 113 of file process.h.
Referenced by pri(), and set_pri().
unsigned int Process::__s3fid protected
unique identifier
Definition at line 116 of file process.h.
Referenced by Process(), and s3fid().
Timeline* Process::__alignment protected
cached value of owner's timeline
Definition at line 119 of file process.h.
Referenced by alignment(), and Process().
unsigned int Process::__num_processes = 0 static protected
variable used to enumerate processes as created
Definition at line 125 of file process.h.
Referenced by Process().
pthread_mutex_t Process::process_class_mutex static protected
mutex protection for access to Process state
Definition at line 128 of file process.h.
Referenced by Interface::Interface(), and Process().
The documentation for this class was generated from the following files:
process.h
process.cc