S3F: s3f::s3fnet::TCPServerSession Class Reference
s3f::s3fnet::TCPServerSession Class Reference
The TCP server test protocol session.
#include <tcp_server.h>
Public Types
enum InstantiationType { PROT_UNIQUE_INSTANCE = 0x00, PROT_MULTIPLE_INSTANCES = 0x01, PROT_MULTIPLE_IMPLEMENTATIONS = 0x02 }
Multiple protocol session instantiation type.
enum ExecutionStage { PSESS_CREATED = 0, PSESS_CONFIGURED = 1, PSESS_INITIALIZED = 2, PSESS_WRAPPED_UP = 3 }
A normal protocol session must go though the following stages.
Public Member Functions
TCPServerSession (ProtocolGraph *graph)
The constructor.
virtual ~TCPServerSession ()
The destructor.
virtual void config (s3f::dml::Configuration *cfg)
Configure the TCP server test protocol session.
virtual int getProtocolNumber ()
Return the protocol number.
virtual void init ()
Initialize this protocol session.
void start_timer_callback (Activation ac)
The callback function registered with the start_timer_callback_proc.
virtual void wrapup ()
The method is used to wrap up the protocol session.
int pushdown (Activation msg, ProtocolSession *hi_sess, void *extinfo=0, size_t extinfo_size=0)
The original push method is divided into pushdown() and push().
int popup (Activation msg, ProtocolSession *lo_sess, void *extinfo=0, size_t extinfo_size=0)
The original pop method is divided into popup() and pop().
virtual int control (int ctrltyp, void *ctrlmsg, ProtocolSession *sess)
The control method is used by the protocol session to receive control messages (or information queries) from other protocol sessions both above and below this protocol session on the stack.
ProtocolGraph * inGraph ()
The method returns the protocol graph in which this protocol session resides.
virtual Host * inHost ()
Return a pointer to the host owning this protocol session.
Random::RNG * getRandom ()
The method returns a pointer to the random number generator.
ltime_t getNow ()
The method returns the current simulation time.
char * getNowWithThousandSeparator ()
For printing the current simulation time in a better readable format.
int configured ()
This method returns true if the protocol session has been configured.
int initialized ()
This method returns true if the protocol session has been initialized.
int wrapped_up ()
This method returns true if the protocol session has been wrapped up.
virtual const char * psesstype ()
Public Attributes
Process * start_timer_callback_proc
Process object for start timer callback Provide call_back functionality for implementing the start timer in the TCPServerSession.
ProtocolCallbackActivation * start_timer_ac
Activation object for start timer callback.
char * name
Symbolic name of the protocol this session implements.
float version
Version number of this protocol implemenntation, represented as a floating point number (e.g., 1.23).
char * use
Name of the protocol class from which this protocol session is instantiated.
Protected Member Functions
void start_on ()
start the TCP server
void handle_client (int socket)
function representing the handle_client stage
void connection_accepted (TCPServerSessionContinuation *const cnt)
function representing the connection_accepted stage
void request_received (TCPServerSessionContinuation *const cnt)
function representing the request_received stage
void sending_data (TCPServerSessionContinuation *const cnt)
function representing the sending_data stage
void data_sent (TCPServerSessionContinuation *const cnt)
function representing the data_sent stage
void session_closed (TCPServerSessionContinuation *const cnt)
function representing the session_closed stage
virtual int instantiation_type ()
This method controls how protocol instances can coexist with one another.
Protected Attributes
ProtocolGraph * ingraph
Points to the protocol graph.
Random::RNG * sess_rng
Pointer to a random number generator.
int stage
This variable indicates the current stage of this protocol session.
Private Member Functions
virtual int push (Activation msg, ProtocolSession *hi_sess, void *extinfo=0, size_t extinfo_size=0)
Push message to lower protocol layer.
virtual int pop (Activation msg, ProtocolSession *lo_sess, void *extinfo=0, size_t extinfo_size=0)
Pop message to higher protocol layer.
Private Attributes
uint16 server_port
Port number to receive incoming request.
uint32 request_size
Size of the request from client (must be consistent).
uint32 client_limit
Number of client sessions that can be handled simultaneously.
bool accept_completed
Accept has been completed We have at least one client connected.
bool show_report
Whether we print out the result or not.
SocketMaster * sm
Pointer to the socket master.
IPADDR server_ip
The ip address of this server (interface 0).
uint32 nclients
Number of clients currently connected.
Detailed Description
The TCP server test protocol session.
This is a test protocol that does not exist in reality. In a normal situation, the protocol waits for an incoming request from a TCP client, spawns a process to handle the client connection, and then sends the requested number of bytes to the client.
Definition at line 40 of file tcp_server.h.
Member Enumeration Documentation
enum s3f::s3fnet::ProtocolSession::InstantiationType inherited
Multiple protocol session instantiation type.
Enumerator
PROT_UNIQUE_INSTANCE
PROT_MULTIPLE_INSTANCES
PROT_MULTIPLE_IMPLEMENTATIONS
Definition at line 44 of file protocol_session.h.
{
     PROT_UNIQUE_INSTANCE                = 0x00,
     PROT_MULTIPLE_INSTANCES             = 0x01,
     PROT_MULTIPLE_IMPLEMENTATIONS       = 0x02
   };
enum s3f::s3fnet::ProtocolSession::ExecutionStage inherited
A normal protocol session must go though the following stages.
Enumerator
PSESS_CREATED
this protocol session has just been created
PSESS_CONFIGURED
the config method of this protocol session has been called
PSESS_INITIALIZED
the init method of this protocol session has been called
PSESS_WRAPPED_UP
Definition at line 51 of file protocol_session.h.
                       {
     PSESS_CREATED       = 0,
     PSESS_CONFIGURED    = 1,
     PSESS_INITIALIZED   = 2,
     PSESS_WRAPPED_UP    = 3
   };
Constructor & Destructor Documentation
s3f::s3fnet::TCPServerSession::TCPServerSession (ProtocolGraph * graph)
The constructor.
Definition at line 142 of file tcp_server.cc.
References s3f::s3fnet::ProtocolSession::inHost(), and TCP_DUMP.
                                                        :
   ProtocolSession(graph), accept_completed(true), start_timer_ac(0), start_timer_callback_proc(0)
 {
   TCP_DUMP(printf("[host=\"%s\"] new tcp server session.\n", inHost()->nhi.toString()));
 }
s3f::s3fnet::TCPServerSession::~TCPServerSession () virtual
The destructor.
Definition at line 148 of file tcp_server.cc.
 {}
Member Function Documentation
void s3f::s3fnet::TCPServerSession::config (s3f::dml::Configuration * cfg) virtual
Configure the TCP server test protocol session.
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 150 of file tcp_server.cc.
References client_limit, s3f::s3fnet::ProtocolSession::config(), DEFAULT_SERVER_PORT, s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolSession::inHost(), request_size, server_port, show_report, and TCP_DUMP.
 {
   ProtocolSession::config(cfg);
   char* str = (char*)cfg->findSingle("port");
   if(str)
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: TCPServerSession::config(), invalid PORT attribute.\n");
     server_port = atoi(str);
   }
   else server_port = DEFAULT_SERVER_PORT;
   str = (char*)cfg->findSingle("request_size");
   if(str)
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: TCPServerSession::config(), invalid REQUEST_SIZE attribute.\n");
     request_size = atoi(str);
     if(request_size < sizeof(uint32))
       error_quit("ERROR: TCPServerSession::config(), REQUEST_SIZE must be larger than 4 (bytes).\n");
   }
   else request_size = sizeof(uint32);
   str = (char*)cfg->findSingle("client_limit");
   if(str)
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: TCPServerSession::config(), invalid CLIENT_LIMIT attribute.\n");
     client_limit = atoi(str);
   }
   else client_limit = 0; // means infinite
   str = (char*)cfg->findSingle("SHOW_REPORT");
   if(str)
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: TCPServerSession::config(), invalid SHOW_REPORT attribute.\n");
     if(!strcasecmp(str, "true")) show_report = true;
     else if(!strcasecmp(str, "false")) show_report = false;
     else error_quit("ERROR: TCPServerSession::config(), invalid SHOW_REPORT attribute (%s).\n", str);
   }
   else show_report = true;
   TCP_DUMP(printf("[host=\"%s\"] config():\n"
                   "  server_port=%u, request_size=%u, client_limit=%u.\n",
                   inHost()->nhi.toString(),
                   server_port, request_size, client_limit));
 }
virtual int s3f::s3fnet::TCPServerSession::getProtocolNumber () inline virtual
Return the protocol number.
The number returned specifies the relationship between this protocol and the other protocols defined in the same protocol stack.
Returns
Protocol number for blocking tcp client
Implements s3f::s3fnet::ProtocolSession.
Definition at line 60 of file tcp_server.h.
References s3f::s3fnet::S3FNET_PROTOCOL_TYPE_TCPTEST_SERVER.
 { return S3FNET_PROTOCOL_TYPE_TCPTEST_SERVER; }
void s3f::s3fnet::TCPServerSession::init () virtual
Initialize this protocol session.
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 201 of file tcp_server.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::Host::getDefaultIP(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::IPPrefix::ip2txt(), IPADDR_INVALID, server_ip, sm, SOCKET_API, start_timer_ac, start_timer_callback(), start_timer_callback_proc, TCP_DUMP, and Entity::waitFor().
 {
   ProtocolSession::init();
   server_ip = inHost()->getDefaultIP();
   if(IPADDR_INVALID == server_ip)
     error_quit("ERROR: TCPServerSession::init(), invalid IP address, the host's not connected to network.\n");
   sm = SOCKET_API;
   if(!sm)
   {
           error_quit("TCPServerSession::init(), missing socket master on host \"%s\".\n", inHost()->nhi.toString());
   }
   TCP_DUMP(printf("[host=\"%s\"] init(), server_ip=\"%s\".\n",
                   inHost()->nhi.toString(), IPPrefix::ip2txt(server_ip)));
   Host* owner_host = inHost();
   start_timer_callback_proc = new Process( (Entity *)owner_host, (void (s3f::Entity::*)(s3f::Activation))&TCPServerSession::start_timer_callback);
   start_timer_ac = new ProtocolCallbackActivation(this);
   Activation ac (start_timer_ac);
   HandleCode h = inHost()->waitFor( start_timer_callback_proc, ac, 0, inHost()->tie_breaking_seed ); //currently the starting time is 0
 }
void s3f::s3fnet::TCPServerSession::start_timer_callback (Activation ac)
The callback function registered with the start_timer_callback_proc.
Definition at line 345 of file tcp_server.cc.
References start_on().
Referenced by init().
 {
   TCPServerSession* server = (TCPServerSession*)((ProtocolCallbackActivation*)ac)->session;
   server->start_on();
 }
void s3f::s3fnet::TCPServerSession::start_on () protected
start the TCP server
Definition at line 224 of file tcp_server.cc.
References accept_completed, s3f::s3fnet::SocketMaster::bind(), client_limit, s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), handle_client(), s3f::s3fnet::ProtocolSession::inHost(), IPADDR_ANYDEST, nclients, server_port, sm, s3f::s3fnet::SocketMaster::socket(), TCP_DUMP, and TCP_PROTOCOL_NAME.
Referenced by start_timer_callback().
 {
   TCP_DUMP(printf("[host=\"%s\"] %s: main_proc(), starting server.\n",
                   inHost()->nhi.toString(), getNowWithThousandSeparator()));
   if((!client_limit || nclients++ < client_limit) && accept_completed == true) //should always true
   {
           accept_completed = false;
           int ssock = sm->socket();
           if(!sm->bind(ssock, IPADDR_ANYDEST, server_port, TCP_PROTOCOL_NAME, 0))
           {
             TCP_DUMP(printf("session_proc() on host \"%s\": failed to bind.\n",
                             inHost()->nhi.toString()));
             nclients--;
             accept_completed = true;
             return;
           }
           TCP_DUMP(printf("[host=\"%s\"] %s: waiting for incoming connection on socket %d.\n",
                           inHost()->nhi.toString(), getNowWithThousandSeparator(), ssock));
           handle_client(ssock); //call accept
   }
 }
void s3f::s3fnet::TCPServerSession::handle_client (int socket) protected
function representing the handle_client stage
Definition at line 250 of file tcp_server.cc.
References s3f::s3fnet::SocketMaster::accept(), sm, s3f::s3fnet::TCPServerSessionContinuation::status, s3f::s3fnet::TCPServerSessionContinuation::TCP_SERVER_SESSION_ACCEPTING, and TCPServerSessionContinuation.
Referenced by connection_accepted(), s3f::s3fnet::TCPServerSessionContinuation::failure(), session_closed(), and start_on().
 {
   TCPServerSessionContinuation* cnt = new TCPServerSessionContinuation(this, ssock);
   cnt->status = TCPServerSessionContinuation::TCP_SERVER_SESSION_ACCEPTING;
   sm->accept(ssock, true, cnt, 0);
 }
void s3f::s3fnet::TCPServerSession::connection_accepted (TCPServerSessionContinuation *const cnt) protected
function representing the connection_accepted stage
Definition at line 258 of file tcp_server.cc.
References accept_completed, client_limit, s3f::s3fnet::TCPServerSessionContinuation::client_socket, handle_client(), nclients, s3f::s3fnet::SocketMaster::recv(), s3f::s3fnet::TCPServerSessionContinuation::reqbuf, request_size, s3f::s3fnet::SocketContinuation::retval, s3f::s3fnet::TCPServerSessionContinuation::server_socket, sm, s3f::s3fnet::TCPServerSessionContinuation::status, and s3f::s3fnet::TCPServerSessionContinuation::TCP_SERVER_SESSION_RECEIVING.
Referenced by s3f::s3fnet::TCPServerSessionContinuation::success().
 {
   accept_completed = true;
   //init another accept
   if((!client_limit || nclients++ < client_limit ) && accept_completed == true)
     handle_client(cnt->server_socket);
   cnt->client_socket = cnt->retval;
   cnt->status = TCPServerSessionContinuation::TCP_SERVER_SESSION_RECEIVING;
   sm->recv(cnt->client_socket, request_size, cnt->reqbuf, cnt);
 }
void s3f::s3fnet::TCPServerSession::request_received (TCPServerSessionContinuation *const cnt) protected
function representing the request_received stage
Definition at line 272 of file tcp_server.cc.
References s3f::s3fnet::TCPServerSessionContinuation::file_size, s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::TCPServerSessionContinuation::reqbuf, request_size, s3f::s3fnet::SocketContinuation::retval, sending_data(), s3f::s3fnet::TCPServerSessionContinuation::sent_bytes, s3f::s3fnet::TCPServerSessionContinuation::server_socket, and TCP_DUMP.
Referenced by s3f::s3fnet::TCPServerSessionContinuation::success().
 {
   // assume the request can be received with one call
   assert(cnt->retval == (int)request_size);
   cnt->file_size = ntohl(*(uint32*)cnt->reqbuf);
   TCP_DUMP(printf("[host=\"%s\"] %s: session_proc(), socket %d received request "
                   "(request_size=%u, file_size=%u).\n",
                   inHost()->nhi.toString(), getNowWithThousandSeparator(),
                   cnt->server_socket, request_size, cnt->file_size));
   cnt->sent_bytes = 0;
   sending_data(cnt);
 }
void s3f::s3fnet::TCPServerSession::sending_data (TCPServerSessionContinuation *const cnt) protected
function representing the sending_data stage
Definition at line 288 of file tcp_server.cc.
References s3f::s3fnet::TCPServerSessionContinuation::client_socket, s3f::s3fnet::TCPServerSessionContinuation::file_size, s3f::s3fnet::SocketMaster::send(), s3f::s3fnet::TCPServerSessionContinuation::sent_bytes, sm, s3f::s3fnet::TCPServerSessionContinuation::status, and s3f::s3fnet::TCPServerSessionContinuation::TCP_SERVER_SESSION_SENDING.
Referenced by data_sent(), and request_received().
 {
   if(cnt->sent_bytes < cnt->file_size)
   {
           uint32 to_send = cnt->file_size-cnt->sent_bytes;
           cnt->status = TCPServerSessionContinuation::TCP_SERVER_SESSION_SENDING;
           sm->send(cnt->client_socket, to_send, 0, cnt);
   }
 }
void s3f::s3fnet::TCPServerSession::data_sent (TCPServerSessionContinuation *const cnt) protected
function representing the data_sent stage
Definition at line 299 of file tcp_server.cc.
References s3f::s3fnet::TCPServerSessionContinuation::client_socket, s3f::s3fnet::SocketMaster::close(), s3f::s3fnet::TCPServerSessionContinuation::file_size, s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::SocketContinuation::retval, sending_data(), s3f::s3fnet::TCPServerSessionContinuation::sent_bytes, sm, s3f::s3fnet::TCPServerSessionContinuation::status, TCP_DUMP, and s3f::s3fnet::TCPServerSessionContinuation::TCP_SERVER_SESSION_CLOSING.
Referenced by s3f::s3fnet::TCPServerSessionContinuation::success().
 {
   cnt->sent_bytes += cnt->retval;
   TCP_DUMP(printf("[host=\"%s\"] %s: session_proc(), socket %d "
                   "sent %d bytes (%d bytes left).\n",
                   inHost()->nhi.toString(), getNowWithThousandSeparator(),
                   cnt->client_socket, cnt->retval, cnt->file_size-cnt->sent_bytes));
   if(cnt->sent_bytes < cnt->file_size)
   {
         sending_data(cnt);
     return;
   }
   TCP_DUMP(printf("[host=\"%s\"] %s: session_proc(), finished sending %u bytes.\n",
                   inHost()->nhi.toString(), getNowWithThousandSeparator(), cnt->file_size));
   // the server will close the connection.
   cnt->status = TCPServerSessionContinuation::TCP_SERVER_SESSION_CLOSING;
   sm->close(cnt->client_socket, cnt);
 }
void s3f::s3fnet::TCPServerSession::session_closed (TCPServerSessionContinuation *const cnt) protected
function representing the session_closed stage
Definition at line 322 of file tcp_server.cc.
References accept_completed, client_limit, s3f::s3fnet::TCPServerSessionContinuation::client_socket, s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), handle_client(), s3f::s3fnet::ProtocolSession::inHost(), nclients, s3f::s3fnet::TCPServerSessionContinuation::server_socket, and TCP_DUMP.
Referenced by s3f::s3fnet::TCPServerSessionContinuation::success().
 {
   TCP_DUMP(printf("[host=\"%s\"] %s: session_proc(), socket %d connection closed.\n",
                   inHost()->nhi.toString(), getNowWithThousandSeparator(), cnt->client_socket));
   if(client_limit && nclients-- == client_limit && accept_completed == true)
     handle_client(cnt->server_socket);
   // the continuation will be reclaimed after this
 }
int s3f::s3fnet::TCPServerSession::push (Activation msg, ProtocolSession * hi_sess, void * extinfo = 0, size_t extinfo_size = 0) private virtual
Push message to lower protocol layer.
This method should not be called; it is provided here to prompt an error message if it's called accidentally.
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 333 of file tcp_server.cc.
References s3f::s3fnet::error_quit().
 {
   error_quit("ERROR: TCPServerSession::push() should not be called.\n");
   return 1;
 }
int s3f::s3fnet::TCPServerSession::pop (Activation msg, ProtocolSession * lo_sess, void * extinfo = 0, size_t extinfo_size = 0) private virtual
Pop message to higher protocol layer.
This method should not be called; it is provided here to prompt an error message if it's called accidentally.
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 339 of file tcp_server.cc.
References s3f::s3fnet::error_quit().
 {
   error_quit("ERROR: TCPServerSession::pop() should not be called.\n");
   return 1;
 }
void s3f::s3fnet::ProtocolSession::wrapup () virtual inherited
The method is used to wrap up the protocol session.
It is called when the simulation finishes. It is designed to give user a chance to report simulation statistics. The default behavior is doing nothing. Subclass may override this method for protocol specific dealings. Note that there is no specific order in which wrapup is called for protocol sessions in a protocol graph.
Definition at line 59 of file protocol_session.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolSession::initialized(), s3f::s3fnet::ProtocolSession::name, s3f::s3fnet::ProtocolSession::PSESS_WRAPPED_UP, s3f::s3fnet::ProtocolSession::stage, and s3f::s3fnet::ProtocolSession::wrapped_up().
 {
   // Make sure this init function at the base class should be called
   // by the derived function!
   if(!initialized())
     error_quit("ERROR: ProtocolSession \"%s\" wrapup() called before init(), "
                "forgot to call base class's init() in your derived class?\n", name);
   else if(wrapped_up())
     error_quit("ERROR: duplicate calls to ProtocolSession::wrapup(): "
                "session name is \"%s\".\n", name);
   else stage = PSESS_WRAPPED_UP;
 }
int s3f::s3fnet::ProtocolSession::pushdown (Activation msg, ProtocolSession * hi_sess, void * extinfo = 0, size_t extinfo_size = 0) inherited
The original push method is divided into pushdown() and push().
The pushdown method is the generic part of the code, which is reserved for modeling the handling of messages transferred between protocol layers.
See Also
ProtocolSession::push method for details.
Definition at line 72 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::push().
Referenced by s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), s3f::s3fnet::IPSession::control(), s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), s3f::s3fnet::OpenFlowSwitchSession::OutputControl(), s3f::s3fnet::OpenFlowSwitchSession::OutputPacket(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::UDPMaster::push(), s3f::s3fnet::TCPMaster::push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::send(), and s3f::s3fnet::TCPSession::send_data().
 {
   return push(msg, hi_sess, extinfo, extinfo_size);
 }
int s3f::s3fnet::ProtocolSession::popup (Activation msg, ProtocolSession * lo_sess, void * extinfo = 0, size_t extinfo_size = 0) inherited
The original pop method is divided into popup() and pop().
The popup method is the generic part of the code, which is reserved for modeling the handling of messages transferred between protocol layers.
See Also
ProtocolSession::pop method for details.
Definition at line 77 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::pop().
Referenced by s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::IPSession::push(), and s3f::s3fnet::SimplePhy::receivePacket().
 {
   return pop(msg, lo_sess, extinfo, extinfo_size);
 }
int s3f::s3fnet::ProtocolSession::control (int ctrltyp, void * ctrlmsg, ProtocolSession * sess) virtual inherited
The control method is used by the protocol session to receive control messages (or information queries) from other protocol sessions both above and below this protocol session on the stack.
The derived class should override this method to provide support for handling different control messages. In this case, the derived class should invoke this method when encountering a control type that it does not know to to process.
The control messages are distinguished via types. The ctrl type is an integer; its meaning is specified by the particular protocol. The users are recommended to use ctrl type values beyond 1000 (excluding 1000). The values within 1000 are reserved. The control message is of type void* and should be cast to the appropriate types accordingly. Note that, unless specified otherwise, the caller is responsible to reclaim the control message once the method returns. The protocol session that invoking this method will have a reference to itself in the third argument.
The method returns an integer, indicating whether the control message is successfully processed. Unless specified otherwise, a zero means success. Non-zero means trouble and the returned value can be used as the error number, the meaning of which is specified by each particular protocol.
For information on a specific control type, see s3f::s3fnet::ProtocolSessionCtrlTypes
Reimplemented in s3f::s3fnet::IPSession, s3f::s3fnet::NBSocketMaster, s3f::s3fnet::SocketMaster, s3f::s3fnet::OpenFlowSwitchSession, s3f::s3fnet::SimplePhy, s3f::s3fnet::OpenVZEventSession, s3f::s3fnet::OpenFlowControllerSession, s3f::s3fnet::UDPMaster, s3f::s3fnet::DummySession, s3f::s3fnet::LowestProtocolSession, and s3f::s3fnet::NicProtocolSession.
Definition at line 92 of file protocol_session.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::PSESS_CTRL_SESSION_GET_INTERFACE, s3f::s3fnet::PSESS_CTRL_SESSION_IS_LOWEST, s3f::s3fnet::PSESS_CTRL_SESSION_SET_CHILD, and s3f::s3fnet::PSESS_CTRL_SESSION_SET_PARENT.
Referenced by s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::TCPSession::clear_app_state(), s3f::s3fnet::Host::config(), s3f::s3fnet::NicProtocolSession::control(), s3f::s3fnet::DummySession::control(), s3f::s3fnet::UDPMaster::control(), s3f::s3fnet::OpenFlowControllerSession::control(), s3f::s3fnet::OpenVZEventSession::control(), s3f::s3fnet::OpenFlowSwitchSession::control(), s3f::s3fnet::SocketMaster::control(), s3f::s3fnet::NBSocketMaster::control(), s3f::s3fnet::IPSession::control(), s3f::s3fnet::Host::loadForwardingTable(), s3f::s3fnet::UDPSession::release(), s3f::s3fnet::UDPSession::wake_app(), and s3f::s3fnet::TCPSession::wake_app().
 {
   switch(ctrltype) {
   case PSESS_CTRL_SESSION_IS_LOWEST:
     assert(ctrlmsg);
     *((bool*)ctrlmsg) = false;
     return 0;
   case PSESS_CTRL_SESSION_GET_INTERFACE:
     assert(ctrlmsg);
     *((NetworkInterface**)ctrlmsg) = 0;
     return 0;
   case PSESS_CTRL_SESSION_SET_PARENT:
   case PSESS_CTRL_SESSION_SET_CHILD:
     return 0;
   default:
     // all control types should be handled at this point; if not, we
     // should report the problem
     error_quit("ERROR: ProtocolSession::control(), "
                "unknown control type: %d.\n", ctrltype);
   }
   return 0;
 }
ProtocolGraph* s3f::s3fnet::ProtocolSession::inGraph () inline inherited
The method returns the protocol graph in which this protocol session resides.
Definition at line 178 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::ingraph.
Referenced by s3f::s3fnet::SimplePhy::config(), s3f::s3fnet::SimplePhy::control(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::SimpleMac::init(), s3f::s3fnet::SimplePhy::init(), s3f::s3fnet::RedQueue::init(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::SimplePhy::push(), s3f::s3fnet::SimplePhy::receivePacket(), s3f::s3fnet::SimplePhy::sendPacket(), s3f::s3fnet::SimpleMac::SimpleMac(), s3f::s3fnet::SimplePhy::SimplePhy(), s3f::s3fnet::SimpleMac::~SimpleMac(), and s3f::s3fnet::SimplePhy::~SimplePhy().
 { return ingraph; }
Host * s3f::s3fnet::ProtocolSession::inHost () virtual inherited
Return a pointer to the host owning this protocol session.
Reimplemented in s3f::s3fnet::NicProtocolSession.
Definition at line 118 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::ingraph.
Referenced by s3f::s3fnet::UDPSession::abort(), s3f::s3fnet::SocketMaster::abort(), s3f::s3fnet::NBSocketMaster::abort(), s3f::s3fnet::SocketMaster::accept(), s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::accept1a(), s3f::s3fnet::SocketMaster::accept1b(), s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SocketMaster::accept2b(), s3f::s3fnet::OpenFlowSwitchSession::AddFlow(), s3f::s3fnet::TCPSession::backoff_timeout(), s3f::s3fnet::SocketMaster::bind(), s3f::s3fnet::NBSocketMaster::bind(), s3f::s3fnet::SocketMaster::block_till(), s3f::s3fnet::NBSocketMaster::block_till(), s3f::s3fnet::BTCPClientSession::BTCPClientSession(), s3f::s3fnet::OpenFlowSwitchSession::BufferFromPacket(), s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::UDPServerSession::client_connected(), s3f::s3fnet::SocketMaster::close(), s3f::s3fnet::NBSocketMaster::close(), s3f::s3fnet::SocketMaster::close1(), s3f::s3fnet::NBSocketMaster::close1(), s3f::s3fnet::UDPMaster::config(), s3f::s3fnet::DummySession::config(), s3f::s3fnet::TCPClientSession::config(), s3f::s3fnet::UDPServerSession::config(), s3f::s3fnet::UDPClientSession::config(), config(), s3f::s3fnet::TCPMaster::config(), s3f::s3fnet::NBTCPClientSession::config(), s3f::s3fnet::BTCPClientSession::config(), s3f::s3fnet::IPSession::config(), s3f::s3fnet::NBTCPServerSession::config(), s3f::s3fnet::UDPSession::connect(), s3f::s3fnet::SocketMaster::connect(), s3f::s3fnet::NBSocketMaster::connect(), s3f::s3fnet::SocketMaster::connect1(), s3f::s3fnet::NBSocketMaster::connect1(), s3f::s3fnet::SocketMaster::connected(), s3f::s3fnet::NBSocketMaster::connected(), s3f::s3fnet::UDPMaster::control(), s3f::s3fnet::SocketMaster::control(), s3f::s3fnet::NBSocketMaster::control(), s3f::s3fnet::IPSession::control(), s3f::s3fnet::TCPMaster::createSession(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::UDPServerSession::data_sent(), data_sent(), s3f::s3fnet::UDPSession::disconnect(), s3f::s3fnet::TCPMaster::enableFastTimeout(), s3f::s3fnet::SocketMaster::eof(), s3f::s3fnet::NBSocketMaster::eof(), s3f::s3fnet::UDPClientSessionContinuation::failure(), s3f::s3fnet::UDPServerSessionContinuation::failure(), s3f::s3fnet::TCPServerSessionContinuation::failure(), s3f::s3fnet::TCPClientSessionContinuation::failure(), s3f::s3fnet::BTCPClientSessionContinuation::failure(), s3f::s3fnet::TCPMaster::fast_timer_callback_body(), s3f::s3fnet::Stats::FlowStatsDump(), s3f::s3fnet::OpenFlowSwitchSession::FlowTableLookup(), s3f::s3fnet::IPSession::get_parent_by_protocol(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::ProtocolSession::getNow(), s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::OpenFlowSwitchSession::HandleControlInput(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), s3f::s3fnet::DummySession::init(), s3f::s3fnet::UDPMaster::init(), s3f::s3fnet::OpenFlowControllerSession::init(), s3f::s3fnet::OpenVZEventSession::init(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPServerSession::init(), s3f::s3fnet::UDPClientSession::init(), init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::OpenFlowSwitchSession::init(), s3f::s3fnet::NBTCPClientSession::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::SocketMaster::init(), s3f::s3fnet::IPSession::init(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::NBSocketMaster::init(), s3f::s3fnet::NBTCPServerSession::init(), s3f::s3fnet::TCPSession::init_state_closed(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::IPSession::IPSession(), s3f::s3fnet::UDPSession::listen(), s3f::s3fnet::SocketMaster::listen(), s3f::s3fnet::NBSocketMaster::listen(), s3f::s3fnet::IPSession::load_forwarding_table(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), s3f::s3fnet::OpenFlowSwitchSession::ModFlow(), s3f::s3fnet::NBSocketMaster::NBSocketMaster(), s3f::s3fnet::NBTCPClientSession::NBTCPClientSession(), s3f::s3fnet::NBTCPServerSession::NBTCPServerSession(), s3f::s3fnet::NBTCPClientSession::non_blocking_loop(), s3f::s3fnet::NBTCPServerSession::non_blocking_loop(), s3f::s3fnet::OpenFlowSwitchSession::OutputControl(), s3f::s3fnet::OpenFlowSwitchSession::OutputPacket(), s3f::s3fnet::OpenFlowSwitchSession::OutputPort(), s3f::s3fnet::OpenFlowControllerSession::pop(), s3f::s3fnet::UDPMaster::pop(), s3f::s3fnet::OpenVZEventSession::pop(), s3f::s3fnet::OpenFlowSwitchSession::pop(), s3f::s3fnet::TCPMaster::pop(), s3f::s3fnet::IPSession::pop(), s3f::s3fnet::LearningController::process_recv_packet(), s3f::s3fnet::UDPMaster::push(), s3f::s3fnet::TCPMaster::push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::receive(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::LearningControllerSession::ReceiveFromSwitch(), s3f::s3fnet::OpenFlowSwitchSession::ReceivePacketOut(), s3f::s3fnet::OpenFlowSwitchSession::ReceivePortMod(), s3f::s3fnet::OpenFlowSwitchSession::ReceiveStatsRequest(), s3f::s3fnet::SocketMaster::recv(), s3f::s3fnet::NBSocketMaster::recv(), s3f::s3fnet::SocketMaster::recv1(), s3f::s3fnet::NBSocketMaster::recv1(), s3f::s3fnet::UDPServerSession::request_received(), request_received(), s3f::s3fnet::UDPClientSession::request_sent(), s3f::s3fnet::TCPClientSession::request_sent(), s3f::s3fnet::NBTCPClientSessionContinuation::resume(), s3f::s3fnet::NBTCPServerSessionContinuation::resume(), s3f::s3fnet::OpenFlowSwitchSession::RunThroughFlowTable(), s3f::s3fnet::UDPSession::send(), s3f::s3fnet::SocketMaster::send(), s3f::s3fnet::NBSocketMaster::send(), s3f::s3fnet::SocketMaster::send1(), s3f::s3fnet::NBSocketMaster::send1(), s3f::s3fnet::TCPSession::send_data(), s3f::s3fnet::OpenFlowSwitchSession::SendFlowExpired(), s3f::s3fnet::OpenFlowSwitchSession::SendOpenflowBuffer(), s3f::s3fnet::OpenFlowSwitchSession::SendPortStatus(), s3f::s3fnet::UDPClientSession::server_connected(), s3f::s3fnet::TCPClientSession::server_connected(), s3f::s3fnet::BTCPClientSession::server_connected(), s3f::s3fnet::UDPServerSession::session_closed(), s3f::s3fnet::UDPClientSession::session_closed(), s3f::s3fnet::TCPClientSession::session_closed(), session_closed(), s3f::s3fnet::BTCPClientSession::session_closed(), s3f::s3fnet::TCPMaster::setConnected(), s3f::s3fnet::OpenFlowSwitchSession::SetController(), s3f::s3fnet::TCPMaster::setIdle(), s3f::s3fnet::TCPMaster::setListening(), s3f::s3fnet::UDPSession::setSource(), s3f::s3fnet::TCPMaster::slow_timer_callback_body(), s3f::s3fnet::TCPSession::slowTimeoutHandling(), s3f::s3fnet::SocketMaster::socket(), s3f::s3fnet::NBSocketMaster::socket(), s3f::s3fnet::SocketMaster::SocketMaster(), s3f::s3fnet::UDPServerSession::start_on(), s3f::s3fnet::UDPClientSession::start_on(), start_on(), s3f::s3fnet::TCPClientSession::start_on(), s3f::s3fnet::NBTCPClientSession::start_on(), s3f::s3fnet::BTCPClientSession::start_on(), s3f::s3fnet::NBTCPServerSession::start_on(), s3f::s3fnet::NBTCPServerSessionContinuation::success(), s3f::s3fnet::TCPClientSession::TCPClientSession(), s3f::s3fnet::TCPMaster::TCPMaster(), TCPServerSession(), s3f::s3fnet::TCPSession::TCPSession(), s3f::s3fnet::UDPClientSession::timeout(), s3f::s3fnet::TCPClientSession::timeout(), s3f::s3fnet::BTCPClientSession::timeout(), s3f::s3fnet::UDPClientSession::UDPClientSession(), s3f::s3fnet::UDPMaster::UDPMaster(), s3f::s3fnet::UDPServerSession::UDPServerSession(), s3f::s3fnet::UDPSession::UDPSession(), s3f::s3fnet::TCPSession::update_timeout(), s3f::s3fnet::IPSession::verify_local_ip_address(), and s3f::s3fnet::UDPSession::wake_app().
 {
   return dynamic_cast<Host*>(ingraph);
 }
Random::RNG* s3f::s3fnet::ProtocolSession::getRandom () inline inherited
The method returns a pointer to the random number generator.
Definition at line 200 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::sess_rng.
Referenced by s3f::s3fnet::DroptailQueue::calibrate(), s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::DummySession::init(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), and s3f::s3fnet::NetworkInterface::receivePacket().
 { return sess_rng;}
ltime_t s3f::s3fnet::ProtocolSession::getNow () inherited
The method returns the current simulation time.
To be safe, please do NOT call this function after initialization and before wrapup phase. That is, it is unsafe to call this method in the constructor, destructor, config, init, and wrapup methods. The time service is carried out by the host's owner community. This method just directs the call to the community. It's given here for convenience.
Definition at line 123 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::inHost(), and Entity::now().
Referenced by s3f::s3fnet::DroptailQueue::calibrate(), s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::TCPMaster::enableFastTimeout(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::TCPMaster::fast_timer_callback_body(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::TCPSession::now(), s3f::s3fnet::OpenVZEventSession::pop(), s3f::s3fnet::TCPMaster::slow_timer_callback_body(), s3f::s3fnet::SocketMaster::socket(), s3f::s3fnet::NBSocketMaster::socket(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), and s3f::s3fnet::BTCPClientSession::start_on().
 {
   return inHost()->now();
 }
char * s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator () inherited
For printing the current simulation time in a better readable format.
Definition at line 128 of file protocol_session.cc.
References s3f::s3fnet::Host::getNowWithThousandSeparator(), and s3f::s3fnet::ProtocolSession::inHost().
Referenced by s3f::s3fnet::UDPSession::abort(), s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::UDPSession::connect(), s3f::s3fnet::TCPMaster::createSession(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::UDPServerSession::data_sent(), data_sent(), s3f::s3fnet::UDPSession::disconnect(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::UDPSession::listen(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), s3f::s3fnet::DummySession::pop(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::OpenVZEventSession::pop(), s3f::s3fnet::UDPMaster::pop(), s3f::s3fnet::TCPMaster::pop(), s3f::s3fnet::IPSession::pop(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::UDPMaster::push(), s3f::s3fnet::SimplePhy::push(), s3f::s3fnet::TCPMaster::push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::receive(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::SimplePhy::receivePacket(), s3f::s3fnet::UDPServerSession::request_received(), request_received(), s3f::s3fnet::UDPClientSession::request_sent(), s3f::s3fnet::TCPClientSession::request_sent(), s3f::s3fnet::UDPSession::send(), s3f::s3fnet::TCPSession::send_data(), s3f::s3fnet::SimplePhy::sendPacket(), s3f::s3fnet::UDPClientSession::server_connected(), s3f::s3fnet::TCPClientSession::server_connected(), s3f::s3fnet::BTCPClientSession::server_connected(), s3f::s3fnet::UDPServerSession::session_closed(), s3f::s3fnet::UDPClientSession::session_closed(), s3f::s3fnet::TCPClientSession::session_closed(), session_closed(), s3f::s3fnet::BTCPClientSession::session_closed(), s3f::s3fnet::TCPMaster::setConnected(), s3f::s3fnet::TCPMaster::setIdle(), s3f::s3fnet::TCPMaster::setListening(), s3f::s3fnet::UDPSession::setSource(), s3f::s3fnet::TCPSession::slowTimeoutHandling(), s3f::s3fnet::UDPServerSession::start_on(), s3f::s3fnet::UDPClientSession::start_on(), start_on(), s3f::s3fnet::TCPClientSession::start_on(), s3f::s3fnet::BTCPClientSession::start_on(), s3f::s3fnet::TCPSession::TCPSession(), s3f::s3fnet::UDPClientSession::timeout(), s3f::s3fnet::TCPClientSession::timeout(), s3f::s3fnet::BTCPClientSession::timeout(), s3f::s3fnet::UDPSession::UDPSession(), s3f::s3fnet::TCPSession::update_timeout(), and s3f::s3fnet::UDPSession::wake_app().
 {
         return inHost()->getNowWithThousandSeparator();
 }
int s3f::s3fnet::ProtocolSession::configured () inline inherited
This method returns true if the protocol session has been configured.
This method is used to make sure we configure the protocol session before initializing it.
Definition at line 221 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_CONFIGURED, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::config(), and s3f::s3fnet::ProtocolSession::init().
 { return stage >= PSESS_CONFIGURED; }
int s3f::s3fnet::ProtocolSession::initialized () inline inherited
This method returns true if the protocol session has been initialized.
This can be used to sequence calls to the init method of protocol sessions. For example, if protocol session A requires protocol session B to be initialized before A can be initialized, A's init method can call B's init method as long as B's initialized() returns true. The system does not enforce any ordering in its calls the init methods of all protocol sessions declared in the dml configuration.
Definition at line 233 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_INITIALIZED, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::init(), and s3f::s3fnet::ProtocolSession::wrapup().
 { return stage >= PSESS_INITIALIZED; }
int s3f::s3fnet::ProtocolSession::wrapped_up () inline inherited
This method returns true if the protocol session has been wrapped up.
This can be used to sequence calls to the wrapup method of protocol sessions. For example, if protocol session A requires protocol session B to be wrapped up before A can be wrapped up, A's wrapup method can call B's wrapup method as long as B's wrapped_up() returns true. The system does not enforce any ordering in its calls the wrapup methods of all protocol sessions declared in the dml configuration.
Definition at line 245 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_WRAPPED_UP, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::wrapup().
 { return stage >= PSESS_WRAPPED_UP; }
virtual const char* s3f::s3fnet::ProtocolSession::psesstype () inline virtual inherited
Reimplemented in s3f::s3fnet::NBSocketMaster, and s3f::s3fnet::SocketMaster.
Definition at line 247 of file protocol_session.h.
 { return "GENERIC"; } // DEBUG
virtual int s3f::s3fnet::ProtocolSession::instantiation_type () inline protected virtual inherited
This method controls how protocol instances can coexist with one another.
It returns one of the following:
PROT_UNIQUE_INSTANCE (default): allows only one instance for each type of protocol per protocol stack;
PROT_MULTIPLE_INSTANCES: allows multiple instances of the same implementation for each type of protocol per protocol stack;
PROT_MULTIPLE_IMPLEMENTATIONS: allows multiple instances from different implementations of the same protocol to exist on the protocol stack.
Reimplemented in s3f::s3fnet::BTCPClientSession, and s3f::s3fnet::TCPClientSession.
Definition at line 269 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PROT_UNIQUE_INSTANCE.
Referenced by s3f::s3fnet::ProtocolGraph::insert_session().
 { return PROT_UNIQUE_INSTANCE; }
Member Data Documentation
Process* s3f::s3fnet::TCPServerSession::start_timer_callback_proc
Process object for start timer callback Provide call_back functionality for implementing the start timer in the TCPServerSession.
This S3F process is used by waitFor() function.
Definition at line 72 of file tcp_server.h.
Referenced by init().
ProtocolCallbackActivation* s3f::s3fnet::TCPServerSession::start_timer_ac
Activation object for start timer callback.
Stores the data for the callback function. In this case, the TCPServerSession object is stored.
Definition at line 84 of file tcp_server.h.
Referenced by init().
uint16 s3f::s3fnet::TCPServerSession::server_port private
Port number to receive incoming request.
Definition at line 131 of file tcp_server.h.
Referenced by config(), and start_on().
uint32 s3f::s3fnet::TCPServerSession::request_size private
Size of the request from client (must be consistent).
Definition at line 136 of file tcp_server.h.
Referenced by config(), connection_accepted(), request_received(), and s3f::s3fnet::TCPServerSessionContinuation::TCPServerSessionContinuation().
uint32 s3f::s3fnet::TCPServerSession::client_limit private
Number of client sessions that can be handled simultaneously.
Definition at line 141 of file tcp_server.h.
Referenced by config(), connection_accepted(), s3f::s3fnet::TCPServerSessionContinuation::failure(), session_closed(), and start_on().
bool s3f::s3fnet::TCPServerSession::accept_completed private
Accept has been completed We have at least one client connected.
Definition at line 147 of file tcp_server.h.
Referenced by connection_accepted(), s3f::s3fnet::TCPServerSessionContinuation::failure(), session_closed(), and start_on().
bool s3f::s3fnet::TCPServerSession::show_report private
Whether we print out the result or not.
Definition at line 152 of file tcp_server.h.
Referenced by config().
SocketMaster* s3f::s3fnet::TCPServerSession::sm private
Pointer to the socket master.
Definition at line 159 of file tcp_server.h.
Referenced by connection_accepted(), data_sent(), handle_client(), init(), sending_data(), and start_on().
IPADDR s3f::s3fnet::TCPServerSession::server_ip private
The ip address of this server (interface 0).
Definition at line 165 of file tcp_server.h.
Referenced by init().
uint32 s3f::s3fnet::TCPServerSession::nclients private
Number of clients currently connected.
Definition at line 170 of file tcp_server.h.
Referenced by connection_accepted(), s3f::s3fnet::TCPServerSessionContinuation::failure(), session_closed(), and start_on().
char* s3f::s3fnet::ProtocolSession::name inherited
Symbolic name of the protocol this session implements.
The name of the protocol is derived from the DML 'name' attribute. It must not be NULL once the protocol session is configured.
Definition at line 63 of file protocol_session.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::SimpleMac::init(), s3f::s3fnet::UDPMaster::init(), s3f::s3fnet::SimplePhy::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::SocketMaster::init(), s3f::s3fnet::IPSession::init(), s3f::s3fnet::NBSocketMaster::init(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::ProtocolGraph::insert_session(), s3f::s3fnet::ProtocolSession::wrapup(), and s3f::s3fnet::ProtocolSession::~ProtocolSession().
float s3f::s3fnet::ProtocolSession::version inherited
Version number of this protocol implemenntation, represented as a floating point number (e.g., 1.23).
Definition at line 69 of file protocol_session.h.
char* s3f::s3fnet::ProtocolSession::use inherited
Name of the protocol class from which this protocol session is instantiated.
The protocol class must be registered with the Protocols class so that we will be able to instantiate an object from the class. (C++ does not support self-reflection). The class name must not be NULL once the protocol session is configured.
Definition at line 79 of file protocol_session.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::ProtocolGraph::insert_session(), and s3f::s3fnet::ProtocolSession::~ProtocolSession().
ProtocolGraph* s3f::s3fnet::ProtocolSession::ingraph protected inherited
Points to the protocol graph.
Definition at line 335 of file protocol_session.h.
Referenced by s3f::s3fnet::NicProtocolSession::getNetworkInterface(), s3f::s3fnet::ProtocolSession::inGraph(), and s3f::s3fnet::ProtocolSession::inHost().
Random::RNG* s3f::s3fnet::ProtocolSession::sess_rng protected inherited
Pointer to a random number generator.
Definition at line 338 of file protocol_session.h.
Referenced by s3f::s3fnet::ProtocolSession::getRandom(), and s3f::s3fnet::ProtocolSession::init().
int s3f::s3fnet::ProtocolSession::stage protected inherited
This variable indicates the current stage of this protocol session.
Each protocol session will go through four staged: PSESS_CREATED, PSESS_CONFIGURED, PSESS_INITIALIZED, and then PSESS_WRAPPED_UP.
Definition at line 346 of file protocol_session.h.
Referenced by s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::ProtocolSession::configured(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::ProtocolSession::initialized(), s3f::s3fnet::ProtocolSession::wrapped_up(), and s3f::s3fnet::ProtocolSession::wrapup().
The documentation for this class was generated from the following files:
tcp_server.h
tcp_server.cc