S3F: s3f::s3fnet::SocketSession Class Reference
s3f::s3fnet::SocketSession Class Reference abstract
The socket session.
#include <socket_session.h>
Public Member Functions
SocketSession (uint32 proto=0, IPADDR srcip=0, uint16 srcport=0, IPADDR destip=0, uint16 destport=0)
The constructor.
virtual ~SocketSession ()
The destructor.
virtual bool connect (IPADDR destip, uint16 destport)=0
Connect to remote host Return true if connected successfuly to the destination with a given ip address and port number.
virtual void disconnect ()=0
Disconnect the session.
virtual int send (int length, byte *msg)=0
Send data to remote host Send the data down the protocol stack.
virtual int recv (int length, byte *msg)=0
Receive data from remote host Receive the arrived data.
virtual bool listen ()=0
Passive open.
virtual bool connected ()=0
Returns true if connected.
virtual bool setSource (IPADDR ip, uint16 port)=0
Set the source ip and port for a connection.
virtual void abort ()=0
Abort the session.
virtual void setSocketID (int sock)=0
Set the socket id.
virtual SessionMaster * getSessionMaster ()=0
Return the master protocol session.
virtual void reinit ()
Called by socket to reinitialize the destination ip and port.
virtual void release ()=0
Necessary steps are taken to reclaim this socket session.
char * toString (char *buf)
Translate the ID into a textual string.
Public Attributes
uint32 prot_id
The protocol number.
IPADDR src_ip
Source ip address.
IPADDR dst_ip
Destination ip address.
uint16 src_port
Source port number.
uint16 dst_port
Destination port number.
Detailed Description
The socket session.
A socket session is an application session used for communication between an application and the underlying protocols (especially, the socket master protocol session) through a socket.
Definition at line 174 of file socket_session.h.
Constructor & Destructor Documentation
s3f::s3fnet::SocketSession::SocketSession (uint32 proto = 0, IPADDR srcip = 0, uint16 srcport = 0, IPADDR destip = 0, uint16 destport = 0) inline
The constructor.
Definition at line 177 of file socket_session.h.
                                                                                                        :
     SessionID(proto, srcip, srcport, destip, destport) {}
virtual s3f::s3fnet::SocketSession::~SocketSession () inline virtual
The destructor.
Definition at line 181 of file socket_session.h.
 {}
Member Function Documentation
virtual bool s3f::s3fnet::SocketSession::connect (IPADDR destip, uint16 destport) pure virtual
Connect to remote host Return true if connected successfuly to the destination with a given ip address and port number.
Must be implemented by deriving class (pure virtual).
Parameters
destip the destination ip address
destport the desination port
Returns
bool true on success, else false
Implemented in s3f::s3fnet::TCPSession, and s3f::s3fnet::UDPSession.
Referenced by s3f::s3fnet::SocketMaster::connect(), and s3f::s3fnet::NBSocketMaster::connect().
virtual void s3f::s3fnet::SocketSession::disconnect () pure virtual
Disconnect the session.
Must be implemented by deriving class (pure virtual).
Implemented in s3f::s3fnet::TCPSession, and s3f::s3fnet::UDPSession.
Referenced by s3f::s3fnet::SocketMaster::close(), and s3f::s3fnet::NBSocketMaster::close().
virtual int s3f::s3fnet::SocketSession::send (int length, byte * msg) pure virtual
Send data to remote host Send the data down the protocol stack.
If it is fake data, msg is NULL. Return how many bytes have been sent out. -1 means error. Must be implemented by deriving class (pure virtual).
Parameters
length size in bytes of message to send
msg actual byte buffer to send
Returns
number of bytes sent, -1 means error
Implemented in s3f::s3fnet::TCPSession, and s3f::s3fnet::UDPSession.
Referenced by s3f::s3fnet::SocketMaster::send(), and s3f::s3fnet::NBSocketMaster::send().
virtual int s3f::s3fnet::SocketSession::recv (int length, byte * msg) pure virtual
Receive data from remote host Receive the arrived data.
If the msg is not NULL, the data is copied into the message buffer up to the number of bytes requested. Return how many bytes that have really been received. -1 means error. Must be implemented by deriving class (pure virtual).
Parameters
length size in bytes of receive buffer provided
msg receive buffer to write received data into
Returns
number of bytes read, -1 means error
Implemented in s3f::s3fnet::TCPSession, and s3f::s3fnet::UDPSession.
Referenced by s3f::s3fnet::SocketMaster::recv(), and s3f::s3fnet::NBSocketMaster::recv().
virtual bool s3f::s3fnet::SocketSession::listen () pure virtual
Passive open.
Must be implemented by deriving class (pure virtual).
Returns
true if connected successfully, false otherwise
Implemented in s3f::s3fnet::TCPSession, and s3f::s3fnet::UDPSession.
Referenced by s3f::s3fnet::SocketMaster::accept(), s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::listen(), and s3f::s3fnet::NBSocketMaster::listen().
virtual bool s3f::s3fnet::SocketSession::connected () pure virtual
Returns true if connected.
Must be implemented by deriving class (pure virtual).
Returns
true if connected, false otherwise
Implemented in s3f::s3fnet::TCPSession, and s3f::s3fnet::UDPSession.
Referenced by s3f::s3fnet::SocketMaster::accept(), s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::close(), s3f::s3fnet::NBSocketMaster::close(), s3f::s3fnet::SocketMaster::connect(), s3f::s3fnet::NBSocketMaster::connect(), s3f::s3fnet::SocketMaster::connected(), s3f::s3fnet::NBSocketMaster::connected(), s3f::s3fnet::SocketMaster::listen(), s3f::s3fnet::NBSocketMaster::listen(), s3f::s3fnet::SocketMaster::recv(), s3f::s3fnet::NBSocketMaster::recv(), s3f::s3fnet::SocketMaster::send(), and s3f::s3fnet::NBSocketMaster::send().
virtual bool s3f::s3fnet::SocketSession::setSource (IPADDR ip, uint16 port) pure virtual
Set the source ip and port for a connection.
Must be implemented by deriving class (pure virtual).
Parameters
ip source ip address
port source port
Returns
true if successful, false otherwise
Implemented in s3f::s3fnet::TCPSession, and s3f::s3fnet::UDPSession.
Referenced by s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SocketMaster::bind(), and s3f::s3fnet::NBSocketMaster::bind().
virtual void s3f::s3fnet::SocketSession::abort () pure virtual
Abort the session.
Must be implemented by deriving class (pure virtual).
Implemented in s3f::s3fnet::TCPSession, and s3f::s3fnet::UDPSession.
Referenced by s3f::s3fnet::SocketMaster::abort(), and s3f::s3fnet::NBSocketMaster::abort().
virtual void s3f::s3fnet::SocketSession::setSocketID (int sock) pure virtual
Set the socket id.
Must be implemented by deriving class (pure virtual).
Parameters
sock the socket id
Implemented in s3f::s3fnet::TCPSession, and s3f::s3fnet::UDPSession.
Referenced by s3f::s3fnet::NBSocketMaster::accept(), and s3f::s3fnet::SocketMaster::accept2a().
virtual SessionMaster* s3f::s3fnet::SocketSession::getSessionMaster () pure virtual
Return the master protocol session.
Must be implemented by deriving class (pure virtual).
Returns
the session's master (ie BlockingSocketMaster)
Implemented in s3f::s3fnet::TCPSession, and s3f::s3fnet::UDPSession.
Referenced by s3f::s3fnet::NBSocketMaster::accept(), and s3f::s3fnet::SocketMaster::accept2a().
virtual void s3f::s3fnet::SocketSession::reinit () inline virtual
Called by socket to reinitialize the destination ip and port.
Definition at line 268 of file socket_session.h.
References s3f::s3fnet::SessionID::dst_ip, s3f::s3fnet::SessionID::dst_port, and IPADDR_ANYDEST.
Referenced by s3f::s3fnet::SocketMaster::control(), and s3f::s3fnet::NBSocketMaster::control().
{
     dst_ip = IPADDR_ANYDEST;
     dst_port = 0;
   }
virtual void s3f::s3fnet::SocketSession::release () pure virtual
Necessary steps are taken to reclaim this socket session.
Must be implemented by deriving class (pure virtual).
Implemented in s3f::s3fnet::TCPSession, and s3f::s3fnet::UDPSession.
Referenced by s3f::s3fnet::SocketMaster::close1(), s3f::s3fnet::NBSocketMaster::close1(), and s3f::s3fnet::Socket::release().
char* s3f::s3fnet::SessionID::toString (char * buf) inline inherited
Translate the ID into a textual string.
Parameters
buf buffer to write into (MUST NOT BE NULL)
Returns
pointer to the same buffer passe din
Definition at line 121 of file socket_session.h.
References s3f::s3fnet::SessionID::dst_ip, s3f::s3fnet::SessionID::dst_port, s3f::s3fnet::IPPrefix::ip2txt(), s3f::s3fnet::SessionID::prot_id, s3f::s3fnet::SessionID::src_ip, and s3f::s3fnet::SessionID::src_port.
{
     assert(buf);
     char buf0[50], buf1[50];
     sprintf(buf, "prot %u src_ip %s src_port %u dst_ip %s dst_port %u",
             prot_id, IPPrefix::ip2txt(src_ip, buf0), src_port,
             IPPrefix::ip2txt(dst_ip, buf1), dst_port);
     return buf;
   }
Member Data Documentation
uint32 s3f::s3fnet::SessionID::prot_id inherited
The protocol number.
Definition at line 132 of file socket_session.h.
Referenced by s3f::s3fnet::SessionCmp::operator()(), s3f::s3fnet::SessionID::operator=(), and s3f::s3fnet::SessionID::toString().
IPADDR s3f::s3fnet::SessionID::src_ip inherited
Source ip address.
Definition at line 135 of file socket_session.h.
Referenced by s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SessionCmp::operator()(), s3f::s3fnet::SessionID::operator=(), s3f::s3fnet::UDPSession::send(), s3f::s3fnet::TCPSession::send_data(), s3f::s3fnet::UDPSession::setSource(), s3f::s3fnet::TCPSession::setSource(), and s3f::s3fnet::SessionID::toString().
IPADDR s3f::s3fnet::SessionID::dst_ip inherited
Destination ip address.
Definition at line 138 of file socket_session.h.
Referenced by s3f::s3fnet::TCPSession::active_open(), s3f::s3fnet::UDPSession::connect(), s3f::s3fnet::SocketMaster::connected(), s3f::s3fnet::NBSocketMaster::connected(), s3f::s3fnet::SessionCmp::operator()(), s3f::s3fnet::SessionID::operator=(), reinit(), s3f::s3fnet::UDPSession::send(), s3f::s3fnet::TCPSession::send_data(), and s3f::s3fnet::SessionID::toString().
uint16 s3f::s3fnet::SessionID::src_port inherited
Source port number.
Definition at line 141 of file socket_session.h.
Referenced by s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SessionCmp::operator()(), s3f::s3fnet::SessionID::operator=(), s3f::s3fnet::UDPSession::send(), s3f::s3fnet::TCPSession::send_data(), s3f::s3fnet::UDPSession::setSource(), s3f::s3fnet::TCPSession::setSource(), and s3f::s3fnet::SessionID::toString().
uint16 s3f::s3fnet::SessionID::dst_port inherited
Destination port number.
Definition at line 144 of file socket_session.h.
Referenced by s3f::s3fnet::TCPSession::active_open(), s3f::s3fnet::UDPSession::connect(), s3f::s3fnet::SocketMaster::connected(), s3f::s3fnet::NBSocketMaster::connected(), s3f::s3fnet::SessionCmp::operator()(), s3f::s3fnet::SessionID::operator=(), reinit(), s3f::s3fnet::UDPSession::send(), s3f::s3fnet::TCPSession::send_data(), and s3f::s3fnet::SessionID::toString().
The documentation for this class was generated from the following file:
socket_session.h