S3F: TimelineInterface Class Reference
TimelineInterface Class Reference
TimelineInterface is another helper class, that carries information from the Interface class instance to be read by Timelines.
#include <interface.h>
Public Member Functions
TimelineInterface ()
TimelineInterface (stop_cond sc)
virtual ~TimelineInterface ()
int get_log_ticks_per_sec ()
void put_log_ticks_per_sec (int ltps)
int get_numTimelines ()
TimelineInterface (ltime_t t)
virtual bool stop_condition ()
default stop_condition function is not to stop
ltime_t get_stop_before ()
access to epoch state variable
void put_stop_before (ltime_t stop_before)
next_action get_next_action ()
access to type of synchronization
stop_cond get_stop_cond ()
void put_next_action (next_action na)
void put_stop_cond (stop_cond sc)
Public Attributes
next_action __next_action
type of next synchronization
stop_cond __stop_cond
ltime_t __stop_before
time up to which the Timelines ought to simulate
int __num_Timelines
SimCtrl * sc
bool isOpenVZEmu
whether S3F supports the openvz-based emulation
bool user_force_stop
flag indicating whether ctrl+c is pressed by users
ltime_t sim_target_time
Used to control whether it is the end of simulation cycle, and ready to enter emulation cycle, refer to the paper Yuhao Zheng, Dong Jin, and David Nicol.
pthread_mutex_t sim_target_time_mutex
use to guard multi-thread access to sim_target_time
int __log_ticks_per_sec
Detailed Description
TimelineInterface is another helper class, that carries information from the Interface class instance to be read by Timelines.
In particular it holds
– the simulation time up to which the Timelines ought next simulate
– the "type" of the next epoch of simulation
– a function called to determine whether to continue the simulation epoch
– the time-scale of the simulation clock ticks
One of these is created, and when the Timelines are created each is given a pointer to it
Definition at line 56 of file interface.h.
Constructor & Destructor Documentation
TimelineInterface::TimelineInterface () inline
Definition at line 60 of file interface.h.
References sim_target_time_mutex.
                             : __next_action(STOP_FUNCTION), __stop_cond(STOP_ON_ANY), user_force_stop(false)
         {  pthread_mutex_init(&sim_target_time_mutex, NULL); }
TimelineInterface::TimelineInterface (stop_cond sc) inline
Definition at line 63 of file interface.h.
References sim_target_time_mutex.
                                           : __next_action(STOP_FUNCTION), __stop_cond(sc), user_force_stop(false)
         { pthread_mutex_init(&sim_target_time_mutex, NULL); }
TimelineInterface::~TimelineInterface () virtual
Definition at line 41 of file interface.cc.
{
 #ifdef PTHREAD_BARRIER
         pthread_barrier_destroy(&window_barrier);
         pthread_barrier_destroy(&top_barrier);
         pthread_barrier_destroy(&bottom_barrier);
 #ifdef OPENVZ_EMULATION
         if(isOpenVZEmu == true)
         {
                 pthread_barrier_destroy(&emu_barrier);
                 pthread_barrier_destroy(&emu_window_barrier);
         }
 #endif
 #else
         window_barrier.destroy();
         top_barrier.destroy();
         bottom_barrier.destroy();
 #ifdef OPENVZ_EMULATION
         if(isOpenVZEmu == true)
         {
                 emu_barrier.destroy();
                 emu_window_barrier.destroy();
         }
 #endif
 #endif
 }
TimelineInterface::TimelineInterface (ltime_t t) inline
Definition at line 137 of file interface.h.
References sim_target_time_mutex.
                                        : __next_action(STOP_BEFORE_TIME),
                         __stop_before(t), user_force_stop(false)
         {pthread_mutex_init(&sim_target_time_mutex, NULL);};
Member Function Documentation
int TimelineInterface::get_log_ticks_per_sec () inline
Definition at line 132 of file interface.h.
References __log_ticks_per_sec.
Referenced by Interface::runtime_measurements(), and Timeline::Timeline().
 { return __log_ticks_per_sec; }
void TimelineInterface::put_log_ticks_per_sec (int ltps) inline
Definition at line 133 of file interface.h.
References __log_ticks_per_sec.
Referenced by Interface::Interface().
 { __log_ticks_per_sec = ltps; }
int TimelineInterface::get_numTimelines () inline
Definition at line 134 of file interface.h.
References __num_Timelines.
Referenced by Timeline::sim_global_scheduler_one_epoch(), and Timeline::Timeline().
 { return __num_Timelines; }
virtual bool TimelineInterface::stop_condition () inline virtual
default stop_condition function is not to stop
Definition at line 142 of file interface.h.
Referenced by Timeline::global_continue().
 { return false; }
ltime_t TimelineInterface::get_stop_before () inline
access to epoch state variable
Definition at line 146 of file interface.h.
References __stop_before.
Referenced by Interface::advance_body(), Timeline::sim_global_scheduler_one_epoch(), and Timeline::thread_function().
 { return __stop_before;    }
void TimelineInterface::put_stop_before (ltime_t stop_before) inline
Definition at line 147 of file interface.h.
References __stop_before.
Referenced by Interface::advance_body().
 { __stop_before = stop_before; }
next_action TimelineInterface::get_next_action () inline
access to type of synchronization
Definition at line 150 of file interface.h.
References __next_action.
Referenced by Timeline::thread_function(), and Timeline::Timeline().
 { return __next_action; }
stop_cond TimelineInterface::get_stop_cond () inline
Definition at line 151 of file interface.h.
References __stop_cond.
 { return __stop_cond; }
void TimelineInterface::put_next_action (next_action na) inline
Definition at line 152 of file interface.h.
References __next_action.
Referenced by Interface::advance_body().
 { __next_action = na;   }
void TimelineInterface::put_stop_cond (stop_cond sc) inline
Definition at line 153 of file interface.h.
References __stop_cond, and sc.
Referenced by Interface::advance_body().
 { __stop_cond = sc;   }
Member Data Documentation
next_action TimelineInterface::__next_action
type of next synchronization
Definition at line 68 of file interface.h.
Referenced by get_next_action(), and put_next_action().
stop_cond TimelineInterface::__stop_cond
Definition at line 69 of file interface.h.
Referenced by get_stop_cond(), and put_stop_cond().
ltime_t TimelineInterface::__stop_before
time up to which the Timelines ought to simulate
Definition at line 71 of file interface.h.
Referenced by get_stop_before(), and put_stop_before().
int TimelineInterface::__num_Timelines
Definition at line 72 of file interface.h.
Referenced by get_numTimelines(), and Interface::Interface().
SimCtrl* TimelineInterface::sc
Definition at line 75 of file interface.h.
Referenced by Interface::advance_body(), s3f::s3fnet::Net::config(), Interface::InitModel(), Interface::Interface(), put_stop_cond(), and Timeline::ve_proxy_entity_potential_impact_time().
bool TimelineInterface::isOpenVZEmu
whether S3F supports the openvz-based emulation
Definition at line 76 of file interface.h.
Referenced by Interface::advance_body(), Interface::InitModel(), Interface::Interface(), and Timeline::thread_function().
bool TimelineInterface::user_force_stop
flag indicating whether ctrl+c is pressed by users
Definition at line 77 of file interface.h.
Referenced by s3f::s3fnet::sigproc().
ltime_t TimelineInterface::sim_target_time
Used to control whether it is the end of simulation cycle, and ready to enter emulation cycle, refer to the paper Yuhao Zheng, Dong Jin, and David Nicol.
"Impacts of application lookahead on distributed network emulation," Winter Simulation Conference (WSC), 2013
Definition at line 85 of file interface.h.
pthread_mutex_t TimelineInterface::sim_target_time_mutex
use to guard multi-thread access to sim_target_time
Definition at line 86 of file interface.h.
Referenced by TimelineInterface().
int TimelineInterface::__log_ticks_per_sec
Definition at line 131 of file interface.h.
Referenced by get_log_ticks_per_sec(), and put_log_ticks_per_sec().
The documentation for this class was generated from the following files:
interface.h
interface.cc