S3F: SimCtrl Class Reference
SimCtrl Class Reference abstract
Class of the VE controller, previously called Sim/Control.
#include <simctrl.h>
Public Member Functions
SimCtrl ()
constructor
virtual ~SimCtrl ()
destructor
void inject_emu_event_to_s3fnet ()
inject emulation events to S3FNet
virtual int set_ve_boundary (int idbase, int nve)=0
set VE boundary for emulation, must be called before emu_init()
virtual int get_idbase ()=0
get start ID of this emulation setup
virtual int get_nve ()=0
get total number of VEs in this emulation setup
virtual VEHandle * get_vehandle (int ctid)=0
get a VE handle by its VE ID
virtual int set_ve_mindelay (int ctid, ltime_t delay)=0
after emu_init() and for no lookahead only, set the mindelay of a given VE
virtual ltime_t get_ve_mindelay (int ctid)=0
get mindelay of a given VE
virtual int set_ve_nif (int ctid, int nif)=0
set the number of interfaces of a VE, should be set before emu_init()
virtual int get_ve_nif (int ctid)=0
get the number of interfaces of a given VE
virtual int set_ve_ifip (int ctid, int ifid, const char *ip)=0
set the IP address of an interface, should be called before emu_init()
virtual int exec_ve_command (int ctid, const char *cmd)=0
execute a command on a VE for experiment purposes, should be called after emu_init()
virtual ltime_t get_clock ()=0
get current emulation time
virtual int emu_reset (bool close=false)=0
emulation reset, recommended to be called before emu_init and clean any errors
virtual int emu_init (int la_type=LOOKAHEAD_NONE)=0
emulation initialization, should be called before emu_cycle()
virtual int emu_cycle (ltime_t barrier)=0
emulation cycle: advance all VEs to a given barrier
virtual int emu_done ()=0
emulation clean up, should be called after emulation is over
Static Public Member Functions
static SimCtrl * get_simctrl (int type=EMULATION_LOCAL)
obtain concrete VE controller handle, for S3F/S3FNet use
static const char * errcode2txt (int code)
translate error code into human readable text
Public Attributes
Interface * siminf
simulation interface pointer
Detailed Description
Class of the VE controller, previously called Sim/Control.
This class handles the emulation subsystem for the S3F/S3FNet. This class is an abstract class which defines the function call interfaces.
Before emulation, emu_reset() and emu_init() should be called exactly once. This makes the emulation VEs enter virtual time mode.
After emulation, emu_done() should be called exactly once. This makes the emulation VEs return to normal mode.
During the emulation, emu_cycle() can be called to advance VEs to a barrier. When lookahead is enabled, emulation clock will stop exactly at the barrier. However, when lookahead is disabled, emulation may stop before the barrier, according to the optimized scheduling algorithm presented in our JOS'13 paper.
Before calling emu_cycle(), packets to be delivered should be put in recvq. After emu_cycle() returns, packets should be picked up from sendq.
Definition at line 219 of file simctrl.h.
Constructor & Destructor Documentation
SimCtrl::SimCtrl ()
constructor
Definition at line 117 of file simctrl.cc.
References siminf.
 {
         siminf = NULL;
 }
SimCtrl::~SimCtrl () virtual
destructor
Definition at line 124 of file simctrl.cc.
 {
 }
Member Function Documentation
SimCtrl * SimCtrl::get_simctrl (int type = EMULATION_LOCAL) static
obtain concrete VE controller handle, for S3F/S3FNet use
Parameters
type emulation type, either EMULATION_LOCAL or EMULATION_DISTRIBUTED
Returns
a concrete VE controller handle
Definition at line 130 of file simctrl.cc.
References EMULATION_DISTRIBUTED, and EMULATION_LOCAL.
Referenced by Interface::Interface().
 {
         switch (type)
         {
         case EMULATION_LOCAL:
                 return new SSimCtrl;
         case EMULATION_DISTRIBUTED:
                 return new DSimCtrl;
         default:
                 return NULL;
         }
         return NULL;
 }
const char * SimCtrl::errcode2txt (int code) static
translate error code into human readable text
Parameters
code error code
Returns
error text in string
Definition at line 146 of file simctrl.cc.
References EBUSY, and EINVAL.
Referenced by Interface::advance_body(), s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Net::config(), Interface::InitModel(), and main().
 {
         static char str[10];
         switch (-code)
         {
         case EPERM:     return "EPERM";
         case ENOENT:    return "ENOENT";
         case ESRCH:     return "ESRCH";
         case EINTR:     return "EINTR";
         case EIO:       return "EIO";
         case ENXIO:     return "ENXIO";
         case E2BIG:     return "E2BIG";
         case ENOEXEC:   return "ENOEXEC";
         case EBADF:     return "EBADF";
         case ECHILD:    return "ECHILD";
         case ENOMEM:    return "ENOMEM";
         case EACCES:    return "EACCES";
         case EFAULT:    return "EFAULT";
         case EBUSY:     return "EBUSY";
         case EEXIST:    return "EEXIST";
         case ENODEV:    return "ENODEV";
         case EINVAL:    return "EINVAL";
         case EPIPE:     return "EPIPE";
         case ERANGE:    return "ERANGE";
         }
         sprintf(str, "%d", code);
         return str;
 }
void SimCtrl::inject_emu_event_to_s3fnet ()
inject emulation events to S3FNet
Definition at line 177 of file simctrl.cc.
References siminf.
 {
         if (siminf) ((s3f::s3fnet::SimInterface*)siminf)->topnet->injectEmuEvents();
 }
virtual int SimCtrl::set_ve_boundary (int idbase, int nve) pure virtual
set VE boundary for emulation, must be called before emu_init()
Parameters
idbase start ID of this emulation setup
nve total number of VEs in this emulation setup
Returns
0 if succeed, negative error code otherwise
Implemented in DSimCtrl, and SSimCtrl.
Referenced by s3f::s3fnet::Net::config().
virtual int SimCtrl::get_idbase () pure virtual
get start ID of this emulation setup
Returns
start ID of this emulation setup
Implemented in DSimCtrl, and SSimCtrl.
virtual int SimCtrl::get_nve () pure virtual
get total number of VEs in this emulation setup
Returns
total number of VEs in this emulation setup
Implemented in DSimCtrl, and SSimCtrl.
virtual VEHandle* SimCtrl::get_vehandle (int ctid) pure virtual
get a VE handle by its VE ID
Parameters
ctid VE ID
Returns
pointer to VE handle, or NULL for invalid ctid
Implemented in DSimCtrl, and SSimCtrl.
Referenced by s3f::s3fnet::Host::init(), and s3f::s3fnet::Net::init().
virtual int SimCtrl::set_ve_mindelay (int ctid, ltime_t delay) pure virtual
after emu_init() and for no lookahead only, set the mindelay of a given VE
Parameters
ctid VE ID
delay mindelay
Returns
0 if succeed, negative error code otherwise
Implemented in DSimCtrl, and SSimCtrl.
virtual ltime_t SimCtrl::get_ve_mindelay (int ctid) pure virtual
get mindelay of a given VE
Parameters
ctid VE ID
Returns
mindelay of this VE
Implemented in DSimCtrl, and SSimCtrl.
virtual int SimCtrl::set_ve_nif (int ctid, int nif) pure virtual
set the number of interfaces of a VE, should be set before emu_init()
Parameters
ctid VE ID
nif nubmer of interfaces of this VE
Returns
0 if succeed, negative error code otherwise
Implemented in DSimCtrl, and SSimCtrl.
Referenced by s3f::s3fnet::Host::config().
virtual int SimCtrl::get_ve_nif (int ctid) pure virtual
get the number of interfaces of a given VE
Parameters
ctid VE ID
Returns
nubmer of interfaces of this VE, or negative error code for invalide ctid
Implemented in DSimCtrl, and SSimCtrl.
virtual int SimCtrl::set_ve_ifip (int ctid, int ifid, const char * ip) pure virtual
set the IP address of an interface, should be called before emu_init()
Parameters
ctid VE ID
ifid interface ID
ip IP address in string
Returns
0 if succeed, negative error code otherwise
Implemented in DSimCtrl, and SSimCtrl.
Referenced by s3f::s3fnet::NetworkInterface::config().
virtual int SimCtrl::exec_ve_command (int ctid, const char * cmd) pure virtual
execute a command on a VE for experiment purposes, should be called after emu_init()
Parameters
ctid VE ID
cmd command to execute
Returns
0 if succeed, negative error code otherwise
Implemented in DSimCtrl, and SSimCtrl.
virtual ltime_t SimCtrl::get_clock () pure virtual
get current emulation time
Returns
current emulation time
Implemented in DSimCtrl, and SSimCtrl.
Referenced by Timeline::ve_proxy_entity_potential_impact_time().
virtual int SimCtrl::emu_reset (bool close = false) pure virtual
emulation reset, recommended to be called before emu_init and clean any errors
Parameters
close for distributed emulation only, whether to close the connection
Returns
0 if succeed, negative error code otherwise
Implemented in DSimCtrl, and SSimCtrl.
Referenced by s3f::s3fnet::Net::config().
virtual int SimCtrl::emu_init (int la_type = LOOKAHEAD_NONE) pure virtual
emulation initialization, should be called before emu_cycle()
Parameters
la_type lookahead type, either LOOKAHEAD_NONE or LOOKAHEAD_ANN
Returns
0 if succeed, negative error code otherwise
Implemented in DSimCtrl, and SSimCtrl.
Referenced by Interface::InitModel().
virtual int SimCtrl::emu_cycle (ltime_t barrier) pure virtual
emulation cycle: advance all VEs to a given barrier
Parameters
barrier barrier in virtual time (may stop before it if using LOOKAHEAD_NONE)
Returns
0 if succeed, negative error code otherwise
Implemented in DSimCtrl, and SSimCtrl.
virtual int SimCtrl::emu_done () pure virtual
emulation clean up, should be called after emulation is over
Returns
0 if succeed, negative error code otherwise
Implemented in DSimCtrl, and SSimCtrl.
Referenced by Interface::advance_body().
Member Data Documentation
Interface* SimCtrl::siminf
simulation interface pointer
Definition at line 239 of file simctrl.h.
Referenced by s3f::s3fnet::Net::config(), inject_emu_event_to_s3fnet(), and SimCtrl().
The documentation for this class was generated from the following files:
simctrl.h
simctrl.cc