S3F: s3f::s3fnet::IPSession Class Reference
s3f::s3fnet::IPSession Class Reference
The Internet protocol session.
#include <ip_session.h>
Public Types
enum IPPushReturn {
IPPUSHRET_DOWN_DONE = 0, IPPUSHRET_TO_LOCAL_DONE = 1, IPPUSHRET_TO_LOCAL_FAIL = 2, IPPUSHRET_NO_ROUTE = 3,
IPPUSHRET_DROPPED_TTL_LIMIT = 4
}
All possible return values of IP push operation.
enum IPPopReturn {
IPPOPRET_UP_DONE = 0, IPPOPRET_FORWARD_DONE = 1, IPPOPRET_DROPPED_BY_FILTER = 2, IPPOPRET_DROPPED_NO_PROTOCOL = 3,
IPPOPRET_DROPPED_NO_ROUTE = 4, IPPOPRET_DROPPED_TTL_LIMIT = 5, IPPOPRET_DROPPED_NOT_FOR_ME = 6
}
All possible return values of IP pop operation.
enum InstantiationType { PROT_UNIQUE_INSTANCE = 0x00, PROT_MULTIPLE_INSTANCES = 0x01, PROT_MULTIPLE_IMPLEMENTATIONS = 0x02 }
Multiple protocol session instantiation type.
enum ExecutionStage { PSESS_CREATED = 0, PSESS_CONFIGURED = 1, PSESS_INITIALIZED = 2, PSESS_WRAPPED_UP = 3 }
A normal protocol session must go though the following stages.
Public Member Functions
IPSession (ProtocolGraph *graph)
The constructor.
virtual ~IPSession ()
The destructor.
virtual void config (s3f::dml::Configuration *cfg)
Configure the IP session.
virtual int getProtocolNumber ()
Return the protocol number.
virtual void init ()
Initialize the IP session.
virtual int control (int ctrltyp, void *ctrlmsg, ProtocolSession *sess)
The control method is used by the protocol session to receive control message (or query information) from adjacent protocol sessions both above and below.
void print_payload (const u_char *payload, int len)
print packet payload data (avoid printing binary data)
void print_hex_ascii_line (const u_char *payload, int len, int offset)
Print data in rows of 16 bytes in the format (offset hex ascii).
virtual void wrapup ()
The method is used to wrap up the protocol session.
int pushdown (Activation msg, ProtocolSession *hi_sess, void *extinfo=0, size_t extinfo_size=0)
The original push method is divided into pushdown() and push().
int popup (Activation msg, ProtocolSession *lo_sess, void *extinfo=0, size_t extinfo_size=0)
The original pop method is divided into popup() and pop().
ProtocolGraph * inGraph ()
The method returns the protocol graph in which this protocol session resides.
virtual Host * inHost ()
Return a pointer to the host owning this protocol session.
Random::RNG * getRandom ()
The method returns a pointer to the random number generator.
ltime_t getNow ()
The method returns the current simulation time.
char * getNowWithThousandSeparator ()
For printing the current simulation time in a better readable format.
int configured ()
This method returns true if the protocol session has been configured.
int initialized ()
This method returns true if the protocol session has been initialized.
int wrapped_up ()
This method returns true if the protocol session has been wrapped up.
virtual const char * psesstype ()
Static Public Member Functions
static int strtonum (const char *str)
Safe alternative to atoi() if valid numbers could be 0 (which atoi() returns on error).
Public Attributes
char * name
Symbolic name of the protocol this session implements.
float version
Version number of this protocol implemenntation, represented as a floating point number (e.g., 1.23).
char * use
Name of the protocol class from which this protocol session is instantiated.
Protected Member Functions
bool verify_target_ip_address (IPADDR ipaddr)
Verify whether an ip address is acceptable by local ip or not.
bool verify_local_ip_address (IPADDR ipaddr)
Verify whether an ip address is local or not.
void load_forwarding_table (s3f::dml::Configuration *cfg)
Load forwarding table.
ProtocolSession * get_parent_by_protocol (uint32 protocol)
Find parent by protocol number.
int handle_pop_pkt (Activation ip_msg, ProtocolSession *lo_sess, void *extinfo=NULL, int extinfo_size=0)
Handle packets that are popped up.
int handle_pop_local_pkt (Activation msg, ProtocolSession *lo_sess, void *extinfo=NULL, int extinfo_size=0)
Handle packets that are popped up and targetted to this machine.
virtual int instantiation_type ()
This method controls how protocol instances can coexist with one another.
Protected Attributes
ProtocolGraph * ingraph
Points to the protocol graph.
Random::RNG * sess_rng
Pointer to a random number generator.
int stage
This variable indicates the current stage of this protocol session.
Private Member Functions
virtual int push (Activation msg, ProtocolSession *hi_sess, void *extinfo=0, size_t extinfo_size=0)
Send a message down the protocol stack to lower layer.
virtual int pop (Activation msg, ProtocolSession *lo_sess, void *extinfo=0, size_t extinfo_size=0)
Receive data up the protocol stack to the upper layer.
S3FNET_VECTOR (RouteInfo *)*route_vec
Route specified in dml file.
S3FNET_VECTOR (DMLRouteInfo *)*dml_route_vec
S3FNET_VECTOR (ProtocolSession *)*listener_vec
Private Attributes
ForwardingTable * forwarding_table
Forwarding table used to deliver packets.
bool show_drop
Whether to print a message when a packet has been dropped.
ProtocolSession * pop_intercept_sess
session that intercept packet.
Detailed Description
The Internet protocol session.
Definition at line 30 of file ip_session.h.
Member Enumeration Documentation
enum s3f::s3fnet::IPSession::IPPushReturn
All possible return values of IP push operation.
Enumerator
IPPUSHRET_DOWN_DONE
The packet has been pushed down successfully.
IPPUSHRET_TO_LOCAL_DONE
The packet has been dealt with locally by popping up to an upper protocol successfully.
IPPUSHRET_TO_LOCAL_FAIL
The packet cannot be dealt with locally by popping up to an upper protocol successfully.
IPPUSHRET_NO_ROUTE
The packet cannot be pushed down due to no route to the destination being found.
IPPUSHRET_DROPPED_TTL_LIMIT
The packet is dropped due to TTL limit reached.
Definition at line 35 of file ip_session.h.
{
                 IPPUSHRET_DOWN_DONE         = 0,
                 IPPUSHRET_TO_LOCAL_DONE     = 1,
                 IPPUSHRET_TO_LOCAL_FAIL     = 2,
                 IPPUSHRET_NO_ROUTE          = 3,
                 IPPUSHRET_DROPPED_TTL_LIMIT = 4,
         };
enum s3f::s3fnet::IPSession::IPPopReturn
All possible return values of IP pop operation.
Enumerator
IPPOPRET_UP_DONE
The packet has been popped up to an upper layer successfully.
IPPOPRET_FORWARD_DONE
The packet has been forwarded successfully.
IPPOPRET_DROPPED_BY_FILTER
The packet is dropped by the filter (i.e., the intercept session).
IPPOPRET_DROPPED_NO_PROTOCOL
The packet is dropped due to no matching protocol on this host.
IPPOPRET_DROPPED_NO_ROUTE
The packet is dropped due to no route found.
IPPOPRET_DROPPED_TTL_LIMIT
The packet is dropped due to TTL limit reached.
IPPOPRET_DROPPED_NOT_FOR_ME
The packet is dropped because it is not for this end host.
Definition at line 58 of file ip_session.h.
{
                 IPPOPRET_UP_DONE = 0,
                 IPPOPRET_FORWARD_DONE        = 1,
                 IPPOPRET_DROPPED_BY_FILTER   = 2,
                 IPPOPRET_DROPPED_NO_PROTOCOL = 3,
                 IPPOPRET_DROPPED_NO_ROUTE    = 4,
                 IPPOPRET_DROPPED_TTL_LIMIT   = 5,
                 IPPOPRET_DROPPED_NOT_FOR_ME   = 6,
         };
enum s3f::s3fnet::ProtocolSession::InstantiationType inherited
Multiple protocol session instantiation type.
Enumerator
PROT_UNIQUE_INSTANCE
PROT_MULTIPLE_INSTANCES
PROT_MULTIPLE_IMPLEMENTATIONS
Definition at line 44 of file protocol_session.h.
{
     PROT_UNIQUE_INSTANCE                = 0x00,
     PROT_MULTIPLE_INSTANCES             = 0x01,
     PROT_MULTIPLE_IMPLEMENTATIONS       = 0x02
   };
enum s3f::s3fnet::ProtocolSession::ExecutionStage inherited
A normal protocol session must go though the following stages.
Enumerator
PSESS_CREATED
this protocol session has just been created
PSESS_CONFIGURED
the config method of this protocol session has been called
PSESS_INITIALIZED
the init method of this protocol session has been called
PSESS_WRAPPED_UP
Definition at line 51 of file protocol_session.h.
                       {
     PSESS_CREATED       = 0,
     PSESS_CONFIGURED    = 1,
     PSESS_INITIALIZED   = 2,
     PSESS_WRAPPED_UP    = 3
   };
Constructor & Destructor Documentation
s3f::s3fnet::IPSession::IPSession (ProtocolGraph * graph)
The constructor.
Definition at line 30 of file ip_session.cc.
References s3f::s3fnet::ProtocolSession::inHost(), and IP_DUMP.
                                          :
   ProtocolSession(graph),
   forwarding_table(0), show_drop(false),
   route_vec(0), dml_route_vec(0), listener_vec(0),
   pop_intercept_sess(0)
 {
   IP_DUMP(printf("[host=\"%s\"] new ip session.\n", inHost()->nhi.toString()));
 }
s3f::s3fnet::IPSession::~IPSession () virtual
The destructor.
Definition at line 39 of file ip_session.cc.
References forwarding_table, and IP_DUMP.
 {
   IP_DUMP(printf("delete ip session.\n"));
   if(route_vec)
   {
     for(unsigned i=0; i<route_vec->size(); i++)
       delete (*route_vec)[i];
     delete route_vec;
   }
   if(dml_route_vec)
   {
     for(unsigned i=0; i<dml_route_vec->size(); i++)
       delete (*dml_route_vec)[i];
     delete dml_route_vec;
   }
   if(listener_vec) delete listener_vec;
   if(forwarding_table) delete forwarding_table;
 }
Member Function Documentation
void s3f::s3fnet::IPSession::config (s3f::dml::Configuration * cfg) virtual
Configure the IP session.
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 60 of file ip_session.cc.
References s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolSession::inHost(), IP_DUMP, and show_drop.
 {
   IP_DUMP(printf("[host=\"%s\"] config().\n", inHost()->nhi.toString()));
   ProtocolSession::config(cfg);
   char* str = (char*) cfg->findSingle("show_drop");
   if(str)
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: IPSession::config(), invalid SHOW_DROP attribute.\n");
     if(!strcasecmp(str, "true")) show_drop = true;
     else if(!strcasecmp(str, "false")) show_drop = false;
     else error_quit("ERROR: IPSession::config(), invalid SHOW_DROP: %s.\n", str);
   }
 }
virtual int s3f::s3fnet::IPSession::getProtocolNumber () inline virtual
Return the protocol number.
This specifies the relationship between this protocol and the other protocols defined in the same protocol stack.
Implements s3f::s3fnet::ProtocolSession.
Definition at line 99 of file ip_session.h.
References s3f::s3fnet::S3FNET_PROTOCOL_TYPE_IPV4.
 { return S3FNET_PROTOCOL_TYPE_IPV4; }
void s3f::s3fnet::IPSession::init () virtual
Initialize the IP session.
This function will be called after the entire network is read in and configured and all the links are connected, but before the simulation starts running.
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 76 of file ip_session.cc.
References s3f::s3fnet::ForwardingTable::addListener(), s3f::s3fnet::IPPrefix::addr, s3f::s3fnet::ForwardingTable::addRoute(), s3f::s3fnet::RouteInfo::destination, s3f::s3fnet::error_quit(), forwarding_table, FT_ROUTE_SUCCESS, s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::IPPrefix::ip2txt(), IP_DUMP, IP_PROTOCOL_NAME, s3f::s3fnet::ProtocolSession::name, NET_PROTOCOL_NAME, and s3f::s3fnet::RouteInfo::resolve().
 {
     IP_DUMP(printf("[host=\"%s\"] init().\n", inHost()->nhi.toString()));
     ProtocolSession::init();
     if(strcasecmp(name, NET_PROTOCOL_NAME) && strcasecmp(name, IP_PROTOCOL_NAME))
       error_quit("ERROR: IpSession::init(), unmatched protocol name: \"%s\", expecting \"NET\" or \"IP\".\n", name);
     // create a forwarding table for this machine
     if(!forwarding_table)
       forwarding_table = new ForwardingTable(this);
     // we need to add those routes specified in DML file.
     if(route_vec)
     {
       int size = route_vec->size();
       for(int i = 0; i < size; i++)
       {
         RouteInfo* route = (*route_vec)[i]->resolve(inHost());
             if(route)
             {
               int ret = forwarding_table->addRoute(route);
               if(ret != FT_ROUTE_SUCCESS)
               {
                         fprintf(stderr, "IPSession::init(), duplicate route to \"%s\" on host nhi=\"%s\".\n",
                     IPPrefix::ip2txt(route->destination.addr), inHost()->nhi.toString());
               }
             }
       }
       // finally, remove the vector.
       delete route_vec;
       route_vec = 0;
     }
     if(dml_route_vec)
     {
       int size = dml_route_vec->size();
       for(int i = 0; i < size; i++)
       {
             // route type is static by default (ML)
             RouteInfo* route = (*dml_route_vec)[i]->resolve(inHost());
             if(route)
             {
               int ret = forwarding_table->addRoute(route);
               if(ret != FT_ROUTE_SUCCESS)
               {
                         fprintf(stderr, "IPSession::init(), duplicate route to \"%s\" on host nhi=\"%s\".\n",
                     IPPrefix::ip2txt(route->destination.addr), inHost()->nhi.toString());
               }
             }
       }
       // finally, remove the vector.
       for(int i = 0; i < size; i++) delete (*dml_route_vec)[i];
       delete dml_route_vec;
       dml_route_vec = 0;
     }
     if(listener_vec)
     {
       int size = listener_vec->size();
       for(int i = 0; i < size; i++)
       {
             ProtocolSession* sess = (*listener_vec)[i];
             forwarding_table->addListener(sess);
       }
       delete listener_vec;
       listener_vec = 0;
     }
 }
int s3f::s3fnet::IPSession::control (int ctrltyp, void * ctrlmsg, ProtocolSession * sess) virtual
The control method is used by the protocol session to receive control message (or query information) from adjacent protocol sessions both above and below.
The protocol session invoking this method will have a reference to itself in the third argument. The control messages are distinguished by types. The message type is an integer; its meaning is specified by the particular protocol. The control message is of type void* and should be cast to the appropriate types accordingly. Note that the caller is responsible to reclaim the control message once the method returns. The method returns an integer, indicating whether the control message is successfully processed. Unless specified otherwise, a zero means success. Nonzero means trouble and the returned value can be used as the error number, the meaning of which is specified by each particular protocol. The default behavior does nothing except returning zero.
[ctrltyp = IP_CTRL_VERIFY_LOCAL_ADDRESS]:
   ctrlmsg should be a pointer to a 32-bit destination address.
   if the returned value is 1, it means that it is a local ip address;
   if the returned value is 0, it means that it is not a local ip address.
   NOTE THIS METHOD DOES NOT CONFIRM TO THE ORIGINAL DESIGN PHYLOSOPHY;
   THE RETURN VALUE INDICATES WHETHER THE ADDRESS IS LOCAL, RATHER
   THAN WHETHER THE CONTROL CALL IS SUCCESSFUL.
[ctrltyp = IP_CTRL_GET_FORWARDING_TABLE]:
   ctrlmsg should be a pointer to a pointer to a forwarding table. The forwarding
   table of the host will be assigned to that point.
   0 is always returned.
[ctrltype = IP_CTRL_LOAD_FORWARDING_TABLE]:
   ctrlmsg is a pointer to the configuration. It forces the IP to create a forwarding table and
   read in the entries from the the configuraion. 0 is always returned.
[ctrltyp = IP_CTRL_INSERT_ROUTE]:
   ctrlmsg should be a pointer to a RouteInfo object. Insert the RouteInfo object
   to the forwarding table.
   0 is always returned.
[ctrltyp = IP_CTRL_DELETE_ROUTE]:
   ctrlmsg should be a pointer to a RouteInfo object. Delete the RouteInfo object
   from the forwarding table.
   0 is always returned.
[ctrltyp = IP_CTRL_INSERT_DMLROUTE]:
   ctrlmsg should be a pointer to a DMLRouteInfo object. Convert and insert the RouteInfo object
   to the forwarding table.
   0 is always returned.
[ctrltype = IP_CTRL_ADD_INTERCEPT_SESSION]:
   the caller will be set as the intercept session; there can be at most
   only one session that intercepts all pop up IP packets.
   return 0 if succeeded; abort on error.
[ctrltyp = IP_CTRL_PUSH_REQUEST]:
   ctrlmsg should be a pointer to an IPPushRequest object. The
   push method is called as if the message is pushed from the
   protocol session above IP.
[ctrltyp = IP_CTRL_ADD_FIB_LISTENTER]:
   set the caller to be the protocol session who wish to receive a
   notification upon changes to the forwarding table.
   0 is always returned.
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 148 of file ip_session.cc.
References s3f::s3fnet::ForwardingTable::addListener(), s3f::s3fnet::IPPrefix::addr, s3f::s3fnet::ForwardingTable::addRoute(), s3f::s3fnet::ProtocolSession::control(), s3f::s3fnet::RouteInfo::destination, s3f::s3fnet::error_quit(), forwarding_table, FT_ROUTE_NOT_FOUND, FT_ROUTE_SUCCESS, s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::IPPrefix::ip2txt(), s3f::s3fnet::IP_CTRL_ADD_FIB_LISTENER, s3f::s3fnet::IP_CTRL_ADD_INTERCEPT_SESSION, s3f::s3fnet::IP_CTRL_DELETE_ROUTE, s3f::s3fnet::IP_CTRL_GET_FORWARDING_TABLE, s3f::s3fnet::IP_CTRL_INSERT_DMLROUTE, s3f::s3fnet::IP_CTRL_INSERT_ROUTE, s3f::s3fnet::IP_CTRL_LOAD_FORWARDING_TABLE, s3f::s3fnet::IP_CTRL_PUSH_REQUEST, s3f::s3fnet::IP_CTRL_VERIFY_LOCAL_IP_ADDRESS, s3f::s3fnet::IP_CTRL_VERIFY_TARGET_IP_ADDRESS, IP_DUMP, load_forwarding_table(), s3f::s3fnet::IPPushRequest::msg, s3f::s3fnet::IPPushRequest::options, pop_intercept_sess, s3f::s3fnet::ProtocolSession::pushdown(), s3f::s3fnet::ForwardingTable::removeRoute(), s3f::s3fnet::RouteInfo::resolve(), s3f::s3fnet::DMLRouteInfo::resolve(), S3FNET_VECTOR(), verify_local_ip_address(), and verify_target_ip_address().
Referenced by load_forwarding_table().
 {
   IP_DUMP(printf("[host=\"%s\"] control(): type=%d.\n", inHost()->nhi.toString(), ctrltyp));
   switch(ctrltyp) {
   case IP_CTRL_VERIFY_TARGET_IP_ADDRESS: {
     // ctrlmsg should be a pointer to a 32-bit destination address.
     assert(ctrlmsg);
     return verify_target_ip_address(*((uint32*)ctrlmsg));
   }
   case IP_CTRL_VERIFY_LOCAL_IP_ADDRESS: {
     // ctrlmsg should be a pointer to a 32-bit destination address.
     assert(ctrlmsg);
     return verify_local_ip_address(*((uint32*)ctrlmsg));
   }
   case IP_CTRL_GET_FORWARDING_TABLE: {
     // ctrlmsg should be a pointer to a pointer to a forwarding table.
     assert(ctrlmsg);
     *((ForwardingTable**)ctrlmsg) = forwarding_table;
     return 0;
   }
   case IP_CTRL_LOAD_FORWARDING_TABLE: {
     assert(ctrlmsg);
     load_forwarding_table((s3f::dml::Configuration*)ctrlmsg);
     return 0;
   }
   case IP_CTRL_INSERT_ROUTE: {
     // ctrlmsg should be a pointer to a RouteInfo object.
     assert(ctrlmsg);
     RouteInfo* route = (RouteInfo*)ctrlmsg;
     if(forwarding_table)
     {
       if(route->resolve(inHost()))
       { // if resolved, it'll return itself
         int ret = forwarding_table->addRoute(route);
         if(ret != FT_ROUTE_SUCCESS)
         {
                   fprintf(stderr, "IPSession::control(IP_CTRL_INSERT_ROUTE), duplicate route to \"%s\".\n",
                   IPPrefix::ip2txt(route->destination.addr));
             }
       }
     }
     else
     {
       if(!route_vec) route_vec = new S3FNET_VECTOR(RouteInfo*);
       route_vec->push_back(route);
     }
     return 0;
   }
   case IP_CTRL_DELETE_ROUTE: {
     // ctrlmsg should be a pointer to a prefix.
     assert(ctrlmsg);
     RouteInfo* route = (RouteInfo*)ctrlmsg;
     if(forwarding_table)
     {
       if(route->resolve(inHost()))
       { // if resolved, it'll return itself
             int ret = forwarding_table->removeRoute(route);
             if(ret == FT_ROUTE_NOT_FOUND)
             {
               fprintf(stderr, "IPSession::control(IP_CTRL_DELETE_ROUTE), delete route to \"%s\" not found.\n",
                   IPPrefix::ip2txt(route->destination.addr));
             }
       }
     }
     else
     {
       fprintf(stderr, "IPSession::control(IP_CTRL_DELETE_ROUTE), delete route to \"%s\" from empty table.\n",
                   IPPrefix::ip2txt(route->destination.addr));
     }
     return 0;
   }
   case IP_CTRL_INSERT_DMLROUTE: {
     // ctrlmsg should be a pointer to a DMLRouteInfo object.
     assert(ctrlmsg);
     DMLRouteInfo* dml_route = (DMLRouteInfo*)ctrlmsg;
     if(forwarding_table)
     {
       RouteInfo* route = dml_route->resolve(inHost());
       if(route)
       {
             int ret = forwarding_table->addRoute(route);
             if(ret != FT_ROUTE_SUCCESS)
             {
                   fprintf(stderr, "IPSession::control(IP_CTRL_INSERT_DMLROUTE), duplicate route to \"%s\".\n",
                   IPPrefix::ip2txt(route->destination.addr));
             }
       }
       delete dml_route;
     }
     else
     {
       if(!dml_route_vec) dml_route_vec = new S3FNET_VECTOR(DMLRouteInfo*);
       dml_route_vec->push_back(dml_route);
     }
     return 0;
   }
   case IP_CTRL_ADD_INTERCEPT_SESSION: {
     if(pop_intercept_sess)
     {
       error_quit("ERROR: IPSession::control(), duplicate intercept session; only one allowed.\n");
     }
     else pop_intercept_sess = sess;
     return 0;
   }
   case IP_CTRL_PUSH_REQUEST: {
     IPPushRequest* req = (IPPushRequest*)ctrlmsg;
     assert(req && req->options && req->msg);
     return pushdown(req->msg, 0, req->options, sizeof(IPPushOption));
   }
   case IP_CTRL_ADD_FIB_LISTENER: {
     if(forwarding_table) forwarding_table->addListener(sess);
     else
     {
       if(!listener_vec) listener_vec = new S3FNET_VECTOR(ProtocolSession*);
       listener_vec->push_back(sess);
     }
     return 0;
   }
   default:
     return ProtocolSession::control(ctrltyp, ctrlmsg, sess);
   }
 }
int s3f::s3fnet::IPSession::strtonum (const char * str) inline static
Safe alternative to atoi() if valid numbers could be 0 (which atoi() returns on error).
Definition at line 611 of file ip_session.cc.
Referenced by load_forwarding_table().
{
     std::istringstream iss(str);
     int res;
     iss >> std::ws >> res >> std::ws;
     if(!iss.eof()) {
                 return -1;
         }
     return res;
 }
void s3f::s3fnet::IPSession::print_payload (const u_char * payload, int len)
print packet payload data (avoid printing binary data)
Definition at line 668 of file ip_session.cc.
References print_hex_ascii_line().
 {
         int len_rem = len;
         int line_width = 16;                    /* number of bytes per line */
         int line_len;
         int offset = 0;                                 /* zero-based offset counter */
         const u_char *ch = payload;
         if (len <= 0)
                 return;
         /* data fits on one line */
         if (len <= line_width) {
                 print_hex_ascii_line(ch, len, offset);
                 return;
         }
         /* data spans multiple lines */
         for ( ;; ) {
                 /* compute current line length */
                 line_len = line_width % len_rem;
                 /* print line */
                 print_hex_ascii_line(ch, line_len, offset);
                 /* compute total remaining */
                 len_rem = len_rem - line_len;
                 /* shift pointer to remaining bytes to print */
                 ch = ch + line_len;
                 /* add offset */
                 offset = offset + line_width;
                 /* check if we have line width chars or less */
                 if (len_rem <= line_width) {
                         /* print last line and get out */
                         print_hex_ascii_line(ch, len_rem, offset);
                         break;
                 }
         }
 }
void s3f::s3fnet::IPSession::print_hex_ascii_line (const u_char * payload, int len, int offset)
Print data in rows of 16 bytes in the format (offset hex ascii).
47 45 54 20 2f 20 48 54 54 50 2f 31 2e 31 0d 0a GET / HTTP/1.1..
Definition at line 624 of file ip_session.cc.
Referenced by print_payload().
 {
         int i;
         int gap;
         const u_char *ch;
         /* offset */
         printf("%05d   ", offset);
         /* hex */
         ch = payload;
         for(i = 0; i < len; i++) {
                 printf("%02x ", *ch);
                 ch++;
                 /* print extra space after 8th byte for visual aid */
                 if (i == 7)
                         printf(" ");
         }
         /* print space to handle line less than 8 bytes */
         if (len < 8)
                 printf(" ");
         /* fill hex gap with spaces if not full line */
         if (len < 16) {
                 gap = 16 - len;
                 for (i = 0; i < gap; i++) {
                         printf("   ");
                 }
         }
         printf("   ");
         /* ascii (if printable) */
         ch = payload;
         for(i = 0; i < len; i++) {
                 if (isprint(*ch))
                         printf("%c", *ch);
                 else
                         printf(".");
                 ch++;
         }
         printf("\n");
 }
int s3f::s3fnet::IPSession::push (Activation msg, ProtocolSession * hi_sess, void * extinfo = 0, size_t extinfo_size = 0) private virtual
Send a message down the protocol stack to lower layer.
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 282 of file ip_session.cc.
References s3f::s3fnet::ProtocolMessage::carryPayload(), DEFAULT_IP_TIMETOLIVE, s3f::s3fnet::IPPushOption::dst_ip, s3f::s3fnet::IPMessage::dst_ip, s3f::s3fnet::IPOptionToAbove::dst_ip, Message::erase_all(), forwarding_table, s3f::s3fnet::NetworkInterface::getHighestProtocolSession(), s3f::s3fnet::NetworkInterface::getIP(), s3f::s3fnet::Host::getNetworkInterface(), s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ForwardingTable::getRoute(), s3f::s3fnet::IPPushOption::iface_id, s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::IPPrefix::ip2txt(), IP_DUMP, s3f::s3fnet::IPADDR_INADDR_ANY, IPPUSHRET_DOWN_DONE, IPPUSHRET_DROPPED_TTL_LIMIT, IPPUSHRET_NO_ROUTE, IPPUSHRET_TO_LOCAL_DONE, IPPUSHRET_TO_LOCAL_FAIL, s3f::s3fnet::RouteInfo::nic, s3f::s3fnet::ProtocolSession::popup(), s3f::s3fnet::IPPushOption::prot_id, s3f::s3fnet::ProtocolSession::pushdown(), show_drop, s3f::s3fnet::IPPushOption::src_ip, s3f::s3fnet::IPMessage::src_ip, s3f::s3fnet::IPOptionToAbove::src_ip, s3f::s3fnet::ProtocolMessage::totalRealBytes(), s3f::s3fnet::IPPushOption::ttl, s3f::s3fnet::IPOptionToAbove::ttl, and verify_local_ip_address().
 {
         assert(msg);
         assert(extinfo_size == sizeof(IPPushOption));
         IPPushOption* pushopt = (IPPushOption*)extinfo;
         // handle the case that the packet is sent to itself
         if(verify_local_ip_address(pushopt->dst_ip))
         {
                 if(hi_sess)
                 {
                         // if the protocol is found on local stack
                         IP_DUMP(printf("[host=\"%s\"] %s: send itself a packet for protocol %u.\n",
                                         inHost()->nhi.toString(), getNowWithThousandSeparator(), pushopt->prot_id));
                         // extended information for ip address information
                         IPOptionToAbove ipupopt;
                         ipupopt.src_ip = pushopt->src_ip;
                         ipupopt.dst_ip = pushopt->dst_ip;
                         ipupopt.ttl = DEFAULT_IP_TIMETOLIVE;
                         // if the upper layer has not set the source ip address, reset
                         // it to the same as the destination.
                         if(IPADDR_INADDR_ANY == ipupopt.src_ip) ipupopt.src_ip = ipupopt.dst_ip;
                         hi_sess->popup(msg, this, (void*)&ipupopt, sizeof(IPOptionToAbove));
                         return IPPUSHRET_TO_LOCAL_DONE;
                 }
                 else
                 {
                         // no such protocol, drop the packet directly (no need for icmp)
                         if(show_drop)
{
                                 printf("[host=\"%s\"] %s: drop a local packet of missing protocol %u.\n",
                                                 inHost()->nhi.toString(), getNowWithThousandSeparator(), pushopt->prot_id);
                         }
                         msg->erase_all();
                         return IPPUSHRET_TO_LOCAL_FAIL;
                 }
         } // end of the send-to-self case
         if(pushopt->ttl == 0) //Reach TTL limit
         {
                 if(show_drop)
                 {
                         printf("[host=\"%s\"] %s: drop packet due to ttl.\n", inHost()->nhi.toString(), getNowWithThousandSeparator());
                 }
                 msg->erase_all();
                 return IPPUSHRET_DROPPED_TTL_LIMIT;
         }
         // figure out the outgoing interface in case it's not specified
         NetworkInterface* outgoing_nic = 0;
         void* route_info = 0;
         if(inHost()->isOpenVZEmu() == true) // outgoing_nic is obtained from the interface id info in EmuPacket
         {
                 //default iface_id is 0
                 outgoing_nic = inHost()->getNetworkInterface(pushopt->iface_id);
         }
         else
         {
                 assert(forwarding_table);
                 RouteInfo* pRoute = forwarding_table->getRoute(pushopt->dst_ip);
                 if(0 == pRoute)
                 {
                         if(show_drop)
{
                                 printf("[host=\"%s\"] %s: no route to \"%s\", dropping Packet.\n",
                                                 inHost()->nhi.toString(), getNowWithThousandSeparator(), IPPrefix::ip2txt(pushopt->dst_ip));
                         }
                         msg->erase_all();
                         return IPPUSHRET_NO_ROUTE;
                 }
                 outgoing_nic = pRoute->nic;
                 route_info = (void*)pRoute;
         }
         assert(outgoing_nic);
         /* Figure out the source ip address and destination ip address.
          * If the src ip address designated by the upper layer is INADDR_ANY,
          * it will be changed as the network interface's ip address.*/
         IPADDR src_ip;
         if(IPADDR_INADDR_ANY == pushopt->src_ip) src_ip = outgoing_nic->getIP();
         else src_ip = pushopt->src_ip;
         // create ip_msg (ip header and upper layer msg as payload)
         // note: IP header is not needed for pure emulation case (i.e., every host/switch/router entity is attached to an openVZ-based VE), but it is needed for mixed sim/emu case
         IPMessage* ip_message = new IPMessage(src_ip, pushopt->dst_ip, pushopt->prot_id, pushopt->ttl);
         ip_message->carryPayload((ProtocolMessage*)msg);
         Activation ip_msg (ip_message);
         // send the packet to the outgoing_mac
         ProtocolSession* outgoing_mac = outgoing_nic->getHighestProtocolSession();
         if(inHost()->isOpenVZEmu() == true)
         {
                 IP_DUMP(char s1[50]; char s2[50];
                 printf("IPSession::push(), [host=\"%s\"] %s: send packet from \"%s\" [interface %d] to \"%s\" (%d real bytes) .\n",
                                 inHost()->nhi.toString(), getNowWithThousandSeparator(),
                                 IPPrefix::ip2txt(src_ip, s1),
                                 pushopt->iface_id,
                                 IPPrefix::ip2txt(pushopt->dst_ip, s2),
                                 ((OpenVZMessage*)msg)->totalRealBytes()););
                 outgoing_mac->pushdown(ip_msg, this);
         }
         else
         {
                 IP_DUMP(char s1[50]; char s2[50];
                 printf("[host=\"%s\"] %s: send packet from \"%s\" to \"%s\" (%d real bytes).\n",
                                 inHost()->nhi.toString(), getNowWithThousandSeparator(),
                                 IPPrefix::ip2txt(ip_message->src_ip, s1),
                                 IPPrefix::ip2txt(ip_message->dst_ip, s2),
                                 ip_message->totalRealBytes()););
                 IPOptionToBelow mac_ext_info(route_info, false);
                 outgoing_mac->pushdown(ip_msg, this, (void*)&mac_ext_info, sizeof(IPOptionToBelow));
         }
         return IPPUSHRET_DOWN_DONE;
 }
int s3f::s3fnet::IPSession::pop (Activation msg, ProtocolSession * lo_sess, void * extinfo = 0, size_t extinfo_size = 0) private virtual
Receive data up the protocol stack to the upper layer.
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 410 of file ip_session.cc.
References s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), handle_pop_pkt(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::IPPrefix::ip2txt(), and IP_DUMP.
 {
   assert(lo_sess);
   IP_DUMP(char buf1[50]; char buf2[50];
                   printf("[host=\"%s\"] %s: pop() receive packet from \"%s\" to \"%s\".\n",
                                   inHost()->nhi.toString(), getNowWithThousandSeparator(),
                                   IPPrefix::ip2txt(((IPMessage*)msg)->src_ip, buf1),
                                   IPPrefix::ip2txt(((IPMessage*)msg)->dst_ip, buf2)));
   // perform checksum -- add later
   return handle_pop_pkt(msg, lo_sess, extinfo, extinfo_size);
 }
bool s3f::s3fnet::IPSession::verify_target_ip_address (IPADDR ipaddr) protected
Verify whether an ip address is acceptable by local ip or not.
Definition at line 429 of file ip_session.cc.
References IPADDR_ANYDEST, and verify_local_ip_address().
Referenced by control(), and handle_pop_pkt().
 {
   if(ipaddr == IPADDR_ANYDEST || (ipaddr & 0xe0000000) || verify_local_ip_address(ipaddr))
         return true;
   else
         return false;
 }
bool s3f::s3fnet::IPSession::verify_local_ip_address (IPADDR ipaddr) protected
Verify whether an ip address is local or not.
Definition at line 423 of file ip_session.cc.
References s3f::s3fnet::ProtocolSession::inHost().
Referenced by control(), push(), and verify_target_ip_address().
 {
   if(inHost()->getNetworkInterfaceByIP(ipaddr)) return true;
   else return false;
 }
void s3f::s3fnet::IPSession::load_forwarding_table (s3f::dml::Configuration * cfg) protected
Load forwarding table.
Definition at line 437 of file ip_session.cc.
References s3f::s3fnet::RouteInfo::config(), s3f::s3fnet::DMLRouteInfo::config(), control(), s3f::s3fnet::error_quit(), forwarding_table, s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::IP_CTRL_INSERT_DMLROUTE, s3f::s3fnet::IP_CTRL_INSERT_ROUTE, and strtonum().
Referenced by control().
 {
         if (!forwarding_table) {
                 int trie_version = -1;
                 char* str = (char*)cfg->findSingle("trie_version");
                 if (str && !(s3f::dml::dmlConfig::isConf(str))) {
                         trie_version = strtonum(str);
                         if(trie_version < 0) {
                                 error_quit("ERROR: trie_version attribute must be >= 0.\n");
                         }
                 }
                 int cache_version = -1;
                 str = (char*)cfg->findSingle("cache_version");
                 if (str && !(s3f::dml::dmlConfig::isConf(str))) {
                         cache_version = strtonum(str);
                         if(cache_version < 0) {
                                 error_quit("ERROR: cache_version attribute must be >= 0.\n");
                         }
                 }
                 forwarding_table = new ForwardingTable(this,trie_version,cache_version);
                 assert(forwarding_table);
         }
   Host* h = inHost();
   s3f::dml::Enumeration* renum = cfg->find("route");
   while (renum->hasMoreElements())
   {
     s3f::dml::Configuration* rcfg = (s3f::dml::Configuration*)renum->nextElement();
     if(!s3f::dml::dmlConfig::isConf(rcfg))
       error_quit("ERROR: IPSession::load_forwarding_table(), invalid ROUTE attribute.\n");
     RouteInfo* route = new RouteInfo();
     route->config(h, rcfg);
     control(IP_CTRL_INSERT_ROUTE, route, NULL);
   }
   delete renum;
   s3f::dml::Enumeration* denum = cfg->find("nhi_route");
   while(denum->hasMoreElements())
   {
     s3f::dml::Configuration* rcfg = (s3f::dml::Configuration*)denum->nextElement();
     if(!s3f::dml::dmlConfig::isConf(rcfg))
       error_quit("ERROR: IPSession::load_forwarding_table(), invalid DML_ROUTE attribute.\n");
     DMLRouteInfo* dml_route = new DMLRouteInfo;
     dml_route->config(rcfg);
     control(IP_CTRL_INSERT_DMLROUTE, dml_route, NULL);
   }
   delete denum;
 }
ProtocolSession * s3f::s3fnet::IPSession::get_parent_by_protocol (uint32 protocol) protected
Find parent by protocol number.
Definition at line 489 of file ip_session.cc.
References s3f::s3fnet::ProtocolSession::inHost(), and s3f::s3fnet::ProtocolGraph::sessionForNumber().
Referenced by handle_pop_local_pkt().
 {
   return inHost()->sessionForNumber(protocol_no);
 }
int s3f::s3fnet::IPSession::handle_pop_pkt (Activation ip_msg, ProtocolSession * lo_sess, void * extinfo = NULL, int extinfo_size = 0) protected
Handle packets that are popped up.
Definition at line 494 of file ip_session.cc.
References s3f::s3fnet::IPMessage::dst_ip, s3f::s3fnet::ProtocolMessage::erase_all(), forwarding_table, s3f::s3fnet::NetworkInterface::getHighestProtocolSession(), s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ForwardingTable::getRoute(), handle_pop_local_pkt(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::IPPrefix::ip2txt(), IP_DUMP, IPPOPRET_DROPPED_NO_ROUTE, IPPOPRET_DROPPED_TTL_LIMIT, IPPOPRET_FORWARD_DONE, s3f::s3fnet::Host::isOpenVZEmu(), s3f::s3fnet::RouteInfo::nic, s3f::s3fnet::IPMessage::protocol_no, s3f::s3fnet::ProtocolSession::pushdown(), show_drop, s3f::s3fnet::IPMessage::src_ip, s3f::s3fnet::IPMessage::time_to_live, and verify_target_ip_address().
Referenced by pop().
 {
   IPMessage* ip_message = (IPMessage*)ip_msg;
   // decrement the time-to-live field of the packet
   ip_message->time_to_live--;
   // if packet is for me deliver it to proper protocol
   if(verify_target_ip_address(ip_message->dst_ip) || inHost()->isOpenVZEmu() == true)
   {
     return handle_pop_local_pkt(ip_msg, lo_sess);
   }
   else
   {
     // otherwise just send the packet on its way further
     IP_DUMP(printf("[host=\"%s\"] %s: received a packet but not for me.\n",
                 inHost()->nhi.toString(), getNowWithThousandSeparator()));
     if(ip_message->time_to_live > 0)
     {
       // figure out the outgoing interface
       NetworkInterface* outgoing_nic = 0;
       void* carried_route_info = 0;
           // on_demand_routing is turned off, find the route for the destination
           RouteInfo* pRoute = forwarding_table->getRoute(ip_message->dst_ip);
           if(0 == pRoute)
           {
               if(show_drop)
               {
                 char s1[50]; char s2[50];
                 printf("[host=\"%s\"] %s: drop packet from \"%s\" to \"%s\" (no route).\n",
                      inHost()->nhi.toString(), getNowWithThousandSeparator(),
                      IPPrefix::ip2txt(ip_message->src_ip, s1),
                      IPPrefix::ip2txt(ip_message->dst_ip, s2));
               }
               ip_message->erase_all();
             return IPPOPRET_DROPPED_NO_ROUTE;
           }
           IP_DUMP(char s1[50]; char s2[50];
           printf("[host=\"%s\"] %s: forward packet from \"%s\" to \"%s\" for protocol %d.\n",
                        inHost()->nhi.toString(), getNowWithThousandSeparator(),
                        IPPrefix::ip2txt(ip_message->src_ip, s1),
                        IPPrefix::ip2txt(ip_message->dst_ip, s2), ip_message->protocol_no));
           outgoing_nic = pRoute->nic;
           carried_route_info = (void*)pRoute;
       assert(outgoing_nic);
       IPOptionToBelow mac_ext_info(carried_route_info, true);
       outgoing_nic->getHighestProtocolSession()->pushdown(ip_msg, this, (void*)&mac_ext_info, sizeof(IPOptionToBelow));
       return IPPOPRET_FORWARD_DONE;
     }
     else
     {
         if(show_drop)
         {
               char s1[50]; char s2[50];
               printf("[host=\"%s\"] %s: drop packet from \"%s\" to \"%s\" (ttl expires).\n",
                           inHost()->nhi.toString(), getNowWithThousandSeparator(),
                           IPPrefix::ip2txt(ip_message->src_ip, s1),
                           IPPrefix::ip2txt(ip_message->dst_ip, s2));
         }
       ip_message->erase_all();
       return IPPOPRET_DROPPED_TTL_LIMIT;
     }
   }
 }
int s3f::s3fnet::IPSession::handle_pop_local_pkt (Activation msg, ProtocolSession * lo_sess, void * extinfo = NULL, int extinfo_size = 0) protected
Handle packets that are popped up and targetted to this machine.
Definition at line 567 of file ip_session.cc.
References s3f::s3fnet::ProtocolMessage::dropPayload(), s3f::s3fnet::IPMessage::dst_ip, s3f::s3fnet::IPOptionToAbove::dst_ip, s3f::s3fnet::ProtocolMessage::erase(), s3f::s3fnet::ProtocolMessage::erase_all(), get_parent_by_protocol(), s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::IPPrefix::ip2txt(), IP_DUMP, IPPOPRET_DROPPED_NO_PROTOCOL, IPPOPRET_UP_DONE, s3f::s3fnet::ProtocolSession::popup(), s3f::s3fnet::IPMessage::protocol_no, show_drop, s3f::s3fnet::IPMessage::src_ip, s3f::s3fnet::IPOptionToAbove::src_ip, s3f::s3fnet::IPMessage::time_to_live, and s3f::s3fnet::IPOptionToAbove::ttl.
Referenced by handle_pop_pkt().
 {
   IPMessage* ip_message = (IPMessage*)msg;
   ProtocolSession* prot = get_parent_by_protocol((int)(uint32)ip_message->protocol_no);
   IP_DUMP(printf("[host=\"%s\"] %s: receive local packet for protocol %u.\n",
                  inHost()->nhi.toString(), getNowWithThousandSeparator(), ip_message->protocol_no));
   // send the packet upward
   int ret_val;
   if(prot)
   {
       IPOptionToAbove ipupopt;
       ipupopt.src_ip = ip_message->src_ip;
       ipupopt.dst_ip = ip_message->dst_ip;
       ipupopt.ttl = ip_message->time_to_live;
       ProtocolMessage* pmsg = ip_message->dropPayload();
       assert(pmsg);
       Activation upper_msg (pmsg);
       ip_message->erase(); //delete IP header
       prot->popup(upper_msg, this, (void*)&ipupopt, sizeof(IPOptionToAbove));
       ret_val = IPPOPRET_UP_DONE;
   }
   else
   {
       if(show_drop)
       {
         char s1[50]; char s2[50];
         printf("[host=\"%s\"] %s: drop packet from \"%s\" to \"%s\" (no protocol)\n",
                         inHost()->nhi.toString(), getNowWithThousandSeparator(),
                         IPPrefix::ip2txt(ip_message->src_ip, s1),
                         IPPrefix::ip2txt(ip_message->dst_ip, s2));
       }
     // no such protocol! drop the packet
     ip_message->erase_all();
     ret_val = IPPOPRET_DROPPED_NO_PROTOCOL;
   }
   return ret_val;
 }
s3f::s3fnet::IPSession::S3FNET_VECTOR (RouteInfo *) private
Route specified in dml file.
Referenced by control().
s3f::s3fnet::IPSession::S3FNET_VECTOR (DMLRouteInfo *) private
s3f::s3fnet::IPSession::S3FNET_VECTOR (ProtocolSession *) private
void s3f::s3fnet::ProtocolSession::wrapup () virtual inherited
The method is used to wrap up the protocol session.
It is called when the simulation finishes. It is designed to give user a chance to report simulation statistics. The default behavior is doing nothing. Subclass may override this method for protocol specific dealings. Note that there is no specific order in which wrapup is called for protocol sessions in a protocol graph.
Definition at line 59 of file protocol_session.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolSession::initialized(), s3f::s3fnet::ProtocolSession::name, s3f::s3fnet::ProtocolSession::PSESS_WRAPPED_UP, s3f::s3fnet::ProtocolSession::stage, and s3f::s3fnet::ProtocolSession::wrapped_up().
 {
   // Make sure this init function at the base class should be called
   // by the derived function!
   if(!initialized())
     error_quit("ERROR: ProtocolSession \"%s\" wrapup() called before init(), "
                "forgot to call base class's init() in your derived class?\n", name);
   else if(wrapped_up())
     error_quit("ERROR: duplicate calls to ProtocolSession::wrapup(): "
                "session name is \"%s\".\n", name);
   else stage = PSESS_WRAPPED_UP;
 }
int s3f::s3fnet::ProtocolSession::pushdown (Activation msg, ProtocolSession * hi_sess, void * extinfo = 0, size_t extinfo_size = 0) inherited
The original push method is divided into pushdown() and push().
The pushdown method is the generic part of the code, which is reserved for modeling the handling of messages transferred between protocol layers.
See Also
ProtocolSession::push method for details.
Definition at line 72 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::push().
Referenced by s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), control(), handle_pop_pkt(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), s3f::s3fnet::OpenFlowSwitchSession::OutputControl(), s3f::s3fnet::OpenFlowSwitchSession::OutputPacket(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::UDPMaster::push(), s3f::s3fnet::TCPMaster::push(), push(), s3f::s3fnet::UDPSession::send(), and s3f::s3fnet::TCPSession::send_data().
 {
   return push(msg, hi_sess, extinfo, extinfo_size);
 }
int s3f::s3fnet::ProtocolSession::popup (Activation msg, ProtocolSession * lo_sess, void * extinfo = 0, size_t extinfo_size = 0) inherited
The original pop method is divided into popup() and pop().
The popup method is the generic part of the code, which is reserved for modeling the handling of messages transferred between protocol layers.
See Also
ProtocolSession::pop method for details.
Definition at line 77 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::pop().
Referenced by handle_pop_local_pkt(), s3f::s3fnet::SimpleMac::pop(), push(), and s3f::s3fnet::SimplePhy::receivePacket().
 {
   return pop(msg, lo_sess, extinfo, extinfo_size);
 }
ProtocolGraph* s3f::s3fnet::ProtocolSession::inGraph () inline inherited
The method returns the protocol graph in which this protocol session resides.
Definition at line 178 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::ingraph.
Referenced by s3f::s3fnet::SimplePhy::config(), s3f::s3fnet::SimplePhy::control(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::SimpleMac::init(), s3f::s3fnet::SimplePhy::init(), s3f::s3fnet::RedQueue::init(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::SimplePhy::push(), s3f::s3fnet::SimplePhy::receivePacket(), s3f::s3fnet::SimplePhy::sendPacket(), s3f::s3fnet::SimpleMac::SimpleMac(), s3f::s3fnet::SimplePhy::SimplePhy(), s3f::s3fnet::SimpleMac::~SimpleMac(), and s3f::s3fnet::SimplePhy::~SimplePhy().
 { return ingraph; }
Host * s3f::s3fnet::ProtocolSession::inHost () virtual inherited
Return a pointer to the host owning this protocol session.
Reimplemented in s3f::s3fnet::NicProtocolSession.
Definition at line 118 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::ingraph.
Referenced by s3f::s3fnet::UDPSession::abort(), s3f::s3fnet::SocketMaster::abort(), s3f::s3fnet::NBSocketMaster::abort(), s3f::s3fnet::SocketMaster::accept(), s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::accept1a(), s3f::s3fnet::SocketMaster::accept1b(), s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SocketMaster::accept2b(), s3f::s3fnet::OpenFlowSwitchSession::AddFlow(), s3f::s3fnet::TCPSession::backoff_timeout(), s3f::s3fnet::SocketMaster::bind(), s3f::s3fnet::NBSocketMaster::bind(), s3f::s3fnet::SocketMaster::block_till(), s3f::s3fnet::NBSocketMaster::block_till(), s3f::s3fnet::BTCPClientSession::BTCPClientSession(), s3f::s3fnet::OpenFlowSwitchSession::BufferFromPacket(), s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::UDPServerSession::client_connected(), s3f::s3fnet::SocketMaster::close(), s3f::s3fnet::NBSocketMaster::close(), s3f::s3fnet::SocketMaster::close1(), s3f::s3fnet::NBSocketMaster::close1(), s3f::s3fnet::UDPMaster::config(), s3f::s3fnet::DummySession::config(), s3f::s3fnet::TCPClientSession::config(), s3f::s3fnet::UDPServerSession::config(), s3f::s3fnet::UDPClientSession::config(), s3f::s3fnet::TCPServerSession::config(), s3f::s3fnet::TCPMaster::config(), s3f::s3fnet::NBTCPClientSession::config(), s3f::s3fnet::BTCPClientSession::config(), config(), s3f::s3fnet::NBTCPServerSession::config(), s3f::s3fnet::UDPSession::connect(), s3f::s3fnet::SocketMaster::connect(), s3f::s3fnet::NBSocketMaster::connect(), s3f::s3fnet::SocketMaster::connect1(), s3f::s3fnet::NBSocketMaster::connect1(), s3f::s3fnet::SocketMaster::connected(), s3f::s3fnet::NBSocketMaster::connected(), s3f::s3fnet::UDPMaster::control(), s3f::s3fnet::SocketMaster::control(), s3f::s3fnet::NBSocketMaster::control(), control(), s3f::s3fnet::TCPMaster::createSession(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::UDPServerSession::data_sent(), s3f::s3fnet::TCPServerSession::data_sent(), s3f::s3fnet::UDPSession::disconnect(), s3f::s3fnet::TCPMaster::enableFastTimeout(), s3f::s3fnet::SocketMaster::eof(), s3f::s3fnet::NBSocketMaster::eof(), s3f::s3fnet::UDPClientSessionContinuation::failure(), s3f::s3fnet::UDPServerSessionContinuation::failure(), s3f::s3fnet::TCPServerSessionContinuation::failure(), s3f::s3fnet::TCPClientSessionContinuation::failure(), s3f::s3fnet::BTCPClientSessionContinuation::failure(), s3f::s3fnet::TCPMaster::fast_timer_callback_body(), s3f::s3fnet::Stats::FlowStatsDump(), s3f::s3fnet::OpenFlowSwitchSession::FlowTableLookup(), get_parent_by_protocol(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::ProtocolSession::getNow(), s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), handle_pop_local_pkt(), handle_pop_pkt(), s3f::s3fnet::OpenFlowSwitchSession::HandleControlInput(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), s3f::s3fnet::DummySession::init(), s3f::s3fnet::UDPMaster::init(), s3f::s3fnet::OpenFlowControllerSession::init(), s3f::s3fnet::OpenVZEventSession::init(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPServerSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::TCPServerSession::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::OpenFlowSwitchSession::init(), s3f::s3fnet::NBTCPClientSession::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::SocketMaster::init(), init(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::NBSocketMaster::init(), s3f::s3fnet::NBTCPServerSession::init(), s3f::s3fnet::TCPSession::init_state_closed(), s3f::s3fnet::OpenVZEventSession::injectEvent(), IPSession(), s3f::s3fnet::UDPSession::listen(), s3f::s3fnet::SocketMaster::listen(), s3f::s3fnet::NBSocketMaster::listen(), load_forwarding_table(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), s3f::s3fnet::OpenFlowSwitchSession::ModFlow(), s3f::s3fnet::NBSocketMaster::NBSocketMaster(), s3f::s3fnet::NBTCPClientSession::NBTCPClientSession(), s3f::s3fnet::NBTCPServerSession::NBTCPServerSession(), s3f::s3fnet::NBTCPClientSession::non_blocking_loop(), s3f::s3fnet::NBTCPServerSession::non_blocking_loop(), s3f::s3fnet::OpenFlowSwitchSession::OutputControl(), s3f::s3fnet::OpenFlowSwitchSession::OutputPacket(), s3f::s3fnet::OpenFlowSwitchSession::OutputPort(), s3f::s3fnet::OpenFlowControllerSession::pop(), s3f::s3fnet::UDPMaster::pop(), s3f::s3fnet::OpenVZEventSession::pop(), s3f::s3fnet::OpenFlowSwitchSession::pop(), s3f::s3fnet::TCPMaster::pop(), pop(), s3f::s3fnet::LearningController::process_recv_packet(), s3f::s3fnet::UDPMaster::push(), s3f::s3fnet::TCPMaster::push(), push(), s3f::s3fnet::UDPSession::receive(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::LearningControllerSession::ReceiveFromSwitch(), s3f::s3fnet::OpenFlowSwitchSession::ReceivePacketOut(), s3f::s3fnet::OpenFlowSwitchSession::ReceivePortMod(), s3f::s3fnet::OpenFlowSwitchSession::ReceiveStatsRequest(), s3f::s3fnet::SocketMaster::recv(), s3f::s3fnet::NBSocketMaster::recv(), s3f::s3fnet::SocketMaster::recv1(), s3f::s3fnet::NBSocketMaster::recv1(), s3f::s3fnet::UDPServerSession::request_received(), s3f::s3fnet::TCPServerSession::request_received(), s3f::s3fnet::UDPClientSession::request_sent(), s3f::s3fnet::TCPClientSession::request_sent(), s3f::s3fnet::NBTCPClientSessionContinuation::resume(), s3f::s3fnet::NBTCPServerSessionContinuation::resume(), s3f::s3fnet::OpenFlowSwitchSession::RunThroughFlowTable(), s3f::s3fnet::UDPSession::send(), s3f::s3fnet::SocketMaster::send(), s3f::s3fnet::NBSocketMaster::send(), s3f::s3fnet::SocketMaster::send1(), s3f::s3fnet::NBSocketMaster::send1(), s3f::s3fnet::TCPSession::send_data(), s3f::s3fnet::OpenFlowSwitchSession::SendFlowExpired(), s3f::s3fnet::OpenFlowSwitchSession::SendOpenflowBuffer(), s3f::s3fnet::OpenFlowSwitchSession::SendPortStatus(), s3f::s3fnet::UDPClientSession::server_connected(), s3f::s3fnet::TCPClientSession::server_connected(), s3f::s3fnet::BTCPClientSession::server_connected(), s3f::s3fnet::UDPServerSession::session_closed(), s3f::s3fnet::UDPClientSession::session_closed(), s3f::s3fnet::TCPClientSession::session_closed(), s3f::s3fnet::TCPServerSession::session_closed(), s3f::s3fnet::BTCPClientSession::session_closed(), s3f::s3fnet::TCPMaster::setConnected(), s3f::s3fnet::OpenFlowSwitchSession::SetController(), s3f::s3fnet::TCPMaster::setIdle(), s3f::s3fnet::TCPMaster::setListening(), s3f::s3fnet::UDPSession::setSource(), s3f::s3fnet::TCPMaster::slow_timer_callback_body(), s3f::s3fnet::TCPSession::slowTimeoutHandling(), s3f::s3fnet::SocketMaster::socket(), s3f::s3fnet::NBSocketMaster::socket(), s3f::s3fnet::SocketMaster::SocketMaster(), s3f::s3fnet::UDPServerSession::start_on(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPServerSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), s3f::s3fnet::NBTCPClientSession::start_on(), s3f::s3fnet::BTCPClientSession::start_on(), s3f::s3fnet::NBTCPServerSession::start_on(), s3f::s3fnet::NBTCPServerSessionContinuation::success(), s3f::s3fnet::TCPClientSession::TCPClientSession(), s3f::s3fnet::TCPMaster::TCPMaster(), s3f::s3fnet::TCPServerSession::TCPServerSession(), s3f::s3fnet::TCPSession::TCPSession(), s3f::s3fnet::UDPClientSession::timeout(), s3f::s3fnet::TCPClientSession::timeout(), s3f::s3fnet::BTCPClientSession::timeout(), s3f::s3fnet::UDPClientSession::UDPClientSession(), s3f::s3fnet::UDPMaster::UDPMaster(), s3f::s3fnet::UDPServerSession::UDPServerSession(), s3f::s3fnet::UDPSession::UDPSession(), s3f::s3fnet::TCPSession::update_timeout(), verify_local_ip_address(), and s3f::s3fnet::UDPSession::wake_app().
 {
   return dynamic_cast<Host*>(ingraph);
 }
Random::RNG* s3f::s3fnet::ProtocolSession::getRandom () inline inherited
The method returns a pointer to the random number generator.
Definition at line 200 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::sess_rng.
Referenced by s3f::s3fnet::DroptailQueue::calibrate(), s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::DummySession::init(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), and s3f::s3fnet::NetworkInterface::receivePacket().
 { return sess_rng;}
ltime_t s3f::s3fnet::ProtocolSession::getNow () inherited
The method returns the current simulation time.
To be safe, please do NOT call this function after initialization and before wrapup phase. That is, it is unsafe to call this method in the constructor, destructor, config, init, and wrapup methods. The time service is carried out by the host's owner community. This method just directs the call to the community. It's given here for convenience.
Definition at line 123 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::inHost(), and Entity::now().
Referenced by s3f::s3fnet::DroptailQueue::calibrate(), s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::TCPMaster::enableFastTimeout(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::TCPMaster::fast_timer_callback_body(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::TCPSession::now(), s3f::s3fnet::OpenVZEventSession::pop(), s3f::s3fnet::TCPMaster::slow_timer_callback_body(), s3f::s3fnet::SocketMaster::socket(), s3f::s3fnet::NBSocketMaster::socket(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), and s3f::s3fnet::BTCPClientSession::start_on().
 {
   return inHost()->now();
 }
char * s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator () inherited
For printing the current simulation time in a better readable format.
Definition at line 128 of file protocol_session.cc.
References s3f::s3fnet::Host::getNowWithThousandSeparator(), and s3f::s3fnet::ProtocolSession::inHost().
Referenced by s3f::s3fnet::UDPSession::abort(), s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::UDPSession::connect(), s3f::s3fnet::TCPMaster::createSession(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::UDPServerSession::data_sent(), s3f::s3fnet::TCPServerSession::data_sent(), s3f::s3fnet::UDPSession::disconnect(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), handle_pop_local_pkt(), handle_pop_pkt(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::UDPSession::listen(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), s3f::s3fnet::DummySession::pop(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::OpenVZEventSession::pop(), s3f::s3fnet::UDPMaster::pop(), s3f::s3fnet::TCPMaster::pop(), pop(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::UDPMaster::push(), s3f::s3fnet::SimplePhy::push(), s3f::s3fnet::TCPMaster::push(), push(), s3f::s3fnet::UDPSession::receive(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::SimplePhy::receivePacket(), s3f::s3fnet::UDPServerSession::request_received(), s3f::s3fnet::TCPServerSession::request_received(), s3f::s3fnet::UDPClientSession::request_sent(), s3f::s3fnet::TCPClientSession::request_sent(), s3f::s3fnet::UDPSession::send(), s3f::s3fnet::TCPSession::send_data(), s3f::s3fnet::SimplePhy::sendPacket(), s3f::s3fnet::UDPClientSession::server_connected(), s3f::s3fnet::TCPClientSession::server_connected(), s3f::s3fnet::BTCPClientSession::server_connected(), s3f::s3fnet::UDPServerSession::session_closed(), s3f::s3fnet::UDPClientSession::session_closed(), s3f::s3fnet::TCPClientSession::session_closed(), s3f::s3fnet::TCPServerSession::session_closed(), s3f::s3fnet::BTCPClientSession::session_closed(), s3f::s3fnet::TCPMaster::setConnected(), s3f::s3fnet::TCPMaster::setIdle(), s3f::s3fnet::TCPMaster::setListening(), s3f::s3fnet::UDPSession::setSource(), s3f::s3fnet::TCPSession::slowTimeoutHandling(), s3f::s3fnet::UDPServerSession::start_on(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPServerSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), s3f::s3fnet::BTCPClientSession::start_on(), s3f::s3fnet::TCPSession::TCPSession(), s3f::s3fnet::UDPClientSession::timeout(), s3f::s3fnet::TCPClientSession::timeout(), s3f::s3fnet::BTCPClientSession::timeout(), s3f::s3fnet::UDPSession::UDPSession(), s3f::s3fnet::TCPSession::update_timeout(), and s3f::s3fnet::UDPSession::wake_app().
 {
         return inHost()->getNowWithThousandSeparator();
 }
int s3f::s3fnet::ProtocolSession::configured () inline inherited
This method returns true if the protocol session has been configured.
This method is used to make sure we configure the protocol session before initializing it.
Definition at line 221 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_CONFIGURED, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::config(), and s3f::s3fnet::ProtocolSession::init().
 { return stage >= PSESS_CONFIGURED; }
int s3f::s3fnet::ProtocolSession::initialized () inline inherited
This method returns true if the protocol session has been initialized.
This can be used to sequence calls to the init method of protocol sessions. For example, if protocol session A requires protocol session B to be initialized before A can be initialized, A's init method can call B's init method as long as B's initialized() returns true. The system does not enforce any ordering in its calls the init methods of all protocol sessions declared in the dml configuration.
Definition at line 233 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_INITIALIZED, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::init(), and s3f::s3fnet::ProtocolSession::wrapup().
 { return stage >= PSESS_INITIALIZED; }
int s3f::s3fnet::ProtocolSession::wrapped_up () inline inherited
This method returns true if the protocol session has been wrapped up.
This can be used to sequence calls to the wrapup method of protocol sessions. For example, if protocol session A requires protocol session B to be wrapped up before A can be wrapped up, A's wrapup method can call B's wrapup method as long as B's wrapped_up() returns true. The system does not enforce any ordering in its calls the wrapup methods of all protocol sessions declared in the dml configuration.
Definition at line 245 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_WRAPPED_UP, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::wrapup().
 { return stage >= PSESS_WRAPPED_UP; }
virtual const char* s3f::s3fnet::ProtocolSession::psesstype () inline virtual inherited
Reimplemented in s3f::s3fnet::NBSocketMaster, and s3f::s3fnet::SocketMaster.
Definition at line 247 of file protocol_session.h.
 { return "GENERIC"; } // DEBUG
virtual int s3f::s3fnet::ProtocolSession::instantiation_type () inline protected virtual inherited
This method controls how protocol instances can coexist with one another.
It returns one of the following:
PROT_UNIQUE_INSTANCE (default): allows only one instance for each type of protocol per protocol stack;
PROT_MULTIPLE_INSTANCES: allows multiple instances of the same implementation for each type of protocol per protocol stack;
PROT_MULTIPLE_IMPLEMENTATIONS: allows multiple instances from different implementations of the same protocol to exist on the protocol stack.
Reimplemented in s3f::s3fnet::BTCPClientSession, and s3f::s3fnet::TCPClientSession.
Definition at line 269 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PROT_UNIQUE_INSTANCE.
Referenced by s3f::s3fnet::ProtocolGraph::insert_session().
 { return PROT_UNIQUE_INSTANCE; }
Member Data Documentation
ForwardingTable* s3f::s3fnet::IPSession::forwarding_table private
Forwarding table used to deliver packets.
Definition at line 216 of file ip_session.h.
Referenced by control(), handle_pop_pkt(), init(), load_forwarding_table(), push(), and ~IPSession().
bool s3f::s3fnet::IPSession::show_drop private
Whether to print a message when a packet has been dropped.
Definition at line 219 of file ip_session.h.
Referenced by config(), handle_pop_local_pkt(), handle_pop_pkt(), and push().
ProtocolSession* s3f::s3fnet::IPSession::pop_intercept_sess private
session that intercept packet.
Definition at line 227 of file ip_session.h.
Referenced by control().
char* s3f::s3fnet::ProtocolSession::name inherited
Symbolic name of the protocol this session implements.
The name of the protocol is derived from the DML 'name' attribute. It must not be NULL once the protocol session is configured.
Definition at line 63 of file protocol_session.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::SimpleMac::init(), s3f::s3fnet::UDPMaster::init(), s3f::s3fnet::SimplePhy::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::SocketMaster::init(), init(), s3f::s3fnet::NBSocketMaster::init(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::ProtocolGraph::insert_session(), s3f::s3fnet::ProtocolSession::wrapup(), and s3f::s3fnet::ProtocolSession::~ProtocolSession().
float s3f::s3fnet::ProtocolSession::version inherited
Version number of this protocol implemenntation, represented as a floating point number (e.g., 1.23).
Definition at line 69 of file protocol_session.h.
char* s3f::s3fnet::ProtocolSession::use inherited
Name of the protocol class from which this protocol session is instantiated.
The protocol class must be registered with the Protocols class so that we will be able to instantiate an object from the class. (C++ does not support self-reflection). The class name must not be NULL once the protocol session is configured.
Definition at line 79 of file protocol_session.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::ProtocolGraph::insert_session(), and s3f::s3fnet::ProtocolSession::~ProtocolSession().
ProtocolGraph* s3f::s3fnet::ProtocolSession::ingraph protected inherited
Points to the protocol graph.
Definition at line 335 of file protocol_session.h.
Referenced by s3f::s3fnet::NicProtocolSession::getNetworkInterface(), s3f::s3fnet::ProtocolSession::inGraph(), and s3f::s3fnet::ProtocolSession::inHost().
Random::RNG* s3f::s3fnet::ProtocolSession::sess_rng protected inherited
Pointer to a random number generator.
Definition at line 338 of file protocol_session.h.
Referenced by s3f::s3fnet::ProtocolSession::getRandom(), and s3f::s3fnet::ProtocolSession::init().
int s3f::s3fnet::ProtocolSession::stage protected inherited
This variable indicates the current stage of this protocol session.
Each protocol session will go through four staged: PSESS_CREATED, PSESS_CONFIGURED, PSESS_INITIALIZED, and then PSESS_WRAPPED_UP.
Definition at line 346 of file protocol_session.h.
Referenced by s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::ProtocolSession::configured(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::ProtocolSession::initialized(), s3f::s3fnet::ProtocolSession::wrapped_up(), and s3f::s3fnet::ProtocolSession::wrapup().
The documentation for this class was generated from the following files:
ip_session.h
ip_session.cc