S3F: s3f::s3fnet::TCPBlockList Class Reference
s3f::s3fnet::TCPBlockList Class Reference
A list of blocks of consecutive sequence numbers.
#include <tcp_blocks.h>
Public Types
enum { PATTERN_UNSORTED = 0, PATTERN_INCREASE = 1 }
Public Member Functions
TCPBlockList (int pattern)
The constructor.
~TCPBlockList ()
The destructor.
void insert_block (uint32 seqno, uint32 len)
Insert a block with sequence numbers of length len starting from seqno into the list.
void clear_blocks (uint32 seqno)
Clear all blocks less than a given seqno.
void clear_all_blocks ()
Clear all blocks.
int fetch_blocks (uint32 *buffer, int num)
Fetch blocks.
uint32 remove_lowest (bool remove)
Remove the block with the lowest sequence number.
bool is_new (uint32 *seqno, uint32 *length)
Return whether the block delineated by the starting seqno and length is a new block in the list; if not, the returned parameters point to the non-overlapped region within the given block.
uint32 get_lowest ()
Return the lowest sequence number of this list.
uint32 get_highest ()
Return the highest sequence number of this list.
uint32 unavailable (uint32 startno)
Used only when the pattern is PATTERN_INCREASE.
Protected Member Functions
bool overlap_blocks ()
Coalesce the first block in the list with other blocks in the list; return true if further coalescing is needed.
void resort_blocks ()
Resort blocks (in increasing order): relocate the first block (newly inserted) in the list to the correct position.
Private Attributes
int pattern
Whether the list should be sorted (increasingly) or not.
TCPBlock * head_block
The head of the block list.
Detailed Description
A list of blocks of consecutive sequence numbers.
The data structure is used by both sending and receiving windows to keep track of data sent and received.
Definition at line 36 of file tcp_blocks.h.
Member Enumeration Documentation
anonymous enum
Enumerator
PATTERN_UNSORTED
PATTERN_INCREASE
Definition at line 38 of file tcp_blocks.h.
        {
     PATTERN_UNSORTED = 0,
     PATTERN_INCREASE = 1
   };
Constructor & Destructor Documentation
s3f::s3fnet::TCPBlockList::TCPBlockList (int pattern)
The constructor.
Definition at line 13 of file tcp_blocks.cc.
References head_block.
                                   : pattern(pat)
 {
   head_block = new TCPBlock(UINT_MAX, 0);
 }
s3f::s3fnet::TCPBlockList::~TCPBlockList () inline
The destructor.
Definition at line 47 of file tcp_blocks.h.
References clear_all_blocks(), and head_block.
 { clear_all_blocks(); delete head_block; }
Member Function Documentation
void s3f::s3fnet::TCPBlockList::insert_block (uint32 seqno, uint32 len)
Insert a block with sequence numbers of length len starting from seqno into the list.
Definition at line 18 of file tcp_blocks.cc.
References head_block, s3f::s3fnet::TCPBlock::left_edge, mymax, mymin, s3f::s3fnet::TCPBlock::next, overlap_blocks(), pattern, PATTERN_INCREASE, resort_blocks(), and s3f::s3fnet::TCPBlock::right_edge.
Referenced by s3f::s3fnet::TCPSession::receiver_recv_sack(), and s3f::s3fnet::TCPSession::sender_recv_sack().
 {
   TCPBlock *new_block = new TCPBlock(seqno, seqno+len);
   new_block->next = head_block->next;
   head_block->next = new_block;
   // if overlapped, we still have to check whether the first block
   // overlaps with other blocks. it's tricky. For example, (0, 100),
   // (200, 300), now (100, 200) is coming. Then the first time
   // when overlapping, (0,100) integrates with (100,200), that's
   // (0,200), we still have to integrate (0,200) and (200, 300),
   // that's (0, 300). However, 2 times is enough.
   if(overlap_blocks()) overlap_blocks();
   // update highest and lowest
   head_block->right_edge = mymax(head_block->right_edge, seqno + len);
   head_block->left_edge = mymin(head_block->left_edge, seqno);
   // if the block list needs to be sorted increasingly
   if(PATTERN_INCREASE == pattern) resort_blocks();
 }
void s3f::s3fnet::TCPBlockList::clear_blocks (uint32 seqno)
Clear all blocks less than a given seqno.
Definition at line 106 of file tcp_blocks.cc.
References head_block, s3f::s3fnet::TCPBlock::left_edge, mymax, s3f::s3fnet::TCPBlock::next, pattern, PATTERN_INCREASE, and s3f::s3fnet::TCPBlock::right_edge.
Referenced by clear_all_blocks(), s3f::s3fnet::TCPSession::receiver_send_sack(), and s3f::s3fnet::TCPSession::sender_recv_sack().
 {
   TCPBlock *q = head_block, *p = head_block->next;
   while(p)
   {
     if(p->left_edge < seqno) // left edge below seqno
     {
       // we need to update lowest
       head_block->left_edge = mymax(head_block->left_edge, seqno);
       if(p->right_edge > seqno)
       {
         // if seqno is contained in block, we need to cut partially
         p->left_edge = seqno;
         // if it's increasing sort, we are done
         if(PATTERN_INCREASE == pattern) break;
         else
         {
           q = p;
           p = p->next;
         }
       }
       else
       {
         // we have to delete the whole block, we have to consider the next block
         q->next = p->next;
         delete p;
         p = q->next;
       }
     }
     else // left edge above seqno
     {
       // if it's increasing sort, we're done
       if(PATTERN_INCREASE == pattern) break;
       else
       {
         q = p;
         p = p->next;
       }
     }
   }
   // if all blocks are cleared, we have to reset lowest and highest
   if(!head_block->next)
   {
     head_block->left_edge = UINT_MAX;
     head_block->right_edge = 0;
   }
 }
void s3f::s3fnet::TCPBlockList::clear_all_blocks ()
Clear all blocks.
Definition at line 157 of file tcp_blocks.cc.
References clear_blocks(), head_block, and s3f::s3fnet::TCPBlock::right_edge.
Referenced by s3f::s3fnet::TCPSession::process_new_acks(), s3f::s3fnet::TCPSession::slow_timeout_handling_helper(), and ~TCPBlockList().
 {
   clear_blocks(head_block->right_edge);
 }
int s3f::s3fnet::TCPBlockList::fetch_blocks (uint32 * buffer, int num)
Fetch blocks.
Put the the boundaries (left edge and right edge) of each block in the given buffer. Therefore, the buffer length is at least 2*num*sizeof(uint32) bytes. Return the number of blocks that are really included.
Definition at line 162 of file tcp_blocks.cc.
References head_block, and s3f::s3fnet::TCPBlock::next.
Referenced by s3f::s3fnet::TCPSession::receiver_send_sack().
 {
   int i;
   TCPBlock *p = head_block->next;
   assert(buffer);
   for(i=0; p && i<num; i++, p=p->next)
   {
     buffer[2*i] = p->left_edge;
     buffer[2*i+1] = p->right_edge;
   }
   return i;
 }
uint32 s3f::s3fnet::TCPBlockList::remove_lowest (bool remove)
Remove the block with the lowest sequence number.
The block is removed from the list only if the remove parameter is true. The function returns the length of the lowest block.
Definition at line 175 of file tcp_blocks.cc.
References head_block, s3f::s3fnet::TCPBlock::left_edge, mymin, s3f::s3fnet::TCPBlock::next, pattern, PATTERN_UNSORTED, and s3f::s3fnet::TCPBlock::right_edge.
 {
   TCPBlock* p;
   uint32 ret_len = 0;
   for(p=head_block; p; p=p->next)
   {
     if(p->next && p->next->left_edge == head_block->left_edge)
     {
       ret_len = p->next->right_edge - p->next->left_edge;
       if(remove)
       {
         TCPBlock* q = p->next->next;
         delete p->next;
         p->next = q;
       }
       break;
     }
   }
   // we should elect a new lowest seqno
   if(remove)
   {
     // elect a new lowest block
     if(head_block->next)
     {
       head_block->left_edge = head_block->next->left_edge;
       if(PATTERN_UNSORTED == pattern)
       {
         // if unsorted, we have to traverse all blocks in the list to get the lowest no
         for(p=head_block->next->next; p; p=p->next)
                 head_block->left_edge = mymin(head_block->left_edge, p->left_edge);
       }
     }
     else
     {
       head_block->left_edge = UINT_MAX;
       head_block->right_edge = 0;
     }
   }
   return ret_len;
 }
bool s3f::s3fnet::TCPBlockList::is_new (uint32 * seqno, uint32 * length)
Return whether the block delineated by the starting seqno and length is a new block in the list; if not, the returned parameters point to the non-overlapped region within the given block.
Definition at line 219 of file tcp_blocks.cc.
References head_block, mymax, mymin, s3f::s3fnet::TCPBlock::next, pattern, and PATTERN_INCREASE.
Referenced by s3f::s3fnet::TCPSession::receiver_recv_sack().
 {
   assert(seqno && length);
   uint32 overlap_seqno;
   uint32 overlap_length;
   if(*length == 0) return false;
   for(TCPBlock *p = head_block->next; p; p=p->next)
   {
     if(pattern == PATTERN_INCREASE && p->left_edge >= *seqno + *length)
       return true;
     overlap_seqno  = mymax(*seqno, p->left_edge);
     overlap_length = mymin(*seqno + *length, p->right_edge) - overlap_seqno;
     if(overlap_length > 0) // if overlap
     {
       // the new packet is contained in a block completely
       if(overlap_length == *length) return false;
       if(overlap_seqno > p->left_edge)
       {
         // if the left part of the packet is overlapped we get rid of the overlapped part
         *seqno  = p->right_edge;
         *length = *seqno + *length - p->right_edge;
       }
       else
       {
         // right part of the packet is overlapped
         *length = p->left_edge - *seqno;
       }
     }
   }
   return true;
 }
uint32 s3f::s3fnet::TCPBlockList::get_lowest () inline
Return the lowest sequence number of this list.
Definition at line 83 of file tcp_blocks.h.
References head_block, and s3f::s3fnet::TCPBlock::left_edge.
 { return head_block->left_edge; }
uint32 s3f::s3fnet::TCPBlockList::get_highest () inline
Return the highest sequence number of this list.
Definition at line 86 of file tcp_blocks.h.
References head_block, and s3f::s3fnet::TCPBlock::right_edge.
 { return head_block->right_edge; }
uint32 s3f::s3fnet::TCPBlockList::unavailable (uint32 startno)
Used only when the pattern is PATTERN_INCREASE.
The method returns the first unavailable item in the list from the current position.
Definition at line 258 of file tcp_blocks.cc.
References head_block, s3f::s3fnet::TCPBlock::left_edge, mymax, s3f::s3fnet::TCPBlock::next, pattern, PATTERN_INCREASE, and s3f::s3fnet::TCPBlock::right_edge.
Referenced by s3f::s3fnet::TCPSession::sack_resend_segments().
 {
   assert(pattern == PATTERN_INCREASE);
   TCPBlock *p, *q = head_block;
   for(p = q->next; p && startno >= p->left_edge; p = p->next)
     q = p;
   if(q == head_block) return startno;
   else return mymax(q->right_edge, startno);
 }
bool s3f::s3fnet::TCPBlockList::overlap_blocks () protected
Coalesce the first block in the list with other blocks in the list; return true if further coalescing is needed.
Definition at line 40 of file tcp_blocks.cc.
References head_block, s3f::s3fnet::TCPBlock::left_edge, mymax, mymin, s3f::s3fnet::TCPBlock::next, and s3f::s3fnet::TCPBlock::right_edge.
Referenced by insert_block().
 {
   bool no_overlap = true;
   TCPBlock *real_head = head_block->next, *p = real_head;
   // not overlapped if the list is empty
   if(!p) return false;
   while(p->next)
   {
     // example: [100,200]->[0,100]
     if((real_head->left_edge >= p->next->left_edge) &&
        (real_head->left_edge <= p->next->right_edge))
     {
       no_overlap = false;
       // combine of the two blocks
       real_head->left_edge = p->next->left_edge;
       real_head->right_edge = mymax(real_head->right_edge, p->next->right_edge);
     }
     // example: [0,100]->[100,200]
     else if((real_head->right_edge >= p->next->left_edge) &&
             (real_head->right_edge <= p->next->right_edge))
     {
       no_overlap = false;
       real_head->right_edge = p->next->right_edge;
       real_head->left_edge = mymin(real_head ->left_edge, p->next->left_edge);
     }
     if(no_overlap) p = p->next;
     else
     {
       // delete p->next, because it has been integrated to the first
       // block of the list
       TCPBlock *q = p->next;
       p->next = p->next->next;
       delete q;
       break;
     }
   }
   return !no_overlap;
 }
void s3f::s3fnet::TCPBlockList::resort_blocks () protected
Resort blocks (in increasing order): relocate the first block (newly inserted) in the list to the correct position.
Definition at line 86 of file tcp_blocks.cc.
References head_block, s3f::s3fnet::TCPBlock::left_edge, and s3f::s3fnet::TCPBlock::next.
Referenced by insert_block().
 {
   if(!head_block->next) return;
   TCPBlock *p, *q = head_block->next;
   uint32 first_no = q->left_edge;
   // find the right position of first_no and then relocate the first
   // block between block q and block p.
   for(p = q->next; p && p->left_edge < first_no; p = p->next)
     q = p;
   if(q != head_block->next)
   {
     q->next = head_block->next;
     q = head_block->next->next;
     head_block->next->next = p;
     head_block->next = q;
   }
 }
Member Data Documentation
int s3f::s3fnet::TCPBlockList::pattern private
Whether the list should be sorted (increasingly) or not.
Definition at line 106 of file tcp_blocks.h.
Referenced by clear_blocks(), insert_block(), is_new(), remove_lowest(), and unavailable().
TCPBlock* s3f::s3fnet::TCPBlockList::head_block private
The head of the block list.
Definition at line 109 of file tcp_blocks.h.
Referenced by clear_all_blocks(), clear_blocks(), fetch_blocks(), get_highest(), get_lowest(), insert_block(), is_new(), overlap_blocks(), remove_lowest(), resort_blocks(), TCPBlockList(), unavailable(), and ~TCPBlockList().
The documentation for this class was generated from the following files:
tcp_blocks.h
tcp_blocks.cc