S3F: s3f::s3fnet::TCPSendWindow Class Reference
s3f::s3fnet::TCPSendWindow Class Reference
The sliding window for TCP sender.
#include <tcp_sndwnd.h>
Public Member Functions
TCPSendWindow (uint32 initseq, uint32 bufsiz, uint32 wndsiz)
The constructor.
~TCPSendWindow ()
The destructor.
DataMessage * generate (uint32 seqno, uint32 length)
Generate a message with designated length and sequence number.
void release (uint32 length)
Shift the send window and then release the buffer.
uint32 canSend ()
Return how many bytes can be sent right now from the buffer.
bool needToRequest ()
If all the requested data has been sent out, we need to request more data from the upper layer.
void requestToSend (byte *msg, uint32 length)
Request to send new data.
void reset ()
Reset the window.
uint32 dataInBuffer ()
Returns how much of the buffer is used.
uint32 freeInBuffer ()
Returns how much of the buffer is free.
uint32 bufferSize ()
Returns buffer size.
uint32 dataInRequest ()
Returns how much data is still requesting to enter the buffer.
uint32 dataBuffered ()
Returns how much data has been put into the buffer.
void clearDataBuffered ()
Clear how much data has been buffered.
uint32 start ()
Return the first sequence of the window.
uint32 end ()
Return the last sequence of the window.
uint32 firstUnused ()
Return the first unused sequence in the window.
uint32 size ()
Return the size of the window.
uint32 used ()
Return how much of the window is used up in bytes.
uint32 unused ()
Return how much of the window is unused in bytes.
uint32 lengthTo (const uint32 seqno)
Return the number of bytes between a give sequence number and the start of the window.
void setStart (const uint32 seqno)
Set the start sequence number of the window.
void shift (uint32 offset)
Increase the lower edge of the window by offset number of bytes.
void expand (uint32 nbytes)
Expand the window size by nbytes.
void shrink (uint32 nbytes)
Shrink the size of the window by nbytes.
bool use (uint32 nbytes)
Use up nbytes of the window with data.
void setSYN (bool syn)
set SYN bit.
void setFIN (bool fin)
set FIN bit.
bool synAtFront ()
Return true if SYN segment is in the window.
bool finAtFront ()
Return true if FIN segment is in the window.
uint32 next ()
Like firstUnused method, but also uses SYN & FIN segments; the method is used for sending window.
uint32 expect ()
Like start method, but also uses SYN & FIN segments; the method is used for receiving window.
bool within (uint32 seqno)
Returns true iff 'seqno' is within the window.
bool isUsed (uint32 seqno)
Returns true iff 'seqno' is used within the window.
bool empty ()
Returns true iff the window is empty (nothing used).
Protected Member Functions
void release_buffer (uint32 length)
Remove the unused data from the head.
void add_to_buffer (uint32 length)
Move some data from the request to the buffer when the buffer has some vacancy.
void seq_shift (uint32 offset)
Shift the window by the given offset permanently.
Protected Attributes
uint32 buffer_size
Buffer size.
uint32 length_in_buffer
How many bytes are in the buffer waiting to be sent out?
uint32 length_in_request
How many bytes are waiting to enter the buffer?
uint32 length_buffered
How many bytes have been put into the buffer.
DataChunk * head_chunk
Point to the head of the message list.
DataChunk * tail_chunk
Point to the tail of the message list.
byte * first_raw_data
The pointer to the message block.
uint32 start_seqno
Starting sequence number of the window.
uint32 win_size
Size of the window in bytes.
uint32 used_size
How many bytes are used in window.
int syn_included
Whether SYN is in window.
int fin_included
Whether FIN is in window.
Detailed Description
The sliding window for TCP sender.
Definition at line 21 of file tcp_sndwnd.h.
Constructor & Destructor Documentation
s3f::s3fnet::TCPSendWindow::TCPSendWindow (uint32 initseq, uint32 bufsiz, uint32 wndsiz)
The constructor.
Definition at line 14 of file tcp_sndwnd.cc.
References s3f::s3fnet::error_quit().
                                                                          :
   TCPSeqWindow(initseq, wndsiz), buffer_size(bufsiz),
   length_in_buffer(0), length_in_request(0), length_buffered(0),
   head_chunk(0), tail_chunk(0), first_raw_data(0)
 {
   // make sure window size must be less than buffer size
   if(wndsiz > bufsiz)
   {
     error_quit("ERROR: TCP window size (%u) must be no larger than buffer size (%u).\n",
                wndsiz, bufsiz);
   }
 }
s3f::s3fnet::TCPSendWindow::~TCPSendWindow ()
The destructor.
Definition at line 27 of file tcp_sndwnd.cc.
References first_raw_data, head_chunk, and s3f::s3fnet::DataChunk::real_data.
 {
   if(first_raw_data)
   {
     delete[] first_raw_data;
     assert(head_chunk);
     head_chunk->real_data = 0;
   }
   delete head_chunk;
 }
Member Function Documentation
DataMessage * s3f::s3fnet::TCPSendWindow::generate (uint32 seqno, uint32 length)
Generate a message with designated length and sequence number.
Definition at line 38 of file tcp_sndwnd.cc.
References head_chunk, length_in_buffer, mymin, s3f::s3fnet::DataChunk::next, s3f::s3fnet::DataChunk::real_data, s3f::s3fnet::DataChunk::real_length, and s3f::s3fnet::TCPSeqWindow::start().
Referenced by s3f::s3fnet::TCPSession::send_data().
 {
   // make sure the sequence does not fall within the buffer
   assert(seqno >= start() && seqno + length <= start() + length_in_buffer);
   // calculate the offset from the start
   uint32 offset = seqno - start();
   // find the right block in the list
   DataChunk* node = head_chunk;
   while(node && offset)
   {
     // if the start position is at node->real_data + offset in the current
     // node, quit the loop.
     if(node->real_length > offset) break;
     offset -= node->real_length;
     node = node->next;
   }
   assert(node);
   // fetch data and put it into a generated payload message.
   if(node->real_length - offset >= length)
   {
     byte* payload;
     // the current node can satisfy the data length requested.
     if(node->real_data)
     {
       // if the current node carries real data, it is the first node
       // and, at the same time, the current node can satisfy the data
       // length required
       payload = new byte[length];
       memcpy((byte*)payload, node->real_data+offset, length);
     }
     else
     {
       // if the current node carries fake data, it is the first node
       // and, at the same time, the current node can satisfy the data
       // length required
       payload = 0;
     }
     return new DataMessage(length, payload);
   }
   else
   {
     // the current node cannot satisfy the data length requested; we
     // maintain a message list, since we need to attach each new block
     // at the tail of the list, we need to keep the tail pointer.
     DataChunk* msglist_head = 0, *msglist_tail = 0;
     uint32 cur_length = length;
     while(cur_length > 0)
     {
       // for the current block, how much data can be transmitted?
       int len = mymin(node->real_length-offset, cur_length);
       assert(node);
       if(node->real_data)
       {
         // look ahead to see how many real data ahead; we want to consolidate the real data here...
         int contiguous_len = len;
         for(DataChunk* pnode = node->next; pnode && pnode->real_data; pnode = pnode->next)
         {
           if(pnode->real_length+contiguous_len >= cur_length)
           {
                 contiguous_len += mymin(cur_length - contiguous_len, pnode->real_length);
                 break;
           }
           else contiguous_len += pnode->real_length;
         }
         // we allocate a block containing these contiguous data
         byte* block = new byte[contiguous_len];
         int copied_len = 0;
         while(copied_len < contiguous_len)
         {
           int new_len = mymin(contiguous_len-copied_len, (int)(node->real_length-offset));
           memcpy(block+copied_len, node->real_data+offset, new_len);
           copied_len += new_len;
           if(offset+new_len < node->real_length)
           {
                 offset += new_len;
                 assert(copied_len == contiguous_len);
           }
           else
           {
                 node = node->next;
                 offset = 0;
           }
         }
         cur_length -= contiguous_len;
         assert(offset==0 || (offset>0 && cur_length==0));
         // put the contiguous message block at the tail
         DataChunk* msg_node = new DataChunk(contiguous_len, block);
         if(!msglist_head)
         {
           msglist_head = msglist_tail = msg_node;
         }
         else
         {
           msglist_tail->next = msg_node;
           msglist_tail = msg_node;
         }
       }
       else // if fake data
       {
         if(!msglist_head)
         {
           msglist_head = msglist_tail = new DataChunk(len);
         }
         else if(!msglist_tail->real_data)
         {
           // the tail block also uses fake data, so we can merge them
               // together by simply adding the lengths
               msglist_tail->real_length += len;
         }
         else
         {
           // the tail block uses real data, we have to create another
               // message node to contain this fake data
               msglist_tail->next = new DataChunk(len);
               msglist_tail = msglist_tail->next;
             }
             // we have to visit the next message node if not enough data is fetched.
             if((cur_length -= len) > 0)
             {
               node = node->next;
               offset = 0;
             }
       }
     } // while loop
     return new DataMessage(msglist_head);
   }
 }
void s3f::s3fnet::TCPSendWindow::release (uint32 length)
Shift the send window and then release the buffer.
Definition at line 175 of file tcp_sndwnd.cc.
References add_to_buffer(), freeInBuffer(), length_in_request, mymin, release_buffer(), and s3f::s3fnet::TCPSeqWindow::shift().
Referenced by s3f::s3fnet::TCPSession::process_new_acks().
 {
   // shift the seq window
   shift(length);
   // release the buffer
   release_buffer(length);
   // because there are free buffer available, we need to add new data
   // to the buffer
   add_to_buffer(mymin(length_in_request, freeInBuffer()));
 }
uint32 s3f::s3fnet::TCPSendWindow::canSend () inline
Return how many bytes can be sent right now from the buffer.
Definition at line 36 of file tcp_sndwnd.h.
References length_in_buffer, and s3f::s3fnet::TCPSeqWindow::used().
Referenced by s3f::s3fnet::TCPSession::appl_send(), and s3f::s3fnet::TCPSession::receive().
 { return length_in_buffer - used(); }
bool s3f::s3fnet::TCPSendWindow::needToRequest () inline
If all the requested data has been sent out, we need to request more data from the upper layer.
Definition at line 42 of file tcp_sndwnd.h.
References length_in_request.
Referenced by s3f::s3fnet::TCPSession::receive().
 { return length_in_request <= 0; }
void s3f::s3fnet::TCPSendWindow::requestToSend (byte * msg, uint32 length)
Request to send new data.
Definition at line 188 of file tcp_sndwnd.cc.
References add_to_buffer(), first_raw_data, freeInBuffer(), head_chunk, length_in_request, mymin, s3f::s3fnet::DataChunk::next, s3f::s3fnet::DataChunk::real_data, and tail_chunk.
Referenced by s3f::s3fnet::TCPSession::appl_send().
 {
   DataChunk* datachk = new DataChunk(msg_len, msg);
   if(tail_chunk)
   {
     assert(head_chunk);
     tail_chunk->next = datachk;
     tail_chunk = datachk;
   }
   else
   {
     assert(!first_raw_data && !head_chunk);
     head_chunk = tail_chunk = datachk;
     first_raw_data = datachk->real_data;
   }
   // how much data is been requested to send currently
   length_in_request += msg_len;
   // see whether the new data can be put in the buffer.
   add_to_buffer(mymin(msg_len, freeInBuffer()));
 }
void s3f::s3fnet::TCPSendWindow::reset ()
Reset the window.
Definition at line 211 of file tcp_sndwnd.cc.
References first_raw_data, head_chunk, length_in_buffer, length_in_request, s3f::s3fnet::DataChunk::real_data, s3f::s3fnet::TCPSeqWindow::reset(), and tail_chunk.
Referenced by s3f::s3fnet::TCPSession::init_state_listen().
 {
   TCPSeqWindow::reset();
   length_in_request = length_in_buffer = 0;
   // restore the data pointer at the head chunk before destroying the
   // entire list
   if(head_chunk)
   {
     if(head_chunk->real_data)
       head_chunk->real_data = first_raw_data;
     delete head_chunk;
   }
   head_chunk = tail_chunk = 0;
   first_raw_data = 0;
 }
uint32 s3f::s3fnet::TCPSendWindow::dataInBuffer () inline
Returns how much of the buffer is used.
Definition at line 52 of file tcp_sndwnd.h.
References length_in_buffer.
Referenced by s3f::s3fnet::TCPSession::appl_close(), s3f::s3fnet::TCPSession::init_state_fin_wait_1(), s3f::s3fnet::TCPSession::process_dup_acks(), s3f::s3fnet::TCPSession::receive(), and s3f::s3fnet::TCPSession::segment_and_send().
 { return length_in_buffer; }
uint32 s3f::s3fnet::TCPSendWindow::freeInBuffer () inline
Returns how much of the buffer is free.
Definition at line 55 of file tcp_sndwnd.h.
References buffer_size, and length_in_buffer.
Referenced by release(), and requestToSend().
 { return buffer_size - length_in_buffer; }
uint32 s3f::s3fnet::TCPSendWindow::bufferSize () inline
Returns buffer size.
Definition at line 58 of file tcp_sndwnd.h.
References buffer_size.
 { return buffer_size; }
uint32 s3f::s3fnet::TCPSendWindow::dataInRequest () inline
Returns how much data is still requesting to enter the buffer.
Definition at line 62 of file tcp_sndwnd.h.
References length_in_request.
 { return length_in_request; }
uint32 s3f::s3fnet::TCPSendWindow::dataBuffered () inline
Returns how much data has been put into the buffer.
Definition at line 65 of file tcp_sndwnd.h.
References length_buffered.
Referenced by s3f::s3fnet::TCPSession::appl_send(), and s3f::s3fnet::TCPSession::wake_app().
 { return length_buffered; }
void s3f::s3fnet::TCPSendWindow::clearDataBuffered () inline
Clear how much data has been buffered.
Definition at line 68 of file tcp_sndwnd.h.
References length_buffered.
Referenced by s3f::s3fnet::TCPSession::appl_send().
 { length_buffered = 0; }
void s3f::s3fnet::TCPSendWindow::release_buffer (uint32 length) protected
Remove the unused data from the head.
because the data with lower sequence number is at the front of the list, we just need to remove from the head node.
Definition at line 242 of file tcp_sndwnd.cc.
References first_raw_data, head_chunk, length_in_buffer, s3f::s3fnet::DataChunk::next, s3f::s3fnet::DataChunk::real_data, s3f::s3fnet::DataChunk::real_length, and tail_chunk.
Referenced by release().
 {
   assert(length <= length_in_buffer);
   length_in_buffer -= length;
   while(length > 0)
   {
     // check whether we can finish it in the current node.
     if(head_chunk->real_length > length)
     {
       head_chunk->real_length -= length;
       if(head_chunk->real_data)
         head_chunk->real_data += length;
       length = 0;
     }
     else // we need to destroy the current node
     {
       length -= head_chunk->real_length;
       // release the node; note that the real data (present or not)
       // should not be reclaimed here and we should not chain the
       // deletion!
       DataChunk* node = head_chunk->next;
       head_chunk->real_data = 0;
       head_chunk->next = 0;
       delete head_chunk;
       head_chunk = node;
       if(first_raw_data) delete[] first_raw_data;
       if(head_chunk)
       {
         first_raw_data = head_chunk->real_data;
       }
       else
       {
         // in case that the whole list is deleted
         tail_chunk = 0;
         first_raw_data = 0;
       }
     }
   }
 }
void s3f::s3fnet::TCPSendWindow::add_to_buffer (uint32 length) protected
Move some data from the request to the buffer when the buffer has some vacancy.
Definition at line 230 of file tcp_sndwnd.cc.
References buffer_size, length_buffered, length_in_buffer, and length_in_request.
Referenced by release(), and requestToSend().
 {
   assert(length_in_buffer + length <= buffer_size);
   // update how many bytes in the buffer and being requested.
   length_in_buffer += length;
   length_in_request -= length;
   length_buffered += length;
   assert(length_in_request >= 0);
 }
uint32 s3f::s3fnet::TCPSeqWindow::start () inline inherited
Return the first sequence of the window.
Definition at line 37 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::start_seqno.
Referenced by generate(), s3f::s3fnet::TCPSession::init_state_established(), s3f::s3fnet::TCPSession::process_acks(), s3f::s3fnet::TCPSession::process_dup_acks(), s3f::s3fnet::TCPSession::sack_resend_segments(), and s3f::s3fnet::TCPSession::timeout_resend().
 { return start_seqno; }
uint32 s3f::s3fnet::TCPSeqWindow::end () inline inherited
Return the last sequence of the window.
Definition at line 40 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::start_seqno, and s3f::s3fnet::TCPSeqWindow::win_size.
 { return start_seqno + win_size - 1; }
uint32 s3f::s3fnet::TCPSeqWindow::firstUnused () inline inherited
Return the first unused sequence in the window.
Definition at line 43 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::start_seqno, and s3f::s3fnet::TCPSeqWindow::used_size.
Referenced by s3f::s3fnet::TCPSession::acknowledge(), s3f::s3fnet::TCPSession::appl_close(), s3f::s3fnet::TCPSession::appl_send(), s3f::s3fnet::TCPSession::fastTimeoutHandling(), s3f::s3fnet::TCPSession::init_state_fin_wait_1(), s3f::s3fnet::TCPSession::init_state_syn_received(), s3f::s3fnet::TCPSession::init_state_syn_sent(), s3f::s3fnet::TCPSession::process_dup_acks(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::TCPSession::sack_send_in_fast_recovery(), s3f::s3fnet::TCPSession::slow_timeout_handling_helper(), and s3f::s3fnet::TCPSession::timeout_resend().
 { return start_seqno + used_size; }
uint32 s3f::s3fnet::TCPSeqWindow::size () inline inherited
Return the size of the window.
Definition at line 46 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::win_size.
Referenced by s3f::s3fnet::TCPSession::calc_advertised_wnd().
 { return win_size; }
uint32 s3f::s3fnet::TCPSeqWindow::used () inline inherited
Return how much of the window is used up in bytes.
Definition at line 49 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::used_size.
Referenced by canSend(), s3f::s3fnet::TCPSession::checkIdle(), s3f::s3fnet::TCPRecvWindow::freeInBuffer(), s3f::s3fnet::TCPSession::process_acks(), s3f::s3fnet::TCPSession::process_dup_acks(), s3f::s3fnet::TCPSession::process_new_acks(), and s3f::s3fnet::TCPSession::segment_and_send().
 { return used_size; }
uint32 s3f::s3fnet::TCPSeqWindow::unused () inline inherited
Return how much of the window is unused in bytes.
Definition at line 52 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::used_size, and s3f::s3fnet::TCPSeqWindow::win_size.
Referenced by s3f::s3fnet::TCPSession::process_dup_acks(), s3f::s3fnet::TCPSession::sack_send_in_fast_recovery(), and s3f::s3fnet::TCPSession::segment_and_send().
 { return (win_size - used_size); }
uint32 s3f::s3fnet::TCPSeqWindow::lengthTo (const uint32 seqno) inline inherited
Return the number of bytes between a give sequence number and the start of the window.
Definition at line 56 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::start_seqno.
Referenced by s3f::s3fnet::TCPSession::resend_segments().
 { return seqno - start_seqno; }
void s3f::s3fnet::TCPSeqWindow::setStart (const uint32 seqno) inline inherited
Set the start sequence number of the window.
Definition at line 63 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::start_seqno.
Referenced by s3f::s3fnet::TCPSession::active_open(), and s3f::s3fnet::TCPSession::process_SYN().
 { start_seqno = seqno; }
void s3f::s3fnet::TCPSeqWindow::shift (uint32 offset) inline inherited
Increase the lower edge of the window by offset number of bytes.
Definition at line 71 of file tcp_seqwnd.h.
References mymin, s3f::s3fnet::TCPSeqWindow::start_seqno, and s3f::s3fnet::TCPSeqWindow::used_size.
Referenced by s3f::s3fnet::TCPRecvWindow::generate(), and release().
   {
     start_seqno += offset;
     used_size -= mymin(offset, used_size);
   }
void s3f::s3fnet::TCPSeqWindow::expand (uint32 nbytes) inline inherited
Expand the window size by nbytes.
Note that the new size must not be larger than the buffer size—the condition is not enforced by this method.
Definition at line 80 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::win_size.
Referenced by s3f::s3fnet::TCPSession::calc_advertised_wnd().
 { win_size += nbytes; }
void s3f::s3fnet::TCPSeqWindow::shrink (uint32 nbytes) inline inherited
Shrink the size of the window by nbytes.
One can only shrink the size of unused space.
Definition at line 84 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::used_size, and s3f::s3fnet::TCPSeqWindow::win_size.
   {
     assert(nbytes <= (win_size - used_size));
     win_size -= nbytes;
   }
bool s3f::s3fnet::TCPSeqWindow::use (uint32 nbytes) inline inherited
Use up nbytes of the window with data.
Returns true if success, i.e., there is available unused space for this operation.
Definition at line 92 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::used_size, and s3f::s3fnet::TCPSeqWindow::win_size.
Referenced by s3f::s3fnet::TCPRecvWindow::addToBuffer(), and s3f::s3fnet::TCPSession::segment_and_send().
   {
     if(used_size + nbytes > win_size) return false;
     used_size += nbytes;
     return true;
   }
void s3f::s3fnet::TCPSeqWindow::setSYN (bool syn) inline inherited
set SYN bit.
Definition at line 104 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::seq_shift(), s3f::s3fnet::TCPSeqWindow::syn_included, and s3f::s3fnet::TCPSeqWindow::used_size.
Referenced by s3f::s3fnet::TCPSession::init_state_syn_received(), s3f::s3fnet::TCPSession::init_state_syn_sent(), s3f::s3fnet::TCPSession::process_ACK(), and s3f::s3fnet::TCPSession::process_SYN().
   {
     if(syn) assert(used_size == 0);
     else seq_shift(1);
     syn_included = syn ? 1 : 0;
   }
void s3f::s3fnet::TCPSeqWindow::setFIN (bool fin) inline inherited
set FIN bit.
Definition at line 112 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::fin_included, and s3f::s3fnet::TCPSeqWindow::seq_shift().
Referenced by s3f::s3fnet::TCPSession::appl_close(), s3f::s3fnet::TCPSession::init_state_fin_wait_1(), s3f::s3fnet::TCPSession::process_ACK(), and s3f::s3fnet::TCPSession::process_FIN().
   {
     if(!fin) seq_shift(1);
     fin_included = fin ? 1 : 0;
   }
bool s3f::s3fnet::TCPSeqWindow::synAtFront () inline inherited
Return true if SYN segment is in the window.
Definition at line 119 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::syn_included.
Referenced by s3f::s3fnet::TCPSession::init_state_established().
 { return syn_included; }
bool s3f::s3fnet::TCPSeqWindow::finAtFront () inline inherited
Return true if FIN segment is in the window.
Definition at line 122 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::fin_included, and s3f::s3fnet::TCPSeqWindow::used_size.
Referenced by s3f::s3fnet::TCPSession::init_state_established().
 { return (fin_included && used_size == 0); }
uint32 s3f::s3fnet::TCPSeqWindow::next () inline inherited
Like firstUnused method, but also uses SYN & FIN segments; the method is used for sending window.
Definition at line 126 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::fin_included, s3f::s3fnet::TCPSeqWindow::start_seqno, s3f::s3fnet::TCPSeqWindow::syn_included, and s3f::s3fnet::TCPSeqWindow::used_size.
Referenced by s3f::s3fnet::TCPSession::abort(), s3f::s3fnet::TCPSession::init_state_last_ack(), s3f::s3fnet::TCPSession::init_state_syn_received(), s3f::s3fnet::TCPSession::process_ACK(), and s3f::s3fnet::TCPSession::process_acks().
 { return start_seqno+used_size+syn_included+fin_included; }
uint32 s3f::s3fnet::TCPSeqWindow::expect () inline inherited
Like start method, but also uses SYN & FIN segments; the method is used for receiving window.
Definition at line 130 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::fin_included, s3f::s3fnet::TCPSeqWindow::start_seqno, and s3f::s3fnet::TCPSeqWindow::syn_included.
Referenced by s3f::s3fnet::TCPSession::abort(), s3f::s3fnet::TCPSession::appl_close(), s3f::s3fnet::TCPRecvWindow::available(), s3f::s3fnet::TCPSession::fastTimeoutHandling(), s3f::s3fnet::TCPRecvWindow::generate(), s3f::s3fnet::TCPRecvWindow::getExpectedSeqno(), s3f::s3fnet::TCPSession::init_state_fin_wait_1(), s3f::s3fnet::TCPSession::init_state_last_ack(), s3f::s3fnet::TCPSession::init_state_syn_received(), s3f::s3fnet::TCPSession::init_state_syn_sent(), s3f::s3fnet::TCPSession::process_ACK(), s3f::s3fnet::TCPSession::resend_segments(), s3f::s3fnet::TCPSession::segment_and_send(), s3f::s3fnet::TCPSession::slow_timeout_handling_helper(), and s3f::s3fnet::TCPSession::timeout_resend().
 { return start_seqno+syn_included+fin_included; }
bool s3f::s3fnet::TCPSeqWindow::within (uint32 seqno) inline inherited
Returns true iff 'seqno' is within the window.
Definition at line 137 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::fin_included, s3f::s3fnet::TCPSeqWindow::start_seqno, s3f::s3fnet::TCPSeqWindow::syn_included, and s3f::s3fnet::TCPSeqWindow::win_size.
Referenced by s3f::s3fnet::TCPSession::process_new_data().
   {
     return (start_seqno+syn_included+fin_included <= seqno &&
             seqno < start_seqno+syn_included+fin_included+win_size);
   }
bool s3f::s3fnet::TCPSeqWindow::isUsed (uint32 seqno) inline inherited
Returns true iff 'seqno' is used within the window.
Definition at line 144 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::start_seqno, and s3f::s3fnet::TCPSeqWindow::used_size.
   {
     return (start_seqno <= seqno && seqno < start_seqno + used_size);
   }
bool s3f::s3fnet::TCPSeqWindow::empty () inline inherited
Returns true iff the window is empty (nothing used).
Definition at line 150 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::used_size.
Referenced by s3f::s3fnet::TCPSession::appl_close(), s3f::s3fnet::TCPSession::init_state_close_wait(), s3f::s3fnet::TCPSession::init_state_closing(), s3f::s3fnet::TCPSession::init_state_fin_wait_1(), s3f::s3fnet::TCPSession::process_FIN(), and s3f::s3fnet::TCPSession::receive().
 { return (used_size == 0); }
void s3f::s3fnet::TCPSeqWindow::seq_shift (uint32 offset) inline protected inherited
Shift the window by the given offset permanently.
Definition at line 157 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::start_seqno.
Referenced by s3f::s3fnet::TCPSeqWindow::setFIN(), and s3f::s3fnet::TCPSeqWindow::setSYN().
 { start_seqno += offset; }
Member Data Documentation
uint32 s3f::s3fnet::TCPSendWindow::buffer_size protected
Buffer size.
Definition at line 86 of file tcp_sndwnd.h.
Referenced by add_to_buffer(), bufferSize(), and freeInBuffer().
uint32 s3f::s3fnet::TCPSendWindow::length_in_buffer protected
How many bytes are in the buffer waiting to be sent out?
Definition at line 89 of file tcp_sndwnd.h.
Referenced by add_to_buffer(), canSend(), dataInBuffer(), freeInBuffer(), generate(), release_buffer(), and reset().
uint32 s3f::s3fnet::TCPSendWindow::length_in_request protected
How many bytes are waiting to enter the buffer?
Definition at line 92 of file tcp_sndwnd.h.
Referenced by add_to_buffer(), dataInRequest(), needToRequest(), release(), requestToSend(), and reset().
uint32 s3f::s3fnet::TCPSendWindow::length_buffered protected
How many bytes have been put into the buffer.
Definition at line 95 of file tcp_sndwnd.h.
Referenced by add_to_buffer(), clearDataBuffered(), and dataBuffered().
DataChunk* s3f::s3fnet::TCPSendWindow::head_chunk protected
Point to the head of the message list.
Definition at line 98 of file tcp_sndwnd.h.
Referenced by generate(), release_buffer(), requestToSend(), reset(), and ~TCPSendWindow().
DataChunk* s3f::s3fnet::TCPSendWindow::tail_chunk protected
Point to the tail of the message list.
Definition at line 101 of file tcp_sndwnd.h.
Referenced by release_buffer(), requestToSend(), and reset().
byte* s3f::s3fnet::TCPSendWindow::first_raw_data protected
The pointer to the message block.
When some data gets acknowledged, if the data contains real data, we have to release them. Obviously, a naive way is to new a smaller block data and move the left unacknowledged data to it. Instead, in order to optimize the performance, we simply keep a pointer as the offset to the raw message. If the first whole block is released, we can delete this raw message.
Definition at line 112 of file tcp_sndwnd.h.
Referenced by release_buffer(), requestToSend(), reset(), and ~TCPSendWindow().
uint32 s3f::s3fnet::TCPSeqWindow::start_seqno protected inherited
Starting sequence number of the window.
Definition at line 161 of file tcp_seqwnd.h.
Referenced by s3f::s3fnet::TCPSeqWindow::end(), s3f::s3fnet::TCPSeqWindow::expect(), s3f::s3fnet::TCPSeqWindow::firstUnused(), s3f::s3fnet::TCPSeqWindow::isUsed(), s3f::s3fnet::TCPSeqWindow::lengthTo(), s3f::s3fnet::TCPSeqWindow::next(), s3f::s3fnet::TCPSeqWindow::seq_shift(), s3f::s3fnet::TCPSeqWindow::setStart(), s3f::s3fnet::TCPSeqWindow::shift(), s3f::s3fnet::TCPSeqWindow::start(), and s3f::s3fnet::TCPSeqWindow::within().
uint32 s3f::s3fnet::TCPSeqWindow::win_size protected inherited
Size of the window in bytes.
Definition at line 164 of file tcp_seqwnd.h.
Referenced by s3f::s3fnet::TCPRecvWindow::bufferSize(), s3f::s3fnet::TCPSeqWindow::end(), s3f::s3fnet::TCPSeqWindow::expand(), s3f::s3fnet::TCPRecvWindow::freeInBuffer(), s3f::s3fnet::TCPSeqWindow::shrink(), s3f::s3fnet::TCPSeqWindow::size(), s3f::s3fnet::TCPSeqWindow::unused(), s3f::s3fnet::TCPSeqWindow::use(), and s3f::s3fnet::TCPSeqWindow::within().
uint32 s3f::s3fnet::TCPSeqWindow::used_size protected inherited
How many bytes are used in window.
Definition at line 167 of file tcp_seqwnd.h.
Referenced by s3f::s3fnet::TCPSeqWindow::empty(), s3f::s3fnet::TCPSeqWindow::finAtFront(), s3f::s3fnet::TCPSeqWindow::firstUnused(), s3f::s3fnet::TCPSeqWindow::isUsed(), s3f::s3fnet::TCPSeqWindow::next(), s3f::s3fnet::TCPSeqWindow::reset(), s3f::s3fnet::TCPSeqWindow::setSYN(), s3f::s3fnet::TCPSeqWindow::shift(), s3f::s3fnet::TCPSeqWindow::shrink(), s3f::s3fnet::TCPSeqWindow::unused(), s3f::s3fnet::TCPSeqWindow::use(), and s3f::s3fnet::TCPSeqWindow::used().
int s3f::s3fnet::TCPSeqWindow::syn_included protected inherited
Whether SYN is in window.
Definition at line 170 of file tcp_seqwnd.h.
Referenced by s3f::s3fnet::TCPSeqWindow::expect(), s3f::s3fnet::TCPSeqWindow::next(), s3f::s3fnet::TCPSeqWindow::reset(), s3f::s3fnet::TCPSeqWindow::setSYN(), s3f::s3fnet::TCPSeqWindow::synAtFront(), and s3f::s3fnet::TCPSeqWindow::within().
int s3f::s3fnet::TCPSeqWindow::fin_included protected inherited
Whether FIN is in window.
Definition at line 173 of file tcp_seqwnd.h.
Referenced by s3f::s3fnet::TCPSeqWindow::expect(), s3f::s3fnet::TCPSeqWindow::finAtFront(), s3f::s3fnet::TCPSeqWindow::next(), s3f::s3fnet::TCPSeqWindow::reset(), s3f::s3fnet::TCPSeqWindow::setFIN(), and s3f::s3fnet::TCPSeqWindow::within().
The documentation for this class was generated from the following files:
tcp_sndwnd.h
tcp_sndwnd.cc