S3F: s3f::s3fnet::TrieData Class Reference
s3f::s3fnet::TrieData Class Reference abstract
A generic data type for data stored in trie.
#include <trie.h>
Public Member Functions
virtual ~TrieData ()
The virtual destructor does nothing here.
virtual int size ()=0
returns size in bytes
bool equiv (TrieData *td)
Compares this TrieData instance to another.
TrieData * clone ()
Duplicates the TrieData instance.
Protected Member Functions
virtual char * toByteArray ()
transform the structure into a byte array of length size()
Detailed Description
A generic data type for data stored in trie.
This class is used by the Trie class as a base class to store data.
Definition at line 48 of file trie.h.
Constructor & Destructor Documentation
virtual s3f::s3fnet::TrieData::~TrieData () inline virtual
The virtual destructor does nothing here.
Definition at line 51 of file trie.h.
 {};
Member Function Documentation
virtual int s3f::s3fnet::TrieData::size () pure virtual
returns size in bytes
Implemented in s3f::s3fnet::RouteInfo.
Referenced by s3f::s3fnet::tda0::TrieDataArray0::addElement(), clone(), and equiv().
virtual char* s3f::s3fnet::TrieData::toByteArray () inline protected virtual
transform the structure into a byte array of length size()
Definition at line 58 of file trie.h.
Referenced by clone(), and equiv().
{
         return (char*)this;
   }
bool s3f::s3fnet::TrieData::equiv (TrieData * td) inline
Compares this TrieData instance to another.
Parameters
td the TrieData reference to compare with.
Returns
true if data is identical, otherwise false
Definition at line 68 of file trie.h.
References size(), and toByteArray().
Referenced by s3f::s3fnet::tda2::TrieDataArray2::addElement(), s3f::s3fnet::trie2::Trie2::insert(), and s3f::s3fnet::trie3::Trie3::insert().
{
         if(size() != td->size()) {
                 return false;
         }
         int i;
         char* selfarray = toByteArray();
         char* tdarray = td->toByteArray();
         for(i=0;i<size();i++) {
                 if(selfarray[i] != tdarray[i]) {
                         return false;
                 }
         }
         return true;
   }
TrieData* s3f::s3fnet::TrieData::clone () inline
Duplicates the TrieData instance.
Creates another TrieData instance containing identical data. Relies on the toByteArray() virtual method but is not, itself, virtual.
See Also
toByteArray()
Returns
(deep) copy of the current TrieData
Definition at line 91 of file trie.h.
References size(), and toByteArray().
Referenced by s3f::s3fnet::tda2::TrieDataArray2::removeElement().
                     {
         int s = size();
         int i;
         char* temp = new char[s];
         memcpy((void*)temp,toByteArray(),s);
         return (TrieData*)temp;
   }
The documentation for this class was generated from the following file:
trie.h