S3F: s3f::s3fnet::DMLRouteInfo Class Reference
s3f::s3fnet::DMLRouteInfo Class Reference
ROUTE and NHI_ROUTE attributes from DML.
#include <forwardingtable.h>
Public Member Functions
DMLRouteInfo ()
The constructor.
~DMLRouteInfo ()
The destructor.
void config (s3f::dml::Configuration *cfg)
Read the NHI_ROUTE attribute from the DML file.
RouteInfo * resolve (Host *machine)
This method translates the nhi address read from the DML file to the corresponding ip address.
Public Attributes
bool dst_ip
Indicates whether dst_str is an IP or NHI.
char * dst_str
The character string of the destination NHI.
char * nexthop_str
The character string of the next hop NHI.
int iface_id
The network interface id.
int cost
The cost of this routing entry.
int protocol
The protocol that installs this routing entry.
Detailed Description
ROUTE and NHI_ROUTE attributes from DML.
The ROUTE and NHI_ROUTE attributes will be eventually converted to RouteInfo and inserted into the forwarding table.
Definition at line 123 of file forwardingtable.h.
Constructor & Destructor Documentation
s3f::s3fnet::DMLRouteInfo::DMLRouteInfo () inline
The constructor.
Definition at line 126 of file forwardingtable.h.
                  :
     dst_ip(false),dst_str(0), nexthop_str(0), iface_id(0), cost(1),
     protocol(RouteInfo::STATIC) {}
s3f::s3fnet::DMLRouteInfo::~DMLRouteInfo () inline
The destructor.
Definition at line 131 of file forwardingtable.h.
References dst_str, and nexthop_str.
                   {
     if(dst_str) delete[] dst_str;
     if(nexthop_str) delete[] nexthop_str;
   }
Member Function Documentation
void s3f::s3fnet::DMLRouteInfo::config (s3f::dml::Configuration * cfg)
Read the NHI_ROUTE attribute from the DML file.
Definition at line 427 of file forwardingtable.cc.
References cost, dst_ip, dst_str, s3f::s3fnet::RouteInfo::EGP, s3f::s3fnet::error_quit(), iface_id, s3f::s3fnet::RouteInfo::IGP, nexthop_str, s3f::s3fnet::RouteInfo::PAO, protocol, s3f::s3fnet::sstrdup(), and s3f::s3fnet::RouteInfo::STATIC.
Referenced by s3f::s3fnet::Host::config(), and s3f::s3fnet::IPSession::load_forwarding_table().
 {
   // read destination
   char* dest_string = (char*)cfg->findSingle("dest");
   if(!dest_string) {
         dest_string = (char*)cfg->findSingle("destip");
         if(!dest_string) {
                 error_quit("ERROR: DMLRouteInfo::config(), "
                    "missing or invalid DEST attribute.\n");
         }
         dst_ip = true;
   }
   if(s3f::dml::dmlConfig::isConf(dest_string)) {
     error_quit("ERROR: DMLRouteInfo::config(), "
                "missing or invalid DEST attribute.\n");
   }
   dst_str = sstrdup(dest_string);
   // read interface
   char* itrf_string = (char*)cfg->findSingle("interface");
   if(!itrf_string || s3f::dml::dmlConfig::isConf(itrf_string))
     error_quit("ERROR: DMLRouteInfo::config(), "
                "missing or invalid INTERFACE attribute.\n");
   iface_id = atoi(itrf_string);
   // read next hop
   char* nexthop_string = (char*)cfg->findSingle("next_hop");
   if(nexthop_string) {
     if(s3f::dml::dmlConfig::isConf(nexthop_string))
       error_quit("ERROR: DMLRouteInfo::config(), "
                  "invalid NEXT_HOP attribute.\n");
     nexthop_str = sstrdup(nexthop_string);
   }
   char* str = (char*)cfg->findSingle("cost");
   if(str) {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: DMLRouteInfo::config(), "
                  "invalid COST attribute.\n");
     cost = atoi(str);
   } else {
     if(!strcasecmp(dst_str, "default"))
       cost = 0x7ffffff; // default route has highest cost
     else cost = 1;
   }
   str = (char*)cfg->findSingle("protocol");
   if(str) {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: DMLRouteInfo::config(), "
                  "invalid PROTOCOL attribute.\n");
     if(!strncmp(str, "STATIC", 6)) {
       protocol = RouteInfo::STATIC;
     } else if (!strncmp(str, "IGP", 3)) {
       protocol = RouteInfo::IGP;
     } else if (!strncmp(str, "EGP", 3)) {
       protocol = RouteInfo::EGP;
 #ifdef S3FNET_PAO_ROUTING
     } else if (!strncmp(str, "PAO", 3)) {
       protocol = RouteInfo::PAO;
 #endif
     } else {
       error_quit("ERROR: DMLRouteInfo::config(), "
                  "invalid PROTOCOL: \"%s\".\n", str);
     }
   } else protocol = RouteInfo::STATIC;
 }
RouteInfo * s3f::s3fnet::DMLRouteInfo::resolve (Host * machine)
This method translates the nhi address read from the DML file to the corresponding ip address.
If successful, the method returns a newly created RouteInfo object.
Definition at line 495 of file forwardingtable.cc.
References s3f::s3fnet::IPPrefix::addr, s3f::s3fnet::RouteInfo::cost, cost, s3f::s3fnet::RouteInfo::destination, s3f::s3fnet::Link::display(), dst_ip, dst_str, s3f::s3fnet::error_retn(), s3f::s3fnet::NetworkInterface::getIP(), s3f::s3fnet::NetworkInterface::getLink(), s3f::s3fnet::Net::getNameService(), s3f::s3fnet::Host::getNetworkInterface(), s3f::s3fnet::Link::getNetworkInterfaces(), s3f::s3fnet::Link::getNumOfNetworkInterface(), iface_id, s3f::s3fnet::Host::inNet(), IPADDR_INVALID, s3f::s3fnet::IPPrefix::len, s3f::s3fnet::DmlObject::myParent, s3f::s3fnet::RouteInfo::next_hop, nexthop_str, s3f::s3fnet::DmlObject::nhi, s3f::s3fnet::NameService::nhi2ip(), s3f::s3fnet::RouteInfo::nic, s3f::s3fnet::RouteInfo::protocol, protocol, s3f::s3fnet::RouteInfo::resolved, s3f::s3fnet::Nhi::toStlString(), s3f::s3fnet::Nhi::toString(), and s3f::s3fnet::IPPrefix::txt2ip().
Referenced by s3f::s3fnet::IPSession::control().
 {
   RouteInfo* route = new RouteInfo;
   // resolve destination.
   if(!strcasecmp(dst_str, "default")) {
     // make this a default route.
     route->destination.addr = 0;
     route->destination.len = 0;
   } else if(!dst_ip) { // we only assume that dst_str is an nic nhi address
     // start with an invalid address
     route->destination.addr = IPADDR_INVALID;
     // if it's not started with a colon, we first assume we are given
     // a relative nhi address
     if(dst_str[0] != ':') {
       S3FNET_STRING abs_addr = machine->myParent->nhi.toStlString();
       if(abs_addr.size() > 0) abs_addr += ":";
       abs_addr += dst_str;
       NameService* namesvc = machine->inNet()->getNameService();
       route->destination.addr = namesvc->nhi2ip(abs_addr);
     }
     // if it's still unresolved, we assume it's an absolute address
     if(IPADDR_INVALID == route->destination.addr) {
       if(dst_str[0] != ':')
       {
         NameService* namesvc = machine->inNet()->getNameService();
             route->destination.addr = namesvc->nhi2ip(S3FNET_STRING(dst_str));
       }
       else
       {
             // we need to strip off the first colon if necessary
         NameService* namesvc = machine->inNet()->getNameService();
             route->destination.addr = namesvc->nhi2ip(S3FNET_STRING(&dst_str[1]));
       }
     }
     // if it's still unresolved, it's an invalid address
     if(IPADDR_INVALID == route->destination.addr) {
       error_retn("WARNING: DMLRouteInfo::resolve(), "
                  "invalid destination nhi: \"%s\".\n", dst_str);
       delete route;
       return 0;
     }
     route->destination.len = 32; // what else should be here?
   } else { // dst_str is a CIDR IP
         // TODO: Check that this is a valid destination IP (properly resolve at least 1 address in the mask)
         route->destination.addr = IPPrefix::txt2ip(dst_str,&(route->destination.len));
   }
   route->cost = cost;
   route->protocol = protocol;
   // resolve the outgoing interface
   route->nic = machine->getNetworkInterface(iface_id);
   if(!route->nic) {
     error_retn("WARNING: DMLRouteInfo::resolve(), "
                "interface %d cannot be resolved at host %s.\n",
                iface_id, machine->nhi.toStlString().c_str());
     delete route;
     return 0;
   }
   Link* link = (Link*)route->nic->getLink();
   if(!link) {
     error_retn("WARNING: DMLRouteInfo::resolve() interface %d is not attached at host %s.\n",
                iface_id, machine->nhi.toStlString().c_str());
     delete route;
     return 0;
   }
   // resolve the nexthop address
   if(!nexthop_str) {
     // nic must have just 1 peer so that the next_hop is only the peer
     int num_link_itrfs = 0;
     //link->getInterfaces(machine->getCommunity(), num_link_itrfs);
     num_link_itrfs = link->getNumOfNetworkInterface();
     // Currently, if the link is a LAN link, we must specify next hop address in the
     // dml file. Otherwise, we always use a default value:
     if(num_link_itrfs > 2) {
       link->display();
       error_retn("WARNING: DMLRouteInfo::resolve(), "
                  "next_hop must be specified for interfaces on LAN links!\n");
       delete route;
       return 0;
     }
     // get the other ip address to be the next hop address
     //S3FNET_STRING_VECTOR& v = link->getIfaceNhis();
     vector<NetworkInterface*> ifaces = link->getNetworkInterfaces();
     IPADDR local_ip = route->nic->getIP();
     for(unsigned i = 0; i < ifaces.size(); i++)
     {
       route->next_hop = ifaces[i]->getIP();
       if(route->next_hop != local_ip) break;
     }
   }
   else {
     // translate the next_hop nhi string to ip address; note that
     // next_hop must be linked with this interface
     // we use abs_addr to be the absolution nhi address and the
     // nexthop_str to be the relative one
     S3FNET_STRING abs_addr;
     if(nexthop_str[0] == ':') {
       // next hop starts with a colon; it's an absolute nhi address
       abs_addr = S3FNET_STRING(&nexthop_str[1]);
     } else {
       // we assume nexthop_str is the relative nhi address
       abs_addr = machine->myParent->nhi.toStlString();
       if(abs_addr.size() > 0) abs_addr += ":";
       abs_addr += nexthop_str;
     }
     //S3FNET_STRING_VECTOR& v = link->getIfaceNhis();
     vector<NetworkInterface*> ifaces = link->getNetworkInterfaces();
     bool found = false; int i;
     // we first assume it's relative
     for(i=0; i<(int)ifaces.size(); i++)
     {
       if(ifaces[i]->nhi.toStlString() == abs_addr)
       {
           route->next_hop = ifaces[i]->getIP();
           found = true;
           break;
       }
     }
     // if it's still unresolved, we assume it's absolute (unless it
     // starts with colon, in which case we already tested at the
     // previous step
     if(!found && nexthop_str[0] != ':')
     {
       for(i=0; i<(int)ifaces.size(); i++)
       {
           if(ifaces[i]->nhi.toStlString() == S3FNET_STRING(nexthop_str))
           {
                   route->next_hop = ifaces[i]->getIP();
                   found = true;
                   break;
           }
       }
     }
     if(!found || IPADDR_INVALID == route->next_hop)
     {
       //for(i=0; i<v.size(); i++) printf("%s\n", v[i].c_str());
       error_retn("ERROR: DMLRouterInfo::resolve(), invalid next_hop \"%s\" for host \"%s\"\n",
                  nexthop_str, machine->nhi.toString());
       delete route;
       return 0;
     }
   }
   route->resolved = true;
   return route;
 }
Member Data Documentation
bool s3f::s3fnet::DMLRouteInfo::dst_ip
Indicates whether dst_str is an IP or NHI.
Definition at line 148 of file forwardingtable.h.
Referenced by config(), and resolve().
char* s3f::s3fnet::DMLRouteInfo::dst_str
The character string of the destination NHI.
Definition at line 151 of file forwardingtable.h.
Referenced by config(), resolve(), and ~DMLRouteInfo().
char* s3f::s3fnet::DMLRouteInfo::nexthop_str
The character string of the next hop NHI.
Definition at line 154 of file forwardingtable.h.
Referenced by config(), resolve(), and ~DMLRouteInfo().
int s3f::s3fnet::DMLRouteInfo::iface_id
The network interface id.
Definition at line 157 of file forwardingtable.h.
Referenced by config(), and resolve().
int s3f::s3fnet::DMLRouteInfo::cost
The cost of this routing entry.
Definition at line 160 of file forwardingtable.h.
Referenced by config(), and resolve().
int s3f::s3fnet::DMLRouteInfo::protocol
The protocol that installs this routing entry.
Definition at line 163 of file forwardingtable.h.
Referenced by config(), and resolve().
The documentation for this class was generated from the following files:
forwardingtable.h
forwardingtable.cc