S3F: s3f::s3fnet::TrieDataArray Class Reference
s3f::s3fnet::TrieDataArray Class Reference abstract
Abstract base class for storing coalesced TrieData sets.
#include <trie.h>
Public Types
enum TrieDataArrayType {
UNCOALESCED = 0, UNCOALESCED_MAP = 1, NAIVE = 2, HASHED = 3,
FAST_HASHED = 4
}
Enum listing the types of TrieDataArrays available.
Public Member Functions
virtual unsigned int addElement (TrieData *data)=0
Adds the given TrieData to the array.
virtual TrieData * getElement (unsigned int index)=0
Gets the element at 'index' Pure virtual method to get elements from the array.
virtual TrieData * removeElement (unsigned int index, bool get=false)=0
Remove element at 'index' from the array.
Detailed Description
Abstract base class for storing coalesced TrieData sets.
Existence of this class adds an extra memory reference to each lookup due to base-class pointer-casting in implementing Tries. As such, this should be used primarily for testing with Tries designed for such, then the best implementation(s) should be directly added as their own Trie implementation.
All types are implicitly maps (vs actual arrays) since they store pointers unless there is an explicit _MAP type with the same name.
Is pure-virtual. Derived classes must add their own member array/list/etc. This allows subclasses to choose stack-based or ptr-based storage as desired.
Definition at line 189 of file trie.h.
Member Enumeration Documentation
enum s3f::s3fnet::TrieDataArray::TrieDataArrayType
Enum listing the types of TrieDataArrays available.
Enumerator
UNCOALESCED
Every object in the Trie has a unique array entry.
UNCOALESCED_MAP
Stores references instead of the actual data.
NAIVE, HASHED, and FAST_HASHED are based on this for ease of implementation.
NAIVE
Multiple nodes in the Trie may map to the same (identical) TrieData entry in the array to save space.
HASHED
Expands on NAIVE using hashing to quickly find the correct entry in the array.
FAST_HASHED
Sacrifices storage in some cases for faster lookup speed by allowing some duplicate entries in the array.
Definition at line 194 of file trie.h.
{
                 UNCOALESCED = 0,
                 UNCOALESCED_MAP = 1,
                 NAIVE = 2,
                 HASHED = 3,
                 FAST_HASHED = 4
         };
Member Function Documentation
virtual unsigned int s3f::s3fnet::TrieDataArray::addElement (TrieData * data) pure virtual
Adds the given TrieData to the array.
Pure virtual method to add elements to the TrieDataArray.
Parameters
data reference to insert and/or copy (depending on implementation)
Returns
the index at which the data is stored
Referenced by s3f::s3fnet::trie4::Trie4::create(), and s3f::s3fnet::trie4::Trie4::insert().
virtual TrieData* s3f::s3fnet::TrieDataArray::getElement (unsigned int index) pure virtual
Gets the element at 'index' Pure virtual method to get elements from the array.
Parameters
index array index of the element to get
Returns
TrieData reference to the element
Referenced by s3f::s3fnet::trie4::Trie4::getDefault(), and s3f::s3fnet::trie4::Trie4::lookup().
virtual TrieData* s3f::s3fnet::TrieDataArray::removeElement (unsigned int index, bool get = false) pure virtual
Remove element at 'index' from the array.
Pure virtual method to remove elements from the array.
Parameters
index array index of the element to remove
get whether to return the removed element or just remove it
Returns
a copy of removed element if 'get' is true, else returns NULL.
Referenced by s3f::s3fnet::trie4::Trie4::insert(), and s3f::s3fnet::trie4::Trie4::remove().
The documentation for this class was generated from the following file:
trie.h