S3F: s3f::s3fnet::UDPSession Class Reference
s3f::s3fnet::UDPSession Class Reference
The UDP session.
#include <udp_session.h>
Public Member Functions
UDPSession (UDPMaster *master, int sock)
The constructor.
virtual ~UDPSession ()
The destructor.
virtual bool connect (IPADDR destip, uint16 destport)
Connect to a destination ip address and port number.
virtual void disconnect ()
Disconnect this session.
virtual int send (int length, byte *msg=0)
Send the given number of bytes.
virtual int recv (int length, byte *msg=0)
Receive a message of the given size.
virtual bool listen ()
Passive open.
virtual bool connected ()
Whether a connection is made.
virtual bool setSource (IPADDR ip, uint16 port)
Set the ip and the port number of the connection.
virtual void abort ()
Abort the session.
virtual void setSocketID (int sock)
Set socket.
virtual SessionMaster * getSessionMaster ()
Return the master protocol session.
virtual void release ()
Release this session if unnecessary.
void receive (UDPMessage *udphdr)
Receive the message popped up from the ip session.
virtual void reinit ()
Called by socket to reinitialize the destination ip and port.
char * toString (char *buf)
Translate the ID into a textual string.
Public Attributes
uint32 prot_id
The protocol number.
IPADDR src_ip
Source ip address.
IPADDR dst_ip
Destination ip address.
uint16 src_port
Source port number.
uint16 dst_port
Destination port number.
Private Member Functions
void wake_app (int signal)
Wake up the application on a signal.
void clear_app_state (int signal)
Clear a specific signal bit from application.
int generate (int length, byte *msg)
Copy the received messages into the user receive buffer of the given size.
S3FNET_DEQUE (DataMessage *) rcvbuf
The receive buffer to store the received messages.
Private Attributes
UDPMaster * udp_master
Point to the udp master.
int socket
The socket id.
bool is_connected
Whether the UDP session has been connected.
int rcvbuf_len
The total number of bytes stored in the receive buffer.
int rcvbuf_offset
Offset to the first message in the receive buffer, which points to the byte to be transferred next to the application.
byte * appl_rcvbuf
The buffer (owned by application) to receive data.
uint32 appl_rcvbuf_size
Total number of bytes expected to receive.
uint32 appl_data_rcvd
The size of the received data (that has been put into the receive buffer).
Detailed Description
The UDP session.
Definition at line 24 of file udp_session.h.
Constructor & Destructor Documentation
s3f::s3fnet::UDPSession::UDPSession (UDPMaster * master, int sock)
The constructor.
Definition at line 24 of file udp_session.cc.
References s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::DmlObject::nhi, s3f::s3fnet::Nhi::toString(), UDP_DUMP, and udp_master.
                                                   :
   SocketSession(S3FNET_PROTOCOL_TYPE_UDP),
   udp_master(master), socket(sock), is_connected(false),
   rcvbuf_len(0), rcvbuf_offset(0),
   appl_rcvbuf(0), appl_rcvbuf_size(0), appl_data_rcvd(0)
 {
   UDP_DUMP(printf("[host=\"%s\"] %s: new udp session.\n",
                   udp_master->inHost()->nhi.toString(),
                   udp_master->getNowWithThousandSeparator()));
 }
s3f::s3fnet::UDPSession::~UDPSession () virtual
The destructor.
Definition at line 35 of file udp_session.cc.
 {
   /*UDP_DUMP(printf("delete udp session on host \"%s\".\n",
     udp_master->inHost()->nhi.toString()));*/
 }
Member Function Documentation
bool s3f::s3fnet::UDPSession::connect (IPADDR destip, uint16 destport) virtual
Connect to a destination ip address and port number.
Returns true if the connection has been established successfuly.
Implements s3f::s3fnet::SocketSession.
Definition at line 41 of file udp_session.cc.
References s3f::s3fnet::SessionID::dst_ip, s3f::s3fnet::SessionID::dst_port, s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::IPPrefix::ip2txt(), is_connected, s3f::s3fnet::DmlObject::nhi, s3f::s3fnet::SocketSignal::OK_TO_SEND, socket, s3f::s3fnet::Nhi::toString(), UDP_DUMP, udp_master, and wake_app().
 {
   UDP_DUMP(printf("[host=\"%s\"] %s: connect(), socket %d, dest_ip=\"%s\", dest_port=%d.\n",
                   udp_master->inHost()->nhi.toString(),
                   udp_master->getNowWithThousandSeparator(), socket,
                   IPPrefix::ip2txt(destip), destport));
   // UDP is connectionless protocol; we simple set the destination ip
   // and port number to make a complete address of the peer
   dst_ip = destip;
   dst_port = destport;
   is_connected = true;
   wake_app(SocketSignal::OK_TO_SEND);
   return true;
 }
void s3f::s3fnet::UDPSession::disconnect () virtual
Disconnect this session.
Implements s3f::s3fnet::SocketSession.
Definition at line 58 of file udp_session.cc.
References s3f::s3fnet::SocketSignal::CONN_CLOSED, s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::inHost(), is_connected, s3f::s3fnet::DmlObject::nhi, s3f::s3fnet::SocketSignal::SESSION_RELEASED, socket, s3f::s3fnet::Nhi::toString(), UDP_DUMP, udp_master, and wake_app().
 {
   UDP_DUMP(printf("[host=\"%s\"] %s: disconnect(), socket %d.\n",
                   udp_master->inHost()->nhi.toString(),
                   udp_master->getNowWithThousandSeparator(), socket));
   is_connected = false;
   wake_app(SocketSignal::CONN_CLOSED | SocketSignal::SESSION_RELEASED);
 }
int s3f::s3fnet::UDPSession::send (int length, byte * msg = 0) virtual
Send the given number of bytes.
The msg parameter, if not NULL, points to the message storage. The method returns the number of bytes that have truly been sent out. -1 means error.
Implements s3f::s3fnet::SocketSession.
Definition at line 144 of file udp_session.cc.
References s3f::s3fnet::ProtocolMessage::carryPayload(), DEFAULT_IP_TIMETOLIVE, s3f::s3fnet::SessionID::dst_ip, s3f::s3fnet::SessionID::dst_port, s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::UDPMaster::max_datagram_size, mymin, s3f::s3fnet::DmlObject::nhi, s3f::s3fnet::SocketSignal::OK_TO_SEND, s3f::s3fnet::ProtocolSession::pushdown(), s3f::s3fnet::S3FNET_PROTOCOL_TYPE_UDP, s3f::s3fnet::SessionID::src_ip, s3f::s3fnet::SessionID::src_port, s3f::s3fnet::Nhi::toString(), UDP_DUMP, udp_master, and wake_app().
 {
   int offset = 0;
   while(offset < length) // if there's anything left to be sent
   {
     int to_send = mymin(udp_master->max_datagram_size, length-offset);
     UDP_DUMP(printf("[host=\"%s\"] %s: send(length=%d), send a message of %d bytes, offset=%d.\n",
                     udp_master->inHost()->nhi.toString(),
                     udp_master->getNowWithThousandSeparator(), length, to_send, offset));
     DataMessage* dmsg;
     if(msg) dmsg = new DataMessage(to_send, &msg[offset], true);
     else dmsg = new DataMessage(to_send);
     offset += to_send;
     UDPMessage* udphdr = new UDPMessage(src_port, dst_port);
     udphdr->carryPayload(dmsg);
     Activation ac(udphdr);
     IPPushOption ops(src_ip, dst_ip, S3FNET_PROTOCOL_TYPE_UDP, DEFAULT_IP_TIMETOLIVE);
     udp_master->pushdown(ac, 0, (void*)&ops, sizeof(IPPushOption));
   }
   wake_app(SocketSignal::OK_TO_SEND);
   return length;
 }
int s3f::s3fnet::UDPSession::recv (int length, byte * msg = 0) virtual
Receive a message of the given size.
The msg parameter, if not NULL, points to the buffer to store the message. The method returns the number of bytes that have been truly received. -1 means error.
Implements s3f::s3fnet::SocketSession.
Definition at line 171 of file udp_session.cc.
References appl_rcvbuf, appl_rcvbuf_size, clear_app_state(), s3f::s3fnet::SocketSignal::DATA_AVAILABLE, and generate().
 {
   assert(length > 0);
   uint32 got = generate(length, msg);
   if(got == 0)
   {
     // if no data available, the socket will be suspended waiting for
     // the DATA_AVAILABLE signal, we set the receive parameters so
     // that the socket will be notified when message arrives
     assert(appl_rcvbuf == 0 && appl_rcvbuf_size == 0);
     appl_rcvbuf = msg;
     appl_rcvbuf_size = length;
     clear_app_state(SocketSignal::DATA_AVAILABLE);
   }
   return got;
 }
bool s3f::s3fnet::UDPSession::listen () virtual
Passive open.
Returns true if there is an incoming connection that has been established successfully.
Implements s3f::s3fnet::SocketSession.
Definition at line 68 of file udp_session.cc.
References s3f::s3fnet::SocketSignal::FIRST_CONNECTION, s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::inHost(), is_connected, s3f::s3fnet::DmlObject::nhi, socket, s3f::s3fnet::Nhi::toString(), UDP_DUMP, udp_master, and wake_app().
 {
   UDP_DUMP(printf("[host=\"%s\"] %s: listen(), socket %d.\n",
                   udp_master->inHost()->nhi.toString(),
                   udp_master->getNowWithThousandSeparator(), socket));
   is_connected = true;
   wake_app(SocketSignal::FIRST_CONNECTION);
   return true;
 }
bool s3f::s3fnet::UDPSession::connected () virtual
Whether a connection is made.
Returns true if connected.
Implements s3f::s3fnet::SocketSession.
Definition at line 79 of file udp_session.cc.
References is_connected.
 {
   return is_connected;
 }
bool s3f::s3fnet::UDPSession::setSource (IPADDR ip, uint16 port) virtual
Set the ip and the port number of the connection.
Returns true if set up correctly.
Implements s3f::s3fnet::SocketSession.
Definition at line 84 of file udp_session.cc.
References s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::IPPrefix::ip2txt(), s3f::s3fnet::DmlObject::nhi, socket, s3f::s3fnet::SessionID::src_ip, s3f::s3fnet::SessionID::src_port, s3f::s3fnet::Nhi::toString(), UDP_DUMP, and udp_master.
 {
   UDP_DUMP(printf("[host=\"%s\"] %s: setSource(), socket %d, src_ip=\"%s\", src_port=%d.\n",
                   udp_master->inHost()->nhi.toString(),
                   udp_master->getNowWithThousandSeparator(), socket, IPPrefix::ip2txt(ip), port));
   src_ip   = ip;
   src_port = port;
   return true;
 }
void s3f::s3fnet::UDPSession::abort () virtual
Abort the session.
Implements s3f::s3fnet::SocketSession.
Definition at line 95 of file udp_session.cc.
References s3f::s3fnet::SocketSignal::CONN_RESET, s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::DmlObject::nhi, socket, s3f::s3fnet::Nhi::toString(), UDP_DUMP, udp_master, and wake_app().
 {
   UDP_DUMP(printf("[host=\"%s\"] %s: abort(), socket %d.\n",
                   udp_master->inHost()->nhi.toString(),
                   udp_master->getNowWithThousandSeparator(), socket));
   wake_app(SocketSignal::CONN_RESET);
 }
virtual void s3f::s3fnet::UDPSession::setSocketID (int sock) inline virtual
Set socket.
Implements s3f::s3fnet::SocketSession.
Definition at line 71 of file udp_session.h.
References socket.
 { socket = sock; }
virtual SessionMaster* s3f::s3fnet::UDPSession::getSessionMaster () inline virtual
Return the master protocol session.
Implements s3f::s3fnet::SocketSession.
Definition at line 74 of file udp_session.h.
References udp_master.
 { return udp_master; }
void s3f::s3fnet::UDPSession::release () virtual
Release this session if unnecessary.
Implements s3f::s3fnet::SocketSession.
Definition at line 104 of file udp_session.cc.
References s3f::s3fnet::ProtocolSession::control(), s3f::s3fnet::UDPMaster::deleteSession(), s3f::s3fnet::SessionMaster::getSocketMaster(), s3f::s3fnet::SOCK_CTRL_DETACH_SESSION, socket, and udp_master.
 {
   /*UDP_DUMP(printf("[host=\"%s\"] %s: release(), socket %d.\n",
     udp_master->inHost()->nhi.toString(),
     udp_master->getNowWithThousandSeparator(), socket));*/
   // detach the udp session from the socket master
   SocketSignal socksig(socket, 0);
   udp_master->getSocketMaster()->control(SOCK_CTRL_DETACH_SESSION, (void*)&socksig, NULL);
   // then remove from the udp master
   udp_master->deleteSession(this);
 }
void s3f::s3fnet::UDPSession::receive (UDPMessage * udphdr)
Receive the message popped up from the ip session.
Definition at line 189 of file udp_session.cc.
References appl_data_rcvd, appl_rcvbuf, appl_rcvbuf_size, s3f::s3fnet::SocketSignal::DATA_AVAILABLE, s3f::s3fnet::ProtocolMessage::dropPayload(), generate(), s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::DmlObject::nhi, rcvbuf_len, s3f::s3fnet::DataMessage::real_length, s3f::s3fnet::DataMessage::realByteCount(), s3f::s3fnet::Nhi::toString(), UDP_DUMP, udp_master, and wake_app().
 {
   DataMessage* dmsg = (DataMessage*)udphdr->dropPayload();
   assert(dmsg && dmsg->real_length > 0);
   rcvbuf.push_back(dmsg);
   rcvbuf_len += dmsg->realByteCount();
   UDP_DUMP(printf("[host=\"%s\"] %s: receive(), incoming %d bytes; order-to-fill %d bytes.\n",
                   udp_master->inHost()->nhi.toString(),
                   udp_master->getNowWithThousandSeparator(), dmsg->realByteCount(),
                   appl_rcvbuf_size));
   if(appl_rcvbuf_size > 0)
   {
     appl_data_rcvd = generate(appl_rcvbuf_size, appl_rcvbuf);
     if(appl_data_rcvd > 0)
     {
       UDP_DUMP(printf("[host=\"%s\"] %s: generated %d bytes.\n",
                       udp_master->inHost()->nhi.toString(),
                       udp_master->getNowWithThousandSeparator(), appl_data_rcvd));
       appl_rcvbuf = 0;
       appl_rcvbuf_size = 0; // reset receive parameters
       wake_app(SocketSignal::DATA_AVAILABLE);
     }
   }
 }
void s3f::s3fnet::UDPSession::wake_app (int signal) private
Wake up the application on a signal.
Definition at line 118 of file udp_session.cc.
References appl_data_rcvd, appl_rcvbuf, appl_rcvbuf_size, s3f::s3fnet::ProtocolSession::control(), s3f::s3fnet::SocketSignal::DATA_AVAILABLE, s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::SessionMaster::getSocketMaster(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::SocketSignal::nbytes, s3f::s3fnet::DmlObject::nhi, s3f::s3fnet::SOCK_CTRL_SET_SIGNAL, socket, s3f::s3fnet::Nhi::toString(), UDP_DUMP, and udp_master.
Referenced by abort(), connect(), disconnect(), listen(), receive(), and send().
 {
   UDP_DUMP(printf("[host=\"%s\"] %s: wake_app(), signal=%08x.\n",
                   udp_master->inHost()->nhi.toString(),
                   udp_master->getNowWithThousandSeparator(), signal));
   SocketSignal socksig(socket, signal);
   if(signal & SocketSignal::DATA_AVAILABLE)
   {
     socksig.nbytes = appl_data_rcvd;
     appl_rcvbuf = 0;
     appl_rcvbuf_size = 0;
   }
   udp_master->getSocketMaster()->control(SOCK_CTRL_SET_SIGNAL, &socksig, NULL);
 }
void s3f::s3fnet::UDPSession::clear_app_state (int signal) private
Clear a specific signal bit from application.
Definition at line 134 of file udp_session.cc.
References s3f::s3fnet::ProtocolSession::control(), s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::SessionMaster::getSocketMaster(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::DmlObject::nhi, s3f::s3fnet::SOCK_CTRL_CLEAR_SIGNAL, socket, s3f::s3fnet::Nhi::toString(), UDP_DUMP, and udp_master.
Referenced by recv().
 {
   UDP_DUMP(printf("[host=\"%s\"] %s: clear_app_state(), signal=%08x.\n",
                   udp_master->inHost()->nhi.toString(),
                   udp_master->getNowWithThousandSeparator(), signal));
   SocketSignal socksig(socket, signal);
   udp_master->getSocketMaster()->control(SOCK_CTRL_CLEAR_SIGNAL, &socksig, NULL);
 }
int s3f::s3fnet::UDPSession::generate (int length, byte * msg) private
Copy the received messages into the user receive buffer of the given size.
Return the number of bytes successfully transferred.
Definition at line 217 of file udp_session.cc.
References s3f::s3fnet::DataMessage::payload, rcvbuf_len, rcvbuf_offset, and s3f::s3fnet::DataMessage::realByteCount().
Referenced by receive(), and recv().
 {
   int rcvd = 0;
   // scan thru the received data blocks
   while(!rcvbuf.empty())
   {
     DataMessage* dmsg = rcvbuf.front();
     // data received not enough to fill application receive buffer
     if(dmsg->realByteCount()-rcvbuf_offset <= length)
     {
       int to_recv = dmsg->realByteCount()-rcvbuf_offset;
       if(msg && dmsg->payload)
       {
         memcpy(&msg[rcvd], (byte*)dmsg->payload+rcvbuf_offset, to_recv);
       }
       rcvbuf_len -= to_recv;
       rcvbuf_offset = 0;
       rcvd += to_recv;
       rcvbuf.pop_front();
       delete dmsg;
       if(to_recv == length) break;
     }
     // the data message contains more bytes than needed by application
     else
     {
       int to_recv = length;
       if(msg && dmsg->payload)
       {
         memcpy(&msg[rcvd], (byte*)dmsg->payload+rcvbuf_offset, to_recv);
       }
       rcvbuf_len -= to_recv;
       rcvbuf_offset += to_recv;
       rcvd += to_recv;
       break;
     }
   }
   return rcvd;
 }
s3f::s3fnet::UDPSession::S3FNET_DEQUE (DataMessage *) private
The receive buffer to store the received messages.
virtual void s3f::s3fnet::SocketSession::reinit () inline virtual inherited
Called by socket to reinitialize the destination ip and port.
Definition at line 268 of file socket_session.h.
References s3f::s3fnet::SessionID::dst_ip, s3f::s3fnet::SessionID::dst_port, and IPADDR_ANYDEST.
Referenced by s3f::s3fnet::SocketMaster::control(), and s3f::s3fnet::NBSocketMaster::control().
{
     dst_ip = IPADDR_ANYDEST;
     dst_port = 0;
   }
char* s3f::s3fnet::SessionID::toString (char * buf) inline inherited
Translate the ID into a textual string.
Parameters
buf buffer to write into (MUST NOT BE NULL)
Returns
pointer to the same buffer passe din
Definition at line 121 of file socket_session.h.
References s3f::s3fnet::SessionID::dst_ip, s3f::s3fnet::SessionID::dst_port, s3f::s3fnet::IPPrefix::ip2txt(), s3f::s3fnet::SessionID::prot_id, s3f::s3fnet::SessionID::src_ip, and s3f::s3fnet::SessionID::src_port.
{
     assert(buf);
     char buf0[50], buf1[50];
     sprintf(buf, "prot %u src_ip %s src_port %u dst_ip %s dst_port %u",
             prot_id, IPPrefix::ip2txt(src_ip, buf0), src_port,
             IPPrefix::ip2txt(dst_ip, buf1), dst_port);
     return buf;
   }
Member Data Documentation
UDPMaster* s3f::s3fnet::UDPSession::udp_master private
Point to the udp master.
Definition at line 99 of file udp_session.h.
Referenced by abort(), clear_app_state(), connect(), disconnect(), getSessionMaster(), listen(), receive(), release(), send(), setSource(), UDPSession(), and wake_app().
int s3f::s3fnet::UDPSession::socket private
The socket id.
Definition at line 102 of file udp_session.h.
Referenced by abort(), clear_app_state(), connect(), disconnect(), listen(), release(), setSocketID(), setSource(), and wake_app().
bool s3f::s3fnet::UDPSession::is_connected private
Whether the UDP session has been connected.
Definition at line 105 of file udp_session.h.
Referenced by connect(), connected(), disconnect(), and listen().
int s3f::s3fnet::UDPSession::rcvbuf_len private
The total number of bytes stored in the receive buffer.
Definition at line 111 of file udp_session.h.
Referenced by generate(), and receive().
int s3f::s3fnet::UDPSession::rcvbuf_offset private
Offset to the first message in the receive buffer, which points to the byte to be transferred next to the application.
Definition at line 115 of file udp_session.h.
Referenced by generate().
byte* s3f::s3fnet::UDPSession::appl_rcvbuf private
The buffer (owned by application) to receive data.
Definition at line 118 of file udp_session.h.
Referenced by receive(), recv(), and wake_app().
uint32 s3f::s3fnet::UDPSession::appl_rcvbuf_size private
Total number of bytes expected to receive.
Definition at line 121 of file udp_session.h.
Referenced by receive(), recv(), and wake_app().
uint32 s3f::s3fnet::UDPSession::appl_data_rcvd private
The size of the received data (that has been put into the receive buffer).
Definition at line 125 of file udp_session.h.
Referenced by receive(), and wake_app().
uint32 s3f::s3fnet::SessionID::prot_id inherited
The protocol number.
Definition at line 132 of file socket_session.h.
Referenced by s3f::s3fnet::SessionCmp::operator()(), s3f::s3fnet::SessionID::operator=(), and s3f::s3fnet::SessionID::toString().
IPADDR s3f::s3fnet::SessionID::src_ip inherited
Source ip address.
Definition at line 135 of file socket_session.h.
Referenced by s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SessionCmp::operator()(), s3f::s3fnet::SessionID::operator=(), send(), s3f::s3fnet::TCPSession::send_data(), setSource(), s3f::s3fnet::TCPSession::setSource(), and s3f::s3fnet::SessionID::toString().
IPADDR s3f::s3fnet::SessionID::dst_ip inherited
Destination ip address.
Definition at line 138 of file socket_session.h.
Referenced by s3f::s3fnet::TCPSession::active_open(), connect(), s3f::s3fnet::SocketMaster::connected(), s3f::s3fnet::NBSocketMaster::connected(), s3f::s3fnet::SessionCmp::operator()(), s3f::s3fnet::SessionID::operator=(), s3f::s3fnet::SocketSession::reinit(), send(), s3f::s3fnet::TCPSession::send_data(), and s3f::s3fnet::SessionID::toString().
uint16 s3f::s3fnet::SessionID::src_port inherited
Source port number.
Definition at line 141 of file socket_session.h.
Referenced by s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SessionCmp::operator()(), s3f::s3fnet::SessionID::operator=(), send(), s3f::s3fnet::TCPSession::send_data(), setSource(), s3f::s3fnet::TCPSession::setSource(), and s3f::s3fnet::SessionID::toString().
uint16 s3f::s3fnet::SessionID::dst_port inherited
Destination port number.
Definition at line 144 of file socket_session.h.
Referenced by s3f::s3fnet::TCPSession::active_open(), connect(), s3f::s3fnet::SocketMaster::connected(), s3f::s3fnet::NBSocketMaster::connected(), s3f::s3fnet::SessionCmp::operator()(), s3f::s3fnet::SessionID::operator=(), s3f::s3fnet::SocketSession::reinit(), send(), s3f::s3fnet::TCPSession::send_data(), and s3f::s3fnet::SessionID::toString().
The documentation for this class was generated from the following files:
udp_session.h
udp_session.cc