S3F: s3f::s3fnet::UDPClientSession Class Reference
s3f::s3fnet::UDPClientSession Class Reference
The UDP client test protocol session.
#include <udp_client.h>
Public Types
enum InstantiationType { PROT_UNIQUE_INSTANCE = 0x00, PROT_MULTIPLE_INSTANCES = 0x01, PROT_MULTIPLE_IMPLEMENTATIONS = 0x02 }
Multiple protocol session instantiation type.
enum ExecutionStage { PSESS_CREATED = 0, PSESS_CONFIGURED = 1, PSESS_INITIALIZED = 2, PSESS_WRAPPED_UP = 3 }
A normal protocol session must go though the following stages.
Public Member Functions
UDPClientSession (ProtocolGraph *graph)
The constructor.
virtual ~UDPClientSession ()
The destructor.
virtual void config (s3f::dml::Configuration *cfg)
Configure the UDP client test protocol session.
virtual int getProtocolNumber ()
Return the protocol number.
virtual void init ()
Initialize this protocol session.
void start_timer_callback (Activation ac)
The callback function registered with the start_timer_callback_proc.
void start_timer_callback_body (Activation)
the actual body of the start_timer_callback function
virtual void wrapup ()
The method is used to wrap up the protocol session.
int pushdown (Activation msg, ProtocolSession *hi_sess, void *extinfo=0, size_t extinfo_size=0)
The original push method is divided into pushdown() and push().
int popup (Activation msg, ProtocolSession *lo_sess, void *extinfo=0, size_t extinfo_size=0)
The original pop method is divided into popup() and pop().
virtual int control (int ctrltyp, void *ctrlmsg, ProtocolSession *sess)
The control method is used by the protocol session to receive control messages (or information queries) from other protocol sessions both above and below this protocol session on the stack.
ProtocolGraph * inGraph ()
The method returns the protocol graph in which this protocol session resides.
virtual Host * inHost ()
Return a pointer to the host owning this protocol session.
Random::RNG * getRandom ()
The method returns a pointer to the random number generator.
ltime_t getNow ()
The method returns the current simulation time.
char * getNowWithThousandSeparator ()
For printing the current simulation time in a better readable format.
int configured ()
This method returns true if the protocol session has been configured.
int initialized ()
This method returns true if the protocol session has been initialized.
int wrapped_up ()
This method returns true if the protocol session has been wrapped up.
virtual const char * psesstype ()
Public Attributes
Process * start_timer_callback_proc
Provide call_back functionality for implementing the start timer in the UDPClientSession this S3F process is used by waitFor() function.
ProtocolCallbackActivation * start_timer_ac
bool start_timer_called_once
Storing the data for the callback function.
char * name
Symbolic name of the protocol this session implements.
float version
Version number of this protocol implemenntation, represented as a floating point number (e.g., 1.23).
char * use
Name of the protocol class from which this protocol session is instantiated.
Protected Member Functions
void main_proc (int sample_off_time, ltime_t lead_time)
the first function to call for starting a communication at client side
void start_once ()
first time to choose the fixed UDP server if the DML specifies to use fixed server
void start_on ()
start the socket communication, such as bind and connect, and choose random server if the DML specifies to use random server
void server_connected (UDPClientSessionContinuation *const cnt)
function representing the server_connected stage
void request_sent (UDPClientSessionContinuation *const cnt)
function representing the request_sent stage
void data_received (UDPClientSessionContinuation *const cnt)
function representing the data_received stage
void session_closed (UDPClientSessionContinuation *const cnt)
function representing the session_closed stage
bool get_random_server (IPADDR &server_ip, uint16 &server_port)
Get a server ip and port randomly from traffic description and return false if failed to do so.
void timeout (int sock)
Called if the file transfer takes too long.
virtual int push (Activation msg, ProtocolSession *hi_sess, void *extinfo=0, size_t extinfo_size=0)
This method should not be called; it is provided here to prompt an error message if it's called accidentally.
virtual int pop (Activation msg, ProtocolSession *lo_sess, void *extinfo=0, size_t extinfo_size=0)
This method should not be called; it is provided here to prompt an error message if it's called accidentally.
virtual int instantiation_type ()
This method controls how protocol instances can coexist with one another.
Protected Attributes
ProtocolGraph * ingraph
Points to the protocol graph.
Random::RNG * sess_rng
Pointer to a random number generator.
int stage
This variable indicates the current stage of this protocol session.
Private Attributes
ltime_t start_time
Time before a session starts.
double start_time_double
ltime_t start_window
Size of random window before session starts.
double start_window_double
ltime_t user_timeout
timeout before aborting a session
ltime_t off_time
Off time between sessions.
double off_time_double
bool off_time_run_first
Whether 1st session starts with an off time.
bool off_time_exponential
Constant or exponential off time.
bool fixed_server
Whether to find a random target.
uint32 request_size
Size of the request sent to the server.
uint32 file_size
Size of the file to be sent from the server.
uint16 start_port
The starting port number for client sessions.
S3FNET_STRING server_list
bool show_report
Whether we print out the result or not.
SocketMaster * sm
Points to the socket master.
IPADDR client_ip
The ip address of the client (interface 0).
uint32 nsess
Number of sessions initiated by this client (statistics).
IPADDR server_ip
Server ip address of the current connection.
uint16 server_port
Server port number of the current connection.
Detailed Description
The UDP client test protocol session.
This is a test protocol that does not exist in reality. In a normal situation, the protocol waits for a period of time before it randomly selects a UDP server and tries to retrieve a number of bytes from the server. The process repeats until simulation ends. The difference between this class and the BlockingUDPClientSession class is that the latter uses blocking socket calls. In SSF, blocking is implemented using non-simple processes that come with a detectable higher execution cost than simple processes.
Definition at line 35 of file udp_client.h.
Member Enumeration Documentation
enum s3f::s3fnet::ProtocolSession::InstantiationType inherited
Multiple protocol session instantiation type.
Enumerator
PROT_UNIQUE_INSTANCE
PROT_MULTIPLE_INSTANCES
PROT_MULTIPLE_IMPLEMENTATIONS
Definition at line 44 of file protocol_session.h.
{
     PROT_UNIQUE_INSTANCE                = 0x00,
     PROT_MULTIPLE_INSTANCES             = 0x01,
     PROT_MULTIPLE_IMPLEMENTATIONS       = 0x02
   };
enum s3f::s3fnet::ProtocolSession::ExecutionStage inherited
A normal protocol session must go though the following stages.
Enumerator
PSESS_CREATED
this protocol session has just been created
PSESS_CONFIGURED
the config method of this protocol session has been called
PSESS_INITIALIZED
the init method of this protocol session has been called
PSESS_WRAPPED_UP
Definition at line 51 of file protocol_session.h.
                       {
     PSESS_CREATED       = 0,
     PSESS_CONFIGURED    = 1,
     PSESS_INITIALIZED   = 2,
     PSESS_WRAPPED_UP    = 3
   };
Constructor & Destructor Documentation
s3f::s3fnet::UDPClientSession::UDPClientSession (ProtocolGraph * graph)
The constructor.
Definition at line 148 of file udp_client.cc.
References s3f::s3fnet::ProtocolSession::inHost(), and UDP_DUMP.
                                                        :
   ProtocolSession(graph), nsess(0)
 {
   UDP_DUMP(printf("[host=\"%s\"] new udp client session.\n", inHost()->nhi.toString()));
 }
s3f::s3fnet::UDPClientSession::~UDPClientSession () virtual
The destructor.
Definition at line 154 of file udp_client.cc.
 {}
Member Function Documentation
void s3f::s3fnet::UDPClientSession::config (s3f::dml::Configuration * cfg) virtual
Configure the UDP client test protocol session.
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 156 of file udp_client.cc.
References s3f::s3fnet::ProtocolSession::config(), Entity::d2t(), DEFAULT_CLIENT_PORT, s3f::s3fnet::error_quit(), file_size, fixed_server, s3f::s3fnet::ProtocolSession::inHost(), off_time, off_time_double, off_time_exponential, off_time_run_first, request_size, server_list, show_report, start_port, start_time, start_time_double, start_window, start_window_double, UDP_DUMP, and user_timeout.
 {
   ProtocolSession::config(cfg);
   char* str = (char*)cfg->findSingle("start_time");
   if(str)
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: UDPClientSession::config(), invalid START_TIME attribute.\n");
     start_time_double = atof(str);
   }
   else start_time_double = 0;
   start_time = inHost()->d2t(start_time_double, 0);
   str = (char*)cfg->findSingle("start_window");
   if(str)
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: UDPClientSession::config(), invalid START_WINDOW attribute.\n");
     start_window_double = atof(str);
   }
   else start_window_double = 0;
   start_window = inHost()->d2t(start_window_double, 0);
   double user_timeout_double;
   str = (char*)cfg->findSingle("user_timeout");
   if(str)
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: UDPClientSession::config(), invalid USER_TIMEOUT attribute.\n");
     user_timeout_double = atof(str);
   }
   else user_timeout_double = 100; //default is 100 s
   user_timeout = inHost()->d2t(user_timeout_double, 0);
   str = (char*)cfg->findSingle("off_time");
   if(!str || s3f::dml::dmlConfig::isConf(str))
     error_quit("ERROR: UDPClientSession::config(), missing or invalid OFF_TIME attribute.\n");
   off_time_double = atof(str);
   off_time = inHost()->d2t(off_time_double, 0);
   str = (char*)cfg->findSingle("off_time_run_first");
   if(str)
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: UDPClientSession::config(), invalid OFF_TIME_RUN_FIRST attribute.\n");
     if(!strcasecmp(str, "true")) off_time_run_first = true;
     else off_time_run_first = false;
   }
   else off_time_run_first = false;
   str = (char*)cfg->findSingle("off_time_exponential");
   if(str)
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: UDPClientSession::config(), invalid OFF_TIME_EXPONENTIAL attribute.\n");
     if(!strcasecmp(str, "true")) off_time_exponential = true;
     else off_time_exponential = false;
   }
   else off_time_exponential = false;
   str = (char*)cfg->findSingle("fixed_server");
   if(str)
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: UDPClientSession::config(), invalid FIXED_SERVER attribute.\n");
     if(!strcasecmp(str, "true")) fixed_server = true;
     else fixed_server = false;
   }
   else fixed_server = false;
   str = (char*)cfg->findSingle("request_size");
   if(str)
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: UDPClientSession::config(), invalid REQUEST_SIZE attribute.\n");
     request_size = atoi(str);
     if(request_size < sizeof(uint32))
       error_quit("ERROR: UDPClientSession::config(), REQUEST_SIZE must be larger than 4 (bytes).\n");
   }
   else request_size = sizeof(uint32);
   str = (char*)cfg->findSingle("file_size");
   if(!str || s3f::dml::dmlConfig::isConf(str))
     error_quit("ERROR: UDPClientSession::config(), missing or invalid FILE_SIZE attribute.\n");
   file_size = atoi(str);
   str = (char*)cfg->findSingle("client_port");
   if(str)
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: UDPClientSession::config(), invalid CLIENT_PORT attribute.\n");
     start_port = atoi(str);
   }
   else start_port = DEFAULT_CLIENT_PORT;
   str = (char*)cfg->findSingle("server_list");
   if(str)
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: UDPClientSession::config(), invalid SERVER_LIST attribute.\n");
     server_list = str;
   }
   else server_list = "forUDP";
   str = (char*)cfg->findSingle("SHOW_REPORT");
   if(str)
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: UDPClientSession::config(), invalid SHOW_REPORT attribute.\n");
     if(!strcasecmp(str, "true")) show_report = true;
     else if(!strcasecmp(str, "false")) show_report = false;
     else error_quit("ERROR: UDPClientSession::config(), invalid SHOW_REPORT attribute (%s).\n", str);
   }
   else show_report = true;
   UDP_DUMP(printf("[host=\"%s\"] config():\n"
                   "  start_time=%ld, start_window=%ld, user_timeout=%ld, off_time=%ld,\n"
                   "  off_time_run_first=%d, off_time_exponential=%d, fixed_server=%d,\n"
                   "  request_size=%u, file_size=%u, start_port=%u.\n",
                   inHost()->nhi.toString(), start_time, start_window, user_timeout,
                   off_time, off_time_run_first, off_time_exponential, fixed_server,
                   request_size, file_size, start_port));
 }
virtual int s3f::s3fnet::UDPClientSession::getProtocolNumber () inline virtual
Return the protocol number.
This specifies the relationship between this protocol and the other protocols defined in the same protocol stack.
Implements s3f::s3fnet::ProtocolSession.
Definition at line 53 of file udp_client.h.
References s3f::s3fnet::S3FNET_PROTOCOL_TYPE_UDPTEST_CLIENT.
 { return S3FNET_PROTOCOL_TYPE_UDPTEST_CLIENT; }
void s3f::s3fnet::UDPClientSession::init () virtual
Initialize this protocol session.
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 281 of file udp_client.cc.
References client_ip, Entity::d2t(), s3f::s3fnet::error_quit(), s3f::s3fnet::Host::getDefaultIP(), s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::getRandom(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::IPPrefix::ip2txt(), IPADDR_INVALID, main_proc(), off_time_run_first, sm, SOCKET_API, start_time, start_time_double, start_timer_called_once, start_window, start_window_double, UDP_DUMP, and Random::RNG::Uniform().
 {
   ProtocolSession::init();
   client_ip = inHost()->getDefaultIP();
   if(IPADDR_INVALID == client_ip)
     error_quit("ERROR: UDPClientSession::init(), invalid IP address, the host's not connected to network.\n");
   sm = SOCKET_API;
   if(!sm)
           error_quit("UDPClientSession::init(), missing socket master on host \"%s\".\n", inHost()->nhi.toString());
   UDP_DUMP(printf("[host=\"%s\"] init(), client_ip=\"%s\".\n",
                   inHost()->nhi.toString(), IPPrefix::ip2txt(client_ip)));
   start_timer_called_once = false;
   // get new start time and wait
   if(start_window > 0)
   {
     start_time_double += getRandom()->Uniform(0, 1)*start_window_double;
     start_time = inHost()->d2t(start_time_double, 0);
   }
   UDP_DUMP(printf("[host=\"%s\"] %s: main_proc(), starting client until %ld.\n",
                   inHost()->nhi.toString(), getNowWithThousandSeparator(), start_time));
   main_proc(off_time_run_first, start_time);
 }
void s3f::s3fnet::UDPClientSession::start_timer_callback (Activation ac)
The callback function registered with the start_timer_callback_proc.
Definition at line 528 of file udp_client.cc.
References start_timer_callback_body().
Referenced by main_proc().
 {
         UDPClientSession* client = (UDPClientSession*)((ProtocolCallbackActivation*)ac)->session;
     client->start_timer_callback_body(ac);
 }
void s3f::s3fnet::UDPClientSession::start_timer_callback_body (Activation ac)
the actual body of the start_timer_callback function
Definition at line 534 of file udp_client.cc.
References start_on(), start_once(), and start_timer_called_once.
Referenced by start_timer_callback().
 {
         if(start_timer_called_once == true)
         {
                 start_on();
         }
         else
         {
                 start_timer_called_once = true;
                 start_once();
         }
 }
void s3f::s3fnet::UDPClientSession::main_proc (int sample_off_time, ltime_t lead_time) protected
the first function to call for starting a communication at client side
Definition at line 310 of file udp_client.cc.
References Entity::d2t(), Random::RNG::Exponential(), s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::getRandom(), s3f::s3fnet::ProtocolSession::inHost(), off_time, off_time_double, off_time_exponential, start_timer_ac, start_timer_callback(), start_timer_callback_proc, s3f::s3fnet::Host::tie_breaking_seed, UDP_DUMP, and Entity::waitFor().
Referenced by s3f::s3fnet::UDPClientSessionContinuation::failure(), init(), and session_closed().
 {
   // check whether off time starts first
   ltime_t t = lead_time;
   if(sample_off_time)
   {
     if(off_time == 0)
     {
       UDP_DUMP(printf("[host=\"%s\"] %s: main_proc(), OFF (forever).\n",
                       inHost()->nhi.toString(), getNowWithThousandSeparator()));
       return;
     }
     else
     {
       double vt_double;
       if(off_time_exponential)
           vt_double = getRandom()->Exponential(1.0/off_time_double);
       else
           vt_double = off_time_double;
       ltime_t vt = inHost()->d2t(vt_double, 0);
       t += vt;
       UDP_DUMP(printf("[host=\"%s\"] %s: main_proc(), OFF (duration=%ld).\n",
                       inHost()->nhi.toString(), getNowWithThousandSeparator(), vt));
     }
   }
   Host* owner_host = inHost();
   start_timer_callback_proc = new Process( (Entity *)owner_host, (void (s3f::Entity::*)(s3f::Activation))&UDPClientSession::start_timer_callback);
   start_timer_ac = new ProtocolCallbackActivation(this);
   Activation ac (start_timer_ac);
   HandleCode h = owner_host->waitFor( start_timer_callback_proc, ac, t, owner_host->tie_breaking_seed );
 }
void s3f::s3fnet::UDPClientSession::start_once () protected
first time to choose the fixed UDP server if the DML specifies to use fixed server
Definition at line 344 of file udp_client.cc.
References fixed_server, get_random_server(), server_ip, server_port, and start_on().
Referenced by start_timer_callback_body().
 {
   // if fixed_server is true, the client connects with the same server
   // for the whole simulation; the server is chosen from randomly from
   // dml traffic description
   if(fixed_server)
   {
     if(!get_random_server(server_ip, server_port))
       return; // stop if something's wrong
   }
   start_on();
 }
void s3f::s3fnet::UDPClientSession::start_on () protected
start the socket communication, such as bind and connect, and choose random server if the DML specifies to use random server
Definition at line 358 of file udp_client.cc.
References s3f::s3fnet::SocketMaster::bind(), s3f::s3fnet::SocketMaster::connect(), fixed_server, get_random_server(), s3f::s3fnet::ProtocolSession::getNow(), s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::IPPrefix::ip2txt(), s3f::s3fnet::IPADDR_INADDR_ANY, nsess, server_ip, server_port, sm, s3f::s3fnet::SocketMaster::socket(), start_port, s3f::s3fnet::UDPClientSessionContinuation::status, s3f::s3fnet::UDPClientSessionContinuation::UDP_CLIENT_SESSION_CONNECTING, UDP_DUMP, UDP_PROTOCOL_NAME, and UDPClientSessionContinuation.
Referenced by start_once(), and start_timer_callback_body().
 {
   // if the server is not fixed, the client connects with the
   // different servers for the whole simulation
   if(!fixed_server)
   {
     if(!get_random_server(server_ip, server_port))
       return; // stop if something's wrong
   }
   UDP_DUMP(printf("[host=\"%s\"] %s: main_proc(), ON.\n",
                   inHost()->nhi.toString(), getNowWithThousandSeparator()));
   nsess++;
   int sock = sm->socket();
   if(!sm->bind(sock, IPADDR_INADDR_ANY/*client_ip*/, start_port++, UDP_PROTOCOL_NAME, 0))
   {
     UDP_DUMP(printf("start_on() on host \"%s\": failed to bind.\n", inHost()->nhi.toString()));
     return;
   }
   UDP_DUMP(printf("[host=\"%s\"] %s: session_proc(), socket %d connecting to server: \"%s:%d\".\n",
                   inHost()->nhi.toString(), getNowWithThousandSeparator(), sock,
                   IPPrefix::ip2txt(server_ip), server_port));
   // creating a continuation for this session.
   UDPClientSessionContinuation* cnt = new UDPClientSessionContinuation(this, sock, getNow());
   cnt->status = UDPClientSessionContinuation::UDP_CLIENT_SESSION_CONNECTING;
   sm->connect(sock, server_ip, server_port, cnt);
 }
void s3f::s3fnet::UDPClientSession::server_connected (UDPClientSessionContinuation *const cnt) protected
function representing the server_connected stage
Definition at line 390 of file udp_client.cc.
References file_size, s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::inHost(), request_size, s3f::s3fnet::SocketMaster::send(), sm, s3f::s3fnet::UDPClientSessionContinuation::socket, s3f::s3fnet::UDPClientSessionContinuation::status, s3f::s3fnet::UDPClientSessionContinuation::UDP_CLIENT_SESSION_REQUESTING, and UDP_DUMP.
Referenced by s3f::s3fnet::UDPClientSessionContinuation::success().
 {
   UDP_DUMP(printf("[host=\"%s\"] %s: session_proc(), socket %d sending request "
                   "(request_size=%u, file_size=%u).\n",
                   inHost()->nhi.toString(), getNowWithThousandSeparator(),
                   cnt->socket, request_size, file_size));
   // we send real bytes to the server
   byte* reqbuf = new byte[request_size];
   *(uint32*)reqbuf = htonl(file_size);
   // sending out data request
   cnt->status = UDPClientSessionContinuation::UDP_CLIENT_SESSION_REQUESTING;
   sm->send(cnt->socket, request_size, reqbuf, cnt);
   delete[] reqbuf;
 }
void s3f::s3fnet::UDPClientSession::request_sent (UDPClientSessionContinuation *const cnt) protected
function representing the request_sent stage
Definition at line 408 of file udp_client.cc.
References file_size, s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::UDPClientSessionContinuation::rcvd_bytes, s3f::s3fnet::SocketMaster::recv(), sm, s3f::s3fnet::UDPClientSessionContinuation::socket, s3f::s3fnet::UDPClientSessionContinuation::status, s3f::s3fnet::UDPClientSessionContinuation::UDP_CLIENT_SESSION_RECEIVING, UDP_DUMP, user_timeout, s3f::s3fnet::UDPClientSessionContinuation::user_timer, s3f::s3fnet::UDPClientSessionContinuation::user_timer_ac, s3f::s3fnet::UDPClientSessionContinuation::user_timer_callback(), s3f::s3fnet::UDPClientSessionContinuation::user_timer_callback_proc, and Entity::waitFor().
Referenced by s3f::s3fnet::UDPClientSessionContinuation::success().
 {
   UDP_DUMP(printf("[host=\"%s\"] %s: session_proc(), socket %d request sent.\n",
                   inHost()->nhi.toString(), getNowWithThousandSeparator(), cnt->socket));
   // time out if the file transfer takes too long
   Host* owner_host = inHost();
   cnt->user_timer_callback_proc =
                   new Process( (Entity *)owner_host, (void (s3f::Entity::*)(s3f::Activation))&UDPClientSessionContinuation::user_timer_callback);
   cnt->user_timer_ac = new UDPClientSessionCallbackActivation(this, cnt);
   Activation ac (cnt->user_timer_ac);
   cnt->user_timer = inHost()->waitFor( cnt->user_timer_callback_proc, ac, user_timeout, inHost()->tie_breaking_seed );
   cnt->rcvd_bytes = 0;
   if(cnt->rcvd_bytes < file_size)
   {
     int to_recv = file_size-cnt->rcvd_bytes;
     cnt->status = UDPClientSessionContinuation::UDP_CLIENT_SESSION_RECEIVING;
     sm->recv(cnt->socket, to_recv, 0, cnt);
   }
 }
void s3f::s3fnet::UDPClientSession::data_received (UDPClientSessionContinuation *const cnt) protected
function representing the data_received stage
Definition at line 430 of file udp_client.cc.
References client_ip, s3f::s3fnet::SocketMaster::close(), file_size, s3f::s3fnet::ProtocolSession::getNow(), s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::IPPrefix::ip2txt(), s3f::s3fnet::UDPClientSessionContinuation::rcvd_bytes, s3f::s3fnet::SocketMaster::recv(), s3f::s3fnet::SocketContinuation::retval, server_ip, show_report, sm, s3f::s3fnet::UDPClientSessionContinuation::socket, s3f::s3fnet::UDPClientSessionContinuation::start_time, s3f::s3fnet::UDPClientSessionContinuation::status, Entity::t2d(), s3f::s3fnet::UDPClientSessionContinuation::UDP_CLIENT_SESSION_CLOSING, s3f::s3fnet::UDPClientSessionContinuation::UDP_CLIENT_SESSION_RECEIVING, UDP_DUMP, and s3f::s3fnet::UDPClientSessionContinuation::user_timer.
Referenced by s3f::s3fnet::UDPClientSessionContinuation::success().
 {
   cnt->rcvd_bytes += cnt->retval;
   UDP_DUMP(printf("[host=\"%s\"] %s: session_proc(), socket %d "
                   "received %d bytes (%d bytes left).\n",
                   inHost()->nhi.toString(), getNowWithThousandSeparator(),
                   cnt->socket, cnt->retval, file_size-cnt->rcvd_bytes));
   if(cnt->rcvd_bytes < file_size)
   {
     int to_recv = file_size-cnt->rcvd_bytes;
     assert(cnt->status == UDPClientSessionContinuation::UDP_CLIENT_SESSION_RECEIVING);
     sm->recv(cnt->socket, to_recv, 0, cnt);
     return;
   }
   if(show_report)
   {
     char buf1[50]; char buf2[50];
     double total_time = inHost()->t2d(getNow() - cnt->start_time, 0);
     printf("%s: UDP client \"%s\" downloaded %d bytes from server \"%s\", throughput %f Kb/s.\n",
            getNowWithThousandSeparator(), IPPrefix::ip2txt(client_ip, buf1), file_size,
            IPPrefix::ip2txt(server_ip, buf2), (8e-3 * file_size / total_time ));
   }
   HandlePtr hptr(new Handle(cnt->user_timer));
   hptr->cancel();
   cnt->user_timer = 0;
   // waiting for closing udp connection.
   cnt->status = UDPClientSessionContinuation::UDP_CLIENT_SESSION_CLOSING;
   sm->close(cnt->socket, cnt);
 }
void s3f::s3fnet::UDPClientSession::session_closed (UDPClientSessionContinuation *const cnt) protected
function representing the session_closed stage
Definition at line 465 of file udp_client.cc.
References s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::inHost(), main_proc(), s3f::s3fnet::UDPClientSessionContinuation::socket, and UDP_DUMP.
Referenced by s3f::s3fnet::UDPClientSessionContinuation::success().
 {
   UDP_DUMP(printf("[host=\"%s\"] %s: session_proc(), socket %d connection closed.\n",
                   inHost()->nhi.toString(), getNowWithThousandSeparator(), cnt->socket));
   main_proc(true, 0);
   // the continuation will be reclaimed after this
 }
bool s3f::s3fnet::UDPClientSession::get_random_server (IPADDR & server_ip, uint16 & server_port) protected
Get a server ip and port randomly from traffic description and return false if failed to do so.
Definition at line 486 of file udp_client.cc.
References s3f::s3fnet::Net::control(), s3f::s3fnet::Net::getNameService(), s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::getRandom(), s3f::s3fnet::Traffic::getServers(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::Host::inNet(), s3f::s3fnet::IPPrefix::ip2txt(), IPADDR_INVALID, s3f::s3fnet::NET_CTRL_GET_TRAFFIC, s3f::s3fnet::NameService::nhi2ip(), s3f::s3fnet::S3FNET_VECTOR(), server_list, server_port, show_report, UDP_DUMP, and Random::RNG::Uniform().
Referenced by start_on(), and start_once().
 {
   Traffic* traffic = 0;
   Host* host = inHost();
   host->inNet()->control(NET_CTRL_GET_TRAFFIC, (void*)&traffic);
   if(!traffic) return false;
   S3FNET_VECTOR(TrafficServerData*) servers;
   if(!traffic->getServers(host, servers, server_list.c_str()) || servers.size() == 0)
   {
     if(show_report)
       printf("WARNING: [host=\"%s\"] %s: get_random_server(), found no server for %s.\n",
              inHost()->nhi.toString(), getNowWithThousandSeparator(), server_list.c_str());
     return false;
   }
   int sidx = (int)floor(getRandom()->Uniform(0, 1) * servers.size());
   server_ip = host->inNet()->getNameService()->nhi2ip(servers[sidx]->nhi->toStlString());
   server_port = servers[sidx]->port;
   if(server_ip == IPADDR_INVALID)
   {
     if(show_report)
       printf("WARNING: [host=\"%s\"] %s: get_random_server(), unresolved server for \"%s\": %s:%d.\n",
              inHost()->nhi.toString(), getNowWithThousandSeparator(), server_list.c_str(),
              IPPrefix::ip2txt(server_ip), server_port);
     return false;
   }
   UDP_DUMP(printf("[host=\"%s\"] %s: get_random_server(), selected server: \"%s:%d\".\n",
                   inHost()->nhi.toString(), getNowWithThousandSeparator(), IPPrefix::ip2txt(server_ip), server_port));
   return true;
 }
void s3f::s3fnet::UDPClientSession::timeout (int sock) protected
Called if the file transfer takes too long.
Definition at line 521 of file udp_client.cc.
References s3f::s3fnet::SocketMaster::abort(), s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::inHost(), sm, and UDP_DUMP.
 {
   UDP_DUMP(printf("[host=\"%s\"] %s: timeout(), socket %d abort.\n",
                   inHost()->nhi.toString(), getNowWithThousandSeparator(), sock));
   sm->abort(sock);
 }
int s3f::s3fnet::UDPClientSession::push (Activation msg, ProtocolSession * hi_sess, void * extinfo = 0, size_t extinfo_size = 0) protected virtual
This method should not be called; it is provided here to prompt an error message if it's called accidentally.
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 474 of file udp_client.cc.
References s3f::s3fnet::error_quit().
 {
   error_quit("ERROR: UDPClientSession::push() should not be called.\n");
   return 1;
 }
int s3f::s3fnet::UDPClientSession::pop (Activation msg, ProtocolSession * lo_sess, void * extinfo = 0, size_t extinfo_size = 0) protected virtual
This method should not be called; it is provided here to prompt an error message if it's called accidentally.
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 480 of file udp_client.cc.
References s3f::s3fnet::error_quit().
 {
   error_quit("ERROR: UDPClientSession::pop() should not be called.\n");
   return 1;
 }
void s3f::s3fnet::ProtocolSession::wrapup () virtual inherited
The method is used to wrap up the protocol session.
It is called when the simulation finishes. It is designed to give user a chance to report simulation statistics. The default behavior is doing nothing. Subclass may override this method for protocol specific dealings. Note that there is no specific order in which wrapup is called for protocol sessions in a protocol graph.
Definition at line 59 of file protocol_session.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolSession::initialized(), s3f::s3fnet::ProtocolSession::name, s3f::s3fnet::ProtocolSession::PSESS_WRAPPED_UP, s3f::s3fnet::ProtocolSession::stage, and s3f::s3fnet::ProtocolSession::wrapped_up().
 {
   // Make sure this init function at the base class should be called
   // by the derived function!
   if(!initialized())
     error_quit("ERROR: ProtocolSession \"%s\" wrapup() called before init(), "
                "forgot to call base class's init() in your derived class?\n", name);
   else if(wrapped_up())
     error_quit("ERROR: duplicate calls to ProtocolSession::wrapup(): "
                "session name is \"%s\".\n", name);
   else stage = PSESS_WRAPPED_UP;
 }
int s3f::s3fnet::ProtocolSession::pushdown (Activation msg, ProtocolSession * hi_sess, void * extinfo = 0, size_t extinfo_size = 0) inherited
The original push method is divided into pushdown() and push().
The pushdown method is the generic part of the code, which is reserved for modeling the handling of messages transferred between protocol layers.
See Also
ProtocolSession::push method for details.
Definition at line 72 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::push().
Referenced by s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), s3f::s3fnet::IPSession::control(), s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), s3f::s3fnet::OpenFlowSwitchSession::OutputControl(), s3f::s3fnet::OpenFlowSwitchSession::OutputPacket(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::UDPMaster::push(), s3f::s3fnet::TCPMaster::push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::send(), and s3f::s3fnet::TCPSession::send_data().
 {
   return push(msg, hi_sess, extinfo, extinfo_size);
 }
int s3f::s3fnet::ProtocolSession::popup (Activation msg, ProtocolSession * lo_sess, void * extinfo = 0, size_t extinfo_size = 0) inherited
The original pop method is divided into popup() and pop().
The popup method is the generic part of the code, which is reserved for modeling the handling of messages transferred between protocol layers.
See Also
ProtocolSession::pop method for details.
Definition at line 77 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::pop().
Referenced by s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::IPSession::push(), and s3f::s3fnet::SimplePhy::receivePacket().
 {
   return pop(msg, lo_sess, extinfo, extinfo_size);
 }
int s3f::s3fnet::ProtocolSession::control (int ctrltyp, void * ctrlmsg, ProtocolSession * sess) virtual inherited
The control method is used by the protocol session to receive control messages (or information queries) from other protocol sessions both above and below this protocol session on the stack.
The derived class should override this method to provide support for handling different control messages. In this case, the derived class should invoke this method when encountering a control type that it does not know to to process.
The control messages are distinguished via types. The ctrl type is an integer; its meaning is specified by the particular protocol. The users are recommended to use ctrl type values beyond 1000 (excluding 1000). The values within 1000 are reserved. The control message is of type void* and should be cast to the appropriate types accordingly. Note that, unless specified otherwise, the caller is responsible to reclaim the control message once the method returns. The protocol session that invoking this method will have a reference to itself in the third argument.
The method returns an integer, indicating whether the control message is successfully processed. Unless specified otherwise, a zero means success. Non-zero means trouble and the returned value can be used as the error number, the meaning of which is specified by each particular protocol.
For information on a specific control type, see s3f::s3fnet::ProtocolSessionCtrlTypes
Reimplemented in s3f::s3fnet::IPSession, s3f::s3fnet::NBSocketMaster, s3f::s3fnet::SocketMaster, s3f::s3fnet::OpenFlowSwitchSession, s3f::s3fnet::SimplePhy, s3f::s3fnet::OpenVZEventSession, s3f::s3fnet::OpenFlowControllerSession, s3f::s3fnet::UDPMaster, s3f::s3fnet::DummySession, s3f::s3fnet::LowestProtocolSession, and s3f::s3fnet::NicProtocolSession.
Definition at line 92 of file protocol_session.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::PSESS_CTRL_SESSION_GET_INTERFACE, s3f::s3fnet::PSESS_CTRL_SESSION_IS_LOWEST, s3f::s3fnet::PSESS_CTRL_SESSION_SET_CHILD, and s3f::s3fnet::PSESS_CTRL_SESSION_SET_PARENT.
Referenced by s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::TCPSession::clear_app_state(), s3f::s3fnet::Host::config(), s3f::s3fnet::NicProtocolSession::control(), s3f::s3fnet::DummySession::control(), s3f::s3fnet::UDPMaster::control(), s3f::s3fnet::OpenFlowControllerSession::control(), s3f::s3fnet::OpenVZEventSession::control(), s3f::s3fnet::OpenFlowSwitchSession::control(), s3f::s3fnet::SocketMaster::control(), s3f::s3fnet::NBSocketMaster::control(), s3f::s3fnet::IPSession::control(), s3f::s3fnet::Host::loadForwardingTable(), s3f::s3fnet::UDPSession::release(), s3f::s3fnet::UDPSession::wake_app(), and s3f::s3fnet::TCPSession::wake_app().
 {
   switch(ctrltype) {
   case PSESS_CTRL_SESSION_IS_LOWEST:
     assert(ctrlmsg);
     *((bool*)ctrlmsg) = false;
     return 0;
   case PSESS_CTRL_SESSION_GET_INTERFACE:
     assert(ctrlmsg);
     *((NetworkInterface**)ctrlmsg) = 0;
     return 0;
   case PSESS_CTRL_SESSION_SET_PARENT:
   case PSESS_CTRL_SESSION_SET_CHILD:
     return 0;
   default:
     // all control types should be handled at this point; if not, we
     // should report the problem
     error_quit("ERROR: ProtocolSession::control(), "
                "unknown control type: %d.\n", ctrltype);
   }
   return 0;
 }
ProtocolGraph* s3f::s3fnet::ProtocolSession::inGraph () inline inherited
The method returns the protocol graph in which this protocol session resides.
Definition at line 178 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::ingraph.
Referenced by s3f::s3fnet::SimplePhy::config(), s3f::s3fnet::SimplePhy::control(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::SimpleMac::init(), s3f::s3fnet::SimplePhy::init(), s3f::s3fnet::RedQueue::init(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::SimplePhy::push(), s3f::s3fnet::SimplePhy::receivePacket(), s3f::s3fnet::SimplePhy::sendPacket(), s3f::s3fnet::SimpleMac::SimpleMac(), s3f::s3fnet::SimplePhy::SimplePhy(), s3f::s3fnet::SimpleMac::~SimpleMac(), and s3f::s3fnet::SimplePhy::~SimplePhy().
 { return ingraph; }
Host * s3f::s3fnet::ProtocolSession::inHost () virtual inherited
Return a pointer to the host owning this protocol session.
Reimplemented in s3f::s3fnet::NicProtocolSession.
Definition at line 118 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::ingraph.
Referenced by s3f::s3fnet::UDPSession::abort(), s3f::s3fnet::SocketMaster::abort(), s3f::s3fnet::NBSocketMaster::abort(), s3f::s3fnet::SocketMaster::accept(), s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::accept1a(), s3f::s3fnet::SocketMaster::accept1b(), s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SocketMaster::accept2b(), s3f::s3fnet::OpenFlowSwitchSession::AddFlow(), s3f::s3fnet::TCPSession::backoff_timeout(), s3f::s3fnet::SocketMaster::bind(), s3f::s3fnet::NBSocketMaster::bind(), s3f::s3fnet::SocketMaster::block_till(), s3f::s3fnet::NBSocketMaster::block_till(), s3f::s3fnet::BTCPClientSession::BTCPClientSession(), s3f::s3fnet::OpenFlowSwitchSession::BufferFromPacket(), s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::UDPServerSession::client_connected(), s3f::s3fnet::SocketMaster::close(), s3f::s3fnet::NBSocketMaster::close(), s3f::s3fnet::SocketMaster::close1(), s3f::s3fnet::NBSocketMaster::close1(), s3f::s3fnet::UDPMaster::config(), s3f::s3fnet::DummySession::config(), s3f::s3fnet::TCPClientSession::config(), s3f::s3fnet::UDPServerSession::config(), config(), s3f::s3fnet::TCPServerSession::config(), s3f::s3fnet::TCPMaster::config(), s3f::s3fnet::NBTCPClientSession::config(), s3f::s3fnet::BTCPClientSession::config(), s3f::s3fnet::IPSession::config(), s3f::s3fnet::NBTCPServerSession::config(), s3f::s3fnet::UDPSession::connect(), s3f::s3fnet::SocketMaster::connect(), s3f::s3fnet::NBSocketMaster::connect(), s3f::s3fnet::SocketMaster::connect1(), s3f::s3fnet::NBSocketMaster::connect1(), s3f::s3fnet::SocketMaster::connected(), s3f::s3fnet::NBSocketMaster::connected(), s3f::s3fnet::UDPMaster::control(), s3f::s3fnet::SocketMaster::control(), s3f::s3fnet::NBSocketMaster::control(), s3f::s3fnet::IPSession::control(), s3f::s3fnet::TCPMaster::createSession(), data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::UDPServerSession::data_sent(), s3f::s3fnet::TCPServerSession::data_sent(), s3f::s3fnet::UDPSession::disconnect(), s3f::s3fnet::TCPMaster::enableFastTimeout(), s3f::s3fnet::SocketMaster::eof(), s3f::s3fnet::NBSocketMaster::eof(), s3f::s3fnet::UDPClientSessionContinuation::failure(), s3f::s3fnet::UDPServerSessionContinuation::failure(), s3f::s3fnet::TCPServerSessionContinuation::failure(), s3f::s3fnet::TCPClientSessionContinuation::failure(), s3f::s3fnet::BTCPClientSessionContinuation::failure(), s3f::s3fnet::TCPMaster::fast_timer_callback_body(), s3f::s3fnet::Stats::FlowStatsDump(), s3f::s3fnet::OpenFlowSwitchSession::FlowTableLookup(), s3f::s3fnet::IPSession::get_parent_by_protocol(), get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::ProtocolSession::getNow(), s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::OpenFlowSwitchSession::HandleControlInput(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), s3f::s3fnet::DummySession::init(), s3f::s3fnet::UDPMaster::init(), s3f::s3fnet::OpenFlowControllerSession::init(), s3f::s3fnet::OpenVZEventSession::init(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPServerSession::init(), init(), s3f::s3fnet::TCPServerSession::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::OpenFlowSwitchSession::init(), s3f::s3fnet::NBTCPClientSession::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::SocketMaster::init(), s3f::s3fnet::IPSession::init(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::NBSocketMaster::init(), s3f::s3fnet::NBTCPServerSession::init(), s3f::s3fnet::TCPSession::init_state_closed(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::IPSession::IPSession(), s3f::s3fnet::UDPSession::listen(), s3f::s3fnet::SocketMaster::listen(), s3f::s3fnet::NBSocketMaster::listen(), s3f::s3fnet::IPSession::load_forwarding_table(), main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), s3f::s3fnet::OpenFlowSwitchSession::ModFlow(), s3f::s3fnet::NBSocketMaster::NBSocketMaster(), s3f::s3fnet::NBTCPClientSession::NBTCPClientSession(), s3f::s3fnet::NBTCPServerSession::NBTCPServerSession(), s3f::s3fnet::NBTCPClientSession::non_blocking_loop(), s3f::s3fnet::NBTCPServerSession::non_blocking_loop(), s3f::s3fnet::OpenFlowSwitchSession::OutputControl(), s3f::s3fnet::OpenFlowSwitchSession::OutputPacket(), s3f::s3fnet::OpenFlowSwitchSession::OutputPort(), s3f::s3fnet::OpenFlowControllerSession::pop(), s3f::s3fnet::UDPMaster::pop(), s3f::s3fnet::OpenVZEventSession::pop(), s3f::s3fnet::OpenFlowSwitchSession::pop(), s3f::s3fnet::TCPMaster::pop(), s3f::s3fnet::IPSession::pop(), s3f::s3fnet::LearningController::process_recv_packet(), s3f::s3fnet::UDPMaster::push(), s3f::s3fnet::TCPMaster::push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::receive(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::LearningControllerSession::ReceiveFromSwitch(), s3f::s3fnet::OpenFlowSwitchSession::ReceivePacketOut(), s3f::s3fnet::OpenFlowSwitchSession::ReceivePortMod(), s3f::s3fnet::OpenFlowSwitchSession::ReceiveStatsRequest(), s3f::s3fnet::SocketMaster::recv(), s3f::s3fnet::NBSocketMaster::recv(), s3f::s3fnet::SocketMaster::recv1(), s3f::s3fnet::NBSocketMaster::recv1(), s3f::s3fnet::UDPServerSession::request_received(), s3f::s3fnet::TCPServerSession::request_received(), request_sent(), s3f::s3fnet::TCPClientSession::request_sent(), s3f::s3fnet::NBTCPClientSessionContinuation::resume(), s3f::s3fnet::NBTCPServerSessionContinuation::resume(), s3f::s3fnet::OpenFlowSwitchSession::RunThroughFlowTable(), s3f::s3fnet::UDPSession::send(), s3f::s3fnet::SocketMaster::send(), s3f::s3fnet::NBSocketMaster::send(), s3f::s3fnet::SocketMaster::send1(), s3f::s3fnet::NBSocketMaster::send1(), s3f::s3fnet::TCPSession::send_data(), s3f::s3fnet::OpenFlowSwitchSession::SendFlowExpired(), s3f::s3fnet::OpenFlowSwitchSession::SendOpenflowBuffer(), s3f::s3fnet::OpenFlowSwitchSession::SendPortStatus(), server_connected(), s3f::s3fnet::TCPClientSession::server_connected(), s3f::s3fnet::BTCPClientSession::server_connected(), s3f::s3fnet::UDPServerSession::session_closed(), session_closed(), s3f::s3fnet::TCPClientSession::session_closed(), s3f::s3fnet::TCPServerSession::session_closed(), s3f::s3fnet::BTCPClientSession::session_closed(), s3f::s3fnet::TCPMaster::setConnected(), s3f::s3fnet::OpenFlowSwitchSession::SetController(), s3f::s3fnet::TCPMaster::setIdle(), s3f::s3fnet::TCPMaster::setListening(), s3f::s3fnet::UDPSession::setSource(), s3f::s3fnet::TCPMaster::slow_timer_callback_body(), s3f::s3fnet::TCPSession::slowTimeoutHandling(), s3f::s3fnet::SocketMaster::socket(), s3f::s3fnet::NBSocketMaster::socket(), s3f::s3fnet::SocketMaster::SocketMaster(), s3f::s3fnet::UDPServerSession::start_on(), start_on(), s3f::s3fnet::TCPServerSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), s3f::s3fnet::NBTCPClientSession::start_on(), s3f::s3fnet::BTCPClientSession::start_on(), s3f::s3fnet::NBTCPServerSession::start_on(), s3f::s3fnet::NBTCPServerSessionContinuation::success(), s3f::s3fnet::TCPClientSession::TCPClientSession(), s3f::s3fnet::TCPMaster::TCPMaster(), s3f::s3fnet::TCPServerSession::TCPServerSession(), s3f::s3fnet::TCPSession::TCPSession(), timeout(), s3f::s3fnet::TCPClientSession::timeout(), s3f::s3fnet::BTCPClientSession::timeout(), UDPClientSession(), s3f::s3fnet::UDPMaster::UDPMaster(), s3f::s3fnet::UDPServerSession::UDPServerSession(), s3f::s3fnet::UDPSession::UDPSession(), s3f::s3fnet::TCPSession::update_timeout(), s3f::s3fnet::IPSession::verify_local_ip_address(), and s3f::s3fnet::UDPSession::wake_app().
 {
   return dynamic_cast<Host*>(ingraph);
 }
Random::RNG* s3f::s3fnet::ProtocolSession::getRandom () inline inherited
The method returns a pointer to the random number generator.
Definition at line 200 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::sess_rng.
Referenced by s3f::s3fnet::DroptailQueue::calibrate(), s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::RedQueue::enqueue(), get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::DummySession::init(), s3f::s3fnet::TCPClientSession::init(), init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::BTCPClientSession::init(), main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), and s3f::s3fnet::NetworkInterface::receivePacket().
 { return sess_rng;}
ltime_t s3f::s3fnet::ProtocolSession::getNow () inherited
The method returns the current simulation time.
To be safe, please do NOT call this function after initialization and before wrapup phase. That is, it is unsafe to call this method in the constructor, destructor, config, init, and wrapup methods. The time service is carried out by the host's owner community. This method just directs the call to the community. It's given here for convenience.
Definition at line 123 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::inHost(), and Entity::now().
Referenced by s3f::s3fnet::DroptailQueue::calibrate(), s3f::s3fnet::RedQueue::calibrate(), data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::TCPMaster::enableFastTimeout(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::TCPMaster::fast_timer_callback_body(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::TCPSession::now(), s3f::s3fnet::OpenVZEventSession::pop(), s3f::s3fnet::TCPMaster::slow_timer_callback_body(), s3f::s3fnet::SocketMaster::socket(), s3f::s3fnet::NBSocketMaster::socket(), start_on(), s3f::s3fnet::TCPClientSession::start_on(), and s3f::s3fnet::BTCPClientSession::start_on().
 {
   return inHost()->now();
 }
char * s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator () inherited
For printing the current simulation time in a better readable format.
Definition at line 128 of file protocol_session.cc.
References s3f::s3fnet::Host::getNowWithThousandSeparator(), and s3f::s3fnet::ProtocolSession::inHost().
Referenced by s3f::s3fnet::UDPSession::abort(), s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::UDPSession::connect(), s3f::s3fnet::TCPMaster::createSession(), data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::UDPServerSession::data_sent(), s3f::s3fnet::TCPServerSession::data_sent(), s3f::s3fnet::UDPSession::disconnect(), s3f::s3fnet::RedQueue::enqueue(), get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::TCPClientSession::init(), init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::UDPSession::listen(), main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), s3f::s3fnet::DummySession::pop(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::OpenVZEventSession::pop(), s3f::s3fnet::UDPMaster::pop(), s3f::s3fnet::TCPMaster::pop(), s3f::s3fnet::IPSession::pop(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::UDPMaster::push(), s3f::s3fnet::SimplePhy::push(), s3f::s3fnet::TCPMaster::push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::receive(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::SimplePhy::receivePacket(), s3f::s3fnet::UDPServerSession::request_received(), s3f::s3fnet::TCPServerSession::request_received(), request_sent(), s3f::s3fnet::TCPClientSession::request_sent(), s3f::s3fnet::UDPSession::send(), s3f::s3fnet::TCPSession::send_data(), s3f::s3fnet::SimplePhy::sendPacket(), server_connected(), s3f::s3fnet::TCPClientSession::server_connected(), s3f::s3fnet::BTCPClientSession::server_connected(), s3f::s3fnet::UDPServerSession::session_closed(), session_closed(), s3f::s3fnet::TCPClientSession::session_closed(), s3f::s3fnet::TCPServerSession::session_closed(), s3f::s3fnet::BTCPClientSession::session_closed(), s3f::s3fnet::TCPMaster::setConnected(), s3f::s3fnet::TCPMaster::setIdle(), s3f::s3fnet::TCPMaster::setListening(), s3f::s3fnet::UDPSession::setSource(), s3f::s3fnet::TCPSession::slowTimeoutHandling(), s3f::s3fnet::UDPServerSession::start_on(), start_on(), s3f::s3fnet::TCPServerSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), s3f::s3fnet::BTCPClientSession::start_on(), s3f::s3fnet::TCPSession::TCPSession(), timeout(), s3f::s3fnet::TCPClientSession::timeout(), s3f::s3fnet::BTCPClientSession::timeout(), s3f::s3fnet::UDPSession::UDPSession(), s3f::s3fnet::TCPSession::update_timeout(), and s3f::s3fnet::UDPSession::wake_app().
 {
         return inHost()->getNowWithThousandSeparator();
 }
int s3f::s3fnet::ProtocolSession::configured () inline inherited
This method returns true if the protocol session has been configured.
This method is used to make sure we configure the protocol session before initializing it.
Definition at line 221 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_CONFIGURED, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::config(), and s3f::s3fnet::ProtocolSession::init().
 { return stage >= PSESS_CONFIGURED; }
int s3f::s3fnet::ProtocolSession::initialized () inline inherited
This method returns true if the protocol session has been initialized.
This can be used to sequence calls to the init method of protocol sessions. For example, if protocol session A requires protocol session B to be initialized before A can be initialized, A's init method can call B's init method as long as B's initialized() returns true. The system does not enforce any ordering in its calls the init methods of all protocol sessions declared in the dml configuration.
Definition at line 233 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_INITIALIZED, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::init(), and s3f::s3fnet::ProtocolSession::wrapup().
 { return stage >= PSESS_INITIALIZED; }
int s3f::s3fnet::ProtocolSession::wrapped_up () inline inherited
This method returns true if the protocol session has been wrapped up.
This can be used to sequence calls to the wrapup method of protocol sessions. For example, if protocol session A requires protocol session B to be wrapped up before A can be wrapped up, A's wrapup method can call B's wrapup method as long as B's wrapped_up() returns true. The system does not enforce any ordering in its calls the wrapup methods of all protocol sessions declared in the dml configuration.
Definition at line 245 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_WRAPPED_UP, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::wrapup().
 { return stage >= PSESS_WRAPPED_UP; }
virtual const char* s3f::s3fnet::ProtocolSession::psesstype () inline virtual inherited
Reimplemented in s3f::s3fnet::NBSocketMaster, and s3f::s3fnet::SocketMaster.
Definition at line 247 of file protocol_session.h.
 { return "GENERIC"; } // DEBUG
virtual int s3f::s3fnet::ProtocolSession::instantiation_type () inline protected virtual inherited
This method controls how protocol instances can coexist with one another.
It returns one of the following:
PROT_UNIQUE_INSTANCE (default): allows only one instance for each type of protocol per protocol stack;
PROT_MULTIPLE_INSTANCES: allows multiple instances of the same implementation for each type of protocol per protocol stack;
PROT_MULTIPLE_IMPLEMENTATIONS: allows multiple instances from different implementations of the same protocol to exist on the protocol stack.
Reimplemented in s3f::s3fnet::BTCPClientSession, and s3f::s3fnet::TCPClientSession.
Definition at line 269 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PROT_UNIQUE_INSTANCE.
Referenced by s3f::s3fnet::ProtocolGraph::insert_session().
 { return PROT_UNIQUE_INSTANCE; }
Member Data Documentation
Process* s3f::s3fnet::UDPClientSession::start_timer_callback_proc
Provide call_back functionality for implementing the start timer in the UDPClientSession this S3F process is used by waitFor() function.
Definition at line 60 of file udp_client.h.
Referenced by main_proc().
ProtocolCallbackActivation* s3f::s3fnet::UDPClientSession::start_timer_ac
Definition at line 66 of file udp_client.h.
Referenced by main_proc().
bool s3f::s3fnet::UDPClientSession::start_timer_called_once
Storing the data for the callback function.
In this case, the UDPClientSession object is stored.
Definition at line 68 of file udp_client.h.
Referenced by init(), and start_timer_callback_body().
ltime_t s3f::s3fnet::UDPClientSession::start_time private
Time before a session starts.
Definition at line 104 of file udp_client.h.
Referenced by config(), and init().
double s3f::s3fnet::UDPClientSession::start_time_double private
Definition at line 105 of file udp_client.h.
Referenced by config(), and init().
ltime_t s3f::s3fnet::UDPClientSession::start_window private
Size of random window before session starts.
Definition at line 106 of file udp_client.h.
Referenced by config(), and init().
double s3f::s3fnet::UDPClientSession::start_window_double private
Definition at line 107 of file udp_client.h.
Referenced by config(), and init().
ltime_t s3f::s3fnet::UDPClientSession::user_timeout private
timeout before aborting a session
Definition at line 108 of file udp_client.h.
Referenced by config(), and request_sent().
ltime_t s3f::s3fnet::UDPClientSession::off_time private
Off time between sessions.
Definition at line 109 of file udp_client.h.
Referenced by config(), and main_proc().
double s3f::s3fnet::UDPClientSession::off_time_double private
Definition at line 110 of file udp_client.h.
Referenced by config(), and main_proc().
bool s3f::s3fnet::UDPClientSession::off_time_run_first private
Whether 1st session starts with an off time.
Definition at line 111 of file udp_client.h.
Referenced by config(), and init().
bool s3f::s3fnet::UDPClientSession::off_time_exponential private
Constant or exponential off time.
Definition at line 112 of file udp_client.h.
Referenced by config(), and main_proc().
bool s3f::s3fnet::UDPClientSession::fixed_server private
Whether to find a random target.
Definition at line 113 of file udp_client.h.
Referenced by config(), start_on(), and start_once().
uint32 s3f::s3fnet::UDPClientSession::request_size private
Size of the request sent to the server.
Definition at line 114 of file udp_client.h.
Referenced by config(), and server_connected().
uint32 s3f::s3fnet::UDPClientSession::file_size private
Size of the file to be sent from the server.
Definition at line 115 of file udp_client.h.
Referenced by config(), data_received(), request_sent(), and server_connected().
uint16 s3f::s3fnet::UDPClientSession::start_port private
The starting port number for client sessions.
Definition at line 116 of file udp_client.h.
Referenced by config(), and start_on().
S3FNET_STRING s3f::s3fnet::UDPClientSession::server_list private
Definition at line 117 of file udp_client.h.
Referenced by config(), and get_random_server().
bool s3f::s3fnet::UDPClientSession::show_report private
Whether we print out the result or not.
Definition at line 118 of file udp_client.h.
Referenced by config(), data_received(), and get_random_server().
SocketMaster* s3f::s3fnet::UDPClientSession::sm private
Points to the socket master.
Definition at line 121 of file udp_client.h.
Referenced by data_received(), s3f::s3fnet::UDPClientSessionContinuation::failure(), init(), request_sent(), server_connected(), start_on(), and timeout().
IPADDR s3f::s3fnet::UDPClientSession::client_ip private
The ip address of the client (interface 0).
Definition at line 123 of file udp_client.h.
Referenced by data_received(), and init().
uint32 s3f::s3fnet::UDPClientSession::nsess private
Number of sessions initiated by this client (statistics).
Definition at line 124 of file udp_client.h.
Referenced by start_on().
IPADDR s3f::s3fnet::UDPClientSession::server_ip private
Server ip address of the current connection.
Definition at line 126 of file udp_client.h.
Referenced by data_received(), start_on(), and start_once().
uint16 s3f::s3fnet::UDPClientSession::server_port private
Server port number of the current connection.
Definition at line 127 of file udp_client.h.
Referenced by get_random_server(), start_on(), and start_once().
char* s3f::s3fnet::ProtocolSession::name inherited
Symbolic name of the protocol this session implements.
The name of the protocol is derived from the DML 'name' attribute. It must not be NULL once the protocol session is configured.
Definition at line 63 of file protocol_session.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::SimpleMac::init(), s3f::s3fnet::UDPMaster::init(), s3f::s3fnet::SimplePhy::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::SocketMaster::init(), s3f::s3fnet::IPSession::init(), s3f::s3fnet::NBSocketMaster::init(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::ProtocolGraph::insert_session(), s3f::s3fnet::ProtocolSession::wrapup(), and s3f::s3fnet::ProtocolSession::~ProtocolSession().
float s3f::s3fnet::ProtocolSession::version inherited
Version number of this protocol implemenntation, represented as a floating point number (e.g., 1.23).
Definition at line 69 of file protocol_session.h.
char* s3f::s3fnet::ProtocolSession::use inherited
Name of the protocol class from which this protocol session is instantiated.
The protocol class must be registered with the Protocols class so that we will be able to instantiate an object from the class. (C++ does not support self-reflection). The class name must not be NULL once the protocol session is configured.
Definition at line 79 of file protocol_session.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::ProtocolGraph::insert_session(), and s3f::s3fnet::ProtocolSession::~ProtocolSession().
ProtocolGraph* s3f::s3fnet::ProtocolSession::ingraph protected inherited
Points to the protocol graph.
Definition at line 335 of file protocol_session.h.
Referenced by s3f::s3fnet::NicProtocolSession::getNetworkInterface(), s3f::s3fnet::ProtocolSession::inGraph(), and s3f::s3fnet::ProtocolSession::inHost().
Random::RNG* s3f::s3fnet::ProtocolSession::sess_rng protected inherited
Pointer to a random number generator.
Definition at line 338 of file protocol_session.h.
Referenced by s3f::s3fnet::ProtocolSession::getRandom(), and s3f::s3fnet::ProtocolSession::init().
int s3f::s3fnet::ProtocolSession::stage protected inherited
This variable indicates the current stage of this protocol session.
Each protocol session will go through four staged: PSESS_CREATED, PSESS_CONFIGURED, PSESS_INITIALIZED, and then PSESS_WRAPPED_UP.
Definition at line 346 of file protocol_session.h.
Referenced by s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::ProtocolSession::configured(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::ProtocolSession::initialized(), s3f::s3fnet::ProtocolSession::wrapped_up(), and s3f::s3fnet::ProtocolSession::wrapup().
The documentation for this class was generated from the following files:
udp_client.h
udp_client.cc