S3F: s3f::s3fnet::TCPSession Class Reference
s3f::s3fnet::TCPSession Class Reference
The TCP session.
#include <tcp_session.h>
Public Types
enum {
TCP_STATE_CLOSED = 0, TCP_STATE_LISTEN = 1, TCP_STATE_SYN_SENT = 2, TCP_STATE_SYN_RECEIVED = 3,
TCP_STATE_ESTABLISHED = 4, TCP_STATE_CLOSE_WAIT = 5, TCP_STATE_CLOSING = 6, TCP_STATE_FIN_WAIT_1 = 7,
TCP_STATE_FIN_WAIT_2 = 8, TCP_STATE_LAST_ACK = 9, TCP_STATE_TIME_WAIT = 10
}
Public Member Functions
TCPSession (TCPMaster *master, int sock)
The constructor.
virtual ~TCPSession ()
The destructor.
virtual bool connect (IPADDR destip, uint16 destport)
Connect to a destination ip address and port number.
virtual void disconnect ()
Disconnect this session.
virtual int send (int length, byte *msg=0)
Send the given number of bytes.
virtual int recv (int length, byte *msg=0)
Receive a message of the given size.
virtual bool listen ()
Passive open.
virtual bool connected ()
Whether a connection is made.
virtual bool setSource (IPADDR ip, uint16 port)
Set the ip and the port number of the connection.
virtual void abort ()
Abort the session.
virtual void setSocketID (int sock)
Set socket.
virtual SessionMaster * getSessionMaster ()
Return the master protocol session.
virtual void release ()
Release this session if unnecessary.
void receive (TCPMessage *tcphdr)
Receive the message popped up from the ip session.
void slowTimeoutHandling ()
Slow timeout handler (in tcp_tmr.cc).
void fastTimeoutHandling ()
Fast timeout handler (in tcp_tmr.cc).
virtual void reinit ()
Called by socket to reinitialize the destination ip and port.
char * toString (char *buf)
Translate the ID into a textual string.
Public Attributes
uint32 prot_id
The protocol number.
IPADDR src_ip
Source ip address.
IPADDR dst_ip
Destination ip address.
uint16 src_port
Source port number.
uint16 dst_port
Destination port number.
Private Member Functions
bool is_ok (int action)
Return true if the given action is ok at the time.
bool active_open (IPADDR dst_ip, uint16 dst_port)
Active open.
bool passive_open ()
Passive open.
void appl_close ()
Close the connection.
void allocate_buffers ()
Allocate both send and receive windows.
void deallocate_buffers ()
Deallocate both send and receive windows.
void reset ()
Reset the session to CLOSED state and wake up application.
void wake_app (int signal)
Wake application upon a signal.
void clear_app_state (int signal)
Clear application signal bit(s).
int init_state_closed ()
Change to CLOSED state.
int init_state_syn_sent ()
Change to SYN_SENT state.
int init_state_syn_received ()
Change to SYN_RECEIVED state.
int init_state_listen ()
Change to LISTEN state.
int init_state_established ()
Change to ESTABLISHED state.
int init_state_close_wait ()
Change to CLOSE_WAIT state.
int init_state_last_ack ()
Change to LAST_ACK state.
int init_state_fin_wait_1 ()
Change to FIN_WAIT_1 state.
int init_state_fin_wait_2 ()
Change to FIN_WAIT_2 state.
int init_state_closing ()
Change to CLOSING state.
int init_state_time_wait ()
Change to TIME_WAIT state.
uint32 appl_send (uint32 length, byte *msg)
When the upper layer attempts to send out data, this function will be called.
void send_data (uint32 seqno, uint32 datalen=0, byte mask=0, uint32 ackno=0, bool need_calc_rtt=false, bool need_set_rextimeout=false)
Physically send the data to the IP layer.
uint32 segment_and_send (uint32 seqno, uint32 length)
Segment and send data.
uint32 resend_segments (uint32 seqno, uint32 nsegments)
Resend the segments.
void acknowledge (bool nodelay)
Generate acknowledgements; no delay is imposed if the nodelay parameter is true.
void timeout_resend ()
This function is called when retransmission timer expires.
uint32 calc_advertised_wnd ()
Calculate the advertised window size.
void send_delay_ack ()
Set the session to send delayed ACK when next time the fast timer fires.
void cancel_delay_ack ()
Set the session to cancel sending delayed ACK when next timer the fast timer fires.
uint32 appl_recv (uint32 length, byte *msg)
When the upper layer wants to receive data (length bytes) from TCP, this function will be called.
void process_SYN (TCPMessage *tcphdr, int &signal)
Process SYN packets.
void process_FIN (int &signal)
Process FIN packets.
bool process_ACK (TCPMessage *tcphdr, int &signal)
Process ACK packets.
bool process_acks (TCPMessage *tcphdr)
Process the ACKs that correspond to received TCP message, and update session states like RTT and retransmission timer.
bool process_new_data (DataMessage *payload, uint32 seqno)
Process data arrival.
void process_dup_acks ()
Process duplicate ACKs received.
void process_new_acks (TCPMessage *tcphdr, uint32 acked)
Process ACKs that respond to new data.
void check_cwnd ()
Check congestion window size.
void calc_threshold ()
Calculate the threshold.
void update_remote_window_size (uint32 window_size)
update the remote receive window size.
uint32 slow_timeout_handling_helper (const uint32 timerid)
Slow timeout handler with a given timer id.
void update_timeout ()
Update the current smoothed RTT timeout with the new rtt measurment.
void backoff_timeout ()
Backoff the current timeout.
ltime_t now ()
An alias to get the current simulation time.
ltime_t timeout_value ()
Current smoothed RTT timeout value.
double timeout_double_value ()
double initial_timeout ()
Return initial timeout value for the first timeout.
bool checkIdle ()
Check whether the idle time is long enough to slow start.
int sender_send_sack (int sack_flag, byte mask, byte *&options)
This method handles the situation when a sender tries to send a packet.
int receiver_send_sack (int sack_flag, byte mask, uint32 ackno, byte *&options)
This method handles the situation when a receiver tries to send a packet.
void sender_recv_sack (TCPMessage *tcphdr)
This method handles the situation when a sender receives sack options.
void receiver_recv_sack (TCPMessage *tcphdr)
This method handles the situation when a receiver receives a packet.
void sack_send_in_fast_recovery ()
The method handles sending sack when fast recovery is enabled.
bool sack_resend_segments (bool first_flag)
When the sack option is set, this method is used for retransmissions.
Static Private Member Functions
static char * get_state_name (int state)
Translate the tcp state into a string.
Private Attributes
TCPMaster * tcp_master
Point to the tcp master.
int state
The current state of the tcp session.
int socket
The socket id.
TCPRecvWindow * rcvwnd
The receive window of the tcp session.
TCPSendWindow * sndwnd
The send window of the tcp session.
uint32 rcvwnd_size
Remote receive window size.
uint32 cwnd
Congestion window.
uint32 ssthresh
Threshold size for updating the congestion window.
uint32 mss
Maximum segment size.
uint32 ndupacks
Number of consecutive duplicate ACKs received.
uint32 nrxmits
Number of consecutive packet retransmissions.
uint32 persist_shift
Left shift to get persist (exponential) timeout.
int rtt_smoothed
Smoothed round trip time.
int rtt_measured
Measured round trip time.
int rtt_count
The current RTT count.
int rtt_var
Current estimated RTT variance.
uint32 rxmit_seq
The last sequence number of retransmitted segment plus one.
uint32 measured_seq
The sequence number of the segment currently being measured.
uint32 recover_seq
The largest seqno sent out when loss happens.
uint32 sack_pipe
Indicate how much can be sent during fast recovery in SACK.
bool delayed_ack
True if the delayed ack is turned on.
bool fast_recovery
True if the session is still in the fast recovery mode.
bool timeout_loss
Whether it is a timeout loss.
bool sack_permitted
Whether SACK is permitted as indicated by the peer.
bool close_issued
Whether the upper layer has issued close.
bool simultaneous_closing
Whether it is a simultaneous closing.
TCPBlockList * snd_scoreboard
The score board for blocks sacked maintained by the sender side.
TCPBlockList * rcv_scoreboard
The score board for the receiver side.
ltime_t rxmit_timeout
The current retransmission timeout.
double rxmit_timeout_double
ltime_t idle_time
Idle time for the other party.
double idle_time_double
ltime_t rxmit_timer_count
Retransmission timer count.
double rxmit_timer_count_double
ltime_t msl_timer_count
The timer count that lasts 2*msl.
double msl_timer_count_double
Detailed Description
The TCP session.
Definition at line 24 of file tcp_session.h.
Member Enumeration Documentation
anonymous enum
Enumerator
TCP_STATE_CLOSED
TCP_STATE_LISTEN
TCP_STATE_SYN_SENT
TCP_STATE_SYN_RECEIVED
TCP_STATE_ESTABLISHED
TCP_STATE_CLOSE_WAIT
TCP_STATE_CLOSING
TCP_STATE_FIN_WAIT_1
TCP_STATE_FIN_WAIT_2
TCP_STATE_LAST_ACK
TCP_STATE_TIME_WAIT
Definition at line 29 of file tcp_session.h.
        {
     TCP_STATE_CLOSED       = 0,
     TCP_STATE_LISTEN       = 1,
     TCP_STATE_SYN_SENT     = 2,
     TCP_STATE_SYN_RECEIVED = 3,
     TCP_STATE_ESTABLISHED  = 4,
     TCP_STATE_CLOSE_WAIT   = 5,
     TCP_STATE_CLOSING      = 6,
     TCP_STATE_FIN_WAIT_1   = 7,
     TCP_STATE_FIN_WAIT_2   = 8,
     TCP_STATE_LAST_ACK     = 9,
     TCP_STATE_TIME_WAIT    = 10
   };
Constructor & Destructor Documentation
s3f::s3fnet::TCPSession::TCPSession (TCPMaster * master, int sock)
The constructor.
Definition at line 29 of file tcp_session.cc.
References s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::inHost(), init_state_closed(), s3f::s3fnet::DmlObject::nhi, TCP_DUMP, tcp_master, and s3f::s3fnet::Nhi::toString().
                                                   :
   SocketSession(S3FNET_PROTOCOL_TYPE_TCP),
   tcp_master(master), state(0), socket(sock),
   rcvwnd(0), sndwnd(0),
   rcvwnd_size(0), cwnd(0), ssthresh(0), mss(0),
   ndupacks(0), nrxmits(0), persist_shift(0),
   rtt_smoothed(0), rtt_measured(0), rtt_count(0), rtt_var(0),
   rxmit_seq(0), measured_seq(0), recover_seq(0), sack_pipe(0),
   delayed_ack(false), fast_recovery(false),
   timeout_loss(false), sack_permitted(false),
   close_issued(false), simultaneous_closing(false),
   snd_scoreboard(0), rcv_scoreboard(0),
   rxmit_timeout(0), idle_time(0),
   rxmit_timer_count(0), msl_timer_count(0)
 {
   TCP_DUMP(printf("[host=\"%s\"] %s: new tcp session.\n",
                   tcp_master->inHost()->nhi.toString(), tcp_master->getNowWithThousandSeparator()));
   init_state_closed();
 }
s3f::s3fnet::TCPSession::~TCPSession () virtual
The destructor.
Definition at line 50 of file tcp_session.cc.
References rcvwnd, and sndwnd.
 {
   if(rcvwnd) delete rcvwnd;
   if(sndwnd) delete sndwnd;
 }
Member Function Documentation
bool s3f::s3fnet::TCPSession::connect (IPADDR destip, uint16 destport) virtual
Connect to a destination ip address and port number.
Returns true if the connection has been established successfuly.
Implements s3f::s3fnet::SocketSession.
Definition at line 56 of file tcp_session.cc.
References active_open(), APP_ACTION_CONNECT, and is_ok().
 {
   if(is_ok(APP_ACTION_CONNECT))
   {
     // Not allowing connection from LISTEN state. Can be added easily here,
     // by just switching the state back to CLOSED and connecting
     return active_open(destip, destport);
   }
   return false;
 }
void s3f::s3fnet::TCPSession::disconnect () virtual
Disconnect this session.
Implements s3f::s3fnet::SocketSession.
Definition at line 67 of file tcp_session.cc.
References APP_ACTION_DISCONNECT, appl_close(), and is_ok().
 {
   if(is_ok(APP_ACTION_DISCONNECT))
   {
     appl_close();
   }
 }
int s3f::s3fnet::TCPSession::send (int length, byte * msg = 0) virtual
Send the given number of bytes.
The msg parameter, if not NULL, points to the message storage. The method returns the number of bytes that have truly been sent out. -1 means error.
Implements s3f::s3fnet::SocketSession.
Definition at line 75 of file tcp_session.cc.
References APP_ACTION_SEND, appl_send(), and is_ok().
 {
   if(is_ok(APP_ACTION_SEND))
   {
     return appl_send(length, msg);
   }
   return 0;
 }
int s3f::s3fnet::TCPSession::recv (int length, byte * msg = 0) virtual
Receive a message of the given size.
The msg parameter, if not NULL, points to the buffer to store the message. The method returns the number of bytes that have been truly received. -1 means error.
Implements s3f::s3fnet::SocketSession.
Definition at line 84 of file tcp_session.cc.
References APP_ACTION_RECEIVE, appl_recv(), and is_ok().
 {
   if(is_ok(APP_ACTION_RECEIVE))
   {
     return appl_recv(length, msg);
   }
   return 0;
 }
bool s3f::s3fnet::TCPSession::listen () virtual
Passive open.
Returns true if there is an incoming connection that has been established successfully.
Implements s3f::s3fnet::SocketSession.
Definition at line 93 of file tcp_session.cc.
References APP_ACTION_LISTEN, is_ok(), and passive_open().
 {
   if(is_ok(APP_ACTION_LISTEN))
   {
     passive_open();
     return true;
   }
   return false;
 }
bool s3f::s3fnet::TCPSession::connected () virtual
Whether a connection is made.
Returns true if connected.
Implements s3f::s3fnet::SocketSession.
Definition at line 103 of file tcp_session.cc.
References state, and TCP_STATE_ESTABLISHED.
 {
   return state >= TCP_STATE_ESTABLISHED;
 }
bool s3f::s3fnet::TCPSession::setSource (IPADDR ip, uint16 port) virtual
Set the ip and the port number of the connection.
Returns true if set up correctly.
Implements s3f::s3fnet::SocketSession.
Definition at line 108 of file tcp_session.cc.
References s3f::s3fnet::SessionID::src_ip, and s3f::s3fnet::SessionID::src_port.
 {
   src_ip   = ip;
   src_port = port;
   return true;
 }
void s3f::s3fnet::TCPSession::abort () virtual
Abort the session.
Implements s3f::s3fnet::SocketSession.
Definition at line 116 of file tcp_session.cc.
References s3f::s3fnet::TCPSeqWindow::expect(), s3f::s3fnet::TCPSeqWindow::next(), rcvwnd, reset(), send_data(), sndwnd, and s3f::s3fnet::TCPMessage::TCP_FLAG_RST.
 {
   if(sndwnd)
   {
     assert(rcvwnd);
     send_data(sndwnd->next(), 0, TCPMessage::TCP_FLAG_RST, rcvwnd->expect(), false, false);
   }
   reset();
 }
virtual void s3f::s3fnet::TCPSession::setSocketID (int sock) inline virtual
Set socket.
Implements s3f::s3fnet::SocketSession.
Definition at line 88 of file tcp_session.h.
References socket.
 { socket = sock; }
virtual SessionMaster* s3f::s3fnet::TCPSession::getSessionMaster () inline virtual
Return the master protocol session.
Implements s3f::s3fnet::SocketSession.
Definition at line 91 of file tcp_session.h.
References tcp_master.
 { return tcp_master; }
void s3f::s3fnet::TCPSession::release () virtual
Release this session if unnecessary.
Implements s3f::s3fnet::SocketSession.
Definition at line 126 of file tcp_session.cc.
References s3f::s3fnet::TCPMaster::deleteSession(), and tcp_master.
 {
   assert(tcp_master);
   tcp_master->deleteSession(this);
 }
void s3f::s3fnet::TCPSession::receive (TCPMessage * tcphdr)
Receive the message popped up from the ip session.
Definition at line 40 of file tcp_receiver.cc.
References s3f::s3fnet::TCPMessage::ackno, acknowledge(), s3f::s3fnet::TCPRecvWindow::available(), s3f::s3fnet::TCPSendWindow::canSend(), close_issued, s3f::s3fnet::SocketSignal::DATA_AVAILABLE, s3f::s3fnet::TCPSendWindow::dataInBuffer(), s3f::s3fnet::TCPSeqWindow::empty(), s3f::s3fnet::TCPSeqWindow::firstUnused(), s3f::s3fnet::TCPMessage::flags, get_state_name(), s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::inHost(), init_state_fin_wait_1(), s3f::s3fnet::TCPSendWindow::needToRequest(), s3f::s3fnet::DmlObject::nhi, s3f::s3fnet::SocketSignal::NO_SIGNAL, s3f::s3fnet::SocketSignal::OK_TO_SEND, s3f::s3fnet::ProtocolMessage::payload(), process_ACK(), process_FIN(), process_new_data(), process_SYN(), rcvwnd, s3f::s3fnet::DataMessage::realByteCount(), reset(), s3f::s3fnet::TCPRecvWindow::resetRecvParameters(), segment_and_send(), s3f::s3fnet::TCPMessage::seqno, sndwnd, state, TCP_DUMP, s3f::s3fnet::TCPMessage::TCP_FLAG_ACK, s3f::s3fnet::TCPMessage::TCP_FLAG_FIN, s3f::s3fnet::TCPMessage::TCP_FLAG_PSH, s3f::s3fnet::TCPMessage::TCP_FLAG_RST, s3f::s3fnet::TCPMessage::TCP_FLAG_SYN, s3f::s3fnet::TCPMessage::TCP_FLAG_URG, tcp_master, TCP_STATE_CLOSE_WAIT, TCP_STATE_CLOSED, TCP_STATE_ESTABLISHED, TCP_STATE_FIN_WAIT_1, TCP_STATE_FIN_WAIT_2, TCP_STATE_LISTEN, TCP_STATE_SYN_SENT, s3f::s3fnet::Nhi::toString(), wake_app(), and s3f::s3fnet::TCPMessage::wsize.
 {
   TCP_DUMP(printf("[host=\"%s\"] %s: receive(), flags=[%c%c%c%c%c%c] "
                   "seqno=%u, ackno=%u, wsize=%u, len=%u [state=%s]\n",
                   tcp_master->inHost()->nhi.toString(),
                   tcp_master->getNowWithThousandSeparator(),
                   (tcphdr->flags & TCPMessage::TCP_FLAG_SYN) ? 'S' : '.',
                   (tcphdr->flags & TCPMessage::TCP_FLAG_FIN) ? 'F' : '.',
                   (tcphdr->flags & TCPMessage::TCP_FLAG_RST) ? 'R' : '.',
                   (tcphdr->flags & TCPMessage::TCP_FLAG_ACK) ? 'A' : '.',
                   (tcphdr->flags & TCPMessage::TCP_FLAG_URG) ? 'U' : '.',
                   (tcphdr->flags & TCPMessage::TCP_FLAG_PSH) ? 'P' : '.',
                   tcphdr->seqno, tcphdr->ackno, tcphdr->wsize,
                   tcphdr->payload() ? ((DataMessage*)tcphdr->payload())->realByteCount() : 0,
                   get_state_name(state)));
   // if true ack will be sent immediately
   bool must_ack = false;
   int signal = 0;
   // if it's RST segment, reset the connection
   if(tcphdr->flags & TCPMessage::TCP_FLAG_RST)
   {
     if (state != TCP_STATE_LISTEN) reset();
     return;
   }
   // if it's a SYN segment, handle it
   if(tcphdr->flags & TCPMessage::TCP_FLAG_SYN)
   {
     process_SYN(tcphdr, signal);
     if(state == TCP_STATE_SYN_SENT) must_ack = true;
   }
   // if it's a FIN segment, handle it
   if(tcphdr->flags & TCPMessage::TCP_FLAG_FIN)
   {
     process_FIN(signal);
     must_ack = true;
   }
   // handle new data
   DataMessage* payload = (DataMessage*)tcphdr->payload();
   if((payload && payload->realByteCount() > 0) &&  // there is new data coming
      (state == TCP_STATE_ESTABLISHED || state == TCP_STATE_FIN_WAIT_1 ||
       state == TCP_STATE_FIN_WAIT_2))
   {
     if(process_new_data(payload, tcphdr->seqno))
       must_ack = true;
     // collect the bytes report to the socket layer once we received
     // the expected bytes
     if(rcvwnd->available())
     {
       signal |= SocketSignal::DATA_AVAILABLE;
       rcvwnd->resetRecvParameters();
     }
   }
   // if it's an ACK segment, handle it
   if(tcphdr->flags & TCPMessage::TCP_FLAG_ACK)
   {
     if(process_ACK(tcphdr, signal))  must_ack = true;
   }
   if(state == TCP_STATE_CLOSED) return;
   // if we got a non-zero sized packet or must ack immediately then
   // send an ACK
   if(must_ack || (payload && payload->realByteCount() > 0))
     acknowledge(must_ack);
   // check whether to send data
   if(state == TCP_STATE_ESTABLISHED || state == TCP_STATE_CLOSE_WAIT)
   {
     // figure how much data we could send out
     uint32 len_to_send = sndwnd->canSend();
     // check whether we can send out packets.
     if(len_to_send > 0)
     {
       uint32 seqno = sndwnd->firstUnused();
       segment_and_send(seqno, len_to_send);
       if(sndwnd->needToRequest())
       {
         signal |= SocketSignal::OK_TO_SEND;
       }
     }
   }
   if(close_issued && state == TCP_STATE_ESTABLISHED)
   {
     // if the upper layer has issued close, check whether
     if(sndwnd->empty() && sndwnd->dataInBuffer() == 0)
     {
       signal |= init_state_fin_wait_1();
     }
   }
   //printf("state=%d, signal=%d, close_issued=%d\n", state, signal, close_issued);
   // if there is a signal to send to application then send it ghyan
   // for further consideration!
   if(signal != SocketSignal::NO_SIGNAL) wake_app(signal);
 }
void s3f::s3fnet::TCPSession::slowTimeoutHandling ()
Slow timeout handler (in tcp_tmr.cc).
Definition at line 29 of file tcp_timer.cc.
References s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::TCPMaster::getSlowTimeout(), s3f::s3fnet::ProtocolSession::inHost(), msl_timer_count, s3f::s3fnet::DmlObject::nhi, RETX_TIMER, rtt_count, rxmit_timer_count, slow_timeout_handling_helper(), state, TCP_DUMP, tcp_master, TCP_STATE_TIME_WAIT, s3f::s3fnet::Nhi::toString(), TWO_MSL_TIMER, and wake_app().
 {
   uint32 signal = 0;
   // update measured RTT
   if(rtt_count) rtt_count++;
   TCP_DUMP(printf("[host=\"%s\"] %s: slowTimeoutHandling(), rtt=%d, rxmit=%ld, msl=%ld.\n",
                   tcp_master->inHost()->nhi.toString(),
                   tcp_master->getNowWithThousandSeparator(), rtt_count,
                   rxmit_timer_count, msl_timer_count));
   // update retransmission timer. if the count is set as 0, then it's
   // not a valid timer, meaning that the timer is not set.
   if(rxmit_timer_count > 0)
   {
     rxmit_timer_count -= tcp_master->getSlowTimeout();
     // if it's time out, handle it.
     if(rxmit_timer_count <= 0)
       signal |= slow_timeout_handling_helper(RETX_TIMER);
   }
   // update 2msl timer.
   if(msl_timer_count > 0)
   {
     msl_timer_count -= tcp_master->getSlowTimeout();
     // if it's time out, handle it.
     if(msl_timer_count <= 0)
       signal |= slow_timeout_handling_helper(TWO_MSL_TIMER);
   }
   else if(state == TCP_STATE_TIME_WAIT)
   {
     signal |= slow_timeout_handling_helper(TWO_MSL_TIMER);
   }
   if(signal) wake_app(signal);
 }
void s3f::s3fnet::TCPSession::fastTimeoutHandling ()
Fast timeout handler (in tcp_tmr.cc).
Definition at line 125 of file tcp_timer.cc.
References cancel_delay_ack(), delayed_ack, s3f::s3fnet::TCPSeqWindow::expect(), s3f::s3fnet::TCPSeqWindow::firstUnused(), rcvwnd, send_data(), sndwnd, and s3f::s3fnet::TCPMessage::TCP_FLAG_ACK.
 {
   if(delayed_ack)
   {
     send_data(sndwnd->firstUnused(), 0, TCPMessage::TCP_FLAG_ACK, rcvwnd->expect(), false, false);
     cancel_delay_ack();
   }
 }
char * s3f::s3fnet::TCPSession::get_state_name (int state) static private
Translate the tcp state into a string.
Definition at line 132 of file tcp_session.cc.
References TCP_STATE_CLOSE_WAIT, TCP_STATE_CLOSED, TCP_STATE_CLOSING, TCP_STATE_ESTABLISHED, TCP_STATE_FIN_WAIT_1, TCP_STATE_FIN_WAIT_2, TCP_STATE_LAST_ACK, TCP_STATE_LISTEN, TCP_STATE_SYN_RECEIVED, TCP_STATE_SYN_SENT, and TCP_STATE_TIME_WAIT.
Referenced by process_ACK(), receive(), and send_data().
 {
   switch(state)
   {
           case TCP_STATE_CLOSED: return "CLOSED";
           case TCP_STATE_LISTEN: return "LISTEN";
           case TCP_STATE_SYN_SENT: return "SYN_SENT";
           case TCP_STATE_SYN_RECEIVED: return "SYN_RECEIVED";
           case TCP_STATE_ESTABLISHED: return "ESTABLISHED";
           case TCP_STATE_CLOSE_WAIT: return "CLOSE_WAIT";
           case TCP_STATE_CLOSING: return "CLOSING";
           case TCP_STATE_FIN_WAIT_1: return "FIN_WAIT_1";
           case TCP_STATE_FIN_WAIT_2: return "FIN_WAIT_2";
           case TCP_STATE_LAST_ACK: return "LAST_ACK";
           case TCP_STATE_TIME_WAIT: return "TIME_WAIT";
           default: return "UNKNOWN";
   }
 }
bool s3f::s3fnet::TCPSession::is_ok (int action) private
Return true if the given action is ok at the time.
Definition at line 151 of file tcp_session.cc.
References APP_ACTION_CONNECT, APP_ACTION_DISCONNECT, APP_ACTION_LISTEN, APP_ACTION_RECEIVE, APP_ACTION_RESET_PORT, APP_ACTION_SEND, state, tcp_master, TCP_STATE_CLOSE_WAIT, TCP_STATE_CLOSED, TCP_STATE_ESTABLISHED, TCP_STATE_FIN_WAIT_1, TCP_STATE_FIN_WAIT_2, and TCP_STATE_TIME_WAIT.
Referenced by connect(), disconnect(), listen(), recv(), and send().
 {
   assert(tcp_master);
   switch(action) {
   case APP_ACTION_RESET_PORT:
     return (state == TCP_STATE_CLOSED);
   case APP_ACTION_SEND:
     return (state == TCP_STATE_ESTABLISHED ||
             state == TCP_STATE_CLOSE_WAIT);
   case APP_ACTION_RECEIVE:
     return (state == TCP_STATE_ESTABLISHED ||
             state == TCP_STATE_CLOSE_WAIT ||
             state == TCP_STATE_FIN_WAIT_1 ||
             state == TCP_STATE_FIN_WAIT_2);
   case APP_ACTION_DISCONNECT:
     return (state == TCP_STATE_ESTABLISHED ||
             state == TCP_STATE_CLOSE_WAIT ||
             state == TCP_STATE_TIME_WAIT);
   case APP_ACTION_CONNECT:
     return (state == TCP_STATE_CLOSED);
   case APP_ACTION_LISTEN:
     return (state == TCP_STATE_CLOSED);
   default:
     return false;
   }
 }
bool s3f::s3fnet::TCPSession::active_open (IPADDR dst_ip, uint16 dst_port) private
Active open.
Definition at line 178 of file tcp_session.cc.
References allocate_buffers(), s3f::s3fnet::SessionID::dst_ip, s3f::s3fnet::SessionID::dst_port, s3f::s3fnet::TCPMaster::getISS(), init_state_syn_sent(), s3f::s3fnet::TCPSeqWindow::setStart(), sndwnd, and tcp_master.
Referenced by connect().
 {
   // set the destination
   dst_ip   = destip;
   dst_port = destport;
   // allocate buffers
   allocate_buffers();
   // get/set iss
   assert(sndwnd && tcp_master);
   sndwnd->setStart(tcp_master->getISS());
   // go to TCP_STATE_SYN_SENT state
   init_state_syn_sent();
   return true;
 }
bool s3f::s3fnet::TCPSession::passive_open () private
Passive open.
Definition at line 197 of file tcp_session.cc.
References allocate_buffers(), and init_state_listen().
Referenced by listen().
 {
   // allocate buffers
   allocate_buffers();
   // go to TCP_STATE_LISTEN state
   init_state_listen();
   return true;
 }
void s3f::s3fnet::TCPSession::appl_close () private
Close the connection.
Definition at line 208 of file tcp_session.cc.
References clear_app_state(), close_issued, s3f::s3fnet::SocketSignal::CONN_CLOSED, s3f::s3fnet::TCPSendWindow::dataInBuffer(), s3f::s3fnet::TCPSeqWindow::empty(), s3f::s3fnet::TCPSeqWindow::expect(), s3f::s3fnet::TCPSeqWindow::firstUnused(), init_state_fin_wait_1(), init_state_last_ack(), s3f::s3fnet::SocketSignal::OK_TO_CLOSE, rcvwnd, send_data(), s3f::s3fnet::TCPSeqWindow::setFIN(), sndwnd, state, s3f::s3fnet::TCPMessage::TCP_FLAG_FIN, TCP_STATE_CLOSE_WAIT, TCP_STATE_ESTABLISHED, TCP_STATE_TIME_WAIT, and wake_app().
Referenced by disconnect().
 {
   assert(sndwnd);
   if(sndwnd->empty() && sndwnd->dataInBuffer() == 0)
   {
     // if there is nothing to send
     switch(state) {
     case TCP_STATE_ESTABLISHED:
       // go to state TCP_STATE_FIN_WAIT_1
       init_state_fin_wait_1();
       return;
     case TCP_STATE_CLOSE_WAIT:
       // send out FIN
       send_data(sndwnd->firstUnused(), 0, TCPMessage::TCP_FLAG_FIN,
                 rcvwnd->expect(), true, true);
       sndwnd->setFIN(true);
       // go to state TCP_STATE_LAST_ACK
       init_state_last_ack();
       return;
     case TCP_STATE_TIME_WAIT:
       wake_app(SocketSignal::CONN_CLOSED);
       return;
     }
   }
   else
   {
     clear_app_state(SocketSignal::OK_TO_CLOSE);
     close_issued = true;
   }
 }
void s3f::s3fnet::TCPSession::allocate_buffers () private
Allocate both send and receive windows.
Definition at line 241 of file tcp_session.cc.
References s3f::s3fnet::TCPMaster::getRcvWndSize(), s3f::s3fnet::TCPMaster::getSndBufSize(), s3f::s3fnet::TCPMaster::getSndWndSize(), rcvwnd, sndwnd, and tcp_master.
Referenced by active_open(), and passive_open().
 {
   // allocate send buffer
   sndwnd = new TCPSendWindow(0, tcp_master->getSndBufSize(), tcp_master->getSndWndSize());
   assert(sndwnd);
   // allocate receive buffer
   rcvwnd = new TCPRecvWindow(0, tcp_master->getRcvWndSize());
   assert(rcvwnd);
 }
void s3f::s3fnet::TCPSession::deallocate_buffers () private
Deallocate both send and receive windows.
Definition at line 252 of file tcp_session.cc.
References rcvwnd, and sndwnd.
Referenced by init_state_closed().
 {
   if(rcvwnd) { delete rcvwnd; rcvwnd = 0; }
   if(sndwnd) { delete sndwnd; sndwnd = 0; }
 }
void s3f::s3fnet::TCPSession::reset () private
Reset the session to CLOSED state and wake up application.
Definition at line 258 of file tcp_session.cc.
References s3f::s3fnet::SocketSignal::CONN_RESET, init_state_closed(), and wake_app().
Referenced by abort(), process_ACK(), receive(), and slow_timeout_handling_helper().
 {
   // go to closed state
   init_state_closed();
   // signaling CONN_RESET might prompt the upper layer to delete this
   // session. therefore, after this, we should not do other things any
   // more, because all dats structures might be invalid.
   wake_app(SocketSignal::CONN_RESET);
 }
void s3f::s3fnet::TCPSession::wake_app (int signal) private
Wake application upon a signal.
Definition at line 269 of file tcp_session.cc.
References s3f::s3fnet::ProtocolSession::control(), s3f::s3fnet::SocketSignal::DATA_AVAILABLE, s3f::s3fnet::TCPSendWindow::dataBuffered(), s3f::s3fnet::TCPRecvWindow::dataReceived(), s3f::s3fnet::SessionMaster::getSocketMaster(), s3f::s3fnet::SocketSignal::nbytes, s3f::s3fnet::SocketSignal::OK_TO_SEND, rcvwnd, sndwnd, s3f::s3fnet::SOCK_CTRL_SET_SIGNAL, socket, and tcp_master.
Referenced by appl_close(), receive(), reset(), and slowTimeoutHandling().
 {
   SocketSignal socksig(socket, signal);
   if(signal & SocketSignal::OK_TO_SEND)
     socksig.nbytes = sndwnd->dataBuffered();
   if(signal & SocketSignal::DATA_AVAILABLE)
   {
     socksig.nbytes = rcvwnd->dataReceived();
   }
   tcp_master->getSocketMaster()->control(SOCK_CTRL_SET_SIGNAL, &socksig, NULL);
 }
void s3f::s3fnet::TCPSession::clear_app_state (int signal) private
Clear application signal bit(s).
Definition at line 281 of file tcp_session.cc.
References s3f::s3fnet::ProtocolSession::control(), s3f::s3fnet::SessionMaster::getSocketMaster(), s3f::s3fnet::SOCK_CTRL_CLEAR_SIGNAL, socket, and tcp_master.
Referenced by appl_close(), appl_recv(), appl_send(), init_state_close_wait(), init_state_closing(), init_state_last_ack(), and process_FIN().
 {
   SocketSignal socksig(socket, signal);
   tcp_master->getSocketMaster()->control(SOCK_CTRL_CLEAR_SIGNAL, &socksig, NULL);
 }
int s3f::s3fnet::TCPSession::init_state_closed () private
Change to CLOSED state.
Definition at line 20 of file tcp_state.cc.
References cancel_delay_ack(), cwnd, Entity::d2t(), deallocate_buffers(), s3f::s3fnet::TCPMaster::getInitThresh(), s3f::s3fnet::TCPMaster::getMSS(), s3f::s3fnet::TCPMaster::getRcvWndSize(), s3f::s3fnet::ProtocolSession::inHost(), initial_timeout(), msl_timer_count, mss, ndupacks, nrxmits, rcvwnd_size, rtt_count, rtt_smoothed, rtt_var, rxmit_timeout, rxmit_timeout_double, rxmit_timer_count, s3f::s3fnet::TCPMaster::setIdle(), ssthresh, state, TCP_DEFAULT_RTTVAR_SHIFT, TCP_DEFAULT_SLOW_TIMEOUT, tcp_master, and TCP_STATE_CLOSED.
Referenced by process_ACK(), reset(), and TCPSession().
 {
   state = TCP_STATE_CLOSED;
   // reset all the variables
   rxmit_timer_count  = 0;
   msl_timer_count  = 0;
   rcvwnd_size = tcp_master->getRcvWndSize();
   cwnd = tcp_master->getMSS();
   ssthresh = tcp_master->getInitThresh();
   mss = tcp_master->getMSS();
   rtt_smoothed = 0;
   rtt_count = 0;
   rtt_var = (int)(rint(3 / TCP_DEFAULT_SLOW_TIMEOUT))<<TCP_DEFAULT_RTTVAR_SHIFT;
   rxmit_timeout_double = initial_timeout();
   rxmit_timeout = tcp_master->inHost()->d2t(rxmit_timeout_double, 0);
   nrxmits = 0;
   ndupacks = 0;
   // cancel delay ack
   cancel_delay_ack();
   // release any buffers that might be allocated
   deallocate_buffers();
   tcp_master->setIdle(this);
   return 0;
 }
int s3f::s3fnet::TCPSession::init_state_syn_sent () private
Change to SYN_SENT state.
Definition at line 50 of file tcp_state.cc.
References s3f::s3fnet::TCPSeqWindow::expect(), s3f::s3fnet::TCPSeqWindow::firstUnused(), nrxmits, rcvwnd, send_data(), s3f::s3fnet::TCPMaster::setConnected(), s3f::s3fnet::TCPSeqWindow::setSYN(), sndwnd, state, s3f::s3fnet::TCPMessage::TCP_FLAG_SYN, tcp_master, and TCP_STATE_SYN_SENT.
Referenced by active_open().
 {
   state = TCP_STATE_SYN_SENT;
   nrxmits = 0;
   tcp_master->setConnected(this);
   // send out SYN packet
   send_data(sndwnd->firstUnused(), 0, TCPMessage::TCP_FLAG_SYN, rcvwnd->expect(), true, true);
   sndwnd->setSYN(true);
   return 0;
 }
int s3f::s3fnet::TCPSession::init_state_syn_received () private
Change to SYN_RECEIVED state.
Definition at line 64 of file tcp_state.cc.
References s3f::s3fnet::TCPSeqWindow::expect(), s3f::s3fnet::TCPSeqWindow::firstUnused(), s3f::s3fnet::TCPSeqWindow::next(), nrxmits, rcvwnd, send_data(), s3f::s3fnet::TCPMaster::setConnected(), s3f::s3fnet::TCPSeqWindow::setSYN(), sndwnd, state, s3f::s3fnet::TCPMessage::TCP_FLAG_ACK, s3f::s3fnet::TCPMessage::TCP_FLAG_SYN, tcp_master, TCP_STATE_CLOSED, TCP_STATE_LISTEN, and TCP_STATE_SYN_RECEIVED.
Referenced by process_ACK(), and process_SYN().
 {
   assert(state != TCP_STATE_CLOSED);
   bool myListen = (state == TCP_STATE_LISTEN);
   state = TCP_STATE_SYN_RECEIVED;
   nrxmits = 0;
   tcp_master->setConnected(this);
   if(myListen)
   {
     sndwnd->setSYN(true);
     send_data(sndwnd->firstUnused(), 0, TCPMessage::TCP_FLAG_SYN | TCPMessage::TCP_FLAG_ACK,
               rcvwnd->expect(), true, true);
   }
   else
   {
     send_data(sndwnd->next(), 0, TCPMessage::TCP_FLAG_ACK, rcvwnd->expect(), false, false);
   }
   return 0;
 }
int s3f::s3fnet::TCPSession::init_state_listen () private
Change to LISTEN state.
Definition at line 88 of file tcp_state.cc.
References cancel_delay_ack(), cwnd, s3f::s3fnet::TCPMaster::getInitThresh(), s3f::s3fnet::TCPMaster::getMSS(), s3f::s3fnet::TCPMaster::getRcvWndSize(), msl_timer_count, mss, ndupacks, rcvwnd, rcvwnd_size, s3f::s3fnet::TCPSendWindow::reset(), s3f::s3fnet::TCPSeqWindow::reset(), rxmit_timer_count, s3f::s3fnet::TCPMaster::setListening(), sndwnd, ssthresh, state, tcp_master, TCP_STATE_CLOSED, and TCP_STATE_LISTEN.
Referenced by passive_open().
 {
   // set the session as listening.
   tcp_master->setListening(this);
   // if the previous state is not CLOSED,
   // we need to initialize the session state.
   if(state != TCP_STATE_CLOSED)
   {
     sndwnd->reset();
     rcvwnd ->reset();
     rcvwnd_size = tcp_master->getRcvWndSize();
     mss = tcp_master->getMSS();
     cwnd = mss;
     ssthresh = tcp_master->getInitThresh();
     cancel_delay_ack();
     ndupacks = 0;
   }
   // set the state id.
   state = TCP_STATE_LISTEN;
   // cancel any timers
   rxmit_timer_count = 0;
   msl_timer_count = 0;
   return 0;
 }
int s3f::s3fnet::TCPSession::init_state_established () private
Change to ESTABLISHED state.
Definition at line 117 of file tcp_state.cc.
References close_issued, s3f::s3fnet::TCPSeqWindow::finAtFront(), s3f::s3fnet::TCPMaster::getInitThresh(), s3f::s3fnet::SocketSignal::OK_TO_SEND, recover_seq, simultaneous_closing, sndwnd, ssthresh, s3f::s3fnet::TCPSeqWindow::start(), state, s3f::s3fnet::TCPSeqWindow::synAtFront(), tcp_master, and TCP_STATE_ESTABLISHED.
Referenced by process_ACK().
 {
   state = TCP_STATE_ESTABLISHED;
   close_issued = false;
   simultaneous_closing = false;
   ssthresh = tcp_master->getInitThresh();
   recover_seq = sndwnd->start();
   assert(!sndwnd->synAtFront());
   assert(!sndwnd->finAtFront());
   return SocketSignal::OK_TO_SEND;
 }
int s3f::s3fnet::TCPSession::init_state_close_wait () private
Change to CLOSE_WAIT state.
Definition at line 130 of file tcp_state.cc.
References clear_app_state(), s3f::s3fnet::SocketSignal::DATA_AVAILABLE, s3f::s3fnet::TCPSeqWindow::empty(), rcvwnd, rxmit_timer_count, s3f::s3fnet::SocketSignal::SOCK_EOF, state, and TCP_STATE_CLOSE_WAIT.
Referenced by process_FIN().
 {
   int signal = 0;
   state = TCP_STATE_CLOSE_WAIT;
   rxmit_timer_count = 0;
   // at this point we have received a FIN, so if nothing in receive
   // window, there won't be, so signal EOF to application
   if(rcvwnd->empty())
   {
     clear_app_state(SocketSignal::DATA_AVAILABLE);
     signal |= SocketSignal::SOCK_EOF;
   }
   else
   {
     signal |= (SocketSignal::DATA_AVAILABLE | SocketSignal::SOCK_EOF);
   }
   return signal;
 }
int s3f::s3fnet::TCPSession::init_state_last_ack () private
Change to LAST_ACK state.
Definition at line 152 of file tcp_state.cc.
References cancel_delay_ack(), clear_app_state(), delayed_ack, s3f::s3fnet::TCPSeqWindow::expect(), s3f::s3fnet::TCPMaster::isDelayedAck(), s3f::s3fnet::TCPSeqWindow::next(), s3f::s3fnet::SocketSignal::OK_TO_CLOSE, s3f::s3fnet::SocketSignal::OK_TO_SEND, rcvwnd, send_data(), sndwnd, state, s3f::s3fnet::TCPMessage::TCP_FLAG_ACK, tcp_master, and TCP_STATE_LAST_ACK.
Referenced by appl_close().
 {
   state = TCP_STATE_LAST_ACK;
   if(tcp_master->isDelayedAck() && delayed_ack)
   {
     send_data(sndwnd->next(), 0, TCPMessage::TCP_FLAG_ACK, rcvwnd->expect(), false, false);
     cancel_delay_ack();
   }
   clear_app_state(SocketSignal::OK_TO_SEND | SocketSignal::OK_TO_CLOSE);
   return 0;
 }
int s3f::s3fnet::TCPSession::init_state_fin_wait_1 () private
Change to FIN_WAIT_1 state.
Definition at line 166 of file tcp_state.cc.
References cancel_delay_ack(), s3f::s3fnet::TCPSendWindow::dataInBuffer(), delayed_ack, s3f::s3fnet::TCPMaster::disableFastTimeout(), s3f::s3fnet::TCPSeqWindow::empty(), s3f::s3fnet::TCPSeqWindow::expect(), s3f::s3fnet::TCPSeqWindow::firstUnused(), init_state_closing(), s3f::s3fnet::TCPMaster::isDelayedAck(), nrxmits, rcvwnd, send_data(), s3f::s3fnet::TCPSeqWindow::setFIN(), simultaneous_closing, sndwnd, state, s3f::s3fnet::TCPMessage::TCP_FLAG_ACK, s3f::s3fnet::TCPMessage::TCP_FLAG_FIN, tcp_master, and TCP_STATE_FIN_WAIT_1.
Referenced by appl_close(), and receive().
 {
   state = TCP_STATE_FIN_WAIT_1;
   // make sure nothing to send out
   assert(sndwnd->empty() && sndwnd->dataInBuffer() == 0);
   // Reset this since there is no data in window.
   // In fact if its not 0 there's probably a bug.
   nrxmits = 0;
   // Send a fin and possibly ack any left over delayed acks
   if(tcp_master->isDelayedAck() && delayed_ack)
   {
     send_data(sndwnd->firstUnused(), 0,
               TCPMessage::TCP_FLAG_FIN | TCPMessage::TCP_FLAG_ACK,
               rcvwnd->expect(), true, true);
     cancel_delay_ack();
     tcp_master->disableFastTimeout(this);
   }
   else
   {
     send_data(sndwnd->firstUnused(), 0, TCPMessage::TCP_FLAG_FIN,
               rcvwnd->expect(), true, true);
   }
   sndwnd->setFIN(true);
   // Now if established state received a fin while was waiting to dump
   // its buffer, then next state will be TCP_STATE_CLOSING.
   if(simultaneous_closing)  return init_state_closing();
   else return 0;
 }
int s3f::s3fnet::TCPSession::init_state_fin_wait_2 () private
Change to FIN_WAIT_2 state.
Definition at line 200 of file tcp_state.cc.
References rxmit_timer_count, state, and TCP_STATE_FIN_WAIT_2.
Referenced by process_ACK().
 {
   state = TCP_STATE_FIN_WAIT_2;
   // schedules timeout so we don't wait forever
   rxmit_timer_count = 0;
   return 0;
 }
int s3f::s3fnet::TCPSession::init_state_closing () private
Change to CLOSING state.
Definition at line 210 of file tcp_state.cc.
References clear_app_state(), s3f::s3fnet::SocketSignal::DATA_AVAILABLE, s3f::s3fnet::TCPSeqWindow::empty(), rcvwnd, s3f::s3fnet::SocketSignal::SOCK_EOF, state, and TCP_STATE_CLOSING.
Referenced by init_state_fin_wait_1(), and process_FIN().
 {
   int signal = 0;
   state = TCP_STATE_CLOSING;
   if(rcvwnd->empty())
   {
     clear_app_state(SocketSignal::DATA_AVAILABLE);
     signal |= SocketSignal::SOCK_EOF;
   }
   return signal;
 }
int s3f::s3fnet::TCPSession::init_state_time_wait () private
Change to TIME_WAIT state.
Definition at line 225 of file tcp_state.cc.
References s3f::s3fnet::TCPMaster::getMSL(), msl_timer_count, state, TCP_DEFAULT_MSL_TIMEOUT_FACTOR, tcp_master, and TCP_STATE_TIME_WAIT.
Referenced by process_ACK(), and process_FIN().
 {
   state = TCP_STATE_TIME_WAIT;
   // set up the 2*msl timeout
   msl_timer_count = TCP_DEFAULT_MSL_TIMEOUT_FACTOR * tcp_master->getMSL();
   return 0;
 }
uint32 s3f::s3fnet::TCPSession::appl_send (uint32 length, byte * msg) private
When the upper layer attempts to send out data, this function will be called.
The message will be kept in the send window until it will be sent out and got acknowledged by the receiver. In addition, the message should be allocated at the upper layer. In other words, the upper layer cannot allocate the message from the stack.
Definition at line 23 of file tcp_sender.cc.
References s3f::s3fnet::TCPSendWindow::canSend(), clear_app_state(), s3f::s3fnet::TCPSendWindow::clearDataBuffered(), s3f::s3fnet::TCPSendWindow::dataBuffered(), s3f::s3fnet::TCPSeqWindow::firstUnused(), s3f::s3fnet::SocketSignal::OK_TO_SEND, s3f::s3fnet::TCPSendWindow::requestToSend(), segment_and_send(), and sndwnd.
Referenced by send().
 {
   // clear how much data has been buffered.
   sndwnd->clearDataBuffered();
   // request to send out data
   if(msg)
   {
     byte* msgcpy = new byte[length]; assert(msgcpy);
     memcpy(msgcpy, msg, length);
     sndwnd->requestToSend(msgcpy, length);
   }
   else sndwnd->requestToSend(0, length);
   // check whether we can send out packets.
   uint32 len_to_send = sndwnd->canSend();
   if(len_to_send > 0)
   {
     // send out new data if possible
     segment_and_send(sndwnd->firstUnused(), len_to_send);
   }
   // this function will be triggered from the socket layer. If we do
   // it once, we don't need to do it again.
   clear_app_state(SocketSignal::OK_TO_SEND);
   // return number of bytes have been put into the buffer.
   uint32 ret = sndwnd->dataBuffered();
   sndwnd->clearDataBuffered();
   return ret;
 }
void s3f::s3fnet::TCPSession::send_data (uint32 seqno, uint32 datalen = 0, byte mask = 0, uint32 ackno = 0, bool need_calc_rtt = false, bool need_set_rextimeout = false) private
Physically send the data to the IP layer.
The method will call the push function of the TCP master.
Definition at line 55 of file tcp_sender.cc.
References calc_advertised_wnd(), s3f::s3fnet::ProtocolMessage::carryPayload(), DEFAULT_IP_TIMETOLIVE, s3f::s3fnet::SessionID::dst_ip, s3f::s3fnet::SessionID::dst_port, s3f::s3fnet::TCPMessage::flags, s3f::s3fnet::TCPSendWindow::generate(), get_state_name(), s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::inHost(), measured_seq, s3f::s3fnet::DmlObject::nhi, s3f::s3fnet::ProtocolSession::pushdown(), s3f::s3fnet::DataMessage::realByteCount(), rtt_count, rxmit_timer_count, s3f::s3fnet::S3FNET_PROTOCOL_TYPE_TCP, S3FNET_TCPHDR_LENGTH, s3f::s3fnet::TCPMessage::seqno, sndwnd, s3f::s3fnet::SessionID::src_ip, s3f::s3fnet::SessionID::src_port, state, TCP_DUMP, s3f::s3fnet::TCPMessage::TCP_FLAG_ACK, s3f::s3fnet::TCPMessage::TCP_FLAG_FIN, s3f::s3fnet::TCPMessage::TCP_FLAG_PSH, s3f::s3fnet::TCPMessage::TCP_FLAG_RST, s3f::s3fnet::TCPMessage::TCP_FLAG_SYN, s3f::s3fnet::TCPMessage::TCP_FLAG_URG, tcp_master, timeout_value(), s3f::s3fnet::Nhi::toString(), and s3f::s3fnet::TCPMessage::wsize.
Referenced by abort(), acknowledge(), appl_close(), fastTimeoutHandling(), init_state_fin_wait_1(), init_state_last_ack(), init_state_syn_received(), init_state_syn_sent(), process_ACK(), resend_segments(), segment_and_send(), slow_timeout_handling_helper(), and timeout_resend().
 {
   // they will be used when SACK enabled.
   int added_len = 0;
   byte* options = NULL;
   DataMessage* data = NULL;
   // generate the payload for this TCP packet.
   if(length > 0) data = sndwnd->generate(seqno, length);
   // except the SYN and FIN packets, we set ACK anyway.
   if(!(mask & TCPMessage::TCP_FLAG_SYN)/* && !(mask & TCPMessage::TCP_FLAG_FIN)*/)
     mask |= TCPMessage::TCP_FLAG_ACK;
   // create the TCP header.
   TCPMessage* tcp_msg = new TCPMessage
     (src_port, dst_port, seqno, ackno, mask, calc_advertised_wnd(),
      (S3FNET_TCPHDR_LENGTH+added_len)/sizeof(uint32), options);
   // attach the payload to the tcp message header.
   tcp_msg->carryPayload(data);
   TCP_DUMP(printf("[host=\"%s\"] %s: send_data(), flags=[%c%c%c%c%c%c] "
                   "seqno=%u, ackno=%u, wsize=%u, len=%u [state=%s]\n",
                   tcp_master->inHost()->nhi.toString(),
                   tcp_master->getNowWithThousandSeparator(),
                   (tcp_msg->flags & TCPMessage::TCP_FLAG_SYN) ? 'S' : '.',
                   (tcp_msg->flags & TCPMessage::TCP_FLAG_FIN) ? 'F' : '.',
                   (tcp_msg->flags & TCPMessage::TCP_FLAG_RST) ? 'R' : '.',
                   (tcp_msg->flags & TCPMessage::TCP_FLAG_ACK) ? 'A' : '.',
                   (tcp_msg->flags & TCPMessage::TCP_FLAG_URG) ? 'U' : '.',
                   (tcp_msg->flags & TCPMessage::TCP_FLAG_PSH) ? 'P' : '.',
                   tcp_msg->seqno, ackno, tcp_msg->wsize,
                   data?data->realByteCount():0, get_state_name(state)));
   if(need_calc_rtt && !rtt_count)
   {
     measured_seq = seqno;
     rtt_count = 1;
   }
   // Physically Send the Data
   IPPushOption ops(src_ip, dst_ip, S3FNET_PROTOCOL_TYPE_TCP, DEFAULT_IP_TIMETOLIVE);
   tcp_master->pushdown(tcp_msg, NULL, (void*)&ops, sizeof(IPPushOption));
   // if timer is not scheduled, schedule it and start RTT measurment;
   // whenever a segment is sent out, we should check whether we need
   // to start the retransmission timer
   if(need_set_rextimeout && rxmit_timer_count == 0)
   {
     rxmit_timer_count = timeout_value();
   }
 }
uint32 s3f::s3fnet::TCPSession::segment_and_send (uint32 seqno, uint32 length) private
Segment and send data.
Definition at line 110 of file tcp_sender.cc.
References cwnd, s3f::s3fnet::TCPSendWindow::dataInBuffer(), s3f::s3fnet::TCPSeqWindow::expect(), mss, mymin, rcvwnd, rcvwnd_size, S3FNET_IP_MAX_DATA_SIZE, S3FNET_TCPHDR_LENGTH, send_data(), sndwnd, s3f::s3fnet::TCPSeqWindow::unused(), s3f::s3fnet::TCPSeqWindow::use(), and s3f::s3fnet::TCPSeqWindow::used().
Referenced by appl_send(), process_dup_acks(), receive(), and sack_send_in_fast_recovery().
 {
   if(length <= 0) return 0;
   uint32 bytes_sent = 0;
   if(sndwnd->used() < mymin(rcvwnd_size, cwnd))
   {
     uint32 nbytes = mymin(rcvwnd_size, cwnd)-sndwnd->used();
     nbytes = mymin(nbytes, sndwnd->unused());
     nbytes = mymin(nbytes, length);
     nbytes = mymin(nbytes, mss);
     nbytes = mymin(nbytes, S3FNET_IP_MAX_DATA_SIZE - S3FNET_TCPHDR_LENGTH);
     while(nbytes == mss ||
           0 < nbytes && nbytes < mss &&
           nbytes == sndwnd->dataInBuffer() - sndwnd->used())
     {
       if(!sndwnd->use(nbytes)) return bytes_sent;
       send_data(seqno, nbytes, 0, rcvwnd->expect(), true, true);
       seqno += nbytes;
       length -= nbytes;
       bytes_sent += nbytes;
       nbytes = mymin(rcvwnd_size, cwnd)-sndwnd->used();
       nbytes = mymin(nbytes, sndwnd->unused());
       nbytes = mymin(nbytes, length);
       nbytes = mymin(nbytes, mss);
       nbytes = mymin(nbytes, S3FNET_IP_MAX_DATA_SIZE - S3FNET_TCPHDR_LENGTH);
     }
   }
   return bytes_sent;
 }
uint32 s3f::s3fnet::TCPSession::resend_segments (uint32 seqno, uint32 nsegments) private
Resend the segments.
Definition at line 144 of file tcp_sender.cc.
References cwnd, s3f::s3fnet::TCPSeqWindow::expect(), s3f::s3fnet::TCPSeqWindow::lengthTo(), mss, mymin, rcvwnd, recover_seq, rxmit_seq, rxmit_timer_count, send_data(), and sndwnd.
Referenced by process_dup_acks(), process_new_acks(), sack_resend_segments(), and timeout_resend().
 {
   // first cancel retransmission timeout
   rxmit_timer_count = 0;
   // send up to nsegments
   uint32 bytes_sent = 0;
   nsegments = mymin(nsegments, (cwnd - sndwnd->lengthTo(seqno))/mss);
   while(nsegments > 0)
   {
     // figure out minimum sized segment; minimum between mss and the
     // amount of data to send in window
     uint32 nbytes = mymin(mss, recover_seq - seqno);
     if(nbytes > 0)
     {
       send_data(seqno, nbytes, 0, rcvwnd->expect(), false, true);
       seqno += nbytes;
       bytes_sent += nbytes;
       nsegments--;
     } else break;
   }
   // update rxmit_seq if nesessary
   rxmit_seq = seqno;
   // return nubmer for bytes sent
   return bytes_sent;
 }
void s3f::s3fnet::TCPSession::acknowledge (bool nodelay) private
Generate acknowledgements; no delay is imposed if the nodelay parameter is true.
Definition at line 173 of file tcp_sender.cc.
References cancel_delay_ack(), delayed_ack, s3f::s3fnet::TCPSeqWindow::firstUnused(), s3f::s3fnet::TCPRecvWindow::getExpectedSeqno(), s3f::s3fnet::TCPMaster::isDelayedAck(), rcvwnd, send_data(), send_delay_ack(), sndwnd, s3f::s3fnet::TCPMessage::TCP_FLAG_ACK, and tcp_master.
Referenced by receive().
 {
   if(tcp_master->isDelayedAck() && !nodelay && !delayed_ack)
   {
     // put ack on delayed ack queue
     send_delay_ack();
   }
   else
   {
     // send the ack
     send_data(sndwnd->firstUnused(), 0, TCPMessage::TCP_FLAG_ACK,
               rcvwnd->getExpectedSeqno(), false, false);
     // if delayed ack, we should cancel it
     if(tcp_master->isDelayedAck()) cancel_delay_ack();
   }
 }
void s3f::s3fnet::TCPSession::timeout_resend () private
This function is called when retransmission timer expires.
Definition at line 191 of file tcp_sender.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::TCPSeqWindow::expect(), s3f::s3fnet::TCPSeqWindow::firstUnused(), s3f::s3fnet::TCPMaster::getVersion(), rcvwnd, resend_segments(), sack_resend_segments(), send_data(), sndwnd, s3f::s3fnet::TCPSeqWindow::start(), state, s3f::s3fnet::TCPMessage::TCP_FLAG_ACK, s3f::s3fnet::TCPMessage::TCP_FLAG_FIN, s3f::s3fnet::TCPMessage::TCP_FLAG_SYN, tcp_master, TCP_STATE_CLOSE_WAIT, TCP_STATE_CLOSING, TCP_STATE_ESTABLISHED, TCP_STATE_FIN_WAIT_1, TCP_STATE_LAST_ACK, TCP_STATE_SYN_RECEIVED, TCP_STATE_SYN_SENT, s3f::s3fnet::TCPMaster::TCP_VERSION_NEW_RENO, s3f::s3fnet::TCPMaster::TCP_VERSION_RENO, s3f::s3fnet::TCPMaster::TCP_VERSION_SACK, and s3f::s3fnet::TCPMaster::TCP_VERSION_TAHOE.
Referenced by slow_timeout_handling_helper().
 {
   switch(state) {
   case TCP_STATE_SYN_SENT:
     // retransmit the syn segment
     send_data(sndwnd->firstUnused(), 0, TCPMessage::TCP_FLAG_SYN,
               rcvwnd->expect(), false, true);
     break;
   case TCP_STATE_SYN_RECEIVED:
     // retransmit the syn and ack segment
     send_data(sndwnd->firstUnused(), 0, TCPMessage::TCP_FLAG_SYN | TCPMessage::TCP_FLAG_ACK,
               rcvwnd->expect(), false, true);
     break;
   case TCP_STATE_ESTABLISHED:
   case TCP_STATE_CLOSE_WAIT:
     // retransmit data segment
     switch(tcp_master->getVersion()) {
     case TCPMaster::TCP_VERSION_TAHOE:
       resend_segments(sndwnd->start(), INT_MAX);
       break;
     case TCPMaster::TCP_VERSION_RENO:
     case TCPMaster::TCP_VERSION_NEW_RENO:
       resend_segments(sndwnd->start(), 1);
       break;
     case TCPMaster::TCP_VERSION_SACK:
       sack_resend_segments(true);
       break;
     default:
       assert(0);
     }
     break;
   case TCP_STATE_CLOSING:
   case TCP_STATE_FIN_WAIT_1:
   case TCP_STATE_LAST_ACK:
     // resend the FIN segment
     send_data(sndwnd->firstUnused/*next*/(), 0, TCPMessage::TCP_FLAG_FIN,
               rcvwnd->expect(), false, true);
     break;
   default:
     // TCP_STATE_LISTEN, TCP_STATE_CLOSED, TCP_STATE_TIME_WAIT,
     // or TCP_STATE_FIN_WAIT_2
     error_quit("PANIC: TCPSession::timeout_resend(), unexpected state: %d.\n", state);
   }
 }
uint32 s3f::s3fnet::TCPSession::calc_advertised_wnd () private
Calculate the advertised window size.
Definition at line 240 of file tcp_sender.cc.
References s3f::s3fnet::TCPRecvWindow::bufferSize(), s3f::s3fnet::TCPSeqWindow::expand(), s3f::s3fnet::TCPRecvWindow::freeInBuffer(), mss, mymax, rcvwnd, s3f::s3fnet::TCPSeqWindow::size(), state, and TCP_STATE_ESTABLISHED.
Referenced by send_data().
 {
   // first check the free space in the buffer
   uint32 window = rcvwnd->freeInBuffer();
   if(state < TCP_STATE_ESTABLISHED) return window;
   // if silly-window-syndrome-avoidance algorithm is used, run it
   if(window * 4 < rcvwnd->bufferSize() || window < mss)
     window = 0;
   // never shrink an already advertised window
   window = mymax(window, rcvwnd->size());
   // update the current receive window
   int incremental = window - rcvwnd->size();
   if(incremental > 0) rcvwnd->expand(incremental);
   return window;
 }
void s3f::s3fnet::TCPSession::send_delay_ack () private
Set the session to send delayed ACK when next time the fast timer fires.
Definition at line 260 of file tcp_sender.cc.
References delayed_ack, s3f::s3fnet::TCPMaster::enableFastTimeout(), and tcp_master.
Referenced by acknowledge().
 {
   delayed_ack = true;
   tcp_master->enableFastTimeout(this);
 }
void s3f::s3fnet::TCPSession::cancel_delay_ack () private
Set the session to cancel sending delayed ACK when next timer the fast timer fires.
Definition at line 266 of file tcp_sender.cc.
References delayed_ack, s3f::s3fnet::TCPMaster::disableFastTimeout(), and tcp_master.
Referenced by acknowledge(), fastTimeoutHandling(), init_state_closed(), init_state_fin_wait_1(), init_state_last_ack(), and init_state_listen().
 {
   tcp_master->disableFastTimeout(this);
   delayed_ack = false;
 }
uint32 s3f::s3fnet::TCPSession::appl_recv (uint32 length, byte * msg) private
When the upper layer wants to receive data (length bytes) from TCP, this function will be called.
The msg parameter points the message buffer, which can be NULL if only fake data is needed.
Definition at line 22 of file tcp_receiver.cc.
References clear_app_state(), s3f::s3fnet::SocketSignal::DATA_AVAILABLE, s3f::s3fnet::TCPRecvWindow::generate(), rcvwnd, and s3f::s3fnet::TCPRecvWindow::setRecvParameters().
Referenced by recv().
 {
   assert(length > 0);
   uint32 got = rcvwnd->generate(length, msg);
   if(got == 0)
   {
     // if no data available, the socket will be suspended waiting for
     // the DATA_AVAILABLE signal, we set the receive parameters so
     // that the socket will be notified when message arrives
     rcvwnd->setRecvParameters(length, msg);
     // this function will be triggered from the socket layer. If we do
     // it once, we don't need to do it again.
     clear_app_state(SocketSignal::DATA_AVAILABLE);
   }
   return got;
 }
void s3f::s3fnet::TCPSession::process_SYN (TCPMessage * tcphdr, int & signal) private
Process SYN packets.
Definition at line 146 of file tcp_receiver.cc.
References s3f::s3fnet::SocketSignal::FIRST_CONNECTION, s3f::s3fnet::TCPMaster::getISS(), init_state_syn_received(), nrxmits, rcvwnd, rcvwnd_size, s3f::s3fnet::TCPMessage::seqno, s3f::s3fnet::TCPSeqWindow::setStart(), s3f::s3fnet::TCPSeqWindow::setSYN(), sndwnd, state, tcp_master, TCP_STATE_LISTEN, TCP_STATE_SYN_RECEIVED, TCP_STATE_SYN_SENT, and s3f::s3fnet::TCPMessage::wsize.
Referenced by receive().
 {
   switch(state) {
   case TCP_STATE_SYN_SENT:
     rcvwnd->setStart(tcphdr->seqno);
     rcvwnd->setSYN(true);
     nrxmits = 0;
     rcvwnd_size = tcphdr->wsize;
     return;
   case TCP_STATE_SYN_RECEIVED:
     // we are not supposed to receive it
     return;
   case TCP_STATE_LISTEN:
     // Initialize the receive window
     rcvwnd->setStart(tcphdr->seqno);
     rcvwnd->setSYN(true);
     // Get initial sequence no and initialize Send Window
     sndwnd->setStart(tcp_master->getISS());
     rcvwnd_size = tcphdr->wsize;
     // We may want to signal the above application about that we have
     // received the first SYN segment. For further consideration.
     signal |= SocketSignal::FIRST_CONNECTION;
     signal |= init_state_syn_received();
     break;
   default:
     // for all other states, just ignore SYN packet because it may be
     // an retransmitted SYN packet sent by the other side.
     break;
   }
 }
void s3f::s3fnet::TCPSession::process_FIN (int & signal) private
Process FIN packets.
Definition at line 183 of file tcp_receiver.cc.
References clear_app_state(), close_issued, s3f::s3fnet::SocketSignal::DATA_AVAILABLE, s3f::s3fnet::TCPSeqWindow::empty(), init_state_close_wait(), init_state_closing(), init_state_time_wait(), rcvwnd, s3f::s3fnet::TCPSeqWindow::setFIN(), simultaneous_closing, s3f::s3fnet::SocketSignal::SOCK_EOF, state, TCP_STATE_CLOSE_WAIT, TCP_STATE_ESTABLISHED, TCP_STATE_FIN_WAIT_1, and TCP_STATE_FIN_WAIT_2.
Referenced by receive().
 {
   switch(state) {
   case TCP_STATE_ESTABLISHED:
     rcvwnd->setFIN(true);
     // the other side wants to end the connection, we want to finish
     // it too; so it's simultaneous closing.
     if(close_issued) simultaneous_closing = true;
     signal |= init_state_close_wait();
     break;
   case TCP_STATE_CLOSE_WAIT:
     // at this point we have received a FIN, so if nothing in receive
     // window, there won't be more, so signal EOF to application
     if(rcvwnd->empty())
     {
       clear_app_state(SocketSignal::DATA_AVAILABLE);
       signal |= SocketSignal::SOCK_EOF;
     }
     else signal |= SocketSignal::DATA_AVAILABLE | SocketSignal::SOCK_EOF;
     break;
   case TCP_STATE_FIN_WAIT_1:
     rcvwnd->setFIN(true); // FIN byte
     // this state may be changed once ACK is handled
     signal |= init_state_closing();
     break;
   case TCP_STATE_FIN_WAIT_2:
     rcvwnd->setFIN(true); // FIN byte
     signal |= init_state_time_wait();
     break;
   default:
     // other states, do nothing right now
     break;
   }
 }
bool s3f::s3fnet::TCPSession::process_ACK (TCPMessage * tcphdr, int & signal) private
Process ACK packets.
Definition at line 222 of file tcp_receiver.cc.
References s3f::s3fnet::TCPMessage::ackno, s3f::s3fnet::SocketSignal::CONN_CLOSED, s3f::s3fnet::error_quit(), s3f::s3fnet::TCPSeqWindow::expect(), s3f::s3fnet::TCPMessage::flags, get_state_name(), init_state_closed(), init_state_established(), init_state_fin_wait_2(), init_state_syn_received(), init_state_time_wait(), msl_timer_count, s3f::s3fnet::TCPSeqWindow::next(), nrxmits, process_acks(), rcvwnd, reset(), rxmit_timer_count, send_data(), s3f::s3fnet::SocketSignal::SESSION_RELEASED, s3f::s3fnet::TCPSeqWindow::setFIN(), s3f::s3fnet::TCPSeqWindow::setSYN(), sndwnd, state, s3f::s3fnet::TCPMessage::TCP_FLAG_FIN, s3f::s3fnet::TCPMessage::TCP_FLAG_RST, s3f::s3fnet::TCPMessage::TCP_FLAG_SYN, TCP_STATE_CLOSE_WAIT, TCP_STATE_CLOSED, TCP_STATE_CLOSING, TCP_STATE_ESTABLISHED, TCP_STATE_FIN_WAIT_1, TCP_STATE_FIN_WAIT_2, TCP_STATE_LAST_ACK, TCP_STATE_LISTEN, TCP_STATE_SYN_RECEIVED, TCP_STATE_SYN_SENT, and TCP_STATE_TIME_WAIT.
Referenced by receive().
 {
   switch(state) {
   case TCP_STATE_CLOSED:
     error_quit("PANIC: TCPSession::process_ACK(), state=%s.\n", get_state_name(state));
     return false;
   case TCP_STATE_LISTEN:
     // shouldn't be receiving ACK's yet
     send_data(tcphdr->ackno, 0, TCPMessage::TCP_FLAG_RST, rcvwnd->expect(), false, false);
     return false;
   case TCP_STATE_SYN_SENT:
     // illegal acknowledgment
     if(tcphdr->ackno != sndwnd->next())
     {
       send_data(tcphdr->ackno, 0, TCPMessage::TCP_FLAG_RST, rcvwnd->expect(), false, false);
       reset();
       return false;
     }
     process_acks(tcphdr);
     if(tcphdr->flags & TCPMessage::TCP_FLAG_SYN)
     {
       sndwnd->setSYN(false);
       signal |= init_state_established();
     }
     else signal |= init_state_syn_received();
     return false;
   case TCP_STATE_SYN_RECEIVED:
     if(tcphdr->ackno != sndwnd->next())
     {
       send_data(tcphdr->ackno, 0, TCPMessage::TCP_FLAG_RST, rcvwnd->expect(), false, false);
       reset();
       return false;
     }
     if(process_acks(tcphdr))  return true;
     sndwnd->setSYN(false); // SYN byte
     signal |= init_state_established();
     return false;
   case TCP_STATE_ESTABLISHED:
   case TCP_STATE_CLOSE_WAIT:
     return process_acks(tcphdr);
   case TCP_STATE_LAST_ACK:
     if(tcphdr->ackno == sndwnd->next())
     {
       rxmit_timer_count = 0;
       sndwnd->setFIN(false);  // ACK our FIN
       signal |= init_state_closed();
       // when connection is closed, we release the session
       signal |= SocketSignal::CONN_CLOSED | SocketSignal::SESSION_RELEASED;
       return false;
     }
     else return true;   // illegal packet
   case TCP_STATE_FIN_WAIT_1:
     if(tcphdr->ackno == sndwnd->next())
     {
       sndwnd->setFIN(false); // our FIN was acked
       nrxmits = 0;
       if(tcphdr->flags & TCPMessage::TCP_FLAG_FIN)
       {
         rcvwnd->setFIN(true); // FIN byte
         signal |= init_state_time_wait();
       }
       else signal |= init_state_fin_wait_2();
     }
     return false;
   case TCP_STATE_FIN_WAIT_2:
     return false;
   case TCP_STATE_CLOSING:
     if(tcphdr->ackno == sndwnd->next())
     {
       rxmit_timer_count = 0;
       sndwnd->setFIN(false);  // ACK our FIN
       signal |= init_state_time_wait();
     }
     return false;
   case TCP_STATE_TIME_WAIT:
     if(tcphdr->ackno == sndwnd->next())
     {
       msl_timer_count = 0;
     }
     return false;
   }
   return false;
 }
bool s3f::s3fnet::TCPSession::process_acks (TCPMessage * tcphdr) private
Process the ACKs that correspond to received TCP message, and update session states like RTT and retransmission timer.
Definition at line 328 of file tcp_receiver.cc.
References s3f::s3fnet::TCPMessage::ackno, ndupacks, s3f::s3fnet::TCPSeqWindow::next(), process_dup_acks(), process_new_acks(), rcvwnd_size, sndwnd, s3f::s3fnet::TCPSeqWindow::start(), update_remote_window_size(), s3f::s3fnet::TCPSeqWindow::used(), and s3f::s3fnet::TCPMessage::wsize.
Referenced by process_ACK().
 {
   uint32 snd_una = sndwnd->start();
   // check if ACK is not within our window. if so, send an immediate
   // ACK and drop the segment
   if(tcphdr->ackno < snd_una || tcphdr->ackno > sndwnd->next())
     return true;
   // check to see if we have a duplicate ACK
   if(tcphdr->ackno == snd_una &&
      tcphdr->wsize == rcvwnd_size &&
      sndwnd->used() > 0)
   {
     process_dup_acks();
     return false;
   }
   // update the remote window size
   update_remote_window_size(tcphdr->wsize);
   // we really got new data acked
   uint32 acked;
   if((acked = tcphdr->ackno - snd_una) > 0)
     process_new_acks(tcphdr, acked);
   // reset duplicate ACK count
   ndupacks = 0;
   return false;
 }
bool s3f::s3fnet::TCPSession::process_new_data (DataMessage * payload, uint32 seqno) private
Process data arrival.
Definition at line 316 of file tcp_receiver.cc.
References s3f::s3fnet::TCPRecvWindow::addToBuffer(), rcvwnd, and s3f::s3fnet::TCPSeqWindow::within().
Referenced by receive().
 {
   // check whether the seqno falls in the window
   if(rcvwnd->within(seqno))
   {
     // URG and PSH are unsupported (RFC 793).
     rcvwnd->addToBuffer(payload, seqno);
     return false;
   }
   else return true;  // illegal data
 }
void s3f::s3fnet::TCPSession::process_dup_acks () private
Process duplicate ACKs received.
Definition at line 517 of file tcp_receiver.cc.
References calc_threshold(), cwnd, s3f::s3fnet::TCPSendWindow::dataInBuffer(), s3f::s3fnet::TCPSeqWindow::firstUnused(), s3f::s3fnet::TCPMaster::getMaxConWnd(), s3f::s3fnet::TCPMaster::getVersion(), mss, mymin, ndupacks, recover_seq, resend_segments(), rtt_count, sack_pipe, sack_resend_segments(), sack_send_in_fast_recovery(), segment_and_send(), sndwnd, ssthresh, s3f::s3fnet::TCPSeqWindow::start(), TCP_DEFAULT_MAX_DUPACKS, tcp_master, s3f::s3fnet::TCPMaster::TCP_VERSION_NEW_RENO, s3f::s3fnet::TCPMaster::TCP_VERSION_RENO, s3f::s3fnet::TCPMaster::TCP_VERSION_SACK, s3f::s3fnet::TCPMaster::TCP_VERSION_TAHOE, s3f::s3fnet::TCPSeqWindow::unused(), and s3f::s3fnet::TCPSeqWindow::used().
Referenced by process_acks().
 {
   // another duplicate ack
   ndupacks++;
   if(ndupacks == TCP_DEFAULT_MAX_DUPACKS)
   {
     calc_threshold();
     // we remember the largest seqno already sent out
     recover_seq = sndwnd->firstUnused();
     // we think this packet is lost, so we disable measuring rtt
     rtt_count = 0;
     switch(tcp_master->getVersion()){
     case TCPMaster::TCP_VERSION_TAHOE:
       // in tahoe, fast recovery is off; tahoe fast rxmit resets
       // congestion window to mss and resend 1 segment
       cwnd = mss;
       resend_segments(sndwnd->start(), 1);
       break;
     case TCPMaster::TCP_VERSION_RENO:
     case TCPMaster::TCP_VERSION_NEW_RENO:
       // in Reno, fast recovery is on
       cwnd = mymin(ssthresh + 3*mss, tcp_master->getMaxConWnd());
       resend_segments(sndwnd->start(), 1);
       // more data to send out
       if(sndwnd->unused() >= mss)
       {
         segment_and_send(sndwnd->firstUnused(),
                         mymin(sndwnd->unused(), sndwnd->dataInBuffer() - sndwnd->used()) );
       }
       break;
     case TCPMaster::TCP_VERSION_SACK:
       sack_pipe = cwnd - TCP_DEFAULT_MAX_DUPACKS;
       cwnd = mymin(ssthresh /* + 3*mss */, tcp_master->getMaxConWnd());
       // we resend a packet
       assert(sack_resend_segments(true));
       break;
     default:
       assert(0);
     }
   }
   else if(ndupacks > TCP_DEFAULT_MAX_DUPACKS)
   {
     // now we have more than TCP_DEFAULT_MAX_DUPACKS duplicate acks so if Reno
     // then increase the Congestion Window by mss and resend another
     // segment Do fast recovery
     switch(tcp_master->getVersion()){
     case TCPMaster::TCP_VERSION_TAHOE:
       // do nothing
       break;
     case TCPMaster::TCP_VERSION_RENO:
     case TCPMaster::TCP_VERSION_NEW_RENO:
       cwnd = mymin(cwnd + mss, tcp_master->getMaxConWnd());
       if(sndwnd->unused() >= mss)
       {
         segment_and_send(sndwnd->firstUnused(),
                         mymin(sndwnd->unused(), sndwnd->dataInBuffer() - sndwnd->used()) );
       }
       break;
     case TCPMaster::TCP_VERSION_SACK:
       sack_pipe -= mss;
       sack_send_in_fast_recovery();
       break;
     default:
       assert(0);
     }
   }
 }
void s3f::s3fnet::TCPSession::process_new_acks (TCPMessage * tcphdr, uint32 acked) private
Process ACKs that respond to new data.
Definition at line 359 of file tcp_receiver.cc.
References s3f::s3fnet::TCPMessage::ackno, check_cwnd(), s3f::s3fnet::TCPBlockList::clear_all_blocks(), cwnd, fast_recovery, s3f::s3fnet::TCPMaster::getMaxConWnd(), s3f::s3fnet::TCPMaster::getVersion(), measured_seq, mss, mymin, ndupacks, recover_seq, s3f::s3fnet::TCPSendWindow::release(), resend_segments(), rtt_count, rtt_measured, rxmit_seq, rxmit_timer_count, sack_pipe, sack_send_in_fast_recovery(), snd_scoreboard, sndwnd, ssthresh, state, TCP_DEFAULT_MAX_DUPACKS, tcp_master, TCP_STATE_CLOSE_WAIT, TCP_STATE_ESTABLISHED, s3f::s3fnet::TCPMaster::TCP_VERSION_NEW_RENO, s3f::s3fnet::TCPMaster::TCP_VERSION_RENO, s3f::s3fnet::TCPMaster::TCP_VERSION_SACK, s3f::s3fnet::TCPMaster::TCP_VERSION_TAHOE, timeout_loss, timeout_value(), update_timeout(), and s3f::s3fnet::TCPSeqWindow::used().
Referenced by process_acks().
 {
   if(state == TCP_STATE_ESTABLISHED ||
      state == TCP_STATE_CLOSE_WAIT)
   {
     // shift the window
     sndwnd->release(acked);
   }
   // As implemented in Java SSFNet, when new data got acked, first
   // update retransmission timeout, and then update rtt. Is it right?
   // we don't need the retransmission timer any more
   rxmit_timer_count = 0;
   // if there's still packet on the fly, we should reset the timeout
   if(sndwnd->used() > 0)
   {
     // reschedule timer
     rxmit_timer_count = timeout_value();
   }
   // update timers. if data acked was RXMIT data then do not update
   // (Karn's algorithm) Smoothed RTT and Dev calculations
   if(rtt_count && (tcphdr->ackno > measured_seq))
   {
     // Jakobson's Algorithm for timers (1988)
     rtt_measured = rtt_count - 1;
     update_timeout();
   }
   if(state != TCP_STATE_ESTABLISHED &&
      state != TCP_STATE_CLOSE_WAIT)
     return;
   // indicate whether it's the first partial ack
   bool is_FirstNonDupACK;
   if(ndupacks >= TCP_DEFAULT_MAX_DUPACKS)
   {
     // when the first non-duplicate ACK has arrived, enter fast
     // recovery
     is_FirstNonDupACK = true;
     switch(tcp_master->getVersion()) {
     case TCPMaster::TCP_VERSION_TAHOE:
       // do nothing, just go to slow start!
       break;
     case TCPMaster::TCP_VERSION_RENO:
       // reset congestion window and go to congestion avoidance
       cwnd = mymin(ssthresh, tcp_master->getMaxConWnd());
       // we check whether there are new data to send out we don't need
       // to resend any segments here
       break;
     case TCPMaster::TCP_VERSION_NEW_RENO:
       // still stay in fast recovery, until acks of new data received
       // we use fast_recovery to indicate it's still in fast
       // recovery
       fast_recovery = true;
       break;
     case TCPMaster::TCP_VERSION_SACK:
       fast_recovery = true;
       break;
     default:
       assert(0);
     }
   }
   else is_FirstNonDupACK = false;
   // if no new data has been confirmed, we have to resend segments
   if(tcphdr->ackno < recover_seq)
   {
     switch(tcp_master->getVersion()) {
     case TCPMaster::TCP_VERSION_TAHOE:
       // do nothing, just go to slow start!
       // The C++ TCP implementation is modified here to make it
       // compatible with the Java version (and the NS-2 version as
       // well). The congestion window is bumped by one each time a
       // non-duplicate packet is received (we're in the slow start
       // mood now). This happens no matter whether the ack is the
       // first non-duplicate ack or not! -jason.
       if(true || !is_FirstNonDupACK)
       {
         check_cwnd();
       }
       // we resend the segments - GO-BACK-N
       if(tcphdr->ackno > rxmit_seq)
       {
         resend_segments(tcphdr->ackno, UINT_MAX);
       }
       else
       {
         resend_segments(rxmit_seq, UINT_MAX);
       }
       break;
     case TCPMaster::TCP_VERSION_RENO:
       // go to congestion avoidance phase
       check_cwnd();
       if(timeout_loss)
       {
         if(tcphdr->ackno > rxmit_seq)
         {
           resend_segments(tcphdr->ackno, UINT_MAX);
         }
         else
         {
           resend_segments(rxmit_seq, UINT_MAX);
         }
       }
       break;
     case TCPMaster::TCP_VERSION_NEW_RENO:
       // it's still a partial ack, we resend one segment indicated by
       // the ack number
       resend_segments(tcphdr->ackno, 1);
       // update congestion window: deflate the congestion window by
       // the amount of data acknowledged and then add one back and
       // send one new segment if permitted by the new value of cwnd
       cwnd -= (acked - mss);
       break;
     case TCPMaster::TCP_VERSION_SACK:
       sack_pipe -= mss;
       sack_send_in_fast_recovery();
       break;
     default:
       assert(0);
     }
   }
   // we have to update congestion window
   else
   {
     // no timeout loss
     timeout_loss = false;
     if(fast_recovery &&
        (tcp_master->getVersion() == TCPMaster::TCP_VERSION_NEW_RENO ||
         tcp_master->getVersion() == TCPMaster::TCP_VERSION_SACK))
     {
       cwnd = mymin(ssthresh, mss + sndwnd->used());
       fast_recovery = false;
       // clear all blocks
       if(tcp_master->getVersion() == TCPMaster::TCP_VERSION_SACK)
           snd_scoreboard->clear_all_blocks();
     }
     else check_cwnd();
   }
 }
void s3f::s3fnet::TCPSession::check_cwnd () private
Check congestion window size.
Definition at line 595 of file tcp_receiver.cc.
References cwnd, s3f::s3fnet::TCPMaster::getMaxConWnd(), mss, mymin, ssthresh, TCP_DUMP, and tcp_master.
Referenced by process_new_acks().
 {
 #ifdef TCP_DEBUG
   uint32 old_cwnd = cwnd;
 #endif
   if(cwnd < ssthresh)
   { // slow start
     cwnd = mymin(cwnd + mss, tcp_master->getMaxConWnd());
     TCP_DUMP(printf("check_cwnd(), slow start: CW %u => %u.\n", old_cwnd, cwnd));
   }
   else
   { // congestion avoidance
     cwnd = mymin(cwnd + (mss*mss)/cwnd, tcp_master->getMaxConWnd());
     TCP_DUMP(printf("check_cwnd(), congestion avoidance: CW %u => %u.\n", old_cwnd, cwnd));
   }
 }
void s3f::s3fnet::TCPSession::calc_threshold () private
Calculate the threshold.
Definition at line 612 of file tcp_receiver.cc.
References cwnd, mss, mymax, mymin, rcvwnd_size, ssthresh, and TCP_DEFAULT_THRESH_FACTOR.
Referenced by process_dup_acks(), and slow_timeout_handling_helper().
 {
   ssthresh = mymax(mymin(cwnd, rcvwnd_size)/TCP_DEFAULT_THRESH_FACTOR, 2 * mss);
 }
void s3f::s3fnet::TCPSession::update_remote_window_size (uint32 window_size) private
update the remote receive window size.
Definition at line 617 of file tcp_receiver.cc.
References s3f::s3fnet::TCPMaster::getRcvWndSize(), rcvwnd_size, and tcp_master.
Referenced by process_acks().
 {
   // update recv window size
   rcvwnd_size = tcp_master->getRcvWndSize();
 }
uint32 s3f::s3fnet::TCPSession::slow_timeout_handling_helper (const uint32 timerid) private
Slow timeout handler with a given timer id.
Definition at line 68 of file tcp_timer.cc.
References backoff_timeout(), calc_threshold(), s3f::s3fnet::TCPBlockList::clear_all_blocks(), s3f::s3fnet::SocketSignal::CONN_CLOSED, cwnd, s3f::s3fnet::TCPSeqWindow::expect(), s3f::s3fnet::TCPSeqWindow::firstUnused(), s3f::s3fnet::TCPMaster::getMaxRxmit(), s3f::s3fnet::TCPMaster::getVersion(), mss, ndupacks, nrxmits, rcvwnd, recover_seq, reset(), RETX_TIMER, rtt_count, rtt_smoothed, rtt_var, rxmit_timer_count, send_data(), s3f::s3fnet::SocketSignal::SESSION_RELEASED, snd_scoreboard, sndwnd, state, TCP_DEFAULT_RTT_SHIFT, s3f::s3fnet::TCPMessage::TCP_FLAG_RST, tcp_master, TCP_STATE_TIME_WAIT, s3f::s3fnet::TCPMaster::TCP_VERSION_SACK, timeout_loss, timeout_resend(), and TWO_MSL_TIMER.
Referenced by slowTimeoutHandling().
 {
   uint32 signal = 0;
   if(timerid == RETX_TIMER)
   {
     // we should set clear off all "sacked" flags
     if(TCPMaster::TCP_VERSION_SACK == tcp_master->getVersion())
       snd_scoreboard->clear_all_blocks();
     // no longer measure RTT
     rtt_count = 0;
     nrxmits++;  // this also takes care of Karn's algorithm
     recover_seq  = sndwnd->firstUnused();
     timeout_loss = true;
     backoff_timeout();
     if(nrxmits <= tcp_master->getMaxRxmit())
     {
       // Jacobson's Slow Start
       //
       // Cut the threshold to 1/2 of mymin(CW, RWndSize) and reset
       // Congestion window
       calc_threshold();
       cwnd = mss;
       ndupacks = 0;
       // update rtt var (according to Java SSFNet)
       if(nrxmits > tcp_master->getMaxRxmit() / 4)
       {
         rtt_var += (rtt_smoothed >> TCP_DEFAULT_RTT_SHIFT);
         rtt_smoothed = 0;
       }
       // cancel retransmission timer
       rxmit_timer_count = 0;
       // we should resend the packet assumed to get lost
       timeout_resend();
     }
     else
     {
       // we have tried one too many times...connection must be dead
       send_data(sndwnd->firstUnused(), 0, TCPMessage::TCP_FLAG_RST, rcvwnd->expect(), false, false);
       reset();
     }
   }
   else if(timerid == TWO_MSL_TIMER)
   {
     assert(state == TCP_STATE_TIME_WAIT);
     signal |= (SocketSignal::CONN_CLOSED |
                SocketSignal::SESSION_RELEASED);
   }
   else assert(false);
   return signal;
 }
void s3f::s3fnet::TCPSession::update_timeout () private
Update the current smoothed RTT timeout with the new rtt measurment.
Definition at line 134 of file tcp_timer.cc.
References Entity::d2t(), s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::TCPMaster::getSlowTimeoutDouble(), s3f::s3fnet::ProtocolSession::inHost(), mymax, mymin, s3f::s3fnet::DmlObject::nhi, nrxmits, rtt_count, rtt_measured, rtt_smoothed, rtt_var, rxmit_timeout, rxmit_timeout_double, TCP_DEFAULT_RTT_SHIFT, TCP_DEFAULT_RTTVAR_SHIFT, TCP_DEFAULT_RXMIT_MAX_TIMEOUT, TCP_DEFAULT_RXMIT_MIN_TIMEOUT, TCP_DUMP, tcp_master, timeout_value(), and s3f::s3fnet::Nhi::toString().
Referenced by process_new_acks().
 {
   if(rtt_smoothed)
   {
     int delta = rtt_measured - (rtt_smoothed >> TCP_DEFAULT_RTT_SHIFT);
     if((rtt_smoothed += delta) <= 0)  rtt_smoothed = 1;
     if(delta < 0)  delta = -delta;
     delta -= (rtt_var >> TCP_DEFAULT_RTTVAR_SHIFT);
     if((rtt_var += delta) <= 0)  rtt_var = 1;
   }
   else
   {
     rtt_smoothed = (rtt_measured + 1) << TCP_DEFAULT_RTT_SHIFT;
     rtt_var = (rtt_measured + 1) << (TCP_DEFAULT_RTTVAR_SHIFT - 1);
   }
   rxmit_timeout_double = mymax(mymin(tcp_master->getSlowTimeoutDouble() * ((rtt_smoothed >> TCP_DEFAULT_RTT_SHIFT) + rtt_var),
                               TCP_DEFAULT_RXMIT_MAX_TIMEOUT), TCP_DEFAULT_RXMIT_MIN_TIMEOUT);
   rxmit_timeout = tcp_master->inHost()->d2t(rxmit_timeout_double, 0);
   rtt_count = 0;
   nrxmits = 0;
   TCP_DUMP(printf("[host=\"%s\"] %s: update_timeout(), rtt_measured=%d, rtt_smoothed=%d, RTO=%ld.\n",
                   tcp_master->inHost()->nhi.toString(),
                   tcp_master->getNowWithThousandSeparator(), rtt_measured, rtt_smoothed,
                   timeout_value()));
 }
void s3f::s3fnet::TCPSession::backoff_timeout () private
Backoff the current timeout.
Definition at line 163 of file tcp_timer.cc.
References Entity::d2t(), s3f::s3fnet::TCPMaster::getSlowTimeoutDouble(), s3f::s3fnet::ProtocolSession::inHost(), mymax, mymin, nrxmits, rtt_smoothed, rtt_var, rxmit_timeout, rxmit_timeout_double, s3f::s3fnet::tcp_backoff, TCP_DEFAULT_BACKOFF_LIMIT, TCP_DEFAULT_RTT_SHIFT, TCP_DEFAULT_RXMIT_MAX_TIMEOUT, TCP_DEFAULT_RXMIT_MIN_TIMEOUT, and tcp_master.
Referenced by slow_timeout_handling_helper().
 {
   rxmit_timeout_double = mymax( mymin((tcp_master->getSlowTimeoutDouble() *
                                tcp_backoff[mymin(nrxmits, (uint32)TCP_DEFAULT_BACKOFF_LIMIT)] *
                                ((rtt_smoothed >> TCP_DEFAULT_RTT_SHIFT) + rtt_var)), TCP_DEFAULT_RXMIT_MAX_TIMEOUT),
                                TCP_DEFAULT_RXMIT_MIN_TIMEOUT);
   rxmit_timeout = tcp_master->inHost()->d2t(rxmit_timeout_double, 0);
 }
ltime_t s3f::s3fnet::TCPSession::now () inline private
An alias to get the current simulation time.
Definition at line 385 of file tcp_session.h.
References s3f::s3fnet::ProtocolSession::getNow(), and tcp_master.
Referenced by checkIdle().
 { return tcp_master->getNow(); }
ltime_t s3f::s3fnet::TCPSession::timeout_value () inline private
Current smoothed RTT timeout value.
Definition at line 388 of file tcp_session.h.
References rxmit_timeout.
Referenced by checkIdle(), process_new_acks(), send_data(), and update_timeout().
 { return rxmit_timeout; }
double s3f::s3fnet::TCPSession::timeout_double_value () inline private
Definition at line 389 of file tcp_session.h.
References rxmit_timeout_double.
 { return rxmit_timeout_double; }
double s3f::s3fnet::TCPSession::initial_timeout () inline private
Return initial timeout value for the first timeout.
Definition at line 392 of file tcp_session.h.
References rtt_smoothed, rtt_var, and TCP_DEFAULT_SLOW_TIMEOUT.
Referenced by init_state_closed().
   {
     return (((rtt_smoothed>>2) + rtt_var)>>1) * TCP_DEFAULT_SLOW_TIMEOUT;
   }
bool s3f::s3fnet::TCPSession::checkIdle () private
Check whether the idle time is long enough to slow start.
Definition at line 172 of file tcp_timer.cc.
References cwnd, idle_time, mss, now(), sndwnd, timeout_value(), and s3f::s3fnet::TCPSeqWindow::used().
 {
   int idle = sndwnd->used() == 0;
   if(idle && (now() - idle_time >= timeout_value()))
   {
     cwnd = mss;
     return true;
   }
   return false;
 }
int s3f::s3fnet::TCPSession::sender_send_sack (int sack_flag, byte mask, byte *& options) private
This method handles the situation when a sender tries to send a packet.
It sends the sack permitted option. At the same time, it keeps which segments are sent out but have not yet been acknowledged (maybe sacked) in the list of entries.
Definition at line 40 of file tcp_sack.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::TCPMessage::TCP_FLAG_SYN, TCP_SACK_PERMITTED, and TCP_SACK_PERMITTED_KIND.
 {
   // sender notifies the other side that sack is permitted.
   if(sack_flag == TCP_SACK_PERMITTED)
   {
     // TCP_SACK_PERMITTED when SYN is set,otherwise terminate the program.
     if(!(TCPMessage::TCP_FLAG_SYN & mask))
       error_quit("ERROR: TCPSession::sender_send_sack(), "
                  "TCP_SACK_PERMITTED must be used together with SYN mask.\n");
     // because the header should be a multiple of 32 bits, so 4 bytes are here.
     byte* sack_permitted_option = new byte[4];
     sack_permitted_option[0] = TCP_SACK_PERMITTED_KIND;         // Kind   = 4
     sack_permitted_option[1] = 2;                           // Length = 2
     options = sack_permitted_option;
     return 4;   // add 4 bytes.
   } else return 0;
 }
int s3f::s3fnet::TCPSession::receiver_send_sack (int sack_flag, byte mask, uint32 ackno, byte *& options) private
This method handles the situation when a receiver tries to send a packet.
It should consider sending the sack options. The method returns the length to be added to the standard TCP header length.
Definition at line 61 of file tcp_sack.cc.
References s3f::s3fnet::TCPBlockList::clear_blocks(), s3f::s3fnet::TCPBlockList::fetch_blocks(), rcv_scoreboard, TCP_SACK_MAX_BLOCKS, TCP_SACK_OPTION, and TCP_SACK_OPTION_KIND.
 {
   // as RFC 2018, SACK options should be included in all ACKs which do not ACK
   // the highest seqnuence number in the data receiver's queue.
   if((TCP_SACK_OPTION == sack_flag) &&(ackno < rcvwnd->getHighestSeqno()))
   {
     // the first 2 bytes are empty. 2 -> Kind(5), length; 4 * (left, right)
     // important: make it's multiple of 32 bits.
     //      byte tcp_option[4+8*4];
     byte* tcp_option = new byte[4 + 8 * TCP_SACK_MAX_BLOCKS];
     // kind = 5
     tcp_option[0]  = TCP_SACK_OPTION_KIND;
     uint32 *buffer =  (uint32 *)&tcp_option[2];
     // before sending out attached sack blocks, remove lowest
     rcv_scoreboard->clear_blocks(ackno);
     // we can convey TCP_SACK_MAX_BLOCKS blocks
     int real_num = rcv_scoreboard->fetch_blocks(buffer, TCP_SACK_MAX_BLOCKS);
     // update the length of valid sack option. totally, there are real_num blocks.
     tcp_option[1] = 2 + 8 * real_num;
     // return added length
     // attention: 4 + 8 * real_num includes the 2 padding bytes, which make
     // the length be a multiple of 4 bytes.
     // data->insert_at_front(tcp_option, 4 + 8 * real_num);
     // return 1 + 2 * real_num;         // (1 + 2 * real_num) * (32 bits)
     //
     // [03/23/04] always carry the same size.
     options = tcp_option;
     return 4 + 8 * TCP_SACK_MAX_BLOCKS;
   }
   return 0;
 }
void s3f::s3fnet::TCPSession::sender_recv_sack (TCPMessage * tcphdr) private
This method handles the situation when a sender receives sack options.
The information is kept accordingly.
Definition at line 99 of file tcp_sack.cc.
References s3f::s3fnet::TCPMessage::ackno, s3f::s3fnet::TCPBlockList::clear_blocks(), s3f::s3fnet::TCPMessage::flags, s3f::s3fnet::TCPMaster::getVersion(), s3f::s3fnet::TCPBlockList::insert_block(), s3f::s3fnet::TCPMessage::options, snd_scoreboard, TCP_DUMP, s3f::s3fnet::TCPMessage::TCP_FLAG_ACK, tcp_master, TCP_SACK_OPTION_KIND, and s3f::s3fnet::TCPMaster::TCP_VERSION_SACK.
 {
   // update the sack information obtained.
   if(tmsg->options && TCP_SACK_OPTION_KIND == tmsg->options[0])
   {
     TCP_DUMP(printf("sender_recv_sack(), SACK option set!\n"));
     assert(tcp_master->getVersion() == TCPMaster::TCP_VERSION_SACK);
     // first if ack advances, we update the mySack_Entries.
     if(tmsg->flags & TCPMessage::TCP_FLAG_ACK)
     {
         snd_scoreboard->clear_blocks(tmsg->ackno);
     }
     // sack_length is 2 + 8 * num
     // int num = ((tcp_hdr_option_length(msg)-2)/8);
     assert(tmsg->options);
     int num = (tmsg->options[1] - 2) / 8;
     uint32 left,right;
     // now we sack the entries
     for(int i=0; i<num; i++)
     {
       // 2  is (kind, length)
       left  = *((uint32 *)&tmsg->options[2 + 4 * 2 * i]);
       right = *((uint32 *)&tmsg->options[2 + 4 * (2 * i + 1)]);
       snd_scoreboard->insert_block(left, right - left);
     }
   }
 }
void s3f::s3fnet::TCPSession::receiver_recv_sack (TCPMessage * tcphdr) private
This method handles the situation when a receiver receives a packet.
The method retrieves the sack permitted information. At the same time, it updates the highest sequence number received so far.
Definition at line 130 of file tcp_sack.cc.
References s3f::s3fnet::TCPBlockList::insert_block(), s3f::s3fnet::TCPBlockList::is_new(), s3f::s3fnet::TCPMessage::options, s3f::s3fnet::ProtocolMessage::payload(), rcv_scoreboard, s3f::s3fnet::DataMessage::realByteCount(), sack_permitted, s3f::s3fnet::TCPMessage::seqno, and TCP_SACK_PERMITTED_KIND.
 {
   if(tmsg->options && (TCP_SACK_PERMITTED_KIND == tmsg->options[0]))
     sack_permitted = true;
   DataMessage* payload = (DataMessage*)tmsg->payload();
   if(!payload || !payload->realByteCount()) return;
   uint32 real_seqno  = tmsg->seqno;
   uint32 real_length = payload->realByteCount();
   if(rcv_scoreboard->is_new(&real_seqno, &real_length))
     rcv_scoreboard->insert_block(real_seqno, real_length);
 }
void s3f::s3fnet::TCPSession::sack_send_in_fast_recovery () private
The method handles sending sack when fast recovery is enabled.
Definition at line 162 of file tcp_sack.cc.
References cwnd, s3f::s3fnet::TCPSeqWindow::firstUnused(), mss, sack_pipe, sack_resend_segments(), segment_and_send(), sndwnd, and s3f::s3fnet::TCPSeqWindow::unused().
Referenced by process_dup_acks(), and process_new_acks().
 {
   bool found = true;
   while(sack_pipe < cwnd && found)
   {
     if(!sack_resend_segments(false)) found = false;
     else sack_pipe += mss;
   }
   if(!found && sndwnd->unused() >= mss)
   {
     sack_pipe += segment_and_send(sndwnd->firstUnused(), cwnd - sack_pipe);
   }
 }
bool s3f::s3fnet::TCPSession::sack_resend_segments (bool first_flag) private
When the sack option is set, this method is used for retransmissions.
Definition at line 145 of file tcp_sack.cc.
References recover_seq, resend_segments(), rxmit_seq, snd_scoreboard, sndwnd, s3f::s3fnet::TCPSeqWindow::start(), and s3f::s3fnet::TCPBlockList::unavailable().
Referenced by process_dup_acks(), sack_send_in_fast_recovery(), and timeout_resend().
 {
   // we only support fixed-sized packet length
   if(first_flag)  rxmit_seq = snd_scoreboard->unavailable(sndwnd->start());
   else rxmit_seq = snd_scoreboard->unavailable(rxmit_seq);
   if(rxmit_seq < recover_seq)
   {
     // here note that rxmit_seq will be updated in resend_segments
     resend_segments(rxmit_seq, 1);
     return true;
   }
   // can't find a packet to be retransmitted.
   return false;
 }
virtual void s3f::s3fnet::SocketSession::reinit () inline virtual inherited
Called by socket to reinitialize the destination ip and port.
Definition at line 268 of file socket_session.h.
References s3f::s3fnet::SessionID::dst_ip, s3f::s3fnet::SessionID::dst_port, and IPADDR_ANYDEST.
Referenced by s3f::s3fnet::SocketMaster::control(), and s3f::s3fnet::NBSocketMaster::control().
{
     dst_ip = IPADDR_ANYDEST;
     dst_port = 0;
   }
char* s3f::s3fnet::SessionID::toString (char * buf) inline inherited
Translate the ID into a textual string.
Parameters
buf buffer to write into (MUST NOT BE NULL)
Returns
pointer to the same buffer passe din
Definition at line 121 of file socket_session.h.
References s3f::s3fnet::SessionID::dst_ip, s3f::s3fnet::SessionID::dst_port, s3f::s3fnet::IPPrefix::ip2txt(), s3f::s3fnet::SessionID::prot_id, s3f::s3fnet::SessionID::src_ip, and s3f::s3fnet::SessionID::src_port.
{
     assert(buf);
     char buf0[50], buf1[50];
     sprintf(buf, "prot %u src_ip %s src_port %u dst_ip %s dst_port %u",
             prot_id, IPPrefix::ip2txt(src_ip, buf0), src_port,
             IPPrefix::ip2txt(dst_ip, buf1), dst_port);
     return buf;
   }
Member Data Documentation
TCPMaster* s3f::s3fnet::TCPSession::tcp_master private
Point to the tcp master.
Definition at line 109 of file tcp_session.h.
Referenced by acknowledge(), active_open(), allocate_buffers(), backoff_timeout(), cancel_delay_ack(), check_cwnd(), clear_app_state(), getSessionMaster(), init_state_closed(), init_state_established(), init_state_fin_wait_1(), init_state_last_ack(), init_state_listen(), init_state_syn_received(), init_state_syn_sent(), init_state_time_wait(), is_ok(), now(), process_dup_acks(), process_new_acks(), process_SYN(), receive(), release(), send_data(), send_delay_ack(), sender_recv_sack(), slow_timeout_handling_helper(), slowTimeoutHandling(), TCPSession(), timeout_resend(), update_remote_window_size(), update_timeout(), and wake_app().
int s3f::s3fnet::TCPSession::state private
The current state of the tcp session.
Definition at line 112 of file tcp_session.h.
Referenced by appl_close(), calc_advertised_wnd(), connected(), init_state_close_wait(), init_state_closed(), init_state_closing(), init_state_established(), init_state_fin_wait_1(), init_state_fin_wait_2(), init_state_last_ack(), init_state_listen(), init_state_syn_received(), init_state_syn_sent(), init_state_time_wait(), is_ok(), process_ACK(), process_FIN(), process_new_acks(), process_SYN(), receive(), send_data(), slow_timeout_handling_helper(), slowTimeoutHandling(), and timeout_resend().
int s3f::s3fnet::TCPSession::socket private
The socket id.
Definition at line 115 of file tcp_session.h.
Referenced by clear_app_state(), s3f::s3fnet::TCPMaster::deleteSession(), s3f::s3fnet::TCPMaster::setConnected(), s3f::s3fnet::TCPMaster::setIdle(), s3f::s3fnet::TCPMaster::setListening(), setSocketID(), and wake_app().
TCPRecvWindow* s3f::s3fnet::TCPSession::rcvwnd private
The receive window of the tcp session.
Definition at line 118 of file tcp_session.h.
Referenced by abort(), acknowledge(), allocate_buffers(), appl_close(), appl_recv(), calc_advertised_wnd(), deallocate_buffers(), fastTimeoutHandling(), init_state_close_wait(), init_state_closing(), init_state_fin_wait_1(), init_state_last_ack(), init_state_listen(), init_state_syn_received(), init_state_syn_sent(), process_ACK(), process_FIN(), process_new_data(), process_SYN(), receive(), resend_segments(), segment_and_send(), slow_timeout_handling_helper(), timeout_resend(), wake_app(), and ~TCPSession().
TCPSendWindow* s3f::s3fnet::TCPSession::sndwnd private
The send window of the tcp session.
Definition at line 121 of file tcp_session.h.
Referenced by abort(), acknowledge(), active_open(), allocate_buffers(), appl_close(), appl_send(), checkIdle(), deallocate_buffers(), fastTimeoutHandling(), init_state_established(), init_state_fin_wait_1(), init_state_last_ack(), init_state_listen(), init_state_syn_received(), init_state_syn_sent(), process_ACK(), process_acks(), process_dup_acks(), process_new_acks(), process_SYN(), receive(), resend_segments(), sack_resend_segments(), sack_send_in_fast_recovery(), segment_and_send(), send_data(), slow_timeout_handling_helper(), timeout_resend(), wake_app(), and ~TCPSession().
uint32 s3f::s3fnet::TCPSession::rcvwnd_size private
Remote receive window size.
Definition at line 124 of file tcp_session.h.
Referenced by calc_threshold(), init_state_closed(), init_state_listen(), process_acks(), process_SYN(), segment_and_send(), and update_remote_window_size().
uint32 s3f::s3fnet::TCPSession::cwnd private
Congestion window.
Definition at line 127 of file tcp_session.h.
Referenced by calc_threshold(), check_cwnd(), checkIdle(), init_state_closed(), init_state_listen(), process_dup_acks(), process_new_acks(), resend_segments(), sack_send_in_fast_recovery(), segment_and_send(), and slow_timeout_handling_helper().
uint32 s3f::s3fnet::TCPSession::ssthresh private
Threshold size for updating the congestion window.
Definition at line 130 of file tcp_session.h.
Referenced by calc_threshold(), check_cwnd(), init_state_closed(), init_state_established(), init_state_listen(), process_dup_acks(), and process_new_acks().
uint32 s3f::s3fnet::TCPSession::mss private
Maximum segment size.
Definition at line 133 of file tcp_session.h.
Referenced by calc_advertised_wnd(), calc_threshold(), check_cwnd(), checkIdle(), init_state_closed(), init_state_listen(), process_dup_acks(), process_new_acks(), resend_segments(), sack_send_in_fast_recovery(), segment_and_send(), and slow_timeout_handling_helper().
uint32 s3f::s3fnet::TCPSession::ndupacks private
Number of consecutive duplicate ACKs received.
Definition at line 136 of file tcp_session.h.
Referenced by init_state_closed(), init_state_listen(), process_acks(), process_dup_acks(), process_new_acks(), and slow_timeout_handling_helper().
uint32 s3f::s3fnet::TCPSession::nrxmits private
Number of consecutive packet retransmissions.
Definition at line 139 of file tcp_session.h.
Referenced by backoff_timeout(), init_state_closed(), init_state_fin_wait_1(), init_state_syn_received(), init_state_syn_sent(), process_ACK(), process_SYN(), slow_timeout_handling_helper(), and update_timeout().
uint32 s3f::s3fnet::TCPSession::persist_shift private
Left shift to get persist (exponential) timeout.
Definition at line 142 of file tcp_session.h.
int s3f::s3fnet::TCPSession::rtt_smoothed private
Smoothed round trip time.
Definition at line 145 of file tcp_session.h.
Referenced by backoff_timeout(), init_state_closed(), initial_timeout(), slow_timeout_handling_helper(), and update_timeout().
int s3f::s3fnet::TCPSession::rtt_measured private
Measured round trip time.
Definition at line 148 of file tcp_session.h.
Referenced by process_new_acks(), and update_timeout().
int s3f::s3fnet::TCPSession::rtt_count private
The current RTT count.
Definition at line 151 of file tcp_session.h.
Referenced by init_state_closed(), process_dup_acks(), process_new_acks(), send_data(), slow_timeout_handling_helper(), slowTimeoutHandling(), and update_timeout().
int s3f::s3fnet::TCPSession::rtt_var private
Current estimated RTT variance.
Definition at line 154 of file tcp_session.h.
Referenced by backoff_timeout(), init_state_closed(), initial_timeout(), slow_timeout_handling_helper(), and update_timeout().
uint32 s3f::s3fnet::TCPSession::rxmit_seq private
The last sequence number of retransmitted segment plus one.
Definition at line 157 of file tcp_session.h.
Referenced by process_new_acks(), resend_segments(), and sack_resend_segments().
uint32 s3f::s3fnet::TCPSession::measured_seq private
The sequence number of the segment currently being measured.
Definition at line 160 of file tcp_session.h.
Referenced by process_new_acks(), and send_data().
uint32 s3f::s3fnet::TCPSession::recover_seq private
The largest seqno sent out when loss happens.
Definition at line 163 of file tcp_session.h.
Referenced by init_state_established(), process_dup_acks(), process_new_acks(), resend_segments(), sack_resend_segments(), and slow_timeout_handling_helper().
uint32 s3f::s3fnet::TCPSession::sack_pipe private
Indicate how much can be sent during fast recovery in SACK.
Definition at line 166 of file tcp_session.h.
Referenced by process_dup_acks(), process_new_acks(), and sack_send_in_fast_recovery().
bool s3f::s3fnet::TCPSession::delayed_ack private
True if the delayed ack is turned on.
Definition at line 169 of file tcp_session.h.
Referenced by acknowledge(), cancel_delay_ack(), fastTimeoutHandling(), init_state_fin_wait_1(), init_state_last_ack(), and send_delay_ack().
bool s3f::s3fnet::TCPSession::fast_recovery private
True if the session is still in the fast recovery mode.
Definition at line 172 of file tcp_session.h.
Referenced by process_new_acks().
bool s3f::s3fnet::TCPSession::timeout_loss private
Whether it is a timeout loss.
Definition at line 175 of file tcp_session.h.
Referenced by process_new_acks(), and slow_timeout_handling_helper().
bool s3f::s3fnet::TCPSession::sack_permitted private
Whether SACK is permitted as indicated by the peer.
Definition at line 178 of file tcp_session.h.
Referenced by receiver_recv_sack().
bool s3f::s3fnet::TCPSession::close_issued private
Whether the upper layer has issued close.
Definition at line 181 of file tcp_session.h.
Referenced by appl_close(), init_state_established(), process_FIN(), and receive().
bool s3f::s3fnet::TCPSession::simultaneous_closing private
Whether it is a simultaneous closing.
Definition at line 184 of file tcp_session.h.
Referenced by init_state_established(), init_state_fin_wait_1(), and process_FIN().
TCPBlockList* s3f::s3fnet::TCPSession::snd_scoreboard private
The score board for blocks sacked maintained by the sender side.
Definition at line 187 of file tcp_session.h.
Referenced by process_new_acks(), sack_resend_segments(), sender_recv_sack(), and slow_timeout_handling_helper().
TCPBlockList* s3f::s3fnet::TCPSession::rcv_scoreboard private
The score board for the receiver side.
Definition at line 190 of file tcp_session.h.
Referenced by receiver_recv_sack(), and receiver_send_sack().
ltime_t s3f::s3fnet::TCPSession::rxmit_timeout private
The current retransmission timeout.
Definition at line 193 of file tcp_session.h.
Referenced by backoff_timeout(), init_state_closed(), timeout_value(), and update_timeout().
double s3f::s3fnet::TCPSession::rxmit_timeout_double private
Definition at line 194 of file tcp_session.h.
Referenced by backoff_timeout(), init_state_closed(), timeout_double_value(), and update_timeout().
ltime_t s3f::s3fnet::TCPSession::idle_time private
Idle time for the other party.
Definition at line 197 of file tcp_session.h.
Referenced by checkIdle().
double s3f::s3fnet::TCPSession::idle_time_double private
Definition at line 198 of file tcp_session.h.
ltime_t s3f::s3fnet::TCPSession::rxmit_timer_count private
Retransmission timer count.
Definition at line 201 of file tcp_session.h.
Referenced by init_state_close_wait(), init_state_closed(), init_state_fin_wait_2(), init_state_listen(), process_ACK(), process_new_acks(), resend_segments(), send_data(), slow_timeout_handling_helper(), and slowTimeoutHandling().
double s3f::s3fnet::TCPSession::rxmit_timer_count_double private
Definition at line 202 of file tcp_session.h.
ltime_t s3f::s3fnet::TCPSession::msl_timer_count private
The timer count that lasts 2*msl.
Definition at line 206 of file tcp_session.h.
Referenced by init_state_closed(), init_state_listen(), init_state_time_wait(), process_ACK(), and slowTimeoutHandling().
double s3f::s3fnet::TCPSession::msl_timer_count_double private
Definition at line 207 of file tcp_session.h.
uint32 s3f::s3fnet::SessionID::prot_id inherited
The protocol number.
Definition at line 132 of file socket_session.h.
Referenced by s3f::s3fnet::SessionCmp::operator()(), s3f::s3fnet::SessionID::operator=(), and s3f::s3fnet::SessionID::toString().
IPADDR s3f::s3fnet::SessionID::src_ip inherited
Source ip address.
Definition at line 135 of file socket_session.h.
Referenced by s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SessionCmp::operator()(), s3f::s3fnet::SessionID::operator=(), s3f::s3fnet::UDPSession::send(), send_data(), s3f::s3fnet::UDPSession::setSource(), setSource(), and s3f::s3fnet::SessionID::toString().
IPADDR s3f::s3fnet::SessionID::dst_ip inherited
Destination ip address.
Definition at line 138 of file socket_session.h.
Referenced by active_open(), s3f::s3fnet::UDPSession::connect(), s3f::s3fnet::SocketMaster::connected(), s3f::s3fnet::NBSocketMaster::connected(), s3f::s3fnet::SessionCmp::operator()(), s3f::s3fnet::SessionID::operator=(), s3f::s3fnet::SocketSession::reinit(), s3f::s3fnet::UDPSession::send(), send_data(), and s3f::s3fnet::SessionID::toString().
uint16 s3f::s3fnet::SessionID::src_port inherited
Source port number.
Definition at line 141 of file socket_session.h.
Referenced by s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SessionCmp::operator()(), s3f::s3fnet::SessionID::operator=(), s3f::s3fnet::UDPSession::send(), send_data(), s3f::s3fnet::UDPSession::setSource(), setSource(), and s3f::s3fnet::SessionID::toString().
uint16 s3f::s3fnet::SessionID::dst_port inherited
Destination port number.
Definition at line 144 of file socket_session.h.
Referenced by active_open(), s3f::s3fnet::UDPSession::connect(), s3f::s3fnet::SocketMaster::connected(), s3f::s3fnet::NBSocketMaster::connected(), s3f::s3fnet::SessionCmp::operator()(), s3f::s3fnet::SessionID::operator=(), s3f::s3fnet::SocketSession::reinit(), s3f::s3fnet::UDPSession::send(), send_data(), and s3f::s3fnet::SessionID::toString().
The documentation for this class was generated from the following files:
tcp_session.h
tcp_receiver.cc
tcp_sack.cc
tcp_sender.cc
tcp_session.cc
tcp_state.cc
tcp_timer.cc