S3F: Handle Class Reference
Handle Class Reference
#include <event.h>
Public Member Functions
Handle (void *)
Handle ()
~Handle ()
bool cancel ()
Public Attributes
Event * __eptr
ltime_t __time
Timeline * __home_tl
Detailed Description
Definition at line 102 of file event.h.
Constructor & Destructor Documentation
Handle::Handle (void * eptr)
Definition at line 70 of file event.cc.
References __eptr, __home_tl, __time, Event::get_home_tl(), and Event::get_time().
{
   __eptr = (Event*)eptr;
   __time = __eptr->get_time();
   __home_tl = __eptr->get_home_tl();
 }
Handle::Handle () inline
Definition at line 105 of file event.h.
 {};
Handle::~Handle ()
Definition at line 83 of file event.cc.
 {};
Member Function Documentation
bool Handle::cancel ()
Definition at line 76 of file event.cc.
References __eptr, and Event::cancel().
                     {
  if( __time <= __home_tl->now()) return false;
  __eptr->cancel();
  if( __time <= __home_tl->now()) return false;
  return true;
 }
Member Data Documentation
Event* Handle::__eptr
Definition at line 107 of file event.h.
Referenced by cancel(), and Handle().
ltime_t Handle::__time
Definition at line 108 of file event.h.
Referenced by Handle().
Timeline* Handle::__home_tl
Definition at line 109 of file event.h.
Referenced by Handle().
The documentation for this class was generated from the following files:
event.h
event.cc