S3F: s3f::s3fnet::BSocketContinuation Class Reference
s3f::s3fnet::BSocketContinuation Class Reference abstract
Continuation used by the non-blocking socket interface.
#include <socket_master.h>
Public Member Functions
BSocketContinuation (ProtocolSession *sess)
The constructor.
virtual void success ()=0
Indicates successful state completion.
virtual void failure ()=0
Indicates failed state completion.
ProtocolSession * getOwnerSession ()
Return the owner protocol session.
virtual const char * getType ()
virtual void setSCVal (int v)
Function to set the SocketContinuation (SC) value.
virtual int getSCVal ()
Function to get the SocketContinuation (SC) value.
Public Attributes
void(SocketMaster::* next_stage)(int, BSocketContinuation *)
Proceeds to next continuation stage.
int myscval
int retval
The return value of the function using the continuation.
ProtocolSession * owner
The owner protocol session.
SocketContinuation * chain_continuation
Other continuation structures can be chained here.
Detailed Description
Continuation used by the non-blocking socket interface.
Definition at line 38 of file socket_master.h.
Constructor & Destructor Documentation
s3f::s3fnet::BSocketContinuation::BSocketContinuation (ProtocolSession * sess) inline
The constructor.
Definition at line 41 of file socket_master.h.
 : SocketContinuation(sess) {}
Member Function Documentation
virtual void s3f::s3fnet::BSocketContinuation::success () pure virtual
Indicates successful state completion.
Called if the function using the continuation completes successfully. The function needs to be overridden in the derived class.
Implemented in s3f::s3fnet::BTCPClientSessionContinuation, s3f::s3fnet::TCPClientSessionContinuation, s3f::s3fnet::TCPServerSessionContinuation, s3f::s3fnet::UDPServerSessionContinuation, and s3f::s3fnet::UDPClientSessionContinuation.
Referenced by s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SocketMaster::accept2b(), s3f::s3fnet::SocketMaster::close(), s3f::s3fnet::SocketMaster::close1(), s3f::s3fnet::SocketMaster::connect1(), s3f::s3fnet::SocketMaster::recv(), s3f::s3fnet::SocketMaster::recv1(), s3f::s3fnet::SocketMaster::send(), and s3f::s3fnet::SocketMaster::send1().
virtual void s3f::s3fnet::BSocketContinuation::failure () pure virtual
Indicates failed state completion.
Called if an error occurred in the function using the continuation. The function needs to be overridden in the derived class.
Implemented in s3f::s3fnet::BTCPClientSessionContinuation, s3f::s3fnet::TCPClientSessionContinuation, s3f::s3fnet::TCPServerSessionContinuation, s3f::s3fnet::UDPServerSessionContinuation, and s3f::s3fnet::UDPClientSessionContinuation.
Referenced by s3f::s3fnet::SocketMaster::accept(), s3f::s3fnet::SocketMaster::accept1a(), s3f::s3fnet::SocketMaster::accept1b(), s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SocketMaster::accept2b(), s3f::s3fnet::SocketMaster::close(), s3f::s3fnet::SocketMaster::close1(), s3f::s3fnet::SocketMaster::connect(), s3f::s3fnet::SocketMaster::connect1(), s3f::s3fnet::SocketMaster::recv(), s3f::s3fnet::SocketMaster::recv1(), s3f::s3fnet::SocketMaster::send(), and s3f::s3fnet::SocketMaster::send1().
ProtocolSession* s3f::s3fnet::SocketContinuation::getOwnerSession () inline inherited
Return the owner protocol session.
Definition at line 34 of file socket_session.h.
References s3f::s3fnet::SocketContinuation::owner.
 { return owner; }
virtual const char* s3f::s3fnet::SocketContinuation::getType () inline virtual inherited
Reimplemented in s3f::s3fnet::NBTCPServerSessionContinuation, s3f::s3fnet::BTCPClientSessionContinuation, s3f::s3fnet::NBTCPClientSessionContinuation, and s3f::s3fnet::TCPClientSessionContinuation.
Definition at line 42 of file socket_session.h.
 { return "N/A"; }
virtual void s3f::s3fnet::SocketContinuation::setSCVal (int v) inline virtual inherited
Function to set the SocketContinuation (SC) value.
Parameters
v SC value to set
Definition at line 56 of file socket_session.h.
References s3f::s3fnet::SocketContinuation::myscval.
Referenced by s3f::s3fnet::BTCPClientSessionContinuation::BTCPClientSessionContinuation().
 { myscval = v; }
virtual int s3f::s3fnet::SocketContinuation::getSCVal () inline virtual inherited
Function to get the SocketContinuation (SC) value.
Returns
the SC value
Definition at line 62 of file socket_session.h.
References s3f::s3fnet::SocketContinuation::myscval.
 { return myscval; }
Member Data Documentation
void(SocketMaster::* s3f::s3fnet::BSocketContinuation::next_stage)(int, BSocketContinuation *)
Proceeds to next continuation stage.
Used as a function pointer to proceed to the next stage of the continuation. The continuation function must be a method of the SocketMaster class.
Definition at line 65 of file socket_master.h.
Referenced by s3f::s3fnet::SocketMaster::accept(), s3f::s3fnet::SocketMaster::accept1a(), s3f::s3fnet::SocketMaster::accept1b(), s3f::s3fnet::SocketMaster::block_till(), s3f::s3fnet::SocketMaster::close(), s3f::s3fnet::SocketMaster::connect(), s3f::s3fnet::SocketMaster::recv(), and s3f::s3fnet::SocketMaster::send().
int s3f::s3fnet::SocketContinuation::myscval inherited
Definition at line 50 of file socket_session.h.
Referenced by s3f::s3fnet::SocketContinuation::getSCVal(), s3f::s3fnet::SocketContinuation::setSCVal(), and s3f::s3fnet::SocketContinuation::~SocketContinuation().
int s3f::s3fnet::SocketContinuation::retval inherited
The return value of the function using the continuation.
The return value makes sense only when the function has completed successfully. Note that a function using continuation could be of a bool type, in which case we still use an integer return value.
Definition at line 71 of file socket_session.h.
Referenced by s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SocketMaster::accept2b(), s3f::s3fnet::TCPServerSession::connection_accepted(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::UDPServerSession::data_sent(), s3f::s3fnet::TCPServerSession::data_sent(), s3f::s3fnet::FileSender::handleIO(), s3f::s3fnet::NBTCPClientSession::non_blocking_loop(), s3f::s3fnet::NBTCPServerSession::non_blocking_loop(), s3f::s3fnet::SocketMaster::recv(), s3f::s3fnet::NBSocketMaster::recv(), s3f::s3fnet::SocketMaster::recv1(), s3f::s3fnet::NBSocketMaster::recv1(), s3f::s3fnet::UDPServerSession::request_received(), s3f::s3fnet::TCPServerSession::request_received(), s3f::s3fnet::SocketMaster::send(), s3f::s3fnet::NBSocketMaster::send(), s3f::s3fnet::SocketMaster::send1(), and s3f::s3fnet::NBSocketMaster::send1().
ProtocolSession* s3f::s3fnet::SocketContinuation::owner inherited
The owner protocol session.
Definition at line 74 of file socket_session.h.
Referenced by s3f::s3fnet::UDPClientSessionContinuation::failure(), s3f::s3fnet::UDPServerSessionContinuation::failure(), s3f::s3fnet::NBTCPClientSessionContinuation::failure(), s3f::s3fnet::TCPClientSessionContinuation::failure(), s3f::s3fnet::TCPServerSessionContinuation::failure(), s3f::s3fnet::NBTCPServerSessionContinuation::failure(), s3f::s3fnet::BTCPClientSessionContinuation::failure(), s3f::s3fnet::SocketContinuation::getOwnerSession(), s3f::s3fnet::NBTCPClientSessionContinuation::resume(), s3f::s3fnet::NBTCPServerSessionContinuation::resume(), s3f::s3fnet::UDPServerSessionContinuation::send_timeout(), s3f::s3fnet::UDPClientSessionContinuation::success(), s3f::s3fnet::UDPServerSessionContinuation::success(), s3f::s3fnet::TCPClientSessionContinuation::success(), s3f::s3fnet::TCPServerSessionContinuation::success(), s3f::s3fnet::NBTCPClientSessionContinuation::success(), s3f::s3fnet::BTCPClientSessionContinuation::success(), s3f::s3fnet::NBTCPServerSessionContinuation::success(), s3f::s3fnet::UDPClientSessionContinuation::timeout(), s3f::s3fnet::TCPClientSessionContinuation::timeout(), and s3f::s3fnet::BTCPClientSessionContinuation::timeout().
SocketContinuation* s3f::s3fnet::SocketContinuation::chain_continuation inherited
Other continuation structures can be chained here.
Definition at line 77 of file socket_session.h.
Referenced by s3f::s3fnet::SocketMaster::accept(), s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::accept1a(), s3f::s3fnet::SocketMaster::accept1b(), and s3f::s3fnet::SocketContinuation::~SocketContinuation().
The documentation for this class was generated from the following file:
socket_master.h