S3F: s3f::s3fnet::DropController Class Reference
s3f::s3fnet::DropController Class Reference
A controller that builds a flow for each received packet to drop all packets it matches (this demonstrates the flow table's basic implementation).
#include <openflow_controller.h>
Public Member Functions
void ReceiveFromSwitch (OpenFlowSwitchSession *swtch, ofpbuf *buffer)
A switch calls this method to pass a message on to the Controller.
virtual void AddSwitch (OpenFlowSwitchSession *swtch)
Adds a switch to the controller.
void StartDump (StatsDumpCallback *cb)
Starts a callback-based, reliable, possibly multi-message reply to a request made by the controller.
Public Attributes
int type
model of the controller, e.g., learning_switch
Protected Types
typedef std::set
< OpenFlowSwitchSession * > Switches_t
Protected Member Functions
virtual void SendToSwitch (OpenFlowSwitchSession *swtch, void *msg, size_t length)
ofp_flow_mod * BuildFlow (sw_flow_key key, uint32_t buffer_id, uint16_t command, void *acts, size_t actions_len, int idle_timeout, int hard_timeout)
uint8_t GetPacketType (ofpbuf *buffer)
Protected Attributes
Switches_t m_switches
The collection of switches registered to this controller.
Detailed Description
A controller that builds a flow for each received packet to drop all packets it matches (this demonstrates the flow table's basic implementation).
When a connected switch passes it a packet that the switch doesn't recognize, the controller configures the switch to make a flow that drops alike packets.
Definition at line 126 of file openflow_controller.h.
Member Typedef Documentation
typedef std::set<OpenFlowSwitchSession* > s3f::s3fnet::Controller::Switches_t protected inherited
Definition at line 114 of file openflow_controller.h.
Member Function Documentation
void s3f::s3fnet::DropController::ReceiveFromSwitch (OpenFlowSwitchSession * swtch, ofpbuf * buffer) virtual
A switch calls this method to pass a message on to the Controller.
Parameters
swtch The switch the message was received from.
buffer The message.
Reimplemented from s3f::s3fnet::Controller.
Definition at line 107 of file openflow_controller.cc.
References s3f::s3fnet::Controller::BuildFlow(), s3f::s3fnet::Controller::GetPacketType(), s3f::s3fnet::Controller::m_switches, OF_CTRL_DUMP, s3f::s3fnet::Controller::SendToSwitch(), and s3f::s3fnet::Controller::type.
 {
         if (m_switches.find (swtch) == m_switches.end ())
         {
                 OF_CTRL_DUMP( printf("Can't receive from this switch, not registered to the Controller.\n") );
                 return;
         }
         // We have received any packet at this point, so we pull the header to figure out what type of packet we're handling.
         uint8_t type = GetPacketType (buffer);
         if (type == OFPT_PACKET_IN) // The switch didn't understand the packet it received, so it forwarded it to the controller.
         {
                 ofp_packet_in * opi = (ofp_packet_in*)ofpbuf_try_pull (buffer, offsetof (ofp_packet_in, data));
                 int port = ntohs (opi->in_port);
                 // Create matching key.
                 sw_flow_key key;
                 key.wildcards = 0;
                 flow_extract (buffer, port != -1 ? port : OFPP_NONE, &key.flow);
                 ofp_flow_mod* ofm = BuildFlow (key, opi->buffer_id, OFPFC_ADD, 0, 0, OFP_FLOW_PERMANENT, OFP_FLOW_PERMANENT);
                 SendToSwitch (swtch, ofm, ofm->header.length);
         }
 }
void s3f::s3fnet::Controller::AddSwitch (OpenFlowSwitchSession * swtch) virtual inherited
Adds a switch to the controller.
Parameters
swtch The switch to register.
Reimplemented in s3f::s3fnet::LearningController.
Definition at line 26 of file openflow_controller.cc.
References s3f::s3fnet::error_quit(), and s3f::s3fnet::Controller::m_switches.
Referenced by s3f::s3fnet::LearningController::AddSwitch().
 {
         if (m_switches.find (swtch) != m_switches.end ())
         {
                 error_quit ("This Controller has already registered this switch!");
         }
         else
         {
                 m_switches.insert (swtch);
         }
 }
void s3f::s3fnet::Controller::StartDump (StatsDumpCallback * cb) inherited
Starts a callback-based, reliable, possibly multi-message reply to a request made by the controller.
If an incoming request needs to have a reliable reply that might require multiple messages, it can use StartDump() to set up a callback that will be called as buffer space for replies.
A stats request made by the controller is processed by the switch, the switch then calls this method to tell the controller to start asking for information. By default (it can be overridden), the controller stops all work to run through the callback. ReceiveFromSwitch must be defined appropriately to handle the status reply messages generated by the switch, or otherwise the status reply messages will be sent and discarded.
Parameters
cb The callback data.
Definition at line 87 of file openflow_controller.cc.
References OF_CTRL_DUMP, s3f::s3fnet::OpenFlowSwitchSession::StatsDone(), s3f::s3fnet::OpenFlowSwitchSession::StatsDump(), and s3f::s3fnet::StatsDumpCallback::swtch.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::ReceiveStatsRequest().
 {
         if (cb != 0)
         {
                 int error = 1;
                 while (error > 0) // Switch's StatsDump returns 1 if the reply isn't complete.
                 {
                         error = cb->swtch->StatsDump (cb);
                 }
                 if (error != 0) // When the reply is complete, error will equal zero if there's no errors.
                 {
                         OF_CTRL_DUMP (cout << "Dump Callback Error: " << strerror (-error) << endl );
                 }
                 // Clean up
                 cb->swtch->StatsDone (cb);
         }
 }
void s3f::s3fnet::Controller::SendToSwitch (OpenFlowSwitchSession * swtch, void * msg, size_t length) protected virtual inherited
However the controller is implemented, this method is to be used to pass a message on to a switch.
Parameters
swtch The switch to receive the message.
msg The message to send.
length The length of the message.
Definition at line 38 of file openflow_controller.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::OpenFlowSwitchSession::ForwardControlInput(), and s3f::s3fnet::Controller::m_switches.
Referenced by s3f::s3fnet::LearningController::process_recv_packet(), and ReceiveFromSwitch().
 {
         if (m_switches.find (swtch) == m_switches.end ())
         {
                 error_quit ("Can't send to this switch, not registered to the Controller.");
                 return;
         }
         swtch->ForwardControlInput (msg, length);
 }
ofp_flow_mod * s3f::s3fnet::Controller::BuildFlow (sw_flow_key key, uint32_t buffer_id, uint16_t command, void * acts, size_t actions_len, int idle_timeout, int hard_timeout) protected inherited
Construct flow data from a matching key to build a flow entry for adding, modifying, or deleting a flow.
Parameters
key The matching key data; used to create a flow that matches the packet.
buffer_id The OpenFlow Buffer ID; used to run the actions on the packet if we add or modify the flow.
command Whether to add, modify, or delete this flow.
acts List of actions to execute.
actions_len Length of the actions buffer.
idle_timeout Flow expires if left inactive for this amount of time (specify OFP_FLOW_PERMANENT to disable feature).
hard_timeout Flow expires after this amount of time (specify OFP_FLOW_PERMANENT to disable feature).
Returns
Flow data that when passed to SetFlow will add, modify, or delete a flow it defines.
Definition at line 49 of file openflow_controller.cc.
Referenced by s3f::s3fnet::LearningController::process_recv_packet(), and ReceiveFromSwitch().
 {
         ofp_flow_mod* ofm = (ofp_flow_mod*)malloc (sizeof(ofp_flow_mod) + actions_len);
         ofm->header.version = OFP_VERSION;
         ofm->header.type = OFPT_FLOW_MOD;
         ofm->header.length = htons (sizeof(ofp_flow_mod) + actions_len);
         ofm->command = htons (command);
         ofm->idle_timeout = htons (idle_timeout);
         ofm->hard_timeout = htons (hard_timeout);
         ofm->buffer_id = htonl (buffer_id);
         ofm->priority = OFP_DEFAULT_PRIORITY;
         memcpy (ofm->actions,acts,actions_len);
         ofm->match.wildcards = key.wildcards;                                 // Wildcard fields
         ofm->match.in_port = key.flow.in_port;                                // Input switch port
         memcpy (ofm->match.dl_src, key.flow.dl_src, sizeof ofm->match.dl_src); // Ethernet source address.
         memcpy (ofm->match.dl_dst, key.flow.dl_dst, sizeof ofm->match.dl_dst); // Ethernet destination address.
         ofm->match.dl_vlan = key.flow.dl_vlan;                                // Input VLAN OFP_VLAN_NONE;
         ofm->match.dl_type = key.flow.dl_type;                                // Ethernet frame type ETH_TYPE_IP;
         ofm->match.nw_proto = key.flow.nw_proto;                              // IP Protocol
         ofm->match.nw_src = key.flow.nw_src;                                  // IP source address
         ofm->match.nw_dst = key.flow.nw_dst;                                  // IP destination address
         ofm->match.tp_src = key.flow.tp_src;                                  // TCP/UDP source port
         ofm->match.tp_dst = key.flow.tp_dst;                                  // TCP/UDP destination port
         ofm->match.mpls_label1 = key.flow.mpls_label1;                        // Top of label stack htonl(MPLS_INVALID_LABEL);
         ofm->match.mpls_label2 = key.flow.mpls_label1;                        // Second label (if available) htonl(MPLS_INVALID_LABEL);
         return ofm;
 }
uint8_t s3f::s3fnet::Controller::GetPacketType (ofpbuf * buffer) protected inherited
Get the packet type on the buffer, which can then be used to determine how to handle the buffer.
Parameters
buffer The packet in OpenFlow buffer format.
Returns
The packet type, as defined in the ofp_type struct.
Definition at line 79 of file openflow_controller.cc.
References s3f::s3fnet::Controller::type.
Referenced by ReceiveFromSwitch(), and s3f::s3fnet::LearningController::ReceiveFromSwitch().
 {
         ofp_header* hdr = (ofp_header*)ofpbuf_try_pull (buffer, sizeof (ofp_header));
         uint8_t type = hdr->type;
         ofpbuf_push_uninit (buffer, sizeof (ofp_header));
         return type;
 }
Member Data Documentation
int s3f::s3fnet::Controller::type inherited
model of the controller, e.g., learning_switch
Definition at line 71 of file openflow_controller.h.
Referenced by s3f::s3fnet::Controller::GetPacketType(), s3f::s3fnet::Net::Net(), ReceiveFromSwitch(), s3f::s3fnet::LearningController::ReceiveFromSwitch(), and s3f::s3fnet::OpenFlowSwitchSession::SetController().
Switches_t s3f::s3fnet::Controller::m_switches protected inherited
The collection of switches registered to this controller.
Definition at line 115 of file openflow_controller.h.
Referenced by s3f::s3fnet::Controller::AddSwitch(), ReceiveFromSwitch(), s3f::s3fnet::LearningController::ReceiveFromSwitch(), s3f::s3fnet::Controller::SendToSwitch(), and s3f::s3fnet::Controller::~Controller().
The documentation for this class was generated from the following files:
openflow_controller.h
openflow_controller.cc