S3F: InChannel Class Reference
InChannel Class Reference
An InChannel is the endpoint of connections made by an OutChannel's mapto call.
#include <inchannel.h>
Public Member Functions
InChannel (Entity *)
InChannels are owned by Entities; at construction the identity of the owning Entity must be given.
virtual ~InChannel ()
Have to declare a dtor, but nothing intelligent is done by this implementation if an InChannel were deleted.
Entity * owner ()
Returns a pointer to the Entity that owns this InChannel.
Timeline * alignment ()
Returns a pointer to the Timeline on which the InChannel's owning entity is aligned.
void waitOn ()
waitOn() may be called by an executing Process, in which case that process is attached to the InChannel.
void waitOn (Process *)
The named Process is attached to the InChannel to be activated on the next Activation to arrive.
bool unwaitOn (Process *)
UnwaitOn disconnects the named process from the InChannel list.
bool unwaitOn ()
UnwaitOn disconnects the current running process from the InChannel list.
void bind ()
The named Process is attached to the InChannel to be activated on the next Activation to arrive.
void bind (Process *)
bind() may be called by an executing Process, in which case that process is attached to the InChannel.
bool unbind (Process *)
Removes the named Process from the list of Processes attached to the InChannel.
bool unbind ()
Removes the running Process from the list of Processes attached to the InChannel.
bool is_waiting (Process *)
Returns true if the named Process is attached to the InChannel but not bound to it.
bool is_waiting ()
Returns true if the running Process is attached to the InChannel but not bound to it.
bool is_bound (Process *)
Returns true if the named Process is bound to the InChannel.
bool is_bound ()
Returns true if the running Process is bound to the InChannel.
unsigned int s3fid ()
Returns the unique id assigned to this InChannel.
bool is_ve_attached ()
Whether the inchannel belongs to an entity host which is an openvz-based VE.
void set_ve_attached (bool v)
Set the attribute to indicate whether the inchannel belongs to an entity host which is an openvz-based VE.
InChannel (Entity *, string)
An InChannel may declare a string at construction, which is put in a directory at its owning Entity.
Protected Member Functions
void add_process (Process *)
add_process is called by the two versions of waitOn to attach the named Process, but not bind it.
void insertion_gateway (Process *, bool, unsigned int)
check alignment, and then see if the timeline's active channel is in fact this one.
void insert_process_pri (Process *, bool, unsigned int)
insert_process_pri is called both as a result of calling waitOn and as a result of calling bind.
Protected Attributes
list< ProcessPri > __waitingList
Ordered list of processes attached to the InChannel, awaiting activation.
string __extname
name of the inchannel (if apply)
Entity * __owner
owner of the channel
Timeline * __alignment
timeline of the entity that owns this InChannel
unsigned int __s3fid
unique id
bool __ve_attached
whether the inchannel belongs to a VE-proxy entity
Static Protected Attributes
static pthread_mutex_t inchannel_class_mutex
mutex protects access to __num_inchannels
static unsigned int __num_inchannels = 0
enumerate the number of inchannels we have created
Detailed Description
An InChannel is the endpoint of connections made by an OutChannel's mapto call.
If an InChannel is named as the target of such a call, then whenever the OutChannel write method is used to send an Activation, Processes that somehow have been attached to the Inchannel are activated.
A Process may be attached by calling InChannel methods bind, or waitOn. The former attachment persists after an activation is made, whereas the latter does not. Binds and waitOn calls may be undone by calls unbind and unwaitOn.
Definition at line 55 of file inchannel.h.
Constructor & Destructor Documentation
InChannel::InChannel (Entity * theowner)
InChannels are owned by Entities; at construction the identity of the owning Entity must be given.
Definition at line 22 of file inchannel.cc.
References Entity::__inchannel_list, __num_inchannels, __s3fid, Entity::entity_inst_mutex, and inchannel_class_mutex.
                                      : __extname(string("")),
                 __owner(theowner), __alignment(theowner->alignment()), __ve_attached(false)  {
         // the initialization above saves the identity of the owner, and
         // the timeline on which the owner is aligned.  It initializes the
         // string name to "" because none other was provided.
         // get unique id number
         pthread_mutex_lock(&inchannel_class_mutex);
         __s3fid = __num_inchannels++;
         pthread_mutex_unlock(&inchannel_class_mutex);
         // register inchannel with entity that owns it
         pthread_mutex_lock(&theowner->entity_inst_mutex);
         theowner->__inchannel_list.push_back(this);
         pthread_mutex_unlock(&theowner->entity_inst_mutex);
 }
InChannel::~InChannel () virtual
Have to declare a dtor, but nothing intelligent is done by this implementation if an InChannel were deleted.
Definition at line 75 of file inchannel.cc.
References inchannel_class_mutex, and s3fid().
                       {
         if(! s3fid() ) pthread_mutex_destroy(&inchannel_class_mutex);
 }
InChannel::InChannel (Entity * , string)
An InChannel may declare a string at construction, which is put in a directory at its owning Entity.
Member Function Documentation
Entity* InChannel::owner () inline
Returns a pointer to the Entity that owns this InChannel.
Definition at line 68 of file inchannel.h.
References __owner.
Referenced by OutChannel::mapto(), and Timeline::schedule().
 { return __owner; }
Timeline* InChannel::alignment () inline
Returns a pointer to the Timeline on which the InChannel's owning entity is aligned.
Definition at line 70 of file inchannel.h.
References __alignment.
Referenced by bind(), insertion_gateway(), is_bound(), is_waiting(), mappedChannel::mappedChannel(), Timeline::schedule(), unbind(), unwaitOn(), and waitOn().
 { return __alignment; }
void InChannel::waitOn ()
waitOn() may be called by an executing Process, in which case that process is attached to the InChannel.
It is automatically dis-attached after completing the activation.
Definition at line 95 of file inchannel.cc.
References add_process(), and alignment().
{
         // timeline has pointer to the currently running process
         //  Register that Process on the InChannel's waiting list.  The priority
         //  for activation is the processes' priority
         assert( alignment()->get_running_proc() != NULL);
         add_process( alignment()->get_running_proc() );
 }
void InChannel::waitOn (Process * proc)
The named Process is attached to the InChannel to be activated on the next Activation to arrive.
It is automatically dis-attached after completing the activation. Unlike the original SSF, there are no assumed or implied suspension semantics. Control is returned from the waitOn call and the calling process may go on to do other things.
Definition at line 103 of file inchannel.cc.
References add_process().
{
         //  Register *proc on the InChannel's waiting list.  The priority
         //  for activation is *proc's own priority
         add_process( proc );
 }
bool InChannel::unwaitOn (Process * proc)
UnwaitOn disconnects the named process from the InChannel list.
Returning true if the Process was found and removed, false otherwise. Unlike the original SSF, there are no assumed or implied suspension semantics. Control is returned from the waitOn call and the calling process may go on to do other things.
Definition at line 253 of file inchannel.cc.
References __waitingList.
{
         // loop over the InChannel's waiting list
         for(std::list<ProcessPri>::iterator list_iter = __waitingList.begin();
                         list_iter != __waitingList.end(); list_iter++) {
                 // is the current element associated with the named Process, and is it
                 // bound?
                 if( proc == (*list_iter).get_proc() && !(*list_iter).get_bound() ) {
                         // yes, remove it from the list and return true
                         __waitingList.erase(list_iter);
                         return true;
                 }
         }
         return false;
 }
bool InChannel::unwaitOn ()
UnwaitOn disconnects the current running process from the InChannel list.
Returning true if the Process was found and removed, false otherwise.
Definition at line 271 of file inchannel.cc.
References alignment(), and Timeline::get_running_proc().
{
         Process *proc = alignment()->get_running_proc();
         assert( proc != NULL);
         return unwaitOn( proc );
 }
void InChannel::bind ()
The named Process is attached to the InChannel to be activated on the next Activation to arrive.
It remains attached after an process activation.
Definition at line 197 of file inchannel.cc.
References alignment(), Timeline::get_running_proc(), insertion_gateway(), and Process::pri().
                       {
         Process* proc = alignment()->get_running_proc();
         // have to check that there is actually a running process now,
         // throw a fatal error if there is not
         assert( proc != NULL);
         insertion_gateway( proc, true, proc->pri());
 }
void InChannel::bind (Process * proc)
bind() may be called by an executing Process, in which case that process is attached to the InChannel.
It remains attached after an process activation.
Definition at line 193 of file inchannel.cc.
References insertion_gateway(), and Process::pri().
{
         insertion_gateway( proc, true, proc->pri());
 }
bool InChannel::unbind (Process * proc)
Removes the named Process from the list of Processes attached to the InChannel.
True returned if the Process found and removed, false otherwise.
Definition at line 217 of file inchannel.cc.
References __waitingList.
{
         // loop over the InChannel's waiting list
         for(std::list<ProcessPri>::iterator list_iter = __waitingList.begin();
                         list_iter != __waitingList.end(); list_iter++) {
                 // is the current element associated with the named Process, and is it
                 // bound?
                 if( proc == (*list_iter).get_proc() && (*list_iter).get_bound() ) {
                         // yes, remove it from the list and return true
                         __waitingList.erase(list_iter);
                         return true;
                 }
         }
         // didn't find it so return false
         return false;
 }
bool InChannel::unbind ()
Removes the running Process from the list of Processes attached to the InChannel.
True returned if the Process found and removed, false otherwise.
Definition at line 236 of file inchannel.cc.
References alignment(), and Timeline::get_running_proc().
{
         Process *proc = alignment()->get_running_proc();
         assert( proc != NULL);
         return unbind( proc );
 }
bool InChannel::is_waiting (Process * proc)
Returns true if the named Process is attached to the InChannel but not bound to it.
Definition at line 323 of file inchannel.cc.
References __waitingList.
{
         bool ans = false;
         // scan entire list
         for(std::list<ProcessPri>::iterator list_iter = __waitingList.begin();
                         list_iter != __waitingList.end(); list_iter++) {
                 // return true if we match the process and the entry is not bound
                 if( proc == (*list_iter).get_proc() && !(*list_iter).get_bound() )
                 { ans = true;
                 break;
                 };
         }
         return ans;
 }
bool InChannel::is_waiting ()
Returns true if the running Process is attached to the InChannel but not bound to it.
Definition at line 340 of file inchannel.cc.
References alignment(), and Timeline::get_running_proc().
{
         Process *proc = alignment()->get_running_proc();
         assert( proc != NULL);
         return is_waiting( proc );
 }
bool InChannel::is_bound (Process * proc)
Returns true if the named Process is bound to the InChannel.
Definition at line 289 of file inchannel.cc.
References __waitingList.
{
         bool ans = false;
         // scan entire list
         for(std::list<ProcessPri>::iterator list_iter = __waitingList.begin();
                         list_iter != __waitingList.end(); list_iter++) {
                 // return true if we found the same process, and it is bound
                 if ( proc == (*list_iter).get_proc()
                                 && (*list_iter).get_bound() ) {
                         ans = true;
                         break;
                 }
         }
         return ans;
 }
bool InChannel::is_bound ()
Returns true if the running Process is bound to the InChannel.
Definition at line 307 of file inchannel.cc.
References alignment(), and Timeline::get_running_proc().
{
         Process *proc = alignment()->get_running_proc();
         assert( proc != NULL);
         return is_bound( proc );
 }
unsigned int InChannel::s3fid () inline
Returns the unique id assigned to this InChannel.
Definition at line 110 of file inchannel.h.
References __s3fid.
Referenced by s3f::s3fnet::Host::listen(), and ~InChannel().
 { return __s3fid; }
bool InChannel::is_ve_attached () inline
Whether the inchannel belongs to an entity host which is an openvz-based VE.
Definition at line 112 of file inchannel.h.
References __ve_attached.
Referenced by Timeline::get_cross_timeline_events(), Timeline::schedule(), and Timeline::sync_window().
 { return __ve_attached; }
void InChannel::set_ve_attached (bool v) inline
Set the attribute to indicate whether the inchannel belongs to an entity host which is an openvz-based VE.
Definition at line 114 of file inchannel.h.
References __ve_attached.
Referenced by s3f::s3fnet::NetworkInterface::config().
 { __ve_attached = v; }
void InChannel::add_process (Process * proc) protected
add_process is called by the two versions of waitOn to attach the named Process, but not bind it.
If the process is already attached—an error—the request is ignored.
Definition at line 177 of file inchannel.cc.
References insertion_gateway(), and Process::pri().
Referenced by waitOn().
{
         insertion_gateway( proc, false, proc->pri() );
 }
void InChannel::insertion_gateway (Process * proc, bool b, unsigned int pri) protected
check alignment, and then see if the timeline's active channel is in fact this one.
Definition at line 131 of file inchannel.cc.
References Process::alignment(), alignment(), Timeline::get_activeChannel(), insert_process_pri(), Timeline::schedule(), and user_pri.
Referenced by add_process(), and bind().
{
         assert( alignment() == proc->alignment() );
         // if the timeline's activeChannel is not this inChannel we can go ahead
         // and implement it
         if( alignment()->get_activeChannel() != this ) {
                 insert_process_pri( proc, b, user_pri(pri) );
         } else {
                 // we have to avoid an infinite loop, so instead schedule an event
                 // to do this insertion, to occur next after the present event processing finishes
                 alignment()->schedule(this, proc, b, user_pri(pri) );
         }
 }
void InChannel::insert_process_pri (Process * proc, bool b, unsigned int pri) protected
insert_process_pri is called both as a result of calling waitOn and as a result of calling bind.
The ProcessPri structure has all the information needed to activate the Process, holds whether the Process is bound or not, and has the priority used to sequence of activations of Processes that are attached to the same InChannel.
Called to put a description of a Process to activate in the InChannel's list of such. The ProcessPri structure identifies the Process's owner (needed because the Process code body is an Entity method), the Process code body, whether the association persists (bound) after an activation, and the priority on the list.
The method does a linear insertion into the list, placing the element immediately before the first entry it encounters (scanning by increasing priority) with a priority that is strictly larger. This implies that insertions with the same priority are ordered FCFS among themselves.
Definition at line 146 of file inchannel.cc.
References __waitingList, and ProcessPri::get_pri().
Referenced by insertion_gateway(), and Timeline::sync_window().
{
         ProcessPri pp(proc, b, pri);
         for(std::list<ProcessPri>::iterator list_iter = __waitingList.begin();
                         list_iter != __waitingList.end(); list_iter++) {
                 // insert pp if the element currently viewed has a priority
                 // that is strictly larger than pp's
                 //
                 if( (*list_iter).get_pri() > pp.get_pri()) {
                         __waitingList.insert(list_iter, pp);
                         return;
                 }
         }
         // hit the end of the list, which means there is no existing element
         // with a strictly larger priority, so that this one goes at the end
         __waitingList.push_back( pp );
         return;
 }
Member Data Documentation
list<ProcessPri> InChannel::__waitingList protected
Ordered list of processes attached to the InChannel, awaiting activation.
List is sorted low to high by the priority field in the ProcessPri structure
Definition at line 160 of file inchannel.h.
Referenced by insert_process_pri(), is_bound(), is_waiting(), Timeline::sync_window(), unbind(), and unwaitOn().
string InChannel::__extname protected
name of the inchannel (if apply)
Definition at line 162 of file inchannel.h.
Entity* InChannel::__owner protected
owner of the channel
Definition at line 163 of file inchannel.h.
Referenced by owner().
Timeline* InChannel::__alignment protected
timeline of the entity that owns this InChannel
Definition at line 164 of file inchannel.h.
Referenced by alignment().
unsigned int InChannel::__s3fid protected
unique id
Definition at line 165 of file inchannel.h.
Referenced by InChannel(), and s3fid().
bool InChannel::__ve_attached protected
whether the inchannel belongs to a VE-proxy entity
Definition at line 166 of file inchannel.h.
Referenced by is_ve_attached(), and set_ve_attached().
pthread_mutex_t InChannel::inchannel_class_mutex static protected
mutex protects access to __num_inchannels
Definition at line 174 of file inchannel.h.
Referenced by InChannel(), Interface::Interface(), and ~InChannel().
unsigned int InChannel::__num_inchannels = 0 static protected
enumerate the number of inchannels we have created
Definition at line 177 of file inchannel.h.
Referenced by InChannel().
The documentation for this class was generated from the following files:
inchannel.h
inchannel.cc