S3F: s3f::s3fnet::IPMessage Class Reference
s3f::s3fnet::IPMessage Class Reference
IP header.
#include <ip_message.h>
Public Member Functions
IPMessage ()
The default constructor (without any argument).
IPMessage (IPADDR src, IPADDR dest, uint8 protono, uint8 live)
The constructor with set fields.
IPMessage (IPADDR src, IPADDR dest, uint8 protono, uint8 live, uint16 id, uint8 tos_ip, uint8 flags_ip, uint16 fragmentOffset_ip, uint16 total_length_ip)
IPMessage (const IPMessage &iphdr)
The copy constructor.
virtual ProtocolMessage * clone ()
Clone the protocol message.
virtual int type ()
Return the protocol number that the message is representing.
virtual int packingSize ()
This method returns the number of bytes that are needed to pack this IP header.
virtual int realByteCount ()
Return the number of bytes that a IP header really occupies in the real world, even though we might not actually allocating the buffer with this size in simulation.
void carryPayload (ProtocolMessage *payload)
This method appends another protocol message to this protocol message and treats it as the payload.
virtual ProtocolMessage * dropPayload ()
If there is a payload, drop it from the linked list, then return it.
ProtocolMessage * payload ()
Returns the next header.
virtual void erase ()
This method is called to release the memory of this packet and its subsequent payload.
virtual void erase_all ()
int totalPackingSize ()
Returns the total byte count (in simulation) including the payload.
int totalRealBytes ()
Returns the total number of bytes of the protocol message including the payload in the real-world.
ProtocolMessage * getMessageByType (int type_code)
Given a protocol message type code, this method goes through the message chain starting from this message, and returns the first ProtocolMessage that has this type code.
unsigned int get_type ()
void inc_evts ()
int dec_evts ()
Static Public Member Functions
static int registerMessage (ProtocolMessage *(*fct)(), int type)
Called by S3FNET_REGISTER_MESSAGE macro to register a protocol message.
Public Attributes
IPADDR src_ip
Source ip address.
IPADDR dst_ip
Destination ip address.
uint8 protocol_no
Protocol identifier for the protocol above IP.
uint8 time_to_live
Number of hops before the protocol message is dropped.
uint16 identification
uint8 tos
uint8 flags
uint16 fragmentOffset
uint16 total_length
Static Public Attributes
static S3FNET_INT2PTR_MAP * registered_messages = 0
A mapping between message type and message constructor.
Protected Member Functions
virtual ~IPMessage ()
The destructor is protected from accidental invocation.
Protected Attributes
unsigned int __type
int __evts
Detailed Description
IP header.
Definition at line 24 of file ip_message.h.
Constructor & Destructor Documentation
s3f::s3fnet::IPMessage::IPMessage ()
The default constructor (without any argument).
Definition at line 14 of file ip_message.cc.
Referenced by clone().
                      : src_ip(IPADDR_INVALID), dst_ip(IPADDR_INVALID), protocol_no(0),
         time_to_live(0), identification(0), tos(0), flags(0), fragmentOffset(0), total_length(S3FNET_IPHDR_LENGTH){}
s3f::s3fnet::IPMessage::IPMessage (IPADDR src, IPADDR dest, uint8 protono, uint8 live)
The constructor with set fields.
Definition at line 17 of file ip_message.cc.
                                                                        :
         src_ip(src), dst_ip(dest), protocol_no(protono), time_to_live(live), identification(0),
         tos(0), flags(0), fragmentOffset(0), total_length(S3FNET_IPHDR_LENGTH){}
s3f::s3fnet::IPMessage::IPMessage (IPADDR src, IPADDR dest, uint8 protono, uint8 live, uint16 id, uint8 tos_ip, uint8 flags_ip, uint16 fragmentOffset_ip, uint16 total_length_ip)
Definition at line 21 of file ip_message.cc.
                                                                           :
         src_ip(src), dst_ip(dest), protocol_no(protono), time_to_live(live), identification(id), tos(tos_ip),
         flags(flags_ip), fragmentOffset(fragmentOffset_ip), total_length(total_length_ip){}
s3f::s3fnet::IPMessage::IPMessage (const IPMessage & iphdr)
The copy constructor.
Definition at line 26 of file ip_message.cc.
                                          :
   ProtocolMessage(iph), // important!!!
   src_ip(iph.src_ip), dst_ip(iph.dst_ip),
   protocol_no(iph.protocol_no), time_to_live(iph.time_to_live),
   identification(iph.identification), tos(iph.tos),
   flags(iph.flags), fragmentOffset(iph.fragmentOffset),
   total_length(iph.total_length)
 {}
s3f::s3fnet::IPMessage::~IPMessage () protected virtual
The destructor is protected from accidental invocation.
Definition at line 41 of file ip_message.cc.
 {}
Member Function Documentation
ProtocolMessage * s3f::s3fnet::IPMessage::clone () virtual
Clone the protocol message.
Implements s3f::s3fnet::ProtocolMessage.
Definition at line 35 of file ip_message.cc.
References IPMessage().
 {
   //printf("IPMessage cloned()\n");
   return new IPMessage(*this);
 }
virtual int s3f::s3fnet::IPMessage::type () inline virtual
Return the protocol number that the message is representing.
Implements s3f::s3fnet::ProtocolMessage.
Definition at line 41 of file ip_message.h.
References s3f::s3fnet::S3FNET_PROTOCOL_TYPE_IPV4.
 { return S3FNET_PROTOCOL_TYPE_IPV4; }
virtual int s3f::s3fnet::IPMessage::packingSize () inline virtual
This method returns the number of bytes that are needed to pack this IP header.
This is for serialization.
Reimplemented from s3f::s3fnet::ProtocolMessage.
Definition at line 47 of file ip_message.h.
References s3f::s3fnet::ProtocolMessage::packingSize(), and S3FNET_IPHDR_LENGTH.
   {
     //return 2*sizeof(IPADDR)+2*sizeof(uint8)+ProtocolMessage::packingSize();
     return S3FNET_IPHDR_LENGTH + ProtocolMessage::packingSize();
   }
virtual int s3f::s3fnet::IPMessage::realByteCount () inline virtual
Return the number of bytes that a IP header really occupies in the real world, even though we might not actually allocating the buffer with this size in simulation.
Implements s3f::s3fnet::ProtocolMessage.
Definition at line 59 of file ip_message.h.
References S3FNET_IPHDR_LENGTH.
 { return S3FNET_IPHDR_LENGTH; }
int s3f::s3fnet::ProtocolMessage::registerMessage (ProtocolMessage *(*)() fct, int type) static inherited
Called by S3FNET_REGISTER_MESSAGE macro to register a protocol message.
Definition at line 96 of file protocol_message.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolMessage::registered_messages, and S3FNET_MAKE_PAIR.
 {
   // allocate the global data structure if it's not there
   if(!registered_messages)
   {
     registered_messages = new S3FNET_INT2PTR_MAP;
     assert(registered_messages);
   }
   // insert the mapping; check if duplicated
   if(!registered_messages->insert(S3FNET_MAKE_PAIR(type, (void*)fct)).second)
     error_quit("ERROR: duplicate protocol message types: %d\n", type);
   // we need to return something so that S3FNET_REGISTER_MESSAGE macro works
   return 0;
 }
void s3f::s3fnet::ProtocolMessage::carryPayload (ProtocolMessage * payload) inherited
This method appends another protocol message to this protocol message and treats it as the payload.
Definition at line 27 of file protocol_message.cc.
References s3f::s3fnet::error_retn(), and s3f::s3fnet::ProtocolMessage::next.
Referenced by s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::send(), and s3f::s3fnet::TCPSession::send_data().
 {
   // adjust the links, warning if found dangling nodes
   if(next)
   {
     error_retn("WARNING: ProtocolMessage::carryPayload(), overwrite pre-exist payload (may cause memory leak)!\n");
     delete next;
   }
   next = load;
 }
ProtocolMessage * s3f::s3fnet::ProtocolMessage::dropPayload () virtual inherited
If there is a payload, drop it from the linked list, then return it.
Return NULL if there is no payload.
Definition at line 38 of file protocol_message.cc.
References s3f::s3fnet::ProtocolMessage::next.
Referenced by s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::SimpleMac::pop(), and s3f::s3fnet::UDPSession::receive().
 {
   // sever the link between this node and the payload and return it
   ProtocolMessage* pmsg = next;
   next = 0;
   return pmsg;
 }
ProtocolMessage* s3f::s3fnet::ProtocolMessage::payload () inline inherited
Returns the next header.
Definition at line 103 of file protocol_message.h.
References s3f::s3fnet::ProtocolMessage::next.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::BufferFromPacket(), s3f::s3fnet::DataMessage::DataMessage(), s3f::s3fnet::NetworkInterface::emu_packet_modify_iface(), s3f::s3fnet::DataMessage::packingSize(), s3f::s3fnet::DataMessage::realByteCount(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::TCPSession::receiver_recv_sack(), and s3f::s3fnet::DataMessage::~DataMessage().
 { return next; }
void s3f::s3fnet::ProtocolMessage::erase () virtual inherited
This method is called to release the memory of this packet and its subsequent payload.
One must avoid deleting a protocol message object directly. This requirement is necessary for the support to optimizations such as the reference counter.
For better protection, the destructor of the protocol message (and its extended classes) should be defined as protected.
Reimplemented from Message.
Definition at line 46 of file protocol_message.cc.
Referenced by s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::OpenFlowSwitchSession::HandleControlInput(), and s3f::s3fnet::SimpleMac::pop().
 {
   //printf("ProtocolMessage erased, type = %d\n", this->type());
   delete this;
 }
void s3f::s3fnet::ProtocolMessage::erase_all () virtual inherited
Reimplemented from Message.
Definition at line 52 of file protocol_message.cc.
References s3f::s3fnet::ProtocolMessage::erase_all(), and s3f::s3fnet::ProtocolMessage::next.
Referenced by s3f::s3fnet::ProtocolMessage::erase_all(), s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::IPSession::handle_pop_pkt(), and s3f::s3fnet::DummySession::pop().
 {
         if(this->next) this->next->erase_all();
     //printf("ProtocolMessage deleted, type = %d\n", this->type());
         delete this;
 }
int s3f::s3fnet::ProtocolMessage::totalPackingSize () inherited
Returns the total byte count (in simulation) including the payload.
Definition at line 60 of file protocol_message.cc.
References s3f::s3fnet::ProtocolMessage::next, s3f::s3fnet::ProtocolMessage::packingSize(), and s3f::s3fnet::ProtocolMessage::totalPackingSize().
Referenced by s3f::s3fnet::ProtocolMessage::totalPackingSize().
 {
   // add them all
   if(next)
           return packingSize()+next->totalPackingSize();
   else
           return packingSize();
 }
int s3f::s3fnet::ProtocolMessage::totalRealBytes () inherited
Returns the total number of bytes of the protocol message including the payload in the real-world.
Definition at line 74 of file protocol_message.cc.
References s3f::s3fnet::ProtocolMessage::next, s3f::s3fnet::ProtocolMessage::realByteCount(), and s3f::s3fnet::ProtocolMessage::totalRealBytes().
Referenced by s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::IPSession::push(), and s3f::s3fnet::ProtocolMessage::totalRealBytes().
 {
   // add them all
   if(next)
           return realByteCount()+next->totalRealBytes();
   else
           return realByteCount();
 }
ProtocolMessage * s3f::s3fnet::ProtocolMessage::getMessageByType (int type_code) inherited
Given a protocol message type code, this method goes through the message chain starting from this message, and returns the first ProtocolMessage that has this type code.
If none is found, NULL is returned.
Definition at line 83 of file protocol_message.cc.
References s3f::s3fnet::ProtocolMessage::next, and s3f::s3fnet::ProtocolMessage::type().
 {
   ProtocolMessage* cur = this;
   while(cur)
   {
     if(cur->type() == t) return cur;
     cur = cur->next;
   }
   return 0;
 }
unsigned int Message::get_type () inline inherited
Definition at line 23 of file message.h.
References Message::__type.
 { return __type; }
void Message::inc_evts () inline inherited
Definition at line 28 of file message.h.
References Message::__evts.
Referenced by Event::Event().
 { __evts++; }
int Message::dec_evts () inline inherited
Definition at line 29 of file message.h.
References Message::__evts.
Referenced by Event::~Event().
 { return --__evts; }
Member Data Documentation
IPADDR s3f::s3fnet::IPMessage::src_ip
Source ip address.
Definition at line 62 of file ip_message.h.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::BufferFromPacket(), s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::IPSession::handle_pop_pkt(), and s3f::s3fnet::IPSession::push().
IPADDR s3f::s3fnet::IPMessage::dst_ip
Destination ip address.
Definition at line 65 of file ip_message.h.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::BufferFromPacket(), s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::IPSession::handle_pop_pkt(), and s3f::s3fnet::IPSession::push().
uint8 s3f::s3fnet::IPMessage::protocol_no
Protocol identifier for the protocol above IP.
Definition at line 68 of file ip_message.h.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::BufferFromPacket(), s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::IPSession::handle_pop_pkt(), and s3f::s3fnet::SimpleMac::pop().
uint8 s3f::s3fnet::IPMessage::time_to_live
Number of hops before the protocol message is dropped.
Definition at line 71 of file ip_message.h.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::BufferFromPacket(), s3f::s3fnet::IPSession::handle_pop_local_pkt(), and s3f::s3fnet::IPSession::handle_pop_pkt().
uint16 s3f::s3fnet::IPMessage::identification
Definition at line 73 of file ip_message.h.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::BufferFromPacket().
uint8 s3f::s3fnet::IPMessage::tos
Definition at line 74 of file ip_message.h.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::BufferFromPacket().
uint8 s3f::s3fnet::IPMessage::flags
Definition at line 75 of file ip_message.h.
uint16 s3f::s3fnet::IPMessage::fragmentOffset
Definition at line 76 of file ip_message.h.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::BufferFromPacket().
uint16 s3f::s3fnet::IPMessage::total_length
Definition at line 77 of file ip_message.h.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::BufferFromPacket().
S3FNET_INT2PTR_MAP * s3f::s3fnet::ProtocolMessage::registered_messages = 0 static inherited
A mapping between message type and message constructor.
Definition at line 158 of file protocol_message.h.
Referenced by s3f::s3fnet::ProtocolMessage::registerMessage().
unsigned int Message::__type protected inherited
Definition at line 31 of file message.h.
Referenced by Message::clone(), Message::get_type(), Message::Message(), and Message::operator=().
int Message::__evts protected inherited
Definition at line 32 of file message.h.
Referenced by Message::clone(), Message::dec_evts(), Message::inc_evts(), Message::Message(), and Message::operator=().
The documentation for this class was generated from the following files:
ip_message.h
ip_message.cc