S3F: s3f::s3fnet::SimplePhy Class Reference
s3f::s3fnet::SimplePhy Class Reference
A simple PHY layer protocol.
#include <simple_phy.h>
Public Types
enum InstantiationType { PROT_UNIQUE_INSTANCE = 0x00, PROT_MULTIPLE_INSTANCES = 0x01, PROT_MULTIPLE_IMPLEMENTATIONS = 0x02 }
Multiple protocol session instantiation type.
enum ExecutionStage { PSESS_CREATED = 0, PSESS_CONFIGURED = 1, PSESS_INITIALIZED = 2, PSESS_WRAPPED_UP = 3 }
A normal protocol session must go though the following stages.
Public Member Functions
SimplePhy (ProtocolGraph *graph)
The constructor.
virtual ~SimplePhy ()
The destructor.
virtual void config (s3f::dml::Configuration *cfg)
Configurate this protocol layer.
virtual void init ()
Initialize the protocol layer.
virtual int getProtocolNumber ()
Return the protocol number.
virtual int control (int ctrltyp, void *ctrlmsg, ProtocolSession *sess)
Handle control messages.
void sendPacket (Activation pkt, ltime_t delay)
Send out a packet.
void receivePacket (Activation pkt, int nw_iface=0)
Receive a packet.
double getBitrate ()
NetworkInterface * getNetworkInterface ()
Return a pointer to the owner interface.
virtual Host * inHost ()
Return a pointer to the host owning this protocol session.
virtual void wrapup ()
The method is used to wrap up the protocol session.
int pushdown (Activation msg, ProtocolSession *hi_sess, void *extinfo=0, size_t extinfo_size=0)
The original push method is divided into pushdown() and push().
int popup (Activation msg, ProtocolSession *lo_sess, void *extinfo=0, size_t extinfo_size=0)
The original pop method is divided into popup() and pop().
ProtocolGraph * inGraph ()
The method returns the protocol graph in which this protocol session resides.
Random::RNG * getRandom ()
The method returns a pointer to the random number generator.
ltime_t getNow ()
The method returns the current simulation time.
char * getNowWithThousandSeparator ()
For printing the current simulation time in a better readable format.
int configured ()
This method returns true if the protocol session has been configured.
int initialized ()
This method returns true if the protocol session has been initialized.
int wrapped_up ()
This method returns true if the protocol session has been wrapped up.
virtual const char * psesstype ()
Public Attributes
char * name
Symbolic name of the protocol this session implements.
float version
Version number of this protocol implemenntation, represented as a floating point number (e.g., 1.23).
char * use
Name of the protocol class from which this protocol session is instantiated.
Protected Member Functions
virtual int instantiation_type ()
This method controls how protocol instances can coexist with one another.
Protected Attributes
double bitrate
The physical bandwidth of the link this NIC is attached to.
long bufsize
The buffer size of this NIC.
ltime_t latency
This is the latency of the NIC itself.
float jitter_range
The jitter range of the NIC.
NicQueue * buffer
The nic queue for outgoing packets.
ProtocolSession * parent_prot
The pointer to the upper layer.
ProtocolSession * child_prot
The pointer to the lower protocol session.
ProtocolGraph * ingraph
Points to the protocol graph.
Random::RNG * sess_rng
Pointer to a random number generator.
int stage
This variable indicates the current stage of this protocol session.
Private Member Functions
virtual int push (Activation pkt, ProtocolSession *hi_sess, void *extinfo, size_t extinfo_size=0)
A packet to be sent is pushed down from the protocol stack from the upper layer.
Detailed Description
A simple PHY layer protocol.
The layer below MAC in a NIC. Essentially, it bridges the associated nic queue and the upper layers in the host. For example, a packet from the upper layer will be turned in to the nic queue to calculate the queueing delay. In addition, a received packet will be submitted to the upper layer through this protocol layer. This layer derives from the LowestProtocolSession class.
Definition at line 31 of file simple_phy.h.
Member Enumeration Documentation
enum s3f::s3fnet::ProtocolSession::InstantiationType inherited
Multiple protocol session instantiation type.
Enumerator
PROT_UNIQUE_INSTANCE
PROT_MULTIPLE_INSTANCES
PROT_MULTIPLE_IMPLEMENTATIONS
Definition at line 44 of file protocol_session.h.
{
     PROT_UNIQUE_INSTANCE                = 0x00,
     PROT_MULTIPLE_INSTANCES             = 0x01,
     PROT_MULTIPLE_IMPLEMENTATIONS       = 0x02
   };
enum s3f::s3fnet::ProtocolSession::ExecutionStage inherited
A normal protocol session must go though the following stages.
Enumerator
PSESS_CREATED
this protocol session has just been created
PSESS_CONFIGURED
the config method of this protocol session has been called
PSESS_INITIALIZED
the init method of this protocol session has been called
PSESS_WRAPPED_UP
Definition at line 51 of file protocol_session.h.
                       {
     PSESS_CREATED       = 0,
     PSESS_CONFIGURED    = 1,
     PSESS_INITIALIZED   = 2,
     PSESS_WRAPPED_UP    = 3
   };
Constructor & Destructor Documentation
s3f::s3fnet::SimplePhy::SimplePhy (ProtocolGraph * graph)
The constructor.
Definition at line 28 of file simple_phy.cc.
References s3f::s3fnet::ProtocolSession::inGraph(), and SPHY_DUMP.
                                          :
   LowestProtocolSession(graph), bitrate(0), bufsize(0), latency(0), jitter_range(0), buffer(0)
 {
   SPHY_DUMP(printf("[nic=\"%s\"] new simple_phy session.\n", ((NetworkInterface*)inGraph())->nhi.toString()));
 }
s3f::s3fnet::SimplePhy::~SimplePhy () virtual
The destructor.
Definition at line 34 of file simple_phy.cc.
References buffer, s3f::s3fnet::ProtocolSession::inGraph(), and SPHY_DUMP.
 {
   SPHY_DUMP(printf("[nic=\"%s\"] delete simple_phy session.\n", ((NetworkInterface*)inGraph())->nhi.toString()));
   if(buffer) delete buffer;
 }
Member Function Documentation
void s3f::s3fnet::SimplePhy::config (s3f::dml::Configuration * cfg) virtual
Configurate this protocol layer.
The configuration includes reading buffer size, bandwidth, and latency, as well as the nic queue attribute (such as the type of nic queue one uses in this network interface.
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 40 of file simple_phy.cc.
References bitrate, buffer, bufsize, s3f::s3fnet::NicQueue::config(), s3f::s3fnet::ProtocolSession::config(), Entity::d2t(), DEFAULT_BUFFER_SIZE, s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolSession::inGraph(), s3f::s3fnet::NicProtocolSession::inHost(), jitter_range, latency, s3f::s3fnet::NicQueues::newNicQueueInstance(), and SPHY_DUMP.
 {
   SPHY_DUMP(printf("[nic=\"%s\"] config().\n", ((NetworkInterface*)inGraph())->nhi.toString()));
   LowestProtocolSession::config(cfg);
   // obtain the bandwidth for this nic
   char* bitrate_string = (char*)cfg->findSingle("bitrate");
   if(0 != bitrate_string && !s3f::dml::dmlConfig::isConf(bitrate_string))
   {
     bitrate = atof(bitrate_string);
     if(bitrate < 0)
     {
       error_quit("ERROR: SimplePhy::config(), negative bit rate.\n");
     }
   }
   else error_quit("ERROR: SimplePhy::config(), missing BITRATE attribute.\n");
   // obtain the latency for this nic
   char* latency_string = (char*)cfg->findSingle("latency");
   if(0 != latency_string)
   {
     if(s3f::dml::dmlConfig::isConf(latency_string))
     {
       error_quit("ERROR: SimplyPhy::config(), illegal LATENCY attribute.\n");
     }
     double latency_double = atof(latency_string);
     latency = inHost()->d2t(latency_double, 0);
     if(latency < 0)
     {
       error_quit("ERROR: SimplePhy::config(), negative latency.\n");
     }
   }
   // obtain the jitter range for this nic
   char* jitter_range_string = (char*)cfg->findSingle("jitter_range");
   if(0 != jitter_range_string)
   {
     if(s3f::dml::dmlConfig::isConf(jitter_range_string))
     {
       error_quit("ERROR: SimplyPhy::config(), illegal JITTER_RANGE attribute.\n");
     }
     jitter_range = (float)atof(jitter_range_string);
     if(jitter_range < 0 || jitter_range > 1)
     {
       error_quit("ERROR: SimplePhy::config(), illegal jitter range(%f), should be [0, 1]\n", jitter_range);
     }
   }
   // obtain the buffer size
   char* buffer_string = (char*)cfg->findSingle("buffer");
   if(0 != buffer_string)
   {
     if(s3f::dml::dmlConfig::isConf(buffer_string))
     {
       error_quit("ERROR: SimplyPhy::config(), illegal BUFFER attribute.\n");
     }
     bufsize = atol(buffer_string);
     if(bufsize < 0)
     {
       error_quit("ERROR: SimplePhy::config(), negative buffer size (%s).\n", buffer_string);
     }
   }
   else
   {
             bufsize = DEFAULT_BUFFER_SIZE;
   }
   SPHY_DUMP(printf("[nic=\"%s\"] config(): bitrate=%lf, latency=%ld, jitter_range=%f, buffer(size)=%ld.\n",
                    ((NetworkInterface*)inGraph())->nhi.toString(),
                    bitrate, latency, jitter_range, bufsize));
   // obtain the queue type and create the corresponding queue. If the
   // queue has not been indicated, we will use the default mixed
   // queue.
   char* default_queue = "droptail" /*"mixfluid"*/;
   char* queue_string = (char*)cfg->findSingle("queue");
   if(!queue_string) queue_string = default_queue;
   if(s3f::dml::dmlConfig::isConf(queue_string))
     error_quit("ERROR: SimplePhy::config(), illegal QUEUE attribute.\n");
   SPHY_DUMP(printf("[nic=\"%s\"] config(): queue is \"%s\".\n",
                    ((NetworkInterface*)inGraph())->nhi.toString(), queue_string));
   // create a new queue based on the type of the queue
   if(!(buffer = NicQueues::newNicQueueInstance(queue_string, this)))
     error_quit("ERROR: SimplePhy::config(), unable to create nic queue: \"%s\"!\n", queue_string);
   buffer->config(cfg);
 }
void s3f::s3fnet::SimplePhy::init () virtual
Initialize the protocol layer.
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 130 of file simple_phy.cc.
References buffer, s3f::s3fnet::error_quit(), s3f::s3fnet::NicProtocolSession::getNetworkInterface(), s3f::s3fnet::ProtocolSession::inGraph(), s3f::s3fnet::NicQueue::init(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::IPPrefix::ip2txt(), s3f::s3fnet::ProtocolSession::name, PHY_PROTOCOL_NAME, and SPHY_DUMP.
 {
   SPHY_DUMP(printf("[nic=\"%s\", ip=\"%s\"] init().\n",
                    ((NetworkInterface*)inGraph())->nhi.toString(),
                    IPPrefix::ip2txt(getNetworkInterface()->getIP())));
   LowestProtocolSession::init();
   if(strcasecmp(name, PHY_PROTOCOL_NAME))
     error_quit("ERROR: SimplePhy::init(), unmatched protocol name: \"%s\", expecting \"PHY\".\n", name);
   // initialize the buffer itself
   buffer->init();
 }
virtual int s3f::s3fnet::SimplePhy::getProtocolNumber () inline virtual
Return the protocol number.
Implements s3f::s3fnet::ProtocolSession.
Definition at line 51 of file simple_phy.h.
References s3f::s3fnet::S3FNET_PROTOCOL_TYPE_SIMPLE_PHY.
 { return S3FNET_PROTOCOL_TYPE_SIMPLE_PHY; }
int s3f::s3fnet::SimplePhy::control (int ctrltyp, void * ctrlmsg, ProtocolSession * sess) virtual
Handle control messages.
Reimplemented from s3f::s3fnet::LowestProtocolSession.
Definition at line 183 of file simple_phy.cc.
References bitrate, buffer, bufsize, s3f::s3fnet::LowestProtocolSession::control(), s3f::s3fnet::ProtocolSession::inGraph(), jitter_range, latency, s3f::s3fnet::PHY_CTRL_GET_BITRATE, s3f::s3fnet::PHY_CTRL_GET_BUFFER_SIZE, s3f::s3fnet::PHY_CTRL_GET_JITTER_RANGE, s3f::s3fnet::PHY_CTRL_GET_LATENCY, s3f::s3fnet::PHY_CTRL_GET_QUEUE, and SPHY_DUMP.
 {
   SPHY_DUMP(printf("[nic=\"%s\"] control(): type=%d.\n",
                    ((NetworkInterface*)inGraph())->nhi.toString(), ctrltyp));
   switch(ctrltyp) {
   case PHY_CTRL_GET_BITRATE:
     assert(ctrlmsg);
     *((double*)ctrlmsg) = bitrate;
     return 0;
   case PHY_CTRL_GET_BUFFER_SIZE:
     assert(ctrlmsg);
     *((long*)ctrlmsg) = bufsize;
     return 0;
   case PHY_CTRL_GET_JITTER_RANGE:
     assert(ctrlmsg);
     *((float*)ctrlmsg) = jitter_range;
     return 0;
   case PHY_CTRL_GET_LATENCY:
     assert(ctrlmsg);
     *((ltime_t*)ctrlmsg) = latency;
     return 0;
   case PHY_CTRL_GET_QUEUE:
     assert(ctrlmsg);
     *((NicQueue**)ctrlmsg) = buffer;
     return 0;
   default:
     return LowestProtocolSession::control(ctrltyp, ctrlmsg, sess);
   }
 }
void s3f::s3fnet::SimplePhy::sendPacket (Activation pkt, ltime_t delay) virtual
Send out a packet.
Implements s3f::s3fnet::LowestProtocolSession.
Definition at line 158 of file simple_phy.cc.
References s3f::s3fnet::NicProtocolSession::getNetworkInterface(), s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::inGraph(), s3f::s3fnet::IPPrefix::ip2txt(), s3f::s3fnet::NetworkInterface::sendPacket(), and SPHY_DUMP.
 {
   SPHY_DUMP(printf("[nic=\"%s\", ip=\"%s\"] %s: sendPacket(delay=%ld).\n",
                    ((NetworkInterface*)inGraph())->nhi.toString(),
                IPPrefix::ip2txt(getNetworkInterface()->getIP()), getNowWithThousandSeparator(), delay));
   getNetworkInterface()->sendPacket(pkt, delay);
 }
void s3f::s3fnet::SimplePhy::receivePacket (Activation pkt, int nw_iface = 0) virtual
Receive a packet.
Implements s3f::s3fnet::LowestProtocolSession.
Definition at line 167 of file simple_phy.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::NicProtocolSession::getNetworkInterface(), s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::inGraph(), s3f::s3fnet::IPPrefix::ip2txt(), s3f::s3fnet::PHYOptionToAbove::nw_iface, s3f::s3fnet::NicProtocolSession::parent_prot, s3f::s3fnet::ProtocolSession::popup(), and SPHY_DUMP.
 {
   SPHY_DUMP(printf("[nic=\"%s\", ip=\"%s\"] %s: receivePacket().\n",
                    ((NetworkInterface*)inGraph())->nhi.toString(),
                    IPPrefix::ip2txt(getNetworkInterface()->getIP()), getNowWithThousandSeparator()));
   if(!parent_prot)
   {
     error_quit("ERROR: SimplePhy()::receivePacket(), no parent protocol session set.\n");
   }
   PHYOptionToAbove phyupopt;
   phyupopt.nw_iface = nw_iface;
   parent_prot->popup(pkt, this, (void*)&phyupopt, sizeof(PHYOptionToAbove));
 }
double s3f::s3fnet::SimplePhy::getBitrate () inline
Definition at line 62 of file simple_phy.h.
References bitrate.
 { return bitrate; }
int s3f::s3fnet::SimplePhy::push (Activation pkt, ProtocolSession * hi_sess, void * extinfo, size_t extinfo_size = 0) private virtual
A packet to be sent is pushed down from the protocol stack from the upper layer.
Here, msg must be NULL and the extinfo parameter carries the packet.
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 145 of file simple_phy.cc.
References buffer, s3f::s3fnet::NicQueue::enqueue(), s3f::s3fnet::NicProtocolSession::getNetworkInterface(), s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::inGraph(), s3f::s3fnet::IPPrefix::ip2txt(), and SPHY_DUMP.
 {
   SPHY_DUMP(printf("[nic=\"%s\", ip=\"%s\"] %s: push(), enqueue packet.\n",
                    ((NetworkInterface*)inGraph())->nhi.toString(),
                    IPPrefix::ip2txt(getNetworkInterface()->getIP()), getNowWithThousandSeparator()));
   assert(pkt);
   assert(buffer);
   buffer->enqueue(pkt);
   return 0;
 }
NetworkInterface * s3f::s3fnet::NicProtocolSession::getNetworkInterface () inherited
Return a pointer to the owner interface.
Definition at line 37 of file nic_protocol_session.cc.
References s3f::s3fnet::ProtocolSession::ingraph.
Referenced by s3f::s3fnet::NicProtocolSession::control(), s3f::s3fnet::NicProtocolSession::inHost(), s3f::s3fnet::SimpleMac::init(), init(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::SimpleMac::push(), push(), receivePacket(), and sendPacket().
 {
   return dynamic_cast<NetworkInterface*>(ingraph);
 }
Host * s3f::s3fnet::NicProtocolSession::inHost () virtual inherited
Return a pointer to the host owning this protocol session.
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 42 of file nic_protocol_session.cc.
References s3f::s3fnet::NetworkInterface::getHost(), and s3f::s3fnet::NicProtocolSession::getNetworkInterface().
Referenced by s3f::s3fnet::DroptailQueue::calibrate(), s3f::s3fnet::RedQueue::calibrate(), config(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::DroptailQueue::init(), s3f::s3fnet::SimpleMac::pop(), and s3f::s3fnet::SimpleMac::push().
 {
   return getNetworkInterface()->getHost();
 }
void s3f::s3fnet::ProtocolSession::wrapup () virtual inherited
The method is used to wrap up the protocol session.
It is called when the simulation finishes. It is designed to give user a chance to report simulation statistics. The default behavior is doing nothing. Subclass may override this method for protocol specific dealings. Note that there is no specific order in which wrapup is called for protocol sessions in a protocol graph.
Definition at line 59 of file protocol_session.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolSession::initialized(), s3f::s3fnet::ProtocolSession::name, s3f::s3fnet::ProtocolSession::PSESS_WRAPPED_UP, s3f::s3fnet::ProtocolSession::stage, and s3f::s3fnet::ProtocolSession::wrapped_up().
 {
   // Make sure this init function at the base class should be called
   // by the derived function!
   if(!initialized())
     error_quit("ERROR: ProtocolSession \"%s\" wrapup() called before init(), "
                "forgot to call base class's init() in your derived class?\n", name);
   else if(wrapped_up())
     error_quit("ERROR: duplicate calls to ProtocolSession::wrapup(): "
                "session name is \"%s\".\n", name);
   else stage = PSESS_WRAPPED_UP;
 }
int s3f::s3fnet::ProtocolSession::pushdown (Activation msg, ProtocolSession * hi_sess, void * extinfo = 0, size_t extinfo_size = 0) inherited
The original push method is divided into pushdown() and push().
The pushdown method is the generic part of the code, which is reserved for modeling the handling of messages transferred between protocol layers.
See Also
ProtocolSession::push method for details.
Definition at line 72 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::push().
Referenced by s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), s3f::s3fnet::IPSession::control(), s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), s3f::s3fnet::OpenFlowSwitchSession::OutputControl(), s3f::s3fnet::OpenFlowSwitchSession::OutputPacket(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::UDPMaster::push(), s3f::s3fnet::TCPMaster::push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::send(), and s3f::s3fnet::TCPSession::send_data().
 {
   return push(msg, hi_sess, extinfo, extinfo_size);
 }
int s3f::s3fnet::ProtocolSession::popup (Activation msg, ProtocolSession * lo_sess, void * extinfo = 0, size_t extinfo_size = 0) inherited
The original pop method is divided into popup() and pop().
The popup method is the generic part of the code, which is reserved for modeling the handling of messages transferred between protocol layers.
See Also
ProtocolSession::pop method for details.
Definition at line 77 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::pop().
Referenced by s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::IPSession::push(), and receivePacket().
 {
   return pop(msg, lo_sess, extinfo, extinfo_size);
 }
ProtocolGraph* s3f::s3fnet::ProtocolSession::inGraph () inline inherited
The method returns the protocol graph in which this protocol session resides.
Definition at line 178 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::ingraph.
Referenced by config(), control(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::SimpleMac::init(), init(), s3f::s3fnet::RedQueue::init(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::SimpleMac::push(), push(), receivePacket(), sendPacket(), s3f::s3fnet::SimpleMac::SimpleMac(), SimplePhy(), s3f::s3fnet::SimpleMac::~SimpleMac(), and ~SimplePhy().
 { return ingraph; }
Random::RNG* s3f::s3fnet::ProtocolSession::getRandom () inline inherited
The method returns a pointer to the random number generator.
Definition at line 200 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::sess_rng.
Referenced by s3f::s3fnet::DroptailQueue::calibrate(), s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::DummySession::init(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), and s3f::s3fnet::NetworkInterface::receivePacket().
 { return sess_rng;}
ltime_t s3f::s3fnet::ProtocolSession::getNow () inherited
The method returns the current simulation time.
To be safe, please do NOT call this function after initialization and before wrapup phase. That is, it is unsafe to call this method in the constructor, destructor, config, init, and wrapup methods. The time service is carried out by the host's owner community. This method just directs the call to the community. It's given here for convenience.
Definition at line 123 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::inHost(), and Entity::now().
Referenced by s3f::s3fnet::DroptailQueue::calibrate(), s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::TCPMaster::enableFastTimeout(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::TCPMaster::fast_timer_callback_body(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::TCPSession::now(), s3f::s3fnet::OpenVZEventSession::pop(), s3f::s3fnet::TCPMaster::slow_timer_callback_body(), s3f::s3fnet::SocketMaster::socket(), s3f::s3fnet::NBSocketMaster::socket(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), and s3f::s3fnet::BTCPClientSession::start_on().
 {
   return inHost()->now();
 }
char * s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator () inherited
For printing the current simulation time in a better readable format.
Definition at line 128 of file protocol_session.cc.
References s3f::s3fnet::Host::getNowWithThousandSeparator(), and s3f::s3fnet::ProtocolSession::inHost().
Referenced by s3f::s3fnet::UDPSession::abort(), s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::UDPSession::connect(), s3f::s3fnet::TCPMaster::createSession(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::UDPServerSession::data_sent(), s3f::s3fnet::TCPServerSession::data_sent(), s3f::s3fnet::UDPSession::disconnect(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::UDPSession::listen(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), s3f::s3fnet::DummySession::pop(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::OpenVZEventSession::pop(), s3f::s3fnet::UDPMaster::pop(), s3f::s3fnet::TCPMaster::pop(), s3f::s3fnet::IPSession::pop(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::UDPMaster::push(), push(), s3f::s3fnet::TCPMaster::push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::receive(), s3f::s3fnet::TCPSession::receive(), receivePacket(), s3f::s3fnet::UDPServerSession::request_received(), s3f::s3fnet::TCPServerSession::request_received(), s3f::s3fnet::UDPClientSession::request_sent(), s3f::s3fnet::TCPClientSession::request_sent(), s3f::s3fnet::UDPSession::send(), s3f::s3fnet::TCPSession::send_data(), sendPacket(), s3f::s3fnet::UDPClientSession::server_connected(), s3f::s3fnet::TCPClientSession::server_connected(), s3f::s3fnet::BTCPClientSession::server_connected(), s3f::s3fnet::UDPServerSession::session_closed(), s3f::s3fnet::UDPClientSession::session_closed(), s3f::s3fnet::TCPClientSession::session_closed(), s3f::s3fnet::TCPServerSession::session_closed(), s3f::s3fnet::BTCPClientSession::session_closed(), s3f::s3fnet::TCPMaster::setConnected(), s3f::s3fnet::TCPMaster::setIdle(), s3f::s3fnet::TCPMaster::setListening(), s3f::s3fnet::UDPSession::setSource(), s3f::s3fnet::TCPSession::slowTimeoutHandling(), s3f::s3fnet::UDPServerSession::start_on(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPServerSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), s3f::s3fnet::BTCPClientSession::start_on(), s3f::s3fnet::TCPSession::TCPSession(), s3f::s3fnet::UDPClientSession::timeout(), s3f::s3fnet::TCPClientSession::timeout(), s3f::s3fnet::BTCPClientSession::timeout(), s3f::s3fnet::UDPSession::UDPSession(), s3f::s3fnet::TCPSession::update_timeout(), and s3f::s3fnet::UDPSession::wake_app().
 {
         return inHost()->getNowWithThousandSeparator();
 }
int s3f::s3fnet::ProtocolSession::configured () inline inherited
This method returns true if the protocol session has been configured.
This method is used to make sure we configure the protocol session before initializing it.
Definition at line 221 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_CONFIGURED, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::config(), and s3f::s3fnet::ProtocolSession::init().
 { return stage >= PSESS_CONFIGURED; }
int s3f::s3fnet::ProtocolSession::initialized () inline inherited
This method returns true if the protocol session has been initialized.
This can be used to sequence calls to the init method of protocol sessions. For example, if protocol session A requires protocol session B to be initialized before A can be initialized, A's init method can call B's init method as long as B's initialized() returns true. The system does not enforce any ordering in its calls the init methods of all protocol sessions declared in the dml configuration.
Definition at line 233 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_INITIALIZED, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::init(), and s3f::s3fnet::ProtocolSession::wrapup().
 { return stage >= PSESS_INITIALIZED; }
int s3f::s3fnet::ProtocolSession::wrapped_up () inline inherited
This method returns true if the protocol session has been wrapped up.
This can be used to sequence calls to the wrapup method of protocol sessions. For example, if protocol session A requires protocol session B to be wrapped up before A can be wrapped up, A's wrapup method can call B's wrapup method as long as B's wrapped_up() returns true. The system does not enforce any ordering in its calls the wrapup methods of all protocol sessions declared in the dml configuration.
Definition at line 245 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_WRAPPED_UP, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::wrapup().
 { return stage >= PSESS_WRAPPED_UP; }
virtual const char* s3f::s3fnet::ProtocolSession::psesstype () inline virtual inherited
Reimplemented in s3f::s3fnet::NBSocketMaster, and s3f::s3fnet::SocketMaster.
Definition at line 247 of file protocol_session.h.
 { return "GENERIC"; } // DEBUG
virtual int s3f::s3fnet::ProtocolSession::instantiation_type () inline protected virtual inherited
This method controls how protocol instances can coexist with one another.
It returns one of the following:
PROT_UNIQUE_INSTANCE (default): allows only one instance for each type of protocol per protocol stack;
PROT_MULTIPLE_INSTANCES: allows multiple instances of the same implementation for each type of protocol per protocol stack;
PROT_MULTIPLE_IMPLEMENTATIONS: allows multiple instances from different implementations of the same protocol to exist on the protocol stack.
Reimplemented in s3f::s3fnet::BTCPClientSession, and s3f::s3fnet::TCPClientSession.
Definition at line 269 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PROT_UNIQUE_INSTANCE.
Referenced by s3f::s3fnet::ProtocolGraph::insert_session().
 { return PROT_UNIQUE_INSTANCE; }
Member Data Documentation
double s3f::s3fnet::SimplePhy::bitrate protected
The physical bandwidth of the link this NIC is attached to.
Definition at line 74 of file simple_phy.h.
Referenced by config(), control(), and getBitrate().
long s3f::s3fnet::SimplePhy::bufsize protected
The buffer size of this NIC.
Definition at line 77 of file simple_phy.h.
Referenced by config(), and control().
ltime_t s3f::s3fnet::SimplePhy::latency protected
This is the latency of the NIC itself.
Definition at line 80 of file simple_phy.h.
Referenced by config(), and control().
float s3f::s3fnet::SimplePhy::jitter_range protected
The jitter range of the NIC.
It should be within [0,1].
Definition at line 83 of file simple_phy.h.
Referenced by config(), and control().
NicQueue* s3f::s3fnet::SimplePhy::buffer protected
The nic queue for outgoing packets.
Definition at line 86 of file simple_phy.h.
Referenced by config(), control(), init(), push(), and ~SimplePhy().
ProtocolSession* s3f::s3fnet::NicProtocolSession::parent_prot protected inherited
The pointer to the upper layer.
Definition at line 44 of file nic_protocol_session.h.
Referenced by s3f::s3fnet::NicProtocolSession::control(), s3f::s3fnet::SimpleMac::pop(), and receivePacket().
ProtocolSession* s3f::s3fnet::NicProtocolSession::child_prot protected inherited
The pointer to the lower protocol session.
Definition at line 47 of file nic_protocol_session.h.
Referenced by s3f::s3fnet::NicProtocolSession::control(), and s3f::s3fnet::SimpleMac::push().
char* s3f::s3fnet::ProtocolSession::name inherited
Symbolic name of the protocol this session implements.
The name of the protocol is derived from the DML 'name' attribute. It must not be NULL once the protocol session is configured.
Definition at line 63 of file protocol_session.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::SimpleMac::init(), s3f::s3fnet::UDPMaster::init(), init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::SocketMaster::init(), s3f::s3fnet::IPSession::init(), s3f::s3fnet::NBSocketMaster::init(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::ProtocolGraph::insert_session(), s3f::s3fnet::ProtocolSession::wrapup(), and s3f::s3fnet::ProtocolSession::~ProtocolSession().
float s3f::s3fnet::ProtocolSession::version inherited
Version number of this protocol implemenntation, represented as a floating point number (e.g., 1.23).
Definition at line 69 of file protocol_session.h.
char* s3f::s3fnet::ProtocolSession::use inherited
Name of the protocol class from which this protocol session is instantiated.
The protocol class must be registered with the Protocols class so that we will be able to instantiate an object from the class. (C++ does not support self-reflection). The class name must not be NULL once the protocol session is configured.
Definition at line 79 of file protocol_session.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::ProtocolGraph::insert_session(), and s3f::s3fnet::ProtocolSession::~ProtocolSession().
ProtocolGraph* s3f::s3fnet::ProtocolSession::ingraph protected inherited
Points to the protocol graph.
Definition at line 335 of file protocol_session.h.
Referenced by s3f::s3fnet::NicProtocolSession::getNetworkInterface(), s3f::s3fnet::ProtocolSession::inGraph(), and s3f::s3fnet::ProtocolSession::inHost().
Random::RNG* s3f::s3fnet::ProtocolSession::sess_rng protected inherited
Pointer to a random number generator.
Definition at line 338 of file protocol_session.h.
Referenced by s3f::s3fnet::ProtocolSession::getRandom(), and s3f::s3fnet::ProtocolSession::init().
int s3f::s3fnet::ProtocolSession::stage protected inherited
This variable indicates the current stage of this protocol session.
Each protocol session will go through four staged: PSESS_CREATED, PSESS_CONFIGURED, PSESS_INITIALIZED, and then PSESS_WRAPPED_UP.
Definition at line 346 of file protocol_session.h.
Referenced by s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::ProtocolSession::configured(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::ProtocolSession::initialized(), s3f::s3fnet::ProtocolSession::wrapped_up(), and s3f::s3fnet::ProtocolSession::wrapup().
The documentation for this class was generated from the following files:
simple_phy.h
simple_phy.cc