S3F: s3f::s3fnet::Nhi Class Reference
s3f::s3fnet::Nhi Class Reference
The NHI address used in DML.
#include <nhi.h>
Public Types
enum { NHI_INTERFACE = 1, NHI_MACHINE = 2, NHI_NET = 4, NHI_INVALID = 8 }
Type of the NHI address.
Public Member Functions
Nhi ()
The constructor.
Nhi (char *str, int type)
The constructor.
Nhi (Nhi &rhs)
The constructor.
virtual ~Nhi ()
The destructor.
Nhi & operator= (Nhi &rhs)
Override the assign operator.
Nhi & operator+= (int id)
Override the += operator.
char * toString (char *buf)
Returns a char array representation of this NHI.
char *const toString ()
The method is the same as the method with the same name except that it uses an internal static buffer.
S3FNET_STRING toStlString ()
Returns an STL string representation of this NHI.
void display ()
Prints out this NHI address to standard output.
int convert (char *str, int type)
Convert from a string representation.
bool contains (Nhi &nhi)
Checks whether this NHI address contains the given NHI.
bool contains (char *nhiAddr)
Checks whether this NHI address contains the given NHI given as a string.
void setRelativeTo (Nhi &parent)
Changes the NHI so that it's given relative to the parameter.
Static Public Member Functions
static int readNhiRange (S3FNET_POINTER_VECTOR &pVector, s3f::dml::Configuration *cfg)
Function to read the contents of an nhi_range attribute into a vector.
Public Attributes
S3FNET_LONG_VECTOR ids
Vector of successive ids.
int start
This is an index into ids.
int type
The type of the NHI address.
Static Private Attributes
static char internal_buf [50]
Friends
bool operator== (Nhi &n1, Nhi &n2)
Override the == operator.
Detailed Description
The NHI address used in DML.
NHI stands for Network Host Interface. This NHI class provides utility functions that process NHI address and handle conversion of NHI addresses to and from character strings.
Definition at line 24 of file nhi.h.
Member Enumeration Documentation
anonymous enum
Type of the NHI address.
Enumerator
NHI_INTERFACE
network interface type
NHI_MACHINE
host or router type
NHI_NET
a sub-network type
NHI_INVALID
invalid type
Definition at line 27 of file nhi.h.
        {
     NHI_INTERFACE       = 1,
     NHI_MACHINE         = 2,
     NHI_NET             = 4,
     NHI_INVALID         = 8
   };
Constructor & Destructor Documentation
s3f::s3fnet::Nhi::Nhi ()
The constructor.
Definition at line 17 of file nhi.cc.
Referenced by readNhiRange().
          : start(0), type(NHI_INVALID)
 {}
s3f::s3fnet::Nhi::Nhi (char * str, int type)
The constructor.
Definition at line 20 of file nhi.cc.
References convert().
                          : start(0), type(NHI_INVALID)
 {
   // convert the string into NHI
   convert(str, t);
 }
s3f::s3fnet::Nhi::Nhi (Nhi & rhs)
The constructor.
Definition at line 26 of file nhi.cc.
 {
   (*this) = rhs;
 }
s3f::s3fnet::Nhi::~Nhi () virtual
The destructor.
Definition at line 31 of file nhi.cc.
References ids.
 { ids.clear(); }
Member Function Documentation
Nhi & s3f::s3fnet::Nhi::operator= (Nhi & rhs)
Override the assign operator.
Definition at line 33 of file nhi.cc.
References ids, start, and type.
 {
   if(this == &rhs)
     return (*this);
   start = rhs.start;
   type = rhs.type;
   ids.clear();
   for(unsigned i=0; i < rhs.ids.size(); i++)
     ids.push_back(rhs.ids[i]);
   return (*this);
 }
Nhi & s3f::s3fnet::Nhi::operator+= (int id)
Override the += operator.
Append an id to the end of the NHI.
Definition at line 47 of file nhi.cc.
References ids.
 {
   ids.push_back(id);
   return (*this);
 }
char * s3f::s3fnet::Nhi::toString (char * buf)
Returns a char array representation of this NHI.
The buffer pointed to by buf MUST have enough storage space.
Definition at line 76 of file nhi.cc.
References ids, NHI_INTERFACE, NHI_INVALID, NHI_MACHINE, NHI_NET, start, and type.
Referenced by s3f::s3fnet::UDPSession::abort(), s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::Host::config(), s3f::s3fnet::RouteInfo::config(), s3f::s3fnet::TrafficPattern::config(), s3f::s3fnet::Net::config(), s3f::s3fnet::Host::config_network_interface(), s3f::s3fnet::UDPSession::connect(), s3f::s3fnet::Net::connect_links(), s3f::s3fnet::UDPSession::disconnect(), s3f::s3fnet::TrafficPattern::display(), s3f::s3fnet::Net::display(), s3f::s3fnet::UDPClientSessionContinuation::failure(), s3f::s3fnet::UDPServerSessionContinuation::failure(), s3f::s3fnet::TCPClientSessionContinuation::failure(), s3f::s3fnet::TCPServerSessionContinuation::failure(), s3f::s3fnet::BTCPClientSessionContinuation::failure(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), s3f::s3fnet::NetworkInterface::init(), s3f::s3fnet::Host::init(), s3f::s3fnet::Net::init(), s3f::s3fnet::UDPSession::listen(), s3f::s3fnet::Host::loadForwardingTable(), s3f::s3fnet::LearningController::process_recv_packet(), readNhiRange(), s3f::s3fnet::UDPSession::receive(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::LearningControllerSession::ReceiveFromSwitch(), s3f::s3fnet::NetworkInterface::receivePacket(), s3f::s3fnet::Net::register_host(), s3f::s3fnet::RouteInfo::resolve(), s3f::s3fnet::DMLRouteInfo::resolve(), s3f::s3fnet::NBTCPClientSessionContinuation::resume(), s3f::s3fnet::NBTCPServerSessionContinuation::resume(), s3f::s3fnet::UDPSession::send(), s3f::s3fnet::TCPSession::send_data(), s3f::s3fnet::NetworkInterface::sendPacket(), setRelativeTo(), s3f::s3fnet::UDPSession::setSource(), s3f::s3fnet::TCPSession::slowTimeoutHandling(), s3f::s3fnet::NBTCPServerSessionContinuation::success(), s3f::s3fnet::TCPSession::TCPSession(), s3f::s3fnet::UDPSession::UDPSession(), s3f::s3fnet::TCPSession::update_timeout(), s3f::s3fnet::UDPSession::wake_app(), s3f::s3fnet::Host::~Host(), s3f::s3fnet::Net::~Net(), and s3f::s3fnet::NetworkInterface::~NetworkInterface().
 {
   unsigned i;
   char* p = buf; *p = '\0';
   int minlength;
   if(type == NHI_INVALID) {
     strcpy(buf, "NHI_INVALID");
     return buf;
   }
   minlength = (type == Nhi::NHI_INTERFACE)?2:1;
   if(ids.size() == 0) {
     buf[0] = '\0';
     return buf;
   }
   for(i=start; i < ids.size() - minlength; i++)
     p += sprintf(p, "%ld:", ids[i]);
   switch (type) {
   case NHI_INTERFACE:
     sprintf(p, "%ld(%ld)", ids[i], ids[i+1]);
     break;
   case NHI_MACHINE:
   case NHI_NET:
     sprintf(p, "%ld", ids[i]);
     break;
   default:
     assert(0);
     break;
   }
   return buf;
 }
char *const s3f::s3fnet::Nhi::toString ()
The method is the same as the method with the same name except that it uses an internal static buffer.
Definition at line 70 of file nhi.cc.
References internal_buf.
Referenced by setRelativeTo(), and toStlString().
 {
   // not a good idea in a multiprocessor environment
   return toString(internal_buf);
 }
S3FNET_STRING s3f::s3fnet::Nhi::toStlString ()
Returns an STL string representation of this NHI.
Definition at line 115 of file nhi.cc.
References toString().
Referenced by s3f::s3fnet::Link::config(), s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), s3f::s3fnet::Link::display(), s3f::s3fnet::Host::getDefaultIP(), s3f::s3fnet::Net::nhi2obj(), and s3f::s3fnet::DMLRouteInfo::resolve().
 {
   char buf[255];
   toString(buf);
   S3FNET_STRING str(buf);
   return str;
 }
void s3f::s3fnet::Nhi::display ()
Prints out this NHI address to standard output.
(Maybe we can make this more generic to any file streams; but the necessity never arised.)
Definition at line 123 of file nhi.cc.
References ids, NHI_INTERFACE, NHI_INVALID, NHI_MACHINE, NHI_NET, start, and type.
 {
   unsigned i;
   int minlength;
   if(type == NHI_INVALID) {
     printf("NHI_INVALID");
     return;
   }
   minlength = (type == Nhi::NHI_INTERFACE)?2:1;
   for(i=start; i < ids.size() - minlength; i++)
     printf("%ld:", ids[i]);
   switch (type) {
   case NHI_INTERFACE:
     printf("%ld(%ld)", ids[i], ids[i+1]);
     break;
   case NHI_MACHINE:
   case NHI_NET:
     printf("%ld", ids[i]);
     break;
   default:
     assert(0);
     break;
   }
 }
int s3f::s3fnet::Nhi::convert (char * str, int type)
Convert from a string representation.
The type specifies what kind of NHI this is so that we can do some error checking. This method return non-zero if the conversion fails.
Definition at line 154 of file nhi.cc.
References ids, NHI_INTERFACE, NHI_INVALID, start, and type.
Referenced by s3f::s3fnet::TrafficPattern::config(), s3f::s3fnet::TrafficPattern::configure_servers(), Nhi(), and readNhiRange().
 {
   char* p = str, *q;
   while((q = strchr(p, ':'))) {
     *q = '\0';
     ids.push_back(atoi(p));
     *q = ':';
     p = ++q;
   }
   // At this point p must point to a string of the form 2(1)
   // If we just have 2, this is a machine NHI or a Net NHI,
   type = ntype;
   q = strchr(p, '(');
   if(q) {
     *q = '\0';
     type = NHI_INTERFACE;
   } else {
     type &= ~NHI_INTERFACE;
   }
   ids.push_back(atoi(p));
   if(type == NHI_INTERFACE) {
     *q = '(';
     p = ++q;
     q = strchr(p, ')');
     if(q) {
       *q = '\0';
       ids.push_back(atoi(p));
       *q = ')';
     } else {
       type = NHI_INVALID;
       ids.push_back(atoi(p)); // unnecessary
     }
   }
   start = 0;
   return (type & ntype)?0:1;
 }
bool s3f::s3fnet::Nhi::contains (Nhi & nhi)
Checks whether this NHI address contains the given NHI.
Definition at line 253 of file nhi.cc.
References ids, and start.
Referenced by s3f::s3fnet::Traffic::getServers(), and setRelativeTo().
 {
   int len, len2;
   len = ids.size() - start;
   len2 = nhi.ids.size() - nhi.start;
   if(len > len2) return false;
   for(int i=0; i < len; i++)
     if(ids[start + i] != nhi.ids[nhi.start + i])
       return false;
   return true;
 }
bool s3f::s3fnet::Nhi::contains (char * nhiAddr)
Checks whether this NHI address contains the given NHI given as a string.
Definition at line 269 of file nhi.cc.
References ids, and start.
 {
   assert(nhiAddr);
   for(unsigned i=start; i<ids.size(); i++) {
     if(*nhiAddr == 0) return false;
     int x = 0;
     while(*nhiAddr != 0 && *nhiAddr != ':') x = x*10+((*nhiAddr++)-'0');
     if(*nhiAddr) nhiAddr++;
     if(x != ids[i]) return false;
   }
   return true;
 }
int s3f::s3fnet::Nhi::readNhiRange (S3FNET_POINTER_VECTOR & pVector, s3f::dml::Configuration * cfg) static
Function to read the contents of an nhi_range attribute into a vector.
The caller is responsible to release the memory that is allocated in this function for the pVector.
Example of the DML that it handles: [port 10 nhi_range [from 1:2(0) to 1:5(0)]
Definition at line 205 of file nhi.cc.
References convert(), s3f::s3fnet::error_quit(), ids, Nhi(), NHI_INTERFACE, and toString().
Referenced by s3f::s3fnet::TrafficPattern::configure_servers().
 {
   // Look for from and to.
   Nhi from, to;
   int expected = Nhi::NHI_INTERFACE; // both must be interface nhi
   char* str = (char*)cfg->findSingle("from");
   if(!str || s3f::dml::dmlConfig::isConf(str)) {
     error_quit("ERROR: invalid FROM attribute in NHI_RANGE!\n");
   } else if(from.convert(str, expected)) {
     error_quit("ERROR: nhi type conversion error: \"%s\", "
                "invalid FROM attribute in NHI_RANGE.\n", str);
   }
   str = (char*)cfg->findSingle("to");
   if(!str || s3f::dml::dmlConfig::isConf(str)) {
     error_quit("ERROR: invalid TO attribute in NHI_RANGE!\n");
   } else if(to.convert(str, expected)) {
     error_quit("ERROR: nhi type conversion error: \"%s\", "
                "invalid TO attribute in NHI_RANGE.\n", str);
   }
   // These must have the same length and same prefix.
   unsigned size = from.ids.size();
   assert(size >= 2); // interface nhi must have such length
   if(size != to.ids.size()) {
     error_quit("ERROR: FROM and TO attributes in NHI_range must have the same size.\n");
   }
   for(unsigned k=0; k<size-2; k++) {
     if(from.ids[k] != to.ids[k]) {
       char buf0[50], buf1[50];
       error_quit("ERROR: FROM \"%s\" and TO \"%s\" are not in the same subnet.\n",
                  from.toString(buf0), to.toString(buf1));
     }
   }
   // cycle the machine id and create new Nhi objects for each.
   int toid = to.ids[size-2];
   for(int i=from.ids[size-2]; i <= toid; i++) {
     from.ids[size-2] = i;
     Nhi* pNhi = new Nhi(from);
     nhivec.push_back(pNhi);
   }
   return 0;
 }
void s3f::s3fnet::Nhi::setRelativeTo (Nhi & parent)
Changes the NHI so that it's given relative to the parameter.
For this to work, parent must contain this NHI address.
Definition at line 285 of file nhi.cc.
References contains(), s3f::s3fnet::error_quit(), ids, start, and toString().
 {
   if(!parent.contains(*this)) {
     char buf1[50], buf2[50];
     error_quit("ERROR: Nhi::setRelativeTo(), "
                "parent \"%s\" does not contain this nhi \"%s\".\n",
                parent.toString(buf1), toString(buf2));
   }
   start += parent.ids.size();
 }
Friends And Related Function Documentation
bool operator== (Nhi & n1, Nhi & n2) friend
Override the == operator.
Definition at line 53 of file nhi.cc.
 {
   int len, len2;
   len = n1.ids.size() - n1.start;
   len2 = n2.ids.size() - n2.start;
   if(len != len2)
     return false;
   for(int i=0; i < len; i++)
     if(n1.ids[n1.start + i] != n2.ids[n2.start + i])
       return false;
   return true;
 }
Member Data Documentation
S3FNET_LONG_VECTOR s3f::s3fnet::Nhi::ids
Vector of successive ids.
The last one could be the interface id.
Definition at line 119 of file nhi.h.
Referenced by contains(), convert(), display(), s3f::s3fnet::Host::init(), s3f::s3fnet::Net::nhi2obj(), operator+=(), operator=(), s3f::s3fnet::operator==(), readNhiRange(), setRelativeTo(), toString(), and ~Nhi().
int s3f::s3fnet::Nhi::start
This is an index into ids.
It is a start position of the NHI. Useful for altering the NHI during address resolution.
See Also
Net::Resolve.
Definition at line 126 of file nhi.h.
Referenced by contains(), convert(), display(), s3f::s3fnet::Net::nhi2obj(), operator=(), s3f::s3fnet::operator==(), setRelativeTo(), and toString().
int s3f::s3fnet::Nhi::type
The type of the NHI address.
Definition at line 129 of file nhi.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), s3f::s3fnet::Net::config(), convert(), display(), s3f::s3fnet::Net::nhi2obj(), operator=(), s3f::s3fnet::Traffic::resolve_nhi(), and toString().
char s3f::s3fnet::Nhi::internal_buf static private
Definition at line 132 of file nhi.h.
Referenced by toString().
The documentation for this class was generated from the following files:
nhi.h
nhi.cc