S3F: s3f::s3fnet::trie1::Trie1 Class Reference
s3f::s3fnet::trie1::Trie1 Class Reference
A data structure for forwarding tables.
#include <trie1.h>
Classes
class iterator
Public Types
enum TrieType {
ORIGINAL = 0, SIMPLE = 1, PREFIX = 2, UNORDERED_PREFIX = 3,
ARRAY_BACKED = 4, ARRAY_BACKED_PREFIX = 5, ARRAY_BACKED_UNORDERED_PREFIX = 6
}
Enum containing Trie implementations.
Public Member Functions
Trie1 ()
The constructor.
virtual ~Trie1 ()
The destructor.
virtual TrieData * insert (TRIEBITSTRING key, int nBits, TrieData *data, bool replace)
Inserts a new (key, data) pair.
virtual TrieData * remove (TRIEBITSTRING key, int nBits)
Removes a key from the Trie.
virtual TrieData * lookup (TRIEBITSTRING key)
Finds a key in the Trie.
virtual TrieData * getDefault ()
Get the default Route.
virtual int size ()
Return the number of items in the trie.
iterator begin ()
iterator & end ()
Public Attributes
iterator last
Last item in iterator.
Protected Member Functions
TrieNode * search (TRIEBITSTRING key, int len, TrieNode **failedNode, int *failedbitpos)
Helper function for the insert and lookup methods.
Static Protected Member Functions
static void create (TrieNode *theroot, TRIEBITSTRING key, int nBits, TrieData *data)
Creates a node from the root.
static void deallocate (TrieNode *theroot)
Deallocate the trie recursively.
Protected Attributes
TrieNode * root
The root of the trie.
int nElements
Number of data elements stored in the trie.
Detailed Description
A data structure for forwarding tables.
This class only contains basic enhancements to the original s3fnet Trie (extracted to Trie0). Any optimization to Trie0 should be added to Trie1 instead and may be addable to Trie[2-n] as well.
NOTE: If CIDR addresses are used, they must be ordered from longest mask lengths to shortest to prevent DUPLICATE_ROUTE replacement. Example order: ip1, ip2/31, ..., ip100/16, ..., ip1000/1 CIDR addresses are also only guaranteed to work for static routing.
Definition at line 47 of file trie1.h.
Member Enumeration Documentation
enum s3f::s3fnet::Trie::TrieType inherited
Enum containing Trie implementations.
Enumerator
ORIGINAL
Very first s3fnet Trie implementation.
SIMPLE
Identical to ORIGINAL with minor fixes/enhancements.
PREFIX
Stores values at minimum depth instead of depth equal to their bit-length (ie depth 32 for an ipv4 address).
UNORDERED_PREFIX
Like PREFIX but can take CIDR-format IP address as input in any order.
ARRAY_BACKED
Trie that stores indices into an array in its nodes (vs data IN the nodes).
ARRAY_BACKED_PREFIX
ARRAY_BACKED_UNORDERED_PREFIX
PREFIX with array-backing (ARRAY_BACKED).
Definition at line 112 of file trie.h.
                       {
                 ORIGINAL = 0,
                 SIMPLE = 1,
                 PREFIX = 2,
                 UNORDERED_PREFIX = 3,
                 ARRAY_BACKED = 4,
                 ARRAY_BACKED_PREFIX = 5,
                 ARRAY_BACKED_UNORDERED_PREFIX = 6
         };
Constructor & Destructor Documentation
s3f::s3fnet::trie1::Trie1::Trie1 ()
The constructor.
Definition at line 53 of file trie1.cc.
References root.
              : nElements(0), last(this) {
         root = new TrieNode();
         assert(root);
 }
s3f::s3fnet::trie1::Trie1::~Trie1 () virtual
The destructor.
Definition at line 61 of file trie1.cc.
References deallocate(), nElements, and root.
 {
   deallocate(root);
   nElements = 0;
 }
Member Function Documentation
TrieData * s3f::s3fnet::trie1::Trie1::insert (TRIEBITSTRING key, int nBits, TrieData * data, bool replace) virtual
Inserts a new (key, data) pair.
Adds a new (key, data) pair to the Trie. If the key already exists, and if the replace flag is set, we will replace the old data with the new one and return the old data. If the replace flag is not set, the old data remains in the trie and the new data is returned. If the key does not exist in trie, the data will be inserted and the return value is 0.
Parameters
key the key to insert
nBits bits of the key to consider (useful for CIDR)
data the TrieData object to add
replace whether to replace an existing value with the same key
Returns
NULL on success, otherwise the TrieData object we attempted to insert (so reference is not lost)
Implements s3f::s3fnet::Trie.
Definition at line 70 of file trie1.cc.
References create(), s3f::s3fnet::trie1::TrieNode::data, nElements, REMOVE, and search().
{
   // TODO: Force insertion to specified depth? At least note WHY duplicate route problem occurs.
   TrieNode *fail = 0;
   int bitpos = 0;
   TrieNode* match = search(key, nBits, &fail, &bitpos);
   // Does the key already exist in our trie?
   // If so, replace the data if replace flag is true.
   if(match) {
     if(!replace) return data;
     TrieData* temp = match->data;
     match->data = data;
     return temp;
   }
   // Create all the necessary nodes for the unmatched bits
   // after fail and insert the data.
   create(fail, REMOVE(bitpos, key), nBits-bitpos, data);
   nElements++;
   return 0;
 }
TrieData * s3f::s3fnet::trie1::Trie1::remove (TRIEBITSTRING key, int nBits) virtual
Removes a key from the Trie.
Remove the key from the trie, if it exists, and returns the data corresponding to the removed key. If the key is not in the trie, return NULL.
Parameters
key the key to remove
nBits bits of the key to consider
Returns
the data correspoding to the key on success, otherwise NULL
Implements s3f::s3fnet::Trie.
Definition at line 126 of file trie1.cc.
References s3f::s3fnet::trie1::TrieNode::children, s3f::s3fnet::trie1::TrieNode::data, nElements, and search().
 {
   TrieNode* ptr;
   TrieData* olddata;
   TrieNode* parent;
   int index;
   ptr = search(key, nBits, &parent, &index);
   if(!ptr) return 0;
   olddata = ptr->data;
   ptr->data = 0;
   nElements--;
   if(ptr->children[0] == 0 && ptr->children[1] == 0) {
         delete parent->children[index];
         parent->children[index] = 0;
   }
   return olddata;
 }
TrieData * s3f::s3fnet::trie1::Trie1::lookup (TRIEBITSTRING key) virtual
Finds a key in the Trie.
Perform a longest-matching prefix search for the key and if found, places the data in pData. Otherwise, pData is NULL.
Parameters
key the key to lookup
Returns
the data matching the key on success, otherwise NULL
Implements s3f::s3fnet::Trie.
Definition at line 104 of file trie1.cc.
References s3f::s3fnet::trie1::TrieNode::children, s3f::s3fnet::trie1::TrieNode::data, root, and s3f::s3fnet::trie1::TRIE_BIT_MASK.
 {
   // If this Trie exists to call 'lookup', root has already been asserted as non-null
   TrieNode* cur = root->children[(key & TRIE_BIT_MASK)?1:0];
   TrieData* pData = root->data; // handles default-route case
   while(cur) {
     if(cur->data) {
                 pData = cur->data;
         }
         key <<= 1; // needed from pre-loop lookup and removes last unnecessary shift
     cur = cur->children[(key & TRIE_BIT_MASK)?1:0];
   }
   return pData;
 }
TrieData * s3f::s3fnet::trie1::Trie1::getDefault () virtual
Get the default Route.
Returns
an instance of the default route as a TrieData object
Implements s3f::s3fnet::Trie.
Definition at line 147 of file trie1.cc.
References s3f::s3fnet::trie1::TrieNode::data, and root.
{
         if(root) return root->data;
         return 0;
 }
virtual int s3f::s3fnet::trie1::Trie1::size () inline virtual
Return the number of items in the trie.
Returns
the size of the Trie (generally the number of elements contained)
Implements s3f::s3fnet::Trie.
Definition at line 102 of file trie1.h.
References nElements.
 { return nElements; }
TrieNode * s3f::s3fnet::trie1::Trie1::search (TRIEBITSTRING key, int len, TrieNode ** failedNode, int * failedbitpos) protected
Helper function for the insert and lookup methods.
This function will search the trie for the key and if found, return a pointer to the TrieNode. If not found, it will return NULL, and set failedNode to the TrieNode where the search fails and failedbitpos to the bit position that failed.
Parameters
key the key for insert/lookup
len the bits to consider of the key
failedNode a TrieNode reference address to write the address of the last node traversed before failure
failedbitpos an integer address to write the bit position of the last traversal before failure
Returns
the TrieNode found, NULL otherwise
Definition at line 160 of file trie1.cc.
References s3f::s3fnet::trie1::TrieNode::children, s3f::s3fnet::trie1::TrieNode::data, GETBIT, root, and TRIE_KEY_SIZE.
Referenced by insert(), and remove().
 {
   // TODO: Optimize this function
   TrieNode* cur, *lastcur, *parent;
   TrieNode* match = 0;
   int bitpos, curbit, parentbit;
   if(len > TRIE_KEY_SIZE(key)) {
         len = TRIE_KEY_SIZE(key);
   }
   // Go through the bits starting from the MSB and traverse
   // the tree. Remember the last match.
   for(bitpos = 0, lastcur = cur = root;
       cur && bitpos < len;
       cur = cur->children[curbit], bitpos++) {
     if(cur->data) {
                 parent = lastcur;
                 parentbit = GETBIT(bitpos-1,key);
                 match = cur;
         }
     lastcur = cur;
     curbit = GETBIT(bitpos, key);
   }
   if(cur && cur->data) {
         match = cur;
         if(failedNode && failedbitpos) {
                 // we have a match on the last node, parent is lastcur
                 *failedNode = lastcur;
                 *failedbitpos = GETBIT(bitpos-1,key);
         }
   } else if(failedNode && failedbitpos) {
         // if there is a match
         if(match) {
                 *failedNode = parent;
                 *failedbitpos = parentbit;
         } else { // no match
                 if(cur) {
                   *failedbitpos = bitpos;
                   *failedNode = cur;
                 } else {
                   *failedbitpos = bitpos - 1;
                   *failedNode = lastcur;
                 }
         }
   }
   return match;
 }
void s3f::s3fnet::trie1::Trie1::create (TrieNode * theroot, TRIEBITSTRING key, int nBits, TrieData * data) static protected
Creates a node from the root.
Static helper function for the insert method. Creates nBits nodes for the key starting at TrieNode theroot.
Parameters
theroot the root entry to start from
key the key to create a node for
nBits the bits to consider
data the data to store
Definition at line 217 of file trie1.cc.
References s3f::s3fnet::trie1::TrieNode::children, and GETBIT.
Referenced by insert().
 {
   TrieNode* ptr;
   for(int i=0; i < nBits; i++, theroot = ptr) {
         assert(theroot->children[GETBIT(i, key)] == 0);
     ptr = theroot->children[GETBIT(i, key)] = new TrieNode();
     assert(ptr);
   }
   theroot->data = data;
 }
void s3f::s3fnet::trie1::Trie1::deallocate (TrieNode * theroot) static protected
Deallocate the trie recursively.
Parameters
theroot the root entry of the Trie to free
Definition at line 233 of file trie1.cc.
References s3f::s3fnet::trie1::TrieNode::children, and s3f::s3fnet::trie1::TRIE_KEY_SPAN.
Referenced by ~Trie1().
 {
   if(theroot == 0) return;
   // deallocate all the children
   for(int i = 0; i < TRIE_KEY_SPAN; i++)
     deallocate(theroot->children[i]);
   delete theroot;
 }
Trie1::iterator s3f::s3fnet::trie1::Trie1::begin ()
Definition at line 408 of file trie1.cc.
{
   iterator first(this); // create iterator
   ++first; // find first element
   return first; // return by copy
 }
iterator& s3f::s3fnet::trie1::Trie1::end () inline
Definition at line 289 of file trie1.h.
References last.
 { return last; }
Member Data Documentation
TrieNode* s3f::s3fnet::trie1::Trie1::root protected
The root of the trie.
Definition at line 139 of file trie1.h.
Referenced by getDefault(), lookup(), search(), Trie1(), and ~Trie1().
int s3f::s3fnet::trie1::Trie1::nElements protected
Number of data elements stored in the trie.
Definition at line 142 of file trie1.h.
Referenced by insert(), remove(), size(), and ~Trie1().
iterator s3f::s3fnet::trie1::Trie1::last
Last item in iterator.
Definition at line 278 of file trie1.h.
Referenced by end().
The documentation for this class was generated from the following files:
trie1.h
trie1.cc