S3F: Random::RNG Class Reference
Random::RNG Class Reference
These are C++ lang routines which can be used to evaluate the probability density functions (pdf's), cumulative distribution functions (cdf's), and inverse distribution functions (idf's) for a variety of discrete and continuous random variables.
#include <rng.h>
Public Member Functions
RNG ()
double Random ()
~RNG ()
double Bernoulli_pdf (double p, long x)
double Bernoulli_cdf (double p, long x)
long Bernoulli_idf (double p, double u)
double Equilikely_pdf (long a, long b, long x)
double Equilikely_cdf (long a, long b, long x)
long Equilikely_idf (long a, long b, double u)
double Binomial_pdf (long n, double p, long x)
double Binomial_cdf (long n, double p, long x)
long Binomial_idf (long n, double p, double u)
double Geometric_pdf (double p, long x)
double Geometric_cdf (double p, long x)
long Geometric_idf (double p, double u)
double Pascal_pdf (long n, double p, long x)
double Pascal_cdf (long n, double p, long x)
long Pascal_idf (long n, double p, double u)
double Poisson_pdf (double m, long x)
double Poisson_cdf (double m, long x)
long Poisson_idf (double m, double u)
double Uniform_pdf (double a, double b, double x)
double Uniform_cdf (double a, double b, double x)
double Uniform_idf (double a, double b, double u)
double Exponential_pdf (double m, double x)
double Exponential_cdf (double m, double x)
double Exponential_idf (double m, double u)
double Erlang_pdf (long n, double b, double x)
double Erlang_cdf (long n, double b, double x)
double Erlang_idf (long n, double b, double u)
double Normal_pdf (double x)
double Normal_cdf (double x)
double Normal_idf (double u)
double Gauss_pdf (double m, double s, double x)
double Gauss_cdf (double m, double s, double x)
double Gauss_idf (double m, double s, double u)
double Lognormal_pdf (double a, double b, double x)
double Lognormal_cdf (double a, double b, double x)
double Lognormal_idf (double a, double b, double u)
double Chisquare_pdf (long n, double x)
double Chisquare_cdf (long n, double x)
double Chisquare_idf (long n, double u)
double Student_pdf (long n, double x)
double Student_cdf (long n, double x)
double Student_idf (long n, double u)
double Uniform (double a, double b)
double Exponential (double m)
double Erlang (long n, double b)
double Normal ()
double Gauss (double m, double s)
double Lognormal (double a, double b)
double Chisquare (long n)
double Student (long n)
double Ln_Gamma (double a)
double Ln_Factorial (long n)
double Ln_Beta (double a, double b)
double Ln_Choose (long n, long m)
double Incomplete_Gamma (double a, double x)
double Incomplete_Beta (double a, double b, double x)
long Bernoulli (double p)
long Binomial (long n, double p)
long Equilikely (long a, long b)
long Geometric (double p)
long Pascal (long n, double p)
long Poisson (double m)
Public Attributes
RNGS::RngStream * __rngStream
Detailed Description
These are C++ lang routines which can be used to evaluate the probability density functions (pdf's), cumulative distribution functions (cdf's), and inverse distribution functions (idf's) for a variety of discrete and continuous random variables.
The following notational conventions are used:
x : possible value of the random variable
u : real variable (probability) between 0 and 1
a, b, n, p, m, s : distribution specific parameters
There are pdf's, cdf's and idf's for 6 discrete random variables:
 Random Variable    Range (x)  Mean         Variance
 Bernoulli(p)       0..1       p            p*(1-p)
 Binomial(n, p)     0..n       n*p          n*p*(1-p)
 Equilikely(a, b)   a..b       (a+b)/2      ((b-a+1)*(b-a+1)-1)/12
 Geometric(p)       0...       p/(1-p)      p/((1-p)*(1-p))
 Pascal(n, p)       0...       n*p/(1-p)    n*p/((1-p)*(1-p))
 Poisson(m)         0...       m            m
and for 8 continuous random variables:
 Random Variable    Range (x)  Mean         Variance
 Uniform(a, b)      a < x < b  (a+b)/2      (b-a)*(b-a)/12
 Exponential(m)     x > 0      m            m*m
 Erlang(n, b)       x > 0      n*b          n*b*b
 Normal             all x      0            1
 Gauss(m, s)        all x      m            s*s
 Lognormal(a, b)    x > 0         see below
 Chisquare(n)       x > 0      n            2*n
 Student(n)         all x      0  (n > 1)   n/(n-2)   (n > 2)
For the Lognormal(a, b), the mean and variance are:
                   mean = Exp(a + 0.5*b*b)
               variance = (Exp(b*b) - 1)*Exp(2*a + b*b)
Name : DFU.C
Purpose : Distribution/Density Function Routines
Author : Steve Park
Language : Turbo Pascal, 5.0
Latest Revision : 09-19-90
Reference : Lecture Notes on Simulation, by Steve Park
Converted to C : David W. Geyer 09-02-91
Definition at line 72 of file rng.h.
Constructor & Destructor Documentation
RNG::RNG ()
Definition at line 10 of file rng.cc.
References __rngStream.
          {
   __rngStream = new RNGS::RngStream();
   // pthread_mutex_init(&(__rngStream->nextState_lock), NULL);
 }
Random::RNG::~RNG () inline
Definition at line 77 of file rng.h.
 {};
Member Function Documentation
double RNG::Random ()
Definition at line 15 of file rng.cc.
References __rngStream, and RNGS::RngStream::RandU01().
Referenced by Bernoulli(), Equilikely(), Exponential(), Geometric(), Normal(), Poisson(), and Uniform().
 { return __rngStream->RandU01(); }
double RNG::Bernoulli_pdf (double p, long x)
Definition at line 553 of file rng.cc.
 {
   if (x == 0)
     return((double)1.0 - p);
   else
     return(p);
 }  /* Bernoulli_pdf */
double RNG::Bernoulli_cdf (double p, long x)
Definition at line 561 of file rng.cc.
 {
   if (x == 0)
     return((double)1.0 - p);
   else
     return((double)1.0);
 }  /* Bernoulli_cdf */
long RNG::Bernoulli_idf (double p, double u)
Definition at line 569 of file rng.cc.
 {
   if (u < ((double)1.0 - p))
     return((long)0.0);
   else
     return((long)1.0);
 }  /* Bernoulli_idf */
double RNG::Equilikely_pdf (long a, long b, long x)
Definition at line 584 of file rng.cc.
 {
   return( (double)1.0 / ((double)b - (double)a + (double)1.0) );
 }  /* Equilikely_pdf */
double RNG::Equilikely_cdf (long a, long b, long x)
Definition at line 589 of file rng.cc.
 {
   return( ((double)x - (double)a + (double)1.0) /
           ((double)b - (double)a + (double)1.0)  );
 }  /* Equilikely_cdf */
long RNG::Equilikely_idf (long a, long b, double u)
Definition at line 595 of file rng.cc.
 {
   return(a + (long)(u * (b - a + 1)) );
 }  /* Equilikely_idf */
double RNG::Binomial_pdf (long n, double p, long x)
Definition at line 607 of file rng.cc.
References Ln_Choose().
 { double s, t;
   s = Ln_Choose(n, x);                   /* break this calculation        */
   t = x * log(p) + (n - x) * log(1 - p); /* into two parts                */
   return(exp(s + t));                    /* to avoid 80x87 stack overflow */
 }  /* Binomial_pdf */
double RNG::Binomial_cdf (long n, double p, long x)
Definition at line 615 of file rng.cc.
References Incomplete_Beta().
Referenced by Binomial_idf().
 {
   if (x < n)
     return((double)1.0 - Incomplete_Beta((double)(x+1), (double)(n-x), p));
   else
     return((double)1.0);
 }  /* Binomial_cdf */
long RNG::Binomial_idf (long n, double p, double u)
Definition at line 623 of file rng.cc.
References Binomial_cdf().
 { long  x;
   x = (long)(n * p);                         /* start searching at the mean */
   if (Binomial_cdf(n, p, x) <= u)
     while (Binomial_cdf(n, p, x) <= u)  {
       x++;
     }
   else if (Binomial_cdf(n, p, 0) <= u)
     while (Binomial_cdf(n, p, x - 1) > u)  {
       x--;
     }
   else
     x = 0;
   return(x);
 }  /* Binomial_idf */
double RNG::Geometric_pdf (double p, long x)
Definition at line 646 of file rng.cc.
 {
   return( (1.0 - p) * exp(x * log(p)) );
 }  /* Geometric_pdf */
double RNG::Geometric_cdf (double p, long x)
Definition at line 651 of file rng.cc.
 {
   return( 1.0 - exp((x + 1) * log(p)) );
 }  /* Geometric_cdf */
long RNG::Geometric_idf (double p, double u)
Definition at line 656 of file rng.cc.
 {
   return( (long)(log(1.0 - u) / log(p)) );
 }  /* Geometric_idf */
double RNG::Pascal_pdf (long n, double p, long x)
Definition at line 668 of file rng.cc.
References Ln_Choose().
 { double  s, t;
   s = Ln_Choose(n + x - 1, x);            /* break this calculation        */
   t = x * log(p) + n * log(1.0 - p);      /* into two parts                */
   return(exp(s + t));                     /* to avoid 80x87 stack overflow */
 }  /* Pascal_pdf */
double RNG::Pascal_cdf (long n, double p, long x)
Definition at line 676 of file rng.cc.
References Incomplete_Beta().
Referenced by Pascal_idf().
 {
   return(1.0 - Incomplete_Beta(x + 1, (double)n, p));
 }  /* Pascal_cdf */
long RNG::Pascal_idf (long n, double p, double u)
Definition at line 681 of file rng.cc.
References Pascal_cdf().
 { long  x;
   x = (long)(n * p / (1.0 - p));            /* start searching at the mean */
   if (Pascal_cdf(n, p, x) <= u)
     while (Pascal_cdf(n, p, x) <= u)  {
       x++;
     }
   else if (Pascal_cdf(n, p, 0) <= u)
     while (Pascal_cdf(n, p, x - 1) > u)  {
       x--;
     }
   else
     x = 0;
   return(x);
 }  /* Pascal_idf */
double RNG::Poisson_pdf (double m, long x)
Definition at line 705 of file rng.cc.
References Ln_Factorial().
 { double t;
   t = - m + x * log(m) - Ln_Factorial(x);
   return(exp(t));
 }  /* Poisson_pdf */
double RNG::Poisson_cdf (double m, long x)
Definition at line 712 of file rng.cc.
References Incomplete_Gamma().
Referenced by Poisson_idf().
 {
   return((double)1.0 - Incomplete_Gamma((double)x + 1.0, m));
 }  /* Poisson_cdf */
long RNG::Poisson_idf (double m, double u)
Definition at line 717 of file rng.cc.
References BinarySearch::found(), Poisson_cdf(), BinarySearch::refine(), and BinarySearch::search().
 { long x;
   x = (long)m;                            /* start searching at the mean */
 #ifdef OLDWAY
   if (Poisson_cdf(m, x) <= u)
     while (Poisson_cdf(m, x) <= u)  {
       x++;
     }
   else if (Poisson_cdf(m, 0) <= u)
     while (Poisson_cdf(m, x - 1) > u)  {
       x--;
     }
   else
     x = 0;
   return(x);
 #else
   int limit = (int)(2*m);
   BinarySearch BS(0,limit);  // use this to control search
   x = BS.search();       // starting point
   while(! BS.found() ) {
         if( Poisson_cdf(m, x) <= u ) x = BS.refine(0);
         else x = BS.refine(1);
   }
   x = BS.search();
   // if x == 2*m then we need to correct for having excluded upper end
   if (x < limit) return (x);
   while (Poisson_cdf(m, x) <= u)  {
       x++;
   }
   return x;
 #endif
 }  /* Poisson_idf */
double RNG::Uniform_pdf (double a, double b, double x)
Definition at line 762 of file rng.cc.
 {
   return(1.0 / (b - a));
 }  /* Uniform_pdf */
double RNG::Uniform_cdf (double a, double b, double x)
Definition at line 767 of file rng.cc.
 {
   return((x - a) / (b - a));
 }  /* Uniform_cdf */
double RNG::Uniform_idf (double a, double b, double u)
Definition at line 772 of file rng.cc.
 {
   return(a + (b - a) * u);
 }  /* Uniform_idf */
double RNG::Exponential_pdf (double m, double x)
Definition at line 784 of file rng.cc.
 {
   return((1.0 / m) * exp(- x / m));
 }  /* Exponential_pdf */
double RNG::Exponential_cdf (double m, double x)
Definition at line 789 of file rng.cc.
 {
   return(1.0 - exp(- x / m));
 }  /* Exponential_cdf */
double RNG::Exponential_idf (double m, double u)
Definition at line 794 of file rng.cc.
 {
   return(- m * log(1 - u));
 }  /* Exponential_idf */
double RNG::Erlang_pdf (long n, double b, double x)
Definition at line 806 of file rng.cc.
References Ln_Gamma().
Referenced by Erlang_idf().
 { double t;
   t = (double)(n - 1) * log(x / b) - (x / b) - log(b) - Ln_Gamma((double)n);
   return(exp(t));
 }  /* Erlang_pdf */
double RNG::Erlang_cdf (long n, double b, double x)
Definition at line 813 of file rng.cc.
References Incomplete_Gamma().
Referenced by Erlang_idf().
 {
   return(Incomplete_Gamma((double)n, x / b));
 }  /* Erlang_cdf */
double RNG::Erlang_idf (long n, double b, double u)
Definition at line 818 of file rng.cc.
References Erlang_cdf(), and Erlang_pdf().
 { double tiny = 1.0e-10, t, x;
   x = (double)n * b;                 /* initialize to the mean, then - */
   do {                               /* use Newton-Raphson iteration   */
     t = x;
     x = t + (u - Erlang_cdf(n, b, t)) / Erlang_pdf(n, b, t);
     if (x <= 0.0)
       x = 0.5 * t;
   } while (fabs(x - t) >= tiny);
   return(x);
 }  /* Erlang_idf */
double RNG::Normal_pdf (double x)
Definition at line 837 of file rng.cc.
Referenced by Gauss_pdf(), Lognormal_pdf(), and Normal_idf().
 { double c = 0.3989422804;                          /* 1 / Sqrt(2 * pi) */
   return(c * exp(-0.5 * x * x));
 }  /* Normal_pdf */
double RNG::Normal_cdf (double x)
Definition at line 843 of file rng.cc.
References Incomplete_Gamma().
Referenced by Gauss_cdf(), Lognormal_cdf(), and Normal_idf().
 { double t;
   t = Incomplete_Gamma(0.5, 0.5 * x * x);
   if (x < 0.0)
     return(0.5 * (1.0 - t));
   else
     return(0.5 * (1.0 + t));
 }  /* Normal_cdf */
double RNG::Normal_idf (double u)
Definition at line 853 of file rng.cc.
References Normal_cdf(), and Normal_pdf().
Referenced by Gauss_idf(), and Lognormal_idf().
 { double tiny = 1.0e-10, t, x;
   x = 0.0;                           /* initialize to the mean, then - */
   do {                               /* use Newton-Raphson iteration   */
     t = x;
     x = t + (u - Normal_cdf(t)) / Normal_pdf(t);
   } while (fabs(x - t) >= tiny);
   return(x);
 }  /* Normal_idf */
double RNG::Gauss_pdf (double m, double s, double x)
Definition at line 871 of file rng.cc.
References Normal_pdf().
 { double t;
   t = (x - m) / s;
   return(Normal_pdf(t) / s);
 }  /* Gauss_pdf */
double RNG::Gauss_cdf (double m, double s, double x)
Definition at line 878 of file rng.cc.
References Normal_cdf().
 { double t;
   t = (x - m) / s;
   return(Normal_cdf(t));
 }  /* Gauss_cdf */
double RNG::Gauss_idf (double m, double s, double u)
Definition at line 885 of file rng.cc.
References Normal_idf().
 {
   return(m + s * Normal_idf(u));
 }  /* Gauss_idf */
double RNG::Lognormal_pdf (double a, double b, double x)
Definition at line 897 of file rng.cc.
References Normal_pdf().
 { double t;
   t = (log(x) - a) / b;
   return(Normal_pdf(t) / (b * x));
 }  /* Lognormal_pdf */
double RNG::Lognormal_cdf (double a, double b, double x)
Definition at line 904 of file rng.cc.
References Normal_cdf().
 { double t;
   t = (log(x) - a) / b;
   return(Normal_cdf(t));
 }  /* Lognormal_cdf */
double RNG::Lognormal_idf (double a, double b, double u)
Definition at line 911 of file rng.cc.
References Normal_idf().
 { double t;
   t = a + b * Normal_idf(u);
   return(exp(t));
 }  /* Lognormal_idf */
double RNG::Chisquare_pdf (long n, double x)
Definition at line 925 of file rng.cc.
References Ln_Gamma().
Referenced by Chisquare_idf().
 { double t;
   t = (n / 2 - 1) * log(x / 2) - (x / 2) - log(2) - Ln_Gamma( (double)(n / 2));
   return(exp(t));
 }  /* Chisquare_pdf */
double RNG::Chisquare_cdf (long n, double x)
Definition at line 932 of file rng.cc.
References Incomplete_Gamma().
Referenced by Chisquare_idf().
 {
   return(Incomplete_Gamma(n / 2, x / 2));
 }  /* Chisquare_cdf */
double RNG::Chisquare_idf (long n, double u)
Definition at line 937 of file rng.cc.
References Chisquare_cdf(), and Chisquare_pdf().
 { double tiny = 1.0e-10, t, x;
   x = n;                               /* initialize to the mean, then - */
   do {                                 /* use Newton-Raphson iteration   */
     t = x;
     x = t + (u - Chisquare_cdf(n, t)) / Chisquare_pdf(n, t);
     if (x <= 0)
       x = 0.5 * t;
   } while (fabs(x - t) >= tiny);
   return(x);
 }  /* Chisquare_idf */
double RNG::Student_pdf (long n, double x)
Definition at line 956 of file rng.cc.
References Ln_Beta().
Referenced by Student_idf().
 { double t;
   t = -0.5 * (n + 1) * log(1 + ((x * x) / (double)n))
                                      - Ln_Beta(0.5, (double)n / 2.0);
   return(exp(t) / sqrt((double)n));
 }  /* Student_pdf */
double RNG::Student_cdf (long n, double x)
Definition at line 964 of file rng.cc.
References Incomplete_Beta().
Referenced by Student_idf().
 { double s, t;
   t = (x * x) / (n + x * x);
   s = Incomplete_Beta(0.5, (double)n / 2.0, t);
   if (x >= 0)
     return(0.5 * (1.0 + s));
   else
     return(0.5 * (1.0 - s));
 }  /* Student_cdf */
double RNG::Student_idf (long n, double u)
Definition at line 975 of file rng.cc.
References ABS, Student_cdf(), and Student_pdf().
 { double tiny = 1.0e-10, t, x;
   x = 0;                              /* initialize to the mean, then - */
   do {                                /* use Newton-Raphson iteration   */
     t = x;
     x = t + (u - Student_cdf(n, t)) / Student_pdf(n, t);
   } while (ABS(x - t) >= tiny);
   return(x);
 }  /* Student_idf */
double RNG::Uniform (double a, double b)
Definition at line 59 of file rng.cc.
References Random().
Referenced by s3f::s3fnet::DroptailQueue::calibrate(), s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::DummySession::init(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::BTCPClientSession::init(), and s3f::s3fnet::NetworkInterface::receivePacket().
 {
   return(a + (b - a) * Random());
 }  /* Uniform */
double RNG::Exponential (double m)
Definition at line 70 of file rng.cc.
References Random().
Referenced by Erlang(), pHold_Node::listen(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), and s3f::s3fnet::BTCPClientSession::main_proc().
 {
   return(- m * log(1.0 - Random()));
 } /* Exponential */
double RNG::Erlang (long n, double b)
Definition at line 81 of file rng.cc.
References Exponential().
 { long   i;
   double x;
   x = 0.0;
   for (i=0;i < n;i++)
     x += Exponential(b);
   return(x);
 } /* Erlang */
double RNG::Normal ()
Definition at line 98 of file rng.cc.
References Random().
Referenced by Chisquare(), Gauss(), Lognormal(), and Student().
 { double p0 = 0.322232431088;        double q0 = 0.099348462606;
   double p1 = 1.0;                   double q1 = 0.588581570495;
   double p2 = 0.342242088547;        double q2 = 0.531103462366;
   double p3 = 0.204231210245e-1;     double q3 = 0.103537752850;
   double p4 = 0.453642210148e-4;     double q4 = 0.385607006340e-2;
   double u, t, p, q;
   u = Random();
   if (u < 0.5)
     t = sqrt(- 2 * log(u));
   else
     t = sqrt(- 2 * log(1.0 - u));
   p = p0 + t * (p1 + t * (p2 + t * (p3 + t * p4)));
   q = q0 + t * (q1 + t * (q2 + t * (q3 + t * q4)));
   if (u < 0.5)
     return( (p / q) - t );
   else
     return( t - (p / q) );
 }  /* Normal */
double RNG::Gauss (double m, double s)
Definition at line 125 of file rng.cc.
References Normal().
 {
   return(m + s * Normal());
 }  /* Gauss */
double RNG::Lognormal (double a, double b)
Definition at line 136 of file rng.cc.
References Normal().
 {
   return( exp(a + b * Normal()) );
 }  /* Lognormal */
double RNG::Chisquare (long n)
Definition at line 147 of file rng.cc.
References Normal().
Referenced by Student().
 { long    i;
   double  z, x;
   x = 0.0;
   for(i=0;i < n;i++)  {
     z = Normal();
     x += z * z;
   }
   return(x);
 } /* Chisquare */
double RNG::Student (long n)
Definition at line 165 of file rng.cc.
References Chisquare(), and Normal().
 {
   return( Normal() / sqrt(Chisquare(n) / (double)n) );
 } /* Student */
double RNG::Ln_Gamma (double a)
Definition at line 298 of file rng.cc.
Referenced by Chisquare_pdf(), Erlang_pdf(), Incomplete_Gamma(), Ln_Beta(), and Ln_Factorial().
 { double c = 2.506628274631;                     /* Sqrt(2 * pi) */
   double s[6], sum, temp;
   int    i;
   s[0] =  76.180091729406 / a;
   s[1] = -86.505320327112 / (a + 1);
   s[2] =  24.014098222230 / (a + 2);
   s[3] =  -1.231739516140 / (a + 3);
   s[4] =   0.001208580030 / (a + 4);
   s[5] =  -0.000005363820 / (a + 5);
   sum  =   1.000000000178;
   for (i=0;i < 6;i++)
     sum += s[i];
   temp = (a - 0.5) * log(a + 4.5) - (a + 4.5) + log(c * sum);
   return(temp);
 }  /* Ln_Gamma */
double RNG::Ln_Factorial (long n)
Definition at line 325 of file rng.cc.
References Ln_Gamma().
Referenced by Poisson_pdf().
 {
   return(Ln_Gamma((double)n + (double)1.0));
 }  /* Ln_Factorial */
double RNG::Ln_Beta (double a, double b)
Definition at line 339 of file rng.cc.
References Ln_Gamma().
Referenced by Incomplete_Beta(), Ln_Choose(), and Student_pdf().
 { double temp;
   temp    = Ln_Gamma(a) + Ln_Gamma(b) - Ln_Gamma(a + b);
   return(temp);
 }  /* Ln_Beta */
double RNG::Ln_Choose (long n, long m)
Definition at line 356 of file rng.cc.
References Ln_Beta().
Referenced by Binomial_pdf(), and Pascal_pdf().
 {
   if (m > 0)
     return(- Ln_Beta((double)m, (double)(n - m + 1)) - log((double)m));
   else
     return((double) 0.0);
 }  /* Ln_Choose */
double RNG::Incomplete_Gamma (double a, double x)
Definition at line 377 of file rng.cc.
References Ln_Gamma().
Referenced by Chisquare_cdf(), Erlang_cdf(), Normal_cdf(), and Poisson_cdf().
 { double tiny = 1.0e-10;                      /* convergence parameter */
   double t, sum, term, factor, f, g, c[2], p[3], q[3];
   long   n;
   if (x > 0.0)
     factor = exp(-x + a * log(x) - Ln_Gamma(a));
   else
     factor = 0.0;
   if (x < a + 1.0) {                 /* evaluate as an infinite series - */
       t    = a;                      /* A & S equation 6.5.29            */
       term = 1.0 / a;
       sum  = term;
       do {                           /* sum until 'term' is small */
         t++;
         term *= x / t;
         sum  += term;
       } while (term >= tiny * sum);
       return(factor * sum);
   }
   else  {                            /* evaluate as a continued fraction - */
     p[0]  = 0.0;                     /* A & S eqn 6.5.31 with the extended */
     q[0]  = 1.0;                     /* pattern 2-a, 2, 3-a, 3, 4-a, 4,... */
     p[1]  = 1.0;                     /* - see also A & S sec 3.10, eqn (3) */
     q[1]  = x;
     f     = p[1] / q[1];
     n     = 0;
     do {                             /* recursively generate the continued */
       g  = f;                        /* fraction 'f' until two consecutive */
       n++;                           /* values are small                   */
       if ((n%2) > 0) {
         c[0] = ((double)(n + 1) / 2) - a;
         c[1] = 1.0;
       }
       else  {
         c[0] = (double)(n / 2);
         c[1] = x;
       }
       p[2] = c[1] * p[1] + c[0] * p[0];
       q[2] = c[1] * q[1] + c[0] * q[0];
       if (q[2] != 0.0)  {             /* rescale to avoid overflow */
           p[0] = p[1] / q[2];
           q[0] = q[1] / q[2];
           p[1] = p[2] / q[2];
           q[1] = 1.0;
           f    = p[1];
       }
     } while ((fabs(f - g) >= tiny) || (q[1] != 1.0));
     return((double)1.0 - factor * f);
   }
 }  /* Incomplete_Gamma */
double RNG::Incomplete_Beta (double a, double b, double x)
Definition at line 441 of file rng.cc.
References ABS, and Ln_Beta().
Referenced by Binomial_cdf(), Pascal_cdf(), and Student_cdf().
 { double tiny = 1.0e-10;                      /* convergence parameter */
   double t, factor, f, g, c, p[3], q[3];
   int swap;
   long   n;
   if (x > (a + 1) / (a + b + 1)) {   /* to accelerate convergence   */
     swap = 1;                        /* complement x and swap a & b */
     x    = 1 - x;
     t    = a;
     a    = b;
     b    = t;
   }
   else                                /* do nothing */
     swap = 0;
   if (x > 0)
     factor = exp(a * log(x) + b * log(1 - x) - Ln_Beta(a,b)) / a;
   else
     factor = 0;
   p[0] = 0;
   q[0] = 1;
   p[1] = 1;
   q[1] = 1;
   f    = p[1] / q[1];
   n    = 0;
   do {                               /* recursively generate the continued */
     g = f;                           /* fraction 'f' until two consecutive */
     n++;                             /* values are small                   */
     if ((n%2) > 0)  {
       t = (n - 1) / 2;
       c = -(a + t) * (a + b + t) * x / ((a + n - 1) * (a + n));
     }
     else  {
       t = n / 2;
       c = t * (b - t) * x / ((a + n - 1) * (a + n));
     }
     p[2] = p[1] + c * p[0];
     q[2] = q[1] + c * q[0];
     if (q[2] != 0)  {                /* rescale to avoid overflow */
       p[0] = p[1] / q[2];
       q[0] = q[1] / q[2];
       p[1] = p[2] / q[2];
       q[1] = 1.0;
       f    = p[1];
     }
   } while ((ABS(f - g) >= tiny) || (q[1] != 1));
   if (swap)
     return(1.0 - factor * f);
   else
     return(factor * f);
 }  /* Incomplete_Beta */
long RNG::Bernoulli (double p)
Definition at line 198 of file rng.cc.
References Random().
Referenced by Binomial().
 {
   if (Random() < (1 - p))
     return((long) 0);
   else
     return((long) 1);
 }  /* Bernoulli */
long RNG::Binomial (long n, double p)
Definition at line 211 of file rng.cc.
References Bernoulli().
 { long i, x = 0;
   for(i=0;i < n;i++)
     x += Bernoulli(p);
   return(x);
 }  /* Binomial */
long RNG::Equilikely (long a, long b)
Definition at line 224 of file rng.cc.
References Random().
 {
   return(a + (long)((b - a + 1) * Random()));
 }  /* Equilikely */
long RNG::Geometric (double p)
Definition at line 234 of file rng.cc.
References Random().
Referenced by Pascal().
 {
   return( (long)( (log(1 - Random()) / log(p)) ) );
 }  /* Geometric */
long RNG::Pascal (long n, double p)
Definition at line 244 of file rng.cc.
References Geometric().
 { long i, x = 0;
   for (i=0;i < n;i++)
     x += Geometric(p);
   return(x);
 }  /* Pascal */
long RNG::Poisson (double m)
Definition at line 257 of file rng.cc.
References Random().
 { long   x = 0;
   double t;
   t = exp(m);
   do {
     x++;
     t *= Random();
   } while (t >= 1);
   return(x - 1);
 }  /* Poisson */
Member Data Documentation
RNGS::RngStream* Random::RNG::__rngStream
Definition at line 75 of file rng.h.
Referenced by Random(), and RNG().
The documentation for this class was generated from the following files:
rng.h
rng.cc