S3F: AsyncMessageHandler Class Reference
AsyncMessageHandler Class Reference
Class for an asynchronous message handler.
#include <asyncmsg.h>
Public Member Functions
AsyncMessageHandler ()
constructor
~AsyncMessageHandler ()
destructor
bool isconnected ()
is the network socket currently connected?
int amh_connect ()
socket listen, for slave side
int amh_connect (const char *address)
socket connect, for master side
int amh_close ()
close socket connection
int amh_send (const AsyncMessage *msg)
send a message
int amh_recv (AsyncMessage **pmsg)
receive a message (non-blocking)
Private Attributes
bool connected
flag: is the TCP socket connected?
int tcpfd
TCP socket.
Static Private Attributes
static const int HDRLEN = sizeof(AsyncMessage) - sizeof(char*)
header length of a async message
Detailed Description
Class for an asynchronous message handler.
This class handles all the socket operation between master and slaves.
Definition at line 56 of file asyncmsg.h.
Constructor & Destructor Documentation
AsyncMessageHandler::AsyncMessageHandler ()
constructor
Definition at line 55 of file asyncmsg.cc.
References connected, and tcpfd.
 {
         connected = false;
         tcpfd = 0;
 }
AsyncMessageHandler::~AsyncMessageHandler ()
destructor
Definition at line 63 of file asyncmsg.cc.
References amh_close(), and connected.
 {
         if (connected) amh_close();
 }
Member Function Documentation
bool AsyncMessageHandler::isconnected () inline
is the network socket currently connected?
Definition at line 66 of file asyncmsg.h.
References connected.
 { return connected; }
int AsyncMessageHandler::amh_connect ()
socket listen, for slave side
Definition at line 70 of file asyncmsg.cc.
References BACKLOG, connected, PORT, and tcpfd.
Referenced by VESlave::master_connect(), and VESlave::slave_mainloop().
 {
         if (connected) return -EEXIST;
         int sockfd, newsockfd;
         socklen_t clilen;
         struct sockaddr_in serv_addr, cli_addr;
         int reuseaddr = 1;
         sockfd = socket(AF_INET, SOCK_STREAM, 0);
         if (sockfd < 0) return -ENODEV;
         bzero(&serv_addr, sizeof(serv_addr));
         serv_addr.sin_family = AF_INET;
         serv_addr.sin_addr.s_addr = INADDR_ANY;
         serv_addr.sin_port = htons(PORT);
         setsockopt(sockfd, SOL_SOCKET, SO_REUSEADDR, &reuseaddr, sizeof(reuseaddr));
         if (bind(sockfd, (struct sockaddr*)&serv_addr, sizeof(serv_addr)) < 0) return -EACCES;
         if (listen(sockfd, BACKLOG) < 0) return -EIO;
         clilen = sizeof(cli_addr);
         newsockfd = accept(sockfd, (struct sockaddr*)&cli_addr, &clilen);
         close(sockfd);
         if (newsockfd < 0) return -EIO;
         int on = 1;
         setsockopt(newsockfd, IPPROTO_TCP, TCP_NODELAY, &on, sizeof(on));
         tcpfd = newsockfd;
         connected = true;
         return 0;
 }
int AsyncMessageHandler::amh_connect (const char * address)
socket connect, for master side
Definition at line 103 of file asyncmsg.cc.
References connected, PORT, and tcpfd.
 {
         if (connected) return -EEXIST;
         int sockfd;
         struct sockaddr_in serv_addr;
         struct hostent *server;
         sockfd = socket(AF_INET, SOCK_STREAM, 0);
         if (sockfd < 0) return -ENODEV;
         server = gethostbyname(hostname);
         if (!server) return -EBADF;
         bzero(&serv_addr, sizeof(serv_addr));
         serv_addr.sin_family = AF_INET;
         bcopy(server->h_addr, &serv_addr.sin_addr.s_addr, server->h_length);
         serv_addr.sin_port = htons(PORT);
         if (connect(sockfd,(struct sockaddr *) &serv_addr,sizeof(serv_addr)) < 0) return -EIO;
         int on = 1;
         setsockopt(sockfd, IPPROTO_TCP, TCP_NODELAY, &on, sizeof(on));
         tcpfd = sockfd;
         connected = true;
         return 0;
 }
int AsyncMessageHandler::amh_close ()
close socket connection
Definition at line 131 of file asyncmsg.cc.
References connected, and tcpfd.
Referenced by VESlave::master_disconnect(), VESlave::slave_mainloop(), and ~AsyncMessageHandler().
 {
         if (!connected) return -ENXIO;
         close(tcpfd);
         tcpfd = 0;
         connected = false;
         return 0;
 }
int AsyncMessageHandler::amh_send (const AsyncMessage * msg)
send a message
Definition at line 142 of file asyncmsg.cc.
References connected, HDRLEN, AsyncMessage::payload, AsyncMessage::payloadlen, and tcpfd.
 {
         if (!connected) return -ENXIO;
         int size = HDRLEN + msg->payloadlen;
         char *buf = new char[size];
         if (!buf) return -ENOMEM;
         memcpy(buf, msg, HDRLEN);
         if (msg->payloadlen) memcpy(buf + HDRLEN, msg->payload, msg->payloadlen);
         int sent = 0;
         while (sent < size) {
                 int n = write(tcpfd, buf + sent, size - sent);
                 if (n <= 0) { sched_yield(); continue; }
                 sent += n;
         }
         delete buf;
         return 0;
 }
int AsyncMessageHandler::amh_recv (AsyncMessage ** pmsg)
receive a message (non-blocking)
Definition at line 166 of file asyncmsg.cc.
References connected, HDRLEN, AsyncMessage::payload, AsyncMessage::payloadlen, SOCKET_TIMEOUT, and tcpfd.
Referenced by VESlave::slave_mainloop().
 {
         if (!connected) return -ENXIO;
         fd_set rset;
         FD_ZERO(&rset);
         FD_SET(tcpfd, &rset);
         struct timeval tv;
         tv.tv_sec = 0;
         tv.tv_usec = SOCKET_TIMEOUT;
         int sel = select(tcpfd+1, &rset, NULL, NULL, &tv);
         if (sel <= 0) { *pmsg = NULL; return 0; }
         char buf[HDRLEN];
         int rcvd = read(tcpfd, buf, HDRLEN);
         if (rcvd <= 0) { *pmsg = NULL; return 0; }
         while (rcvd < HDRLEN) {
                 int n = read(tcpfd, buf + rcvd, HDRLEN - rcvd);
                 if (n <= 0) { sched_yield(); continue; }
                 rcvd += n;
         }
         AsyncMessage *msg = new AsyncMessage;
         if (!msg) return -ENOMEM;
         memcpy(msg, buf, HDRLEN);
         *pmsg = msg;
         if (!msg->payloadlen) return 0;
         msg->payload = new char[msg->payloadlen];
         if (!msg->payload) return -ENOMEM;
         rcvd = 0;
         while (rcvd < msg->payloadlen) {
                 int n = read(tcpfd, msg->payload + rcvd, msg->payloadlen - rcvd);
                 if (n <= 0) { sched_yield(); continue; }
                 rcvd += n;
         }
         return 0;
 }
Member Data Documentation
const int AsyncMessageHandler::HDRLEN = sizeof(AsyncMessage) - sizeof(char*) static private
header length of a async message
Definition at line 85 of file asyncmsg.h.
Referenced by amh_recv(), and amh_send().
bool AsyncMessageHandler::connected private
flag: is the TCP socket connected?
Definition at line 88 of file asyncmsg.h.
Referenced by amh_close(), amh_connect(), amh_recv(), amh_send(), AsyncMessageHandler(), isconnected(), and ~AsyncMessageHandler().
int AsyncMessageHandler::tcpfd private
TCP socket.
Definition at line 91 of file asyncmsg.h.
Referenced by amh_close(), amh_connect(), amh_recv(), amh_send(), and AsyncMessageHandler().
The documentation for this class was generated from the following files:
asyncmsg.h
asyncmsg.cc