S3F: s3f::s3fnet::TrafficPattern Class Reference
s3f::s3fnet::TrafficPattern Class Reference
A traffic pattern in the traffic specification.
#include <traffic.h>
Public Member Functions
TrafficPattern ()
The constructor.
virtual ~TrafficPattern ()
The destructor.
void config (s3f::dml::Configuration *cfg)
Configure the traffic pattern.
void display (int indent=0)
Print out this traffic pattern.
Public Attributes
Nhi client
The nhi address of the client in this traffic pattern.
TRAFFIC_SERVERDATA_VECTOR servers
The list of servers in this traffic pattern.
Protected Member Functions
void deallocate_servers ()
Deallocate the content of the servers vector.
void configure_servers (s3f::dml::Configuration *cfg)
Read server data from DML.
Detailed Description
A traffic pattern in the traffic specification.
A traffic pattern is defined as a mapping from a client nhi to a list of servers. Traffic patters are specified in DML.
Definition at line 102 of file traffic.h.
Constructor & Destructor Documentation
s3f::s3fnet::TrafficPattern::TrafficPattern ()
The constructor.
Definition at line 156 of file traffic.cc.
 {}
s3f::s3fnet::TrafficPattern::~TrafficPattern () virtual
The destructor.
Definition at line 158 of file traffic.cc.
References deallocate_servers().
 {
   deallocate_servers();
 }
Member Function Documentation
void s3f::s3fnet::TrafficPattern::config (s3f::dml::Configuration * cfg)
Configure the traffic pattern.
Definition at line 170 of file traffic.cc.
References client, configure_servers(), s3f::s3fnet::Nhi::convert(), s3f::s3fnet::error_quit(), s3f::s3fnet::Nhi::NHI_MACHINE, s3f::s3fnet::Nhi::toString(), TRAFFIC_CLIENT, TRAFFIC_DUMP, and TRAFFIC_SERVERS.
Referenced by s3f::s3fnet::Traffic::config().
 {
   // configure the client for a traffic pattern. this is a must-set
   // attribute.
   char* client_string = (char*)cfg->findSingle(TRAFFIC_CLIENT);
   if(!client_string) {
     error_quit("ERROR: TrafficPattern::config(), "
                "missing TRAFFIC.PATTERN.CLIENT attribute!\n");
   } else{
     if(s3f::dml::dmlConfig::isConf(client_string))
       error_quit("ERROR: TrafficPattern::config(), "
                  "invalid TRAFFIC.PATTERN.CLIENT attribute.\n");
     //client.convert(client_string, Nhi::NHI_MACHINE | Nhi::NHI_NET);
     client.convert(client_string, Nhi::NHI_MACHINE); //removed the Nhi:NHI_NET here, not sure if I missed anything
     TRAFFIC_DUMP(printf("client \"%s\":\n", client.toString()));
   }
   // configure the servers in a traffic pattern
   s3f::dml::Enumeration* ss = cfg->find(TRAFFIC_SERVERS);
   while(ss->hasMoreElements()) {
     s3f::dml::Configuration* scfg =
       (s3f::dml::Configuration*)ss->nextElement();
     if(!s3f::dml::dmlConfig::isConf(scfg))
       error_quit("ERROR: TrafficPattern::config(), "
                  "invalid TRAFFIC.PATTERN.SERVERS attribute.\n");
     configure_servers(scfg);
   }
   delete ss;
 }
void s3f::s3fnet::TrafficPattern::display (int indent = 0)
Print out this traffic pattern.
Definition at line 270 of file traffic.cc.
References client, DML_OBJECT_INDENT, servers, and s3f::s3fnet::Nhi::toString().
 {
   char str[18];
   client.toString(str);
   printf("%*cPattern [\n", indent, ' ');
   indent += DML_OBJECT_INDENT;
   printf("%*cclient %s\n", indent, ' ', str);
   // Display servers
   printf("%*cservers [", indent, ' ');
   for(unsigned i = 0; i < servers.size(); i++)
   {
     printf("port %d nhi ", servers[i]->port);
     printf(" ");
   }
   printf("]\n%*c]\n", indent-DML_OBJECT_INDENT, ' ');
 }
void s3f::s3fnet::TrafficPattern::deallocate_servers () protected
Deallocate the content of the servers vector.
Definition at line 163 of file traffic.cc.
References servers.
Referenced by ~TrafficPattern().
 {
   for(unsigned i=0; i<servers.size(); i++)
     delete servers[i];
   servers.clear();
 }
void s3f::s3fnet::TrafficPattern::configure_servers (s3f::dml::Configuration * cfg) protected
Read server data from DML.
Definition at line 200 of file traffic.cc.
References s3f::s3fnet::Nhi::convert(), s3f::s3fnet::error_quit(), s3f::s3fnet::Nhi::NHI_INTERFACE, s3f::s3fnet::Nhi::readNhiRange(), servers, s3f::s3fnet::sstrdup(), TRAFFIC_SERVER_LIST, TRAFFIC_SERVER_NHI, TRAFFIC_SERVER_NHI_RANGE, TRAFFIC_SERVER_PORT, and TRAFFIC_SERVER_SESSIONS.
Referenced by config().
 {
   // read servers like:
   //   servers [port 10 nhi 1:2(0)]
   //   servers [port 10 nhi_range [from 1:2(0) to 1:5(0)]]
   char* server_list_string = (char*)cfg->findSingle(TRAFFIC_SERVER_LIST);
   if(server_list_string)
   {
     if(s3f::dml::dmlConfig::isConf(server_list_string))
       error_quit("ERROR: TrafficPattern::configure_servers(), invalid traffic SERVERS.LIST attribute.\n");
     server_list_string = sstrdup(server_list_string);
   }
   int new_port = 0;
   char* server_port_string = (char*)cfg->findSingle(TRAFFIC_SERVER_PORT);
   if(server_port_string)
   {
     if(s3f::dml::dmlConfig::isConf(server_port_string))
       error_quit("ERROR: TrafficPattern::configure_servers(), invalid traffic SERVERS.PORT attribute.\n");
     new_port = atoi(server_port_string);
   }
   int new_sessions = 1;
   char* sessions_string = (char*)cfg->findSingle(TRAFFIC_SERVER_SESSIONS);
   if(sessions_string)
   {
     if(s3f::dml::dmlConfig::isConf(sessions_string))
       error_quit("ERROR: TrafficPattern::configure_servers(), invalid traffic SERVERS.SESSIONS attribute.\n");
     new_sessions = atoi(sessions_string);
   }
   s3f::dml::Enumeration* ss = cfg->find(TRAFFIC_SERVER_NHI);
   while(ss->hasMoreElements())
   {
     char* nhi_string = (char*)ss->nextElement();
     if(s3f::dml::dmlConfig::isConf(nhi_string))
       error_quit("ERROR: TrafficPattern::configure_servers(), invalid traffic SERVERS.NHI attribute.\n");
     Nhi* nhi = new Nhi;
     if(0 != nhi->convert(nhi_string, Nhi::NHI_INTERFACE))
     {
       error_quit("ERROR: TrafficPattern::configure_servers(), bad server nhi address: \"%s\".\n", nhi_string);
     }
     TrafficServerData* sd = new TrafficServerData(nhi, new_port, sstrdup(server_list_string),new_sessions);
     servers.push_back(sd);
   }
   delete ss;
   ss = cfg->find(TRAFFIC_SERVER_NHI_RANGE);
   while(ss->hasMoreElements())
   {
     s3f::dml::Configuration* rcfg = (s3f::dml::Configuration*)ss->nextElement();
     if(!s3f::dml::dmlConfig::isConf(rcfg))
       error_quit("ERROR: TrafficPattern::configure_servers(), invalid traffic SERVERS.NHI_RANGE attribute.\n");
     S3FNET_POINTER_VECTOR nhivector;
     if(0 != Nhi::readNhiRange(nhivector, rcfg))
     {
       error_quit("ERROR: TrafficPattern::configure_servers(), bad server nhi_range.\n");
     }
     for(unsigned i=0; i < nhivector.size(); i++)
     {
       TrafficServerData* sd = new TrafficServerData((Nhi*)nhivector[i], new_port, sstrdup(server_list_string), new_sessions);
       servers.push_back(sd);
     }
   }
   delete ss;
   if(server_list_string) delete[] server_list_string;
 }
Member Data Documentation
Nhi s3f::s3fnet::TrafficPattern::client
The nhi address of the client in this traffic pattern.
Definition at line 125 of file traffic.h.
Referenced by config(), display(), s3f::s3fnet::Traffic::getServers(), and s3f::s3fnet::Traffic::resolve_nhi().
TRAFFIC_SERVERDATA_VECTOR s3f::s3fnet::TrafficPattern::servers
The list of servers in this traffic pattern.
Definition at line 128 of file traffic.h.
Referenced by configure_servers(), deallocate_servers(), display(), and s3f::s3fnet::Traffic::getServers().
The documentation for this class was generated from the following files:
traffic.h
traffic.cc