S3F: s3f::s3fnet::OpenFlowMessage Class Reference
s3f::s3fnet::OpenFlowMessage Class Reference
Message between OpenFlow controller and OpenFlow switch, for both directions.
#include <openflow_message.h>
Public Member Functions
OpenFlowMessage ()
the default constructor
OpenFlowMessage (ofpbuf *buf, uint32_t pkt_uid, OpenFlowSwitchSession *snd_switch)
the constructor used for packet from switch to controller
OpenFlowMessage (ofp_flow_mod *msg, uint16_t len, OpenFlowSwitchSession *snd_switch, ofpbuf *buf, uint32_t pkt_uid)
the constructor used for packet from controller to switch
OpenFlowMessage (ofp_flow_mod *msg, uint16_t len)
OpenFlowMessage (const OpenFlowMessage &msg)
the copy constructor
virtual ProtocolMessage * clone ()
This method is required for each derived class.
virtual int type ()
each protocol message must have a unique type
virtual int packingSize ()
return the buffer size needed to serialize this protocol message
virtual int realByteCount ()
return the number of bytes used by the protocol message on a real network
void carryPayload (ProtocolMessage *payload)
This method appends another protocol message to this protocol message and treats it as the payload.
virtual ProtocolMessage * dropPayload ()
If there is a payload, drop it from the linked list, then return it.
ProtocolMessage * payload ()
Returns the next header.
virtual void erase ()
This method is called to release the memory of this packet and its subsequent payload.
virtual void erase_all ()
int totalPackingSize ()
Returns the total byte count (in simulation) including the payload.
int totalRealBytes ()
Returns the total number of bytes of the protocol message including the payload in the real-world.
ProtocolMessage * getMessageByType (int type_code)
Given a protocol message type code, this method goes through the message chain starting from this message, and returns the first ProtocolMessage that has this type code.
unsigned int get_type ()
void inc_evts ()
int dec_evts ()
Static Public Member Functions
static int registerMessage (ProtocolMessage *(*fct)(), int type)
Called by S3FNET_REGISTER_MESSAGE macro to register a protocol message.
Public Attributes
ofpbuf * buffer
uint32_t packet_uid
ofp_flow_mod * ofm
uint16_t length
OpenFlowSwitchSession * sender
the OpenFlow switch that sends the packet
Static Public Attributes
static S3FNET_INT2PTR_MAP * registered_messages = 0
A mapping between message type and message constructor.
Protected Member Functions
virtual ~OpenFlowMessage ()
the destructor is protected to avoid direct deletion; erase() should be called upon reclaiming a protocol message
Protected Attributes
unsigned int __type
int __evts
Detailed Description
Message between OpenFlow controller and OpenFlow switch, for both directions.
Not used by entity-based controllers.
Definition at line 26 of file openflow_message.h.
Constructor & Destructor Documentation
s3f::s3fnet::OpenFlowMessage::OpenFlowMessage ()
the default constructor
Definition at line 15 of file openflow_message.cc.
Referenced by clone().
                                  : buffer(0), packet_uid(-1), ofm(0), length(0), sender(0)
 {}
s3f::s3fnet::OpenFlowMessage::OpenFlowMessage (ofpbuf * buf, uint32_t pkt_uid, OpenFlowSwitchSession * snd_switch)
the constructor used for packet from switch to controller
Definition at line 18 of file openflow_message.cc.
                                                                                                  :
                   buffer(buf), packet_uid(pkt_uid), sender(snd_switch), ofm(0), length(0)
 {}
s3f::s3fnet::OpenFlowMessage::OpenFlowMessage (ofp_flow_mod * msg, uint16_t len, OpenFlowSwitchSession * snd_switch, ofpbuf * buf, uint32_t pkt_uid)
the constructor used for packet from controller to switch
Definition at line 22 of file openflow_message.cc.
                                                                                                                                   :
                         buffer(buf), packet_uid(pkt_uid), sender(snd_switch), ofm(msg), length(len)
 {}
s3f::s3fnet::OpenFlowMessage::OpenFlowMessage (ofp_flow_mod * msg, uint16_t len)
Definition at line 26 of file openflow_message.cc.
                                                                 :
                         buffer(0), packet_uid(-1), sender(0), ofm(msg), length(len)
 {}
s3f::s3fnet::OpenFlowMessage::OpenFlowMessage (const OpenFlowMessage & msg)
the copy constructor
Definition at line 30 of file openflow_message.cc.
                                                            :
                   ProtocolMessage(msg), // the base class's copy constructor must be called
                   buffer(msg.buffer), packet_uid(msg.packet_uid), sender(msg.sender),
                   ofm(msg.ofm), length(msg.length)
 {}
s3f::s3fnet::OpenFlowMessage::~OpenFlowMessage () protected virtual
the destructor is protected to avoid direct deletion; erase() should be called upon reclaiming a protocol message
Definition at line 36 of file openflow_message.cc.
 {}
Member Function Documentation
virtual ProtocolMessage* s3f::s3fnet::OpenFlowMessage::clone () inline virtual
This method is required for each derived class.
This message should be defined in the derived class as something like:
ProtocolMessage* MyMessage::clone()
  { return new MyMessage(*this); }
, where MyMessage is a derived class of ProtocolMessage.
Implements s3f::s3fnet::ProtocolMessage.
Definition at line 46 of file openflow_message.h.
References OpenFlowMessage().
 { return new OpenFlowMessage(*this); }
virtual int s3f::s3fnet::OpenFlowMessage::type () inline virtual
each protocol message must have a unique type
Implements s3f::s3fnet::ProtocolMessage.
Definition at line 49 of file openflow_message.h.
References s3f::s3fnet::S3FNET_PROTOCOL_TYPE_OPENFLOW_CONTROLLER.
 { return S3FNET_PROTOCOL_TYPE_OPENFLOW_CONTROLLER; }
int s3f::s3fnet::OpenFlowMessage::packingSize () virtual
return the buffer size needed to serialize this protocol message
Reimplemented from s3f::s3fnet::ProtocolMessage.
Definition at line 38 of file openflow_message.cc.
References buffer, length, and s3f::s3fnet::ProtocolMessage::packingSize().
 {
         // must add the parent class packing size
         int mysiz = ProtocolMessage::packingSize();
         if(length > 0) //controller to switch msg
         {
                 mysiz += length;
         }
         else //switch to controller msg
         {
                 mysiz += buffer->size;
         }
         return mysiz;
 }
int s3f::s3fnet::OpenFlowMessage::realByteCount () virtual
return the number of bytes used by the protocol message on a real network
Implements s3f::s3fnet::ProtocolMessage.
Definition at line 54 of file openflow_message.cc.
References buffer, and length.
 {
         if(length > 0) //controller to switch msg
                 return length;
         else //switch to controller msg
                 return buffer->size;
 }
int s3f::s3fnet::ProtocolMessage::registerMessage (ProtocolMessage *(*)() fct, int type) static inherited
Called by S3FNET_REGISTER_MESSAGE macro to register a protocol message.
Definition at line 96 of file protocol_message.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolMessage::registered_messages, and S3FNET_MAKE_PAIR.
 {
   // allocate the global data structure if it's not there
   if(!registered_messages)
   {
     registered_messages = new S3FNET_INT2PTR_MAP;
     assert(registered_messages);
   }
   // insert the mapping; check if duplicated
   if(!registered_messages->insert(S3FNET_MAKE_PAIR(type, (void*)fct)).second)
     error_quit("ERROR: duplicate protocol message types: %d\n", type);
   // we need to return something so that S3FNET_REGISTER_MESSAGE macro works
   return 0;
 }
void s3f::s3fnet::ProtocolMessage::carryPayload (ProtocolMessage * payload) inherited
This method appends another protocol message to this protocol message and treats it as the payload.
Definition at line 27 of file protocol_message.cc.
References s3f::s3fnet::error_retn(), and s3f::s3fnet::ProtocolMessage::next.
Referenced by s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::send(), and s3f::s3fnet::TCPSession::send_data().
 {
   // adjust the links, warning if found dangling nodes
   if(next)
   {
     error_retn("WARNING: ProtocolMessage::carryPayload(), overwrite pre-exist payload (may cause memory leak)!\n");
     delete next;
   }
   next = load;
 }
ProtocolMessage * s3f::s3fnet::ProtocolMessage::dropPayload () virtual inherited
If there is a payload, drop it from the linked list, then return it.
Return NULL if there is no payload.
Definition at line 38 of file protocol_message.cc.
References s3f::s3fnet::ProtocolMessage::next.
Referenced by s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::SimpleMac::pop(), and s3f::s3fnet::UDPSession::receive().
 {
   // sever the link between this node and the payload and return it
   ProtocolMessage* pmsg = next;
   next = 0;
   return pmsg;
 }
ProtocolMessage* s3f::s3fnet::ProtocolMessage::payload () inline inherited
Returns the next header.
Definition at line 103 of file protocol_message.h.
References s3f::s3fnet::ProtocolMessage::next.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::BufferFromPacket(), s3f::s3fnet::DataMessage::DataMessage(), s3f::s3fnet::NetworkInterface::emu_packet_modify_iface(), s3f::s3fnet::DataMessage::packingSize(), s3f::s3fnet::DataMessage::realByteCount(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::TCPSession::receiver_recv_sack(), and s3f::s3fnet::DataMessage::~DataMessage().
 { return next; }
void s3f::s3fnet::ProtocolMessage::erase () virtual inherited
This method is called to release the memory of this packet and its subsequent payload.
One must avoid deleting a protocol message object directly. This requirement is necessary for the support to optimizations such as the reference counter.
For better protection, the destructor of the protocol message (and its extended classes) should be defined as protected.
Reimplemented from Message.
Definition at line 46 of file protocol_message.cc.
Referenced by s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::OpenFlowSwitchSession::HandleControlInput(), and s3f::s3fnet::SimpleMac::pop().
 {
   //printf("ProtocolMessage erased, type = %d\n", this->type());
   delete this;
 }
void s3f::s3fnet::ProtocolMessage::erase_all () virtual inherited
Reimplemented from Message.
Definition at line 52 of file protocol_message.cc.
References s3f::s3fnet::ProtocolMessage::erase_all(), and s3f::s3fnet::ProtocolMessage::next.
Referenced by s3f::s3fnet::ProtocolMessage::erase_all(), s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::IPSession::handle_pop_pkt(), and s3f::s3fnet::DummySession::pop().
 {
         if(this->next) this->next->erase_all();
     //printf("ProtocolMessage deleted, type = %d\n", this->type());
         delete this;
 }
int s3f::s3fnet::ProtocolMessage::totalPackingSize () inherited
Returns the total byte count (in simulation) including the payload.
Definition at line 60 of file protocol_message.cc.
References s3f::s3fnet::ProtocolMessage::next, s3f::s3fnet::ProtocolMessage::packingSize(), and s3f::s3fnet::ProtocolMessage::totalPackingSize().
Referenced by s3f::s3fnet::ProtocolMessage::totalPackingSize().
 {
   // add them all
   if(next)
           return packingSize()+next->totalPackingSize();
   else
           return packingSize();
 }
int s3f::s3fnet::ProtocolMessage::totalRealBytes () inherited
Returns the total number of bytes of the protocol message including the payload in the real-world.
Definition at line 74 of file protocol_message.cc.
References s3f::s3fnet::ProtocolMessage::next, s3f::s3fnet::ProtocolMessage::realByteCount(), and s3f::s3fnet::ProtocolMessage::totalRealBytes().
Referenced by s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::IPSession::push(), and s3f::s3fnet::ProtocolMessage::totalRealBytes().
 {
   // add them all
   if(next)
           return realByteCount()+next->totalRealBytes();
   else
           return realByteCount();
 }
ProtocolMessage * s3f::s3fnet::ProtocolMessage::getMessageByType (int type_code) inherited
Given a protocol message type code, this method goes through the message chain starting from this message, and returns the first ProtocolMessage that has this type code.
If none is found, NULL is returned.
Definition at line 83 of file protocol_message.cc.
References s3f::s3fnet::ProtocolMessage::next, and s3f::s3fnet::ProtocolMessage::type().
 {
   ProtocolMessage* cur = this;
   while(cur)
   {
     if(cur->type() == t) return cur;
     cur = cur->next;
   }
   return 0;
 }
unsigned int Message::get_type () inline inherited
Definition at line 23 of file message.h.
References Message::__type.
 { return __type; }
void Message::inc_evts () inline inherited
Definition at line 28 of file message.h.
References Message::__evts.
Referenced by Event::Event().
 { __evts++; }
int Message::dec_evts () inline inherited
Definition at line 29 of file message.h.
References Message::__evts.
Referenced by Event::~Event().
 { return --__evts; }
Member Data Documentation
ofpbuf* s3f::s3fnet::OpenFlowMessage::buffer
Definition at line 57 of file openflow_message.h.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::HandleControlInput(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), packingSize(), and realByteCount().
uint32_t s3f::s3fnet::OpenFlowMessage::packet_uid
Definition at line 58 of file openflow_message.h.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::HandleControlInput().
ofp_flow_mod* s3f::s3fnet::OpenFlowMessage::ofm
Definition at line 60 of file openflow_message.h.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::HandleControlInput(), and s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch().
uint16_t s3f::s3fnet::OpenFlowMessage::length
Definition at line 61 of file openflow_message.h.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::HandleControlInput(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), packingSize(), and realByteCount().
OpenFlowSwitchSession* s3f::s3fnet::OpenFlowMessage::sender
the OpenFlow switch that sends the packet
Definition at line 63 of file openflow_message.h.
Referenced by s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch().
S3FNET_INT2PTR_MAP * s3f::s3fnet::ProtocolMessage::registered_messages = 0 static inherited
A mapping between message type and message constructor.
Definition at line 158 of file protocol_message.h.
Referenced by s3f::s3fnet::ProtocolMessage::registerMessage().
unsigned int Message::__type protected inherited
Definition at line 31 of file message.h.
Referenced by Message::clone(), Message::get_type(), Message::Message(), and Message::operator=().
int Message::__evts protected inherited
Definition at line 32 of file message.h.
Referenced by Message::clone(), Message::dec_evts(), Message::inc_evts(), Message::Message(), and Message::operator=().
The documentation for this class was generated from the following files:
openflow_message.h
openflow_message.cc