S3F: s3f::s3fnet::CidrBlock Class Reference
s3f::s3fnet::CidrBlock Class Reference
A block of IP addresses.
#include <cidr.h>
Public Member Functions
CidrBlock ()
The default constructor.
CidrBlock (unsigned addr, int len)
The constructor with a set ip prefix.
virtual ~CidrBlock ()
The destructor.
void setPrefix (unsigned addr, int len)
Set the ip prefix of this CIDR block.
CidrBlock * getSubCidrBlock (long id)
Find a CIDR sub-block of a given id.
void addSubCidrBlock (long id, CidrBlock *cb)
Add a CIDR sub-block with a given id.
const IPPrefix & getPrefix ()
Get the prefix of this CIDR block.
void display (FILE *fp)
Display the CIDR out to the given file stream.
Protected Member Functions
typedef S3FNET_MAP (long, CidrBlock *) CidrTable
Protected Attributes
IPPrefix prefix
IP prefix for this block.
CidrTable sub_blocks
A mapping from id to CIDR sub-blocks.
Detailed Description
A block of IP addresses.
We use the Classless Inter-Domain Routing (CIDR) for IP address assignment. The CidrBlock class represents the hierarchical structure of the assigned IP addresses.
Definition at line 25 of file cidr.h.
Constructor & Destructor Documentation
s3f::s3fnet::CidrBlock::CidrBlock () inline
The default constructor.
Definition at line 39 of file cidr.h.
 {}
s3f::s3fnet::CidrBlock::CidrBlock (unsigned addr, int len) inline
The constructor with a set ip prefix.
Definition at line 42 of file cidr.h.
                                     :
     prefix(addr, len) {}
s3f::s3fnet::CidrBlock::~CidrBlock () virtual
The destructor.
Definition at line 15 of file cidr.cc.
References sub_blocks.
 {
   if (sub_blocks.size()) {
     for (CidrTable::iterator iter = sub_blocks.begin();
          iter != sub_blocks.end(); iter++) {
       delete iter->second;
     }
   }
 }
Member Function Documentation
typedef s3f::s3fnet::CidrBlock::S3FNET_MAP (long , CidrBlock *) protected
void s3f::s3fnet::CidrBlock::setPrefix (unsigned addr, int len)
Set the ip prefix of this CIDR block.
Definition at line 42 of file cidr.cc.
References s3f::s3fnet::IPPrefix::addr, s3f::s3fnet::IPPrefix::len, and prefix.
Referenced by s3f::s3fnet::NameService::config_net_cidr().
 {
   prefix.addr = addr;
   prefix.len = len;
 }
CidrBlock * s3f::s3fnet::CidrBlock::getSubCidrBlock (long id)
Find a CIDR sub-block of a given id.
Definition at line 25 of file cidr.cc.
References sub_blocks.
Referenced by s3f::s3fnet::Net::config_net(), and s3f::s3fnet::NameService::netnhi2prefix().
 {
   CidrTable::iterator iter = sub_blocks.find(id);
   if (iter == sub_blocks.end())
     return NULL;
   return iter->second;
 }
void s3f::s3fnet::CidrBlock::addSubCidrBlock (long id, CidrBlock * cb)
Add a CIDR sub-block with a given id.
Definition at line 33 of file cidr.cc.
References s3f::s3fnet::error_quit(), S3FNET_MAKE_PAIR, and sub_blocks.
Referenced by s3f::s3fnet::NameService::config_net_cidr(), and s3f::s3fnet::NameService::config_topnet_cidr().
 {
   assert(cb);
   if (!sub_blocks.insert(S3FNET_MAKE_PAIR(id, cb)).second) {
     error_quit("ERROR: CidrBlock::addSubCidrBlock(), "
                "CIDR id exists for id %lu\n", id);
   }
 }
const IPPrefix& s3f::s3fnet::CidrBlock::getPrefix () inline
Get the prefix of this CIDR block.
Definition at line 58 of file cidr.h.
References prefix.
Referenced by s3f::s3fnet::Net::config_net(), s3f::s3fnet::NameService::config_net_cidr(), and s3f::s3fnet::NameService::netnhi2prefix().
 { return prefix; }
void s3f::s3fnet::CidrBlock::display (FILE * fp)
Display the CIDR out to the given file stream.
Definition at line 48 of file cidr.cc.
References s3f::s3fnet::IPPrefix::addr, s3f::s3fnet::IPPrefix::ip2txt(), s3f::s3fnet::IPPrefix::len, and prefix.
 {
   fprintf(fp, "CIDR block, net prefix = %s/%d\n",
           IPPrefix::ip2txt(prefix.addr), prefix.len);
 }
Member Data Documentation
IPPrefix s3f::s3fnet::CidrBlock::prefix protected
IP prefix for this block.
Definition at line 32 of file cidr.h.
Referenced by display(), getPrefix(), and setPrefix().
CidrTable s3f::s3fnet::CidrBlock::sub_blocks protected
A mapping from id to CIDR sub-blocks.
Definition at line 35 of file cidr.h.
Referenced by addSubCidrBlock(), getSubCidrBlock(), and ~CidrBlock().
The documentation for this class was generated from the following files:
cidr.h
cidr.cc