S3F: s3f::s3fnet::Net Class Reference
s3f::s3fnet::Net Class Reference
A network.
#include <net.h>
Public Member Functions
Net (SimInterface *sim_interface)
The constructor used by the top net.
Net (SimInterface *sim_interface, Net *parent, long id)
The constructor used by nets other than the top net.
virtual ~Net ()
The destructor.
void config (s3f::dml::Configuration *cfg)
Configure this net from DML.
void init ()
Initialize the network.
virtual void display (int indent=0)
Displays the contents of this net.
DmlObject * nhi2obj (Nhi *nhi)
Resolves the given NHI address relative to this network.
IPADDR nicnhi2ip (S3FNET_STRING nhi)
Resolve the given interface NHI to an address.
const char * ip2nicnhi (IPADDR addr)
Resolve IPADDR to the corresponding nic nhi.
IPPrefix getPrefix ()
Get the IP prefix of this network.
S3FNET_INT2PTR_MAP & getHosts ()
Return all hosts in this level of net, including routers and switches.
S3FNET_INT2PTR_MAP & getNets ()
Return all subnets of this level of net.
S3FNET_POINTER_VECTOR & getLinks ()
Return all links in this level of net.
NameService * getNameService ()
Return global name resolution service.
NetworkInterface * nicnhi_to_obj (S3FNET_STRING nhi_str)
Return the network interface object by giving the NHI of the interface.
void register_host (Host *host, const S3FNET_STRING &name, bool isOpenVZEmu)
Register local host with given name.
void register_interface (NetworkInterface *iface, IPADDR ip, bool isOpenVZEmu)
Register local interface with the given IPADDR.
int control (int ctrltyp, void *ctrlmsg)
Ask some information about the current network For some queries, if the current network does not know the answer, it will forward the question to its parent network.
Net * getTopNet ()
return pointer of the top net
int openflow_controller_type ()
Return the type of openflow controller.
int openflow_controller_model ()
Return the model of openflow controller.
Controller * get_of_controller ()
Return the pointer to the non-entity-based controller.
Static Public Member Functions
static void getIdrangeLimits (s3f::dml::Configuration *rcfg, int &low, int &high)
Get the limits of an id-range.
Public Attributes
pthread_mutex_t of_buf_mutex
Add lock to access openflow buffer in openflow library (topnet only attribute).
long id
Every DmlObject object must have an ID obtained from the DML.
Nhi nhi
The nhi address to identify the object.
DmlObject * myParent
The parent.
Protected Member Functions
void config_top_net (s3f::dml::Configuration *cfg)
Configure the top net.
void config_link (s3f::dml::Configuration *cfg)
Configure a link.
void config_host (s3f::dml::Configuration *cfg, S3FNET_LONG_SET &uniqset, bool is_router=false, bool is_of_switch=false)
Configure a host.
void config_router (s3f::dml::Configuration *cfg, S3FNET_LONG_SET &uniqset)
Configure a router.
void config_of_switch (s3f::dml::Configuration *cfg, S3FNET_LONG_SET &uniqset)
Configure a openflow switch, currently simply indicate that the host is an openflow switch.
void config_net (s3f::dml::Configuration *cfg, S3FNET_LONG_SET &uniqset)
Configure a sub network.
void connect_links ()
This function is a helper function for the configure function.
void finish_config_top_net (s3f::dml::Configuration *cfg)
Process configurations that can't be done until all hosts/nets/links have been configured.
void load_fwdtable (s3f::dml::Configuration *cfg)
load forwarding tables of all the hosts containing in this net
Protected Attributes
SimInterface * sim_iface
the interface for running experiments; created in s3fnet.cc
int alignment
the timeline that the net (and all its hosts) are aligned to
SimCtrl * sim_ctrl
to control openvz-based emulation
int idbase
ID base of VE, also the first VE id.
int nr_ve
numbers of VEs */
bool isOpenVZEmu
whether openvz-based emulation is supported
struct sniff_ethernet * ethernet
The Ethernet header.
const struct sniff_ip * ip
The IP header.
const struct sniff_arp * arp
The ARP header.
const struct sniff_tcp * tcp
The TCP header.
const char * payload
Packet payload.
u_int size_ip
size of IP header
u_int size_tcp
size of TCP header
NetAccessory * netacc
The extra options for a net.
IPPrefix ip_prefix
IP prefix of this net.
S3FNET_INT2PTR_MAP hosts
List of hosts: a map from id to a pointer of the host.
S3FNET_INT2PTR_MAP nets
List of sub-networks: a map from id to a pointer of the network.
S3FNET_POINTER_VECTOR links
List of links.
CidrBlock * curCidr
Used by the config methods to refer the cidr block of the current network it is processing.
bool is_top_net
indicator on whether this net object is the top net
Net * top_net
NameService * namesvc
The global name resolution service, created at topnet, passed to all subnets.
Traffic * traffic
Controller * of_controller
The non-entity-based openflow controller, created at topnet during initialization.
long int pkt_from_ve_counter
store the total number of packet received from VEs
Detailed Description
A network.
The net class is the container for everything. All DML objects (including internal nets) must be contained in a net. Conceptually a net is just a collection of hosts and routers and other nets. The concept of a net is not that important for protocols like TCP and IP, but it's crucial for OSPF and BGP because a net can be an autonomous system (AS) or an OSPF area. This net class will start the configuration of the network. it will scan for hosts, routers, links and other nets in the DML and create/link these entities. nets also play a very important role in resolution of NHI addresses.
Definition at line 156 of file net.h.
Constructor & Destructor Documentation
s3f::s3fnet::Net::Net (SimInterface * sim_interface)
The constructor used by the top net.
Definition at line 31 of file net.cc.
References s3f::s3fnet::error_quit(), NET_DUMP, s3f::s3fnet::NO_OF_CONTROLLER, of_buf_mutex, of_controller, s3f::s3fnet::OF_DROP_CONTROLLER, OF_FLOW_EXPIRATION_TIME, s3f::s3fnet::OF_LEARNING_SWITCH_CONTROLLER, openflow_controller_model(), openflow_controller_type(), and s3f::s3fnet::Controller::type.
Referenced by config_net().
                                     :
                                 DmlObject(0), ip_prefix(0, 0), is_top_net(true), namesvc(0),
                                 sim_iface(sim_interface), top_net(this), traffic(0), netacc(0), sim_ctrl(0), pkt_from_ve_counter(0),
                                 idbase(0), nr_ve(0), isOpenVZEmu(false)
 {
         NET_DUMP(printf("new topnet.\n"));
         // create openflow controller (non-entity-type) based on the model specified in DML ("simulated_openflow_controller_model")
         if(openflow_controller_type() == 0)
         {
                 switch( openflow_controller_model() )
                 {
                 case OF_LEARNING_SWITCH_CONTROLLER:
                         of_controller = new LearningController();
                         of_controller->type = OF_LEARNING_SWITCH_CONTROLLER;
                         ((LearningController*)of_controller)->setFlowExpirationTime(OF_FLOW_EXPIRATION_TIME); //todo use dml attribute later
                         break;
                 case OF_DROP_CONTROLLER:
                         of_controller = new DropController();
                         of_controller->type = OF_DROP_CONTROLLER;
                         break;
                 case NO_OF_CONTROLLER:
                         of_controller = 0;
                         break;
                 default:
                         error_quit("Net:Net(), not able to create openflow controller, unknown type().");
                         break;
                 }
         }
         pthread_mutex_init(&of_buf_mutex,NULL);
 }
s3f::s3fnet::Net::Net (SimInterface * sim_interface, Net * parent, long id)
The constructor used by nets other than the top net.
Definition at line 67 of file net.cc.
References NET_DUMP.
                                                            :
                                 DmlObject(parent, myid), ip_prefix(0, 0), is_top_net(false), netacc(0),
                                 namesvc(parent->namesvc), sim_iface(sim_interface), top_net(parent->top_net),
                                 traffic(0), sim_ctrl(0), pkt_from_ve_counter(0), idbase(0), nr_ve(0), isOpenVZEmu(false)
 {
         NET_DUMP(printf("new subnet: id=%ld.\n", myid));
 }
s3f::s3fnet::Net::~Net () virtual
The destructor.
Definition at line 75 of file net.cc.
References hosts, is_top_net, isOpenVZEmu, links, NET_DUMP, netacc, nets, s3f::s3fnet::DmlObject::nhi, of_buf_mutex, pkt_from_ve_counter, and s3f::s3fnet::Nhi::toString().
 {
         NET_DUMP(printf("delete net: nhi=\"%s\".\n", nhi.toString()));
 #ifdef OPENVZ_EMULATION
         if(is_top_net == true && isOpenVZEmu == true)
         {
                 printf("total #packet in from VEs = %ld\n", pkt_from_ve_counter);
                 pthread_mutex_destroy(&of_buf_mutex);
         }
 #endif
         if(netacc) delete netacc;
         for(S3FNET_INT2PTR_MAP::iterator iter = nets.begin(); iter != nets.end(); iter++)
         {
                 assert(iter->second);
                 delete (Net*)(iter->second);
         }
         for(S3FNET_INT2PTR_MAP::iterator iter = hosts.begin(); iter != hosts.end(); iter++) {
                 assert(iter->second);
                 delete (Host*)(iter->second);
         }
         for(unsigned i=0; i<links.size(); i++)
         {
                 assert(links[i]);
                 delete (Link*)(links[i]);
         }
 }
Member Function Documentation
void s3f::s3fnet::Net::config (s3f::dml::Configuration * cfg)
Configure this net from DML.
Definition at line 107 of file net.cc.
References alignment, config_host(), config_link(), config_net(), config_of_switch(), config_router(), config_top_net(), SimCtrl::emu_reset(), SimCtrl::errcode2txt(), s3f::s3fnet::error_quit(), finish_config_top_net(), Interface::get_timeline_interface(), s3f::s3fnet::DmlObject::id, idbase, isOpenVZEmu, s3f::s3fnet::DmlObject::myParent, NET_DUMP, s3f::s3fnet::DmlObject::nhi, s3f::s3fnet::Nhi::NHI_NET, nr_ve, TimelineInterface::sc, SimCtrl::set_ve_boundary(), sim_ctrl, sim_iface, SimCtrl::siminf, s3f::s3fnet::Nhi::toString(), and s3f::s3fnet::Nhi::type.
Referenced by s3f::s3fnet::SimInterface::BuildModel(), and config_net().
 {
         NET_DUMP(printf("config().\n"));
         s3f::dml::Configuration* topcfg;
         char* str;
         set<long> uniqset;
         if(!myParent) //topnet
         {
                 config_top_net(cfg);
                 topcfg = cfg;
                 cfg = (s3f::dml::Configuration*)cfg->findSingle("net");
                 if(!cfg || !s3f::dml::dmlConfig::isConf(cfg))
                         error_quit("ERROR: missing or invalid (top) NET attribute.\n");
 #ifdef OPENVZ_EMULATION
                 char* str = (char*)cfg->findSingle("ve_id_base");
                 if(!str) idbase = -1;
                 else
                 {
                         if(s3f::dml::dmlConfig::isConf(str))
                                 error_quit("ERROR: invalid idbase attribute.\n");
                         idbase = atoi(str);
                         if(idbase < 100)
                                 error_quit("ERROR: idbase attribute must >= 100.\n");
                 }
                 str = (char*)cfg->findSingle("number_ve");
                 if(!str) nr_ve = -1;
                 else
                 {
                         if(s3f::dml::dmlConfig::isConf(str))
                                 error_quit("ERROR: invalid number_ve attribute.\n");
                         nr_ve = atoi(str);
                         if(nr_ve < 2)
                                 error_quit("ERROR: number_ve attribute must >= 2.\n");
                 }
                 if(idbase == -1 || nr_ve == -1)
                 {
                         isOpenVZEmu = false;
                 }
                 else
                 {
                         isOpenVZEmu = true;
                 }
                 //pass variables to sim_ctrl class in the TimelineInterface
                 if(isOpenVZEmu == true)
                 {
                         sim_ctrl = sim_iface->get_timeline_interface()->sc;
                         assert(sim_ctrl);
                         int return_code = sim_ctrl->set_ve_boundary(idbase, nr_ve);
                         if(return_code != 0)
{
                                 printf("error in set_ve_boundary(), error code = %s\n",
                                                 SimCtrl::errcode2txt(return_code));
                                 error_quit("Net::config(), sim_ctrl->set_ve_boundary\n");
                         }
                         return_code = sim_ctrl->emu_reset();
                         if(return_code != 0)
{
                                 printf("error in emu_reset(), error code = %s\n",
                                                 SimCtrl::errcode2txt(return_code));
                                 error_quit("Net::config(), sim_ctrl->emu_reset\n");
                         }
                         sim_ctrl->siminf = sim_iface;
                 }
                 NET_DUMP(printf("config(): openVZ idbase=%d, number_ve=%d.\n", idbase, nr_ve));
 #endif
         }
         else
         {
                 nhi = myParent->nhi;
                 nhi += id;
         }
         nhi.type = Nhi::NHI_NET;
         // config alignment
         // now timeline is assigned to the net, default one is 0,
         // todo we can provide option to assign to individual host
         str = (char*)cfg->findSingle("alignment");
         if(!str) alignment = 0;
         else
         {
                 if(s3f::dml::dmlConfig::isConf(str))
                         error_quit("ERROR: Net::config(), invalid NET.ALIGNMENT attribute.\n");
                 alignment = atoi(str);
         }
         NET_DUMP(printf("config(): nhi=\"%s\", alignment=\"%d\"\n", nhi.toString(), alignment));
         //config subnetworks, hosts and links in the sequence in dml, deepest first
         // config sub networks
         NET_DUMP(printf("net \"%s\" config sub networks.\n", nhi.toString()));
         s3f::dml::Enumeration* nenum = cfg->find("net");
         while(nenum->hasMoreElements())
         {
                 s3f::dml::Configuration* ncfg = (s3f::dml::Configuration*)nenum->nextElement();
                 if(!s3f::dml::dmlConfig::isConf(ncfg))
                         error_quit("ERROR: Net::config(), invalid NET.NET attribute.\n");
                 config_net(ncfg, uniqset);
         }
         delete nenum;
         // config hosts/routers/switches
         NET_DUMP(printf("net \"%s\" config hosts.\n", nhi.toString()));
         s3f::dml::Enumeration* henum = cfg->find("host");
         while (henum->hasMoreElements())
         {
                 s3f::dml::Configuration* hcfg = (s3f::dml::Configuration*)henum->nextElement();
                 if(!s3f::dml::dmlConfig::isConf(hcfg))
                         error_quit("ERROR: Net::config(), invalid NET.HOST attribute.\n");
                 config_host(hcfg, uniqset, false);
         }
         delete henum;
         henum = cfg->find("router");
         while (henum->hasMoreElements())
         {
                 s3f::dml::Configuration* hcfg = (s3f::dml::Configuration*)henum->nextElement();
                 if(!s3f::dml::dmlConfig::isConf(hcfg))
                         error_quit("ERROR: Net::config(), invalid NET.ROUTER attribute.\n");
                 config_router(hcfg, uniqset);
         }
         delete henum;
         henum = cfg->find("ofswitch");
         while (henum->hasMoreElements())
         {
                 s3f::dml::Configuration* hcfg = (s3f::dml::Configuration*)henum->nextElement();
                 if(!s3f::dml::dmlConfig::isConf(hcfg))
                         error_quit("ERROR: Net::config(), invalid NET.openflow_switch attribute.\n");
                 config_of_switch(hcfg, uniqset);
         }
         delete henum;
         // config links
         NET_DUMP(printf("net \"%s\" config links.\n", nhi.toString()));
         s3f::dml::Enumeration* lenum = cfg->find("link");
         while(lenum->hasMoreElements())
         {
                 s3f::dml::Configuration* lcfg = (s3f::dml::Configuration*)lenum->nextElement();
                 if(!s3f::dml::dmlConfig::isConf(lcfg))
                         error_quit("ERROR: Net::config(), invalid NET.LINK attribute.\n");
                 config_link(lcfg);
         }
         delete lenum;
         if(!myParent) finish_config_top_net(topcfg);
 }
void s3f::s3fnet::Net::init ()
Initialize the network.
This function is called after the entire network has been read from the DML but before the simulation actually starts.
Definition at line 377 of file net.cc.
References SimCtrl::get_vehandle(), idbase, s3f::s3fnet::Traffic::init(), isOpenVZEmu, links, s3f::s3fnet::DmlObject::myParent, s3f::s3fnet::NET_ACCESSORY_TRAFFIC, NET_DUMP, netacc, nets, s3f::s3fnet::DmlObject::nhi, nr_ve, s3f::s3fnet::NetAccessory::requestAttribute(), sim_ctrl, s3f::s3fnet::Nhi::toString(), and traffic.
Referenced by s3f::s3fnet::SimInterface::BuildModel().
 {
         NET_DUMP(printf("net \"%s\" init.\n", nhi.toString()));
         if(!myParent) // top net
         {
                 if(netacc)
                 {
                         // find the traffic attribute; initialize the traffic
                         Traffic* traffic = 0;
                         if(netacc->requestAttribute(NET_ACCESSORY_TRAFFIC, (void*&)traffic))
{
                                 if(traffic) traffic->init();
                         }
                 }
 #ifdef OPENVZ_EMULATION
                 //init ve handler, store send queue and recv queue in topnet
                 if(isOpenVZEmu == true)
                 {
                         for (int i = 0; i < nr_ve; i++)
{
                                 VEHandle* vh = sim_ctrl->get_vehandle(idbase+i);
                                 ve.push_back(vh);
                         }
                 }
 #endif
         }
         // initialize nets
         for(S3FNET_INT2PTR_MAP::iterator iter = nets.begin(); iter != nets.end(); iter++)
         {
                 ((Net*)iter->second)->init();
         }
         // initialize links.
         // Links must be initialized before hosts because protocols which are initialized with each host might want links initialized.
         for(unsigned i=0; i < links.size(); i++)
         {
                 ((Link*)links[i])->init();
         }
 }
void s3f::s3fnet::Net::display (int indent = 0) virtual
Displays the contents of this net.
Reimplemented from s3f::s3fnet::DmlObject.
Definition at line 419 of file net.cc.
References s3f::s3fnet::IPPrefix::display(), DML_OBJECT_INDENT, hosts, ip_prefix, links, nets, s3f::s3fnet::DmlObject::nhi, and s3f::s3fnet::Nhi::toString().
 {
         char strNhi[50];
         nhi.toString(strNhi);
         printf("%*cNet [\n", indent, ' ');
         indent += DML_OBJECT_INDENT;
         printf("%*cnhi %s\n", indent, ' ', strNhi);
         printf("%*cip_prefix ", indent, ' ');
         ip_prefix.display();
         printf("\n");
         // display hosts/routers
         for(S3FNET_INT2PTR_MAP::iterator iter = hosts.begin();
                         iter != hosts.end(); iter++)
                 ((Host*)(iter->second))->display(indent);
         // display nets
         for(S3FNET_INT2PTR_MAP::iterator iter = nets.begin();
                         iter != nets.end(); iter++)
                 ((Net*)(iter->second))->display(indent);
         // display Links
         for(unsigned i = 0; i < links.size(); i++)
                 ((Link*)links[i])->display(indent);
         printf("%*c]\n", indent-DML_OBJECT_INDENT, ' ');
 }
DmlObject * s3f::s3fnet::Net::nhi2obj (Nhi * nhi)
Resolves the given NHI address relative to this network.
Returns NULL if no such object exists in this network. Depending on the type of NHI, we resolve net/host/interface addresses. It is important that the NHI must have determined its type before this method can be called.
Definition at line 291 of file net.cc.
References hosts, s3f::s3fnet::Nhi::ids, namesvc, nets, nhi2obj(), s3f::s3fnet::Nhi::NHI_INTERFACE, s3f::s3fnet::Nhi::NHI_NET, s3f::s3fnet::NameService::nicnhi2iface(), s3f::s3fnet::S3FNET_VECTOR(), s3f::s3fnet::Nhi::start, s3f::s3fnet::Nhi::toStlString(), and s3f::s3fnet::Nhi::type.
Referenced by nhi2obj(), and s3f::s3fnet::Traffic::resolve_nhi().
 {
         // if it's a network interface, use nicnhi2iface_map in the namesvc
         if(pNhi->type == Nhi::NHI_INTERFACE)
         {
                 return namesvc->nicnhi2iface(pNhi->toStlString());
         }
         // if it's host or net NHI, search in its nets / hosts
         S3FNET_VECTOR(long)* pIDs = &(pNhi->ids);
         int origStart = pNhi->start;
         int len = pIDs->size() - origStart;;
         int type = pNhi->type;
         // The maximum length for the nhi to be in this net.
         int maxlength = (type == Nhi::NHI_INTERFACE)?2:1;
         // If the NHI is in some other Net, let that net do the work
         if(len > maxlength)
         {
                 int id = (*pIDs)[origStart];
                 // Find the Net with this id.
                 S3FNET_INT2PTR_MAP::iterator iter = nets.find(id);
                 if(iter == nets.end()) return 0;
                 Net* pNet = (Net*)iter->second;
                 pNhi->start++;
                 DmlObject* pObject = pNet->nhi2obj(pNhi);
                 pNhi->start = origStart;
                 return pObject;
         }
         // The net/machine is in this net.
         int id = (*pIDs)[origStart];
         if(type == Nhi::NHI_NET)
         {
                 S3FNET_INT2PTR_MAP::iterator iter = nets.find(id);
                 if(iter == nets.end()) return 0;
                 return (Net*)iter->second;
         }
         else
         {
                 S3FNET_INT2PTR_MAP::iterator iter = hosts.find(id);
                 if(iter == hosts.end()) return 0;
                 return  (Host*)iter->second;
         }
 }
IPADDR s3f::s3fnet::Net::nicnhi2ip (S3FNET_STRING nhi)
Resolve the given interface NHI to an address.
If failed, it returns IPADDR_INVALID.
Definition at line 285 of file net.cc.
References namesvc, and s3f::s3fnet::NameService::nhi2ip().
 {
         assert(namesvc);
         return namesvc->nhi2ip(nhi_str);
 }
const char* s3f::s3fnet::Net::ip2nicnhi (IPADDR addr)
Resolve IPADDR to the corresponding nic nhi.
If failed, it returns null.
IPPrefix s3f::s3fnet::Net::getPrefix () inline
Get the IP prefix of this network.
Definition at line 201 of file net.h.
 { return ip_prefix; }
void s3f::s3fnet::Net::getIdrangeLimits (s3f::dml::Configuration * rcfg, int & low, int & high) static
Get the limits of an id-range.
Definition at line 337 of file net.cc.
References s3f::s3fnet::error_quit().
Referenced by s3f::s3fnet::Host::config(), config_host(), and config_net().
 {
         // get id start and end
         char* str = (char*)cfg->findSingle("id");
         if(str) {
                 if(s3f::dml::dmlConfig::isConf(str))
                         error_quit("ERROR: Net::getIdrangeLimits(), invalid ID attribute.\n");
                 low = high = atoi(str);
                 return;
         }
         s3f::dml::Configuration* rcfg = (s3f::dml::Configuration*)
                 cfg->findSingle("idrange");
         if(!rcfg)
                 error_quit("Error: Net::getIdrangeLimits(), "
                                 "neither ID nor IDRANGE is specified.\n");
         if(!s3f::dml::dmlConfig::isConf(rcfg))
                 error_quit("ERROR: Net::getIdrangeLimits(), invalid IDRANGE attribute.\n");
         str = (char*)rcfg->findSingle("from");
         if(!str  || s3f::dml::dmlConfig::isConf(str))
                 error_quit("ERROR: Net::getIdrangeLimits(), "
                                 "missing or invalid IDRANGE.FROM attribute.\n");
         low = atoi(str);
         str = (char*)rcfg->findSingle("to");
         if(!str  || s3f::dml::dmlConfig::isConf(str))
                 error_quit("ERROR: Net::getIdrangeLimits(), "
                                 "missing or invalid IDRANGE.TO attribute.\n");
         high = atoi(str);
         if(low > high)
                 error_quit("ERROR: Net::getIdrangeLimits(), "
                                 "IDRANGE FROM %d is greater then TO %d.\n", low, high);
         if(low < 0)
                 error_quit("ERROR: Net::getIdrangeLimits(), "
                                 "IDRANGE.FROM must be non-negative.\n");
 }
S3FNET_INT2PTR_MAP& s3f::s3fnet::Net::getHosts () inline
Return all hosts in this level of net, including routers and switches.
Definition at line 207 of file net.h.
 { return hosts; }
S3FNET_INT2PTR_MAP& s3f::s3fnet::Net::getNets () inline
Return all subnets of this level of net.
Definition at line 210 of file net.h.
 { return nets; }
S3FNET_POINTER_VECTOR& s3f::s3fnet::Net::getLinks () inline
Return all links in this level of net.
Definition at line 213 of file net.h.
 { return links; }
NameService * s3f::s3fnet::Net::getNameService ()
Return global name resolution service.
Definition at line 280 of file net.cc.
References namesvc.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::Host::getDefaultIP(), s3f::s3fnet::DummySession::init(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::DMLRouteInfo::resolve(), and s3f::s3fnet::OpenFlowSwitchSession::SetController().
 {
         return namesvc;
 }
NetworkInterface * s3f::s3fnet::Net::nicnhi_to_obj (S3FNET_STRING nhi_str)
Return the network interface object by giving the NHI of the interface.
Definition at line 617 of file net.cc.
References namesvc, and s3f::s3fnet::NameService::nicnhi2iface().
Referenced by s3f::s3fnet::Link::config().
 {
         return namesvc->nicnhi2iface(nhi_str);
 }
void s3f::s3fnet::Net::register_host (Host * host, const S3FNET_STRING & name, bool isOpenVZEmu)
Register local host with given name.
This method should be called in the config phase of each connected interface.
Definition at line 587 of file net.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::NameService::get_veid2hostobj_map(), namesvc, s3f::s3fnet::DmlObject::nhi, S3FNET_MAKE_PAIR, s3f::s3fnet::Nhi::toString(), and s3f::s3fnet::Host::veid.
 {
         assert(host);
 #ifdef OPENVZ_EMULATION
         // register all hosts with its nhi
         if( isOpenVZEmu == true )
         {
                 if( !(namesvc->get_veid2hostobj_map()->insert(S3FNET_MAKE_PAIR(host->veid, host))).second )
                 {
                         error_quit("ERROR: Net::register_host(), duplicate veid in veid2hostobj_map, "
                                         "veid = (%d), host = \"%s\".\n", host->veid, host->nhi.toString());
                 }
         }
 #endif
 }
void s3f::s3fnet::Net::register_interface (NetworkInterface * iface, IPADDR ip, bool isOpenVZEmu)
Register local interface with the given IPADDR.
This method should be called in the config phase of each connected interface.
Definition at line 604 of file net.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::NameService::get_ip2iface_map(), s3f::s3fnet::IPPrefix::ip2txt(), namesvc, NET_DUMP, and S3FNET_MAKE_PAIR.
Referenced by s3f::s3fnet::NetworkInterface::config().
 {
         assert(iface);
         NET_DUMP(printf("register_interface(): ip=\"%s\".\n", IPPrefix::ip2txt(ip_addr)));
         if( !(namesvc->get_ip2iface_map()->insert(S3FNET_MAKE_PAIR(ip_addr, iface))).second )
         {
                 error_quit("ERROR: Net::register_interface(), "
                                 "duplicate registered network interface: IP=\"%s\"", IPPrefix::ip2txt(ip_addr));
         }
 }
int s3f::s3fnet::Net::control (int ctrltyp, void * ctrlmsg)
Ask some information about the current network For some queries, if the current network does not know the answer, it will forward the question to its parent network.
[ctrltyp = NET_CTRL_GET_TRAFFIC] get the traffic manager from the top net; for a sub-network the query will be forwarded to its parent network. ctrlmsg should be a pointer to a pointer to a Traffic object. The control method returns 1 if found; 0 otherwise.
Definition at line 622 of file net.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::DmlObject::myParent, s3f::s3fnet::NET_ACCESSORY_TRAFFIC, s3f::s3fnet::NET_CTRL_GET_TRAFFIC, netacc, and s3f::s3fnet::NetAccessory::requestAttribute().
Referenced by s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), and s3f::s3fnet::BTCPClientSession::get_random_server().
 {
         switch(ctrltyp) {
         case NET_CTRL_GET_TRAFFIC:
                 // only the top net has the right to specify traffic.
                 if(myParent) return ((Net*)myParent)->control(NET_CTRL_GET_TRAFFIC, ctrlmsg);
                 else
                 {
                         if(netacc)
{
                                 netacc->requestAttribute(NET_ACCESSORY_TRAFFIC, *((void**)ctrlmsg));
                                 return 1;
                         }
                         else
{
                                 *((void**)ctrlmsg) = 0;
                                 return 0;
                         }
                 }
         default:
                 error_quit("ERROR: Unknown Net::control() command!\n");
                 return 0;
         }
 }
Net* s3f::s3fnet::Net::getTopNet () inline
return pointer of the top net
Definition at line 245 of file net.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), s3f::s3fnet::Host::getTopNet(), and s3f::s3fnet::Host::init().
 {return top_net;}
int s3f::s3fnet::Net::openflow_controller_type () inline
Return the type of openflow controller.
0 means non-entity-based controller, and 1 means entity-based controller.
Definition at line 279 of file net.h.
Referenced by Net().
 { return sim_iface->openflow_controller_type; }
int s3f::s3fnet::Net::openflow_controller_model () inline
Return the model of openflow controller.
E.g., 1 - non-entity-based learning switch, 3 - entity-based learning switch. Refer to enum OPENFLOW_CONTROLLER_MODEL in openflow_interface.h
Definition at line 284 of file net.h.
Referenced by Net().
 { return sim_iface->openflow_controller_model; }
Controller* s3f::s3fnet::Net::get_of_controller () inline
Return the pointer to the non-entity-based controller.
Definition at line 287 of file net.h.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::SetController().
 { return top_net->of_controller; }
void s3f::s3fnet::Net::config_top_net (s3f::dml::Configuration * cfg) protected
Configure the top net.
Definition at line 521 of file net.cc.
References s3f::s3fnet::NameService::config(), curCidr, s3f::s3fnet::error_quit(), namesvc, NET_DUMP, and s3f::s3fnet::NameService::top_cidr_block.
Referenced by config().
 {
         NET_DUMP(printf("config_top_net().\n"));
         id = 0;
         // start name resolution service
         s3f::dml::Configuration* acfg = (s3f::dml::Configuration*)cfg->findSingle("environment_info");
         if (!acfg)
                 error_quit("ERROR: Net::config_top_net(), missing ENVIRONMENT_INFO attribute; run dmlenv first!\n");
         else if(!s3f::dml::dmlConfig::isConf(acfg))
                 error_quit("ERROR: Net::config_top_net(), invalid ENVIRONMENT_INFO attribute.\n");
         namesvc = new NameService;
         namesvc->config(acfg);
         assert(namesvc);
         curCidr = &namesvc->top_cidr_block;
 }
void s3f::s3fnet::Net::config_link (s3f::dml::Configuration * cfg) protected
Configure a link.
Definition at line 513 of file net.cc.
References s3f::s3fnet::Link::createLink(), links, and NET_DUMP.
Referenced by config().
 {
         NET_DUMP(printf("config_link().\n"));
         // construct default link
         Link* newlink = Link::createLink(this, cfg);
         links.push_back(newlink);
 }
void s3f::s3fnet::Net::config_host (s3f::dml::Configuration * cfg, S3FNET_LONG_SET & uniqset, bool is_router = false, bool is_of_switch = false) protected
Configure a host.
Definition at line 448 of file net.cc.
References alignment, s3f::s3fnet::Host::config(), s3f::s3fnet::error_quit(), Interface::get_Timeline(), getIdrangeLimits(), hosts, s3f::s3fnet::Host::is_of_switch, s3f::s3fnet::Host::is_router, NET_DUMP, S3FNET_MAKE_PAIR, and sim_iface.
Referenced by config(), config_of_switch(), and config_router().
 {
         // get id start and end
         int id_start, id_end;
         getIdrangeLimits(cfg, id_start, id_end);
         // now the id range is fixed. config them one by one.
         for(int i = id_start; i <= id_end; i++)
         {
                 if(!uniqset.insert((long)i).second)
                         error_quit("ERROR: duplicate ID %d used for NET.HOST/ROUTER.\n", i);
                 NET_DUMP(printf("config_host(), created host %d on timeline %d\n", i, alignment));
                 //todo: for host-based alignment assignment. generate hostnhi first,
                 Timeline* tl = sim_iface->get_Timeline(alignment);
                 Host* h = new Host(tl, this, (long)i);
                 hosts.insert(S3FNET_MAKE_PAIR(i, h));
                 if(is_router) h->is_router = true;
                 if(is_of_switch) h->is_of_switch = true;
                 h->config(cfg);
         }
 }
void s3f::s3fnet::Net::config_router (s3f::dml::Configuration * cfg, S3FNET_LONG_SET & uniqset) protected
Configure a router.
Definition at line 472 of file net.cc.
References config_host().
Referenced by config().
 {
         config_host(cfg, uniqset, true, false);
 }
void s3f::s3fnet::Net::config_of_switch (s3f::dml::Configuration * cfg, S3FNET_LONG_SET & uniqset) protected
Configure a openflow switch, currently simply indicate that the host is an openflow switch.
Definition at line 477 of file net.cc.
References config_host().
Referenced by config().
 {
         config_host(cfg, uniqset, false, true);
 }
void s3f::s3fnet::Net::config_net (s3f::dml::Configuration * cfg, S3FNET_LONG_SET & uniqset) protected
Configure a sub network.
Definition at line 482 of file net.cc.
References config(), curCidr, s3f::s3fnet::error_quit(), getIdrangeLimits(), s3f::s3fnet::CidrBlock::getPrefix(), s3f::s3fnet::CidrBlock::getSubCidrBlock(), ip_prefix, Net(), nets, S3FNET_MAKE_PAIR, and sim_iface.
Referenced by config().
 {
         //CidrBlock* self_cidr = curCidr;
         // get id start and end
         int id_start, id_end;
         getIdrangeLimits(cfg, id_start, id_end);
         // now the id range is fixed. config them one by one.
         for(int i = id_start; i <= id_end; i++) {
                 if(!uniqset.insert((long)i).second)
                         error_quit("ERROR: duplicate ID %d used for NET.NET.\n", i);
                 Net* nn = new Net(sim_iface, this, (long)i);
                 assert(nn);
                 assert(curCidr);
                 CidrBlock* subcidr = curCidr->getSubCidrBlock(i);
                 assert(subcidr);
                 nn->curCidr = subcidr;
                 nn->ip_prefix = subcidr->getPrefix();
                 nets.insert(S3FNET_MAKE_PAIR(i, nn));
                 nn->config(cfg);
         }
         // before quit, assign self_cidr back.
         //curCidr = self_cidr;
 }
void s3f::s3fnet::Net::connect_links () protected
This function is a helper function for the configure function.
Once the configure method has read in all the hosts, routers and links, this function will go through the links and connect the interfaces.
Definition at line 263 of file net.cc.
References s3f::s3fnet::Link::connect(), connect_links(), links, NET_DUMP, nets, s3f::s3fnet::DmlObject::nhi, and s3f::s3fnet::Nhi::toString().
Referenced by connect_links(), and finish_config_top_net().
 {
         NET_DUMP(printf("net \"%s\" connect links.\n", nhi.toString()));
         for(S3FNET_INT2PTR_MAP::iterator iter = nets.begin(); iter != nets.end(); iter++)
         {
                 Net* nn = (Net*)(iter->second);
                 nn->connect_links();
         }
         for(unsigned i=0; i < links.size(); i++)
         {
                 Link* pLink = (Link*)links[i];
                 pLink->connect(this);
         }
 }
void s3f::s3fnet::Net::finish_config_top_net (s3f::dml::Configuration * cfg) protected
Process configurations that can't be done until all hosts/nets/links have been configured.
Definition at line 541 of file net.cc.
References s3f::s3fnet::NetAccessory::addAttribute(), s3f::s3fnet::Traffic::config(), connect_links(), s3f::s3fnet::error_quit(), load_fwdtable(), s3f::s3fnet::NET_ACCESSORY_TRAFFIC, NET_DUMP, netacc, and traffic.
Referenced by config().
 {
         NET_DUMP(printf("finish_config_top_net().\n"));
         // configure traffic
         s3f::dml::Configuration* tcfg = (s3f::dml::Configuration*)cfg->findSingle("net.traffic");
         if(tcfg)
         {
                 if(!s3f::dml::dmlConfig::isConf(tcfg))
                         error_quit("ERROR: Net::config(), invalid NET.TRAFFIC attribute.\n");
                 traffic = new Traffic(this);
                 assert(traffic);
                 traffic->config(tcfg);
                 if(!netacc) netacc = new NetAccessory;
                 netacc->addAttribute(NET_ACCESSORY_TRAFFIC, (void*)traffic);
         }
         else
                 traffic = 0;
         // connect the links in the net
         connect_links();
         // load the forwarding tables if specified
         s3f::dml::Enumeration* fenum = cfg->find("forwarding_table");
         while(fenum->hasMoreElements())
         {
                 s3f::dml::Configuration* fcfg = (s3f::dml::Configuration*)fenum->nextElement();
                 if(!s3f::dml::dmlConfig::isConf(fcfg))
                         error_quit("ERROR: Net::finish_config_top_net(), invalid FORWARDING_TABLE attribute.\n");
                 load_fwdtable(fcfg);
         }
         delete fenum;
 }
void s3f::s3fnet::Net::load_fwdtable (s3f::dml::Configuration * cfg) protected
load forwarding tables of all the hosts containing in this net
Definition at line 575 of file net.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::NameService::hostnhi2hostobj(), s3f::s3fnet::Host::loadForwardingTable(), and namesvc.
Referenced by finish_config_top_net().
 {
         char* str = (char*)cfg->findSingle("node_nhi");
         if (!str || s3f::dml::dmlConfig::isConf(str))
                 error_quit("ERROR: Net::load_fwdtable(), missing or invalid FORWARDING_TABLE.NODE_NHI attribute.\n");
         S3FNET_STRING hostnhi = str;
         Host* host = namesvc->hostnhi2hostobj(hostnhi);
         assert(host);
         host->loadForwardingTable(cfg);
 }
Member Data Documentation
pthread_mutex_t s3f::s3fnet::Net::of_buf_mutex
Add lock to access openflow buffer in openflow library (topnet only attribute).
Definition at line 290 of file net.h.
Referenced by Net(), and ~Net().
SimInterface* s3f::s3fnet::Net::sim_iface protected
the interface for running experiments; created in s3fnet.cc
Definition at line 293 of file net.h.
Referenced by config(), config_host(), and config_net().
int s3f::s3fnet::Net::alignment protected
the timeline that the net (and all its hosts) are aligned to
Definition at line 294 of file net.h.
Referenced by config(), and config_host().
SimCtrl* s3f::s3fnet::Net::sim_ctrl protected
to control openvz-based emulation
Definition at line 295 of file net.h.
Referenced by config(), and init().
int s3f::s3fnet::Net::idbase protected
ID base of VE, also the first VE id.
Definition at line 296 of file net.h.
Referenced by config(), and init().
int s3f::s3fnet::Net::nr_ve protected
numbers of VEs */
Definition at line 297 of file net.h.
Referenced by config(), and init().
bool s3f::s3fnet::Net::isOpenVZEmu protected
whether openvz-based emulation is supported
Definition at line 298 of file net.h.
Referenced by config(), init(), and ~Net().
struct sniff_ethernet* s3f::s3fnet::Net::ethernet protected
The Ethernet header.
Definition at line 301 of file net.h.
const struct sniff_ip* s3f::s3fnet::Net::ip protected
The IP header.
Definition at line 302 of file net.h.
const struct sniff_arp* s3f::s3fnet::Net::arp protected
The ARP header.
Definition at line 303 of file net.h.
const struct sniff_tcp* s3f::s3fnet::Net::tcp protected
The TCP header.
Definition at line 304 of file net.h.
const char* s3f::s3fnet::Net::payload protected
Packet payload.
Definition at line 305 of file net.h.
u_int s3f::s3fnet::Net::size_ip protected
size of IP header
Definition at line 306 of file net.h.
u_int s3f::s3fnet::Net::size_tcp protected
size of TCP header
Definition at line 307 of file net.h.
NetAccessory* s3f::s3fnet::Net::netacc protected
The extra options for a net.
Not all Net objects should own some attributes like as ASBoundary (whether this net is at the boudary of an AS), AS number, etc.
Definition at line 314 of file net.h.
Referenced by control(), finish_config_top_net(), init(), and ~Net().
IPPrefix s3f::s3fnet::Net::ip_prefix protected
IP prefix of this net.
Definition at line 317 of file net.h.
Referenced by config_net(), and display().
S3FNET_INT2PTR_MAP s3f::s3fnet::Net::hosts protected
List of hosts: a map from id to a pointer of the host.
Definition at line 320 of file net.h.
Referenced by config_host(), display(), nhi2obj(), and ~Net().
S3FNET_INT2PTR_MAP s3f::s3fnet::Net::nets protected
List of sub-networks: a map from id to a pointer of the network.
Definition at line 323 of file net.h.
Referenced by config_net(), connect_links(), display(), init(), nhi2obj(), and ~Net().
S3FNET_POINTER_VECTOR s3f::s3fnet::Net::links protected
List of links.
Definition at line 326 of file net.h.
Referenced by config_link(), connect_links(), display(), init(), and ~Net().
CidrBlock* s3f::s3fnet::Net::curCidr protected
Used by the config methods to refer the cidr block of the current network it is processing.
Definition at line 330 of file net.h.
Referenced by config_net(), and config_top_net().
bool s3f::s3fnet::Net::is_top_net protected
indicator on whether this net object is the top net
Definition at line 333 of file net.h.
Referenced by ~Net().
Net* s3f::s3fnet::Net::top_net protected
Definition at line 336 of file net.h.
NameService* s3f::s3fnet::Net::namesvc protected
The global name resolution service, created at topnet, passed to all subnets.
Definition at line 339 of file net.h.
Referenced by config_top_net(), getNameService(), load_fwdtable(), nhi2obj(), nicnhi2ip(), nicnhi_to_obj(), register_host(), and register_interface().
Traffic* s3f::s3fnet::Net::traffic protected
Definition at line 341 of file net.h.
Referenced by finish_config_top_net(), and init().
Controller* s3f::s3fnet::Net::of_controller protected
The non-entity-based openflow controller, created at topnet during initialization.
Definition at line 344 of file net.h.
Referenced by Net().
long int s3f::s3fnet::Net::pkt_from_ve_counter protected
store the total number of packet received from VEs
Definition at line 388 of file net.h.
Referenced by ~Net().
long s3f::s3fnet::DmlObject::id inherited
Every DmlObject object must have an ID obtained from the DML.
Definition at line 44 of file dmlobj.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), config(), s3f::s3fnet::Host::config_network_interface(), s3f::s3fnet::RouteInfo::display(), and s3f::s3fnet::NetworkInterface::emu_packet_modify_iface().
Nhi s3f::s3fnet::DmlObject::nhi inherited
The nhi address to identify the object.
Definition at line 47 of file dmlobj.h.
Referenced by s3f::s3fnet::UDPSession::abort(), s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::Link::config(), s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), s3f::s3fnet::RouteInfo::config(), config(), s3f::s3fnet::Host::config_network_interface(), s3f::s3fnet::UDPSession::connect(), connect_links(), s3f::s3fnet::UDPSession::disconnect(), s3f::s3fnet::Link::display(), display(), s3f::s3fnet::UDPClientSessionContinuation::failure(), s3f::s3fnet::UDPServerSessionContinuation::failure(), s3f::s3fnet::TCPServerSessionContinuation::failure(), s3f::s3fnet::TCPClientSessionContinuation::failure(), s3f::s3fnet::BTCPClientSessionContinuation::failure(), s3f::s3fnet::Host::getDefaultIP(), s3f::s3fnet::Traffic::getServers(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), s3f::s3fnet::NetworkInterface::init(), s3f::s3fnet::Host::init(), init(), s3f::s3fnet::UDPSession::listen(), s3f::s3fnet::Host::loadForwardingTable(), s3f::s3fnet::LearningController::process_recv_packet(), s3f::s3fnet::UDPSession::receive(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::LearningControllerSession::ReceiveFromSwitch(), s3f::s3fnet::NetworkInterface::receivePacket(), register_host(), s3f::s3fnet::RouteInfo::resolve(), s3f::s3fnet::DMLRouteInfo::resolve(), s3f::s3fnet::NBTCPClientSessionContinuation::resume(), s3f::s3fnet::NBTCPServerSessionContinuation::resume(), s3f::s3fnet::UDPSession::send(), s3f::s3fnet::TCPSession::send_data(), s3f::s3fnet::NetworkInterface::sendPacket(), s3f::s3fnet::UDPSession::setSource(), s3f::s3fnet::TCPSession::slowTimeoutHandling(), s3f::s3fnet::NBTCPServerSessionContinuation::success(), s3f::s3fnet::TCPSession::TCPSession(), s3f::s3fnet::UDPSession::UDPSession(), s3f::s3fnet::TCPSession::update_timeout(), s3f::s3fnet::UDPSession::wake_app(), s3f::s3fnet::Host::~Host(), ~Net(), and s3f::s3fnet::NetworkInterface::~NetworkInterface().
DmlObject* s3f::s3fnet::DmlObject::myParent inherited
The parent.
DML objects are nested.
Definition at line 50 of file dmlobj.h.
Referenced by s3f::s3fnet::Link::config(), s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), config(), s3f::s3fnet::Link::connect(), control(), s3f::s3fnet::NetworkInterface::getHost(), init(), s3f::s3fnet::Host::inNet(), s3f::s3fnet::NetworkInterface::NetworkInterface(), and s3f::s3fnet::DMLRouteInfo::resolve().
The documentation for this class was generated from the following files:
net.h
net.cc