S3F: s3f::s3fnet::trie0::Trie0 Class Reference
s3f::s3fnet::trie0::Trie0 Class Reference
A data structure for forwarding tables.
#include <trie0.h>
Classes
class iterator
Public Types
enum TrieType {
ORIGINAL = 0, SIMPLE = 1, PREFIX = 2, UNORDERED_PREFIX = 3,
ARRAY_BACKED = 4, ARRAY_BACKED_PREFIX = 5, ARRAY_BACKED_UNORDERED_PREFIX = 6
}
Enum containing Trie implementations.
Public Member Functions
Trie0 ()
The constructor.
virtual ~Trie0 ()
The destructor.
virtual TrieData * insert (TRIEBITSTRING key, int nBits, TrieData *data, bool replace)
Inserts a new (key, data) pair.
virtual TrieData * remove (TRIEBITSTRING key, int nBits)
Removes a key from the Trie.
virtual TrieData * lookup (TRIEBITSTRING key)
Finds a key in the Trie.
virtual TrieData * getDefault ()
Get the default Route.
virtual int size ()
Return the number of items in the trie.
iterator begin ()
iterator & end ()
Public Attributes
iterator last
Last item in iterator.
Protected Member Functions
TrieNode * search (TRIEBITSTRING key, int len, TrieNode **failedNode, int *failedbitpos)
Helper function for the insert and lookup methods.
Static Protected Member Functions
static void create (TrieNode *theroot, TRIEBITSTRING key, int nBits, TrieData *data)
Creates a node from the root.
static void deallocate (TrieNode *theroot)
Deallocate the trie recursively.
Protected Attributes
TrieNode * root
The root of the trie.
int nElements
Number of data elements stored in the trie.
Private Attributes
TRIEBITSTRING cached_key
The ip address of the cached route.
TrieData * cached_data
The cached route.
Detailed Description
A data structure for forwarding tables.
We use this class to implement the routing table so that we can do fast longest-matching prefix lookups. Our Trie is a container for bit-strings. When a new bit-string is added, the number of significant bits must be specified. Just as in IP addressing, the significant bits are counted starting from the most significant bit. The maximum size of the bit-string is 32 bits. With each key, we also store a corresponding pointer to hold user data. In a routing table implementation, the keys will be the IP prefixes and the data will be a (link, next-hop) pair.
NOTE: If CIDR addresses are used, they must be ordered from longest mask lengths to shortest to prevent DUPLICATE_ROUTE replacement. Example order: ip1, ip2/31, ..., ip100/16, ..., ip1000/1 CIDR addresses are also only guaranteed to work for static routing.
Definition at line 52 of file trie0.h.
Member Enumeration Documentation
enum s3f::s3fnet::Trie::TrieType inherited
Enum containing Trie implementations.
Enumerator
ORIGINAL
Very first s3fnet Trie implementation.
SIMPLE
Identical to ORIGINAL with minor fixes/enhancements.
PREFIX
Stores values at minimum depth instead of depth equal to their bit-length (ie depth 32 for an ipv4 address).
UNORDERED_PREFIX
Like PREFIX but can take CIDR-format IP address as input in any order.
ARRAY_BACKED
Trie that stores indices into an array in its nodes (vs data IN the nodes).
ARRAY_BACKED_PREFIX
ARRAY_BACKED_UNORDERED_PREFIX
PREFIX with array-backing (ARRAY_BACKED).
Definition at line 112 of file trie.h.
                       {
                 ORIGINAL = 0,
                 SIMPLE = 1,
                 PREFIX = 2,
                 UNORDERED_PREFIX = 3,
                 ARRAY_BACKED = 4,
                 ARRAY_BACKED_PREFIX = 5,
                 ARRAY_BACKED_UNORDERED_PREFIX = 6
         };
Constructor & Destructor Documentation
s3f::s3fnet::trie0::Trie0::Trie0 ()
The constructor.
Definition at line 53 of file trie0.cc.
References root.
              : nElements(0), last(this)
 {
   root = new TrieNode(); assert(root);
 }
s3f::s3fnet::trie0::Trie0::~Trie0 () virtual
The destructor.
Definition at line 61 of file trie0.cc.
References deallocate(), nElements, and root.
 {
   deallocate(root);
   nElements = 0;
 }
Member Function Documentation
TrieData * s3f::s3fnet::trie0::Trie0::insert (TRIEBITSTRING key, int nBits, TrieData * data, bool replace) virtual
Inserts a new (key, data) pair.
Adds a new (key, data) pair to the Trie. If the key already exists, and if the replace flag is set, we will replace the old data with the new one and return the old data. If the replace flag is not set, the old data remains in the Trie and the new data is returned. If the key does not exist in Trie, the data will be inserted and the return value is 0.
Parameters
key the key to insert
nBits bits of the key to consider (useful for CIDR)
data the TrieData object to add
replace whether to replace an existing value with the same key
Returns
NULL on success, otherwise the TrieData object we attempted to insert (so reference is not lost)
Implements s3f::s3fnet::Trie.
Definition at line 70 of file trie0.cc.
References create(), s3f::s3fnet::trie0::TrieNode::data, nElements, REMOVE, and search().
 {
   TrieNode *fail = 0;
   int bitpos = 0;
   TrieNode* match = search(key, nBits, &fail, &bitpos);
   // Does the key already exist in our trie?
   // If so, replace the data if replace flag is true.
   if(match) {
     if(!replace) return data;
     TrieData* temp = match->data;
     match->data = data;
     return temp;
   }
   // Create all the necessary nodes for the unmatched bits
   // after fail and insert the data.
   create(fail, REMOVE(bitpos, key), nBits-bitpos, data);
   nElements++;
   return 0;
 }
TrieData * s3f::s3fnet::trie0::Trie0::remove (TRIEBITSTRING key, int nBits) virtual
Removes a key from the Trie.
Remove the key from the trie, if it exists, and returns the data corresponding to the removed key. If the key is not in the Trie0, return NULL.
Parameters
key the key to remove
nBits bits of the key to consider
Returns
the data correspoding to the key on success, otherwise NULL
Implements s3f::s3fnet::Trie.
Definition at line 121 of file trie0.cc.
References s3f::s3fnet::trie0::TrieNode::data, nElements, and search().
 {
   TrieNode* ptr;
   TrieData* olddata;
   ptr = search(key, nBits, 0, 0);
   if(!ptr) return 0;
   olddata = ptr->data;
   // BUGBUG: Here we just set the data to NULL and the TrieNode still
   // exists.  To conserve memory, we might want to delete the TrieNode
   // if it's a leaf.  But then we need to adjust the parent's pointer
   // and stuff.
   ptr->data = 0;
   nElements--;
   return olddata;
 }
TrieData * s3f::s3fnet::trie0::Trie0::lookup (TRIEBITSTRING key) virtual
Finds a key in the Trie.
Perform a longest-matching prefix search for the key and if found, places the data in pData. Otherwise, pData is NULL.
Parameters
key the key to lookup
Returns
the data matching the key on success, otherwise NULL
Implements s3f::s3fnet::Trie.
Definition at line 104 of file trie0.cc.
References s3f::s3fnet::trie0::TrieNode::children, s3f::s3fnet::trie0::TrieNode::data, and root.
{
   TrieNode* cur = root;
   TrieData* pData = 0;
   while(cur) {
     if(cur->data) pData = cur->data;
     cur = cur->children[(key&0x80000000)?1:0];
     key <<= 1;
   }
   return pData;
 }
TrieData * s3f::s3fnet::trie0::Trie0::getDefault () virtual
Get the default Route.
Returns
an instance of the default route as a TrieData object
Implements s3f::s3fnet::Trie.
Definition at line 140 of file trie0.cc.
References s3f::s3fnet::trie0::TrieNode::data, and root.
{
         if(root) return root->data;
         return 0;
 }
virtual int s3f::s3fnet::trie0::Trie0::size () inline virtual
Return the number of items in the trie.
Returns
the size of the Trie (generally the number of elements contained)
Implements s3f::s3fnet::Trie.
Definition at line 107 of file trie0.h.
References nElements.
 { return nElements; }
TrieNode * s3f::s3fnet::trie0::Trie0::search (TRIEBITSTRING key, int len, TrieNode ** failedNode, int * failedbitpos) protected
Helper function for the insert and lookup methods.
This function will search the trie for the key and if found, return a pointer to the TrieNode. If not found, it will return NULL, and set failedNode to the TrieNode where the search fails and failedbitpos to the bit position that failed.
Parameters
key the key for insert/lookup
len the bits to consider of the key
failedNode a TrieNode reference address to write the address of the last node traversed before failure
failedbitpos an integer address to write the bit position of the last traversal before failure
Returns
the TrieNode found, NULL otherwise
Definition at line 152 of file trie0.cc.
References s3f::s3fnet::trie0::TrieNode::children, s3f::s3fnet::trie0::TrieNode::data, GETBIT, root, and TRIE_KEY_SIZE.
Referenced by insert(), and remove().
 {
   TrieNode* cur, *lastcur;
   TrieNode* match = 0;
   int bitpos, curbit;
   // Go through the bits starting from the MSB and traverse
   // the tree. Remember the last match.
   for(bitpos = 0, lastcur = cur = root;
       cur && bitpos < len && bitpos < TRIE_KEY_SIZE(key);
       cur = cur->children[curbit], bitpos++) {
     if(cur->data) match = cur;
     lastcur = cur;
     curbit = GETBIT(bitpos, key);
   }
   if(cur && cur->data) match = cur;
   else if(failedNode && failedbitpos) {
     if(cur) {
       *failedbitpos = bitpos;
       *failedNode = cur;
     } else {
       *failedbitpos = bitpos - 1;
       *failedNode = lastcur;
     }
   }
   return match;
 }
void s3f::s3fnet::trie0::Trie0::create (TrieNode * theroot, TRIEBITSTRING key, int nBits, TrieData * data) static protected
Creates a node from the root.
Static helper function for the insert method. Creates nBits nodes for the key starting at TrieNode theroot.
Parameters
theroot the root entry to start from
key the key to create a node for
nBits the bits to consider
data the data to store
Definition at line 189 of file trie0.cc.
References s3f::s3fnet::trie0::TrieNode::children, and GETBIT.
Referenced by insert().
 {
   TrieNode* ptr;
   for(int i=0; i < nBits; i++, theroot = ptr) {
     assert(theroot->children[GETBIT(i, key)] == 0);
     ptr = theroot->children[GETBIT(i, key)] = new TrieNode();
     assert(ptr);
   }
   theroot->data = data;
 }
void s3f::s3fnet::trie0::Trie0::deallocate (TrieNode * theroot) static protected
Deallocate the trie recursively.
Parameters
theroot the root entry of the Trie to free
Definition at line 205 of file trie0.cc.
References s3f::s3fnet::trie0::TrieNode::children, and s3f::s3fnet::trie0::TRIE_KEY_SPAN.
Referenced by ~Trie0().
 {
   if(theroot == 0) return;
   // deallocate all the children
   for(int i = 0; i < TRIE_KEY_SPAN; i++)
     deallocate(theroot->children[i]);
   delete theroot;
 }
Trie0::iterator s3f::s3fnet::trie0::Trie0::begin ()
Definition at line 380 of file trie0.cc.
{
   iterator first(this); // create iterator
   ++first; // find first element
   return first; // return by copy
 }
iterator& s3f::s3fnet::trie0::Trie0::end () inline
Definition at line 300 of file trie0.h.
References last.
 { return last; }
Member Data Documentation
TrieNode* s3f::s3fnet::trie0::Trie0::root protected
The root of the trie.
Definition at line 144 of file trie0.h.
Referenced by getDefault(), lookup(), search(), Trie0(), and ~Trie0().
int s3f::s3fnet::trie0::Trie0::nElements protected
Number of data elements stored in the trie.
Definition at line 147 of file trie0.h.
Referenced by insert(), remove(), size(), and ~Trie0().
TRIEBITSTRING s3f::s3fnet::trie0::Trie0::cached_key private
The ip address of the cached route.
Definition at line 151 of file trie0.h.
TrieData* s3f::s3fnet::trie0::Trie0::cached_data private
The cached route.
Definition at line 154 of file trie0.h.
iterator s3f::s3fnet::trie0::Trie0::last
Last item in iterator.
Definition at line 289 of file trie0.h.
Referenced by end().
The documentation for this class was generated from the following files:
trie0.h
trie0.cc