S3F: s3f::s3fnet::DataMessage Class Reference
s3f::s3fnet::DataMessage Class Reference
A generic protocol message carrying a payload as a continuous byte stream or a list of data chunks.
#include <data_message.h>
Public Member Functions
DataMessage ()
Default constructor without any argument.
DataMessage (int real_len, byte *byte_array=0, bool need_copying=false)
Constructor with given fields.
DataMessage (DataChunk *data_chunks, bool need_copying=false)
This is the constructor that takes a list of data chunks as payload.
DataMessage (const DataMessage &)
The copy constructor.
virtual ProtocolMessage * clone ()
Cloning the protocol message (required by ProtocolMessage).
virtual ~DataMessage ()
The destructor.
virtual int type ()
Return the protocol number that this message represents.
virtual int packingSize ()
This method returns the number of bytes that are needed to pack this protocol message in simulation.
virtual int realByteCount ()
Return the number of bytes that this data message occupies in the real world, even though we might not actually allocating the buffer with this size in simulation.
void carryPayload (ProtocolMessage *payload)
This method appends another protocol message to this protocol message and treats it as the payload.
virtual ProtocolMessage * dropPayload ()
If there is a payload, drop it from the linked list, then return it.
ProtocolMessage * payload ()
Returns the next header.
virtual void erase ()
This method is called to release the memory of this packet and its subsequent payload.
virtual void erase_all ()
int totalPackingSize ()
Returns the total byte count (in simulation) including the payload.
int totalRealBytes ()
Returns the total number of bytes of the protocol message including the payload in the real-world.
ProtocolMessage * getMessageByType (int type_code)
Given a protocol message type code, this method goes through the message chain starting from this message, and returns the first ProtocolMessage that has this type code.
unsigned int get_type ()
void inc_evts ()
int dec_evts ()
Static Public Member Functions
static int registerMessage (ProtocolMessage *(*fct)(), int type)
Called by S3FNET_REGISTER_MESSAGE macro to register a protocol message.
Public Attributes
void * payload
The payload.
int real_length
The real payload size, i.e., in the real target system rather than in the simulator.
Static Public Attributes
static S3FNET_INT2PTR_MAP * registered_messages = 0
A mapping between message type and message constructor.
Protected Attributes
unsigned int __type
int __evts
Detailed Description
A generic protocol message carrying a payload as a continuous byte stream or a list of data chunks.
There are two types of the payload this message is carrying. The payload data can be represented as a continuous byte stream or byte array. If this is true, the payload pointer should be of type byte* that points to a byte array or simply NULL. The latter case is when the data is intentionally not included in simulation for better efficiency. Also, the real_length should be the number of real bytes of this payload in the target system (rather than in the simulator). The data can also be a list of data chunks, in which case the list could have both fake data and real data blocks. This situation is identified by having real_length set to be zero. The real length of the payload can be obtained by invoking the DataChunk::totalRealBytes method.
Definition at line 112 of file data_message.h.
Constructor & Destructor Documentation
s3f::s3fnet::DataMessage::DataMessage ()
Default constructor without any argument.
Definition at line 13 of file data_message.cc.
Referenced by clone().
 : payload(0), real_length(0) {}
s3f::s3fnet::DataMessage::DataMessage (int real_len, byte * byte_array = 0, bool need_copying = false)
Constructor with given fields.
If need_copying is true, the constructor will explicitly copy the byte_array to an internal buffer. Otherwise, the ownership of byte_array is simply transferred. DataMessage thereafter takes the responsibility of reclaiming the buffer eventually. real_len is the real length of the message (i.e., in the target system rather than in simulation).
Definition at line 15 of file data_message.cc.
References s3f::s3fnet::ProtocolMessage::payload().
                                                                           : real_length(real_len)
 {
   assert(real_len > 0);
   if(byte_array && need_copying)
   {
     payload = new byte[real_len]; assert(payload);
     memcpy((byte*)payload, byte_array, real_len);
   }
   else payload = byte_array;
 }
s3f::s3fnet::DataMessage::DataMessage (DataChunk * data_chunks, bool need_copying = false)
This is the constructor that takes a list of data chunks as payload.
If need_copying is true, the constructor will explicitly copy the data chunks. Otherwise, the ownership of the list is transferred.
Definition at line 26 of file data_message.cc.
References s3f::s3fnet::DataChunk::clone(), and s3f::s3fnet::ProtocolMessage::payload().
                                                               : real_length(0) // to identify the payload is a list of data chunks
 {
   if(datachk && need_copying)
   {
     payload = datachk->clone();
   }
   else payload = datachk;
 }
s3f::s3fnet::DataMessage::DataMessage (const DataMessage & dmsg)
The copy constructor.
Definition at line 35 of file data_message.cc.
References s3f::s3fnet::ProtocolMessage::clone(), s3f::s3fnet::ProtocolMessage::payload(), payload, and real_length.
                                                 : ProtocolMessage(dmsg) // important !!!
 {
   real_length = dmsg.real_length;
   if(dmsg.payload)
   {
     if(real_length > 0)
     {
       payload = new byte[real_length]; assert(payload);
       memcpy((byte*)payload, (byte*)dmsg.payload, real_length);
     }
     else
     {
       payload = ((DataChunk*)dmsg.payload)->clone();
     }
   }
   else payload = 0;
 }
s3f::s3fnet::DataMessage::~DataMessage () virtual
The destructor.
Definition at line 58 of file data_message.cc.
References s3f::s3fnet::ProtocolMessage::payload(), and real_length.
 {
   if(payload)
   {
     if(real_length > 0) delete[] (byte*)payload;
     else delete (DataChunk*)payload;
   }
 }
Member Function Documentation
ProtocolMessage * s3f::s3fnet::DataMessage::clone () virtual
Cloning the protocol message (required by ProtocolMessage).
Implements s3f::s3fnet::ProtocolMessage.
Definition at line 53 of file data_message.cc.
References DataMessage().
 {
   return new DataMessage(*this);
 }
virtual int s3f::s3fnet::DataMessage::type () inline virtual
Return the protocol number that this message represents.
Implements s3f::s3fnet::ProtocolMessage.
Definition at line 155 of file data_message.h.
References s3f::s3fnet::S3FNET_PROTOCOL_TYPE_OPAQUE_DATA.
 { return S3FNET_PROTOCOL_TYPE_OPAQUE_DATA; }
int s3f::s3fnet::DataMessage::packingSize () virtual
This method returns the number of bytes that are needed to pack this protocol message in simulation.
This is for serialization.
Reimplemented from s3f::s3fnet::ProtocolMessage.
Definition at line 67 of file data_message.cc.
References s3f::s3fnet::ProtocolMessage::packingSize(), s3f::s3fnet::ProtocolMessage::payload(), and real_length.
 {
   int base = ProtocolMessage::packingSize()+2*sizeof(int32);
   if(payload)
   {
     if(real_length > 0) return base+real_length;
     else return base+((DataChunk*)payload)->totalPackingSize();
   }
   else return base;
 }
int s3f::s3fnet::DataMessage::realByteCount () virtual
Return the number of bytes that this data message occupies in the real world, even though we might not actually allocating the buffer with this size in simulation.
Implements s3f::s3fnet::ProtocolMessage.
Definition at line 78 of file data_message.cc.
References s3f::s3fnet::ProtocolMessage::payload(), and real_length.
Referenced by s3f::s3fnet::UDPSession::generate(), s3f::s3fnet::UDPSession::receive(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::TCPSession::receiver_recv_sack(), and s3f::s3fnet::TCPSession::send_data().
 {
   if(real_length > 0) return real_length;
   else if(payload) return ((DataChunk*)payload)->totalRealBytes();
   else return 0;
 }
int s3f::s3fnet::ProtocolMessage::registerMessage (ProtocolMessage *(*)() fct, int type) static inherited
Called by S3FNET_REGISTER_MESSAGE macro to register a protocol message.
Definition at line 96 of file protocol_message.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolMessage::registered_messages, and S3FNET_MAKE_PAIR.
 {
   // allocate the global data structure if it's not there
   if(!registered_messages)
   {
     registered_messages = new S3FNET_INT2PTR_MAP;
     assert(registered_messages);
   }
   // insert the mapping; check if duplicated
   if(!registered_messages->insert(S3FNET_MAKE_PAIR(type, (void*)fct)).second)
     error_quit("ERROR: duplicate protocol message types: %d\n", type);
   // we need to return something so that S3FNET_REGISTER_MESSAGE macro works
   return 0;
 }
void s3f::s3fnet::ProtocolMessage::carryPayload (ProtocolMessage * payload) inherited
This method appends another protocol message to this protocol message and treats it as the payload.
Definition at line 27 of file protocol_message.cc.
References s3f::s3fnet::error_retn(), and s3f::s3fnet::ProtocolMessage::next.
Referenced by s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::send(), and s3f::s3fnet::TCPSession::send_data().
 {
   // adjust the links, warning if found dangling nodes
   if(next)
   {
     error_retn("WARNING: ProtocolMessage::carryPayload(), overwrite pre-exist payload (may cause memory leak)!\n");
     delete next;
   }
   next = load;
 }
ProtocolMessage * s3f::s3fnet::ProtocolMessage::dropPayload () virtual inherited
If there is a payload, drop it from the linked list, then return it.
Return NULL if there is no payload.
Definition at line 38 of file protocol_message.cc.
References s3f::s3fnet::ProtocolMessage::next.
Referenced by s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::SimpleMac::pop(), and s3f::s3fnet::UDPSession::receive().
 {
   // sever the link between this node and the payload and return it
   ProtocolMessage* pmsg = next;
   next = 0;
   return pmsg;
 }
ProtocolMessage* s3f::s3fnet::ProtocolMessage::payload () inline inherited
Returns the next header.
Definition at line 103 of file protocol_message.h.
References s3f::s3fnet::ProtocolMessage::next.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::BufferFromPacket(), DataMessage(), s3f::s3fnet::NetworkInterface::emu_packet_modify_iface(), packingSize(), realByteCount(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::TCPSession::receiver_recv_sack(), and ~DataMessage().
 { return next; }
void s3f::s3fnet::ProtocolMessage::erase () virtual inherited
This method is called to release the memory of this packet and its subsequent payload.
One must avoid deleting a protocol message object directly. This requirement is necessary for the support to optimizations such as the reference counter.
For better protection, the destructor of the protocol message (and its extended classes) should be defined as protected.
Reimplemented from Message.
Definition at line 46 of file protocol_message.cc.
Referenced by s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::OpenFlowSwitchSession::HandleControlInput(), and s3f::s3fnet::SimpleMac::pop().
 {
   //printf("ProtocolMessage erased, type = %d\n", this->type());
   delete this;
 }
void s3f::s3fnet::ProtocolMessage::erase_all () virtual inherited
Reimplemented from Message.
Definition at line 52 of file protocol_message.cc.
References s3f::s3fnet::ProtocolMessage::erase_all(), and s3f::s3fnet::ProtocolMessage::next.
Referenced by s3f::s3fnet::ProtocolMessage::erase_all(), s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::IPSession::handle_pop_pkt(), and s3f::s3fnet::DummySession::pop().
 {
         if(this->next) this->next->erase_all();
     //printf("ProtocolMessage deleted, type = %d\n", this->type());
         delete this;
 }
int s3f::s3fnet::ProtocolMessage::totalPackingSize () inherited
Returns the total byte count (in simulation) including the payload.
Definition at line 60 of file protocol_message.cc.
References s3f::s3fnet::ProtocolMessage::next, s3f::s3fnet::ProtocolMessage::packingSize(), and s3f::s3fnet::ProtocolMessage::totalPackingSize().
Referenced by s3f::s3fnet::ProtocolMessage::totalPackingSize().
 {
   // add them all
   if(next)
           return packingSize()+next->totalPackingSize();
   else
           return packingSize();
 }
int s3f::s3fnet::ProtocolMessage::totalRealBytes () inherited
Returns the total number of bytes of the protocol message including the payload in the real-world.
Definition at line 74 of file protocol_message.cc.
References s3f::s3fnet::ProtocolMessage::next, s3f::s3fnet::ProtocolMessage::realByteCount(), and s3f::s3fnet::ProtocolMessage::totalRealBytes().
Referenced by s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::IPSession::push(), and s3f::s3fnet::ProtocolMessage::totalRealBytes().
 {
   // add them all
   if(next)
           return realByteCount()+next->totalRealBytes();
   else
           return realByteCount();
 }
ProtocolMessage * s3f::s3fnet::ProtocolMessage::getMessageByType (int type_code) inherited
Given a protocol message type code, this method goes through the message chain starting from this message, and returns the first ProtocolMessage that has this type code.
If none is found, NULL is returned.
Definition at line 83 of file protocol_message.cc.
References s3f::s3fnet::ProtocolMessage::next, and s3f::s3fnet::ProtocolMessage::type().
 {
   ProtocolMessage* cur = this;
   while(cur)
   {
     if(cur->type() == t) return cur;
     cur = cur->next;
   }
   return 0;
 }
unsigned int Message::get_type () inline inherited
Definition at line 23 of file message.h.
References Message::__type.
 { return __type; }
void Message::inc_evts () inline inherited
Definition at line 28 of file message.h.
References Message::__evts.
Referenced by Event::Event().
 { __evts++; }
int Message::dec_evts () inline inherited
Definition at line 29 of file message.h.
References Message::__evts.
Referenced by Event::~Event().
 { return --__evts; }
Member Data Documentation
void* s3f::s3fnet::DataMessage::payload
The payload.
The format of the payload can be a byte array (including NULL), or a list of data chunks.
Definition at line 116 of file data_message.h.
Referenced by s3f::s3fnet::TCPRecvWindow::addToBuffer(), DataMessage(), and s3f::s3fnet::UDPSession::generate().
int s3f::s3fnet::DataMessage::real_length
The real payload size, i.e., in the real target system rather than in the simulator.
If this field is zero, it means the payload is a list of data chunks.
Definition at line 121 of file data_message.h.
Referenced by s3f::s3fnet::TCPRecvWindow::addToBuffer(), DataMessage(), packingSize(), realByteCount(), s3f::s3fnet::UDPSession::receive(), and ~DataMessage().
S3FNET_INT2PTR_MAP * s3f::s3fnet::ProtocolMessage::registered_messages = 0 static inherited
A mapping between message type and message constructor.
Definition at line 158 of file protocol_message.h.
Referenced by s3f::s3fnet::ProtocolMessage::registerMessage().
unsigned int Message::__type protected inherited
Definition at line 31 of file message.h.
Referenced by Message::clone(), Message::get_type(), Message::Message(), and Message::operator=().
int Message::__evts protected inherited
Definition at line 32 of file message.h.
Referenced by Message::clone(), Message::dec_evts(), Message::inc_evts(), Message::Message(), and Message::operator=().
The documentation for this class was generated from the following files:
data_message.h
data_message.cc