S3F: s3f::s3fnet::RouteCache Class Reference
s3f::s3fnet::RouteCache Class Reference abstract
Base class for any routing caches.
#include <forwardingtable.h>
Public Types
enum RouteCacheType { SINGLE_ENTRY = 0, DIRECT_MAPPED = 1, ASSOCIATIVE = 2, NONE = 255 }
Public Member Functions
virtual RouteInfo * lookup (IPADDR ipaddr)=0
virtual void update (IPADDR ipaddr, RouteInfo *route)=0
virtual void invalidate ()=0
Detailed Description
Base class for any routing caches.
Stores a limited subset of RouteInfo values for faster lookup than in the Trie structure.
This class is designed to allow varied cache implementations regardless of the Trie implementation used at the cost of a single additional memory access vs a static, non-configurable cache as part of ForwardingTable's data.
Definition at line 177 of file forwardingtable.h.
Member Enumeration Documentation
enum s3f::s3fnet::RouteCache::RouteCacheType
Enumerator
SINGLE_ENTRY
DIRECT_MAPPED
ASSOCIATIVE
NONE
Definition at line 179 of file forwardingtable.h.
{
                 SINGLE_ENTRY = 0,
                 DIRECT_MAPPED = 1,
                 ASSOCIATIVE = 2,
                 NONE = 255
         };
Member Function Documentation
virtual RouteInfo* s3f::s3fnet::RouteCache::lookup (IPADDR ipaddr) pure virtual
Implemented in s3f::s3fnet::routecache2::RouteCache2, s3f::s3fnet::routecache1::RouteCache1, and s3f::s3fnet::routecache0::RouteCache0.
Referenced by s3f::s3fnet::ForwardingTable::getRoute().
virtual void s3f::s3fnet::RouteCache::update (IPADDR ipaddr, RouteInfo * route) pure virtual
Implemented in s3f::s3fnet::routecache2::RouteCache2, s3f::s3fnet::routecache1::RouteCache1, and s3f::s3fnet::routecache0::RouteCache0.
Referenced by s3f::s3fnet::ForwardingTable::getRoute().
virtual void s3f::s3fnet::RouteCache::invalidate () pure virtual
Implemented in s3f::s3fnet::routecache2::RouteCache2, s3f::s3fnet::routecache1::RouteCache1, and s3f::s3fnet::routecache0::RouteCache0.
Referenced by s3f::s3fnet::ForwardingTable::addRoute(), and s3f::s3fnet::ForwardingTable::removeRoute().
The documentation for this class was generated from the following file:
forwardingtable.h