S3F: s3f::s3fnet::OpenFlowSwitchSession Class Reference
s3f::s3fnet::OpenFlowSwitchSession Class Reference
An OpenFlow switch that switches multiple LAN segments via an OpenFlow-compatible flow table.
#include <openflow_switch_session.h>
Public Types
enum InstantiationType { PROT_UNIQUE_INSTANCE = 0x00, PROT_MULTIPLE_INSTANCES = 0x01, PROT_MULTIPLE_IMPLEMENTATIONS = 0x02 }
Multiple protocol session instantiation type.
enum ExecutionStage { PSESS_CREATED = 0, PSESS_CONFIGURED = 1, PSESS_INITIALIZED = 2, PSESS_WRAPPED_UP = 3 }
A normal protocol session must go though the following stages.
Public Member Functions
virtual void wrapup ()
The method is used to wrap up the protocol session.
int pushdown (Activation msg, ProtocolSession *hi_sess, void *extinfo=0, size_t extinfo_size=0)
The original push method is divided into pushdown() and push().
int popup (Activation msg, ProtocolSession *lo_sess, void *extinfo=0, size_t extinfo_size=0)
The original pop method is divided into popup() and pop().
ProtocolGraph * inGraph ()
The method returns the protocol graph in which this protocol session resides.
virtual Host * inHost ()
Return a pointer to the host owning this protocol session.
Random::RNG * getRandom ()
The method returns a pointer to the random number generator.
ltime_t getNow ()
The method returns the current simulation time.
char * getNowWithThousandSeparator ()
For printing the current simulation time in a better readable format.
int configured ()
This method returns true if the protocol session has been configured.
int initialized ()
This method returns true if the protocol session has been initialized.
int wrapped_up ()
This method returns true if the protocol session has been wrapped up.
virtual const char * psesstype ()
From NetDevice
virtual bool SetMtu (const uint16_t mtu)
virtual uint16_t GetMtu (void) const
virtual bool IsLinkUp (void) const
Public Attributes
NetworkInterface * ofctrl_port
the NetworkInterface of the OpenFlow controller
bool is_ctrl_sess
whether it connects to an entity-based controller instead of non-entity controller
S3FNET_STRING ctrl_nhi
the nhi of the controller entity
Host * ctrl_host
the Host* of the active controller
OpenFlowControllerSession * ctrl_sess
pointer of the controller protocol session
char * name
Symbolic name of the protocol this session implements.
float version
Version number of this protocol implemenntation, represented as a floating point number (e.g., 1.23).
char * use
Name of the protocol class from which this protocol session is instantiated.
Protected Member Functions
virtual void DoDispose (void)
ofpbuf * BufferFromPacket (ProtocolMessage *packet)
virtual int instantiation_type ()
This method controls how protocol instances can coexist with one another.
Protected Attributes
ProtocolGraph * ingraph
Points to the protocol graph.
Random::RNG * sess_rng
Pointer to a random number generator.
int stage
This variable indicates the current stage of this protocol session.
Private Member Functions
int AddFlow (const ofp_flow_mod *ofm)
int ModFlow (const ofp_flow_mod *ofm)
int OutputAll (uint32_t packet_uid, int in_port, bool flood)
void OutputPacket (uint32_t packet_uid, int out_port)
void OutputPort (uint32_t packet_uid, int in_port, int out_port, bool ignore_no_fwd)
void OutputControl (uint32_t packet_uid, int in_port, size_t max_len, int reason)
void SendErrorMsg (uint16_t type, uint16_t code, const void *data, size_t len)
void SendFeaturesReply ()
void SendFlowExpired (sw_flow *flow, enum ofp_flow_expired_reason reason)
void SendPortStatus (Port p, uint8_t status)
void SendVPortTableFeatures ()
int SendOpenflowBuffer (ofpbuf *buffer)
void RunThroughFlowTable (uint32_t packet_uid, int port, bool send_to_controller=true)
int RunThroughVPortTable (uint32_t packet_uid, int port, uint32_t vport)
void FlowTableLookup (sw_flow_key key, ofpbuf *buffer, uint32_t packet_uid, int port, bool send_to_controller)
int UpdatePortStatus (Port &p)
void FillPortDesc (Port p, ofp_phy_port *desc)
void * MakeOpenflowReply (size_t openflow_len, uint8_t type, ofpbuf **bufferp)
OpenFlowSwitchSession Description Data
These four data describe the OpenFlowSwitchSession as if it were a real OpenFlow switch.
There is a type of stats request that OpenFlow switches are supposed to handle that returns the description of the OpenFlow switch. Currently manufactured by "The S3F team", software description is "Simulated OpenFlow Switch", and the other two are "N/A".
static const char * GetManufacturerDescription ()
static const char * GetHardwareDescription ()
static const char * GetSoftwareDescription ()
static const char * GetSerialNumber ()
OpenFlowSwitchSession (ProtocolGraph *graph)
the constructor must be take an argument of the protocol graph
virtual ~OpenFlowSwitchSession ()
the destructor
virtual int getProtocolNumber ()
each protocol must have a unique protocol number
virtual void config (s3f::dml::Configuration *cfg)
called to configure this protocol session
virtual void init ()
called after config() to initialize this protocol session
virtual int control (int ctrltyp, void *ctrlmsg, ProtocolSession *sess)
called by other protocol sessions to send special control messages
virtual int push (Activation msg, ProtocolSession *hi_sess, void *extinfo=0, std::size_t extinfo_size=0)
called by the protocol session above to push a protocol message down the protocol stack
virtual int pop (Activation msg, ProtocolSession *lo_sess, void *extinfo=0, size_t extinfo_size=0)
called by the protocol session below to pop a protocol message up the protocol stack
void SetController ()
Set up the Switch's controller connection.
int AddSwitchPort (NetworkInterface *switchPort)
Add a 'port' to a switch device.
int AddVPort (const ofp_vport_mod *ovpm)
Add a virtual port to a switch device.
int StatsDump (StatsDumpCallback *cb_)
Stats callback is ready for a dump.
void StatsDone (StatsDumpCallback *cb_)
Stats callback is done.
void DoOutput (uint32_t packet_uid, int in_port, size_t max_len, int out_port, bool ignore_no_fwd)
Called from the OpenFlow Interface to output the Packet on either a Port or the Controller.
int ForwardControlInput (const void *msg, size_t length)
The registered controller calls this method when sending a message to the switch.
virtual void HandleControlInput (Activation pkt)
sw_chain * GetChain ()
uint32_t GetNSwitchPorts (void) const
int GetSwitchPortIndex (Port p)
Port GetSwitchPort (uint32_t n) const
vport_table_t GetVPortTable ()
Receive Methods
Actions to do when a specific OpenFlow message/packet is received
Parameters
msg The OpenFlow message received.
Returns
0 if everything's ok, otherwise an error number.
typedef std::map< uint32_t,
SwitchPacketMetadata > PacketData_t
typedef std::vector< Port > Ports_t
Mac48Address * m_address
Address of this device. (the base MAC address, should not be used as for now)
uint16_t m_mtu
Maximum Transmission Unit.
PacketData_t m_packetData
Packet data.
Ports_t m_ports
Switch's ports.
Controller * np_controller
Connection to the non-entity controller; controller is not implemented as a protocol session, but as direct function calls.
uint64_t m_id
Unique identifier for this switch, needed for OpenFlow.
ltime_t m_lastExecute
Last time the periodic execution occurred.
uint16_t m_flags
Flags; configurable by the controller.
uint16_t m_missSendLen
Flow Table Miss Send Length; configurable by the controller.
sw_chain * m_chain
Flow Table; forwarding rules.
vport_table_t m_vportTable
Virtual Port Table.
static const uint16_t DEFAULT_MTU = 1500
int ReceiveFeaturesRequest (const void *msg)
int ReceiveGetConfigRequest (const void *msg)
int ReceiveSetConfig (const void *msg)
int ReceivePacketOut (const void *msg)
int ReceiveFlow (const void *msg)
int ReceivePortMod (const void *msg)
int ReceiveStatsRequest (const void *oh)
int ReceiveEchoRequest (const void *oh)
int ReceiveEchoReply (const void *oh)
int ReceiveVPortMod (const void *msg)
int ReceiveVPortTableFeaturesRequest (const void *msg)
Detailed Description
An OpenFlow switch that switches multiple LAN segments via an OpenFlow-compatible flow table.
The OpenFlowSwitchSession object aggregates multiple NetworkInterface as ports and acts like a switch. It implements OpenFlow-compatibility, according to the OpenFlow Switch Specification v0.8.9 <www.openflowswitch.org/documents/openflow-spec-v0.8.9.pdf>. It implements a flow table that all received packets are run through. It implements a connection to a controller via a subclass of the Controller class, which can send messages to manipulate the flow table, thereby manipulating how the OpenFlow switch behaves.
Definition at line 39 of file openflow_switch_session.h.
Member Typedef Documentation
typedef std::map<uint32_t,SwitchPacketMetadata> s3f::s3fnet::OpenFlowSwitchSession::PacketData_t private
Definition at line 466 of file openflow_switch_session.h.
typedef std::vector<Port> s3f::s3fnet::OpenFlowSwitchSession::Ports_t private
Definition at line 469 of file openflow_switch_session.h.
Member Enumeration Documentation
enum s3f::s3fnet::ProtocolSession::InstantiationType inherited
Multiple protocol session instantiation type.
Enumerator
PROT_UNIQUE_INSTANCE
PROT_MULTIPLE_INSTANCES
PROT_MULTIPLE_IMPLEMENTATIONS
Definition at line 44 of file protocol_session.h.
{
     PROT_UNIQUE_INSTANCE                = 0x00,
     PROT_MULTIPLE_INSTANCES             = 0x01,
     PROT_MULTIPLE_IMPLEMENTATIONS       = 0x02
   };
enum s3f::s3fnet::ProtocolSession::ExecutionStage inherited
A normal protocol session must go though the following stages.
Enumerator
PSESS_CREATED
this protocol session has just been created
PSESS_CONFIGURED
the config method of this protocol session has been called
PSESS_INITIALIZED
the init method of this protocol session has been called
PSESS_WRAPPED_UP
Definition at line 51 of file protocol_session.h.
                       {
     PSESS_CREATED       = 0,
     PSESS_CONFIGURED    = 1,
     PSESS_INITIALIZED   = 2,
     PSESS_WRAPPED_UP    = 3
   };
Constructor & Destructor Documentation
s3f::s3fnet::OpenFlowSwitchSession::OpenFlowSwitchSession (ProtocolGraph * graph)
the constructor must be take an argument of the protocol graph
Definition at line 66 of file openflow_switch_session.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::GenerateId(), m_chain, m_id, m_ports, m_vportTable, and OF_SWITCH_DUMP.
                                                                  :
                                 ProtocolSession(graph), m_mtu(0xffff), m_lastExecute(0),
                                 np_controller(0), m_flags(0), m_missSendLen(OFP_DEFAULT_MISS_SEND_LEN), m_address(0),
                                 ofctrl_port(NULL), is_ctrl_sess(false), ctrl_host(0), ctrl_sess(0)
 {
         // create your session-related variables here
         OF_SWITCH_DUMP(printf("An OpenFlow switch protocol session is created.\n"));
         time_init (); // OFSI's clock; needed to use the buffer storage system.
         m_chain = chain_create ();
         if (m_chain == 0)
         {
                 error_quit ("Not enough memory to create the flow table.");
         }
         m_id = GenerateId();
         m_ports.reserve (DP_MAX_PORTS);
         vport_table_init (&m_vportTable);
 }
s3f::s3fnet::OpenFlowSwitchSession::~OpenFlowSwitchSession () virtual
the destructor
Definition at line 88 of file openflow_switch_session.cc.
References DoDispose(), and OF_SWITCH_DUMP.
 {
         // reclaim your session-related variables here
         OF_SWITCH_DUMP(printf("An openflow switch protocol session is reclaimed.\n"));
         DoDispose();
 }
Member Function Documentation
const char * s3f::s3fnet::OpenFlowSwitchSession::GetManufacturerDescription () static
Definition at line 38 of file openflow_switch_session.cc.
Referenced by s3f::s3fnet::Stats::DescStatsDump().
 {
         return "The S3F team";
 }
const char * s3f::s3fnet::OpenFlowSwitchSession::GetHardwareDescription () static
Definition at line 43 of file openflow_switch_session.cc.
Referenced by s3f::s3fnet::Stats::DescStatsDump().
 {
         return "N/A";
 }
const char * s3f::s3fnet::OpenFlowSwitchSession::GetSoftwareDescription () static
Definition at line 48 of file openflow_switch_session.cc.
Referenced by s3f::s3fnet::Stats::DescStatsDump().
 {
         return "Simulated OpenFlow Switch";
 }
const char * s3f::s3fnet::OpenFlowSwitchSession::GetSerialNumber () static
Definition at line 53 of file openflow_switch_session.cc.
Referenced by s3f::s3fnet::Stats::DescStatsDump().
 {
         return "N/A";
 }
virtual int s3f::s3fnet::OpenFlowSwitchSession::getProtocolNumber () inline virtual
each protocol must have a unique protocol number
Implements s3f::s3fnet::ProtocolSession.
Definition at line 64 of file openflow_switch_session.h.
References s3f::s3fnet::S3FNET_PROTOCOL_TYPE_OPENFLOW_SWITCH.
 { return S3FNET_PROTOCOL_TYPE_OPENFLOW_SWITCH; }
void s3f::s3fnet::OpenFlowSwitchSession::config (s3f::dml::Configuration * cfg) virtual
called to configure this protocol session
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 96 of file openflow_switch_session.cc.
References s3f::s3fnet::ProtocolSession::config(), ctrl_nhi, s3f::s3fnet::error_quit(), and OF_SWITCH_DUMP.
Referenced by OutputAll(), and RunThroughFlowTable().
 {
         // the same method at the parent class must be called
         ProtocolSession::config(cfg);
         char* str = (char*) cfg->findSingle("controller");
         if(str)
         {
                 if(s3f::dml::dmlConfig::isConf(str))
                         error_quit("ERROR: OpenFlowSwitchSession::config(), invalid controller attribute.\n");
                 ctrl_nhi = str;
                 OF_SWITCH_DUMP(printf("\t active controller = %s \n", ctrl_nhi.c_str()));
         }
 }
void s3f::s3fnet::OpenFlowSwitchSession::init () virtual
called after config() to initialize this protocol session
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 112 of file openflow_switch_session.cc.
References AddSwitchPort(), DEFAULT_MTU, s3f::s3fnet::Host::getNetworkInterfaceMap(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::ProtocolSession::init(), is_ctrl_sess, OF_SWITCH_DUMP, SetController(), and SetMtu().
 {
         // the same method at the parent class must be called
         ProtocolSession::init();
         // initialize the session-related variables here
         OF_SWITCH_DUMP(printf("OpenFlow switch session is initialized.\n"));
         if( inHost()->inNet()->openflow_controller_type() == 1 ) // entity-based controller, controller is a protocol session
                 is_ctrl_sess = true;
         else
                 is_ctrl_sess = false;
         /* set up controller */
         OF_SWITCH_DUMP(printf("**** Set up Controller\n"));
         SetController();
         /* add switch ports */
         S3FNET_HOST_IFACE_MAP ifaces = inHost()->getNetworkInterfaceMap();
         S3FNET_HOST_IFACE_MAP::iterator iter;
         for(iter=ifaces.begin(); iter!=ifaces.end(); ++iter)
         {
                 OF_SWITCH_DUMP( printf("Add SwitchPort %d\n", (*iter).first) );
                 NetworkInterface* nw_iface = (*iter).second;
                 AddSwitchPort (nw_iface);
         }
         SetMtu(DEFAULT_MTU);
 }
int s3f::s3fnet::OpenFlowSwitchSession::control (int ctrltyp, void * ctrlmsg, ProtocolSession * sess) virtual
called by other protocol sessions to send special control messages
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 142 of file openflow_switch_session.cc.
References s3f::s3fnet::ProtocolSession::control(), s3f::s3fnet::OPENFLOW_SWITCH_CTRL_COMMAND1, and s3f::s3fnet::OPENFLOW_SWITCH_CTRL_COMMAND2.
 {
         switch(ctrltyp)
         {
         case OPENFLOW_SWITCH_CTRL_COMMAND1:
         case OPENFLOW_SWITCH_CTRL_COMMAND2:
                 return 0; // openflow switch control commands, not in use yet
         default:
                 return ProtocolSession::control(ctrltyp, ctrlmsg, sess);
         }
 }
int s3f::s3fnet::OpenFlowSwitchSession::push (Activation msg, ProtocolSession * hi_sess, void * extinfo = 0, std::size_t extinfo_size = 0) virtual
called by the protocol session above to push a protocol message down the protocol stack
Definition at line 155 of file openflow_switch_session.cc.
References s3f::s3fnet::error_quit().
 {
         error_quit("ERROR: a message is pushed down to the openflow switch session from protocol layer above; it's impossible for now.\n");
         return 0;
 }
int s3f::s3fnet::OpenFlowSwitchSession::pop (Activation msg, ProtocolSession * lo_sess, void * extinfo = 0, size_t extinfo_size = 0) virtual
called by the protocol session below to pop a protocol message up the protocol stack
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 161 of file openflow_switch_session.cc.
References s3f::s3fnet::SwitchPacketMetadata::buffer, BufferFromPacket(), s3f::s3fnet::SwitchPacketMetadata::dst, s3f::s3fnet::SimpleMacMessage::dst48, s3f::s3fnet::error_quit(), s3f::s3fnet::Host::getNetworkInterface(), s3f::s3fnet::ProtocolSession::inHost(), m_address, m_chain, m_lastExecute, m_packetData, m_ports, Entity::now(), s3f::s3fnet::MACOptionToAbove::nw_iface, OF_SWITCH_DUMP, s3f::s3fnet::SwitchPacketMetadata::packet, s3f::s3fnet::MACOptionToAbove::protocol_no, s3f::s3fnet::SwitchPacketMetadata::protocolNumber, RunThroughFlowTable(), save_buffer(), SendFlowExpired(), SendPortStatus(), s3f::s3fnet::SwitchPacketMetadata::src, s3f::s3fnet::SimpleMacMessage::src48, and UpdatePortStatus().
 {
         OF_SWITCH_DUMP(printf("A message is popped up to the openflow switch session from the MAC layer.\n"));
         MACOptionToAbove* macopt = (MACOptionToAbove*)extinfo;
         NetworkInterface* netdev = inHost()->getNetworkInterface(macopt->nw_iface);
         if(netdev == NULL) error_quit("OpenFlowSwitchSession::pop(), not able to find network interface");
         ProtocolMessage* packet = (ProtocolMessage*)msg;
         OF_SWITCH_DUMP (cout << "Switch[" << inHost()->nhi.toString()<< "], ID [" << m_address << "] --------------------------------------------" << endl);
         for (size_t i = 0; i < m_ports.size (); i++)
         {
                 if (m_ports[i].netdev == netdev)
                 {
                         SwitchPacketMetadata data;
                         //data.packet = packet->clone();
                         data.packet = packet;
                         //pthread_mutex_lock(&(inHost()->getTopNet()->of_buf_mutex));
                         ofpbuf *buffer = BufferFromPacket (data.packet); //kevin: as for now, all Mtu has the same size
                         //pthread_mutex_unlock(&(inHost()->getTopNet()->of_buf_mutex));
                         m_ports[i].rx_packets++;
                         m_ports[i].rx_bytes += buffer->size;
                         data.buffer = buffer;
                         pthread_mutex_lock(&(inHost()->getTopNet()->of_buf_mutex));
                         uint32_t packet_uid = save_buffer (buffer);
                         pthread_mutex_unlock(&(inHost()->getTopNet()->of_buf_mutex));
                         SimpleMacMessage* l2_hdr = (SimpleMacMessage*)packet; //kevn: as for now, directly use SimpleMacMessage, will need to check layer2 msg type later
                         data.src = l2_hdr->src48;
                         data.dst = l2_hdr->dst48;
                         data.protocolNumber = (uint16_t)(macopt->protocol_no);
                         m_packetData.insert (std::make_pair (packet_uid, data));
                         OF_SWITCH_DUMP ( cout << "Switch[" << inHost()->nhi.toString()<< "], Received packet from " << l2_hdr->src48 << " looking for " << l2_hdr->dst48 << endl );
                         //temp
                         //cout << "Switch[" << inHost()->nhi.toString() << "], packet_uid = " << packet_uid << " i = " << i << endl;
                         RunThroughFlowTable (packet_uid, i);
                         break;
                 }
         }
         // Run periodic execution.
         ltime_t now = inHost()->now();
         if (now >= m_lastExecute + 1) // If a second or more has passed from the simulation time, execute.
         {
                 // If port status is modified in any way, notify the controller.
                 for (size_t i = 0; i < m_ports.size (); i++)
                 {
                         if (UpdatePortStatus (m_ports[i]))
{
                                 SendPortStatus (m_ports[i], OFPPR_MODIFY);
                         }
                 }
                 // If any flows have expired, delete them and notify the controller.
                 List deleted = LIST_INITIALIZER (&deleted);
                 sw_flow *f, *n;
                 chain_timeout (m_chain, &deleted);
                 LIST_FOR_EACH_SAFE (f, n, sw_flow, node, &deleted)
                 {
                         std::ostringstream str;
                         str << "Flow [";
                         for (int i = 0; i < 6; i++)
                                 str << (i!=0 ? ":" : "") << std::hex << f->key.flow.dl_src[i]/16 << f->key.flow.dl_src[i]%16;
                         str << " -> ";
                         for (int i = 0; i < 6; i++)
                                 str << (i!=0 ? ":" : "") << std::hex << f->key.flow.dl_dst[i]/16 << f->key.flow.dl_dst[i]%16;
                         str <<  "] expired.";
                         OF_SWITCH_DUMP (cout << str.str () << endl);
                         SendFlowExpired (f, (ofp_flow_expired_reason)f->reason);
                         list_remove (&f->node);
                         flow_free (f);
                 }
                 m_lastExecute = now;
         }
         // returning 0 indicates success
         return 0;
 }
void s3f::s3fnet::OpenFlowSwitchSession::SetController ()
Set up the Switch's controller connection.
Definition at line 270 of file openflow_switch_session.cc.
References ctrl_host, ctrl_nhi, ctrl_sess, s3f::s3fnet::error_quit(), s3f::s3fnet::Net::get_of_controller(), s3f::s3fnet::Net::getNameService(), s3f::s3fnet::NameService::hostnhi2hostobj(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::Host::inNet(), is_ctrl_sess, s3f::s3fnet::NO_OF_CONTROLLER, np_controller, s3f::s3fnet::OF_DROP_CONTROLLER, OF_FLOW_EXPIRATION_TIME, s3f::s3fnet::OF_LEARNING_SWITCH_CONTROLLER, s3f::s3fnet::OF_LEARNING_SWITCH_CONTROLLER_ENTITY, s3f::s3fnet::S3FNET_PROTOCOL_TYPE_OPENFLOW_CONTROLLER, s3f::s3fnet::ProtocolGraph::sessionForNumber(), s3f::s3fnet::Controller::type, and s3f::s3fnet::OpenFlowControllerSession::type.
Referenced by init().
 {
         if(is_ctrl_sess == true) //controller protocol session
         {
                 ctrl_host = inHost()->inNet()->getNameService()->hostnhi2hostobj(ctrl_nhi);
                 assert(ctrl_host);
                 ctrl_sess = (OpenFlowControllerSession*)(ctrl_host->sessionForNumber(S3FNET_PROTOCOL_TYPE_OPENFLOW_CONTROLLER));
                 assert(ctrl_sess);
                 switch(ctrl_sess->type)
                 {
                 case OF_LEARNING_SWITCH_CONTROLLER_ENTITY:
                         ((LearningControllerSession*)ctrl_sess)->setFlowExpirationTime(OF_FLOW_EXPIRATION_TIME);
                         ((LearningControllerSession*)ctrl_sess)->AddSwitch(this);
                         break;
                 case NO_OF_CONTROLLER:
                         error_quit("OpenFlowSwitchSession::SetController(), no controller entity.");
                         break;
                 default:
                         error_quit("OpenFlowSwitchSession::SetController(), wrong controller entity type.");
                         break;
                 }
         }
         else //controller non-protocol session, direct function calls
         {
                 np_controller = inHost()->inNet()->get_of_controller();
                 assert(np_controller);
                 switch(np_controller->type)
                 {
                 case OF_LEARNING_SWITCH_CONTROLLER:
                         ((LearningController*)np_controller)->AddSwitch(this);
                         break;
                 case OF_DROP_CONTROLLER:
                         ((DropController*)np_controller)->AddSwitch(this);
                         break;
                 case NO_OF_CONTROLLER:
                         error_quit("OpenFlowSwitchSession::SetController(), no controller.");
                         break;
                 default:
                         error_quit("OpenFlowSwitchSession::SetController(), wrong controller type.");
                         break;
                 }
         }
 }
int s3f::s3fnet::OpenFlowSwitchSession::AddSwitchPort (NetworkInterface * switchPort)
Add a 'port' to a switch device.
This method adds a new switch port to a OpenFlowSwitchSession, so that the new switch port (NetworkInterface) becomes part of the switch and L2 frames start being forwarded to/from this NetworkInterface.
Parameters
switchPort The port to add.
Returns
0 if everything's ok, otherwise an error number.
Definition at line 321 of file openflow_switch_session.cc.
References s3f::s3fnet::Port::config, s3f::s3fnet::NetworkInterface::getMac48Addr(), m_address, m_ports, s3f::s3fnet::Port::netdev, and SendPortStatus().
Referenced by init().
 {
         if (m_address == 0)
         {
                 m_address = switchPort->getMac48Addr();
         }
         if (m_ports.size () < DP_MAX_PORTS)
         {
                 Port p;
                 p.config = 0;
                 p.netdev = switchPort;
                 m_ports.push_back (p);
                 // Notify the controller that this port has been added
                 SendPortStatus (p, OFPPR_ADD);
         }
         else
         {
                 return EXFULL;
         }
         return 0;
 }
int s3f::s3fnet::OpenFlowSwitchSession::AddVPort (const ofp_vport_mod * ovpm)
Add a virtual port to a switch device.
The Ericsson OFSID has the concept of virtual ports and virtual port tables. These are implemented in the OpenFlowSwitchSession, but don't have an understood use [perhaps it may have to do with MPLS integration].
Parameters
ovpm The data for adding a virtual port.
Returns
0 if everything's ok, otherwise an error number.
Definition at line 376 of file openflow_switch_session.cc.
References EINVAL, m_vportTable, OF_SWITCH_DUMP, SendErrorMsg(), and s3f::s3fnet::ValidateVPortActions().
Referenced by ReceiveVPortMod().
 {
         size_t actions_len = ntohs (ovpm->header.length) - sizeof *ovpm;
         unsigned int vport = ntohl (ovpm->vport);
         unsigned int parent_port = ntohl (ovpm->parent_port);
         // check whether port table entry exists for specified port number
         vport_table_entry *vpe = vport_table_lookup (&m_vportTable, vport);
         if (vpe != 0)
         {
                 OF_SWITCH_DUMP ( cout << "vport " << vport << " already exists!" << endl );
                 SendErrorMsg (OFPET_BAD_ACTION, OFPET_VPORT_MOD_FAILED, ovpm, ntohs (ovpm->header.length));
                 return EINVAL;
         }
         // check whether actions are valid
         uint16_t v_code = ValidateVPortActions (ovpm->actions, actions_len);
         if (v_code != ACT_VALIDATION_OK)
         {
                 SendErrorMsg (OFPET_BAD_ACTION, v_code, ovpm, ntohs (ovpm->header.length));
                 return EINVAL;
         }
         vpe = vport_table_entry_alloc (actions_len);
         vpe->vport = vport;
         vpe->parent_port = parent_port;
         if (vport < OFPP_VP_START || vport > OFPP_VP_END)
         {
                 OF_SWITCH_DUMP ( cout << "port " << vport << " is not in the virtual port range (" << OFPP_VP_START << "-" << OFPP_VP_END << ")" << endl );
                 SendErrorMsg (OFPET_BAD_ACTION, OFPET_VPORT_MOD_FAILED, ovpm, ntohs (ovpm->header.length));
                 free_vport_table_entry (vpe); // free allocated entry
                 return EINVAL;
         }
         vpe->port_acts->actions_len = actions_len;
         memcpy (vpe->port_acts->actions, ovpm->actions, actions_len);
         int error = insert_vport_table_entry (&m_vportTable, vpe);
         if (error)
         {
                 OF_SWITCH_DUMP ( cout << "could not insert port table entry for port " << vport << endl );
         }
         return error;
 }
int s3f::s3fnet::OpenFlowSwitchSession::StatsDump (StatsDumpCallback * cb_)
Stats callback is ready for a dump.
Controllers have a callback system for status requests which calls this function.
Parameters
cb_ The callback data.
Returns
0 if everything's ok, otherwise an error number.
Definition at line 1311 of file openflow_switch_session.cc.
References s3f::s3fnet::Stats::DoDump(), s3f::s3fnet::StatsDumpCallback::done, MakeOpenflowReply(), s3f::s3fnet::StatsDumpCallback::s, SendOpenflowBuffer(), s3f::s3fnet::StatsDumpCallback::state, and s3f::s3fnet::Stats::type.
Referenced by s3f::s3fnet::Controller::StartDump(), and s3f::s3fnet::OpenFlowControllerSession::StartDump().
 {
         ofp_stats_reply *osr;
         ofpbuf *buffer;
         int err;
         if (cb->done)
         {
                 return 0;
         }
         osr = (ofp_stats_reply*)MakeOpenflowReply (sizeof *osr, OFPT_STATS_REPLY, &buffer);
         osr->type = htons (cb->s->type);
         osr->flags = 0;
         err = cb->s->DoDump (this, cb->state, buffer);
         if (err >= 0)
         {
                 if (err == 0)
                 {
                         cb->done = true;
                 }
                 else
                 {
                         // Buffer might have been reallocated, so find our data again.
                         osr = (ofp_stats_reply*)ofpbuf_at_assert (buffer, 0, sizeof *osr);
                         osr->flags = ntohs (OFPSF_REPLY_MORE);
                 }
                 int err2 = SendOpenflowBuffer (buffer);
                 if (err2)
                 {
                         err = err2;
                 }
         }
         return err;
 }
void s3f::s3fnet::OpenFlowSwitchSession::StatsDone (StatsDumpCallback * cb_)
Stats callback is done.
Controllers have a callback system for status requests which calls this function.
Parameters
cb_ The callback data.
Definition at line 1350 of file openflow_switch_session.cc.
References s3f::s3fnet::Stats::DoCleanup(), s3f::s3fnet::StatsDumpCallback::s, and s3f::s3fnet::StatsDumpCallback::state.
Referenced by s3f::s3fnet::Controller::StartDump(), and s3f::s3fnet::OpenFlowControllerSession::StartDump().
 {
         if (cb)
         {
                 cb->s->DoCleanup (cb->state);
                 free (cb->s);
                 free (cb);
         }
 }
void s3f::s3fnet::OpenFlowSwitchSession::DoOutput (uint32_t packet_uid, int in_port, size_t max_len, int out_port, bool ignore_no_fwd)
Called from the OpenFlow Interface to output the Packet on either a Port or the Controller.
Parameters
packet_uid Packet UID; used to fetch the packet and its metadata.
in_port The index of the port the Packet was initially received on.
max_len The maximum number of bytes the caller wants to be sent; a value of 0 indicates the entire packet should be sent. Used when outputting to controller.
out_port The port we want to output on.
ignore_no_fwd If true, Ports that are set to not forward are forced to forward.
Definition at line 363 of file openflow_switch_session.cc.
References OutputControl(), and OutputPort().
Referenced by s3f::s3fnet::ExecuteActions(), and s3f::s3fnet::ExecuteVPortActions().
 {
         if (out_port != OFPP_CONTROLLER)
         {
                 OutputPort (packet_uid, in_port, out_port, ignore_no_fwd);
         }
         else
         {
                 OutputControl (packet_uid, in_port, max_len, OFPR_ACTION);
         }
 }
int s3f::s3fnet::OpenFlowSwitchSession::ForwardControlInput (const void * msg, size_t length)
The registered controller calls this method when sending a message to the switch.
Parameters
msg The message received from the controller.
length Length of the message.
Returns
0 if everything's ok, otherwise an error number.
Definition at line 1438 of file openflow_switch_session.cc.
References EINVAL, ReceiveEchoReply(), ReceiveEchoRequest(), ReceiveFeaturesRequest(), ReceiveFlow(), ReceiveGetConfigRequest(), ReceivePacketOut(), ReceivePortMod(), ReceiveSetConfig(), ReceiveStatsRequest(), ReceiveVPortMod(), ReceiveVPortTableFeaturesRequest(), and SendErrorMsg().
Referenced by HandleControlInput(), s3f::s3fnet::Controller::SendToSwitch(), and s3f::s3fnet::OpenFlowControllerSession::SendToSwitch().
 {
         // Check encapsulated length.
         ofp_header *oh = (ofp_header*) msg;
         if (ntohs (oh->length) > length)
         {
                 return -EINVAL;
         }
         assert (oh->version == OFP_VERSION);
         int error = 0;
         // Figure out how to handle it.
         switch (oh->type)
         {
         case OFPT_FEATURES_REQUEST:
                 error = length < sizeof(ofp_header) ? -EFAULT : ReceiveFeaturesRequest (msg);
                 break;
         case OFPT_GET_CONFIG_REQUEST:
                 error = length < sizeof(ofp_header) ? -EFAULT : ReceiveGetConfigRequest (msg);
                 break;
         case OFPT_SET_CONFIG:
                 error = length < sizeof(ofp_switch_config) ? -EFAULT : ReceiveSetConfig (msg);
                 break;
         case OFPT_PACKET_OUT:
                 error = length < sizeof(ofp_packet_out) ? -EFAULT : ReceivePacketOut (msg);
                 break;
         case OFPT_FLOW_MOD:
                 error = length < sizeof(ofp_flow_mod) ? -EFAULT : ReceiveFlow (msg);
                 break;
         case OFPT_PORT_MOD:
                 error = length < sizeof(ofp_port_mod) ? -EFAULT : ReceivePortMod (msg);
                 break;
         case OFPT_STATS_REQUEST:
                 error = length < sizeof(ofp_stats_request) ? -EFAULT : ReceiveStatsRequest (msg);
                 break;
         case OFPT_ECHO_REQUEST:
                 error = length < sizeof(ofp_header) ? -EFAULT : ReceiveEchoRequest (msg);
                 break;
         case OFPT_ECHO_REPLY:
                 error = length < sizeof(ofp_header) ? -EFAULT : ReceiveEchoReply (msg);
                 break;
         case OFPT_VPORT_MOD:
                 error = length < sizeof(ofp_vport_mod) ? -EFAULT : ReceiveVPortMod (msg);
                 break;
         case OFPT_VPORT_TABLE_FEATURES_REQUEST:
                 error = length < sizeof(ofp_header) ? -EFAULT : ReceiveVPortTableFeaturesRequest (msg);
                 break;
         default:
                 SendErrorMsg ((ofp_error_type)OFPET_BAD_REQUEST, (ofp_bad_request_code)OFPBRC_BAD_TYPE, msg, length);
                 error = -EINVAL;
                 break;
         }
         if (msg != 0)
         {
                 free ((ofpbuf*)msg);
         }
         return error;
 }
void s3f::s3fnet::OpenFlowSwitchSession::HandleControlInput (Activation pkt) virtual
Definition at line 1415 of file openflow_switch_session.cc.
References s3f::s3fnet::OpenFlowMessage::buffer, discard_buffer(), s3f::s3fnet::ProtocolMessage::erase(), ForwardControlInput(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::OpenFlowMessage::length, m_packetData, s3f::s3fnet::OpenFlowMessage::ofm, and s3f::s3fnet::OpenFlowMessage::packet_uid.
Referenced by s3f::s3fnet::NetworkInterface::receivePacket().
 {
         OpenFlowMessage* msg = (OpenFlowMessage*)pkt;
         ForwardControlInput(msg->ofm, msg->length);
         //claim buffer and message
         if(msg->packet_uid != -1) //direct inquiry response
         {
                 pthread_mutex_lock(&(inHost()->getTopNet()->of_buf_mutex));
                 m_packetData.erase(msg->packet_uid);
                 discard_buffer(msg->packet_uid);
                 ofpbuf_delete(msg->buffer);
                 msg->erase();
                 pthread_mutex_unlock(&(inHost()->getTopNet()->of_buf_mutex));
         }
         else //other response, e.g. learned flow in learning switch
         {
                 msg->erase();
         }
 }
sw_chain * s3f::s3fnet::OpenFlowSwitchSession::GetChain ()
Returns
The flow table chain.
Definition at line 1499 of file openflow_switch_session.cc.
References m_chain.
Referenced by s3f::s3fnet::Stats::AggregateStatsDump(), s3f::s3fnet::Stats::FlowStatsDump(), and s3f::s3fnet::Stats::TableStatsDump().
 {
         return m_chain;
 }
uint32_t s3f::s3fnet::OpenFlowSwitchSession::GetNSwitchPorts (void) const
Returns
Number of switch ports attached to this switch.
Definition at line 1504 of file openflow_switch_session.cc.
References m_ports.
 {
         return m_ports.size ();
 }
int s3f::s3fnet::OpenFlowSwitchSession::GetSwitchPortIndex (Port p)
Parameters
p The Port to get the index of.
Returns
The index of the provided Port.
Definition at line 1514 of file openflow_switch_session.cc.
References m_ports, and s3f::s3fnet::Port::netdev.
Referenced by FillPortDesc(), and s3f::s3fnet::Stats::PortStatsDump().
 {
         for (size_t i = 0; i < m_ports.size (); i++)
         {
                 if (m_ports[i].netdev == p.netdev)
                 {
                         //return i;
                         return m_ports[i].netdev->id;
                 }
         }
         return -1;
 }
Port s3f::s3fnet::OpenFlowSwitchSession::GetSwitchPort (uint32_t n) const
Parameters
n index of the Port.
Returns
The Port.
Definition at line 1509 of file openflow_switch_session.cc.
References m_ports.
Referenced by s3f::s3fnet::Stats::PortStatsDump().
 {
         return m_ports[n];
 }
vport_table_t s3f::s3fnet::OpenFlowSwitchSession::GetVPortTable ()
Returns
The virtual port table.
Definition at line 1527 of file openflow_switch_session.cc.
References m_vportTable.
Referenced by s3f::s3fnet::Stats::PortStatsDump(), and s3f::s3fnet::Stats::PortTableStatsDump().
 {
         return m_vportTable;
 }
bool s3f::s3fnet::OpenFlowSwitchSession::SetMtu (const uint16_t mtu) virtual
Definition at line 346 of file openflow_switch_session.cc.
References m_mtu.
Referenced by init().
 {
         m_mtu = mtu;
         return true;
 }
uint16_t s3f::s3fnet::OpenFlowSwitchSession::GetMtu (void) const virtual
Definition at line 352 of file openflow_switch_session.cc.
References m_mtu.
Referenced by BufferFromPacket().
 {
         return m_mtu;
 }
bool s3f::s3fnet::OpenFlowSwitchSession::IsLinkUp (void) const virtual
Definition at line 358 of file openflow_switch_session.cc.
 {
         return true;
 }
void s3f::s3fnet::OpenFlowSwitchSession::DoDispose (void) protected virtual
Definition at line 250 of file openflow_switch_session.cc.
References is_ctrl_sess, m_chain, m_ports, m_vportTable, and np_controller.
Referenced by ~OpenFlowSwitchSession().
 {
         for (Ports_t::iterator b = m_ports.begin (), e = m_ports.end (); b != e; b++)
         {
                 if(is_ctrl_sess == false)
                 {
                         //SendPortStatus (*b, OFPPR_DELETE); //temp prevent seg fault at the end
                 }
                 b->netdev = 0;
         }
         m_ports.clear ();
         if(is_ctrl_sess == false)
         {
                 np_controller = 0;
         }
         chain_destroy (m_chain);
         RBTreeDestroy (m_vportTable.table);
 }
ofpbuf * s3f::s3fnet::OpenFlowSwitchSession::BufferFromPacket (ProtocolMessage * packet) protected
Takes a packet and generates an OpenFlow buffer from it, loading the packet data as well as its headers.
Definition at line 423 of file openflow_switch_session.cc.
References s3f::s3fnet::TCPMessage::ackno, s3f::s3fnet::IPMessage::dst_ip, s3f::s3fnet::UDPMessage::dst_port, s3f::s3fnet::TCPMessage::dst_port, s3f::s3fnet::TCPMessage::flags, s3f::s3fnet::IPMessage::fragmentOffset, GetMtu(), s3f::s3fnet::IPMessage::identification, s3f::s3fnet::ProtocolSession::inHost(), OF_SWITCH_DUMP, s3f::s3fnet::ProtocolMessage::payload(), s3f::s3fnet::IPMessage::protocol_no, s3f::s3fnet::S3FNET_PROTOCOL_TYPE_TCP, s3f::s3fnet::S3FNET_PROTOCOL_TYPE_UDP, s3f::s3fnet::TCPMessage::seqno, s3f::s3fnet::IPMessage::src_ip, s3f::s3fnet::UDPMessage::src_port, s3f::s3fnet::TCPMessage::src_port, s3f::s3fnet::IPMessage::time_to_live, s3f::s3fnet::IPMessage::tos, s3f::s3fnet::IPMessage::total_length, and s3f::s3fnet::TCPMessage::wsize.
Referenced by pop().
 {
         OF_SWITCH_DUMP (cout << "Switch[" << inHost()->nhi.toString()<< "], OpenFlowSwitchSession::BufferFromPacket(), Creating Openflow buffer from packet." << endl);
         int mtu = GetMtu();
         /*
          * Allocate buffer with some headroom to add headers in forwarding
          * to the controller or adding a vlan tag, plus an extra 2 bytes to
          * allow IP headers to be aligned on a 4-byte boundary.
          */
         const int headroom = 128 + 2;
         const int hard_header = VLAN_ETH_HEADER_LEN;
         ofpbuf *buffer = ofpbuf_new (headroom + hard_header + mtu);
         buffer->data = (char*)buffer->data + headroom + hard_header;
         int l2_length = 0, l3_length = 0, l4_length = 0;
         /* layer 2 */
         //kevin: will do msg type check later
         SimpleMacMessage* l2_hdr = (SimpleMacMessage*)packet;
         buffer->l2 = new eth_header;
         eth_header* eth_h = (eth_header*)buffer->l2;
         l2_hdr->dst48->CopyTo (eth_h->eth_dst);              // Destination Mac Address
         l2_hdr->src48->CopyTo (eth_h->eth_src);              // Source Mac Address
         eth_h->eth_type = htons (ETH_TYPE_IP);    // Ether Type
         OF_SWITCH_DUMP ( cout << "Switch[" << inHost()->nhi.toString()<< "], Parsed EthernetHeader" << endl );
         l2_length = ETH_HEADER_LEN;
         /* layer 3 */
         IPMessage* l3_hdr = (IPMessage*)(l2_hdr->payload());
         buffer->l3 = new ip_header;
         ip_header* ip_h = (ip_header*)buffer->l3;
         ip_h->ip_ihl_ver  = IP_IHL_VER (5, IP_VERSION);       // Version
         ip_h->ip_tos      = l3_hdr->tos;                  // Type of Service/Differentiated Services
         ip_h->ip_tot_len  = l3_hdr->total_length;               // Total Length
         ip_h->ip_id       = l3_hdr->identification;       // Identification
         ip_h->ip_frag_off = l3_hdr->fragmentOffset;       // Fragment Offset
         ip_h->ip_ttl      = l3_hdr->time_to_live;                  // Time to Live
         ip_h->ip_proto    = l3_hdr->protocol_no;             // Protocol
         ip_h->ip_src      = htonl ((uint32_t)l3_hdr->src_ip); // Source Address
         ip_h->ip_dst      = htonl ((uint32_t)l3_hdr->dst_ip); // Destination Address
         ip_h->ip_csum     = csum (&ip_h, sizeof ip_h);        // Header Checksum
         OF_SWITCH_DUMP ( cout << "Switch[" << inHost()->nhi.toString()<< "], Parsed Ipv4Header" << endl );
         l3_length = IP_HEADER_LEN;
         /*
       // ARP Packet; the underlying OpenFlow header isn't used to match, so this is probably superfluous.
       ArpHeader arp_hd;
       if (packet->PeekHeader (arp_hd))
         {
           buffer->l3 = new arp_eth_header;
           arp_eth_header* arp_h = (arp_eth_header*)buffer->l3;
           arp_h->ar_hrd = ARP_HRD_ETHERNET;                             // Hardware type.
           arp_h->ar_pro = ARP_PRO_IP;                                   // Protocol type.
           arp_h->ar_op = arp_hd.m_type;                                 // Opcode.
           arp_hd.GetDestinationHardwareAddress ().CopyTo (arp_h->ar_tha); // Target hardware address.
           arp_hd.GetSourceHardwareAddress ().CopyTo (arp_h->ar_sha);    // Sender hardware address.
           arp_h->ar_tpa = arp_hd.GetDestinationIpv4Address ().Get ();   // Target protocol address.
           arp_h->ar_spa = arp_hd.GetSourceIpv4Address ().Get ();        // Sender protocol address.
           arp_h->ar_hln = sizeof arp_h->ar_tha;                         // Hardware address length.
           arp_h->ar_pln = sizeof arp_h->ar_tpa;                         // Protocol address length.
           OF_SWITCH_DUMP ( cout << "Parsed ArpHeader" << endl );
           l3_length = ARP_ETH_HEADER_LEN;
         }
          */
         if(l3_hdr->protocol_no == S3FNET_PROTOCOL_TYPE_TCP)
         {
                 TCPMessage* tcp_hd = (TCPMessage*)(l3_hdr->payload());
                 buffer->l4 = new tcp_header;
                 tcp_header* tcp_h = (tcp_header*)buffer->l4;
                 tcp_h->tcp_src = htonl (tcp_hd->src_port);         // Source Port
                 tcp_h->tcp_dst = htonl (tcp_hd->dst_port);    // Destination Port
                 tcp_h->tcp_seq = tcp_hd->seqno; // Sequence Number
                 tcp_h->tcp_ack = tcp_hd->ackno;      // ACK Number
                 tcp_h->tcp_ctl = TCP_FLAGS (tcp_hd->flags);  // Data Offset + Reserved + Flags
                 tcp_h->tcp_winsz = tcp_hd->wsize;       // Window Size
                 tcp_h->tcp_urg = 0;      // Urgent Pointer (currently not set)
                 tcp_h->tcp_csum = csum (&tcp_h, sizeof tcp_h);    // Header Checksum
                 OF_SWITCH_DUMP ( cout << "Switch[" << inHost()->nhi.toString()<< "], Parsed TcpHeader" << endl );
                 l4_length = TCP_HEADER_LEN;
         }
         else if (l3_hdr->protocol_no == S3FNET_PROTOCOL_TYPE_UDP)
         {
                 UDPMessage* udp_hd = (UDPMessage*)(l3_hdr->payload());
                 buffer->l4 = new udp_header;
                 udp_header* udp_h = (udp_header*)buffer->l4;
                 udp_h->udp_src = htonl (udp_hd->src_port);     // Source Port
                 udp_h->udp_dst = htonl (udp_hd->dst_port); // Destination Port
                 //udp_h->udp_len = htons (UDP_HEADER_LEN + udp_hd->payload()->packingSize());
                 udp_h->udp_len = htons (UDP_HEADER_LEN);
                 //if (ipopt->protocol_no == Ipv4L3Protocol::PROT_NUMBER)
                 //{
                 /*  ip_header* ip_h = (ip_header*)buffer->l3;
           uint32_t udp_csum = csum_add32 (0, ip_h->ip_src);
           udp_csum = csum_add32 (udp_csum, ip_h->ip_dst);
           udp_csum = csum_add16 (udp_csum, IP_TYPE_UDP << 8);
           udp_csum = csum_add16 (udp_csum, udp_h->udp_len);
           udp_csum = csum_continue (udp_csum, udp_h, sizeof udp_h);
           udp_h->udp_csum = csum_finish (csum_continue (udp_csum, buffer->data, buffer->size)); // Header Checksum
                  */
                 //}
                 //else
                 //{
                 udp_h->udp_csum = htons (0);
                 //}
                 OF_SWITCH_DUMP ( cout << "Switch[" << inHost()->nhi.toString()<< "], Parsed UdpHeader" << endl );
                 l4_length = UDP_HEADER_LEN;
         }
         // Load Packet data into buffer data
         // as for now, payload is not inspected for rules, just add something here, will replace with payload data in the future
         //packet->CopyData ((uint8_t*)buffer->data, packet->GetSize ());
         if (buffer->l4)
         {
                 /*  cout          << " udp_len = " << ((udp_header*)(buffer->l4))->udp_len
                           << " udp_src = " << udp_h->udp_src
                           << " udp_dst = " << ((udp_header*)(buffer->l4))->udp_dst
                           << " udp_csum = " << ((udp_header*)(buffer->l4))->udp_csum
                           << " l4_length = " <<  l4_length
                           << " udp_hd->src_port = " << udp_hd->src_port
                           << " udp_hd->dst_port = " << udp_hd->dst_port
                           << endl;*/
                 ofpbuf_push (buffer, buffer->l4, l4_length);
                 //ofpbuf_push (buffer, buffer->l4, 1);
                 if(l3_hdr->protocol_no == S3FNET_PROTOCOL_TYPE_TCP)
                         delete (tcp_header*)buffer->l4;
                 else if(l3_hdr->protocol_no == S3FNET_PROTOCOL_TYPE_UDP)
                         delete (udp_header*)buffer->l4;
         }
         if (buffer->l3)
         {
                 ofpbuf_push (buffer, buffer->l3, l3_length);
                 delete (ip_header*)buffer->l3;
         }
         if (buffer->l2)
         {
                 ofpbuf_push (buffer, buffer->l2, l2_length);
                 delete (eth_header*)buffer->l2;
         }
         return buffer;
 }
int s3f::s3fnet::OpenFlowSwitchSession::AddFlow (const ofp_flow_mod * ofm) private
Add a flow.
Parameters
ofm The flow data to add.
Returns
0 if everything's ok, otherwise an error number.
Definition at line 1140 of file openflow_switch_session.cc.
References discard_buffer(), s3f::s3fnet::ExecuteActions(), s3f::s3fnet::ProtocolSession::inHost(), m_chain, Entity::now(), OF_SWITCH_DUMP, retrieve_buffer(), SendErrorMsg(), and s3f::s3fnet::ValidateActions().
Referenced by ReceiveFlow().
 {
         size_t actions_len = ntohs (ofm->header.length) - sizeof *ofm;
         // Allocate memory.
         sw_flow *flow = flow_alloc (actions_len);
         if (flow == 0)
         {
                 if (ntohl (ofm->buffer_id) != (uint32_t) -1)
                 {
                         pthread_mutex_lock(&(inHost()->getTopNet()->of_buf_mutex));
                         discard_buffer (ntohl (ofm->buffer_id));
                         pthread_mutex_unlock(&(inHost()->getTopNet()->of_buf_mutex));
                 }
                 return -ENOMEM;
         }
         flow_extract_match (&flow->key, &ofm->match);
         uint16_t v_code = ValidateActions (&flow->key, ofm->actions, actions_len);
         if (v_code != ACT_VALIDATION_OK)
         {
                 SendErrorMsg (OFPET_BAD_ACTION, v_code, ofm, ntohs (ofm->header.length));
                 flow_free (flow);
                 if (ntohl (ofm->buffer_id) != (uint32_t) -1)
                 {
                         pthread_mutex_lock(&(inHost()->getTopNet()->of_buf_mutex));
                         discard_buffer (ntohl (ofm->buffer_id));
                         pthread_mutex_unlock(&(inHost()->getTopNet()->of_buf_mutex));
                 }
                 return -ENOMEM;
         }
         // Fill out flow.
         flow->priority = flow->key.wildcards ? ntohs (ofm->priority) : -1;
         flow->idle_timeout = ntohs (ofm->idle_timeout);
         flow->hard_timeout = ntohs (ofm->hard_timeout);
         flow->used = flow->created = (time_t)(inHost()->now());
         flow->sf_acts->actions_len = actions_len;
         flow->byte_count = 0;
         flow->packet_count = 0;
         memcpy (flow->sf_acts->actions, ofm->actions, actions_len);
         // Act.
         int error = chain_insert (m_chain, flow);
         if (error)
         {
                 if (error == -ENOBUFS)
                 {
                         SendErrorMsg (OFPET_FLOW_MOD_FAILED, OFPFMFC_ALL_TABLES_FULL, ofm, ntohs (ofm->header.length));
                 }
                 flow_free (flow);
                 if (ntohl (ofm->buffer_id) != (uint32_t) -1)
                 {
                         pthread_mutex_lock(&(inHost()->getTopNet()->of_buf_mutex));
                         discard_buffer (ntohl (ofm->buffer_id));
                         pthread_mutex_unlock(&(inHost()->getTopNet()->of_buf_mutex));
                 }
                 return error;
         }
         OF_SWITCH_DUMP(cout << "Switch[" << inHost()->nhi.toString()<< "], Added new flow." << endl);
         if (ntohl (ofm->buffer_id) != std::numeric_limits<uint32_t>::max ())
         {
                 //pthread_mutex_lock(&(inHost()->getTopNet()->of_buf_mutex));
                 ofpbuf *buffer = retrieve_buffer (ofm->buffer_id); // ntohl(ofm->buffer_id)
                 //pthread_mutex_unlock(&(inHost()->getTopNet()->of_buf_mutex));
                 if (buffer)
                 {
                         sw_flow_key key;
                         flow_used (flow, buffer);
                         flow_extract (buffer, ofm->match.in_port, &key.flow); // ntohs(ofm->match.in_port);
                         ExecuteActions (this, ofm->buffer_id, buffer, &key, ofm->actions, actions_len, false);
                         pthread_mutex_lock(&(inHost()->getTopNet()->of_buf_mutex));
                         ofpbuf_delete (buffer);
                         pthread_mutex_unlock(&(inHost()->getTopNet()->of_buf_mutex));
                 }
                 else
                 {
                         return -ESRCH;
                 }
         }
         return 0;
 }
int s3f::s3fnet::OpenFlowSwitchSession::ModFlow (const ofp_flow_mod * ofm) private
Modify a flow.
Parameters
ofm The flow data to modify.
Returns
0 if everything's ok, otherwise an error number.
Definition at line 1227 of file openflow_switch_session.cc.
References discard_buffer(), s3f::s3fnet::ExecuteActions(), s3f::s3fnet::ProtocolSession::inHost(), m_chain, OF_SWITCH_DUMP, retrieve_buffer(), SendErrorMsg(), and s3f::s3fnet::ValidateActions().
Referenced by ReceiveFlow().
 {
         sw_flow_key key;
         flow_extract_match (&key, &ofm->match);
         size_t actions_len = ntohs (ofm->header.length) - sizeof *ofm;
         uint16_t v_code = ValidateActions (&key, ofm->actions, actions_len);
         OF_SWITCH_DUMP( cout << "Switch[" << inHost()->nhi.toString()<< "], Modify a flow." << endl );
         if (v_code != ACT_VALIDATION_OK)
         {
                 SendErrorMsg ((ofp_error_type)OFPET_BAD_ACTION, v_code, ofm, ntohs (ofm->header.length));
                 if (ntohl (ofm->buffer_id) != (uint32_t) -1)
                 {
                         pthread_mutex_lock(&(inHost()->getTopNet()->of_buf_mutex));
                         discard_buffer (ntohl (ofm->buffer_id));
                         pthread_mutex_unlock(&(inHost()->getTopNet()->of_buf_mutex));
                 }
                 return -ENOMEM;
         }
         uint16_t priority = key.wildcards ? ntohs (ofm->priority) : -1;
         int strict = (ofm->command == htons (OFPFC_MODIFY_STRICT)) ? 1 : 0;
         chain_modify (m_chain, &key, priority, strict, ofm->actions, actions_len);
         if (ntohl (ofm->buffer_id) != std::numeric_limits<uint32_t>::max ())
         {
                 //pthread_mutex_lock(&(inHost()->getTopNet()->of_buf_mutex));
                 ofpbuf *buffer = retrieve_buffer (ofm->buffer_id); // ntohl (ofm->buffer_id)
                 //pthread_mutex_unlock(&(inHost()->getTopNet()->of_buf_mutex));
                 if (buffer)
                 {
                         sw_flow_key skb_key;
                         flow_extract (buffer, ofm->match.in_port, &skb_key.flow); // ntohs(ofm->match.in_port);
                         ExecuteActions (this, ofm->buffer_id, buffer, &skb_key, ofm->actions, actions_len, false);
                         pthread_mutex_lock(&(inHost()->getTopNet()->of_buf_mutex));
                         ofpbuf_delete (buffer);
                         pthread_mutex_unlock(&(inHost()->getTopNet()->of_buf_mutex));
                 }
                 else
                 {
                         return -ESRCH;
                 }
         }
         return 0;
 }
int s3f::s3fnet::OpenFlowSwitchSession::OutputAll (uint32_t packet_uid, int in_port, bool flood) private
Send packets out all the ports except the originating one
Parameters
packet_uid Packet UID; used to fetch the packet and its metadata.
in_port The index of the port the Packet was initially received on. This port doesn't forward when flooding.
flood If true, don't send out on the ports with flooding disabled.
Returns
0 if everything's ok, otherwise an error number.
Definition at line 574 of file openflow_switch_session.cc.
References config(), m_ports, OF_SWITCH_DUMP, and OutputPort().
Referenced by OutputPort().
 {
         OF_SWITCH_DUMP( printf("Flooding over ports.\n") );
         int prev_port = -1;
         for (size_t i = 0; i < m_ports.size (); i++)
         {
                 if (m_ports[i].netdev->id == (unsigned)in_port) // Originating port
                 {
                         continue;
                 }
                 if(m_ports[i].netdev->is_of_ctrl_iface == true) //do not send to the port connecting to an active controller
                 {
                         continue;
                 }
                 if (flood && m_ports[i].config & OFPPC_NO_FLOOD) // Port configured to not allow flooding
                 {
                         continue;
                 }
                 if (prev_port != -1)
                 {
                         OutputPort (packet_uid, in_port, prev_port, false);
                 }
                 prev_port = m_ports[i].netdev->id;
         }
         if (prev_port != -1)
         {
                 OutputPort (packet_uid, in_port, prev_port, false);
         }
         return 0;
 }
void s3f::s3fnet::OpenFlowSwitchSession::OutputPacket (uint32_t packet_uid, int out_port) private
Sends a copy of the Packet over the provided output port
Parameters
packet_uid Packet UID; used to fetch the packet and its metadata.
out_port the port that the switch will forward/send a packet out.
Definition at line 610 of file openflow_switch_session.cc.
References s3f::s3fnet::SwitchPacketMetadata::buffer, s3f::s3fnet::ProtocolMessage::clone(), s3f::s3fnet::Port::config, s3f::s3fnet::NetworkInterface::getHighestProtocolSession(), s3f::s3fnet::NetworkInterface::getLowestProtocolSession(), s3f::s3fnet::ProtocolSession::inHost(), m_packetData, m_ports, s3f::s3fnet::Port::netdev, OF_SWITCH_DUMP, s3f::s3fnet::SwitchPacketMetadata::packet, s3f::s3fnet::ProtocolSession::pushdown(), s3f::s3fnet::Port::tx_bytes, and s3f::s3fnet::Port::tx_packets.
Referenced by OutputPort().
 {
         if (out_port >= 0 && out_port < DP_MAX_PORTS)
         {
                 Port& p = m_ports[out_port];
                 if (p.netdev != 0 && !(p.config & OFPPC_PORT_DOWN))
                 {
                         SwitchPacketMetadata data = m_packetData.find (packet_uid)->second;
                         size_t bufsize = data.buffer->size;
                         OF_SWITCH_DUMP (cout << "Switch[" << inHost()->nhi.toString()<< "], Sending packet over port " << out_port << endl);
                         //kevin: use clone first since flooding, suspect FlowTableLookup::m_packetData.erase (packet_uid) will not delete the packet. thus copy will cause memory leak
                         Activation pkt(data.packet->clone());
                         //send directly to the outgoing network interface (simplyPHY.push)
                         p.netdev->getLowestProtocolSession()->pushdown(pkt, p.netdev->getHighestProtocolSession());
                         p.tx_packets++;
                         p.tx_bytes += bufsize;
                         //p.tx_dropped++; //currently ignore drop status
                         return;
                 }
         }
         OF_SWITCH_DUMP (cout << "Switch[" << inHost()->nhi.toString()<< "] Can't forward to bad port " << out_port << endl);
 }
void s3f::s3fnet::OpenFlowSwitchSession::OutputPort (uint32_t packet_uid, int in_port, int out_port, bool ignore_no_fwd) private
Seeks to send out a Packet over the provided output port. This is called generically when we may or may not know the specific port we're outputting on. There are many pre-set types of port options besides a Port that's hooked to our OpenFlowSwitchSession. For example, it could be outputting as a flood, or seeking to output to the controller.
Parameters
packet_uid Packet UID; used to fetch the packet and its metadata.
in_port The index of the port the Packet was initially received on.
out_port The port we want to output on.
ignore_no_fwd If true, Ports that are set to not forward are forced to forward.
Definition at line 636 of file openflow_switch_session.cc.
References s3f::s3fnet::ProtocolSession::inHost(), OF_SWITCH_DUMP, OutputAll(), OutputControl(), OutputPacket(), RunThroughFlowTable(), and RunThroughVPortTable().
Referenced by DoOutput(), OutputAll(), and RunThroughVPortTable().
 {
         if (out_port == OFPP_FLOOD)
         {
                 OutputAll (packet_uid, in_port, true);
         }
         else if (out_port == OFPP_ALL)
         {
                 OutputAll (packet_uid, in_port, false);
         }
         else if (out_port == OFPP_CONTROLLER)
         {
                 OutputControl (packet_uid, in_port, 0, OFPR_ACTION);
         }
         else if (out_port == OFPP_IN_PORT)
         {
                 OutputPacket (packet_uid, in_port);
         }
         else if (out_port == OFPP_TABLE)
         {
                 RunThroughFlowTable (packet_uid, in_port < DP_MAX_PORTS ? in_port : -1, false);
         }
         else if (out_port >= OFPP_VP_START && out_port <= OFPP_VP_END)
         {
                 // port is a virtual port
                 OF_SWITCH_DUMP (cout << "Switch[" << inHost()->nhi.toString()<< "], packet sent to virtual port " << out_port << endl );
                 if (in_port < DP_MAX_PORTS)
                 {
                         RunThroughVPortTable (packet_uid, in_port, out_port);
                 }
                 else
                 {
                         RunThroughVPortTable (packet_uid, -1, out_port);
                 }
         }
         else if (in_port == out_port)
         {
                 OF_SWITCH_DUMP ( cout << "Switch[" << inHost()->nhi.toString()<< "], can't directly forward to input port" << endl );
         }
         else
         {
                 OutputPacket (packet_uid, out_port);
         }
 }
void s3f::s3fnet::OpenFlowSwitchSession::OutputControl (uint32_t packet_uid, int in_port, size_t max_len, int reason) private
Sends a copy of the Packet to the controller. If the packet can be saved in an OpenFlow buffer, then only the first 'max_len' bytes of the packet are sent; otherwise, all of the packet is sent.
Parameters
packet_uid Packet UID; used to fetch the packet and its metadata.
in_port The index of the port the Packet was initially received on.
max_len The maximum number of bytes that the caller wants to be sent; a value of 0 indicates the entire packet should be sent.
reason Why the packet is being sent.
Definition at line 706 of file openflow_switch_session.cc.
References s3f::s3fnet::NetworkInterface::getHighestProtocolSession(), s3f::s3fnet::NetworkInterface::getLowestProtocolSession(), s3f::s3fnet::ProtocolSession::inHost(), is_ctrl_sess, m_packetData, OF_SWITCH_DUMP, ofctrl_port, s3f::s3fnet::ProtocolSession::pushdown(), and SendOpenflowBuffer().
Referenced by DoOutput(), FlowTableLookup(), and OutputPort().
 {
         OF_SWITCH_DUMP (cout << "Switch[" << inHost()->nhi.toString()<< "], Sending packet to controller" << endl );
         ofpbuf* buffer = m_packetData.find (packet_uid)->second.buffer;
         size_t total_len = buffer->size;
         if (packet_uid != std::numeric_limits<uint32_t>::max () && max_len != 0 && buffer->size > max_len)
         {
                 buffer->size = max_len;
         }
         ofp_packet_in *opi = (ofp_packet_in*)ofpbuf_push_uninit (buffer, offsetof (ofp_packet_in, data));
         opi->header.version = OFP_VERSION;
         opi->header.type    = OFPT_PACKET_IN;
         opi->header.length  = htons (buffer->size);
         opi->header.xid     = htonl (0);
         opi->buffer_id      = htonl (packet_uid);
         opi->total_len      = htons (total_len);
         opi->in_port        = htons (in_port);
         opi->reason         = reason;
         opi->pad            = 0;
         if(is_ctrl_sess == false) //non-protocol-session controller
         {
                 SendOpenflowBuffer (buffer);
         }
         else //non-protocol-session controller
         {
                 pthread_mutex_lock(&(inHost()->getTopNet()->of_buf_mutex));
                 update_openflow_length (buffer);
                 pthread_mutex_unlock(&(inHost()->getTopNet()->of_buf_mutex));
                 OpenFlowMessage* msg = new OpenFlowMessage(buffer, packet_uid, this);
                 Activation pkt(msg);
                 //send directly to the outgoing network interface connected with controller (simplyPHY.push)
                 ofctrl_port->getLowestProtocolSession()->pushdown(pkt, ofctrl_port->getHighestProtocolSession());
         }
 }
void s3f::s3fnet::OpenFlowSwitchSession::SendErrorMsg (uint16_t type, uint16_t code, const void * data, size_t len) private
If an error message happened during the controller's request, send it to the controller.
Parameters
type The type of error.
code The error code.
data The faulty data that lead to the error.
len The length of the faulty data.
Definition at line 840 of file openflow_switch_session.cc.
References MakeOpenflowReply(), and SendOpenflowBuffer().
Referenced by AddFlow(), AddVPort(), ForwardControlInput(), ModFlow(), ReceivePacketOut(), and ReceiveVPortMod().
 {
         ofpbuf *buffer;
         ofp_error_msg *oem = (ofp_error_msg*)MakeOpenflowReply (sizeof(*oem) + len, OFPT_ERROR, &buffer);
         oem->type = htons (type);
         oem->code = htons (code);
         memcpy (oem->data, data, len);
         SendOpenflowBuffer (buffer);
 }
void s3f::s3fnet::OpenFlowSwitchSession::SendFeaturesReply () private
Send a reply about this OpenFlow switch's features to the controller.
List of capabilities and actions to support are found in the specification <www.openflowswitch.org/documents/openflow-spec-v0.8.9.pdf>.
Supported capabilities and actions are defined in the openflow interface. To recap, flow status, flow table status, port status, virtual port table status can all be requested. It can also transmit over multiple physical interfaces.
It supports every action: outputting over a port, and all of the flow table manipulation actions: setting the 802.1q VLAN ID, the 802.1q priority, stripping the 802.1 header, setting the Ethernet source address and destination, setting the IP source address and destination, setting the TCP/UDP source address and destination, and setting the MPLS label and EXP bits.
Attention
Capabilities STP (Spanning Tree Protocol) and IP packet reassembly are not currently supported.
Definition at line 764 of file openflow_switch_session.cc.
References FillPortDesc(), m_chain, m_id, m_ports, MakeOpenflowReply(), N_PKT_BUFFERS, OFP_SUPPORTED_ACTIONS, OFP_SUPPORTED_CAPABILITIES, and SendOpenflowBuffer().
Referenced by ReceiveFeaturesRequest().
 {
         ofpbuf *buffer;
         ofp_switch_features *ofr = (ofp_switch_features*)MakeOpenflowReply (sizeof *ofr, OFPT_FEATURES_REPLY, &buffer);
         ofr->datapath_id  = htonll (m_id);
         ofr->n_tables     = m_chain->n_tables;
         ofr->n_buffers    = htonl (N_PKT_BUFFERS);
         ofr->capabilities = htonl (OFP_SUPPORTED_CAPABILITIES);
         ofr->actions      = htonl (OFP_SUPPORTED_ACTIONS);
         for (size_t i = 0; i < m_ports.size (); i++)
         {
                 ofp_phy_port* opp = (ofp_phy_port*)ofpbuf_put_zeros (buffer, sizeof *opp);
                 FillPortDesc (m_ports[i], opp);
         }
         SendOpenflowBuffer (buffer);
 }
void s3f::s3fnet::OpenFlowSwitchSession::SendFlowExpired (sw_flow * flow, enum ofp_flow_expired_reason reason) private
Send a reply to the controller that a specific flow has expired.
Parameters
flow The flow that expired.
reason The reason for sending this expiration notification.
Definition at line 823 of file openflow_switch_session.cc.
References s3f::s3fnet::ProtocolSession::inHost(), MakeOpenflowReply(), and SendOpenflowBuffer().
Referenced by pop().
 {
         ofpbuf *buffer;
         ofp_flow_expired *ofe = (ofp_flow_expired*)MakeOpenflowReply (sizeof *ofe, OFPT_FLOW_EXPIRED, &buffer);
         flow_fill_match (&ofe->match, &flow->key);
         ofe->priority = htons (flow->priority);
         ofe->reason = reason;
         memset (ofe->pad, 0, sizeof ofe->pad);
         ofe->duration     = htonl (inHost()->now() - flow->created);
         memset (ofe->pad2, 0, sizeof ofe->pad2);
         ofe->packet_count = htonll (flow->packet_count);
         ofe->byte_count   = htonll (flow->byte_count);
         SendOpenflowBuffer (buffer);
 }
void s3f::s3fnet::OpenFlowSwitchSession::SendPortStatus (Port p, uint8_t status) private
Send a reply about a Port's status to the controller.
Parameters
p The port to get status from.
status The reason for sending this reply.
Definition at line 808 of file openflow_switch_session.cc.
References FillPortDesc(), s3f::s3fnet::ProtocolSession::inHost(), MakeOpenflowReply(), and SendOpenflowBuffer().
Referenced by AddSwitchPort(), and pop().
 {
         ofpbuf *buffer;
         ofp_port_status *ops = (ofp_port_status*)MakeOpenflowReply (sizeof *ops, OFPT_PORT_STATUS, &buffer);
         ops->reason = status;
         memset (ops->pad, 0, sizeof ops->pad);
         FillPortDesc (p, &ops->desc);
         SendOpenflowBuffer (buffer);
         pthread_mutex_lock(&(inHost()->getTopNet()->of_buf_mutex));
         ofpbuf_delete (buffer);
         pthread_mutex_unlock(&(inHost()->getTopNet()->of_buf_mutex));
 }
void s3f::s3fnet::OpenFlowSwitchSession::SendVPortTableFeatures () private
Send a reply about this OpenFlow switch's virtual port table features to the controller.
Definition at line 783 of file openflow_switch_session.cc.
References m_vportTable, MakeOpenflowReply(), OFP_SUPPORTED_VPORT_TABLE_ACTIONS, and SendOpenflowBuffer().
Referenced by ReceiveVPortTableFeaturesRequest().
 {
         ofpbuf *buffer;
         ofp_vport_table_features *ovtfr = (ofp_vport_table_features*)MakeOpenflowReply (sizeof *ovtfr, OFPT_VPORT_TABLE_FEATURES_REPLY, &buffer);
         ovtfr->actions = htonl (OFP_SUPPORTED_VPORT_TABLE_ACTIONS);
         ovtfr->max_vports = htonl (m_vportTable.max_vports);
         ovtfr->max_chain_depth = htons (-1); // support a chain depth of 2^16
         ovtfr->mixed_chaining = true;
         SendOpenflowBuffer (buffer);
 }
int s3f::s3fnet::OpenFlowSwitchSession::SendOpenflowBuffer (ofpbuf * buffer) private
Send a message to the controller. This method is the key to communicating with the controller, it does the actual sending. The other Send methods call this one when they are ready to send a message.
Parameters
buffer Buffer of the message to send out.
Returns
0 if successful, otherwise an error number.
Definition at line 686 of file openflow_switch_session.cc.
References ctrl_sess, s3f::s3fnet::ProtocolSession::inHost(), is_ctrl_sess, np_controller, s3f::s3fnet::Controller::ReceiveFromSwitch(), and s3f::s3fnet::OpenFlowControllerSession::ReceiveFromSwitch().
Referenced by OutputControl(), ReceiveEchoRequest(), ReceiveGetConfigRequest(), SendErrorMsg(), SendFeaturesReply(), SendFlowExpired(), SendPortStatus(), SendVPortTableFeatures(), and StatsDump().
 {
         pthread_mutex_lock(&(inHost()->getTopNet()->of_buf_mutex));
         update_openflow_length (buffer);
         pthread_mutex_unlock(&(inHost()->getTopNet()->of_buf_mutex));
         if(is_ctrl_sess == false) //non-protocol-session controller
         {
                 if(np_controller != 0) np_controller->ReceiveFromSwitch (this, buffer);
         }
         else // protocol session controller
         {
                 if(ctrl_sess != 0)
                 {
                         ctrl_sess->ReceiveFromSwitch(this, buffer);
                 }
         }
         return 0;
 }
void s3f::s3fnet::OpenFlowSwitchSession::RunThroughFlowTable (uint32_t packet_uid, int port, bool send_to_controller = true) private
Run the packet through the flow table. Looks up in the flow table for a match. If it doesn't match, it forwards the packet to the registered controller, if the flag is set.
Parameters
packet_uid Packet UID; used to fetch the packet and its metadata.
port The port this packet was received over.
send_to_controller If set, sends to the controller if the packet isn't matched.
Definition at line 893 of file openflow_switch_session.cc.
References s3f::s3fnet::SwitchPacketMetadata::buffer, config(), FlowTableLookup(), s3f::s3fnet::ProtocolSession::inHost(), m_flags, m_packetData, m_ports, and OF_SWITCH_DUMP.
Referenced by OutputPort(), and pop().
 {
         SwitchPacketMetadata data = m_packetData.find (packet_uid)->second;
         ofpbuf* buffer = data.buffer;
         sw_flow_key key;
         key.wildcards = 0; // Lookup cannot take wildcards.
         // Extract the matching key's flow data from the packet's headers; if the policy is to drop fragments and the message is a fragment, drop it.
         if (flow_extract (buffer, port != -1 ? port : OFPP_NONE, &key.flow) && (m_flags & OFPC_FRAG_MASK) == OFPC_FRAG_DROP)
         {
                 pthread_mutex_lock(&(inHost()->getTopNet()->of_buf_mutex));
                 ofpbuf_delete (buffer);
                 pthread_mutex_unlock(&(inHost()->getTopNet()->of_buf_mutex));
                 return;
         }
         // drop MPLS packets with TTL 1
         if (buffer->l2_5)
         {
                 mpls_header mpls_h;
                 mpls_h.value = ntohl (*((uint32_t*)buffer->l2_5));
                 if (mpls_h.ttl == 1)
                 {
                         // increment mpls drop counter
                         if (port != -1)
{
                                 m_ports[port].mpls_ttl0_dropped++;
                         }
                         return;
                 }
         }
         // If we received the packet on a port, and opted not to receive any messages from it...
         if (port != -1)
         {
                 uint32_t config = m_ports[port].config;
                 if ( ( config & (OFPPC_NO_RECV | OFPPC_NO_RECV_STP))
                                 && (config & (!eth_addr_equals (key.flow.dl_dst, stp_eth_addr) ? OFPPC_NO_RECV : OFPPC_NO_RECV_STP)) )
                 {
                         return;
                 }
         }
         OF_SWITCH_DUMP ( cout << "Switch[" << inHost()->nhi.toString()<< "], Matching against the flow table." << endl );
         //todo: directly call FlowTableLookup first, once we have the timing model for switch <-> controller, then we may change here
         FlowTableLookup (key, buffer, packet_uid, port, send_to_controller);
 }
int s3f::s3fnet::OpenFlowSwitchSession::RunThroughVPortTable (uint32_t packet_uid, int port, uint32_t vport) private
Run the packet through the vport table. As with AddVPort, this doesn't have an understood use yet.
Parameters
packet_uid Packet UID; used to fetch the packet and its metadata.
port The port this packet was received over.
vport The virtual port this packet identifies itself by.
Returns
0 if everything's ok, otherwise an error number.
Definition at line 942 of file openflow_switch_session.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::ExecuteVPortActions(), m_flags, m_packetData, m_vportTable, and OutputPort().
Referenced by OutputPort().
 {
         ofpbuf* buffer = m_packetData.find (packet_uid)->second.buffer;
         // extract the flow again since we need it
         // and the layer pointers may changed
         sw_flow_key key;
         key.wildcards = 0;
         if (flow_extract (buffer, port != -1 ? port : OFPP_NONE, &key.flow)
                         && (m_flags & OFPC_FRAG_MASK) == OFPC_FRAG_DROP)
         {
                 return 0;
         }
         // run through the chain of port table entries
         vport_table_entry *vpe = vport_table_lookup (&m_vportTable, vport);
         m_vportTable.lookup_count++;
         if (vpe)
         {
                 m_vportTable.port_match_count++;
         }
         while (vpe != 0)
         {
                 ExecuteVPortActions (this, packet_uid, m_packetData.find (packet_uid)->second.buffer, &key, vpe->port_acts->actions, vpe->port_acts->actions_len);
                 vport_used (vpe, buffer); // update counters for virtual port
                 if (vpe->parent_port_ptr == 0)
                 {
                         // if a port table's parent_port_ptr is 0 then
                         // the parent_port should be a physical port
                         if (vpe->parent_port <= OFPP_VP_START) // done traversing port chain, send packet to output port
{
                                 OutputPort (packet_uid, port != -1 ? port : OFPP_NONE, vpe->parent_port, false);
                         }
                         else
{
                                 error_quit("virtual port points to parent port\n");
                         }
                 }
                 else // increment the number of port entries accessed by chaining
                 {
                         m_vportTable.chain_match_count++;
                 }
                 // move to the parent port entry
                 vpe = vpe->parent_port_ptr;
         }
         return 0;
 }
void s3f::s3fnet::OpenFlowSwitchSession::FlowTableLookup (sw_flow_key key, ofpbuf * buffer, uint32_t packet_uid, int port, bool send_to_controller) private
Called by RunThroughFlowTable on a scheduled delay to account for the flow table lookup overhead.
Parameters
key Matching key to look up in the flow table.
buffer Buffer of the packet received.
packet_uid Packet UID; used to fetch the packet and its metadata.
port The port the packet was received over.
send_to_controller
Definition at line 850 of file openflow_switch_session.cc.
References discard_buffer(), s3f::s3fnet::ExecuteActions(), s3f::s3fnet::ProtocolSession::inHost(), is_ctrl_sess, m_chain, m_missSendLen, m_packetData, OF_SWITCH_DUMP, and OutputControl().
Referenced by RunThroughFlowTable().
 {
         sw_flow *flow = chain_lookup (m_chain, &key);
         if (flow != 0)
         {
                 /* kevin: if the rule is flooding, ask controller again, need to double verify */
                 ofp_action_output* oa = (ofp_action_output*)(flow->sf_acts->actions);
                 if(oa->port == OFPP_FLOOD)
                 {
                         OF_SWITCH_DUMP (cout << "Switch[" << inHost()->nhi.toString()<< "], Flow not matched." << endl);
                         if (send_to_controller)
{
                                 OutputControl (packet_uid, port, m_missSendLen, OFPR_NO_MATCH);
                         }
                 }
                 else
                 {
                         OF_SWITCH_DUMP (cout << "Switch[" << inHost()->nhi.toString()<< "], Flow matched" << endl);
                         flow_used (flow, buffer);
                         ExecuteActions (this, packet_uid, buffer, &key, flow->sf_acts->actions, flow->sf_acts->actions_len, false);
                 }
         }
         else
         {
                 OF_SWITCH_DUMP (cout << "Switch[" << inHost()->nhi.toString()<< "], Flow not matched." << endl);
                 if (send_to_controller)
                 {
                         OutputControl (packet_uid, port, m_missSendLen, OFPR_NO_MATCH);
                 }
         }
         if(is_ctrl_sess == false)
         {
                 // Clean up; at this point we're done with the packet.
                 pthread_mutex_lock(&(inHost()->getTopNet()->of_buf_mutex));
                 m_packetData.erase (packet_uid);
                 discard_buffer (packet_uid); //kevin: todo: this line cause double free error for multi-timline, need to investigate
                 ofpbuf_delete (buffer);
                 pthread_mutex_unlock(&(inHost()->getTopNet()->of_buf_mutex));
         }
 }
int s3f::s3fnet::OpenFlowSwitchSession::UpdatePortStatus (Port & p) private
Update the port status field of the switch port. A non-zero return value indicates some field has changed.
Parameters
p A reference to a Port; used to change its config and flag fields.
Returns
true if the status of the Port is changed, false if unchanged (was already the right status).
Definition at line 794 of file openflow_switch_session.cc.
References s3f::s3fnet::Port::config, and s3f::s3fnet::Port::state.
Referenced by pop().
 {
         uint32_t orig_config = p.config;
         uint32_t orig_state = p.state;
         // Port is always enabled because the Net Device is always enabled.
         p.config &= ~OFPPC_PORT_DOWN;
         //assume link is always up first
         p.state &= ~OFPPS_LINK_DOWN;
         return ((orig_config != p.config) || (orig_state != p.state));
 }
void s3f::s3fnet::OpenFlowSwitchSession::FillPortDesc (Port p, ofp_phy_port * desc) private
Fill out a description of the switch port.
Parameters
p The port to get the description from.
desc A pointer to the description message; used to fill the description message with the data from the port.
Definition at line 745 of file openflow_switch_session.cc.
References s3f::s3fnet::Port::config, s3f::s3fnet::Mac48Address::CopyTo(), s3f::s3fnet::NetworkInterface::getMac48Addr(), GetSwitchPortIndex(), s3f::s3fnet::Port::netdev, and s3f::s3fnet::Port::state.
Referenced by SendFeaturesReply(), and SendPortStatus().
 {
         desc->port_no = htons (GetSwitchPortIndex (p));
         std::ostringstream nm;
         nm << "eth" << GetSwitchPortIndex (p);
         strncpy ((char *)desc->name, nm.str ().c_str (), sizeof desc->name);
         p.netdev->getMac48Addr()->CopyTo (desc->hw_addr);
         desc->config = htonl (p.config);
         desc->state = htonl (p.state);
         // TODO: This should probably be fixed eventually to specify different available features.
         desc->curr = 0; // htonl(netdev_get_features(p->netdev, NETDEV_FEAT_CURRENT));
         desc->supported = 0; // htonl(netdev_get_features(p->netdev, NETDEV_FEAT_SUPPORTED));
         desc->advertised = 0; // htonl(netdev_get_features(p->netdev, NETDEV_FEAT_ADVERTISED));
         desc->peer = 0; // htonl(netdev_get_features(p->netdev, NETDEV_FEAT_PEER));
 }
void * s3f::s3fnet::OpenFlowSwitchSession::MakeOpenflowReply (size_t openflow_len, uint8_t type, ofpbuf ** bufferp) private
Generates an OpenFlow reply message based on the type.
Parameters
openflow_len Length of the reply to make.
type Type of reply message to make.
bufferp Message buffer; used to make the reply.
Returns
The OpenFlow reply message.
Definition at line 681 of file openflow_switch_session.cc.
Referenced by ReceiveGetConfigRequest(), SendErrorMsg(), SendFeaturesReply(), SendFlowExpired(), SendPortStatus(), SendVPortTableFeatures(), and StatsDump().
 {
         return make_openflow_xid (openflow_len, type, 0, bufferp);
 }
int s3f::s3fnet::OpenFlowSwitchSession::ReceiveFeaturesRequest (const void * msg) private
Definition at line 991 of file openflow_switch_session.cc.
References SendFeaturesReply().
Referenced by ForwardControlInput().
 {
         SendFeaturesReply ();
         return 0;
 }
int s3f::s3fnet::OpenFlowSwitchSession::ReceiveGetConfigRequest (const void * msg) private
Definition at line 1003 of file openflow_switch_session.cc.
References m_flags, m_missSendLen, MakeOpenflowReply(), and SendOpenflowBuffer().
Referenced by ForwardControlInput().
 {
         ofpbuf *buffer;
         ofp_switch_config *osc = (ofp_switch_config*)MakeOpenflowReply (sizeof *osc, OFPT_GET_CONFIG_REPLY, &buffer);
         osc->flags = htons (m_flags);
         osc->miss_send_len = htons (m_missSendLen);
         return SendOpenflowBuffer (buffer);
 }
int s3f::s3fnet::OpenFlowSwitchSession::ReceiveSetConfig (const void * msg) private
Definition at line 1013 of file openflow_switch_session.cc.
References m_flags, and m_missSendLen.
Referenced by ForwardControlInput().
 {
         const ofp_switch_config *osc = (ofp_switch_config*)msg;
         int n_flags = ntohs (osc->flags) & (OFPC_SEND_FLOW_EXP | OFPC_FRAG_MASK);
         if ((n_flags & OFPC_FRAG_MASK) != OFPC_FRAG_NORMAL && (n_flags & OFPC_FRAG_MASK) != OFPC_FRAG_DROP)
         {
                 n_flags = (n_flags & ~OFPC_FRAG_MASK) | OFPC_FRAG_DROP;
         }
         m_flags = n_flags;
         m_missSendLen = ntohs (osc->miss_send_len);
         return 0;
 }
int s3f::s3fnet::OpenFlowSwitchSession::ReceivePacketOut (const void * msg) private
Definition at line 1028 of file openflow_switch_session.cc.
References EINVAL, s3f::s3fnet::ExecuteActions(), s3f::s3fnet::ProtocolSession::inHost(), OF_SWITCH_DUMP, retrieve_buffer(), SendErrorMsg(), and s3f::s3fnet::ValidateActions().
Referenced by ForwardControlInput().
 {
         const ofp_packet_out *opo = (ofp_packet_out*)msg;
         ofpbuf *buffer;
         size_t actions_len = ntohs (opo->actions_len);
         if (actions_len > (ntohs (opo->header.length) - sizeof *opo))
         {
                 OF_SWITCH_DUMP (cout << "Switch[" << inHost()->nhi.toString()<< "], message too short for number of actions" << endl);
                 return -EINVAL;
         }
         if (ntohl (opo->buffer_id) == (uint32_t) -1)
         {
                 // FIXME: can we avoid copying data here?
                 int data_len = ntohs (opo->header.length) - sizeof *opo - actions_len;
                 buffer = ofpbuf_new (data_len);
                 ofpbuf_put (buffer, (uint8_t *)opo->actions + actions_len, data_len);
         }
         else
         {
                 //pthread_mutex_lock(&(inHost()->getTopNet()->of_buf_mutex));
                 buffer = retrieve_buffer (ntohl (opo->buffer_id));
                 //pthread_mutex_unlock(&(inHost()->getTopNet()->of_buf_mutex));
                 if (buffer == 0)
                 {
                         return -ESRCH;
                 }
         }
         sw_flow_key key;
         flow_extract (buffer, opo->in_port, &key.flow); // ntohs(opo->in_port)
         uint16_t v_code = ValidateActions (&key, opo->actions, actions_len);
         if (v_code != ACT_VALIDATION_OK)
         {
                 SendErrorMsg (OFPET_BAD_ACTION, v_code, msg, ntohs (opo->header.length));
                 pthread_mutex_lock(&(inHost()->getTopNet()->of_buf_mutex));
                 ofpbuf_delete (buffer);
                 pthread_mutex_unlock(&(inHost()->getTopNet()->of_buf_mutex));
                 return -EINVAL;
         }
         ExecuteActions (this, opo->buffer_id, buffer, &key, opo->actions, actions_len, true);
         return 0;
 }
int s3f::s3fnet::OpenFlowSwitchSession::ReceiveFlow (const void * msg) private
Definition at line 1278 of file openflow_switch_session.cc.
References AddFlow(), m_chain, and ModFlow().
Referenced by ForwardControlInput().
 {
         const ofp_flow_mod *ofm = (ofp_flow_mod*)msg;
         uint16_t command = ntohs (ofm->command);
         if (command == OFPFC_ADD)
         {
                 return AddFlow (ofm);
         }
         else if ((command == OFPFC_MODIFY) || (command == OFPFC_MODIFY_STRICT))
         {
                 return ModFlow (ofm);
         }
         else if (command == OFPFC_DELETE)
         {
                 sw_flow_key key;
                 flow_extract_match (&key, &ofm->match);
                 return chain_delete (m_chain, &key, ofm->out_port, 0, 0) ? 0 : -ESRCH;
         }
         else if (command == OFPFC_DELETE_STRICT)
         {
                 sw_flow_key key;
                 uint16_t priority;
                 flow_extract_match (&key, &ofm->match);
                 priority = key.wildcards ? ntohs (ofm->priority) : -1;
                 return chain_delete (m_chain, &key, ofm->out_port, priority, 1) ? 0 : -ESRCH;
         }
         else
         {
                 return -ENODEV;
         }
 }
int s3f::s3fnet::OpenFlowSwitchSession::ReceivePortMod (const void * msg) private
Definition at line 1076 of file openflow_switch_session.cc.
References s3f::s3fnet::Port::config, s3f::s3fnet::Mac48Address::CopyFrom(), s3f::s3fnet::NetworkInterface::getMac48Addr(), s3f::s3fnet::ProtocolSession::inHost(), m_ports, s3f::s3fnet::Port::netdev, and OF_SWITCH_DUMP.
Referenced by ForwardControlInput().
 {
         ofp_port_mod* opm = (ofp_port_mod*)msg;
         int port = opm->port_no; // ntohs(opm->port_no);
         if (port < DP_MAX_PORTS)
         {
                 Port& p = m_ports[port];
                 // Make sure the port id hasn't changed since this was sent
                 Mac48Address hw_addr = Mac48Address ();
                 hw_addr.CopyFrom (opm->hw_addr);
                 if (*(p.netdev->getMac48Addr()) != hw_addr)
                 {
                         OF_SWITCH_DUMP(cout << "Switch[" << inHost()->nhi.toString()<< "], OpenFlowSwitchSession::ReceivePortMod(), hw_addr != p.netdev->getMac48Addr()" << endl);
                         return 0;
                 }
                 if (opm->mask)
                 {
                         uint32_t config_mask = ntohl (opm->mask);
                         p.config &= ~config_mask;
                         p.config |= ntohl (opm->config) & config_mask;
                 }
                 if (opm->mask & htonl (OFPPC_PORT_DOWN))
                 {
                         if ((opm->config & htonl (OFPPC_PORT_DOWN)) && (p.config & OFPPC_PORT_DOWN) == 0)
{
                                 p.config |= OFPPC_PORT_DOWN;
                                 // TODO: Possibly disable the Port's Net Device via the appropriate interface.
                         }
                         else if ((opm->config & htonl (OFPPC_PORT_DOWN)) == 0 && (p.config & OFPPC_PORT_DOWN))
{
                                 p.config &= ~OFPPC_PORT_DOWN;
                                 // TODO: Possibly enable the Port's Net Device via the appropriate interface.
                         }
                 }
         }
         return 0;
 }
int s3f::s3fnet::OpenFlowSwitchSession::ReceiveStatsRequest (const void * oh) private
Definition at line 1360 of file openflow_switch_session.cc.
References ctrl_sess, s3f::s3fnet::Stats::DoInit(), s3f::s3fnet::StatsDumpCallback::done, EINVAL, s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolSession::inHost(), is_ctrl_sess, np_controller, OF_SWITCH_DUMP, s3f::s3fnet::StatsDumpCallback::rq, s3f::s3fnet::StatsDumpCallback::s, s3f::s3fnet::Controller::StartDump(), s3f::s3fnet::OpenFlowControllerSession::StartDump(), s3f::s3fnet::StatsDumpCallback::state, and s3f::s3fnet::StatsDumpCallback::swtch.
Referenced by ForwardControlInput().
 {
         const ofp_stats_request *rq = (ofp_stats_request*)oh;
         size_t rq_len = ntohs (rq->header.length);
         int type = ntohs (rq->type);
         int body_len = rq_len - offsetof (ofp_stats_request, body);
         Stats* st = new Stats ((ofp_stats_types)type, (unsigned)body_len);
         if (st == 0)
         {
                 return -EINVAL;
         }
         StatsDumpCallback cb;
         cb.done = false;
         cb.rq = (ofp_stats_request*)xmemdup (rq, rq_len);
         cb.s = st;
         cb.state = 0;
         cb.swtch = this;
         if (cb.s)
         {
                 int err = cb.s->DoInit (rq->body, body_len, &cb.state);
                 if (err)
                 {
                         OF_SWITCH_DUMP ( cout << "Switch[" << inHost()->nhi.toString()<< "], failed initialization of stats request type " << type << ": " << strerror (-err) << endl );
                         free (cb.rq);
                         return err;
                 }
         }
         if(is_ctrl_sess == false)
         {
                 if(np_controller != 0) np_controller->StartDump (&cb);
                 else error_quit ("Switch needs to be registered to a passive controller in order to start the stats reply.");
         }
         else
         {
                 if(ctrl_sess != 0) ctrl_sess->StartDump(&cb);
                 else error_quit ("Switch needs to be registered to an active controller in order to start the stats reply.");
         }
         return 0;
 }
int s3f::s3fnet::OpenFlowSwitchSession::ReceiveEchoRequest (const void * oh) private
Definition at line 1405 of file openflow_switch_session.cc.
References SendOpenflowBuffer().
Referenced by ForwardControlInput().
 {
         return SendOpenflowBuffer (make_echo_reply ((ofp_header*)oh));
 }
int s3f::s3fnet::OpenFlowSwitchSession::ReceiveEchoReply (const void * oh) private
Definition at line 1410 of file openflow_switch_session.cc.
Referenced by ForwardControlInput().
 {
         return 0;
 }
int s3f::s3fnet::OpenFlowSwitchSession::ReceiveVPortMod (const void * msg) private
Definition at line 1120 of file openflow_switch_session.cc.
References AddVPort(), m_vportTable, and SendErrorMsg().
Referenced by ForwardControlInput().
 {
         const ofp_vport_mod *ovpm = (ofp_vport_mod*)msg;
         uint16_t command = ntohs (ovpm->command);
         if (command == OFPVP_ADD)
         {
                 return AddVPort (ovpm);
         }
         else if (command == OFPVP_DELETE)
         {
                 if (remove_vport_table_entry (&m_vportTable, ntohl (ovpm->vport)))
                 {
                         SendErrorMsg (OFPET_BAD_ACTION, OFPET_VPORT_MOD_FAILED, ovpm, ntohs (ovpm->header.length));
                 }
         }
         return 0;
 }
int s3f::s3fnet::OpenFlowSwitchSession::ReceiveVPortTableFeaturesRequest (const void * msg) private
Definition at line 997 of file openflow_switch_session.cc.
References SendVPortTableFeatures().
Referenced by ForwardControlInput().
 {
         SendVPortTableFeatures ();
         return 0;
 }
void s3f::s3fnet::ProtocolSession::wrapup () virtual inherited
The method is used to wrap up the protocol session.
It is called when the simulation finishes. It is designed to give user a chance to report simulation statistics. The default behavior is doing nothing. Subclass may override this method for protocol specific dealings. Note that there is no specific order in which wrapup is called for protocol sessions in a protocol graph.
Definition at line 59 of file protocol_session.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolSession::initialized(), s3f::s3fnet::ProtocolSession::name, s3f::s3fnet::ProtocolSession::PSESS_WRAPPED_UP, s3f::s3fnet::ProtocolSession::stage, and s3f::s3fnet::ProtocolSession::wrapped_up().
 {
   // Make sure this init function at the base class should be called
   // by the derived function!
   if(!initialized())
     error_quit("ERROR: ProtocolSession \"%s\" wrapup() called before init(), "
                "forgot to call base class's init() in your derived class?\n", name);
   else if(wrapped_up())
     error_quit("ERROR: duplicate calls to ProtocolSession::wrapup(): "
                "session name is \"%s\".\n", name);
   else stage = PSESS_WRAPPED_UP;
 }
int s3f::s3fnet::ProtocolSession::pushdown (Activation msg, ProtocolSession * hi_sess, void * extinfo = 0, size_t extinfo_size = 0) inherited
The original push method is divided into pushdown() and push().
The pushdown method is the generic part of the code, which is reserved for modeling the handling of messages transferred between protocol layers.
See Also
ProtocolSession::push method for details.
Definition at line 72 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::push().
Referenced by s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), s3f::s3fnet::IPSession::control(), s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), OutputControl(), OutputPacket(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::UDPMaster::push(), s3f::s3fnet::TCPMaster::push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::send(), and s3f::s3fnet::TCPSession::send_data().
 {
   return push(msg, hi_sess, extinfo, extinfo_size);
 }
int s3f::s3fnet::ProtocolSession::popup (Activation msg, ProtocolSession * lo_sess, void * extinfo = 0, size_t extinfo_size = 0) inherited
The original pop method is divided into popup() and pop().
The popup method is the generic part of the code, which is reserved for modeling the handling of messages transferred between protocol layers.
See Also
ProtocolSession::pop method for details.
Definition at line 77 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::pop().
Referenced by s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::IPSession::push(), and s3f::s3fnet::SimplePhy::receivePacket().
 {
   return pop(msg, lo_sess, extinfo, extinfo_size);
 }
ProtocolGraph* s3f::s3fnet::ProtocolSession::inGraph () inline inherited
The method returns the protocol graph in which this protocol session resides.
Definition at line 178 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::ingraph.
Referenced by s3f::s3fnet::SimplePhy::config(), s3f::s3fnet::SimplePhy::control(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::SimpleMac::init(), s3f::s3fnet::SimplePhy::init(), s3f::s3fnet::RedQueue::init(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::SimplePhy::push(), s3f::s3fnet::SimplePhy::receivePacket(), s3f::s3fnet::SimplePhy::sendPacket(), s3f::s3fnet::SimpleMac::SimpleMac(), s3f::s3fnet::SimplePhy::SimplePhy(), s3f::s3fnet::SimpleMac::~SimpleMac(), and s3f::s3fnet::SimplePhy::~SimplePhy().
 { return ingraph; }
Host * s3f::s3fnet::ProtocolSession::inHost () virtual inherited
Return a pointer to the host owning this protocol session.
Reimplemented in s3f::s3fnet::NicProtocolSession.
Definition at line 118 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::ingraph.
Referenced by s3f::s3fnet::UDPSession::abort(), s3f::s3fnet::SocketMaster::abort(), s3f::s3fnet::NBSocketMaster::abort(), s3f::s3fnet::SocketMaster::accept(), s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::accept1a(), s3f::s3fnet::SocketMaster::accept1b(), s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SocketMaster::accept2b(), AddFlow(), s3f::s3fnet::TCPSession::backoff_timeout(), s3f::s3fnet::SocketMaster::bind(), s3f::s3fnet::NBSocketMaster::bind(), s3f::s3fnet::SocketMaster::block_till(), s3f::s3fnet::NBSocketMaster::block_till(), s3f::s3fnet::BTCPClientSession::BTCPClientSession(), BufferFromPacket(), s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::UDPServerSession::client_connected(), s3f::s3fnet::SocketMaster::close(), s3f::s3fnet::NBSocketMaster::close(), s3f::s3fnet::SocketMaster::close1(), s3f::s3fnet::NBSocketMaster::close1(), s3f::s3fnet::UDPMaster::config(), s3f::s3fnet::DummySession::config(), s3f::s3fnet::TCPClientSession::config(), s3f::s3fnet::UDPServerSession::config(), s3f::s3fnet::UDPClientSession::config(), s3f::s3fnet::TCPServerSession::config(), s3f::s3fnet::TCPMaster::config(), s3f::s3fnet::NBTCPClientSession::config(), s3f::s3fnet::BTCPClientSession::config(), s3f::s3fnet::IPSession::config(), s3f::s3fnet::NBTCPServerSession::config(), s3f::s3fnet::UDPSession::connect(), s3f::s3fnet::SocketMaster::connect(), s3f::s3fnet::NBSocketMaster::connect(), s3f::s3fnet::SocketMaster::connect1(), s3f::s3fnet::NBSocketMaster::connect1(), s3f::s3fnet::SocketMaster::connected(), s3f::s3fnet::NBSocketMaster::connected(), s3f::s3fnet::UDPMaster::control(), s3f::s3fnet::SocketMaster::control(), s3f::s3fnet::NBSocketMaster::control(), s3f::s3fnet::IPSession::control(), s3f::s3fnet::TCPMaster::createSession(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::UDPServerSession::data_sent(), s3f::s3fnet::TCPServerSession::data_sent(), s3f::s3fnet::UDPSession::disconnect(), s3f::s3fnet::TCPMaster::enableFastTimeout(), s3f::s3fnet::SocketMaster::eof(), s3f::s3fnet::NBSocketMaster::eof(), s3f::s3fnet::UDPClientSessionContinuation::failure(), s3f::s3fnet::UDPServerSessionContinuation::failure(), s3f::s3fnet::TCPServerSessionContinuation::failure(), s3f::s3fnet::TCPClientSessionContinuation::failure(), s3f::s3fnet::BTCPClientSessionContinuation::failure(), s3f::s3fnet::TCPMaster::fast_timer_callback_body(), s3f::s3fnet::Stats::FlowStatsDump(), FlowTableLookup(), s3f::s3fnet::IPSession::get_parent_by_protocol(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::ProtocolSession::getNow(), s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::IPSession::handle_pop_pkt(), HandleControlInput(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), s3f::s3fnet::DummySession::init(), s3f::s3fnet::UDPMaster::init(), s3f::s3fnet::OpenFlowControllerSession::init(), s3f::s3fnet::OpenVZEventSession::init(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPServerSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::TCPServerSession::init(), s3f::s3fnet::TCPMaster::init(), init(), s3f::s3fnet::NBTCPClientSession::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::SocketMaster::init(), s3f::s3fnet::IPSession::init(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::NBSocketMaster::init(), s3f::s3fnet::NBTCPServerSession::init(), s3f::s3fnet::TCPSession::init_state_closed(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::IPSession::IPSession(), s3f::s3fnet::UDPSession::listen(), s3f::s3fnet::SocketMaster::listen(), s3f::s3fnet::NBSocketMaster::listen(), s3f::s3fnet::IPSession::load_forwarding_table(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), ModFlow(), s3f::s3fnet::NBSocketMaster::NBSocketMaster(), s3f::s3fnet::NBTCPClientSession::NBTCPClientSession(), s3f::s3fnet::NBTCPServerSession::NBTCPServerSession(), s3f::s3fnet::NBTCPClientSession::non_blocking_loop(), s3f::s3fnet::NBTCPServerSession::non_blocking_loop(), OutputControl(), OutputPacket(), OutputPort(), s3f::s3fnet::OpenFlowControllerSession::pop(), s3f::s3fnet::UDPMaster::pop(), s3f::s3fnet::OpenVZEventSession::pop(), pop(), s3f::s3fnet::TCPMaster::pop(), s3f::s3fnet::IPSession::pop(), s3f::s3fnet::LearningController::process_recv_packet(), s3f::s3fnet::UDPMaster::push(), s3f::s3fnet::TCPMaster::push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::receive(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::LearningControllerSession::ReceiveFromSwitch(), ReceivePacketOut(), ReceivePortMod(), ReceiveStatsRequest(), s3f::s3fnet::SocketMaster::recv(), s3f::s3fnet::NBSocketMaster::recv(), s3f::s3fnet::SocketMaster::recv1(), s3f::s3fnet::NBSocketMaster::recv1(), s3f::s3fnet::UDPServerSession::request_received(), s3f::s3fnet::TCPServerSession::request_received(), s3f::s3fnet::UDPClientSession::request_sent(), s3f::s3fnet::TCPClientSession::request_sent(), s3f::s3fnet::NBTCPClientSessionContinuation::resume(), s3f::s3fnet::NBTCPServerSessionContinuation::resume(), RunThroughFlowTable(), s3f::s3fnet::UDPSession::send(), s3f::s3fnet::SocketMaster::send(), s3f::s3fnet::NBSocketMaster::send(), s3f::s3fnet::SocketMaster::send1(), s3f::s3fnet::NBSocketMaster::send1(), s3f::s3fnet::TCPSession::send_data(), SendFlowExpired(), SendOpenflowBuffer(), SendPortStatus(), s3f::s3fnet::UDPClientSession::server_connected(), s3f::s3fnet::TCPClientSession::server_connected(), s3f::s3fnet::BTCPClientSession::server_connected(), s3f::s3fnet::UDPServerSession::session_closed(), s3f::s3fnet::UDPClientSession::session_closed(), s3f::s3fnet::TCPClientSession::session_closed(), s3f::s3fnet::TCPServerSession::session_closed(), s3f::s3fnet::BTCPClientSession::session_closed(), s3f::s3fnet::TCPMaster::setConnected(), SetController(), s3f::s3fnet::TCPMaster::setIdle(), s3f::s3fnet::TCPMaster::setListening(), s3f::s3fnet::UDPSession::setSource(), s3f::s3fnet::TCPMaster::slow_timer_callback_body(), s3f::s3fnet::TCPSession::slowTimeoutHandling(), s3f::s3fnet::SocketMaster::socket(), s3f::s3fnet::NBSocketMaster::socket(), s3f::s3fnet::SocketMaster::SocketMaster(), s3f::s3fnet::UDPServerSession::start_on(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPServerSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), s3f::s3fnet::NBTCPClientSession::start_on(), s3f::s3fnet::BTCPClientSession::start_on(), s3f::s3fnet::NBTCPServerSession::start_on(), s3f::s3fnet::NBTCPServerSessionContinuation::success(), s3f::s3fnet::TCPClientSession::TCPClientSession(), s3f::s3fnet::TCPMaster::TCPMaster(), s3f::s3fnet::TCPServerSession::TCPServerSession(), s3f::s3fnet::TCPSession::TCPSession(), s3f::s3fnet::UDPClientSession::timeout(), s3f::s3fnet::TCPClientSession::timeout(), s3f::s3fnet::BTCPClientSession::timeout(), s3f::s3fnet::UDPClientSession::UDPClientSession(), s3f::s3fnet::UDPMaster::UDPMaster(), s3f::s3fnet::UDPServerSession::UDPServerSession(), s3f::s3fnet::UDPSession::UDPSession(), s3f::s3fnet::TCPSession::update_timeout(), s3f::s3fnet::IPSession::verify_local_ip_address(), and s3f::s3fnet::UDPSession::wake_app().
 {
   return dynamic_cast<Host*>(ingraph);
 }
Random::RNG* s3f::s3fnet::ProtocolSession::getRandom () inline inherited
The method returns a pointer to the random number generator.
Definition at line 200 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::sess_rng.
Referenced by s3f::s3fnet::DroptailQueue::calibrate(), s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::DummySession::init(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), and s3f::s3fnet::NetworkInterface::receivePacket().
 { return sess_rng;}
ltime_t s3f::s3fnet::ProtocolSession::getNow () inherited
The method returns the current simulation time.
To be safe, please do NOT call this function after initialization and before wrapup phase. That is, it is unsafe to call this method in the constructor, destructor, config, init, and wrapup methods. The time service is carried out by the host's owner community. This method just directs the call to the community. It's given here for convenience.
Definition at line 123 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::inHost(), and Entity::now().
Referenced by s3f::s3fnet::DroptailQueue::calibrate(), s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::TCPMaster::enableFastTimeout(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::TCPMaster::fast_timer_callback_body(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::TCPSession::now(), s3f::s3fnet::OpenVZEventSession::pop(), s3f::s3fnet::TCPMaster::slow_timer_callback_body(), s3f::s3fnet::SocketMaster::socket(), s3f::s3fnet::NBSocketMaster::socket(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), and s3f::s3fnet::BTCPClientSession::start_on().
 {
   return inHost()->now();
 }
char * s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator () inherited
For printing the current simulation time in a better readable format.
Definition at line 128 of file protocol_session.cc.
References s3f::s3fnet::Host::getNowWithThousandSeparator(), and s3f::s3fnet::ProtocolSession::inHost().
Referenced by s3f::s3fnet::UDPSession::abort(), s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::UDPSession::connect(), s3f::s3fnet::TCPMaster::createSession(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::UDPServerSession::data_sent(), s3f::s3fnet::TCPServerSession::data_sent(), s3f::s3fnet::UDPSession::disconnect(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::UDPSession::listen(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), s3f::s3fnet::DummySession::pop(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::OpenVZEventSession::pop(), s3f::s3fnet::UDPMaster::pop(), s3f::s3fnet::TCPMaster::pop(), s3f::s3fnet::IPSession::pop(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::UDPMaster::push(), s3f::s3fnet::SimplePhy::push(), s3f::s3fnet::TCPMaster::push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::receive(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::SimplePhy::receivePacket(), s3f::s3fnet::UDPServerSession::request_received(), s3f::s3fnet::TCPServerSession::request_received(), s3f::s3fnet::UDPClientSession::request_sent(), s3f::s3fnet::TCPClientSession::request_sent(), s3f::s3fnet::UDPSession::send(), s3f::s3fnet::TCPSession::send_data(), s3f::s3fnet::SimplePhy::sendPacket(), s3f::s3fnet::UDPClientSession::server_connected(), s3f::s3fnet::TCPClientSession::server_connected(), s3f::s3fnet::BTCPClientSession::server_connected(), s3f::s3fnet::UDPServerSession::session_closed(), s3f::s3fnet::UDPClientSession::session_closed(), s3f::s3fnet::TCPClientSession::session_closed(), s3f::s3fnet::TCPServerSession::session_closed(), s3f::s3fnet::BTCPClientSession::session_closed(), s3f::s3fnet::TCPMaster::setConnected(), s3f::s3fnet::TCPMaster::setIdle(), s3f::s3fnet::TCPMaster::setListening(), s3f::s3fnet::UDPSession::setSource(), s3f::s3fnet::TCPSession::slowTimeoutHandling(), s3f::s3fnet::UDPServerSession::start_on(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPServerSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), s3f::s3fnet::BTCPClientSession::start_on(), s3f::s3fnet::TCPSession::TCPSession(), s3f::s3fnet::UDPClientSession::timeout(), s3f::s3fnet::TCPClientSession::timeout(), s3f::s3fnet::BTCPClientSession::timeout(), s3f::s3fnet::UDPSession::UDPSession(), s3f::s3fnet::TCPSession::update_timeout(), and s3f::s3fnet::UDPSession::wake_app().
 {
         return inHost()->getNowWithThousandSeparator();
 }
int s3f::s3fnet::ProtocolSession::configured () inline inherited
This method returns true if the protocol session has been configured.
This method is used to make sure we configure the protocol session before initializing it.
Definition at line 221 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_CONFIGURED, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::config(), and s3f::s3fnet::ProtocolSession::init().
 { return stage >= PSESS_CONFIGURED; }
int s3f::s3fnet::ProtocolSession::initialized () inline inherited
This method returns true if the protocol session has been initialized.
This can be used to sequence calls to the init method of protocol sessions. For example, if protocol session A requires protocol session B to be initialized before A can be initialized, A's init method can call B's init method as long as B's initialized() returns true. The system does not enforce any ordering in its calls the init methods of all protocol sessions declared in the dml configuration.
Definition at line 233 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_INITIALIZED, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::init(), and s3f::s3fnet::ProtocolSession::wrapup().
 { return stage >= PSESS_INITIALIZED; }
int s3f::s3fnet::ProtocolSession::wrapped_up () inline inherited
This method returns true if the protocol session has been wrapped up.
This can be used to sequence calls to the wrapup method of protocol sessions. For example, if protocol session A requires protocol session B to be wrapped up before A can be wrapped up, A's wrapup method can call B's wrapup method as long as B's wrapped_up() returns true. The system does not enforce any ordering in its calls the wrapup methods of all protocol sessions declared in the dml configuration.
Definition at line 245 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_WRAPPED_UP, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::wrapup().
 { return stage >= PSESS_WRAPPED_UP; }
virtual const char* s3f::s3fnet::ProtocolSession::psesstype () inline virtual inherited
Reimplemented in s3f::s3fnet::NBSocketMaster, and s3f::s3fnet::SocketMaster.
Definition at line 247 of file protocol_session.h.
 { return "GENERIC"; } // DEBUG
virtual int s3f::s3fnet::ProtocolSession::instantiation_type () inline protected virtual inherited
This method controls how protocol instances can coexist with one another.
It returns one of the following:
PROT_UNIQUE_INSTANCE (default): allows only one instance for each type of protocol per protocol stack;
PROT_MULTIPLE_INSTANCES: allows multiple instances of the same implementation for each type of protocol per protocol stack;
PROT_MULTIPLE_IMPLEMENTATIONS: allows multiple instances from different implementations of the same protocol to exist on the protocol stack.
Reimplemented in s3f::s3fnet::BTCPClientSession, and s3f::s3fnet::TCPClientSession.
Definition at line 269 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PROT_UNIQUE_INSTANCE.
Referenced by s3f::s3fnet::ProtocolGraph::insert_session().
 { return PROT_UNIQUE_INSTANCE; }
Member Data Documentation
NetworkInterface* s3f::s3fnet::OpenFlowSwitchSession::ofctrl_port
the NetworkInterface of the OpenFlow controller
Definition at line 205 of file openflow_switch_session.h.
Referenced by s3f::s3fnet::NetworkInterface::init(), and OutputControl().
bool s3f::s3fnet::OpenFlowSwitchSession::is_ctrl_sess
whether it connects to an entity-based controller instead of non-entity controller
Definition at line 206 of file openflow_switch_session.h.
Referenced by DoDispose(), FlowTableLookup(), init(), OutputControl(), ReceiveStatsRequest(), SendOpenflowBuffer(), and SetController().
S3FNET_STRING s3f::s3fnet::OpenFlowSwitchSession::ctrl_nhi
the nhi of the controller entity
Definition at line 207 of file openflow_switch_session.h.
Referenced by config(), and SetController().
Host* s3f::s3fnet::OpenFlowSwitchSession::ctrl_host
the Host* of the active controller
Definition at line 208 of file openflow_switch_session.h.
Referenced by SetController().
OpenFlowControllerSession* s3f::s3fnet::OpenFlowSwitchSession::ctrl_sess
pointer of the controller protocol session
Definition at line 209 of file openflow_switch_session.h.
Referenced by ReceiveStatsRequest(), SendOpenflowBuffer(), and SetController().
Mac48Address* s3f::s3fnet::OpenFlowSwitchSession::m_address private
Address of this device. (the base MAC address, should not be used as for now)
Definition at line 463 of file openflow_switch_session.h.
Referenced by AddSwitchPort(), and pop().
uint16_t s3f::s3fnet::OpenFlowSwitchSession::m_mtu private
Maximum Transmission Unit.
Definition at line 464 of file openflow_switch_session.h.
Referenced by GetMtu(), and SetMtu().
PacketData_t s3f::s3fnet::OpenFlowSwitchSession::m_packetData private
Packet data.
Definition at line 467 of file openflow_switch_session.h.
Referenced by FlowTableLookup(), HandleControlInput(), OutputControl(), OutputPacket(), pop(), RunThroughFlowTable(), and RunThroughVPortTable().
Ports_t s3f::s3fnet::OpenFlowSwitchSession::m_ports private
Switch's ports.
Definition at line 470 of file openflow_switch_session.h.
Referenced by AddSwitchPort(), DoDispose(), GetNSwitchPorts(), GetSwitchPort(), GetSwitchPortIndex(), OpenFlowSwitchSession(), OutputAll(), OutputPacket(), pop(), ReceivePortMod(), RunThroughFlowTable(), and SendFeaturesReply().
Controller* s3f::s3fnet::OpenFlowSwitchSession::np_controller private
Connection to the non-entity controller; controller is not implemented as a protocol session, but as direct function calls.
Definition at line 472 of file openflow_switch_session.h.
Referenced by DoDispose(), ReceiveStatsRequest(), SendOpenflowBuffer(), and SetController().
uint64_t s3f::s3fnet::OpenFlowSwitchSession::m_id private
Unique identifier for this switch, needed for OpenFlow.
Definition at line 474 of file openflow_switch_session.h.
Referenced by OpenFlowSwitchSession(), and SendFeaturesReply().
ltime_t s3f::s3fnet::OpenFlowSwitchSession::m_lastExecute private
Last time the periodic execution occurred.
Definition at line 477 of file openflow_switch_session.h.
Referenced by pop().
uint16_t s3f::s3fnet::OpenFlowSwitchSession::m_flags private
Flags; configurable by the controller.
Definition at line 478 of file openflow_switch_session.h.
Referenced by ReceiveGetConfigRequest(), ReceiveSetConfig(), RunThroughFlowTable(), and RunThroughVPortTable().
uint16_t s3f::s3fnet::OpenFlowSwitchSession::m_missSendLen private
Flow Table Miss Send Length; configurable by the controller.
Definition at line 479 of file openflow_switch_session.h.
Referenced by FlowTableLookup(), ReceiveGetConfigRequest(), and ReceiveSetConfig().
sw_chain* s3f::s3fnet::OpenFlowSwitchSession::m_chain private
Flow Table; forwarding rules.
Definition at line 481 of file openflow_switch_session.h.
Referenced by AddFlow(), DoDispose(), FlowTableLookup(), GetChain(), ModFlow(), OpenFlowSwitchSession(), pop(), ReceiveFlow(), and SendFeaturesReply().
vport_table_t s3f::s3fnet::OpenFlowSwitchSession::m_vportTable private
Virtual Port Table.
Definition at line 482 of file openflow_switch_session.h.
Referenced by AddVPort(), DoDispose(), GetVPortTable(), OpenFlowSwitchSession(), ReceiveVPortMod(), RunThroughVPortTable(), and SendVPortTableFeatures().
const uint16_t s3f::s3fnet::OpenFlowSwitchSession::DEFAULT_MTU = 1500 static private
Definition at line 484 of file openflow_switch_session.h.
Referenced by init().
char* s3f::s3fnet::ProtocolSession::name inherited
Symbolic name of the protocol this session implements.
The name of the protocol is derived from the DML 'name' attribute. It must not be NULL once the protocol session is configured.
Definition at line 63 of file protocol_session.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::SimpleMac::init(), s3f::s3fnet::UDPMaster::init(), s3f::s3fnet::SimplePhy::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::SocketMaster::init(), s3f::s3fnet::IPSession::init(), s3f::s3fnet::NBSocketMaster::init(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::ProtocolGraph::insert_session(), s3f::s3fnet::ProtocolSession::wrapup(), and s3f::s3fnet::ProtocolSession::~ProtocolSession().
float s3f::s3fnet::ProtocolSession::version inherited
Version number of this protocol implemenntation, represented as a floating point number (e.g., 1.23).
Definition at line 69 of file protocol_session.h.
char* s3f::s3fnet::ProtocolSession::use inherited
Name of the protocol class from which this protocol session is instantiated.
The protocol class must be registered with the Protocols class so that we will be able to instantiate an object from the class. (C++ does not support self-reflection). The class name must not be NULL once the protocol session is configured.
Definition at line 79 of file protocol_session.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::ProtocolGraph::insert_session(), and s3f::s3fnet::ProtocolSession::~ProtocolSession().
ProtocolGraph* s3f::s3fnet::ProtocolSession::ingraph protected inherited
Points to the protocol graph.
Definition at line 335 of file protocol_session.h.
Referenced by s3f::s3fnet::NicProtocolSession::getNetworkInterface(), s3f::s3fnet::ProtocolSession::inGraph(), and s3f::s3fnet::ProtocolSession::inHost().
Random::RNG* s3f::s3fnet::ProtocolSession::sess_rng protected inherited
Pointer to a random number generator.
Definition at line 338 of file protocol_session.h.
Referenced by s3f::s3fnet::ProtocolSession::getRandom(), and s3f::s3fnet::ProtocolSession::init().
int s3f::s3fnet::ProtocolSession::stage protected inherited
This variable indicates the current stage of this protocol session.
Each protocol session will go through four staged: PSESS_CREATED, PSESS_CONFIGURED, PSESS_INITIALIZED, and then PSESS_WRAPPED_UP.
Definition at line 346 of file protocol_session.h.
Referenced by s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::ProtocolSession::configured(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::ProtocolSession::initialized(), s3f::s3fnet::ProtocolSession::wrapped_up(), and s3f::s3fnet::ProtocolSession::wrapup().
The documentation for this class was generated from the following files:
openflow_switch_session.h
openflow_switch_session.cc