S3F: s3f::s3fnet::trie2::Trie2::iterator Class Reference
s3f::s3fnet::trie2::Trie2::iterator Class Reference
#include <trie2.h>
Classes
class NodeNext
Stores iterator's state.
class State
Public Types
enum NextMove { LEFT = 0, RIGHT = 1, UP = 2, UNDEF = 3 }
Enum for iterator movement.
Public Member Functions
iterator ()
iterator constructor
iterator (Trie2 *t)
iterator constructor for Trie2 types
iterator (const Trie2::iterator &it)
iterator copy constructor
~iterator ()
iterator destructor
iterator & operator= (iterator &rhs)
Assignment operator.
int operator== (iterator &rhs)
Equals comparison operator.
int operator!= (iterator &rhs)
Not equals comparison operator.
iterator & operator++ ()
Prefix incr.
TrieNode * operator-> ()
Arrow operator.
S3FNET_STACK (NodeNext *) stateStack
Iterator's state stack.
void print ()
Prints the iterator.
Public Attributes
Trie2 * myTrie
Trie2 reference Generally root for iterator.
TrieNode * currentNode
Current iterator node.
Private Member Functions
void copyStack (S3FNET_STACK(NodeNext *)&from, bool deepCopy=true)
Copy state stack.
void nextNode ()
Move to next node.
Detailed Description
Depth-first iterator.
Definition at line 130 of file trie2.h.
Member Enumeration Documentation
enum s3f::s3fnet::trie2::Trie2::iterator::NextMove
Enum for iterator movement.
Enumerator
LEFT
Iterator should move to the left.
RIGHT
Iterator should move to the right.
UP
Iterator should move up (backwards)
UNDEF
Iterator movement is undefined.
Definition at line 141 of file trie2.h.
                   {
       LEFT  = 0,
       RIGHT = 1,
       UP    = 2,
       UNDEF = 3
     };
Constructor & Destructor Documentation
s3f::s3fnet::trie2::Trie2::iterator::iterator ()
iterator constructor
Definition at line 224 of file trie2.cc.
                         : myTrie(0), currentNode(0), stateStack()
 {}
s3f::s3fnet::trie2::Trie2::iterator::iterator (Trie2 * t)
iterator constructor for Trie2 types
Definition at line 228 of file trie2.cc.
                                 : myTrie(t), currentNode(0),
                                     stateStack()
 {}
s3f::s3fnet::trie2::Trie2::iterator::iterator (const Trie2::iterator & it)
iterator copy constructor
Definition at line 232 of file trie2.cc.
References copyStack(), and S3FNET_STACK().
                                                :
   myTrie(it.myTrie), currentNode(it.currentNode), stateStack()
 {
   if (it.stateStack.size() > 0) {
     // copy stack -- Need to modify the it.stateStack but will put it back.
     // So, casting away const.
     S3FNET_STACK(NodeNext*)& ss = (S3FNET_STACK(NodeNext*)&)it.stateStack;
     copyStack(ss, true); // deep copy
   }
 }
s3f::s3fnet::trie2::Trie2::iterator::~iterator ()
iterator destructor
Definition at line 243 of file trie2.cc.
{
   // destroy state contents
   while (stateStack.size() > 0) {
     iterator::NodeNext* nn = stateStack.top();
     stateStack.pop();
     delete nn;
   }
 }
Member Function Documentation
Trie2::iterator & s3f::s3fnet::trie2::Trie2::iterator::operator= (iterator & rhs)
Assignment operator.
Does deep copy of state stack.
Definition at line 252 of file trie2.cc.
References currentNode, and myTrie.
{
   myTrie = rhs.myTrie;
   currentNode = rhs.currentNode;
   if (rhs.stateStack.size() > 0) {
     // copy stack
     copyStack(rhs.stateStack);
   }
   return *this;
 }
int s3f::s3fnet::trie2::Trie2::iterator::operator== (iterator & rhs)
Equals comparison operator.
Definition at line 282 of file trie2.cc.
References currentNode.
{
   if (currentNode != rhs.currentNode) {
     return 0;
   }
   if (stateStack.size() != rhs.stateStack.size()) {
     return 0;
   }
   if (stateStack.size() > 0 && !(stateStack.top() == rhs.stateStack.top())) {
     return 0;
   }
   return 1;
 }
int s3f::s3fnet::trie2::Trie2::iterator::operator!= (iterator & rhs)
Not equals comparison operator.
Definition at line 295 of file trie2.cc.
{
   return (*this == rhs) ? 0 : 1;
 }
Trie2::iterator & s3f::s3fnet::trie2::Trie2::iterator::operator++ ()
Prefix incr.
operator.
Definition at line 299 of file trie2.cc.
References TRIE2_DUMP.
{
   if (!currentNode) {
     stateStack.push(new NodeNext(myTrie->root, LEFT));
     currentNode = myTrie->root;
     assert(currentNode);
   }
   do {
     nextNode();
   } while (currentNode->data == 0  // repeat until node with data found
            && currentNode != myTrie->root); // or reached end
   if (currentNode == myTrie->root) {
     currentNode = 0;
     TRIE2_DUMP(std::cout << currentNode << " stopped (end)" << std::endl);
   } else {
     TRIE2_DUMP(std::cout << currentNode << " stopped (found)" << std::endl);
   }
   return *this;
 }
TrieNode * s3f::s3fnet::trie2::Trie2::iterator::operator-> ()
Arrow operator.
Definition at line 370 of file trie2.cc.
{
   return currentNode;
 }
s3f::s3fnet::trie2::Trie2::iterator::S3FNET_STACK (NodeNext *)
Iterator's state stack.
Referenced by iterator().
void s3f::s3fnet::trie2::Trie2::iterator::print ()
Prints the iterator.
Used primarily for debugging.
Definition at line 375 of file trie2.cc.
{
   std::cout << "Trie2::iterator -- trie=" << myTrie << " currentNode=" << currentNode
        << " stateStack size=" << stateStack.size() << std::endl;
 }
void s3f::s3fnet::trie2::Trie2::iterator::copyStack (S3FNET_STACK(NodeNext *)& from, bool deepCopy = true) private
Copy state stack.
Copies the state stack. Intended as an assignment helper.
Definition at line 263 of file trie2.cc.
References S3FNET_STACK.
Referenced by iterator().
{
   S3FNET_STACK(NodeNext*)& to = stateStack;
   if (from.size() > 0) {
     // pop elem
     NodeNext* nn = from.top();
     from.pop();
     // copy rest
     copyStack(from);
     // copy elem
     if (deepCopy) {
       to.push(new NodeNext(*nn));
     } else {
       to.push(nn);
     }
     from.push(nn);
   }
   return;
 }
void s3f::s3fnet::trie2::Trie2::iterator::nextNode () private
Move to next node.
Moves to the next node. Intended as an iterator helper.
Definition at line 319 of file trie2.cc.
References s3f::s3fnet::trie2::TrieNode::children, s3f::s3fnet::trie2::Trie2::iterator::NodeNext::next, s3f::s3fnet::trie2::Trie2::iterator::NodeNext::node, and TRIE2_DUMP.
{
   bool keepMoving = true;
   while(keepMoving) {
     NodeNext* nn = stateStack.top();
     stateStack.pop();
     currentNode = nn->node;
     assert(currentNode);
     switch (nn->next) {
     case LEFT: {
       stateStack.push(new NodeNext(nn->node, RIGHT)); // afterwards move right
       TrieNode* leftChild = currentNode->children[LEFT];
       if (leftChild) { // has left child?
         stateStack.push(new NodeNext(leftChild, LEFT)); // descend left
         TRIE2_DUMP(std::cout << currentNode << " push RIGHT, LEFT down, push LEFT (" <<
                   stateStack.size() << ") - "; currentNode->dump(); std::cout << std::endl);
       } else {
         TRIE2_DUMP(std::cout << currentNode << " push RIGHT (" << stateStack.size() <<
                   ") - "; currentNode->dump(); std::cout << std::endl);
       }
       }
       break;
     case RIGHT: {
       stateStack.push(new NodeNext(nn->node, UP)); // afterwards move up
       TrieNode* rightChild = currentNode->children[RIGHT];
       if (rightChild) { // has right child?
         TRIE2_DUMP(std::cout << currentNode << " push UP, RIGHT down, push LEFT (" <<
                   stateStack.size() << ") - "; currentNode->dump(); std::cout << std::endl);
         stateStack.push(new NodeNext(rightChild, LEFT)); // afterwards move left
       } else {
         TRIE2_DUMP(std::cout << currentNode << " push UP (" << stateStack.size() <<
                   ") - "; currentNode->dump(); std::cout << std::endl);
       }
       }
       break;
     case UP:
       // visit node
       keepMoving = false;
       TRIE2_DUMP(std::cout << currentNode << " visit (" << stateStack.size() <<
                 ") - "; currentNode->dump(); std::cout << std::endl);
       assert(currentNode != myTrie->root || stateStack.size() == 0);
       break;
     default:
       // ERROR: undefined state of trie iterator
       throw State();
     } // switch
     delete nn;
   } // while
 }
Member Data Documentation
Trie2* s3f::s3fnet::trie2::Trie2::iterator::myTrie
Trie2 reference Generally root for iterator.
Definition at line 220 of file trie2.h.
Referenced by operator=().
TrieNode* s3f::s3fnet::trie2::Trie2::iterator::currentNode
Current iterator node.
Definition at line 225 of file trie2.h.
Referenced by operator=(), and operator==().
The documentation for this class was generated from the following files:
trie2.h
trie2.cc