S3F: s3f::s3fnet::trie1::Trie1::iterator Class Reference
s3f::s3fnet::trie1::Trie1::iterator Class Reference
#include <trie1.h>
Classes
class NodeNext
Stores iterator's state.
class State
Public Types
enum NextMove { LEFT = 0, RIGHT = 1, UP = 2, UNDEF = 3 }
Enum for iterator movement.
Public Member Functions
iterator ()
iterator constructor
iterator (Trie1 *t)
iterator constructor for Trie1 types
iterator (const Trie1::iterator &it)
iterator copy constructor
~iterator ()
iterator destructor
iterator & operator= (iterator &rhs)
Assignment operator.
int operator== (iterator &rhs)
Equals comparison operator.
int operator!= (iterator &rhs)
Not equals comparison operator.
iterator & operator++ ()
Prefix incr.
TrieNode * operator-> ()
Arrow operator.
S3FNET_STACK (NodeNext *) stateStack
Iterator's state stack.
void print ()
Prints the iterator.
Public Attributes
Trie1 * myTrie
Trie1 reference Generally root for iterator.
TrieNode * currentNode
Current iterator node.
Private Member Functions
void copyStack (S3FNET_STACK(NodeNext *)&from, bool deepCopy=true)
Copy state stack.
void nextNode ()
Move to next node.
Detailed Description
Depth-first iterator.
Definition at line 150 of file trie1.h.
Member Enumeration Documentation
enum s3f::s3fnet::trie1::Trie1::iterator::NextMove
Enum for iterator movement.
Enumerator
LEFT
Iterator should move to the left.
RIGHT
Iterator should move to the right.
UP
Iterator should move up (backwards)
UNDEF
Iterator movement is undefined.
Definition at line 161 of file trie1.h.
                   {
       LEFT  = 0,
       RIGHT = 1,
       UP    = 2,
       UNDEF = 3
     };
Constructor & Destructor Documentation
s3f::s3fnet::trie1::Trie1::iterator::iterator ()
iterator constructor
Definition at line 252 of file trie1.cc.
                         : myTrie(0), currentNode(0), stateStack()
 {}
s3f::s3fnet::trie1::Trie1::iterator::iterator (Trie1 * t)
iterator constructor for Trie1 types
Definition at line 256 of file trie1.cc.
                                 : myTrie(t), currentNode(0),
                                     stateStack()
 {}
s3f::s3fnet::trie1::Trie1::iterator::iterator (const Trie1::iterator & it)
iterator copy constructor
Definition at line 260 of file trie1.cc.
References copyStack(), and S3FNET_STACK().
                                                :
   myTrie(it.myTrie), currentNode(it.currentNode), stateStack()
 {
   if (it.stateStack.size() > 0) {
     // copy stack -- Need to modify the it.stateStack but will put it back.
     // So, casting away const.
     S3FNET_STACK(NodeNext*)& ss = (S3FNET_STACK(NodeNext*)&)it.stateStack;
     copyStack(ss, true); // deep copy
   }
 }
s3f::s3fnet::trie1::Trie1::iterator::~iterator ()
iterator destructor
Definition at line 271 of file trie1.cc.
{
   // destroy state contents
   while (stateStack.size() > 0) {
     iterator::NodeNext* nn = stateStack.top();
     stateStack.pop();
     delete nn;
   }
 }
Member Function Documentation
Trie1::iterator & s3f::s3fnet::trie1::Trie1::iterator::operator= (iterator & rhs)
Assignment operator.
Does deep copy of state stack.
Definition at line 280 of file trie1.cc.
References currentNode, and myTrie.
{
   myTrie = rhs.myTrie;
   currentNode = rhs.currentNode;
   if (rhs.stateStack.size() > 0) {
     // copy stack
     copyStack(rhs.stateStack);
   }
   return *this;
 }
int s3f::s3fnet::trie1::Trie1::iterator::operator== (iterator & rhs)
Equals comparison operator.
Definition at line 310 of file trie1.cc.
References currentNode.
{
   if (currentNode != rhs.currentNode) {
     return 0;
   }
   if (stateStack.size() != rhs.stateStack.size()) {
     return 0;
   }
   if (stateStack.size() > 0 && !(stateStack.top() == rhs.stateStack.top())) {
     return 0;
   }
   return 1;
 }
int s3f::s3fnet::trie1::Trie1::iterator::operator!= (iterator & rhs)
Not equals comparison operator.
Definition at line 323 of file trie1.cc.
{
   return (*this == rhs) ? 0 : 1;
 }
Trie1::iterator & s3f::s3fnet::trie1::Trie1::iterator::operator++ ()
Prefix incr.
operator.
Definition at line 327 of file trie1.cc.
References TRIE1_DUMP.
{
   if (!currentNode) {
     stateStack.push(new NodeNext(myTrie->root, LEFT));
     currentNode = myTrie->root;
     assert(currentNode);
   }
   do {
     nextNode();
   } while (currentNode->data == 0  // repeat until node with data found
            && currentNode != myTrie->root); // or reached end
   if (currentNode == myTrie->root) {
     currentNode = 0;
     TRIE1_DUMP(std::cout << currentNode << " stopped (end)" << std::endl);
   } else {
     TRIE1_DUMP(std::cout << currentNode << " stopped (found)" << std::endl);
   }
   return *this;
 }
TrieNode * s3f::s3fnet::trie1::Trie1::iterator::operator-> ()
Arrow operator.
Definition at line 398 of file trie1.cc.
{
   return currentNode;
 }
s3f::s3fnet::trie1::Trie1::iterator::S3FNET_STACK (NodeNext *)
Iterator's state stack.
Referenced by iterator().
void s3f::s3fnet::trie1::Trie1::iterator::print ()
Prints the iterator.
Used primarily for debugging.
Definition at line 403 of file trie1.cc.
{
   std::cout << "Trie1::iterator -- trie=" << myTrie << " currentNode=" << currentNode
        << " stateStack size=" << stateStack.size() << std::endl;
 }
void s3f::s3fnet::trie1::Trie1::iterator::copyStack (S3FNET_STACK(NodeNext *)& from, bool deepCopy = true) private
Copy state stack.
Copies the state stack. Intended as an assignment helper.
Definition at line 291 of file trie1.cc.
References S3FNET_STACK.
Referenced by iterator().
{
   S3FNET_STACK(NodeNext*)& to = stateStack;
   if (from.size() > 0) {
     // pop elem
     NodeNext* nn = from.top();
     from.pop();
     // copy rest
     copyStack(from);
     // copy elem
     if (deepCopy) {
       to.push(new NodeNext(*nn));
     } else {
       to.push(nn);
     }
     from.push(nn);
   }
   return;
 }
void s3f::s3fnet::trie1::Trie1::iterator::nextNode () private
Move to next node.
Moves to the next node. Intended as an iterator helper.
Definition at line 347 of file trie1.cc.
References s3f::s3fnet::trie1::TrieNode::children, s3f::s3fnet::trie1::Trie1::iterator::NodeNext::next, s3f::s3fnet::trie1::Trie1::iterator::NodeNext::node, and TRIE1_DUMP.
{
   bool keepMoving = true;
   while(keepMoving) {
     NodeNext* nn = stateStack.top();
     stateStack.pop();
     currentNode = nn->node;
     assert(currentNode);
     switch (nn->next) {
     case LEFT: {
       stateStack.push(new NodeNext(nn->node, RIGHT)); // afterwards move right
       TrieNode* leftChild = currentNode->children[LEFT];
       if (leftChild) { // has left child?
         stateStack.push(new NodeNext(leftChild, LEFT)); // descend left
         TRIE1_DUMP(std::cout << currentNode << " push RIGHT, LEFT down, push LEFT (" <<
                   stateStack.size() << ") - "; currentNode->dump(); std::cout << std::endl);
       } else {
         TRIE1_DUMP(std::cout << currentNode << " push RIGHT (" << stateStack.size() <<
                   ") - "; currentNode->dump(); std::cout << std::endl);
       }
       }
       break;
     case RIGHT: {
       stateStack.push(new NodeNext(nn->node, UP)); // afterwards move up
       TrieNode* rightChild = currentNode->children[RIGHT];
       if (rightChild) { // has right child?
         TRIE1_DUMP(std::cout << currentNode << " push UP, RIGHT down, push LEFT (" <<
                   stateStack.size() << ") - "; currentNode->dump(); std::cout << std::endl);
         stateStack.push(new NodeNext(rightChild, LEFT)); // afterwards move left
       } else {
         TRIE1_DUMP(std::cout << currentNode << " push UP (" << stateStack.size() <<
                   ") - "; currentNode->dump(); std::cout << std::endl);
       }
       }
       break;
     case UP:
       // visit node
       keepMoving = false;
       TRIE1_DUMP(std::cout << currentNode << " visit (" << stateStack.size() <<
                 ") - "; currentNode->dump(); std::cout << std::endl);
       assert(currentNode != myTrie->root || stateStack.size() == 0);
       break;
     default:
       // ERROR: undefined state of trie iterator
       throw State();
     } // switch
     delete nn;
   } // while
 }
Member Data Documentation
Trie1* s3f::s3fnet::trie1::Trie1::iterator::myTrie
Trie1 reference Generally root for iterator.
Definition at line 240 of file trie1.h.
Referenced by operator=().
TrieNode* s3f::s3fnet::trie1::Trie1::iterator::currentNode
Current iterator node.
Definition at line 245 of file trie1.h.
Referenced by operator=(), and operator==().
The documentation for this class was generated from the following files:
trie1.h
trie1.cc