S3F: s3f::s3fnet::Stats Class Reference
s3f::s3fnet::Stats Class Reference
#include <openflow_interface.h>
Classes
struct FlowStatsState
State of the FlowStats request/reply.
struct PortStatsState
State of the PortStats request/reply.
Public Member Functions
Stats (ofp_stats_types _type, size_t body_len)
int DoInit (const void *body, int body_len, void **state)
Prepares to dump some kind of statistics on the connected OpenFlowSwitchSession.
int DoDump (OpenFlowSwitchSession *swtch, void *state, ofpbuf *buffer)
Appends statistics for OpenFlowSwitchSession to 'buffer'.
void DoCleanup (void *state)
Cleans any state created by the init or dump functions.
Public Attributes
ofp_stats_types type
Private Member Functions
int DescStatsDump (void *state, ofpbuf *buffer)
int FlowStatsInit (const void *body, int body_len, void **state)
int FlowStatsDump (OpenFlowSwitchSession *dp, FlowStatsState *s, ofpbuf *buffer)
int AggregateStatsInit (const void *body, int body_len, void **state)
int AggregateStatsDump (OpenFlowSwitchSession *dp, ofp_aggregate_stats_request *s, ofpbuf *buffer)
int TableStatsDump (OpenFlowSwitchSession *dp, void *state, ofpbuf *buffer)
int PortStatsInit (const void *body, int body_len, void **state)
int PortStatsDump (OpenFlowSwitchSession *dp, PortStatsState *s, ofpbuf *buffer)
int PortTableStatsDump (OpenFlowSwitchSession *dp, void *state, ofpbuf *buffer)
Private Attributes
int(* FlowDumpCallback)(sw_flow *flow, void *state)
int(* AggregateDumpCallback)(sw_flow *flow, void *state)
Detailed Description
Definition at line 131 of file openflow_interface.h.
Constructor & Destructor Documentation
s3f::s3fnet::Stats::Stats (ofp_stats_types _type, size_t body_len)
Definition at line 22 of file openflow_interface.cc.
References OF_IFACE_DUMP, and type.
 {
   type = _type;
   size_t min_body = 0, max_body = 0;
   switch (type)
     {
     case OFPST_DESC:
       break;
     case OFPST_FLOW:
       min_body = max_body = sizeof(ofp_flow_stats_request);
       break;
     case OFPST_AGGREGATE:
       min_body = max_body = sizeof(ofp_aggregate_stats_request);
       break;
     case OFPST_TABLE:
       break;
     case OFPST_PORT:
       min_body = 0;
       max_body = std::numeric_limits<size_t>::max (); // Not sure about this one. This would guarantee that the body_len is always acceptable.
       break;
     case OFPST_PORT_TABLE:
       break;
     default:
       OF_IFACE_DUMP (cout << "received stats request of unknown type " << type << endl);
       return; // -EINVAL;
     }
   if ((min_body != 0 || max_body != 0) && (body_len < min_body || body_len > max_body))
     {
           OF_IFACE_DUMP (cout << "stats request type " << type << " with bad body length " << body_len << endl);
       return; // -EINVAL;
     }
 }
Member Function Documentation
int s3f::s3fnet::Stats::DoInit (const void * body, int body_len, void ** state)
Prepares to dump some kind of statistics on the connected OpenFlowSwitchSession.
Parameters
body Body member of the struct ofp_stats_request.
body_len Length of the body member.
state State information.
Returns
0 if successful, otherwise a negative error code.
Definition at line 57 of file openflow_interface.cc.
References AggregateStatsInit(), FlowStatsInit(), PortStatsInit(), and type.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::ReceiveStatsRequest().
 {
   switch (type)
     {
     case OFPST_DESC:
       return 0;
     case OFPST_FLOW:
       return FlowStatsInit (body, body_len, state);
     case OFPST_AGGREGATE:
       return AggregateStatsInit (body, body_len, state);
     case OFPST_TABLE:
       return 0;
     case OFPST_PORT:
       return PortStatsInit (body, body_len, state);
     case OFPST_PORT_TABLE:
       return 0;
     case OFPST_VENDOR:
       return 0;
     }
   return 0;
 }
int s3f::s3fnet::Stats::DoDump (OpenFlowSwitchSession * swtch, void * state, ofpbuf * buffer)
Appends statistics for OpenFlowSwitchSession to 'buffer'.
Parameters
swtch The OpenFlowSwitchSession this callback is associated with.
state State information.
buffer Buffer to append stats reply to.
Returns
1 if it should be called again later with another buffer, 0 if it is done, or a negative errno value on failure.
Definition at line 80 of file openflow_interface.cc.
References AggregateStatsDump(), DescStatsDump(), FlowStatsDump(), PortStatsDump(), PortTableStatsDump(), TableStatsDump(), and type.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::StatsDump().
 {
   switch (type)
     {
     case OFPST_DESC:
       return DescStatsDump (state, buffer);
     case OFPST_FLOW:
       return FlowStatsDump (swtch, (FlowStatsState *)state, buffer);
     case OFPST_AGGREGATE:
       return AggregateStatsDump (swtch, (ofp_aggregate_stats_request *)state, buffer);
     case OFPST_TABLE:
       return TableStatsDump (swtch, state, buffer);
     case OFPST_PORT:
       return PortStatsDump (swtch, (PortStatsState *)state, buffer);
     case OFPST_PORT_TABLE:
       return PortTableStatsDump (swtch, state, buffer);
     case OFPST_VENDOR:
       return 0;
     }
   return 0;
 }
void s3f::s3fnet::Stats::DoCleanup (void * state)
Cleans any state created by the init or dump functions.
May not be implemented if no cleanup is required.
Parameters
state State information to clear.
Definition at line 103 of file openflow_interface.cc.
References type.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::StatsDone().
 {
   switch (type)
     {
     case OFPST_DESC:
       break;
     case OFPST_FLOW:
       free ((FlowStatsState *)state);
       break;
     case OFPST_AGGREGATE:
       free ((ofp_aggregate_stats_request *)state);
       break;
     case OFPST_TABLE:
       break;
     case OFPST_PORT:
       free (((PortStatsState *)state)->ports);
       free ((PortStatsState *)state);
       break;
     case OFPST_PORT_TABLE:
       break;
     case OFPST_VENDOR:
       break;
     }
 }
int s3f::s3fnet::Stats::DescStatsDump (void * state, ofpbuf * buffer) private
Definition at line 128 of file openflow_interface.cc.
References s3f::s3fnet::OpenFlowSwitchSession::GetHardwareDescription(), s3f::s3fnet::OpenFlowSwitchSession::GetManufacturerDescription(), s3f::s3fnet::OpenFlowSwitchSession::GetSerialNumber(), and s3f::s3fnet::OpenFlowSwitchSession::GetSoftwareDescription().
Referenced by DoDump().
 {
   ofp_desc_stats *ods = (ofp_desc_stats*)ofpbuf_put_zeros (buffer, sizeof *ods);
   strncpy (ods->mfr_desc, OpenFlowSwitchSession::GetManufacturerDescription (), sizeof ods->mfr_desc);
   strncpy (ods->hw_desc, OpenFlowSwitchSession::GetHardwareDescription (), sizeof ods->hw_desc);
   strncpy (ods->sw_desc, OpenFlowSwitchSession::GetSoftwareDescription (), sizeof ods->sw_desc);
   strncpy (ods->serial_num, OpenFlowSwitchSession::GetSerialNumber (), sizeof ods->serial_num);
   return 0;
 }
int s3f::s3fnet::Stats::FlowStatsInit (const void * body, int body_len, void ** state) private
Definition at line 140 of file openflow_interface.cc.
References s3f::s3fnet::Stats::FlowStatsState::position, s3f::s3fnet::Stats::FlowStatsState::rq, and s3f::s3fnet::Stats::FlowStatsState::table_idx.
Referenced by DoInit().
 {
   const ofp_flow_stats_request *fsr = (ofp_flow_stats_request*)body;
   FlowStatsState *s = (FlowStatsState*)xmalloc (sizeof *s);
   s->table_idx = fsr->table_id == 0xff ? 0 : fsr->table_id;
   memset (&s->position, 0, sizeof s->position);
   s->rq = *fsr;
   *state = s;
   return 0;
 }
int s3f::s3fnet::Stats::FlowStatsDump (OpenFlowSwitchSession * dp, FlowStatsState * s, ofpbuf * buffer) private
Definition at line 184 of file openflow_interface.cc.
References s3f::s3fnet::Stats::FlowStatsState::buffer, FlowDumpCallback, s3f::s3fnet::OpenFlowSwitchSession::GetChain(), s3f::s3fnet::ProtocolSession::inHost(), MAX_FLOW_STATS_BYTES, Entity::now(), s3f::s3fnet::Stats::FlowStatsState::now, s3f::s3fnet::Stats::FlowStatsState::position, s3f::s3fnet::Stats::FlowStatsState::rq, and s3f::s3fnet::Stats::FlowStatsState::table_idx.
Referenced by DoDump().
 {
   sw_flow_key match_key;
   flow_extract_match (&match_key, &s->rq.match);
   s->buffer = buffer;
   s->now = (time_t)(swtch->inHost()->now());
   while (s->table_idx < swtch->GetChain ()->n_tables
          && (s->rq.table_id == 0xff || s->rq.table_id == s->table_idx))
     {
       sw_table *table = swtch->GetChain ()->tables[s->table_idx];
       if (table->iterate (table, &match_key, s->rq.out_port, &s->position, Stats::FlowDumpCallback, s))
         {
           break;
         }
       s->table_idx++;
       memset (&s->position, 0, sizeof s->position);
     }
   return s->buffer->size >= MAX_FLOW_STATS_BYTES;
 }
int s3f::s3fnet::Stats::AggregateStatsInit (const void * body, int body_len, void ** state) private
Definition at line 208 of file openflow_interface.cc.
Referenced by DoInit().
 {
   //ofp_aggregate_stats_request *s = (ofp_aggregate_stats_request*)body;
   *state = (ofp_aggregate_stats_request*)body;
   return 0;
 }
int s3f::s3fnet::Stats::AggregateStatsDump (OpenFlowSwitchSession * dp, ofp_aggregate_stats_request * s, ofpbuf * buffer) private
Definition at line 224 of file openflow_interface.cc.
References AggregateDumpCallback, and s3f::s3fnet::OpenFlowSwitchSession::GetChain().
Referenced by DoDump().
 {
   ofp_aggregate_stats_request *rq = s;
   ofp_aggregate_stats_reply *rpy = (ofp_aggregate_stats_reply*)ofpbuf_put_zeros (buffer, sizeof *rpy);
   sw_flow_key match_key;
   flow_extract_match (&match_key, &rq->match);
   int table_idx = rq->table_id == 0xff ? 0 : rq->table_id;
   sw_table_position position;
   memset (&position, 0, sizeof position);
   while (table_idx < swtch->GetChain ()->n_tables
          && (rq->table_id == 0xff || rq->table_id == table_idx))
     {
       sw_table *table = swtch->GetChain ()->tables[table_idx];
       int error = table->iterate (table, &match_key, rq->out_port, &position, Stats::AggregateDumpCallback, rpy);
       if (error)
         {
           return error;
         }
       table_idx++;
       memset (&position, 0, sizeof position);
     }
   rpy->packet_count = htonll (rpy->packet_count);
   rpy->byte_count = htonll (rpy->byte_count);
   rpy->flow_count = htonl (rpy->flow_count);
   return 0;
 }
int s3f::s3fnet::Stats::TableStatsDump (OpenFlowSwitchSession * dp, void * state, ofpbuf * buffer) private
Definition at line 255 of file openflow_interface.cc.
References s3f::s3fnet::OpenFlowSwitchSession::GetChain().
Referenced by DoDump().
 {
   sw_chain* ft = swtch->GetChain ();
   for (int i = 0; i < ft->n_tables; i++)
     {
       ofp_table_stats *ots = (ofp_table_stats*)ofpbuf_put_zeros (buffer, sizeof *ots);
       sw_table_stats stats;
       ft->tables[i]->stats (ft->tables[i], &stats);
       strncpy (ots->name, stats.name, sizeof ots->name);
       ots->table_id = i;
       ots->wildcards = htonl (stats.wildcards);
       ots->max_entries = htonl (stats.max_flows);
       ots->active_count = htonl (stats.n_flows);
       ots->lookup_count = htonll (stats.n_lookup);
       ots->matched_count = htonll (stats.n_matched);
     }
   return 0;
 }
int s3f::s3fnet::Stats::PortStatsInit (const void * body, int body_len, void ** state) private
Definition at line 287 of file openflow_interface.cc.
References s3f::s3fnet::Stats::PortStatsState::num_ports, and s3f::s3fnet::Stats::PortStatsState::ports.
Referenced by DoInit().
 {
   PortStatsState *s = (PortStatsState*)xmalloc (sizeof *s);
   // the body contains a list of port numbers
   s->ports = (uint32_t*)xmalloc (body_len);
   memcpy (s->ports, body, body_len);
   s->num_ports = body_len / sizeof(uint32_t);
   *state = s;
   return 0;
 }
int s3f::s3fnet::Stats::PortStatsDump (OpenFlowSwitchSession * dp, PortStatsState * s, ofpbuf * buffer) private
Definition at line 300 of file openflow_interface.cc.
References s3f::s3fnet::OpenFlowSwitchSession::GetSwitchPort(), s3f::s3fnet::OpenFlowSwitchSession::GetSwitchPortIndex(), s3f::s3fnet::OpenFlowSwitchSession::GetVPortTable(), s3f::s3fnet::Port::mpls_ttl0_dropped, s3f::s3fnet::Port::netdev, s3f::s3fnet::Stats::PortStatsState::num_ports, OF_IFACE_DUMP, s3f::s3fnet::Stats::PortStatsState::ports, s3f::s3fnet::Port::rx_bytes, s3f::s3fnet::Port::rx_packets, s3f::s3fnet::Port::tx_bytes, s3f::s3fnet::Port::tx_dropped, and s3f::s3fnet::Port::tx_packets.
Referenced by DoDump().
 {
   ofp_port_stats *ops;
   uint32_t port;
   // port stats are different depending on whether port is physical or virtual
   for (size_t i = 0; i < s->num_ports; i++)
     {
       port = ntohl (s->ports[i]);
       // physical port?
       if (port <= OFPP_MAX)
         {
           Port p = swtch->GetSwitchPort (port);
           if (p.netdev == 0)
             {
               continue;
             }
           ops = (ofp_port_stats*)ofpbuf_put_zeros (buffer, sizeof *ops);
           ops->port_no = htonl (swtch->GetSwitchPortIndex (p));
           ops->rx_packets   = htonll (p.rx_packets);
           ops->tx_packets   = htonll (p.tx_packets);
           ops->rx_bytes     = htonll (p.rx_bytes);
           ops->tx_bytes     = htonll (p.tx_bytes);
           ops->rx_dropped   = htonll (-1);
           ops->tx_dropped   = htonll (p.tx_dropped);
           ops->rx_errors    = htonll (-1);
           ops->tx_errors    = htonll (-1);
           ops->rx_frame_err = htonll (-1);
           ops->rx_over_err  = htonll (-1);
           ops->rx_crc_err   = htonll (-1);
           ops->collisions   = htonll (-1);
           ops->mpls_ttl0_dropped = htonll (p.mpls_ttl0_dropped);
           ops++;
         }
       else if (port >= OFPP_VP_START && port <= OFPP_VP_END) // virtual port?
         {
           // lookup the virtual port
           vport_table_t vt = swtch->GetVPortTable ();
           vport_table_entry *vpe = vport_table_lookup (&vt, port);
           if (vpe == 0)
             {
                   OF_IFACE_DUMP (cout << "vport entry not found!" << endl);
               continue;
             }
           // only tx_packets and tx_bytes are really relevant for virtual ports
           ops = (ofp_port_stats*)ofpbuf_put_zeros (buffer, sizeof *ops);
           ops->port_no = htonl (vpe->vport);
           ops->rx_packets   = htonll (-1);
           ops->tx_packets   = htonll (vpe->packet_count);
           ops->rx_bytes     = htonll (-1);
           ops->tx_bytes     = htonll (vpe->byte_count);
           ops->rx_dropped   = htonll (-1);
           ops->tx_dropped   = htonll (-1);
           ops->rx_errors    = htonll (-1);
           ops->tx_errors    = htonll (-1);
           ops->rx_frame_err = htonll (-1);
           ops->rx_over_err  = htonll (-1);
           ops->rx_crc_err   = htonll (-1);
           ops->collisions   = htonll (-1);
           ops->mpls_ttl0_dropped = htonll (-1);
           ops++;
         }
     }
   return 0;
 }
int s3f::s3fnet::Stats::PortTableStatsDump (OpenFlowSwitchSession * dp, void * state, ofpbuf * buffer) private
Definition at line 275 of file openflow_interface.cc.
References s3f::s3fnet::OpenFlowSwitchSession::GetVPortTable().
Referenced by DoDump().
 {
   ofp_vport_table_stats *opts = (ofp_vport_table_stats*)ofpbuf_put_zeros (buffer, sizeof *opts);
   opts->max_vports = htonl (swtch->GetVPortTable ().max_vports);
   opts->active_vports = htonl (swtch->GetVPortTable ().active_vports);
   opts->lookup_count = htonll (swtch->GetVPortTable ().lookup_count);
   opts->port_match_count = htonll (swtch->GetVPortTable ().port_match_count);
   opts->chain_match_count = htonll (swtch->GetVPortTable ().chain_match_count);
   return 0;
 }
Member Data Documentation
ofp_stats_types s3f::s3fnet::Stats::type
Definition at line 187 of file openflow_interface.h.
Referenced by DoCleanup(), DoDump(), DoInit(), Stats(), and s3f::s3fnet::OpenFlowSwitchSession::StatsDump().
int(* s3f::s3fnet::Stats::FlowDumpCallback)(sw_flow *flow, void *state) private
Definition at line 192 of file openflow_interface.h.
Referenced by FlowStatsDump().
int(* s3f::s3fnet::Stats::AggregateDumpCallback)(sw_flow *flow, void *state) private
Definition at line 196 of file openflow_interface.h.
Referenced by AggregateStatsDump().
The documentation for this class was generated from the following files:
openflow_interface.h
openflow_interface.cc