S3F: s3f::s3fnet::Traffic Class Reference
s3f::s3fnet::Traffic Class Reference
Specification of traffic in DML.
#include <traffic.h>
Public Types
typedef
TRAFFIC_PATTERN_LIST::iterator TRAFFIC_PATTERN_LIST_ITERATOR
Public Member Functions
typedef S3FNET_LIST (TrafficPattern *) TRAFFIC_PATTERN_LIST
Traffic (Net *net)
The constructor.
virtual ~Traffic ()
The destructor.
void config (s3f::dml::Configuration *cfg)
Configure traffic from DML.
void init ()
Initialize the traffic, primarily to resolve the nhi address in the traffic patterns.
virtual void display (int indent=0)
Print out information about this traffic object.
bool getServers (Host *host, S3FNET_VECTOR(TrafficServerData *)&servers, const char *list=NULL)
This function is meant to be called by a client protocol.
Protected Member Functions
void resolve_nhi ()
Resolve the client nhi addresses in the traffic patterns.
void release_patterns ()
Reclaim the space occupied by traffic patterns.
Private Attributes
Net * topnet
The top network that owns this traffic object.
TRAFFIC_PATTERN_LIST * patterns
List of traffic patterns.
Detailed Description
Specification of traffic in DML.
This class manages the traffic specification found in the outermost net attribute in the DML. The traffic specification maps the clients to servers with which they should establish connections. Application-layer client and server protocols should be able to access this traffic information and act upon it accordingly.
Definition at line 43 of file traffic.h.
Member Typedef Documentation
typedef TRAFFIC_PATTERN_LIST::iterator s3f::s3fnet::Traffic::TRAFFIC_PATTERN_LIST_ITERATOR
Definition at line 46 of file traffic.h.
Constructor & Destructor Documentation
s3f::s3fnet::Traffic::Traffic (Net * net)
The constructor.
Definition at line 26 of file traffic.cc.
References TRAFFIC_DUMP.
                          : topnet(net), patterns(0)
 {
     TRAFFIC_DUMP(printf("new traffic \n"));
 }
s3f::s3fnet::Traffic::~Traffic () virtual
The destructor.
Definition at line 31 of file traffic.cc.
References release_patterns().
 {
   // release traffic patterns when Traffic object is destroyed.
   release_patterns();
 }
Member Function Documentation
typedef s3f::s3fnet::Traffic::S3FNET_LIST (TrafficPattern *)
void s3f::s3fnet::Traffic::config (s3f::dml::Configuration * cfg)
Configure traffic from DML.
Definition at line 50 of file traffic.cc.
References s3f::s3fnet::TrafficPattern::config(), s3f::s3fnet::error_quit(), patterns, and TRAFFIC_PATTERN.
Referenced by s3f::s3fnet::Net::finish_config_top_net().
 {
   // find out traffic patterns defined
   s3f::dml::Enumeration* ss = cfg->find(TRAFFIC_PATTERN);
   while(ss->hasMoreElements())
   {
     // create and populate a traffic pattern
     TrafficPattern* pattern = new TrafficPattern;
     assert(pattern);
     s3f::dml::Configuration* pcfg = (s3f::dml::Configuration*)ss->nextElement();
     if(!s3f::dml::dmlConfig::isConf(pcfg))
       error_quit("ERROR: illegal TRAFFIC.PATTERN attribute.\n");
     pattern->config(pcfg);
     if(!patterns)
     {
       patterns = new TRAFFIC_PATTERN_LIST;
       assert(patterns);
     }
     // put the new pattern in the list
     patterns->push_back(pattern);
   }
   delete ss;
 }
void s3f::s3fnet::Traffic::init ()
Initialize the traffic, primarily to resolve the nhi address in the traffic patterns.
This method is called after the entire network has been read in and configured.
Definition at line 74 of file traffic.cc.
References resolve_nhi().
Referenced by s3f::s3fnet::Net::init().
 {
   resolve_nhi();
 }
void s3f::s3fnet::Traffic::display (int indent = 0) virtual
Print out information about this traffic object.
Definition at line 117 of file traffic.cc.
References DML_OBJECT_INDENT, and patterns.
 {
   printf("%*cTraffic [\n", indent, ' ');
   indent += DML_OBJECT_INDENT;
   // Display Patterns
   if(patterns) {
     for(TRAFFIC_PATTERN_LIST_ITERATOR it = patterns->begin();
         it != patterns->end(); it++) {
       if(*it) (*it)->display(indent);
     }
   }
   printf("%*c]\n", indent-DML_OBJECT_INDENT, ' ');
 }
bool s3f::s3fnet::Traffic::getServers (Host * host, S3FNET_VECTOR(TrafficServerData *)& servers, const char * list = NULL)
This function is meant to be called by a client protocol.
It will check if there's a match between the protocol's machine and the client specification in traffic patterns. If so, information the corresponding servers will be returned through the parameter as a vector of TrafficServerData objects. If list is not NULL, only servers that offering exactly the same type of service are returned. It is important to note that TrafficServerData objects belong to the system; the user shouldn't reclaim them.
Definition at line 133 of file traffic.cc.
References s3f::s3fnet::TrafficPattern::client, s3f::s3fnet::Nhi::contains(), s3f::s3fnet::DmlObject::nhi, patterns, and s3f::s3fnet::TrafficPattern::servers.
Referenced by s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), and s3f::s3fnet::BTCPClientSession::get_random_server().
 {
   if(!patterns) return false;
   bool found_match = false;
   for(TRAFFIC_PATTERN_LIST_ITERATOR it = patterns->begin();
       it != patterns->end(); it++) {
     TrafficPattern* pattern = *it;
     if(!pattern) continue;
     if(pattern->client.contains(host->nhi)) {
       for(unsigned j=0; j<pattern->servers.size(); j++) {
         if(!list || !pattern->servers[j]->list ||
            !strcasecmp(list, pattern->servers[j]->list)) {
           found_match = true;
           servers.push_back(pattern->servers[j]);
         }
       }
     }
   }
   return found_match;
 }
void s3f::s3fnet::Traffic::resolve_nhi () protected
Resolve the client nhi addresses in the traffic patterns.
Definition at line 79 of file traffic.cc.
References s3f::s3fnet::TrafficPattern::client, s3f::s3fnet::Net::nhi2obj(), s3f::s3fnet::Nhi::NHI_MACHINE, s3f::s3fnet::Nhi::NHI_NET, patterns, topnet, and s3f::s3fnet::Nhi::type.
Referenced by init().
 {
   // Now we will resolve each of the nhi's in the servers vector of
   // each pattern. This must be done after IP addresses have been
   // assigned to network interfaces.
   if(!patterns) return;
   for(TRAFFIC_PATTERN_LIST_ITERATOR it = patterns->begin(); it != patterns->end(); it++)
   {
     TrafficPattern* pattern = *it;
     // first, try to resolve the client's nhi address; we first try to
     // interpret the client address as a network nhi, if no, we try
     // machine nhi.
     bool is_success = false;
     int nhi_type = pattern->client.type;
     if(pattern->client.type & Nhi::NHI_NET)
     {
       pattern->client.type = Nhi::NHI_NET;
       if(topnet->nhi2obj(&pattern->client))
         is_success = true;
     }
     if(!is_success)
     {
       pattern->client.type = nhi_type;
       if(pattern->client.type & Nhi::NHI_MACHINE)
       {
         pattern->client.type = Nhi::NHI_MACHINE;
         if(topnet->nhi2obj(&pattern->client))
           is_success = true;
       }
     }
   }
 }
void s3f::s3fnet::Traffic::release_patterns () protected
Reclaim the space occupied by traffic patterns.
Definition at line 37 of file traffic.cc.
References patterns.
Referenced by ~Traffic().
 {
   if(!patterns) return;
   while(!patterns->empty()) {
     TrafficPattern* p = patterns->front();
     patterns->pop_front();
     delete p;
   }
   // finally, delete patterns
   delete patterns; patterns = 0;
 }
Member Data Documentation
Net* s3f::s3fnet::Traffic::topnet private
The top network that owns this traffic object.
Definition at line 90 of file traffic.h.
Referenced by resolve_nhi().
TRAFFIC_PATTERN_LIST* s3f::s3fnet::Traffic::patterns private
List of traffic patterns.
Definition at line 93 of file traffic.h.
Referenced by config(), display(), getServers(), release_patterns(), and resolve_nhi().
The documentation for this class was generated from the following files:
traffic.h
traffic.cc