S3F: s3f::s3fnet::Host Class Reference
s3f::s3fnet::Host Class Reference
A host or router or switch.
#include <host.h>
Public Member Functions
Host (Timeline *tl, Net *net, long id)
The constructor.
virtual ~Host ()
The destructor.
void listen (Activation pkt)
listen on all inChannels at NetworkInterfaces (binding) and send the arrived packet to the right network interface, one lisent_proc per host entity
virtual void config (s3f::dml::Configuration *cfg)
The config method is used to configure the host from DML.
virtual void init ()
The init method is used to initialize the host once it has been configured.
Net * inNet ()
Return the network containing this host.
Random::RNG * getRandom ()
Return the random number generator of this host.
int getHostSeed ()
The method returns the random seed of this host.
bool isRouter ()
Return true if this host is a router.
bool isOpenFlowSwitch ()
Return true if this host is an openflow switch.
bool isOpenVZEmu ()
Return true if this host supports OpenVZ-based Emulation.
ProtocolSession * getNetworkLayerProtocol ()
Return the network layer protocol (i.e., the IP protocol).
NetworkInterface * getNetworkInterface (int id)
Return network interface of the given id.
NetworkInterface * getNetworkInterfaceByIP (IPADDR ipaddr)
Return the network interface of this host that has the given IP address.
IPADDR getDefaultIP ()
Return the IP address of the first network interface.
void loadForwardingTable (s3f::dml::Configuration *cfg)
Load forwarding table from DML.
virtual void display (int indent=0)
Print out the name of this host.
char * getNowWithThousandSeparator ()
print out the current simulation time with thousand separator
Net * getTopNet ()
return the pointer of the top net
S3FNET_HOST_IFACE_MAP getNetworkInterfaceMap ()
Return the list of network interfaces associated to this host.
int getVEID ()
Return the VE's ID (OpenVZ VE) of this host.
ltime_t now ()
Time on Entity's Timeline, either the time at which the current (or most recent) event on the timeline was executed, or the end of the last synchronization window.
Timeline * alignment ()
Returns pointer to the Timeline on which this Entity is aligned.
HandleCode waitFor (Process *proc, Activation act, ltime_t waitinterval)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
HandleCode waitFor (Process *proc, ltime_t waitinterval)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
HandleCode waitFor (Process *proc, Activation act, ltime_t waitinterval, unsigned int)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
HandleCode waitFor (Process *proc, ltime_t waitinterval, unsigned int)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
HandleCode waitFor (Activation act, ltime_t waitinterval)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
HandleCode waitFor (ltime_t waitinterval)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
HandleCode waitFor (Activation act, ltime_t waitinterval, unsigned int)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
HandleCode waitFor (ltime_t waitinterval, unsigned int)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
unsigned int s3fid ()
Unique identifier for Entity, index 0 to total number of Entities created.
string getName ()
Return the text name ("" if none was given at initialization)
InChannel * getInChannel (string)
When an InChannel is create it can provide a text name, unique among InChannels on the same Entity.
Process * getProcess (string)
When a Process is create it can provide a text name, unique among Processes on the same Entity.
double t2d (ltime_t t)
Conversion routines to translate from clock ticks to double precision.
double t2d (ltime_t t, int s)
Conversion routines to translate from clock ticks to double precision.
ltime_t d2t (double d)
Conversion routines to translate from double precision to clock ticks.
ltime_t d2t (double d, int s)
Conversion routines to translate from double precision to clock ticks.
virtual void wrapup ()
The wrapup method is called at the end of the simulation.
ProtocolSession * sessionForName (char *pname)
If a protocol session has been created and registered under the given name, the method returns the protocol session.
ProtocolSession * sessionForNumber (int pno)
If a protocol session has been created and registered under the given protocol number, the method returns the protocol session.
Static Public Member Functions
static Entity * getEntity (string)
Directory look up of the Entity pointer, given its text name.
Public Attributes
Process * listen_proc
long tie_breaking_seed
unique number per host Used for ensuring the S3F event processing order is always deterministic, Last element used for tie breaking in case that other factors for determining the priority are the same (e.g., event timestamp) refer to S3F Entity::waitFor() for more info
bool is_of_ctrl
OpenFlowControllerSession * of_ctrl_sess
int of_ctrl_type
long id
Every DmlObject object must have an ID obtained from the DML.
Nhi nhi
The nhi address to identify the object.
DmlObject * myParent
The parent.
char * description
Optional string to describe the protocol graph.
Protected Member Functions
void config_network_interface (s3f::dml::Configuration *cfg, int id)
Configure a network interface.
void set_network_layer_protocol (ProtocolSession *ip)
This method is called to register the network protocol.
virtual Host * getHost ()
This is the virtual method defined in ProtocolGraph.
void BuildEntity (Timeline *)
The core of the Entity construction is done by BuildEntity.
ltime_t min_sync_cross_timeline_delay (ltime_t)
Among all outbound cross-timeline connections with OutChannels in this Entity, find the smallest min-delay that is at least as large as the argument.
ltime_t min_sync_all_timeline_delay (ltime_t)
Among all outbound connections with OutChannels in this Entity, find the smallest min-delay that is at least as large as the argument.
unsigned int count_min_delay_crossings (ltime_t)
Count the number of outbound cross-timeline connections with minimum delay at least as large as thrs.
ProtocolSession * config_session (s3f::dml::Configuration *cfg)
Internal use: to configure a protocol session.
void insert_session (ProtocolSession *psess)
Insert a protocol session to this protocol graph.
Protected Attributes
Random::RNG * rng
The random number generator, per host.
int host_seed
The seed of this host.
bool is_router
Whether this machine is a router.
bool is_of_switch
Whether this machine is an openflow switch.
bool is_switch
Whether this machine is a switch.
Nhi nhi_host
int veid
ID of the associated VE.
bool is_openVZEmu
whether the host is an openVZ emulation host
S3FNET_HOST_IFACE_MAP ifaces
The list of network interfaces.
ProtocolSession * network_prot
Point to the network protocol session.
char disp_now_buf [32]
string __name
text name given at initialization
Timeline * __timeline
pointer to Timeline on which this Entity is aligned
unsigned int __s3fid
Unique identity for Entity.
int __log_ticks_per_sec
time-scale of clock.
vector< OutChannel * > __outchannel_list
list of outchannels owned by this entity
vector< InChannel * > __inchannel_list
list of inchannels owned by this entity
vector< Process * > __process_list
list of processes owned by this entity
map< string, Process * > ProcessName
map< string, InChannel * > InChannelName
directory of inchannels declared with string names
pthread_mutex_t entity_inst_mutex
mutex for access to Entity instances state
S3FNET_GRAPH_PROTONAME_MAP pname_map
Mapping between protocol names and instances of protocol sessions.
S3FNET_GRAPH_PROTONUM_MAP pno_map
Mapping between protocol numbers and instances of protocol sessions.
S3FNET_GRAPH_PSESS_VECTOR protocol_list
List of protocol sessions created.
Static Protected Attributes
static double __pow [36]
pow[i] = 10^{i-18}.
static map< string, Entity * > EntityName
Entity text to Pointer Directory.
static pthread_mutex_t entity_class_mutex
Mutex that protects access to Entity state.
static unsigned int __num_entities = 0
counter of number of entities created
Detailed Description
A host or router or switch.
Definition at line 31 of file host.h.
Constructor & Destructor Documentation
s3f::s3fnet::Host::Host (Timeline * tl, Net * net, long id)
The constructor.
The parent DML object is the network containing the host.
Definition at line 25 of file host.cc.
References disp_now_buf, and HOST_DUMP.
                                                  : Entity(tl), DmlObject(parent, hostid),
                 host_seed(0), is_router(false), is_switch(false), network_prot(0), is_openVZEmu(false),
                 is_of_switch(false), is_of_ctrl(false), of_ctrl_sess(0), of_ctrl_type(1)
 {
         HOST_DUMP(printf("[id=%ld] new host.\n", id));
         int i;
         for(i=0; i<31; i++)
         {
                 disp_now_buf[i] = '0';
         }
         disp_now_buf[31]='\0';
 }
s3f::s3fnet::Host::~Host () virtual
The destructor.
Definition at line 38 of file host.cc.
References HOST_DUMP, ifaces, s3f::s3fnet::DmlObject::nhi, rng, and s3f::s3fnet::Nhi::toString().
 {
         HOST_DUMP(printf("[nhi=\"%s\"] delete host.\n", nhi.toString()));
         if(rng) delete rng;
         S3FNET_HOST_IFACE_MAP::iterator iter;
         for(iter = ifaces.begin(); iter != ifaces.end(); iter++)
                 delete (*iter).second;
 }
Member Function Documentation
void s3f::s3fnet::Host::listen (Activation pkt)
listen on all inChannels at NetworkInterfaces (binding) and send the arrived packet to the right network interface, one lisent_proc per host entity
Definition at line 235 of file host.cc.
References Process::activeChannel(), s3f::s3fnet::error_quit(), ifaces, listen_proc, s3f::s3fnet::NetworkInterface::receivePacket(), and InChannel::s3fid().
Referenced by init().
 {
         NetworkInterface* rcv_iface = 0;
         S3FNET_HOST_IFACE_MAP::iterator iter;
         for(iter=ifaces.begin(); iter!=ifaces.end(); ++iter)
         {
                 if( (*iter).second->ic->s3fid() == listen_proc->activeChannel()->s3fid() )
                 {
                         rcv_iface = (*iter).second;
                         break;
                 }
         }
         if(rcv_iface)
                 rcv_iface->receivePacket(pkt);
         else
                 error_quit("ERROR: received an activation not belong to any InChannels of this host.\n");
 }
void s3f::s3fnet::Host::config (s3f::dml::Configuration * cfg) virtual
The config method is used to configure the host from DML.
It is expected to be called first, right after the Host object is created and before the init method is called. A DML configuration should be passed as an argument to the method. Aside from configuring the host, the method also calls the config method of the base class (i.e., ProtocolGraph), and therefore configure the protocol graph (i.e., a stack of protocol sessions) on this host.
Reimplemented from s3f::s3fnet::ProtocolGraph.
Definition at line 49 of file host.cc.
References s3f::s3fnet::ProtocolGraph::config(), s3f::s3fnet::RouteInfo::config(), s3f::s3fnet::DMLRouteInfo::config(), config_network_interface(), s3f::s3fnet::ProtocolSession::control(), s3f::s3fnet::error_quit(), s3f::s3fnet::Net::getIdrangeLimits(), s3f::s3fnet::Net::getNameService(), s3f::s3fnet::Net::getTopNet(), HOST_DUMP, host_seed, s3f::s3fnet::DmlObject::id, ifaces, inNet(), s3f::s3fnet::ProtocolGraph::insert_session(), s3f::s3fnet::IP_CTRL_INSERT_DMLROUTE, s3f::s3fnet::IP_CTRL_INSERT_ROUTE, IP_PROTOCOL_CLASSNAME, IP_PROTOCOL_NAME, is_openVZEmu, s3f::s3fnet::DmlObject::myParent, s3f::s3fnet::ProtocolSession::name, NET_PROTOCOL_NAME, s3f::s3fnet::Protocols::newInstance(), s3f::s3fnet::DmlObject::nhi, s3f::s3fnet::Nhi::NHI_MACHINE, s3f::s3fnet::ProtocolSession::PSESS_CONFIGURED, s3f::s3fnet::ProtocolGraph::sessionForName(), set_network_layer_protocol(), SimCtrl::set_ve_nif(), s3f::s3fnet::sstrdup(), s3f::s3fnet::ProtocolSession::stage, s3f::s3fnet::Nhi::toStlString(), s3f::s3fnet::Nhi::toString(), s3f::s3fnet::Nhi::type, s3f::s3fnet::ProtocolSession::use, and veid.
Referenced by s3f::s3fnet::Net::config_host().
 {
         assert(cfg);
         nhi = myParent->nhi;
         nhi += id;
         nhi.type = Nhi::NHI_MACHINE;
         HOST_DUMP(printf("[nhi=\"%s\"] config().\n", nhi.toString()));
         NameService* namesvc = inNet()->getNameService();
         assert(namesvc);
         char* str = (char*)cfg->findSingle("veid");
         if(!str)
         {
                 veid = -1;
                 is_openVZEmu = false;
         }
         else
         {
                 if(s3f::dml::dmlConfig::isConf(str))
                         error_quit("ERROR: invalid veid attribute.\n");
                 veid = atoi(str);
                 is_openVZEmu = true;
                 if(veid < 0)
                         error_quit("ERROR: veid attribute must be a non-negative integer.\n");
         }
 #ifndef OPENVZ_EMULATION
         if(is_openVZEmu == true)
                 error_quit("ERROR: host's veid is set, but OPENVZ_EMULATION is undefined.\n");
 #endif
         HOST_DUMP(printf("nhi=\"%s\", veid=%d.\n", nhi.toString(), veid));
         HOST_DUMP(printf("[nhi=\"%s\"] register host.\n", nhi.toString()));
         dynamic_cast<Net*>(myParent)->register_host(this, S3FNET_STRING(nhi.toStlString()), is_openVZEmu);
         str = (char*)cfg->findSingle("rng_level");
         if(str)
         {
                 if(s3f::dml::dmlConfig::isConf(str))
                         error_quit("ERROR: Host::config(), invalid HOST.RNG_LEVEL attribute.\n");
                 if(!strcasecmp(str, "host"))
                         host_seed = 0;
                 else if(!strcasecmp(str, "protocol"))
                         host_seed = -1;
                 else
                         error_quit("ERROR: Host::config(), unknown HOST.RNG_LEVEL \"%s\".\n", str);
         }
         else //default is host-level
                 host_seed = 0;
         HOST_DUMP(printf("[nhi=\"%s\"] host_seed=%d.\n", nhi.toString(), host_seed));
         s3f::dml::Configuration* gcfg = (s3f::dml::Configuration*)cfg->findSingle("graph");
         if(!gcfg || !s3f::dml::dmlConfig::isConf(gcfg))
                 error_quit("ERROR: host::config(), invalid or missing HOST.GRAPH attribute.\n");
         ProtocolGraph::config(gcfg);
         ProtocolSession* ip = sessionForName(NET_PROTOCOL_NAME);
         if(!ip) ip = sessionForName(IP_PROTOCOL_NAME);
         if(!ip)
         {
                 // if the network protocol (IP) is undefined, we create a default ip session
                 ip = Protocols::newInstance(IP_PROTOCOL_CLASSNAME, this);
                 if(!ip) error_quit("ERROR: unregistered protocol \"%s\".\n", IP_PROTOCOL_CLASSNAME);
                 // no need to configure the default ip protocol session
                 ip->name = sstrdup(NET_PROTOCOL_NAME);
                 ip->use  = sstrdup(IP_PROTOCOL_CLASSNAME);
                 ip->stage = ProtocolSession::PSESS_CONFIGURED;
                 insert_session(ip);
         }
         set_network_layer_protocol(ip);
         s3f::dml::Enumeration* ss = cfg->find("interface");
         bool is_first_iface = true; //to ensure the interface start from 0 for openvz
         while(ss->hasMoreElements())
         {
                 s3f::dml::Configuration* icfg = (s3f::dml::Configuration*)ss->nextElement();
                 if(!s3f::dml::dmlConfig::isConf(icfg))
                         error_quit("ERROR: host::config(), invalid HOST.INTERFACE attribute.\n");
                 int low, high;
                 Net::getIdrangeLimits(icfg, low, high);
                 if(is_first_iface == true)
                 {
                         is_first_iface = false;
                         if(low !=0 && is_openVZEmu == true)
                                 error_quit("VE's interface must start from 0\n");
                 }
                 for(int i = low; i <= high; i++)
                         config_network_interface(icfg, i);
         }
         delete ss;
         if(ifaces.empty())
                 error_quit("ERROR: host::config(), no interface on host \"%s\".\n", nhi.toString());
         ss = cfg->find("route");
         while(ss->hasMoreElements())
         {
                 s3f::dml::Configuration* rcfg = (s3f::dml::Configuration*)ss->nextElement();
                 if(!s3f::dml::dmlConfig::isConf(rcfg))
                         error_quit("ERROR: host::config(), invalid HOST.ROUTE attribute.\n");
                 RouteInfo* route = new RouteInfo;
                 route->config(this, rcfg);
                 ip->control(IP_CTRL_INSERT_ROUTE, route, NULL);
                 HOST_DUMP(printf("[nhi=\"%s\"] install route.\n", nhi.toString()));
         }
         delete ss;
 #ifdef OPENVZ_EMULATION
         if(is_openVZEmu == true)
         {
                 int idbase = inNet()->getTopNet()->get_idbase();
                 SimCtrl* simCtrl = inNet()->getTopNet()->getSimCtrl();
                 //set #iface in VE
                 int return_code = simCtrl->set_ve_nif(idbase+veid, ifaces.size());
                 if(return_code != 0)
                 {
                         error_quit("Host::config(), simCtrl->set_ve_nif error, return code = %d\n", return_code);
                 }
         }
 #endif
         ss = cfg->find("nhi_route");
         while(ss->hasMoreElements())
         {
                 s3f::dml::Configuration* rcfg = (s3f::dml::Configuration*)ss->nextElement();
                 if(!s3f::dml::dmlConfig::isConf(rcfg))
                         error_quit("ERROR: host::config(), invalid HOST.NHI_ROUTE attribute.\n");
                 DMLRouteInfo* dml_route = new DMLRouteInfo;
                 dml_route->config(rcfg);
                 ip->control(IP_CTRL_INSERT_DMLROUTE, dml_route, NULL);
                 HOST_DUMP(printf("[nhi=\"%s\"] install dml route.\n", nhi.toString()));
         }
         delete ss;
 }
void s3f::s3fnet::Host::init () virtual
The init method is used to initialize the host once it has been configured.
The init method will initialize the interfaces and the random seed of this host. The method also calls the init method of base class (i.e., ProtocolGraph) and initializes all protocol sessions in the protocol graph.
Reimplemented from s3f::s3fnet::ProtocolGraph.
Definition at line 188 of file host.cc.
References Entity::alignment(), s3f::s3fnet::error_retn(), SimCtrl::get_vehandle(), s3f::s3fnet::Net::getTopNet(), HOST_DUMP, s3f::s3fnet::Nhi::ids, ifaces, s3f::s3fnet::ProtocolGraph::init(), inNet(), is_openVZEmu, listen(), listen_proc, s3f::s3fnet::DmlObject::nhi, Entity::Process, rng, tie_breaking_seed, VEHandle::tl, s3f::s3fnet::Nhi::toString(), and veid.
 {
         HOST_DUMP(printf("[nhi=\"%s\"] init().\n", nhi.toString()));
         if(ifaces.empty())
                 error_retn("WARNING: Host nhi=\"%s\" has no active interface.\n", nhi.toString());
         rng = new Random::RNG();
         ProtocolGraph::init();
         listen_proc = new Process( (Entity *)this, (void (s3f::Entity::*)(s3f::Activation))&Host::listen);
 #ifdef OPENVZ_EMULATION
         if(is_openVZEmu == true) //set the alignment in this VE's VEhandler, to support openVZ emulation lookahead
         {
                 int idbase = inNet()->getTopNet()->get_idbase();
                 SimCtrl* simCtrl = inNet()->getTopNet()->getSimCtrl();
                 assert(simCtrl);
                 VEHandle* vh = simCtrl->get_vehandle(idbase+veid);
                 assert(vh);
                 vh->tl = alignment();
         }
 #endif
         //init all network interfaces, and binding the "listen" process to the InChannels
         S3FNET_HOST_IFACE_MAP::iterator iter;
         for(iter = ifaces.begin(); iter != ifaces.end(); iter++)
         {
                 (*iter).second->init();
                 (*iter).second->ic->bind(listen_proc);
         }
         int nDigits;
         if(nhi.ids[1] == 0) nDigits = 1;
         else nDigits = (int)(floor(log10(abs(nhi.ids[1]))) + 1);
         tie_breaking_seed = (long)(nhi.ids[0]*pow(10.0, (double)max(6, nDigits)) + nhi.ids[1]);
 }
Net * s3f::s3fnet::Host::inNet ()
Return the network containing this host.
Definition at line 254 of file host.cc.
References s3f::s3fnet::DmlObject::myParent.
Referenced by s3f::s3fnet::NetworkInterface::config(), config(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), getDefaultIP(), s3f::s3fnet::DummySession::init(), init(), s3f::s3fnet::DMLRouteInfo::resolve(), and s3f::s3fnet::OpenFlowSwitchSession::SetController().
 {
         return dynamic_cast<Net*>(myParent);
 }
Random::RNG* s3f::s3fnet::Host::getRandom () inline
Return the random number generator of this host.
Definition at line 80 of file host.h.
Referenced by s3f::s3fnet::ProtocolSession::init().
 {return rng;}
int s3f::s3fnet::Host::getHostSeed () inline
The method returns the random seed of this host.
If it's zero, the protocol sessions on this host will share the same random stream; otherwise, each session (protocol) has its own random number generator.
Definition at line 87 of file host.h.
 { return host_seed; }
bool s3f::s3fnet::Host::isRouter () inline
Return true if this host is a router.
Definition at line 90 of file host.h.
Referenced by s3f::s3fnet::SimpleMac::pop().
 { return is_router; }
bool s3f::s3fnet::Host::isOpenFlowSwitch () inline
Return true if this host is an openflow switch.
Definition at line 93 of file host.h.
Referenced by s3f::s3fnet::SimpleMac::pop().
 { return is_of_switch; }
bool s3f::s3fnet::Host::isOpenVZEmu () inline
Return true if this host supports OpenVZ-based Emulation.
In particular, the DML file assign a veid to this host.
Definition at line 96 of file host.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::IPSession::handle_pop_pkt(), and s3f::s3fnet::OpenVZEventSession::pop().
 { return is_openVZEmu;}
ProtocolSession * s3f::s3fnet::Host::getNetworkLayerProtocol ()
Return the network layer protocol (i.e., the IP protocol).
There must be one and only one such protocol defined within each host or router. An error will be prompted if it is undefined.
Definition at line 296 of file host.cc.
References s3f::s3fnet::error_quit(), and network_prot.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::DummySession::init(), s3f::s3fnet::UDPMaster::init(), s3f::s3fnet::OpenVZEventSession::init(), s3f::s3fnet::TCPMaster::init(), and loadForwardingTable().
 {
         if(!network_prot)
         {
                 // this is impossible since a default ip protocol is always
                 // created if it's undefined in DML
                 error_quit("ERROR: network protocol session undefined.\n");
         }
         return network_prot;
 }
NetworkInterface * s3f::s3fnet::Host::getNetworkInterface (int id)
Return network interface of the given id.
NULL will be returned if it is not found. Note that this method can only be called after the config phase.
Definition at line 259 of file host.cc.
References ifaces.
Referenced by s3f::s3fnet::RouteInfo::config(), s3f::s3fnet::OpenFlowControllerSession::pop(), s3f::s3fnet::OpenFlowSwitchSession::pop(), s3f::s3fnet::IPSession::push(), and s3f::s3fnet::DMLRouteInfo::resolve().
 {
         S3FNET_HOST_IFACE_MAP::iterator iter;
         iter = ifaces.find(id);
         if(iter != ifaces.end()) return (*iter).second;
         else return 0;
 }
NetworkInterface * s3f::s3fnet::Host::getNetworkInterfaceByIP (IPADDR ipaddr)
Return the network interface of this host that has the given IP address.
NULL if it does not exist.
Definition at line 280 of file host.cc.
References ifaces.
 {
         for(S3FNET_HOST_IFACE_MAP::iterator iter = ifaces.begin();
                         iter != ifaces.end(); iter++)
         {
                 if((*iter).second->getIP() == ipaddr)
                         return (*iter).second;
         }
         return 0;
 }
IPADDR s3f::s3fnet::Host::getDefaultIP ()
Return the IP address of the first network interface.
Definition at line 274 of file host.cc.
References s3f::s3fnet::Net::getNameService(), inNet(), s3f::s3fnet::DmlObject::nhi, s3f::s3fnet::NameService::nhi2ip(), and s3f::s3fnet::Nhi::toStlString().
Referenced by s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPServerSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::TCPServerSession::init(), s3f::s3fnet::NBTCPClientSession::init(), s3f::s3fnet::BTCPClientSession::init(), and s3f::s3fnet::NBTCPServerSession::init().
 {
         NameService* namesvc = inNet()->getNameService();
         return namesvc->nhi2ip(nhi.toStlString());
 }
void s3f::s3fnet::Host::loadForwardingTable (s3f::dml::Configuration * cfg)
Load forwarding table from DML.
Definition at line 267 of file host.cc.
References s3f::s3fnet::ProtocolSession::control(), getNetworkLayerProtocol(), HOST_DUMP, s3f::s3fnet::IP_CTRL_LOAD_FORWARDING_TABLE, s3f::s3fnet::DmlObject::nhi, and s3f::s3fnet::Nhi::toString().
Referenced by s3f::s3fnet::Net::load_fwdtable().
 {
         HOST_DUMP(printf("[nhi=\"%s\"] load forwarding table.\n", nhi.toString()));
         getNetworkLayerProtocol()->control(IP_CTRL_LOAD_FORWARDING_TABLE, cfg, NULL);
 }
void s3f::s3fnet::Host::display (int indent = 0) virtual
Print out the name of this host.
Reimplemented from s3f::s3fnet::DmlObject.
Definition at line 291 of file host.cc.
 {
         printf("%*cHost %lu", indent, ' ', id);
 }
char * s3f::s3fnet::Host::getNowWithThousandSeparator ()
print out the current simulation time with thousand separator
Definition at line 316 of file host.cc.
References disp_now_buf, and Entity::now().
Referenced by s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::NetworkInterface::receivePacket(), and s3f::s3fnet::NetworkInterface::sendPacket().
 {
         char* buffer = disp_now_buf;
         char buffer_old[32]="";
         ltime_t r = 0;
         ltime_t t = now();
         r = t%1000;
         t = t/1000;
         sprintf(buffer, "%03ld", r);
         sprintf(buffer_old, "%s", buffer);
         while (t != 0)
         {
                 r = t%1000;
                 t = t/1000;
                 if(t!=0)
                         sprintf(buffer, "%03ld,%s", r, buffer_old);
                 else
                         sprintf(buffer, "%ld,%s", r, buffer_old);
                 sprintf(buffer_old, "%s", buffer);
         }
         return disp_now_buf;
 }
Net* s3f::s3fnet::Host::getTopNet () inline
return the pointer of the top net
Definition at line 126 of file host.h.
References s3f::s3fnet::Net::getTopNet().
Referenced by s3f::s3fnet::OpenVZEventSession::pop(), and s3f::s3fnet::SimpleMac::push().
 {return inNet()->getTopNet();}
S3FNET_HOST_IFACE_MAP s3f::s3fnet::Host::getNetworkInterfaceMap () inline
Return the list of network interfaces associated to this host.
Definition at line 129 of file host.h.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::init().
 {return ifaces;}
int s3f::s3fnet::Host::getVEID () inline
Return the VE's ID (OpenVZ VE) of this host.
Definition at line 132 of file host.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::NameService::ip2veid(), and s3f::s3fnet::OpenVZEventSession::pop().
 {return veid;}
void s3f::s3fnet::Host::config_network_interface (s3f::dml::Configuration * cfg, int id) protected
Configure a network interface.
Definition at line 227 of file host.cc.
References s3f::s3fnet::NetworkInterface::config(), HOST_DUMP, s3f::s3fnet::DmlObject::id, ifaces, s3f::s3fnet::DmlObject::nhi, S3FNET_MAKE_PAIR, and s3f::s3fnet::Nhi::toString().
Referenced by config().
 {
         HOST_DUMP(printf("[nhi=\"%s\"] new interface %d.\n", nhi.toString(), id));
         NetworkInterface* iface = new NetworkInterface(this, id);
         iface->config(cfg);
         ifaces.insert(S3FNET_MAKE_PAIR(id,iface));
 }
void s3f::s3fnet::Host::set_network_layer_protocol (ProtocolSession * ip) protected
This method is called to register the network protocol.
There must be one and only one such protocol defined within each host or router. An error will be prompted if there are more than one network protocols defined
Definition at line 307 of file host.cc.
References s3f::s3fnet::error_quit(), and network_prot.
Referenced by config().
 {
         if(network_prot)
         {
                 error_quit("ERROR: duplicate network protocol session defined.\n");
         }
         network_prot = np;
 }
virtual Host* s3f::s3fnet::Host::getHost () inline protected virtual
This is the virtual method defined in ProtocolGraph.
Here it returns a pointer to itself.
Definition at line 185 of file host.h.
 { return this; }
ltime_t Entity::now () inherited
Time on Entity's Timeline, either the time at which the current (or most recent) event on the timeline was executed, or the end of the last synchronization window.
Definition at line 111 of file entity.cc.
References Entity::__timeline, and Timeline::now().
Referenced by s3f::s3fnet::SocketMaster::abort(), s3f::s3fnet::NBSocketMaster::abort(), s3f::s3fnet::SocketMaster::accept(), s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::accept1a(), s3f::s3fnet::SocketMaster::accept1b(), s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SocketMaster::accept2b(), s3f::s3fnet::OpenFlowSwitchSession::AddFlow(), s3f::s3fnet::SocketMaster::bind(), s3f::s3fnet::NBSocketMaster::bind(), s3f::s3fnet::SocketMaster::block_till(), s3f::s3fnet::NBSocketMaster::block_till(), s3f::s3fnet::SocketMaster::close(), s3f::s3fnet::NBSocketMaster::close(), s3f::s3fnet::SocketMaster::close1(), s3f::s3fnet::NBSocketMaster::close1(), s3f::s3fnet::SocketMaster::connect(), s3f::s3fnet::NBSocketMaster::connect(), s3f::s3fnet::SocketMaster::connect1(), s3f::s3fnet::NBSocketMaster::connect1(), s3f::s3fnet::SocketMaster::connected(), s3f::s3fnet::NBSocketMaster::connected(), s3f::s3fnet::SocketMaster::control(), s3f::s3fnet::NBSocketMaster::control(), s3f::s3fnet::SocketMaster::eof(), s3f::s3fnet::NBSocketMaster::eof(), s3f::s3fnet::Stats::FlowStatsDump(), s3f::s3fnet::ProtocolSession::getNow(), getNowWithThousandSeparator(), pHold_Node::listen(), s3f::s3fnet::SocketMaster::listen(), s3f::s3fnet::NBSocketMaster::listen(), OutChannel::mapto(), OutChannel::new_min_write_delay(), s3f::s3fnet::OpenFlowSwitchSession::pop(), s3f::s3fnet::SocketMaster::recv(), s3f::s3fnet::NBSocketMaster::recv(), s3f::s3fnet::SocketMaster::recv1(), s3f::s3fnet::NBSocketMaster::recv1(), s3f::s3fnet::SocketMaster::send(), s3f::s3fnet::NBSocketMaster::send(), s3f::s3fnet::SocketMaster::send1(), s3f::s3fnet::NBSocketMaster::send1(), pHold_Node::talk(), Entity::waitFor(), and OutChannel::write().
 { return __timeline->now(); };
Timeline * Entity::alignment () inherited
Returns pointer to the Timeline on which this Entity is aligned.
Definition at line 120 of file entity.cc.
References Entity::__timeline.
Referenced by init(), OutChannel::mapto(), Process::Process(), Timeline::schedule(), Entity::waitFor(), and OutChannel::write().
 { return __timeline; }
HandleCode Entity::waitFor (Process * proc, Activation act, ltime_t waitinterval) inherited
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
The named process must be owned by an entity aligned to this timeline—checked by the Timeline::schedule method. A HandleCode object is returned, it can be used to cancel the scheduled activation. No priority is included, so Timeline::default_schedule_pri is used as a basis.
Parameters
waitinterval wait interval (from now) that S3F will process the activation.
act activation (event); If no Activation is included, one is created with NULL as the protected pointer.
proc The process to execute. Must be owned by an Entity that is co-aligned with this Entity. If no process in included, the default process of this Entity is used.
Definition at line 148 of file entity.cc.
References Entity::alignment(), Timeline::default_sched_pri, Entity::now(), Timeline::schedule(), and user_pri.
Referenced by s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::UDPServerSession::client_connected(), s3f::s3fnet::TCPMaster::enableFastTimeout(), s3f::s3fnet::TCPMaster::fast_timer_callback_body(), s3f::s3fnet::DummySession::init(), s3f::s3fnet::UDPServerSession::init(), s3f::s3fnet::TCPServerSession::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::NBTCPClientSession::init(), s3f::s3fnet::NBTCPServerSession::init(), s3f::s3fnet::OpenVZEventSession::injectEvent(), pHold_Node::listen(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), s3f::s3fnet::UDPClientSession::request_sent(), s3f::s3fnet::TCPClientSession::request_sent(), s3f::s3fnet::BTCPClientSession::server_connected(), and s3f::s3fnet::TCPMaster::slow_timer_callback_body().
{
       return alignment()->schedule( proc, now()+delay, user_pri(Timeline::default_sched_pri), act);
    }
HandleCode Entity::waitFor (Process * proc, ltime_t waitinterval) inherited
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
The named process must be owned by an entity aligned to this timeline—checked by the Timeline::schedule method. A HandleCode object is returned, it can be used to cancel the scheduled activation. No priority is included, so Timeline::default_schedule_pri is used as a basis. No Activation is included, so one is created with NULL as the protected pointer.
Parameters
waitinterval wait interval (from now) that S3F will process the activation.
proc The process to execute. Must be owned by an Entity that is co-aligned with this Entity. If no process in included, the default process of this Entity is used.
Definition at line 162 of file entity.cc.
References Entity::alignment(), Timeline::default_sched_pri, Entity::now(), Timeline::schedule(), and user_pri.
{
      Message* m = NULL;
      Activation act(m);
      return alignment()->schedule( proc, now()+delay, user_pri(Timeline::default_sched_pri), act);
    }
HandleCode Entity::waitFor (Process * proc, Activation act, ltime_t waitinterval, unsigned int pri) inherited
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
The named process must be owned by an entity aligned to this timeline—checked by the Timeline::schedule method. A HandleCode object is returned, it can be used to cancel the scheduled activation.
Parameters
waitinterval wait interval (from now) that S3F will process the activation.
act activation (event); If no Activation is included, one is created with NULL as the protected pointer.
proc The process to execute. Must be owned by an Entity that is co-aligned with this Entity. If no process in included, the default process of this Entity is used.
pri A tie-breaking priority. If no priority is included, Timeline::default_schedule_pri is used as a basis.
Definition at line 152 of file entity.cc.
References Entity::alignment(), Entity::now(), Timeline::schedule(), and user_pri.
{
       return alignment()->schedule( proc, now()+delay, user_pri(pri), act);
    }
HandleCode Entity::waitFor (Process * proc, ltime_t waitinterval, unsigned int pri) inherited
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
The named process must be owned by an entity aligned to this timeline—checked by the Timeline::schedule method. A HandleCode object is returned, it can be used to cancel the scheduled activation. No Activation is included, so one is created with NULL as the protected pointer.
Parameters
waitinterval wait interval (from now) that S3F will process the activation.
proc The process to execute. Must be owned by an Entity that is co-aligned with this Entity. If no process in included, the default process of this Entity is used.
pri A tie-breaking priority. If no priority is included, Timeline::default_schedule_pri is used as a basis.
Definition at line 156 of file entity.cc.
References Entity::alignment(), Entity::now(), Timeline::schedule(), and user_pri.
{
      Message* m = NULL;
      Activation act(m);
      return alignment()->schedule( proc, now()+delay, user_pri(pri), act);
    }
HandleCode Entity::waitFor (Activation act, ltime_t waitinterval) inherited
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
The named process must be owned by an entity aligned to this timeline—checked by the Timeline::schedule method. A HandleCode object is returned, it can be used to cancel the scheduled activation. No priority is included, so Timeline::default_schedule_pri is used as a basis. No process in included, so the default process of this Entity is used.
Parameters
waitinterval wait interval (from now) that S3F will process the activation.
act Activation (event); If no Activation is included, one is created with NULL as the protected pointer.
Definition at line 168 of file entity.cc.
References Entity::alignment(), Timeline::default_sched_pri, Entity::now(), Timeline::schedule(), and user_pri.
{
       return alignment()->schedule( alignment()->__this, now()+delay, user_pri(Timeline::default_sched_pri), act);
    }
HandleCode Entity::waitFor (ltime_t waitinterval) inherited
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
The named process must be owned by an entity aligned to this timeline—checked by the Timeline::schedule method. A HandleCode object is returned, it can be used to cancel the scheduled activation. No priority is included, so Timeline::default_schedule_pri is used as a basis. No process in included, so the default process of this Entity is used. No Activation is included, so one is created with NULL as the protected pointer.
Parameters
waitinterval wait interval (from now) that S3F will process the activation.
Definition at line 182 of file entity.cc.
References Entity::alignment(), Timeline::default_sched_pri, Entity::now(), Timeline::schedule(), and user_pri.
{
      Message* m = NULL;
      Activation act(m);
      return alignment()->schedule( alignment()->__this, now()+delay, user_pri(Timeline::default_sched_pri), act);
    }
HandleCode Entity::waitFor (Activation act, ltime_t waitinterval, unsigned int pri) inherited
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
The named process must be owned by an entity aligned to this timeline—checked by the Timeline::schedule method. A HandleCode object is returned, it can be used to cancel the scheduled activation. No process in included, so the default process of this Entity is used.
Parameters
waitinterval wait interval (from now) that S3F will process the activation.
act Activation (event); If no Activation is included, one is created with NULL as the protected pointer.
pri A tie-breaking priority. If no priority is included, Timeline::default_schedule_pri is used as a basis.
Definition at line 172 of file entity.cc.
References Entity::alignment(), Entity::now(), Timeline::schedule(), and user_pri.
{
       return alignment()->schedule( alignment()->__this, now()+delay, user_pri(pri), act);
    }
HandleCode Entity::waitFor (ltime_t waitinterval, unsigned int pri) inherited
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
The named process must be owned by an entity aligned to this timeline—checked by the Timeline::schedule method. A HandleCode object is returned, it can be used to cancel the scheduled activation. No process in included, so the default process of this Entity is used. No activation is included, so one is created with NULL as the protected pointer.
Parameters
waitinterval wait interval (from now) that S3F will process the activation.
pri A tie-breaking priority. If no priority is included, Timeline::default_schedule_pri is used as a basis.
Definition at line 176 of file entity.cc.
References Entity::alignment(), Entity::now(), Timeline::schedule(), and user_pri.
{
      Message* m = NULL;
      Activation act(m);
      return alignment()->schedule( alignment()->__this, now()+delay, user_pri(pri), act);
    }
unsigned int Entity::s3fid () inline inherited
Unique identifier for Entity, index 0 to total number of Entities created.
Definition at line 171 of file entity.h.
References Entity::__s3fid.
Referenced by pHold_Node::init(), and Entity::~Entity().
 { return __s3fid; }
string Entity::getName () inline inherited
Return the text name ("" if none was given at initialization)
Definition at line 187 of file entity.h.
References Entity::__name.
 { return __name;}
Entity * Entity::getEntity (string) static inherited
Directory look up of the Entity pointer, given its text name.
Definition at line 200 of file entity.cc.
References Entity::entity_class_mutex, and Entity::EntityName.
Referenced by pHold_Node::init().
{
         // protect global directory using entity class mutex
         pthread_mutex_lock(&entity_class_mutex);
         // look for the name in the directory.
         map<string,Entity*>::const_iterator itr
                 = EntityName.find(name);
         // if the iterator points to the end of the map we didn't find it
         if( itr == EntityName.end()) {
                         // make list available to others and return NULL
                         pthread_mutex_unlock(&entity_class_mutex);
                         return (Entity*) NULL;
         }
         // Entity found.  Make directory available to others and return the
         // pointer
         pthread_mutex_unlock(&entity_class_mutex);
         return (*itr).second;
  }
InChannel * Entity::getInChannel (string) inherited
When an InChannel is create it can provide a text name, unique among InChannels on the same Entity.
That name goes into a directory. This method retrieves the name, returning NULL if no associated mapping was found.
Definition at line 391 of file entity.cc.
References Entity::entity_inst_mutex, and Entity::InChannelName.
Referenced by pHold_Node::init().
{
     // off timeline entities may query this directory, so protect
     // access with a per-entity mutex.
         pthread_mutex_lock(&entity_inst_mutex);
         // see if we can find the named string
         map<string,InChannel*>::const_iterator itr = InChannelName.find(ic_name);
         // nope.  release the mutex and return NULL
         if( itr == InChannelName.end()) {
                         pthread_mutex_unlock(&entity_inst_mutex);
                         return (InChannel*) NULL;
         }
     // release the mutex and return the InChannel pointer
         pthread_mutex_unlock(&entity_inst_mutex);
         return (*itr).second;
 }
Process * Entity::getProcess (string) inherited
When a Process is create it can provide a text name, unique among Processes on the same Entity.
That name goes into a directory. This method retrieves the name, returning NULL if no associated mapping was found.
Definition at line 426 of file entity.cc.
References Entity::entity_inst_mutex, and Entity::ProcessName.
{
     // off timeline entities may query this directory, so protect
     // access with a per-entity mutex.
         pthread_mutex_lock(&entity_inst_mutex);
         // see if we can find the named string
         map<string,Process*>::const_iterator itr = ProcessName.find(p_name);
         // nope.  release the mutex and return NULL
         if( itr == ProcessName.end()) {
                         pthread_mutex_unlock(&entity_inst_mutex);
                         return (Process*) NULL;
         }
     // release the mutex and return the Process pointer
         pthread_mutex_unlock(&entity_inst_mutex);
         return (*itr).second;
 }
double Entity::t2d (ltime_t t) inherited
Conversion routines to translate from clock ticks to double precision.
Definition at line 257 of file entity.cc.
Referenced by s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::TCPMaster::enableFastTimeout(), s3f::s3fnet::TCPMaster::fast_timer_callback_body(), and s3f::s3fnet::TCPMaster::slow_timer_callback_body().
 { return (double)t; }
double Entity::t2d (ltime_t t, int s) inherited
Conversion routines to translate from clock ticks to double precision.
Parameters
t clock ticks input
s specify the units of the double precision input or output, in units of log_10(clock ticks per second). So, for example, if a double represents milliseconds, the s value is 3
Definition at line 262 of file entity.cc.
References Entity::__log_ticks_per_sec, and Entity::__pow.
{
         int scale = 18+(s-__log_ticks_per_sec);
         if(scale < 36 && scale>=0 ) return t*__pow[scale];
         return t*pow(10.0, scale-18);
   }
ltime_t Entity::d2t (double d) inherited
Conversion routines to translate from double precision to clock ticks.
Definition at line 269 of file entity.cc.
Referenced by s3f::s3fnet::TCPSession::backoff_timeout(), s3f::s3fnet::DroptailQueue::calibrate(), s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::DummySession::config(), s3f::s3fnet::TCPClientSession::config(), s3f::s3fnet::UDPServerSession::config(), s3f::s3fnet::SimplePhy::config(), s3f::s3fnet::UDPClientSession::config(), s3f::s3fnet::TCPMaster::config(), s3f::s3fnet::BTCPClientSession::config(), s3f::s3fnet::Link::connect(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::DroptailQueue::init(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::TCPSession::init_state_closed(), pHold_Node::listen(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), s3f::s3fnet::NetworkInterface::sendPacket(), s3f::s3fnet::TCPMaster::TCPMaster(), and s3f::s3fnet::TCPSession::update_timeout().
 { return (ltime_t)d; }
ltime_t Entity::d2t (double d, int s) inherited
Conversion routines to translate from double precision to clock ticks.
Parameters
d double input
s specify the units of the double precision input or output, in units of log_10(clock ticks per second). So, for example, if a double represents milliseconds, the s value is 3
Definition at line 274 of file entity.cc.
References Entity::__log_ticks_per_sec, and Entity::__pow.
{
         int scale = 18+(__log_ticks_per_sec-s);
         if(scale < 36 && scale>=0 ) return (ltime_t)round(d*__pow[scale]);
         else return (ltime_t)round(d*pow(10.0, scale-18));
   }
void Entity::BuildEntity (Timeline * tl) protected inherited
The core of the Entity construction is done by BuildEntity.
Finish constructing the Entity.
– save the Timeline pointer
– build the tables used to support tick - double precision conversion
– give the entity a unique name
– put the entity onto its Timeline's list of entities.
Definition at line 73 of file entity.cc.
References Timeline::__entity_list, Entity::__log_ticks_per_sec, Entity::__num_entities, Entity::__pow, Entity::__s3fid, Entity::__timeline, Entity::entity_class_mutex, Entity::entity_inst_mutex, Timeline::get_log_ticks_per_sec(), and Timeline::timeline_inst_mutex.
Referenced by Entity::Entity().
{
         // remember alignment, often used to check for cross-timeline connections
         __timeline = tl;
     // initialize the mutex used to serialize access to the individual
     // Entity state (not the static class variables).
     pthread_mutex_init(&entity_inst_mutex,NULL);
     // get unique Entity id. Global access so protect by mutex
         pthread_mutex_lock(&entity_class_mutex);
         __s3fid = __num_entities++;
         pthread_mutex_unlock(&entity_class_mutex);
         // first entity builds the pow[] table, used in tick - double precision conversion
         if( __s3fid == 0 ) {
                 for(int i=0; i<36; i++) __pow[i] = pow(10.0, (double)(i-18));
         }
         // copy time-scale information from the Timeline
         __log_ticks_per_sec = tl->get_log_ticks_per_sec();
         // record entity on timeline's list of entities
         pthread_mutex_lock(&tl->timeline_inst_mutex);
         tl->__entity_list.push_back(this);
         pthread_mutex_unlock(&tl->timeline_inst_mutex);
    }
ltime_t Entity::min_sync_cross_timeline_delay (ltime_t thrs) protected inherited
Among all outbound cross-timeline connections with OutChannels in this Entity, find the smallest min-delay that is at least as large as the argument.
Definition at line 289 of file entity.cc.
References Entity::__outchannel_list.
{
    // initialize search answer to "nothing here"
    ltime_t ans = -1;
    // buffer the minimum read up from a channel connection
    ltime_t ch_min;
    // length of the list of this entity's outchannels
    unsigned int end = __outchannel_list.size();
    // visit every one of the outchannels this entity owns
    for(unsigned int i=0; i<end; i++) {
         // ask it to provide the minimum cross timeline delay at least as
         // large as thrs, among all its mappings
         //
         ch_min = __outchannel_list[i]->min_sync_cross_timeline_delay(thrs);
         // save that value if it is no larger than thrs, AND either this is
         // first one we've seen, or its value is less than the smallest one
         // seen to date.
         //
         if( (-1 < ch_min) && thrs<=ch_min && ((ans<0) || (ch_min<ans))) ans = ch_min;
    }
    // final answer is in ans
    return ans;
  }
ltime_t Entity::min_sync_all_timeline_delay (ltime_t thrs) protected inherited
Among all outbound connections with OutChannels in this Entity, find the smallest min-delay that is at least as large as the argument.
Definition at line 318 of file entity.cc.
References Entity::__outchannel_list.
{
    // initialize search answer to "nothing here"
    ltime_t ans = -1;
    // buffer the minimum read up from a channel connection
    ltime_t ch_min;
    // length of the list of this entity's outchannels
    unsigned int end = __outchannel_list.size();
    // visit every one of the outchannels this entity owns
    for(unsigned int i=0; i<end; i++) {
         // ask it to provide the minimum cross timeline delay at least as
         // large as thrs, among all its mappings
         //
         ch_min = __outchannel_list[i]->min_sync_all_timeline_delay(thrs);
         // save that value if it is no larger than thrs, AND either this is
         // first one we've seen, or its value is less than the smallest one
         // seen to date.
         //
         if( (-1 < ch_min) && thrs<=ch_min && ((ans<0) || (ch_min<ans))) ans = ch_min;
    }
    // final answer is in ans
    return ans;
  }
unsigned int Entity::count_min_delay_crossings (ltime_t thrs) protected inherited
Count the number of outbound cross-timeline connections with minimum delay at least as large as thrs.
Definition at line 355 of file entity.cc.
References Entity::__outchannel_list.
{
   // initialize running sum
   unsigned int ans = 0;
   // number of OutChannels owned by this entity
   unsigned int end = __outchannel_list.size();
   // For each OutChannel as it to count the number of outbound
   // cross timeline connections with minimum delay less than or equal
   // to thrs
   //
   for(unsigned int i=0; i<end; i++) {
     ans += __outchannel_list[i]->count_min_delay_crossings(thrs);
   }
   // return accumulated sum
   return ans;
 }
void s3f::s3fnet::ProtocolGraph::wrapup () virtual inherited
The wrapup method is called at the end of the simulation.
It is used to collect statistical information of the simulation run. The wrapup method in turn calls the wrapup methods of all protocol sessions in the protocol graph. The order in which protocol sessions wrap up should NOT be expected!
Definition at line 65 of file protocol_graph.cc.
References s3f::s3fnet::ProtocolGraph::protocol_list.
 {
   // wrapup each protocol session
   for(S3FNET_GRAPH_PSESS_VECTOR::reverse_iterator iter = protocol_list.rbegin();
       iter != protocol_list.rend(); iter++)
   {
     if(!(*iter)->wrapped_up()) (*iter)->wrapup();
   }
 }
ProtocolSession * s3f::s3fnet::ProtocolGraph::sessionForName (char * pname) inherited
If a protocol session has been created and registered under the given name, the method returns the protocol session.
Otherwise, a NULL is returned.
Definition at line 75 of file protocol_graph.cc.
References s3f::s3fnet::ProtocolGraph::pname_map.
Referenced by s3f::s3fnet::SocketMaster::bind(), s3f::s3fnet::NBSocketMaster::bind(), s3f::s3fnet::NetworkInterface::config(), config(), s3f::s3fnet::UDPMaster::init(), and s3f::s3fnet::TCPMaster::init().
 {
   // return protocol session of the given name or NULL if not found
   S3FNET_GRAPH_PROTONAME_MAP::iterator iter;
   iter = pname_map.find(pname);
   if(iter != pname_map.end()) return (*iter).second;
   else return 0;
 }
ProtocolSession * s3f::s3fnet::ProtocolGraph::sessionForNumber (int pno) inherited
If a protocol session has been created and registered under the given protocol number, the method returns the protocol session.
Otherwise, a NULL is returned.
Definition at line 84 of file protocol_graph.cc.
References s3f::s3fnet::ProtocolGraph::pno_map.
Referenced by s3f::s3fnet::IPSession::get_parent_by_protocol(), s3f::s3fnet::NetworkInterface::init(), s3f::s3fnet::SimpleMac::pop(), and s3f::s3fnet::OpenFlowSwitchSession::SetController().
 {
   // return protocol session of the given name or NULL if not found
   S3FNET_GRAPH_PROTONUM_MAP::iterator iter = pno_map.find(pno);
   if(iter != pno_map.end()) return (*iter).second;
   else return 0;
 }
ProtocolSession * s3f::s3fnet::ProtocolGraph::config_session (s3f::dml::Configuration * cfg) protected inherited
Internal use: to configure a protocol session.
Definition at line 108 of file protocol_graph.cc.
References s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolGraph::insert_session(), and s3f::s3fnet::Protocols::newInstance().
Referenced by s3f::s3fnet::ProtocolGraph::config().
 {
   // find out session name from 'name' attribute
   char* str= (char*)cfg->findSingle("name");
   if(!str)
     error_quit("ERROR: session missing NAME attribute");
   if(s3f::dml::dmlConfig::isConf(str))
     error_quit("ERROR: invalid ProtocolSession.NAME.\n");
   S3FNET_STRING sessname = str;
   // find out class name from 'use' attribute
   char* classname = (char*)cfg->findSingle("use");
   if(!classname)
     error_quit("ERROR: session missing USE attribute");
   if(s3f::dml::dmlConfig::isConf(classname))
     error_quit("ERROR: invalid ProtocolSession.USE.\n");
   // classname is not copied from dml library, so it's temporary
   // valid until the next dml query!
   // create a new protocol session
   ProtocolSession* psess = Protocols::newInstance(classname, this);
   if(!psess)
   {
     error_quit("ERROR: failed to create protocol \"%s\".\n", classname);
   }
   // configure the protocol session
   psess->config(cfg);
   insert_session(psess);
   return psess;
 }
void s3f::s3fnet::ProtocolGraph::insert_session (ProtocolSession * psess) protected inherited
Insert a protocol session to this protocol graph.
Definition at line 141 of file protocol_graph.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolSession::getProtocolNumber(), s3f::s3fnet::ProtocolSession::instantiation_type(), s3f::s3fnet::ProtocolSession::name, s3f::s3fnet::ProtocolGraph::pname_map, s3f::s3fnet::ProtocolGraph::pno_map, s3f::s3fnet::ProtocolSession::PROT_MULTIPLE_INSTANCES, s3f::s3fnet::ProtocolSession::PROT_UNIQUE_INSTANCE, s3f::s3fnet::ProtocolGraph::protocol_list, S3FNET_MAKE_PAIR, S3FNET_PAIR, and s3f::s3fnet::ProtocolSession::use.
Referenced by s3f::s3fnet::NetworkInterface::config(), config(), and s3f::s3fnet::ProtocolGraph::config_session().
 {
   S3FNET_PAIR(S3FNET_GRAPH_PROTONAME_MAP::iterator, bool) ret0 =
     pname_map.insert(S3FNET_MAKE_PAIR(S3FNET_STRING(psess->name), psess));
   if(!ret0.second)
   {
     if(psess->instantiation_type() == ProtocolSession::PROT_UNIQUE_INSTANCE)
       error_quit("ERROR: protocol session \"%s\" only allows unique instance.\n", psess->use);
     else if(psess->instantiation_type() == ProtocolSession::PROT_MULTIPLE_INSTANCES &&
             strcasecmp((*ret0.first).second->use, psess->use))
       error_quit("ERROR: protocol session \"%s\" allows multiple instances of the same implementation.\n", psess->use);
   }
   int sno = psess->getProtocolNumber();
   S3FNET_PAIR(S3FNET_GRAPH_PROTONUM_MAP::iterator, bool) ret1 = pno_map.insert(S3FNET_MAKE_PAIR(sno, psess));
   if(!ret1.second)
   {
     if(psess->instantiation_type() == ProtocolSession::PROT_UNIQUE_INSTANCE)
       error_quit("ERROR: protocol session \"%s\" only allows unique instance.\n", psess->use);
     else if(psess->instantiation_type() == ProtocolSession::PROT_MULTIPLE_INSTANCES &&
             strcasecmp((*ret1.first).second->use, psess->use))
       error_quit("ERROR: protocol session \"%s\" allows multiple instances of the same implementation.\n", psess->use);
   }
   protocol_list.push_back(psess);
 }
Member Data Documentation
Process* s3f::s3fnet::Host::listen_proc
Definition at line 43 of file host.h.
Referenced by init(), and listen().
long s3f::s3fnet::Host::tie_breaking_seed
unique number per host Used for ensuring the S3F event processing order is always deterministic, Last element used for tie breaking in case that other factors for determining the priority are the same (e.g., event timestamp) refer to S3F Entity::waitFor() for more info
Definition at line 54 of file host.h.
Referenced by s3f::s3fnet::TCPMaster::enableFastTimeout(), s3f::s3fnet::DummySession::init(), s3f::s3fnet::TCPMaster::init(), init(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), and s3f::s3fnet::NetworkInterface::sendPacket().
bool s3f::s3fnet::Host::is_of_ctrl
Definition at line 134 of file host.h.
Referenced by s3f::s3fnet::OpenFlowControllerSession::init().
OpenFlowControllerSession* s3f::s3fnet::Host::of_ctrl_sess
Definition at line 135 of file host.h.
Referenced by s3f::s3fnet::NetworkInterface::handle_openflow_message_to_controller(), and s3f::s3fnet::OpenFlowControllerSession::init().
int s3f::s3fnet::Host::of_ctrl_type
Definition at line 136 of file host.h.
Random::RNG* s3f::s3fnet::Host::rng protected
The random number generator, per host.
Each host is expected to maintain a unique random stream, seeded initially as a function of the host id.
Definition at line 144 of file host.h.
Referenced by init(), and ~Host().
int s3f::s3fnet::Host::host_seed protected
The seed of this host.
If the seed is 0, it means that all the protocols on the host share a single random stream. Otherwise, each session (protocol) has its own random number generator.
Definition at line 151 of file host.h.
Referenced by config().
bool s3f::s3fnet::Host::is_router protected
Whether this machine is a router.
Definition at line 154 of file host.h.
Referenced by s3f::s3fnet::Net::config_host().
bool s3f::s3fnet::Host::is_of_switch protected
Whether this machine is an openflow switch.
Definition at line 157 of file host.h.
Referenced by s3f::s3fnet::Net::config_host().
bool s3f::s3fnet::Host::is_switch protected
Whether this machine is a switch.
Definition at line 160 of file host.h.
Nhi s3f::s3fnet::Host::nhi_host protected
Definition at line 162 of file host.h.
int s3f::s3fnet::Host::veid protected
ID of the associated VE.
Definition at line 165 of file host.h.
Referenced by config(), init(), and s3f::s3fnet::Net::register_host().
bool s3f::s3fnet::Host::is_openVZEmu protected
whether the host is an openVZ emulation host
Definition at line 166 of file host.h.
Referenced by config(), and init().
S3FNET_HOST_IFACE_MAP s3f::s3fnet::Host::ifaces protected
The list of network interfaces.
Definition at line 169 of file host.h.
Referenced by config(), config_network_interface(), getNetworkInterface(), getNetworkInterfaceByIP(), init(), listen(), and ~Host().
ProtocolSession* s3f::s3fnet::Host::network_prot protected
Point to the network protocol session.
Definition at line 172 of file host.h.
Referenced by getNetworkLayerProtocol(), and set_network_layer_protocol().
char s3f::s3fnet::Host::disp_now_buf[32] protected
Definition at line 187 of file host.h.
Referenced by getNowWithThousandSeparator(), and Host().
string Entity::__name protected inherited
text name given at initialization
Definition at line 267 of file entity.h.
Referenced by Entity::getName().
Timeline* Entity::__timeline protected inherited
pointer to Timeline on which this Entity is aligned
Definition at line 268 of file entity.h.
Referenced by Entity::alignment(), Entity::BuildEntity(), and Entity::now().
unsigned int Entity::__s3fid protected inherited
Unique identity for Entity.
Definition at line 269 of file entity.h.
Referenced by Entity::BuildEntity(), and Entity::s3fid().
double Entity::__pow static protected inherited
pow[i] = 10^{i-18}.
Used in time scale transformation
Definition at line 273 of file entity.h.
Referenced by Entity::BuildEntity(), Entity::d2t(), and Entity::t2d().
int Entity::__log_ticks_per_sec protected inherited
time-scale of clock.
Obtained from timeline when the entity is created.
Definition at line 275 of file entity.h.
Referenced by Entity::BuildEntity(), Entity::d2t(), and Entity::t2d().
vector<OutChannel*> Entity::__outchannel_list protected inherited
list of outchannels owned by this entity
Definition at line 279 of file entity.h.
Referenced by Entity::count_min_delay_crossings(), Timeline::initialize_appt(), Entity::min_sync_all_timeline_delay(), Entity::min_sync_cross_timeline_delay(), and OutChannel::OutChannel().
vector<InChannel*> Entity::__inchannel_list protected inherited
list of inchannels owned by this entity
Definition at line 280 of file entity.h.
Referenced by InChannel::InChannel().
vector<Process*> Entity::__process_list protected inherited
list of processes owned by this entity
Definition at line 281 of file entity.h.
Referenced by Process::Process().
map<string,Process*> Entity::ProcessName protected inherited
Definition at line 284 of file entity.h.
Referenced by Entity::getProcess().
map<string,InChannel*> Entity::InChannelName protected inherited
directory of inchannels declared with string names
Definition at line 285 of file entity.h.
Referenced by Entity::getInChannel().
pthread_mutex_t Entity::entity_inst_mutex protected inherited
mutex for access to Entity instances state
Definition at line 288 of file entity.h.
Referenced by Entity::BuildEntity(), Entity::getInChannel(), Entity::getProcess(), InChannel::InChannel(), OutChannel::OutChannel(), Process::Process(), and Entity::~Entity().
map< string, Entity * > Entity::EntityName static protected inherited
Entity text to Pointer Directory.
Definition at line 293 of file entity.h.
Referenced by Entity::getEntity().
pthread_mutex_t Entity::entity_class_mutex static protected inherited
Mutex that protects access to Entity state.
Definition at line 296 of file entity.h.
Referenced by Entity::BuildEntity(), Entity::getEntity(), and Interface::Interface().
unsigned int Entity::__num_entities = 0 static protected inherited
counter of number of entities created
Definition at line 299 of file entity.h.
Referenced by Entity::BuildEntity().
long s3f::s3fnet::DmlObject::id inherited
Every DmlObject object must have an ID obtained from the DML.
Definition at line 44 of file dmlobj.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), config(), s3f::s3fnet::Net::config(), config_network_interface(), s3f::s3fnet::RouteInfo::display(), and s3f::s3fnet::NetworkInterface::emu_packet_modify_iface().
Nhi s3f::s3fnet::DmlObject::nhi inherited
The nhi address to identify the object.
Definition at line 47 of file dmlobj.h.
Referenced by s3f::s3fnet::UDPSession::abort(), s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::Link::config(), s3f::s3fnet::NetworkInterface::config(), config(), s3f::s3fnet::RouteInfo::config(), s3f::s3fnet::Net::config(), config_network_interface(), s3f::s3fnet::UDPSession::connect(), s3f::s3fnet::Net::connect_links(), s3f::s3fnet::UDPSession::disconnect(), s3f::s3fnet::Link::display(), s3f::s3fnet::Net::display(), s3f::s3fnet::UDPClientSessionContinuation::failure(), s3f::s3fnet::UDPServerSessionContinuation::failure(), s3f::s3fnet::TCPServerSessionContinuation::failure(), s3f::s3fnet::TCPClientSessionContinuation::failure(), s3f::s3fnet::BTCPClientSessionContinuation::failure(), getDefaultIP(), s3f::s3fnet::Traffic::getServers(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), s3f::s3fnet::NetworkInterface::init(), init(), s3f::s3fnet::Net::init(), s3f::s3fnet::UDPSession::listen(), loadForwardingTable(), s3f::s3fnet::LearningController::process_recv_packet(), s3f::s3fnet::UDPSession::receive(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::LearningControllerSession::ReceiveFromSwitch(), s3f::s3fnet::NetworkInterface::receivePacket(), s3f::s3fnet::Net::register_host(), s3f::s3fnet::RouteInfo::resolve(), s3f::s3fnet::DMLRouteInfo::resolve(), s3f::s3fnet::NBTCPClientSessionContinuation::resume(), s3f::s3fnet::NBTCPServerSessionContinuation::resume(), s3f::s3fnet::UDPSession::send(), s3f::s3fnet::TCPSession::send_data(), s3f::s3fnet::NetworkInterface::sendPacket(), s3f::s3fnet::UDPSession::setSource(), s3f::s3fnet::TCPSession::slowTimeoutHandling(), s3f::s3fnet::NBTCPServerSessionContinuation::success(), s3f::s3fnet::TCPSession::TCPSession(), s3f::s3fnet::UDPSession::UDPSession(), s3f::s3fnet::TCPSession::update_timeout(), s3f::s3fnet::UDPSession::wake_app(), ~Host(), s3f::s3fnet::Net::~Net(), and s3f::s3fnet::NetworkInterface::~NetworkInterface().
DmlObject* s3f::s3fnet::DmlObject::myParent inherited
The parent.
DML objects are nested.
Definition at line 50 of file dmlobj.h.
Referenced by s3f::s3fnet::Link::config(), s3f::s3fnet::NetworkInterface::config(), config(), s3f::s3fnet::Net::config(), s3f::s3fnet::Link::connect(), s3f::s3fnet::Net::control(), s3f::s3fnet::NetworkInterface::getHost(), s3f::s3fnet::Net::init(), inNet(), s3f::s3fnet::NetworkInterface::NetworkInterface(), and s3f::s3fnet::DMLRouteInfo::resolve().
char* s3f::s3fnet::ProtocolGraph::description inherited
Optional string to describe the protocol graph.
The string is NULL if the DML 'graph' attribute does not contain a 'description' attribute.
Definition at line 43 of file protocol_graph.h.
Referenced by s3f::s3fnet::ProtocolGraph::config(), and s3f::s3fnet::ProtocolGraph::~ProtocolGraph().
S3FNET_GRAPH_PROTONAME_MAP s3f::s3fnet::ProtocolGraph::pname_map protected inherited
Mapping between protocol names and instances of protocol sessions.
Definition at line 108 of file protocol_graph.h.
Referenced by s3f::s3fnet::ProtocolGraph::config(), s3f::s3fnet::ProtocolGraph::insert_session(), and s3f::s3fnet::ProtocolGraph::sessionForName().
S3FNET_GRAPH_PROTONUM_MAP s3f::s3fnet::ProtocolGraph::pno_map protected inherited
Mapping between protocol numbers and instances of protocol sessions.
Definition at line 111 of file protocol_graph.h.
Referenced by s3f::s3fnet::ProtocolGraph::insert_session(), and s3f::s3fnet::ProtocolGraph::sessionForNumber().
S3FNET_GRAPH_PSESS_VECTOR s3f::s3fnet::ProtocolGraph::protocol_list protected inherited
List of protocol sessions created.
Definition at line 114 of file protocol_graph.h.
Referenced by s3f::s3fnet::ProtocolGraph::init(), s3f::s3fnet::ProtocolGraph::insert_session(), s3f::s3fnet::ProtocolGraph::wrapup(), and s3f::s3fnet::ProtocolGraph::~ProtocolGraph().
The documentation for this class was generated from the following files:
host.h
host.cc