S3F: s3f::s3fnet::ProtocolGraph Class Reference
s3f::s3fnet::ProtocolGraph Class Reference
A stack of protocol sessions.
#include <protocol_graph.h>
Public Member Functions
virtual void config (s3f::dml::Configuration *cfg)
The config method is used to configure the protocol graph.
virtual void init ()
The init method is used to initialize the protocol graph once it has been configured.
virtual void wrapup ()
The wrapup method is called at the end of the simulation.
ProtocolSession * sessionForName (char *pname)
If a protocol session has been created and registered under the given name, the method returns the protocol session.
ProtocolSession * sessionForNumber (int pno)
If a protocol session has been created and registered under the given protocol number, the method returns the protocol session.
Public Attributes
char * description
Optional string to describe the protocol graph.
Protected Member Functions
ProtocolGraph ()
The constructor.
virtual ~ProtocolGraph ()
The destructor.
ProtocolSession * config_session (s3f::dml::Configuration *cfg)
Internal use: to configure a protocol session.
void insert_session (ProtocolSession *psess)
Insert a protocol session to this protocol graph.
Protected Attributes
S3FNET_GRAPH_PROTONAME_MAP pname_map
Mapping between protocol names and instances of protocol sessions.
S3FNET_GRAPH_PROTONUM_MAP pno_map
Mapping between protocol numbers and instances of protocol sessions.
S3FNET_GRAPH_PSESS_VECTOR protocol_list
List of protocol sessions created.
Detailed Description
A stack of protocol sessions.
The ProtocolGraph class represents a protocol graph, which is an abstraction of the protocol stack in a node, in a fashion similar to the ISO/OSI stack model. A protocol graph maintains a list of protocol sessions, representing protocols running at different layers. It serves as a container for the protocol sessions.
Definition at line 34 of file protocol_graph.h.
Constructor & Destructor Documentation
s3f::s3fnet::ProtocolGraph::ProtocolGraph () protected
The constructor.
Definition at line 92 of file protocol_graph.cc.
                              :
   // initialize the object accordingly
   description(0)
 {}
s3f::s3fnet::ProtocolGraph::~ProtocolGraph () protected virtual
The destructor.
Definition at line 97 of file protocol_graph.cc.
References description, and protocol_list.
 {
   // reclaim everything
   if(description) delete description;
   for(int i=protocol_list.size()-1; i>=0; i--)
   {
     ProtocolSession* ps = protocol_list[i];
     delete ps;
   }
 }
Member Function Documentation
void s3f::s3fnet::ProtocolGraph::config (s3f::dml::Configuration * cfg) virtual
The config method is used to configure the protocol graph.
It is expected to be called first, right after the ProtocolGraph object is created and before the init method is called. A DML configuration should be passed as an argument to the method and it should be the value (a list of attributes) of a 'graph' attribute. An example of the DML configuration is given as follows:
    graph [
      ProtocolSession [ name "protocol name" using "class name" ... ]
      ...
    ]
    interface [ id 0
      ProtocolSession [ name "mac" using "mac class name" ... ]
      ProtocolSession [ name "phy" using "phy class name" ... ]
    ]
    interface [ id 1 ... ]
The config method will configure each protocol session in the protocol graph, represented by the 'session' attribute. Also, the method will search for global attributes '.graph.session' and instantiate each of the protocol sessions if it hasn't been created. The network interface is configured by 'interface' attribute, which optionally contain another list of protocol sessions, namely the MAC session and the PHY session.
Reimplemented in s3f::s3fnet::Host, and s3f::s3fnet::NetworkInterface.
Definition at line 16 of file protocol_graph.cc.
References config_session(), description, s3f::s3fnet::error_quit(), pname_map, and s3f::s3fnet::sstrdup().
Referenced by s3f::s3fnet::NetworkInterface::config(), and s3f::s3fnet::Host::config().
 {
   // find 'description'
   char* desc = (char*)cfg->findSingle("description");
   if(desc) description = sstrdup(desc);
   // create & configure each 'ProtocolSession'
   s3f::dml::Enumeration* ss = cfg->find("ProtocolSession");
   while(ss->hasMoreElements())
   {
     s3f::dml::Configuration* scfg = (s3f::dml::Configuration*)ss->nextElement();
     if(!s3f::dml::dmlConfig::isConf(scfg))
       error_quit("ERROR: invalid GRAPH.ProtocolSession attribute.\n");
     config_session(scfg);
   }
   delete ss;
   // create & configure each '.global.session' if not yet created
   ss = cfg->find(".global.session");
   while(ss->hasMoreElements())
   {
     s3f::dml::Configuration* ds = (s3f::dml::Configuration*)ss->nextElement();
     if(!s3f::dml::dmlConfig::isConf(ds))
       error_quit("ERROR: invalid .GLOBAL.SESSION attribute.\n");
     char* dn = (char*)ds->findSingle("name");
     if(dn && s3f::dml::dmlConfig::isConf(dn))
       error_quit("ERROR: invalid .GLOBAL.SESSION.NAME attribute.\n");
     if(dn && pname_map.find(dn) != pname_map.end())
     {
       config_session(ds);
     }
   }
   delete ss;
 }
void s3f::s3fnet::ProtocolGraph::init () virtual
The init method is used to initialize the protocol graph once it has been configured.
The init method will call init methods of all protocol sessions in the protocol graph. The order in which protocol sessions are initialized should NOT be expected!
Reimplemented in s3f::s3fnet::Host, and s3f::s3fnet::NetworkInterface.
Definition at line 51 of file protocol_graph.cc.
References protocol_list.
Referenced by s3f::s3fnet::NetworkInterface::init(), and s3f::s3fnet::Host::init().
 {
   // Initialize each protocol session: the order in which protocol
   // sessions are initialized in this case is that the last 'session'
   // defined in 'graph' attribute goes first, although it's after
   // those protocol sessions defined with '.global.session'.
   // The ordering should not be used by any protocol session!
   for(S3FNET_GRAPH_PSESS_VECTOR::reverse_iterator iter = protocol_list.rbegin();
       iter != protocol_list.rend(); iter++)
   {
     if(!(*iter)->initialized()) (*iter)->init();
   }
 }
void s3f::s3fnet::ProtocolGraph::wrapup () virtual
The wrapup method is called at the end of the simulation.
It is used to collect statistical information of the simulation run. The wrapup method in turn calls the wrapup methods of all protocol sessions in the protocol graph. The order in which protocol sessions wrap up should NOT be expected!
Definition at line 65 of file protocol_graph.cc.
References protocol_list.
 {
   // wrapup each protocol session
   for(S3FNET_GRAPH_PSESS_VECTOR::reverse_iterator iter = protocol_list.rbegin();
       iter != protocol_list.rend(); iter++)
   {
     if(!(*iter)->wrapped_up()) (*iter)->wrapup();
   }
 }
ProtocolSession * s3f::s3fnet::ProtocolGraph::sessionForName (char * pname)
If a protocol session has been created and registered under the given name, the method returns the protocol session.
Otherwise, a NULL is returned.
Definition at line 75 of file protocol_graph.cc.
References pname_map.
Referenced by s3f::s3fnet::SocketMaster::bind(), s3f::s3fnet::NBSocketMaster::bind(), s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), s3f::s3fnet::UDPMaster::init(), and s3f::s3fnet::TCPMaster::init().
 {
   // return protocol session of the given name or NULL if not found
   S3FNET_GRAPH_PROTONAME_MAP::iterator iter;
   iter = pname_map.find(pname);
   if(iter != pname_map.end()) return (*iter).second;
   else return 0;
 }
ProtocolSession * s3f::s3fnet::ProtocolGraph::sessionForNumber (int pno)
If a protocol session has been created and registered under the given protocol number, the method returns the protocol session.
Otherwise, a NULL is returned.
Definition at line 84 of file protocol_graph.cc.
References pno_map.
Referenced by s3f::s3fnet::IPSession::get_parent_by_protocol(), s3f::s3fnet::NetworkInterface::init(), s3f::s3fnet::SimpleMac::pop(), and s3f::s3fnet::OpenFlowSwitchSession::SetController().
 {
   // return protocol session of the given name or NULL if not found
   S3FNET_GRAPH_PROTONUM_MAP::iterator iter = pno_map.find(pno);
   if(iter != pno_map.end()) return (*iter).second;
   else return 0;
 }
ProtocolSession * s3f::s3fnet::ProtocolGraph::config_session (s3f::dml::Configuration * cfg) protected
Internal use: to configure a protocol session.
Definition at line 108 of file protocol_graph.cc.
References s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::error_quit(), insert_session(), and s3f::s3fnet::Protocols::newInstance().
Referenced by config().
 {
   // find out session name from 'name' attribute
   char* str= (char*)cfg->findSingle("name");
   if(!str)
     error_quit("ERROR: session missing NAME attribute");
   if(s3f::dml::dmlConfig::isConf(str))
     error_quit("ERROR: invalid ProtocolSession.NAME.\n");
   S3FNET_STRING sessname = str;
   // find out class name from 'use' attribute
   char* classname = (char*)cfg->findSingle("use");
   if(!classname)
     error_quit("ERROR: session missing USE attribute");
   if(s3f::dml::dmlConfig::isConf(classname))
     error_quit("ERROR: invalid ProtocolSession.USE.\n");
   // classname is not copied from dml library, so it's temporary
   // valid until the next dml query!
   // create a new protocol session
   ProtocolSession* psess = Protocols::newInstance(classname, this);
   if(!psess)
   {
     error_quit("ERROR: failed to create protocol \"%s\".\n", classname);
   }
   // configure the protocol session
   psess->config(cfg);
   insert_session(psess);
   return psess;
 }
void s3f::s3fnet::ProtocolGraph::insert_session (ProtocolSession * psess) protected
Insert a protocol session to this protocol graph.
Definition at line 141 of file protocol_graph.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolSession::getProtocolNumber(), s3f::s3fnet::ProtocolSession::instantiation_type(), s3f::s3fnet::ProtocolSession::name, pname_map, pno_map, s3f::s3fnet::ProtocolSession::PROT_MULTIPLE_INSTANCES, s3f::s3fnet::ProtocolSession::PROT_UNIQUE_INSTANCE, protocol_list, S3FNET_MAKE_PAIR, S3FNET_PAIR, and s3f::s3fnet::ProtocolSession::use.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), and config_session().
 {
   S3FNET_PAIR(S3FNET_GRAPH_PROTONAME_MAP::iterator, bool) ret0 =
     pname_map.insert(S3FNET_MAKE_PAIR(S3FNET_STRING(psess->name), psess));
   if(!ret0.second)
   {
     if(psess->instantiation_type() == ProtocolSession::PROT_UNIQUE_INSTANCE)
       error_quit("ERROR: protocol session \"%s\" only allows unique instance.\n", psess->use);
     else if(psess->instantiation_type() == ProtocolSession::PROT_MULTIPLE_INSTANCES &&
             strcasecmp((*ret0.first).second->use, psess->use))
       error_quit("ERROR: protocol session \"%s\" allows multiple instances of the same implementation.\n", psess->use);
   }
   int sno = psess->getProtocolNumber();
   S3FNET_PAIR(S3FNET_GRAPH_PROTONUM_MAP::iterator, bool) ret1 = pno_map.insert(S3FNET_MAKE_PAIR(sno, psess));
   if(!ret1.second)
   {
     if(psess->instantiation_type() == ProtocolSession::PROT_UNIQUE_INSTANCE)
       error_quit("ERROR: protocol session \"%s\" only allows unique instance.\n", psess->use);
     else if(psess->instantiation_type() == ProtocolSession::PROT_MULTIPLE_INSTANCES &&
             strcasecmp((*ret1.first).second->use, psess->use))
       error_quit("ERROR: protocol session \"%s\" allows multiple instances of the same implementation.\n", psess->use);
   }
   protocol_list.push_back(psess);
 }
Member Data Documentation
char* s3f::s3fnet::ProtocolGraph::description
Optional string to describe the protocol graph.
The string is NULL if the DML 'graph' attribute does not contain a 'description' attribute.
Definition at line 43 of file protocol_graph.h.
Referenced by config(), and ~ProtocolGraph().
S3FNET_GRAPH_PROTONAME_MAP s3f::s3fnet::ProtocolGraph::pname_map protected
Mapping between protocol names and instances of protocol sessions.
Definition at line 108 of file protocol_graph.h.
Referenced by config(), insert_session(), and sessionForName().
S3FNET_GRAPH_PROTONUM_MAP s3f::s3fnet::ProtocolGraph::pno_map protected
Mapping between protocol numbers and instances of protocol sessions.
Definition at line 111 of file protocol_graph.h.
Referenced by insert_session(), and sessionForNumber().
S3FNET_GRAPH_PSESS_VECTOR s3f::s3fnet::ProtocolGraph::protocol_list protected
List of protocol sessions created.
Definition at line 114 of file protocol_graph.h.
Referenced by init(), insert_session(), wrapup(), and ~ProtocolGraph().
The documentation for this class was generated from the following files:
protocol_graph.h
protocol_graph.cc