S3F: s3f::s3fnet::RouteInfo Class Reference
s3f::s3fnet::RouteInfo Class Reference
A route entry of a forwarding table.
#include <forwardingtable.h>
Public Types
enum RoutingProtocol {
UNSPEC = 0, STATIC = 1, IGP = 2, EGP = 3,
BGP = 4, OSPF = 5, XORP = 6, PAO = 7,
REVERSE = 8
}
How/who installed the RouteInfo into the forwarding table?
Public Member Functions
RouteInfo ()
The constructor.
virtual ~RouteInfo ()
The destructor.
RouteInfo * resolve (Host *machine)
Validate this route info is valid by chekcing the next hop is connected with this interface.
bool operator== (RouteInfo &rhs)
Override the equal operator.
bool operator!= (RouteInfo &rhs)
Override the inequal operator.
RouteInfo & operator= (const RouteInfo &r)
Override the assign operator.
void display (FILE *fp)
Output the route to the give file stream.
void config (Host *h, s3f::dml::Configuration *cfg)
Configure the route entry for the specified host.
bool equiv (TrieData *td)
Compares this TrieData instance to another.
TrieData * clone ()
Duplicates the TrieData instance.
Public Attributes
IPPrefix destination
The destination IP prefix.
IPADDR next_hop
The IP address of the next hop.
NetworkInterface * nic
The network interface through which it gets to the next hop.
int cost
The cost of this routing entry.
int protocol
The protocol that maintains this routing entry.
bool resolved
Indicate whether the resolve() method has been called.
Static Public Attributes
static char * routingProtocol2Str []
Protected Member Functions
virtual int size ()
returns size in bytes
virtual char * toByteArray ()
transform the structure into a byte array of length size()
Detailed Description
A route entry of a forwarding table.
Definition at line 34 of file forwardingtable.h.
Member Enumeration Documentation
enum s3f::s3fnet::RouteInfo::RoutingProtocol
How/who installed the RouteInfo into the forwarding table?
Enumerator
UNSPEC
unspecified
STATIC
this is a static route
IGP
this route was installed by an Interior Gateway Protocol
EGP
this route was installed by an Exterior Gateway Protocol
BGP
this route was installed by the Border Gateway Protocol
OSPF
this route was installed by the Open Shortest Path First protocol
XORP
this route was installed by XORP
PAO
installed by Policy-Aware On-demand routing mechanism
REVERSE
installed using ip reverse route
Definition at line 37 of file forwardingtable.h.
{
     UNSPEC = 0,
     STATIC = 1,
     IGP    = 2,
     EGP    = 3,
     BGP    = 4,
     OSPF   = 5,
     XORP   = 6,
     PAO    = 7,
     REVERSE = 8,
   };
Constructor & Destructor Documentation
s3f::s3fnet::RouteInfo::RouteInfo () inline
The constructor.
Definition at line 51 of file forwardingtable.h.
Referenced by size().
              : next_hop(IPADDR_INVALID), nic(0),
     cost(1), protocol(STATIC), resolved(false) {}
virtual s3f::s3fnet::RouteInfo::~RouteInfo () inline virtual
The destructor.
Definition at line 55 of file forwardingtable.h.
 {}
Member Function Documentation
RouteInfo * s3f::s3fnet::RouteInfo::resolve (Host * machine)
Validate this route info is valid by chekcing the next hop is connected with this interface.
Return NULL if not.
Definition at line 152 of file forwardingtable.cc.
References s3f::s3fnet::Link::display(), s3f::s3fnet::error_retn(), s3f::s3fnet::NetworkInterface::getIP(), s3f::s3fnet::NetworkInterface::getLink(), s3f::s3fnet::Link::getNetworkInterfaces(), s3f::s3fnet::Link::getNumOfNetworkInterface(), s3f::s3fnet::IPPrefix::ip2txt(), IPADDR_INVALID, next_hop, s3f::s3fnet::DmlObject::nhi, nic, resolved, and s3f::s3fnet::Nhi::toString().
Referenced by s3f::s3fnet::IPSession::control(), and s3f::s3fnet::IPSession::init().
 {
   if(resolved) return this;
   Link* link = (Link*)nic->getLink();
   if(!link)
   {
     char buf1[50]; char buf2[50];
     error_retn("WARNING: RouteInfo::resolve() interface %s is not attached at host %s.\n",
                nic->nhi.toString(buf1), machine->nhi.toString(buf2));
     return 0;
   }
   IPADDR local_ip = nic->getIP();
   if(next_hop == local_ip) next_hop = IPADDR_INVALID;
   if(IPADDR_INVALID == next_hop)
   {
     // nic must have just 1 peer so that the next_hop is the only peer.
     int num_link_itrfs = 0;
     //link->getInterfaces(machine->getCommunity(), num_link_itrfs);
     num_link_itrfs = link->getNumOfNetworkInterface();
     // if the link is a LAN link, we must specify next hop address in
     // the dml file. Otherwise, we use the ip address of the only
     // interface
     if(num_link_itrfs > 2)
     {
       link->display();
       error_retn("WARNING: RouteInfo::resolve(), next_hop cannot be determined for LAN links on host %s.\n",
                  machine->nhi.toString());
       return 0;
     }
     // find the other attachment point to be the next hop
     //S3FNET_STRING_VECTOR& v = link->getIfaceNhis();
     vector<NetworkInterface*> ifaces = link->getNetworkInterfaces();
     for(unsigned i = 0; i < ifaces.size(); i++)
     {
       next_hop = ifaces[i]->getIP();
       if(next_hop != local_ip) break;
     }
   }
   else
   { // if next hop is specified, make sure it's one of the attachment points
     bool found = false;
     //S3FNET_STRING_VECTOR& v = link->getIfaceNhis();
     vector<NetworkInterface*> ifaces = link->getNetworkInterfaces();
     for(unsigned i = 0; i < ifaces.size(); i++)
     {
       IPADDR attached = ifaces[i]->getIP();
       if(attached == next_hop)
       { // note that next hop cannot be local ip (see above)
         found = true;
         break;
       }
     }
     if(!found)
     {
       error_retn("WARNING: RouterInfo::resolve(), invalid next_hop \"%s\" for host \"%s\"\n",
                  IPPrefix::ip2txt(next_hop), machine->nhi.toString());
       return 0;
     }
   }
   resolved = true;
   return this;
 }
bool s3f::s3fnet::RouteInfo::operator== (RouteInfo & rhs) inline
Override the equal operator.
Definition at line 63 of file forwardingtable.h.
References cost, destination, next_hop, nic, protocol, and resolved.
{
     return destination == rhs.destination &&
       next_hop == rhs.next_hop &&
       nic == rhs.nic &&
       cost == rhs.cost &&
       protocol == rhs.protocol &&
       resolved == rhs.resolved;
   }
bool s3f::s3fnet::RouteInfo::operator!= (RouteInfo & rhs) inline
Override the inequal operator.
Definition at line 73 of file forwardingtable.h.
 { return !(*this==rhs); }
RouteInfo& s3f::s3fnet::RouteInfo::operator= (const RouteInfo & r) inline
Override the assign operator.
Definition at line 76 of file forwardingtable.h.
References cost, destination, next_hop, nic, protocol, and resolved.
{
     destination = r.destination;
     next_hop    = r.next_hop;
     nic         = r.nic;
     cost        = r.cost;
     protocol    = r.protocol;
     resolved    = r.resolved;
     return *this;
   }
void s3f::s3fnet::RouteInfo::display (FILE * fp)
Output the route to the give file stream.
Definition at line 69 of file forwardingtable.cc.
References cost, destination, s3f::s3fnet::IPPrefix::display(), s3f::s3fnet::NetworkInterface::getIP(), s3f::s3fnet::DmlObject::id, s3f::s3fnet::IPPrefix::ip2txt(), next_hop, and nic.
 {
   if(!fp) fp = stderr;
   fprintf(fp, "\troute [\n");
   fprintf(fp, "\t\tdest_ip ");
   destination.display(fp);
   fprintf(fp, "\n\t\tnext_hop %s", IPPrefix::ip2txt(next_hop));
   fprintf(fp, "\n\t\tinterface [%d] %s", (int)nic->id, IPPrefix::ip2txt(nic->getIP()));
   fprintf(fp, "\n\t\tcost %d", cost);
   fprintf(fp, "\n\t]\n");
 }
void s3f::s3fnet::RouteInfo::config (Host * h, s3f::dml::Configuration * cfg)
Configure the route entry for the specified host.
Definition at line 81 of file forwardingtable.cc.
References s3f::s3fnet::IPPrefix::addr, BGP, cost, destination, EGP, s3f::s3fnet::error_quit(), s3f::s3fnet::Host::getNetworkInterface(), IGP, IPADDR_INVALID, s3f::s3fnet::IPPrefix::len, next_hop, s3f::s3fnet::DmlObject::nhi, nic, OSPF, PAO, protocol, STATIC, s3f::s3fnet::Nhi::toString(), and s3f::s3fnet::IPPrefix::txt2ip().
Referenced by s3f::s3fnet::Host::config(), and s3f::s3fnet::IPSession::load_forwarding_table().
 {
   char* str = (char*)cfg->findSingle("dest_ip");
   if(!str || s3f::dml::dmlConfig::isConf(str))
     error_quit("ERROR: RouteInfo::config(), missing or invalid DEST_IP attribute.\n");
   if(!strcasecmp(str, "default"))
   {
     destination.addr = 0;
     destination.len = 0;
   }
   else destination.addr = IPPrefix::txt2ip(str, &(destination.len));
   str = (char*)cfg->findSingle("interface");
   if(!str || s3f::dml::dmlConfig::isConf(str))
     error_quit("ERROR: RouteInfo::config(), missing or invalid INTERFACE attribute.\n");
   int iface = atoi(str);
   nic = h->getNetworkInterface(iface);
   if(!nic)
   {
     error_quit("ERROR: RouteInfo::config(), nic %d on host \"%s\" non-exist.\n", iface, h->nhi.toString());
   }
   str = (char*)cfg->findSingle("next_hop");
   if(str)
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: RouteInfo::config(), invalid NEXT_HOP attribute.\n");
     int len=0;
     next_hop = IPPrefix::txt2ip(str, &len);
     // the prefix length is useless here
   }
   else next_hop = IPADDR_INVALID;
   str = (char*)cfg->findSingle("cost");
   if(str)
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: RouteInfo::config(), invalid COST attribute.\n");
     cost = atoi(str);
   }
   else
   {
     if(destination.addr == 0 && destination.len == 0)
       cost = 0x7ffffff; // default route has highest cost
     else cost = 1;
   }
   str = (char*)cfg->findSingle("protocol");
   if(str)
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: RouteInfo::config(), invalid PROTOCOL attribute.\n");
     if(!strncmp(str, "STATIC", 6)) {
       protocol = STATIC;
     } else if (!strncmp(str, "IGP", 3)) {
       protocol = IGP;
     } else if (!strncmp(str, "EGP", 3)) {
       protocol = EGP;
     } else if (!strncmp(str, "BGP", 3)) {
       protocol = BGP;
     } else if (!strncmp(str, "OSPF", 4)) {
       protocol = OSPF;
     } else if (!strncmp(str, "PAO", 3)) {
       protocol = PAO;
     } else {
       error_quit("ERROR: RouteInfo::config(), invalid PROTOCOL: \"%s\".\n", str);
     }
   }
   else protocol = STATIC;
 }
virtual int s3f::s3fnet::RouteInfo::size () inline protected virtual
returns size in bytes
Implements s3f::s3fnet::TrieData.
Definition at line 93 of file forwardingtable.h.
References RouteInfo().
                      {
         return sizeof(RouteInfo);
   }
virtual char* s3f::s3fnet::TrieData::toByteArray () inline protected virtual inherited
transform the structure into a byte array of length size()
Definition at line 58 of file trie.h.
Referenced by s3f::s3fnet::TrieData::clone(), and s3f::s3fnet::TrieData::equiv().
{
         return (char*)this;
   }
bool s3f::s3fnet::TrieData::equiv (TrieData * td) inline inherited
Compares this TrieData instance to another.
Parameters
td the TrieData reference to compare with.
Returns
true if data is identical, otherwise false
Definition at line 68 of file trie.h.
References s3f::s3fnet::TrieData::size(), and s3f::s3fnet::TrieData::toByteArray().
Referenced by s3f::s3fnet::tda2::TrieDataArray2::addElement(), s3f::s3fnet::trie2::Trie2::insert(), and s3f::s3fnet::trie3::Trie3::insert().
{
         if(size() != td->size()) {
                 return false;
         }
         int i;
         char* selfarray = toByteArray();
         char* tdarray = td->toByteArray();
         for(i=0;i<size();i++) {
                 if(selfarray[i] != tdarray[i]) {
                         return false;
                 }
         }
         return true;
   }
TrieData* s3f::s3fnet::TrieData::clone () inline inherited
Duplicates the TrieData instance.
Creates another TrieData instance containing identical data. Relies on the toByteArray() virtual method but is not, itself, virtual.
See Also
toByteArray()
Returns
(deep) copy of the current TrieData
Definition at line 91 of file trie.h.
References s3f::s3fnet::TrieData::size(), and s3f::s3fnet::TrieData::toByteArray().
Referenced by s3f::s3fnet::tda2::TrieDataArray2::removeElement().
                     {
         int s = size();
         int i;
         char* temp = new char[s];
         memcpy((void*)temp,toByteArray(),s);
         return (TrieData*)temp;
   }
Member Data Documentation
char * s3f::s3fnet::RouteInfo::routingProtocol2Str static
Initial value:
= {
  "UNSPEC", "STATIC", "IGP", "EGP", "BGP", "OSPF", "XORP", "PAO", "REVERSE"
}
Definition at line 48 of file forwardingtable.h.
IPPrefix s3f::s3fnet::RouteInfo::destination
The destination IP prefix.
Definition at line 99 of file forwardingtable.h.
Referenced by s3f::s3fnet::ForwardingTable::addRoute(), config(), s3f::s3fnet::IPSession::control(), display(), s3f::s3fnet::IPSession::init(), s3f::s3fnet::trie2::Trie2::insert(), operator=(), operator==(), s3f::s3fnet::ForwardingTable::removeRoute(), and s3f::s3fnet::DMLRouteInfo::resolve().
IPADDR s3f::s3fnet::RouteInfo::next_hop
The IP address of the next hop.
Definition at line 102 of file forwardingtable.h.
Referenced by config(), display(), s3f::s3fnet::trie2::Trie2::insert(), operator=(), operator==(), resolve(), and s3f::s3fnet::DMLRouteInfo::resolve().
NetworkInterface* s3f::s3fnet::RouteInfo::nic
The network interface through which it gets to the next hop.
Definition at line 105 of file forwardingtable.h.
Referenced by config(), display(), s3f::s3fnet::IPSession::handle_pop_pkt(), operator=(), operator==(), s3f::s3fnet::IPSession::push(), resolve(), and s3f::s3fnet::DMLRouteInfo::resolve().
int s3f::s3fnet::RouteInfo::cost
The cost of this routing entry.
Definition at line 108 of file forwardingtable.h.
Referenced by config(), display(), operator=(), operator==(), and s3f::s3fnet::DMLRouteInfo::resolve().
int s3f::s3fnet::RouteInfo::protocol
The protocol that maintains this routing entry.
Definition at line 111 of file forwardingtable.h.
Referenced by config(), operator=(), operator==(), and s3f::s3fnet::DMLRouteInfo::resolve().
bool s3f::s3fnet::RouteInfo::resolved
Indicate whether the resolve() method has been called.
Definition at line 114 of file forwardingtable.h.
Referenced by operator=(), operator==(), resolve(), and s3f::s3fnet::DMLRouteInfo::resolve().
The documentation for this class was generated from the following files:
forwardingtable.h
forwardingtable.cc