S3F: s3f::s3fnet::DummySession Class Reference
s3f::s3fnet::DummySession Class Reference
A dummy protocol session, sending hello messages to specified peers.
#include <dummy_session.h>
Public Types
enum InstantiationType { PROT_UNIQUE_INSTANCE = 0x00, PROT_MULTIPLE_INSTANCES = 0x01, PROT_MULTIPLE_IMPLEMENTATIONS = 0x02 }
Multiple protocol session instantiation type.
enum ExecutionStage { PSESS_CREATED = 0, PSESS_CONFIGURED = 1, PSESS_INITIALIZED = 2, PSESS_WRAPPED_UP = 3 }
A normal protocol session must go though the following stages.
Public Member Functions
DummySession (ProtocolGraph *graph)
the constructor must be take an argument of the protocol graph
virtual ~DummySession ()
the destructor
virtual int getProtocolNumber ()
each protocol must have a unique protocol number
virtual void config (s3f::dml::Configuration *cfg)
called to configure this protocol session
virtual void init ()
called after config() to initialize this protocol session
virtual int control (int ctrltyp, void *ctrlmsg, ProtocolSession *sess)
called by other protocol sessions to send special control messages
virtual int push (Activation msg, ProtocolSession *hi_sess, void *extinfo=0, size_t extinfo_size=0)
called by the protocol session above to push a protocol message down the protocol stack
virtual int pop (Activation msg, ProtocolSession *lo_sess, void *extinfo=0, size_t extinfo_size=0)
called by the protocol session below to pop a protocol message up the protocol stack
void callback (Activation ac)
the callback function registered with the callback_proc
void callback_body (Activation ac)
the actual body of the callback function
virtual void wrapup ()
The method is used to wrap up the protocol session.
int pushdown (Activation msg, ProtocolSession *hi_sess, void *extinfo=0, size_t extinfo_size=0)
The original push method is divided into pushdown() and push().
int popup (Activation msg, ProtocolSession *lo_sess, void *extinfo=0, size_t extinfo_size=0)
The original pop method is divided into popup() and pop().
ProtocolGraph * inGraph ()
The method returns the protocol graph in which this protocol session resides.
virtual Host * inHost ()
Return a pointer to the host owning this protocol session.
Random::RNG * getRandom ()
The method returns a pointer to the random number generator.
ltime_t getNow ()
The method returns the current simulation time.
char * getNowWithThousandSeparator ()
For printing the current simulation time in a better readable format.
int configured ()
This method returns true if the protocol session has been configured.
int initialized ()
This method returns true if the protocol session has been initialized.
int wrapped_up ()
This method returns true if the protocol session has been wrapped up.
virtual const char * psesstype ()
Public Attributes
Process * callback_proc
the S3F process used by waitFor() function in the dummy protocol, provide call_back functionality
ProtocolCallbackActivation * dcac
storing the data for the callback function this case, the dummy session object is stored.
S3FNET_STRING hello_message
hello message for the dummy protocol
S3FNET_STRING hello_peer_nhi
NHI of the peer node which hello messages will be sent.
S3FNET_STRING hello_peer_ip
IP of the peer node which hello messages will be sent.
ltime_t hello_interval
duration between which hello messages will be sent
ltime_t jitter
jitter added into the hello_interval
IPADDR hello_peer
the IP of the peer we send periodic hello messages
IPSession * ip_session
the IP layer below this protocol
int pkt_seq_num
packet sequence number (increasing)
char * name
Symbolic name of the protocol this session implements.
float version
Version number of this protocol implemenntation, represented as a floating point number (e.g., 1.23).
char * use
Name of the protocol class from which this protocol session is instantiated.
Protected Member Functions
virtual int instantiation_type ()
This method controls how protocol instances can coexist with one another.
Protected Attributes
ProtocolGraph * ingraph
Points to the protocol graph.
Random::RNG * sess_rng
Pointer to a random number generator.
int stage
This variable indicates the current stage of this protocol session.
Detailed Description
A dummy protocol session, sending hello messages to specified peers.
Definition at line 25 of file dummy_session.h.
Member Enumeration Documentation
enum s3f::s3fnet::ProtocolSession::InstantiationType inherited
Multiple protocol session instantiation type.
Enumerator
PROT_UNIQUE_INSTANCE
PROT_MULTIPLE_INSTANCES
PROT_MULTIPLE_IMPLEMENTATIONS
Definition at line 44 of file protocol_session.h.
{
     PROT_UNIQUE_INSTANCE                = 0x00,
     PROT_MULTIPLE_INSTANCES             = 0x01,
     PROT_MULTIPLE_IMPLEMENTATIONS       = 0x02
   };
enum s3f::s3fnet::ProtocolSession::ExecutionStage inherited
A normal protocol session must go though the following stages.
Enumerator
PSESS_CREATED
this protocol session has just been created
PSESS_CONFIGURED
the config method of this protocol session has been called
PSESS_INITIALIZED
the init method of this protocol session has been called
PSESS_WRAPPED_UP
Definition at line 51 of file protocol_session.h.
                       {
     PSESS_CREATED       = 0,
     PSESS_CONFIGURED    = 1,
     PSESS_INITIALIZED   = 2,
     PSESS_WRAPPED_UP    = 3
   };
Constructor & Destructor Documentation
s3f::s3fnet::DummySession::DummySession (ProtocolGraph * graph)
the constructor must be take an argument of the protocol graph
Definition at line 29 of file dummy_session.cc.
References DUMMY_DUMP.
                                                : ProtocolSession(graph)
 {
   // create your session-related variables here
   DUMMY_DUMP(printf("A dummy protocol session is created.\n"));
 }
s3f::s3fnet::DummySession::~DummySession () virtual
the destructor
Definition at line 35 of file dummy_session.cc.
References callback_proc, and DUMMY_DUMP.
 {
   // reclaim your session-related variables here
   DUMMY_DUMP(printf("A dummy protocol session is reclaimed.\n"));
   if(callback_proc) delete callback_proc;
 }
Member Function Documentation
virtual int s3f::s3fnet::DummySession::getProtocolNumber () inline virtual
each protocol must have a unique protocol number
Implements s3f::s3fnet::ProtocolSession.
Definition at line 37 of file dummy_session.h.
References s3f::s3fnet::S3FNET_PROTOCOL_TYPE_DUMMY.
 { return S3FNET_PROTOCOL_TYPE_DUMMY; }
void s3f::s3fnet::DummySession::config (s3f::dml::Configuration * cfg) virtual
called to configure this protocol session
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 42 of file dummy_session.cc.
References s3f::s3fnet::ProtocolSession::config(), Entity::d2t(), DUMMY_DUMP, s3f::s3fnet::error_quit(), hello_interval, hello_message, hello_peer_ip, hello_peer_nhi, s3f::s3fnet::ProtocolSession::inHost(), and jitter.
 {
   // the same method at the parent class must be called
   ProtocolSession::config(cfg);
   // parameterize your protocol session from DML configuration
   char* str = (char*)cfg->findSingle("hello_message");
   if(str)
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: DummySession::config(), invalid HELLO_MESSAGE attribute.");
     else hello_message = str;
   }
   else hello_message = "hello there";
   double hello_interval_double;
   str = (char*)cfg->findSingle("hello_interval");
   if(!str) hello_interval_double = 0;
           //error_quit("ERROR: DummySession::config(), missing HELLO_INTERVAL attribute.");
   else if(s3f::dml::dmlConfig::isConf(str))
     error_quit("ERROR: DummySession::config(), invalid HELLO_INTERVAL attribute.");
   else hello_interval_double = atof(str);
   if(hello_interval_double < 0)
     error_quit("ERROR: DummySession::config(), HELLO_INTERVAL needs to be non-negative.");
   hello_interval = inHost()->d2t(hello_interval_double, 0);
   if(hello_interval > 0)
   {
           str = (char*)cfg->findSingle("hello_peer_nhi");
           if(str)
           {
                 if(s3f::dml::dmlConfig::isConf(str))
                   error_quit("ERROR: DummySession::config(), invalid HELLO_PEER_NHI attribute.");
                 else hello_peer_nhi = str;
           }
           str = (char*)cfg->findSingle("hello_peer_ip");
           if(str)
           {
                 if(s3f::dml::dmlConfig::isConf(str))
                   error_quit("ERROR: DummySession::config(), invalid HELLO_PEER_IP attribute.");
                 else
         hello_peer_ip = str;
           }
           if(!hello_peer_nhi.empty() && !hello_peer_ip.empty())
                   error_quit("ERROR: DummySession::config(), HELLO_PEER_NHI and HELLO_PEER_IP both defined.");
           else if(hello_peer_nhi.empty() && hello_peer_ip.empty())
                   error_quit("ERROR: DummySession::config(), missing HELLO_PEER_NHI and HELLO_PEER_IP attribute.");
           DUMMY_DUMP(printf("A dummy session is configured in host of NHI=\"%s\":\n", inHost()->nhi.toString()););
           DUMMY_DUMP(printf("=> hello message: \"%s\".\n", hello_message.c_str()););
           if(!hello_peer_nhi.empty())
           {
                   DUMMY_DUMP(printf("=> hello peer: nhi=\"%s\".\n", hello_peer_nhi.c_str()););
           }
           else
           {
                   DUMMY_DUMP(printf("=> hello peer: ip=\"%s\".\n", hello_peer_ip.c_str()););
           }
           double jitter_double;
           str = (char*)cfg->findSingle("jitter");
           if(!str) jitter_double = 0;
           else if(s3f::dml::dmlConfig::isConf(str))
             error_quit("ERROR: DummySession::config(), invalid jitter attribute.");
           else
       jitter_double = atof(str);
           if(jitter_double < 0)
             error_quit("ERROR: DummySession::config(), jitter needs to be non-negative.");
           jitter = inHost()->d2t(jitter_double, 0);
           DUMMY_DUMP(printf("jitter = %ld\n", jitter););
   }
   DUMMY_DUMP(printf("=> hello interval: %ld.\n", hello_interval););
 }
void s3f::s3fnet::DummySession::init () virtual
called after config() to initialize this protocol session
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 116 of file dummy_session.cc.
References callback(), callback_proc, dcac, DUMMY_DUMP, s3f::s3fnet::error_quit(), s3f::s3fnet::Net::getNameService(), s3f::s3fnet::Host::getNetworkLayerProtocol(), s3f::s3fnet::ProtocolSession::getRandom(), hello_interval, hello_peer, hello_peer_ip, hello_peer_nhi, s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::Host::inNet(), ip_session, jitter, s3f::s3fnet::NameService::nhi2ip(), pkt_seq_num, s3f::s3fnet::Host::tie_breaking_seed, s3f::s3fnet::IPPrefix::txt2ip(), Random::RNG::Uniform(), and Entity::waitFor().
 {
   // the same method at the parent class must be called
   ProtocolSession::init();
   // initialize the session-related variables here
   DUMMY_DUMP(printf("Dummy session is initialized.\n"));
   pkt_seq_num = 0;
   // we couldn't resolve the NHI to IP translation in config method,
   // but now we can, since name service finally becomes functional
   if(!hello_peer_nhi.empty())
   {
         Host* owner_host = inHost();
         Net* owner_net = owner_host->inNet();
         hello_peer = owner_net->getNameService()->nhi2ip(hello_peer_nhi);
   }
   else
     hello_peer = IPPrefix::txt2ip(hello_peer_ip.c_str());
   // similarly we couldn't resolve the IP layer until now
   ip_session = (IPSession*)inHost()->getNetworkLayerProtocol();
   if(!ip_session) error_quit("ERROR: can't find the IP layer; impossible!");
   Host* owner_host = inHost();
   callback_proc = new Process( (Entity *)owner_host, (void (s3f::Entity::*)(s3f::Activation))&DummySession::callback);
   //hello interval = 0 means the dummy session only listens to messages
   if(hello_interval == 0) return;
   ltime_t wait_time = (ltime_t)getRandom()->Uniform(hello_interval-jitter, hello_interval+jitter);
   //schedule the first hello message
   dcac = new ProtocolCallbackActivation(this);
   Activation ac (dcac);
   HandleCode h = owner_host->waitFor( callback_proc, ac, wait_time, owner_host->tie_breaking_seed);
 }
int s3f::s3fnet::DummySession::control (int ctrltyp, void * ctrlmsg, ProtocolSession * sess) virtual
called by other protocol sessions to send special control messages
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 182 of file dummy_session.cc.
References s3f::s3fnet::ProtocolSession::control(), s3f::s3fnet::DUMMY_CTRL_COMMAND1, and s3f::s3fnet::DUMMY_CTRL_COMMAND2.
 {
   switch(ctrltyp)
   {
         case DUMMY_CTRL_COMMAND1:
         case DUMMY_CTRL_COMMAND2:
           return 0; // dummy control commands, we do nothing here
         default:
           return ProtocolSession::control(ctrltyp, ctrlmsg, sess);
   }
 }
int s3f::s3fnet::DummySession::push (Activation msg, ProtocolSession * hi_sess, void * extinfo = 0, size_t extinfo_size = 0) virtual
called by the protocol session above to push a protocol message down the protocol stack
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 194 of file dummy_session.cc.
References s3f::s3fnet::error_quit().
 {
   error_quit("ERROR: a message is pushed down to the dummy session from protocol layer above; it's impossible.\n");
   return 0;
 }
int s3f::s3fnet::DummySession::pop (Activation msg, ProtocolSession * lo_sess, void * extinfo = 0, size_t extinfo_size = 0) virtual
called by the protocol session below to pop a protocol message up the protocol stack
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 200 of file dummy_session.cc.
References s3f::s3fnet::IPOptionToAbove::dst_ip, DUMMY_DUMP, s3f::s3fnet::ProtocolMessage::erase_all(), s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::DummyMessage::hello_message, s3f::s3fnet::IPPrefix::ip2txt(), s3f::s3fnet::S3FNET_PROTOCOL_TYPE_DUMMY, s3f::s3fnet::IPOptionToAbove::src_ip, and s3f::s3fnet::ProtocolMessage::type().
 {
   DUMMY_DUMP(printf("A message is popped up to the dummy session from the IP layer.\n"));
   char* pkt_type = "dummy";
   //check if it is a dummy packet
   ProtocolMessage* message = (ProtocolMessage*)msg;
   if(message->type() != S3FNET_PROTOCOL_TYPE_DUMMY)
   {
           error_quit("ERROR: the message popup to dummy session is not S3FNET_PROTOCOL_TYPE_DUMMY.\n");
   }
   // the protocol message must be of DummyMessage type, and the extra info must be of IPOptionToAbove type
   DummyMessage* dmsg = (DummyMessage*)msg;
   IPOptionToAbove* ipopt = (IPOptionToAbove*)extinfo;
   DUMMY_DUMP(char buf1[32]; char buf2[32];
                          printf("[%s] Dummy session receives hello: \"%s\" (ip_src=%s, ip_dest=%s)\n",
                      getNowWithThousandSeparator(), dmsg->hello_message.c_str(),
                  IPPrefix::ip2txt(ipopt->src_ip, buf1), IPPrefix::ip2txt(ipopt->dst_ip, buf2)); );
   dmsg->erase_all();
   // returning 0 indicates success
   return 0;
 }
void s3f::s3fnet::DummySession::callback (Activation ac)
the callback function registered with the callback_proc
Definition at line 154 of file dummy_session.cc.
References callback_body().
Referenced by init().
 {
   DummySession* ds = (DummySession*)((ProtocolCallbackActivation*)ac)->session;
   ds->callback_body(ac);
 }
void s3f::s3fnet::DummySession::callback_body (Activation ac)
the actual body of the callback function
Definition at line 160 of file dummy_session.cc.
References callback_proc, DEFAULT_IP_TIMETOLIVE, s3f::s3fnet::IPPushOption::dst_ip, DUMMY_DUMP, s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::getRandom(), hello_interval, hello_message, hello_peer, s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::IPPrefix::ip2txt(), ip_session, s3f::s3fnet::IPADDR_INADDR_ANY, jitter, s3f::s3fnet::IPPushOption::prot_id, s3f::s3fnet::ProtocolSession::pushdown(), s3f::s3fnet::S3FNET_PROTOCOL_TYPE_DUMMY, s3f::s3fnet::IPPushOption::src_ip, s3f::s3fnet::IPPushOption::ttl, Random::RNG::Uniform(), and Entity::waitFor().
Referenced by callback().
 {
   DummyMessage* dmsg = new DummyMessage(hello_message);
   Activation dmsg_ac (dmsg);
   IPPushOption ipopt;
   ipopt.dst_ip = hello_peer;
   ipopt.src_ip = IPADDR_INADDR_ANY;
   ipopt.prot_id = S3FNET_PROTOCOL_TYPE_DUMMY;
   ipopt.ttl = DEFAULT_IP_TIMETOLIVE;
   DUMMY_DUMP(char s[32]; printf("[%s] Dummy session sends hello: \"%s\" to %s \n",
                   getNowWithThousandSeparator(), hello_message.c_str(),
                   IPPrefix::ip2txt(hello_peer, s)));
   ip_session->pushdown(dmsg_ac, this, (void*)&ipopt, sizeof(IPPushOption));
   // next hello interval time
   ltime_t wait_time = (ltime_t)getRandom()->Uniform(hello_interval - jitter, hello_interval + jitter);
   HandleCode h = inHost()->waitFor( callback_proc, ac, wait_time, inHost()->tie_breaking_seed );
 }
void s3f::s3fnet::ProtocolSession::wrapup () virtual inherited
The method is used to wrap up the protocol session.
It is called when the simulation finishes. It is designed to give user a chance to report simulation statistics. The default behavior is doing nothing. Subclass may override this method for protocol specific dealings. Note that there is no specific order in which wrapup is called for protocol sessions in a protocol graph.
Definition at line 59 of file protocol_session.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolSession::initialized(), s3f::s3fnet::ProtocolSession::name, s3f::s3fnet::ProtocolSession::PSESS_WRAPPED_UP, s3f::s3fnet::ProtocolSession::stage, and s3f::s3fnet::ProtocolSession::wrapped_up().
 {
   // Make sure this init function at the base class should be called
   // by the derived function!
   if(!initialized())
     error_quit("ERROR: ProtocolSession \"%s\" wrapup() called before init(), "
                "forgot to call base class's init() in your derived class?\n", name);
   else if(wrapped_up())
     error_quit("ERROR: duplicate calls to ProtocolSession::wrapup(): "
                "session name is \"%s\".\n", name);
   else stage = PSESS_WRAPPED_UP;
 }
int s3f::s3fnet::ProtocolSession::pushdown (Activation msg, ProtocolSession * hi_sess, void * extinfo = 0, size_t extinfo_size = 0) inherited
The original push method is divided into pushdown() and push().
The pushdown method is the generic part of the code, which is reserved for modeling the handling of messages transferred between protocol layers.
See Also
ProtocolSession::push method for details.
Definition at line 72 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::push().
Referenced by callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), s3f::s3fnet::IPSession::control(), s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), s3f::s3fnet::OpenFlowSwitchSession::OutputControl(), s3f::s3fnet::OpenFlowSwitchSession::OutputPacket(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::UDPMaster::push(), s3f::s3fnet::TCPMaster::push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::send(), and s3f::s3fnet::TCPSession::send_data().
 {
   return push(msg, hi_sess, extinfo, extinfo_size);
 }
int s3f::s3fnet::ProtocolSession::popup (Activation msg, ProtocolSession * lo_sess, void * extinfo = 0, size_t extinfo_size = 0) inherited
The original pop method is divided into popup() and pop().
The popup method is the generic part of the code, which is reserved for modeling the handling of messages transferred between protocol layers.
See Also
ProtocolSession::pop method for details.
Definition at line 77 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::pop().
Referenced by s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::IPSession::push(), and s3f::s3fnet::SimplePhy::receivePacket().
 {
   return pop(msg, lo_sess, extinfo, extinfo_size);
 }
ProtocolGraph* s3f::s3fnet::ProtocolSession::inGraph () inline inherited
The method returns the protocol graph in which this protocol session resides.
Definition at line 178 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::ingraph.
Referenced by s3f::s3fnet::SimplePhy::config(), s3f::s3fnet::SimplePhy::control(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::SimpleMac::init(), s3f::s3fnet::SimplePhy::init(), s3f::s3fnet::RedQueue::init(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::SimplePhy::push(), s3f::s3fnet::SimplePhy::receivePacket(), s3f::s3fnet::SimplePhy::sendPacket(), s3f::s3fnet::SimpleMac::SimpleMac(), s3f::s3fnet::SimplePhy::SimplePhy(), s3f::s3fnet::SimpleMac::~SimpleMac(), and s3f::s3fnet::SimplePhy::~SimplePhy().
 { return ingraph; }
Host * s3f::s3fnet::ProtocolSession::inHost () virtual inherited
Return a pointer to the host owning this protocol session.
Reimplemented in s3f::s3fnet::NicProtocolSession.
Definition at line 118 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::ingraph.
Referenced by s3f::s3fnet::UDPSession::abort(), s3f::s3fnet::SocketMaster::abort(), s3f::s3fnet::NBSocketMaster::abort(), s3f::s3fnet::SocketMaster::accept(), s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::accept1a(), s3f::s3fnet::SocketMaster::accept1b(), s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SocketMaster::accept2b(), s3f::s3fnet::OpenFlowSwitchSession::AddFlow(), s3f::s3fnet::TCPSession::backoff_timeout(), s3f::s3fnet::SocketMaster::bind(), s3f::s3fnet::NBSocketMaster::bind(), s3f::s3fnet::SocketMaster::block_till(), s3f::s3fnet::NBSocketMaster::block_till(), s3f::s3fnet::BTCPClientSession::BTCPClientSession(), s3f::s3fnet::OpenFlowSwitchSession::BufferFromPacket(), callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::UDPServerSession::client_connected(), s3f::s3fnet::SocketMaster::close(), s3f::s3fnet::NBSocketMaster::close(), s3f::s3fnet::SocketMaster::close1(), s3f::s3fnet::NBSocketMaster::close1(), s3f::s3fnet::UDPMaster::config(), config(), s3f::s3fnet::TCPClientSession::config(), s3f::s3fnet::UDPServerSession::config(), s3f::s3fnet::UDPClientSession::config(), s3f::s3fnet::TCPServerSession::config(), s3f::s3fnet::TCPMaster::config(), s3f::s3fnet::NBTCPClientSession::config(), s3f::s3fnet::BTCPClientSession::config(), s3f::s3fnet::IPSession::config(), s3f::s3fnet::NBTCPServerSession::config(), s3f::s3fnet::UDPSession::connect(), s3f::s3fnet::SocketMaster::connect(), s3f::s3fnet::NBSocketMaster::connect(), s3f::s3fnet::SocketMaster::connect1(), s3f::s3fnet::NBSocketMaster::connect1(), s3f::s3fnet::SocketMaster::connected(), s3f::s3fnet::NBSocketMaster::connected(), s3f::s3fnet::UDPMaster::control(), s3f::s3fnet::SocketMaster::control(), s3f::s3fnet::NBSocketMaster::control(), s3f::s3fnet::IPSession::control(), s3f::s3fnet::TCPMaster::createSession(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::UDPServerSession::data_sent(), s3f::s3fnet::TCPServerSession::data_sent(), s3f::s3fnet::UDPSession::disconnect(), s3f::s3fnet::TCPMaster::enableFastTimeout(), s3f::s3fnet::SocketMaster::eof(), s3f::s3fnet::NBSocketMaster::eof(), s3f::s3fnet::UDPClientSessionContinuation::failure(), s3f::s3fnet::UDPServerSessionContinuation::failure(), s3f::s3fnet::TCPServerSessionContinuation::failure(), s3f::s3fnet::TCPClientSessionContinuation::failure(), s3f::s3fnet::BTCPClientSessionContinuation::failure(), s3f::s3fnet::TCPMaster::fast_timer_callback_body(), s3f::s3fnet::Stats::FlowStatsDump(), s3f::s3fnet::OpenFlowSwitchSession::FlowTableLookup(), s3f::s3fnet::IPSession::get_parent_by_protocol(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::ProtocolSession::getNow(), s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::OpenFlowSwitchSession::HandleControlInput(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), init(), s3f::s3fnet::UDPMaster::init(), s3f::s3fnet::OpenFlowControllerSession::init(), s3f::s3fnet::OpenVZEventSession::init(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPServerSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::TCPServerSession::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::OpenFlowSwitchSession::init(), s3f::s3fnet::NBTCPClientSession::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::SocketMaster::init(), s3f::s3fnet::IPSession::init(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::NBSocketMaster::init(), s3f::s3fnet::NBTCPServerSession::init(), s3f::s3fnet::TCPSession::init_state_closed(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::IPSession::IPSession(), s3f::s3fnet::UDPSession::listen(), s3f::s3fnet::SocketMaster::listen(), s3f::s3fnet::NBSocketMaster::listen(), s3f::s3fnet::IPSession::load_forwarding_table(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), s3f::s3fnet::OpenFlowSwitchSession::ModFlow(), s3f::s3fnet::NBSocketMaster::NBSocketMaster(), s3f::s3fnet::NBTCPClientSession::NBTCPClientSession(), s3f::s3fnet::NBTCPServerSession::NBTCPServerSession(), s3f::s3fnet::NBTCPClientSession::non_blocking_loop(), s3f::s3fnet::NBTCPServerSession::non_blocking_loop(), s3f::s3fnet::OpenFlowSwitchSession::OutputControl(), s3f::s3fnet::OpenFlowSwitchSession::OutputPacket(), s3f::s3fnet::OpenFlowSwitchSession::OutputPort(), s3f::s3fnet::OpenFlowControllerSession::pop(), s3f::s3fnet::UDPMaster::pop(), s3f::s3fnet::OpenVZEventSession::pop(), s3f::s3fnet::OpenFlowSwitchSession::pop(), s3f::s3fnet::TCPMaster::pop(), s3f::s3fnet::IPSession::pop(), s3f::s3fnet::LearningController::process_recv_packet(), s3f::s3fnet::UDPMaster::push(), s3f::s3fnet::TCPMaster::push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::receive(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::LearningControllerSession::ReceiveFromSwitch(), s3f::s3fnet::OpenFlowSwitchSession::ReceivePacketOut(), s3f::s3fnet::OpenFlowSwitchSession::ReceivePortMod(), s3f::s3fnet::OpenFlowSwitchSession::ReceiveStatsRequest(), s3f::s3fnet::SocketMaster::recv(), s3f::s3fnet::NBSocketMaster::recv(), s3f::s3fnet::SocketMaster::recv1(), s3f::s3fnet::NBSocketMaster::recv1(), s3f::s3fnet::UDPServerSession::request_received(), s3f::s3fnet::TCPServerSession::request_received(), s3f::s3fnet::UDPClientSession::request_sent(), s3f::s3fnet::TCPClientSession::request_sent(), s3f::s3fnet::NBTCPClientSessionContinuation::resume(), s3f::s3fnet::NBTCPServerSessionContinuation::resume(), s3f::s3fnet::OpenFlowSwitchSession::RunThroughFlowTable(), s3f::s3fnet::UDPSession::send(), s3f::s3fnet::SocketMaster::send(), s3f::s3fnet::NBSocketMaster::send(), s3f::s3fnet::SocketMaster::send1(), s3f::s3fnet::NBSocketMaster::send1(), s3f::s3fnet::TCPSession::send_data(), s3f::s3fnet::OpenFlowSwitchSession::SendFlowExpired(), s3f::s3fnet::OpenFlowSwitchSession::SendOpenflowBuffer(), s3f::s3fnet::OpenFlowSwitchSession::SendPortStatus(), s3f::s3fnet::UDPClientSession::server_connected(), s3f::s3fnet::TCPClientSession::server_connected(), s3f::s3fnet::BTCPClientSession::server_connected(), s3f::s3fnet::UDPServerSession::session_closed(), s3f::s3fnet::UDPClientSession::session_closed(), s3f::s3fnet::TCPClientSession::session_closed(), s3f::s3fnet::TCPServerSession::session_closed(), s3f::s3fnet::BTCPClientSession::session_closed(), s3f::s3fnet::TCPMaster::setConnected(), s3f::s3fnet::OpenFlowSwitchSession::SetController(), s3f::s3fnet::TCPMaster::setIdle(), s3f::s3fnet::TCPMaster::setListening(), s3f::s3fnet::UDPSession::setSource(), s3f::s3fnet::TCPMaster::slow_timer_callback_body(), s3f::s3fnet::TCPSession::slowTimeoutHandling(), s3f::s3fnet::SocketMaster::socket(), s3f::s3fnet::NBSocketMaster::socket(), s3f::s3fnet::SocketMaster::SocketMaster(), s3f::s3fnet::UDPServerSession::start_on(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPServerSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), s3f::s3fnet::NBTCPClientSession::start_on(), s3f::s3fnet::BTCPClientSession::start_on(), s3f::s3fnet::NBTCPServerSession::start_on(), s3f::s3fnet::NBTCPServerSessionContinuation::success(), s3f::s3fnet::TCPClientSession::TCPClientSession(), s3f::s3fnet::TCPMaster::TCPMaster(), s3f::s3fnet::TCPServerSession::TCPServerSession(), s3f::s3fnet::TCPSession::TCPSession(), s3f::s3fnet::UDPClientSession::timeout(), s3f::s3fnet::TCPClientSession::timeout(), s3f::s3fnet::BTCPClientSession::timeout(), s3f::s3fnet::UDPClientSession::UDPClientSession(), s3f::s3fnet::UDPMaster::UDPMaster(), s3f::s3fnet::UDPServerSession::UDPServerSession(), s3f::s3fnet::UDPSession::UDPSession(), s3f::s3fnet::TCPSession::update_timeout(), s3f::s3fnet::IPSession::verify_local_ip_address(), and s3f::s3fnet::UDPSession::wake_app().
 {
   return dynamic_cast<Host*>(ingraph);
 }
Random::RNG* s3f::s3fnet::ProtocolSession::getRandom () inline inherited
The method returns a pointer to the random number generator.
Definition at line 200 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::sess_rng.
Referenced by s3f::s3fnet::DroptailQueue::calibrate(), s3f::s3fnet::RedQueue::calibrate(), callback_body(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), init(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), and s3f::s3fnet::NetworkInterface::receivePacket().
 { return sess_rng;}
ltime_t s3f::s3fnet::ProtocolSession::getNow () inherited
The method returns the current simulation time.
To be safe, please do NOT call this function after initialization and before wrapup phase. That is, it is unsafe to call this method in the constructor, destructor, config, init, and wrapup methods. The time service is carried out by the host's owner community. This method just directs the call to the community. It's given here for convenience.
Definition at line 123 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::inHost(), and Entity::now().
Referenced by s3f::s3fnet::DroptailQueue::calibrate(), s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::TCPMaster::enableFastTimeout(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::TCPMaster::fast_timer_callback_body(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::TCPSession::now(), s3f::s3fnet::OpenVZEventSession::pop(), s3f::s3fnet::TCPMaster::slow_timer_callback_body(), s3f::s3fnet::SocketMaster::socket(), s3f::s3fnet::NBSocketMaster::socket(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), and s3f::s3fnet::BTCPClientSession::start_on().
 {
   return inHost()->now();
 }
char * s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator () inherited
For printing the current simulation time in a better readable format.
Definition at line 128 of file protocol_session.cc.
References s3f::s3fnet::Host::getNowWithThousandSeparator(), and s3f::s3fnet::ProtocolSession::inHost().
Referenced by s3f::s3fnet::UDPSession::abort(), callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::UDPSession::connect(), s3f::s3fnet::TCPMaster::createSession(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::UDPServerSession::data_sent(), s3f::s3fnet::TCPServerSession::data_sent(), s3f::s3fnet::UDPSession::disconnect(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::UDPSession::listen(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), pop(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::OpenVZEventSession::pop(), s3f::s3fnet::UDPMaster::pop(), s3f::s3fnet::TCPMaster::pop(), s3f::s3fnet::IPSession::pop(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::UDPMaster::push(), s3f::s3fnet::SimplePhy::push(), s3f::s3fnet::TCPMaster::push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::receive(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::SimplePhy::receivePacket(), s3f::s3fnet::UDPServerSession::request_received(), s3f::s3fnet::TCPServerSession::request_received(), s3f::s3fnet::UDPClientSession::request_sent(), s3f::s3fnet::TCPClientSession::request_sent(), s3f::s3fnet::UDPSession::send(), s3f::s3fnet::TCPSession::send_data(), s3f::s3fnet::SimplePhy::sendPacket(), s3f::s3fnet::UDPClientSession::server_connected(), s3f::s3fnet::TCPClientSession::server_connected(), s3f::s3fnet::BTCPClientSession::server_connected(), s3f::s3fnet::UDPServerSession::session_closed(), s3f::s3fnet::UDPClientSession::session_closed(), s3f::s3fnet::TCPClientSession::session_closed(), s3f::s3fnet::TCPServerSession::session_closed(), s3f::s3fnet::BTCPClientSession::session_closed(), s3f::s3fnet::TCPMaster::setConnected(), s3f::s3fnet::TCPMaster::setIdle(), s3f::s3fnet::TCPMaster::setListening(), s3f::s3fnet::UDPSession::setSource(), s3f::s3fnet::TCPSession::slowTimeoutHandling(), s3f::s3fnet::UDPServerSession::start_on(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPServerSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), s3f::s3fnet::BTCPClientSession::start_on(), s3f::s3fnet::TCPSession::TCPSession(), s3f::s3fnet::UDPClientSession::timeout(), s3f::s3fnet::TCPClientSession::timeout(), s3f::s3fnet::BTCPClientSession::timeout(), s3f::s3fnet::UDPSession::UDPSession(), s3f::s3fnet::TCPSession::update_timeout(), and s3f::s3fnet::UDPSession::wake_app().
 {
         return inHost()->getNowWithThousandSeparator();
 }
int s3f::s3fnet::ProtocolSession::configured () inline inherited
This method returns true if the protocol session has been configured.
This method is used to make sure we configure the protocol session before initializing it.
Definition at line 221 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_CONFIGURED, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::config(), and s3f::s3fnet::ProtocolSession::init().
 { return stage >= PSESS_CONFIGURED; }
int s3f::s3fnet::ProtocolSession::initialized () inline inherited
This method returns true if the protocol session has been initialized.
This can be used to sequence calls to the init method of protocol sessions. For example, if protocol session A requires protocol session B to be initialized before A can be initialized, A's init method can call B's init method as long as B's initialized() returns true. The system does not enforce any ordering in its calls the init methods of all protocol sessions declared in the dml configuration.
Definition at line 233 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_INITIALIZED, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::init(), and s3f::s3fnet::ProtocolSession::wrapup().
 { return stage >= PSESS_INITIALIZED; }
int s3f::s3fnet::ProtocolSession::wrapped_up () inline inherited
This method returns true if the protocol session has been wrapped up.
This can be used to sequence calls to the wrapup method of protocol sessions. For example, if protocol session A requires protocol session B to be wrapped up before A can be wrapped up, A's wrapup method can call B's wrapup method as long as B's wrapped_up() returns true. The system does not enforce any ordering in its calls the wrapup methods of all protocol sessions declared in the dml configuration.
Definition at line 245 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_WRAPPED_UP, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::wrapup().
 { return stage >= PSESS_WRAPPED_UP; }
virtual const char* s3f::s3fnet::ProtocolSession::psesstype () inline virtual inherited
Reimplemented in s3f::s3fnet::NBSocketMaster, and s3f::s3fnet::SocketMaster.
Definition at line 247 of file protocol_session.h.
 { return "GENERIC"; } // DEBUG
virtual int s3f::s3fnet::ProtocolSession::instantiation_type () inline protected virtual inherited
This method controls how protocol instances can coexist with one another.
It returns one of the following:
PROT_UNIQUE_INSTANCE (default): allows only one instance for each type of protocol per protocol stack;
PROT_MULTIPLE_INSTANCES: allows multiple instances of the same implementation for each type of protocol per protocol stack;
PROT_MULTIPLE_IMPLEMENTATIONS: allows multiple instances from different implementations of the same protocol to exist on the protocol stack.
Reimplemented in s3f::s3fnet::BTCPClientSession, and s3f::s3fnet::TCPClientSession.
Definition at line 269 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PROT_UNIQUE_INSTANCE.
Referenced by s3f::s3fnet::ProtocolGraph::insert_session().
 { return PROT_UNIQUE_INSTANCE; }
Member Data Documentation
Process* s3f::s3fnet::DummySession::callback_proc
the S3F process used by waitFor() function in the dummy protocol, provide call_back functionality
Definition at line 55 of file dummy_session.h.
Referenced by callback_body(), init(), and ~DummySession().
ProtocolCallbackActivation* s3f::s3fnet::DummySession::dcac
storing the data for the callback function this case, the dummy session object is stored.
Definition at line 66 of file dummy_session.h.
Referenced by init().
S3FNET_STRING s3f::s3fnet::DummySession::hello_message
hello message for the dummy protocol
Definition at line 70 of file dummy_session.h.
Referenced by callback_body(), and config().
S3FNET_STRING s3f::s3fnet::DummySession::hello_peer_nhi
NHI of the peer node which hello messages will be sent.
Definition at line 72 of file dummy_session.h.
Referenced by config(), and init().
S3FNET_STRING s3f::s3fnet::DummySession::hello_peer_ip
IP of the peer node which hello messages will be sent.
Definition at line 74 of file dummy_session.h.
Referenced by config(), and init().
ltime_t s3f::s3fnet::DummySession::hello_interval
duration between which hello messages will be sent
Definition at line 76 of file dummy_session.h.
Referenced by callback_body(), config(), and init().
ltime_t s3f::s3fnet::DummySession::jitter
jitter added into the hello_interval
Definition at line 78 of file dummy_session.h.
Referenced by callback_body(), config(), and init().
IPADDR s3f::s3fnet::DummySession::hello_peer
the IP of the peer we send periodic hello messages
Definition at line 82 of file dummy_session.h.
Referenced by callback_body(), and init().
IPSession* s3f::s3fnet::DummySession::ip_session
the IP layer below this protocol
Definition at line 84 of file dummy_session.h.
Referenced by callback_body(), and init().
int s3f::s3fnet::DummySession::pkt_seq_num
packet sequence number (increasing)
Definition at line 88 of file dummy_session.h.
Referenced by init().
char* s3f::s3fnet::ProtocolSession::name inherited
Symbolic name of the protocol this session implements.
The name of the protocol is derived from the DML 'name' attribute. It must not be NULL once the protocol session is configured.
Definition at line 63 of file protocol_session.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::SimpleMac::init(), s3f::s3fnet::UDPMaster::init(), s3f::s3fnet::SimplePhy::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::SocketMaster::init(), s3f::s3fnet::IPSession::init(), s3f::s3fnet::NBSocketMaster::init(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::ProtocolGraph::insert_session(), s3f::s3fnet::ProtocolSession::wrapup(), and s3f::s3fnet::ProtocolSession::~ProtocolSession().
float s3f::s3fnet::ProtocolSession::version inherited
Version number of this protocol implemenntation, represented as a floating point number (e.g., 1.23).
Definition at line 69 of file protocol_session.h.
char* s3f::s3fnet::ProtocolSession::use inherited
Name of the protocol class from which this protocol session is instantiated.
The protocol class must be registered with the Protocols class so that we will be able to instantiate an object from the class. (C++ does not support self-reflection). The class name must not be NULL once the protocol session is configured.
Definition at line 79 of file protocol_session.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::ProtocolGraph::insert_session(), and s3f::s3fnet::ProtocolSession::~ProtocolSession().
ProtocolGraph* s3f::s3fnet::ProtocolSession::ingraph protected inherited
Points to the protocol graph.
Definition at line 335 of file protocol_session.h.
Referenced by s3f::s3fnet::NicProtocolSession::getNetworkInterface(), s3f::s3fnet::ProtocolSession::inGraph(), and s3f::s3fnet::ProtocolSession::inHost().
Random::RNG* s3f::s3fnet::ProtocolSession::sess_rng protected inherited
Pointer to a random number generator.
Definition at line 338 of file protocol_session.h.
Referenced by s3f::s3fnet::ProtocolSession::getRandom(), and s3f::s3fnet::ProtocolSession::init().
int s3f::s3fnet::ProtocolSession::stage protected inherited
This variable indicates the current stage of this protocol session.
Each protocol session will go through four staged: PSESS_CREATED, PSESS_CONFIGURED, PSESS_INITIALIZED, and then PSESS_WRAPPED_UP.
Definition at line 346 of file protocol_session.h.
Referenced by s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::ProtocolSession::configured(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::ProtocolSession::initialized(), s3f::s3fnet::ProtocolSession::wrapped_up(), and s3f::s3fnet::ProtocolSession::wrapup().
The documentation for this class was generated from the following files:
dummy_session.h
dummy_session.cc