S3F: s3f::s3fnet::TCPMaster Class Reference
s3f::s3fnet::TCPMaster Class Reference
The TCP master.
#include <tcp_master.h>
Public Types
enum { TCP_VERSION_TAHOE = 0, TCP_VERSION_RENO = 1, TCP_VERSION_NEW_RENO = 2, TCP_VERSION_SACK = 3 }
tcp versions implemented in s3fnet
enum InstantiationType { PROT_UNIQUE_INSTANCE = 0x00, PROT_MULTIPLE_INSTANCES = 0x01, PROT_MULTIPLE_IMPLEMENTATIONS = 0x02 }
Multiple protocol session instantiation type.
enum ExecutionStage { PSESS_CREATED = 0, PSESS_CONFIGURED = 1, PSESS_INITIALIZED = 2, PSESS_WRAPPED_UP = 3 }
A normal protocol session must go though the following stages.
Public Member Functions
TCPMaster (ProtocolGraph *graph)
The constructor.
virtual ~TCPMaster ()
The destructor.
virtual void config (s3f::dml::Configuration *cfg)
After a protocol is created, it needs to be configured using the DML attributes specified in the DML file for this protocol.
virtual int getProtocolNumber ()
Return the protocol number.
virtual void init ()
This function will be called after the entire network is read in and configured and after all the links have been connected, but before the simulation starts running.
virtual SocketSession * createSession (int sock)
Create a new TCP session of the given socket id.
void deleteSession (TCPSession *session)
Reclaim a TCP session.
void setConnected (TCPSession *session)
Change the state of the session to connected.
void setListening (TCPSession *session)
Change the state of the session to listening.
void setIdle (TCPSession *session)
Change the state of the session to idle.
void enableFastTimeout (TCPSession *session)
Enable a TCP session for fast timeout handling.
void disableFastTimeout (TCPSession *session)
Disable a TCP session from fast timeout handling.
void slow_timer_callback (Activation)
The callback function registered with the slow_timer_callback_proc.
void slow_timer_callback_body (Activation)
the actual body of the slow_timer_callback function
void fast_timer_callback (Activation)
The callback function registered with the fast_timer_callback_proc.
void fast_timer_callback_body (Activation)
the actual body of the fast_timer_callback function
int getVersion ()
uint32 getISS ()
uint32 getMSS ()
uint32 getRcvWndSize ()
uint32 getSndBufSize ()
uint32 getSndWndSize ()
uint32 getMaxRxmit ()
ltime_t getSlowTimeout ()
double getSlowTimeoutDouble ()
ltime_t getFastTimeout ()
double getFastTimeoutDouble ()
ltime_t getIdleTimeout ()
ltime_t getMSL ()
bool isDelayedAck ()
uint32 getMaxConWnd ()
uint32 getInitThresh ()
ProtocolSession * getSocketMaster ()
Return the socket master, the protocol session directly above the protocol session master.
virtual void wrapup ()
The method is used to wrap up the protocol session.
int pushdown (Activation msg, ProtocolSession *hi_sess, void *extinfo=0, size_t extinfo_size=0)
The original push method is divided into pushdown() and push().
int popup (Activation msg, ProtocolSession *lo_sess, void *extinfo=0, size_t extinfo_size=0)
The original pop method is divided into popup() and pop().
virtual int control (int ctrltyp, void *ctrlmsg, ProtocolSession *sess)
The control method is used by the protocol session to receive control messages (or information queries) from other protocol sessions both above and below this protocol session on the stack.
ProtocolGraph * inGraph ()
The method returns the protocol graph in which this protocol session resides.
virtual Host * inHost ()
Return a pointer to the host owning this protocol session.
Random::RNG * getRandom ()
The method returns a pointer to the random number generator.
ltime_t getNow ()
The method returns the current simulation time.
char * getNowWithThousandSeparator ()
For printing the current simulation time in a better readable format.
int configured ()
This method returns true if the protocol session has been configured.
int initialized ()
This method returns true if the protocol session has been initialized.
int wrapped_up ()
This method returns true if the protocol session has been wrapped up.
virtual const char * psesstype ()
Public Attributes
Process * slow_timer_callback_proc
Provide call_back functionality for implementing the slow timer in the TCPMaster this S3F process is used by waitFor() function.
Process * fast_timer_callback_proc
Provide call_back functionality for implementing the fast timer in the TCPMaster this S3F process is used by waitFor() function.
ProtocolCallbackActivation * slow_timer_ac
Storing the data for the slow timer callback function.
ProtocolCallbackActivation * fast_timer_ac
Storing the data for the fast timer callback function.
char * name
Symbolic name of the protocol this session implements.
float version
Version number of this protocol implemenntation, represented as a floating point number (e.g., 1.23).
char * use
Name of the protocol class from which this protocol session is instantiated.
Protected Member Functions
virtual int push (Activation msg, ProtocolSession *hi_sess, void *extinfo=0, size_t extinfo_size=0)
Send a message down the protocol stack to a lower layer.
virtual int pop (Activation msg, ProtocolSession *lo_sess, void *extinfo=0, size_t extinfo_size=0)
Receive a message up from the protocol stack.
void separate_session (TCPSession *sess)
Disassociate a protocol session from managed lists.
void delete_defunct_sessions ()
Finally remove sessions reclaimed using the deleteSession method.
virtual int instantiation_type ()
This method controls how protocol instances can coexist with one another.
Protected Attributes
ProtocolSession * sock_master
The socket master above the protocol session master.
ProtocolGraph * ingraph
Points to the protocol graph.
Random::RNG * sess_rng
Pointer to a random number generator.
int stage
This variable indicates the current stage of this protocol session.
Private Member Functions
typedef S3FNET_SET (TCPSession *) TCP_SESSIONS_SET
Private Attributes
TCP_SESSIONS_SET listening_sessions
TCP sessions that are listening.
TCP_SESSIONS_SET connected_sessions
TCP sessions that are connected with peers.
TCP_SESSIONS_SET idle_sessions
TCP sessions that are idle.
TCP_SESSIONS_SET fast_timeout_sessions
TCP Sessions to be called when fast timer expires.
TCP_SESSIONS_SET defunct_sessions
TCP sessions to be deleted.
int tcp_version
To identify the TCP variant.
uint32 iss
Initial sequence number.
uint32 mss
Maximum segment size.
uint32 rcv_wnd_size
Receive window size.
uint32 snd_wnd_size
Send window size.
uint32 snd_buf_size
Send buffer size.
uint32 max_rxmit
Maximum number of retransmissions of a segment.
ltime_t slow_timeout
Slow timeout interval.
double slow_timeout_double
ltime_t fast_timeout
Fast timeout interval.
double fast_timeout_double
ltime_t idle_timeout
Timeout interval for FIN_WAIT_2.
double idle_timeout_double
ltime_t msl
Maximum segment lifetime.
double msl_double
bool delayed_ack
True if delayed acknowledgment is turned on.
uint32 max_cong_wnd
Maximum congestion window size.
ltime_t boot_time
The time this TCP master protocol session starts.
double boot_time_double
ltime_t boot_time_window
The time window this TCP master protocol session starts; used to avoid the artificial synchrony in simulation.
double boot_time_window_double
ProtocolSession * ip_sess
The IP layer protocol session, located below this protocol session on the protocol stack.
Detailed Description
The TCP master.
The TCP master is a protocol session that deals with all TCP connections. It takes care of: (i) receiving TCP packets and sending them to the corresponding TCP sessions; (2) sending TCP packets the correspond to TCP sessions and pushing the packets down to the IP layer.
Definition at line 29 of file tcp_master.h.
Member Enumeration Documentation
anonymous enum
tcp versions implemented in s3fnet
Enumerator
TCP_VERSION_TAHOE
TCP_VERSION_RENO
TCP_VERSION_NEW_RENO
TCP_VERSION_SACK
Definition at line 34 of file tcp_master.h.
        {
     TCP_VERSION_TAHOE    = 0,
     TCP_VERSION_RENO     = 1,
     TCP_VERSION_NEW_RENO = 2,
     TCP_VERSION_SACK     = 3
   };
enum s3f::s3fnet::ProtocolSession::InstantiationType inherited
Multiple protocol session instantiation type.
Enumerator
PROT_UNIQUE_INSTANCE
PROT_MULTIPLE_INSTANCES
PROT_MULTIPLE_IMPLEMENTATIONS
Definition at line 44 of file protocol_session.h.
{
     PROT_UNIQUE_INSTANCE                = 0x00,
     PROT_MULTIPLE_INSTANCES             = 0x01,
     PROT_MULTIPLE_IMPLEMENTATIONS       = 0x02
   };
enum s3f::s3fnet::ProtocolSession::ExecutionStage inherited
A normal protocol session must go though the following stages.
Enumerator
PSESS_CREATED
this protocol session has just been created
PSESS_CONFIGURED
the config method of this protocol session has been called
PSESS_INITIALIZED
the init method of this protocol session has been called
PSESS_WRAPPED_UP
Definition at line 51 of file protocol_session.h.
                       {
     PSESS_CREATED       = 0,
     PSESS_CONFIGURED    = 1,
     PSESS_INITIALIZED   = 2,
     PSESS_WRAPPED_UP    = 3
   };
Constructor & Destructor Documentation
s3f::s3fnet::TCPMaster::TCPMaster (ProtocolGraph * graph)
The constructor.
Definition at line 52 of file tcp_master.cc.
References boot_time_window, boot_time_window_double, Entity::d2t(), delayed_ack, fast_timeout, fast_timeout_double, idle_timeout, idle_timeout_double, s3f::s3fnet::ProtocolSession::inHost(), iss, max_cong_wnd, max_rxmit, msl, msl_double, mss, rcv_wnd_size, slow_timeout, slow_timeout_double, snd_buf_size, snd_wnd_size, TCP_DEFAULT_DELAYEDACK, TCP_DEFAULT_FAST_TIMEOUT, TCP_DEFAULT_IDLE_TIMEOUT, TCP_DEFAULT_ISS, TCP_DEFAULT_MAXCONWND, TCP_DEFAULT_MAXRXMIT, TCP_DEFAULT_MSL, TCP_DEFAULT_MSS, TCP_DEFAULT_RCVWNDSIZ, TCP_DEFAULT_SLOW_TIMEOUT, TCP_DEFAULT_SNDBUFSIZ, TCP_DEFAULT_SNDWNDSIZ, TCP_DEFAULT_VERSION, TCP_DUMP, and tcp_version.
                                          :
                 SessionMaster(graph), ip_sess(0), slow_timer_callback_proc(0), fast_timer_callback_proc(0), slow_timer_ac(0)
 {
   TCP_DUMP(printf("[host=\"%s\"] new tcp master session.\n", inHost()->nhi.toString()));
   tcp_version                   = TCP_DEFAULT_VERSION;
   iss                           = TCP_DEFAULT_ISS;
   mss                           = TCP_DEFAULT_MSS;
   rcv_wnd_size                  = TCP_DEFAULT_RCVWNDSIZ;
   snd_wnd_size                  = TCP_DEFAULT_SNDWNDSIZ;
   snd_buf_size                  = TCP_DEFAULT_SNDBUFSIZ;
   max_rxmit                     = TCP_DEFAULT_MAXRXMIT;
   slow_timeout_double   = TCP_DEFAULT_SLOW_TIMEOUT;
   slow_timeout                  = inHost()->d2t(slow_timeout_double, 0);
   fast_timeout_double   = TCP_DEFAULT_FAST_TIMEOUT;
   fast_timeout                  = inHost()->d2t(fast_timeout_double, 0);
   idle_timeout_double   = TCP_DEFAULT_IDLE_TIMEOUT;
   idle_timeout                  = inHost()->d2t(idle_timeout_double, 0);
   msl_double            = TCP_DEFAULT_MSL;
   msl                                   = inHost()->d2t(msl_double, 0);
   delayed_ack                   = TCP_DEFAULT_DELAYEDACK;
   max_cong_wnd                  = TCP_DEFAULT_MAXCONWND;
   boot_time_window_double = 0;
   boot_time_window = 0;
 }
s3f::s3fnet::TCPMaster::~TCPMaster () virtual
The destructor.
Definition at line 79 of file tcp_master.cc.
References connected_sessions, delete_defunct_sessions(), fast_timeout_sessions, idle_sessions, listening_sessions, and S3FNET_SET().
 {
   // reclaim defunct_sessions first
   delete_defunct_sessions();
   // delete all listening sessions
   for(S3FNET_SET(TCPSession*)::iterator l_iter = listening_sessions.begin();
       l_iter != listening_sessions.end(); l_iter++)
     delete (*l_iter);
   listening_sessions.clear();
   // delete all connected sessions
   for(S3FNET_SET(TCPSession*)::iterator c_iter = connected_sessions.begin();
       c_iter != connected_sessions.end(); c_iter++)
     delete (*c_iter);
   connected_sessions.clear();
   // delete all idle sessions
   for(S3FNET_SET(TCPSession*)::iterator i_iter = idle_sessions.begin();
       i_iter != idle_sessions.end(); i_iter++)
     delete (*i_iter);
   idle_sessions.clear();
   // delete the list kept for fast timeout sessions
   fast_timeout_sessions.clear();
 }
Member Function Documentation
void s3f::s3fnet::TCPMaster::config (s3f::dml::Configuration * cfg) virtual
After a protocol is created, it needs to be configured using the DML attributes specified in the DML file for this protocol.
The protocol should read, verify and apply the attributes.
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 106 of file tcp_master.cc.
References boot_time_window, boot_time_window_double, s3f::s3fnet::ProtocolSession::config(), Entity::d2t(), delayed_ack, s3f::s3fnet::error_quit(), fast_timeout, fast_timeout_double, idle_timeout, idle_timeout_double, s3f::s3fnet::ProtocolSession::inHost(), iss, max_cong_wnd, max_rxmit, msl, msl_double, mss, rcv_wnd_size, S3FNET_IPHDR_LENGTH, S3FNET_TCPHDR_LENGTH, slow_timeout, slow_timeout_double, snd_buf_size, snd_wnd_size, TCP_DML_BOOT_TIME, TCP_DML_DELAYEDACK, TCP_DML_FAST_RECOVERY, TCP_DML_FAST_TIMEOUT, TCP_DML_IDLE_TIMEOUT, TCP_DML_ISS, TCP_DML_MAXCONWND, TCP_DML_MAXRXMIT, TCP_DML_MSL, TCP_DML_MSS, TCP_DML_RCVWNDSIZ, TCP_DML_SLOW_TIMEOUT, TCP_DML_SNDBUFSIZ, TCP_DML_SNDWNDSIZ, TCP_DML_TCPINIT, TCP_DML_VERSION, TCP_DUMP, tcp_version, TCP_VERSION_NEW_RENO, TCP_VERSION_RENO, TCP_VERSION_SACK, and TCP_VERSION_TAHOE.
 {
   SessionMaster::config(cfg);
   s3f::dml::Configuration* init_cfg = (s3f::dml::Configuration*)cfg->findSingle(TCP_DML_TCPINIT);
   if(init_cfg)
   {
     if(!s3f::dml::dmlConfig::isConf(init_cfg))
       error_quit("ERROR: TCPMaster::config(), invalid %s attribute.\n", TCP_DML_TCPINIT);
     char* version_string = (char*)init_cfg->findSingle(TCP_DML_VERSION);
     if(version_string)
     {
       if(s3f::dml::dmlConfig::isConf(version_string))
         error_quit("ERROR: TCPMaster::config(), invalid %s:%s attribute.\n",
                         TCP_DML_TCPINIT, TCP_DML_VERSION);
       if(!strcasecmp(version_string, "tahoe"))
       {
         tcp_version = TCP_VERSION_TAHOE;
       }
       else if(!strcasecmp(version_string, "reno"))
       {
         tcp_version = TCP_VERSION_RENO;
       }
       else if(!strcasecmp(version_string, "new_reno"))
       {
         tcp_version = TCP_VERSION_NEW_RENO;
       }
       else if(!strcasecmp(version_string, "sack"))
       {
         tcp_version = TCP_VERSION_SACK;
       }
       else
       {
         error_quit("ERROR: TCPMaster::config(), unknown TCP version: %s\n.", version_string);
       }
     }
     else // for backward compatibility
     {
       char* fast_recovery_string = (char*)init_cfg->findSingle(TCP_DML_FAST_RECOVERY);
       if(fast_recovery_string)
       {
         if(s3f::dml::dmlConfig::isConf(fast_recovery_string))
           error_quit("ERROR: TCPMaster::config(), invalid %s:%s attribute.\n",
                           TCP_DML_TCPINIT, TCP_DML_FAST_RECOVERY);
         if(!strcasecmp(fast_recovery_string, "true"))
         {
           tcp_version = TCP_VERSION_RENO;
         }
         else if(!strcasecmp(fast_recovery_string, "false"))
         {
           tcp_version = TCP_VERSION_TAHOE;
         }
         else
         {
           error_quit("ERROR: TCPMaster::config(), %s.%s (%s) must be either true or false.\n",
                      TCP_DML_TCPINIT, TCP_DML_FAST_RECOVERY, fast_recovery_string);
         }
       }
     }
     char* iss_string = (char*)init_cfg->findSingle(TCP_DML_ISS);
     if(iss_string)
     {
       if(s3f::dml::dmlConfig::isConf(iss_string))
         error_quit("ERROR: TCPMaster::config(), invalid %s:%s attribute.\n",
                         TCP_DML_TCPINIT, TCP_DML_ISS);
       iss = atoi(iss_string);
       if(iss < 0)
       {
         error_quit("ERROR: TCPMaster::config(), %s.%s is negative: %s.\n",
                         TCP_DML_TCPINIT, TCP_DML_ISS, iss_string);
       }
     }
     char* mss_string = (char*)init_cfg->findSingle(TCP_DML_MSS);
     if(mss_string)
     {
       if(s3f::dml::dmlConfig::isConf(mss_string))
         error_quit("ERROR: TCPMaster::config(), invalid %s:%s attribute.\n", TCP_DML_TCPINIT, TCP_DML_MSS);
       mss = atoi(mss_string);
       if(mss < 0 || mss > 65536-S3FNET_TCPHDR_LENGTH-S3FNET_IPHDR_LENGTH)
       {
         error_quit("ERROR: TCPMaster::config(), %s.%s (%s) must be in [0, %d].\n",
                    TCP_DML_TCPINIT, TCP_DML_MSS, mss_string, 65536-S3FNET_TCPHDR_LENGTH-S3FNET_IPHDR_LENGTH);
       }
     }
     char* rwnd_string = (char*)init_cfg->findSingle(TCP_DML_RCVWNDSIZ);
     if(rwnd_string)
     {
       if(s3f::dml::dmlConfig::isConf(rwnd_string))
           error_quit("ERROR: TCPMaster::config(), invalid %s:%s attribute.\n",
                           TCP_DML_TCPINIT, TCP_DML_RCVWNDSIZ);
       rcv_wnd_size = atoi(rwnd_string);
       if(rcv_wnd_size < 0)
       {
         error_quit("ERROR: TCPMaster::config(), %s.%s is negative: %s.\n",
                         TCP_DML_TCPINIT, TCP_DML_RCVWNDSIZ, rwnd_string);
       }
     }
     char* swnd_string = (char*)init_cfg->findSingle(TCP_DML_SNDWNDSIZ);
     if(swnd_string)
     {
       if(s3f::dml::dmlConfig::isConf(swnd_string))
         error_quit("ERROR: TCPMaster::config(), invalid %s:%s attribute.\n",
                         TCP_DML_TCPINIT, TCP_DML_SNDWNDSIZ);
       snd_wnd_size = atoi(swnd_string);
       if(snd_wnd_size < 0)
       {
           error_quit("ERROR: TCPMaster::config(), %s.%s is negative: %s.\n",
                           TCP_DML_TCPINIT, TCP_DML_SNDWNDSIZ, swnd_string);
       }
     }
     char* sbuf_string = (char*)init_cfg->findSingle(TCP_DML_SNDBUFSIZ);
     if(sbuf_string)
     {
       if(s3f::dml::dmlConfig::isConf(sbuf_string))
           error_quit("ERROR: TCPMaster::config(), invalid %s:%s attribute.\n",
                    TCP_DML_TCPINIT, TCP_DML_SNDBUFSIZ);
       snd_buf_size = atoi(sbuf_string);
       if(snd_buf_size < 0)
       {
         error_quit("ERROR: TCPMaster::config(), %s.%s is negative: %s.\n",
                         TCP_DML_TCPINIT, TCP_DML_SNDBUFSIZ, sbuf_string);
       }
     }
     char* rxmit_string = (char*)init_cfg->findSingle(TCP_DML_MAXRXMIT);
     if(rxmit_string)
     {
       if(s3f::dml::dmlConfig::isConf(rxmit_string))
         error_quit("ERROR: TCPMaster::config(), invalid %s:%s attribute.\n",
                         TCP_DML_TCPINIT, TCP_DML_MAXRXMIT);
       max_rxmit = atoi(rxmit_string);
       if(max_rxmit < 0 || max_rxmit > 31)
       {
           error_quit("ERROR: TCPMaster::config(), %s.%s (%s) must be in [0, 31].\n",
                           TCP_DML_TCPINIT, TCP_DML_MAXRXMIT, rxmit_string);
       }
     }
     char* slow_timeout_string = (char*)init_cfg->findSingle(TCP_DML_SLOW_TIMEOUT);
     if(slow_timeout_string)
     {
       if(s3f::dml::dmlConfig::isConf(slow_timeout_string))
           error_quit("ERROR: TCPMaster::config(), invalid %s:%s attribute.\n",
                    TCP_DML_TCPINIT, TCP_DML_SLOW_TIMEOUT);
       slow_timeout_double = atof(slow_timeout_string);
       if(slow_timeout_double < 0)
       {
           error_quit("ERROR: TCPMaster::config(), %s.%s is negative: %s.\n",
                           TCP_DML_TCPINIT, TCP_DML_SLOW_TIMEOUT, slow_timeout_string);
       }
       slow_timeout = inHost()->d2t(slow_timeout_double, 0);
     }
     char* fast_timeout_string = (char*)init_cfg->findSingle(TCP_DML_FAST_TIMEOUT);
     if(fast_timeout_string)
     {
       if(s3f::dml::dmlConfig::isConf(fast_timeout_string))
           error_quit("ERROR: TCPMaster::config(), invalid %s:%s attribute.\n",
                    TCP_DML_TCPINIT, TCP_DML_FAST_TIMEOUT);
       fast_timeout_double = atof(fast_timeout_string);
       if(fast_timeout_double < 0)
       {
         error_quit("ERROR: TCPMaster::config(), %s.%s is negative: %s.\n",
                         TCP_DML_TCPINIT, TCP_DML_FAST_TIMEOUT, fast_timeout_string);
       }
       fast_timeout = inHost()->d2t(fast_timeout_double, 0);
     }
     char* idle_timeout_string = (char*)init_cfg->findSingle(TCP_DML_IDLE_TIMEOUT);
     if(idle_timeout_string)
     {
       if(s3f::dml::dmlConfig::isConf(idle_timeout_string))
           error_quit("ERROR: TCPMaster::config(), invalid %s:%s attribute.\n",
                           TCP_DML_TCPINIT, TCP_DML_IDLE_TIMEOUT);
       idle_timeout_double = atof(idle_timeout_string);
       if(idle_timeout_double < 0)
       {
         error_quit("ERROR: TCPMaster::config(), %s.%s is negative: %s.\n",
                    TCP_DML_TCPINIT, TCP_DML_IDLE_TIMEOUT, idle_timeout_string);
       }
       idle_timeout = inHost()->d2t(idle_timeout_double, 0);
     }
     char* msl_string = (char*)init_cfg->findSingle(TCP_DML_MSL);
     if(msl_string)
     {
       if(s3f::dml::dmlConfig::isConf(msl_string))
         error_quit("ERROR: TCPMaster::config(), invalid %s:%s attribute.\n", TCP_DML_TCPINIT, TCP_DML_MSL);
       msl_double = atof(msl_string);
       if(msl_double < 0)
       {
         error_quit("ERROR: TCPMaster::config(), %s.%s is negative: %s.\n",
                    TCP_DML_TCPINIT, TCP_DML_MSL, msl_string);
       }
       msl = inHost()->d2t(msl_double, 0);
     }
     char* delayed_ack_string = (char*)init_cfg->findSingle(TCP_DML_DELAYEDACK);
     if(delayed_ack_string)
     {
       if(s3f::dml::dmlConfig::isConf(delayed_ack_string))
           error_quit("ERROR: TCPMaster::config(), invalid %s:%s attribute.\n",
                           TCP_DML_TCPINIT, TCP_DML_DELAYEDACK);
       if(!strcasecmp(delayed_ack_string, "true")) delayed_ack = true;
       else if(!strcasecmp(delayed_ack_string, "false")) delayed_ack = false;
       else
       {
         error_quit("ERROR: TCPMaster::config(), %s.%s (%s) must be either true or false.\n",
                    TCP_DML_TCPINIT, TCP_DML_DELAYEDACK, delayed_ack_string);
       }
     }
     char* max_conwnd_string = (char*)init_cfg->findSingle(TCP_DML_MAXCONWND);
     if(max_conwnd_string)
     {
       if(s3f::dml::dmlConfig::isConf(max_conwnd_string))
         error_quit("ERROR: TCPMaster::config(), invalid %s:%s attribute.\n",
                         TCP_DML_TCPINIT, TCP_DML_MAXCONWND);
       max_cong_wnd = atoi(max_conwnd_string);
       if(max_cong_wnd < 1)
       {
         error_quit("ERROR: TCPMaster::config(), %s.%s (%s) should be at least one.\n",
                         TCP_DML_TCPINIT, TCP_DML_MAXCONWND, max_conwnd_string);
       }
     }
   } //end init_cfg
   // send window size must be no larger than the sender buffer size
   if(snd_wnd_size > snd_buf_size)
   {
     error_quit("ERROR: TCPMaster::config(), %s (%u) must be no larger than %s (%u).\n",
                TCP_DML_SNDWNDSIZ, snd_wnd_size, TCP_DML_SNDBUFSIZ, snd_buf_size);
   }
   char* boot_time_string = (char*)cfg->findSingle(TCP_DML_BOOT_TIME);
   if(boot_time_string)
   {
     if(s3f::dml::dmlConfig::isConf(boot_time_string))
       error_quit("ERROR: TCPMaster::config(), invalid %s attribute.\n", TCP_DML_BOOT_TIME);
     boot_time_window_double = atof(boot_time_string);
     if(boot_time_window_double < 0)
     {
       error_quit("ERROR: TCPMaster::config(), %s is negative: %ld.\n", TCP_DML_BOOT_TIME, boot_time_string);
     }
     boot_time_window = inHost()->d2t(boot_time_window_double, 0);
   }
   TCP_DUMP(printf("[host=\"%s\"] config():\n"
                   "  ver=%d, iss=%u, mss=%u, rwnd=%u, swnd=%u, sbuf=%u,\n"
                   "  max_rxmit=%u, slow_timeout=%ld, fast_timeout=%ld, idle_timeout=%ld,\n"
                   "  msl=%ld, delayed_ack=%d, max_cwnd=%u, boot_time_window=%ld.\n",
                   inHost()->nhi.toString(),
                   tcp_version, iss, mss, rcv_wnd_size, snd_wnd_size, snd_buf_size,
                   max_rxmit, slow_timeout, fast_timeout, idle_timeout,
                   msl, delayed_ack, max_cong_wnd, boot_time_window));
   rcv_wnd_size *= mss;
   snd_wnd_size *= mss;
   snd_buf_size *= mss;
   max_cong_wnd *= mss;
 }
virtual int s3f::s3fnet::TCPMaster::getProtocolNumber () inline virtual
Return the protocol number.
This specifies the relationship between this protocol and the other protocols defined in the same protocol stack.
Implements s3f::s3fnet::ProtocolSession.
Definition at line 59 of file tcp_master.h.
References s3f::s3fnet::S3FNET_PROTOCOL_TYPE_TCP.
 { return S3FNET_PROTOCOL_TYPE_TCP; }
void s3f::s3fnet::TCPMaster::init () virtual
This function will be called after the entire network is read in and configured and after all the links have been connected, but before the simulation starts running.
The protocols can do any kind of initialization they need which requires the network to be connected. For TCP, during initialization phase, IP layer immediately beneath this protocol will be figured out.
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 374 of file tcp_master.cc.
References boot_time, boot_time_double, boot_time_window, boot_time_window_double, calc_slow_timeout, Entity::d2t(), s3f::s3fnet::error_quit(), s3f::s3fnet::Host::getNetworkLayerProtocol(), s3f::s3fnet::ProtocolSession::getRandom(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::ProtocolSession::init(), ip_sess, s3f::s3fnet::ProtocolSession::name, s3f::s3fnet::ProtocolGraph::sessionForName(), slow_timer_ac, slow_timer_callback(), slow_timer_callback_proc, s3f::s3fnet::SessionMaster::sock_master, SOCKET_PROTOCOL_NAME, TCP_DUMP, TCP_PROTOCOL_NAME, s3f::s3fnet::Host::tie_breaking_seed, Random::RNG::Uniform(), and Entity::waitFor().
 {
   TCP_DUMP(printf("[host=\"%s\"] init().\n", inHost()->nhi.toString()));
   SessionMaster::init();
   if(strcasecmp(name, TCP_PROTOCOL_NAME))
     error_quit("ERROR: TCPMaster::init(), unmatched protocol name: \"%s\", expecting \"TCP\".\n", name);
   if(boot_time_window > 0)
   {
     boot_time_double = getRandom()->Uniform(0,1)*boot_time_window_double;
     boot_time = inHost()->d2t(boot_time_double, 0);
   } else boot_time = 0;
   // find out the socket layer protocol session
   sock_master = (SessionMaster*)inHost()->sessionForName(SOCKET_PROTOCOL_NAME);
   if(!sock_master)
     error_quit("ERROR: TCPMaster::init(), missing socket layer.\n");
   // find out the IP layer protocol session
   ip_sess = inHost()->getNetworkLayerProtocol();
   assert(ip_sess);
   // create the slow timer
   Host* owner_host = inHost();
   slow_timer_callback_proc = new Process( (Entity *)owner_host,
                   (void (s3f::Entity::*)(s3f::Activation))&TCPMaster::slow_timer_callback);
   // start the slow timer
   slow_timer_ac = new ProtocolCallbackActivation(this);
   Activation ac (slow_timer_ac);
   double t = calc_slow_timeout(0);
   HandleCode h = owner_host->waitFor( slow_timer_callback_proc, ac, inHost()->d2t(t, 0), owner_host->tie_breaking_seed);
 }
SocketSession * s3f::s3fnet::TCPMaster::createSession (int sock) virtual
Create a new TCP session of the given socket id.
Implements s3f::s3fnet::SessionMaster.
Definition at line 472 of file tcp_master.cc.
References s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), idle_sessions, s3f::s3fnet::ProtocolSession::inHost(), TCP_DUMP, and TCPSession.
 {
   TCP_DUMP(printf("[host=\"%s\"] %s: createSession(sock=%d).\n",
                   inHost()->nhi.toString(), getNowWithThousandSeparator(), sock));
   TCPSession* session = new TCPSession(this, sock);
   assert(session);
   idle_sessions.insert(session);
   return session;
 }
void s3f::s3fnet::TCPMaster::deleteSession (TCPSession * session)
Reclaim a TCP session.
Definition at line 483 of file tcp_master.cc.
References defunct_sessions, separate_session(), s3f::s3fnet::TCPSession::socket, and TCP_DUMP.
Referenced by s3f::s3fnet::TCPSession::release().
 {
   TCP_DUMP(printf("deleteSession(sock=%d).\n", session->socket));
   assert(session);
   separate_session(session);
   defunct_sessions.insert(session);
 }
void s3f::s3fnet::TCPMaster::setConnected (TCPSession * session)
Change the state of the session to connected.
Definition at line 520 of file tcp_master.cc.
References connected_sessions, s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::inHost(), separate_session(), s3f::s3fnet::TCPSession::socket, and TCP_DUMP.
Referenced by s3f::s3fnet::TCPSession::init_state_syn_received(), and s3f::s3fnet::TCPSession::init_state_syn_sent().
 {
   TCP_DUMP(printf("[host=\"%s\"] %s: setConnected(sock=%d).\n",
                   inHost()->nhi.toString(), getNowWithThousandSeparator(), session->socket));
   separate_session(session);
   connected_sessions.insert(session);
 }
void s3f::s3fnet::TCPMaster::setListening (TCPSession * session)
Change the state of the session to listening.
Definition at line 529 of file tcp_master.cc.
References s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::inHost(), listening_sessions, separate_session(), s3f::s3fnet::TCPSession::socket, and TCP_DUMP.
Referenced by s3f::s3fnet::TCPSession::init_state_listen().
 {
   TCP_DUMP(printf("[host=\"%s\"] %s: setListening(sock=%d).\n",
                   inHost()->nhi.toString(), getNowWithThousandSeparator(), session->socket));
   separate_session(session);
   listening_sessions.insert(session);
 }
void s3f::s3fnet::TCPMaster::setIdle (TCPSession * session)
Change the state of the session to idle.
Definition at line 538 of file tcp_master.cc.
References s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), idle_sessions, s3f::s3fnet::ProtocolSession::inHost(), separate_session(), s3f::s3fnet::TCPSession::socket, and TCP_DUMP.
Referenced by s3f::s3fnet::TCPSession::init_state_closed().
 {
   TCP_DUMP(printf("[host=\"%s\"] %s: setIdle(sock=%d).\n",
                   inHost()->nhi.toString(), getNowWithThousandSeparator(), session->socket));
   separate_session(session);
   idle_sessions.insert(session);
 }
void s3f::s3fnet::TCPMaster::enableFastTimeout (TCPSession * session)
Enable a TCP session for fast timeout handling.
Definition at line 547 of file tcp_master.cc.
References calc_fast_timeout, fast_timeout_sessions, fast_timer_ac, fast_timer_callback(), fast_timer_callback_proc, s3f::s3fnet::ProtocolSession::getNow(), s3f::s3fnet::ProtocolSession::inHost(), Entity::t2d(), s3f::s3fnet::Host::tie_breaking_seed, and Entity::waitFor().
Referenced by s3f::s3fnet::TCPSession::send_delay_ack().
 {
   assert(session);
   if(!fast_timer_callback_proc)
   {
     // only need to schedule the time at the first time
     // create the fast timer
     Host* owner_host = inHost();
     fast_timer_callback_proc = new Process( (Entity *)owner_host,
                   (void (s3f::Entity::*)(s3f::Activation))&TCPMaster::fast_timer_callback);
     // start the fast timer
     fast_timer_ac = new ProtocolCallbackActivation(this);
     Activation ac (fast_timer_ac);
     double time = inHost()->t2d(getNow(), 0);
     double t = calc_fast_timeout(time);
     HandleCode h = owner_host->waitFor( fast_timer_callback_proc, ac, inHost()->d2t(t, 0), owner_host->tie_breaking_seed);
   }
   fast_timeout_sessions.insert(session);
 }
void s3f::s3fnet::TCPMaster::disableFastTimeout (TCPSession * session)
Disable a TCP session from fast timeout handling.
Definition at line 567 of file tcp_master.cc.
References fast_timeout_sessions.
Referenced by s3f::s3fnet::TCPSession::cancel_delay_ack(), and s3f::s3fnet::TCPSession::init_state_fin_wait_1().
 {
   assert(session);
   fast_timeout_sessions.erase(session);
 }
void s3f::s3fnet::TCPMaster::slow_timer_callback (Activation ac)
The callback function registered with the slow_timer_callback_proc.
Definition at line 604 of file tcp_master.cc.
References slow_timer_callback_body().
Referenced by init().
 {
         TCPMaster* tm = (TCPMaster*)((ProtocolCallbackActivation*)ac)->session;
     tm->slow_timer_callback_body(ac);
 }
void s3f::s3fnet::TCPMaster::slow_timer_callback_body (Activation ac)
the actual body of the slow_timer_callback function
Definition at line 610 of file tcp_master.cc.
References calc_slow_timeout, connected_sessions, delete_defunct_sessions(), s3f::s3fnet::ProtocolSession::getNow(), s3f::s3fnet::ProtocolSession::inHost(), S3FNET_SET(), slow_timer_callback_proc, Entity::t2d(), and Entity::waitFor().
Referenced by slow_timer_callback().
 {
   delete_defunct_sessions();
   // go through each connected session that requires slow timer; to
   // prevent changes during iteration, we copy the list to an array.
   int mysize;
   if((mysize = connected_sessions.size()) > 0)
   {
     TCPSession** mylist  = new TCPSession*[mysize];
     assert(mylist);
     int idx = 0;
     for(S3FNET_SET(TCPSession*)::iterator iter = connected_sessions.begin(); iter != connected_sessions.end(); iter++, idx++)
       mylist[idx] = (*iter);
     for(idx = 0; idx < mysize; idx++)
       mylist[idx]->slowTimeoutHandling();
     delete[] mylist;
   }
   // reschedule for the next timeout
   double time = inHost()->t2d(getNow(), 0);
   double t = calc_slow_timeout(time);
   HandleCode h = inHost()->waitFor( slow_timer_callback_proc, ac, inHost()->d2t(t, 0), inHost()->tie_breaking_seed );
 }
void s3f::s3fnet::TCPMaster::fast_timer_callback (Activation ac)
The callback function registered with the fast_timer_callback_proc.
Definition at line 573 of file tcp_master.cc.
References fast_timer_callback_body().
Referenced by enableFastTimeout().
 {
         TCPMaster* tm = (TCPMaster*)((ProtocolCallbackActivation*)ac)->session;
     tm->fast_timer_callback_body(ac);
 }
void s3f::s3fnet::TCPMaster::fast_timer_callback_body (Activation ac)
the actual body of the fast_timer_callback function
Definition at line 579 of file tcp_master.cc.
References calc_fast_timeout, delete_defunct_sessions(), fast_timeout_sessions, fast_timer_callback_proc, s3f::s3fnet::ProtocolSession::getNow(), s3f::s3fnet::ProtocolSession::inHost(), S3FNET_SET(), Entity::t2d(), and Entity::waitFor().
Referenced by fast_timer_callback().
 {
   delete_defunct_sessions();
   // go through each tcp session that requires fast timer; to prevent
   // changes during iteration, we copy the list to an array.
   int mysize;
   if((mysize = fast_timeout_sessions.size()) > 0)
   {
     TCPSession** mylist  = new TCPSession*[mysize];
     assert(mylist);
     int idx = 0;
     for(S3FNET_SET(TCPSession*)::iterator iter = fast_timeout_sessions.begin(); iter != fast_timeout_sessions.end(); iter++, idx++)
       mylist[idx] = (*iter);
     for(idx = 0; idx < mysize; idx++)
       mylist[idx]->fastTimeoutHandling();
     delete[] mylist;
   }
   // reschedule for the next timeout
   double time = inHost()->t2d(getNow(), 0);
   double t = calc_fast_timeout(time);
   HandleCode h = inHost()->waitFor( fast_timer_callback_proc, ac, inHost()->d2t(t, 0), inHost()->tie_breaking_seed );
 }
int s3f::s3fnet::TCPMaster::push (Activation msg, ProtocolSession * hi_sess, void * extinfo = 0, size_t extinfo_size = 0) protected virtual
Send a message down the protocol stack to a lower layer.
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 409 of file tcp_master.cc.
References s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::inHost(), ip_sess, s3f::s3fnet::ProtocolSession::pushdown(), and TCP_DUMP.
 {
   TCP_DUMP(printf("[host=\"%s\"] %s: push().\n", inHost()->nhi.toString(), getNowWithThousandSeparator()));
   return ip_sess->pushdown(msg, this, extinfo, extinfo_size);
 }
int s3f::s3fnet::TCPMaster::pop (Activation msg, ProtocolSession * lo_sess, void * extinfo = 0, size_t extinfo_size = 0) protected virtual
Receive a message up from the protocol stack.
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 416 of file tcp_master.cc.
References connected_sessions, delete_defunct_sessions(), s3f::s3fnet::IPOptionToAbove::dst_ip, s3f::s3fnet::TCPMessage::dst_port, s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::IPPrefix::ip2txt(), listening_sessions, S3FNET_SET(), s3f::s3fnet::IPOptionToAbove::src_ip, s3f::s3fnet::TCPMessage::src_port, and TCP_DUMP.
 {
   // to be safe, delete all defunct sessions first
   delete_defunct_sessions();
   IPOptionToAbove* ops  = (IPOptionToAbove*)extinfo;
   TCPMessage* tcphdr = (TCPMessage*)msg;
   // check each connected tcp session
   S3FNET_SET(TCPSession*)::iterator iter;
   for(iter = connected_sessions.begin(); iter != connected_sessions.end(); iter++)
   {
     if((*iter)->dst_ip   == ops->src_ip &&
        (*iter)->src_port == tcphdr->dst_port &&
        (*iter)->dst_port == tcphdr->src_port)
     {
       TCP_DUMP(char buf1[50]; char buf2[50];
                printf("[host=\"%s\"] %s: pop(), found matching socket "
                       "(src=\"%s:%d\", dst=\"%s:%d\").\n",
                       inHost()->nhi.toString(), getNowWithThousandSeparator(),
                       IPPrefix::ip2txt((*iter)->src_ip, buf1), (*iter)->src_port,
                       IPPrefix::ip2txt((*iter)->dst_ip, buf2), (*iter)->dst_port));
       (*iter)->receive(tcphdr);
       return 0;
     }
   }
   // check each listening tcp session
   for(iter = listening_sessions.begin(); iter != listening_sessions.end(); iter++)
   {
     if((*iter)->src_port == tcphdr->dst_port)
     {
       // if the port is a listening port, this tcp session will turn
       // into a connected tcp session and at the same time, the upper
       // layer will trigger another listening tcp session.
       (*iter)->src_ip   = ops->dst_ip;
       (*iter)->dst_ip   = ops->src_ip;
       (*iter)->dst_port = tcphdr->src_port;
       TCP_DUMP(char buf1[50]; char buf2[50];
                printf("[host=\"%s\"] %s: pop(), found listening socket "
                       "(src=\"%s:%d\", dst=\"%s:%d\").\n",
                       inHost()->nhi.toString(), getNowWithThousandSeparator(),
                       IPPrefix::ip2txt((*iter)->src_ip, buf1), (*iter)->src_port,
                       IPPrefix::ip2txt((*iter)->dst_ip, buf2), (*iter)->dst_port));
       (*iter)->receive(tcphdr);
       return 0;
     }
   }
   return 0;
 }
void s3f::s3fnet::TCPMaster::separate_session (TCPSession * sess) protected
Disassociate a protocol session from managed lists.
Definition at line 493 of file tcp_master.cc.
References connected_sessions, fast_timeout_sessions, idle_sessions, listening_sessions, and S3FNET_SET().
Referenced by deleteSession(), setConnected(), setIdle(), and setListening().
 {
   S3FNET_SET(TCPSession*)::iterator iter;
   if((iter = listening_sessions.find(session)) != listening_sessions.end())
     listening_sessions.erase(iter);
   else if((iter = connected_sessions.find(session)) != connected_sessions.end())
     connected_sessions.erase(iter);
   else if((iter = idle_sessions.find(session)) != idle_sessions.end())
     idle_sessions.erase(iter);
   if((iter = fast_timeout_sessions.find(session)) != fast_timeout_sessions.end())
     fast_timeout_sessions.erase(iter);
 }
void s3f::s3fnet::TCPMaster::delete_defunct_sessions () protected
Finally remove sessions reclaimed using the deleteSession method.
Definition at line 510 of file tcp_master.cc.
References defunct_sessions, and S3FNET_SET().
Referenced by fast_timer_callback_body(), pop(), slow_timer_callback_body(), and ~TCPMaster().
 {
   for(S3FNET_SET(TCPSession*)::iterator iter = defunct_sessions.begin();
       iter != defunct_sessions.end(); iter++)
   {
     delete (*iter);
   }
   defunct_sessions.clear();
 }
int s3f::s3fnet::TCPMaster::getVersion () inline
Definition at line 126 of file tcp_master.h.
References tcp_version.
Referenced by s3f::s3fnet::TCPSession::process_dup_acks(), s3f::s3fnet::TCPSession::process_new_acks(), s3f::s3fnet::TCPSession::sender_recv_sack(), s3f::s3fnet::TCPSession::slow_timeout_handling_helper(), and s3f::s3fnet::TCPSession::timeout_resend().
 { return tcp_version; }
uint32 s3f::s3fnet::TCPMaster::getISS () inline
Definition at line 127 of file tcp_master.h.
References iss.
Referenced by s3f::s3fnet::TCPSession::active_open(), and s3f::s3fnet::TCPSession::process_SYN().
 { return iss; }
uint32 s3f::s3fnet::TCPMaster::getMSS () inline
Definition at line 128 of file tcp_master.h.
References mss.
Referenced by s3f::s3fnet::TCPSession::init_state_closed(), and s3f::s3fnet::TCPSession::init_state_listen().
 { return mss; }
uint32 s3f::s3fnet::TCPMaster::getRcvWndSize () inline
Definition at line 129 of file tcp_master.h.
References rcv_wnd_size.
Referenced by s3f::s3fnet::TCPSession::allocate_buffers(), s3f::s3fnet::TCPSession::init_state_closed(), s3f::s3fnet::TCPSession::init_state_listen(), and s3f::s3fnet::TCPSession::update_remote_window_size().
 { return rcv_wnd_size; }
uint32 s3f::s3fnet::TCPMaster::getSndBufSize () inline
Definition at line 130 of file tcp_master.h.
References snd_buf_size.
Referenced by s3f::s3fnet::TCPSession::allocate_buffers().
 { return snd_buf_size; }
uint32 s3f::s3fnet::TCPMaster::getSndWndSize () inline
Definition at line 131 of file tcp_master.h.
References snd_wnd_size.
Referenced by s3f::s3fnet::TCPSession::allocate_buffers().
 { return snd_wnd_size; }
uint32 s3f::s3fnet::TCPMaster::getMaxRxmit () inline
Definition at line 132 of file tcp_master.h.
References max_rxmit.
Referenced by s3f::s3fnet::TCPSession::slow_timeout_handling_helper().
 { return max_rxmit; }
ltime_t s3f::s3fnet::TCPMaster::getSlowTimeout () inline
Definition at line 133 of file tcp_master.h.
References slow_timeout.
Referenced by s3f::s3fnet::TCPSession::slowTimeoutHandling().
 { return slow_timeout; }
double s3f::s3fnet::TCPMaster::getSlowTimeoutDouble () inline
Definition at line 134 of file tcp_master.h.
References slow_timeout_double.
Referenced by s3f::s3fnet::TCPSession::backoff_timeout(), and s3f::s3fnet::TCPSession::update_timeout().
 { return slow_timeout_double; }
ltime_t s3f::s3fnet::TCPMaster::getFastTimeout () inline
Definition at line 135 of file tcp_master.h.
References fast_timeout.
 { return fast_timeout; }
double s3f::s3fnet::TCPMaster::getFastTimeoutDouble () inline
Definition at line 136 of file tcp_master.h.
References fast_timeout_double.
 { return fast_timeout_double; }
ltime_t s3f::s3fnet::TCPMaster::getIdleTimeout () inline
Definition at line 137 of file tcp_master.h.
References idle_timeout.
 { return idle_timeout; }
ltime_t s3f::s3fnet::TCPMaster::getMSL () inline
Definition at line 138 of file tcp_master.h.
References msl.
Referenced by s3f::s3fnet::TCPSession::init_state_time_wait().
 { return msl; }
bool s3f::s3fnet::TCPMaster::isDelayedAck () inline
Definition at line 139 of file tcp_master.h.
References delayed_ack.
Referenced by s3f::s3fnet::TCPSession::acknowledge(), s3f::s3fnet::TCPSession::init_state_fin_wait_1(), and s3f::s3fnet::TCPSession::init_state_last_ack().
 { return delayed_ack; }
uint32 s3f::s3fnet::TCPMaster::getMaxConWnd () inline
Definition at line 140 of file tcp_master.h.
References max_cong_wnd.
Referenced by s3f::s3fnet::TCPSession::check_cwnd(), s3f::s3fnet::TCPSession::process_dup_acks(), and s3f::s3fnet::TCPSession::process_new_acks().
 { return max_cong_wnd>0?max_cong_wnd:UINT_MAX; }
uint32 s3f::s3fnet::TCPMaster::getInitThresh () inline
Definition at line 141 of file tcp_master.h.
References TCP_DEFAULT_INIT_THRESH.
Referenced by s3f::s3fnet::TCPSession::init_state_closed(), s3f::s3fnet::TCPSession::init_state_established(), and s3f::s3fnet::TCPSession::init_state_listen().
 { return TCP_DEFAULT_INIT_THRESH; }
typedef s3f::s3fnet::TCPMaster::S3FNET_SET (TCPSession *) private
Referenced by delete_defunct_sessions(), fast_timer_callback_body(), pop(), separate_session(), slow_timer_callback_body(), and ~TCPMaster().
ProtocolSession* s3f::s3fnet::SessionMaster::getSocketMaster () inline inherited
Return the socket master, the protocol session directly above the protocol session master.
Definition at line 472 of file socket_session.h.
References s3f::s3fnet::SessionMaster::sock_master.
Referenced by s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::TCPSession::clear_app_state(), s3f::s3fnet::UDPSession::release(), s3f::s3fnet::UDPSession::wake_app(), and s3f::s3fnet::TCPSession::wake_app().
 { return sock_master; }
void s3f::s3fnet::ProtocolSession::wrapup () virtual inherited
The method is used to wrap up the protocol session.
It is called when the simulation finishes. It is designed to give user a chance to report simulation statistics. The default behavior is doing nothing. Subclass may override this method for protocol specific dealings. Note that there is no specific order in which wrapup is called for protocol sessions in a protocol graph.
Definition at line 59 of file protocol_session.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolSession::initialized(), s3f::s3fnet::ProtocolSession::name, s3f::s3fnet::ProtocolSession::PSESS_WRAPPED_UP, s3f::s3fnet::ProtocolSession::stage, and s3f::s3fnet::ProtocolSession::wrapped_up().
 {
   // Make sure this init function at the base class should be called
   // by the derived function!
   if(!initialized())
     error_quit("ERROR: ProtocolSession \"%s\" wrapup() called before init(), "
                "forgot to call base class's init() in your derived class?\n", name);
   else if(wrapped_up())
     error_quit("ERROR: duplicate calls to ProtocolSession::wrapup(): "
                "session name is \"%s\".\n", name);
   else stage = PSESS_WRAPPED_UP;
 }
int s3f::s3fnet::ProtocolSession::pushdown (Activation msg, ProtocolSession * hi_sess, void * extinfo = 0, size_t extinfo_size = 0) inherited
The original push method is divided into pushdown() and push().
The pushdown method is the generic part of the code, which is reserved for modeling the handling of messages transferred between protocol layers.
See Also
ProtocolSession::push method for details.
Definition at line 72 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::push().
Referenced by s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), s3f::s3fnet::IPSession::control(), s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), s3f::s3fnet::OpenFlowSwitchSession::OutputControl(), s3f::s3fnet::OpenFlowSwitchSession::OutputPacket(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::UDPMaster::push(), push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::send(), and s3f::s3fnet::TCPSession::send_data().
 {
   return push(msg, hi_sess, extinfo, extinfo_size);
 }
int s3f::s3fnet::ProtocolSession::popup (Activation msg, ProtocolSession * lo_sess, void * extinfo = 0, size_t extinfo_size = 0) inherited
The original pop method is divided into popup() and pop().
The popup method is the generic part of the code, which is reserved for modeling the handling of messages transferred between protocol layers.
See Also
ProtocolSession::pop method for details.
Definition at line 77 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::pop().
Referenced by s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::IPSession::push(), and s3f::s3fnet::SimplePhy::receivePacket().
 {
   return pop(msg, lo_sess, extinfo, extinfo_size);
 }
int s3f::s3fnet::ProtocolSession::control (int ctrltyp, void * ctrlmsg, ProtocolSession * sess) virtual inherited
The control method is used by the protocol session to receive control messages (or information queries) from other protocol sessions both above and below this protocol session on the stack.
The derived class should override this method to provide support for handling different control messages. In this case, the derived class should invoke this method when encountering a control type that it does not know to to process.
The control messages are distinguished via types. The ctrl type is an integer; its meaning is specified by the particular protocol. The users are recommended to use ctrl type values beyond 1000 (excluding 1000). The values within 1000 are reserved. The control message is of type void* and should be cast to the appropriate types accordingly. Note that, unless specified otherwise, the caller is responsible to reclaim the control message once the method returns. The protocol session that invoking this method will have a reference to itself in the third argument.
The method returns an integer, indicating whether the control message is successfully processed. Unless specified otherwise, a zero means success. Non-zero means trouble and the returned value can be used as the error number, the meaning of which is specified by each particular protocol.
For information on a specific control type, see s3f::s3fnet::ProtocolSessionCtrlTypes
Reimplemented in s3f::s3fnet::IPSession, s3f::s3fnet::NBSocketMaster, s3f::s3fnet::SocketMaster, s3f::s3fnet::OpenFlowSwitchSession, s3f::s3fnet::SimplePhy, s3f::s3fnet::OpenVZEventSession, s3f::s3fnet::OpenFlowControllerSession, s3f::s3fnet::UDPMaster, s3f::s3fnet::DummySession, s3f::s3fnet::LowestProtocolSession, and s3f::s3fnet::NicProtocolSession.
Definition at line 92 of file protocol_session.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::PSESS_CTRL_SESSION_GET_INTERFACE, s3f::s3fnet::PSESS_CTRL_SESSION_IS_LOWEST, s3f::s3fnet::PSESS_CTRL_SESSION_SET_CHILD, and s3f::s3fnet::PSESS_CTRL_SESSION_SET_PARENT.
Referenced by s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::TCPSession::clear_app_state(), s3f::s3fnet::Host::config(), s3f::s3fnet::NicProtocolSession::control(), s3f::s3fnet::DummySession::control(), s3f::s3fnet::UDPMaster::control(), s3f::s3fnet::OpenFlowControllerSession::control(), s3f::s3fnet::OpenVZEventSession::control(), s3f::s3fnet::OpenFlowSwitchSession::control(), s3f::s3fnet::SocketMaster::control(), s3f::s3fnet::NBSocketMaster::control(), s3f::s3fnet::IPSession::control(), s3f::s3fnet::Host::loadForwardingTable(), s3f::s3fnet::UDPSession::release(), s3f::s3fnet::UDPSession::wake_app(), and s3f::s3fnet::TCPSession::wake_app().
 {
   switch(ctrltype) {
   case PSESS_CTRL_SESSION_IS_LOWEST:
     assert(ctrlmsg);
     *((bool*)ctrlmsg) = false;
     return 0;
   case PSESS_CTRL_SESSION_GET_INTERFACE:
     assert(ctrlmsg);
     *((NetworkInterface**)ctrlmsg) = 0;
     return 0;
   case PSESS_CTRL_SESSION_SET_PARENT:
   case PSESS_CTRL_SESSION_SET_CHILD:
     return 0;
   default:
     // all control types should be handled at this point; if not, we
     // should report the problem
     error_quit("ERROR: ProtocolSession::control(), "
                "unknown control type: %d.\n", ctrltype);
   }
   return 0;
 }
ProtocolGraph* s3f::s3fnet::ProtocolSession::inGraph () inline inherited
The method returns the protocol graph in which this protocol session resides.
Definition at line 178 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::ingraph.
Referenced by s3f::s3fnet::SimplePhy::config(), s3f::s3fnet::SimplePhy::control(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::SimpleMac::init(), s3f::s3fnet::SimplePhy::init(), s3f::s3fnet::RedQueue::init(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::SimplePhy::push(), s3f::s3fnet::SimplePhy::receivePacket(), s3f::s3fnet::SimplePhy::sendPacket(), s3f::s3fnet::SimpleMac::SimpleMac(), s3f::s3fnet::SimplePhy::SimplePhy(), s3f::s3fnet::SimpleMac::~SimpleMac(), and s3f::s3fnet::SimplePhy::~SimplePhy().
 { return ingraph; }
Host * s3f::s3fnet::ProtocolSession::inHost () virtual inherited
Return a pointer to the host owning this protocol session.
Reimplemented in s3f::s3fnet::NicProtocolSession.
Definition at line 118 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::ingraph.
Referenced by s3f::s3fnet::UDPSession::abort(), s3f::s3fnet::SocketMaster::abort(), s3f::s3fnet::NBSocketMaster::abort(), s3f::s3fnet::SocketMaster::accept(), s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::accept1a(), s3f::s3fnet::SocketMaster::accept1b(), s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SocketMaster::accept2b(), s3f::s3fnet::OpenFlowSwitchSession::AddFlow(), s3f::s3fnet::TCPSession::backoff_timeout(), s3f::s3fnet::SocketMaster::bind(), s3f::s3fnet::NBSocketMaster::bind(), s3f::s3fnet::SocketMaster::block_till(), s3f::s3fnet::NBSocketMaster::block_till(), s3f::s3fnet::BTCPClientSession::BTCPClientSession(), s3f::s3fnet::OpenFlowSwitchSession::BufferFromPacket(), s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::UDPServerSession::client_connected(), s3f::s3fnet::SocketMaster::close(), s3f::s3fnet::NBSocketMaster::close(), s3f::s3fnet::SocketMaster::close1(), s3f::s3fnet::NBSocketMaster::close1(), s3f::s3fnet::UDPMaster::config(), s3f::s3fnet::DummySession::config(), s3f::s3fnet::TCPClientSession::config(), s3f::s3fnet::UDPServerSession::config(), s3f::s3fnet::UDPClientSession::config(), s3f::s3fnet::TCPServerSession::config(), config(), s3f::s3fnet::NBTCPClientSession::config(), s3f::s3fnet::BTCPClientSession::config(), s3f::s3fnet::IPSession::config(), s3f::s3fnet::NBTCPServerSession::config(), s3f::s3fnet::UDPSession::connect(), s3f::s3fnet::SocketMaster::connect(), s3f::s3fnet::NBSocketMaster::connect(), s3f::s3fnet::SocketMaster::connect1(), s3f::s3fnet::NBSocketMaster::connect1(), s3f::s3fnet::SocketMaster::connected(), s3f::s3fnet::NBSocketMaster::connected(), s3f::s3fnet::UDPMaster::control(), s3f::s3fnet::SocketMaster::control(), s3f::s3fnet::NBSocketMaster::control(), s3f::s3fnet::IPSession::control(), createSession(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::UDPServerSession::data_sent(), s3f::s3fnet::TCPServerSession::data_sent(), s3f::s3fnet::UDPSession::disconnect(), enableFastTimeout(), s3f::s3fnet::SocketMaster::eof(), s3f::s3fnet::NBSocketMaster::eof(), s3f::s3fnet::UDPClientSessionContinuation::failure(), s3f::s3fnet::UDPServerSessionContinuation::failure(), s3f::s3fnet::TCPServerSessionContinuation::failure(), s3f::s3fnet::TCPClientSessionContinuation::failure(), s3f::s3fnet::BTCPClientSessionContinuation::failure(), fast_timer_callback_body(), s3f::s3fnet::Stats::FlowStatsDump(), s3f::s3fnet::OpenFlowSwitchSession::FlowTableLookup(), s3f::s3fnet::IPSession::get_parent_by_protocol(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::ProtocolSession::getNow(), s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::OpenFlowSwitchSession::HandleControlInput(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), s3f::s3fnet::DummySession::init(), s3f::s3fnet::UDPMaster::init(), s3f::s3fnet::OpenFlowControllerSession::init(), s3f::s3fnet::OpenVZEventSession::init(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPServerSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::TCPServerSession::init(), init(), s3f::s3fnet::OpenFlowSwitchSession::init(), s3f::s3fnet::NBTCPClientSession::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::SocketMaster::init(), s3f::s3fnet::IPSession::init(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::NBSocketMaster::init(), s3f::s3fnet::NBTCPServerSession::init(), s3f::s3fnet::TCPSession::init_state_closed(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::IPSession::IPSession(), s3f::s3fnet::UDPSession::listen(), s3f::s3fnet::SocketMaster::listen(), s3f::s3fnet::NBSocketMaster::listen(), s3f::s3fnet::IPSession::load_forwarding_table(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), s3f::s3fnet::OpenFlowSwitchSession::ModFlow(), s3f::s3fnet::NBSocketMaster::NBSocketMaster(), s3f::s3fnet::NBTCPClientSession::NBTCPClientSession(), s3f::s3fnet::NBTCPServerSession::NBTCPServerSession(), s3f::s3fnet::NBTCPClientSession::non_blocking_loop(), s3f::s3fnet::NBTCPServerSession::non_blocking_loop(), s3f::s3fnet::OpenFlowSwitchSession::OutputControl(), s3f::s3fnet::OpenFlowSwitchSession::OutputPacket(), s3f::s3fnet::OpenFlowSwitchSession::OutputPort(), s3f::s3fnet::OpenFlowControllerSession::pop(), s3f::s3fnet::UDPMaster::pop(), s3f::s3fnet::OpenVZEventSession::pop(), s3f::s3fnet::OpenFlowSwitchSession::pop(), pop(), s3f::s3fnet::IPSession::pop(), s3f::s3fnet::LearningController::process_recv_packet(), s3f::s3fnet::UDPMaster::push(), push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::receive(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::LearningControllerSession::ReceiveFromSwitch(), s3f::s3fnet::OpenFlowSwitchSession::ReceivePacketOut(), s3f::s3fnet::OpenFlowSwitchSession::ReceivePortMod(), s3f::s3fnet::OpenFlowSwitchSession::ReceiveStatsRequest(), s3f::s3fnet::SocketMaster::recv(), s3f::s3fnet::NBSocketMaster::recv(), s3f::s3fnet::SocketMaster::recv1(), s3f::s3fnet::NBSocketMaster::recv1(), s3f::s3fnet::UDPServerSession::request_received(), s3f::s3fnet::TCPServerSession::request_received(), s3f::s3fnet::UDPClientSession::request_sent(), s3f::s3fnet::TCPClientSession::request_sent(), s3f::s3fnet::NBTCPClientSessionContinuation::resume(), s3f::s3fnet::NBTCPServerSessionContinuation::resume(), s3f::s3fnet::OpenFlowSwitchSession::RunThroughFlowTable(), s3f::s3fnet::UDPSession::send(), s3f::s3fnet::SocketMaster::send(), s3f::s3fnet::NBSocketMaster::send(), s3f::s3fnet::SocketMaster::send1(), s3f::s3fnet::NBSocketMaster::send1(), s3f::s3fnet::TCPSession::send_data(), s3f::s3fnet::OpenFlowSwitchSession::SendFlowExpired(), s3f::s3fnet::OpenFlowSwitchSession::SendOpenflowBuffer(), s3f::s3fnet::OpenFlowSwitchSession::SendPortStatus(), s3f::s3fnet::UDPClientSession::server_connected(), s3f::s3fnet::TCPClientSession::server_connected(), s3f::s3fnet::BTCPClientSession::server_connected(), s3f::s3fnet::UDPServerSession::session_closed(), s3f::s3fnet::UDPClientSession::session_closed(), s3f::s3fnet::TCPClientSession::session_closed(), s3f::s3fnet::TCPServerSession::session_closed(), s3f::s3fnet::BTCPClientSession::session_closed(), setConnected(), s3f::s3fnet::OpenFlowSwitchSession::SetController(), setIdle(), setListening(), s3f::s3fnet::UDPSession::setSource(), slow_timer_callback_body(), s3f::s3fnet::TCPSession::slowTimeoutHandling(), s3f::s3fnet::SocketMaster::socket(), s3f::s3fnet::NBSocketMaster::socket(), s3f::s3fnet::SocketMaster::SocketMaster(), s3f::s3fnet::UDPServerSession::start_on(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPServerSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), s3f::s3fnet::NBTCPClientSession::start_on(), s3f::s3fnet::BTCPClientSession::start_on(), s3f::s3fnet::NBTCPServerSession::start_on(), s3f::s3fnet::NBTCPServerSessionContinuation::success(), s3f::s3fnet::TCPClientSession::TCPClientSession(), TCPMaster(), s3f::s3fnet::TCPServerSession::TCPServerSession(), s3f::s3fnet::TCPSession::TCPSession(), s3f::s3fnet::UDPClientSession::timeout(), s3f::s3fnet::TCPClientSession::timeout(), s3f::s3fnet::BTCPClientSession::timeout(), s3f::s3fnet::UDPClientSession::UDPClientSession(), s3f::s3fnet::UDPMaster::UDPMaster(), s3f::s3fnet::UDPServerSession::UDPServerSession(), s3f::s3fnet::UDPSession::UDPSession(), s3f::s3fnet::TCPSession::update_timeout(), s3f::s3fnet::IPSession::verify_local_ip_address(), and s3f::s3fnet::UDPSession::wake_app().
 {
   return dynamic_cast<Host*>(ingraph);
 }
Random::RNG* s3f::s3fnet::ProtocolSession::getRandom () inline inherited
The method returns a pointer to the random number generator.
Definition at line 200 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::sess_rng.
Referenced by s3f::s3fnet::DroptailQueue::calibrate(), s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::DummySession::init(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPClientSession::init(), init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), and s3f::s3fnet::NetworkInterface::receivePacket().
 { return sess_rng;}
ltime_t s3f::s3fnet::ProtocolSession::getNow () inherited
The method returns the current simulation time.
To be safe, please do NOT call this function after initialization and before wrapup phase. That is, it is unsafe to call this method in the constructor, destructor, config, init, and wrapup methods. The time service is carried out by the host's owner community. This method just directs the call to the community. It's given here for convenience.
Definition at line 123 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::inHost(), and Entity::now().
Referenced by s3f::s3fnet::DroptailQueue::calibrate(), s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), enableFastTimeout(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), fast_timer_callback_body(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::TCPSession::now(), s3f::s3fnet::OpenVZEventSession::pop(), slow_timer_callback_body(), s3f::s3fnet::SocketMaster::socket(), s3f::s3fnet::NBSocketMaster::socket(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), and s3f::s3fnet::BTCPClientSession::start_on().
 {
   return inHost()->now();
 }
char * s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator () inherited
For printing the current simulation time in a better readable format.
Definition at line 128 of file protocol_session.cc.
References s3f::s3fnet::Host::getNowWithThousandSeparator(), and s3f::s3fnet::ProtocolSession::inHost().
Referenced by s3f::s3fnet::UDPSession::abort(), s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::UDPSession::connect(), createSession(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::UDPServerSession::data_sent(), s3f::s3fnet::TCPServerSession::data_sent(), s3f::s3fnet::UDPSession::disconnect(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::UDPSession::listen(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), s3f::s3fnet::DummySession::pop(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::OpenVZEventSession::pop(), s3f::s3fnet::UDPMaster::pop(), pop(), s3f::s3fnet::IPSession::pop(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::UDPMaster::push(), s3f::s3fnet::SimplePhy::push(), push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::receive(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::SimplePhy::receivePacket(), s3f::s3fnet::UDPServerSession::request_received(), s3f::s3fnet::TCPServerSession::request_received(), s3f::s3fnet::UDPClientSession::request_sent(), s3f::s3fnet::TCPClientSession::request_sent(), s3f::s3fnet::UDPSession::send(), s3f::s3fnet::TCPSession::send_data(), s3f::s3fnet::SimplePhy::sendPacket(), s3f::s3fnet::UDPClientSession::server_connected(), s3f::s3fnet::TCPClientSession::server_connected(), s3f::s3fnet::BTCPClientSession::server_connected(), s3f::s3fnet::UDPServerSession::session_closed(), s3f::s3fnet::UDPClientSession::session_closed(), s3f::s3fnet::TCPClientSession::session_closed(), s3f::s3fnet::TCPServerSession::session_closed(), s3f::s3fnet::BTCPClientSession::session_closed(), setConnected(), setIdle(), setListening(), s3f::s3fnet::UDPSession::setSource(), s3f::s3fnet::TCPSession::slowTimeoutHandling(), s3f::s3fnet::UDPServerSession::start_on(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPServerSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), s3f::s3fnet::BTCPClientSession::start_on(), s3f::s3fnet::TCPSession::TCPSession(), s3f::s3fnet::UDPClientSession::timeout(), s3f::s3fnet::TCPClientSession::timeout(), s3f::s3fnet::BTCPClientSession::timeout(), s3f::s3fnet::UDPSession::UDPSession(), s3f::s3fnet::TCPSession::update_timeout(), and s3f::s3fnet::UDPSession::wake_app().
 {
         return inHost()->getNowWithThousandSeparator();
 }
int s3f::s3fnet::ProtocolSession::configured () inline inherited
This method returns true if the protocol session has been configured.
This method is used to make sure we configure the protocol session before initializing it.
Definition at line 221 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_CONFIGURED, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::config(), and s3f::s3fnet::ProtocolSession::init().
 { return stage >= PSESS_CONFIGURED; }
int s3f::s3fnet::ProtocolSession::initialized () inline inherited
This method returns true if the protocol session has been initialized.
This can be used to sequence calls to the init method of protocol sessions. For example, if protocol session A requires protocol session B to be initialized before A can be initialized, A's init method can call B's init method as long as B's initialized() returns true. The system does not enforce any ordering in its calls the init methods of all protocol sessions declared in the dml configuration.
Definition at line 233 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_INITIALIZED, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::init(), and s3f::s3fnet::ProtocolSession::wrapup().
 { return stage >= PSESS_INITIALIZED; }
int s3f::s3fnet::ProtocolSession::wrapped_up () inline inherited
This method returns true if the protocol session has been wrapped up.
This can be used to sequence calls to the wrapup method of protocol sessions. For example, if protocol session A requires protocol session B to be wrapped up before A can be wrapped up, A's wrapup method can call B's wrapup method as long as B's wrapped_up() returns true. The system does not enforce any ordering in its calls the wrapup methods of all protocol sessions declared in the dml configuration.
Definition at line 245 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_WRAPPED_UP, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::wrapup().
 { return stage >= PSESS_WRAPPED_UP; }
virtual const char* s3f::s3fnet::ProtocolSession::psesstype () inline virtual inherited
Reimplemented in s3f::s3fnet::NBSocketMaster, and s3f::s3fnet::SocketMaster.
Definition at line 247 of file protocol_session.h.
 { return "GENERIC"; } // DEBUG
virtual int s3f::s3fnet::ProtocolSession::instantiation_type () inline protected virtual inherited
This method controls how protocol instances can coexist with one another.
It returns one of the following:
PROT_UNIQUE_INSTANCE (default): allows only one instance for each type of protocol per protocol stack;
PROT_MULTIPLE_INSTANCES: allows multiple instances of the same implementation for each type of protocol per protocol stack;
PROT_MULTIPLE_IMPLEMENTATIONS: allows multiple instances from different implementations of the same protocol to exist on the protocol stack.
Reimplemented in s3f::s3fnet::BTCPClientSession, and s3f::s3fnet::TCPClientSession.
Definition at line 269 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PROT_UNIQUE_INSTANCE.
Referenced by s3f::s3fnet::ProtocolGraph::insert_session().
 { return PROT_UNIQUE_INSTANCE; }
Member Data Documentation
Process* s3f::s3fnet::TCPMaster::slow_timer_callback_proc
Provide call_back functionality for implementing the slow timer in the TCPMaster this S3F process is used by waitFor() function.
Definition at line 94 of file tcp_master.h.
Referenced by init(), and slow_timer_callback_body().
Process* s3f::s3fnet::TCPMaster::fast_timer_callback_proc
Provide call_back functionality for implementing the fast timer in the TCPMaster this S3F process is used by waitFor() function.
Definition at line 97 of file tcp_master.h.
Referenced by enableFastTimeout(), and fast_timer_callback_body().
ProtocolCallbackActivation* s3f::s3fnet::TCPMaster::slow_timer_ac
Storing the data for the slow timer callback function.
In this case, the TCPMaster object is stored.
Definition at line 107 of file tcp_master.h.
Referenced by init().
ProtocolCallbackActivation* s3f::s3fnet::TCPMaster::fast_timer_ac
Storing the data for the fast timer callback function.
In this case, the TCPMaster object is stored.
Definition at line 109 of file tcp_master.h.
Referenced by enableFastTimeout().
TCP_SESSIONS_SET s3f::s3fnet::TCPMaster::listening_sessions private
TCP sessions that are listening.
Definition at line 147 of file tcp_master.h.
Referenced by pop(), separate_session(), setListening(), and ~TCPMaster().
TCP_SESSIONS_SET s3f::s3fnet::TCPMaster::connected_sessions private
TCP sessions that are connected with peers.
Definition at line 150 of file tcp_master.h.
Referenced by pop(), separate_session(), setConnected(), slow_timer_callback_body(), and ~TCPMaster().
TCP_SESSIONS_SET s3f::s3fnet::TCPMaster::idle_sessions private
TCP sessions that are idle.
Definition at line 153 of file tcp_master.h.
Referenced by createSession(), separate_session(), setIdle(), and ~TCPMaster().
TCP_SESSIONS_SET s3f::s3fnet::TCPMaster::fast_timeout_sessions private
TCP Sessions to be called when fast timer expires.
Definition at line 156 of file tcp_master.h.
Referenced by disableFastTimeout(), enableFastTimeout(), fast_timer_callback_body(), separate_session(), and ~TCPMaster().
TCP_SESSIONS_SET s3f::s3fnet::TCPMaster::defunct_sessions private
TCP sessions to be deleted.
Definition at line 159 of file tcp_master.h.
Referenced by delete_defunct_sessions(), and deleteSession().
int s3f::s3fnet::TCPMaster::tcp_version private
To identify the TCP variant.
Definition at line 162 of file tcp_master.h.
Referenced by config(), getVersion(), and TCPMaster().
uint32 s3f::s3fnet::TCPMaster::iss private
Initial sequence number.
Definition at line 165 of file tcp_master.h.
Referenced by config(), getISS(), and TCPMaster().
uint32 s3f::s3fnet::TCPMaster::mss private
Maximum segment size.
Definition at line 168 of file tcp_master.h.
Referenced by config(), getMSS(), and TCPMaster().
uint32 s3f::s3fnet::TCPMaster::rcv_wnd_size private
Receive window size.
Definition at line 171 of file tcp_master.h.
Referenced by config(), getRcvWndSize(), and TCPMaster().
uint32 s3f::s3fnet::TCPMaster::snd_wnd_size private
Send window size.
Definition at line 174 of file tcp_master.h.
Referenced by config(), getSndWndSize(), and TCPMaster().
uint32 s3f::s3fnet::TCPMaster::snd_buf_size private
Send buffer size.
Definition at line 177 of file tcp_master.h.
Referenced by config(), getSndBufSize(), and TCPMaster().
uint32 s3f::s3fnet::TCPMaster::max_rxmit private
Maximum number of retransmissions of a segment.
Definition at line 180 of file tcp_master.h.
Referenced by config(), getMaxRxmit(), and TCPMaster().
ltime_t s3f::s3fnet::TCPMaster::slow_timeout private
Slow timeout interval.
Definition at line 183 of file tcp_master.h.
Referenced by config(), getSlowTimeout(), and TCPMaster().
double s3f::s3fnet::TCPMaster::slow_timeout_double private
Definition at line 184 of file tcp_master.h.
Referenced by config(), getSlowTimeoutDouble(), and TCPMaster().
ltime_t s3f::s3fnet::TCPMaster::fast_timeout private
Fast timeout interval.
Definition at line 187 of file tcp_master.h.
Referenced by config(), getFastTimeout(), and TCPMaster().
double s3f::s3fnet::TCPMaster::fast_timeout_double private
Definition at line 188 of file tcp_master.h.
Referenced by config(), getFastTimeoutDouble(), and TCPMaster().
ltime_t s3f::s3fnet::TCPMaster::idle_timeout private
Timeout interval for FIN_WAIT_2.
Definition at line 191 of file tcp_master.h.
Referenced by config(), getIdleTimeout(), and TCPMaster().
double s3f::s3fnet::TCPMaster::idle_timeout_double private
Definition at line 192 of file tcp_master.h.
Referenced by config(), and TCPMaster().
ltime_t s3f::s3fnet::TCPMaster::msl private
Maximum segment lifetime.
Definition at line 195 of file tcp_master.h.
Referenced by config(), getMSL(), and TCPMaster().
double s3f::s3fnet::TCPMaster::msl_double private
Definition at line 196 of file tcp_master.h.
Referenced by config(), and TCPMaster().
bool s3f::s3fnet::TCPMaster::delayed_ack private
True if delayed acknowledgment is turned on.
Definition at line 199 of file tcp_master.h.
Referenced by config(), isDelayedAck(), and TCPMaster().
uint32 s3f::s3fnet::TCPMaster::max_cong_wnd private
Maximum congestion window size.
Definition at line 202 of file tcp_master.h.
Referenced by config(), getMaxConWnd(), and TCPMaster().
ltime_t s3f::s3fnet::TCPMaster::boot_time private
The time this TCP master protocol session starts.
Definition at line 205 of file tcp_master.h.
Referenced by init().
double s3f::s3fnet::TCPMaster::boot_time_double private
Definition at line 206 of file tcp_master.h.
Referenced by init().
ltime_t s3f::s3fnet::TCPMaster::boot_time_window private
The time window this TCP master protocol session starts; used to avoid the artificial synchrony in simulation.
Definition at line 210 of file tcp_master.h.
Referenced by config(), init(), and TCPMaster().
double s3f::s3fnet::TCPMaster::boot_time_window_double private
Definition at line 211 of file tcp_master.h.
Referenced by config(), init(), and TCPMaster().
ProtocolSession* s3f::s3fnet::TCPMaster::ip_sess private
The IP layer protocol session, located below this protocol session on the protocol stack.
Definition at line 216 of file tcp_master.h.
Referenced by init(), and push().
ProtocolSession* s3f::s3fnet::SessionMaster::sock_master protected inherited
The socket master above the protocol session master.
Definition at line 483 of file socket_session.h.
Referenced by s3f::s3fnet::SessionMaster::getSocketMaster(), s3f::s3fnet::UDPMaster::init(), and init().
char* s3f::s3fnet::ProtocolSession::name inherited
Symbolic name of the protocol this session implements.
The name of the protocol is derived from the DML 'name' attribute. It must not be NULL once the protocol session is configured.
Definition at line 63 of file protocol_session.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::SimpleMac::init(), s3f::s3fnet::UDPMaster::init(), s3f::s3fnet::SimplePhy::init(), init(), s3f::s3fnet::SocketMaster::init(), s3f::s3fnet::IPSession::init(), s3f::s3fnet::NBSocketMaster::init(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::ProtocolGraph::insert_session(), s3f::s3fnet::ProtocolSession::wrapup(), and s3f::s3fnet::ProtocolSession::~ProtocolSession().
float s3f::s3fnet::ProtocolSession::version inherited
Version number of this protocol implemenntation, represented as a floating point number (e.g., 1.23).
Definition at line 69 of file protocol_session.h.
char* s3f::s3fnet::ProtocolSession::use inherited
Name of the protocol class from which this protocol session is instantiated.
The protocol class must be registered with the Protocols class so that we will be able to instantiate an object from the class. (C++ does not support self-reflection). The class name must not be NULL once the protocol session is configured.
Definition at line 79 of file protocol_session.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::ProtocolGraph::insert_session(), and s3f::s3fnet::ProtocolSession::~ProtocolSession().
ProtocolGraph* s3f::s3fnet::ProtocolSession::ingraph protected inherited
Points to the protocol graph.
Definition at line 335 of file protocol_session.h.
Referenced by s3f::s3fnet::NicProtocolSession::getNetworkInterface(), s3f::s3fnet::ProtocolSession::inGraph(), and s3f::s3fnet::ProtocolSession::inHost().
Random::RNG* s3f::s3fnet::ProtocolSession::sess_rng protected inherited
Pointer to a random number generator.
Definition at line 338 of file protocol_session.h.
Referenced by s3f::s3fnet::ProtocolSession::getRandom(), and s3f::s3fnet::ProtocolSession::init().
int s3f::s3fnet::ProtocolSession::stage protected inherited
This variable indicates the current stage of this protocol session.
Each protocol session will go through four staged: PSESS_CREATED, PSESS_CONFIGURED, PSESS_INITIALIZED, and then PSESS_WRAPPED_UP.
Definition at line 346 of file protocol_session.h.
Referenced by s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::ProtocolSession::configured(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::ProtocolSession::initialized(), s3f::s3fnet::ProtocolSession::wrapped_up(), and s3f::s3fnet::ProtocolSession::wrapup().
The documentation for this class was generated from the following files:
tcp_master.h
tcp_master.cc