S3F: s3f::s3fnet::trie4::Trie4::iterator Class Reference
s3f::s3fnet::trie4::Trie4::iterator Class Reference
#include <trie4.h>
Classes
class NodeNext
Stores iterator's state.
class State
Public Types
enum NextMove { LEFT = 0, RIGHT = 1, UP = 2, UNDEF = 3 }
Enum for iterator movement.
Public Member Functions
iterator ()
iterator constructor
iterator (Trie4 *t)
iterator constructor for Trie4 types
iterator (const Trie4::iterator &it)
iterator copy constructor
~iterator ()
iterator destructor
iterator & operator= (iterator &rhs)
Assignment operator.
int operator== (iterator &rhs)
Equals comparison operator.
int operator!= (iterator &rhs)
Not equals comparison operator.
iterator & operator++ ()
Prefix incr.
TrieNode * operator-> ()
Arrow operator.
S3FNET_STACK (NodeNext *) stateStack
Iterator's state stack.
void print ()
Prints the iterator.
Public Attributes
Trie4 * myTrie
Trie4 reference Generally root for iterator.
TrieNode * currentNode
Current iterator node.
Private Member Functions
void copyStack (S3FNET_STACK(NodeNext *)&from, bool deepCopy=true)
Copy state stack.
void nextNode ()
Move to next node.
Detailed Description
Depth-first iterator.
Definition at line 158 of file trie4.h.
Member Enumeration Documentation
enum s3f::s3fnet::trie4::Trie4::iterator::NextMove
Enum for iterator movement.
Enumerator
LEFT
Iterator should move to the left.
RIGHT
Iterator should move to the right.
UP
Iterator should move up (backwards)
UNDEF
Iterator movement is undefined.
Definition at line 169 of file trie4.h.
                   {
       LEFT  = 0,
       RIGHT = 1,
       UP    = 2,
       UNDEF = 3
     };
Constructor & Destructor Documentation
s3f::s3fnet::trie4::Trie4::iterator::iterator ()
iterator constructor
Definition at line 291 of file trie4.cc.
                         : myTrie(0), currentNode(0), stateStack()
 {}
s3f::s3fnet::trie4::Trie4::iterator::iterator (Trie4 * t)
iterator constructor for Trie4 types
Definition at line 295 of file trie4.cc.
                                 : myTrie(t), currentNode(0),
                                     stateStack()
 {}
s3f::s3fnet::trie4::Trie4::iterator::iterator (const Trie4::iterator & it)
iterator copy constructor
Definition at line 299 of file trie4.cc.
References copyStack(), and S3FNET_STACK().
                                                :
   myTrie(it.myTrie), currentNode(it.currentNode), stateStack()
 {
   if (it.stateStack.size() > 0) {
     // copy stack -- Need to modify the it.stateStack but will put it back.
     // So, casting away const.
     S3FNET_STACK(NodeNext*)& ss = (S3FNET_STACK(NodeNext*)&)it.stateStack;
     copyStack(ss, true); // deep copy
   }
 }
s3f::s3fnet::trie4::Trie4::iterator::~iterator ()
iterator destructor
Definition at line 310 of file trie4.cc.
{
   // destroy state contents
   while (stateStack.size() > 0) {
     iterator::NodeNext* nn = stateStack.top();
     stateStack.pop();
     delete nn;
   }
 }
Member Function Documentation
Trie4::iterator & s3f::s3fnet::trie4::Trie4::iterator::operator= (iterator & rhs)
Assignment operator.
Does deep copy of state stack.
Definition at line 319 of file trie4.cc.
References currentNode, and myTrie.
{
   myTrie = rhs.myTrie;
   currentNode = rhs.currentNode;
   if (rhs.stateStack.size() > 0) {
     // copy stack
     copyStack(rhs.stateStack);
   }
   return *this;
 }
int s3f::s3fnet::trie4::Trie4::iterator::operator== (iterator & rhs)
Equals comparison operator.
Definition at line 349 of file trie4.cc.
References currentNode.
{
   if (currentNode != rhs.currentNode) {
     return 0;
   }
   if (stateStack.size() != rhs.stateStack.size()) {
     return 0;
   }
   if (stateStack.size() > 0 && !(stateStack.top() == rhs.stateStack.top())) {
     return 0;
   }
   return 1;
 }
int s3f::s3fnet::trie4::Trie4::iterator::operator!= (iterator & rhs)
Not equals comparison operator.
Definition at line 362 of file trie4.cc.
{
   return (*this == rhs) ? 0 : 1;
 }
Trie4::iterator & s3f::s3fnet::trie4::Trie4::iterator::operator++ ()
Prefix incr.
operator.
Definition at line 366 of file trie4.cc.
References TRIE4_DUMP.
{
   if (!currentNode) {
     stateStack.push(new NodeNext(myTrie->root, LEFT));
     currentNode = myTrie->root;
     assert(currentNode);
   }
   do {
     nextNode();
   } while (currentNode->index == UINT_MAX  // repeat until node with data found
            && currentNode != myTrie->root); // or reached end
   if (currentNode == myTrie->root) {
     currentNode = 0;
     TRIE4_DUMP(std::cout << currentNode << " stopped (end)" << std::endl);
   } else {
     TRIE4_DUMP(std::cout << currentNode << " stopped (found)" << std::endl);
   }
   return *this;
 }
TrieNode * s3f::s3fnet::trie4::Trie4::iterator::operator-> ()
Arrow operator.
Definition at line 437 of file trie4.cc.
{
   return currentNode;
 }
s3f::s3fnet::trie4::Trie4::iterator::S3FNET_STACK (NodeNext *)
Iterator's state stack.
Referenced by iterator().
void s3f::s3fnet::trie4::Trie4::iterator::print ()
Prints the iterator.
Used primarily for debugging.
Definition at line 442 of file trie4.cc.
{
   std::cout << "Trie4::iterator -- trie=" << myTrie << " currentNode=" << currentNode
        << " stateStack size=" << stateStack.size() << std::endl;
 }
void s3f::s3fnet::trie4::Trie4::iterator::copyStack (S3FNET_STACK(NodeNext *)& from, bool deepCopy = true) private
Copy state stack.
Copies the state stack. Intended as an assignment helper.
Definition at line 330 of file trie4.cc.
References S3FNET_STACK.
Referenced by iterator().
{
   S3FNET_STACK(NodeNext*)& to = stateStack;
   if (from.size() > 0) {
     // pop elem
     NodeNext* nn = from.top();
     from.pop();
     // copy rest
     copyStack(from);
     // copy elem
     if (deepCopy) {
       to.push(new NodeNext(*nn));
     } else {
       to.push(nn);
     }
     from.push(nn);
   }
   return;
 }
void s3f::s3fnet::trie4::Trie4::iterator::nextNode () private
Move to next node.
Moves to the next node. Intended as an iterator helper.
Definition at line 386 of file trie4.cc.
References s3f::s3fnet::trie4::TrieNode::children, s3f::s3fnet::trie4::Trie4::iterator::NodeNext::next, s3f::s3fnet::trie4::Trie4::iterator::NodeNext::node, and TRIE4_DUMP.
{
   bool keepMoving = true;
   while(keepMoving) {
     NodeNext* nn = stateStack.top();
     stateStack.pop();
     currentNode = nn->node;
     assert(currentNode);
     switch (nn->next) {
     case LEFT: {
       stateStack.push(new NodeNext(nn->node, RIGHT)); // afterwards move right
       TrieNode* leftChild = currentNode->children[LEFT];
       if (leftChild) { // has left child?
         stateStack.push(new NodeNext(leftChild, LEFT)); // descend left
         TRIE4_DUMP(std::cout << currentNode << " push RIGHT, LEFT down, push LEFT (" <<
                   stateStack.size() << ") - "; currentNode->dump(); std::cout << std::endl);
       } else {
         TRIE4_DUMP(std::cout << currentNode << " push RIGHT (" << stateStack.size() <<
                   ") - "; currentNode->dump(); std::cout << std::endl);
       }
       }
       break;
     case RIGHT: {
       stateStack.push(new NodeNext(nn->node, UP)); // afterwards move up
       TrieNode* rightChild = currentNode->children[RIGHT];
       if (rightChild) { // has right child?
         TRIE4_DUMP(std::cout << currentNode << " push UP, RIGHT down, push LEFT (" <<
                   stateStack.size() << ") - "; currentNode->dump(); std::cout << std::endl);
         stateStack.push(new NodeNext(rightChild, LEFT)); // afterwards move left
       } else {
         TRIE4_DUMP(std::cout << currentNode << " push UP (" << stateStack.size() <<
                   ") - "; currentNode->dump(); std::cout << std::endl);
       }
       }
       break;
     case UP:
       // visit node
       keepMoving = false;
       TRIE4_DUMP(std::cout << currentNode << " visit (" << stateStack.size() <<
                 ") - "; currentNode->dump(); std::cout << std::endl);
       assert(currentNode != myTrie->root || stateStack.size() == 0);
       break;
     default:
       // ERROR: undefined state of trie iterator
       throw State();
     } // switch
     delete nn;
   } // while
 }
Member Data Documentation
Trie4* s3f::s3fnet::trie4::Trie4::iterator::myTrie
Trie4 reference Generally root for iterator.
Definition at line 248 of file trie4.h.
Referenced by operator=().
TrieNode* s3f::s3fnet::trie4::Trie4::iterator::currentNode
Current iterator node.
Definition at line 253 of file trie4.h.
Referenced by operator=(), and operator==().
The documentation for this class was generated from the following files:
trie4.h
trie4.cc