S3F: s3f::s3fnet::NameService Class Reference
s3f::s3fnet::NameService Class Reference
Global name resolution service.
#include <namesvc.h>
Public Member Functions
typedef S3FNET_MAP (S3FNET_STRING, S3FNET_STRING) STR2STRMAP
typedef S3FNET_MAP (S3FNET_STRING, IPADDR) NHI2IPMAP
typedef S3FNET_MAP (S3FNET_STRING, int) NHI2IDMAP
typedef S3FNET_MAP (IPADDR, S3FNET_STRING) IP2NHIMAP
typedef S3FNET_MAP (IPADDR, NetworkInterface *) IP2IFACE_MAP
typedef S3FNET_MAP (int, Host *) VEID2HOSTOBJ_MAP
const char * hostname2align (const string &str)
Resolve host name to alignment name.
const char * nhi2align (const string &nhi)
Resolve Host Nhi or NIC Nhi (which is converted to Host Nhi) to alignment name.
IPADDR hostname2ip (const S3FNET_STRING &str)
Resolve host name to IPADDR.
IPADDR nhi2ip (const S3FNET_STRING &nhi)
Resolve Host or NIC Nhi to IPADDR.
const char * nhi2hostname (const S3FNET_STRING &nhi)
Resolve Host Nhi or NIC Nhi (converted to Host Nhi) to host name, if defined.
const char * ip2nicnhi (IPADDR addr)
Resolve IPADDR to the corresponding NIC Nhi.
const char * ip2align (IPADDR addr)
Resolve IPADDR to alignment name.
bool netnhi2prefix (const S3FNET_STRING &nhi, IPPrefix &prefix)
Resolve Net Nhi to a prefix; return true if successful.
bool netnhi2prefix (const char *nhi, IPPrefix &prefix)
Resolve Net Nhi to a prefix; return true if successful.
NetworkInterface * ip2iface (IPADDR addr)
Resolve IPADDR to the corresponding NetworkInterface object.
Host * ip2hostobj (IPADDR addr)
Resolve IPADDR to the corresponding Host object.
NetworkInterface * nicnhi2iface (const S3FNET_STRING &nhi)
Resolve NIC Nhi to the corresponding NetworkInterface object.
Host * hostnhi2hostobj (const S3FNET_STRING &nhi)
Resolve Host Nhi to the corresponding Host object.
Mac48Address * ip2mac48 (IPADDR addr)
Resolve IPADDR to Mac48Address.
Host * veid2hostobj (int id)
Resolve VEID to the corresponding Host object.
int ip2veid (IPADDR addr)
Resolve IPADDR to the corresponding VEID.
int hostnhi2veid (const S3FNET_STRING &nhi)
Resolve Host Nhi to the corresponding VEID.
IP2IFACE_MAP * get_ip2iface_map ()
Return the ip2iface_map.
VEID2HOSTOBJ_MAP * get_veid2hostobj_map ()
Return the veid2hostobj_map.
void print_ip2iface_map ()
Print the ip2iface_map.
void print_veid2hostobj_map ()
Print the veid2hostobj_map.
Protected Member Functions
NameService ()
The constructor.
virtual ~NameService ()
The destructor.
virtual void config (s3f::dml::Configuration *cfg)
Configure from DML.
void config_topnet_cidr (s3f::dml::Configuration *cfg)
void config_net_cidr (s3f::dml::Configuration *cfg, CidrBlock *cidr)
void config_hosts (s3f::dml::Configuration *cfg)
void config_nhi_addr (s3f::dml::Configuration *cfg)
Protected Attributes
CidrBlock top_cidr_block
CIDR block for the entire network.
STR2STRMAP * hostname2nicnhi_map
map from host name to nic NHI address
STR2STRMAP * hostnhi2hostname_map
map from host NHI address to host name
STR2STRMAP * hostnhi2align_map
map from host NHI to the name of the alignment it belongs
NHI2IDMAP * hostnhi2id_map
map from host NHI to index of its default interface
NHI2IPMAP * nhi2ip_map
map from nic NHI to IPADDR
IP2NHIMAP * ip2nicnhi_map
map from IPADDR to NHI
IP2IFACE_MAP * ip2iface_map
map from IP to NetworkInterface* object
VEID2HOSTOBJ_MAP * veid2hostobj_map
map from veid (emulation) to Host* object
Detailed Description
Global name resolution service.
This class keeps global information. It can translate between host name, ip address, nhi address, and the alignment names.
Definition at line 29 of file namesvc.h.
Constructor & Destructor Documentation
s3f::s3fnet::NameService::NameService () protected
The constructor.
Definition at line 26 of file namesvc.cc.
References ip2iface_map, NAMESVC_DUMP, and veid2hostobj_map.
                          :
   hostname2nicnhi_map(0), hostnhi2hostname_map(0),
   hostnhi2align_map(0), hostnhi2id_map(0),
   nhi2ip_map(0), ip2nicnhi_map(0), ip2iface_map(0),
   veid2hostobj_map(0)
 {
   NAMESVC_DUMP(printf("new global name service\n"));
   ip2iface_map = new IP2IFACE_MAP;
   veid2hostobj_map = new VEID2HOSTOBJ_MAP;
 }
s3f::s3fnet::NameService::~NameService () protected virtual
The destructor.
Definition at line 37 of file namesvc.cc.
References hostname2nicnhi_map, hostnhi2align_map, hostnhi2hostname_map, hostnhi2id_map, ip2iface_map, ip2nicnhi_map, NAMESVC_DUMP, nhi2ip_map, and veid2hostobj_map.
 {
   NAMESVC_DUMP(printf("delete global name service\n"));
   if(hostname2nicnhi_map) delete hostname2nicnhi_map;
   if(hostnhi2hostname_map) delete hostnhi2hostname_map;
   if(hostnhi2align_map) delete hostnhi2align_map;
   if(hostnhi2id_map) delete hostnhi2id_map;
   if(nhi2ip_map) delete nhi2ip_map;
   if(ip2nicnhi_map) delete ip2nicnhi_map;
   if(ip2iface_map) delete ip2iface_map;
   if(veid2hostobj_map) delete veid2hostobj_map;
 }
Member Function Documentation
typedef s3f::s3fnet::NameService::S3FNET_MAP (S3FNET_STRING , S3FNET_STRING)
typedef s3f::s3fnet::NameService::S3FNET_MAP (S3FNET_STRING , IPADDR)
typedef s3f::s3fnet::NameService::S3FNET_MAP (S3FNET_STRING , int)
typedef s3f::s3fnet::NameService::S3FNET_MAP (IPADDR , S3FNET_STRING)
typedef s3f::s3fnet::NameService::S3FNET_MAP (IPADDR , NetworkInterface *)
typedef s3f::s3fnet::NameService::S3FNET_MAP (int , Host *)
const char * s3f::s3fnet::NameService::hostname2align (const string & str)
Resolve host name to alignment name.
Definition at line 274 of file namesvc.cc.
References hostname2nicnhi_map, and nhi2align().
 {
   if(!hostname2nicnhi_map) return 0;
   else
   {
     STR2STRMAP::iterator iter = hostname2nicnhi_map->find(str);
     if(iter == hostname2nicnhi_map->end()) return 0;
     else return nhi2align((*iter).second);
   }
 }
const char * s3f::s3fnet::NameService::nhi2align (const string & nhi)
Resolve Host Nhi or NIC Nhi (which is converted to Host Nhi) to alignment name.
Definition at line 285 of file namesvc.cc.
References hostnhi2align_map.
Referenced by hostname2align(), and ip2align().
 {
   if(!hostnhi2align_map) return 0;
   // remove the interface specification in nhi
   S3FNET_STRING hostnhi;
   int pos = nhi.find_first_of('(');
   if(pos > 0) hostnhi = nhi.substr(0, pos);
   else hostnhi = nhi;
   STR2STRMAP::iterator iter = hostnhi2align_map->find(hostnhi);
   if(iter == hostnhi2align_map->end()) return 0;
   return (*iter).second.c_str();
 }
IPADDR s3f::s3fnet::NameService::hostname2ip (const S3FNET_STRING & str)
Resolve host name to IPADDR.
Definition at line 300 of file namesvc.cc.
References hostname2nicnhi_map, and nhi2ip().
 {
   if(!hostname2nicnhi_map) return 0;
   else
   {
     STR2STRMAP::iterator iter = hostname2nicnhi_map->find(str);
     if(iter == hostname2nicnhi_map->end()) return 0;
     else return nhi2ip((*iter).second);
   }
 }
IPADDR s3f::s3fnet::NameService::nhi2ip (const S3FNET_STRING & nhi)
Resolve Host or NIC Nhi to IPADDR.
Definition at line 311 of file namesvc.cc.
References IPADDR_INVALID, and nhi2ip_map.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::Host::getDefaultIP(), hostname2ip(), hostnhi2hostobj(), hostnhi2veid(), s3f::s3fnet::DummySession::init(), nicnhi2iface(), s3f::s3fnet::Net::nicnhi2ip(), and s3f::s3fnet::DMLRouteInfo::resolve().
 {
   if(!nhi2ip_map) return IPADDR_INVALID;
   NHI2IPMAP::iterator iter = nhi2ip_map->find(nhi);
   if(iter == nhi2ip_map->end()) return IPADDR_INVALID;
   else return (*iter).second;
 }
const char * s3f::s3fnet::NameService::nhi2hostname (const S3FNET_STRING & nhi)
Resolve Host Nhi or NIC Nhi (converted to Host Nhi) to host name, if defined.
Definition at line 320 of file namesvc.cc.
References hostnhi2hostname_map.
 {
   if(!hostnhi2hostname_map) return 0;
   // remove the interface specification in nhi
   S3FNET_STRING hostnhi;
   int pos = nhi.find_first_of('(');
   if(pos > 0) hostnhi = nhi.substr(0, pos);
   else hostnhi = nhi;
   STR2STRMAP::iterator iter = hostnhi2hostname_map->find(hostnhi);
   if(iter == hostnhi2hostname_map->end()) return 0;
   else return (*iter).second.c_str();
 }
const char * s3f::s3fnet::NameService::ip2nicnhi (IPADDR addr)
Resolve IPADDR to the corresponding NIC Nhi.
Definition at line 335 of file namesvc.cc.
References ip2nicnhi_map.
 {
   if(!ip2nicnhi_map) return 0;
   IP2NHIMAP::iterator iter = ip2nicnhi_map->find(addr);
   if(iter == ip2nicnhi_map->end()) return 0;
   else return (*iter).second.c_str();
 }
const char * s3f::s3fnet::NameService::ip2align (IPADDR addr)
Resolve IPADDR to alignment name.
Definition at line 344 of file namesvc.cc.
References ip2nicnhi_map, and nhi2align().
 {
   if(!ip2nicnhi_map) return 0;
   IP2NHIMAP::iterator iter = ip2nicnhi_map->find(addr);
   if(iter == ip2nicnhi_map->end()) return 0;
   else return nhi2align((*iter).second);
 }
bool s3f::s3fnet::NameService::netnhi2prefix (const S3FNET_STRING & nhi, IPPrefix & prefix)
Resolve Net Nhi to a prefix; return true if successful.
Definition at line 390 of file namesvc.cc.
 {
   if(nhi.length() == 0) return false;
   else return netnhi2prefix(nhi.c_str(), prefix);
 }
bool s3f::s3fnet::NameService::netnhi2prefix (const char * nhi, IPPrefix & prefix)
Resolve Net Nhi to a prefix; return true if successful.
Definition at line 353 of file namesvc.cc.
References s3f::s3fnet::CidrBlock::getPrefix(), s3f::s3fnet::CidrBlock::getSubCidrBlock(), and top_cidr_block.
 {
   if(!str) return false;
   char* p= (char*)str;
   char* end = p;
   if(*end == '\0') return false;
   CidrBlock* cur_cidr = &top_cidr_block;
   for(;;)
   {
     long cur_id = strtol(p, &end, 10);
     CidrBlock *sub_cidr = cur_cidr->getSubCidrBlock(cur_id);
     if(!sub_cidr) return false;
     // move down.
     cur_cidr = sub_cidr;
     // check end condition
     if(*end == '\0')
     {
       prefix = cur_cidr->getPrefix();
       return true;
     }
     else if(*end != ':')
     {
       return false; // wrong format.
     }
     else
     {
       p = end+1;
       if(*p == '\0') return false; // wrong format.
     }
   }
 }
NetworkInterface * s3f::s3fnet::NameService::ip2iface (IPADDR addr)
Resolve IPADDR to the corresponding NetworkInterface object.
Definition at line 409 of file namesvc.cc.
References ip2iface_map.
Referenced by ip2hostobj(), ip2mac48(), and nicnhi2iface().
 {
         if(!ip2iface_map) return 0;
         IP2IFACE_MAP::iterator iter = ip2iface_map->find(addr);
         if(iter == ip2iface_map->end()) return 0;
         else return ((*iter).second);
 }
Host * s3f::s3fnet::NameService::ip2hostobj (IPADDR addr)
Resolve IPADDR to the corresponding Host object.
Definition at line 418 of file namesvc.cc.
References s3f::s3fnet::NetworkInterface::getHost(), and ip2iface().
Referenced by hostnhi2hostobj(), and ip2veid().
 {
         NetworkInterface* iface = ip2iface(addr);
         if(!iface) return 0;
         else return iface->getHost();
 }
NetworkInterface * s3f::s3fnet::NameService::nicnhi2iface (const S3FNET_STRING & nhi)
Resolve NIC Nhi to the corresponding NetworkInterface object.
Definition at line 426 of file namesvc.cc.
References ip2iface(), IPADDR_INVALID, and nhi2ip().
Referenced by s3f::s3fnet::Net::nhi2obj(), and s3f::s3fnet::Net::nicnhi_to_obj().
 {
         IPADDR ip = nhi2ip(nhi);
         if(ip == IPADDR_INVALID) return 0;
         else return ip2iface(ip);
 }
Host * s3f::s3fnet::NameService::hostnhi2hostobj (const S3FNET_STRING & nhi)
Resolve Host Nhi to the corresponding Host object.
Definition at line 433 of file namesvc.cc.
References ip2hostobj(), IPADDR_INVALID, and nhi2ip().
Referenced by s3f::s3fnet::Net::load_fwdtable(), and s3f::s3fnet::OpenFlowSwitchSession::SetController().
 {
         IPADDR ip = nhi2ip(nhi);
         if(ip == IPADDR_INVALID) return 0;
         else return ip2hostobj(ip);
 }
Mac48Address * s3f::s3fnet::NameService::ip2mac48 (IPADDR addr)
Resolve IPADDR to Mac48Address.
Definition at line 396 of file namesvc.cc.
References s3f::s3fnet::NetworkInterface::getMac48Addr(), and ip2iface().
Referenced by s3f::s3fnet::SimpleMac::push().
 {
         Mac48Address* mac48_addr = 0;
         NetworkInterface* nw_inf = ip2iface(addr);
         if(nw_inf != 0)
         {
                 mac48_addr = nw_inf->getMac48Addr();
         }
         return mac48_addr;
 }
Host * s3f::s3fnet::NameService::veid2hostobj (int id)
Resolve VEID to the corresponding Host object.
Definition at line 452 of file namesvc.cc.
References veid2hostobj_map.
 {
         if(!veid2hostobj_map) return 0;
         VEID2HOSTOBJ_MAP::iterator iter = veid2hostobj_map->find(id);
         if(iter == veid2hostobj_map->end()) return 0;
         else return ((*iter).second);
 }
int s3f::s3fnet::NameService::ip2veid (IPADDR addr)
Resolve IPADDR to the corresponding VEID.
Definition at line 461 of file namesvc.cc.
References s3f::s3fnet::Host::getVEID(), and ip2hostobj().
Referenced by hostnhi2veid().
 {
         Host* host = ip2hostobj(addr);
         if(!host) return -1;
         else return host->getVEID();
 }
int s3f::s3fnet::NameService::hostnhi2veid (const S3FNET_STRING & nhi)
Resolve Host Nhi to the corresponding VEID.
Definition at line 468 of file namesvc.cc.
References ip2veid(), IPADDR_INVALID, and nhi2ip().
 {
         IPADDR ip = nhi2ip(nhi);
         if(ip == IPADDR_INVALID) return 0;
         else return ip2veid(ip);
 }
IP2IFACE_MAP* s3f::s3fnet::NameService::get_ip2iface_map () inline
Return the ip2iface_map.
Definition at line 92 of file namesvc.h.
References ip2iface_map.
Referenced by s3f::s3fnet::Net::register_interface().
 { return ip2iface_map; }
VEID2HOSTOBJ_MAP* s3f::s3fnet::NameService::get_veid2hostobj_map () inline
Return the veid2hostobj_map.
Definition at line 95 of file namesvc.h.
References veid2hostobj_map.
Referenced by s3f::s3fnet::Net::register_host().
 { return veid2hostobj_map; }
void s3f::s3fnet::NameService::print_ip2iface_map ()
Print the ip2iface_map.
Definition at line 440 of file namesvc.cc.
References ip2iface_map, and s3f::s3fnet::IPPrefix::ip2txt().
 {
         printf("print_ip2iface_map()\n");
         IP2IFACE_MAP::iterator iter;
         for (iter = ip2iface_map->begin(); iter != ip2iface_map->end(); iter++)
         {
                 printf("ip = %s, iface = %p\n",
                                 IPPrefix::ip2txt((IPADDR)((*iter).first)),
                                 (NetworkInterface*)((*iter).second));
         }
 }
void s3f::s3fnet::NameService::print_veid2hostobj_map ()
Print the veid2hostobj_map.
Definition at line 475 of file namesvc.cc.
References veid2hostobj_map.
 {
         printf("print_veid2hostobj_map()\n");
         VEID2HOSTOBJ_MAP::iterator iter;
         for (iter = veid2hostobj_map->begin(); iter != veid2hostobj_map->end(); iter++)
         {
                 printf("veid = %d, host = %p\n",
                                 (int)((*iter).first),
                                 (Host*)((*iter).second));
         }
 }
void s3f::s3fnet::NameService::config (s3f::dml::Configuration * cfg) protected virtual
Configure from DML.
Definition at line 51 of file namesvc.cc.
References config_hosts(), config_nhi_addr(), config_topnet_cidr(), s3f::s3fnet::error_quit(), and NAMESVC_DUMP.
Referenced by s3f::s3fnet::Net::config_top_net().
 {
   NAMESVC_DUMP(printf("config().\n"));
   assert(cfg);
   s3f::dml::Configuration* ncfg = (s3f::dml::Configuration*)cfg->findSingle("Net");
   if(ncfg)
   {
     if(!s3f::dml::dmlConfig::isConf(ncfg))
       error_quit("ERROR: NameService::config(), invalid ENVIRONMENT_INFO.NET attribute.\n");
     config_topnet_cidr(ncfg);
   }
   s3f::dml::Enumeration* henum = cfg->find("host");
   while(henum->hasMoreElements())
   {
     s3f::dml::Configuration* hcfg = (s3f::dml::Configuration*)henum->nextElement();
     if(!s3f::dml::dmlConfig::isConf(hcfg))
       error_quit("ERROR: NameService::config(), invalid ENVIRONMENT_INFO.HOST attribute.\n");
     config_hosts(hcfg);
   }
   delete henum;
   s3f::dml::Enumeration* aenum = cfg->find("alignment");
   while(aenum->hasMoreElements())
   {
     s3f::dml::Configuration* acfg = (s3f::dml::Configuration*)aenum->nextElement();
     if(!s3f::dml::dmlConfig::isConf(acfg))
       error_quit("ERROR: NameService::config(), invalid ENVIRONMENT_INFO.ALIGNMENT attribute.\n");
     config_nhi_addr(acfg);
   }
   delete aenum;
 }
void s3f::s3fnet::NameService::config_topnet_cidr (s3f::dml::Configuration * cfg) protected
Definition at line 86 of file namesvc.cc.
References s3f::s3fnet::CidrBlock::addSubCidrBlock(), config_net_cidr(), s3f::s3fnet::error_quit(), NAMESVC_DUMP, and top_cidr_block.
Referenced by config().
 {
   NAMESVC_DUMP(printf("config_topnet_cidr().\n"));
   assert(cfg);
   s3f::dml::Enumeration* nenum = (s3f::dml::Enumeration*)cfg->find("Net");
   while(nenum->hasMoreElements())
   {
     s3f::dml::Configuration* ncfg = (s3f::dml::Configuration*)nenum->nextElement();
     if(!s3f::dml::dmlConfig::isConf(ncfg))
       error_quit("ERROR: NameService::config(), invalid ENVIRONMENT_INFO.NET.NET attribute.\n");
     char* str = (char*)ncfg->findSingle("id");
     if(!str || s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: NameService::config_topnet_cidr(), missing or invalid NET.NET.ID attribute in ENVIRONMENT_INFO.\n");
     long id = atol(str);
     NAMESVC_DUMP(printf("config_topnet_cidr(): subnet %ld.\n", id));
     CidrBlock* cidr = new CidrBlock();
     top_cidr_block.addSubCidrBlock(id, cidr);
     // do it recursively for all subnets
     config_net_cidr(ncfg, cidr);
   }
   delete nenum;
 }
void s3f::s3fnet::NameService::config_net_cidr (s3f::dml::Configuration * cfg, CidrBlock * cidr) protected
Definition at line 113 of file namesvc.cc.
References s3f::s3fnet::CidrBlock::addSubCidrBlock(), s3f::s3fnet::IPPrefix::display(), s3f::s3fnet::error_quit(), s3f::s3fnet::CidrBlock::getPrefix(), NAMESVC_DUMP, and s3f::s3fnet::CidrBlock::setPrefix().
Referenced by config_topnet_cidr().
 {
   NAMESVC_DUMP(printf("config_net_cidr().\n"));
   assert(cfg);
   char* str = (char*)cfg->findSingle("prefix_int");
   if(!str || s3f::dml::dmlConfig::isConf(str))
     error_quit("ERROR: NameService::config_net_cidr(), missing NET::PREFIX_INT attribute in ENVIRONMENT_INFO.\n");
   unsigned addr = (unsigned)atoi(str);
   str = (char*)cfg->findSingle("prefix_len");
   if(!str || s3f::dml::dmlConfig::isConf(str))
     error_quit("ERROR: NameService::config_net_cidr(), missing NET::PREFIX_LEN attribute in ENVIRONMENT_INFO.\n");
   int len = atoi(str);
   if(len < 1 || len > 32)
     error_quit("ERROR: NameService::config_net_cidr(), invalid NET::PREFIX_LEN (%d) in ENVIRONMENT_INFO\n", len);
   mycidr->setPrefix(addr, len);
   NAMESVC_DUMP(printf("config_net_cidr(): "); mycidr->getPrefix().display(); printf(".\n"));
   // do it recursively for all subnets
   s3f::dml::Enumeration* nenum = (s3f::dml::Enumeration*)cfg->find("Net");
   while (nenum->hasMoreElements())
   {
     s3f::dml::Configuration* ncfg = (s3f::dml::Configuration*)nenum->nextElement();
     if(!s3f::dml::dmlConfig::isConf(ncfg))
       error_quit("ERROR: NameService::config(), invalid ENVIRONMENT_INFO.NET...NET attribute.\n");
     str = (char*)ncfg->findSingle("id");
     if(!str || s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: NameService::config_topnet_cidr(), missing NET...NET.ID attribute in ENVIRONMENT_INFO.\n");
     long id = atol(str);
     NAMESVC_DUMP(printf("config_net_cidr(): subnet %ld.\n", id));
     CidrBlock* cidr = new CidrBlock();
     mycidr->addSubCidrBlock(id, cidr);
     config_net_cidr(ncfg, cidr);
   }
   delete nenum;
 }
void s3f::s3fnet::NameService::config_hosts (s3f::dml::Configuration * cfg) protected
Definition at line 155 of file namesvc.cc.
References s3f::s3fnet::error_quit(), hostname2nicnhi_map, hostnhi2align_map, hostnhi2hostname_map, hostnhi2id_map, NAMESVC_DUMP, and S3FNET_MAKE_PAIR.
Referenced by config().
 {
   assert(cfg);
   char* str = (char*)cfg->findSingle("name");
   if(!str || s3f::dml::dmlConfig::isConf(str))
     error_quit("ERROR: NameService::config_hosts(), missing or invalid HOST.NAME attribute in ENVIRONMENT_INFO.\n");
   S3FNET_STRING name = str; // copied implicitly
   str = (char*)cfg->findSingle("mapto");
   if(!str || s3f::dml::dmlConfig::isConf(str))
     error_quit("ERROR: NameService::config_hosts(), missing or invalid HOST.MAPTO attribute in ENVIRONMENT_INFO.\n");
   S3FNET_STRING nicnhi = str; // copied implicitly
   // take the NH portion of the NHI address
   int pos = nicnhi.find_first_of('(');
   if(pos <= 0)
     error_quit("ERROR: NameService::config_hosts(), invalid HOST.MAPTO attribute in ENVIRONMENT_INFO.\n");
   int pos2 = nicnhi.find_first_of(')', pos+1);
   if(pos2 <= 0)
     error_quit("ERROR: NameService::config_hosts(), invalid HOST.MAPTO attribute in ENVIRONMENT_INFO.\n");
   S3FNET_STRING hostnhi = nicnhi.substr(0, pos);
   int hostnicidx = atoi(nicnhi.substr(pos+1, pos2-pos+1).c_str());
   if(!hostnhi2id_map) hostnhi2id_map = new NHI2IDMAP;
   if(!(hostnhi2id_map->insert(S3FNET_MAKE_PAIR(hostnhi, hostnicidx))).second)
     error_quit("ERROR: NameService::config_host(),  duplicate host nhi \"%s\" in ENVIRONMENT_INFO.\n", hostnhi.c_str());
   // we only remember named hosts (and provide corresponding mapping)
   if(name != "no_name")
   {
     if(!hostname2nicnhi_map)
     {
       hostname2nicnhi_map = new STR2STRMAP;
       hostnhi2hostname_map = new STR2STRMAP;
     }
     if(!(hostname2nicnhi_map->insert(S3FNET_MAKE_PAIR(name, nicnhi))).second)
       error_quit("ERROR: NameService::config_host(), duplicate host name \"%s\" in ENVIRONMENT_INFO.\n", name.c_str());
     if(!(hostnhi2hostname_map->insert(S3FNET_MAKE_PAIR(hostnhi, name))).second)
       error_quit("ERROR: NameService::config_host(), duplicate nic nhi \"%s\" in ENVIRONMENT_INFO.\n", nicnhi.c_str());
     NAMESVC_DUMP(printf("config_host(): host \"%s\" <=> host nhi \"%s\", nic nhi \"%s\".\n", name.c_str(), hostnhi.c_str(), nicnhi.c_str()));
   }
   else
   {
     NAMESVC_DUMP(printf("config host: anonymous nhi \"%s\".\n", nicnhi.c_str()));
   }
   str = (char*)cfg->findSingle("alignment");
   if(!str || s3f::dml::dmlConfig::isConf(str))
     error_quit("ERROR: NameService::config_host(), missing or invalid HOST.ALIGNMENT attribute in ENVIRONMENT_INFO.\n");
   S3FNET_STRING align = str; // implicit copy
   if(!hostnhi2align_map) hostnhi2align_map = new STR2STRMAP;
   if(!(hostnhi2align_map->insert(S3FNET_MAKE_PAIR(hostnhi, align))).second)
     error_quit("ERROR: NameService::config_host(),  duplicate host nhi \"%s\" in ENVIRONMENT_INFO.\n", hostnhi.c_str());
   NAMESVC_DUMP(printf("config_host(): host nhi \"%s\" <=> alignment \"%s\".\n", hostnhi.c_str(), align.c_str()));
 }
void s3f::s3fnet::NameService::config_nhi_addr (s3f::dml::Configuration * cfg) protected
Definition at line 216 of file namesvc.cc.
References s3f::s3fnet::error_quit(), hostnhi2id_map, ip2nicnhi_map, s3f::s3fnet::IPPrefix::ip2txt(), NAMESVC_DUMP, nhi2ip_map, S3FNET_MAKE_PAIR, and s3f::s3fnet::IPPrefix::txt2ip().
Referenced by config().
 {
   assert(cfg);
   if(!nhi2ip_map) nhi2ip_map = new NHI2IPMAP();
   if(!ip2nicnhi_map) ip2nicnhi_map = new IP2NHIMAP();
   s3f::dml::Enumeration* ienum = cfg->find("interface");
   while(ienum->hasMoreElements())
   {
     s3f::dml::Configuration* icfg = (s3f::dml::Configuration*)ienum->nextElement();
     if(!s3f::dml::dmlConfig::isConf(icfg))
       error_quit("ERROR: NameService::config_nhi_addr(), invalid ALIGNMENT.INTERFACE attribute in ENVIRONMENT_INFO.\n");
     char* str = (char*)icfg->findSingle("nhi");
     if(!str || s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: NameService::config_nhi_addr(), missing or invalid ALIGNMENT.INTERFACE.NHI attribute in ENVIRONMENT_INFO.\n");
     S3FNET_STRING nicnhi = str;
     int pos = nicnhi.find_first_of('(');
     if(pos <= 0)
       error_quit("ERROR: NameService::config_nhi_addr(), invalid ALIGNMENT_INTERFACE.NHI attribute in ENVIRONMENT_INFO.\n");
     int pos2 = nicnhi.find_first_of(')', pos+1);
     if(pos2 <= 0)
       error_quit("ERROR: NameService::config_nhi_addr(), invalid ALIGNMENT_INTERFACE.NHI attribute in ENVIRONMENT_INFO.\n");
     S3FNET_STRING hostnhi = nicnhi.substr(0, pos);
     int hostnicidx = atoi(nicnhi.substr(pos+1, pos2-pos+1).c_str());
     IPADDR ip;
     str = (char*)icfg->findSingle("ip");
     if(str)
     {
       if(s3f::dml::dmlConfig::isConf(str))error_quit("ERROR: NameService::config_nhi_addr(), invalid ALIGNMENT.INTERFACE.IP attribute in ENVIRONMENT_INFO.\n");
       ip = IPPrefix::txt2ip(str);
     }
     NHI2IPMAP::iterator iter = nhi2ip_map->find(nicnhi);
     if(iter != nhi2ip_map->end())
     {
       error_quit("ERROR: NameService::config_nhi_addr(), duplicate nic nhi \"%s\" in ENVIRONMENT_INFO.\n", nicnhi.c_str());
     }
     nhi2ip_map->insert(S3FNET_MAKE_PAIR(nicnhi, ip));
     ip2nicnhi_map->insert(S3FNET_MAKE_PAIR(ip, nicnhi));
     NAMESVC_DUMP(printf("config_nhi_addr(): nhi \"%s\" <=> ip \"%s\".\n", nicnhi.c_str(), IPPrefix::ip2txt(ip)));
     if(hostnhi2id_map)
     {
       NHI2IDMAP::iterator iter = hostnhi2id_map->find(hostnhi);
       if(iter != hostnhi2id_map->end() && hostnicidx == (*iter).second)
       {
         nhi2ip_map->insert(S3FNET_MAKE_PAIR(hostnhi, ip));
         NAMESVC_DUMP(printf("config_nhi_addr(): nhi \"%s\" <=> ip \"%s\".\n", hostnhi.c_str(), IPPrefix::ip2txt(ip)));
           }
     }
   }
   delete ienum;
 }
Member Data Documentation
CidrBlock s3f::s3fnet::NameService::top_cidr_block protected
CIDR block for the entire network.
Definition at line 105 of file namesvc.h.
Referenced by s3f::s3fnet::Net::config_top_net(), config_topnet_cidr(), and netnhi2prefix().
STR2STRMAP* s3f::s3fnet::NameService::hostname2nicnhi_map protected
map from host name to nic NHI address
Definition at line 107 of file namesvc.h.
Referenced by config_hosts(), hostname2align(), hostname2ip(), and ~NameService().
STR2STRMAP* s3f::s3fnet::NameService::hostnhi2hostname_map protected
map from host NHI address to host name
Definition at line 108 of file namesvc.h.
Referenced by config_hosts(), nhi2hostname(), and ~NameService().
STR2STRMAP* s3f::s3fnet::NameService::hostnhi2align_map protected
map from host NHI to the name of the alignment it belongs
Definition at line 109 of file namesvc.h.
Referenced by config_hosts(), nhi2align(), and ~NameService().
NHI2IDMAP* s3f::s3fnet::NameService::hostnhi2id_map protected
map from host NHI to index of its default interface
Definition at line 110 of file namesvc.h.
Referenced by config_hosts(), config_nhi_addr(), and ~NameService().
NHI2IPMAP* s3f::s3fnet::NameService::nhi2ip_map protected
map from nic NHI to IPADDR
Definition at line 111 of file namesvc.h.
Referenced by config_nhi_addr(), nhi2ip(), and ~NameService().
IP2NHIMAP* s3f::s3fnet::NameService::ip2nicnhi_map protected
map from IPADDR to NHI
Definition at line 112 of file namesvc.h.
Referenced by config_nhi_addr(), ip2align(), ip2nicnhi(), and ~NameService().
IP2IFACE_MAP* s3f::s3fnet::NameService::ip2iface_map protected
map from IP to NetworkInterface* object
Definition at line 113 of file namesvc.h.
Referenced by get_ip2iface_map(), ip2iface(), NameService(), print_ip2iface_map(), and ~NameService().
VEID2HOSTOBJ_MAP* s3f::s3fnet::NameService::veid2hostobj_map protected
map from veid (emulation) to Host* object
Definition at line 114 of file namesvc.h.
Referenced by get_veid2hostobj_map(), NameService(), print_veid2hostobj_map(), veid2hostobj(), and ~NameService().
The documentation for this class was generated from the following files:
namesvc.h
namesvc.cc