S3F: PholdMessage Class Reference
PholdMessage Class Reference
Messages transmitting among phold nodes.
#include <phold_node.h>
Public Member Functions
PholdMessage (int)
virtual ~PholdMessage ()
virtual PholdMessage * clone ()
int msg_id ()
int count ()
void inc ()
unsigned int get_type ()
virtual void erase ()
virtual void erase_all ()
void inc_evts ()
int dec_evts ()
Protected Attributes
unsigned int __type
int __evts
Private Attributes
int __msg_id
int __count
Detailed Description
Messages transmitting among phold nodes.
Definition at line 70 of file phold_node.h.
Constructor & Destructor Documentation
PholdMessage::PholdMessage (int msg_id)
Definition at line 14 of file phold_node.cc.
References __msg_id, and msg_id().
Referenced by clone().
{
         __msg_id = msg_id;
 }
PholdMessage::~PholdMessage () virtual
Definition at line 23 of file phold_node.cc.
{
         //
         // call the PholdMessage construct when it goes out of scope
         //
         // printf("called PholdMessage %d dtor\n", __msg_id);
 }
Member Function Documentation
PholdMessage * PholdMessage::clone () virtual
Reimplemented from Message.
Definition at line 18 of file phold_node.cc.
References __msg_id, and PholdMessage().
{
         PholdMessage* phm = new PholdMessage(__msg_id);
         return phm;
 }
int PholdMessage::msg_id () inline
Definition at line 75 of file phold_node.h.
References __msg_id.
Referenced by PholdMessage().
 { return __msg_id; }
int PholdMessage::count () inline
Definition at line 76 of file phold_node.h.
References __count.
 { return __count; }
void PholdMessage::inc () inline
Definition at line 77 of file phold_node.h.
References __count.
 { __count++; }
unsigned int Message::get_type () inline inherited
Definition at line 23 of file message.h.
References Message::__type.
 { return __type; }
virtual void Message::erase () inline virtual inherited
Reimplemented in s3f::s3fnet::ProtocolMessage.
Definition at line 25 of file message.h.
 {};
virtual void Message::erase_all () inline virtual inherited
Reimplemented in s3f::s3fnet::ProtocolMessage.
Definition at line 26 of file message.h.
Referenced by s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::NetworkInterface::receivePacket(), and OutChannel::write().
 {};
void Message::inc_evts () inline inherited
Definition at line 28 of file message.h.
References Message::__evts.
Referenced by Event::Event().
 { __evts++; }
int Message::dec_evts () inline inherited
Definition at line 29 of file message.h.
References Message::__evts.
Referenced by Event::~Event().
 { return --__evts; }
Member Data Documentation
int PholdMessage::__msg_id private
Definition at line 79 of file phold_node.h.
Referenced by clone(), msg_id(), and PholdMessage().
int PholdMessage::__count private
Definition at line 80 of file phold_node.h.
Referenced by count(), and inc().
unsigned int Message::__type protected inherited
Definition at line 31 of file message.h.
Referenced by Message::clone(), Message::get_type(), Message::Message(), and Message::operator=().
int Message::__evts protected inherited
Definition at line 32 of file message.h.
Referenced by Message::clone(), Message::dec_evts(), Message::inc_evts(), Message::Message(), and Message::operator=().
The documentation for this class was generated from the following files:
phold_node.h
phold_node.cc