S3F: s3f::s3fnet::DroptailQueue Class Reference
s3f::s3fnet::DroptailQueue Class Reference
A FIFO queue used inside a network interface.
#include <droptail_queue.h>
Public Member Functions
DroptailQueue (LowestProtocolSession *lowsess)
The constructor.
~DroptailQueue ()
The destructor.
virtual void init ()
Initialize the queue.
virtual int type ()
Return the type of this queue.
void enqueue (Activation msg)
Enqueue the message at the tail of the buffer.
virtual void config (s3f::dml::Configuration *cfg)
Configure the nic queue.
virtual int control (int ctrltyp, void *ctrlmsg, ProtocolSession *sess)
Control information; nothing implemented as default.
virtual void wrapup ()
The wrapup method is called when the simulation finishes.
Protected Member Functions
ltime_t calibrate (int length)
Called by the enqueue method.
Protected Attributes
LowestProtocolSession * phy_sess
The lowest protocol session that this queue is associated with.
double bitrate
Bitrate of the link the NIC is attached to.
long bufsize
The buffer size of the queue.
ltime_t latency
The latency of the NIC.
float jitter_range
The jitter range of this NIC.
Private Attributes
ltime_t last_xmit_time
The time of the last transmission.
ltime_t queue_delay
Queuing delay since the last transmission time.
ltime_t max_queue_delay
Maximum queuing delay is bounded by the queue length.
Detailed Description
A FIFO queue used inside a network interface.
The drop-tail queue maintains a buffer that holds up to a fixed number of bits. Bits go out one by one at the NIC's bit-rate. If attempting to enqueue a message whose size is larger than the currently available free buffer space, the packet is dropped. This is accomplished by the following scheme. Each interface tracks its "queueing delay," which accumulates as packets are written out. Each packet contributes its transmission time (computed as the size of the packet in bits divided by the bit rate of the NIC) to the queueing delay of future packets. This guarantees that the interface will never exceed the local NIC's set bit rate .
Definition at line 33 of file droptail_queue.h.
Constructor & Destructor Documentation
s3f::s3fnet::DroptailQueue::DroptailQueue (LowestProtocolSession * lowsess)
The constructor.
The lowest protocol session in the interface that contains the queue is passed as an argument.
Definition at line 25 of file droptail_queue.cc.
                                                            :
   NicQueue(lowsess), last_xmit_time(0), queue_delay(0) {}
s3f::s3fnet::DroptailQueue::~DroptailQueue () inline
The destructor.
Definition at line 41 of file droptail_queue.h.
 {}
Member Function Documentation
void s3f::s3fnet::DroptailQueue::init () virtual
Initialize the queue.
Reimplemented from s3f::s3fnet::NicQueue.
Definition at line 28 of file droptail_queue.cc.
References s3f::s3fnet::NicQueue::bitrate, s3f::s3fnet::NicQueue::bufsize, Entity::d2t(), s3f::s3fnet::NicProtocolSession::inHost(), s3f::s3fnet::NicQueue::init(), max_queue_delay, and s3f::s3fnet::NicQueue::phy_sess.
 {
   NicQueue::init();
   double max_queue_delay_double = 8 * bufsize / bitrate;
   max_queue_delay = phy_sess->inHost()->d2t(max_queue_delay_double, 0)+1;
 }
virtual int s3f::s3fnet::DroptailQueue::type () inline virtual
Return the type of this queue.
Implements s3f::s3fnet::NicQueue.
Definition at line 47 of file droptail_queue.h.
References DROPTAIL_QUEUE_TYPE.
 { return DROPTAIL_QUEUE_TYPE; }
void s3f::s3fnet::DroptailQueue::enqueue (Activation msg) virtual
Enqueue the message at the tail of the buffer.
If the NIC hasn't yet used up all of its bandwidth, the message is sent after the appropriate buffer delay. If the queue is full, the message will be dropped.
Implements s3f::s3fnet::NicQueue.
Definition at line 36 of file droptail_queue.cc.
References s3f::s3fnet::NicQueue::bitrate, calibrate(), Entity::d2t(), Message::erase_all(), s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolSession::getNow(), IFACE_DUMP, s3f::s3fnet::ProtocolSession::inGraph(), s3f::s3fnet::NicProtocolSession::inHost(), s3f::s3fnet::IPPrefix::ip2txt(), s3f::s3fnet::NicQueue::latency, max_queue_delay, s3f::s3fnet::NicQueue::phy_sess, queue_delay, s3f::s3fnet::LowestProtocolSession::sendPacket(), and s3f::s3fnet::ProtocolMessage::totalRealBytes().
 {
         assert(phy_sess);
         ProtocolMessage* msg = (ProtocolMessage*)pkt;
         int len = msg->totalRealBytes();
         IFACE_DUMP(printf("DroptailQueue::enqueue() pkt_len = %d\n", len););
         if (len <= 0)
                 error_quit("DroptailQueue::enqueue(), pkt len <= 0\n");
         ltime_t jitter = calibrate(len);
         double transmission_time_double = 8.0*len/bitrate;
         ltime_t transmission_time = phy_sess->inHost()->d2t(transmission_time_double, 0)+1;
         ltime_t testqueue_delay = queue_delay + transmission_time;
         if(testqueue_delay > max_queue_delay)
         {
                 // drop the entire packet if the queue full.
                 IFACE_DUMP(printf("[nic=\"%s\", ip=\"%s\"] %ld: drop packet (queue overflow).\n",
                                    ((NetworkInterface*)phy_sess->inGraph())->nhi.toString(),
                                    IPPrefix::ip2txt(((NetworkInterface*)phy_sess->inGraph())->getIP()),
                                    phy_sess->getNow()));
                 pkt->erase_all();
                 return;
         }
   // calculate queueing delay
   queue_delay = testqueue_delay+jitter+latency;
   IFACE_DUMP(printf("DroptailQueue::enqueue() jitter = %ld, transmission_time = %ld, "
                         "current_queue_delay = %ld, latency = %ld\n",
                                 jitter, transmission_time, queue_delay, latency););
   // call the interface to send the packet.
   phy_sess->sendPacket(pkt, queue_delay);
 }
ltime_t s3f::s3fnet::DroptailQueue::calibrate (int length) protected
Called by the enqueue method.
The queueing delay is calculated relative to the last recorded transmission. If we have moved forward in time, we need to recalibrate the accumulated delay so that it remains relative to the current time. We need to recalibrate before every transmission. If the jitter range is defined in the interface, this method also samples and returns a jitter for sending the message.
Definition at line 74 of file droptail_queue.cc.
References s3f::s3fnet::NicQueue::bitrate, Entity::d2t(), s3f::s3fnet::ProtocolSession::getNow(), s3f::s3fnet::ProtocolSession::getRandom(), s3f::s3fnet::NicProtocolSession::inHost(), s3f::s3fnet::NicQueue::jitter_range, last_xmit_time, s3f::s3fnet::NicQueue::phy_sess, queue_delay, and Random::RNG::Uniform().
Referenced by enqueue().
 {
   ltime_t jitter(0);
   ltime_t now = phy_sess->getNow();
   if(jitter_range > 0) // if jitter is enabled
   {
     double jitter_double = phy_sess->getRandom()->Uniform(-1, 1) * jitter_range * len * 8 / bitrate;
     jitter = phy_sess->inHost()->d2t(jitter_double, 0)+1;
     now += jitter;
   }
   if(now > last_xmit_time) // it's possible jitter makes now < last_xmit_time
   {
     queue_delay -= (now - last_xmit_time);
     if (queue_delay < 0) queue_delay = 0;
     last_xmit_time = now;
   }
   return jitter;
 }
void s3f::s3fnet::NicQueue::config (s3f::dml::Configuration * cfg) virtual inherited
Configure the nic queue.
Reimplemented in s3f::s3fnet::RedQueue.
Definition at line 24 of file nic_queue.cc.
Referenced by s3f::s3fnet::SimplePhy::config(), and s3f::s3fnet::RedQueue::config().
 {}
virtual int s3f::s3fnet::NicQueue::control (int ctrltyp, void * ctrlmsg, ProtocolSession * sess) inline virtual inherited
Control information; nothing implemented as default.
Definition at line 55 of file nic_queue.h.
     { return 0; }
virtual void s3f::s3fnet::NicQueue::wrapup () inline virtual inherited
The wrapup method is called when the simulation finishes.
Definition at line 59 of file nic_queue.h.
 {}
Member Data Documentation
ltime_t s3f::s3fnet::DroptailQueue::last_xmit_time private
The time of the last transmission.
Definition at line 71 of file droptail_queue.h.
Referenced by calibrate().
ltime_t s3f::s3fnet::DroptailQueue::queue_delay private
Queuing delay since the last transmission time.
Definition at line 74 of file droptail_queue.h.
Referenced by calibrate(), and enqueue().
ltime_t s3f::s3fnet::DroptailQueue::max_queue_delay private
Maximum queuing delay is bounded by the queue length.
Definition at line 77 of file droptail_queue.h.
Referenced by enqueue(), and init().
LowestProtocolSession* s3f::s3fnet::NicQueue::phy_sess protected inherited
The lowest protocol session that this queue is associated with.
Definition at line 67 of file nic_queue.h.
Referenced by calibrate(), s3f::s3fnet::RedQueue::calibrate(), enqueue(), s3f::s3fnet::RedQueue::enqueue(), init(), s3f::s3fnet::NicQueue::init(), and s3f::s3fnet::RedQueue::init().
double s3f::s3fnet::NicQueue::bitrate protected inherited
Bitrate of the link the NIC is attached to.
Definition at line 70 of file nic_queue.h.
Referenced by calibrate(), s3f::s3fnet::RedQueue::calibrate(), enqueue(), s3f::s3fnet::RedQueue::enqueue(), init(), s3f::s3fnet::NicQueue::init(), and s3f::s3fnet::RedQueue::init().
long s3f::s3fnet::NicQueue::bufsize protected inherited
The buffer size of the queue.
Definition at line 73 of file nic_queue.h.
Referenced by s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::RedQueue::enqueue(), init(), s3f::s3fnet::NicQueue::init(), and s3f::s3fnet::RedQueue::init().
ltime_t s3f::s3fnet::NicQueue::latency protected inherited
The latency of the NIC.
Definition at line 76 of file nic_queue.h.
Referenced by enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::NicQueue::init(), and s3f::s3fnet::RedQueue::init().
float s3f::s3fnet::NicQueue::jitter_range protected inherited
The jitter range of this NIC.
Definition at line 79 of file nic_queue.h.
Referenced by calibrate(), s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::NicQueue::init(), and s3f::s3fnet::RedQueue::init().
The documentation for this class was generated from the following files:
droptail_queue.h
droptail_queue.cc