S3F: STL_EventList Class Reference
STL_EventList Class Reference
Event list implementation using STL priority queue
#include <stl-eventlist.h>
Public Member Functions
STL_EventList ()
void push (EventPtr n)
void pop ()
bool empty ()
int size ()
EventPtr top ()
Public Attributes
priority_queue< EventPtr,
vector< EventPtr >
, evt_Comparer > evtList
Detailed Description
Event list implementation using STL priority queue
Definition at line 30 of file stl-eventlist.h.
Constructor & Destructor Documentation
STL_EventList::STL_EventList () inline
Definition at line 32 of file stl-eventlist.h.
 {}
Member Function Documentation
void STL_EventList::push (EventPtr n) inline virtual
Implements pq.
Definition at line 34 of file stl-eventlist.h.
References evtList.
Referenced by Timeline::get_cross_timeline_events(), Timeline::initialize_appt(), Timeline::schedule(), and Timeline::sync_window().
 { evtList.push(n);        }
void STL_EventList::pop () inline virtual
Implements pq.
Definition at line 35 of file stl-eventlist.h.
References evtList.
Referenced by Timeline::sync_window(), and Timeline::~Timeline().
 { evtList.pop();          }
bool STL_EventList::empty () inline virtual
Implements pq.
Definition at line 36 of file stl-eventlist.h.
References evtList.
Referenced by Timeline::next_time(), Timeline::select_next_event(), Timeline::ve_proxy_entity_potential_impact_time(), and Timeline::~Timeline().
 { return evtList.empty(); }
int STL_EventList::size () inline virtual
Implements pq.
Definition at line 37 of file stl-eventlist.h.
References evtList.
 { return evtList.size();  }
EventPtr STL_EventList::top () inline virtual
Implements pq.
Definition at line 38 of file stl-eventlist.h.
References evtList.
Referenced by Timeline::next_time(), Timeline::select_next_event(), Timeline::sync_window(), and Timeline::ve_proxy_entity_potential_impact_time().
 { return evtList.top();   }
Member Data Documentation
priority_queue<EventPtr, vector<EventPtr>, evt_Comparer> STL_EventList::evtList
Definition at line 33 of file stl-eventlist.h.
Referenced by empty(), pop(), push(), size(), and top().
The documentation for this class was generated from the following file:
stl-eventlist.h