S3F: s3f::s3fnet::IPPrefix Class Reference
s3f::s3fnet::IPPrefix Class Reference
IP prefix, such as 10.10.0.0/16.
#include <ip_prefix.h>
Public Member Functions
IPPrefix (IPADDR ipaddr=0, int iplen=IPADDR_LENGTH)
The constructor.
IPPrefix & operator= (const IPPrefix &rhs)
The assignment operator.
bool contains (IPPrefix &ip)
Returns true if the given IP prefix is contained in the subnet specified by this prefix.
bool contains (IPADDR ipaddr)
Returns true if the given IP address is contained in the subnet specified by this prefix.
void display (FILE *fp=0) const
Display the IP prefix to an output file (stdout by default).
char * toString (char *buf=0) const
Display the IP prefix into a buffer.
Static Public Member Functions
static char * ip2txt (IPADDR ip, char *str)
Convert an IP prefix to a string.
static char *const ip2txt (IPADDR ip)
Convert an IP prefix to a string and store it in an internal static buffer.
static IPADDR txt2ip (const char *str, int *len=0)
Map from a string to an IP prefix; the length of the prefix is returned via the output argument.
static bool txt2ip (const char *str, IPADDR &addr)
Map from a string to an IP address; the mask length is ignored.
Public Attributes
IPADDR addr
The network address of the prefix.
int len
The length of the mask.
Static Private Attributes
static IPADDR masks [33]
A static lookup table to calculate subnet masks.
static char dispbuf [50]
The buffer used to store the textual representation of this prefix for display.
Friends
bool operator== (const IPPrefix &ip1, const IPPrefix &ip2)
Comparison operator.
Detailed Description
IP prefix, such as 10.10.0.0/16.
IPv4 address class. It also includes some utility functions one can use to process an IP address.
Definition at line 82 of file ip_prefix.h.
Constructor & Destructor Documentation
s3f::s3fnet::IPPrefix::IPPrefix (IPADDR ipaddr = 0, int iplen = IPADDR_LENGTH) inline
The constructor.
Definition at line 85 of file ip_prefix.h.
                                                         :
     addr(ipaddr), len(iplen) {}
Member Function Documentation
char * s3f::s3fnet::IPPrefix::ip2txt (IPADDR ip, char * str) static
Convert an IP prefix to a string.
Definition at line 41 of file ip_prefix.cc.
References IPADDR_DUMP.
Referenced by s3f::s3fnet::SocketMaster::bind(), s3f::s3fnet::NBSocketMaster::bind(), s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::NameService::config_nhi_addr(), s3f::s3fnet::UDPSession::connect(), s3f::s3fnet::SocketMaster::connect(), s3f::s3fnet::NBSocketMaster::connect(), s3f::s3fnet::SocketMaster::connected(), s3f::s3fnet::NBSocketMaster::connected(), s3f::s3fnet::IPSession::control(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::CidrBlock::display(), s3f::s3fnet::RouteInfo::display(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::SimpleMac::init(), s3f::s3fnet::SimplePhy::init(), s3f::s3fnet::RedQueue::init(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPServerSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::NetworkInterface::init(), s3f::s3fnet::TCPServerSession::init(), s3f::s3fnet::NBTCPClientSession::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::IPSession::init(), s3f::s3fnet::NBTCPServerSession::init(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::trie2::Trie2::insert(), ip2txt(), s3f::s3fnet::DummySession::pop(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::OpenVZEventSession::pop(), s3f::s3fnet::UDPMaster::pop(), s3f::s3fnet::TCPMaster::pop(), s3f::s3fnet::IPSession::pop(), s3f::s3fnet::NameService::print_ip2iface_map(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::SimplePhy::push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::SimplePhy::receivePacket(), s3f::s3fnet::NetworkInterface::receivePacket(), s3f::s3fnet::Net::register_interface(), s3f::s3fnet::UDPServerSession::request_received(), s3f::s3fnet::RouteInfo::resolve(), s3f::s3fnet::SimplePhy::sendPacket(), s3f::s3fnet::NetworkInterface::sendPacket(), s3f::s3fnet::UDPSession::setSource(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), s3f::s3fnet::BTCPClientSession::start_on(), s3f::s3fnet::SessionID::toString(), and s3f::s3fnet::NetworkInterface::~NetworkInterface().
 {
   char* s = str;
   for(int i=24; i >=0; i-=8) {
     sprintf(s, "%u", ((unsigned)((ip >> i) & 0xFF)));
     s += strlen(s);
     if(i > 0) sprintf(s++, ".");
   }
   IPADDR_DUMP(printf("ip2txt(): 0x%x => %s\n", ip, str));
   return str;
 }
char *const s3f::s3fnet::IPPrefix::ip2txt (IPADDR ip) static
Convert an IP prefix to a string and store it in an internal static buffer.
This buffer will be re-used everytime this method is called.
Definition at line 53 of file ip_prefix.cc.
References dispbuf, and ip2txt().
 {
   return ip2txt(ip, dispbuf);
 }
IPADDR s3f::s3fnet::IPPrefix::txt2ip (const char * str, int * len = 0) static
Map from a string to an IP prefix; the length of the prefix is returned via the output argument.
Definition at line 58 of file ip_prefix.cc.
References IPADDR_DUMP, and IPADDR_LENGTH.
Referenced by s3f::s3fnet::RouteInfo::config(), s3f::s3fnet::NameService::config_nhi_addr(), s3f::s3fnet::DummySession::init(), and s3f::s3fnet::DMLRouteInfo::resolve().
 {
   assert(str);
   int dot_num = 0;  // how many dot are met
   IPADDR base = 0, incr = 0;
   if(len) *len = 32; // default
   for(int i=0; (isdigit(str[i]) || str[i] == '\0' || str[i] == '/'  ||
                 (str[i] == '.' && dot_num <= 2)); i++) {
     // we get to the end of a number
     if((str[i] == '.') || (str[i] == '\0') || (str[i] == '/')) {
       base *= 256;
       base += incr;
       incr = 0;
       // at the end of the string
       if(str[i] == '\0') break;
       // the end of the part should be the length of mask
       if(str[i] == '/') {
         if(len) *len = atoi(str + i + 1);
         break;
       }
       // another dot
       dot_num++;
     } else { // it is a digit
       incr *= 10;
       incr += (str[i] - '0');
     }
   }
   IPADDR_DUMP(printf("txt2ip(): %s => 0x%x", str, base);
               if(len && *len<IPADDR_LENGTH) printf("/%d", *len);
               printf("\n"));
   return base;
 }
bool s3f::s3fnet::IPPrefix::txt2ip (const char * str, IPADDR & addr) static
Map from a string to an IP address; the mask length is ignored.
Returns true if the conversion is successful.
Definition at line 96 of file ip_prefix.cc.
 {
   assert(str);
   long total=0, t;
   char *p=(char*)str, *endp;
   for (int i=0; i<3; i++) { // the first three segments
     t = strtol(p, &endp, 10);
     if (endp == p || *endp == '\0') return false;
     if (t < 0 || t>255) return false;
     total <<= 8; total += t;
     p = endp + 1;
     if (*p == '\0') return false;
   }
   // the last segment
   t = strtol(p, &endp, 10);
   if (endp == p || *endp != '\0') return false;
   if (t < 0 || t>255) return false;
   total <<= 8; total += t;
   addr = (IPADDR)total;
   return true;
 }
IPPrefix & s3f::s3fnet::IPPrefix::operator= (const IPPrefix & rhs)
The assignment operator.
Definition at line 121 of file ip_prefix.cc.
References addr, and len.
 {
   addr = rhs.addr;
   len = rhs.len;
   return *this;
 }
bool s3f::s3fnet::IPPrefix::contains (IPPrefix & ip)
Returns true if the given IP prefix is contained in the subnet specified by this prefix.
Definition at line 128 of file ip_prefix.cc.
References addr, len, and masks.
 {
   // the ip mask length is ignored in this case
   return ((ip.addr ^ addr) & masks[len]) == 0;
 }
bool s3f::s3fnet::IPPrefix::contains (IPADDR ipaddr)
Returns true if the given IP address is contained in the subnet specified by this prefix.
Definition at line 134 of file ip_prefix.cc.
References addr, len, and masks.
 {
   return ((ipaddr ^ addr) & masks[len]) == 0;
 }
void s3f::s3fnet::IPPrefix::display (FILE * fp = 0) const
Display the IP prefix to an output file (stdout by default).
Definition at line 139 of file ip_prefix.cc.
References addr, IPADDR_LENGTH, and len.
Referenced by s3f::s3fnet::NameService::config_net_cidr(), s3f::s3fnet::RouteInfo::display(), and s3f::s3fnet::Net::display().
 {
   if(NULL == fp) fp = stdout;
   for(int i=24; i >=0; i-=8) {
     fprintf(fp, "%ld", (long)((addr >> i) & 0xFF));
     if(i > 0) fprintf(fp, ".");
   }
   if(len < IPADDR_LENGTH) fprintf(fp, "/%d", len);
 }
char * s3f::s3fnet::IPPrefix::toString (char * buf = 0) const
Display the IP prefix into a buffer.
Definition at line 150 of file ip_prefix.cc.
References addr, dispbuf, IPADDR_LENGTH, and len.
 {
   if(!buf) buf = dispbuf;
   char* ret = buf;
   for(int i=24; i >=0; i-=8) {
     sprintf(buf, "%ld", (long)((addr >> i) & 0xFF));
     buf += strlen(buf);
     if(i > 0) sprintf(buf++, ".");
   }
   if(len < IPADDR_LENGTH) sprintf(buf, "/%d", len);
   return ret;
 }
Friends And Related Function Documentation
bool operator== (const IPPrefix & ip1, const IPPrefix & ip2) friend
Comparison operator.
Definition at line 163 of file ip_prefix.cc.
 {
   return (ip1.len == ip2.len) &&
     ((ip1.addr & IPPrefix::masks[ip1.len]) ==
      (ip2.addr & IPPrefix::masks[ip2.len]));
 }
Member Data Documentation
IPADDR s3f::s3fnet::IPPrefix::addr
The network address of the prefix.
Definition at line 132 of file ip_prefix.h.
Referenced by s3f::s3fnet::ForwardingTable::addRoute(), s3f::s3fnet::RouteInfo::config(), contains(), s3f::s3fnet::IPSession::control(), s3f::s3fnet::CidrBlock::display(), display(), s3f::s3fnet::IPSession::init(), s3f::s3fnet::trie2::Trie2::insert(), operator=(), s3f::s3fnet::operator==(), s3f::s3fnet::ForwardingTable::removeRoute(), s3f::s3fnet::DMLRouteInfo::resolve(), s3f::s3fnet::CidrBlock::setPrefix(), and toString().
int s3f::s3fnet::IPPrefix::len
The length of the mask.
Definition at line 135 of file ip_prefix.h.
Referenced by s3f::s3fnet::ForwardingTable::addRoute(), s3f::s3fnet::RouteInfo::config(), contains(), s3f::s3fnet::CidrBlock::display(), display(), s3f::s3fnet::trie2::Trie2::insert(), operator=(), s3f::s3fnet::operator==(), s3f::s3fnet::ForwardingTable::removeRoute(), s3f::s3fnet::DMLRouteInfo::resolve(), s3f::s3fnet::CidrBlock::setPrefix(), and toString().
IPADDR s3f::s3fnet::IPPrefix::masks static private
Initial value:
= {
  0x0,
  0x80000000,0xC0000000,0xE0000000,0xF0000000,
  0xF8000000,0xFC000000,0xFE000000,0xFF000000,
  0xFF800000,0xFFC00000,0xFFE00000,0xFFF00000,
  0xFFF80000,0xFFFC0000,0xFFFE0000,0xFFFF0000,
  0xFFFF8000,0xFFFFC000,0xFFFFE000,0xFFFFF000,
  0xFFFFF800,0xFFFFFC00,0xFFFFFE00,0xFFFFFF00,
  0xFFFFFF80,0xFFFFFFC0,0xFFFFFFE0,0xFFFFFFF0,
  0xFFFFFFF8,0xFFFFFFFC,0xFFFFFFFE,0xFFFFFFFF
}
A static lookup table to calculate subnet masks.
Definition at line 139 of file ip_prefix.h.
Referenced by contains(), and s3f::s3fnet::operator==().
char s3f::s3fnet::IPPrefix::dispbuf static private
The buffer used to store the textual representation of this prefix for display.
Definition at line 143 of file ip_prefix.h.
Referenced by ip2txt(), and toString().
The documentation for this class was generated from the following files:
ip_prefix.h
ip_prefix.cc