S3F: s3f::s3fnet::trie3::Trie3 Class Reference
s3f::s3fnet::trie3::Trie3 Class Reference
A data structure for forwarding tables.
#include <trie3.h>
Classes
class iterator
Public Types
enum TrieType {
ORIGINAL = 0, SIMPLE = 1, PREFIX = 2, UNORDERED_PREFIX = 3,
ARRAY_BACKED = 4, ARRAY_BACKED_PREFIX = 5, ARRAY_BACKED_UNORDERED_PREFIX = 6
}
Enum containing Trie implementations.
Public Member Functions
Trie3 ()
The constructor.
virtual ~Trie3 ()
The destructor.
virtual TrieData * insert (TRIEBITSTRING key, int nBits, TrieData *data, bool replace)
Inserts a new (key, data) pair.
virtual TrieData * remove (TRIEBITSTRING key, int nBits)
Removes a key from the Trie.
virtual TrieData * lookup (TRIEBITSTRING key)
Finds a key in the Trie.
virtual TrieData * getDefault ()
Get the default Route.
virtual int size ()
Return the number of items in the trie.
iterator begin ()
iterator & end ()
Public Attributes
iterator last
Last item in iterator.
Protected Member Functions
bool propagate (TrieNode *node, int start_depth)
Helper function for insert.
Static Protected Member Functions
static void deallocate (TrieNode *theroot)
Deallocate the trie recursively.
Protected Attributes
TrieNode * root
The root of the trie.
int nElements
Number of data elements stored in the trie.
Detailed Description
A data structure for forwarding tables.
Like Trie2, this implementation stores values at their minimum required depth instead of always at depth 32. It's storage use is better than Trie0 and Trie 1, but is still suboptimal, even for this implementation. It may be extendable such that fewer CIDR-style routing entries are effectively stored.
In contrast to Trie2, this Trie supports unordered CIDR input. On a collision with a space-optimized CIDR address already in the tree (ie an address that is stored higher in the tree to save nodes) it will attempt to propagate the node down the tree to some maximum depth (the length of its original mask). This adds light overhead to insert(). It aims to reduce memory overhead, but requires slightly more memory per TrieNode and thus requires extensive testing.
NOTE: The CIDR address loading order limitations noted for Trie0 and Trie1 do not apply to this class.
Definition at line 58 of file trie3.h.
Member Enumeration Documentation
enum s3f::s3fnet::Trie::TrieType inherited
Enum containing Trie implementations.
Enumerator
ORIGINAL
Very first s3fnet Trie implementation.
SIMPLE
Identical to ORIGINAL with minor fixes/enhancements.
PREFIX
Stores values at minimum depth instead of depth equal to their bit-length (ie depth 32 for an ipv4 address).
UNORDERED_PREFIX
Like PREFIX but can take CIDR-format IP address as input in any order.
ARRAY_BACKED
Trie that stores indices into an array in its nodes (vs data IN the nodes).
ARRAY_BACKED_PREFIX
ARRAY_BACKED_UNORDERED_PREFIX
PREFIX with array-backing (ARRAY_BACKED).
Definition at line 112 of file trie.h.
                       {
                 ORIGINAL = 0,
                 SIMPLE = 1,
                 PREFIX = 2,
                 UNORDERED_PREFIX = 3,
                 ARRAY_BACKED = 4,
                 ARRAY_BACKED_PREFIX = 5,
                 ARRAY_BACKED_UNORDERED_PREFIX = 6
         };
Constructor & Destructor Documentation
s3f::s3fnet::trie3::Trie3::Trie3 ()
The constructor.
Definition at line 53 of file trie3.cc.
References root.
              : nElements(0), last(this) {
         root = new TrieNode(0,0);
         assert(root);
 }
s3f::s3fnet::trie3::Trie3::~Trie3 () virtual
The destructor.
Definition at line 61 of file trie3.cc.
References deallocate(), nElements, and root.
 {
   deallocate(root);
   nElements = 0;
 }
Member Function Documentation
TrieData * s3f::s3fnet::trie3::Trie3::insert (TRIEBITSTRING key, int nBits, TrieData * data, bool replace) virtual
Inserts a new (key, data) pair.
Adds a new (key, data) pair to the Trie. If the key already exists, and if the replace flag is set, we will replace the old data with the new one and return the old data. If the replace flag is not set, the old data remains in the trie and the new data is returned. If the key does not exist in trie, the data will be inserted and the return value is 0.
Parameters
key the key to insert
nBits bits of the key to consider (useful for CIDR)
data the TrieData object to add
replace whether to replace an existing value with the same key
Returns
NULL on success, otherwise the TrieData object we attempted to insert (so reference is not lost)
Implements s3f::s3fnet::Trie.
Definition at line 70 of file trie3.cc.
References s3f::s3fnet::trie3::TrieNode::children, s3f::s3fnet::trie3::TrieNode::data, s3f::s3fnet::TrieData::equiv(), s3f::s3fnet::trie3::TrieNode::key, s3f::s3fnet::trie3::TrieNode::maxDepth, nElements, propagate(), root, s3f::s3fnet::trie3::TRIE_BIT_MASK, and TRIE_KEY_SIZE.
{
         if(nBits > TRIE_KEY_SIZE(key)) { // the given mask is too long
                 fprintf(stderr, "Invalid mask size %d\n",nBits);
                 nBits = TRIE_KEY_SIZE(key);
         }
         TrieNode* cur = root; // Note: This Trie implementation guarantees that root is never null
         TrieNode* lastcur;
         TRIEBITSTRING origkey = key;
         int i;
         int index;
         // Note: This Trie implementation guarantees that any non-null, non-root node has data.
         for(i=0;cur;i++) {
                 if(cur->data) { // TODO: Should be able to optimize this check out (see Note above)
                         // if this node already contains the correct forwarding data
                         if(data->equiv(cur->data)) {
                                 // want to keep the node that may be propagated down the farthest
                                 if(cur->maxDepth < nBits) {
                                         cur->maxDepth = nBits;
                                         cur->key = origkey;
                                 }
                                 delete data; // remove duplicate data (doesn't matter which since identical)
                                 return 0;
                         // if inserting to this exact point but data is different, we may have a real conflict
                         } else if(nBits == i) {
                                 /*
                                 // DEBUG BLOCK
                                 RouteInfo* currt = (RouteInfo*)cur->data;
                                 RouteInfo* newrt = (RouteInfo*)data;
                                 TRIE3_DUMP(printf("Potential conflict.\n");)
                                 TRIE3_DUMP(printf("MATCH(nBits == %d): currt.data %s newrt.data\n",i,currt==newrt ? "==":"!=");)
                                 TRIE3_DUMP(printf("inserted node: %s/%d, existing node: %s/%d\n",
                                         IPPrefix::ip2txt(newrt->destination.addr), newrt->destination.len,
                                         IPPrefix::ip2txt(currt->destination.addr), currt->destination.len);)
                                 TRIE3_DUMP(printf("cur->maxDepth = %d, currt->dest.len = %d\n",cur->maxDepth,currt->destination.len);)
                                 // END DEBUG BLOCK
                                 */
                                 // if the data was stored here solely as a space-optimization
                                 if(cur->maxDepth > nBits) {
                                         // try to propagate it down the tree
                                         bool success = propagate(cur,nBits);
                                         //TRIE3_DUMP(printf("propagate %s\n",success?"succeeded":"failed");) // DEBUG
                                         if(success) {
                                                 // collision was avoided, insert given data at cur
                                                 cur->data = data;
                                                 cur->maxDepth = nBits;
                                                 cur->key = origkey;
                                                 return 0;
                                         }
                                 }
                                 if(!replace) {
                                         return data;
                                 }
                                 TrieData* temp = cur->data;
                                 cur->data = data;
                                 cur->maxDepth = nBits;
                                 cur->key = origkey;
                                 return temp;
                         }
                 }
                 // check next node
                 key <<= 1;
                 lastcur = cur;
                 index = (key & TRIE_BIT_MASK)?1:0;
                 cur = cur->children[index];
         }
         /*
         // DEBUG BLOCK
         RouteInfo* newrt = (RouteInfo*)data;
         TRIE3_DUMP(printf("INSERTED node (depth == %d): %s/%d\n", i-1, IPPrefix::ip2txt(newrt->destination.addr), newrt->destination.len);)
         // END DEBUG BLOCK
         */
         // cur is null, so lastcur is where we need to insert
         TrieNode* ptr = lastcur->children[index] = new TrieNode(origkey,nBits);
         ptr->data = data;
         nElements++;
         return 0;
 }
TrieData * s3f::s3fnet::trie3::Trie3::remove (TRIEBITSTRING key, int nBits) virtual
Removes a key from the Trie.
Remove the key from the trie, if it exists, and returns the data corresponding to the removed key. If the key is not in the trie, return NULL.
Parameters
key the key to remove
nBits bits of the key to consider
Returns
the data correspoding to the key on success, otherwise NULL
Implements s3f::s3fnet::Trie.
Definition at line 187 of file trie3.cc.
References s3f::s3fnet::trie3::TrieNode::children, s3f::s3fnet::trie3::TrieNode::data, root, s3f::s3fnet::trie3::TRIE_BIT_MASK, and TRIE_KEY_SIZE.
{
         if(nBits > TRIE_KEY_SIZE(key)) { // the given mask is too long
                 fprintf(stderr, "Invalid mask size %d\n",nBits);
                 nBits = TRIE_KEY_SIZE(key);
         }
         TrieNode* cur = root;
         TrieNode* lastcur;
         int i;
         int index;
         // move to target depth
         for(i=0;cur && i < nBits;i++) {
                 key <<= 1;
                 lastcur = cur;
                 index = (key & TRIE_BIT_MASK)?1:0;
                 cur = cur->children[index];
         }
         // if there is a match at the proper depth
         if(cur && cur->data) {
                 TrieData* olddata = cur->data;
                 cur->data = 0;
                 // free this node if it is now a leaf
                 if(cur->children[0] == NULL && cur->children[1] == NULL) {
                         delete lastcur->children[index];
                 }
                 return olddata;
         }
         // no match was found at the given depth
         return 0;
 }
TrieData * s3f::s3fnet::trie3::Trie3::lookup (TRIEBITSTRING key) virtual
Finds a key in the Trie.
Perform a longest-matching prefix search for the key and if found, places the data in pData. Otherwise, pData is NULL.
Parameters
key the key to lookup
Returns
the data matching the key on success, otherwise NULL
Implements s3f::s3fnet::Trie.
Definition at line 163 of file trie3.cc.
References s3f::s3fnet::trie3::TrieNode::children, s3f::s3fnet::trie3::TrieNode::data, root, and s3f::s3fnet::trie3::TRIE_BIT_MASK.
 {
   // If this Trie exists to call 'lookup', root has already been asserted as non-null
   TrieNode* cur = root->children[(key & TRIE_BIT_MASK)?1:0];
   TrieData* pData = root->data; // handles default-route case
   while(cur) {
     if(cur->data) {
                 pData = cur->data;
         }
         key <<= 1; // needed from pre-loop lookup and removes last unnecessary shift
     cur = cur->children[(key & TRIE_BIT_MASK)?1:0];
   }
   return pData;
 }
TrieData * s3f::s3fnet::trie3::Trie3::getDefault () virtual
Get the default Route.
Returns
an instance of the default route as a TrieData object
Implements s3f::s3fnet::Trie.
Definition at line 221 of file trie3.cc.
References s3f::s3fnet::trie3::TrieNode::data, and root.
{
         if(root) return root->data;
         return 0;
 }
virtual int s3f::s3fnet::trie3::Trie3::size () inline virtual
Return the number of items in the trie.
Returns
the size of the Trie (generally the number of elements contained)
Implements s3f::s3fnet::Trie.
Definition at line 113 of file trie3.h.
References nElements.
 { return nElements; }
bool s3f::s3fnet::trie3::Trie3::propagate (TrieNode * node, int start_depth) protected
Helper function for insert.
Recursively attempts to move a given node down the Trie as long as it would not permanently displace another node and would not exceed its maxDepth.
Parameters
node TrieNode to move down the Trie
start_depth Trie depth at which we start the propagation
Returns
True if propagation succeeded, False otherwise
Definition at line 228 of file trie3.cc.
References s3f::s3fnet::trie3::TrieNode::children, s3f::s3fnet::trie3::TrieNode::data, GETBIT, s3f::s3fnet::trie3::TrieNode::key, s3f::s3fnet::trie3::TrieNode::maxDepth, and TRIE_KEY_SIZE.
Referenced by insert().
{
         //printf("called propagate( %s/%d , %d )\n",IPPrefix::ip2txt(node->key),node->maxDepth,start_depth); // TRACE
         if(start_depth == TRIE_KEY_SIZE(key)) {
                 return false;
         }
         TrieNode* cur = node;
         TrieNode* temp;
         int depth, curbit;
         for(depth=start_depth+1; depth <= node->maxDepth; depth++) {
                 curbit = GETBIT(node->key,start_depth+1);
                 temp = cur->children[curbit];
                 if(temp == NULL) {
                         //TRIE3_DUMP(printf("found null node @depth %d\n",depth);) // DEBUG
                         temp = cur->children[curbit] = new TrieNode(node->key,node->maxDepth);
                         temp->data = node->data;
                         return true;
                 }
                 cur = temp;
         }
         // propagated as deep as possible - must try to chain-propagate the node at maxDepth
         if(cur->maxDepth > node->maxDepth) {
                 bool success = propagate(cur,depth);
                 if(success) {
                         cur->data = node->data;
                         cur->maxDepth = node->maxDepth;
                         cur->key = node->key;
                 }
                 return success;
         }
         return false;
 }
void s3f::s3fnet::trie3::Trie3::deallocate (TrieNode * theroot) static protected
Deallocate the trie recursively.
Parameters
theroot the root entry of the Trie to free
Definition at line 267 of file trie3.cc.
References s3f::s3fnet::trie3::TrieNode::children, and s3f::s3fnet::trie3::TRIE_KEY_SPAN.
Referenced by ~Trie3().
 {
   if(theroot == 0) return;
   // deallocate all the children
   for(int i = 0; i < TRIE_KEY_SPAN; i++)
     deallocate(theroot->children[i]);
   delete theroot;
 }
Trie3::iterator s3f::s3fnet::trie3::Trie3::begin ()
Definition at line 442 of file trie3.cc.
{
   iterator first(this); // create iterator
   ++first; // find first element
   return first; // return by copy
 }
iterator& s3f::s3fnet::trie3::Trie3::end () inline
Definition at line 282 of file trie3.h.
References last.
 { return last; }
Member Data Documentation
TrieNode* s3f::s3fnet::trie3::Trie3::root protected
The root of the trie.
Definition at line 133 of file trie3.h.
Referenced by getDefault(), insert(), lookup(), remove(), Trie3(), and ~Trie3().
int s3f::s3fnet::trie3::Trie3::nElements protected
Number of data elements stored in the trie.
Definition at line 136 of file trie3.h.
Referenced by insert(), size(), and ~Trie3().
iterator s3f::s3fnet::trie3::Trie3::last
Last item in iterator.
Definition at line 271 of file trie3.h.
Referenced by end().
The documentation for this class was generated from the following files:
trie3.h
trie3.cc