S3F: s3f::s3fnet::Trie Class Reference
s3f::s3fnet::Trie Class Reference abstract
Base class for Trie implementations.
#include <trie.h>
Public Types
enum TrieType {
ORIGINAL = 0, SIMPLE = 1, PREFIX = 2, UNORDERED_PREFIX = 3,
ARRAY_BACKED = 4, ARRAY_BACKED_PREFIX = 5, ARRAY_BACKED_UNORDERED_PREFIX = 6
}
Enum containing Trie implementations.
Public Member Functions
virtual TrieData * insert (TRIEBITSTRING key, int nBits, TrieData *data, bool replace)=0
Inserts a new (key, data) pair.
virtual TrieData * remove (TRIEBITSTRING key, int nBits)=0
Removes a key from the Trie.
virtual TrieData * lookup (TRIEBITSTRING key)=0
Finds a key in the Trie.
virtual TrieData * getDefault ()=0
Return the default TrieData item.
virtual int size ()=0
Return the size of the Trie.
Detailed Description
Base class for Trie implementations.
Data structure to store and efficiently match large datasets such as routing tables. This is generally meant to be a pure-virtual (abstract) base class that others must derive. However, a base implementation is provided.
Definition at line 107 of file trie.h.
Member Enumeration Documentation
enum s3f::s3fnet::Trie::TrieType
Enum containing Trie implementations.
Enumerator
ORIGINAL
Very first s3fnet Trie implementation.
SIMPLE
Identical to ORIGINAL with minor fixes/enhancements.
PREFIX
Stores values at minimum depth instead of depth equal to their bit-length (ie depth 32 for an ipv4 address).
UNORDERED_PREFIX
Like PREFIX but can take CIDR-format IP address as input in any order.
ARRAY_BACKED
Trie that stores indices into an array in its nodes (vs data IN the nodes).
ARRAY_BACKED_PREFIX
ARRAY_BACKED_UNORDERED_PREFIX
PREFIX with array-backing (ARRAY_BACKED).
Definition at line 112 of file trie.h.
                       {
                 ORIGINAL = 0,
                 SIMPLE = 1,
                 PREFIX = 2,
                 UNORDERED_PREFIX = 3,
                 ARRAY_BACKED = 4,
                 ARRAY_BACKED_PREFIX = 5,
                 ARRAY_BACKED_UNORDERED_PREFIX = 6
         };
Member Function Documentation
virtual TrieData* s3f::s3fnet::Trie::insert (TRIEBITSTRING key, int nBits, TrieData * data, bool replace) pure virtual
Inserts a new (key, data) pair.
Adds a new (key, data) pair to the Trie. If the key already exists, and if the replace flag is set, we will replace the old data with the new one and return the old data. If the replace flag is not set, the old data remains in the trie and the new data is returned. If the key does not exist in trie, the data will be inserted and the return value is 0.
Parameters
key the key to insert
nBits bits of the key to consider (useful for CIDR)
data the TrieData object to add
replace whether to replace an existing value with the same key
Returns
NULL on success, otherwise the TrieData object we attempted to insert (so reference is not lost)
Implemented in s3f::s3fnet::trie3::Trie3, s3f::s3fnet::trie2::Trie2, s3f::s3fnet::trie0::Trie0, s3f::s3fnet::trie4::Trie4, and s3f::s3fnet::trie1::Trie1.
Referenced by s3f::s3fnet::ForwardingTable::addRoute().
virtual TrieData* s3f::s3fnet::Trie::remove (TRIEBITSTRING key, int nBits) pure virtual
Removes a key from the Trie.
Remove the key from the trie, if it exists, and returns the data corresponding to the removed key. If the key is not in the trie, return NULL.
Parameters
key the key to remove
nBits bits of the key to consider
Returns
the data correspoding to the key on success, otherwise NULL
Implemented in s3f::s3fnet::trie3::Trie3, s3f::s3fnet::trie2::Trie2, s3f::s3fnet::trie0::Trie0, s3f::s3fnet::trie4::Trie4, and s3f::s3fnet::trie1::Trie1.
Referenced by s3f::s3fnet::ForwardingTable::removeRoute().
virtual TrieData* s3f::s3fnet::Trie::lookup (TRIEBITSTRING key) pure virtual
Finds a key in the Trie.
Perform a longest-matching prefix search for the key and if found, places the data in pData. Otherwise, pData is NULL.
Parameters
key the key to lookup
Returns
the data matching the key on success, otherwise NULL
Implemented in s3f::s3fnet::trie3::Trie3, s3f::s3fnet::trie2::Trie2, s3f::s3fnet::trie0::Trie0, s3f::s3fnet::trie4::Trie4, and s3f::s3fnet::trie1::Trie1.
Referenced by s3f::s3fnet::ForwardingTable::getRoute().
virtual TrieData* s3f::s3fnet::Trie::getDefault () pure virtual
Return the default TrieData item.
Gets the 'default' TrieData object (ie, may be returned if there is no match in the Trie but a non-NULL return is needed. This may (and generally will) vary by implementation.
Returns
an instance of the default TrieData object
Implemented in s3f::s3fnet::trie3::Trie3, s3f::s3fnet::trie2::Trie2, s3f::s3fnet::trie0::Trie0, s3f::s3fnet::trie4::Trie4, and s3f::s3fnet::trie1::Trie1.
Referenced by s3f::s3fnet::ForwardingTable::getDefaultRoute().
virtual int s3f::s3fnet::Trie::size () pure virtual
Return the size of the Trie.
Returns
the size of the Trie (generally the number of elements contained)
Implemented in s3f::s3fnet::trie3::Trie3, s3f::s3fnet::trie2::Trie2, s3f::s3fnet::trie0::Trie0, s3f::s3fnet::trie4::Trie4, and s3f::s3fnet::trie1::Trie1.
The documentation for this class was generated from the following file:
trie.h