S3F: Entity Class Reference
Entity Class Reference
In S3F the Entity object holds the simulation state, the methods that express the logic of the simulation model, and the endpoints of the communication channels.
#include <entity.h>
Public Member Functions
Entity (Timeline *tl)
An Entity is constructed always directed to a Timeline it aligns upon The heavy lifting is done by a call to method BuildEntity.
virtual ~Entity ()
destructor.
ltime_t now ()
Time on Entity's Timeline, either the time at which the current (or most recent) event on the timeline was executed, or the end of the last synchronization window.
Timeline * alignment ()
Returns pointer to the Timeline on which this Entity is aligned.
virtual void init ()
Required of all Entities, is called in a phase where it is assumed that S3F objects have been constructed but not connected to each other.
HandleCode waitFor (Process *proc, Activation act, ltime_t waitinterval)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
HandleCode waitFor (Process *proc, ltime_t waitinterval)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
HandleCode waitFor (Process *proc, Activation act, ltime_t waitinterval, unsigned int)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
HandleCode waitFor (Process *proc, ltime_t waitinterval, unsigned int)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
HandleCode waitFor (Activation act, ltime_t waitinterval)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
HandleCode waitFor (ltime_t waitinterval)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
HandleCode waitFor (Activation act, ltime_t waitinterval, unsigned int)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
HandleCode waitFor (ltime_t waitinterval, unsigned int)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
unsigned int s3fid ()
Unique identifier for Entity, index 0 to total number of Entities created.
Entity (Timeline *tl, string)
An Entity can optionally provide a textual identifier that goes into a directory so that a pointer to the Entity can be found by name.
string getName ()
Return the text name ("" if none was given at initialization)
InChannel * getInChannel (string)
When an InChannel is create it can provide a text name, unique among InChannels on the same Entity.
Process * getProcess (string)
When a Process is create it can provide a text name, unique among Processes on the same Entity.
double t2d (ltime_t t)
Conversion routines to translate from clock ticks to double precision.
ltime_t d2t (double d)
Conversion routines to translate from double precision to clock ticks.
double t2d (ltime_t t, int s)
Conversion routines to translate from clock ticks to double precision.
ltime_t d2t (double d, int s)
Conversion routines to translate from double precision to clock ticks.
Static Public Member Functions
static Entity * getEntity (string)
Directory look up of the Entity pointer, given its text name.
Protected Member Functions
void BuildEntity (Timeline *)
The core of the Entity construction is done by BuildEntity.
ltime_t min_sync_cross_timeline_delay (ltime_t)
Among all outbound cross-timeline connections with OutChannels in this Entity, find the smallest min-delay that is at least as large as the argument.
ltime_t min_sync_all_timeline_delay (ltime_t)
Among all outbound connections with OutChannels in this Entity, find the smallest min-delay that is at least as large as the argument.
unsigned int count_min_delay_crossings (ltime_t)
Count the number of outbound cross-timeline connections with minimum delay at least as large as thrs.
Protected Attributes
string __name
text name given at initialization
Timeline * __timeline
pointer to Timeline on which this Entity is aligned
unsigned int __s3fid
Unique identity for Entity.
int __log_ticks_per_sec
time-scale of clock.
vector< OutChannel * > __outchannel_list
list of outchannels owned by this entity
vector< InChannel * > __inchannel_list
list of inchannels owned by this entity
vector< Process * > __process_list
list of processes owned by this entity
map< string, Process * > ProcessName
map< string, InChannel * > InChannelName
directory of inchannels declared with string names
pthread_mutex_t entity_inst_mutex
mutex for access to Entity instances state
Static Protected Attributes
static double __pow [36]
pow[i] = 10^{i-18}.
static map< string, Entity * > EntityName
Entity text to Pointer Directory.
static pthread_mutex_t entity_class_mutex
Mutex that protects access to Entity state.
static unsigned int __num_entities = 0
counter of number of entities created
Detailed Description
In S3F the Entity object holds the simulation state, the methods that express the logic of the simulation model, and the endpoints of the communication channels.
Processes, InChannels, and OutChannels are all owned by some Entity. Each Entity is aligned on some Timeline.
There is a static Entity directory that maps Entity names (which can be declared when the Entity is created) to the memory address of that object. This supports construction of some global name space for Entities, useful for a number of things (i.e., directing communication from outside this system to the correct Entity.)
Each instantiation of an Entity also keeps a directory of InChannels it owns, supporting construction of a local name-space for these. One might use these like ports in networking, with well-known string names (i.e., TCP, UDP) bound to InChannels bound to Processes that handle the associated type of input.
Each Entity provides a function named "init". This is called by the S3F framework after it has built all the Entity objects for the simulation. Normally one expects the Entity constructors to create all the InChannels and OutChannels it owns, and then do the mapping between Enitites in their Entity::init methods.
The notion of S3F Process is just a specially designated Entity method that can be caused to execute. Entity method waitFor is used to schedule execution of the Process named as argument, at a distance in the future given by another argument.
Definition at line 49 of file entity.h.
Constructor & Destructor Documentation
Entity::Entity (Timeline * tl)
An Entity is constructed always directed to a Timeline it aligns upon The heavy lifting is done by a call to method BuildEntity.
Definition at line 26 of file entity.cc.
References BuildEntity().
                              : __name("") {
         BuildEntity(tl);
   }
Entity::~Entity () virtual
destructor.
No real destruction consider here, yet.
Definition at line 57 of file entity.cc.
References entity_inst_mutex, and s3fid().
                  {
         if( !s3fid() ) pthread_mutex_destroy(&entity_inst_mutex);
  }
Entity::Entity (Timeline * tl, string)
An Entity can optionally provide a textual identifier that goes into a directory so that a pointer to the Entity can be found by name.
The heavy lifting is done by a call to method BuildEntity.
Member Function Documentation
ltime_t Entity::now ()
Time on Entity's Timeline, either the time at which the current (or most recent) event on the timeline was executed, or the end of the last synchronization window.
Definition at line 111 of file entity.cc.
References __timeline, and Timeline::now().
Referenced by s3f::s3fnet::SocketMaster::abort(), s3f::s3fnet::NBSocketMaster::abort(), s3f::s3fnet::SocketMaster::accept(), s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::accept1a(), s3f::s3fnet::SocketMaster::accept1b(), s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SocketMaster::accept2b(), s3f::s3fnet::OpenFlowSwitchSession::AddFlow(), s3f::s3fnet::SocketMaster::bind(), s3f::s3fnet::NBSocketMaster::bind(), s3f::s3fnet::SocketMaster::block_till(), s3f::s3fnet::NBSocketMaster::block_till(), s3f::s3fnet::SocketMaster::close(), s3f::s3fnet::NBSocketMaster::close(), s3f::s3fnet::SocketMaster::close1(), s3f::s3fnet::NBSocketMaster::close1(), s3f::s3fnet::SocketMaster::connect(), s3f::s3fnet::NBSocketMaster::connect(), s3f::s3fnet::SocketMaster::connect1(), s3f::s3fnet::NBSocketMaster::connect1(), s3f::s3fnet::SocketMaster::connected(), s3f::s3fnet::NBSocketMaster::connected(), s3f::s3fnet::SocketMaster::control(), s3f::s3fnet::NBSocketMaster::control(), s3f::s3fnet::SocketMaster::eof(), s3f::s3fnet::NBSocketMaster::eof(), s3f::s3fnet::Stats::FlowStatsDump(), s3f::s3fnet::ProtocolSession::getNow(), s3f::s3fnet::Host::getNowWithThousandSeparator(), pHold_Node::listen(), s3f::s3fnet::SocketMaster::listen(), s3f::s3fnet::NBSocketMaster::listen(), OutChannel::mapto(), OutChannel::new_min_write_delay(), s3f::s3fnet::OpenFlowSwitchSession::pop(), s3f::s3fnet::SocketMaster::recv(), s3f::s3fnet::NBSocketMaster::recv(), s3f::s3fnet::SocketMaster::recv1(), s3f::s3fnet::NBSocketMaster::recv1(), s3f::s3fnet::SocketMaster::send(), s3f::s3fnet::NBSocketMaster::send(), s3f::s3fnet::SocketMaster::send1(), s3f::s3fnet::NBSocketMaster::send1(), pHold_Node::talk(), waitFor(), and OutChannel::write().
 { return __timeline->now(); };
Timeline * Entity::alignment ()
Returns pointer to the Timeline on which this Entity is aligned.
Definition at line 120 of file entity.cc.
References __timeline.
Referenced by s3f::s3fnet::Host::init(), OutChannel::mapto(), Process::Process(), Timeline::schedule(), waitFor(), and OutChannel::write().
 { return __timeline; }
virtual void Entity::init () inline virtual
Required of all Entities, is called in a phase where it is assumed that S3F objects have been constructed but not connected to each other.
An Entity's init function will do the connection.
Reimplemented in s3f::s3fnet::Host, and pHold_Node.
Definition at line 80 of file entity.h.
 {} ;
HandleCode Entity::waitFor (Process * proc, Activation act, ltime_t waitinterval)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
The named process must be owned by an entity aligned to this timeline—checked by the Timeline::schedule method. A HandleCode object is returned, it can be used to cancel the scheduled activation. No priority is included, so Timeline::default_schedule_pri is used as a basis.
Parameters
waitinterval wait interval (from now) that S3F will process the activation.
act activation (event); If no Activation is included, one is created with NULL as the protected pointer.
proc The process to execute. Must be owned by an Entity that is co-aligned with this Entity. If no process in included, the default process of this Entity is used.
Definition at line 148 of file entity.cc.
References alignment(), Timeline::default_sched_pri, now(), Timeline::schedule(), and user_pri.
Referenced by s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::UDPServerSession::client_connected(), s3f::s3fnet::TCPMaster::enableFastTimeout(), s3f::s3fnet::TCPMaster::fast_timer_callback_body(), s3f::s3fnet::DummySession::init(), s3f::s3fnet::UDPServerSession::init(), s3f::s3fnet::TCPServerSession::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::NBTCPClientSession::init(), s3f::s3fnet::NBTCPServerSession::init(), s3f::s3fnet::OpenVZEventSession::injectEvent(), pHold_Node::listen(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), s3f::s3fnet::UDPClientSession::request_sent(), s3f::s3fnet::TCPClientSession::request_sent(), s3f::s3fnet::BTCPClientSession::server_connected(), and s3f::s3fnet::TCPMaster::slow_timer_callback_body().
{
       return alignment()->schedule( proc, now()+delay, user_pri(Timeline::default_sched_pri), act);
    }
HandleCode Entity::waitFor (Process * proc, ltime_t waitinterval)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
The named process must be owned by an entity aligned to this timeline—checked by the Timeline::schedule method. A HandleCode object is returned, it can be used to cancel the scheduled activation. No priority is included, so Timeline::default_schedule_pri is used as a basis. No Activation is included, so one is created with NULL as the protected pointer.
Parameters
waitinterval wait interval (from now) that S3F will process the activation.
proc The process to execute. Must be owned by an Entity that is co-aligned with this Entity. If no process in included, the default process of this Entity is used.
Definition at line 162 of file entity.cc.
References alignment(), Timeline::default_sched_pri, now(), Timeline::schedule(), and user_pri.
{
      Message* m = NULL;
      Activation act(m);
      return alignment()->schedule( proc, now()+delay, user_pri(Timeline::default_sched_pri), act);
    }
HandleCode Entity::waitFor (Process * proc, Activation act, ltime_t waitinterval, unsigned int pri)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
The named process must be owned by an entity aligned to this timeline—checked by the Timeline::schedule method. A HandleCode object is returned, it can be used to cancel the scheduled activation.
Parameters
waitinterval wait interval (from now) that S3F will process the activation.
act activation (event); If no Activation is included, one is created with NULL as the protected pointer.
proc The process to execute. Must be owned by an Entity that is co-aligned with this Entity. If no process in included, the default process of this Entity is used.
pri A tie-breaking priority. If no priority is included, Timeline::default_schedule_pri is used as a basis.
Definition at line 152 of file entity.cc.
References alignment(), now(), Timeline::schedule(), and user_pri.
{
       return alignment()->schedule( proc, now()+delay, user_pri(pri), act);
    }
HandleCode Entity::waitFor (Process * proc, ltime_t waitinterval, unsigned int pri)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
The named process must be owned by an entity aligned to this timeline—checked by the Timeline::schedule method. A HandleCode object is returned, it can be used to cancel the scheduled activation. No Activation is included, so one is created with NULL as the protected pointer.
Parameters
waitinterval wait interval (from now) that S3F will process the activation.
proc The process to execute. Must be owned by an Entity that is co-aligned with this Entity. If no process in included, the default process of this Entity is used.
pri A tie-breaking priority. If no priority is included, Timeline::default_schedule_pri is used as a basis.
Definition at line 156 of file entity.cc.
References alignment(), now(), Timeline::schedule(), and user_pri.
{
      Message* m = NULL;
      Activation act(m);
      return alignment()->schedule( proc, now()+delay, user_pri(pri), act);
    }
HandleCode Entity::waitFor (Activation act, ltime_t waitinterval)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
The named process must be owned by an entity aligned to this timeline—checked by the Timeline::schedule method. A HandleCode object is returned, it can be used to cancel the scheduled activation. No priority is included, so Timeline::default_schedule_pri is used as a basis. No process in included, so the default process of this Entity is used.
Parameters
waitinterval wait interval (from now) that S3F will process the activation.
act Activation (event); If no Activation is included, one is created with NULL as the protected pointer.
Definition at line 168 of file entity.cc.
References alignment(), Timeline::default_sched_pri, now(), Timeline::schedule(), and user_pri.
{
       return alignment()->schedule( alignment()->__this, now()+delay, user_pri(Timeline::default_sched_pri), act);
    }
HandleCode Entity::waitFor (ltime_t waitinterval)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
The named process must be owned by an entity aligned to this timeline—checked by the Timeline::schedule method. A HandleCode object is returned, it can be used to cancel the scheduled activation. No priority is included, so Timeline::default_schedule_pri is used as a basis. No process in included, so the default process of this Entity is used. No Activation is included, so one is created with NULL as the protected pointer.
Parameters
waitinterval wait interval (from now) that S3F will process the activation.
Definition at line 182 of file entity.cc.
References alignment(), Timeline::default_sched_pri, now(), Timeline::schedule(), and user_pri.
{
      Message* m = NULL;
      Activation act(m);
      return alignment()->schedule( alignment()->__this, now()+delay, user_pri(Timeline::default_sched_pri), act);
    }
HandleCode Entity::waitFor (Activation act, ltime_t waitinterval, unsigned int pri)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
The named process must be owned by an entity aligned to this timeline—checked by the Timeline::schedule method. A HandleCode object is returned, it can be used to cancel the scheduled activation. No process in included, so the default process of this Entity is used.
Parameters
waitinterval wait interval (from now) that S3F will process the activation.
act Activation (event); If no Activation is included, one is created with NULL as the protected pointer.
pri A tie-breaking priority. If no priority is included, Timeline::default_schedule_pri is used as a basis.
Definition at line 172 of file entity.cc.
References alignment(), now(), Timeline::schedule(), and user_pri.
{
       return alignment()->schedule( alignment()->__this, now()+delay, user_pri(pri), act);
    }
HandleCode Entity::waitFor (ltime_t waitinterval, unsigned int pri)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
The named process must be owned by an entity aligned to this timeline—checked by the Timeline::schedule method. A HandleCode object is returned, it can be used to cancel the scheduled activation. No process in included, so the default process of this Entity is used. No activation is included, so one is created with NULL as the protected pointer.
Parameters
waitinterval wait interval (from now) that S3F will process the activation.
pri A tie-breaking priority. If no priority is included, Timeline::default_schedule_pri is used as a basis.
Definition at line 176 of file entity.cc.
References alignment(), now(), Timeline::schedule(), and user_pri.
{
      Message* m = NULL;
      Activation act(m);
      return alignment()->schedule( alignment()->__this, now()+delay, user_pri(pri), act);
    }
unsigned int Entity::s3fid () inline
Unique identifier for Entity, index 0 to total number of Entities created.
Definition at line 171 of file entity.h.
References __s3fid.
Referenced by pHold_Node::init(), and ~Entity().
 { return __s3fid; }
string Entity::getName () inline
Return the text name ("" if none was given at initialization)
Definition at line 187 of file entity.h.
References __name.
 { return __name;}
Entity * Entity::getEntity (string) static
Directory look up of the Entity pointer, given its text name.
Definition at line 200 of file entity.cc.
References entity_class_mutex, and EntityName.
Referenced by pHold_Node::init().
{
         // protect global directory using entity class mutex
         pthread_mutex_lock(&entity_class_mutex);
         // look for the name in the directory.
         map<string,Entity*>::const_iterator itr
                 = EntityName.find(name);
         // if the iterator points to the end of the map we didn't find it
         if( itr == EntityName.end()) {
                         // make list available to others and return NULL
                         pthread_mutex_unlock(&entity_class_mutex);
                         return (Entity*) NULL;
         }
         // Entity found.  Make directory available to others and return the
         // pointer
         pthread_mutex_unlock(&entity_class_mutex);
         return (*itr).second;
  }
InChannel * Entity::getInChannel (string)
When an InChannel is create it can provide a text name, unique among InChannels on the same Entity.
That name goes into a directory. This method retrieves the name, returning NULL if no associated mapping was found.
Definition at line 391 of file entity.cc.
References entity_inst_mutex, and InChannelName.
Referenced by pHold_Node::init().
{
     // off timeline entities may query this directory, so protect
     // access with a per-entity mutex.
         pthread_mutex_lock(&entity_inst_mutex);
         // see if we can find the named string
         map<string,InChannel*>::const_iterator itr = InChannelName.find(ic_name);
         // nope.  release the mutex and return NULL
         if( itr == InChannelName.end()) {
                         pthread_mutex_unlock(&entity_inst_mutex);
                         return (InChannel*) NULL;
         }
     // release the mutex and return the InChannel pointer
         pthread_mutex_unlock(&entity_inst_mutex);
         return (*itr).second;
 }
Process * Entity::getProcess (string)
When a Process is create it can provide a text name, unique among Processes on the same Entity.
That name goes into a directory. This method retrieves the name, returning NULL if no associated mapping was found.
Definition at line 426 of file entity.cc.
References entity_inst_mutex, and ProcessName.
{
     // off timeline entities may query this directory, so protect
     // access with a per-entity mutex.
         pthread_mutex_lock(&entity_inst_mutex);
         // see if we can find the named string
         map<string,Process*>::const_iterator itr = ProcessName.find(p_name);
         // nope.  release the mutex and return NULL
         if( itr == ProcessName.end()) {
                         pthread_mutex_unlock(&entity_inst_mutex);
                         return (Process*) NULL;
         }
     // release the mutex and return the Process pointer
         pthread_mutex_unlock(&entity_inst_mutex);
         return (*itr).second;
 }
double Entity::t2d (ltime_t t)
Conversion routines to translate from clock ticks to double precision.
Definition at line 257 of file entity.cc.
Referenced by s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::TCPMaster::enableFastTimeout(), s3f::s3fnet::TCPMaster::fast_timer_callback_body(), and s3f::s3fnet::TCPMaster::slow_timer_callback_body().
 { return (double)t; }
ltime_t Entity::d2t (double d)
Conversion routines to translate from double precision to clock ticks.
Definition at line 269 of file entity.cc.
Referenced by s3f::s3fnet::TCPSession::backoff_timeout(), s3f::s3fnet::DroptailQueue::calibrate(), s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::DummySession::config(), s3f::s3fnet::TCPClientSession::config(), s3f::s3fnet::UDPServerSession::config(), s3f::s3fnet::SimplePhy::config(), s3f::s3fnet::UDPClientSession::config(), s3f::s3fnet::TCPMaster::config(), s3f::s3fnet::BTCPClientSession::config(), s3f::s3fnet::Link::connect(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::DroptailQueue::init(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::TCPSession::init_state_closed(), pHold_Node::listen(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), s3f::s3fnet::NetworkInterface::sendPacket(), s3f::s3fnet::TCPMaster::TCPMaster(), and s3f::s3fnet::TCPSession::update_timeout().
 { return (ltime_t)d; }
double Entity::t2d (ltime_t t, int s)
Conversion routines to translate from clock ticks to double precision.
Parameters
t clock ticks input
s specify the units of the double precision input or output, in units of log_10(clock ticks per second). So, for example, if a double represents milliseconds, the s value is 3
Definition at line 262 of file entity.cc.
References __log_ticks_per_sec, and __pow.
{
         int scale = 18+(s-__log_ticks_per_sec);
         if(scale < 36 && scale>=0 ) return t*__pow[scale];
         return t*pow(10.0, scale-18);
   }
ltime_t Entity::d2t (double d, int s)
Conversion routines to translate from double precision to clock ticks.
Parameters
d double input
s specify the units of the double precision input or output, in units of log_10(clock ticks per second). So, for example, if a double represents milliseconds, the s value is 3
Definition at line 274 of file entity.cc.
References __log_ticks_per_sec, and __pow.
{
         int scale = 18+(__log_ticks_per_sec-s);
         if(scale < 36 && scale>=0 ) return (ltime_t)round(d*__pow[scale]);
         else return (ltime_t)round(d*pow(10.0, scale-18));
   }
void Entity::BuildEntity (Timeline * tl) protected
The core of the Entity construction is done by BuildEntity.
Finish constructing the Entity.
– save the Timeline pointer
– build the tables used to support tick - double precision conversion
– give the entity a unique name
– put the entity onto its Timeline's list of entities.
Definition at line 73 of file entity.cc.
References Timeline::__entity_list, __log_ticks_per_sec, __num_entities, __pow, __s3fid, __timeline, entity_class_mutex, entity_inst_mutex, Timeline::get_log_ticks_per_sec(), and Timeline::timeline_inst_mutex.
Referenced by Entity().
{
         // remember alignment, often used to check for cross-timeline connections
         __timeline = tl;
     // initialize the mutex used to serialize access to the individual
     // Entity state (not the static class variables).
     pthread_mutex_init(&entity_inst_mutex,NULL);
     // get unique Entity id. Global access so protect by mutex
         pthread_mutex_lock(&entity_class_mutex);
         __s3fid = __num_entities++;
         pthread_mutex_unlock(&entity_class_mutex);
         // first entity builds the pow[] table, used in tick - double precision conversion
         if( __s3fid == 0 ) {
                 for(int i=0; i<36; i++) __pow[i] = pow(10.0, (double)(i-18));
         }
         // copy time-scale information from the Timeline
         __log_ticks_per_sec = tl->get_log_ticks_per_sec();
         // record entity on timeline's list of entities
         pthread_mutex_lock(&tl->timeline_inst_mutex);
         tl->__entity_list.push_back(this);
         pthread_mutex_unlock(&tl->timeline_inst_mutex);
    }
ltime_t Entity::min_sync_cross_timeline_delay (ltime_t thrs) protected
Among all outbound cross-timeline connections with OutChannels in this Entity, find the smallest min-delay that is at least as large as the argument.
Definition at line 289 of file entity.cc.
References __outchannel_list.
{
    // initialize search answer to "nothing here"
    ltime_t ans = -1;
    // buffer the minimum read up from a channel connection
    ltime_t ch_min;
    // length of the list of this entity's outchannels
    unsigned int end = __outchannel_list.size();
    // visit every one of the outchannels this entity owns
    for(unsigned int i=0; i<end; i++) {
         // ask it to provide the minimum cross timeline delay at least as
         // large as thrs, among all its mappings
         //
         ch_min = __outchannel_list[i]->min_sync_cross_timeline_delay(thrs);
         // save that value if it is no larger than thrs, AND either this is
         // first one we've seen, or its value is less than the smallest one
         // seen to date.
         //
         if( (-1 < ch_min) && thrs<=ch_min && ((ans<0) || (ch_min<ans))) ans = ch_min;
    }
    // final answer is in ans
    return ans;
  }
ltime_t Entity::min_sync_all_timeline_delay (ltime_t thrs) protected
Among all outbound connections with OutChannels in this Entity, find the smallest min-delay that is at least as large as the argument.
Definition at line 318 of file entity.cc.
References __outchannel_list.
{
    // initialize search answer to "nothing here"
    ltime_t ans = -1;
    // buffer the minimum read up from a channel connection
    ltime_t ch_min;
    // length of the list of this entity's outchannels
    unsigned int end = __outchannel_list.size();
    // visit every one of the outchannels this entity owns
    for(unsigned int i=0; i<end; i++) {
         // ask it to provide the minimum cross timeline delay at least as
         // large as thrs, among all its mappings
         //
         ch_min = __outchannel_list[i]->min_sync_all_timeline_delay(thrs);
         // save that value if it is no larger than thrs, AND either this is
         // first one we've seen, or its value is less than the smallest one
         // seen to date.
         //
         if( (-1 < ch_min) && thrs<=ch_min && ((ans<0) || (ch_min<ans))) ans = ch_min;
    }
    // final answer is in ans
    return ans;
  }
unsigned int Entity::count_min_delay_crossings (ltime_t thrs) protected
Count the number of outbound cross-timeline connections with minimum delay at least as large as thrs.
Definition at line 355 of file entity.cc.
References __outchannel_list.
{
   // initialize running sum
   unsigned int ans = 0;
   // number of OutChannels owned by this entity
   unsigned int end = __outchannel_list.size();
   // For each OutChannel as it to count the number of outbound
   // cross timeline connections with minimum delay less than or equal
   // to thrs
   //
   for(unsigned int i=0; i<end; i++) {
     ans += __outchannel_list[i]->count_min_delay_crossings(thrs);
   }
   // return accumulated sum
   return ans;
 }
Member Data Documentation
string Entity::__name protected
text name given at initialization
Definition at line 267 of file entity.h.
Referenced by getName().
Timeline* Entity::__timeline protected
pointer to Timeline on which this Entity is aligned
Definition at line 268 of file entity.h.
Referenced by alignment(), BuildEntity(), and now().
unsigned int Entity::__s3fid protected
Unique identity for Entity.
Definition at line 269 of file entity.h.
Referenced by BuildEntity(), and s3fid().
double Entity::__pow static protected
pow[i] = 10^{i-18}.
Used in time scale transformation
Definition at line 273 of file entity.h.
Referenced by BuildEntity(), d2t(), and t2d().
int Entity::__log_ticks_per_sec protected
time-scale of clock.
Obtained from timeline when the entity is created.
Definition at line 275 of file entity.h.
Referenced by BuildEntity(), d2t(), and t2d().
vector<OutChannel*> Entity::__outchannel_list protected
list of outchannels owned by this entity
Definition at line 279 of file entity.h.
Referenced by count_min_delay_crossings(), Timeline::initialize_appt(), min_sync_all_timeline_delay(), min_sync_cross_timeline_delay(), and OutChannel::OutChannel().
vector<InChannel*> Entity::__inchannel_list protected
list of inchannels owned by this entity
Definition at line 280 of file entity.h.
Referenced by InChannel::InChannel().
vector<Process*> Entity::__process_list protected
list of processes owned by this entity
Definition at line 281 of file entity.h.
Referenced by Process::Process().
map<string,Process*> Entity::ProcessName protected
Definition at line 284 of file entity.h.
Referenced by getProcess().
map<string,InChannel*> Entity::InChannelName protected
directory of inchannels declared with string names
Definition at line 285 of file entity.h.
Referenced by getInChannel().
pthread_mutex_t Entity::entity_inst_mutex protected
mutex for access to Entity instances state
Definition at line 288 of file entity.h.
Referenced by BuildEntity(), getInChannel(), getProcess(), InChannel::InChannel(), OutChannel::OutChannel(), Process::Process(), and ~Entity().
map< string, Entity * > Entity::EntityName static protected
Entity text to Pointer Directory.
Definition at line 293 of file entity.h.
Referenced by getEntity().
pthread_mutex_t Entity::entity_class_mutex static protected
Mutex that protects access to Entity state.
Definition at line 296 of file entity.h.
Referenced by BuildEntity(), getEntity(), and Interface::Interface().
unsigned int Entity::__num_entities = 0 static protected
counter of number of entities created
Definition at line 299 of file entity.h.
Referenced by BuildEntity().
The documentation for this class was generated from the following files:
entity.h
entity.cc