S3F: Event Class Reference
Event Class Reference
Class Event holds all the information needed to execute an s3f event.
#include <event.h>
Public Member Functions
Event ()
Event (ltime_t, int, Process *proc, Activation act, Timeline *home_tl, unsigned int)
Event (unsigned int, ltime_t, int, InChannel *inc, Activation act, Process *, Timeline *home_tl, unsigned int)
Event (ltime_t, int, unsigned int tl, int type, Timeline *home_tl, unsigned int)
Event (ltime_t, int, InChannel *inc, Process *proc, bool bind, unsigned int pri, Timeline *home_tl, unsigned int)
~Event ()
Process * get_proc ()
unsigned int get_evtype ()
Activation get_act ()
InChannel * get_inc ()
unsigned int get_tl ()
unsigned int get_pri ()
unsigned int get_evtnum ()
bool get_bind ()
void cancel ()
void release ()
void * adrs ()
Event * get ()
ltime_t get_time ()
Timeline * get_home_tl ()
Public Attributes
ltime_t __time
not used in priority queue but placed here for information
int __key2
priority
unsigned int __evtnum
inserted by timeline on scheduling
Protected Attributes
unsigned int __EventType
what to do with this event
Process * __proc
process to exec. on TIMEOUT
InChannel * __inc
InChannel on which Activation arrives.
unsigned int __tl
used for the appointment events
unsigned int __pri
priority used for ordering
bool __bind
Activation __act
Activation to deliver in case of ACTIVATE.
Timeline * __home_tl
timeline on which this is scheduled
Detailed Description
Class Event holds all the information needed to execute an s3f event.
Fields are describe below:
__EventType : an enumerated type that flags the type of the event to be done. The possibilities are
EVTYPE_TIMEOUT – used when the event results from a waitFor call from a Process.
EVTYPE_ACTIVATE – used when the event results from the presentation of an Activation instance to an InChannel
EVTYPE_WAIT_APPT – handle incoming appointment time from named timeline
EVTYPE_MAKE_APPT – create outgoing appointment time for named timeline
EVTYPE_BIND – bind a process to an inchannel
EVTYPE_CANCEL – used to flag that this event should not be executed, is filtered before presenting to the simulation
__proc : Pointer to a Process, the one called when executing an EVTYPE_TIMEOUT event
__inc : Pointer to an InChannel, the one to which an Activation is directed at the simulation time
__act : Pointer to an Activation, presented to Processes that are bound to or waiting on the InChannel in __inc, on a EVTYPE_ACTIVATE event
__tl : Pointer to a timeline involved in the appointment
Time is not in this event, that is carried in the priority_queue data structure that contains this one
Definition at line 56 of file event.h.
Constructor & Destructor Documentation
Event::Event ()
Event::Event (ltime_t t, int key2, Process * proc, Activation act, Timeline * home_tl, unsigned int evtnum)
Definition at line 9 of file event.cc.
References __key2, __time, and Message::inc_evts().
                                                                                                         :
         __evtnum(evtnum), __EventType(EVTYPE_TIMEOUT),  __proc(proc), __act(act), __home_tl(home_tl)
                 { if(act) act->inc_evts();
                   __time = t; __key2 = key2;
                 };
Event::Event (unsigned int etype, ltime_t t, int key2, InChannel * inc, Activation act, Process * proc, Timeline * home_tl, unsigned int evtnum)
Definition at line 14 of file event.cc.
References __key2, __time, and Message::inc_evts().
                                                                                                                                             :
         __evtnum(evtnum), __EventType(etype), __proc(proc),
         __inc(inc), __act(act),  __home_tl(home_tl)
                 { if(act) act->inc_evts();
                   __time = t; __key2 = key2;
                 } ;
Event::Event (ltime_t t, int key2, unsigned int tl, int type, Timeline * home_tl, unsigned int evtnum)
Definition at line 33 of file event.cc.
References __key2, and __time.
                                                                                                     :
         __evtnum(evtnum), __EventType(type), __tl(tl),  __home_tl(home_tl)
                 { __time = t; __key2 = key2; };
Event::Event (ltime_t t, int key2, InChannel * inc, Process * proc, bool bind, unsigned int pri, Timeline * home_tl, unsigned int evtnum)
Definition at line 36 of file event.cc.
References __key2, and __time.
                                                                                                                                     :
         __evtnum(evtnum), __EventType(EVTYPE_BIND), __proc(proc), __inc(inc), __pri(pri), __bind(bind),  __home_tl(home_tl)
                 { __time = t; __key2 = key2; };
Event::~Event ()
Definition at line 50 of file event.cc.
References __act, __EventType, Message::dec_evts(), EVTYPE_ACTIVATE, and EVTYPE_TIMEOUT.
                {
  // printf("called event %p dtor\n", this);
  #ifndef SAFE_MSG_PTR
  if( __EventType == EVTYPE_TIMEOUT || __EventType == EVTYPE_ACTIVATE ) {
         if( __act && __act->dec_evts() == 0) delete __act;
  }
  #endif
 };
Member Function Documentation
Process * Event::get_proc ()
Definition at line 59 of file event.cc.
References __proc.
Referenced by Timeline::sync_window().
 { return __proc; }
unsigned int Event::get_evtype ()
Definition at line 60 of file event.cc.
References __EventType.
Referenced by Timeline::sync_window().
 { return __EventType; }
Activation Event::get_act ()
Definition at line 61 of file event.cc.
References __act.
Referenced by Timeline::sync_window().
 { return __act; }
InChannel * Event::get_inc ()
Definition at line 62 of file event.cc.
References __inc.
Referenced by Timeline::sync_window().
 { return __inc; }
unsigned int Event::get_tl ()
Definition at line 63 of file event.cc.
References __tl.
Referenced by Timeline::sync_window().
 { return __tl; }
unsigned int Event::get_pri ()
Definition at line 64 of file event.cc.
References __pri.
Referenced by Timeline::sync_window().
 { return __pri; }
unsigned int Event::get_evtnum ()
Definition at line 65 of file event.cc.
References __evtnum.
 { return __evtnum; }
bool Event::get_bind ()
Definition at line 66 of file event.cc.
References __bind.
Referenced by Timeline::sync_window().
 { return __bind; }
void Event::cancel ()
Definition at line 68 of file event.cc.
References __EventType, and EVTYPE_CANCEL.
Referenced by Handle::cancel().
 { __EventType = EVTYPE_CANCEL; }
void Event::release ()
Definition at line 43 of file event.cc.
Referenced by Timeline::sync_window().
 { delete this; }
void * Event::adrs ()
Definition at line 44 of file event.cc.
 { return (void *)this; }
Event * Event::get ()
Definition at line 40 of file event.cc.
 { return this; }
ltime_t Event::get_time () inline
Definition at line 80 of file event.h.
References __time.
Referenced by Handle::Handle(), Timeline::sync_window(), and Timeline::ve_proxy_entity_potential_impact_time().
 { return __time; }
Timeline* Event::get_home_tl () inline
Definition at line 81 of file event.h.
References __home_tl.
Referenced by Handle::Handle().
 { return __home_tl; }
Member Data Documentation
ltime_t Event::__time
not used in priority queue but placed here for information
Definition at line 82 of file event.h.
Referenced by Event(), get_time(), evt_Comparer::operator()(), and Timeline::select_next_event().
int Event::__key2
priority
Definition at line 83 of file event.h.
Referenced by Event(), evt_Comparer::operator()(), and Timeline::select_next_event().
unsigned int Event::__evtnum
inserted by timeline on scheduling
Definition at line 84 of file event.h.
Referenced by get_evtnum().
unsigned int Event::__EventType protected
what to do with this event
Definition at line 86 of file event.h.
Referenced by cancel(), get_evtype(), and ~Event().
Process* Event::__proc protected
process to exec. on TIMEOUT
Definition at line 87 of file event.h.
Referenced by get_proc().
InChannel* Event::__inc protected
InChannel on which Activation arrives.
Definition at line 88 of file event.h.
Referenced by get_inc().
unsigned int Event::__tl protected
used for the appointment events
Definition at line 89 of file event.h.
Referenced by get_tl().
unsigned int Event::__pri protected
priority used for ordering
Definition at line 90 of file event.h.
Referenced by get_pri().
bool Event::__bind protected
Definition at line 91 of file event.h.
Referenced by get_bind().
Activation Event::__act protected
Activation to deliver in case of ACTIVATE.
Definition at line 92 of file event.h.
Referenced by get_act(), and ~Event().
Timeline* Event::__home_tl protected
timeline on which this is scheduled
Definition at line 93 of file event.h.
Referenced by get_home_tl().
The documentation for this class was generated from the following files:
event.h
event.cc