S3F: s3f::s3fnet::TCPRecvWindow Class Reference
s3f::s3fnet::TCPRecvWindow Class Reference
The sliding window for TCP receiver.
#include <tcp_rcvwnd.h>
Public Member Functions
TCPRecvWindow (uint32 initseq, uint32 winsiz)
The constructor.
~TCPRecvWindow ()
The destructor.
bool available ()
Whether there is new data available.
uint32 generate (uint32 length, byte *msg)
Generate the message of the given length and submit it to the upper layer.
void addToBuffer (DataMessage *msg, uint32 seqno)
Add the message to the receive buffer.
uint32 freeInBuffer ()
The free space in the buffer.
uint32 bufferSize ()
The buffer size.
uint32 getHighestSeqno ()
Return the highest sequence number ever received.
uint32 getExpectedSeqno ()
Get the expected sequence number from the buffer; this is necessary because an ACK packet may be sent out before the buffer is released.
void setRecvParameters (uint32 bufsiz, byte *buf)
Set the application buffer to receive data.
void resetRecvParameters ()
The application buffer no longer used.
uint32 dataReceived ()
Return the number of bytes received last time.
uint32 start ()
Return the first sequence of the window.
uint32 end ()
Return the last sequence of the window.
uint32 firstUnused ()
Return the first unused sequence in the window.
uint32 size ()
Return the size of the window.
uint32 used ()
Return how much of the window is used up in bytes.
uint32 unused ()
Return how much of the window is unused in bytes.
uint32 lengthTo (const uint32 seqno)
Return the number of bytes between a give sequence number and the start of the window.
void setStart (const uint32 seqno)
Set the start sequence number of the window.
void shift (uint32 offset)
Increase the lower edge of the window by offset number of bytes.
void expand (uint32 nbytes)
Expand the window size by nbytes.
void shrink (uint32 nbytes)
Shrink the size of the window by nbytes.
bool use (uint32 nbytes)
Use up nbytes of the window with data.
void setSYN (bool syn)
set SYN bit.
void setFIN (bool fin)
set FIN bit.
bool synAtFront ()
Return true if SYN segment is in the window.
bool finAtFront ()
Return true if FIN segment is in the window.
uint32 next ()
Like firstUnused method, but also uses SYN & FIN segments; the method is used for sending window.
uint32 expect ()
Like start method, but also uses SYN & FIN segments; the method is used for receiving window.
bool within (uint32 seqno)
Returns true iff 'seqno' is within the window.
bool isUsed (uint32 seqno)
Returns true iff 'seqno' is used within the window.
bool empty ()
Returns true iff the window is empty (nothing used).
void reset ()
Resets the window.
Protected Member Functions
void seq_shift (uint32 offset)
Shift the window by the given offset permanently.
Protected Attributes
uint32 start_seqno
Starting sequence number of the window.
uint32 win_size
Size of the window in bytes.
uint32 used_size
How many bytes are used in window.
int syn_included
Whether SYN is in window.
int fin_included
Whether FIN is in window.
Private Member Functions
bool add_to_buffer_helper (uint32 seqno, uint32 length, byte *msg)
A helper function for addToBuffer.
TCPSegment * get_a_segment ()
Return a free segment.
void add_a_free_segment (TCPSegment *seg)
Add a segment to the free list.
Private Attributes
TCPSegment * seg_buffer
A buffer to put received segments.
TCPSegment * free_seg_list
A list of unused segments.
uint32 highest_seqno
The highest sequence number received.
byte * appl_rcvbuf
The buffer (owned by application) to receive data.
uint32 appl_rcvbuf_size
Total number of bytes expected to receive.
uint32 appl_data_rcvd
The size of the received data (that has been put into the receive buffer).
Detailed Description
The sliding window for TCP receiver.
We use a linked list as the buffer to store received packets. When the upper layer requests to receive data, it will pop up data from the linked list.
Definition at line 52 of file tcp_rcvwnd.h.
Constructor & Destructor Documentation
s3f::s3fnet::TCPRecvWindow::TCPRecvWindow (uint32 initseq, uint32 winsiz)
The constructor.
Definition at line 14 of file tcp_rcvwnd.cc.
                                                           :
   TCPSeqWindow(initseq, winsiz), seg_buffer(0),
   free_seg_list(0), highest_seqno(initseq),
   appl_rcvbuf(0), appl_rcvbuf_size(0), appl_data_rcvd(0) {}
s3f::s3fnet::TCPRecvWindow::~TCPRecvWindow ()
The destructor.
Definition at line 19 of file tcp_rcvwnd.cc.
References free_seg_list, s3f::s3fnet::TCPSegment::msg, s3f::s3fnet::TCPSegment::next, and seg_buffer.
 {
   while(seg_buffer)
   {
     TCPSegment* seg = seg_buffer->next;
     if(seg_buffer->msg) delete[] seg_buffer->msg;
     delete seg_buffer;
     seg_buffer = seg;
   }
   while(free_seg_list)
   {
     TCPSegment* seg = free_seg_list->next;
     delete free_seg_list;
     free_seg_list = seg;
   }
 }
Member Function Documentation
bool s3f::s3fnet::TCPRecvWindow::available ()
Whether there is new data available.
Definition at line 37 of file tcp_rcvwnd.cc.
References appl_data_rcvd, appl_rcvbuf, appl_rcvbuf_size, s3f::s3fnet::TCPSeqWindow::expect(), generate(), seg_buffer, and s3f::s3fnet::TCPSegment::seqno.
Referenced by s3f::s3fnet::TCPSession::receive().
 {
   // return true if new data is put into the application's receive
   // buffer set previously when TCPSession::recv() is called
   if(appl_rcvbuf_size > 0)
   {
     if(seg_buffer && seg_buffer->seqno <= expect())
     {
       appl_data_rcvd = generate(appl_rcvbuf_size, appl_rcvbuf);
       return appl_data_rcvd > 0;
     }
     else return false;
   }
   else return false;
 }
uint32 s3f::s3fnet::TCPRecvWindow::generate (uint32 length, byte * msg)
Generate the message of the given length and submit it to the upper layer.
Definition at line 53 of file tcp_rcvwnd.cc.
References add_a_free_segment(), s3f::s3fnet::TCPSeqWindow::expect(), s3f::s3fnet::TCPSegment::length, s3f::s3fnet::TCPSegment::msg, s3f::s3fnet::TCPSegment::next, seg_buffer, s3f::s3fnet::TCPSegment::seqno, and s3f::s3fnet::TCPSeqWindow::shift().
Referenced by s3f::s3fnet::TCPSession::appl_recv(), and available().
 {
   // we always grab one block from the buffer and report it to the
   // upper layer.
   uint32 request_len = length;
   while(seg_buffer && length > 0 && (expect() == seg_buffer->seqno))
   {
     // we consider the situation in which the upper layer has
     // requested different data lengths.
     if(length >= seg_buffer->length)
     {
       // can submit whole data block to the upper layer.
       if(msg)
       {
         if(seg_buffer->msg)
         {
           memcpy(msg, seg_buffer->msg, seg_buffer->length);
           delete[] seg_buffer->msg;
         }
         else
         {
                 memset(msg, 0, seg_buffer->length);
         }
         msg += seg_buffer->length;
       }
       else if(seg_buffer->msg)
       {
         delete[] seg_buffer->msg;
       }
       // update the start sequence number
       shift(seg_buffer->length);
       length -= seg_buffer->length;
       TCPSegment* seg = seg_buffer->next;
       add_a_free_segment(seg_buffer);
       seg_buffer = seg;
     }
     else
     {
       // we have to cut the current data block into two pieces.
       if(msg)
       {
         if(seg_buffer->msg)
         {
           memcpy(msg, seg_buffer->msg, length);
           byte* remain_msg = new byte[seg_buffer->length - length];
           memcpy(remain_msg, seg_buffer->msg+length, seg_buffer->length - length);
           delete [] seg_buffer->msg;
           seg_buffer->msg = remain_msg;
         }
         else
         {
                 memset(msg, 0, length);
         }
         msg += seg_buffer->length;
       }
       else if(seg_buffer->msg)
       {
         byte* remain_msg = new byte[seg_buffer->length - length];
         memcpy(remain_msg, seg_buffer->msg+length, seg_buffer->length - length);
         delete [] seg_buffer->msg;
         seg_buffer->msg = remain_msg;
       }
       // shorten the length of the remaining message.
       seg_buffer->seqno += length;
       seg_buffer->length -= length;
       // update the start sequence number
       shift(length);
       length = 0;
     }
   }
   return request_len - length;
 }
void s3f::s3fnet::TCPRecvWindow::addToBuffer (DataMessage * msg, uint32 seqno)
Add the message to the receive buffer.
Definition at line 130 of file tcp_rcvwnd.cc.
References add_to_buffer_helper(), s3f::s3fnet::DataChunk::next, s3f::s3fnet::DataMessage::payload, s3f::s3fnet::DataChunk::real_data, s3f::s3fnet::DataChunk::real_length, s3f::s3fnet::DataMessage::real_length, and s3f::s3fnet::TCPSeqWindow::use().
Referenced by s3f::s3fnet::TCPSession::process_new_data().
 {
   assert(msg);
   if(msg->real_length > 0)
   {
     bool new_data = add_to_buffer_helper(seqno, msg->real_length, (byte*)msg->payload);
     if(new_data && msg->payload) msg->payload = 0;
     use(msg->real_length);
   }
   else
   {
     DataChunk* node = (DataChunk*)msg->payload;
     while(node)
     {
       DataChunk* next_node = node->next;
       bool new_data = add_to_buffer_helper(seqno, node->real_length, node->real_data);
       if(new_data && node->real_data)
           node->real_data = 0;
       seqno += node->real_length;
       use(node->real_length);
       node = next_node;
     }
   }
 }
uint32 s3f::s3fnet::TCPRecvWindow::freeInBuffer () inline
The free space in the buffer.
Definition at line 71 of file tcp_rcvwnd.h.
References s3f::s3fnet::TCPSeqWindow::used(), and s3f::s3fnet::TCPSeqWindow::win_size.
Referenced by s3f::s3fnet::TCPSession::calc_advertised_wnd().
 { return win_size - used(); }
uint32 s3f::s3fnet::TCPRecvWindow::bufferSize () inline
The buffer size.
Definition at line 74 of file tcp_rcvwnd.h.
References s3f::s3fnet::TCPSeqWindow::win_size.
Referenced by s3f::s3fnet::TCPSession::calc_advertised_wnd().
 { return win_size; }
uint32 s3f::s3fnet::TCPRecvWindow::getHighestSeqno () inline
Return the highest sequence number ever received.
Definition at line 77 of file tcp_rcvwnd.h.
References highest_seqno.
 { return highest_seqno; }
uint32 s3f::s3fnet::TCPRecvWindow::getExpectedSeqno ()
Get the expected sequence number from the buffer; this is necessary because an ACK packet may be sent out before the buffer is released.
Definition at line 156 of file tcp_rcvwnd.cc.
References s3f::s3fnet::TCPSeqWindow::expect(), s3f::s3fnet::TCPSegment::next, and seg_buffer.
Referenced by s3f::s3fnet::TCPSession::acknowledge().
 {
   uint32 expect_no = expect();
   for(TCPSegment* seg = seg_buffer; seg; seg = seg->next)
   {
     // if the packet with the expect sequence number has already been
     // in the buffer, we find the next one
     if(expect_no >= seg->seqno) expect_no += seg->length;
     else return expect_no;
   }
   return expect_no;
 }
void s3f::s3fnet::TCPRecvWindow::setRecvParameters (uint32 bufsiz, byte * buf) inline
Set the application buffer to receive data.
Definition at line 90 of file tcp_rcvwnd.h.
References appl_rcvbuf, and appl_rcvbuf_size.
Referenced by s3f::s3fnet::TCPSession::appl_recv().
   {
     assert(appl_rcvbuf_size == 0 && appl_rcvbuf == 0);
     appl_rcvbuf_size = bufsiz;
     appl_rcvbuf = buf;
   }
void s3f::s3fnet::TCPRecvWindow::resetRecvParameters () inline
The application buffer no longer used.
Definition at line 98 of file tcp_rcvwnd.h.
References appl_rcvbuf, and appl_rcvbuf_size.
Referenced by s3f::s3fnet::TCPSession::receive().
   {
     appl_rcvbuf_size = 0; appl_rcvbuf = 0;
   }
uint32 s3f::s3fnet::TCPRecvWindow::dataReceived () inline
Return the number of bytes received last time.
Definition at line 104 of file tcp_rcvwnd.h.
References appl_data_rcvd.
Referenced by s3f::s3fnet::TCPSession::wake_app().
 { return appl_data_rcvd; }
bool s3f::s3fnet::TCPRecvWindow::add_to_buffer_helper (uint32 seqno, uint32 length, byte * msg) private
A helper function for addToBuffer.
Definition at line 169 of file tcp_rcvwnd.cc.
References get_a_segment(), highest_seqno, s3f::s3fnet::TCPSegment::length, s3f::s3fnet::TCPSegment::msg, mymax, s3f::s3fnet::TCPSegment::next, seg_buffer, s3f::s3fnet::TCPSegment::seqno, and s3f::s3fnet::TCPSegment::set().
Referenced by addToBuffer().
 {
   /* Copy the received message to the buffer, if msg is NULL, we will
     take it as fake data. Here we assume that the packet either
     overlaps completely with a packet already received, or is a
     totally new packet. In other words, the sender will never send out
     a partially overlapped packet. The method returns true if the data
     is new. Otherwise, it returns false. */
   if(length <= 0) return false;
   highest_seqno = mymax(highest_seqno, seqno + length - 1);
   // we use a linked list to put all segments.
   if(!seg_buffer)
   {
     // there is no segment in the buffer
     TCPSegment* seg = get_a_segment();
     seg->set(seqno, length, msg, 0);
     seg_buffer = seg;
     return true; // a new packet
   }
   else if(seqno < seg_buffer->seqno)
   {
     // if the newly arrived is a packet predates all received ones
     if(seqno + length == seg_buffer->seqno && !msg && !seg_buffer->msg)
     {
       // the new packet is just before the head packet in the buffer
       // and both of them use fake data. we can merge them together.
       seg_buffer->seqno = seqno;
       seg_buffer->length += length;
     }
     else
     {
       TCPSegment* seg = get_a_segment();
       seg->set(seqno, length, msg, seg_buffer);
       seg_buffer = seg;
     }
     return true; // a new packet
   }
   else if(seqno < seg_buffer->seqno + length)
   {
     // this must be an old packet; according to our assumption, there
     // must be a complete match
     return false;
   }
   else
   {
     // the new packet is after the already-received packet.
     TCPSegment* seg;
     for(seg = seg_buffer; seg->next && seqno >= seg->next->seqno; seg = seg->next);
     // check whether there is overlapping. when the loop stops, it
     // must be either seg->next is NULL or seqno < seg->next->segno;
     // therefore, the new packet can only overlap with the segment
     // pointed by seg.
     if(seqno < seg->seqno + seg->length)
     {
       // overlapping with an old packet
       return false;
     }
     else if(seqno == seg->seqno + seg->length && !msg && !seg->msg)
     {
       // contiguous packets and they both use fake data.
       seg->length += length;
       return true;
     }
     else
     {
       // non-overlapping, non-contiguous, just put it behind seg.
       TCPSegment* new_seg = get_a_segment();
       new_seg->set(seqno, length, msg, seg->next);
       seg->next = new_seg;
       return true;
     }
   }
 }
TCPSegment * s3f::s3fnet::TCPRecvWindow::get_a_segment () private
Return a free segment.
We use a list to keep old segments to save time on memory allocation.
Definition at line 245 of file tcp_rcvwnd.cc.
References free_seg_list, and s3f::s3fnet::TCPSegment::next.
Referenced by add_to_buffer_helper().
 {
   if(free_seg_list)
   {
     TCPSegment* ret = free_seg_list;
     free_seg_list = ret->next;
     return ret;
   }
   else
         return new TCPSegment();
 }
void s3f::s3fnet::TCPRecvWindow::add_a_free_segment (TCPSegment * seg) private
Add a segment to the free list.
Definition at line 257 of file tcp_rcvwnd.cc.
References free_seg_list, and s3f::s3fnet::TCPSegment::next.
Referenced by generate().
 {
   assert(seg);
   seg->next = free_seg_list;
   free_seg_list = seg;
 }
uint32 s3f::s3fnet::TCPSeqWindow::start () inline inherited
Return the first sequence of the window.
Definition at line 37 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::start_seqno.
Referenced by s3f::s3fnet::TCPSendWindow::generate(), s3f::s3fnet::TCPSession::init_state_established(), s3f::s3fnet::TCPSession::process_acks(), s3f::s3fnet::TCPSession::process_dup_acks(), s3f::s3fnet::TCPSession::sack_resend_segments(), and s3f::s3fnet::TCPSession::timeout_resend().
 { return start_seqno; }
uint32 s3f::s3fnet::TCPSeqWindow::end () inline inherited
Return the last sequence of the window.
Definition at line 40 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::start_seqno, and s3f::s3fnet::TCPSeqWindow::win_size.
 { return start_seqno + win_size - 1; }
uint32 s3f::s3fnet::TCPSeqWindow::firstUnused () inline inherited
Return the first unused sequence in the window.
Definition at line 43 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::start_seqno, and s3f::s3fnet::TCPSeqWindow::used_size.
Referenced by s3f::s3fnet::TCPSession::acknowledge(), s3f::s3fnet::TCPSession::appl_close(), s3f::s3fnet::TCPSession::appl_send(), s3f::s3fnet::TCPSession::fastTimeoutHandling(), s3f::s3fnet::TCPSession::init_state_fin_wait_1(), s3f::s3fnet::TCPSession::init_state_syn_received(), s3f::s3fnet::TCPSession::init_state_syn_sent(), s3f::s3fnet::TCPSession::process_dup_acks(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::TCPSession::sack_send_in_fast_recovery(), s3f::s3fnet::TCPSession::slow_timeout_handling_helper(), and s3f::s3fnet::TCPSession::timeout_resend().
 { return start_seqno + used_size; }
uint32 s3f::s3fnet::TCPSeqWindow::size () inline inherited
Return the size of the window.
Definition at line 46 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::win_size.
Referenced by s3f::s3fnet::TCPSession::calc_advertised_wnd().
 { return win_size; }
uint32 s3f::s3fnet::TCPSeqWindow::used () inline inherited
Return how much of the window is used up in bytes.
Definition at line 49 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::used_size.
Referenced by s3f::s3fnet::TCPSendWindow::canSend(), s3f::s3fnet::TCPSession::checkIdle(), freeInBuffer(), s3f::s3fnet::TCPSession::process_acks(), s3f::s3fnet::TCPSession::process_dup_acks(), s3f::s3fnet::TCPSession::process_new_acks(), and s3f::s3fnet::TCPSession::segment_and_send().
 { return used_size; }
uint32 s3f::s3fnet::TCPSeqWindow::unused () inline inherited
Return how much of the window is unused in bytes.
Definition at line 52 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::used_size, and s3f::s3fnet::TCPSeqWindow::win_size.
Referenced by s3f::s3fnet::TCPSession::process_dup_acks(), s3f::s3fnet::TCPSession::sack_send_in_fast_recovery(), and s3f::s3fnet::TCPSession::segment_and_send().
 { return (win_size - used_size); }
uint32 s3f::s3fnet::TCPSeqWindow::lengthTo (const uint32 seqno) inline inherited
Return the number of bytes between a give sequence number and the start of the window.
Definition at line 56 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::start_seqno.
Referenced by s3f::s3fnet::TCPSession::resend_segments().
 { return seqno - start_seqno; }
void s3f::s3fnet::TCPSeqWindow::setStart (const uint32 seqno) inline inherited
Set the start sequence number of the window.
Definition at line 63 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::start_seqno.
Referenced by s3f::s3fnet::TCPSession::active_open(), and s3f::s3fnet::TCPSession::process_SYN().
 { start_seqno = seqno; }
void s3f::s3fnet::TCPSeqWindow::shift (uint32 offset) inline inherited
Increase the lower edge of the window by offset number of bytes.
Definition at line 71 of file tcp_seqwnd.h.
References mymin, s3f::s3fnet::TCPSeqWindow::start_seqno, and s3f::s3fnet::TCPSeqWindow::used_size.
Referenced by generate(), and s3f::s3fnet::TCPSendWindow::release().
   {
     start_seqno += offset;
     used_size -= mymin(offset, used_size);
   }
void s3f::s3fnet::TCPSeqWindow::expand (uint32 nbytes) inline inherited
Expand the window size by nbytes.
Note that the new size must not be larger than the buffer size—the condition is not enforced by this method.
Definition at line 80 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::win_size.
Referenced by s3f::s3fnet::TCPSession::calc_advertised_wnd().
 { win_size += nbytes; }
void s3f::s3fnet::TCPSeqWindow::shrink (uint32 nbytes) inline inherited
Shrink the size of the window by nbytes.
One can only shrink the size of unused space.
Definition at line 84 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::used_size, and s3f::s3fnet::TCPSeqWindow::win_size.
   {
     assert(nbytes <= (win_size - used_size));
     win_size -= nbytes;
   }
bool s3f::s3fnet::TCPSeqWindow::use (uint32 nbytes) inline inherited
Use up nbytes of the window with data.
Returns true if success, i.e., there is available unused space for this operation.
Definition at line 92 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::used_size, and s3f::s3fnet::TCPSeqWindow::win_size.
Referenced by addToBuffer(), and s3f::s3fnet::TCPSession::segment_and_send().
   {
     if(used_size + nbytes > win_size) return false;
     used_size += nbytes;
     return true;
   }
void s3f::s3fnet::TCPSeqWindow::setSYN (bool syn) inline inherited
set SYN bit.
Definition at line 104 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::seq_shift(), s3f::s3fnet::TCPSeqWindow::syn_included, and s3f::s3fnet::TCPSeqWindow::used_size.
Referenced by s3f::s3fnet::TCPSession::init_state_syn_received(), s3f::s3fnet::TCPSession::init_state_syn_sent(), s3f::s3fnet::TCPSession::process_ACK(), and s3f::s3fnet::TCPSession::process_SYN().
   {
     if(syn) assert(used_size == 0);
     else seq_shift(1);
     syn_included = syn ? 1 : 0;
   }
void s3f::s3fnet::TCPSeqWindow::setFIN (bool fin) inline inherited
set FIN bit.
Definition at line 112 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::fin_included, and s3f::s3fnet::TCPSeqWindow::seq_shift().
Referenced by s3f::s3fnet::TCPSession::appl_close(), s3f::s3fnet::TCPSession::init_state_fin_wait_1(), s3f::s3fnet::TCPSession::process_ACK(), and s3f::s3fnet::TCPSession::process_FIN().
   {
     if(!fin) seq_shift(1);
     fin_included = fin ? 1 : 0;
   }
bool s3f::s3fnet::TCPSeqWindow::synAtFront () inline inherited
Return true if SYN segment is in the window.
Definition at line 119 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::syn_included.
Referenced by s3f::s3fnet::TCPSession::init_state_established().
 { return syn_included; }
bool s3f::s3fnet::TCPSeqWindow::finAtFront () inline inherited
Return true if FIN segment is in the window.
Definition at line 122 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::fin_included, and s3f::s3fnet::TCPSeqWindow::used_size.
Referenced by s3f::s3fnet::TCPSession::init_state_established().
 { return (fin_included && used_size == 0); }
uint32 s3f::s3fnet::TCPSeqWindow::next () inline inherited
Like firstUnused method, but also uses SYN & FIN segments; the method is used for sending window.
Definition at line 126 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::fin_included, s3f::s3fnet::TCPSeqWindow::start_seqno, s3f::s3fnet::TCPSeqWindow::syn_included, and s3f::s3fnet::TCPSeqWindow::used_size.
Referenced by s3f::s3fnet::TCPSession::abort(), s3f::s3fnet::TCPSession::init_state_last_ack(), s3f::s3fnet::TCPSession::init_state_syn_received(), s3f::s3fnet::TCPSession::process_ACK(), and s3f::s3fnet::TCPSession::process_acks().
 { return start_seqno+used_size+syn_included+fin_included; }
uint32 s3f::s3fnet::TCPSeqWindow::expect () inline inherited
Like start method, but also uses SYN & FIN segments; the method is used for receiving window.
Definition at line 130 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::fin_included, s3f::s3fnet::TCPSeqWindow::start_seqno, and s3f::s3fnet::TCPSeqWindow::syn_included.
Referenced by s3f::s3fnet::TCPSession::abort(), s3f::s3fnet::TCPSession::appl_close(), available(), s3f::s3fnet::TCPSession::fastTimeoutHandling(), generate(), getExpectedSeqno(), s3f::s3fnet::TCPSession::init_state_fin_wait_1(), s3f::s3fnet::TCPSession::init_state_last_ack(), s3f::s3fnet::TCPSession::init_state_syn_received(), s3f::s3fnet::TCPSession::init_state_syn_sent(), s3f::s3fnet::TCPSession::process_ACK(), s3f::s3fnet::TCPSession::resend_segments(), s3f::s3fnet::TCPSession::segment_and_send(), s3f::s3fnet::TCPSession::slow_timeout_handling_helper(), and s3f::s3fnet::TCPSession::timeout_resend().
 { return start_seqno+syn_included+fin_included; }
bool s3f::s3fnet::TCPSeqWindow::within (uint32 seqno) inline inherited
Returns true iff 'seqno' is within the window.
Definition at line 137 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::fin_included, s3f::s3fnet::TCPSeqWindow::start_seqno, s3f::s3fnet::TCPSeqWindow::syn_included, and s3f::s3fnet::TCPSeqWindow::win_size.
Referenced by s3f::s3fnet::TCPSession::process_new_data().
   {
     return (start_seqno+syn_included+fin_included <= seqno &&
             seqno < start_seqno+syn_included+fin_included+win_size);
   }
bool s3f::s3fnet::TCPSeqWindow::isUsed (uint32 seqno) inline inherited
Returns true iff 'seqno' is used within the window.
Definition at line 144 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::start_seqno, and s3f::s3fnet::TCPSeqWindow::used_size.
   {
     return (start_seqno <= seqno && seqno < start_seqno + used_size);
   }
bool s3f::s3fnet::TCPSeqWindow::empty () inline inherited
Returns true iff the window is empty (nothing used).
Definition at line 150 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::used_size.
Referenced by s3f::s3fnet::TCPSession::appl_close(), s3f::s3fnet::TCPSession::init_state_close_wait(), s3f::s3fnet::TCPSession::init_state_closing(), s3f::s3fnet::TCPSession::init_state_fin_wait_1(), s3f::s3fnet::TCPSession::process_FIN(), and s3f::s3fnet::TCPSession::receive().
 { return (used_size == 0); }
void s3f::s3fnet::TCPSeqWindow::reset () inline inherited
Resets the window.
Definition at line 153 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::fin_included, s3f::s3fnet::TCPSeqWindow::syn_included, and s3f::s3fnet::TCPSeqWindow::used_size.
Referenced by s3f::s3fnet::TCPSession::init_state_listen(), and s3f::s3fnet::TCPSendWindow::reset().
 { used_size = 0; syn_included = fin_included = 0; }
void s3f::s3fnet::TCPSeqWindow::seq_shift (uint32 offset) inline protected inherited
Shift the window by the given offset permanently.
Definition at line 157 of file tcp_seqwnd.h.
References s3f::s3fnet::TCPSeqWindow::start_seqno.
Referenced by s3f::s3fnet::TCPSeqWindow::setFIN(), and s3f::s3fnet::TCPSeqWindow::setSYN().
 { start_seqno += offset; }
Member Data Documentation
TCPSegment* s3f::s3fnet::TCPRecvWindow::seg_buffer private
A buffer to put received segments.
Definition at line 121 of file tcp_rcvwnd.h.
Referenced by add_to_buffer_helper(), available(), generate(), getExpectedSeqno(), and ~TCPRecvWindow().
TCPSegment* s3f::s3fnet::TCPRecvWindow::free_seg_list private
A list of unused segments.
Definition at line 124 of file tcp_rcvwnd.h.
Referenced by add_a_free_segment(), get_a_segment(), and ~TCPRecvWindow().
uint32 s3f::s3fnet::TCPRecvWindow::highest_seqno private
The highest sequence number received.
Definition at line 127 of file tcp_rcvwnd.h.
Referenced by add_to_buffer_helper(), and getHighestSeqno().
byte* s3f::s3fnet::TCPRecvWindow::appl_rcvbuf private
The buffer (owned by application) to receive data.
Definition at line 130 of file tcp_rcvwnd.h.
Referenced by available(), resetRecvParameters(), and setRecvParameters().
uint32 s3f::s3fnet::TCPRecvWindow::appl_rcvbuf_size private
Total number of bytes expected to receive.
Definition at line 133 of file tcp_rcvwnd.h.
Referenced by available(), resetRecvParameters(), and setRecvParameters().
uint32 s3f::s3fnet::TCPRecvWindow::appl_data_rcvd private
The size of the received data (that has been put into the receive buffer).
Definition at line 137 of file tcp_rcvwnd.h.
Referenced by available(), and dataReceived().
uint32 s3f::s3fnet::TCPSeqWindow::start_seqno protected inherited
Starting sequence number of the window.
Definition at line 161 of file tcp_seqwnd.h.
Referenced by s3f::s3fnet::TCPSeqWindow::end(), s3f::s3fnet::TCPSeqWindow::expect(), s3f::s3fnet::TCPSeqWindow::firstUnused(), s3f::s3fnet::TCPSeqWindow::isUsed(), s3f::s3fnet::TCPSeqWindow::lengthTo(), s3f::s3fnet::TCPSeqWindow::next(), s3f::s3fnet::TCPSeqWindow::seq_shift(), s3f::s3fnet::TCPSeqWindow::setStart(), s3f::s3fnet::TCPSeqWindow::shift(), s3f::s3fnet::TCPSeqWindow::start(), and s3f::s3fnet::TCPSeqWindow::within().
uint32 s3f::s3fnet::TCPSeqWindow::win_size protected inherited
Size of the window in bytes.
Definition at line 164 of file tcp_seqwnd.h.
Referenced by bufferSize(), s3f::s3fnet::TCPSeqWindow::end(), s3f::s3fnet::TCPSeqWindow::expand(), freeInBuffer(), s3f::s3fnet::TCPSeqWindow::shrink(), s3f::s3fnet::TCPSeqWindow::size(), s3f::s3fnet::TCPSeqWindow::unused(), s3f::s3fnet::TCPSeqWindow::use(), and s3f::s3fnet::TCPSeqWindow::within().
uint32 s3f::s3fnet::TCPSeqWindow::used_size protected inherited
How many bytes are used in window.
Definition at line 167 of file tcp_seqwnd.h.
Referenced by s3f::s3fnet::TCPSeqWindow::empty(), s3f::s3fnet::TCPSeqWindow::finAtFront(), s3f::s3fnet::TCPSeqWindow::firstUnused(), s3f::s3fnet::TCPSeqWindow::isUsed(), s3f::s3fnet::TCPSeqWindow::next(), s3f::s3fnet::TCPSeqWindow::reset(), s3f::s3fnet::TCPSeqWindow::setSYN(), s3f::s3fnet::TCPSeqWindow::shift(), s3f::s3fnet::TCPSeqWindow::shrink(), s3f::s3fnet::TCPSeqWindow::unused(), s3f::s3fnet::TCPSeqWindow::use(), and s3f::s3fnet::TCPSeqWindow::used().
int s3f::s3fnet::TCPSeqWindow::syn_included protected inherited
Whether SYN is in window.
Definition at line 170 of file tcp_seqwnd.h.
Referenced by s3f::s3fnet::TCPSeqWindow::expect(), s3f::s3fnet::TCPSeqWindow::next(), s3f::s3fnet::TCPSeqWindow::reset(), s3f::s3fnet::TCPSeqWindow::setSYN(), s3f::s3fnet::TCPSeqWindow::synAtFront(), and s3f::s3fnet::TCPSeqWindow::within().
int s3f::s3fnet::TCPSeqWindow::fin_included protected inherited
Whether FIN is in window.
Definition at line 173 of file tcp_seqwnd.h.
Referenced by s3f::s3fnet::TCPSeqWindow::expect(), s3f::s3fnet::TCPSeqWindow::finAtFront(), s3f::s3fnet::TCPSeqWindow::next(), s3f::s3fnet::TCPSeqWindow::reset(), s3f::s3fnet::TCPSeqWindow::setFIN(), and s3f::s3fnet::TCPSeqWindow::within().
The documentation for this class was generated from the following files:
tcp_rcvwnd.h
tcp_rcvwnd.cc