S3F: s3f::s3fnet::TCPClientSessionCallbackActivation Class Reference
s3f::s3fnet::TCPClientSessionCallbackActivation Class Reference
Stores the data for the callback function.
#include <tcp_client.h>
Public Member Functions
TCPClientSessionCallbackActivation (ProtocolSession *sess, TCPClientSessionContinuation *tcp_cnt)
Constructor.
virtual ~TCPClientSessionCallbackActivation ()
unsigned int get_type ()
virtual Message * clone ()
virtual void erase ()
virtual void erase_all ()
void inc_evts ()
int dec_evts ()
Public Attributes
TCPClientSessionContinuation * cnt
ProtocolSession * session
Protected Attributes
unsigned int __type
int __evts
Detailed Description
Stores the data for the callback function.
In this case, the TCPClientSession object and the TCPClientSessionContinuation object are stored.
Definition at line 253 of file tcp_client.h.
Constructor & Destructor Documentation
s3f::s3fnet::TCPClientSessionCallbackActivation::TCPClientSessionCallbackActivation (ProtocolSession * sess, TCPClientSessionContinuation * tcp_cnt) inline
Constructor.
Definition at line 259 of file tcp_client.h.
                                                                                                          :
                 ProtocolCallbackActivation(sess), cnt(tcp_cnt){};
virtual s3f::s3fnet::TCPClientSessionCallbackActivation::~TCPClientSessionCallbackActivation () inline virtual
Definition at line 265 of file tcp_client.h.
 {};
Member Function Documentation
unsigned int Message::get_type () inline inherited
Definition at line 23 of file message.h.
References Message::__type.
 { return __type; }
Message * Message::clone () virtual inherited
Reimplemented in s3f::s3fnet::DataMessage, s3f::s3fnet::ProtocolMessage, PholdMessage, s3f::s3fnet::TCPMessage, s3f::s3fnet::OpenFlowMessage, s3f::s3fnet::OpenVZMessage, s3f::s3fnet::SimpleMacMessage, s3f::s3fnet::DummyMessage, s3f::s3fnet::UDPMessage, and s3f::s3fnet::IPMessage.
Definition at line 29 of file message.cc.
References Message::__evts, Message::__type, and Message::Message().
Referenced by OutChannel::write().
{
         Message* msg = new Message();
         msg->__type = __type;
         msg->__evts = 0;
         return msg;
 }
virtual void Message::erase () inline virtual inherited
Reimplemented in s3f::s3fnet::ProtocolMessage.
Definition at line 25 of file message.h.
 {};
virtual void Message::erase_all () inline virtual inherited
Reimplemented in s3f::s3fnet::ProtocolMessage.
Definition at line 26 of file message.h.
Referenced by s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::NetworkInterface::receivePacket(), and OutChannel::write().
 {};
void Message::inc_evts () inline inherited
Definition at line 28 of file message.h.
References Message::__evts.
Referenced by Event::Event().
 { __evts++; }
int Message::dec_evts () inline inherited
Definition at line 29 of file message.h.
References Message::__evts.
Referenced by Event::~Event().
 { return --__evts; }
Member Data Documentation
TCPClientSessionContinuation* s3f::s3fnet::TCPClientSessionCallbackActivation::cnt
Definition at line 265 of file tcp_client.h.
ProtocolSession* s3f::s3fnet::ProtocolCallbackActivation::session inherited
Definition at line 358 of file protocol_session.h.
Referenced by s3f::s3fnet::ProtocolCallbackActivation::ProtocolCallbackActivation().
unsigned int Message::__type protected inherited
Definition at line 31 of file message.h.
Referenced by Message::clone(), Message::get_type(), Message::Message(), and Message::operator=().
int Message::__evts protected inherited
Definition at line 32 of file message.h.
Referenced by Message::clone(), Message::dec_evts(), Message::inc_evts(), Message::Message(), and Message::operator=().
The documentation for this class was generated from the following file:
tcp_client.h