S3F: Timeline Class Reference
Timeline Class Reference
Timeline is a logical process in concept, and a pthread by implementation.
#include <timeline.h>
Public Member Functions
Timeline (TimelineInterface *)
At creation a Timeline is given a pointer to a data structure that is the interface between the Timeline and Interface objects.
virtual ~Timeline ()
ltime_t now ()
A timeline can be queried for the simulation time, either the time stamp of the last event executed, or (if the state is not RUNNING) the largest time in the synchronization window last completed.
ltime_t horizon ()
The synchronization horizon, the upper edge of the current synchronization window.
TimelineState get_state ()
Reports the state of the Timeline.
unsigned s3fid ()
Returns the id for this timeline, between 0 and the number of created timelines minus 1.
int get_log_ticks_per_sec ()
The simulation clock is a long integer.
TimelineInterface * get_timeline_interface ()
Return the pointer of the TimelineInterface class.
void * thread_function ()
This is the code body of the Timeline thread.
Static Public Attributes
static pthread_mutex_t timeline_class_mutex
Synchronizes access to __entity_list.
static unsigned int __num_timelines = 0
Enumerates the number of Timeline instances created.
static int default_sched_pri
Calls to schedule that could provide a priority for same-time tie-breking but do not are given this default_sched_pri.
static int min_sched_pri
minimum possible scheduling priority, used only by a timeline, not a user priority
static vector< Timeline * > timeline_adrs
Protected Member Functions
HandleCode schedule (Process *, ltime_t, unsigned int, Activation)
Schedule the given process activation, at the given time, using the provided Activation record.
HandleCode schedule (InChannel *, ltime_t, unsigned int, Activation)
Schedule the given arrival, at the given time, delivering the provided Activation record.
void schedule (InChannel *, Process *, bool, unsigned int)
In order to avoid an infinite loop where an process that was activated by an arrival on an inchannel calls waitOn for that inchannel AGAIN and just gets picked again to execute, we schedule attachments to the inchannel's waiting list to occur after all the user events at the current execution time have taken place.
Process * get_running_proc ()
Timeline variable __this points to the Process currently executing (NULL if the Timeline state is not RUNNING).
ltime_t next_time ()
Return the timestamp of the event with least timestamp of the two event-lists.
void cross_timeline_delay (ltime_t d)
As mapto calls are made, each one that crosses timeline boundaries has its minimum delay value reported to the timeline, using this method.
void all_timeline_delay (ltime_t)
void same_timeline_delay (ltime_t)
ltime_t min_sync_cross_timeline_delay (ltime_t thrs)
This computation finds among all OutChannels owned by Entities aligned to this Timeline, the smallest minimum delay no smaller than thrs among mappings to InChannels on other timelines.
ltime_t min_sync_all_timeline_delay (ltime_t thrs)
unsigned int count_min_delay_crossings (ltime_t)
Count the number of connections whose minimum delay values are no smaller than the argument.
ltime_t get_min_sync_cross_timeline_delay ()
Returns the value of __min_sync_cross_timeline_delay.
ltime_t get_min_sync_all_timeline_delay ()
Returns the value of __min_sync_all_timeline_delay.
ltime_t get_min_sync_same_timeline_delay ()
Returns the value of __min_sync_same_timeline_delay.
void initialize_appt (bool, ltime_t)
unsigned long get_nxt_handle ()
void get_cross_timeline_events ()
Writes that cross timelines are buffered until the beginning of the next synchronization window; when buffered, a description of the write is placed in a list associated with the Timeline where the InChannel endpoint resides.
void change_state (TimelineState s)
Changes Timeline state variable __state to s.
InChannel * get_activeChannel ()
void put_activeChannel (InChannel *inc)
unsigned long get_executed ()
unsigned long get_work_executed ()
unsigned long get_sync_executed ()
void sync_window ()
The heart of the thread_body is code that establishes a synchronization window, and then all Timelines execute asynchronously up to the time established as an upper bound.
bool global_continue ()
Called after a window synchronization to see if the conditions for continuing execution are meet.
void select_next_event (int &evt_list, ltime_t &evt_time)
Select which event_list of the two (__events and __ve_sink_events) has the next event.
void sim_global_scheduler_one_epoch ()
void sim_emu_global_scheduler_one_epoch ()
ltime_t ve_proxy_entity_potential_impact_time ()
void manual_binding_thread_to_core ()
Private Attributes
TimelineState __state
The current state of the Timeline, (one of INITIALIZING, RUNNING, BLOCKED).
unsigned int __s3fid
This Timeline's own id.
Process * __this
Just before a Process body is executed, __this is set to point to the instance of the Process.
TimelineInterface * __interface_control
When the Timeline is created an run, an s3f::Interface object has filled out information describing how it wishes the simulation to advance during the next epoch of time.
vector< Entity * > __entity_list
This list holds a pointer for every Entity aligned to this Timeline.
ltime_t __min_sync_cross_timeline_delay
Minimum transfer delay among all cross-timeline channels in this timeline.
ltime_t __min_sync_all_timeline_delay
Minimum transfer delay among all channels in this timeline (non-cross-timeline and cross-timeline).
ltime_t __min_sync_same_timeline_delay
Minimum transfer delay among all non-cross-timeline channels in this timeline.
ltime_t __window_size
unsigned int __channels_at_minimum
After __min_sync_cross_timeline_delay is computed, we count the number of connections whose minimum delay values are exactly this.
bool __recompute_min_delay
Set to false at the beginning of a synchronization window, __recompute_min_delay is set to true if a dynamically called mapto or an unmap call remove the last known connection with minimum delay value __min_sync_cross_timeline_delay.
int __log_ticks_per_sec
Scale factor for virtual time clock, gives the logarithm base 10 of the number of clock ticks (increment of 1 on the clock variable) in each virtual time second.
ltime_t __time
The virtual time up to which the timeline has advanced.
ltime_t __stop_before
This holds the result of a window calculation by all simulation threads, establishing an upper bound on how far they may simulate this window.
unsigned int __window
This integer keeps track of the number of synchronization windows that have been completed.
InChannel * __activeChannel
vector< EventPtr > __window_list
Vector holding description of cross timeline writes.
pthread_mutex_t __events_mutex
Access to __window_list is guarded by mutex __events_mutex.
pthread_mutex_t timeline_inst_mutex
pthread_cond_t __appointment_cond_var
When a timeline encounters an incoming appointment time from a timeline, whose time has not yet reached the appointment, it waits on this condition variable.
Timeline * __waiting_on_timeline
When a timeline reaches an incoming appointment and finds that the timeline it awaits has not yet reached the synchronization point, it puts that Timeline's address in this variable and does a wait on the condition variable.
vector< mappedChannel * > __channels_to_map
When mapto is called during execution of the simulation it may be necessary to delay its implementation until the end of the current simulation window.
vector< mappedChannel * > __delays_to_change
The s3f interface to OutChannels allows for dynamic adjustment to the minimum delay on some specified connection.
vector< InAppointment > __in_appt
vector< OutAppointment > __out_appt
STL_EventList __events
The event list.
STL_EventList __ve_sink_events
Used for integrated with openVZ-based network emulation.
unsigned long __handle_idx
unsigned long __executed
unsigned long __work_executed
unsigned long __sync_executed
unsigned long __executed_one_window
unsigned long __work_executed_one_window
unsigned long __sync_executed_one_window
unsigned int __evtnum
bool __no_global_check
ltime_t t_prime
time of first executed deliver-to-VE event in previous SSW
Friends
void * proxy_function (void *)
Detailed Description
Timeline is a logical process in concept, and a pthread by implementation.
Multiple S3F entities can be assigned to a timeline and thus being processed by a hardware core.
Definition at line 51 of file timeline.h.
Constructor & Destructor Documentation
Timeline::Timeline (TimelineInterface * tli)
At creation a Timeline is given a pointer to a data structure that is the interface between the Timeline and Interface objects.
Definition at line 20 of file timeline.cc.
References __activeChannel, __appointment_cond_var, __channels_at_minimum, __events_mutex, __executed, __executed_one_window, __handle_idx, __in_appt, __log_ticks_per_sec, __min_sync_all_timeline_delay, __min_sync_cross_timeline_delay, __min_sync_same_timeline_delay, __no_global_check, __num_timelines, __out_appt, __s3fid, __state, __sync_executed, __sync_executed_one_window, __this, __time, __work_executed, __work_executed_one_window, default_sched_pri, TimelineInterface::get_log_ticks_per_sec(), TimelineInterface::get_next_action(), TimelineInterface::get_numTimelines(), INITIALIZING, min_sched_pri, STOP_FUNCTION, t_prime, timeline_adrs, timeline_class_mutex, and timeline_inst_mutex.
                                           :
                          __interface_control(tli), __evtnum(0)  {
         // mutex for Timeline state must be initialized
         pthread_mutex_init(&timeline_inst_mutex, NULL);
         // mutex guarding __window_list must be initialized
         pthread_mutex_init(&__events_mutex,NULL);
         pthread_cond_init(&__appointment_cond_var, NULL);
         // always start at time 0.  Change this?
         __time = 0;
         // interface tells us what the timescale is, remember it
         __log_ticks_per_sec = tli->get_log_ticks_per_sec();
         // -1 means no meaningful value
         __min_sync_cross_timeline_delay = -1;
         __min_sync_all_timeline_delay = -1;
         __min_sync_same_timeline_delay = -1;
         __channels_at_minimum = 0;
         // we always start in the initialization state, no process running
         __state = INITIALIZING;
         __this  = NULL;
         __activeChannel = NULL;
         __executed = __work_executed = __sync_executed = 0;
         __executed_one_window = __work_executed_one_window = __sync_executed_one_window = 0;
         // the default scheduling priority from the user's perspective
         // is the largest unsigned integer you can represent in 16 bits
         default_sched_pri = (1<<16)-1;
         // minimum scheduling priority from the system's perspective
         min_sched_pri = INT_MAX;
         __handle_idx = 0;
         // get a unique id for this timeline.  Just in case there
         // are multiple threads building timelines, protect the access
         // with the static Timeline class mutex
         //
         pthread_mutex_lock(&timeline_class_mutex);
         __s3fid = __num_timelines++;
         timeline_adrs.push_back(this);
         pthread_mutex_unlock(&timeline_class_mutex);
         // initialize appointment vectors
         int num_timelines = (int)tli->get_numTimelines();
         __in_appt.resize(num_timelines);
         __out_appt.resize(num_timelines);
         // initialize flag indicating whether to call a timeline interface
         // function to see if a global termination condition has been met
         if( tli->get_next_action() == STOP_FUNCTION ) __no_global_check = false;
         else __no_global_check = true;
 #ifdef OPENVZ_EMULATION_LOOKAHEAD
         ve_lookahead = -1;
 #endif
         t_prime = 0;
 }
Timeline::~Timeline () virtual
Definition at line 1352 of file timeline.cc.
References __appointment_cond_var, __events, __events_mutex, __in_appt, __out_appt, __ve_sink_events, STL_EventList::empty(), STL_EventList::pop(), s3fid(), timeline_class_mutex, and timeline_inst_mutex.
                      {
         while(!__events.empty()) {
                 __events.pop();
         }
         while(!__ve_sink_events.empty()) {
                 __ve_sink_events.pop();
         }
         // destroy mutexes and cond_var
         //
         if( !s3fid() ) pthread_mutex_destroy(&timeline_class_mutex);
 #ifdef PTHREAD_BARRIER
         if( !s3fid() ) pthread_mutex_destroy(&bottom_barrier_min_value_mutex);
         if( !s3fid() ) pthread_mutex_destroy(&emu_window_barrier_min_value_mutex);
 #endif
         pthread_mutex_destroy(&__events_mutex);
         pthread_mutex_destroy(&timeline_inst_mutex);
         pthread_cond_destroy(&__appointment_cond_var);
         for(unsigned int i=0; i<__in_appt.size(); i++) {
                 pthread_mutex_destroy(&__in_appt[i].appt_mutex);
         }
         for(unsigned int i=0; i<__out_appt.size(); i++) {
                 pthread_mutex_destroy(&__out_appt[i].appt_mutex);
         }
 }
Member Function Documentation
ltime_t Timeline::now () inline
A timeline can be queried for the simulation time, either the time stamp of the last event executed, or (if the state is not RUNNING) the largest time in the synchronization window last completed.
Definition at line 67 of file timeline.h.
References __time.
Referenced by OutChannel::new_transfer_delay(), Entity::now(), and schedule().
 { return __time; }
ltime_t Timeline::horizon () inline
The synchronization horizon, the upper edge of the current synchronization window.
Definition at line 70 of file timeline.h.
References __stop_before.
Referenced by OutChannel::mapto(), OutChannel::new_min_write_delay(), OutChannel::new_transfer_delay(), schedule(), and OutChannel::write().
 { return __stop_before; }
TimelineState Timeline::get_state () inline
Reports the state of the Timeline.
Definition at line 73 of file timeline.h.
References __state.
Referenced by OutChannel::new_transfer_delay().
 { return __state; }
unsigned Timeline::s3fid () inline
Returns the id for this timeline, between 0 and the number of created timelines minus 1.
Definition at line 76 of file timeline.h.
References __s3fid.
Referenced by initialize_appt(), schedule(), sim_global_scheduler_one_epoch(), sync_window(), thread_function(), and ~Timeline().
 { return __s3fid; }
int Timeline::get_log_ticks_per_sec () inline
The simulation clock is a long integer.
When the Interface to the simulation is created, a scale factor describing the units is given in terms of the logarithm (base 10) of the number of integer ticks per second of virtual time. This methods reports that value.
Definition at line 83 of file timeline.h.
References __log_ticks_per_sec.
Referenced by Entity::BuildEntity().
 { return __log_ticks_per_sec; }
TimelineInterface* Timeline::get_timeline_interface () inline
Return the pointer of the TimelineInterface class.
There is only one TimelineInterface*.
Definition at line 88 of file timeline.h.
References __interface_control.
 { return __interface_control; }
void * Timeline::thread_function ()
This is the code body of the Timeline thread.
It synchronizes with other Timelines, it interacts with the event data structures, it calls the Process functions associated with waitFor timeouts and waitOn deliveries.
A Timeline is a pthread, and thread_function is the code body declared for it. All of Timeline processing happens within this function or calls made from it.
The interface specifies an epoch of simulation time to cover, by specifying the simulation time to and beyond no Timeline may advance. The timeline awaits that specification by engaging in a barrier synchronization with all other Timelines and the control thread on barrier variable "window_barrier".
The call starts by synchronizing with all other Timelines and the control thread through the "window_barrier" barrier construct. It blocks there until all Timeline threads and the control thread have reached it. In particular, the control thread does not enter that barrier until it has put information about the first synchronization epoch in the the interface it provides.
The epoch is divided into a number of synchronization windows, constructed in such a way that during a synchronization window all Timelines may execute events asynchronously. After the upper edge of a synchronization window is computed, it is compared with the epoch stopping time. If the latter is smaller, the stopping point for that cycle becomes the epoch stopping time.
Execution of a synchronization window may cause events to be created on one Timeline, to be executed on a different one. Such events are buffered in a list associated with the target Timeline. Therefore, each synchronization window begins calling method get_cross_timeline_events() to transfer those events into the Timeline's event list. After this is done the Timeline's event list has all the events it will do in the coming window, and the next step is to compute the upper edge of the synchronization window.
Each Timeline offers to a global min-reduction the sum of
(i) The earliest time of any event in its event list, and
(ii) The smallest minimum delay associated with any connection that crosses timelines and has the outchannel on this Timeline.
The minimum computed defines a time before which it is impossible for an event created on one timeline to have to be executed on another. That minimum is the upper edge of the synchronization window.
Once the window is defined, method sync_window() is called to do all the processing associated with the window.
Different barrier variables are used to control the synchronization window, ones that only the Timelines use (as the control thread is waiting on the window_barrier instance for the epoch to finish.
On return from sync_window() it may be necessary to implement mapto calls that could not be executed dynamically, and changes of minimum delays on connections that likewise could not be executed dynamically. As a result of these it may be necessary to recompute this Timeline's smallest cross timeline minimum delay. Following this, the Timeline repeats the cycle for another synchronization window, or enters the window barrier again which synchronizes all Timeline threads and the control thread, and releases the control thread when the epoch is completed.
Definition at line 311 of file timeline.cc.
References __interface_control, __no_global_check, __time, TimelineInterface::get_next_action(), TimelineInterface::get_stop_before(), TimelineInterface::isOpenVZEmu, s3fid(), sim_emu_global_scheduler_one_epoch(), sim_global_scheduler_one_epoch(), STOP_BEFORE_TIME, and STOP_FUNCTION.
{
         // variables used in the loop below
         ltime_t epoch_end;
         while(1) {
                 // wait for all Timelines to reach this, and the control thread
                 // to put epoch information in the interface
 #ifdef MUTEX_BARRIER
                 __interface_control->window_barrier.wait( -1 );
 #endif
 #ifdef SCHED_YIELD_BARRIER
                 __interface_control->window_barrier.wait( s3fid(), -1 );
 #endif
 #ifdef PTHREAD_BARRIER
                 pthread_barrier_wait( &(__interface_control->window_barrier) );
 #endif
                 //
                 // Before entering the top_barrier to release
                 // the simulation threads, the control thread filled
                 // out the interface with parameters describing
                 // the first window
                 //
                 epoch_end = __interface_control->get_stop_before();
                 if( __interface_control->get_next_action() == STOP_BEFORE_TIME )
                 {
                         //not accidentally process any events after the epoch end
                         if(epoch_end <= __time+1) break;
                 }
                 if( __interface_control->get_next_action() == STOP_FUNCTION )
                         __no_global_check = false;
                 else __no_global_check = true;
                 // enter the loop of doing synchronization windows until the full simulation epoch is covered.
 #ifdef OPENVZ_EMULATION
                 if(__interface_control->isOpenVZEmu == true)
                         sim_emu_global_scheduler_one_epoch();
                 else
                         sim_global_scheduler_one_epoch();
 #else
                 sim_global_scheduler_one_epoch();
 #endif
         }
         return (void *)NULL;
 }
HandleCode Timeline::schedule (Process * proc, ltime_t t, unsigned int pri, Activation act) protected
Schedule the given process activation, at the given time, using the provided Activation record.
Return a handle for cancelation. Necessarily the process belongs to an entity aligned to this timeline, but this has not yet been checked. Throw an assertion if violated
A timeline can directly schedule the execution of a given Process (if the Process is owned by an Entity aligned to this Timeline). An "Activation" is given as an argument to any Process whose execution results. An Activation is a std::tr1::shared_ptr protecting a pointer to a message derived from base class Message. Its use alleviates issues of copying and deleting messages. The unsigned int is a priority used in tie-breaking activations scheduled at the same time. It return a "HandleCode" that can be used to cancel the action scheduled.
Parameters
proc the process whose activation is scheduled
t the time of the activation
pri a priority used as a tie-breaker when events have the same base time
act a smart pointer wrapper around an instance of a class derived from class Message, the payload.
Definition at line 105 of file timeline.cc.
References __events, __evtnum, Entity::alignment(), Process::owner(), and STL_EventList::push().
Referenced by InChannel::insertion_gateway(), Entity::waitFor(), and OutChannel::write().
{
         // can only directly schedule a Process if its owner is on this timeline
         assert( proc->owner()->alignment() == this );
         // create a timeout event to be scheduled on this timeline,
         Event* e = new Event(t, pri, proc, act, this, __evtnum++);
         if (!e)
         {
                 printf ("Timeline::schedule(), unable to allocate memory for TIMEOUT (probably) event\n");
                 exit(0);
         }
         HandleCode h = (void *)e;
         EventPtr eptr(e);
         // push onto the priority queue
         __events.push( eptr );
         // return the handle.  The fact that it is a smart pointer
         // to an event is not part of the API, but is a useful
         //  implementation detail
         //
         return h;
 }
HandleCode Timeline::schedule (InChannel * ic, ltime_t t, unsigned int pri, Activation act) protected
Schedule the given arrival, at the given time, delivering the provided Activation record.
Return a handle for cancelation.
A timeline can directly schedule the arrival of a message at an InChannel owned by an Entity aligned to this Timeline at a given time. An "Activation" is given as an argument to any Process whose execution results. An Activation is a std::tr1::shared_ptr protecting a pointer to a message derived from base class Message. Its use alleviates issues of copying and deleting messages. The unsigned int is a priority used in tie-breaking activations scheduled at the same time. It return a "HandleCode" that can be used to cancel the action scheduled.
Parameters
ic the InChannel where the Activation will be delivered
t is the time of the delivery
pri is a priority used as a tie-breaker when events have the same base time
act is a smart pointer wrapper around an instance of a class derived from class Message, the payload.
If the InChannel is owned by an Entity not aligned with this timeline, and the target time is at least as large as the horizon, put the Event in a list for the target timeline. Otherwise place in a vector of Events associated with the OutAppointment
Definition at line 156 of file timeline.cc.
References __events, __events_mutex, __evtnum, __out_appt, __time, __ve_sink_events, __window_list, InChannel::alignment(), Entity::alignment(), EVTYPE_ACTIVATE, horizon(), InChannel::is_ve_attached(), InChannel::owner(), STL_EventList::push(), and s3fid().
{
         // if the activation is crossing timelines, do a reset to avoid
         // thread unsafety problems
         Timeline* tgt = ic->owner()->alignment();
         Event* e =new Event(EVTYPE_ACTIVATE,t, 0, ic, act, NULL, tgt, __evtnum++);
         // return a smart pointer to the event to be scheduled. That's the
         // handle for a cancelation.
         HandleCode h = (void *)e;
         EventPtr eptr(e);
         // see if the target InChannel is on this timeline or not
         if( tgt != this && horizon() <= t) {
                 // going to a different timeline in a future window,
                 // so save it to be exchanged
                 //  after the window synchronization has taken place
                 // Access to this list must be serialized
                 pthread_mutex_lock( &(tgt->__events_mutex));
                 // Put the event in the buffer
                 tgt->__window_list.push_back( eptr );
                 // release the mutex
                 pthread_mutex_unlock( &(tgt->__events_mutex) );
                 // we're done
                 return h;
         }
         if( tgt != this && t < horizon()) {
                 // exchange this at the appointment structure. Get the target timeline
                 // index
                 { int tgt_tl = ic->alignment()->s3fid();
                 pthread_mutex_lock( &__out_appt[tgt_tl].appt_mutex );
 #ifdef DEBUG
                 printf("at %ld timeline %d pushes event (time %ld) on __out_appt[%d]\n",
                                 __time, s3fid(), t, tgt_tl);
 #endif
                 __out_appt[tgt_tl].events.push_back( eptr );
                 pthread_mutex_unlock( &__out_appt[tgt_tl].appt_mutex );
                 return h;
                 }
         }
         // the InChannel is owned by an entity aligned to this
         // timeline, so the event just goes onto the event list
         //
         if(ic->is_ve_attached() == true)
         {
                 __ve_sink_events.push( eptr );
         }
         else
         {
                 __events.push ( eptr );
         }
         // we're done
         return h;
 }
void Timeline::schedule (InChannel * ic, Process * proc, bool bind, unsigned int pri) protected
In order to avoid an infinite loop where an process that was activated by an arrival on an inchannel calls waitOn for that inchannel AGAIN and just gets picked again to execute, we schedule attachments to the inchannel's waiting list to occur after all the user events at the current execution time have taken place.
This version of schedule implements that.
Definition at line 223 of file timeline.cc.
References __events, __evtnum, now(), and STL_EventList::push().
{
         Event* e;
         // create an event to happen immediately to implement the attachment
         e=new Event(now(), pri, ic,proc,bind,pri,this, __evtnum++);
         EventPtr eptr(e);
         __events.push (eptr);
 }
Process* Timeline::get_running_proc () inline protected
Timeline variable __this points to the Process currently executing (NULL if the Timeline state is not RUNNING).
This method returns that pointer.
Definition at line 226 of file timeline.h.
References __this.
Referenced by InChannel::bind(), InChannel::is_bound(), InChannel::is_waiting(), InChannel::unbind(), and InChannel::unwaitOn().
 { return __this; }
ltime_t Timeline::next_time () protected
Return the timestamp of the event with least timestamp of the two event-lists.
Return -1 if the __events and __ve_sink_events event-lists are empty.
Definition at line 242 of file timeline.cc.
References __events, __ve_sink_events, STL_EventList::empty(), and STL_EventList::top().
Referenced by sim_global_scheduler_one_epoch().
{
   // return -1 if there are no events
   if( __events.empty() && __ve_sink_events.empty() ) return -1;
   if( __events.empty() ) return (__ve_sink_events.top())->get_time();
   if( __ve_sink_events.empty() ) return (__events.top())->get_time();
   return min( (__ve_sink_events.top())->get_time(), (__events.top())->get_time() );
 }
void Timeline::cross_timeline_delay (ltime_t d) protected
As mapto calls are made, each one that crosses timeline boundaries has its minimum delay value reported to the timeline, using this method.
During initialization, mapto calls that cross timeline boundaries will call this method so that at the end of all the init() calls we know what __min_sync_cross_timeline_delay is. Recall that __min_sync_cross_timeline_delay is initialized to -1.
Definition at line 1392 of file timeline.cc.
Referenced by OutChannel::mapto().
{
         // change __min_sync_cross_timeline_delay if either this is
         // the first call to the method, or the offered delay
         // is smaller than the smallest seen so far
         //
         if( (__min_sync_cross_timeline_delay == -1) ||
                         (delay < __min_sync_cross_timeline_delay) ) {
                 __min_sync_cross_timeline_delay = delay;
         }
 }
void Timeline::all_timeline_delay (ltime_t delay) protected
Definition at line 1405 of file timeline.cc.
References __min_sync_all_timeline_delay.
Referenced by OutChannel::mapto().
{
         if( (__min_sync_all_timeline_delay == -1) ||
                         (delay < __min_sync_all_timeline_delay) ) {
                 __min_sync_all_timeline_delay = delay;
         }
 }
void Timeline::same_timeline_delay (ltime_t delay) protected
Definition at line 1412 of file timeline.cc.
References __min_sync_same_timeline_delay.
Referenced by OutChannel::mapto().
{
         if( (__min_sync_same_timeline_delay == -1) ||
                         (delay < __min_sync_same_timeline_delay) ) {
                 __min_sync_same_timeline_delay = delay;
         }
 }
ltime_t Timeline::min_sync_cross_timeline_delay (ltime_t thrs) protected
This computation finds among all OutChannels owned by Entities aligned to this Timeline, the smallest minimum delay no smaller than thrs among mappings to InChannels on other timelines.
The result of this computation is put into Timeline variable __min_sync_cross_timeline_delay.
The thresholding is used to support the eventual inclusion of "Composite Synchronization" described in
Nicol, David M., and Jason Liu. "Composite synchronization in parallel discrete-event simulation." Parallel and Distributed Systems, IEEE Transactions on 13.5 (2002): 433-446.
Using thrs <=0 ensures that the overall minimum is found.
Definition at line 1429 of file timeline.cc.
References __entity_list.
Referenced by Interface::InitModel(), and sync_window().
{
         // initialize answer variable to "nothing here"
         ltime_t ans = -1;
         // buffer entity delay once computed
         ltime_t ent_delay = 0;
         // number of entities to visit
         unsigned int end = __entity_list.size();
         // For each entity call its own min_sync_cross_timeline_delay method,
         // passing the same threshold.  Save it, and adjust ans if
         //   -- ans is initialized to -1, or
         //   -- the entity's minimum delay is at least as large as thrs, AND
         //       is smaller than the working minimum
         //
         for(unsigned int i=0; i<end; i++) {
                 ent_delay = __entity_list[i]->min_sync_cross_timeline_delay(thrs);
                 if(ent_delay != -1) // -1 means everything is on the same timeline
                 {
                         if( thrs<= ent_delay && ((ans<0) || (ent_delay<ans))) ans = ent_delay;
                 }
         }
         return ans;
 }
ltime_t Timeline::min_sync_all_timeline_delay (ltime_t thrs) protected
Definition at line 1456 of file timeline.cc.
References __entity_list.
Referenced by Interface::InitModel().
{
         // initialize answer variable to "nothing here"
         ltime_t ans = -1;
         // buffer entity delay once computed
         ltime_t ent_delay = 0;
         // number of entities to visit
         unsigned int end = __entity_list.size();
         // For each entity call its own min_sync_cross_timeline_delay method,
         // passing the same threshold.  Save it, and adjust ans if
         //   -- ans is initialized to -1, or
         //   -- the entity's minimum delay is at least as large as thrs, AND
         //       is smaller than the working minimum
         //
         for(unsigned int i=0; i<end; i++) {
                 ent_delay = __entity_list[i]->min_sync_all_timeline_delay(thrs);
                 if(ent_delay != -1) // -1 means everything is on the same timeline
                 {
                         if( thrs<= ent_delay && ((ans<0) || (ent_delay<ans))) ans = ent_delay;
                 }
         }
         return ans;
 }
unsigned int Timeline::count_min_delay_crossings (ltime_t thrs) protected
Count the number of connections whose minimum delay values are no smaller than the argument.
Result is stored in variable __channels_at_minimum.
Definition at line 1492 of file timeline.cc.
References __entity_list.
Referenced by Interface::InitModel(), and sync_window().
{
         // initialize running total
         unsigned int ans = 0;
         // number of entities to visit
         unsigned int end = __entity_list.size();
         // each entity will count the number of such channels it has
         // and return the values
         //
         for(unsigned int i=0; i<end; i++) {
                 ans += __entity_list[i]->count_min_delay_crossings(thrs);
         }
         // return summation
         return ans;
 }
ltime_t Timeline::get_min_sync_cross_timeline_delay () inline protected
Returns the value of __min_sync_cross_timeline_delay.
Definition at line 277 of file timeline.h.
References __min_sync_cross_timeline_delay.
Referenced by OutChannel::new_transfer_delay().
 { return __min_sync_cross_timeline_delay; }
ltime_t Timeline::get_min_sync_all_timeline_delay () inline protected
Returns the value of __min_sync_all_timeline_delay.
Definition at line 280 of file timeline.h.
References __min_sync_all_timeline_delay.
 { return __min_sync_all_timeline_delay; }
ltime_t Timeline::get_min_sync_same_timeline_delay () inline protected
Returns the value of __min_sync_same_timeline_delay.
Definition at line 283 of file timeline.h.
References __min_sync_same_timeline_delay.
 { return __min_sync_same_timeline_delay; }
void Timeline::initialize_appt (bool first, ltime_t thrs) protected
Definition at line 1511 of file timeline.cc.
References __appointment_cond_var, __entity_list, __events, __events_mutex, __evtnum, __in_appt, OutChannel::__mapped_to, __num_timelines, __out_appt, Entity::__outchannel_list, __window_size, EVTYPE_MAKE_APPT, EVTYPE_WAIT_APPT, min_sched_pri, OutChannel::min_write_delay(), STL_EventList::push(), s3fid(), and timeline_adrs.
Referenced by Interface::InitModel().
{
         __window_size = thrs;
         if(first) pthread_cond_init(&__appointment_cond_var, NULL);
         for(unsigned int i=0; i<__num_timelines; i++) {
                 if(first) pthread_mutex_init(&__in_appt[i].appt_mutex, NULL);
                 if(first) pthread_mutex_init(&__out_appt[i].appt_mutex, NULL);
                 __in_appt[i].waiting = false;
                 __in_appt[i].appointment = -1;   // flag for uninitialized
                 __out_appt[i].lookahead  = -1;   // flag for uninitialized
         }
         // work through all cross-timeline channels, to determine
         // the lookahead between this Timeline and others
         //
         for(unsigned int i=0; i< __entity_list.size(); i++) {
                 Entity* e = __entity_list[i];
                 for(unsigned int j=0; j<e->__outchannel_list.size(); j++) {
                         OutChannel *oc = e->__outchannel_list[j];
                         for(unsigned int k=0; k<oc->__mapped_to.size(); k++) {
                                 if( oc->__mapped_to[k].xtimeline() ) {
                                         // this channel crosses timelines.  Figure the
                                         // lookahead as the sum of the channel per-write minimum and the
                                         // transfer time
                                         ltime_t lookahead = oc->min_write_delay()
                                                         + oc->__mapped_to[k].transfer_delay();
                                         // if the lookeahd is less than thrs this is an asynchronous channel
                                         if( lookahead < thrs) oc->__mapped_to[k].set_asynchronous(true);
                                         else oc->__mapped_to[k].set_asynchronous(false);
                                         unsigned int tgt_tl = oc->__mapped_to[k].ic()->alignment()->s3fid();
                                         if( __out_appt[tgt_tl].lookahead < 0 ||
                                                         lookahead < __out_appt[tgt_tl].lookahead ) {
                                                 __out_appt[tgt_tl].lookahead = lookahead;
                                         }
                                 }
                         }
                 }
         }
         // for every Timeline whose lookahead is not -1 and is less than
         // the threshold,  schedule an event on the target
         // and one on the source, at the appointment time
         for(unsigned int i=0; i<__num_timelines; i++)   {
                 if( __out_appt[i].lookahead != -1 && __out_appt[i].lookahead < thrs ) {
                         // event for the source
                         pthread_mutex_lock(&__events_mutex);
{
                                 Event* e = new Event(__out_appt[i].lookahead, min_sched_pri-1,i,EVTYPE_MAKE_APPT, this, __evtnum++ );
                                 EventPtr eptr(e);
 #ifdef DEBUG
                                 printf("timeline %d creates appt-write to %d for %ld\n",
                                                 s3fid(), i, __out_appt[i].lookahead);
 #endif
                                 __events.push( eptr );
                         }
                         pthread_mutex_unlock(&__events_mutex);
                         // event for the destination
                         pthread_mutex_lock(&timeline_adrs[i]->__events_mutex);
{
                                 Event *e = new Event(__out_appt[i].lookahead, min_sched_pri,s3fid(),EVTYPE_WAIT_APPT, timeline_adrs[i], __evtnum++);
                                 EventPtr eptr(e);
 #ifdef DEBUG
                                 printf("timeline %d schedules appt-read from %d for %ld\n",
                                                 i, s3fid(), __out_appt[i].lookahead);
 #endif
                                 timeline_adrs[i]->__events.push( eptr );
                         }
                         pthread_mutex_unlock(&timeline_adrs[i]->__events_mutex);
                 }}
 }
unsigned long Timeline::get_nxt_handle () protected
Definition at line 1590 of file timeline.cc.
References __handle_idx.
{
         return __handle_idx++;
 }
void Timeline::get_cross_timeline_events () protected
Writes that cross timelines are buffered until the beginning of the next synchronization window; when buffered, a description of the write is placed in a list associated with the Timeline where the InChannel endpoint resides.
In the previous synchronization window, other Timelines may have done outchannel writes that through maptos should deliver activations to inchannels on this Timeline. These were buffered in the __window_list vector. Reading from __window_list should be isolated by barrier synchronizations from any writes into it, so unlike the writes (which had to have mutex protection), the reads need none.
Definition at line 1315 of file timeline.cc.
References __events, __ve_sink_events, __window_list, EVTYPE_ACTIVATE, EVTYPE_EXEC_ACTIVATE, InChannel::is_ve_attached(), and STL_EventList::push().
Referenced by sim_global_scheduler_one_epoch().
{
         // local copy of the list size, since it will not change
         // each pass through the loop, an optimization
         //
         int num_to_do = __window_list.size();
         // For each buffered event, all that is needed is a copy into __events
         //
         for(int i=0; i<num_to_do; i++) {
                 InChannel* ic = __window_list[i]->get_inc();
                 if(!ic) break;
                 if( ic->is_ve_attached() == true &&
                                 (__window_list[i]->get_evtype() == EVTYPE_EXEC_ACTIVATE ||
                                                 __window_list[i]->get_evtype() == EVTYPE_ACTIVATE) )
                 {
                         __ve_sink_events.push( __window_list[i] );
                 }
                 else
                 {
                         __events.push( __window_list[i] );
                 }
         }
         // if the list was not empty, it can be emptied now
         if( num_to_do > 0 ) __window_list.clear();
 }
void Timeline::change_state (TimelineState s) inline protected
Changes Timeline state variable __state to s.
Just before a Process body is executed the Timeline calls change_state(RUNNING); Immediately afterward it calls change_state(BLOCKED).
Definition at line 316 of file timeline.h.
References __state.
Referenced by sim_global_scheduler_one_epoch(), and sync_window().
 { __state = s; }
InChannel* Timeline::get_activeChannel () inline protected
Definition at line 318 of file timeline.h.
References __activeChannel.
Referenced by InChannel::insertion_gateway().
 { return __activeChannel; }
void Timeline::put_activeChannel (InChannel * inc) inline protected
Definition at line 319 of file timeline.h.
References __activeChannel.
Referenced by sync_window().
 { __activeChannel = inc; }
unsigned long Timeline::get_executed () inline protected
Definition at line 320 of file timeline.h.
References __executed.
Referenced by Interface::runtime_measurements().
 { return __executed;     }
unsigned long Timeline::get_work_executed () inline protected
Definition at line 321 of file timeline.h.
References __work_executed.
Referenced by Interface::runtime_measurements().
 { return __work_executed; }
unsigned long Timeline::get_sync_executed () inline protected
Definition at line 322 of file timeline.h.
References __sync_executed.
Referenced by Interface::runtime_measurements().
 { return __sync_executed; }
void Timeline::sync_window () protected
The heart of the thread_body is code that establishes a synchronization window, and then all Timelines execute asynchronously up to the time established as an upper bound.
This method holds the code that executes all events within a synchronization window.
Definition at line 786 of file timeline.cc.
References __appointment_cond_var, __channels_at_minimum, __channels_to_map, __delays_to_change, __events, __evtnum, __executed, __executed_one_window, Process::__func, __in_appt, OutChannel::__mapped_to, OutChannel::__min_write_delay, __out_appt, __recompute_min_delay, __s3fid, __sync_executed, __sync_executed_one_window, __this, __time, __ve_sink_events, InChannel::__waitingList, __window, __window_size, __work_executed, __work_executed_one_window, InAppointment_block::appointment, InAppointment_block::appt_mutex, OutAppointment_block::appt_mutex, CALL_MEMBER_FN, change_state(), count_min_delay_crossings(), OutAppointment_block::events, EVTYPE_ACTIVATE, EVTYPE_BIND, EVTYPE_CANCEL, EVTYPE_EXEC_ACTIVATE, EVTYPE_MAKE_APPT, EVTYPE_TIMEOUT, EVTYPE_WAIT_APPT, Event::get_act(), Event::get_bind(), Event::get_evtype(), Event::get_inc(), Event::get_pri(), Event::get_proc(), Event::get_time(), Event::get_tl(), InChannel::insert_process_pri(), InChannel::is_ve_attached(), min_sched_pri, min_sync_cross_timeline_delay(), OutChannel::min_write_delay(), OutChannel::min_xtransfer_delay(), Process::owner(), STL_EventList::pop(), STL_EventList::push(), Process::put_activeChannel(), put_activeChannel(), Event::release(), RUNNING, s3fid(), select_next_event(), t_prime, timeline_adrs, STL_EventList::top(), user_pri, InAppointment_block::waiting, and WAITING.
Referenced by sim_global_scheduler_one_epoch().
{
         // local variables, mostly to buffer individual elements
         // read more than one time from somewhat-complicated to access
         // data structures
         EventPtr   nxt_evt;
         int selected_evtlst; // 0 - none, 1 - events, 2 - __ve_sink_events
         ltime_t nxt_evt_time;
         Entity*  ent;
         OutChannel* oc;
         InChannel* ic;
         ltime_t delay;
         unsigned int tl;
         Timeline* dest_tl;
         InAppointment* in_appt;
         bool released;
         // flag set to true if at the end of the window we need to recompute
         // the minimum cross timeline delay
         //
         __recompute_min_delay = false;
         // knowing the window index helps with some double buffering schemes
         __window++;
         // select the next event
         select_next_event(selected_evtlst, nxt_evt_time);
         // event list loop.  Do all events with times strictly less than __stop_before
         //
         while ( selected_evtlst != 0 && nxt_evt_time < __stop_before && __interface_control->user_force_stop == false)
         {
                 if(selected_evtlst == 2)
                 {
                         nxt_evt = __ve_sink_events.top();
                         __ve_sink_events.pop();
                         if(t_prime == 0) t_prime = nxt_evt->get_time(); //set t_prime, the time of first executed deliver-to-VE event in current SSW
                 }
                 else //selected_evtlst == 1
                 {
                         nxt_evt = __events.top();
                         __events.pop();
                 }
                 // advance simulation time this far
                 __time  = nxt_evt->get_time();
                 // process the event, depending on event type
                 //
 #ifdef DEBUG
                 printf("At %ld on timeline %d event type %d executed, selected_evtlst = %d\n",
                                 __time, s3fid(), nxt_evt->get_evtype(), selected_evtlst);
 #endif
                 __executed++;
                 __executed_one_window++;
                 switch (nxt_evt->get_evtype()) {
                 // on a timeout we call the function whose pointer is carried
                 // with the event, passing along the activation that is also carried
                 // with the event
                 //
                 case EVTYPE_TIMEOUT :
                         __work_executed++;
                         __work_executed_one_window++;
                         // set __this for reference to process that is running
                         __this = nxt_evt->get_proc();
                         // make process' __active NULL to flag that it was triggered by
                         // a waitFor
                         //
                         __this->put_activeChannel( NULL );
                         // Macro to call the Process body associated with the Process pointed to
                         // by __this, passing to it the Activation carried along in the event
                         //
                         CALL_MEMBER_FN( *__this->owner(), __this->__func )(nxt_evt->get_act());
                         __this = NULL;
                         break;
                         // EVTYPE_ACTIVATE  identifies all activations of Processes attached to
                         // the named in-channel.  It schedules individual EVTYPE_EXEC_ACTIVATE
                         // events to do the work.  Since the EVTYPE_ACTIVATE is scheduled at the highest
                         // priority order, the priorities on these activations "fit" with the priorities
                         // of any other scheduled events at the same time.
                         //
                         //
                 case EVTYPE_ACTIVATE :
                         // The InChannel has an STL list of Processes that should be
                         // activated if an Activation appears on the InChannel.
                         // Iterate over that list, for each member call the associated
                         // Process
                         //
                         ic = nxt_evt->get_inc();
                         // for each process create an EXEC_ACTIVATION event and schedule it at
                         // the priority given in the process priority list
                         //
                         for(std::list<ProcessPri>::iterator
                                         list_iter = ic->__waitingList.begin();
                                         list_iter != ic->__waitingList.end(); list_iter++)
{
                                 Event* e;
                                 if( (*list_iter).get_pri() > 0 )
{
                                         e = new Event(EVTYPE_EXEC_ACTIVATE, __time, (*list_iter).get_pri(), ic,
                                                         nxt_evt->get_act(), (*list_iter).get_proc(),this, __evtnum++);
                                 }
                                 else
{
                                         e = new Event(EVTYPE_EXEC_ACTIVATE, __time, (*list_iter).get_proc()->pri(), ic,
                                                         nxt_evt->get_act(), (*list_iter).get_proc(),this, __evtnum++);
                                 }
                                 if( ic->is_ve_attached() == true )
{
                                         __ve_sink_events.push(e);
                                 }
                                 else
{
                                         __events.push(e);
                                 }
                                 // Depending on whether the Process was attached to the InChannel by bind()
                                 // which survives this call) or by waitOn (which does not), we may need
                                 // to remove the Process from the InChannel list.  The get_bound() method
                                 // returns true if the Process went on via a bind() call.  Remove before
                                 // the call in case of queries against the binding state during the call
                                 if( !(*list_iter).get_bound() )
{
                                         list_iter = nxt_evt->get_inc()->__waitingList.erase(list_iter);
                                 }
                         }
                         break;
                 case EVTYPE_EXEC_ACTIVATE:
                         __work_executed++;
                         __work_executed_one_window++;
                         __this = nxt_evt->get_proc();
                         // Need to know what Entity owns the Process
                         ent = __this->owner();
                         // running process needs to know what inchannel triggered it
                         //
                         __this->put_activeChannel( nxt_evt->get_inc() );
                         put_activeChannel( nxt_evt->get_inc() );
                         // Macro to call the Process body associated with the Process pointed to
                         // by __this, passing to it the Activation carried along in the event
                         //
                         assert(nxt_evt);
                         assert(nxt_evt->get_act());
                         CALL_MEMBER_FN( *ent, __this->__func)(nxt_evt->get_act());
                         put_activeChannel( NULL );
                         __this->put_activeChannel( NULL );
                         // not processing this body anymore
                         __this = NULL;
                         break;
                 case EVTYPE_MAKE_APPT:
                         __sync_executed++;
                         __sync_executed_one_window++;
                         // get the identity of the timeline needing this appointment
                         tl = nxt_evt->get_tl();
                         // turn that into a pointer to the timeline
                         dest_tl = timeline_adrs[tl];
                         // recover pointer to the InAppointment structure on the destination,
                         // using own timeline identity index into destination's incoming appt array
                         in_appt = &dest_tl->__in_appt[__s3fid];
                         // gain access to the data in the appointment structure
                         pthread_mutex_lock( &in_appt->appt_mutex );
                         // write the new appointment into it
                         in_appt->appointment = __time + __out_appt[tl].lookahead;
                         // if the target timeline is waiting it needs a signal to its
                         // condition variable
                         if( in_appt->waiting ) {
 #ifdef DEBUG
                                 printf("at %ld timeline %d signals timeline %d\n",
                                                 __time, s3fid(), tl);
 #endif
                                 pthread_cond_signal(&dest_tl->__appointment_cond_var);
                                 // &in_appt->appt_mutex);
                         }
                         // release the appointment data
                         pthread_mutex_unlock( &in_appt->appt_mutex );
                         // schedule the next appointment write at a scheduling priority
                         // higher than the appointment wait
{
                                 Event *e =new Event(in_appt->appointment, min_sched_pri-1, tl,EVTYPE_MAKE_APPT,this, __evtnum++);
                                 EventPtr eptr(e);
 #ifdef DEBUG
                                 printf("at %ld timeline %d schedules next update to timeline %d for %ld\n",
                                                 __time, s3fid(), tl, __time + __out_appt[tl].lookahead);
 #endif
                                 // __events.push( pqn );
                                 __events.push( eptr );
                         }
                         break;
                 case EVTYPE_WAIT_APPT:
                         __sync_executed++;
                         __sync_executed_one_window++;
                         // get the identity of the timeline we're waiting for
                         tl = nxt_evt->get_tl();
 #ifdef DEBUG
                         printf("at %ld timeline %d checks appointment from %d, sees %ld\n",
                                         __time, s3fid(), tl, __in_appt[tl].appointment);
 #endif
                         // continue if the appointment time is larger than the clock
                         released = false;
                         if( __time < __in_appt[tl].appointment) released = true;
                         // acquire the appointment lock and have another look
                         if(! released ) {
                                 pthread_mutex_lock( &__in_appt[tl].appt_mutex );
                                 if( __time < __in_appt[tl].appointment) {
                                         // got lucky
                                         pthread_mutex_unlock( &__in_appt[tl].appt_mutex );
                                 }
                                 else {
                                         // flag waiting state, mark state of timeline as waiting,
                                         // and wait for a signal from the timeline it waits for
                                         __in_appt[tl].waiting = true;
                                         change_state(WAITING);
 #ifdef DEBUG
                                         printf("at %ld timeline %d to wait on timeline %d\n",
                                                         __time, s3fid(), tl);
 #endif
                                         pthread_cond_wait(&__appointment_cond_var, &__in_appt[tl].appt_mutex);
                                         // the appointment time has been updated. Adjust state
                                         // and schedule another EVTYPE_WAIT_APPT at the given time
                                         //
                                         change_state(RUNNING);
                                         __in_appt[tl].waiting = false;
 #ifdef DEBUG
                                         printf("at %ld timeline %d released by timeline %d\n",
                                                         __time, s3fid(), tl);
 #endif
                                         // free up mutex
                                         pthread_mutex_unlock( &__in_appt[tl].appt_mutex );
                                 }
                         }
                         // schedule the next incoming appointment wait time
{
                                 Event* e =new Event(__in_appt[tl].appointment, min_sched_pri, tl,EVTYPE_WAIT_APPT,this, __evtnum++);
                                 EventPtr eptr(e);
 #ifdef DEBUG
                                 printf("at %ld timeline %d schedules wait check from timeline %d at time %ld\n",
                                                 __time, s3fid(), tl, __in_appt[tl].appointment);
 #endif
                                 __events.push( eptr );
                         }
                         // move any events left here by the appointment source into own event list
{
                                 OutAppointment *out_appt = &(timeline_adrs[tl]->__out_appt[s3fid()]);
                                 pthread_mutex_lock( &out_appt->appt_mutex);
                                 for(int i = out_appt->events.size()-1; i>= 0; i--) {
                                         InChannel* ic = out_appt->events[i]->get_inc();
                                         assert(ic);
                                         if( ic->is_ve_attached() == true &&
                                                         (out_appt->events[i]->get_evtype() == EVTYPE_EXEC_ACTIVATE ||
                                                                         out_appt->events[i]->get_evtype() == EVTYPE_ACTIVATE) )
{
                                                 __ve_sink_events.push( out_appt->events[i] );
                                         }
                                         else
{
                                                 __events.push( out_appt->events[i] );
                                         }
                                 }
                                 out_appt->events.clear();
                                 pthread_mutex_unlock( &out_appt->appt_mutex);
                         }
                         break;
                 case EVTYPE_BIND:
                         __work_executed++;
                         __work_executed_one_window++;
                         // safe now to implement delayed binding
                         nxt_evt->get_inc()->insert_process_pri( nxt_evt->get_proc(),
                                         nxt_evt->get_bind(), user_pri(nxt_evt->get_pri()) );
                         break;
                         // simply ignore cancelled events
                 case EVTYPE_CANCEL :
                         __executed--;
                         __executed_one_window--;
                         break;
                 }
                 nxt_evt->release();
                 //prepare for processing the next event
                 select_next_event(selected_evtlst, nxt_evt_time);
         }
         // All events in this window now processed. Check for any needed
         // dynamic updating of mappings or minimum delays
         // that were called for during the last burst
         //
         // any maptos needing doing?
         //
         if( __channels_to_map.size() > 0 ) {
                 // yes. map the channels
                 //
                 for(unsigned int i=0; i<__channels_to_map.size(); i++) {
                         // which outchannel is doing the mapto?
                         //
                         oc = __channels_to_map[i]->oc();
                         // the __channels_to_map structure has the complete mapping
                         // information, and so all that needs to be done is to put
                         // it in the outchannel's list of mapped channels.
                         //
                         oc->__mapped_to.push_back( *__channels_to_map[i] );
                         // if minimum cross timeline delay for this is equal
                         // to the timeline's minimum, increment the count of
                         // such.  If it is less than the existing minimum,
                         // throw a flag that indicates a new minimum must be
                         // computed.
                         //
                         delay = oc->min_write_delay() +
                                         __channels_to_map[i]->transfer_delay();
                         if( delay == __min_sync_cross_timeline_delay )
                                 __channels_at_minimum++;
                         else {
                                 if( delay < __min_sync_cross_timeline_delay )
                                         __recompute_min_delay = true;
                         }
                 }
                 // empty the list, call the element's destructors
                 __channels_to_map.clear();
         }
         // check whether there are cross timeline minimum delays that
         // with updates buffered
         //
         if( __delays_to_change.size() > 0 ) {
                 // temporary variable used to compute the complete crossing time
                 ltime_t crossing;
                 // change the minimum delay of each channel in this list,
                 // and determine whether that triggers a recalculation of the
                 // minimum cross timeline channel delay
                 //
                 for(unsigned int i=0; i<__delays_to_change.size(); i++) {
                         oc = __delays_to_change[i]->oc();
                         ic = __delays_to_change[i]->ic();
                         // Different logic for changing an OutChannel's minimum write delay
                         if( __delays_to_change[i]->select() ) {
                                 ltime_t xtransfer = oc->min_xtransfer_delay();
                                 ltime_t mwd = __delays_to_change[i]->min_write_delay();
                                 // if xtransfer is not -1 there is a cross timeline mapping, which means
                                 // we have to check that there's a known positive lower bound on the
                                 // transfer time.  If not, at this point we can only ignore the change
                                 // request...
                                 //
                                 crossing = mwd+xtransfer;
                                 if( xtransfer >= -1 && crossing == 0 ) continue;
                                 // implement the change
                                 oc->__min_write_delay = mwd;
                                 // flag if the change impacts the minimum cross timeline delay
                                 if( crossing == __min_sync_cross_timeline_delay ) __channels_at_minimum++;
                                 if( crossing < __min_sync_cross_timeline_delay)  __recompute_min_delay = true;
                         }
                         // if we get here the delay is a tranfer delay, so find the corresponding InChannel
                         delay = __delays_to_change[i]->transfer_delay();
                         // search the OutChannel's table of mappings for this one
                         unsigned int end = oc->__mapped_to.size();
                         for(unsigned int i=0; i<end; i++) {
                                 if( oc->__mapped_to[i].ic() == ic ) {
                                         // found the named InChannel, so change the transfer delay
                                         (oc->__mapped_to[i]).set_transfer_delay(delay);
                                         // if this just lowers the delay to the existing minimum
                                         // we just have one more such connection
                                         //
                                         ltime_t crossing = oc->min_write_delay() +
                                                         oc->__mapped_to[i].transfer_delay();
                                         if( crossing == __min_sync_cross_timeline_delay )
                                                 __channels_at_minimum++;
                                         else if ( crossing < __min_sync_cross_timeline_delay)
                                                 // It got smaller than the Timeline's smallest, so
                                                 // we'll have to redo the minimum cross timeline delay
                                                 // calculation
                                                 //
                                                 __recompute_min_delay = true;
                                         break;
                                 }
                         }
                 }
                 __delays_to_change.clear();
         }
         // haven't done anything with appointments yet
         // if in the course of doing an unmap during processing or
         // a mapto or min delay change above we changed the minimum
         // cross timeline delay, recompute it and then recompute
         // the number of times a cross-timeline channel with that minimum
         // delay appears
         //
         if(__recompute_min_delay ) {
                 // method min_sync_cross_timeline_delay goes through all entities
                 __min_sync_cross_timeline_delay = min_sync_cross_timeline_delay(__window_size);
                 // count the number of connections whose minimum delays are
                 // exactly the Timeline's overall minimum
                 //
                 __channels_at_minimum = count_min_delay_crossings( __min_sync_cross_timeline_delay );
         }
         // we're done with this synchronization window.  Time advances to the very end of it.
         __time = __stop_before-1;
 #ifdef SYNC_WIN_EVENT_COUNT
         printf("now = %ld, timeline = %d, window# = %d, total events = %ld, work events = %ld, sync events = %ld\n",
                         __time, s3fid(), __window, __executed_one_window, __work_executed_one_window, __sync_executed_one_window);
 #endif
         __executed_one_window = __work_executed_one_window = __sync_executed_one_window = 0;
 }
bool Timeline::global_continue () protected
Called after a window synchronization to see if the conditions for continuing execution are meet.
Checks to see if the timeline interface specification for advancing is to call an interface function or not to determine whether to advance. The decision to check or not is cached in private bool variable __no_global_check (set to true if the configuration is NOT to call such a function. Otherwise, TimelineInterface function stop_condition() is called.
Definition at line 1594 of file timeline.cc.
References __interface_control, __no_global_check, and TimelineInterface::stop_condition().
Referenced by sim_global_scheduler_one_epoch().
{
         if( __no_global_check ) return true;
         return !__interface_control->stop_condition();
 }
void Timeline::select_next_event (int & evt_list, ltime_t & evt_time) protected
Select which event_list of the two (__events and __ve_sink_events) has the next event.
Return the evt_list indicator (0 - none, 1 - events, 2 - __ve_sink_events) and the next_evt_time (-1 if none)
Definition at line 1239 of file timeline.cc.
References __events, Event::__key2, Event::__time, __time, __ve_sink_events, STL_EventList::empty(), and STL_EventList::top().
Referenced by sync_window().
 {
         if( __events.empty() && __ve_sink_events.empty() )
         {
                 evt_list = 0;
                 evt_time = -1;
                 return;
         }
         if( __events.empty() )
         {
                 evt_list = 2;
                 evt_time = (__ve_sink_events.top())->get_time();
                 return;
         }
         if( __ve_sink_events.empty() )
         {
                 evt_list = 1;
                 evt_time = (__events.top())->get_time();
                 return;
         }
         EventPtr lhs =  __events.top();
         EventPtr rhs =  __ve_sink_events.top();
         int who = 1; //1 for __events and 2 for __ve_sink_events
         if( lhs->__time > rhs->__time ) who = 2;
         else if( lhs->__time < rhs->__time ) who = 1;
         else if( lhs->__key2 > rhs->__key2)  who = 2;
         else who = 1;
         if(who == 1)
         {
                 evt_list = 1;
                 evt_time = (__events.top())->get_time();
                 //test only
                 if(evt_time < __time)
                 {
                         printf("Strange\n");
                         getchar();
                 }
                 return;
         }
         if(who == 2)
         {
                 evt_list = 2;
                 evt_time = (__ve_sink_events.top())->get_time();
                 //test only
                 if(evt_time < __time)
                 {
                         printf("Strange\n");
                         getchar();
                 }
                 return;
         }
 }
void Timeline::sim_global_scheduler_one_epoch () protected
Definition at line 634 of file timeline.cc.
References __interface_control, __time, __window_size, BLOCKED, change_state(), get_cross_timeline_events(), TimelineInterface::get_numTimelines(), TimelineInterface::get_stop_before(), global_continue(), MAX, next_time(), RUNNING, s3fid(), and sync_window().
Referenced by thread_function().
 {
         ltime_t epoch_end = __interface_control->get_stop_before();
         ltime_t nxt_time;
         int bottom_barrier_status = 0;
         do
         {
                 get_cross_timeline_events();
                 // compute upper edge of synchronization window---equal to
                 // min_{all timelines}{ time_of_first_event + minimum_cross_timeline_delay }
                 change_state(BLOCKED);
                 nxt_time = next_time();
 #ifdef FAST_MULTITIMELINE_NO_X_EVENTS
                 //todo revisit this part if cross-timeline delay is dynamic, e.g. support dynamic routing
                 if( __interface_control->get_numTimelines() > 1 && __min_sync_cross_timeline_delay > 0 )
 #else
                 if( __interface_control->get_numTimelines() > 1 )
 #endif
                 {
                         // if either there is no event on the event list, or no outbound connections
                         // that span Timelines, offer __window_size to the barrier
                         if( nxt_time < 0 || __min_sync_cross_timeline_delay < 0  )
{
                                 ltime_t this_window = MAX(__time, nxt_time) + __window_size;
                                 if(this_window > __time)
{
 #ifdef MUTEX_BARRIER
                                         bottom_barrier_status = __interface_control->bottom_barrier.wait( this_window );
 #endif
 #ifdef SCHED_YIELD_BARRIER
                                         bottom_barrier_status = __interface_control->bottom_barrier.wait( s3fid(), this_window );
 #endif
 #ifdef PTHREAD_BARRIER
                                         pthread_mutex_lock(&bottom_barrier_min_value_mutex);
                                         if(bottom_barrier_min_value == prev_bottom_barrier_min_value || bottom_barrier_min_value > this_window) bottom_barrier_min_value = this_window;
                                         pthread_mutex_unlock(&bottom_barrier_min_value_mutex);
                                         bottom_barrier_status = pthread_barrier_wait( &(__interface_control->bottom_barrier) );
                                         if(bottom_barrier_status == -1) prev_bottom_barrier_min_value = bottom_barrier_min_value;
 #endif
                                 }
                                 else //mean nothing to execute, next_time should be infinitely large
{
 #ifdef MUTEX_BARRIER
                                         bottom_barrier_status = __interface_control->bottom_barrier.wait(-1);
 #endif
 #ifdef SCHED_YIELD_BARRIER
                                         bottom_barrier_status = __interface_control->bottom_barrier.wait(s3fid(), -1);
 #endif
 #ifdef PTHREAD_BARRIER
                                         bottom_barrier_status = pthread_barrier_wait( &(__interface_control->bottom_barrier) );
 #endif
                                 }
                         }
                         else
{
                                 // either nxt_time or __min_sync_cross_timeline_delay may be -1,
                                 // so ensure in both cases that the event time offered is at
                                 // least __time, and that the minimum cross timeline delay is at
                                 // least 0.  Compute the sum and offer to the min-reduction.
 #ifdef MUTEX_BARRIER
                                 bottom_barrier_status = __interface_control->bottom_barrier.wait( MAX(__time,nxt_time) + MAX(0,__min_sync_cross_timeline_delay));
 #endif
 #ifdef SCHED_YIELD_BARRIER
                                 bottom_barrier_status = __interface_control->bottom_barrier.wait( s3fid(), MAX(__time,nxt_time) + MAX(0,__min_sync_cross_timeline_delay));
 #endif
 #ifdef PTHREAD_BARRIER
                                 ltime_t offered_min_value = MAX(__time,nxt_time) + MAX(0,__min_sync_cross_timeline_delay);
                                 pthread_mutex_lock(&bottom_barrier_min_value_mutex);
                                 if(bottom_barrier_min_value == prev_bottom_barrier_min_value || bottom_barrier_min_value > offered_min_value) bottom_barrier_min_value = offered_min_value;
                                 pthread_mutex_unlock(&bottom_barrier_min_value_mutex);
                                 bottom_barrier_status = pthread_barrier_wait( &(__interface_control->bottom_barrier) );
                                 if(bottom_barrier_status == -1) prev_bottom_barrier_min_value = bottom_barrier_min_value;
 #endif
                         }
                         // get the upper window edge computed by the min-reduction.
                         // __stop_before holds that value.
 #ifdef PTHREAD_BARRIER
                         __stop_before = bottom_barrier_min_value;
 #else
                         __stop_before = __interface_control->bottom_barrier.get_min_value();
 #endif
                         // we cannot go farther than the upper edge of the epoch window though.
                         if(__stop_before <= 0) //nothing in the eventlist, jump directly to the epoch_end;
{
                                 __stop_before = epoch_end;
                         }
                         else
{
                                 __stop_before = min(__stop_before, epoch_end);
                         }
                 }
                 else
                 {
                         __stop_before = epoch_end;
                 }
                 // do the simulation work for the window.
                 change_state(RUNNING);
 #ifdef DEBUG
                 printf("timeline %d enters window [%ld,%ld), size = %ld\n",
                                 s3fid(), __time, __stop_before, __stop_before - __time);
 #endif
                 sync_window();
                 change_state(BLOCKED);
                 // synchronize at a "end of cycle" barrier, but the one
                 // to join depends on whether we've finished an epoch.
                 // Can tell if __stop_before < stop_before (means not done)
                 //   While this is a min-reduction, we aren't using that capability
                 // here, so just offer -1 (nothing)
                 if( __stop_before < epoch_end && __interface_control->user_force_stop == false)
                 {
 #ifdef MUTEX_BARRIER
                         __interface_control->top_barrier.wait(-1);
 #endif
 #ifdef SCHED_YIELD_BARRIER
                         __interface_control->top_barrier.wait( s3fid(),  global_continue() );
 #endif
 #ifdef PTHREAD_BARRIER
                         // PTHREAD_BARRIER_SERIAL_THREAD is -1
                         pthread_barrier_wait( &(__interface_control->top_barrier) );
 #endif
                 }
                 else
                 {
 #ifdef MUTEX_BARRIER
                         __interface_control->window_barrier.wait(__stop_before);
 #endif
 #ifdef SCHED_YIELD_BARRIER
                         __interface_control->window_barrier.wait(s3fid(), __stop_before);
 #endif
 #ifdef PTHREAD_BARRIER
                         pthread_barrier_wait( &(__interface_control->window_barrier) );
 #endif
                 }
                 // do another synchronization window if the last one was not the epoch end
                 //
         } while( __stop_before < epoch_end && __interface_control->user_force_stop == false);
 }
void Timeline::sim_emu_global_scheduler_one_epoch () protected
Referenced by thread_function().
ltime_t Timeline::ve_proxy_entity_potential_impact_time () protected
Definition at line 359 of file timeline.cc.
References __events, __interface_control, __min_sync_all_timeline_delay, __ve_sink_events, STL_EventList::empty(), SimCtrl::get_clock(), Event::get_time(), TimelineInterface::sc, STOPBYDEMAND_MAX_ESW_SCALAR, and STL_EventList::top().
 {
         ltime_t nxt_time_ve;
         ltime_t nxt_time;
         ltime_t emu_now = __interface_control->sc->get_clock();
         ltime_t return_time;
         if( __events.empty() && __ve_sink_events.empty() )
         {
 #ifdef OPENVZ_EMULATION_LOOKAHEAD
                 //return emu_now + __min_sync_all_timeline_delay;
 #else
                 return emu_now + STOPBYDEMAND_MAX_ESW_SCALAR * VTIME_VTIMESLICE;
 #endif
         }
         if( __ve_sink_events.empty() ) nxt_time_ve = INT_MAX;
         else nxt_time_ve = __ve_sink_events.top()->get_time();
         if( __events.empty() ) nxt_time = INT_MAX;
         else nxt_time = __events.top()->get_time();
 #ifdef OPENVZ_EMULATION_LOOKAHEAD
         return_time = min(min(nxt_time, emu_now + ve_lookahead) + __min_sync_all_timeline_delay, nxt_time_ve);
         clear_lookahead();
 #else
         return_time = min(emu_now + __min_sync_all_timeline_delay, nxt_time_ve);
 #endif
         return return_time;
 }
void Timeline::manual_binding_thread_to_core () protected
Friends And Related Function Documentation
void* proxy_function (void * timeline_ptr) friend
Definition at line 37 of file interface.cc.
{
         return static_cast<Timeline *>(timeline_ptr)->thread_function();
 }
Member Data Documentation
TimelineState Timeline::__state private
The current state of the Timeline, (one of INITIALIZING, RUNNING, BLOCKED).
Definition at line 363 of file timeline.h.
Referenced by change_state(), get_state(), and Timeline().
unsigned int Timeline::__s3fid private
This Timeline's own id.
Definition at line 364 of file timeline.h.
Referenced by s3fid(), sync_window(), and Timeline().
Process* Timeline::__this private
Just before a Process body is executed, __this is set to point to the instance of the Process.
This is used as a default Process for calls to waitFor that do not directly specify the Process body to execute at the expiration of the waitFor timer.
Definition at line 371 of file timeline.h.
Referenced by get_running_proc(), sync_window(), and Timeline().
TimelineInterface* Timeline::__interface_control private
When the Timeline is created an run, an s3f::Interface object has filled out information describing how it wishes the simulation to advance during the next epoch of time.
__interface_control holds a pointer to that (shared) structure.
Definition at line 379 of file timeline.h.
Referenced by get_timeline_interface(), global_continue(), sim_global_scheduler_one_epoch(), thread_function(), and ve_proxy_entity_potential_impact_time().
vector<Entity*> Timeline::__entity_list private
This list holds a pointer for every Entity aligned to this Timeline.
Definition at line 382 of file timeline.h.
Referenced by Entity::BuildEntity(), count_min_delay_crossings(), initialize_appt(), Interface::InitModel(), min_sync_all_timeline_delay(), and min_sync_cross_timeline_delay().
ltime_t Timeline::__min_sync_cross_timeline_delay private
Minimum transfer delay among all cross-timeline channels in this timeline.
Definition at line 385 of file timeline.h.
Referenced by get_min_sync_cross_timeline_delay(), Interface::InitModel(), and Timeline().
ltime_t Timeline::__min_sync_all_timeline_delay private
Minimum transfer delay among all channels in this timeline (non-cross-timeline and cross-timeline).
Definition at line 388 of file timeline.h.
Referenced by all_timeline_delay(), get_min_sync_all_timeline_delay(), Timeline(), and ve_proxy_entity_potential_impact_time().
ltime_t Timeline::__min_sync_same_timeline_delay private
Minimum transfer delay among all non-cross-timeline channels in this timeline.
Definition at line 391 of file timeline.h.
Referenced by get_min_sync_same_timeline_delay(), same_timeline_delay(), and Timeline().
ltime_t Timeline::__window_size private
Definition at line 393 of file timeline.h.
Referenced by initialize_appt(), Interface::InitModel(), sim_global_scheduler_one_epoch(), and sync_window().
unsigned int Timeline::__channels_at_minimum private
After __min_sync_cross_timeline_delay is computed, we count the number of connections whose minimum delay values are exactly this.
Such a count helps to minimize calls to the expensive routine that recalculates __min_sync_cross_timeline_delay after some mapping change. If a connection that has this minimum is removed or the minimum delay increases, so long as __channels_at_minimum is still non-zero there is no need to recompute.
Definition at line 403 of file timeline.h.
Referenced by Interface::InitModel(), OutChannel::new_transfer_delay(), sync_window(), and Timeline().
bool Timeline::__recompute_min_delay private
Set to false at the beginning of a synchronization window, __recompute_min_delay is set to true if a dynamically called mapto or an unmap call remove the last known connection with minimum delay value __min_sync_cross_timeline_delay.
The flag is checked at the end of the window and a re-computation triggered if needed.
Definition at line 411 of file timeline.h.
Referenced by OutChannel::new_transfer_delay(), sync_window(), and OutChannel::unmap().
int Timeline::__log_ticks_per_sec private
Scale factor for virtual time clock, gives the logarithm base 10 of the number of clock ticks (increment of 1 on the clock variable) in each virtual time second.
Used when converting double precision floating point variables from or to native clock ticks.
Definition at line 418 of file timeline.h.
Referenced by get_log_ticks_per_sec(), and Timeline().
ltime_t Timeline::__time private
The virtual time up to which the timeline has advanced.
__time is set to the time of a Process body activation when that is made, and then skips up to the end of the synchronization window after all events within the window have been executed.
Definition at line 425 of file timeline.h.
Referenced by now(), schedule(), select_next_event(), sim_global_scheduler_one_epoch(), sync_window(), thread_function(), and Timeline().
ltime_t Timeline::__stop_before private
This holds the result of a window calculation by all simulation threads, establishing an upper bound on how far they may simulate this window.
Any activation with a timestamp strictly less than __stop_before may be executed.
Definition at line 432 of file timeline.h.
Referenced by horizon().
unsigned int Timeline::__window private
This integer keeps track of the number of synchronization windows that have been completed.
Definition at line 435 of file timeline.h.
Referenced by sync_window().
InChannel* Timeline::__activeChannel private
Definition at line 437 of file timeline.h.
Referenced by get_activeChannel(), put_activeChannel(), and Timeline().
vector<EventPtr> Timeline::__window_list private
Vector holding description of cross timeline writes.
These have been formatted already into the same data structure as is used for the priority list.
Definition at line 444 of file timeline.h.
Referenced by get_cross_timeline_events(), and schedule().
pthread_mutex_t Timeline::__events_mutex private
Access to __window_list is guarded by mutex __events_mutex.
Definition at line 447 of file timeline.h.
Referenced by initialize_appt(), schedule(), Timeline(), and ~Timeline().
pthread_mutex_t Timeline::timeline_inst_mutex private
Definition at line 448 of file timeline.h.
Referenced by Entity::BuildEntity(), Timeline(), and ~Timeline().
pthread_cond_t Timeline::__appointment_cond_var private
When a timeline encounters an incoming appointment time from a timeline, whose time has not yet reached the appointment, it waits on this condition variable.
The timeline it waits for must signal the variable.
Definition at line 455 of file timeline.h.
Referenced by initialize_appt(), sync_window(), Timeline(), and ~Timeline().
Timeline* Timeline::__waiting_on_timeline private
When a timeline reaches an incoming appointment and finds that the timeline it awaits has not yet reached the synchronization point, it puts that Timeline's address in this variable and does a wait on the condition variable.
Definition at line 462 of file timeline.h.
vector<mappedChannel*> Timeline::__channels_to_map private
When mapto is called during execution of the simulation it may be necessary to delay its implementation until the end of the current simulation window.
When that happens, a description of the mapping is created and a pointer to it is put in the __channels_to_map vector. At the end of a synchronization window the Timeline checks whether this list is empty, and if not implements the new maptos. If in addition the variable __recompute_min_delay is true, then the new local minimum is computed before entering the next synchronization window (at which point that value is needed).
Definition at line 474 of file timeline.h.
Referenced by OutChannel::mapto(), sync_window(), and OutChannel::unmap().
vector<mappedChannel*> Timeline::__delays_to_change private
The s3f interface to OutChannels allows for dynamic adjustment to the minimum delay on some specified connection.
Delays that cannot immediately be dealt with are buffered in vector __delays_to_change. As with __channels_to_map, at the end of the synchronization window the size of this list is checked. If not empty the new minimum delays are imposed, and any need for recomputation of __min_sync_cross_timeline_delay is noted.
Definition at line 483 of file timeline.h.
Referenced by OutChannel::new_min_write_delay(), OutChannel::new_transfer_delay(), and sync_window().
vector<InAppointment> Timeline::__in_appt private
Definition at line 484 of file timeline.h.
Referenced by initialize_appt(), sync_window(), Timeline(), and ~Timeline().
vector<OutAppointment> Timeline::__out_appt private
Definition at line 485 of file timeline.h.
Referenced by initialize_appt(), schedule(), sync_window(), Timeline(), and ~Timeline().
STL_EventList Timeline::__events private
The event list.
An STL priority list structure is used.
Definition at line 488 of file timeline.h.
Referenced by get_cross_timeline_events(), initialize_appt(), next_time(), schedule(), select_next_event(), sync_window(), ve_proxy_entity_potential_impact_time(), and ~Timeline().
STL_EventList Timeline::__ve_sink_events private
Used for integrated with openVZ-based network emulation.
Storing events that can affect the status of a VE, in particular, a packet received at a VE-proxy entity (should be delivery to the corresponding VE as soon as possible) currently EVTYPE_ACTIVATE and EVTYPE_EXEC_ACTIVATE events, whose inChannel is attached to VE-proxy entity, are put into this event list if __ve_sink_events is used, then __events + __ve_sink_events = all events Details in the 2012 PADS paper "Virtual Time Integration of Emulation and Parallel Simulation"
Definition at line 500 of file timeline.h.
Referenced by get_cross_timeline_events(), next_time(), schedule(), select_next_event(), sync_window(), ve_proxy_entity_potential_impact_time(), and ~Timeline().
unsigned long Timeline::__handle_idx private
Definition at line 502 of file timeline.h.
Referenced by get_nxt_handle(), and Timeline().
unsigned long Timeline::__executed private
Definition at line 503 of file timeline.h.
Referenced by get_executed(), sync_window(), and Timeline().
unsigned long Timeline::__work_executed private
Definition at line 504 of file timeline.h.
Referenced by get_work_executed(), sync_window(), and Timeline().
unsigned long Timeline::__sync_executed private
Definition at line 505 of file timeline.h.
Referenced by get_sync_executed(), sync_window(), and Timeline().
unsigned long Timeline::__executed_one_window private
Definition at line 506 of file timeline.h.
Referenced by sync_window(), and Timeline().
unsigned long Timeline::__work_executed_one_window private
Definition at line 507 of file timeline.h.
Referenced by sync_window(), and Timeline().
unsigned long Timeline::__sync_executed_one_window private
Definition at line 508 of file timeline.h.
Referenced by sync_window(), and Timeline().
unsigned int Timeline::__evtnum private
Definition at line 510 of file timeline.h.
Referenced by initialize_appt(), schedule(), and sync_window().
bool Timeline::__no_global_check private
Definition at line 512 of file timeline.h.
Referenced by global_continue(), thread_function(), and Timeline().
ltime_t Timeline::t_prime private
time of first executed deliver-to-VE event in previous SSW
Definition at line 514 of file timeline.h.
Referenced by sync_window(), and Timeline().
pthread_mutex_t Timeline::timeline_class_mutex static
Synchronizes access to __entity_list.
Needed when the implementation advances to dynamic alignment of Entities to Timelines.
Definition at line 528 of file timeline.h.
Referenced by Interface::Interface(), Timeline(), and ~Timeline().
unsigned int Timeline::__num_timelines = 0 static
Enumerates the number of Timeline instances created.
Value at instance of a Timeline's creation becomes that Timeline's id.
Definition at line 534 of file timeline.h.
Referenced by initialize_appt(), Interface::InitModel(), and Timeline().
int Timeline::default_sched_pri static
Calls to schedule that could provide a priority for same-time tie-breking but do not are given this default_sched_pri.
The range of values permitted a user is 0- (2^{16}-1). default_sched_pri is set to this largest value (like time, smaller means higher priority).
Definition at line 542 of file timeline.h.
Referenced by Timeline(), Entity::waitFor(), and OutChannel::write().
int Timeline::min_sched_pri static
minimum possible scheduling priority, used only by a timeline, not a user priority
Definition at line 545 of file timeline.h.
Referenced by initialize_appt(), sync_window(), and Timeline().
vector< Timeline * > Timeline::timeline_adrs static
Definition at line 546 of file timeline.h.
Referenced by initialize_appt(), sync_window(), and Timeline().
The documentation for this class was generated from the following files:
timeline.h
timeline.cc