S3F: s3f::s3fnet::NetAccessory Class Reference
s3f::s3fnet::NetAccessory Class Reference
Extra options associated with a net.
#include <net.h>
Classes
struct NetAttribute
Public Member Functions
NetAccessory ()
The constructor.
~NetAccessory ()
The destructor.
void addAttribute (byte at, bool value)
Add an attribute of bool type.
void addAttribute (byte at, int value)
Add an attribute of int type.
void addAttribute (byte at, double value)
Add an attribute of double type.
void addAttribute (byte at, void *value)
Add an attribute of pointer type.
bool requestAttribute (byte at, bool &value)
Request an attribute of bool type.
bool requestAttribute (byte at, int &value)
Request an attribute of int type.
bool requestAttribute (byte at, double &value)
Request an attribute of double type.
bool requestAttribute (byte at, void *&value)
Request an attribute of pointer type.
Protected Member Functions
typedef S3FNET_VECTOR (NetAttribute *) NET_ATTRIB_VECTOR
Protected Attributes
NET_ATTRIB_VECTOR netAttribList
List of attributes.
Detailed Description
Extra options associated with a net.
We observe that not all net objects should own some attributes like as AS boundary (whether this net is at the boundary of an AS), AS number, etc. This class provides a uniform interface for these attributes.
Definition at line 400 of file net.h.
Constructor & Destructor Documentation
s3f::s3fnet::NetAccessory::NetAccessory () inline
The constructor.
Definition at line 403 of file net.h.
 {}
s3f::s3fnet::NetAccessory::~NetAccessory ()
The destructor.
Definition at line 968 of file net.cc.
References netAttribList.
 {
         unsigned size= netAttribList.size();
         for(unsigned i=0; i<size; i++)
                 delete netAttribList[i];
 }
Member Function Documentation
void s3f::s3fnet::NetAccessory::addAttribute (byte at, bool value)
Add an attribute of bool type.
Definition at line 864 of file net.cc.
References s3f::s3fnet::NetAccessory::NetAttribute::bool_val, s3f::s3fnet::NetAccessory::NetAttribute::name, netAttribList, and s3f::s3fnet::NetAccessory::NetAttribute::value.
Referenced by s3f::s3fnet::Net::finish_config_top_net().
 {
         NetAttribute* new_attrib = new NetAttribute;
         new_attrib->name = at;
         new_attrib->value.bool_val = value;
         // put it in the list
         netAttribList.push_back(new_attrib);
 }
void s3f::s3fnet::NetAccessory::addAttribute (byte at, int value)
Add an attribute of int type.
Definition at line 874 of file net.cc.
References s3f::s3fnet::NetAccessory::NetAttribute::int_val, s3f::s3fnet::NetAccessory::NetAttribute::name, netAttribList, and s3f::s3fnet::NetAccessory::NetAttribute::value.
 {
         NetAttribute* new_attrib = new NetAttribute;
         new_attrib->name = at;
         new_attrib->value.int_val = value;
         // put it in the list
         netAttribList.push_back(new_attrib);
 }
void s3f::s3fnet::NetAccessory::addAttribute (byte at, double value)
Add an attribute of double type.
Definition at line 884 of file net.cc.
References s3f::s3fnet::NetAccessory::NetAttribute::double_val, s3f::s3fnet::NetAccessory::NetAttribute::name, netAttribList, and s3f::s3fnet::NetAccessory::NetAttribute::value.
 {
         NetAttribute* new_attrib = new NetAttribute;
         new_attrib->name = at;
         new_attrib->value.double_val = value;
         // put it in the list
         netAttribList.push_back(new_attrib);
 }
void s3f::s3fnet::NetAccessory::addAttribute (byte at, void * value)
Add an attribute of pointer type.
Definition at line 894 of file net.cc.
References s3f::s3fnet::NetAccessory::NetAttribute::name, netAttribList, s3f::s3fnet::NetAccessory::NetAttribute::pointer_val, and s3f::s3fnet::NetAccessory::NetAttribute::value.
 {
         NetAttribute* new_attrib = new NetAttribute;
         new_attrib->name = at;
         new_attrib->value.pointer_val = value;
         // put it in the list
         netAttribList.push_back(new_attrib);
 }
bool s3f::s3fnet::NetAccessory::requestAttribute (byte at, bool & value)
Request an attribute of bool type.
Definition at line 904 of file net.cc.
References netAttribList.
Referenced by s3f::s3fnet::Net::control(), and s3f::s3fnet::Net::init().
 {
         int size = netAttribList.size();
         for(int i = 0; i < size; i++)
         {
                 if(netAttribList[i]->name == at)
                 {
                         value = netAttribList[i]->value.bool_val;
                         return true;
                 }
         }
         // if the attribute cannot be found, return 0.
         return false;
 }
bool s3f::s3fnet::NetAccessory::requestAttribute (byte at, int & value)
Request an attribute of int type.
Definition at line 920 of file net.cc.
References netAttribList.
 {
         int size = netAttribList.size();
         for(int i = 0; i < size; i++)
         {
                 if(netAttribList[i]->name == at)
                 {
                         value = netAttribList[i]->value.int_val;
                         return true;
                 }
         }
         // if the attribute cannot be found, return 0.
         return false;
 }
bool s3f::s3fnet::NetAccessory::requestAttribute (byte at, double & value)
Request an attribute of double type.
Definition at line 936 of file net.cc.
References netAttribList.
 {
         int size = netAttribList.size();
         for(int i = 0; i < size; i++)
         {
                 if(netAttribList[i]->name == at)
                 {
                         value = netAttribList[i]->value.double_val;
                         return true;
                 }
         }
         // if the attribute cannot be found, return 0.
         return false;
 }
bool s3f::s3fnet::NetAccessory::requestAttribute (byte at, void *& value)
Request an attribute of pointer type.
Definition at line 952 of file net.cc.
References netAttribList.
 {
         int size = netAttribList.size();
         for(int i = 0; i < size; i++)
         {
                 if(netAttribList[i]->name == at)
                 {
                         value = netAttribList[i]->value.pointer_val;
                         return true;
                 }
         }
         // if the attribute cannot be found, return 0.
         return false;
 }
typedef s3f::s3fnet::NetAccessory::S3FNET_VECTOR (NetAttribute *) protected
Member Data Documentation
NET_ATTRIB_VECTOR s3f::s3fnet::NetAccessory::netAttribList protected
List of attributes.
Definition at line 455 of file net.h.
Referenced by addAttribute(), requestAttribute(), and ~NetAccessory().
The documentation for this class was generated from the following files:
net.h
net.cc