S3F: VESlave Class Reference
VESlave Class Reference
Class for a single VE slave, for both master side and slave side.
#include <dsimctrl.h>
Public Member Functions
VESlave ()
constructor
virtual ~VESlave ()
destructor
int master_connect ()
master side connect slave
int master_disconnect ()
master side disconnect slave
int master_setip (int ctid, int ifid, const char *ip)
master side set VE IP address
int master_exec (int ctid, const char *cmd)
master side exec VE command
int master_init ()
master side initialization
int master_fini (bool close)
master side clean up
int master_pushpacket ()
master side push packets
int master_test ()
master side test
int master_cycle (bool newcycle)
master side cycle
int master_checkstatus (bool *ready)
check if previous call has finished
int slave_mainloop ()
slave side main function
Public Attributes
char * addr
ip address of the slave
int fromid
start VE ID of this slave (static range)
int toid
end VE ID of this slave (static range)
int idoffset
VE ID offset (veid_on_slave = veid_on_host - veid_offset)
bool selected
flag: is this slave selected? (for master side use)
int idbase
start VE ID being selected of this emulation setup
int nve
total number of VEs being selected in this emulation setup
vector< VEHandle * > ve
VE handles.
vector< int > vemap
VE mapping.
vector< int > venif
number of interfaces of all VEs
vector< int > pktcount
number of packets pushed to master
vector< bool > done
for simctrl cycle use
int la_type
type of app lookahead algorithm
bool onedone
flag: at least one VE reaches the barrier?
bool alldone
flag: all VEs reach the barrier?
bool newbarrier
flag: has the barrier been updated since last call?
int ndone
number of finished VEs
ltime_t barrier
barrier given by S3F/S3FNet
ltime_t maxadv
barrier to release VE safely, subject to mindelay constrains
struct timeval tvbarrier
timeval representation of barrier
int nthread
multi-thread number for lookahead prediction
int laerr
lookahead error
Private Types
enum state_t {
DISCONNECTED, READY, ERROR, SETIP,
INIT, FINI, TEST, EXEC,
CYCLE
}
VE slave state enumeration, for master side.
Private Member Functions
int master_setip_gotmsg (void *msg)
master side message handler
int master_exec_gotmsg (void *msg)
master side message handler
int master_init_gotmsg (void *msg)
master side message handler
int master_fini_gotmsg (void *msg)
master side message handler
int master_test_gotmsg (void *msg)
master side message handler
int master_cycle_gotmsg (void *msg)
master side message handler
int slave_gotmsg_setip (void *msg)
slave side message handler
int slave_gotmsg_exec (void *msg)
slave side message handler
int slave_gotmsg_init (void *msg)
slave side message handler
int slave_gotmsg_fini (void *msg)
slave side message handler
int slave_gotmsg_close (void *msg)
slave side message handler
int slave_gotmsg_packet (void *msg)
slave side message handler
int slave_gotmsg_test (void *msg)
slave side message handler
int slave_gotmsg_cycle (void *msg)
slave side message handler
Private Attributes
state_t state
current state of master
void * amh
asynchronous message handler for master-slave communication
bool isinit
has init been called?
Detailed Description
Class for a single VE slave, for both master side and slave side.
A VE slave is a bundle of VEs running on a remote machine. The distributed VE controller can control several VE slaves at a time to run distributed emulation.
Definition at line 20 of file dsimctrl.h.
Member Enumeration Documentation
enum VESlave::state_t private
VE slave state enumeration, for master side.
Enumerator
DISCONNECTED
READY
ERROR
SETIP
INIT
FINI
TEST
EXEC
CYCLE
Definition at line 172 of file dsimctrl.h.
 { DISCONNECTED, READY, ERROR, SETIP, INIT, FINI, TEST, EXEC, CYCLE };
Constructor & Destructor Documentation
VESlave::VESlave ()
constructor
Definition at line 55 of file dsimctrl.cc.
References addr, amh, DISCONNECTED, isinit, laerr, nthread, nve, selected, and state.
 {
         state = DISCONNECTED;
         selected = false;
         isinit = false;
         addr = NULL;
         amh = NULL;
         nthread = 1;
         nve = 0;
         laerr = 0;
         pslave = this;
 }
VESlave::~VESlave () virtual
destructor
Definition at line 70 of file dsimctrl.cc.
References addr, and amh.
 {
         if (addr) delete addr;
         if (amh) delete (AsyncMessageHandler*)amh;
 }
Member Function Documentation
int VESlave::master_connect ()
master side connect slave
Definition at line 78 of file dsimctrl.cc.
References addr, amh, AsyncMessageHandler::amh_connect(), DISCONNECTED, isinit, READY, and state.
Referenced by master_fini(), master_init(), and master_setip().
 {
         if (state != DISCONNECTED) return -EEXIST;
         if (!addr) return -EBADF;
         AsyncMessageHandler *amh = new AsyncMessageHandler;
         int ret = amh->amh_connect(addr);
         if (ret) { delete amh; return ret; }
         this->amh = amh;
         state = READY;
         isinit = false;
         return 0;
 }
int VESlave::master_disconnect ()
master side disconnect slave
Definition at line 93 of file dsimctrl.cc.
References amh, AsyncMessageHandler::amh_close(), AsyncMessage::CLOSE, DISCONNECTED, state, and AsyncMessage::type.
Referenced by master_fini_gotmsg().
 {
         if (state == DISCONNECTED) return 0;
         AsyncMessageHandler *amh = (AsyncMessageHandler*) this->amh;
         AsyncMessage *m = new AsyncMessage;
         m->type = AsyncMessage::CLOSE;
         int ret = ((AsyncMessageHandler*)amh)->amh_send(m);
         delete m;
         if (ret) return ret;
         ret = amh->amh_close();
         delete amh;
         this->amh = NULL;
         if (!ret) state = DISCONNECTED;
         return ret;
 }
int VESlave::master_setip (int ctid, int ifid, const char * ip)
master side set VE IP address
Definition at line 111 of file dsimctrl.cc.
References amh, DISCONNECTED, EBUSY, idbase, idoffset, AsyncMessage::int1, AsyncMessage::int2, isinit, master_connect(), nve, AsyncMessage::payload, AsyncMessage::payloadlen, READY, AsyncMessage::resize(), AsyncMessage::SETIP, SETIP, state, and AsyncMessage::type.
Referenced by DSimCtrl::set_ve_ifip().
 {
         int ret = 0;
         if (isinit) return -EPERM;
         if (state == DISCONNECTED) ret = master_connect();
         if (ret) return ret;
         if (state != READY) return -EBUSY;
         if (ctid < idbase || ctid >= idbase+nve) return -ERANGE;
         AsyncMessage *m = new AsyncMessage;
         m->type = AsyncMessage::SETIP;
         m->int1 = ctid - idoffset;
         m->int2 = ifid;
         m->resize(strlen(ip) + 1);
         memcpy(m->payload, ip, m->payloadlen);
         ret = ((AsyncMessageHandler*)amh)->amh_send(m);
         delete m;
         if (ret) return ret;
         state = SETIP;
         return 0;
 }
int VESlave::master_exec (int ctid, const char * cmd)
master side exec VE command
Definition at line 151 of file dsimctrl.cc.
References amh, EBUSY, AsyncMessage::EXEC, EXEC, idbase, idoffset, AsyncMessage::int1, isinit, nve, AsyncMessage::payload, AsyncMessage::payloadlen, READY, AsyncMessage::resize(), state, and AsyncMessage::type.
Referenced by DSimCtrl::exec_ve_command().
 {
         int ret = 0;
         if (!isinit) return -EPERM;
         if (state != READY) return -EBUSY;
         if (ctid < idbase || ctid >= idbase+nve) return -ERANGE;
         AsyncMessage *m = new AsyncMessage;
         m->type = AsyncMessage::EXEC;
         m->int1 = ctid - idoffset;
         m->resize(strlen(cmd) + 1);
         memcpy(m->payload, cmd, m->payloadlen);
         ret = ((AsyncMessageHandler*)amh)->amh_send(m);
         delete m;
         if (ret) return ret;
         state = EXEC;
         return 0;
 }
int VESlave::master_init ()
master side initialization
Definition at line 188 of file dsimctrl.cc.
References amh, DISCONNECTED, EBUSY, idbase, idoffset, AsyncMessage::INIT, INIT, AsyncMessage::int1, AsyncMessage::int2, isinit, la_type, master_connect(), nve, AsyncMessage::payload, READY, AsyncMessage::resize(), state, AsyncMessage::time, toid, AsyncMessage::type, and venif.
 {
         int ret = 0;
         if (state == DISCONNECTED) ret = master_connect();
         if (ret) return ret;
         if (state != READY) return -EBUSY;
         if (isinit) return -EEXIST;
         if (nve <= 0 || idbase < fromid || idbase+nve-1 > toid) return -ERANGE;
         if ((int)venif.size() != nve) return -ESRCH;
         AsyncMessage *m = new AsyncMessage;
         m->type = AsyncMessage::INIT;
         m->time = la_type;
         m->int1 = idbase - idoffset;
         m->int2 = nve;
         m->resize(nve * sizeof(int));
         for (int i = 0, *p = (int*)m->payload; i < nve; i++, p++) *p = venif[i];
         ret = ((AsyncMessageHandler*)amh)->amh_send(m);
         delete m;
         if (ret) return ret;
         state = INIT;
         return 0;
 }
int VESlave::master_fini (bool close)
master side clean up
Definition at line 231 of file dsimctrl.cc.
References amh, DISCONNECTED, EBUSY, AsyncMessage::FINI, FINI, idbase, idoffset, AsyncMessage::int1, AsyncMessage::int2, master_connect(), nve, READY, state, AsyncMessage::time, and AsyncMessage::type.
 {
         int ret = 0;
         if (state == DISCONNECTED) ret = master_connect();
         if (ret) return ret;
         if (state != READY) return -EBUSY;
         AsyncMessage *m = new AsyncMessage;
         m->type = AsyncMessage::FINI;
         m->int1 = idbase - idoffset;
         m->int2 = nve;
         m->time = close;
         ret = ((AsyncMessageHandler*)amh)->amh_send(m);
         delete m;
         if (ret) return ret;
         state = FINI;
         return 0;
 }
int VESlave::master_pushpacket ()
master side push packets
Definition at line 276 of file dsimctrl.cc.
References amh, EmuPacket::data, idoffset, EmuPacket::ifid, AsyncMessage::int1, AsyncMessage::int2, EmuPacket::len, nve, AsyncMessage::PACKET, AsyncMessage::payload, AsyncMessage::resize(), AsyncMessage::time, EmuPacket::timestamp, AsyncMessage::type, and ve.
 {
         for (int i = 0; i < nve; i++)
                 while (!ve[i]->recvq.empty())
                 {
                         EmuPacket *ppkt = ve[i]->recvq.front();
                         ve[i]->recvq.pop_front();
                         AsyncMessage *m = new AsyncMessage;
                         m->type = AsyncMessage::PACKET;
                         m->time = ppkt->timestamp;
                         m->int1 = ve[i]->id - idoffset;
                         m->int2 = ppkt->ifid;
                         m->resize(ppkt->len);
                         memcpy(m->payload, ppkt->data, ppkt->len);
                         int ret = ((AsyncMessageHandler*)amh)->amh_send(m);
                         delete m;
                         delete ppkt;
                         if (ret) return ret;
                 }
         return 0;
 }
int VESlave::master_test ()
master side test
Definition at line 301 of file dsimctrl.cc.
References amh, EBUSY, isinit, nve, READY, AsyncMessage::resize(), state, AsyncMessage::TEST, TEST, and AsyncMessage::type.
 {
         int ret = 0;
         if (state != READY) return -EBUSY;
         if (!isinit) return -ENXIO;
         AsyncMessage *m = new AsyncMessage;
         m->type = AsyncMessage::TEST;
         m->resize(nve * sizeof(ltime_t));
         ret = ((AsyncMessageHandler*)amh)->amh_send(m);
         delete m;
         if (ret) return ret;
         state = TEST;
         return 0;
 }
int VESlave::master_cycle (bool newcycle)
master side cycle
Definition at line 335 of file dsimctrl.cc.
References amh, barrier, AsyncMessage::CYCLE, CYCLE, EBUSY, AsyncMessage::int1, AsyncMessage::int2, isinit, maxadv, newbarrier, READY, state, AsyncMessage::time, and AsyncMessage::type.
 {
         int ret = 0;
         if (state != READY) return -EBUSY;
         if (!isinit) return -ENXIO;
         AsyncMessage *m = new AsyncMessage;
         m->type = AsyncMessage::CYCLE;
         m->time = newbarrier ? barrier : -1;
         m->int1 = barrier - maxadv;
         m->int2 = newcycle;
         newbarrier = false;
         ret = ((AsyncMessageHandler*)amh)->amh_send(m);
         delete m;
         if (ret) return ret;
         state = CYCLE;
         return 0;
 }
int VESlave::master_checkstatus (bool * ready)
check if previous call has finished
Definition at line 391 of file dsimctrl.cc.
References amh, CYCLE, DISCONNECTED, EXEC, FINI, INIT, master_cycle_gotmsg(), master_exec_gotmsg(), master_fini_gotmsg(), master_init_gotmsg(), master_setip_gotmsg(), master_test_gotmsg(), READY, SETIP, state, and TEST.
Referenced by DSimCtrl::exec_ve_command(), and DSimCtrl::set_ve_ifip().
 {
         if (state == DISCONNECTED || state == READY) { *ready = true; return 0; }
         int ret = 0;
         while (1)
         {
                 AsyncMessage *msg = NULL;
                 if ((ret = ((AsyncMessageHandler*)amh)->amh_recv(&msg))) break;
                 if (!msg) break;
                 switch (state)
                 {
                 case SETIP:
                         ret = master_setip_gotmsg(msg);
                         break;
                 case INIT:
                         ret = master_init_gotmsg(msg);
                         break;
                 case TEST:
                         ret = master_test_gotmsg(msg);
                         break;
                 case EXEC:
                         ret = master_exec_gotmsg(msg);
                         break;
                 case CYCLE:
                         ret = master_cycle_gotmsg(msg);
                         break;
                 case FINI:
                         ret = master_fini_gotmsg(msg);
                         break;
                 default:
                         printf("unexpected state, state=%d\n", state);
                         ret = -EPIPE;
                 }
                 delete msg;
                 if (ret) break;
         }
         if (ret < 0) return ret;
         *ready = (ret > 0) || (state == READY);
         return 0;
 }
int VESlave::slave_mainloop ()
slave side main function
Definition at line 1072 of file dsimctrl.cc.
References amh, AsyncMessageHandler::amh_close(), AsyncMessageHandler::amh_connect(), AsyncMessageHandler::amh_recv(), AsyncMessage::CLOSE, AsyncMessage::CYCLE, EMU_MAX_VE, AsyncMessage::EXEC, AsyncMessage::FINI, AsyncMessage::INIT, AsyncMessage::PACKET, AsyncMessage::SETIP, slave_gotmsg_close(), slave_gotmsg_cycle(), slave_gotmsg_exec(), slave_gotmsg_fini(), slave_gotmsg_init(), slave_gotmsg_packet(), slave_gotmsg_setip(), slave_gotmsg_test(), AsyncMessage::TEST, AsyncMessage::type, and vtime_getvtimeve().
Referenced by main().
 {
         int ret;
         envid_t idlist[EMU_MAX_VE];
         int n;
         if (vtime_getvtimeve(&n, idlist)) {
                 printf("vtime openvz kernel not detected!\n");
                 return -EPERM;
         }
         AsyncMessageHandler *amh = new AsyncMessageHandler;
         if (!amh) return -ENOMEM;
         this->amh = amh;
         while (1)
         {
                 printf("waiting for master\n");
                 if ((ret = amh->amh_connect())) return ret;
                 printf("master connected\n");
                 while (1)
                 {
                         AsyncMessage *msg = NULL;
                         if ((ret = amh->amh_recv(&msg))) return ret;
                         if (!msg) { sched_yield(); continue; }
                         switch (msg->type)
{
                         case AsyncMessage::SETIP:
                                 ret = slave_gotmsg_setip(msg);
                                 break;
                         case AsyncMessage::INIT:
                                 ret = slave_gotmsg_init(msg);
                                 break;
                         case AsyncMessage::FINI:
                                 ret = slave_gotmsg_fini(msg);
                                 break;
                         case AsyncMessage::CLOSE:
                                 ret = slave_gotmsg_close(msg);
                                 break;
                         case AsyncMessage::PACKET:
                                 ret = slave_gotmsg_packet(msg);
                                 break;
                         case AsyncMessage::TEST:
                                 ret = slave_gotmsg_test(msg);
                                 break;
                         case AsyncMessage::EXEC:
                                 ret = slave_gotmsg_exec(msg);
                                 break;
                         case AsyncMessage::CYCLE:
                                 ret = slave_gotmsg_cycle(msg);
                                 break;
                         default:
                                 printf("unexpected message, type=%d\n", msg->type);
                                 ret = -EPIPE;
                         }
                         delete msg;
                         if (ret < 0) return ret;
                         if (ret > 0) break;
                 }
                 if ((ret = amh->amh_close())) return ret;
                 printf("master disconnected\n\n");
         }
         delete amh;
         this->amh = NULL;
         return 0;
 }
int VESlave::master_setip_gotmsg (void * msg) private
master side message handler
Definition at line 136 of file dsimctrl.cc.
References ERROR, AsyncMessage::FAIL, AsyncMessage::int1, READY, state, AsyncMessage::SUCC, and AsyncMessage::type.
Referenced by master_checkstatus().
 {
         AsyncMessage *msg = (AsyncMessage*)m;
         if (msg->type != AsyncMessage::SUCC) {
                 state = ERROR;
                 return msg->type == AsyncMessage::FAIL ? msg->int1 : -EPIPE;
         }
         state = READY;
         return 0;
 }
int VESlave::master_exec_gotmsg (void * msg) private
master side message handler
Definition at line 173 of file dsimctrl.cc.
References ERROR, AsyncMessage::FAIL, AsyncMessage::int1, READY, state, AsyncMessage::SUCC, and AsyncMessage::type.
Referenced by master_checkstatus().
 {
         AsyncMessage *msg = (AsyncMessage*)m;
         if (msg->type != AsyncMessage::SUCC) {
                 state = ERROR;
                 return msg->type == AsyncMessage::FAIL ? msg->int1 : -EPIPE;
         }
         state = READY;
         return 0;
 }
int VESlave::master_init_gotmsg (void * msg) private
master side message handler
Definition at line 215 of file dsimctrl.cc.
References ERROR, AsyncMessage::FAIL, AsyncMessage::int1, isinit, READY, state, AsyncMessage::SUCC, and AsyncMessage::type.
Referenced by master_checkstatus().
 {
         AsyncMessage *msg = (AsyncMessage*)m;
         if (msg->type != AsyncMessage::SUCC) {
                 state = ERROR;
                 return msg->type == AsyncMessage::FAIL ? msg->int1 : -EPIPE;
         }
         isinit = true;
         state = READY;
         return 0;
 }
int VESlave::master_fini_gotmsg (void * msg) private
master side message handler
Definition at line 253 of file dsimctrl.cc.
References DISCONNECTED, ERROR, AsyncMessage::FAIL, AsyncMessage::int1, isinit, master_disconnect(), READY, state, AsyncMessage::SUCC, AsyncMessage::time, and AsyncMessage::type.
Referenced by master_checkstatus().
 {
         AsyncMessage *msg = (AsyncMessage*)m;
         if (msg->type != AsyncMessage::SUCC) {
                 state = ERROR;
                 return msg->type == AsyncMessage::FAIL ? msg->int1 : -EPIPE;
         }
         isinit = false;
         if (msg->time) {
                 int ret = master_disconnect();
                 if (ret) return ret;
                 state = DISCONNECTED;
         }
         else {
                 state = READY;
         }
         return (int)msg->time;
 }
int VESlave::master_test_gotmsg (void * msg) private
master side message handler
Definition at line 320 of file dsimctrl.cc.
References ERROR, AsyncMessage::FAIL, AsyncMessage::int1, READY, state, AsyncMessage::SUCC, and AsyncMessage::type.
Referenced by master_checkstatus().
 {
         AsyncMessage *msg = (AsyncMessage*)m;
         if (msg->type != AsyncMessage::SUCC) {
                 state = ERROR;
                 return msg->type == AsyncMessage::FAIL ? msg->int1 : -EPIPE;
         }
         state = READY;
         return 0;
 }
int VESlave::master_cycle_gotmsg (void * msg) private
master side message handler
Definition at line 357 of file dsimctrl.cc.
References alldone, barrier, EmuPacket::data, ERROR, AsyncMessage::FAIL, idbase, idoffset, EmuPacket::ifid, AsyncMessage::int1, AsyncMessage::int2, laerr, ndone, nve, onedone, AsyncMessage::PACKET, AsyncMessage::payload, AsyncMessage::payloadlen, READY, state, AsyncMessage::SUCC, AsyncMessage::time, EmuPacket::timestamp, AsyncMessage::type, and ve.
Referenced by master_checkstatus().
 {
         AsyncMessage *msg = (AsyncMessage*)m;
         if (msg->type == AsyncMessage::PACKET) {
                 EmuPacket *ppkt = new EmuPacket(msg->payloadlen);
                 ppkt->ifid = msg->int2;
                 memcpy(ppkt->data, msg->payload, msg->payloadlen);
                 ppkt->timestamp = msg->time;
                 ve[msg->int1 - idbase + idoffset]->sendq.push_back(ppkt);
         }
         else if (msg->type == AsyncMessage::SUCC) {
                 ndone = msg->int1;
                 laerr = msg->int2;
                 onedone = (ndone > 0);
                 alldone = (ndone == nve);
                 if (msg->payloadlen != nve * (int)sizeof(ltime_t)) return -EPIPE;
                 ltime_t *p = (ltime_t*)msg->payload;
                 for (int i = 0; i < nve; i++, p++) {
                         ve[i]->lookahead = alldone ? *p : 0;
                         ve[i]->clock = alldone ? barrier : *p;
                 }
                 state = READY;
         }
         else {
                 state = ERROR;
                 return msg->type == AsyncMessage::FAIL ? msg->int1 : -EPIPE;
         }
         return 0;
 }
int VESlave::slave_gotmsg_setip (void * msg) private
slave side message handler
Definition at line 438 of file dsimctrl.cc.
References amh, AsyncMessage::FAIL, gotofail, AsyncMessage::int1, AsyncMessage::int2, AsyncMessage::payload, AsyncMessage::payloadlen, AsyncMessage::SUCC, and AsyncMessage::type.
Referenced by slave_mainloop().
 {
         AsyncMessage *msg = (AsyncMessage*)m;
         int ret, reason = 0;
         AsyncMessage *reply = NULL;
         if (msg->payloadlen > 64) gotofail(-E2BIG);
         char cmd[100];
         sprintf(cmd, "ifconfig veth%d.%d %s", msg->int1, msg->int2, msg->payload);
         if (system(cmd)) gotofail(-ENOEXEC);
         sprintf(cmd, "vzctl exec %d ifconfig eth%d %s", msg->int1, msg->int2, msg->payload);
         if (system(cmd)) gotofail(-ENOEXEC);
         reply = new AsyncMessage;
         reply->type = AsyncMessage::SUCC;
         ret = ((AsyncMessageHandler*)amh)->amh_send(reply);
         delete reply;
         return ret;
 FAIL:
         reply = new AsyncMessage;
         reply->type = AsyncMessage::FAIL;
         reply->int1 = reason;
         ret = ((AsyncMessageHandler*)amh)->amh_send(reply);
         delete reply;
         return ret;
 }
int VESlave::slave_gotmsg_exec (void * msg) private
slave side message handler
Definition at line 469 of file dsimctrl.cc.
References amh, AsyncMessage::FAIL, gotofail, AsyncMessage::int1, AsyncMessage::payload, AsyncMessage::payloadlen, AsyncMessage::SUCC, and AsyncMessage::type.
Referenced by slave_mainloop().
 {
         AsyncMessage *msg = (AsyncMessage*)m;
         int ret, reason = 0;
         AsyncMessage *reply = NULL;
         if (msg->payloadlen > 160) gotofail(-E2BIG);
         char cmd[200];
         sprintf(cmd, "vzctl exec %d \"%s &\"", msg->int1, msg->payload);
         if (system(cmd)) gotofail(-ENOEXEC);
         reply = new AsyncMessage;
         reply->type = AsyncMessage::SUCC;
         ret = ((AsyncMessageHandler*)amh)->amh_send(reply);
         delete reply;
         return ret;
 FAIL:
         reply = new AsyncMessage;
         reply->type = AsyncMessage::FAIL;
         reply->int1 = reason;
         ret = ((AsyncMessageHandler*)amh)->amh_send(reply);
         delete reply;
         return ret;
 }
int VESlave::slave_gotmsg_init (void * msg) private
slave side message handler
Definition at line 497 of file dsimctrl.cc.
References amh, done, EINVAL, EMU_MAX_VE, AsyncMessage::FAIL, gotofail, VEHandle::id, idbase, AsyncMessage::int1, AsyncMessage::int2, isinit, la_type, lastprint, lastvtime, VEHandle::nif, nve, AsyncMessage::payload, AsyncMessage::payloadlen, VEHandle::pcap, pfslave, pktcount, AsyncMessage::SUCC, AsyncMessage::time, timestat_counter, AsyncMessage::type, ve, vemap, venif, vtime_getvtimeve(), vtime_setclock(), and vtime_setenable().
Referenced by slave_mainloop().
 {
         AsyncMessage *msg = (AsyncMessage*)m;
         int ret, reason = 0;
         AsyncMessage *reply = NULL;
         /* parse message */
         if (msg->payloadlen != msg->int2 * (int)sizeof(int)) gotofail(-EINVAL);
         idbase = msg->int1;
         nve = msg->int2;
         la_type = (int)msg->time;
         venif.resize(nve);
         for (int i = 0, *p = (int*)msg->payload; i < nve; i++, p++) venif[i] = *p;
         /* init VEs */
         envid_t idlist[EMU_MAX_VE];
         struct timeval tv;
         int n;
         if (isinit) gotofail(-EEXIST);
         if (nve <= 0) gotofail(-EINVAL);
         tv.tv_sec = tv.tv_usec = 0;
         /* validate vtime VEs */
         for (int i = 0; i < nve; i++)
                 if (vtime_setenable(idbase+i, 0)) gotofail(-EINTR);
         if (vtime_getvtimeve(&n, idlist)) gotofail(-EINTR);
         if (n != 0) gotofail(-ESRCH);
         /* enable vtime switches */
         for (int i = 0; i < nve; i++) {
                 if (vtime_setenable(idbase+i, 1)) gotofail(-EINTR);
                 if (vtime_setclock(idbase+i, &tv)) gotofail(-EINTR);
         }
         /* init VE mapping */
         isinit = true;
         vemap.resize(nve);
         ve.resize(nve);
         done.resize(nve);
         pktcount.resize(nve);
         vtime_getvtimeve(&n, idlist);
         for (int i = 0; i < nve; i++) vemap[idlist[i]-idbase] = i;
         /* init VEHandle */
         for (int i = 0; i < nve; i++) {
                 VEHandle *p = new VEHandle(idbase + i, la_type, venif[i]);
                 if (!p) gotofail(-ENOMEM);
                 ve[vemap[i]] = p;
         }
         /* open pcap handles */
         for (int i = 0; i < nve; i++) {
                 VEHandle *p = ve[vemap[i]];
                 char str[20];
                 char errbuf[PCAP_ERRBUF_SIZE];
                 for (int j = 0; j < p->nif; j++) {
                         sprintf(str, "veth%d.%d", p->id, j);
                         p->pcap[j] = (void*)pcap_open_live(str, BUFSIZ, 0, 1000, errbuf);
                         if (!p->pcap[j]) gotofail(-ENODEV);
                         if (pcap_setdirection((pcap_t*)p->pcap[j], PCAP_D_IN)) gotofail(-EIO);
                         if (pcap_setnonblock((pcap_t*)p->pcap[j], 1, errbuf)) gotofail(-EIO);
                 }
         }
 #ifdef TIME_STAT
         timestat_counter = 0;
         gettimeofday(&lastprint, NULL);
         lastvtime = 0;
 #endif
 #ifdef SLAVE_LOG
         pfslave = fopen("slave.log", "a");
         if (!pfslave) gotofail(-EACCES);
         fprintf(pfslave, "========================================\n");
         if (la_type) for (int i = 0; i < nve; i++) ((Lookahead*)ve[i]->la)->set_pflog(pfslave);
 #endif
         /* reply message */
         reply = new AsyncMessage;
         reply->type = AsyncMessage::SUCC;
         ret = ((AsyncMessageHandler*)amh)->amh_send(reply);
         delete reply;
         return ret;
 FAIL:
         reply = new AsyncMessage;
         reply->type = AsyncMessage::FAIL;
         reply->int1 = reason;
         ret = ((AsyncMessageHandler*)amh)->amh_send(reply);
         delete reply;
         return ret;
 }
int VESlave::slave_gotmsg_fini (void * msg) private
slave side message handler
Definition at line 593 of file dsimctrl.cc.
References amh, idbase, AsyncMessage::int1, AsyncMessage::int2, isinit, nve, pfslave, AsyncMessage::SUCC, AsyncMessage::time, AsyncMessage::type, ve, vemap, and vtime_setenable().
Referenced by slave_mainloop().
 {
         AsyncMessage *msg = (AsyncMessage*)m;
         AsyncMessage *reply = NULL;
         idbase = msg->int1;
         nve = msg->int2;
         /* disable virtual time switches */
         for (int i = 0; i < nve; i++)
                 vtime_setenable(idbase+i, 0);
         if (isinit)
         {
                 /* delete VEHandle */
                 for (int i = 0; i < nve; i++) if (ve[i]) delete ve[i];
                 vemap.clear();
                 ve.clear();
                 isinit = false;
         }
 #ifdef SLAVE_LOG
         if (pfslave) {
                 fprintf(pfslave, "========================================\n\n");
                 fclose(pfslave);
                 pfslave = NULL;
         }
 #endif
         /* reply message */
         reply = new AsyncMessage;
         reply->type = AsyncMessage::SUCC;
         reply->time = msg->time;
         int ret = ((AsyncMessageHandler*)amh)->amh_send(reply);
         delete reply;
         if (ret) return ret;
         /* close connection */
         return (int)msg->time;
 }
int VESlave::slave_gotmsg_close (void * msg) private
slave side message handler
Definition at line 637 of file dsimctrl.cc.
Referenced by slave_mainloop().
 {
         /* close connection */
         return 1;
 }
int VESlave::slave_gotmsg_packet (void * msg) private
slave side message handler
Definition at line 645 of file dsimctrl.cc.
References EmuPacket::data, idbase, EmuPacket::ifid, AsyncMessage::int1, AsyncMessage::int2, AsyncMessage::payload, AsyncMessage::payloadlen, AsyncMessage::time, EmuPacket::timestamp, ve, and vemap.
Referenced by slave_mainloop().
 {
         AsyncMessage *msg = (AsyncMessage*)m;
         EmuPacket *ppkt = new EmuPacket(msg->payloadlen);
         ppkt->ifid = msg->int2;
         memcpy(ppkt->data, msg->payload, msg->payloadlen);
         ppkt->timestamp = msg->time;
         ve[vemap[msg->int1 - idbase]]->recvq.push_back(ppkt);
         return 0;
 }
int VESlave::slave_gotmsg_test (void * msg) private
slave side message handler
Definition at line 660 of file dsimctrl.cc.
References amh, nve, AsyncMessage::resize(), AsyncMessage::SUCC, and AsyncMessage::type.
Referenced by slave_mainloop().
 {
         /* reply message */
         AsyncMessage *reply = new AsyncMessage;
         reply->type = AsyncMessage::SUCC;
         reply->resize(nve * sizeof(ltime_t));
         int ret = ((AsyncMessageHandler*)amh)->amh_send(reply);
         delete reply;
         return ret;
 }
int VESlave::slave_gotmsg_cycle (void * msg) private
slave side message handler
Definition at line 701 of file dsimctrl.cc.
References alldone, amh, avgla, avgminla, barrier, EmuPacket::data, debug, debug_nopause, done, EmuTimer::due, EMU_MAX_VE, AsyncMessage::FAIL, got_packet(), gotofail, EmuPacket::ifid, AsyncMessage::int1, AsyncMessage::int2, la_postcycle_thread(), la_type, laerr, lastprint, lastvtime, EmuPacket::len, MAX_IDLE_COUNT, maxadv, ndone, newbarrier, nthread, nve, onedone, AsyncMessage::PACKET, AsyncMessage::payload, pfslave, EmuTimer::pid, pktcount, EmuTimer::repeat, AsyncMessage::resize(), AsyncMessage::SUCC, AsyncMessage::time, EmuPacket::timestamp, timestat_counter, timestat_interval, timestat_update(), tvbarrier, AsyncMessage::type, ve, vemap, vtime_firetimer(), vtime_getclock(), vtime_gettraplist(), vtime_getvestatus(), vtime_releasetrap(), vtime_releaseve(), vtime_setbarrier(), and vtime_setclock().
Referenced by slave_mainloop().
 {
         AsyncMessage *msg = (AsyncMessage*)m;
         int ret, reason = 0;
         AsyncMessage *reply = NULL;
         ltime_t *p;
         struct timeval tv;
         int rllist[EMU_MAX_VE];
         vtime_vestatus_t stlist[EMU_MAX_VE];
         struct vtime_trap trlist[VTIME_SZ_TRAPLIST];
         int rtlist[VTIME_SZ_TRAPLIST];
         int count;
         bool again, allidle, newcycle;
         if (debug) printf("----- cycle call -----\n");
         /* parse message */
         if (msg->time >= 0) {
                 barrier = msg->time;
                 tvbarrier.tv_sec = barrier / 1000000;
                 tvbarrier.tv_usec = barrier % 1000000;
                 newbarrier = true;
         }
         maxadv = barrier - msg->int1;
         newcycle = msg->int2;
         if (!newcycle) goto STEP2;
         /* step 1: lookahead pre_cycle for all VEs */
         if (la_type) {
                 for (int i = 0; i < nve; i++)
                         if (ve[i]->la) ((Lookahead*)ve[i]->la)->pre_cycle(barrier);
         }
         for (int i = 0; i < nve; i++) { done[i] = false; pktcount[i] = 0; }
         ndone = 0;
 STEP2:
         /* step 2: set the new barrier to all VEs */
         if (newbarrier) {
                 if (debug) printf("new barrier for all VEs: %ld\n", barrier);
                 for (int i = 0; i < nve; i++)
                         if (vtime_setbarrier(ve[i]->id, &tvbarrier)) gotofail(-EINTR);
                 newbarrier = false;
         }
 STEP3:
         /* step 3: push due recv packets & due timers */
         for (int i = 0; i < nve; i++) if (!done[i])
         {
                 /* push recv packets */
                 deque<EmuPacket*> *pq1 = &(ve[i]->recvq);
                 while (!pq1->empty() && pq1->front()->timestamp <= ve[i]->clock) {
                         EmuPacket *ppkt = pq1->front();
                         pq1->pop_front();
                         ve[i]->idle = false;
                         if (ppkt->ifid >= 0 && ppkt->ifid < ve[i]->nif)
{
                                 pcap_inject((pcap_t*)ve[i]->pcap[ppkt->ifid],
                                             ppkt->data, ppkt->len);
 #ifdef SLAVE_LOG
                                 fprintf(pfslave, "%ld.%06ld\tve%d\trecv\t%d\n",
                                         ve[i]->clock/1000000, ve[i]->clock%1000000,
                                         ve[i]->id, ppkt->len);
 #endif
                                 if (debug) printf("VE%d recv packet, time=%ld size=%d\n",
                                         ve[i]->id, ve[i]->clock, ppkt->len);
                         }
                         else {
                                 fprintf(stderr, "simctrl warning: "
                                         "ifid=%d, nif=%d, packet dropped\n",
                                         ppkt->ifid, ve[i]->nif);
                         }
                         delete ppkt;
                 }
                 /* push due timers */
                 priority_queue<EmuTimer> *pq2 = &(ve[i]->timerq);
                 while (!pq2->empty() && pq2->top().due <= ve[i]->clock) {
                         EmuTimer timer = pq2->top();
                         pq2->pop();
                         ve[i]->idle = false;
                         if (timer.pid) vtime_firetimer(timer.pid);
                         if (debug) printf("VE%d timer due, time=%ld\n", ve[i]->id, timer.due);
                         if (timer.repeat) {
                                 timer.due = ve[i]->clock + timer.repeat;
                                 pq2->push(timer);
                         }
                 }
         }
         /* step 4: release selected VEs */
         if (debug) printf("maxadv=%ld barrier=%ld\n", maxadv, barrier);
         again = false;
         allidle = true;
         for (int i = 0; i < nve; i++) {
                 rllist[i] = (!done[i])
                         && (!ve[i]->idle || ve[i]->idlecount > MAX_IDLE_COUNT)
                         && (ve[i]->clock < maxadv - min(ve[i]->offset, 0L));
                 if (!done[i] && ve[i]->clock < maxadv - min(ve[i]->offset, 0L)) again = true;
                 if (debug) printf("VE%d clock=%ld rllist=%d done=%d "
                                 "idle=%d idlecount=%d offset=%ld\n",
                                 ve[i]->id, ve[i]->clock, (int)rllist[i],
                                 (int)done[i], (int)ve[i]->idle,
                                 ve[i]->idlecount, ve[i]->offset);
                 if (rllist[i]) { allidle = false; ve[i]->idlecount = 0; }
         }
         if (allidle) goto STEP9;
         if (vtime_releaseve(nve, rllist)) return -EINTR;
         /* step 5: wait until all VEs have stopped */
         count = 0;
         while (1)
         {
                 int n;
                 bool ok = true;
                 if (vtime_getvestatus(&n, stlist)) return -EINTR;
                 if (n != nve) return -ESRCH;
                 for (int i = 0; i < nve; i++) {
                         if (0 && debug && count > 20) {
                                 printf("VEs still not done, stlist =");
                                 for (int i = 0; i < nve; i++) printf(" %d", stlist[i]);
                                 printf("\n");
                         }
                         if (count > 100 && stlist[i] == VTIME_READY)
                                 stlist[i] = VTIME_SUSPENDED;
                         if (stlist[i] != VTIME_SUSPENDED && stlist[i] != VTIME_IDLE) {
                                 ok = false; /* some VEs still running */
                                 sched_yield();
                                 break;
                         }
                 }
                 if (ok) break;
                 count++;
         }
         if (debug) {
                 printf("VEs have stopped, stlist =");
                 for (int i = 0; i < nve; i++) printf(" %d", stlist[i]);
                 printf("\n");
         }
         /* step 6: collect sent packets */
         for (int i = 0; i < nve; i++) if (rllist[i])
         {
                 for (int j = 0; j < ve[i]->nif; j++)
                 {
                         ve[i]->nowif = j;
                         while (pcap_dispatch((pcap_t*)ve[i]->pcap[j],
                                         -1, got_packet, (u_char*)ve[i]) > 0)
                                 stlist[i] = VTIME_SUSPENDED;
                         while (pktcount[i] < (int)ve[i]->sendq.size())
{
                                 EmuPacket *ppkt = ve[i]->sendq[pktcount[i]++];
 #ifdef SLAVE_LOG
                                 fprintf(pfslave, "%ld.%06ld\tve%d\tsend\t%d\n",
                                         ppkt->timestamp/1000000, ppkt->timestamp%1000000,
                                         ve[i]->id, ppkt->len);
 #endif
                                 AsyncMessage *pktmsg= new AsyncMessage;
                                 pktmsg->type = AsyncMessage::PACKET;
                                 pktmsg->time = ppkt->timestamp;
                                 pktmsg->int1 = ve[i]->id;
                                 pktmsg->int2 = ve[i]->nowif;
                                 pktmsg->resize(ppkt->len);
                                 memcpy(pktmsg->payload, ppkt->data, ppkt->len);
                                 ret = ((AsyncMessageHandler*)amh)->amh_send(pktmsg);
                                 delete pktmsg;
                                 if (ret) return ret;
                         }
                 }
         }
         /* step 7: collect timers */
         for (int i = 0; i < nve; i++) if (rllist[i])
         {
                 int n;
                 if (vtime_gettraplist(ve[i]->id, &n, trlist)) return -EINTR;
                 for (int j = 0; j < n; j++)
                         if (trlist[j].type == VTIME_TRAPTIMER &&
                             trlist[j].data[0] > 0 && trlist[j].data[0] < 1000000)
{
                                 EmuTimer timer;
                                 timer.pid = trlist[j].pid;
                                 timer.due = (trlist[j].data[0] +
                                              trlist[j].time.tv_sec) * 1000000 +
                                         trlist[j].data[1] + trlist[j].time.tv_usec;
                                 timer.repeat = trlist[j].data[2]*1000000 +
                                         trlist[j].data[3];
                                 ve[i]->timerq.push(timer);
                         }
                         else if (trlist[j].type == VTIME_TRAPSLEEP &&
                                 trlist[j].data[0] > 0 && trlist[j].data[0] < 1000000)
{
                                 EmuTimer timer;
                                 timer.pid = 0;
                                 timer.due = trlist[j].data[0]*1000000 + trlist[j].data[1];
                                 timer.repeat = 0;
                                 ve[i]->timerq.push(timer);
                         }
                 /* release all traps */
                 for (int j = 0; j < n; j++) rtlist[j] = 1;
                 if (vtime_releasetrap(ve[i]->id, n, rtlist)) return -EINTR;
         }
         /* step 8: update VE clocks */
         for (int i = 0; i < nve; i++) if (rllist[i]) {
                 if (vtime_getclock(ve[i]->id, &tv)) return -EINTR;
                 ve[i]->lastclock = ve[i]->clock;
                 ve[i]->clock = tv.tv_sec*1000000 + tv.tv_usec;
                 if (debug) printf("VE%d clock=%ld lastc=%ld run=%ld\n", ve[i]->id,
                                 ve[i]->clock, ve[i]->lastclock, ve[i]->clock-ve[i]->lastclock);
                 if (stlist[i] != VTIME_IDLE)
                         ve[i]->avgrun = (9 * ve[i]->avgrun +
                                         (ve[i]->clock - ve[i]->lastclock)) / 10;
         }
 STEP9:
         /* step 9: adjust VEs virtual clocks */
         alldone = true;
         for (int i = 0; i < nve; i++) if (!done[i])
         {
                 ltime_t adjbarrier = barrier - ve[i]->offset - ve[i]->avgrun/2;
                 if (debug) printf("VE%d offset=%ld avgrun=%ld adjbarrier=%ld\n",
                                 ve[i]->id, ve[i]->offset, ve[i]->avgrun, adjbarrier);
                 /* quick advance VE when idle */
                 if (stlist[i] == VTIME_IDLE)
                 {
                         ve[i]->idle = true;
                         ve[i]->idlecount++;
                         ltime_t next = min(maxadv, ve[i]->clock + VTIME_VTIMESLICE), ts;
                         if (!ve[i]->recvq.empty() &&
                             (ts = ve[i]->recvq.front()->timestamp) < adjbarrier)
                                 if (next < 0 || ts < next) next = ts;
                         if (!ve[i]->timerq.empty() &&
                             (ts = ve[i]->timerq.top().due) < adjbarrier)
                                 if (next < 0 || ts < next) next = ts;
                         if (next > ve[i]->clock) {
                                 struct timeval tvnext;
                                 tvnext.tv_sec = next / 1000000;
                                 tvnext.tv_usec = next % 1000000;
                                 if (vtime_setclock(ve[i]->id, &tvnext)) return -EINTR;
                                 if (debug) printf("VE%d idle advance to %ld\n",
                                                 ve[i]->id, next);
                                 ve[i]->offset = 0;
                                 ve[i]->lastclock = ve[i]->clock = next;
                         }
                 }
                 else {
                         ve[i]->idle = false;
                 }
                 /* VE has done current cycle */
                 if (ve[i]->clock >= adjbarrier)
                 {
                         if (debug) printf("VE%d reached barrier\n", ve[i]->id);
                         if (vtime_setclock(ve[i]->id, &tvbarrier)) return -EINTR;
                         if (stlist[i] != VTIME_IDLE) ve[i]->offset += ve[i]->clock - barrier;
                                 else ve[i]->offset = 0;
                         ve[i]->lastclock = ve[i]->clock = barrier;
                         done[i] = true;
                         onedone = true;
                         ndone++;
                 }
                 else
                         alldone = false;
         }
         if (debug && !debug_nopause) {
                 printf("press enter to continue\n");
                 char line[100];
                 fgets(line, 100, stdin);
                 if (strcmp(line, "exit") == 0) debug_nopause = true;
         }
         if (!alldone && again) goto STEP3;
         if (!alldone) goto EXIT;
         /* step 10: lookahead post_cycle for all VEs */
         if (la_type) {
                 if (nthread == 1)
                 {
                         for (int i = 0; i < nve; i++) {
                                 if (ve[i]->la) ((Lookahead*)ve[i]->la)->post_cycle(barrier);
                                 else ve[i]->lookahead = 0;
                         }
                 }
                 else
                 {
                         /* use multi-thread to accelerate */
                         vector<pthread_t> tid(nthread);
                         void *status;
                         for (int i = 0; i < nthread; i++)
                                 if (pthread_create(&tid[i], NULL, la_postcycle_thread, (void*)i))
                                         gotofail(-ECHILD);
                         for (int i = 0; i < nthread; i++)
                                 if (pthread_join(tid[i], &status)) gotofail(-ECHILD);
                 }
 #ifdef TIME_STAT
                 ltime_t minla = -1, totalla = 0;
                 for (int i = 0; i < nve; i++) {
                         if (minla < 0 || ve[i]->lookahead < minla) minla = ve[i]->lookahead;
                         totalla += ve[i]->lookahead;
                 }
                 if (!timestat_counter) timestat_update(avgminla, minla);
                 if (!timestat_counter) timestat_update(avgla, totalla / nve);
 #endif
         }
         /* empty sendq */
         for (int i = 0; i < nve; i++)
                 while (!ve[i]->sendq.empty()) {
                         EmuPacket *ppkt = ve[i]->sendq.front();
                         ve[i]->sendq.pop_front();
                         delete ppkt;
                 }
 #ifdef TIME_STAT
         timestat_counter = (timestat_counter + 1) % timestat_interval;
         if (!timestat_counter)
         {
                 gettimeofday(&tstv2, NULL);
                 int elapse = VTIME_CLOCKDIFFU(tstv2, lastprint);
                 if (elapse > 1000000)
                 {
                         double speed = (double)(barrier - lastvtime) / elapse;
                         lastprint = tstv2;
                         lastvtime = barrier;
                         fprintf(stderr, "vtime=%d.%03d speed=%.3f",
                                 (int)(barrier/1000000), (int)(barrier%1000000/1000), speed);
                         if (la_type) {
                                 double err = 0.0;
                                 for (int i = 0; i < nve; i++)
                                         err += ((Lookahead*)ve[i]->la)->get_error();
                                 err /= nve;
                                 laerr = (int)(err * 10000);
                                 fprintf(stderr, " err=%.0f%% avgla=%.0f avgminla=%.0f",
                                         err*100, avgla, avgminla);
                         }
                         fprintf(stderr, "\n");
                 }
         }
 #endif
 EXIT:
         if (debug) printf("----- cycle done -----\n");
         /* reply message */
         reply = new AsyncMessage;
         reply->type = AsyncMessage::SUCC;
         reply->int1 = ndone;
         reply->int2 = laerr;
         reply->resize(nve * sizeof(ltime_t));
         p = (ltime_t*) reply->payload;
         for (int i = 0; i < nve; i++, p++)
                 *p = alldone ? ve[vemap[i]]->lookahead : ve[vemap[i]]->clock;
         ret = ((AsyncMessageHandler*)amh)->amh_send(reply);
         delete reply;
         return ret;
 FAIL:
         reply = new AsyncMessage;
         reply->type = AsyncMessage::FAIL;
         reply->int1 = reason;
         ret = ((AsyncMessageHandler*)amh)->amh_send(reply);
         delete reply;
         return ret;
 }
Member Data Documentation
char* VESlave::addr
ip address of the slave
Definition at line 63 of file dsimctrl.h.
Referenced by master_connect(), VESlave(), and ~VESlave().
int VESlave::fromid
start VE ID of this slave (static range)
Definition at line 66 of file dsimctrl.h.
int VESlave::toid
end VE ID of this slave (static range)
Definition at line 69 of file dsimctrl.h.
Referenced by master_init().
int VESlave::idoffset
VE ID offset (veid_on_slave = veid_on_host - veid_offset)
Definition at line 72 of file dsimctrl.h.
Referenced by master_cycle_gotmsg(), master_exec(), master_fini(), master_init(), master_pushpacket(), and master_setip().
bool VESlave::selected
flag: is this slave selected? (for master side use)
Definition at line 75 of file dsimctrl.h.
Referenced by VESlave().
int VESlave::idbase
start VE ID being selected of this emulation setup
Definition at line 78 of file dsimctrl.h.
Referenced by DSimCtrl::emu_init(), master_cycle_gotmsg(), master_exec(), master_fini(), master_init(), master_setip(), slave_gotmsg_fini(), slave_gotmsg_init(), and slave_gotmsg_packet().
int VESlave::nve
total number of VEs being selected in this emulation setup
Definition at line 81 of file dsimctrl.h.
Referenced by DSimCtrl::emu_init(), la_postcycle_thread(), master_cycle_gotmsg(), master_exec(), master_fini(), master_init(), master_pushpacket(), master_setip(), master_test(), slave_gotmsg_cycle(), slave_gotmsg_fini(), slave_gotmsg_init(), slave_gotmsg_test(), and VESlave().
vector<VEHandle*> VESlave::ve
VE handles.
Definition at line 84 of file dsimctrl.h.
Referenced by DSimCtrl::emu_init(), la_postcycle_thread(), master_cycle_gotmsg(), master_pushpacket(), slave_gotmsg_cycle(), slave_gotmsg_fini(), slave_gotmsg_init(), and slave_gotmsg_packet().
vector<int> VESlave::vemap
VE mapping.
Definition at line 87 of file dsimctrl.h.
Referenced by slave_gotmsg_cycle(), slave_gotmsg_fini(), slave_gotmsg_init(), and slave_gotmsg_packet().
vector<int> VESlave::venif
number of interfaces of all VEs
Definition at line 90 of file dsimctrl.h.
Referenced by DSimCtrl::emu_init(), master_init(), and slave_gotmsg_init().
vector<int> VESlave::pktcount
number of packets pushed to master
Definition at line 93 of file dsimctrl.h.
Referenced by slave_gotmsg_cycle(), and slave_gotmsg_init().
vector<bool> VESlave::done
for simctrl cycle use
Definition at line 96 of file dsimctrl.h.
Referenced by slave_gotmsg_cycle(), and slave_gotmsg_init().
int VESlave::la_type
type of app lookahead algorithm
Definition at line 99 of file dsimctrl.h.
Referenced by DSimCtrl::emu_init(), master_init(), slave_gotmsg_cycle(), and slave_gotmsg_init().
bool VESlave::onedone
flag: at least one VE reaches the barrier?
Definition at line 102 of file dsimctrl.h.
Referenced by master_cycle_gotmsg(), and slave_gotmsg_cycle().
bool VESlave::alldone
flag: all VEs reach the barrier?
Definition at line 105 of file dsimctrl.h.
Referenced by master_cycle_gotmsg(), and slave_gotmsg_cycle().
bool VESlave::newbarrier
flag: has the barrier been updated since last call?
Definition at line 108 of file dsimctrl.h.
Referenced by master_cycle(), and slave_gotmsg_cycle().
int VESlave::ndone
number of finished VEs
Definition at line 111 of file dsimctrl.h.
Referenced by master_cycle_gotmsg(), and slave_gotmsg_cycle().
ltime_t VESlave::barrier
barrier given by S3F/S3FNet
Definition at line 114 of file dsimctrl.h.
Referenced by la_postcycle_thread(), master_cycle(), master_cycle_gotmsg(), and slave_gotmsg_cycle().
ltime_t VESlave::maxadv
barrier to release VE safely, subject to mindelay constrains
Definition at line 117 of file dsimctrl.h.
Referenced by master_cycle(), and slave_gotmsg_cycle().
struct timeval VESlave::tvbarrier
timeval representation of barrier
Definition at line 120 of file dsimctrl.h.
Referenced by slave_gotmsg_cycle().
int VESlave::nthread
multi-thread number for lookahead prediction
Definition at line 123 of file dsimctrl.h.
Referenced by la_postcycle_thread(), main(), slave_gotmsg_cycle(), and VESlave().
int VESlave::laerr
lookahead error
Definition at line 126 of file dsimctrl.h.
Referenced by DSimCtrl::emu_init(), master_cycle_gotmsg(), slave_gotmsg_cycle(), and VESlave().
state_t VESlave::state private
current state of master
Definition at line 175 of file dsimctrl.h.
Referenced by master_checkstatus(), master_connect(), master_cycle(), master_cycle_gotmsg(), master_disconnect(), master_exec(), master_exec_gotmsg(), master_fini(), master_fini_gotmsg(), master_init(), master_init_gotmsg(), master_setip(), master_setip_gotmsg(), master_test(), master_test_gotmsg(), and VESlave().
void* VESlave::amh private
asynchronous message handler for master-slave communication
Definition at line 178 of file dsimctrl.h.
Referenced by master_checkstatus(), master_connect(), master_cycle(), master_disconnect(), master_exec(), master_fini(), master_init(), master_pushpacket(), master_setip(), master_test(), slave_gotmsg_cycle(), slave_gotmsg_exec(), slave_gotmsg_fini(), slave_gotmsg_init(), slave_gotmsg_setip(), slave_gotmsg_test(), slave_mainloop(), VESlave(), and ~VESlave().
bool VESlave::isinit private
has init been called?
Definition at line 181 of file dsimctrl.h.
Referenced by master_connect(), master_cycle(), master_exec(), master_fini_gotmsg(), master_init(), master_init_gotmsg(), master_setip(), master_test(), slave_gotmsg_fini(), slave_gotmsg_init(), and VESlave().
The documentation for this class was generated from the following files:
dsimctrl.h
dsimctrl.cc