S3F: s3f::s3fnet::OpenVZEventSession Class Reference
s3f::s3fnet::OpenVZEventSession Class Reference
A protocol layer to interact with the associated OpenVZ-based VE.
#include <openVZEmu_event_session.h>
Public Types
enum InstantiationType { PROT_UNIQUE_INSTANCE = 0x00, PROT_MULTIPLE_INSTANCES = 0x01, PROT_MULTIPLE_IMPLEMENTATIONS = 0x02 }
Multiple protocol session instantiation type.
enum ExecutionStage { PSESS_CREATED = 0, PSESS_CONFIGURED = 1, PSESS_INITIALIZED = 2, PSESS_WRAPPED_UP = 3 }
A normal protocol session must go though the following stages.
Public Member Functions
OpenVZEventSession (ProtocolGraph *graph)
the constructor
virtual ~OpenVZEventSession ()
the destructor
virtual int getProtocolNumber ()
Return the protocol number.
virtual void config (s3f::dml::Configuration *cfg)
called to configure this protocol session
virtual void init ()
called after config() to initialize this protocol session
virtual int control (int ctrltyp, void *ctrlmsg, ProtocolSession *sess)
called by other protocol sessions to send special control messages
virtual int push (Activation msg, ProtocolSession *hi_sess, void *extinfo=0, size_t extinfo_size=0)
Handle packet reception from the VE.
virtual int pop (Activation msg, ProtocolSession *lo_sess, void *extinfo=0, size_t extinfo_size=0)
Handle packet transmission to the VE.
void callback (Activation)
the callback function registered with the callback_proc
void callback_body (EmuPacket *, IPADDR, IPADDR)
the actual body of the callback function
void injectEvent (IPADDR dst_ip, IPADDR src_ip, EmuPacket *ppkt, int priority)
Inject an openvz-based emulation packet into the s3fnet simulator.
virtual void wrapup ()
The method is used to wrap up the protocol session.
int pushdown (Activation msg, ProtocolSession *hi_sess, void *extinfo=0, size_t extinfo_size=0)
The original push method is divided into pushdown() and push().
int popup (Activation msg, ProtocolSession *lo_sess, void *extinfo=0, size_t extinfo_size=0)
The original pop method is divided into popup() and pop().
ProtocolGraph * inGraph ()
The method returns the protocol graph in which this protocol session resides.
virtual Host * inHost ()
Return a pointer to the host owning this protocol session.
Random::RNG * getRandom ()
The method returns a pointer to the random number generator.
ltime_t getNow ()
The method returns the current simulation time.
char * getNowWithThousandSeparator ()
For printing the current simulation time in a better readable format.
int configured ()
This method returns true if the protocol session has been configured.
int initialized ()
This method returns true if the protocol session has been initialized.
int wrapped_up ()
This method returns true if the protocol session has been wrapped up.
virtual const char * psesstype ()
Public Attributes
Process * callback_proc
the S3F process used by waitFor() function in the OpenVZEventSession protocol, provide call_back functionality
ProtocolCallbackActivation * dcac
Storing the data for the callback function.
IPSession * ip_session
the IP layer below this protocol
long int pkt_to_ve_counter
store the total number of packet output to VE
char * name
Symbolic name of the protocol this session implements.
float version
Version number of this protocol implemenntation, represented as a floating point number (e.g., 1.23).
char * use
Name of the protocol class from which this protocol session is instantiated.
Protected Member Functions
virtual int instantiation_type ()
This method controls how protocol instances can coexist with one another.
Protected Attributes
ProtocolGraph * ingraph
Points to the protocol graph.
Random::RNG * sess_rng
Pointer to a random number generator.
int stage
This variable indicates the current stage of this protocol session.
Detailed Description
A protocol layer to interact with the associated OpenVZ-based VE.
In particular, transmit and receive emulation packet from/to the VE.
Definition at line 26 of file openVZEmu_event_session.h.
Member Enumeration Documentation
enum s3f::s3fnet::ProtocolSession::InstantiationType inherited
Multiple protocol session instantiation type.
Enumerator
PROT_UNIQUE_INSTANCE
PROT_MULTIPLE_INSTANCES
PROT_MULTIPLE_IMPLEMENTATIONS
Definition at line 44 of file protocol_session.h.
{
     PROT_UNIQUE_INSTANCE                = 0x00,
     PROT_MULTIPLE_INSTANCES             = 0x01,
     PROT_MULTIPLE_IMPLEMENTATIONS       = 0x02
   };
enum s3f::s3fnet::ProtocolSession::ExecutionStage inherited
A normal protocol session must go though the following stages.
Enumerator
PSESS_CREATED
this protocol session has just been created
PSESS_CONFIGURED
the config method of this protocol session has been called
PSESS_INITIALIZED
the init method of this protocol session has been called
PSESS_WRAPPED_UP
Definition at line 51 of file protocol_session.h.
                       {
     PSESS_CREATED       = 0,
     PSESS_CONFIGURED    = 1,
     PSESS_INITIALIZED   = 2,
     PSESS_WRAPPED_UP    = 3
   };
Constructor & Destructor Documentation
s3f::s3fnet::OpenVZEventSession::OpenVZEventSession (ProtocolGraph * graph)
the constructor
Definition at line 36 of file openVZEmu_event_session.cc.
References OPENVZ_EVENT_DUMP.
                                                            : ProtocolSession(graph),
                 pkt_to_ve_counter(0), ip_session(0), dcac(0), callback_proc(0)
 {
         // create your session-related variables here
         OPENVZ_EVENT_DUMP(printf("An OpenVZ EVENT protocol session is created.\n"));
 }
s3f::s3fnet::OpenVZEventSession::~OpenVZEventSession () virtual
the destructor
Definition at line 43 of file openVZEmu_event_session.cc.
References OPENVZ_EVENT_DUMP.
 {
         // reclaim your session-related variables here
         OPENVZ_EVENT_DUMP(printf("An OpenVZ EVENT protocol session is reclaimed.\n"));
         //printf("#packet out to VE = %ld\n", pkt_to_ve_counter);
 }
Member Function Documentation
virtual int s3f::s3fnet::OpenVZEventSession::getProtocolNumber () inline virtual
Return the protocol number.
This protocol number will be stored as the index to the protocol graph. Each protocol must have a unique protocol number
Implements s3f::s3fnet::ProtocolSession.
Definition at line 40 of file openVZEmu_event_session.h.
References s3f::s3fnet::S3FNET_PROTOCOL_TYPE_OPENVZ_EVENT.
 { return S3FNET_PROTOCOL_TYPE_OPENVZ_EVENT; }
void s3f::s3fnet::OpenVZEventSession::config (s3f::dml::Configuration * cfg) virtual
called to configure this protocol session
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 51 of file openVZEmu_event_session.cc.
References s3f::s3fnet::ProtocolSession::config(), and s3f::s3fnet::error_quit().
 {
 #ifndef OPENVZ_EMULATION
         error_quit("OPENVZ_EMULATION is not defined, but DML file contains OpenVZEventSession layer.");
 #endif
         // the same method at the parent class must be called
         ProtocolSession::config(cfg);
 }
void s3f::s3fnet::OpenVZEventSession::init () virtual
called after config() to initialize this protocol session
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 60 of file openVZEmu_event_session.cc.
References callback(), callback_proc, s3f::s3fnet::error_quit(), s3f::s3fnet::Host::getNetworkLayerProtocol(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::ProtocolSession::init(), ip_session, and OPENVZ_EVENT_DUMP.
 {
         // the same method at the parent class must be called
         ProtocolSession::init();
         // initialize the session-related variables here
         OPENVZ_EVENT_DUMP(printf("OpenVZ EVENT protocol session is initialized.\n"));
         // we couldn't resolve the IP layer until now
         ip_session = (IPSession*)inHost()->getNetworkLayerProtocol();
         if(!ip_session) error_quit("ERROR: can't find the IP layer; impossible!");
         Host* owner_host = inHost();
         callback_proc = new Process( (Entity *)owner_host, (void (s3f::Entity::*)(s3f::Activation))&OpenVZEventSession::callback);
 }
int s3f::s3fnet::OpenVZEventSession::control (int ctrltyp, void * ctrlmsg, ProtocolSession * sess) virtual
called by other protocol sessions to send special control messages
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 140 of file openVZEmu_event_session.cc.
References s3f::s3fnet::ProtocolSession::control().
 {
         switch(ctrltyp)
         {
         default:
                 return ProtocolSession::control(ctrltyp, ctrlmsg, sess);
         }
 }
int s3f::s3fnet::OpenVZEventSession::push (Activation msg, ProtocolSession * hi_sess, void * extinfo = 0, size_t extinfo_size = 0) virtual
Handle packet reception from the VE.
Called by the protocol session above to push a protocol message down the protocol stack
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 149 of file openVZEmu_event_session.cc.
References s3f::s3fnet::error_quit().
 {
         error_quit("ERROR: a message is pushed down to the openvz event input session from protocol layer above; it's impossible.\n");
         return 0;
 }
int s3f::s3fnet::OpenVZEventSession::pop (Activation msg, ProtocolSession * lo_sess, void * extinfo = 0, size_t extinfo_size = 0) virtual
Handle packet transmission to the VE.
Called by the protocol session below to pop a protocol message up the protocol stack.
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 155 of file openVZEmu_event_session.cc.
References EmuPacket::data, s3f::s3fnet::IPOptionToAbove::dst_ip, s3f::s3fnet::ProtocolSession::getNow(), s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::Host::getTopNet(), s3f::s3fnet::Host::getVEID(), s3f::s3fnet::OpenVZMessage::ifid, EmuPacket::ifid, s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::IPPrefix::ip2txt(), s3f::s3fnet::Host::isOpenVZEmu(), EmuPacket::len, OPENVZ_EVENT_DUMP, pkt_to_ve_counter, s3f::s3fnet::OpenVZMessage::ppkt, s3f::s3fnet::IPOptionToAbove::src_ip, and EmuPacket::timestamp.
 {
         OPENVZ_EVENT_DUMP(printf("A message is popped up to the openVZ EVENT session from the IP layer.\n"));
         // the protocol message must be of OpenVZMessage type, and the extra info must be of IPOptionToAbove type
         OpenVZMessage* omsg = (OpenVZMessage*)msg;
         IPOptionToAbove* ipopt = (IPOptionToAbove*)extinfo;
         OPENVZ_EVENT_DUMP(char buf1[32]; char buf2[32];
         printf("[%s] OpenVZ EVENT session receives packet: \"%s\" with length %d (ip_src=%s, ip_dest=%s)\n",
                         getNowWithThousandSeparator(), omsg->ppkt->data, omsg->ppkt->len,
                         IPPrefix::ip2txt(ipopt->src_ip, buf1), IPPrefix::ip2txt(ipopt->dst_ip, buf2)); );
 #ifdef OPENVZ_EMULATION
         //deliver packet to openVZ VE if the host is mapped to one
         if(inHost()->isOpenVZEmu() == true)
         {
                 EmuPacket* ppkt = omsg->ppkt;
                 ppkt->timestamp = getNow();
                 ppkt->ifid = omsg->ifid;
                 inHost()->getTopNet()->ve[inHost()->getVEID()]->recvq.push_back(ppkt);
                 pkt_to_ve_counter++;
         }
 #endif
         // returning 0 indicates success
         return 0;
 }
void s3f::s3fnet::OpenVZEventSession::callback (Activation ac)
the callback function registered with the callback_proc
Definition at line 108 of file openVZEmu_event_session.cc.
References callback_body().
Referenced by init().
 {
         OpenVZEventSession* sess =
                         (OpenVZEventSession*)((OpenVZEventSessionCallbackActivation*)ac)->session;
         EmuPacket* packet = ((OpenVZEventSessionCallbackActivation*)ac)->packet;
         IPADDR dst_ip = ((OpenVZEventSessionCallbackActivation*)ac)->dst_ip;
         IPADDR src_ip = ((OpenVZEventSessionCallbackActivation*)ac)->src_ip;
         sess->callback_body(packet, dst_ip, src_ip);
 }
void s3f::s3fnet::OpenVZEventSession::callback_body (EmuPacket * ppkt, IPADDR dst_ip, IPADDR src_ip)
the actual body of the callback function
Definition at line 118 of file openVZEmu_event_session.cc.
References DEFAULT_IP_TIMETOLIVE, s3f::s3fnet::IPPushOption::dst_ip, s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::IPPushOption::iface_id, EmuPacket::ifid, s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::IPPrefix::ip2txt(), ip_session, EmuPacket::len, OPENVZ_EVENT_DUMP, s3f::s3fnet::IPPushOption::prot_id, s3f::s3fnet::ProtocolSession::pushdown(), s3f::s3fnet::S3FNET_PROTOCOL_TYPE_OPENVZ_EVENT, s3f::s3fnet::IPPushOption::src_ip, and s3f::s3fnet::IPPushOption::ttl.
Referenced by callback().
 {
         OpenVZMessage* msg = new OpenVZMessage(ppkt);
         Activation msg_ac (msg);
         //ip session will add src ip
         /* todo: ipopt is no needed in pure emulation case, only iface_id is needed, keep it just in case the design changes later */
         IPPushOption ipopt;
         ipopt.dst_ip = dst_ip;
         ipopt.src_ip = src_ip;
         ipopt.prot_id = S3FNET_PROTOCOL_TYPE_OPENVZ_EVENT;
         ipopt.ttl = DEFAULT_IP_TIMETOLIVE;
         ipopt.iface_id = ppkt->ifid;
         OPENVZ_EVENT_DUMP(printf("[%s] [host=%s] OpenVZEventSession::callback(), "
                         "send a packet, dst_ip = %s, len = %d.\n",
                         getNowWithThousandSeparator(), inHost()->nhi.toString(),
                         IPPrefix::ip2txt(dst_ip), ppkt->len));
         ip_session->pushdown(msg_ac, this, (void*)&ipopt, sizeof(IPPushOption));
 }
void s3f::s3fnet::OpenVZEventSession::injectEvent (IPADDR dst_ip, IPADDR src_ip, EmuPacket * ppkt, int priority)
Inject an openvz-based emulation packet into the s3fnet simulator.
Schedule an waitFor() event for the packet receiving event.
Definition at line 76 of file openVZEmu_event_session.cc.
References callback_proc, s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolSession::getNow(), s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), EmuPacket::ifid, s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::IPPrefix::ip2txt(), EmuPacket::len, OPENVZ_EVENT_DUMP, EmuPacket::timestamp, and Entity::waitFor().
 {
         OpenVZEventSessionCallbackActivation* oac = new OpenVZEventSessionCallbackActivation(this, dst_ip, src_ip, ppkt);
         Activation ac (oac);
         //schedule to send a packet
         Host* owner_host = inHost();
         ltime_t wait_time = ppkt->timestamp - getNow();
 #ifdef OPENVZ_EMULATION_LOOKAHEAD
         //due to the new design of lookahead, it is possible that past emulation events are injected into simulator
         if(wait_time < 0) wait_time = 0;
         HandleCode h = owner_host->waitFor( callback_proc, ac, wait_time, priority);
 #else
         if(wait_time >= 0)
         {
                 HandleCode h = owner_host->waitFor( callback_proc, ac, wait_time, priority);
         }
         else
         {
                 error_quit("inject an event whose time is in the past\n");
         }
 #endif
         OPENVZ_EVENT_DUMP(char s1[50]; char s2[50];
         printf("[%s] [host=%s] OpenVZEventSession::injectEvent(), "
                         "inject an event src_ip = %s, dst_ip = %s, len = %d, "
                         "sending_time = %ld, iface_id = %d\n",
                         getNowWithThousandSeparator(), inHost()->nhi.toString(),
                         IPPrefix::ip2txt(src_ip, s2), IPPrefix::ip2txt(dst_ip, s1),
                         ppkt->len, ppkt->timestamp, ppkt->ifid));
 }
void s3f::s3fnet::ProtocolSession::wrapup () virtual inherited
The method is used to wrap up the protocol session.
It is called when the simulation finishes. It is designed to give user a chance to report simulation statistics. The default behavior is doing nothing. Subclass may override this method for protocol specific dealings. Note that there is no specific order in which wrapup is called for protocol sessions in a protocol graph.
Definition at line 59 of file protocol_session.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolSession::initialized(), s3f::s3fnet::ProtocolSession::name, s3f::s3fnet::ProtocolSession::PSESS_WRAPPED_UP, s3f::s3fnet::ProtocolSession::stage, and s3f::s3fnet::ProtocolSession::wrapped_up().
 {
   // Make sure this init function at the base class should be called
   // by the derived function!
   if(!initialized())
     error_quit("ERROR: ProtocolSession \"%s\" wrapup() called before init(), "
                "forgot to call base class's init() in your derived class?\n", name);
   else if(wrapped_up())
     error_quit("ERROR: duplicate calls to ProtocolSession::wrapup(): "
                "session name is \"%s\".\n", name);
   else stage = PSESS_WRAPPED_UP;
 }
int s3f::s3fnet::ProtocolSession::pushdown (Activation msg, ProtocolSession * hi_sess, void * extinfo = 0, size_t extinfo_size = 0) inherited
The original push method is divided into pushdown() and push().
The pushdown method is the generic part of the code, which is reserved for modeling the handling of messages transferred between protocol layers.
See Also
ProtocolSession::push method for details.
Definition at line 72 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::push().
Referenced by s3f::s3fnet::DummySession::callback_body(), callback_body(), s3f::s3fnet::IPSession::control(), s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), s3f::s3fnet::OpenFlowSwitchSession::OutputControl(), s3f::s3fnet::OpenFlowSwitchSession::OutputPacket(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::UDPMaster::push(), s3f::s3fnet::TCPMaster::push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::send(), and s3f::s3fnet::TCPSession::send_data().
 {
   return push(msg, hi_sess, extinfo, extinfo_size);
 }
int s3f::s3fnet::ProtocolSession::popup (Activation msg, ProtocolSession * lo_sess, void * extinfo = 0, size_t extinfo_size = 0) inherited
The original pop method is divided into popup() and pop().
The popup method is the generic part of the code, which is reserved for modeling the handling of messages transferred between protocol layers.
See Also
ProtocolSession::pop method for details.
Definition at line 77 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::pop().
Referenced by s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::IPSession::push(), and s3f::s3fnet::SimplePhy::receivePacket().
 {
   return pop(msg, lo_sess, extinfo, extinfo_size);
 }
ProtocolGraph* s3f::s3fnet::ProtocolSession::inGraph () inline inherited
The method returns the protocol graph in which this protocol session resides.
Definition at line 178 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::ingraph.
Referenced by s3f::s3fnet::SimplePhy::config(), s3f::s3fnet::SimplePhy::control(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::SimpleMac::init(), s3f::s3fnet::SimplePhy::init(), s3f::s3fnet::RedQueue::init(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::SimplePhy::push(), s3f::s3fnet::SimplePhy::receivePacket(), s3f::s3fnet::SimplePhy::sendPacket(), s3f::s3fnet::SimpleMac::SimpleMac(), s3f::s3fnet::SimplePhy::SimplePhy(), s3f::s3fnet::SimpleMac::~SimpleMac(), and s3f::s3fnet::SimplePhy::~SimplePhy().
 { return ingraph; }
Host * s3f::s3fnet::ProtocolSession::inHost () virtual inherited
Return a pointer to the host owning this protocol session.
Reimplemented in s3f::s3fnet::NicProtocolSession.
Definition at line 118 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::ingraph.
Referenced by s3f::s3fnet::UDPSession::abort(), s3f::s3fnet::SocketMaster::abort(), s3f::s3fnet::NBSocketMaster::abort(), s3f::s3fnet::SocketMaster::accept(), s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::accept1a(), s3f::s3fnet::SocketMaster::accept1b(), s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SocketMaster::accept2b(), s3f::s3fnet::OpenFlowSwitchSession::AddFlow(), s3f::s3fnet::TCPSession::backoff_timeout(), s3f::s3fnet::SocketMaster::bind(), s3f::s3fnet::NBSocketMaster::bind(), s3f::s3fnet::SocketMaster::block_till(), s3f::s3fnet::NBSocketMaster::block_till(), s3f::s3fnet::BTCPClientSession::BTCPClientSession(), s3f::s3fnet::OpenFlowSwitchSession::BufferFromPacket(), s3f::s3fnet::DummySession::callback_body(), callback_body(), s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::UDPServerSession::client_connected(), s3f::s3fnet::SocketMaster::close(), s3f::s3fnet::NBSocketMaster::close(), s3f::s3fnet::SocketMaster::close1(), s3f::s3fnet::NBSocketMaster::close1(), s3f::s3fnet::UDPMaster::config(), s3f::s3fnet::DummySession::config(), s3f::s3fnet::TCPClientSession::config(), s3f::s3fnet::UDPServerSession::config(), s3f::s3fnet::UDPClientSession::config(), s3f::s3fnet::TCPServerSession::config(), s3f::s3fnet::TCPMaster::config(), s3f::s3fnet::NBTCPClientSession::config(), s3f::s3fnet::BTCPClientSession::config(), s3f::s3fnet::IPSession::config(), s3f::s3fnet::NBTCPServerSession::config(), s3f::s3fnet::UDPSession::connect(), s3f::s3fnet::SocketMaster::connect(), s3f::s3fnet::NBSocketMaster::connect(), s3f::s3fnet::SocketMaster::connect1(), s3f::s3fnet::NBSocketMaster::connect1(), s3f::s3fnet::SocketMaster::connected(), s3f::s3fnet::NBSocketMaster::connected(), s3f::s3fnet::UDPMaster::control(), s3f::s3fnet::SocketMaster::control(), s3f::s3fnet::NBSocketMaster::control(), s3f::s3fnet::IPSession::control(), s3f::s3fnet::TCPMaster::createSession(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::UDPServerSession::data_sent(), s3f::s3fnet::TCPServerSession::data_sent(), s3f::s3fnet::UDPSession::disconnect(), s3f::s3fnet::TCPMaster::enableFastTimeout(), s3f::s3fnet::SocketMaster::eof(), s3f::s3fnet::NBSocketMaster::eof(), s3f::s3fnet::UDPClientSessionContinuation::failure(), s3f::s3fnet::UDPServerSessionContinuation::failure(), s3f::s3fnet::TCPServerSessionContinuation::failure(), s3f::s3fnet::TCPClientSessionContinuation::failure(), s3f::s3fnet::BTCPClientSessionContinuation::failure(), s3f::s3fnet::TCPMaster::fast_timer_callback_body(), s3f::s3fnet::Stats::FlowStatsDump(), s3f::s3fnet::OpenFlowSwitchSession::FlowTableLookup(), s3f::s3fnet::IPSession::get_parent_by_protocol(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::ProtocolSession::getNow(), s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::OpenFlowSwitchSession::HandleControlInput(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), s3f::s3fnet::DummySession::init(), s3f::s3fnet::UDPMaster::init(), s3f::s3fnet::OpenFlowControllerSession::init(), init(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPServerSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::TCPServerSession::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::OpenFlowSwitchSession::init(), s3f::s3fnet::NBTCPClientSession::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::SocketMaster::init(), s3f::s3fnet::IPSession::init(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::NBSocketMaster::init(), s3f::s3fnet::NBTCPServerSession::init(), s3f::s3fnet::TCPSession::init_state_closed(), injectEvent(), s3f::s3fnet::IPSession::IPSession(), s3f::s3fnet::UDPSession::listen(), s3f::s3fnet::SocketMaster::listen(), s3f::s3fnet::NBSocketMaster::listen(), s3f::s3fnet::IPSession::load_forwarding_table(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), s3f::s3fnet::OpenFlowSwitchSession::ModFlow(), s3f::s3fnet::NBSocketMaster::NBSocketMaster(), s3f::s3fnet::NBTCPClientSession::NBTCPClientSession(), s3f::s3fnet::NBTCPServerSession::NBTCPServerSession(), s3f::s3fnet::NBTCPClientSession::non_blocking_loop(), s3f::s3fnet::NBTCPServerSession::non_blocking_loop(), s3f::s3fnet::OpenFlowSwitchSession::OutputControl(), s3f::s3fnet::OpenFlowSwitchSession::OutputPacket(), s3f::s3fnet::OpenFlowSwitchSession::OutputPort(), s3f::s3fnet::OpenFlowControllerSession::pop(), s3f::s3fnet::UDPMaster::pop(), pop(), s3f::s3fnet::OpenFlowSwitchSession::pop(), s3f::s3fnet::TCPMaster::pop(), s3f::s3fnet::IPSession::pop(), s3f::s3fnet::LearningController::process_recv_packet(), s3f::s3fnet::UDPMaster::push(), s3f::s3fnet::TCPMaster::push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::receive(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::LearningControllerSession::ReceiveFromSwitch(), s3f::s3fnet::OpenFlowSwitchSession::ReceivePacketOut(), s3f::s3fnet::OpenFlowSwitchSession::ReceivePortMod(), s3f::s3fnet::OpenFlowSwitchSession::ReceiveStatsRequest(), s3f::s3fnet::SocketMaster::recv(), s3f::s3fnet::NBSocketMaster::recv(), s3f::s3fnet::SocketMaster::recv1(), s3f::s3fnet::NBSocketMaster::recv1(), s3f::s3fnet::UDPServerSession::request_received(), s3f::s3fnet::TCPServerSession::request_received(), s3f::s3fnet::UDPClientSession::request_sent(), s3f::s3fnet::TCPClientSession::request_sent(), s3f::s3fnet::NBTCPClientSessionContinuation::resume(), s3f::s3fnet::NBTCPServerSessionContinuation::resume(), s3f::s3fnet::OpenFlowSwitchSession::RunThroughFlowTable(), s3f::s3fnet::UDPSession::send(), s3f::s3fnet::SocketMaster::send(), s3f::s3fnet::NBSocketMaster::send(), s3f::s3fnet::SocketMaster::send1(), s3f::s3fnet::NBSocketMaster::send1(), s3f::s3fnet::TCPSession::send_data(), s3f::s3fnet::OpenFlowSwitchSession::SendFlowExpired(), s3f::s3fnet::OpenFlowSwitchSession::SendOpenflowBuffer(), s3f::s3fnet::OpenFlowSwitchSession::SendPortStatus(), s3f::s3fnet::UDPClientSession::server_connected(), s3f::s3fnet::TCPClientSession::server_connected(), s3f::s3fnet::BTCPClientSession::server_connected(), s3f::s3fnet::UDPServerSession::session_closed(), s3f::s3fnet::UDPClientSession::session_closed(), s3f::s3fnet::TCPClientSession::session_closed(), s3f::s3fnet::TCPServerSession::session_closed(), s3f::s3fnet::BTCPClientSession::session_closed(), s3f::s3fnet::TCPMaster::setConnected(), s3f::s3fnet::OpenFlowSwitchSession::SetController(), s3f::s3fnet::TCPMaster::setIdle(), s3f::s3fnet::TCPMaster::setListening(), s3f::s3fnet::UDPSession::setSource(), s3f::s3fnet::TCPMaster::slow_timer_callback_body(), s3f::s3fnet::TCPSession::slowTimeoutHandling(), s3f::s3fnet::SocketMaster::socket(), s3f::s3fnet::NBSocketMaster::socket(), s3f::s3fnet::SocketMaster::SocketMaster(), s3f::s3fnet::UDPServerSession::start_on(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPServerSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), s3f::s3fnet::NBTCPClientSession::start_on(), s3f::s3fnet::BTCPClientSession::start_on(), s3f::s3fnet::NBTCPServerSession::start_on(), s3f::s3fnet::NBTCPServerSessionContinuation::success(), s3f::s3fnet::TCPClientSession::TCPClientSession(), s3f::s3fnet::TCPMaster::TCPMaster(), s3f::s3fnet::TCPServerSession::TCPServerSession(), s3f::s3fnet::TCPSession::TCPSession(), s3f::s3fnet::UDPClientSession::timeout(), s3f::s3fnet::TCPClientSession::timeout(), s3f::s3fnet::BTCPClientSession::timeout(), s3f::s3fnet::UDPClientSession::UDPClientSession(), s3f::s3fnet::UDPMaster::UDPMaster(), s3f::s3fnet::UDPServerSession::UDPServerSession(), s3f::s3fnet::UDPSession::UDPSession(), s3f::s3fnet::TCPSession::update_timeout(), s3f::s3fnet::IPSession::verify_local_ip_address(), and s3f::s3fnet::UDPSession::wake_app().
 {
   return dynamic_cast<Host*>(ingraph);
 }
Random::RNG* s3f::s3fnet::ProtocolSession::getRandom () inline inherited
The method returns a pointer to the random number generator.
Definition at line 200 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::sess_rng.
Referenced by s3f::s3fnet::DroptailQueue::calibrate(), s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::DummySession::init(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), and s3f::s3fnet::NetworkInterface::receivePacket().
 { return sess_rng;}
ltime_t s3f::s3fnet::ProtocolSession::getNow () inherited
The method returns the current simulation time.
To be safe, please do NOT call this function after initialization and before wrapup phase. That is, it is unsafe to call this method in the constructor, destructor, config, init, and wrapup methods. The time service is carried out by the host's owner community. This method just directs the call to the community. It's given here for convenience.
Definition at line 123 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::inHost(), and Entity::now().
Referenced by s3f::s3fnet::DroptailQueue::calibrate(), s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::TCPMaster::enableFastTimeout(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::TCPMaster::fast_timer_callback_body(), injectEvent(), s3f::s3fnet::TCPSession::now(), pop(), s3f::s3fnet::TCPMaster::slow_timer_callback_body(), s3f::s3fnet::SocketMaster::socket(), s3f::s3fnet::NBSocketMaster::socket(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), and s3f::s3fnet::BTCPClientSession::start_on().
 {
   return inHost()->now();
 }
char * s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator () inherited
For printing the current simulation time in a better readable format.
Definition at line 128 of file protocol_session.cc.
References s3f::s3fnet::Host::getNowWithThousandSeparator(), and s3f::s3fnet::ProtocolSession::inHost().
Referenced by s3f::s3fnet::UDPSession::abort(), s3f::s3fnet::DummySession::callback_body(), callback_body(), s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::UDPSession::connect(), s3f::s3fnet::TCPMaster::createSession(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::UDPServerSession::data_sent(), s3f::s3fnet::TCPServerSession::data_sent(), s3f::s3fnet::UDPSession::disconnect(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::BTCPClientSession::init(), injectEvent(), s3f::s3fnet::UDPSession::listen(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), s3f::s3fnet::DummySession::pop(), s3f::s3fnet::SimpleMac::pop(), pop(), s3f::s3fnet::UDPMaster::pop(), s3f::s3fnet::TCPMaster::pop(), s3f::s3fnet::IPSession::pop(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::UDPMaster::push(), s3f::s3fnet::SimplePhy::push(), s3f::s3fnet::TCPMaster::push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::receive(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::SimplePhy::receivePacket(), s3f::s3fnet::UDPServerSession::request_received(), s3f::s3fnet::TCPServerSession::request_received(), s3f::s3fnet::UDPClientSession::request_sent(), s3f::s3fnet::TCPClientSession::request_sent(), s3f::s3fnet::UDPSession::send(), s3f::s3fnet::TCPSession::send_data(), s3f::s3fnet::SimplePhy::sendPacket(), s3f::s3fnet::UDPClientSession::server_connected(), s3f::s3fnet::TCPClientSession::server_connected(), s3f::s3fnet::BTCPClientSession::server_connected(), s3f::s3fnet::UDPServerSession::session_closed(), s3f::s3fnet::UDPClientSession::session_closed(), s3f::s3fnet::TCPClientSession::session_closed(), s3f::s3fnet::TCPServerSession::session_closed(), s3f::s3fnet::BTCPClientSession::session_closed(), s3f::s3fnet::TCPMaster::setConnected(), s3f::s3fnet::TCPMaster::setIdle(), s3f::s3fnet::TCPMaster::setListening(), s3f::s3fnet::UDPSession::setSource(), s3f::s3fnet::TCPSession::slowTimeoutHandling(), s3f::s3fnet::UDPServerSession::start_on(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPServerSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), s3f::s3fnet::BTCPClientSession::start_on(), s3f::s3fnet::TCPSession::TCPSession(), s3f::s3fnet::UDPClientSession::timeout(), s3f::s3fnet::TCPClientSession::timeout(), s3f::s3fnet::BTCPClientSession::timeout(), s3f::s3fnet::UDPSession::UDPSession(), s3f::s3fnet::TCPSession::update_timeout(), and s3f::s3fnet::UDPSession::wake_app().
 {
         return inHost()->getNowWithThousandSeparator();
 }
int s3f::s3fnet::ProtocolSession::configured () inline inherited
This method returns true if the protocol session has been configured.
This method is used to make sure we configure the protocol session before initializing it.
Definition at line 221 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_CONFIGURED, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::config(), and s3f::s3fnet::ProtocolSession::init().
 { return stage >= PSESS_CONFIGURED; }
int s3f::s3fnet::ProtocolSession::initialized () inline inherited
This method returns true if the protocol session has been initialized.
This can be used to sequence calls to the init method of protocol sessions. For example, if protocol session A requires protocol session B to be initialized before A can be initialized, A's init method can call B's init method as long as B's initialized() returns true. The system does not enforce any ordering in its calls the init methods of all protocol sessions declared in the dml configuration.
Definition at line 233 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_INITIALIZED, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::init(), and s3f::s3fnet::ProtocolSession::wrapup().
 { return stage >= PSESS_INITIALIZED; }
int s3f::s3fnet::ProtocolSession::wrapped_up () inline inherited
This method returns true if the protocol session has been wrapped up.
This can be used to sequence calls to the wrapup method of protocol sessions. For example, if protocol session A requires protocol session B to be wrapped up before A can be wrapped up, A's wrapup method can call B's wrapup method as long as B's wrapped_up() returns true. The system does not enforce any ordering in its calls the wrapup methods of all protocol sessions declared in the dml configuration.
Definition at line 245 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_WRAPPED_UP, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::wrapup().
 { return stage >= PSESS_WRAPPED_UP; }
virtual const char* s3f::s3fnet::ProtocolSession::psesstype () inline virtual inherited
Reimplemented in s3f::s3fnet::NBSocketMaster, and s3f::s3fnet::SocketMaster.
Definition at line 247 of file protocol_session.h.
 { return "GENERIC"; } // DEBUG
virtual int s3f::s3fnet::ProtocolSession::instantiation_type () inline protected virtual inherited
This method controls how protocol instances can coexist with one another.
It returns one of the following:
PROT_UNIQUE_INSTANCE (default): allows only one instance for each type of protocol per protocol stack;
PROT_MULTIPLE_INSTANCES: allows multiple instances of the same implementation for each type of protocol per protocol stack;
PROT_MULTIPLE_IMPLEMENTATIONS: allows multiple instances from different implementations of the same protocol to exist on the protocol stack.
Reimplemented in s3f::s3fnet::BTCPClientSession, and s3f::s3fnet::TCPClientSession.
Definition at line 269 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PROT_UNIQUE_INSTANCE.
Referenced by s3f::s3fnet::ProtocolGraph::insert_session().
 { return PROT_UNIQUE_INSTANCE; }
Member Data Documentation
Process* s3f::s3fnet::OpenVZEventSession::callback_proc
the S3F process used by waitFor() function in the OpenVZEventSession protocol, provide call_back functionality
Definition at line 64 of file openVZEmu_event_session.h.
Referenced by init(), and injectEvent().
ProtocolCallbackActivation* s3f::s3fnet::OpenVZEventSession::dcac
Storing the data for the callback function.
In this case, the OpenVZEventSession session object is stored.
Definition at line 76 of file openVZEmu_event_session.h.
IPSession* s3f::s3fnet::OpenVZEventSession::ip_session
the IP layer below this protocol
Definition at line 85 of file openVZEmu_event_session.h.
Referenced by callback_body(), and init().
long int s3f::s3fnet::OpenVZEventSession::pkt_to_ve_counter
store the total number of packet output to VE
Definition at line 88 of file openVZEmu_event_session.h.
Referenced by pop().
char* s3f::s3fnet::ProtocolSession::name inherited
Symbolic name of the protocol this session implements.
The name of the protocol is derived from the DML 'name' attribute. It must not be NULL once the protocol session is configured.
Definition at line 63 of file protocol_session.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::SimpleMac::init(), s3f::s3fnet::UDPMaster::init(), s3f::s3fnet::SimplePhy::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::SocketMaster::init(), s3f::s3fnet::IPSession::init(), s3f::s3fnet::NBSocketMaster::init(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::ProtocolGraph::insert_session(), s3f::s3fnet::ProtocolSession::wrapup(), and s3f::s3fnet::ProtocolSession::~ProtocolSession().
float s3f::s3fnet::ProtocolSession::version inherited
Version number of this protocol implemenntation, represented as a floating point number (e.g., 1.23).
Definition at line 69 of file protocol_session.h.
char* s3f::s3fnet::ProtocolSession::use inherited
Name of the protocol class from which this protocol session is instantiated.
The protocol class must be registered with the Protocols class so that we will be able to instantiate an object from the class. (C++ does not support self-reflection). The class name must not be NULL once the protocol session is configured.
Definition at line 79 of file protocol_session.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::ProtocolGraph::insert_session(), and s3f::s3fnet::ProtocolSession::~ProtocolSession().
ProtocolGraph* s3f::s3fnet::ProtocolSession::ingraph protected inherited
Points to the protocol graph.
Definition at line 335 of file protocol_session.h.
Referenced by s3f::s3fnet::NicProtocolSession::getNetworkInterface(), s3f::s3fnet::ProtocolSession::inGraph(), and s3f::s3fnet::ProtocolSession::inHost().
Random::RNG* s3f::s3fnet::ProtocolSession::sess_rng protected inherited
Pointer to a random number generator.
Definition at line 338 of file protocol_session.h.
Referenced by s3f::s3fnet::ProtocolSession::getRandom(), and s3f::s3fnet::ProtocolSession::init().
int s3f::s3fnet::ProtocolSession::stage protected inherited
This variable indicates the current stage of this protocol session.
Each protocol session will go through four staged: PSESS_CREATED, PSESS_CONFIGURED, PSESS_INITIALIZED, and then PSESS_WRAPPED_UP.
Definition at line 346 of file protocol_session.h.
Referenced by s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::ProtocolSession::configured(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::ProtocolSession::initialized(), s3f::s3fnet::ProtocolSession::wrapped_up(), and s3f::s3fnet::ProtocolSession::wrapup().
The documentation for this class was generated from the following files:
openVZEmu_event_session.h
openVZEmu_event_session.cc