S3F: OutChannel Class Reference
OutChannel Class Reference
An OutChannel is the the source end of a communication connection.
#include <outchannel.h>
Public Member Functions
OutChannel (Entity *)
constructor, require specification of the Entity that owns it
OutChannel (Entity *, ltime_t)
constructor, require specification of the Entity that owns it.
virtual ~OutChannel ()
destructor.
Entity * owner ()
Returns the identity of the Entity that owns this OutChannel.
ltime_t mapto (InChannel *, ltime_t)
Declare a connection from here to the named InChannel, with a transfer delay equal to the argument delay.
bool unmap (InChannel *)
unmap undoes a mapping between this OutChannel and the named InChannel.
bool is_mapped (InChannel *)
Return true if the named if a mapping exists to the named InChannel.
vector< InChannel * > mapped ()
Return a vector of all the inchannels currently mapped to this outchannel.
ltime_t transfer_delay (InChannel *)
Return the transfer delay from OutChannel to named InChannel.
ltime_t new_transfer_delay (InChannel *, ltime_t)
new_transfer_delay allows the user to change the transfer delay on the mapping.
ltime_t min_xtransfer_delay ()
Return the minimum transfer delay from OutChannel to any InChannel aligned to a different Timeline.
ltime_t min_write_delay ()
Return the promised lower bound on the per-write delay given in a write call.
ltime_t new_min_write_delay (ltime_t)
Change the minimum write delay associated with the OutChannel.
bool write (Activation, ltime_t delay, unsigned int pri)
Method write directs the passed event (Activation act) to be carried to all inchannels to which this outchannel is mapped.
bool write (Activation, ltime_t delay)
Same as the write(Activation, ltime_t delay, unsigned int pri), except the default priority (priority code of the process activated by this write) is used.
bool write (Activation, unsigned int pri)
Same as the write(Activation, ltime_t delay, unsigned int pri), except the zero per-write delay is used.
bool write (Activation)
Same as the write(Activation, ltime_t delay, unsigned int pri), except the default priority (priority code of the process activated by this write) and the zero per write delay are used.
ltime_t min_sync_cross_timeline_delay (ltime_t)
Return the least delay among all cross-timeline mappings whose minimum delay is at least as large as the argument.
ltime_t min_sync_all_timeline_delay (ltime_t)
Return the least delay among all mappings whose minimum delay is at least as large as the argument.
Timeline * alignment ()
unsigned int s3fid ()
Protected Member Functions
InChannel * getInChannel (string)
given a string name for an InChannel, see whether its corresponding InChannel address is known.
unsigned int count_min_delay_crossings (ltime_t)
count the number of cross-timeline connections whose minimum complete delay is less than or equal to thrs
Protected Attributes
Entity * __owner
owner entity
ltime_t __min_write_delay
lower bound on per-write delay
Timeline * __alignment
timeline of outchannel's owner
unsigned int __s3fid
S3f identity.
vector< mappedChannel > __mapped_to
collection of mappings
Static Protected Attributes
static unsigned int __num_outchannels = 0
for identifier
static pthread_mutex_t outchannel_class_mutex
synchronize getting id
Detailed Description
An OutChannel is the the source end of a communication connection.
One establishes a connection by finding the address of an InChannel (e.g. the InChannelName directory of the owning Entity might be searched to find it), and call OutChannel method mapto in order to establish the connection. An OutChannel may declare multiple mapto's—when the "write" method is called passing a message, that message will be delivered to all the InChannels to which the OutChannel has mapped itself.
A mapto declaration includes a delay parameter that is used in the time of arrival calculation. On making a call to write, a parameter of the write is the "write time" delay. The time of arrival is the sum of the time at which the write is made is the the write-time delay plus the delay included in the mapto. At the time an OutChannel is created one may declare a lower bound on any write-time increment that would be included. The bound helps in establishing synchronization windows
Definition at line 83 of file outchannel.h.
Constructor & Destructor Documentation
OutChannel::OutChannel (Entity *)
constructor, require specification of the Entity that owns it
OutChannel::OutChannel (Entity * theowner, ltime_t min_write_delay = 0)
constructor, require specification of the Entity that owns it.
An OutChannel constructor is told the identity of the Entity that owns it, and optionally a minimum per-write delay.
A minimum "per-write" delay can also be specified.
That delay is a lower bound on any ltime_t argument a write method call on this OutChannel will observe.
The chief role of the constructor is to initialize its state variable
__owner : owning entity
__min_write_delay : lower bound on per-write argument
__alignment : the Timeline on which the owning Entity is aligned
__s3fid : the unique OutChannel id
In addition, the constructor adds this OutChannel to the OutChannel list held by its owner.
Definition at line 31 of file outchannel.cc.
References __num_outchannels, Entity::__outchannel_list, __s3fid, Entity::entity_inst_mutex, and outchannel_class_mutex.
                                                                     :
                                    __owner(theowner), __min_write_delay(min_write_delay), __alignment(theowner->alignment())
 {
         pthread_mutex_lock(&outchannel_class_mutex);
         __s3fid = __num_outchannels++;
         pthread_mutex_unlock(&outchannel_class_mutex);
         // register outchannel with entity that owns it
         pthread_mutex_lock(&theowner->entity_inst_mutex);
         theowner->__outchannel_list.push_back(this);
         pthread_mutex_unlock(&theowner->entity_inst_mutex);
 }
OutChannel::~OutChannel () virtual
destructor.
Definition at line 44 of file outchannel.cc.
References outchannel_class_mutex, and s3fid().
{
         if( !s3fid() ) pthread_mutex_destroy(&outchannel_class_mutex);
 }
Member Function Documentation
Entity* OutChannel::owner () inline
Returns the identity of the Entity that owns this OutChannel.
Definition at line 97 of file outchannel.h.
References __owner.
Referenced by mapto(), new_min_write_delay(), and write().
 { return __owner; };
ltime_t OutChannel::mapto (InChannel * ic, ltime_t transfer_delay)
Declare a connection from here to the named InChannel, with a transfer delay equal to the argument delay.
mapto connects this outchannel with the InChannel whose address is passed.
The return value is a simulation time after which the mapping is assured to have been implemented. A negative value is returned as an error code if already a mapping exists between this OutChannel and the named InChannel and the delays are different. The address of the InChannel must be known. InChannels can be declared with string names, whose scope is local to the entity that owns them. Each entity has a directory of string-to-InChannel names that can be consulted for these mappings.
A per-mapping delay can be associated with each mapping. If the OutChannel and target InChannel are on different Timelines then at least one { OutChannel __min_write_delay, per-mapping delay} must be non-zero, otherwise the mapping is not permitted (in which case a -1 is returned).
A mapto to an InChannel that has already been mapped to, but with a different mapping delay causes an error code -1 to be returned also. However, if there is already a mapping to that InChannel but with the same mapping delay, no error is thrown and the current time is returned.
A legitimate mapping is encoded in an instance of the mappedChannel class. However, depending on context, the mapping might not immediately be implemented. A mapping delay that would permit a write to arrive in the current synchronization window will cause implementation of the mapto to be be delayed until the end of the synchronization window. This is implemented by putting a description of the mapping into a Timeline list __channels_to_map, these are dealt with at the end of the synchronization window, and the upper edge of the synchronization window is reported as the time when the mapto will be effected.
Definition at line 186 of file outchannel.cc.
References Timeline::__channels_to_map, __mapped_to, Entity::alignment(), alignment(), Timeline::all_timeline_delay(), Timeline::cross_timeline_delay(), Timeline::horizon(), min_write_delay(), Entity::now(), InChannel::owner(), owner(), RUNNING, Timeline::same_timeline_delay(), transfer_delay(), and mappedChannel::xtimeline().
Referenced by s3f::s3fnet::Link::connect(), and pHold_Node::init().
{
         // return error code if this mapping can't be implemented
         if( (transfer_delay == 0 && min_write_delay() == 0 ) &&
                         ic->owner()->alignment() != owner()->alignment() ) {
                 return -1;
         }
         // search the __mapped_to vector for a match with the InChannel.
         // If present and if the associated delay is different
         // from mapping_delay, do nothing and pass back false
         //
         unsigned int end = __mapped_to.size();
         for(unsigned int i=0; i< end; i++) {
                 if (__mapped_to[i].ic() == ic ) {
                         // Error if the delays are different. Do nothing if they are
                         // the same.
                         //
                         if( __mapped_to[i].transfer_delay() != transfer_delay ) return -1;
                         else return owner()->now();
                 }
         }
         // look for the requested mapping in the timeline's __channels_to_map vector
         end = alignment()->__channels_to_map.size();
         for(unsigned int i=0; i< end; i++) {
                 if (alignment()->__channels_to_map[i]->ic() == ic  &&
                                 alignment()->__channels_to_map[i]->oc() == this) {
                         // Error if the delays are different. Do nothing if they are
                         // the same.
                         //
                         if( alignment()->__channels_to_map[i]->transfer_delay() != transfer_delay ) return -1;
                         else return owner()->now();
                 }
         }
         // create a data structure to hold the mapping description
         mappedChannel mc(this, ic, transfer_delay, false);
         // if the timeline state is not RUNNING we can implement the mapto
         // immediately by storing it in the outchannel's __mapped_to array.
         // Otherwise store it in the timeline's __channels_to_map array
         //
         if( owner()->alignment()->get_state() != RUNNING) {
                 __mapped_to.push_back(mc);
                 // tell the timeline about a cross-timeline delay
                 if ( mc.xtimeline() ) {
                         owner()->alignment()->cross_timeline_delay( transfer_delay );
                 }
                 else
                 {
                         owner()->alignment()->same_timeline_delay( transfer_delay );
                 }
                 // update all timeline delay as well, used for emulation vtime integration
                 owner()->alignment()->all_timeline_delay( transfer_delay );
                 // report an immediate mapping made
                 return owner()->now();
         }
         else {
                 // can't do it now so buffer it up
                 owner()->alignment()->__channels_to_map.push_back(
                                 new mappedChannel( this, ic, transfer_delay, false) );
                 // channel mapping will be implemented at the end of the current barrier
                 // window.  This is stored in variable __stop_at in the timeline
                 //
                 return owner()->alignment()->horizon();
         }
 }
bool OutChannel::unmap (InChannel * ic)
unmap undoes a mapping between this OutChannel and the named InChannel.
we can undo a mapto by calling unmap.
If found the unmapping is done immediately. Any Activations still "in flight" through this mapping are still delivered. Boolean return indicates whether the InChannel was found and removed.
If we find the mapping in the OutChannel's list, then it is removed and true is returned. If we don't find the mapping, we look in the timeline's list of buffered maptos for later implementation, and if found there, remove it. If not found at all, false is returned.
When found, check whether the connection's delay (OutChannel __min_write_delay plus tranfer delay) is identically __min_sync_cross_timeline_delay, in which case decrement the count of such connections.
Definition at line 270 of file outchannel.cc.
References Timeline::__channels_to_map, __mapped_to, Timeline::__recompute_min_delay, alignment(), min_write_delay(), and transfer_delay().
{
         // cache for efficiency
         unsigned int end = __mapped_to.size();
         for( unsigned int i=0; i<end; i++)
                 if( __mapped_to[i].ic() == ic) {
                         // found it.
                         // if this happens to be the minimum delay cross-timeline
                         // channel then decrement count of these and see if that triggers
                         // a recomputation
                         if( __mapped_to[i].xtimeline() &&
                                         min_write_delay() + __mapped_to[i].transfer_delay()
                                         == alignment()->get_min_sync_cross_timeline_delay() ) {
                                 if ( --alignment()->__channels_at_minimum == 0 ) {
                                         alignment()->__recompute_min_delay = true;
                                 }
                         }
                         // We can remove the mapping from the __mapped_to list
                         // by moving the tail end of the list into its position,
                         // and then pop the end of the list.
                         //
                         __mapped_to[i] = __mapped_to[end];
                         __mapped_to.pop_back();
                         return true;
                 }
         // didn't find it in the main list.  Look in the buffered list
         end = alignment()->__channels_to_map.size();
         for( unsigned int i=0; i<end; i++)
                 if( alignment()->__channels_to_map[i]->ic() == ic &&
                                 alignment()->__channels_to_map[i]->oc() == this ) {
                         // found it, so just shorten the list
                         // by copying the end element into this
                         // position and pop the vector
                         alignment()->__channels_to_map[i] = alignment()->__channels_to_map[end-1];
                         alignment()->__channels_to_map.pop_back();
                         return true;
                 }
         // couldn't find it at all
         return false;
 }
bool OutChannel::is_mapped (InChannel * ic)
Return true if the named if a mapping exists to the named InChannel.
Definition at line 319 of file outchannel.cc.
References __mapped_to.
{
         // cache for efficiency
         int end = __mapped_to.size();
         // return true if any of the InChannel pointers saved match the input
         for(int i=0; i<end; i++)
                 if( __mapped_to[i].ic() == ic) return true;
         return false;
 }
vector< InChannel * > OutChannel::mapped ()
Return a vector of all the inchannels currently mapped to this outchannel.
Definition at line 336 of file outchannel.cc.
References __mapped_to.
{
         vector<InChannel*> ans;
         int end = __mapped_to.size();
         for(int i=0; i<end; i++) ans.push_back( __mapped_to[i].ic() );
         return ans;
 }
ltime_t OutChannel::transfer_delay (InChannel * ic)
Return the transfer delay from OutChannel to named InChannel.
-1 if there is no connection.
Definition at line 352 of file outchannel.cc.
References __mapped_to.
Referenced by mapto(), min_xtransfer_delay(), new_transfer_delay(), and unmap().
{
         // cached for efficiency
         int end = __mapped_to.size();
         // return delay if any of the InChannel pointers saved match the input
         for(int i=0; i<end; i++)
                 if( __mapped_to[i].ic() == ic) return __mapped_to[i].transfer_delay();
         // none found so return -1
         return -1;
 }
ltime_t OutChannel::new_transfer_delay (InChannel * ic, ltime_t delay)
new_transfer_delay allows the user to change the transfer delay on the mapping.
A simulation time after which the remapping is assured to be successful is returned if the InChannel is found, otherwise a negative value indicating an error.
Definition at line 394 of file outchannel.cc.
References Timeline::__channels_at_minimum, Timeline::__delays_to_change, __mapped_to, Timeline::__recompute_min_delay, alignment(), Timeline::get_min_sync_cross_timeline_delay(), Timeline::get_state(), Timeline::horizon(), min_write_delay(), Timeline::now(), RUNNING, and transfer_delay().
{
         // cache for efficiency
         int end = __mapped_to.size();
         Timeline* tl = alignment();
         // find the named InChannel
         for(int i=0; i< end; i++) {
                 if( __mapped_to[i].ic() == ic)  {
                         // Found it. If the new minimum is equal to the old one there
                         //  is nothing to do, just return the current time.
                         //
                         if( delay == __mapped_to[i].transfer_delay() ) return tl->now();
                         // if the channel endpoints are co-aligned, just
                         // make the change immediately and return the current time
                         //
                         if( !__mapped_to[i].xtimeline() ) {
                                 __mapped_to[i].set_transfer_delay(delay);
                                 return tl->now();
                         }
                         // If the new delay is larger than the old we can implement it
                         // knowing it does not affect synchronization
                         //
                         if( __mapped_to[i].transfer_delay() < delay ) {
                                 __mapped_to[i].set_transfer_delay(delay);
                                 return tl->now();
                         }
                         // The delay got smaller. compute the new minimum transfer time under this change
                         ltime_t xtransfer = min_write_delay() + delay;
                         // if the new minimum is equal to the timeline's
                         // minimum channel delay then increment the number
                         // of channels at the minimum
                         //
                         if( xtransfer == tl->get_min_sync_cross_timeline_delay() ) {
                                 tl->__channels_at_minimum++;
                                 __mapped_to[i].set_transfer_delay(delay);
                                 return tl->now();
                         }
                         // if the new minimum is less than the timeline's
                         // minimum channel delay it may still be possible to implement,
                         //  if
                         //    -- the timeline isn't currently running
                         //    -- we've advanced far enough into the synchronization window
                         //        that we can implement the change without threatening
                         //        the synchronization
                         //
                         if( xtransfer < tl->get_min_sync_cross_timeline_delay() &&
                                         ((tl->get_state() != RUNNING) ||
                                                         ( tl->horizon() <=  tl->now()+xtransfer ))) {
                                 __mapped_to[i].set_transfer_delay(delay);
                                 return tl->now();
                         }
                         // necessary to delay implementation and recompute the minimum cross timeline delay
                         tl->__recompute_min_delay = true;
                         // Create a mappedChannel structure and place it in the
                         // timeline's __delays_to_change vector
                         //
                         tl->__delays_to_change.push_back(
                                         new mappedChannel( this, ic, delay, false) );
                         break;
                 }
         }
         return tl->horizon();
 }
ltime_t OutChannel::min_xtransfer_delay ()
Return the minimum transfer delay from OutChannel to any InChannel aligned to a different Timeline.
Time returned does NOT include min_write_delay. Returns -1 if there is none.
Definition at line 372 of file outchannel.cc.
References __mapped_to, and transfer_delay().
Referenced by new_min_write_delay(), and Timeline::sync_window().
{
         ltime_t ans = -1;
         // cached for efficiency
         int end = __mapped_to.size();
         for(int i=0; i<end; i++)
                 if(  __mapped_to[i].xtimeline() ) {
                         if (ans<0 || __mapped_to[i].transfer_delay() < ans )
                                 ans = __mapped_to[i].transfer_delay();
                 }
         return ans;
 }
ltime_t OutChannel::min_write_delay () inline
Return the promised lower bound on the per-write delay given in a write call.
Definition at line 147 of file outchannel.h.
References __min_write_delay.
Referenced by count_min_delay_crossings(), Timeline::initialize_appt(), mapto(), min_sync_all_timeline_delay(), min_sync_cross_timeline_delay(), new_transfer_delay(), Timeline::sync_window(), and unmap().
 { return __min_write_delay; }
ltime_t OutChannel::new_min_write_delay (ltime_t mwd)
Change the minimum write delay associated with the OutChannel.
The simulation time after which the change is assured is returned.
Definition at line 474 of file outchannel.cc.
References Timeline::__delays_to_change, __min_write_delay, alignment(), Timeline::horizon(), min_xtransfer_delay(), Entity::now(), and owner().
{
         // if the new one is larger than the old we can implement immediately
         if( __min_write_delay <= mwd ) {
                 __min_write_delay = mwd;
                 return owner()->now();
         }
         // if the sum of the new minimum and the minimum transfer time
         // is at least as large as the event horizon, we can implement immediately
         //
         if ( alignment()->horizon() <= mwd  + min_xtransfer_delay() ) {
                 __min_write_delay = mwd;
                 return owner()->now();
         }
         // has to wait until the end of the window. Put request in Timeline's
         // __delays_to_change queue.   Changes processed in FCFS order, so
         // in both transfer changes and min_write_delay changes only the last
         // change made in a window "sticks"
         //
         alignment()->__delays_to_change.push_back(
                         new mappedChannel( this, NULL, mwd, true) );
         // will have taken place by the time of the event horizon
         return alignment()->horizon();
 }
bool OutChannel::write (Activation act, ltime_t delay, unsigned int pri)
Method write directs the passed event (Activation act) to be carried to all inchannels to which this outchannel is mapped.
The written event is scheduled to arrive at its destination at the time equal to the current time plus the offered per-write delay plus the delay associated with the mapto connection.
A write attempts to write a copy of Activation act to every InChannel targeted by a mapto call by this OutChannel. Any InChannel that is on this same Timeline will get its Activation. Any write done where the per-write delay is at least as large as the minimum declared at construction will deliver the Activation to all the targets. However, we allow a per-write delay that is actually smaller than the promised minimum, provided that the overall delivery time still places the receipt in a future synchronization window. The upper edge of the current window is accessible through Timeline::horizon().
A write that would try to place the Activation across Timelines and within the current window is not performed, but all legal deliveries from the write will be delivered. True is returned if all deliveries are made, False if one or more do not. A model may test the return from write and has access to enough information to determine which deliveries were not made.
Parameters
act typedef for shared_ptr<Message>. Message is the base class for a communication, shared_ptr templates a very capable smart pointer, that, in particular, alleviates the need for deleting Activations as they are past around. In practice a modeler will create a derived class for Message and create an Activation for it. The Message base class carries an unsigned int type that can be used to encode the derived type of Message being carried, needed for casting at the destination.
delay a per-write delay. If it is not included, zero is assumed.
pri a scheduling priority to be used as a 2nd key in the event-list of the target timeline. If no priority is specified, the default is the priority code of the process activated by this write.
Definition at line 90 of file outchannel.cc.
References __mapped_to, __min_write_delay, __owner, Entity::alignment(), Message::clone(), Message::erase_all(), Timeline::horizon(), Entity::now(), owner(), Timeline::schedule(), and user_pri.
Referenced by pHold_Node::init(), s3f::s3fnet::NetworkInterface::sendPacket(), pHold_Node::talk(), and write().
{
         bool allsent = true;
         bool onesent = false;
         // compute the portion of the delivery time that is known
         ltime_t delivery1 = owner()->now() + write_delay;
         ltime_t delivery2;
         // what is the synchronization horizon (i.e., time at which
         // all Timelines next synchronize)?
         ltime_t horizon = owner()->alignment()->horizon();
         // the list won't change as we loop through so this caches the "end of loop"
         // index
         unsigned int end = __mapped_to.size();
         // for every inchannel mapped to this outchannel,
         // schedule an activation on the timeline to which the
         // InChannel's owner is mapped
         //
         for(unsigned int i=0; i<end; i++) {
                 // compute arrival time over this connection
                 //delivery2 = delivery1 + __mapped_to[i].transfer_delay() + 1;
                 delivery2 = delivery1 + __mapped_to[i].transfer_delay() + __min_write_delay;
                 // send it if either the inchannel is aligned with the outchannel,
                 // the delivery time is at least as large as the timeline's event horizon,
                 // or the communication occurs over an asynchronous channel
                 //
                 if( !__mapped_to[i].xtimeline() || horizon <= delivery2 || __mapped_to[i].asynchronous() )
                 {
 #ifndef SAFE_MSG_PTR
                         if(onesent == false) //first packet, no need to duplicate
{
                                 __owner->alignment()->schedule( __mapped_to[i].ic(), delivery2, user_pri(pri), act );
                                 onesent = true;
                         }
                         else
{
                                 Activation act_dup = act->clone();
                                 __owner->alignment()->schedule( __mapped_to[i].ic(), delivery2, user_pri(pri), act_dup );
                         }
 #else
                         __owner->alignment()->schedule( __mapped_to[i].ic(), delivery2, user_pri(pri), act );
 #endif
                 }
                 else allsent = false;
         }
 #ifndef SAFE_MSG_PTR
         //no packet is sent, delete it
         if(onesent == false)
         {
                 printf("s3f outchannel write drop \n");
                 act->erase_all();
         }
 #endif
         return allsent;
 }
bool OutChannel::write (Activation act, ltime_t delay)
Same as the write(Activation, ltime_t delay, unsigned int pri), except the default priority (priority code of the process activated by this write) is used.
Definition at line 153 of file outchannel.cc.
References Timeline::default_sched_pri, and write().
{
         return write(act, delay, Timeline::default_sched_pri);
 }
bool OutChannel::write (Activation act, unsigned int pri)
Same as the write(Activation, ltime_t delay, unsigned int pri), except the zero per-write delay is used.
Definition at line 161 of file outchannel.cc.
References write().
{
         return write(act, 0, pri);
 }
bool OutChannel::write (Activation act)
Same as the write(Activation, ltime_t delay, unsigned int pri), except the default priority (priority code of the process activated by this write) and the zero per write delay are used.
Definition at line 157 of file outchannel.cc.
References Timeline::default_sched_pri, and write().
{
         return write(act, 0, Timeline::default_sched_pri);
 }
ltime_t OutChannel::min_sync_cross_timeline_delay (ltime_t thrs)
Return the least delay among all cross-timeline mappings whose minimum delay is at least as large as the argument.
Thresholding used to support composite synchronization algorithm.
Definition at line 512 of file outchannel.cc.
References __mapped_to, and min_write_delay().
{
         int end = __mapped_to.size();
         if( end == 0 ) return -1;
         ltime_t ans = -1;
         // A more direct test in the loop below is thrs < min_write_delay()+delay
         //  but that involves an addition every time we can avoid by subtracting
         // min_write_delay() from thrs, and test thrs < delay
         //
         thrs -= min_write_delay();
         ltime_t  delay;
         for(int i=0; i< end; i++) {
                 delay = __mapped_to[i].transfer_delay();
                 if( __mapped_to[i].xtimeline()
                                 && thrs <= delay && ( (delay<ans) || (ans<0) ) )
                         ans=delay;
         }
         // return -1 if no xtimeline channels observed
         if(ans == -1) return -1;
         // found at least one xtimeline connection, so ans was changed
         return ans + min_write_delay();
 }
ltime_t OutChannel::min_sync_all_timeline_delay (ltime_t thrs)
Return the least delay among all mappings whose minimum delay is at least as large as the argument.
Definition at line 539 of file outchannel.cc.
References __mapped_to, and min_write_delay().
{
         int end = __mapped_to.size();
         if( end == 0 ) return -1;
         ltime_t ans = -1;
         // A more direct test in the loop below is thrs < min_write_delay()+delay
         //  but that involves an addition every time we can avoid by subtracting
         // min_write_delay() from thrs, and test thrs < delay
         //
         thrs -= min_write_delay();
         ltime_t  delay;
         for(int i=0; i< end; i++) {
            delay = __mapped_to[i].transfer_delay();
            if( thrs <= delay && ( (delay<ans) || (ans<0) ) )
                 ans=delay;
         }
         if(ans == -1) return -1;
         return ans + min_write_delay();
 }
Timeline* OutChannel::alignment () inline
Definition at line 232 of file outchannel.h.
References __alignment.
Referenced by mappedChannel::mappedChannel(), mapto(), new_min_write_delay(), new_transfer_delay(), and unmap().
 { return __alignment; }
unsigned int OutChannel::s3fid () inline
Definition at line 233 of file outchannel.h.
References __s3fid.
Referenced by ~OutChannel().
 { return __s3fid;   }
InChannel* OutChannel::getInChannel (string) protected
given a string name for an InChannel, see whether its corresponding InChannel address is known.
NULL is returned if that address is not yet known.
unsigned int OutChannel::count_min_delay_crossings (ltime_t thrs) protected
count the number of cross-timeline connections whose minimum complete delay is less than or equal to thrs
Definition at line 571 of file outchannel.cc.
References __mapped_to, and min_write_delay().
{
         unsigned int ans = 0;
         int end = __mapped_to.size()-1;
         if( end == 0 ) return 0;
         ltime_t  delay;
         for(int i=0; i<= end; i++) {
                 delay = __mapped_to[i].transfer_delay() + min_write_delay();
                 if( __mapped_to[i].xtimeline() && delay <= thrs) ans++;
         }
         return ans;
 }
Member Data Documentation
Entity* OutChannel::__owner protected
owner entity
Definition at line 256 of file outchannel.h.
Referenced by owner(), and write().
ltime_t OutChannel::__min_write_delay protected
lower bound on per-write delay
Definition at line 257 of file outchannel.h.
Referenced by min_write_delay(), new_min_write_delay(), Timeline::sync_window(), and write().
Timeline* OutChannel::__alignment protected
timeline of outchannel's owner
Definition at line 258 of file outchannel.h.
Referenced by alignment().
unsigned int OutChannel::__s3fid protected
S3f identity.
Definition at line 259 of file outchannel.h.
Referenced by OutChannel(), and s3fid().
unsigned int OutChannel::__num_outchannels = 0 static protected
for identifier
Definition at line 260 of file outchannel.h.
Referenced by OutChannel().
pthread_mutex_t OutChannel::outchannel_class_mutex static protected
synchronize getting id
Definition at line 261 of file outchannel.h.
Referenced by Interface::Interface(), OutChannel(), and ~OutChannel().
vector<mappedChannel> OutChannel::__mapped_to protected
collection of mappings
Definition at line 262 of file outchannel.h.
Referenced by count_min_delay_crossings(), Timeline::initialize_appt(), is_mapped(), mapped(), mapto(), min_sync_all_timeline_delay(), min_sync_cross_timeline_delay(), min_xtransfer_delay(), new_transfer_delay(), Timeline::sync_window(), transfer_delay(), unmap(), and write().
The documentation for this class was generated from the following files:
outchannel.h
outchannel.cc