S3F: s3f::s3fnet::TCPSeqWindow Class Reference
s3f::s3fnet::TCPSeqWindow Class Reference
Implements the sliding window in TCP.
#include <tcp_seqwnd.h>
Public Member Functions
TCPSeqWindow (uint32 init_seqno, uint32 wsize)
The constructor.
uint32 start ()
Return the first sequence of the window.
uint32 end ()
Return the last sequence of the window.
uint32 firstUnused ()
Return the first unused sequence in the window.
uint32 size ()
Return the size of the window.
uint32 used ()
Return how much of the window is used up in bytes.
uint32 unused ()
Return how much of the window is unused in bytes.
uint32 lengthTo (const uint32 seqno)
Return the number of bytes between a give sequence number and the start of the window.
void setStart (const uint32 seqno)
Set the start sequence number of the window.
void shift (uint32 offset)
Increase the lower edge of the window by offset number of bytes.
void expand (uint32 nbytes)
Expand the window size by nbytes.
void shrink (uint32 nbytes)
Shrink the size of the window by nbytes.
bool use (uint32 nbytes)
Use up nbytes of the window with data.
void setSYN (bool syn)
set SYN bit.
void setFIN (bool fin)
set FIN bit.
bool synAtFront ()
Return true if SYN segment is in the window.
bool finAtFront ()
Return true if FIN segment is in the window.
uint32 next ()
Like firstUnused method, but also uses SYN & FIN segments; the method is used for sending window.
uint32 expect ()
Like start method, but also uses SYN & FIN segments; the method is used for receiving window.
bool within (uint32 seqno)
Returns true iff 'seqno' is within the window.
bool isUsed (uint32 seqno)
Returns true iff 'seqno' is used within the window.
bool empty ()
Returns true iff the window is empty (nothing used).
void reset ()
Resets the window.
Protected Member Functions
void seq_shift (uint32 offset)
Shift the window by the given offset permanently.
Protected Attributes
uint32 start_seqno
Starting sequence number of the window.
uint32 win_size
Size of the window in bytes.
uint32 used_size
How many bytes are used in window.
int syn_included
Whether SYN is in window.
int fin_included
Whether FIN is in window.
Detailed Description
Implements the sliding window in TCP.
This class provides basic operations on sequence numbers. One needs to make sure that the window size is less than or equal to the buffer size. This class does not maintain real data. Therefore, the send window and receive window should extend this class to add more functionalities.
Definition at line 25 of file tcp_seqwnd.h.
Constructor & Destructor Documentation
s3f::s3fnet::TCPSeqWindow::TCPSeqWindow (uint32 init_seqno, uint32 wsize) inline
The constructor.
Definition at line 28 of file tcp_seqwnd.h.
                                                 :
     start_seqno(init_seqno), win_size(wsize), used_size(0),
     syn_included(0), fin_included(0) {}
Member Function Documentation
uint32 s3f::s3fnet::TCPSeqWindow::start () inline
Return the first sequence of the window.
Definition at line 37 of file tcp_seqwnd.h.
References start_seqno.
Referenced by s3f::s3fnet::TCPSendWindow::generate(), s3f::s3fnet::TCPSession::init_state_established(), s3f::s3fnet::TCPSession::process_acks(), s3f::s3fnet::TCPSession::process_dup_acks(), s3f::s3fnet::TCPSession::sack_resend_segments(), and s3f::s3fnet::TCPSession::timeout_resend().
 { return start_seqno; }
uint32 s3f::s3fnet::TCPSeqWindow::end () inline
Return the last sequence of the window.
Definition at line 40 of file tcp_seqwnd.h.
References start_seqno, and win_size.
 { return start_seqno + win_size - 1; }
uint32 s3f::s3fnet::TCPSeqWindow::firstUnused () inline
Return the first unused sequence in the window.
Definition at line 43 of file tcp_seqwnd.h.
References start_seqno, and used_size.
Referenced by s3f::s3fnet::TCPSession::acknowledge(), s3f::s3fnet::TCPSession::appl_close(), s3f::s3fnet::TCPSession::appl_send(), s3f::s3fnet::TCPSession::fastTimeoutHandling(), s3f::s3fnet::TCPSession::init_state_fin_wait_1(), s3f::s3fnet::TCPSession::init_state_syn_received(), s3f::s3fnet::TCPSession::init_state_syn_sent(), s3f::s3fnet::TCPSession::process_dup_acks(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::TCPSession::sack_send_in_fast_recovery(), s3f::s3fnet::TCPSession::slow_timeout_handling_helper(), and s3f::s3fnet::TCPSession::timeout_resend().
 { return start_seqno + used_size; }
uint32 s3f::s3fnet::TCPSeqWindow::size () inline
Return the size of the window.
Definition at line 46 of file tcp_seqwnd.h.
References win_size.
Referenced by s3f::s3fnet::TCPSession::calc_advertised_wnd().
 { return win_size; }
uint32 s3f::s3fnet::TCPSeqWindow::used () inline
Return how much of the window is used up in bytes.
Definition at line 49 of file tcp_seqwnd.h.
References used_size.
Referenced by s3f::s3fnet::TCPSendWindow::canSend(), s3f::s3fnet::TCPSession::checkIdle(), s3f::s3fnet::TCPRecvWindow::freeInBuffer(), s3f::s3fnet::TCPSession::process_acks(), s3f::s3fnet::TCPSession::process_dup_acks(), s3f::s3fnet::TCPSession::process_new_acks(), and s3f::s3fnet::TCPSession::segment_and_send().
 { return used_size; }
uint32 s3f::s3fnet::TCPSeqWindow::unused () inline
Return how much of the window is unused in bytes.
Definition at line 52 of file tcp_seqwnd.h.
References used_size, and win_size.
Referenced by s3f::s3fnet::TCPSession::process_dup_acks(), s3f::s3fnet::TCPSession::sack_send_in_fast_recovery(), and s3f::s3fnet::TCPSession::segment_and_send().
 { return (win_size - used_size); }
uint32 s3f::s3fnet::TCPSeqWindow::lengthTo (const uint32 seqno) inline
Return the number of bytes between a give sequence number and the start of the window.
Definition at line 56 of file tcp_seqwnd.h.
References start_seqno.
Referenced by s3f::s3fnet::TCPSession::resend_segments().
 { return seqno - start_seqno; }
void s3f::s3fnet::TCPSeqWindow::setStart (const uint32 seqno) inline
Set the start sequence number of the window.
Definition at line 63 of file tcp_seqwnd.h.
References start_seqno.
Referenced by s3f::s3fnet::TCPSession::active_open(), and s3f::s3fnet::TCPSession::process_SYN().
 { start_seqno = seqno; }
void s3f::s3fnet::TCPSeqWindow::shift (uint32 offset) inline
Increase the lower edge of the window by offset number of bytes.
Definition at line 71 of file tcp_seqwnd.h.
References mymin, start_seqno, and used_size.
Referenced by s3f::s3fnet::TCPRecvWindow::generate(), and s3f::s3fnet::TCPSendWindow::release().
   {
     start_seqno += offset;
     used_size -= mymin(offset, used_size);
   }
void s3f::s3fnet::TCPSeqWindow::expand (uint32 nbytes) inline
Expand the window size by nbytes.
Note that the new size must not be larger than the buffer size—the condition is not enforced by this method.
Definition at line 80 of file tcp_seqwnd.h.
References win_size.
Referenced by s3f::s3fnet::TCPSession::calc_advertised_wnd().
 { win_size += nbytes; }
void s3f::s3fnet::TCPSeqWindow::shrink (uint32 nbytes) inline
Shrink the size of the window by nbytes.
One can only shrink the size of unused space.
Definition at line 84 of file tcp_seqwnd.h.
References used_size, and win_size.
   {
     assert(nbytes <= (win_size - used_size));
     win_size -= nbytes;
   }
bool s3f::s3fnet::TCPSeqWindow::use (uint32 nbytes) inline
Use up nbytes of the window with data.
Returns true if success, i.e., there is available unused space for this operation.
Definition at line 92 of file tcp_seqwnd.h.
References used_size, and win_size.
Referenced by s3f::s3fnet::TCPRecvWindow::addToBuffer(), and s3f::s3fnet::TCPSession::segment_and_send().
   {
     if(used_size + nbytes > win_size) return false;
     used_size += nbytes;
     return true;
   }
void s3f::s3fnet::TCPSeqWindow::setSYN (bool syn) inline
set SYN bit.
Definition at line 104 of file tcp_seqwnd.h.
References seq_shift(), syn_included, and used_size.
Referenced by s3f::s3fnet::TCPSession::init_state_syn_received(), s3f::s3fnet::TCPSession::init_state_syn_sent(), s3f::s3fnet::TCPSession::process_ACK(), and s3f::s3fnet::TCPSession::process_SYN().
   {
     if(syn) assert(used_size == 0);
     else seq_shift(1);
     syn_included = syn ? 1 : 0;
   }
void s3f::s3fnet::TCPSeqWindow::setFIN (bool fin) inline
set FIN bit.
Definition at line 112 of file tcp_seqwnd.h.
References fin_included, and seq_shift().
Referenced by s3f::s3fnet::TCPSession::appl_close(), s3f::s3fnet::TCPSession::init_state_fin_wait_1(), s3f::s3fnet::TCPSession::process_ACK(), and s3f::s3fnet::TCPSession::process_FIN().
   {
     if(!fin) seq_shift(1);
     fin_included = fin ? 1 : 0;
   }
bool s3f::s3fnet::TCPSeqWindow::synAtFront () inline
Return true if SYN segment is in the window.
Definition at line 119 of file tcp_seqwnd.h.
References syn_included.
Referenced by s3f::s3fnet::TCPSession::init_state_established().
 { return syn_included; }
bool s3f::s3fnet::TCPSeqWindow::finAtFront () inline
Return true if FIN segment is in the window.
Definition at line 122 of file tcp_seqwnd.h.
References fin_included, and used_size.
Referenced by s3f::s3fnet::TCPSession::init_state_established().
 { return (fin_included && used_size == 0); }
uint32 s3f::s3fnet::TCPSeqWindow::next () inline
Like firstUnused method, but also uses SYN & FIN segments; the method is used for sending window.
Definition at line 126 of file tcp_seqwnd.h.
References fin_included, start_seqno, syn_included, and used_size.
Referenced by s3f::s3fnet::TCPSession::abort(), s3f::s3fnet::TCPSession::init_state_last_ack(), s3f::s3fnet::TCPSession::init_state_syn_received(), s3f::s3fnet::TCPSession::process_ACK(), and s3f::s3fnet::TCPSession::process_acks().
 { return start_seqno+used_size+syn_included+fin_included; }
uint32 s3f::s3fnet::TCPSeqWindow::expect () inline
Like start method, but also uses SYN & FIN segments; the method is used for receiving window.
Definition at line 130 of file tcp_seqwnd.h.
References fin_included, start_seqno, and syn_included.
Referenced by s3f::s3fnet::TCPSession::abort(), s3f::s3fnet::TCPSession::appl_close(), s3f::s3fnet::TCPRecvWindow::available(), s3f::s3fnet::TCPSession::fastTimeoutHandling(), s3f::s3fnet::TCPRecvWindow::generate(), s3f::s3fnet::TCPRecvWindow::getExpectedSeqno(), s3f::s3fnet::TCPSession::init_state_fin_wait_1(), s3f::s3fnet::TCPSession::init_state_last_ack(), s3f::s3fnet::TCPSession::init_state_syn_received(), s3f::s3fnet::TCPSession::init_state_syn_sent(), s3f::s3fnet::TCPSession::process_ACK(), s3f::s3fnet::TCPSession::resend_segments(), s3f::s3fnet::TCPSession::segment_and_send(), s3f::s3fnet::TCPSession::slow_timeout_handling_helper(), and s3f::s3fnet::TCPSession::timeout_resend().
 { return start_seqno+syn_included+fin_included; }
bool s3f::s3fnet::TCPSeqWindow::within (uint32 seqno) inline
Returns true iff 'seqno' is within the window.
Definition at line 137 of file tcp_seqwnd.h.
References fin_included, start_seqno, syn_included, and win_size.
Referenced by s3f::s3fnet::TCPSession::process_new_data().
   {
     return (start_seqno+syn_included+fin_included <= seqno &&
             seqno < start_seqno+syn_included+fin_included+win_size);
   }
bool s3f::s3fnet::TCPSeqWindow::isUsed (uint32 seqno) inline
Returns true iff 'seqno' is used within the window.
Definition at line 144 of file tcp_seqwnd.h.
References start_seqno, and used_size.
   {
     return (start_seqno <= seqno && seqno < start_seqno + used_size);
   }
bool s3f::s3fnet::TCPSeqWindow::empty () inline
Returns true iff the window is empty (nothing used).
Definition at line 150 of file tcp_seqwnd.h.
References used_size.
Referenced by s3f::s3fnet::TCPSession::appl_close(), s3f::s3fnet::TCPSession::init_state_close_wait(), s3f::s3fnet::TCPSession::init_state_closing(), s3f::s3fnet::TCPSession::init_state_fin_wait_1(), s3f::s3fnet::TCPSession::process_FIN(), and s3f::s3fnet::TCPSession::receive().
 { return (used_size == 0); }
void s3f::s3fnet::TCPSeqWindow::reset () inline
Resets the window.
Definition at line 153 of file tcp_seqwnd.h.
References fin_included, syn_included, and used_size.
Referenced by s3f::s3fnet::TCPSession::init_state_listen(), and s3f::s3fnet::TCPSendWindow::reset().
 { used_size = 0; syn_included = fin_included = 0; }
void s3f::s3fnet::TCPSeqWindow::seq_shift (uint32 offset) inline protected
Shift the window by the given offset permanently.
Definition at line 157 of file tcp_seqwnd.h.
References start_seqno.
Referenced by setFIN(), and setSYN().
 { start_seqno += offset; }
Member Data Documentation
uint32 s3f::s3fnet::TCPSeqWindow::start_seqno protected
Starting sequence number of the window.
Definition at line 161 of file tcp_seqwnd.h.
Referenced by end(), expect(), firstUnused(), isUsed(), lengthTo(), next(), seq_shift(), setStart(), shift(), start(), and within().
uint32 s3f::s3fnet::TCPSeqWindow::win_size protected
Size of the window in bytes.
Definition at line 164 of file tcp_seqwnd.h.
Referenced by s3f::s3fnet::TCPRecvWindow::bufferSize(), end(), expand(), s3f::s3fnet::TCPRecvWindow::freeInBuffer(), shrink(), size(), unused(), use(), and within().
uint32 s3f::s3fnet::TCPSeqWindow::used_size protected
How many bytes are used in window.
Definition at line 167 of file tcp_seqwnd.h.
Referenced by empty(), finAtFront(), firstUnused(), isUsed(), next(), reset(), setSYN(), shift(), shrink(), unused(), use(), and used().
int s3f::s3fnet::TCPSeqWindow::syn_included protected
Whether SYN is in window.
Definition at line 170 of file tcp_seqwnd.h.
Referenced by expect(), next(), reset(), setSYN(), synAtFront(), and within().
int s3f::s3fnet::TCPSeqWindow::fin_included protected
Whether FIN is in window.
Definition at line 173 of file tcp_seqwnd.h.
Referenced by expect(), finAtFront(), next(), reset(), setFIN(), and within().
The documentation for this class was generated from the following file:
tcp_seqwnd.h