S3F: Message Class Reference
Message Class Reference
Messages passed between connected OutChannels and InChannels.
#include <message.h>
Public Member Functions
Message ()
Message (unsigned int)
Message (const Message &msg)
Message & operator= (Message const &msg)
unsigned int get_type ()
virtual Message * clone ()
virtual void erase ()
virtual void erase_all ()
virtual ~Message ()
void inc_evts ()
int dec_evts ()
Protected Attributes
unsigned int __type
int __evts
Detailed Description
Messages passed between connected OutChannels and InChannels.
Definition at line 17 of file message.h.
Constructor & Destructor Documentation
Message::Message ()
Definition at line 10 of file message.cc.
References __evts, and __type.
Referenced by clone().
 { __type = 0; __evts = 0;  }
Message::Message (unsigned int t)
Definition at line 11 of file message.cc.
References __evts, and __type.
 { __type = t; __evts = 0;  }
Message::Message (const Message & msg)
Definition at line 18 of file message.cc.
References __evts, and __type.
{
         __type = msg.__type;
         __evts = 0;
 }
Message::~Message () virtual
Definition at line 17 of file message.cc.
 { }
Member Function Documentation
Message & Message::operator= (Message const & msg)
Definition at line 23 of file message.cc.
References __evts, and __type.
{
         __type = msg.__type;
         __evts = 0;
         return *this;
 }
unsigned int Message::get_type () inline
Definition at line 23 of file message.h.
References __type.
 { return __type; }
Message * Message::clone () virtual
Reimplemented in s3f::s3fnet::DataMessage, s3f::s3fnet::ProtocolMessage, PholdMessage, s3f::s3fnet::TCPMessage, s3f::s3fnet::OpenFlowMessage, s3f::s3fnet::OpenVZMessage, s3f::s3fnet::SimpleMacMessage, s3f::s3fnet::DummyMessage, s3f::s3fnet::UDPMessage, and s3f::s3fnet::IPMessage.
Definition at line 29 of file message.cc.
References __evts, __type, and Message().
Referenced by OutChannel::write().
{
         Message* msg = new Message();
         msg->__type = __type;
         msg->__evts = 0;
         return msg;
 }
virtual void Message::erase () inline virtual
Reimplemented in s3f::s3fnet::ProtocolMessage.
Definition at line 25 of file message.h.
 {};
virtual void Message::erase_all () inline virtual
Reimplemented in s3f::s3fnet::ProtocolMessage.
Definition at line 26 of file message.h.
Referenced by s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::NetworkInterface::receivePacket(), and OutChannel::write().
 {};
void Message::inc_evts () inline
Definition at line 28 of file message.h.
References __evts.
Referenced by Event::Event().
 { __evts++; }
int Message::dec_evts () inline
Definition at line 29 of file message.h.
References __evts.
Referenced by Event::~Event().
 { return --__evts; }
Member Data Documentation
unsigned int Message::__type protected
Definition at line 31 of file message.h.
Referenced by clone(), get_type(), Message(), and operator=().
int Message::__evts protected
Definition at line 32 of file message.h.
Referenced by clone(), dec_evts(), inc_evts(), Message(), and operator=().
The documentation for this class was generated from the following files:
message.h
message.cc