S3F: s3f::s3fnet::LowestProtocolSession Class Reference
s3f::s3fnet::LowestProtocolSession Class Reference abstract
The lowest protocol session in the protocol stack.
#include <lowest_protocol_session.h>
Public Types
enum InstantiationType { PROT_UNIQUE_INSTANCE = 0x00, PROT_MULTIPLE_INSTANCES = 0x01, PROT_MULTIPLE_IMPLEMENTATIONS = 0x02 }
Multiple protocol session instantiation type.
enum ExecutionStage { PSESS_CREATED = 0, PSESS_CONFIGURED = 1, PSESS_INITIALIZED = 2, PSESS_WRAPPED_UP = 3 }
A normal protocol session must go though the following stages.
Public Member Functions
LowestProtocolSession (ProtocolGraph *graph)
The constructor.
virtual int control (int ctrltyp, void *ctrlmsg, ProtocolSession *sess)
Handle the control messages.
virtual void sendPacket (Activation pkt, ltime_t delay)=0
Derived class should use this method to send packet frames out from the host to its peer(s).
virtual void receivePacket (Activation pkt, int nw_iface=0)=0
The method is called by the interface when a packet has arrived.
NetworkInterface * getNetworkInterface ()
Return a pointer to the owner interface.
virtual Host * inHost ()
Return a pointer to the host owning this protocol session.
virtual void config (s3f::dml::Configuration *cfg)
The config method is used to configure the protocol session from DML description.
virtual void init ()
The method is used to initialize the protocol session once the protocol session has been created and configured.
virtual void wrapup ()
The method is used to wrap up the protocol session.
int pushdown (Activation msg, ProtocolSession *hi_sess, void *extinfo=0, size_t extinfo_size=0)
The original push method is divided into pushdown() and push().
int popup (Activation msg, ProtocolSession *lo_sess, void *extinfo=0, size_t extinfo_size=0)
The original pop method is divided into popup() and pop().
ProtocolGraph * inGraph ()
The method returns the protocol graph in which this protocol session resides.
virtual int getProtocolNumber ()=0
Each protocol session should have its unique protocol number.
Random::RNG * getRandom ()
The method returns a pointer to the random number generator.
ltime_t getNow ()
The method returns the current simulation time.
char * getNowWithThousandSeparator ()
For printing the current simulation time in a better readable format.
int configured ()
This method returns true if the protocol session has been configured.
int initialized ()
This method returns true if the protocol session has been initialized.
int wrapped_up ()
This method returns true if the protocol session has been wrapped up.
virtual const char * psesstype ()
Public Attributes
char * name
Symbolic name of the protocol this session implements.
float version
Version number of this protocol implemenntation, represented as a floating point number (e.g., 1.23).
char * use
Name of the protocol class from which this protocol session is instantiated.
Protected Member Functions
virtual int instantiation_type ()
This method controls how protocol instances can coexist with one another.
Protected Attributes
ProtocolSession * parent_prot
The pointer to the upper layer.
ProtocolSession * child_prot
The pointer to the lower protocol session.
ProtocolGraph * ingraph
Points to the protocol graph.
Random::RNG * sess_rng
Pointer to a random number generator.
int stage
This variable indicates the current stage of this protocol session.
Detailed Description
The lowest protocol session in the protocol stack.
The LowestProtocolSession class is the base class of the lowest protocol session in an interface, thus also the lowest in a protocol graph. It provides methods to receive packet frame from the neighboring hosts.
Definition at line 24 of file lowest_protocol_session.h.
Member Enumeration Documentation
enum s3f::s3fnet::ProtocolSession::InstantiationType inherited
Multiple protocol session instantiation type.
Enumerator
PROT_UNIQUE_INSTANCE
PROT_MULTIPLE_INSTANCES
PROT_MULTIPLE_IMPLEMENTATIONS
Definition at line 44 of file protocol_session.h.
{
     PROT_UNIQUE_INSTANCE                = 0x00,
     PROT_MULTIPLE_INSTANCES             = 0x01,
     PROT_MULTIPLE_IMPLEMENTATIONS       = 0x02
   };
enum s3f::s3fnet::ProtocolSession::ExecutionStage inherited
A normal protocol session must go though the following stages.
Enumerator
PSESS_CREATED
this protocol session has just been created
PSESS_CONFIGURED
the config method of this protocol session has been called
PSESS_INITIALIZED
the init method of this protocol session has been called
PSESS_WRAPPED_UP
Definition at line 51 of file protocol_session.h.
                       {
     PSESS_CREATED       = 0,
     PSESS_CONFIGURED    = 1,
     PSESS_INITIALIZED   = 2,
     PSESS_WRAPPED_UP    = 3
   };
Constructor & Destructor Documentation
s3f::s3fnet::LowestProtocolSession::LowestProtocolSession (ProtocolGraph * graph) inline
The constructor.
Definition at line 27 of file lowest_protocol_session.h.
 : NicProtocolSession(graph) {}
Member Function Documentation
int s3f::s3fnet::LowestProtocolSession::control (int ctrltyp, void * ctrlmsg, ProtocolSession * sess) virtual
Handle the control messages.
This control method only recognizes PSESS_CTRL_SESSION_IS_LOWEST control message (called from from the protocol graph).
Reimplemented from s3f::s3fnet::NicProtocolSession.
Reimplemented in s3f::s3fnet::SimplePhy.
Definition at line 13 of file lowest_protocol_session.cc.
References s3f::s3fnet::NicProtocolSession::control(), and s3f::s3fnet::PSESS_CTRL_SESSION_IS_LOWEST.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Link::connect(), s3f::s3fnet::SimplePhy::control(), and s3f::s3fnet::NicQueue::init().
 {
    if(ctype == PSESS_CTRL_SESSION_IS_LOWEST)
    {
      assert(cmsg);
      *((bool*)cmsg) = true;
      return 0;
    }
    else return NicProtocolSession::control(ctype, cmsg, sess);
 }
virtual void s3f::s3fnet::LowestProtocolSession::sendPacket (Activation pkt, ltime_t delay) pure virtual
Derived class should use this method to send packet frames out from the host to its peer(s).
The protocol messages sent down to this protocol session should be wrapped with a packet first before being delivered. A delay is provided as the second argument, which models the time needed for physical device to start transmitting the packet.
Implemented in s3f::s3fnet::SimplePhy.
Referenced by s3f::s3fnet::DroptailQueue::enqueue(), and s3f::s3fnet::RedQueue::enqueue().
virtual void s3f::s3fnet::LowestProtocolSession::receivePacket (Activation pkt, int nw_iface = 0) pure virtual
The method is called by the interface when a packet has arrived.
Derived class must overload this method to accept arrival packet.
Implemented in s3f::s3fnet::SimplePhy.
Referenced by s3f::s3fnet::NetworkInterface::receivePacket().
NetworkInterface * s3f::s3fnet::NicProtocolSession::getNetworkInterface () inherited
Return a pointer to the owner interface.
Definition at line 37 of file nic_protocol_session.cc.
References s3f::s3fnet::ProtocolSession::ingraph.
Referenced by s3f::s3fnet::NicProtocolSession::control(), s3f::s3fnet::NicProtocolSession::inHost(), s3f::s3fnet::SimpleMac::init(), s3f::s3fnet::SimplePhy::init(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::SimplePhy::push(), s3f::s3fnet::SimplePhy::receivePacket(), and s3f::s3fnet::SimplePhy::sendPacket().
 {
   return dynamic_cast<NetworkInterface*>(ingraph);
 }
Host * s3f::s3fnet::NicProtocolSession::inHost () virtual inherited
Return a pointer to the host owning this protocol session.
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 42 of file nic_protocol_session.cc.
References s3f::s3fnet::NetworkInterface::getHost(), and s3f::s3fnet::NicProtocolSession::getNetworkInterface().
Referenced by s3f::s3fnet::DroptailQueue::calibrate(), s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::SimplePhy::config(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::DroptailQueue::init(), s3f::s3fnet::SimpleMac::pop(), and s3f::s3fnet::SimpleMac::push().
 {
   return getNetworkInterface()->getHost();
 }
void s3f::s3fnet::ProtocolSession::config (s3f::dml::Configuration * cfg) virtual inherited
The config method is used to configure the protocol session from DML description.
It is expected to be called first, right after the ProtocolSession object is created and before the init method is called. A DML configuration should be passed as an argument to the method and it should be the value (a list of attributes) of a 'session' attribute (inside 'graph'). The default behavior of this method is to find out 'name' and 'use' attributes. The derived class should override this method to obtain protocol specific parameters from the DML description. However, the derived class must not forget to call this method in the base class so that the default behavior is carried out. The config method recognizes the following attributes:
name: name of the protocol session (required)
use: protocol class name (required)
It is important to note that the timer still cannot be used at this stage since the owner community hasn't been resolved. It has to wait until after the init method is called.
Reimplemented in s3f::s3fnet::NBTCPServerSession, s3f::s3fnet::IPSession, s3f::s3fnet::OpenFlowSwitchSession, s3f::s3fnet::BTCPClientSession, s3f::s3fnet::NBTCPClientSession, s3f::s3fnet::TCPMaster, s3f::s3fnet::TCPServerSession, s3f::s3fnet::UDPClientSession, s3f::s3fnet::SimplePhy, s3f::s3fnet::UDPServerSession, s3f::s3fnet::OpenVZEventSession, s3f::s3fnet::OpenFlowControllerSession, s3f::s3fnet::TCPClientSession, s3f::s3fnet::DummySession, and s3f::s3fnet::UDPMaster.
Definition at line 21 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::configured(), s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolSession::name, s3f::s3fnet::ProtocolSession::PSESS_CONFIGURED, s3f::s3fnet::sstrdup(), s3f::s3fnet::ProtocolSession::stage, and s3f::s3fnet::ProtocolSession::use.
Referenced by s3f::s3fnet::UDPMaster::config(), s3f::s3fnet::DummySession::config(), s3f::s3fnet::TCPClientSession::config(), s3f::s3fnet::OpenFlowControllerSession::config(), s3f::s3fnet::OpenVZEventSession::config(), s3f::s3fnet::UDPServerSession::config(), s3f::s3fnet::SimplePhy::config(), s3f::s3fnet::UDPClientSession::config(), s3f::s3fnet::TCPServerSession::config(), s3f::s3fnet::TCPMaster::config(), s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::NBTCPClientSession::config(), s3f::s3fnet::BTCPClientSession::config(), s3f::s3fnet::OpenFlowSwitchSession::config(), s3f::s3fnet::IPSession::config(), s3f::s3fnet::NBTCPServerSession::config(), and s3f::s3fnet::ProtocolGraph::config_session().
 {
   if(configured())
     error_quit("ERROR: duplicate calls to ProtocolSession::config(): "
                "session name is \"%s\".\n", name);
   else stage = PSESS_CONFIGURED;
   char* myname = (char*)cfg->findSingle("name");
   if(myname && s3f::dml::dmlConfig::isConf(myname))
     error_quit("ERROR: ProtocolSession::config(), invalid NAME attribute.\n");
   if(myname) name = sstrdup(myname);
   else name = 0; // cannot do assertion because it may happen for a "default" interface
   char* myuse  = (char*)cfg->findSingle("use");
   if(myuse && s3f::dml::dmlConfig::isConf(myuse))
     error_quit("ERROR: ProtocolSession::config(), invalid USE attribute.\n");
   if(myuse)  use = sstrdup(myuse);
   else use = 0; // cannot do assertion because it may happen for a "default" interface
 }
void s3f::s3fnet::ProtocolSession::init () virtual inherited
The method is used to initialize the protocol session once the protocol session has been created and configured.
The default behavior is doing nothing. The derived class may override this method for protocol specific initialization. Note that the order of initialization of the protocol sessions in a protocol graph is unspecified. Don't rely on the ordering to help sort out the relationships between protocols.
Reimplemented in s3f::s3fnet::NBTCPServerSession, s3f::s3fnet::NBSocketMaster, s3f::s3fnet::IPSession, s3f::s3fnet::SocketMaster, s3f::s3fnet::BTCPClientSession, s3f::s3fnet::NBTCPClientSession, s3f::s3fnet::OpenFlowSwitchSession, s3f::s3fnet::TCPMaster, s3f::s3fnet::TCPServerSession, s3f::s3fnet::UDPClientSession, s3f::s3fnet::UDPServerSession, s3f::s3fnet::TCPClientSession, s3f::s3fnet::SimplePhy, s3f::s3fnet::OpenVZEventSession, s3f::s3fnet::OpenFlowControllerSession, s3f::s3fnet::UDPMaster, s3f::s3fnet::DummySession, and s3f::s3fnet::SimpleMac.
Definition at line 41 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::configured(), s3f::s3fnet::error_quit(), s3f::s3fnet::Host::getRandom(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::ProtocolSession::initialized(), s3f::s3fnet::ProtocolSession::name, s3f::s3fnet::ProtocolSession::PSESS_INITIALIZED, s3f::s3fnet::ProtocolSession::sess_rng, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::SimpleMac::init(), s3f::s3fnet::DummySession::init(), s3f::s3fnet::UDPMaster::init(), s3f::s3fnet::OpenFlowControllerSession::init(), s3f::s3fnet::OpenVZEventSession::init(), s3f::s3fnet::SimplePhy::init(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPServerSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::TCPServerSession::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::OpenFlowSwitchSession::init(), s3f::s3fnet::NBTCPClientSession::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::SocketMaster::init(), s3f::s3fnet::IPSession::init(), s3f::s3fnet::NBSocketMaster::init(), and s3f::s3fnet::NBTCPServerSession::init().
 {
   // Make sure this init function at the base class should be called
   // by the derived function!
   if(!configured())
     error_quit("ERROR: ProtocolSession \"%s\" init() called before config(), "
                "forgot to call base class's config() in your derived class?\n", name);
   else if(initialized())
     error_quit("ERROR: duplicate calls to ProtocolSession::init(): "
                "session name is \"%s\".\n", name);
   else stage = PSESS_INITIALIZED;
   if(inHost()->getHostSeed() == 0) //host-level rng, i.e. same rng within one host
           sess_rng = inHost()->getRandom();
   else
           sess_rng = new Random::RNG();
 }
void s3f::s3fnet::ProtocolSession::wrapup () virtual inherited
The method is used to wrap up the protocol session.
It is called when the simulation finishes. It is designed to give user a chance to report simulation statistics. The default behavior is doing nothing. Subclass may override this method for protocol specific dealings. Note that there is no specific order in which wrapup is called for protocol sessions in a protocol graph.
Definition at line 59 of file protocol_session.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolSession::initialized(), s3f::s3fnet::ProtocolSession::name, s3f::s3fnet::ProtocolSession::PSESS_WRAPPED_UP, s3f::s3fnet::ProtocolSession::stage, and s3f::s3fnet::ProtocolSession::wrapped_up().
 {
   // Make sure this init function at the base class should be called
   // by the derived function!
   if(!initialized())
     error_quit("ERROR: ProtocolSession \"%s\" wrapup() called before init(), "
                "forgot to call base class's init() in your derived class?\n", name);
   else if(wrapped_up())
     error_quit("ERROR: duplicate calls to ProtocolSession::wrapup(): "
                "session name is \"%s\".\n", name);
   else stage = PSESS_WRAPPED_UP;
 }
int s3f::s3fnet::ProtocolSession::pushdown (Activation msg, ProtocolSession * hi_sess, void * extinfo = 0, size_t extinfo_size = 0) inherited
The original push method is divided into pushdown() and push().
The pushdown method is the generic part of the code, which is reserved for modeling the handling of messages transferred between protocol layers.
See Also
ProtocolSession::push method for details.
Definition at line 72 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::push().
Referenced by s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), s3f::s3fnet::IPSession::control(), s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), s3f::s3fnet::OpenFlowSwitchSession::OutputControl(), s3f::s3fnet::OpenFlowSwitchSession::OutputPacket(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::UDPMaster::push(), s3f::s3fnet::TCPMaster::push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::send(), and s3f::s3fnet::TCPSession::send_data().
 {
   return push(msg, hi_sess, extinfo, extinfo_size);
 }
int s3f::s3fnet::ProtocolSession::popup (Activation msg, ProtocolSession * lo_sess, void * extinfo = 0, size_t extinfo_size = 0) inherited
The original pop method is divided into popup() and pop().
The popup method is the generic part of the code, which is reserved for modeling the handling of messages transferred between protocol layers.
See Also
ProtocolSession::pop method for details.
Definition at line 77 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::pop().
Referenced by s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::IPSession::push(), and s3f::s3fnet::SimplePhy::receivePacket().
 {
   return pop(msg, lo_sess, extinfo, extinfo_size);
 }
ProtocolGraph* s3f::s3fnet::ProtocolSession::inGraph () inline inherited
The method returns the protocol graph in which this protocol session resides.
Definition at line 178 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::ingraph.
Referenced by s3f::s3fnet::SimplePhy::config(), s3f::s3fnet::SimplePhy::control(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::SimpleMac::init(), s3f::s3fnet::SimplePhy::init(), s3f::s3fnet::RedQueue::init(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::SimplePhy::push(), s3f::s3fnet::SimplePhy::receivePacket(), s3f::s3fnet::SimplePhy::sendPacket(), s3f::s3fnet::SimpleMac::SimpleMac(), s3f::s3fnet::SimplePhy::SimplePhy(), s3f::s3fnet::SimpleMac::~SimpleMac(), and s3f::s3fnet::SimplePhy::~SimplePhy().
 { return ingraph; }
virtual int s3f::s3fnet::ProtocolSession::getProtocolNumber () pure virtual inherited
Each protocol session should have its unique protocol number.
The number will be used to retrieve the protocol session object using the protocol graph's sessionForNumber() method. The derived class should override this method and return the correct protocol number. The default is zero. The protocol number should be the same as the type of the corresponding protocol message, which the protocol uses to interact with the protocol session below it. A protocol session may use the protocol message's type to demultiplex the protocol messages at the destination and send the message to the correct protocol session.
Implemented in s3f::s3fnet::NBTCPServerSession, s3f::s3fnet::NBSocketMaster, s3f::s3fnet::IPSession, s3f::s3fnet::SocketMaster, s3f::s3fnet::BTCPClientSession, s3f::s3fnet::NBTCPClientSession, s3f::s3fnet::OpenFlowSwitchSession, s3f::s3fnet::TCPServerSession, s3f::s3fnet::TCPMaster, s3f::s3fnet::UDPClientSession, s3f::s3fnet::SimplePhy, s3f::s3fnet::UDPServerSession, s3f::s3fnet::TCPClientSession, s3f::s3fnet::SimpleMac, s3f::s3fnet::UDPMaster, s3f::s3fnet::OpenVZEventSession, s3f::s3fnet::OpenFlowControllerSession, and s3f::s3fnet::DummySession.
Referenced by s3f::s3fnet::RedQueue::enqueue(), and s3f::s3fnet::ProtocolGraph::insert_session().
Random::RNG* s3f::s3fnet::ProtocolSession::getRandom () inline inherited
The method returns a pointer to the random number generator.
Definition at line 200 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::sess_rng.
Referenced by s3f::s3fnet::DroptailQueue::calibrate(), s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::DummySession::init(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), and s3f::s3fnet::NetworkInterface::receivePacket().
 { return sess_rng;}
ltime_t s3f::s3fnet::ProtocolSession::getNow () inherited
The method returns the current simulation time.
To be safe, please do NOT call this function after initialization and before wrapup phase. That is, it is unsafe to call this method in the constructor, destructor, config, init, and wrapup methods. The time service is carried out by the host's owner community. This method just directs the call to the community. It's given here for convenience.
Definition at line 123 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::inHost(), and Entity::now().
Referenced by s3f::s3fnet::DroptailQueue::calibrate(), s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::TCPMaster::enableFastTimeout(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::TCPMaster::fast_timer_callback_body(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::TCPSession::now(), s3f::s3fnet::OpenVZEventSession::pop(), s3f::s3fnet::TCPMaster::slow_timer_callback_body(), s3f::s3fnet::SocketMaster::socket(), s3f::s3fnet::NBSocketMaster::socket(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), and s3f::s3fnet::BTCPClientSession::start_on().
 {
   return inHost()->now();
 }
char * s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator () inherited
For printing the current simulation time in a better readable format.
Definition at line 128 of file protocol_session.cc.
References s3f::s3fnet::Host::getNowWithThousandSeparator(), and s3f::s3fnet::ProtocolSession::inHost().
Referenced by s3f::s3fnet::UDPSession::abort(), s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::UDPSession::connect(), s3f::s3fnet::TCPMaster::createSession(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::UDPServerSession::data_sent(), s3f::s3fnet::TCPServerSession::data_sent(), s3f::s3fnet::UDPSession::disconnect(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::UDPSession::listen(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), s3f::s3fnet::DummySession::pop(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::OpenVZEventSession::pop(), s3f::s3fnet::UDPMaster::pop(), s3f::s3fnet::TCPMaster::pop(), s3f::s3fnet::IPSession::pop(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::UDPMaster::push(), s3f::s3fnet::SimplePhy::push(), s3f::s3fnet::TCPMaster::push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::receive(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::SimplePhy::receivePacket(), s3f::s3fnet::UDPServerSession::request_received(), s3f::s3fnet::TCPServerSession::request_received(), s3f::s3fnet::UDPClientSession::request_sent(), s3f::s3fnet::TCPClientSession::request_sent(), s3f::s3fnet::UDPSession::send(), s3f::s3fnet::TCPSession::send_data(), s3f::s3fnet::SimplePhy::sendPacket(), s3f::s3fnet::UDPClientSession::server_connected(), s3f::s3fnet::TCPClientSession::server_connected(), s3f::s3fnet::BTCPClientSession::server_connected(), s3f::s3fnet::UDPServerSession::session_closed(), s3f::s3fnet::UDPClientSession::session_closed(), s3f::s3fnet::TCPClientSession::session_closed(), s3f::s3fnet::TCPServerSession::session_closed(), s3f::s3fnet::BTCPClientSession::session_closed(), s3f::s3fnet::TCPMaster::setConnected(), s3f::s3fnet::TCPMaster::setIdle(), s3f::s3fnet::TCPMaster::setListening(), s3f::s3fnet::UDPSession::setSource(), s3f::s3fnet::TCPSession::slowTimeoutHandling(), s3f::s3fnet::UDPServerSession::start_on(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPServerSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), s3f::s3fnet::BTCPClientSession::start_on(), s3f::s3fnet::TCPSession::TCPSession(), s3f::s3fnet::UDPClientSession::timeout(), s3f::s3fnet::TCPClientSession::timeout(), s3f::s3fnet::BTCPClientSession::timeout(), s3f::s3fnet::UDPSession::UDPSession(), s3f::s3fnet::TCPSession::update_timeout(), and s3f::s3fnet::UDPSession::wake_app().
 {
         return inHost()->getNowWithThousandSeparator();
 }
int s3f::s3fnet::ProtocolSession::configured () inline inherited
This method returns true if the protocol session has been configured.
This method is used to make sure we configure the protocol session before initializing it.
Definition at line 221 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_CONFIGURED, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::config(), and s3f::s3fnet::ProtocolSession::init().
 { return stage >= PSESS_CONFIGURED; }
int s3f::s3fnet::ProtocolSession::initialized () inline inherited
This method returns true if the protocol session has been initialized.
This can be used to sequence calls to the init method of protocol sessions. For example, if protocol session A requires protocol session B to be initialized before A can be initialized, A's init method can call B's init method as long as B's initialized() returns true. The system does not enforce any ordering in its calls the init methods of all protocol sessions declared in the dml configuration.
Definition at line 233 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_INITIALIZED, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::init(), and s3f::s3fnet::ProtocolSession::wrapup().
 { return stage >= PSESS_INITIALIZED; }
int s3f::s3fnet::ProtocolSession::wrapped_up () inline inherited
This method returns true if the protocol session has been wrapped up.
This can be used to sequence calls to the wrapup method of protocol sessions. For example, if protocol session A requires protocol session B to be wrapped up before A can be wrapped up, A's wrapup method can call B's wrapup method as long as B's wrapped_up() returns true. The system does not enforce any ordering in its calls the wrapup methods of all protocol sessions declared in the dml configuration.
Definition at line 245 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_WRAPPED_UP, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::wrapup().
 { return stage >= PSESS_WRAPPED_UP; }
virtual const char* s3f::s3fnet::ProtocolSession::psesstype () inline virtual inherited
Reimplemented in s3f::s3fnet::NBSocketMaster, and s3f::s3fnet::SocketMaster.
Definition at line 247 of file protocol_session.h.
 { return "GENERIC"; } // DEBUG
virtual int s3f::s3fnet::ProtocolSession::instantiation_type () inline protected virtual inherited
This method controls how protocol instances can coexist with one another.
It returns one of the following:
PROT_UNIQUE_INSTANCE (default): allows only one instance for each type of protocol per protocol stack;
PROT_MULTIPLE_INSTANCES: allows multiple instances of the same implementation for each type of protocol per protocol stack;
PROT_MULTIPLE_IMPLEMENTATIONS: allows multiple instances from different implementations of the same protocol to exist on the protocol stack.
Reimplemented in s3f::s3fnet::BTCPClientSession, and s3f::s3fnet::TCPClientSession.
Definition at line 269 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PROT_UNIQUE_INSTANCE.
Referenced by s3f::s3fnet::ProtocolGraph::insert_session().
 { return PROT_UNIQUE_INSTANCE; }
Member Data Documentation
ProtocolSession* s3f::s3fnet::NicProtocolSession::parent_prot protected inherited
The pointer to the upper layer.
Definition at line 44 of file nic_protocol_session.h.
Referenced by s3f::s3fnet::NicProtocolSession::control(), s3f::s3fnet::SimpleMac::pop(), and s3f::s3fnet::SimplePhy::receivePacket().
ProtocolSession* s3f::s3fnet::NicProtocolSession::child_prot protected inherited
The pointer to the lower protocol session.
Definition at line 47 of file nic_protocol_session.h.
Referenced by s3f::s3fnet::NicProtocolSession::control(), and s3f::s3fnet::SimpleMac::push().
char* s3f::s3fnet::ProtocolSession::name inherited
Symbolic name of the protocol this session implements.
The name of the protocol is derived from the DML 'name' attribute. It must not be NULL once the protocol session is configured.
Definition at line 63 of file protocol_session.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::SimpleMac::init(), s3f::s3fnet::UDPMaster::init(), s3f::s3fnet::SimplePhy::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::SocketMaster::init(), s3f::s3fnet::IPSession::init(), s3f::s3fnet::NBSocketMaster::init(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::ProtocolGraph::insert_session(), s3f::s3fnet::ProtocolSession::wrapup(), and s3f::s3fnet::ProtocolSession::~ProtocolSession().
float s3f::s3fnet::ProtocolSession::version inherited
Version number of this protocol implemenntation, represented as a floating point number (e.g., 1.23).
Definition at line 69 of file protocol_session.h.
char* s3f::s3fnet::ProtocolSession::use inherited
Name of the protocol class from which this protocol session is instantiated.
The protocol class must be registered with the Protocols class so that we will be able to instantiate an object from the class. (C++ does not support self-reflection). The class name must not be NULL once the protocol session is configured.
Definition at line 79 of file protocol_session.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::ProtocolGraph::insert_session(), and s3f::s3fnet::ProtocolSession::~ProtocolSession().
ProtocolGraph* s3f::s3fnet::ProtocolSession::ingraph protected inherited
Points to the protocol graph.
Definition at line 335 of file protocol_session.h.
Referenced by s3f::s3fnet::NicProtocolSession::getNetworkInterface(), s3f::s3fnet::ProtocolSession::inGraph(), and s3f::s3fnet::ProtocolSession::inHost().
Random::RNG* s3f::s3fnet::ProtocolSession::sess_rng protected inherited
Pointer to a random number generator.
Definition at line 338 of file protocol_session.h.
Referenced by s3f::s3fnet::ProtocolSession::getRandom(), and s3f::s3fnet::ProtocolSession::init().
int s3f::s3fnet::ProtocolSession::stage protected inherited
This variable indicates the current stage of this protocol session.
Each protocol session will go through four staged: PSESS_CREATED, PSESS_CONFIGURED, PSESS_INITIALIZED, and then PSESS_WRAPPED_UP.
Definition at line 346 of file protocol_session.h.
Referenced by s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::ProtocolSession::configured(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::ProtocolSession::initialized(), s3f::s3fnet::ProtocolSession::wrapped_up(), and s3f::s3fnet::ProtocolSession::wrapup().
The documentation for this class was generated from the following files:
lowest_protocol_session.h
lowest_protocol_session.cc