S3F: pHold_Node Class Reference
pHold_Node Class Reference
class of phold node, implemented as an S3F entity
#include <phold_node.h>
Public Member Functions
pHold_Node ()
default constructor
pHold_Node (Timeline *tl, string name, int id, int ports)
constructor
void init ()
Establish the mappings from this node's outchannel's to the inchannels of the others.
void listen (Activation)
"listen" waits on an inchannel.
void talk (Activation)
after the waitsFor period specified in "listen", the "talk" process acts.
ltime_t now ()
Time on Entity's Timeline, either the time at which the current (or most recent) event on the timeline was executed, or the end of the last synchronization window.
Timeline * alignment ()
Returns pointer to the Timeline on which this Entity is aligned.
HandleCode waitFor (Process *proc, Activation act, ltime_t waitinterval)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
HandleCode waitFor (Process *proc, ltime_t waitinterval)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
HandleCode waitFor (Process *proc, Activation act, ltime_t waitinterval, unsigned int)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
HandleCode waitFor (Process *proc, ltime_t waitinterval, unsigned int)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
HandleCode waitFor (Activation act, ltime_t waitinterval)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
HandleCode waitFor (ltime_t waitinterval)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
HandleCode waitFor (Activation act, ltime_t waitinterval, unsigned int)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
HandleCode waitFor (ltime_t waitinterval, unsigned int)
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
unsigned int s3fid ()
Unique identifier for Entity, index 0 to total number of Entities created.
string getName ()
Return the text name ("" if none was given at initialization)
InChannel * getInChannel (string)
When an InChannel is create it can provide a text name, unique among InChannels on the same Entity.
Process * getProcess (string)
When a Process is create it can provide a text name, unique among Processes on the same Entity.
double t2d (ltime_t t)
Conversion routines to translate from clock ticks to double precision.
double t2d (ltime_t t, int s)
Conversion routines to translate from clock ticks to double precision.
ltime_t d2t (double d)
Conversion routines to translate from double precision to clock ticks.
ltime_t d2t (double d, int s)
Conversion routines to translate from double precision to clock ticks.
Static Public Member Functions
static Entity * getEntity (string)
Directory look up of the Entity pointer, given its text name.
Public Attributes
int myid
unique node id
int myports
for computing the next out message; equal to the number of node
InChannel ** ic
list of InChannels of this node
OutChannel ** oc
list of OutChannels of this node
Process * listen_proc
S3F process, listen on InChannels.
Process * talk_proc
S3F process, act after an activation is received on an InChannel.
Random::RNG rng
random number
int next_out
for computing the target outChannel for the next out message
long recvd
count of total activations (listen + talk)
Protected Member Functions
void BuildEntity (Timeline *)
The core of the Entity construction is done by BuildEntity.
ltime_t min_sync_cross_timeline_delay (ltime_t)
Among all outbound cross-timeline connections with OutChannels in this Entity, find the smallest min-delay that is at least as large as the argument.
ltime_t min_sync_all_timeline_delay (ltime_t)
Among all outbound connections with OutChannels in this Entity, find the smallest min-delay that is at least as large as the argument.
unsigned int count_min_delay_crossings (ltime_t)
Count the number of outbound cross-timeline connections with minimum delay at least as large as thrs.
Protected Attributes
string __name
text name given at initialization
Timeline * __timeline
pointer to Timeline on which this Entity is aligned
unsigned int __s3fid
Unique identity for Entity.
int __log_ticks_per_sec
time-scale of clock.
vector< OutChannel * > __outchannel_list
list of outchannels owned by this entity
vector< InChannel * > __inchannel_list
list of inchannels owned by this entity
vector< Process * > __process_list
list of processes owned by this entity
map< string, Process * > ProcessName
map< string, InChannel * > InChannelName
directory of inchannels declared with string names
pthread_mutex_t entity_inst_mutex
mutex for access to Entity instances state
Static Protected Attributes
static double __pow [36]
pow[i] = 10^{i-18}.
static map< string, Entity * > EntityName
Entity text to Pointer Directory.
static pthread_mutex_t entity_class_mutex
Mutex that protects access to Entity state.
static unsigned int __num_entities = 0
counter of number of entities created
Detailed Description
class of phold node, implemented as an S3F entity
Definition at line 14 of file phold_node.h.
Constructor & Destructor Documentation
pHold_Node::pHold_Node ()
default constructor
pHold_Node::pHold_Node (Timeline * tl, string name, int id, int ports)
constructor
Parameters
tl the timeline that this entity is algined to.
name name of the phold node entity.
id assign to myid
ports assign to myports
Definition at line 30 of file phold_node.cc.
References ic, Entity::InChannel, listen(), listen_proc, myid, myports, next_out, oc, Entity::OutChannel, Entity::Process, recvd, talk(), and talk_proc.
                                                                     :
                         Entity(tl,name) {
         myid = id;
         myports = ports;
         int i;
         ic = new InChannel*[ports+1];
         for(i=0; i<ports; i++) {
                 stringstream ss;
                 ss << "IC-" << i;
                 ic[i] = new InChannel( (Entity *)this, ss.str());
         }
         ic[ports] = 0;
         oc = new OutChannel*[ports];
         for(i=0; i<ports; i++) {
                 oc[i] = new OutChannel(this,1);
         }
         next_out = id;
         recvd = 0;
         listen_proc =
                         new Process( (Entity *)this, (void (s3f::Entity::*)(s3f::Activation))&pHold_Node::listen);
         talk_proc =
                         new Process( (Entity *)this, (void (s3f::Entity::*)(s3f::Activation))&pHold_Node::talk);
         // make a lasting binding of the "listen" process to the in-channels
         for(i=0; i<ports; i++)
                 ic[i]->bind(listen_proc);
 }
Member Function Documentation
void pHold_Node::init () virtual
Establish the mappings from this node's outchannel's to the inchannels of the others.
Show use of name directories
Reimplemented from Entity.
Definition at line 131 of file phold_node.cc.
References Entity::getEntity(), Entity::getInChannel(), OutChannel::mapto(), myid, myports, next_out, oc, Entity::s3fid(), TRANSFER_DELAY, and OutChannel::write().
                       {
         // establish the mappings from this node's outchannel's
         // to the inchannels of the others.  Show use of
         // name directories
         //
         int i;
         for(i=0; i<myports; i++) {
                 // make the name of the entity we are targeting
                 stringstream en;
                 en << "Entity-" << i;
                 // Fetch the address of that entity
                 Entity* e = Entity::getEntity(en.str());
                 assert(e != NULL);
                 // construct the name of the InChannel we target.  It
                 // contains this entity's identity, i.e. Entity j targets
                 // inchannel j on each of the entities it communicates with
                 //
                 stringstream in;
                 in << "IC-" << s3fid();
                 // get the address of that inchannel on that entity
                 //
                 InChannel *inc = e->getInChannel(in.str());
                 assert(inc != NULL);
                 // now do the mapping
                 oc[i]->mapto(inc, TRANSFER_DELAY);
         }
         next_out = (myid+1)%myports;
         Activation act( new PholdMessage((myid<<8)));
         for(i=0; i<myports; i++) {
                 oc[i]->write( act, (ltime_t ) 0 , myid);
         }
 }
void pHold_Node::listen (Activation ac)
"listen" waits on an inchannel.
On receiving an activation, it samples a waiting time, and waitsFor that period
Definition at line 77 of file phold_node.cc.
References Entity::d2t(), Random::RNG::Exponential(), myid, Entity::now(), recvd, rng, talk_proc, and Entity::waitFor().
Referenced by pHold_Node().
 {
         recvd++;
         // sample exponential with mean 1/10, assume time-scale is milliseconds
         double millisecs = rng.Exponential(0.1);
         // schedule execution of process "talk" at a time in the future
         // equivalent to the exponential sample interpreted as milliseconds,
         // and pass the given activation along
         //
         ltime_t ticks = d2t(millisecs,3)+1;
         // create a shared pointer to PholdMessage from ac (which we know
         // is a shared pointer to a PholdMessage
         //    One can get at the pointer wrapped in ac by ac.get(),
         // see the printf statement below
         //
         // tr1::shared_ptr<PholdMessage> phm = tr1::dynamic_pointer_cast<PholdMessage>(ac);
         // PholdMessage *phm;
         // Activation ac1( phm=new PholdMessage(ticks) );
         // ac.reset( new PholdMessage(ticks) );
 #ifdef DEBUG
         int id = ((PholdMessage*)ac)->msg_id();
         printf("PH At %ld (%ld) listen on %d receives activation %x, waiting until time %ld\n", now(), recvd, myid, id, now()+ticks);
 #endif
         //HandleCode h = waitFor( talk_proc, ac, ticks, myid );
         waitFor( talk_proc, ac, ticks, myid );
         // uncomment to exercise cancellation logic
         //
         // HandlePtr hptr(new Handle(h));
         // hptr->cancel();
         // waitFor( talk_proc, ac, ticks, myid );
 }
void pHold_Node::talk (Activation ac)
after the waitsFor period specified in "listen", the "talk" process acts.
Definition at line 114 of file phold_node.cc.
References myid, myports, next_out, Entity::now(), oc, recvd, and OutChannel::write().
Referenced by pHold_Node().
 {
         recvd++;
         int tgt = next_out%myports;
         // Activation ac1( phm = new PholdMessage(now()));
 #ifdef DEBUG
         int id = ((PholdMessage *)ac)->msg_id();
         printf("PH At %ld (%ld) talk on %d receives activation %x, writing to %d with %x\n", now(), recvd, myid, id, tgt, id );
 #endif
         if(myports> 0) {
                 oc[tgt]->write(ac ,  (ltime_t) 0, myid);
                 // oc[tgt]->write(ac , (ltime_t)(tgt+1));
                 next_out++;
         }
 }
ltime_t Entity::now () inherited
Time on Entity's Timeline, either the time at which the current (or most recent) event on the timeline was executed, or the end of the last synchronization window.
Definition at line 111 of file entity.cc.
References Entity::__timeline, and Timeline::now().
Referenced by s3f::s3fnet::SocketMaster::abort(), s3f::s3fnet::NBSocketMaster::abort(), s3f::s3fnet::SocketMaster::accept(), s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::accept1a(), s3f::s3fnet::SocketMaster::accept1b(), s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SocketMaster::accept2b(), s3f::s3fnet::OpenFlowSwitchSession::AddFlow(), s3f::s3fnet::SocketMaster::bind(), s3f::s3fnet::NBSocketMaster::bind(), s3f::s3fnet::SocketMaster::block_till(), s3f::s3fnet::NBSocketMaster::block_till(), s3f::s3fnet::SocketMaster::close(), s3f::s3fnet::NBSocketMaster::close(), s3f::s3fnet::SocketMaster::close1(), s3f::s3fnet::NBSocketMaster::close1(), s3f::s3fnet::SocketMaster::connect(), s3f::s3fnet::NBSocketMaster::connect(), s3f::s3fnet::SocketMaster::connect1(), s3f::s3fnet::NBSocketMaster::connect1(), s3f::s3fnet::SocketMaster::connected(), s3f::s3fnet::NBSocketMaster::connected(), s3f::s3fnet::SocketMaster::control(), s3f::s3fnet::NBSocketMaster::control(), s3f::s3fnet::SocketMaster::eof(), s3f::s3fnet::NBSocketMaster::eof(), s3f::s3fnet::Stats::FlowStatsDump(), s3f::s3fnet::ProtocolSession::getNow(), s3f::s3fnet::Host::getNowWithThousandSeparator(), listen(), s3f::s3fnet::SocketMaster::listen(), s3f::s3fnet::NBSocketMaster::listen(), OutChannel::mapto(), OutChannel::new_min_write_delay(), s3f::s3fnet::OpenFlowSwitchSession::pop(), s3f::s3fnet::SocketMaster::recv(), s3f::s3fnet::NBSocketMaster::recv(), s3f::s3fnet::SocketMaster::recv1(), s3f::s3fnet::NBSocketMaster::recv1(), s3f::s3fnet::SocketMaster::send(), s3f::s3fnet::NBSocketMaster::send(), s3f::s3fnet::SocketMaster::send1(), s3f::s3fnet::NBSocketMaster::send1(), talk(), Entity::waitFor(), and OutChannel::write().
 { return __timeline->now(); };
Timeline * Entity::alignment () inherited
Returns pointer to the Timeline on which this Entity is aligned.
Definition at line 120 of file entity.cc.
References Entity::__timeline.
Referenced by s3f::s3fnet::Host::init(), OutChannel::mapto(), Process::Process(), Timeline::schedule(), Entity::waitFor(), and OutChannel::write().
 { return __timeline; }
HandleCode Entity::waitFor (Process * proc, Activation act, ltime_t waitinterval) inherited
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
The named process must be owned by an entity aligned to this timeline—checked by the Timeline::schedule method. A HandleCode object is returned, it can be used to cancel the scheduled activation. No priority is included, so Timeline::default_schedule_pri is used as a basis.
Parameters
waitinterval wait interval (from now) that S3F will process the activation.
act activation (event); If no Activation is included, one is created with NULL as the protected pointer.
proc The process to execute. Must be owned by an Entity that is co-aligned with this Entity. If no process in included, the default process of this Entity is used.
Definition at line 148 of file entity.cc.
References Entity::alignment(), Timeline::default_sched_pri, Entity::now(), Timeline::schedule(), and user_pri.
Referenced by s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::UDPServerSession::client_connected(), s3f::s3fnet::TCPMaster::enableFastTimeout(), s3f::s3fnet::TCPMaster::fast_timer_callback_body(), s3f::s3fnet::DummySession::init(), s3f::s3fnet::UDPServerSession::init(), s3f::s3fnet::TCPServerSession::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::NBTCPClientSession::init(), s3f::s3fnet::NBTCPServerSession::init(), s3f::s3fnet::OpenVZEventSession::injectEvent(), listen(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), s3f::s3fnet::UDPClientSession::request_sent(), s3f::s3fnet::TCPClientSession::request_sent(), s3f::s3fnet::BTCPClientSession::server_connected(), and s3f::s3fnet::TCPMaster::slow_timer_callback_body().
{
       return alignment()->schedule( proc, now()+delay, user_pri(Timeline::default_sched_pri), act);
    }
HandleCode Entity::waitFor (Process * proc, ltime_t waitinterval) inherited
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
The named process must be owned by an entity aligned to this timeline—checked by the Timeline::schedule method. A HandleCode object is returned, it can be used to cancel the scheduled activation. No priority is included, so Timeline::default_schedule_pri is used as a basis. No Activation is included, so one is created with NULL as the protected pointer.
Parameters
waitinterval wait interval (from now) that S3F will process the activation.
proc The process to execute. Must be owned by an Entity that is co-aligned with this Entity. If no process in included, the default process of this Entity is used.
Definition at line 162 of file entity.cc.
References Entity::alignment(), Timeline::default_sched_pri, Entity::now(), Timeline::schedule(), and user_pri.
{
      Message* m = NULL;
      Activation act(m);
      return alignment()->schedule( proc, now()+delay, user_pri(Timeline::default_sched_pri), act);
    }
HandleCode Entity::waitFor (Process * proc, Activation act, ltime_t waitinterval, unsigned int pri) inherited
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
The named process must be owned by an entity aligned to this timeline—checked by the Timeline::schedule method. A HandleCode object is returned, it can be used to cancel the scheduled activation.
Parameters
waitinterval wait interval (from now) that S3F will process the activation.
act activation (event); If no Activation is included, one is created with NULL as the protected pointer.
proc The process to execute. Must be owned by an Entity that is co-aligned with this Entity. If no process in included, the default process of this Entity is used.
pri A tie-breaking priority. If no priority is included, Timeline::default_schedule_pri is used as a basis.
Definition at line 152 of file entity.cc.
References Entity::alignment(), Entity::now(), Timeline::schedule(), and user_pri.
{
       return alignment()->schedule( proc, now()+delay, user_pri(pri), act);
    }
HandleCode Entity::waitFor (Process * proc, ltime_t waitinterval, unsigned int pri) inherited
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
The named process must be owned by an entity aligned to this timeline—checked by the Timeline::schedule method. A HandleCode object is returned, it can be used to cancel the scheduled activation. No Activation is included, so one is created with NULL as the protected pointer.
Parameters
waitinterval wait interval (from now) that S3F will process the activation.
proc The process to execute. Must be owned by an Entity that is co-aligned with this Entity. If no process in included, the default process of this Entity is used.
pri A tie-breaking priority. If no priority is included, Timeline::default_schedule_pri is used as a basis.
Definition at line 156 of file entity.cc.
References Entity::alignment(), Entity::now(), Timeline::schedule(), and user_pri.
{
      Message* m = NULL;
      Activation act(m);
      return alignment()->schedule( proc, now()+delay, user_pri(pri), act);
    }
HandleCode Entity::waitFor (Activation act, ltime_t waitinterval) inherited
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
The named process must be owned by an entity aligned to this timeline—checked by the Timeline::schedule method. A HandleCode object is returned, it can be used to cancel the scheduled activation. No priority is included, so Timeline::default_schedule_pri is used as a basis. No process in included, so the default process of this Entity is used.
Parameters
waitinterval wait interval (from now) that S3F will process the activation.
act Activation (event); If no Activation is included, one is created with NULL as the protected pointer.
Definition at line 168 of file entity.cc.
References Entity::alignment(), Timeline::default_sched_pri, Entity::now(), Timeline::schedule(), and user_pri.
{
       return alignment()->schedule( alignment()->__this, now()+delay, user_pri(Timeline::default_sched_pri), act);
    }
HandleCode Entity::waitFor (ltime_t waitinterval) inherited
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
The named process must be owned by an entity aligned to this timeline—checked by the Timeline::schedule method. A HandleCode object is returned, it can be used to cancel the scheduled activation. No priority is included, so Timeline::default_schedule_pri is used as a basis. No process in included, so the default process of this Entity is used. No Activation is included, so one is created with NULL as the protected pointer.
Parameters
waitinterval wait interval (from now) that S3F will process the activation.
Definition at line 182 of file entity.cc.
References Entity::alignment(), Timeline::default_sched_pri, Entity::now(), Timeline::schedule(), and user_pri.
{
      Message* m = NULL;
      Activation act(m);
      return alignment()->schedule( alignment()->__this, now()+delay, user_pri(Timeline::default_sched_pri), act);
    }
HandleCode Entity::waitFor (Activation act, ltime_t waitinterval, unsigned int pri) inherited
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
The named process must be owned by an entity aligned to this timeline—checked by the Timeline::schedule method. A HandleCode object is returned, it can be used to cancel the scheduled activation. No process in included, so the default process of this Entity is used.
Parameters
waitinterval wait interval (from now) that S3F will process the activation.
act Activation (event); If no Activation is included, one is created with NULL as the protected pointer.
pri A tie-breaking priority. If no priority is included, Timeline::default_schedule_pri is used as a basis.
Definition at line 172 of file entity.cc.
References Entity::alignment(), Entity::now(), Timeline::schedule(), and user_pri.
{
       return alignment()->schedule( alignment()->__this, now()+delay, user_pri(pri), act);
    }
HandleCode Entity::waitFor (ltime_t waitinterval, unsigned int pri) inherited
The waitFor method schedules the activation of the named (or current) process at a distance in the future given by waitinterval.
The named process must be owned by an entity aligned to this timeline—checked by the Timeline::schedule method. A HandleCode object is returned, it can be used to cancel the scheduled activation. No process in included, so the default process of this Entity is used. No activation is included, so one is created with NULL as the protected pointer.
Parameters
waitinterval wait interval (from now) that S3F will process the activation.
pri A tie-breaking priority. If no priority is included, Timeline::default_schedule_pri is used as a basis.
Definition at line 176 of file entity.cc.
References Entity::alignment(), Entity::now(), Timeline::schedule(), and user_pri.
{
      Message* m = NULL;
      Activation act(m);
      return alignment()->schedule( alignment()->__this, now()+delay, user_pri(pri), act);
    }
unsigned int Entity::s3fid () inline inherited
Unique identifier for Entity, index 0 to total number of Entities created.
Definition at line 171 of file entity.h.
References Entity::__s3fid.
Referenced by init(), and Entity::~Entity().
 { return __s3fid; }
string Entity::getName () inline inherited
Return the text name ("" if none was given at initialization)
Definition at line 187 of file entity.h.
References Entity::__name.
 { return __name;}
Entity * Entity::getEntity (string) static inherited
Directory look up of the Entity pointer, given its text name.
Definition at line 200 of file entity.cc.
References Entity::entity_class_mutex, and Entity::EntityName.
Referenced by init().
{
         // protect global directory using entity class mutex
         pthread_mutex_lock(&entity_class_mutex);
         // look for the name in the directory.
         map<string,Entity*>::const_iterator itr
                 = EntityName.find(name);
         // if the iterator points to the end of the map we didn't find it
         if( itr == EntityName.end()) {
                         // make list available to others and return NULL
                         pthread_mutex_unlock(&entity_class_mutex);
                         return (Entity*) NULL;
         }
         // Entity found.  Make directory available to others and return the
         // pointer
         pthread_mutex_unlock(&entity_class_mutex);
         return (*itr).second;
  }
InChannel * Entity::getInChannel (string) inherited
When an InChannel is create it can provide a text name, unique among InChannels on the same Entity.
That name goes into a directory. This method retrieves the name, returning NULL if no associated mapping was found.
Definition at line 391 of file entity.cc.
References Entity::entity_inst_mutex, and Entity::InChannelName.
Referenced by init().
{
     // off timeline entities may query this directory, so protect
     // access with a per-entity mutex.
         pthread_mutex_lock(&entity_inst_mutex);
         // see if we can find the named string
         map<string,InChannel*>::const_iterator itr = InChannelName.find(ic_name);
         // nope.  release the mutex and return NULL
         if( itr == InChannelName.end()) {
                         pthread_mutex_unlock(&entity_inst_mutex);
                         return (InChannel*) NULL;
         }
     // release the mutex and return the InChannel pointer
         pthread_mutex_unlock(&entity_inst_mutex);
         return (*itr).second;
 }
Process * Entity::getProcess (string) inherited
When a Process is create it can provide a text name, unique among Processes on the same Entity.
That name goes into a directory. This method retrieves the name, returning NULL if no associated mapping was found.
Definition at line 426 of file entity.cc.
References Entity::entity_inst_mutex, and Entity::ProcessName.
{
     // off timeline entities may query this directory, so protect
     // access with a per-entity mutex.
         pthread_mutex_lock(&entity_inst_mutex);
         // see if we can find the named string
         map<string,Process*>::const_iterator itr = ProcessName.find(p_name);
         // nope.  release the mutex and return NULL
         if( itr == ProcessName.end()) {
                         pthread_mutex_unlock(&entity_inst_mutex);
                         return (Process*) NULL;
         }
     // release the mutex and return the Process pointer
         pthread_mutex_unlock(&entity_inst_mutex);
         return (*itr).second;
 }
double Entity::t2d (ltime_t t) inherited
Conversion routines to translate from clock ticks to double precision.
Definition at line 257 of file entity.cc.
Referenced by s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::TCPMaster::enableFastTimeout(), s3f::s3fnet::TCPMaster::fast_timer_callback_body(), and s3f::s3fnet::TCPMaster::slow_timer_callback_body().
 { return (double)t; }
double Entity::t2d (ltime_t t, int s) inherited
Conversion routines to translate from clock ticks to double precision.
Parameters
t clock ticks input
s specify the units of the double precision input or output, in units of log_10(clock ticks per second). So, for example, if a double represents milliseconds, the s value is 3
Definition at line 262 of file entity.cc.
References Entity::__log_ticks_per_sec, and Entity::__pow.
{
         int scale = 18+(s-__log_ticks_per_sec);
         if(scale < 36 && scale>=0 ) return t*__pow[scale];
         return t*pow(10.0, scale-18);
   }
ltime_t Entity::d2t (double d) inherited
Conversion routines to translate from double precision to clock ticks.
Definition at line 269 of file entity.cc.
Referenced by s3f::s3fnet::TCPSession::backoff_timeout(), s3f::s3fnet::DroptailQueue::calibrate(), s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::DummySession::config(), s3f::s3fnet::TCPClientSession::config(), s3f::s3fnet::UDPServerSession::config(), s3f::s3fnet::SimplePhy::config(), s3f::s3fnet::UDPClientSession::config(), s3f::s3fnet::TCPMaster::config(), s3f::s3fnet::BTCPClientSession::config(), s3f::s3fnet::Link::connect(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::DroptailQueue::init(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::TCPSession::init_state_closed(), listen(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), s3f::s3fnet::NetworkInterface::sendPacket(), s3f::s3fnet::TCPMaster::TCPMaster(), and s3f::s3fnet::TCPSession::update_timeout().
 { return (ltime_t)d; }
ltime_t Entity::d2t (double d, int s) inherited
Conversion routines to translate from double precision to clock ticks.
Parameters
d double input
s specify the units of the double precision input or output, in units of log_10(clock ticks per second). So, for example, if a double represents milliseconds, the s value is 3
Definition at line 274 of file entity.cc.
References Entity::__log_ticks_per_sec, and Entity::__pow.
{
         int scale = 18+(__log_ticks_per_sec-s);
         if(scale < 36 && scale>=0 ) return (ltime_t)round(d*__pow[scale]);
         else return (ltime_t)round(d*pow(10.0, scale-18));
   }
void Entity::BuildEntity (Timeline * tl) protected inherited
The core of the Entity construction is done by BuildEntity.
Finish constructing the Entity.
– save the Timeline pointer
– build the tables used to support tick - double precision conversion
– give the entity a unique name
– put the entity onto its Timeline's list of entities.
Definition at line 73 of file entity.cc.
References Timeline::__entity_list, Entity::__log_ticks_per_sec, Entity::__num_entities, Entity::__pow, Entity::__s3fid, Entity::__timeline, Entity::entity_class_mutex, Entity::entity_inst_mutex, Timeline::get_log_ticks_per_sec(), and Timeline::timeline_inst_mutex.
Referenced by Entity::Entity().
{
         // remember alignment, often used to check for cross-timeline connections
         __timeline = tl;
     // initialize the mutex used to serialize access to the individual
     // Entity state (not the static class variables).
     pthread_mutex_init(&entity_inst_mutex,NULL);
     // get unique Entity id. Global access so protect by mutex
         pthread_mutex_lock(&entity_class_mutex);
         __s3fid = __num_entities++;
         pthread_mutex_unlock(&entity_class_mutex);
         // first entity builds the pow[] table, used in tick - double precision conversion
         if( __s3fid == 0 ) {
                 for(int i=0; i<36; i++) __pow[i] = pow(10.0, (double)(i-18));
         }
         // copy time-scale information from the Timeline
         __log_ticks_per_sec = tl->get_log_ticks_per_sec();
         // record entity on timeline's list of entities
         pthread_mutex_lock(&tl->timeline_inst_mutex);
         tl->__entity_list.push_back(this);
         pthread_mutex_unlock(&tl->timeline_inst_mutex);
    }
ltime_t Entity::min_sync_cross_timeline_delay (ltime_t thrs) protected inherited
Among all outbound cross-timeline connections with OutChannels in this Entity, find the smallest min-delay that is at least as large as the argument.
Definition at line 289 of file entity.cc.
References Entity::__outchannel_list.
{
    // initialize search answer to "nothing here"
    ltime_t ans = -1;
    // buffer the minimum read up from a channel connection
    ltime_t ch_min;
    // length of the list of this entity's outchannels
    unsigned int end = __outchannel_list.size();
    // visit every one of the outchannels this entity owns
    for(unsigned int i=0; i<end; i++) {
         // ask it to provide the minimum cross timeline delay at least as
         // large as thrs, among all its mappings
         //
         ch_min = __outchannel_list[i]->min_sync_cross_timeline_delay(thrs);
         // save that value if it is no larger than thrs, AND either this is
         // first one we've seen, or its value is less than the smallest one
         // seen to date.
         //
         if( (-1 < ch_min) && thrs<=ch_min && ((ans<0) || (ch_min<ans))) ans = ch_min;
    }
    // final answer is in ans
    return ans;
  }
ltime_t Entity::min_sync_all_timeline_delay (ltime_t thrs) protected inherited
Among all outbound connections with OutChannels in this Entity, find the smallest min-delay that is at least as large as the argument.
Definition at line 318 of file entity.cc.
References Entity::__outchannel_list.
{
    // initialize search answer to "nothing here"
    ltime_t ans = -1;
    // buffer the minimum read up from a channel connection
    ltime_t ch_min;
    // length of the list of this entity's outchannels
    unsigned int end = __outchannel_list.size();
    // visit every one of the outchannels this entity owns
    for(unsigned int i=0; i<end; i++) {
         // ask it to provide the minimum cross timeline delay at least as
         // large as thrs, among all its mappings
         //
         ch_min = __outchannel_list[i]->min_sync_all_timeline_delay(thrs);
         // save that value if it is no larger than thrs, AND either this is
         // first one we've seen, or its value is less than the smallest one
         // seen to date.
         //
         if( (-1 < ch_min) && thrs<=ch_min && ((ans<0) || (ch_min<ans))) ans = ch_min;
    }
    // final answer is in ans
    return ans;
  }
unsigned int Entity::count_min_delay_crossings (ltime_t thrs) protected inherited
Count the number of outbound cross-timeline connections with minimum delay at least as large as thrs.
Definition at line 355 of file entity.cc.
References Entity::__outchannel_list.
{
   // initialize running sum
   unsigned int ans = 0;
   // number of OutChannels owned by this entity
   unsigned int end = __outchannel_list.size();
   // For each OutChannel as it to count the number of outbound
   // cross timeline connections with minimum delay less than or equal
   // to thrs
   //
   for(unsigned int i=0; i<end; i++) {
     ans += __outchannel_list[i]->count_min_delay_crossings(thrs);
   }
   // return accumulated sum
   return ans;
 }
Member Data Documentation
int pHold_Node::myid
unique node id
Definition at line 16 of file phold_node.h.
Referenced by init(), listen(), pHold_Node(), and talk().
int pHold_Node::myports
for computing the next out message; equal to the number of node
Definition at line 17 of file phold_node.h.
Referenced by init(), pHold_Node(), and talk().
InChannel** pHold_Node::ic
list of InChannels of this node
Definition at line 18 of file phold_node.h.
Referenced by pHold_Node().
OutChannel** pHold_Node::oc
list of OutChannels of this node
Definition at line 19 of file phold_node.h.
Referenced by init(), pHold_Node(), and talk().
Process* pHold_Node::listen_proc
S3F process, listen on InChannels.
Definition at line 20 of file phold_node.h.
Referenced by pHold_Node().
Process* pHold_Node::talk_proc
S3F process, act after an activation is received on an InChannel.
Definition at line 21 of file phold_node.h.
Referenced by listen(), and pHold_Node().
Random::RNG pHold_Node::rng
random number
Definition at line 23 of file phold_node.h.
Referenced by listen().
int pHold_Node::next_out
for computing the target outChannel for the next out message
Definition at line 25 of file phold_node.h.
Referenced by init(), pHold_Node(), and talk().
long pHold_Node::recvd
count of total activations (listen + talk)
Definition at line 26 of file phold_node.h.
Referenced by listen(), pHold_Node(), and talk().
string Entity::__name protected inherited
text name given at initialization
Definition at line 267 of file entity.h.
Referenced by Entity::getName().
Timeline* Entity::__timeline protected inherited
pointer to Timeline on which this Entity is aligned
Definition at line 268 of file entity.h.
Referenced by Entity::alignment(), Entity::BuildEntity(), and Entity::now().
unsigned int Entity::__s3fid protected inherited
Unique identity for Entity.
Definition at line 269 of file entity.h.
Referenced by Entity::BuildEntity(), and Entity::s3fid().
double Entity::__pow static protected inherited
pow[i] = 10^{i-18}.
Used in time scale transformation
Definition at line 273 of file entity.h.
Referenced by Entity::BuildEntity(), Entity::d2t(), and Entity::t2d().
int Entity::__log_ticks_per_sec protected inherited
time-scale of clock.
Obtained from timeline when the entity is created.
Definition at line 275 of file entity.h.
Referenced by Entity::BuildEntity(), Entity::d2t(), and Entity::t2d().
vector<OutChannel*> Entity::__outchannel_list protected inherited
list of outchannels owned by this entity
Definition at line 279 of file entity.h.
Referenced by Entity::count_min_delay_crossings(), Timeline::initialize_appt(), Entity::min_sync_all_timeline_delay(), Entity::min_sync_cross_timeline_delay(), and OutChannel::OutChannel().
vector<InChannel*> Entity::__inchannel_list protected inherited
list of inchannels owned by this entity
Definition at line 280 of file entity.h.
Referenced by InChannel::InChannel().
vector<Process*> Entity::__process_list protected inherited
list of processes owned by this entity
Definition at line 281 of file entity.h.
Referenced by Process::Process().
map<string,Process*> Entity::ProcessName protected inherited
Definition at line 284 of file entity.h.
Referenced by Entity::getProcess().
map<string,InChannel*> Entity::InChannelName protected inherited
directory of inchannels declared with string names
Definition at line 285 of file entity.h.
Referenced by Entity::getInChannel().
pthread_mutex_t Entity::entity_inst_mutex protected inherited
mutex for access to Entity instances state
Definition at line 288 of file entity.h.
Referenced by Entity::BuildEntity(), Entity::getInChannel(), Entity::getProcess(), InChannel::InChannel(), OutChannel::OutChannel(), Process::Process(), and Entity::~Entity().
map< string, Entity * > Entity::EntityName static protected inherited
Entity text to Pointer Directory.
Definition at line 293 of file entity.h.
Referenced by Entity::getEntity().
pthread_mutex_t Entity::entity_class_mutex static protected inherited
Mutex that protects access to Entity state.
Definition at line 296 of file entity.h.
Referenced by Entity::BuildEntity(), Entity::getEntity(), and Interface::Interface().
unsigned int Entity::__num_entities = 0 static protected inherited
counter of number of entities created
Definition at line 299 of file entity.h.
Referenced by Entity::BuildEntity().
The documentation for this class was generated from the following files:
phold_node.h
phold_node.cc