S3F: s3f::s3fnet::ForwardingTable Class Reference
s3f::s3fnet::ForwardingTable Class Reference
The forwarding table.
#include <forwardingtable.h>
Public Member Functions
ForwardingTable (ProtocolSession *ipsess, int trie_version=-1, int cache_version=-1)
The constructor.
virtual ~ForwardingTable ()
The destructor.
int addRoute (RouteInfo *route, bool replace=true)
Add the preferred route to a given ip prefix.
int removeRoute (RouteInfo *route)
Remove a route from the forwarding table to a given ip prefix.
RouteInfo * getRoute (IPADDR ipaddr)
Find a route to a given ip address.
void dump (FILE *fp=NULL)
Prints out the forwarding table.
void invalidateAllRoutes (int protocol)
Invalidate all routes in forwarding table that were installed by the given protocol.
RouteInfo * getDefaultRoute ()
If there is a default route, the method returns it; otherwise, it returns NULL.
void addListener (ProtocolSession *sess)
Add a listener protocol session, who wish to be notified of the changes to the forwarding table.
Static Protected Member Functions
static void dump_helper (TrieNode *root, uint32 sofar, int n, FILE *fp)
The recursive helper to the dump method.
Private Attributes
RouteCache * mCache
The routing cache.
Trie * mTrie
The Trie in which routes are stored (ForwardingTable originally inherited from Trie)
ProtocolSession * ip_sess
The IP session is the owner of the forwarding table.
S3FNET_FIB_PROTO_SET listeners
List of protocol sessions who wish to be notified of FIB changes.
Detailed Description
The forwarding table.
This class maps IP addresses (in the form a.b.c.d/p) into RouteInfo structures that specify the interface and the next hop among others. We need the next hop in order to be able to implement LAN links. The forwarding table is implemented as a Trie so we can quickly find the most specific prefix for any destination.
Obviously each machine will have a forwarding table which is the result of routing calculations done by a routing protocol. The forwarding table is used by a network layer protocol, IP, to be specific. Conceptually the ProtoGraph class owns the forwarding table and the routing protocols (like OSPF and BGP) should be able to access and change it accordingly.
Definition at line 218 of file forwardingtable.h.
Constructor & Destructor Documentation
s3f::s3fnet::ForwardingTable::ForwardingTable (ProtocolSession * ipsess, int trie_version = -1, int cache_version = -1)
The constructor.
Definition at line 221 of file forwardingtable.cc.
References s3f::s3fnet::Trie::ARRAY_BACKED, s3f::s3fnet::RouteCache::ASSOCIATIVE, DEFAULT_CACHE_VERSION, DEFAULT_TRIE_VERSION, s3f::s3fnet::RouteCache::DIRECT_MAPPED, mCache, mTrie, s3f::s3fnet::RouteCache::NONE, s3f::s3fnet::Trie::ORIGINAL, s3f::s3fnet::Trie::PREFIX, s3f::s3fnet::Trie::SIMPLE, s3f::s3fnet::RouteCache::SINGLE_ENTRY, and s3f::s3fnet::Trie::UNORDERED_PREFIX.
                                                                                              :
                 ip_sess(ipsess) {
   if(trie_version == -1) {
         trie_version = DEFAULT_TRIE_VERSION;
   }
   if(cache_version == -1) {
         cache_version = DEFAULT_CACHE_VERSION;
   }
   // TODO: Make Trie and Cache configurable via dml (based on version)
   tvstart:
         switch(trie_version) {
         case Trie::ORIGINAL:
                 mTrie = (Trie*)new trie0::Trie0();
                 break;
         case Trie::SIMPLE:
                 mTrie = (Trie*)new trie1::Trie1();
                 break;
         case Trie::PREFIX:
                 mTrie = (Trie*)new trie2::Trie2();
                 break;
         case Trie::UNORDERED_PREFIX:
                 mTrie = (Trie*)new trie3::Trie3();
                 break;
         case Trie::ARRAY_BACKED:
                 mTrie = (Trie*)new trie4::Trie4();
                 break;
         default:
                 fprintf(stderr, "Invalid forwarding table version (%d). Using default (%d).",trie_version,
                                 DEFAULT_TRIE_VERSION);
                 trie_version = DEFAULT_TRIE_VERSION;
                 goto tvstart;
         }
         assert(mTrie);
   cvstart:
         switch(cache_version) {
         case RouteCache::SINGLE_ENTRY:
                 mCache = (RouteCache*)new routecache0::RouteCache0();
                 break;
         case RouteCache::DIRECT_MAPPED:
                 mCache = (RouteCache*)new routecache1::RouteCache1();
                 break;
         case RouteCache::ASSOCIATIVE:
                 mCache = (RouteCache*)new routecache2::RouteCache2();
                 break;
         case RouteCache::NONE:
                 mCache = NULL;
                 break;
         default:
                 fprintf(stderr, "Invalid cache version (%d). Using default (%d).",cache_version,
                                 DEFAULT_CACHE_VERSION);
                 cache_version = DEFAULT_CACHE_VERSION;
                 goto cvstart;
         }
 }
s3f::s3fnet::ForwardingTable::~ForwardingTable () virtual
The destructor.
Definition at line 279 of file forwardingtable.cc.
References mCache, and mTrie.
{
         if(mTrie) {
                 delete mTrie;
         }
         if(mCache) {
                 delete mCache;
         }
 }
Member Function Documentation
int s3f::s3fnet::ForwardingTable::addRoute (RouteInfo * route, bool replace = true)
Add the preferred route to a given ip prefix.
If there's already an entry for this address and if replace is true, the old route will be overwritten and the method returns FT_ROUTE_OVERWRITTEN. Also, the old route will be reclaimed. Otherwise, the method returns 0.
Definition at line 288 of file forwardingtable.cc.
References s3f::s3fnet::IPPrefix::addr, s3f::s3fnet::RouteInfo::destination, FT_ROUTE_NOT_REPLACED, FT_ROUTE_OVERWRITTEN, FT_ROUTE_SUCCESS, s3f::s3fnet::Trie::insert(), s3f::s3fnet::RouteCache::invalidate(), s3f::s3fnet::IP_CTRL_FIB_ADDROUTE, s3f::s3fnet::IP_CTRL_FIB_DELROUTE, ip_sess, s3f::s3fnet::IPPrefix::len, listeners, mCache, and mTrie.
Referenced by s3f::s3fnet::IPSession::control(), s3f::s3fnet::IPSession::init(), and removeRoute().
 {
   if(mCache) {
         mCache->invalidate(); // TODO: only invalidate if necessary
   }
   // if returns a conflict route; it could be the original or the new
   // route depending on whether 'replace' is true or not
   RouteInfo* conflict = (RouteInfo*)
     mTrie->insert(route->destination.addr, route->destination.len, route, replace);
   if(conflict) {
     if(replace) {
       for(S3FNET_FIB_PROTO_SET::iterator iter = listeners.begin();
           iter != listeners.end(); iter++) {
         (*iter)->control(IP_CTRL_FIB_DELROUTE, conflict, ip_sess);
         (*iter)->control(IP_CTRL_FIB_ADDROUTE, route, ip_sess);
       }
       delete conflict; // this is the old route
       return FT_ROUTE_OVERWRITTEN;
     } else {
       assert(conflict == route);
       delete conflict;  // this is the new route
       return FT_ROUTE_NOT_REPLACED;
     }
   } else {
     for(S3FNET_FIB_PROTO_SET::iterator iter = listeners.begin();
         iter != listeners.end(); iter++) {
       (*iter)->control(IP_CTRL_FIB_ADDROUTE, route, ip_sess);
     }
     return FT_ROUTE_SUCCESS;
   }
 }
int s3f::s3fnet::ForwardingTable::removeRoute (RouteInfo * route)
Remove a route from the forwarding table to a given ip prefix.
The removed route will be deleted. The method returns 0 if the route has been found and reclaimed. Oherwise, the method returns FT_ROUTE_NOT_FOUND.
Definition at line 321 of file forwardingtable.cc.
References s3f::s3fnet::IPPrefix::addr, addRoute(), s3f::s3fnet::RouteInfo::destination, FT_ROUTE_NOT_FOUND, FT_ROUTE_SUCCESS, s3f::s3fnet::RouteCache::invalidate(), s3f::s3fnet::IP_CTRL_FIB_DELROUTE, ip_sess, s3f::s3fnet::IPPrefix::len, listeners, mCache, mTrie, and s3f::s3fnet::Trie::remove().
Referenced by s3f::s3fnet::IPSession::control().
 {
   if(mCache) {
         mCache->invalidate(); // TODO: only invalidate if necessary
   }
   RouteInfo* old = (RouteInfo*)mTrie->remove(route->destination.addr, route->destination.len);
   if(old) {
     // we need to compare the existing route with the one we want to
     // remove; if they don't match, we reinstall the existing one;
     // otherwise, we remove it
     if(*route != *old) addRoute(old);
     else {
       for(S3FNET_FIB_PROTO_SET::iterator iter = listeners.begin();
           iter != listeners.end(); iter++) {
         (*iter)->control(IP_CTRL_FIB_DELROUTE, old, ip_sess);
       }
       delete old;
     }
     delete route;
     return FT_ROUTE_SUCCESS;
   } else {
     delete route;
     return FT_ROUTE_NOT_FOUND;
   }
 }
RouteInfo * s3f::s3fnet::ForwardingTable::getRoute (IPADDR ipaddr)
Find a route to a given ip address.
The method returns NULL if no such route exists.
Definition at line 348 of file forwardingtable.cc.
References s3f::s3fnet::Trie::lookup(), s3f::s3fnet::RouteCache::lookup(), mCache, mTrie, and s3f::s3fnet::RouteCache::update().
Referenced by s3f::s3fnet::IPSession::handle_pop_pkt(), and s3f::s3fnet::IPSession::push().
{
   RouteInfo* pData;
   if(mCache) {
         pData = mCache->lookup(ipaddr);
         if(pData != NULL) {
                 return pData;
         }
   }
   // find out the route for the given ip address
   pData = (RouteInfo*)mTrie->lookup(ipaddr);
   if(mCache && pData) {
         mCache->update(ipaddr,pData);
   }
   return pData;
 }
void s3f::s3fnet::ForwardingTable::dump (FILE * fp = NULL)
Prints out the forwarding table.
void s3f::s3fnet::ForwardingTable::invalidateAllRoutes (int protocol)
Invalidate all routes in forwarding table that were installed by the given protocol.
If the protocol is UNSPEC, all routes will be removed.
RouteInfo * s3f::s3fnet::ForwardingTable::getDefaultRoute ()
If there is a default route, the method returns it; otherwise, it returns NULL.
Definition at line 416 of file forwardingtable.cc.
References s3f::s3fnet::Trie::getDefault(), and mTrie.
 {
   if(mTrie) return (RouteInfo*)(mTrie->getDefault());
   return 0;
 }
void s3f::s3fnet::ForwardingTable::addListener (ProtocolSession * sess)
Add a listener protocol session, who wish to be notified of the changes to the forwarding table.
Definition at line 422 of file forwardingtable.cc.
References listeners.
Referenced by s3f::s3fnet::IPSession::control(), and s3f::s3fnet::IPSession::init().
 {
   listeners.insert(sess);
 }
static void s3f::s3fnet::ForwardingTable::dump_helper (TrieNode * root, uint32 sofar, int n, FILE * fp) static protected
The recursive helper to the dump method.
Member Data Documentation
RouteCache* s3f::s3fnet::ForwardingTable::mCache private
The routing cache.
Configurable/extendable much like Trie.
Definition at line 273 of file forwardingtable.h.
Referenced by addRoute(), ForwardingTable(), getRoute(), removeRoute(), and ~ForwardingTable().
Trie* s3f::s3fnet::ForwardingTable::mTrie private
The Trie in which routes are stored (ForwardingTable originally inherited from Trie)
Definition at line 276 of file forwardingtable.h.
Referenced by addRoute(), ForwardingTable(), getDefaultRoute(), getRoute(), removeRoute(), and ~ForwardingTable().
ProtocolSession* s3f::s3fnet::ForwardingTable::ip_sess private
The IP session is the owner of the forwarding table.
Definition at line 279 of file forwardingtable.h.
Referenced by addRoute(), and removeRoute().
S3FNET_FIB_PROTO_SET s3f::s3fnet::ForwardingTable::listeners private
List of protocol sessions who wish to be notified of FIB changes.
The protocol sessions will be informed of the changes via calls to the control() method with the following types: IP_CTRL_FIB_ADDROUTE and IP_CTRL_FIB_DELROUTE. In both cases, the ctrlmsg argument should be a pointer to the corresponding RouteInfo object being added to or removed from the forwarding table.
Definition at line 288 of file forwardingtable.h.
Referenced by addListener(), addRoute(), and removeRoute().
The documentation for this class was generated from the following files:
forwardingtable.h
forwardingtable.cc