S3F: s3f::s3fnet::Socket Class Reference
s3f::s3fnet::Socket Class Reference
The socket information.
#include <socket_session.h>
Public Types
enum {
NO_SIGNAL = 0x00000000, CONN_RESET = 0x00000001, DATA_AVAILABLE = 0x00000002, OK_TO_SEND = 0x00000004,
CONN_CLOSED = 0x00000008, SOCK_EOF = 0x00000010, OK_TO_CLOSE = 0x00000020, FIRST_CONNECTION = 0x00000040,
SESSION_RELEASED = 0x00000080, CONNECT_ACTIVE = 0x00000100, ALL_SIGNALS = 0x00ffffff, SOCK_DELETED = 0x10000000
}
State of socket Uses the same mask as signals.
enum {
RESUME_NONE = 0x00, RESUME_ACCEPT1 = 0x01, RESUME_ACCEPT2 = 0x02, RESUME_MAKENEW = 0x04,
RESUME_SEND1 = 0x08, RESUME_CONNECT1 = 0x10, RESUME_RECV1 = 0x20, RESUME_CLOSE1 = 0x40
}
Socket's resume state for non-blocking execution Used for proper reentrant behavior.
Public Member Functions
Socket ()
The constructor.
void release ()
Release/free the socket session.
void reinit ()
Reinitialize the socket after disconnection.
bool is_active ()
Checks if socket is active.
void activate ()
Activates socket Will cause is_active() to return true.
void deactivate ()
Deactivates socket Reverses one activate() call.
void die_slowly ()
Sets socket state to deleted.
bool has_died ()
Checks if socket has been deleted.
int getResume ()
Gets the socket's resume state Used by non-blocking sockets for proper reentrant behavior.
void setResume (int r)
Sets the socket's resume state Used by non-blocking sockets for proper reentrant behavior.
Public Attributes
SocketSession * session
Pointer to the owner socket session.
uint32 state
The state of the socket.
uint32 mask
The mask of the socket.
SocketContinuation * continuation
The semaphore is used only by the blocking socket master to synchronize processes.
uint32 bytes_completed
The number of bytes that the socket has completed sending or receiving.
Protected Attributes
int resume
State of the socket for proper resume in multi-stage functions like accept().
Private Member Functions
~Socket ()
The destructor as a private method to prevent accidental deletion.
Private Attributes
int active_counter
Indicates how many processes are actively waiting on this socket, in which case the socket must not be removed.
Detailed Description
The socket information.
A socket is an application representation of a connection to a remote peer. It contains necessary information on the state of the connection.
Definition at line 327 of file socket_session.h.
Member Enumeration Documentation
anonymous enum
State of socket Uses the same mask as signals.
Enumerator
NO_SIGNAL
No signal.
CONN_RESET
connection reset
DATA_AVAILABLE
data is available
OK_TO_SEND
clear to send data
CONN_CLOSED
connection is closed
SOCK_EOF
no more data
OK_TO_CLOSE
connection may be closed
FIRST_CONNECTION
is the first connection
SESSION_RELEASED
session has already been released
CONNECT_ACTIVE
connect is in progress
ALL_SIGNALS
logical AND of all signals
SOCK_DELETED
socket was already deleted
Definition at line 333 of file socket_session.h.
        {
     NO_SIGNAL        = 0x00000000,
     CONN_RESET       = 0x00000001,
     DATA_AVAILABLE   = 0x00000002,
     OK_TO_SEND       = 0x00000004,
     CONN_CLOSED      = 0x00000008,
     SOCK_EOF         = 0x00000010,
     OK_TO_CLOSE      = 0x00000020,
     FIRST_CONNECTION = 0x00000040,
     SESSION_RELEASED = 0x00000080,
     CONNECT_ACTIVE   = 0x00000100,
     ALL_SIGNALS      = 0x00ffffff,
     SOCK_DELETED     = 0x10000000
   };
anonymous enum
Socket's resume state for non-blocking execution Used for proper reentrant behavior.
Enumerator
RESUME_NONE
No resume state.
RESUME_ACCEPT1
Socket has passed first stage of accept.
RESUME_ACCEPT2
Socket has passed second stage of accept.
RESUME_MAKENEW
Socket should fork a new thread for incoming connections.
RESUME_SEND1
Socket has passed first stage of send.
RESUME_CONNECT1
Socket has passed first stage of connect.
RESUME_RECV1
Socket has passed first stage of recv.
RESUME_CLOSE1
Socket has passed first stage of close.
Definition at line 352 of file socket_session.h.
        {
     RESUME_NONE    = 0x00,
     RESUME_ACCEPT1 = 0x01,
     RESUME_ACCEPT2 = 0x02,
     RESUME_MAKENEW = 0x04,
     RESUME_SEND1   = 0x08,
     RESUME_CONNECT1 = 0x10,
     RESUME_RECV1    = 0x20,
     RESUME_CLOSE1   = 0x40
   };
Constructor & Destructor Documentation
s3f::s3fnet::Socket::Socket () inline
The constructor.
Definition at line 364 of file socket_session.h.
            :
     session(0), state(NO_SIGNAL), mask(0), continuation(0),
     bytes_completed(0), active_counter(0), resume(RESUME_NONE) {}
s3f::s3fnet::Socket::~Socket () inline private
The destructor as a private method to prevent accidental deletion.
The user should call the release method instead.
Definition at line 451 of file socket_session.h.
 {}
Member Function Documentation
void s3f::s3fnet::Socket::release () inline
Release/free the socket session.
Definition at line 369 of file socket_session.h.
References s3f::s3fnet::SocketSession::release(), and session.
Referenced by s3f::s3fnet::SocketMaster::abort(), s3f::s3fnet::NBSocketMaster::abort(), s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::accept1a(), s3f::s3fnet::SocketMaster::accept1b(), s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SocketMaster::accept2b(), s3f::s3fnet::SocketMaster::bind(), s3f::s3fnet::NBSocketMaster::bind(), s3f::s3fnet::SocketMaster::close(), s3f::s3fnet::NBSocketMaster::close(), s3f::s3fnet::SocketMaster::close1(), s3f::s3fnet::NBSocketMaster::close1(), s3f::s3fnet::SocketMaster::connect1(), s3f::s3fnet::NBSocketMaster::connect1(), s3f::s3fnet::SocketMaster::recv1(), s3f::s3fnet::NBSocketMaster::recv1(), s3f::s3fnet::SocketMaster::send1(), and s3f::s3fnet::NBSocketMaster::send1().
 { if(session) session->release(); }
void s3f::s3fnet::Socket::reinit () inline
Reinitialize the socket after disconnection.
Definition at line 372 of file socket_session.h.
References ALL_SIGNALS, and state.
Referenced by s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::accept1a(), s3f::s3fnet::SocketMaster::accept1b(), s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SocketMaster::accept2b(), s3f::s3fnet::SocketMaster::close(), s3f::s3fnet::NBSocketMaster::close(), s3f::s3fnet::SocketMaster::close1(), s3f::s3fnet::NBSocketMaster::close1(), s3f::s3fnet::SocketMaster::connect1(), s3f::s3fnet::NBSocketMaster::connect1(), s3f::s3fnet::SocketMaster::control(), s3f::s3fnet::NBSocketMaster::control(), s3f::s3fnet::SocketMaster::recv1(), s3f::s3fnet::NBSocketMaster::recv1(), s3f::s3fnet::SocketMaster::send1(), and s3f::s3fnet::NBSocketMaster::send1().
 { state &= ~ALL_SIGNALS; }
bool s3f::s3fnet::Socket::is_active () inline
Checks if socket is active.
Returns
true if socket is active somewhere, false otherwise
Definition at line 378 of file socket_session.h.
References active_counter.
Referenced by s3f::s3fnet::SocketMaster::abort(), s3f::s3fnet::NBSocketMaster::abort(), s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::accept1a(), s3f::s3fnet::SocketMaster::accept1b(), s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SocketMaster::accept2b(), s3f::s3fnet::SocketMaster::close(), s3f::s3fnet::NBSocketMaster::close(), s3f::s3fnet::SocketMaster::close1(), s3f::s3fnet::NBSocketMaster::close1(), s3f::s3fnet::SocketMaster::connect1(), s3f::s3fnet::NBSocketMaster::connect1(), s3f::s3fnet::SocketMaster::recv1(), s3f::s3fnet::NBSocketMaster::recv1(), s3f::s3fnet::SocketMaster::send1(), and s3f::s3fnet::NBSocketMaster::send1().
 { return active_counter > 0; }
void s3f::s3fnet::Socket::activate () inline
Activates socket Will cause is_active() to return true.
See Also
is_active()
deactivate()
Definition at line 386 of file socket_session.h.
References active_counter.
Referenced by s3f::s3fnet::SocketMaster::block_till(), and s3f::s3fnet::NBSocketMaster::block_till().
 { active_counter++; }
void s3f::s3fnet::Socket::deactivate () inline
Deactivates socket Reverses one activate() call.
See Also
activate()
Definition at line 393 of file socket_session.h.
References active_counter.
Referenced by s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::accept1a(), s3f::s3fnet::SocketMaster::accept1b(), s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SocketMaster::accept2b(), s3f::s3fnet::SocketMaster::close1(), s3f::s3fnet::NBSocketMaster::close1(), s3f::s3fnet::SocketMaster::connect1(), s3f::s3fnet::NBSocketMaster::connect1(), s3f::s3fnet::SocketMaster::recv1(), s3f::s3fnet::NBSocketMaster::recv1(), s3f::s3fnet::SocketMaster::send1(), and s3f::s3fnet::NBSocketMaster::send1().
 { active_counter--; }
void s3f::s3fnet::Socket::die_slowly () inline
Sets socket state to deleted.
Definition at line 398 of file socket_session.h.
References SOCK_DELETED, and state.
Referenced by s3f::s3fnet::SocketMaster::abort(), s3f::s3fnet::NBSocketMaster::abort(), s3f::s3fnet::SocketMaster::close(), s3f::s3fnet::NBSocketMaster::close(), s3f::s3fnet::SocketMaster::close1(), and s3f::s3fnet::NBSocketMaster::close1().
 { state |= SOCK_DELETED; }
bool s3f::s3fnet::Socket::has_died () inline
Checks if socket has been deleted.
Returns
true if already deleted, false otherwise
See Also
die_slowly()
Definition at line 405 of file socket_session.h.
References SOCK_DELETED, and state.
Referenced by s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::accept1a(), s3f::s3fnet::SocketMaster::accept1b(), s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SocketMaster::accept2b(), s3f::s3fnet::SocketMaster::close1(), s3f::s3fnet::NBSocketMaster::close1(), s3f::s3fnet::SocketMaster::connect1(), s3f::s3fnet::NBSocketMaster::connect1(), s3f::s3fnet::SocketMaster::recv1(), s3f::s3fnet::NBSocketMaster::recv1(), s3f::s3fnet::SocketMaster::send1(), and s3f::s3fnet::NBSocketMaster::send1().
 { return state & SOCK_DELETED; }
int s3f::s3fnet::Socket::getResume () inline
Gets the socket's resume state Used by non-blocking sockets for proper reentrant behavior.
Returns
socket's resume state
Definition at line 434 of file socket_session.h.
References resume.
Referenced by s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::NBSocketMaster::close(), s3f::s3fnet::NBSocketMaster::connect(), s3f::s3fnet::NBSocketMaster::recv(), and s3f::s3fnet::NBSocketMaster::send().
 { return resume; }
void s3f::s3fnet::Socket::setResume (int r) inline
Sets the socket's resume state Used by non-blocking sockets for proper reentrant behavior.
Parameters
r new resume state
Definition at line 441 of file socket_session.h.
References resume.
Referenced by s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::NBSocketMaster::close(), s3f::s3fnet::NBSocketMaster::connect(), s3f::s3fnet::NBSocketMaster::recv(), and s3f::s3fnet::NBSocketMaster::send().
 { resume = r; }
Member Data Documentation
SocketSession* s3f::s3fnet::Socket::session
Pointer to the owner socket session.
Definition at line 409 of file socket_session.h.
Referenced by s3f::s3fnet::SocketMaster::abort(), s3f::s3fnet::NBSocketMaster::abort(), s3f::s3fnet::SocketMaster::accept(), s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SocketMaster::bind(), s3f::s3fnet::NBSocketMaster::bind(), s3f::s3fnet::SocketMaster::close(), s3f::s3fnet::NBSocketMaster::close(), s3f::s3fnet::SocketMaster::close1(), s3f::s3fnet::NBSocketMaster::close1(), s3f::s3fnet::SocketMaster::connect(), s3f::s3fnet::NBSocketMaster::connect(), s3f::s3fnet::SocketMaster::connected(), s3f::s3fnet::NBSocketMaster::connected(), s3f::s3fnet::SocketMaster::control(), s3f::s3fnet::NBSocketMaster::control(), s3f::s3fnet::SocketMaster::listen(), s3f::s3fnet::NBSocketMaster::listen(), s3f::s3fnet::SocketMaster::recv(), s3f::s3fnet::NBSocketMaster::recv(), release(), s3f::s3fnet::SocketMaster::send(), and s3f::s3fnet::NBSocketMaster::send().
uint32 s3f::s3fnet::Socket::state
The state of the socket.
Definition at line 412 of file socket_session.h.
Referenced by s3f::s3fnet::SocketMaster::accept(), s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::accept1a(), s3f::s3fnet::SocketMaster::accept1b(), s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SocketMaster::accept2b(), s3f::s3fnet::SocketMaster::block_till(), s3f::s3fnet::NBSocketMaster::block_till(), s3f::s3fnet::SocketMaster::close(), s3f::s3fnet::NBSocketMaster::close(), s3f::s3fnet::SocketMaster::close1(), s3f::s3fnet::NBSocketMaster::close1(), s3f::s3fnet::SocketMaster::connect(), s3f::s3fnet::NBSocketMaster::connect(), s3f::s3fnet::SocketMaster::connect1(), s3f::s3fnet::NBSocketMaster::connect1(), s3f::s3fnet::SocketMaster::control(), s3f::s3fnet::NBSocketMaster::control(), die_slowly(), s3f::s3fnet::SocketMaster::eof(), s3f::s3fnet::NBSocketMaster::eof(), has_died(), s3f::s3fnet::SocketMaster::recv(), s3f::s3fnet::NBSocketMaster::recv(), s3f::s3fnet::SocketMaster::recv1(), s3f::s3fnet::NBSocketMaster::recv1(), reinit(), s3f::s3fnet::SocketMaster::send(), s3f::s3fnet::NBSocketMaster::send(), s3f::s3fnet::SocketMaster::send1(), and s3f::s3fnet::NBSocketMaster::send1().
uint32 s3f::s3fnet::Socket::mask
The mask of the socket.
Definition at line 415 of file socket_session.h.
Referenced by s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::accept1a(), s3f::s3fnet::SocketMaster::accept1b(), s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SocketMaster::accept2b(), s3f::s3fnet::SocketMaster::block_till(), s3f::s3fnet::NBSocketMaster::block_till(), s3f::s3fnet::SocketMaster::close1(), s3f::s3fnet::NBSocketMaster::close1(), s3f::s3fnet::SocketMaster::connect1(), s3f::s3fnet::NBSocketMaster::connect1(), s3f::s3fnet::SocketMaster::control(), s3f::s3fnet::NBSocketMaster::control(), s3f::s3fnet::SocketMaster::recv1(), s3f::s3fnet::NBSocketMaster::recv1(), s3f::s3fnet::SocketMaster::send1(), and s3f::s3fnet::NBSocketMaster::send1().
SocketContinuation* s3f::s3fnet::Socket::continuation
The semaphore is used only by the blocking socket master to synchronize processes.
Used by the nonblocking socket master to unblock the socket interface functions.
Definition at line 423 of file socket_session.h.
Referenced by s3f::s3fnet::SocketMaster::block_till(), s3f::s3fnet::NBSocketMaster::block_till(), s3f::s3fnet::SocketMaster::control(), and s3f::s3fnet::NBSocketMaster::control().
uint32 s3f::s3fnet::Socket::bytes_completed
The number of bytes that the socket has completed sending or receiving.
Definition at line 427 of file socket_session.h.
Referenced by s3f::s3fnet::SocketMaster::control(), s3f::s3fnet::NBSocketMaster::control(), s3f::s3fnet::SocketMaster::recv(), s3f::s3fnet::NBSocketMaster::recv(), s3f::s3fnet::SocketMaster::recv1(), s3f::s3fnet::NBSocketMaster::recv1(), s3f::s3fnet::SocketMaster::send(), s3f::s3fnet::NBSocketMaster::send(), s3f::s3fnet::SocketMaster::send1(), and s3f::s3fnet::NBSocketMaster::send1().
int s3f::s3fnet::Socket::resume protected
State of the socket for proper resume in multi-stage functions like accept().
Definition at line 446 of file socket_session.h.
Referenced by getResume(), and setResume().
int s3f::s3fnet::Socket::active_counter private
Indicates how many processes are actively waiting on this socket, in which case the socket must not be removed.
If the active_counter is negative, it means the socket is put on the death role.
Definition at line 457 of file socket_session.h.
Referenced by activate(), deactivate(), and is_active().
The documentation for this class was generated from the following file:
socket_session.h