S3F: s3f::s3fnet::NetworkInterface Class Reference
s3f::s3fnet::NetworkInterface Class Reference
A network interface.
#include <network_interface.h>
Public Member Functions
NetworkInterface (Host *parent, long id)
The constructor.
virtual ~NetworkInterface ()
The destructor.
virtual void config (s3f::dml::Configuration *cfg)
Configure the network interface from DML.
virtual void init ()
Initialize all protocol sessions defined in this network interface.
IPADDR getIP ()
Get the IP address of this network interface.
MACADDR getMacAddr ()
Get the MAC address of this network interface.
Mac48Address * getMac48Addr ()
Get the 48-bit MAC address of this network interface.
Link * getLink ()
Return the link that this network interface is attached to.
ProtocolSession * getHighestProtocolSession ()
Return the highest protocol session in the interface, i.e., the MAC session.
ProtocolSession * getLowestProtocolSession ()
Return the lowest protocol session in the interface, i.e., the physical layer session.
Host * getHost ()
Return the host that contains this network interface.
virtual void display (int indent=0)
Print out the name of this network interface.
void sendPacket (Activation pkt, ltime_t delay)
Send a packet with the given delay.
void receivePacket (Activation pkt)
Receive a packet.
void handle_openflow_message_to_controller (Activation pkt)
Handle the message from openflow switch to openflow controller.
bool isPromiscuousMode ()
Indicate if the promiscuous mode is enabled.
virtual void wrapup ()
The wrapup method is called at the end of the simulation.
ProtocolSession * sessionForName (char *pname)
If a protocol session has been created and registered under the given name, the method returns the protocol session.
ProtocolSession * sessionForNumber (int pno)
If a protocol session has been created and registered under the given protocol number, the method returns the protocol session.
Public Attributes
OutChannel * oc
The associated S3F OutChannel.
InChannel * ic
The associated S3F InChannel.
bool is_of_ctrl_iface
Indicate whether the network interface is the one connecting to an openflow controller, only an openflow switch has such interface.
OpenFlowSwitchSession * of_switch_sess
Pointer to the OpenFlowSwitchSession protocol session layer.
long id
Every DmlObject object must have an ID obtained from the DML.
Nhi nhi
The nhi address to identify the object.
DmlObject * myParent
The parent.
char * description
Optional string to describe the protocol graph.
Protected Member Functions
void emu_packet_modify_iface (Activation pkt)
Modify packet for openvz emu.
void attach_to_link (Link *link)
Set the medium that this interface is attached to attached_link() is called after link connection is created.
ProtocolSession * config_session (s3f::dml::Configuration *cfg)
Internal use: to configure a protocol session.
void insert_session (ProtocolSession *psess)
Insert a protocol session to this protocol graph.
Protected Attributes
IPADDR ip_addr
The IP address allocated to this interface.
MACADDR mac_addr
The MAC address allocated to this interface.
Mac48Address * mac48_addr
The MAC48 address (48 bit IEEE addresses) allocated to this interface.
bool is_oc_connected
Indicator of whether the OutChannel is connected.
bool is_ic_connected
Indicator of whether the InChannel is connected.
Link * attached_link
The link that this interface is attached to.
NicProtocolSession * mac_sess
The MAC layer protocol.
LowestProtocolSession * phy_sess
The PHY layer protocol.
bool is_promiscuous
whether the network interface uses promiscuous mode
S3FNET_GRAPH_PROTONAME_MAP pname_map
Mapping between protocol names and instances of protocol sessions.
S3FNET_GRAPH_PROTONUM_MAP pno_map
Mapping between protocol numbers and instances of protocol sessions.
S3FNET_GRAPH_PSESS_VECTOR protocol_list
List of protocol sessions created.
Detailed Description
A network interface.
This class represents a network interface card (NIC) inside a node (e.g., host, router, switch). A node may contain multiple network interfaces. The network_interface class is a protocol graph consisting of two protocol sessions: the MAC layer and the PHY layer. If unspecified in DML, the default MAC layer protocol is SimpleMac and the default PHY layer protocol is SimplePhy.
Definition at line 36 of file network_interface.h.
Constructor & Destructor Documentation
s3f::s3fnet::NetworkInterface::NetworkInterface (Host * parent, long id)
The constructor.
The parent object is the host containing this network interface.
Definition at line 37 of file network_interface.cc.
References s3f::s3fnet::Mac48Address::Allocate(), IFACE_DUMP, mac48_addr, and s3f::s3fnet::DmlObject::myParent.
                                                            :
   DmlObject(parent, nicid), attached_link(0), mac_sess(0), phy_sess(0),
   is_of_ctrl_iface(false), of_switch_sess(NULL), is_promiscuous(false)
 {
   assert(myParent); // the parent is the host
   IFACE_DUMP(printf("[id=%ld] new network interface.\n", nicid));
   /* init mac48_addr */
   mac48_addr = Mac48Address::Allocate();
 }
s3f::s3fnet::NetworkInterface::~NetworkInterface () virtual
The destructor.
Definition at line 49 of file network_interface.cc.
References IFACE_DUMP, s3f::s3fnet::IPPrefix::ip2txt(), ip_addr, s3f::s3fnet::DmlObject::nhi, and s3f::s3fnet::Nhi::toString().
 {
   IFACE_DUMP(printf("[nhi=\"%s\", ip=\"%s\"] delete network interface.\n",
                     nhi.toString(), IPPrefix::ip2txt(ip_addr)));
 }
Member Function Documentation
void s3f::s3fnet::NetworkInterface::config (s3f::dml::Configuration * cfg) virtual
Configure the network interface from DML.
Reimplemented from s3f::s3fnet::ProtocolGraph.
Definition at line 55 of file network_interface.cc.
References s3f::s3fnet::ProtocolGraph::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::LowestProtocolSession::control(), s3f::s3fnet::NicProtocolSession::control(), DEFAULT_MAC_CLASSNAME, DEFAULT_PHY_CLASSNAME, SimCtrl::errcode2txt(), s3f::s3fnet::error_quit(), getHost(), s3f::s3fnet::Net::getNameService(), s3f::s3fnet::Host::getNetworkLayerProtocol(), s3f::s3fnet::Net::getTopNet(), s3f::s3fnet::Host::getVEID(), ic, s3f::s3fnet::DmlObject::id, IFACE_DUMP, s3f::s3fnet::Host::inNet(), s3f::s3fnet::ProtocolGraph::insert_session(), s3f::s3fnet::IPPrefix::ip2txt(), ip_addr, is_of_ctrl_iface, is_promiscuous, s3f::s3fnet::Host::isOpenVZEmu(), mac48_addr, MAC_PROTOCOL_NAME, mac_sess, s3f::s3fnet::DmlObject::myParent, s3f::s3fnet::ProtocolSession::name, s3f::s3fnet::Protocols::newInstance(), s3f::s3fnet::DmlObject::nhi, s3f::s3fnet::NameService::nhi2ip(), s3f::s3fnet::Nhi::NHI_INTERFACE, PHY_PROTOCOL_NAME, phy_sess, s3f::s3fnet::PSESS_CTRL_SESSION_IS_LOWEST, s3f::s3fnet::PSESS_CTRL_SESSION_SET_CHILD, s3f::s3fnet::PSESS_CTRL_SESSION_SET_PARENT, s3f::s3fnet::Net::register_interface(), s3f::s3fnet::ProtocolGraph::sessionForName(), InChannel::set_ve_attached(), SimCtrl::set_ve_ifip(), s3f::s3fnet::sstrdup(), s3f::s3fnet::Nhi::toStlString(), s3f::s3fnet::Nhi::type, and s3f::s3fnet::ProtocolSession::use.
Referenced by s3f::s3fnet::Host::config_network_interface().
 {
   // settle the nhi address of this interface
   nhi = myParent->nhi;
   nhi += id;
   nhi.type = Nhi::NHI_INTERFACE;
   // settle the ip address and register the interface to the community
   S3FNET_STRING nhi_str = nhi.toStlString();
   Net* owner_net = getHost()->inNet();
   ip_addr = owner_net->getNameService()->nhi2ip(nhi_str);
 #ifdef OPENVZ_EMULATION
   //set ip address for the corresponding VE if the host is an emulation node
   if(getHost()->isOpenVZEmu() == true)
   {
           int idbase = owner_net->getTopNet()->get_idbase();
           int veid = getHost()->getVEID();
           SimCtrl* simCtrl = owner_net->getTopNet()->getSimCtrl();
           char ip_buf[20];
           int return_code = simCtrl->set_ve_ifip(idbase+veid, id, IPPrefix::ip2txt(ip_addr, ip_buf));
           if(return_code != 0)
           {
                   error_quit("NetworkInterface::config(), simCtrl->set_ve_ifip() error, return code = %s\n", SimCtrl::errcode2txt(return_code));
           }
   }
 #endif
   owner_net->register_interface(this, ip_addr, getHost()->isOpenVZEmu());
   IFACE_DUMP(cout << "NIC = " << nhi_str.c_str()
                   << ", IP = " << IPPrefix::ip2txt(ip_addr)
                   << ", MAC = " << mac48_addr
                   << ", IsOpenVZEmu = " << getHost()->isOpenVZEmu()
                   << ", iface_id = " << id << endl;);
   // configure the protocol sessions (this will skip the mac/phy
   // session config unless they are specified explicitly in dml)
   ProtocolGraph::config(cfg);
   char* str = (char*)cfg->findSingle("of_ctrl_iface");
   if(str)
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: invalid of_ctrl_iface attribute.\n");
     if(!strcasecmp(str, "true")) is_of_ctrl_iface = true;
     else is_of_ctrl_iface = false;
   }
   else is_of_ctrl_iface = false;
   str = (char*)cfg->findSingle("promiscuous_mode");
   if(str)
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: invalid promiscuous_mode attribute.\n");
     if(!strcasecmp(str, "true")) is_promiscuous = true;
     else is_promiscuous = false;
   }
   else is_promiscuous = false;
   // if mac protocol is not specified, create the default mac protocol
   mac_sess = (NicProtocolSession*)sessionForName(MAC_PROTOCOL_NAME);
   if(!mac_sess)
   {
     mac_sess = (NicProtocolSession*)Protocols::newInstance(DEFAULT_MAC_CLASSNAME, this);
     if(!mac_sess)
         error_quit("ERROR: unregistered protocol \"%s\".\n", DEFAULT_MAC_CLASSNAME);
     // configure the mac protocol session using the interface dml attributes
     mac_sess->config(cfg);
     mac_sess->name = sstrdup(MAC_PROTOCOL_NAME);
     mac_sess->use  = sstrdup(DEFAULT_MAC_CLASSNAME);
     insert_session(mac_sess);
   }
   IFACE_DUMP(printf("[nhi=\"%s\", ip=\"%s\"] config(): mac session \"%s\".\n",
                     nhi_str.c_str(), IPPrefix::ip2txt(ip_addr), mac_sess->use));
   // if phy protocol is not specified, create the default phy protocol
   phy_sess = (LowestProtocolSession*)sessionForName(PHY_PROTOCOL_NAME);
   if(!phy_sess)
   {
     phy_sess = (LowestProtocolSession*)Protocols::newInstance(DEFAULT_PHY_CLASSNAME, this);
     if(!phy_sess)
         error_quit("ERROR: unregistered protocol \"%s\".\n", DEFAULT_PHY_CLASSNAME);
     // configure the phy protocol session using the interface dml attributes
     phy_sess->config(cfg);
     phy_sess->name = sstrdup(PHY_PROTOCOL_NAME);
     phy_sess->use  = sstrdup(DEFAULT_PHY_CLASSNAME);
     insert_session(phy_sess);
   }
   bool is_lowest;
   if(phy_sess->control(PSESS_CTRL_SESSION_IS_LOWEST, &is_lowest, 0) || !is_lowest)
     error_quit("ERROR: PHY session \"%s\" is not the lowest protocol session.\n", phy_sess->use);
   IFACE_DUMP(printf("[nhi=\"%s\", ip=\"%s\"] config(): phy session \"%s\".\n",
                     nhi_str.c_str(), IPPrefix::ip2txt(ip_addr), phy_sess->use));
   ProtocolSession* ip_sess = getHost()->getNetworkLayerProtocol();
   mac_sess->control(PSESS_CTRL_SESSION_SET_CHILD, 0, phy_sess);
   mac_sess->control(PSESS_CTRL_SESSION_SET_PARENT, 0, ip_sess);
   phy_sess->control(PSESS_CTRL_SESSION_SET_PARENT, 0, mac_sess);
   //create InChannel
   stringstream ss;
   ss << "IC-" << nhi.toStlString();
   ic = new InChannel( (Host *)this->myParent, ss.str());
 #ifdef OPENVZ_EMULATION
   if(getHost()->isOpenVZEmu() == true)
           ic->set_ve_attached(true);
 #endif
 }
void s3f::s3fnet::NetworkInterface::init () virtual
Initialize all protocol sessions defined in this network interface.
Reimplemented from s3f::s3fnet::ProtocolGraph.
Definition at line 170 of file network_interface.cc.
References s3f::s3fnet::error_quit(), getHost(), IFACE_DUMP, s3f::s3fnet::ProtocolGraph::init(), s3f::s3fnet::IPPrefix::ip2txt(), ip_addr, is_of_ctrl_iface, s3f::s3fnet::DmlObject::nhi, of_switch_sess, s3f::s3fnet::OpenFlowSwitchSession::ofctrl_port, s3f::s3fnet::S3FNET_PROTOCOL_TYPE_OPENFLOW_SWITCH, s3f::s3fnet::ProtocolGraph::sessionForNumber(), and s3f::s3fnet::Nhi::toString().
 {
   IFACE_DUMP(printf("[nhi=\"%s\", ip=\"%s\"] init().\n", nhi.toString(), IPPrefix::ip2txt(ip_addr)));
   ProtocolGraph::init();
   if(is_of_ctrl_iface == true)
   {
     of_switch_sess = (OpenFlowSwitchSession*)(getHost()->sessionForNumber(S3FNET_PROTOCOL_TYPE_OPENFLOW_SWITCH));
     if(!of_switch_sess)
         error_quit("NetworkInterface::init(), no OpenFlowSwitchSession is found.");
     of_switch_sess->ofctrl_port = this;
   }
 }
IPADDR s3f::s3fnet::NetworkInterface::getIP () inline
Get the IP address of this network interface.
The IP address is not settled until the end of the config phase.
Definition at line 62 of file network_interface.h.
Referenced by s3f::s3fnet::RouteInfo::display(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::RouteInfo::resolve(), and s3f::s3fnet::DMLRouteInfo::resolve().
 { return ip_addr; }
MACADDR s3f::s3fnet::NetworkInterface::getMacAddr () inline
Get the MAC address of this network interface.
In this function, the MAC address is treated the same as IP (cast to long). The MAC address is not settled until the end of the config phase.
Definition at line 69 of file network_interface.h.
References ARP_IP2MAC.
 { return ARP_IP2MAC(ip_addr); };
Mac48Address* s3f::s3fnet::NetworkInterface::getMac48Addr () inline
Get the 48-bit MAC address of this network interface.
Definition at line 72 of file network_interface.h.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::AddSwitchPort(), s3f::s3fnet::OpenFlowSwitchSession::FillPortDesc(), s3f::s3fnet::NameService::ip2mac48(), s3f::s3fnet::SimpleMac::pop(), and s3f::s3fnet::OpenFlowSwitchSession::ReceivePortMod().
 { return mac48_addr; }
Link* s3f::s3fnet::NetworkInterface::getLink () inline
Return the link that this network interface is attached to.
This method should not be called before the end of the config phase.
Definition at line 78 of file network_interface.h.
Referenced by s3f::s3fnet::RouteInfo::resolve(), and s3f::s3fnet::DMLRouteInfo::resolve().
 { return attached_link; }
ProtocolSession* s3f::s3fnet::NetworkInterface::getHighestProtocolSession () inline
Return the highest protocol session in the interface, i.e., the MAC session.
Definition at line 81 of file network_interface.h.
Referenced by s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), s3f::s3fnet::OpenFlowSwitchSession::OutputControl(), s3f::s3fnet::OpenFlowSwitchSession::OutputPacket(), and s3f::s3fnet::IPSession::push().
 { return mac_sess; }
ProtocolSession* s3f::s3fnet::NetworkInterface::getLowestProtocolSession () inline
Return the lowest protocol session in the interface, i.e., the physical layer session.
Definition at line 84 of file network_interface.h.
Referenced by s3f::s3fnet::Link::connect(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), s3f::s3fnet::OpenFlowSwitchSession::OutputControl(), and s3f::s3fnet::OpenFlowSwitchSession::OutputPacket().
 { return phy_sess; }
Host * s3f::s3fnet::NetworkInterface::getHost ()
Return the host that contains this network interface.
Definition at line 313 of file network_interface.cc.
References s3f::s3fnet::DmlObject::myParent.
Referenced by config(), s3f::s3fnet::Link::connect(), handle_openflow_message_to_controller(), s3f::s3fnet::NicProtocolSession::inHost(), init(), s3f::s3fnet::NameService::ip2hostobj(), receivePacket(), and sendPacket().
 {
   return dynamic_cast<Host*>(myParent);
 }
void s3f::s3fnet::NetworkInterface::display (int indent = 0) virtual
Print out the name of this network interface.
Reimplemented from s3f::s3fnet::DmlObject.
Definition at line 318 of file network_interface.cc.
 {
   printf("%*cNetworkInterface %lu", indent, ' ', id);
 }
void s3f::s3fnet::NetworkInterface::sendPacket (Activation pkt, ltime_t delay)
Send a packet with the given delay.
Essentially, the OutChannel->write is called
Parameters
pkt packet to send.
delay OutChannel Write Delay, including propagation delay and packet transfer delay
Definition at line 184 of file network_interface.cc.
References attached_link, Entity::d2t(), getHost(), s3f::s3fnet::Host::getNowWithThousandSeparator(), IFACE_DUMP, s3f::s3fnet::IPPrefix::ip2txt(), ip_addr, s3f::s3fnet::Link::min_delay, s3f::s3fnet::DmlObject::nhi, oc, s3f::s3fnet::Host::tie_breaking_seed, s3f::s3fnet::Nhi::toString(), and OutChannel::write().
Referenced by s3f::s3fnet::SimplePhy::sendPacket().
 {
   IFACE_DUMP(printf("[nhi=\"%s\", ip=\"%s\"] %s: send packet with delay %ld.\n",
                     nhi.toString(), IPPrefix::ip2txt(ip_addr), getHost()->getNowWithThousandSeparator(), delay));
   unsigned int pri = getHost()->tie_breaking_seed;
   ltime_t link_min_delay = getHost()->d2t(attached_link->min_delay, 0);
   if(delay - link_min_delay < 0)
   {
           printf("Warning: packet delay (%ld) < link's min packet transfer delay (%ld), "
                           "consider re-assign the min_packet_transfer_delay in dml\n",
                           delay, link_min_delay);
           delay = 0;
   }
   else
   {
           delay = delay - link_min_delay;
   }
   IFACE_DUMP(printf("NetworkInterface::sendPacket, link_min_delay = %ld, "
                   "delay to write to outChannel = %ld, pri = %u\n", link_min_delay, delay, pri));
   oc->write(pkt, delay, pri);
 }
void s3f::s3fnet::NetworkInterface::receivePacket (Activation pkt)
Receive a packet.
Called by the inChannnel activation function
Definition at line 216 of file network_interface.cc.
References attached_link, emu_packet_modify_iface(), Message::erase_all(), s3f::s3fnet::error_quit(), s3f::s3fnet::Link::get_rdrop_rate(), getHost(), s3f::s3fnet::Host::getNowWithThousandSeparator(), s3f::s3fnet::ProtocolSession::getRandom(), handle_openflow_message_to_controller(), s3f::s3fnet::OpenFlowSwitchSession::HandleControlInput(), IFACE_DUMP, s3f::s3fnet::IPPrefix::ip2txt(), ip_addr, is_of_ctrl_iface, s3f::s3fnet::DmlObject::nhi, of_switch_sess, phy_sess, s3f::s3fnet::LowestProtocolSession::receivePacket(), s3f::s3fnet::S3FNET_PROTOCOL_TYPE_OPENFLOW_CONTROLLER, s3f::s3fnet::Nhi::toString(), s3f::s3fnet::ProtocolMessage::type(), and Random::RNG::Uniform().
Referenced by s3f::s3fnet::Host::listen().
 {
         if (phy_sess->getRandom()->Uniform(0, 1) < attached_link->get_rdrop_rate()) //drop the receiving packets
         {
                 IFACE_DUMP(printf("[nhi=\"%s\", ip=\"%s\"] %s: receive a packet, but dropped.\n",
                                 nhi.toString(), IPPrefix::ip2txt(ip_addr), getHost()->getNowWithThousandSeparator()));
                 pkt->erase_all();
                 return;
         }
         else
         {
                 IFACE_DUMP(printf("[nhi=\"%s\", ip=\"%s\"] %s: receive a packet.\n",
                                 nhi.toString(), IPPrefix::ip2txt(ip_addr), getHost()->getNowWithThousandSeparator()));
         }
         //if the host is an openflow controller, handle the message (should be switch->controller message) directly
         if(getHost()->is_of_ctrl == true)
         {
                 handle_openflow_message_to_controller(pkt);
                 return;
         }
         // handle the controller-to-switch message
         if(is_of_ctrl_iface == true && getHost()->isOpenFlowSwitch() == true)
         {
                 ProtocolMessage* msg = (ProtocolMessage*)pkt;
                 if(msg->type() != S3FNET_PROTOCOL_TYPE_OPENFLOW_CONTROLLER)
                         error_quit("NetworkInterface::receivePacket(), an OpenFlow switch received a packet on its controller interface, "
                                         "but the packet type is not S3FNET_PROTOCOL_TYPE_OPENFLOW_CONTROLLER.");
                 assert(of_switch_sess);
                 of_switch_sess->HandleControlInput(pkt);
                 return;
         }
 #ifdef OPENVZ_EMULATION
         if(getHost()->isOpenVZEmu() == true)
         {
                 emu_packet_modify_iface(pkt);
         }
 #endif
         // we pass the packet directly to the phy session
         phy_sess->receivePacket(pkt, id);
 }
void s3f::s3fnet::NetworkInterface::handle_openflow_message_to_controller (Activation pkt)
Handle the message from openflow switch to openflow controller.
Definition at line 262 of file network_interface.cc.
References s3f::s3fnet::error_quit(), getHost(), s3f::s3fnet::NO_OF_CONTROLLER, s3f::s3fnet::Host::of_ctrl_sess, s3f::s3fnet::OF_LEARNING_SWITCH_CONTROLLER_ENTITY, s3f::s3fnet::S3FNET_PROTOCOL_TYPE_OPENFLOW_CONTROLLER, s3f::s3fnet::ProtocolMessage::type(), and s3f::s3fnet::OpenFlowControllerSession::type.
Referenced by receivePacket().
 {
         ProtocolMessage* msg = (ProtocolMessage*)pkt;
         assert(msg!=0);
         if(msg->type() != S3FNET_PROTOCOL_TYPE_OPENFLOW_CONTROLLER)
         {
                 error_quit("OpenFlowController received a non-control message.");
         }
         OpenFlowControllerSession* of_ctrl = getHost()->of_ctrl_sess;
         assert(of_ctrl);
         switch(of_ctrl->type)
         {
                 case OF_LEARNING_SWITCH_CONTROLLER_ENTITY:
                         ((LearningControllerSession*)of_ctrl)->HandleInquiryMessageFromOFSwitch(pkt, this);
                         break;
                 case NO_OF_CONTROLLER:
                         error_quit("NetworkInterface::handle_openflow_message_to_controller(), no controller entity.");
                         break;
                 default:
                         error_quit("NetworkInterface::handle_openflow_message_to_controller(), wrong controller entity type.");
                         break;
         }
 }
bool s3f::s3fnet::NetworkInterface::isPromiscuousMode () inline
Indicate if the promiscuous mode is enabled.
Definition at line 121 of file network_interface.h.
Referenced by s3f::s3fnet::SimpleMac::pop().
 { return is_promiscuous; }
void s3f::s3fnet::NetworkInterface::emu_packet_modify_iface (Activation pkt) protected
Modify packet for openvz emu.
In particular, add the network interface id through which the packet is received into the emulation packet.
Definition at line 289 of file network_interface.cc.
References s3f::s3fnet::DmlObject::id, s3f::s3fnet::ProtocolMessage::payload(), s3f::s3fnet::S3FNET_PROTOCOL_TYPE_OPENVZ_EVENT, and s3f::s3fnet::ProtocolMessage::type().
Referenced by receivePacket().
 {
         ProtocolMessage* msg = (ProtocolMessage*)pkt;
         while(msg!=0)
         {
                 if(msg->type() == S3FNET_PROTOCOL_TYPE_OPENVZ_EVENT)
                 {
                         ((OpenVZMessage*)msg)->ifid = id;
                         break;
                 }
                 msg = msg->payload();
         }
 }
void s3f::s3fnet::NetworkInterface::attach_to_link (Link * link) protected
Set the medium that this interface is attached to attached_link() is called after link connection is created.
Definition at line 304 of file network_interface.cc.
References attached_link, and s3f::s3fnet::error_quit().
Referenced by s3f::s3fnet::Link::connect().
 {
   // we should check that an interface is attached to but one link;
   // however, the pre-processing step should have already done that
   if(attached_link)
     error_quit("ERROR: NetworkInterface::attach_to_link(), the interface cannot be attached to multiple links.\n");
   attached_link = link;
 }
void s3f::s3fnet::ProtocolGraph::wrapup () virtual inherited
The wrapup method is called at the end of the simulation.
It is used to collect statistical information of the simulation run. The wrapup method in turn calls the wrapup methods of all protocol sessions in the protocol graph. The order in which protocol sessions wrap up should NOT be expected!
Definition at line 65 of file protocol_graph.cc.
References s3f::s3fnet::ProtocolGraph::protocol_list.
 {
   // wrapup each protocol session
   for(S3FNET_GRAPH_PSESS_VECTOR::reverse_iterator iter = protocol_list.rbegin();
       iter != protocol_list.rend(); iter++)
   {
     if(!(*iter)->wrapped_up()) (*iter)->wrapup();
   }
 }
ProtocolSession * s3f::s3fnet::ProtocolGraph::sessionForName (char * pname) inherited
If a protocol session has been created and registered under the given name, the method returns the protocol session.
Otherwise, a NULL is returned.
Definition at line 75 of file protocol_graph.cc.
References s3f::s3fnet::ProtocolGraph::pname_map.
Referenced by s3f::s3fnet::SocketMaster::bind(), s3f::s3fnet::NBSocketMaster::bind(), config(), s3f::s3fnet::Host::config(), s3f::s3fnet::UDPMaster::init(), and s3f::s3fnet::TCPMaster::init().
 {
   // return protocol session of the given name or NULL if not found
   S3FNET_GRAPH_PROTONAME_MAP::iterator iter;
   iter = pname_map.find(pname);
   if(iter != pname_map.end()) return (*iter).second;
   else return 0;
 }
ProtocolSession * s3f::s3fnet::ProtocolGraph::sessionForNumber (int pno) inherited
If a protocol session has been created and registered under the given protocol number, the method returns the protocol session.
Otherwise, a NULL is returned.
Definition at line 84 of file protocol_graph.cc.
References s3f::s3fnet::ProtocolGraph::pno_map.
Referenced by s3f::s3fnet::IPSession::get_parent_by_protocol(), init(), s3f::s3fnet::SimpleMac::pop(), and s3f::s3fnet::OpenFlowSwitchSession::SetController().
 {
   // return protocol session of the given name or NULL if not found
   S3FNET_GRAPH_PROTONUM_MAP::iterator iter = pno_map.find(pno);
   if(iter != pno_map.end()) return (*iter).second;
   else return 0;
 }
ProtocolSession * s3f::s3fnet::ProtocolGraph::config_session (s3f::dml::Configuration * cfg) protected inherited
Internal use: to configure a protocol session.
Definition at line 108 of file protocol_graph.cc.
References s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolGraph::insert_session(), and s3f::s3fnet::Protocols::newInstance().
Referenced by s3f::s3fnet::ProtocolGraph::config().
 {
   // find out session name from 'name' attribute
   char* str= (char*)cfg->findSingle("name");
   if(!str)
     error_quit("ERROR: session missing NAME attribute");
   if(s3f::dml::dmlConfig::isConf(str))
     error_quit("ERROR: invalid ProtocolSession.NAME.\n");
   S3FNET_STRING sessname = str;
   // find out class name from 'use' attribute
   char* classname = (char*)cfg->findSingle("use");
   if(!classname)
     error_quit("ERROR: session missing USE attribute");
   if(s3f::dml::dmlConfig::isConf(classname))
     error_quit("ERROR: invalid ProtocolSession.USE.\n");
   // classname is not copied from dml library, so it's temporary
   // valid until the next dml query!
   // create a new protocol session
   ProtocolSession* psess = Protocols::newInstance(classname, this);
   if(!psess)
   {
     error_quit("ERROR: failed to create protocol \"%s\".\n", classname);
   }
   // configure the protocol session
   psess->config(cfg);
   insert_session(psess);
   return psess;
 }
void s3f::s3fnet::ProtocolGraph::insert_session (ProtocolSession * psess) protected inherited
Insert a protocol session to this protocol graph.
Definition at line 141 of file protocol_graph.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolSession::getProtocolNumber(), s3f::s3fnet::ProtocolSession::instantiation_type(), s3f::s3fnet::ProtocolSession::name, s3f::s3fnet::ProtocolGraph::pname_map, s3f::s3fnet::ProtocolGraph::pno_map, s3f::s3fnet::ProtocolSession::PROT_MULTIPLE_INSTANCES, s3f::s3fnet::ProtocolSession::PROT_UNIQUE_INSTANCE, s3f::s3fnet::ProtocolGraph::protocol_list, S3FNET_MAKE_PAIR, S3FNET_PAIR, and s3f::s3fnet::ProtocolSession::use.
Referenced by config(), s3f::s3fnet::Host::config(), and s3f::s3fnet::ProtocolGraph::config_session().
 {
   S3FNET_PAIR(S3FNET_GRAPH_PROTONAME_MAP::iterator, bool) ret0 =
     pname_map.insert(S3FNET_MAKE_PAIR(S3FNET_STRING(psess->name), psess));
   if(!ret0.second)
   {
     if(psess->instantiation_type() == ProtocolSession::PROT_UNIQUE_INSTANCE)
       error_quit("ERROR: protocol session \"%s\" only allows unique instance.\n", psess->use);
     else if(psess->instantiation_type() == ProtocolSession::PROT_MULTIPLE_INSTANCES &&
             strcasecmp((*ret0.first).second->use, psess->use))
       error_quit("ERROR: protocol session \"%s\" allows multiple instances of the same implementation.\n", psess->use);
   }
   int sno = psess->getProtocolNumber();
   S3FNET_PAIR(S3FNET_GRAPH_PROTONUM_MAP::iterator, bool) ret1 = pno_map.insert(S3FNET_MAKE_PAIR(sno, psess));
   if(!ret1.second)
   {
     if(psess->instantiation_type() == ProtocolSession::PROT_UNIQUE_INSTANCE)
       error_quit("ERROR: protocol session \"%s\" only allows unique instance.\n", psess->use);
     else if(psess->instantiation_type() == ProtocolSession::PROT_MULTIPLE_INSTANCES &&
             strcasecmp((*ret1.first).second->use, psess->use))
       error_quit("ERROR: protocol session \"%s\" allows multiple instances of the same implementation.\n", psess->use);
   }
   protocol_list.push_back(psess);
 }
Member Data Documentation
OutChannel* s3f::s3fnet::NetworkInterface::oc
The associated S3F OutChannel.
Definition at line 107 of file network_interface.h.
Referenced by s3f::s3fnet::Link::connect(), and sendPacket().
InChannel* s3f::s3fnet::NetworkInterface::ic
The associated S3F InChannel.
Definition at line 110 of file network_interface.h.
Referenced by config(), and s3f::s3fnet::Link::connect().
bool s3f::s3fnet::NetworkInterface::is_of_ctrl_iface
Indicate whether the network interface is the one connecting to an openflow controller, only an openflow switch has such interface.
Definition at line 114 of file network_interface.h.
Referenced by config(), init(), and receivePacket().
OpenFlowSwitchSession* s3f::s3fnet::NetworkInterface::of_switch_sess
Pointer to the OpenFlowSwitchSession protocol session layer.
Definition at line 116 of file network_interface.h.
Referenced by init(), and receivePacket().
IPADDR s3f::s3fnet::NetworkInterface::ip_addr protected
The IP address allocated to this interface.
Definition at line 125 of file network_interface.h.
Referenced by config(), init(), receivePacket(), sendPacket(), and ~NetworkInterface().
MACADDR s3f::s3fnet::NetworkInterface::mac_addr protected
The MAC address allocated to this interface.
Definition at line 128 of file network_interface.h.
Mac48Address* s3f::s3fnet::NetworkInterface::mac48_addr protected
The MAC48 address (48 bit IEEE addresses) allocated to this interface.
Definition at line 131 of file network_interface.h.
Referenced by config(), and NetworkInterface().
bool s3f::s3fnet::NetworkInterface::is_oc_connected protected
Indicator of whether the OutChannel is connected.
Default is false, change when mapping to other InChannel
Definition at line 137 of file network_interface.h.
Referenced by s3f::s3fnet::Link::connect().
bool s3f::s3fnet::NetworkInterface::is_ic_connected protected
Indicator of whether the InChannel is connected.
Default is false, change when mapping to other OutChannel
Definition at line 143 of file network_interface.h.
Referenced by s3f::s3fnet::Link::connect().
Link* s3f::s3fnet::NetworkInterface::attached_link protected
The link that this interface is attached to.
Definition at line 157 of file network_interface.h.
Referenced by attach_to_link(), receivePacket(), and sendPacket().
NicProtocolSession* s3f::s3fnet::NetworkInterface::mac_sess protected
The MAC layer protocol.
Should be the highest protocol layer in the interface's protocol graph.
Definition at line 162 of file network_interface.h.
Referenced by config().
LowestProtocolSession* s3f::s3fnet::NetworkInterface::phy_sess protected
The PHY layer protocol.
Should be the lowest protocol layer in the interface's protocol graph.
Definition at line 167 of file network_interface.h.
Referenced by config(), and receivePacket().
bool s3f::s3fnet::NetworkInterface::is_promiscuous protected
whether the network interface uses promiscuous mode
Definition at line 170 of file network_interface.h.
Referenced by config().
long s3f::s3fnet::DmlObject::id inherited
Every DmlObject object must have an ID obtained from the DML.
Definition at line 44 of file dmlobj.h.
Referenced by config(), s3f::s3fnet::Host::config(), s3f::s3fnet::Net::config(), s3f::s3fnet::Host::config_network_interface(), s3f::s3fnet::RouteInfo::display(), and emu_packet_modify_iface().
Nhi s3f::s3fnet::DmlObject::nhi inherited
The nhi address to identify the object.
Definition at line 47 of file dmlobj.h.
Referenced by s3f::s3fnet::UDPSession::abort(), s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::Link::config(), config(), s3f::s3fnet::Host::config(), s3f::s3fnet::RouteInfo::config(), s3f::s3fnet::Net::config(), s3f::s3fnet::Host::config_network_interface(), s3f::s3fnet::UDPSession::connect(), s3f::s3fnet::Net::connect_links(), s3f::s3fnet::UDPSession::disconnect(), s3f::s3fnet::Link::display(), s3f::s3fnet::Net::display(), s3f::s3fnet::UDPClientSessionContinuation::failure(), s3f::s3fnet::UDPServerSessionContinuation::failure(), s3f::s3fnet::TCPServerSessionContinuation::failure(), s3f::s3fnet::TCPClientSessionContinuation::failure(), s3f::s3fnet::BTCPClientSessionContinuation::failure(), s3f::s3fnet::Host::getDefaultIP(), s3f::s3fnet::Traffic::getServers(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), init(), s3f::s3fnet::Host::init(), s3f::s3fnet::Net::init(), s3f::s3fnet::UDPSession::listen(), s3f::s3fnet::Host::loadForwardingTable(), s3f::s3fnet::LearningController::process_recv_packet(), s3f::s3fnet::UDPSession::receive(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::LearningControllerSession::ReceiveFromSwitch(), receivePacket(), s3f::s3fnet::Net::register_host(), s3f::s3fnet::RouteInfo::resolve(), s3f::s3fnet::DMLRouteInfo::resolve(), s3f::s3fnet::NBTCPClientSessionContinuation::resume(), s3f::s3fnet::NBTCPServerSessionContinuation::resume(), s3f::s3fnet::UDPSession::send(), s3f::s3fnet::TCPSession::send_data(), sendPacket(), s3f::s3fnet::UDPSession::setSource(), s3f::s3fnet::TCPSession::slowTimeoutHandling(), s3f::s3fnet::NBTCPServerSessionContinuation::success(), s3f::s3fnet::TCPSession::TCPSession(), s3f::s3fnet::UDPSession::UDPSession(), s3f::s3fnet::TCPSession::update_timeout(), s3f::s3fnet::UDPSession::wake_app(), s3f::s3fnet::Host::~Host(), s3f::s3fnet::Net::~Net(), and ~NetworkInterface().
DmlObject* s3f::s3fnet::DmlObject::myParent inherited
The parent.
DML objects are nested.
Definition at line 50 of file dmlobj.h.
Referenced by s3f::s3fnet::Link::config(), config(), s3f::s3fnet::Host::config(), s3f::s3fnet::Net::config(), s3f::s3fnet::Link::connect(), s3f::s3fnet::Net::control(), getHost(), s3f::s3fnet::Net::init(), s3f::s3fnet::Host::inNet(), NetworkInterface(), and s3f::s3fnet::DMLRouteInfo::resolve().
char* s3f::s3fnet::ProtocolGraph::description inherited
Optional string to describe the protocol graph.
The string is NULL if the DML 'graph' attribute does not contain a 'description' attribute.
Definition at line 43 of file protocol_graph.h.
Referenced by s3f::s3fnet::ProtocolGraph::config(), and s3f::s3fnet::ProtocolGraph::~ProtocolGraph().
S3FNET_GRAPH_PROTONAME_MAP s3f::s3fnet::ProtocolGraph::pname_map protected inherited
Mapping between protocol names and instances of protocol sessions.
Definition at line 108 of file protocol_graph.h.
Referenced by s3f::s3fnet::ProtocolGraph::config(), s3f::s3fnet::ProtocolGraph::insert_session(), and s3f::s3fnet::ProtocolGraph::sessionForName().
S3FNET_GRAPH_PROTONUM_MAP s3f::s3fnet::ProtocolGraph::pno_map protected inherited
Mapping between protocol numbers and instances of protocol sessions.
Definition at line 111 of file protocol_graph.h.
Referenced by s3f::s3fnet::ProtocolGraph::insert_session(), and s3f::s3fnet::ProtocolGraph::sessionForNumber().
S3FNET_GRAPH_PSESS_VECTOR s3f::s3fnet::ProtocolGraph::protocol_list protected inherited
List of protocol sessions created.
Definition at line 114 of file protocol_graph.h.
Referenced by s3f::s3fnet::ProtocolGraph::init(), s3f::s3fnet::ProtocolGraph::insert_session(), s3f::s3fnet::ProtocolGraph::wrapup(), and s3f::s3fnet::ProtocolGraph::~ProtocolGraph().
The documentation for this class was generated from the following files:
network_interface.h
network_interface.cc