S3F: s3f::s3fnet::ProtocolSession Class Reference
s3f::s3fnet::ProtocolSession Class Reference abstract
A protocol layer on the protocol stack.
#include <protocol_session.h>
Public Types
enum InstantiationType { PROT_UNIQUE_INSTANCE = 0x00, PROT_MULTIPLE_INSTANCES = 0x01, PROT_MULTIPLE_IMPLEMENTATIONS = 0x02 }
Multiple protocol session instantiation type.
enum ExecutionStage { PSESS_CREATED = 0, PSESS_CONFIGURED = 1, PSESS_INITIALIZED = 2, PSESS_WRAPPED_UP = 3 }
A normal protocol session must go though the following stages.
Public Member Functions
virtual void config (s3f::dml::Configuration *cfg)
The config method is used to configure the protocol session from DML description.
virtual void init ()
The method is used to initialize the protocol session once the protocol session has been created and configured.
virtual void wrapup ()
The method is used to wrap up the protocol session.
int pushdown (Activation msg, ProtocolSession *hi_sess, void *extinfo=0, size_t extinfo_size=0)
The original push method is divided into pushdown() and push().
int popup (Activation msg, ProtocolSession *lo_sess, void *extinfo=0, size_t extinfo_size=0)
The original pop method is divided into popup() and pop().
virtual int control (int ctrltyp, void *ctrlmsg, ProtocolSession *sess)
The control method is used by the protocol session to receive control messages (or information queries) from other protocol sessions both above and below this protocol session on the stack.
ProtocolGraph * inGraph ()
The method returns the protocol graph in which this protocol session resides.
virtual Host * inHost ()
Return a pointer to the host owning this protocol session.
virtual int getProtocolNumber ()=0
Each protocol session should have its unique protocol number.
Random::RNG * getRandom ()
The method returns a pointer to the random number generator.
ltime_t getNow ()
The method returns the current simulation time.
char * getNowWithThousandSeparator ()
For printing the current simulation time in a better readable format.
int configured ()
This method returns true if the protocol session has been configured.
int initialized ()
This method returns true if the protocol session has been initialized.
int wrapped_up ()
This method returns true if the protocol session has been wrapped up.
virtual const char * psesstype ()
Public Attributes
char * name
Symbolic name of the protocol this session implements.
float version
Version number of this protocol implemenntation, represented as a floating point number (e.g., 1.23).
char * use
Name of the protocol class from which this protocol session is instantiated.
Protected Member Functions
ProtocolSession (ProtocolGraph *graph)
The constructor is protected; only called from ProtocolGraph.
virtual ~ProtocolSession ()
The destructor is protected; only ProtocolGraph reclaims it.
virtual int instantiation_type ()
This method controls how protocol instances can coexist with one another.
Protected Attributes
ProtocolGraph * ingraph
Points to the protocol graph.
Random::RNG * sess_rng
Pointer to a random number generator.
int stage
This variable indicates the current stage of this protocol session.
Private Member Functions
virtual int push (Activation msg, ProtocolSession *hi_sess, void *extinfo=0, size_t extinfo_size=0)
The method is called when a message is pushed down to this protocol session from the protocol session above.
virtual int pop (Activation msg, ProtocolSession *lo_sess, void *extinfo=0, size_t extinfo_size=0)
The method is called when a message is popped up to this protocol session from the protocol session below.
Detailed Description
A protocol layer on the protocol stack.
The ProtocolSession class represents a protocol layer on the ISO/OSI protocol stack. It's the base class for protocol implementations. The class specifies default mechanisms for how a protocol session should behave. The data path is specified by two methods – push() and pop() – for receiving data from the protocol session above and below. The data exchanged between protocol layers are encapsulated in a ProtocolMessage object. The exchange of control messages between protocol layers (not necessarily adjacent) is implemented through invocations to the control() method. Subclasses may override these methods with specific behavior. Each protocol session class must register with the Protocols class.
See Also
Protocols class for further details.
Definition at line 37 of file protocol_session.h.
Member Enumeration Documentation
enum s3f::s3fnet::ProtocolSession::InstantiationType
Multiple protocol session instantiation type.
Enumerator
PROT_UNIQUE_INSTANCE
PROT_MULTIPLE_INSTANCES
PROT_MULTIPLE_IMPLEMENTATIONS
Definition at line 44 of file protocol_session.h.
{
     PROT_UNIQUE_INSTANCE                = 0x00,
     PROT_MULTIPLE_INSTANCES             = 0x01,
     PROT_MULTIPLE_IMPLEMENTATIONS       = 0x02
   };
enum s3f::s3fnet::ProtocolSession::ExecutionStage
A normal protocol session must go though the following stages.
Enumerator
PSESS_CREATED
this protocol session has just been created
PSESS_CONFIGURED
the config method of this protocol session has been called
PSESS_INITIALIZED
the init method of this protocol session has been called
PSESS_WRAPPED_UP
Definition at line 51 of file protocol_session.h.
                       {
     PSESS_CREATED       = 0,
     PSESS_CONFIGURED    = 1,
     PSESS_INITIALIZED   = 2,
     PSESS_WRAPPED_UP    = 3
   };
Constructor & Destructor Documentation
s3f::s3fnet::ProtocolSession::ProtocolSession (ProtocolGraph * graph) protected
The constructor is protected; only called from ProtocolGraph.
Definition at line 134 of file protocol_session.cc.
                                                      :
   name(0), use(0), ingraph(graph), sess_rng(0), stage(PSESS_CREATED)
 {
   assert(graph);
 }
s3f::s3fnet::ProtocolSession::~ProtocolSession () protected virtual
The destructor is protected; only ProtocolGraph reclaims it.
Definition at line 140 of file protocol_session.cc.
References name, and use.
 {
   /* FIXME: we can't call inHost() here; what can we do?
   if(sess_rng) {
     int seed = inHost()->getHostSeed();
     if(seed) delete sess_rng;
   }
   */
   if(name) delete[] name;
   if(use) delete[] use;
 }
Member Function Documentation
void s3f::s3fnet::ProtocolSession::config (s3f::dml::Configuration * cfg) virtual
The config method is used to configure the protocol session from DML description.
It is expected to be called first, right after the ProtocolSession object is created and before the init method is called. A DML configuration should be passed as an argument to the method and it should be the value (a list of attributes) of a 'session' attribute (inside 'graph'). The default behavior of this method is to find out 'name' and 'use' attributes. The derived class should override this method to obtain protocol specific parameters from the DML description. However, the derived class must not forget to call this method in the base class so that the default behavior is carried out. The config method recognizes the following attributes:
name: name of the protocol session (required)
use: protocol class name (required)
It is important to note that the timer still cannot be used at this stage since the owner community hasn't been resolved. It has to wait until after the init method is called.
Reimplemented in s3f::s3fnet::NBTCPServerSession, s3f::s3fnet::IPSession, s3f::s3fnet::OpenFlowSwitchSession, s3f::s3fnet::BTCPClientSession, s3f::s3fnet::NBTCPClientSession, s3f::s3fnet::TCPMaster, s3f::s3fnet::TCPServerSession, s3f::s3fnet::UDPClientSession, s3f::s3fnet::SimplePhy, s3f::s3fnet::UDPServerSession, s3f::s3fnet::OpenVZEventSession, s3f::s3fnet::OpenFlowControllerSession, s3f::s3fnet::TCPClientSession, s3f::s3fnet::DummySession, and s3f::s3fnet::UDPMaster.
Definition at line 21 of file protocol_session.cc.
References configured(), s3f::s3fnet::error_quit(), name, PSESS_CONFIGURED, s3f::s3fnet::sstrdup(), stage, and use.
Referenced by s3f::s3fnet::UDPMaster::config(), s3f::s3fnet::DummySession::config(), s3f::s3fnet::TCPClientSession::config(), s3f::s3fnet::OpenFlowControllerSession::config(), s3f::s3fnet::OpenVZEventSession::config(), s3f::s3fnet::UDPServerSession::config(), s3f::s3fnet::SimplePhy::config(), s3f::s3fnet::UDPClientSession::config(), s3f::s3fnet::TCPServerSession::config(), s3f::s3fnet::TCPMaster::config(), s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::NBTCPClientSession::config(), s3f::s3fnet::BTCPClientSession::config(), s3f::s3fnet::OpenFlowSwitchSession::config(), s3f::s3fnet::IPSession::config(), s3f::s3fnet::NBTCPServerSession::config(), and s3f::s3fnet::ProtocolGraph::config_session().
 {
   if(configured())
     error_quit("ERROR: duplicate calls to ProtocolSession::config(): "
                "session name is \"%s\".\n", name);
   else stage = PSESS_CONFIGURED;
   char* myname = (char*)cfg->findSingle("name");
   if(myname && s3f::dml::dmlConfig::isConf(myname))
     error_quit("ERROR: ProtocolSession::config(), invalid NAME attribute.\n");
   if(myname) name = sstrdup(myname);
   else name = 0; // cannot do assertion because it may happen for a "default" interface
   char* myuse  = (char*)cfg->findSingle("use");
   if(myuse && s3f::dml::dmlConfig::isConf(myuse))
     error_quit("ERROR: ProtocolSession::config(), invalid USE attribute.\n");
   if(myuse)  use = sstrdup(myuse);
   else use = 0; // cannot do assertion because it may happen for a "default" interface
 }
void s3f::s3fnet::ProtocolSession::init () virtual
The method is used to initialize the protocol session once the protocol session has been created and configured.
The default behavior is doing nothing. The derived class may override this method for protocol specific initialization. Note that the order of initialization of the protocol sessions in a protocol graph is unspecified. Don't rely on the ordering to help sort out the relationships between protocols.
Reimplemented in s3f::s3fnet::NBTCPServerSession, s3f::s3fnet::NBSocketMaster, s3f::s3fnet::IPSession, s3f::s3fnet::SocketMaster, s3f::s3fnet::BTCPClientSession, s3f::s3fnet::NBTCPClientSession, s3f::s3fnet::OpenFlowSwitchSession, s3f::s3fnet::TCPMaster, s3f::s3fnet::TCPServerSession, s3f::s3fnet::UDPClientSession, s3f::s3fnet::UDPServerSession, s3f::s3fnet::TCPClientSession, s3f::s3fnet::SimplePhy, s3f::s3fnet::OpenVZEventSession, s3f::s3fnet::OpenFlowControllerSession, s3f::s3fnet::UDPMaster, s3f::s3fnet::DummySession, and s3f::s3fnet::SimpleMac.
Definition at line 41 of file protocol_session.cc.
References configured(), s3f::s3fnet::error_quit(), s3f::s3fnet::Host::getRandom(), inHost(), initialized(), name, PSESS_INITIALIZED, sess_rng, and stage.
Referenced by s3f::s3fnet::SimpleMac::init(), s3f::s3fnet::DummySession::init(), s3f::s3fnet::UDPMaster::init(), s3f::s3fnet::OpenFlowControllerSession::init(), s3f::s3fnet::OpenVZEventSession::init(), s3f::s3fnet::SimplePhy::init(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPServerSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::TCPServerSession::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::OpenFlowSwitchSession::init(), s3f::s3fnet::NBTCPClientSession::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::SocketMaster::init(), s3f::s3fnet::IPSession::init(), s3f::s3fnet::NBSocketMaster::init(), and s3f::s3fnet::NBTCPServerSession::init().
 {
   // Make sure this init function at the base class should be called
   // by the derived function!
   if(!configured())
     error_quit("ERROR: ProtocolSession \"%s\" init() called before config(), "
                "forgot to call base class's config() in your derived class?\n", name);
   else if(initialized())
     error_quit("ERROR: duplicate calls to ProtocolSession::init(): "
                "session name is \"%s\".\n", name);
   else stage = PSESS_INITIALIZED;
   if(inHost()->getHostSeed() == 0) //host-level rng, i.e. same rng within one host
           sess_rng = inHost()->getRandom();
   else
           sess_rng = new Random::RNG();
 }
void s3f::s3fnet::ProtocolSession::wrapup () virtual
The method is used to wrap up the protocol session.
It is called when the simulation finishes. It is designed to give user a chance to report simulation statistics. The default behavior is doing nothing. Subclass may override this method for protocol specific dealings. Note that there is no specific order in which wrapup is called for protocol sessions in a protocol graph.
Definition at line 59 of file protocol_session.cc.
References s3f::s3fnet::error_quit(), initialized(), name, PSESS_WRAPPED_UP, stage, and wrapped_up().
 {
   // Make sure this init function at the base class should be called
   // by the derived function!
   if(!initialized())
     error_quit("ERROR: ProtocolSession \"%s\" wrapup() called before init(), "
                "forgot to call base class's init() in your derived class?\n", name);
   else if(wrapped_up())
     error_quit("ERROR: duplicate calls to ProtocolSession::wrapup(): "
                "session name is \"%s\".\n", name);
   else stage = PSESS_WRAPPED_UP;
 }
int s3f::s3fnet::ProtocolSession::pushdown (Activation msg, ProtocolSession * hi_sess, void * extinfo = 0, size_t extinfo_size = 0)
The original push method is divided into pushdown() and push().
The pushdown method is the generic part of the code, which is reserved for modeling the handling of messages transferred between protocol layers.
See Also
ProtocolSession::push method for details.
Definition at line 72 of file protocol_session.cc.
References push().
Referenced by s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), s3f::s3fnet::IPSession::control(), s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), s3f::s3fnet::OpenFlowSwitchSession::OutputControl(), s3f::s3fnet::OpenFlowSwitchSession::OutputPacket(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::UDPMaster::push(), s3f::s3fnet::TCPMaster::push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::send(), and s3f::s3fnet::TCPSession::send_data().
 {
   return push(msg, hi_sess, extinfo, extinfo_size);
 }
int s3f::s3fnet::ProtocolSession::popup (Activation msg, ProtocolSession * lo_sess, void * extinfo = 0, size_t extinfo_size = 0)
The original pop method is divided into popup() and pop().
The popup method is the generic part of the code, which is reserved for modeling the handling of messages transferred between protocol layers.
See Also
ProtocolSession::pop method for details.
Definition at line 77 of file protocol_session.cc.
References pop().
Referenced by s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::IPSession::push(), and s3f::s3fnet::SimplePhy::receivePacket().
 {
   return pop(msg, lo_sess, extinfo, extinfo_size);
 }
int s3f::s3fnet::ProtocolSession::control (int ctrltyp, void * ctrlmsg, ProtocolSession * sess) virtual
The control method is used by the protocol session to receive control messages (or information queries) from other protocol sessions both above and below this protocol session on the stack.
The derived class should override this method to provide support for handling different control messages. In this case, the derived class should invoke this method when encountering a control type that it does not know to to process.
The control messages are distinguished via types. The ctrl type is an integer; its meaning is specified by the particular protocol. The users are recommended to use ctrl type values beyond 1000 (excluding 1000). The values within 1000 are reserved. The control message is of type void* and should be cast to the appropriate types accordingly. Note that, unless specified otherwise, the caller is responsible to reclaim the control message once the method returns. The protocol session that invoking this method will have a reference to itself in the third argument.
The method returns an integer, indicating whether the control message is successfully processed. Unless specified otherwise, a zero means success. Non-zero means trouble and the returned value can be used as the error number, the meaning of which is specified by each particular protocol.
For information on a specific control type, see s3f::s3fnet::ProtocolSessionCtrlTypes
Reimplemented in s3f::s3fnet::IPSession, s3f::s3fnet::NBSocketMaster, s3f::s3fnet::SocketMaster, s3f::s3fnet::OpenFlowSwitchSession, s3f::s3fnet::SimplePhy, s3f::s3fnet::OpenVZEventSession, s3f::s3fnet::OpenFlowControllerSession, s3f::s3fnet::UDPMaster, s3f::s3fnet::DummySession, s3f::s3fnet::LowestProtocolSession, and s3f::s3fnet::NicProtocolSession.
Definition at line 92 of file protocol_session.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::PSESS_CTRL_SESSION_GET_INTERFACE, s3f::s3fnet::PSESS_CTRL_SESSION_IS_LOWEST, s3f::s3fnet::PSESS_CTRL_SESSION_SET_CHILD, and s3f::s3fnet::PSESS_CTRL_SESSION_SET_PARENT.
Referenced by s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::TCPSession::clear_app_state(), s3f::s3fnet::Host::config(), s3f::s3fnet::NicProtocolSession::control(), s3f::s3fnet::DummySession::control(), s3f::s3fnet::UDPMaster::control(), s3f::s3fnet::OpenFlowControllerSession::control(), s3f::s3fnet::OpenVZEventSession::control(), s3f::s3fnet::OpenFlowSwitchSession::control(), s3f::s3fnet::SocketMaster::control(), s3f::s3fnet::NBSocketMaster::control(), s3f::s3fnet::IPSession::control(), s3f::s3fnet::Host::loadForwardingTable(), s3f::s3fnet::UDPSession::release(), s3f::s3fnet::UDPSession::wake_app(), and s3f::s3fnet::TCPSession::wake_app().
 {
   switch(ctrltype) {
   case PSESS_CTRL_SESSION_IS_LOWEST:
     assert(ctrlmsg);
     *((bool*)ctrlmsg) = false;
     return 0;
   case PSESS_CTRL_SESSION_GET_INTERFACE:
     assert(ctrlmsg);
     *((NetworkInterface**)ctrlmsg) = 0;
     return 0;
   case PSESS_CTRL_SESSION_SET_PARENT:
   case PSESS_CTRL_SESSION_SET_CHILD:
     return 0;
   default:
     // all control types should be handled at this point; if not, we
     // should report the problem
     error_quit("ERROR: ProtocolSession::control(), "
                "unknown control type: %d.\n", ctrltype);
   }
   return 0;
 }
ProtocolGraph* s3f::s3fnet::ProtocolSession::inGraph () inline
The method returns the protocol graph in which this protocol session resides.
Definition at line 178 of file protocol_session.h.
References ingraph.
Referenced by s3f::s3fnet::SimplePhy::config(), s3f::s3fnet::SimplePhy::control(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::SimpleMac::init(), s3f::s3fnet::SimplePhy::init(), s3f::s3fnet::RedQueue::init(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::SimplePhy::push(), s3f::s3fnet::SimplePhy::receivePacket(), s3f::s3fnet::SimplePhy::sendPacket(), s3f::s3fnet::SimpleMac::SimpleMac(), s3f::s3fnet::SimplePhy::SimplePhy(), s3f::s3fnet::SimpleMac::~SimpleMac(), and s3f::s3fnet::SimplePhy::~SimplePhy().
 { return ingraph; }
Host * s3f::s3fnet::ProtocolSession::inHost () virtual
Return a pointer to the host owning this protocol session.
Reimplemented in s3f::s3fnet::NicProtocolSession.
Definition at line 118 of file protocol_session.cc.
References ingraph.
Referenced by s3f::s3fnet::UDPSession::abort(), s3f::s3fnet::SocketMaster::abort(), s3f::s3fnet::NBSocketMaster::abort(), s3f::s3fnet::SocketMaster::accept(), s3f::s3fnet::NBSocketMaster::accept(), s3f::s3fnet::SocketMaster::accept1a(), s3f::s3fnet::SocketMaster::accept1b(), s3f::s3fnet::SocketMaster::accept2a(), s3f::s3fnet::SocketMaster::accept2b(), s3f::s3fnet::OpenFlowSwitchSession::AddFlow(), s3f::s3fnet::TCPSession::backoff_timeout(), s3f::s3fnet::SocketMaster::bind(), s3f::s3fnet::NBSocketMaster::bind(), s3f::s3fnet::SocketMaster::block_till(), s3f::s3fnet::NBSocketMaster::block_till(), s3f::s3fnet::BTCPClientSession::BTCPClientSession(), s3f::s3fnet::OpenFlowSwitchSession::BufferFromPacket(), s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::UDPServerSession::client_connected(), s3f::s3fnet::SocketMaster::close(), s3f::s3fnet::NBSocketMaster::close(), s3f::s3fnet::SocketMaster::close1(), s3f::s3fnet::NBSocketMaster::close1(), s3f::s3fnet::UDPMaster::config(), s3f::s3fnet::DummySession::config(), s3f::s3fnet::TCPClientSession::config(), s3f::s3fnet::UDPServerSession::config(), s3f::s3fnet::UDPClientSession::config(), s3f::s3fnet::TCPServerSession::config(), s3f::s3fnet::TCPMaster::config(), s3f::s3fnet::NBTCPClientSession::config(), s3f::s3fnet::BTCPClientSession::config(), s3f::s3fnet::IPSession::config(), s3f::s3fnet::NBTCPServerSession::config(), s3f::s3fnet::UDPSession::connect(), s3f::s3fnet::SocketMaster::connect(), s3f::s3fnet::NBSocketMaster::connect(), s3f::s3fnet::SocketMaster::connect1(), s3f::s3fnet::NBSocketMaster::connect1(), s3f::s3fnet::SocketMaster::connected(), s3f::s3fnet::NBSocketMaster::connected(), s3f::s3fnet::UDPMaster::control(), s3f::s3fnet::SocketMaster::control(), s3f::s3fnet::NBSocketMaster::control(), s3f::s3fnet::IPSession::control(), s3f::s3fnet::TCPMaster::createSession(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::UDPServerSession::data_sent(), s3f::s3fnet::TCPServerSession::data_sent(), s3f::s3fnet::UDPSession::disconnect(), s3f::s3fnet::TCPMaster::enableFastTimeout(), s3f::s3fnet::SocketMaster::eof(), s3f::s3fnet::NBSocketMaster::eof(), s3f::s3fnet::UDPClientSessionContinuation::failure(), s3f::s3fnet::UDPServerSessionContinuation::failure(), s3f::s3fnet::TCPServerSessionContinuation::failure(), s3f::s3fnet::TCPClientSessionContinuation::failure(), s3f::s3fnet::BTCPClientSessionContinuation::failure(), s3f::s3fnet::TCPMaster::fast_timer_callback_body(), s3f::s3fnet::Stats::FlowStatsDump(), s3f::s3fnet::OpenFlowSwitchSession::FlowTableLookup(), s3f::s3fnet::IPSession::get_parent_by_protocol(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), getNow(), getNowWithThousandSeparator(), s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::OpenFlowSwitchSession::HandleControlInput(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), s3f::s3fnet::DummySession::init(), s3f::s3fnet::UDPMaster::init(), s3f::s3fnet::OpenFlowControllerSession::init(), s3f::s3fnet::OpenVZEventSession::init(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPServerSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::TCPServerSession::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::OpenFlowSwitchSession::init(), s3f::s3fnet::NBTCPClientSession::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::SocketMaster::init(), s3f::s3fnet::IPSession::init(), init(), s3f::s3fnet::NBSocketMaster::init(), s3f::s3fnet::NBTCPServerSession::init(), s3f::s3fnet::TCPSession::init_state_closed(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::IPSession::IPSession(), s3f::s3fnet::UDPSession::listen(), s3f::s3fnet::SocketMaster::listen(), s3f::s3fnet::NBSocketMaster::listen(), s3f::s3fnet::IPSession::load_forwarding_table(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), s3f::s3fnet::OpenFlowSwitchSession::ModFlow(), s3f::s3fnet::NBSocketMaster::NBSocketMaster(), s3f::s3fnet::NBTCPClientSession::NBTCPClientSession(), s3f::s3fnet::NBTCPServerSession::NBTCPServerSession(), s3f::s3fnet::NBTCPClientSession::non_blocking_loop(), s3f::s3fnet::NBTCPServerSession::non_blocking_loop(), s3f::s3fnet::OpenFlowSwitchSession::OutputControl(), s3f::s3fnet::OpenFlowSwitchSession::OutputPacket(), s3f::s3fnet::OpenFlowSwitchSession::OutputPort(), s3f::s3fnet::OpenFlowControllerSession::pop(), s3f::s3fnet::UDPMaster::pop(), s3f::s3fnet::OpenVZEventSession::pop(), s3f::s3fnet::OpenFlowSwitchSession::pop(), s3f::s3fnet::TCPMaster::pop(), s3f::s3fnet::IPSession::pop(), s3f::s3fnet::LearningController::process_recv_packet(), s3f::s3fnet::UDPMaster::push(), s3f::s3fnet::TCPMaster::push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::receive(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::LearningControllerSession::ReceiveFromSwitch(), s3f::s3fnet::OpenFlowSwitchSession::ReceivePacketOut(), s3f::s3fnet::OpenFlowSwitchSession::ReceivePortMod(), s3f::s3fnet::OpenFlowSwitchSession::ReceiveStatsRequest(), s3f::s3fnet::SocketMaster::recv(), s3f::s3fnet::NBSocketMaster::recv(), s3f::s3fnet::SocketMaster::recv1(), s3f::s3fnet::NBSocketMaster::recv1(), s3f::s3fnet::UDPServerSession::request_received(), s3f::s3fnet::TCPServerSession::request_received(), s3f::s3fnet::UDPClientSession::request_sent(), s3f::s3fnet::TCPClientSession::request_sent(), s3f::s3fnet::NBTCPClientSessionContinuation::resume(), s3f::s3fnet::NBTCPServerSessionContinuation::resume(), s3f::s3fnet::OpenFlowSwitchSession::RunThroughFlowTable(), s3f::s3fnet::UDPSession::send(), s3f::s3fnet::SocketMaster::send(), s3f::s3fnet::NBSocketMaster::send(), s3f::s3fnet::SocketMaster::send1(), s3f::s3fnet::NBSocketMaster::send1(), s3f::s3fnet::TCPSession::send_data(), s3f::s3fnet::OpenFlowSwitchSession::SendFlowExpired(), s3f::s3fnet::OpenFlowSwitchSession::SendOpenflowBuffer(), s3f::s3fnet::OpenFlowSwitchSession::SendPortStatus(), s3f::s3fnet::UDPClientSession::server_connected(), s3f::s3fnet::TCPClientSession::server_connected(), s3f::s3fnet::BTCPClientSession::server_connected(), s3f::s3fnet::UDPServerSession::session_closed(), s3f::s3fnet::UDPClientSession::session_closed(), s3f::s3fnet::TCPClientSession::session_closed(), s3f::s3fnet::TCPServerSession::session_closed(), s3f::s3fnet::BTCPClientSession::session_closed(), s3f::s3fnet::TCPMaster::setConnected(), s3f::s3fnet::OpenFlowSwitchSession::SetController(), s3f::s3fnet::TCPMaster::setIdle(), s3f::s3fnet::TCPMaster::setListening(), s3f::s3fnet::UDPSession::setSource(), s3f::s3fnet::TCPMaster::slow_timer_callback_body(), s3f::s3fnet::TCPSession::slowTimeoutHandling(), s3f::s3fnet::SocketMaster::socket(), s3f::s3fnet::NBSocketMaster::socket(), s3f::s3fnet::SocketMaster::SocketMaster(), s3f::s3fnet::UDPServerSession::start_on(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPServerSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), s3f::s3fnet::NBTCPClientSession::start_on(), s3f::s3fnet::BTCPClientSession::start_on(), s3f::s3fnet::NBTCPServerSession::start_on(), s3f::s3fnet::NBTCPServerSessionContinuation::success(), s3f::s3fnet::TCPClientSession::TCPClientSession(), s3f::s3fnet::TCPMaster::TCPMaster(), s3f::s3fnet::TCPServerSession::TCPServerSession(), s3f::s3fnet::TCPSession::TCPSession(), s3f::s3fnet::UDPClientSession::timeout(), s3f::s3fnet::TCPClientSession::timeout(), s3f::s3fnet::BTCPClientSession::timeout(), s3f::s3fnet::UDPClientSession::UDPClientSession(), s3f::s3fnet::UDPMaster::UDPMaster(), s3f::s3fnet::UDPServerSession::UDPServerSession(), s3f::s3fnet::UDPSession::UDPSession(), s3f::s3fnet::TCPSession::update_timeout(), s3f::s3fnet::IPSession::verify_local_ip_address(), and s3f::s3fnet::UDPSession::wake_app().
 {
   return dynamic_cast<Host*>(ingraph);
 }
virtual int s3f::s3fnet::ProtocolSession::getProtocolNumber () pure virtual
Each protocol session should have its unique protocol number.
The number will be used to retrieve the protocol session object using the protocol graph's sessionForNumber() method. The derived class should override this method and return the correct protocol number. The default is zero. The protocol number should be the same as the type of the corresponding protocol message, which the protocol uses to interact with the protocol session below it. A protocol session may use the protocol message's type to demultiplex the protocol messages at the destination and send the message to the correct protocol session.
Implemented in s3f::s3fnet::NBTCPServerSession, s3f::s3fnet::NBSocketMaster, s3f::s3fnet::IPSession, s3f::s3fnet::SocketMaster, s3f::s3fnet::BTCPClientSession, s3f::s3fnet::NBTCPClientSession, s3f::s3fnet::OpenFlowSwitchSession, s3f::s3fnet::TCPServerSession, s3f::s3fnet::TCPMaster, s3f::s3fnet::UDPClientSession, s3f::s3fnet::SimplePhy, s3f::s3fnet::UDPServerSession, s3f::s3fnet::TCPClientSession, s3f::s3fnet::SimpleMac, s3f::s3fnet::UDPMaster, s3f::s3fnet::OpenVZEventSession, s3f::s3fnet::OpenFlowControllerSession, and s3f::s3fnet::DummySession.
Referenced by s3f::s3fnet::RedQueue::enqueue(), and s3f::s3fnet::ProtocolGraph::insert_session().
Random::RNG* s3f::s3fnet::ProtocolSession::getRandom () inline
The method returns a pointer to the random number generator.
Definition at line 200 of file protocol_session.h.
References sess_rng.
Referenced by s3f::s3fnet::DroptailQueue::calibrate(), s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::DummySession::init(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), and s3f::s3fnet::NetworkInterface::receivePacket().
 { return sess_rng;}
ltime_t s3f::s3fnet::ProtocolSession::getNow ()
The method returns the current simulation time.
To be safe, please do NOT call this function after initialization and before wrapup phase. That is, it is unsafe to call this method in the constructor, destructor, config, init, and wrapup methods. The time service is carried out by the host's owner community. This method just directs the call to the community. It's given here for convenience.
Definition at line 123 of file protocol_session.cc.
References inHost(), and Entity::now().
Referenced by s3f::s3fnet::DroptailQueue::calibrate(), s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::TCPMaster::enableFastTimeout(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::TCPMaster::fast_timer_callback_body(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::TCPSession::now(), s3f::s3fnet::OpenVZEventSession::pop(), s3f::s3fnet::TCPMaster::slow_timer_callback_body(), s3f::s3fnet::SocketMaster::socket(), s3f::s3fnet::NBSocketMaster::socket(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), and s3f::s3fnet::BTCPClientSession::start_on().
 {
   return inHost()->now();
 }
char * s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator ()
For printing the current simulation time in a better readable format.
Definition at line 128 of file protocol_session.cc.
References s3f::s3fnet::Host::getNowWithThousandSeparator(), and inHost().
Referenced by s3f::s3fnet::UDPSession::abort(), s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::UDPSession::connect(), s3f::s3fnet::TCPMaster::createSession(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::UDPServerSession::data_sent(), s3f::s3fnet::TCPServerSession::data_sent(), s3f::s3fnet::UDPSession::disconnect(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::UDPSession::listen(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), s3f::s3fnet::DummySession::pop(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::OpenVZEventSession::pop(), s3f::s3fnet::UDPMaster::pop(), s3f::s3fnet::TCPMaster::pop(), s3f::s3fnet::IPSession::pop(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::UDPMaster::push(), s3f::s3fnet::SimplePhy::push(), s3f::s3fnet::TCPMaster::push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::receive(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::SimplePhy::receivePacket(), s3f::s3fnet::UDPServerSession::request_received(), s3f::s3fnet::TCPServerSession::request_received(), s3f::s3fnet::UDPClientSession::request_sent(), s3f::s3fnet::TCPClientSession::request_sent(), s3f::s3fnet::UDPSession::send(), s3f::s3fnet::TCPSession::send_data(), s3f::s3fnet::SimplePhy::sendPacket(), s3f::s3fnet::UDPClientSession::server_connected(), s3f::s3fnet::TCPClientSession::server_connected(), s3f::s3fnet::BTCPClientSession::server_connected(), s3f::s3fnet::UDPServerSession::session_closed(), s3f::s3fnet::UDPClientSession::session_closed(), s3f::s3fnet::TCPClientSession::session_closed(), s3f::s3fnet::TCPServerSession::session_closed(), s3f::s3fnet::BTCPClientSession::session_closed(), s3f::s3fnet::TCPMaster::setConnected(), s3f::s3fnet::TCPMaster::setIdle(), s3f::s3fnet::TCPMaster::setListening(), s3f::s3fnet::UDPSession::setSource(), s3f::s3fnet::TCPSession::slowTimeoutHandling(), s3f::s3fnet::UDPServerSession::start_on(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPServerSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), s3f::s3fnet::BTCPClientSession::start_on(), s3f::s3fnet::TCPSession::TCPSession(), s3f::s3fnet::UDPClientSession::timeout(), s3f::s3fnet::TCPClientSession::timeout(), s3f::s3fnet::BTCPClientSession::timeout(), s3f::s3fnet::UDPSession::UDPSession(), s3f::s3fnet::TCPSession::update_timeout(), and s3f::s3fnet::UDPSession::wake_app().
 {
         return inHost()->getNowWithThousandSeparator();
 }
int s3f::s3fnet::ProtocolSession::configured () inline
This method returns true if the protocol session has been configured.
This method is used to make sure we configure the protocol session before initializing it.
Definition at line 221 of file protocol_session.h.
References PSESS_CONFIGURED, and stage.
Referenced by config(), and init().
 { return stage >= PSESS_CONFIGURED; }
int s3f::s3fnet::ProtocolSession::initialized () inline
This method returns true if the protocol session has been initialized.
This can be used to sequence calls to the init method of protocol sessions. For example, if protocol session A requires protocol session B to be initialized before A can be initialized, A's init method can call B's init method as long as B's initialized() returns true. The system does not enforce any ordering in its calls the init methods of all protocol sessions declared in the dml configuration.
Definition at line 233 of file protocol_session.h.
References PSESS_INITIALIZED, and stage.
Referenced by init(), and wrapup().
 { return stage >= PSESS_INITIALIZED; }
int s3f::s3fnet::ProtocolSession::wrapped_up () inline
This method returns true if the protocol session has been wrapped up.
This can be used to sequence calls to the wrapup method of protocol sessions. For example, if protocol session A requires protocol session B to be wrapped up before A can be wrapped up, A's wrapup method can call B's wrapup method as long as B's wrapped_up() returns true. The system does not enforce any ordering in its calls the wrapup methods of all protocol sessions declared in the dml configuration.
Definition at line 245 of file protocol_session.h.
References PSESS_WRAPPED_UP, and stage.
Referenced by wrapup().
 { return stage >= PSESS_WRAPPED_UP; }
virtual const char* s3f::s3fnet::ProtocolSession::psesstype () inline virtual
Reimplemented in s3f::s3fnet::NBSocketMaster, and s3f::s3fnet::SocketMaster.
Definition at line 247 of file protocol_session.h.
 { return "GENERIC"; } // DEBUG
virtual int s3f::s3fnet::ProtocolSession::instantiation_type () inline protected virtual
This method controls how protocol instances can coexist with one another.
It returns one of the following:
PROT_UNIQUE_INSTANCE (default): allows only one instance for each type of protocol per protocol stack;
PROT_MULTIPLE_INSTANCES: allows multiple instances of the same implementation for each type of protocol per protocol stack;
PROT_MULTIPLE_IMPLEMENTATIONS: allows multiple instances from different implementations of the same protocol to exist on the protocol stack.
Reimplemented in s3f::s3fnet::BTCPClientSession, and s3f::s3fnet::TCPClientSession.
Definition at line 269 of file protocol_session.h.
References PROT_UNIQUE_INSTANCE.
Referenced by s3f::s3fnet::ProtocolGraph::insert_session().
 { return PROT_UNIQUE_INSTANCE; }
int s3f::s3fnet::ProtocolSession::push (Activation msg, ProtocolSession * hi_sess, void * extinfo = 0, size_t extinfo_size = 0) private virtual
The method is called when a message is pushed down to this protocol session from the protocol session above.
The protocol session above calling this method will have a reference to itself in the second argument. Extra information can be provided as the third argument. The protocol message is given as the first argument. Once this method is called, the message belongs to this session unless it's passed along, for example, further down the protocol stack. That is, if the message is to be dropped for any reason, this session must be responsible to reclaim the message. Message exchange is implemented as method calls for efficiency reasons. It consumes no simulation time (even without context switch) unless users code it explicitly. The extinfo parameter provides a means to pass any auxiliary information that doesn't belong in the protocol message with the call. extinfo_size must contain the size in bytes of the structure passed as extinfo. The extinfo data MUST NOT contain any pointer structures, since it will only be copied as a chunk of memory, based on the extinfo_size. The return value semantics have changed since early versions. Normal return is zero. Non-zero means that the method has blocked and the caller MUST return immediately. The method will be called again with a re-entry flag value after the time delay.
Reimplemented in s3f::s3fnet::NBSocketMaster, s3f::s3fnet::SocketMaster, s3f::s3fnet::IPSession, s3f::s3fnet::NBTCPServerSession, s3f::s3fnet::BTCPClientSession, s3f::s3fnet::TCPClientSession, s3f::s3fnet::TCPServerSession, s3f::s3fnet::TCPMaster, s3f::s3fnet::NBTCPClientSession, s3f::s3fnet::UDPClientSession, s3f::s3fnet::UDPServerSession, s3f::s3fnet::SimplePhy, s3f::s3fnet::OpenVZEventSession, s3f::s3fnet::UDPMaster, s3f::s3fnet::SimpleMac, and s3f::s3fnet::DummySession.
Definition at line 82 of file protocol_session.cc.
References s3f::s3fnet::error_quit().
Referenced by pushdown().
 {
   error_quit("ERROR: called ProtocolSession::push(), that should be overridden.\n");
 }
int s3f::s3fnet::ProtocolSession::pop (Activation msg, ProtocolSession * lo_sess, void * extinfo = 0, size_t extinfo_size = 0) private virtual
The method is called when a message is popped up to this protocol session from the protocol session below.
The protocol session below calling this method will have a reference to itself in the third argument. Extra information can be provided as the third argument. The protocol message is given as the first argument, and the second parameter is the packet that holds the chain of all the ProtocolMessages. There may be scenarios that the packet does not exist, e.g. the host sends some message to itself. In that situation, the second parameter should be NULL and the first parameter MUST be the head of the chain of ProtocolMessages. The extinfo parameter provides a means to pass any auxiliary information that doesn't belong in the protocol message with the call. extinfo_size must contain the size in bytes of the structure passed as extinfo. The extinfo data MUST NOT contain any pointer structures, since it will only be copied as a chunk of memory, based on the extinfo_size. The return value semantics have changed since early versions. Normal return is zero. Non-zero means that the method has blocked and the caller MUST return immediately. The method will be called again with a reentry flag value after the time delay.
The ownership of the the packet (including all messages) is passed alone when pop is called. It means that the callee (upper layer) is responsible to call the erase() of the packet if it decides to release all the memory. This also brings the convenience that the upper layer can handle the whole packet freely. There is NO exception for this rule.
By default the ownership of the extinfo is kept by the caller. It means that the caller(lower layer) is responsible to release the memory used by extInfo if needed, However, there CAN be exceptions of this rule if the caller and the callee has their own agreement and have explicitly noted so.
Reimplemented in s3f::s3fnet::NBSocketMaster, s3f::s3fnet::SocketMaster, s3f::s3fnet::IPSession, s3f::s3fnet::NBTCPServerSession, s3f::s3fnet::BTCPClientSession, s3f::s3fnet::TCPClientSession, s3f::s3fnet::TCPServerSession, s3f::s3fnet::NBTCPClientSession, s3f::s3fnet::TCPMaster, s3f::s3fnet::UDPClientSession, s3f::s3fnet::UDPServerSession, s3f::s3fnet::OpenFlowSwitchSession, s3f::s3fnet::OpenVZEventSession, s3f::s3fnet::UDPMaster, s3f::s3fnet::SimpleMac, s3f::s3fnet::OpenFlowControllerSession, and s3f::s3fnet::DummySession.
Definition at line 87 of file protocol_session.cc.
References s3f::s3fnet::error_quit().
Referenced by popup().
 {
   error_quit("ERROR: called ProtocolSession::pop(), that should be overridden.\n");
 }
Member Data Documentation
char* s3f::s3fnet::ProtocolSession::name
Symbolic name of the protocol this session implements.
The name of the protocol is derived from the DML 'name' attribute. It must not be NULL once the protocol session is configured.
Definition at line 63 of file protocol_session.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), config(), s3f::s3fnet::SimpleMac::init(), s3f::s3fnet::UDPMaster::init(), s3f::s3fnet::SimplePhy::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::SocketMaster::init(), s3f::s3fnet::IPSession::init(), s3f::s3fnet::NBSocketMaster::init(), init(), s3f::s3fnet::ProtocolGraph::insert_session(), wrapup(), and ~ProtocolSession().
float s3f::s3fnet::ProtocolSession::version
Version number of this protocol implemenntation, represented as a floating point number (e.g., 1.23).
Definition at line 69 of file protocol_session.h.
char* s3f::s3fnet::ProtocolSession::use
Name of the protocol class from which this protocol session is instantiated.
The protocol class must be registered with the Protocols class so that we will be able to instantiate an object from the class. (C++ does not support self-reflection). The class name must not be NULL once the protocol session is configured.
Definition at line 79 of file protocol_session.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), config(), s3f::s3fnet::ProtocolGraph::insert_session(), and ~ProtocolSession().
ProtocolGraph* s3f::s3fnet::ProtocolSession::ingraph protected
Points to the protocol graph.
Definition at line 335 of file protocol_session.h.
Referenced by s3f::s3fnet::NicProtocolSession::getNetworkInterface(), inGraph(), and inHost().
Random::RNG* s3f::s3fnet::ProtocolSession::sess_rng protected
Pointer to a random number generator.
Definition at line 338 of file protocol_session.h.
Referenced by getRandom(), and init().
int s3f::s3fnet::ProtocolSession::stage protected
This variable indicates the current stage of this protocol session.
Each protocol session will go through four staged: PSESS_CREATED, PSESS_CONFIGURED, PSESS_INITIALIZED, and then PSESS_WRAPPED_UP.
Definition at line 346 of file protocol_session.h.
Referenced by s3f::s3fnet::Host::config(), config(), configured(), init(), initialized(), wrapped_up(), and wrapup().
The documentation for this class was generated from the following files:
protocol_session.h
protocol_session.cc