S3F: s3f::s3fnet::SocketMaster Class Reference
s3f::s3fnet::SocketMaster Class Reference
The socket master protocol session.
#include <socket_master.h>
Public Types
enum InstantiationType { PROT_UNIQUE_INSTANCE = 0x00, PROT_MULTIPLE_INSTANCES = 0x01, PROT_MULTIPLE_IMPLEMENTATIONS = 0x02 }
Multiple protocol session instantiation type.
enum ExecutionStage { PSESS_CREATED = 0, PSESS_CONFIGURED = 1, PSESS_INITIALIZED = 2, PSESS_WRAPPED_UP = 3 }
A normal protocol session must go though the following stages.
Public Member Functions
SocketMaster (ProtocolGraph *graph)
The constructor.
virtual ~SocketMaster ()
The destructor.
virtual int getProtocolNumber ()
Return the protocol number.
virtual void init ()
Initialize the socket master.
virtual int control (int ctrltyp, void *ctrlmsg, ProtocolSession *sess)
Control messages are passed through this function.
virtual const char * psesstype ()
int socket ()
Returns a new socket id.
bool bind (int sock, IPADDR source_ip, uint16 source_port, char *protocol, uint32 options=0)
Bind the socket Binds the socket with the source ip address, port, and the protocol that maintains the socket.
bool listen (int sock, uint32 queuesize)
Listens for incoming connections This function set up the socket so that it can queue up to 'queuesize' number of foreign connection attempts.
bool connected (int sock, IPADDR *peer_ip=NULL, uint16 *peer_port=NULL)
Indicates if the socket is connected.
bool eof (int sock)
Indicates end of connection.
void abort (int sock)
Reset the connections and invalidate the socket.
void connect (int sock, IPADDR ip, uint16 port, BSocketContinuation *caller)
Connect to remote host This function establishes a connection to the given destination ip and port.
void accept (int sock, bool make_new_socket, BSocketContinuation *caller, BSocketContinuation *first_conn_notify=0)
Checks for arrival of a connection request.
void send (int sock, uint32 length, byte *msg, BSocketContinuation *caller)
Send data to remote host Send a message of the given length and return the number of bytes that have been sent successfully.
void recv (int sock, uint32 bufsiz, byte *buffer, BSocketContinuation *caller)
Receive data from remote host Receive a message of the given length.
void close (int sock, BSocketContinuation *caller)
Terminate the connection Close the connection and invalidate the socket.
virtual void config (s3f::dml::Configuration *cfg)
The config method is used to configure the protocol session from DML description.
virtual void wrapup ()
The method is used to wrap up the protocol session.
int pushdown (Activation msg, ProtocolSession *hi_sess, void *extinfo=0, size_t extinfo_size=0)
The original push method is divided into pushdown() and push().
int popup (Activation msg, ProtocolSession *lo_sess, void *extinfo=0, size_t extinfo_size=0)
The original pop method is divided into popup() and pop().
ProtocolGraph * inGraph ()
The method returns the protocol graph in which this protocol session resides.
virtual Host * inHost ()
Return a pointer to the host owning this protocol session.
Random::RNG * getRandom ()
The method returns a pointer to the random number generator.
ltime_t getNow ()
The method returns the current simulation time.
char * getNowWithThousandSeparator ()
For printing the current simulation time in a better readable format.
int configured ()
This method returns true if the protocol session has been configured.
int initialized ()
This method returns true if the protocol session has been initialized.
int wrapped_up ()
This method returns true if the protocol session has been wrapped up.
Public Attributes
char * name
Symbolic name of the protocol this session implements.
float version
Version number of this protocol implemenntation, represented as a floating point number (e.g., 1.23).
char * use
Name of the protocol class from which this protocol session is instantiated.
Protected Member Functions
typedef S3FNET_MAP (int, Socket *) SOCK_MAP
typedef S3FNET_SET (int) SOCK_SET
virtual int instantiation_type ()
This method controls how protocol instances can coexist with one another.
Protected Attributes
int new_sockid
The next available socket id.
SOCK_MAP bound_socks
A map from a socket id to a bound socket.
SOCK_SET unbound_socks
A set of unbound socket ids.
ProtocolGraph * ingraph
Points to the protocol graph.
Random::RNG * sess_rng
Pointer to a random number generator.
int stage
This variable indicates the current stage of this protocol session.
Private Member Functions
void connect1 (int sock, BSocketContinuation *caller)
continuations of the method connect1() in the standard socket interface
void accept1a (int sock, BSocketContinuation *caller)
continuations of the method accept1a() in the standard socket interface
void accept1b (int sock, BSocketContinuation *caller)
continuations of the method accept1b() in the standard socket interface
void accept2a (int sock, BSocketContinuation *caller)
continuations of the method accept2a() in the standard socket interface
void accept2b (int sock, BSocketContinuation *caller)
continuations of the method accept2b() in the standard socket interface
void send1 (int sock, BSocketContinuation *caller)
continuations of the method send1() in the standard socket interface
void recv1 (int sock, BSocketContinuation *caller)
continuations of the method recv1() in the standard socket interface
void close1 (int sock, BSocketContinuation *caller)
continuations of the method close1() in the standard socket interface
void block_till (int sockid, uint32 mask, bool anysignal, BSocketContinuation *caller)
Checks if we need to block and prepares to do so.
virtual int push (Activation msg, ProtocolSession *hi_sess, void *extinfo=0, size_t extinfo_size=0)
Push to lower protocol layer.
virtual int pop (Activation msg, ProtocolSession *lo_sess, void *extinfo=0, size_t extinfo_size=0)
Pop to higher protocol layer.
Detailed Description
The socket master protocol session.
The socket master protocol session is used to manage sockets; it provides an interface between socket protocol sessions (such as tcp and udp socket sessions) and the underlying protocols. This implementation consists of non-blocking calls in the socket interface.
Definition at line 77 of file socket_master.h.
Member Enumeration Documentation
enum s3f::s3fnet::ProtocolSession::InstantiationType inherited
Multiple protocol session instantiation type.
Enumerator
PROT_UNIQUE_INSTANCE
PROT_MULTIPLE_INSTANCES
PROT_MULTIPLE_IMPLEMENTATIONS
Definition at line 44 of file protocol_session.h.
{
     PROT_UNIQUE_INSTANCE                = 0x00,
     PROT_MULTIPLE_INSTANCES             = 0x01,
     PROT_MULTIPLE_IMPLEMENTATIONS       = 0x02
   };
enum s3f::s3fnet::ProtocolSession::ExecutionStage inherited
A normal protocol session must go though the following stages.
Enumerator
PSESS_CREATED
this protocol session has just been created
PSESS_CONFIGURED
the config method of this protocol session has been called
PSESS_INITIALIZED
the init method of this protocol session has been called
PSESS_WRAPPED_UP
Definition at line 51 of file protocol_session.h.
                       {
     PSESS_CREATED       = 0,
     PSESS_CONFIGURED    = 1,
     PSESS_INITIALIZED   = 2,
     PSESS_WRAPPED_UP    = 3
   };
Constructor & Destructor Documentation
s3f::s3fnet::SocketMaster::SocketMaster (ProtocolGraph * graph)
The constructor.
Definition at line 25 of file socket_master.cc.
References s3f::s3fnet::ProtocolSession::inHost(), and SOCK_DUMP.
                                                : ProtocolSession(graph), new_sockid(0)
 {
   SOCK_DUMP(printf("[host=\"%s\"] new socket master session.\n", inHost()->nhi.toString()));
 }
s3f::s3fnet::SocketMaster::~SocketMaster () virtual
The destructor.
Definition at line 30 of file socket_master.cc.
References bound_socks, and S3FNET_MAP().
 {
   for(S3FNET_MAP(int, Socket*)::iterator iter = bound_socks.begin(); iter != bound_socks.end(); iter++)
   {
     // the sessions are reclaimed by the tcp/udp master; sever the
     // link here prevents the destructor of Socket class to double
     // reclaim the sessions.
     (*iter).second->session = 0;
     (*iter).second->release();
   }
 }
Member Function Documentation
virtual int s3f::s3fnet::SocketMaster::getProtocolNumber () inline virtual
Return the protocol number.
Returns the protocol number specifying the relationship between this protocol and the other protocols defined in the same protocol stack.
Returns
protocol number for Socket protocol
Implements s3f::s3fnet::ProtocolSession.
Definition at line 93 of file socket_master.h.
References s3f::s3fnet::S3FNET_PROTOCOL_TYPE_SOCKET.
 { return S3FNET_PROTOCOL_TYPE_SOCKET; }
void s3f::s3fnet::SocketMaster::init () virtual
Initialize the socket master.
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 42 of file socket_master.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::ProtocolSession::name, SOCK_DUMP, and SOCKET_PROTOCOL_NAME.
 {
   SOCK_DUMP(printf("[host=\"%s\"] init.\n", inHost()->nhi.toString()));
   ProtocolSession::init();
   if(strcasecmp(name, SOCKET_PROTOCOL_NAME))
     error_quit("ERROR: SocketMaster::init(), unmatched protocol name: \"%s\", "
                "expecting \"SOCKET\".\n", name);
 }
int s3f::s3fnet::SocketMaster::control (int ctrltyp, void * ctrlmsg, ProtocolSession * sess) virtual
Control messages are passed through this function.
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 52 of file socket_master.cc.
References bound_socks, s3f::s3fnet::Socket::bytes_completed, s3f::s3fnet::Socket::continuation, s3f::s3fnet::ProtocolSession::control(), s3f::s3fnet::SocketSignal::DATA_AVAILABLE, s3f::s3fnet::error_retn(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::Socket::mask, s3f::s3fnet::SocketSignal::nbytes, Entity::now(), s3f::s3fnet::SocketSignal::OK_TO_SEND, s3f::s3fnet::SocketSession::reinit(), s3f::s3fnet::Socket::reinit(), S3FNET_MAP(), s3f::s3fnet::Socket::session, s3f::s3fnet::SocketSignal::signal, s3f::s3fnet::SOCK_CTRL_CLEAR_SIGNAL, s3f::s3fnet::SOCK_CTRL_DETACH_SESSION, s3f::s3fnet::SOCK_CTRL_GET_APP_SESSION, s3f::s3fnet::SOCK_CTRL_REINIT, s3f::s3fnet::SOCK_CTRL_SET_SIGNAL, SOCK_DUMP, s3f::s3fnet::SocketSignal::sockid, and s3f::s3fnet::Socket::state.
 {
   SocketSignal* socksig = (SocketSignal*)ctrlmsg;
   Socket* mysocket = 0;
   if(ctrltyp == SOCK_CTRL_SET_SIGNAL ||
      ctrltyp == SOCK_CTRL_CLEAR_SIGNAL ||
      ctrltyp == SOCK_CTRL_DETACH_SESSION ||
      ctrltyp == SOCK_CTRL_REINIT ||
      ctrltyp == SOCK_CTRL_GET_APP_SESSION)
   {
     assert(socksig);
     S3FNET_MAP(int, Socket*)::iterator iter = bound_socks.find(socksig->sockid);
     if(iter != bound_socks.end()) mysocket = (*iter).second;
     if(!mysocket)
     {
       error_retn("WARNING: SocketMaster::control(), unknown socket: %d (type %d)\n", socksig->sockid, ctrltyp);
       return 1;
     }
   }
   if(ctrltyp == SOCK_CTRL_SET_SIGNAL)
   {
     SOCK_DUMP(printf("[host=\"%s\"] %ld: control(), SOCK_CTRL_SET_SIGNAL (before): socket=%d "
                      "(mask=%08x, state=%08x), signal=%08x, nbytes=%u.\n",
                      inHost()->nhi.toString(), inHost()->now(),
                      socksig->sockid, mysocket->mask, mysocket->state,
                      socksig->signal, socksig->nbytes));
     if((socksig->signal & SocketSignal::DATA_AVAILABLE) ||
        (socksig->signal & SocketSignal::OK_TO_SEND))
     {
       mysocket->bytes_completed += socksig->nbytes;
     }
     // if there's something new that the state doesn't include
     if(~mysocket->state & socksig->signal)
     {
       mysocket->state |= socksig->signal; // include it
       // if the newly added is what we're waiting for
       if(socksig->signal & mysocket->mask)
       {
           // clear up the data available flag for next receive
         if(mysocket->state & SocketSignal::DATA_AVAILABLE)
           mysocket->state &= ~SocketSignal::DATA_AVAILABLE;
         SOCK_DUMP(printf("unblocking: signal=%08x, state=%08x\n", socksig->signal, mysocket->state));
         assert(mysocket->continuation && ((BSocketContinuation*)mysocket->continuation)->next_stage);
         void (SocketMaster::*fct)(int, BSocketContinuation*) = ((BSocketContinuation*)mysocket->continuation)->next_stage;
         ((BSocketContinuation*)mysocket->continuation)->next_stage = 0;
         (this->*fct)(socksig->sockid, ((BSocketContinuation*)mysocket->continuation));
       }
     }
     SOCK_DUMP(printf("[host=\"%s\"] %ld: control(), SOCK_CTRL_SET_SIGNAL (after): socket=%d "
                      "(mask=%08x, state=%08x), signal=%08x, nbytes=%u.\n",
                      inHost()->nhi.toString(), inHost()->now(),
                      socksig->sockid, mysocket->mask, mysocket->state,
                      socksig->signal, socksig->nbytes));
     return 0;
   }
   else if(ctrltyp == SOCK_CTRL_CLEAR_SIGNAL)
   {
     SOCK_DUMP(printf("[host=\"%s\"] %ld: control(), SOCK_CTRL_CLEAR_SIGNAL (before): socket=%d "
                      "(mask=%08x, state=%08x), signal=%08x.\n",
                      inHost()->nhi.toString(), inHost()->now(),
                      socksig->sockid, mysocket->mask, mysocket->state, socksig->signal));
     mysocket->state &= ~socksig->signal;
     SOCK_DUMP(printf("[host=\"%s\"] %ld: control(), SOCK_CTRL_CLEAR_SIGNAL (after): socket=%d "
                      "(mask=%08x, state=%08x), signal=%08x.\n",
                      inHost()->nhi.toString(), inHost()->now(),
                      socksig->sockid, mysocket->mask, mysocket->state, socksig->signal));
     return 0;
   }
   else if(ctrltyp == SOCK_CTRL_DETACH_SESSION)
   {
     /*SOCK_DUMP(printf("[host=\"%s\"] %ld: control(), SOCK_CTRL_DETACH_SESSION: socket=%d.\n",
       inHost()->nhi.toString(), inHost()->now(), socksig->sockid));*/
     mysocket->session = 0;
     return 0;
   }
   else if(ctrltyp == SOCK_CTRL_REINIT)
   {
     /*SOCK_DUMP(printf("[host=\"%s\"] %ld: control(), SOCK_CTRL_REINIT: socket=%d.\n",
       inHost()->nhi.toString(), inHost()->now(), socksig->sockid));*/
     mysocket->session->reinit();
     mysocket->reinit();
     return 0;
   }
   else if(ctrltyp == SOCK_CTRL_GET_APP_SESSION)
   {
     /*SOCK_DUMP(printf("[host=\"%s\"] %ld: control(), SOCK_CTRL_GET_APP_SESSION: socket=%d.\n",
       inHost()->nhi.toString(), inHost()->now(), socksig->sockid));*/
     /*...*/
     return 0;
   }
   else return ProtocolSession::control(ctrltyp, ctrlmsg, sess);
 }
virtual const char* s3f::s3fnet::SocketMaster::psesstype () inline virtual
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 101 of file socket_master.h.
 { return "BLOCKING_SOCKET"; } // DEBUG
int s3f::s3fnet::SocketMaster::socket ()
Returns a new socket id.
Returns
socket id, -1 means error
Definition at line 162 of file socket_master.cc.
References bound_socks, s3f::s3fnet::ProtocolSession::getNow(), s3f::s3fnet::ProtocolSession::inHost(), new_sockid, SOCK_DUMP, and unbound_socks.
Referenced by accept2a(), s3f::s3fnet::UDPServerSession::request_received(), s3f::s3fnet::UDPServerSession::start_on(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPServerSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), and s3f::s3fnet::BTCPClientSession::start_on().
 {
   bool overlap = false;
   do
   { // go linearly till we find a socket id not used
     new_sockid++;
     if(new_sockid < 0)
     {
       new_sockid = 1; // start from one if wrapped around
       if(overlap) return -1;
       else overlap = true;
     }
   } while(bound_socks.find(new_sockid) != bound_socks.end() ||
           unbound_socks.find(new_sockid) != unbound_socks.end());
   unbound_socks.insert(new_sockid);
   SOCK_DUMP(printf("[host=\"%s\"] %ld: socket(), new socket %d.\n",
                    inHost()->nhi.toString(), getNow(), new_sockid));
   return new_sockid;
 }
bool s3f::s3fnet::SocketMaster::bind (int sock, IPADDR source_ip, uint16 source_port, char * protocol, uint32 options = 0)
Bind the socket Binds the socket with the source ip address, port, and the protocol that maintains the socket.
Parameters
sock the socket id
source_ip the source ip address
source_port the source port
protocol the protocol to be used over the socket (ie to choose TCP or UDP)
options socket option flags
Returns
true if socket is bound successfully, false otherwise
Definition at line 183 of file socket_master.cc.
References bound_socks, s3f::s3fnet::SessionMaster::createSession(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::IPPrefix::ip2txt(), Entity::now(), s3f::s3fnet::Socket::release(), S3FNET_MAKE_PAIR, S3FNET_MAP(), S3FNET_SET(), s3f::s3fnet::Socket::session, s3f::s3fnet::ProtocolGraph::sessionForName(), s3f::s3fnet::SocketSession::setSource(), SOCK_DUMP, and unbound_socks.
Referenced by s3f::s3fnet::UDPServerSession::request_received(), s3f::s3fnet::UDPServerSession::start_on(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPServerSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), and s3f::s3fnet::BTCPClientSession::start_on().
 {
   SOCK_DUMP(printf("[host=\"%s\"] %ld: bind(): socket=%d, src_ip=\"%s\", src_port=%d, "
                    "prot=\"%s\", opt=%u.\n", inHost()->nhi.toString(),
                    inHost()->now(), sock, IPPrefix::ip2txt(src_ip), src_port,
                    ((protocol == 0) ? "<NULL>" : protocol), options));
   SessionMaster* proto = (SessionMaster*)inHost()->sessionForName(protocol);
   if(!proto)
   {
     SOCK_DUMP(printf("bind(), protocol %s not found on host \"%s\".\n",
                      ((protocol == 0) ? "<NULL>" : protocol), inHost()->nhi.toString()));
     return false;
   }
   Socket* mysocket = 0;
   S3FNET_MAP(int, Socket*)::iterator iter = bound_socks.find(sock);
   if(iter != bound_socks.end()) return false;
   S3FNET_SET(int)::iterator setiter = unbound_socks.find(sock);
   if(setiter != unbound_socks.end())
   {
     // create a new socket
     mysocket = new Socket();
     assert(mysocket);
     // get new session
     mysocket->session = proto->createSession(sock);
     assert(mysocket->session);
     // set the src in session
     if(!mysocket->session->setSource(src_ip, src_port))
     {
       mysocket->release();
       return false;
     }
     // move from unbound to bound socket list
     unbound_socks.erase(setiter);
     bound_socks.insert(S3FNET_MAKE_PAIR(sock, mysocket));
     return true;
   }
   else return false;
 }
bool s3f::s3fnet::SocketMaster::listen (int sock, uint32 queuesize)
Listens for incoming connections This function set up the socket so that it can queue up to 'queuesize' number of foreign connection attempts.
The function returns true on success. This function is actually not implemented; it's a placeholder.
Parameters
sock the socket id
queuesize the number of connections to queue
Returns
true on success, false otherwise
Definition at line 228 of file socket_master.cc.
References bound_socks, s3f::s3fnet::SocketSession::connected(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::SocketSession::listen(), Entity::now(), S3FNET_MAP(), s3f::s3fnet::Socket::session, and SOCK_DUMP.
Referenced by s3f::s3fnet::UDPServerSession::start_on().
 {
   SOCK_DUMP(printf("[host=\"%s\"] %ld: listen(): socket=%d, queuesize=%u.\n",
                    inHost()->nhi.toString(), inHost()->now(), sock, queuesize));
   Socket* mysocket = 0;
   S3FNET_MAP(int, Socket*)::iterator iter = bound_socks.find(sock);
   if(iter != bound_socks.end()) mysocket = (*iter).second;
   if(mysocket && mysocket->session && !mysocket->session->connected())
     return mysocket->session->listen();
   else return false;
 }
bool s3f::s3fnet::SocketMaster::connected (int sock, IPADDR * peer_ip = NULL, uint16 * peer_port = NULL)
Indicates if the socket is connected.
A side effect of this function is that the destination ip address and port number are also returned if the parameters provided are not NULL.
Parameters
sock the socket id
peer_ip address of ipv4 structure to write destination ip into on success
peer_port address of port structure to write destination port into on success
Returns
true if the socket is connected, false otherwise
Definition at line 240 of file socket_master.cc.
References bound_socks, s3f::s3fnet::SocketSession::connected(), s3f::s3fnet::SessionID::dst_ip, s3f::s3fnet::SessionID::dst_port, s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::IPPrefix::ip2txt(), Entity::now(), S3FNET_MAP(), s3f::s3fnet::Socket::session, and SOCK_DUMP.
Referenced by s3f::s3fnet::UDPServerSession::request_received().
 {
   SOCK_DUMP(printf("[host=\"%s\"] %ld: connected(): socket=%d.\n",
                    inHost()->nhi.toString(), inHost()->now(), sock));
   Socket* mysocket = 0;
   S3FNET_MAP(int, Socket*)::iterator iter = bound_socks.find(sock);
   if(iter != bound_socks.end()) mysocket = (*iter).second;
   if(mysocket)
   {
     if(mysocket->session && mysocket->session->connected())
     {
       if(ip != 0) *ip = mysocket->session->dst_ip;
       if(port != 0) *port = mysocket->session->dst_port;
       SOCK_DUMP(printf("destination ip=\"%s\", port=%d.\n",
                        IPPrefix::ip2txt(mysocket->session->dst_ip),
                        mysocket->session->dst_port));
       return true;
     }
   }
   return false;
 }
bool s3f::s3fnet::SocketMaster::eof (int sock)
Indicates end of connection.
Returns true if the socket has no more data and the peer has closed the connection.
Parameters
sock the socket id
Returns
true if socket has no more data and connection is closed, false otherwise
Definition at line 262 of file socket_master.cc.
References bound_socks, s3f::s3fnet::Socket::DATA_AVAILABLE, s3f::s3fnet::ProtocolSession::inHost(), Entity::now(), S3FNET_MAP(), SOCK_DUMP, s3f::s3fnet::Socket::SOCK_EOF, and s3f::s3fnet::Socket::state.
 {
   SOCK_DUMP(printf("[host=\"%s\"] %ld: eof(): socket=%d.\n",
                    inHost()->nhi.toString(), inHost()->now(), sock));
   Socket* mysocket = 0;
   S3FNET_MAP(int, Socket*)::iterator iter = bound_socks.find(sock);
   if(iter != bound_socks.end()) mysocket = (*iter).second;
   if(mysocket)
   {
     if((mysocket->state & Socket::SOCK_EOF) &&
        !(mysocket->state & Socket::DATA_AVAILABLE))
     {
       SOCK_DUMP(printf("true.\n"));
       return true;
     }
     return false;
   }
   SOCK_DUMP(printf("true.\n"));
   return true; // if we can't find the open socket, it's true
 }
void s3f::s3fnet::SocketMaster::abort (int sock)
Reset the connections and invalidate the socket.
Parameters
sock the socket id
Definition at line 283 of file socket_master.cc.
References s3f::s3fnet::SocketSession::abort(), bound_socks, s3f::s3fnet::Socket::die_slowly(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::Socket::is_active(), Entity::now(), s3f::s3fnet::Socket::release(), S3FNET_MAP(), s3f::s3fnet::Socket::session, and SOCK_DUMP.
Referenced by s3f::s3fnet::UDPClientSessionContinuation::failure(), s3f::s3fnet::TCPClientSessionContinuation::failure(), s3f::s3fnet::BTCPClientSessionContinuation::failure(), s3f::s3fnet::UDPClientSession::timeout(), s3f::s3fnet::TCPClientSession::timeout(), and s3f::s3fnet::BTCPClientSession::timeout().
 {
   SOCK_DUMP(printf("[host=\"%s\"] %ld: abort(): socket=%d.\n",
                    inHost()->nhi.toString(), inHost()->now(), sock));
   Socket* mysocket = 0;
   S3FNET_MAP(int, Socket*)::iterator iter = bound_socks.find(sock);
   if(iter != bound_socks.end()) mysocket = (*iter).second;
   if(mysocket)
   {
     if(mysocket->session) mysocket->session->abort();
     if(mysocket->is_active()) mysocket->die_slowly();
     else
     {
       // the destructor will call release method---which will detach
       // the socket session from the socket, remove the socket session
       // from the session master, and then reclaim the socket
       // session---before the socket is reclaimed
       mysocket->release();
       bound_socks.erase(sock);
     }
   }
 }
void s3f::s3fnet::SocketMaster::connect (int sock, IPADDR ip, uint16 port, BSocketContinuation * caller)
Connect to remote host This function establishes a connection to the given destination ip and port.
The success method of the continuation will be called on success.
Parameters
sock the socket id
ip the destination ip address
port the destination port
caller the blocking socket continuation
Definition at line 333 of file socket_master.cc.
References block_till(), bound_socks, s3f::s3fnet::Socket::CONN_RESET, s3f::s3fnet::SocketSession::connect(), connect1(), s3f::s3fnet::Socket::CONNECT_ACTIVE, s3f::s3fnet::SocketSession::connected(), s3f::s3fnet::BSocketContinuation::failure(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::IPPrefix::ip2txt(), s3f::s3fnet::BSocketContinuation::next_stage, Entity::now(), s3f::s3fnet::Socket::OK_TO_SEND, S3FNET_MAP(), s3f::s3fnet::Socket::session, SOCK_DUMP, and s3f::s3fnet::Socket::state.
Referenced by s3f::s3fnet::UDPServerSession::request_received(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), and s3f::s3fnet::BTCPClientSession::start_on().
 {
   assert(caller);
   Socket* mysocket = 0;
   S3FNET_MAP(int, Socket*)::iterator iter = bound_socks.find(sock);
   if(iter != bound_socks.end()) mysocket = (*iter).second;
   if(!mysocket || // if the socket is not bound
      !mysocket->session || // this shouldn't happen
      mysocket->session->connected() ||  // if the socket has been connected
      (mysocket->state & Socket::CONNECT_ACTIVE)) // if the socket is connecting
   {
     caller->failure();
     return;
   }
   SOCK_DUMP(printf("[host=\"%s\"] %ld: connect(): socket=%d (state=%08x), ip=\"%s\", port=%d.\n",
                    inHost()->nhi.toString(), inHost()->now(), sock, mysocket->state, IPPrefix::ip2txt(ip), port));
   // initiate the connection
   if(!mysocket->session->connect(ip, port))
   {
     caller->failure();
     return;
   }
   // set the connect active flag up
   mysocket->state |= Socket::CONNECT_ACTIVE;
   caller->next_stage = &SocketMaster::connect1;
   block_till(sock, Socket::OK_TO_SEND|Socket::CONN_RESET, false, caller);
 }
void s3f::s3fnet::SocketMaster::accept (int sock, bool make_new_socket, BSocketContinuation * caller, BSocketContinuation * first_conn_notify = 0)
Checks for arrival of a connection request.
If successful, the success function of the continuation will be called and the return value will be set as the new socket number corresponding to the new connection just established. The failure function of the continuation will be called if an error occurred. If make_new_socket is false, the new connection will use the same socket id as provided in the parameter. If first_conn_notify is not NULL, the success method of this continuation will be called to signal the first connection. The first connection signal is an indication the application process should fork a new process to handle an incoming connection.
Parameters
sock the socket id
make_new_socket whether to fork a new process for incoming connections
caller the blocking socket continuation
first_conn_notify contination to notify socket of first connection
Definition at line 403 of file socket_master.cc.
References accept1a(), accept1b(), block_till(), bound_socks, s3f::s3fnet::SocketContinuation::chain_continuation, s3f::s3fnet::Socket::CONN_RESET, s3f::s3fnet::Socket::CONNECT_ACTIVE, s3f::s3fnet::SocketSession::connected(), s3f::s3fnet::BSocketContinuation::failure(), s3f::s3fnet::Socket::FIRST_CONNECTION, s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::SocketSession::listen(), s3f::s3fnet::BSocketContinuation::next_stage, Entity::now(), S3FNET_MAP(), s3f::s3fnet::Socket::session, SOCK_DUMP, and s3f::s3fnet::Socket::state.
Referenced by s3f::s3fnet::TCPServerSession::handle_client().
 {
   assert(caller);
   Socket* mysocket = 0;
   S3FNET_MAP(int, Socket*)::iterator iter = bound_socks.find(sock);
   if(iter != bound_socks.end()) mysocket = (*iter).second;
   if(!mysocket || // if the socket is not bound
      !mysocket->session || // this shouldn't happen
      mysocket->session->connected() || // if the socket has been connected
      (mysocket->state & Socket::CONNECT_ACTIVE)) // if the socket is connecting
   {
     caller->failure();
     return;
   }
   SOCK_DUMP(printf("[host=\"%s\"] %ld: accept(), socket=%d (state=%08x), make_new_sock=%d.\n",
                    inHost()->nhi.toString(), inHost()->now(), sock, mysocket->state, make_new_socket));
   // initiate the passive listen
   if(!mysocket->session->listen())
   {
     caller->failure();
     return;
   }
   // flip the connect active flag
   mysocket->state |= Socket::CONNECT_ACTIVE;
   // we capture the first connection signal as an indication the
   // application process should fork a new process to handle the
   // incoming connection.
   if(make_new_socket) caller->next_stage = &SocketMaster::accept1a;
   else caller->next_stage = &SocketMaster::accept1b;
   caller->chain_continuation = first_conn_notify;
   block_till(sock, Socket::FIRST_CONNECTION|Socket::CONN_RESET, false, caller);
 }
void s3f::s3fnet::SocketMaster::send (int sock, uint32 length, byte * msg, BSocketContinuation * caller)
Send data to remote host Send a message of the given length and return the number of bytes that have been sent successfully.
The failure function of the continuation will be called if there is an error. Otherwise, the success method is called and the return value is the number of bytes got transferred successfully. If the msg parameter is not NULL, a real message will be sent.
Parameters
sock the socket id
length the size of the message in bytes
msg the message byte buffer
caller the blocking socket continuation
Definition at line 637 of file socket_master.cc.
References block_till(), bound_socks, s3f::s3fnet::Socket::bytes_completed, s3f::s3fnet::Socket::CONN_RESET, s3f::s3fnet::SocketSession::connected(), s3f::s3fnet::BSocketContinuation::failure(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::BSocketContinuation::next_stage, Entity::now(), s3f::s3fnet::Socket::OK_TO_SEND, s3f::s3fnet::SocketContinuation::retval, S3FNET_MAP(), s3f::s3fnet::SocketSession::send(), send1(), s3f::s3fnet::Socket::session, SOCK_DUMP, s3f::s3fnet::Socket::state, and s3f::s3fnet::BSocketContinuation::success().
Referenced by s3f::s3fnet::UDPServerSession::interval_elapsed(), s3f::s3fnet::TCPServerSession::sending_data(), s3f::s3fnet::UDPClientSession::server_connected(), and s3f::s3fnet::TCPClientSession::server_connected().
 {
   assert(caller);
   Socket* mysocket = 0;
   S3FNET_MAP(int, Socket*)::iterator iter = bound_socks.find(sock);
   if(iter != bound_socks.end()) mysocket = (*iter).second;
   if(!mysocket || !mysocket->session || !mysocket->session->connected())
   {
     caller->failure();
     return;
   }
   SOCK_DUMP(printf("[host=\"%s\"] %ld: send(), socket=%d (state=%08x), length=%u (%s).\n",
                    inHost()->nhi.toString(), inHost()->now(), sock, mysocket->state, length, msg?"real":"virtual"));
   // initiate the send
   mysocket->bytes_completed = mysocket->session->send(length, msg);
   if(mysocket->bytes_completed < 0)
   {
     caller->failure();
     return;
   }
   // if initially the message has been sent completely in all, no more
   // waiting is necessary; otherwise, one must wait for the OK_TO_SEND
   // (or CONN_RESET) signal to get the true number of bytes that have
   // completed the transmission
   if(mysocket->bytes_completed < length)
   {
     caller->next_stage = &SocketMaster::send1;
     block_till(sock, Socket::OK_TO_SEND|Socket::CONN_RESET, false, caller);
   }
   else
   {
     SOCK_DUMP(printf("[host=\"%s\"] %ld: send(), socket=%d (state=%08x), sent all %u bytes, immediately.\n",
                      inHost()->nhi.toString(), inHost()->now(), sock, mysocket->state, length));
     caller->retval = length;
     caller->success();
   }
 }
void s3f::s3fnet::SocketMaster::recv (int sock, uint32 bufsiz, byte * buffer, BSocketContinuation * caller)
Receive data from remote host Receive a message of the given length.
On success, the success method of the continuation will be called and the return value will be set to the number of bytes that have been received successfully. The failure method of the continuation will be called if there is an error. If the buffer parameter is not NULL and if the arrived packet contains a real message, the message will be copied to the message buffer.
Parameters
sock the socket id
bufsiz the size of the buffer to read into
buffer the buffer to read into
caller the blocking socket continuation
Definition at line 717 of file socket_master.cc.
References block_till(), bound_socks, s3f::s3fnet::Socket::bytes_completed, s3f::s3fnet::Socket::CONN_RESET, s3f::s3fnet::SocketSession::connected(), s3f::s3fnet::Socket::DATA_AVAILABLE, s3f::s3fnet::BSocketContinuation::failure(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::BSocketContinuation::next_stage, Entity::now(), s3f::s3fnet::SocketSession::recv(), recv1(), s3f::s3fnet::SocketContinuation::retval, S3FNET_MAP(), s3f::s3fnet::Socket::session, SOCK_DUMP, s3f::s3fnet::Socket::SOCK_EOF, s3f::s3fnet::Socket::state, and s3f::s3fnet::BSocketContinuation::success().
Referenced by s3f::s3fnet::TCPServerSession::connection_accepted(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::UDPServerSession::handle_client(), s3f::s3fnet::UDPClientSession::request_sent(), s3f::s3fnet::TCPClientSession::request_sent(), and s3f::s3fnet::BTCPClientSession::server_connected().
 {
   assert(caller);
   Socket* mysocket = 0;
   S3FNET_MAP(int, Socket*)::iterator iter = bound_socks.find(sock);
   if(iter != bound_socks.end()) mysocket = (*iter).second;
   if(!mysocket || !mysocket->session || !mysocket->session->connected())
   {
     caller->failure();
     return;
   }
   SOCK_DUMP(printf("[host=\"%s\"] %ld: recv(), socket=%d (state=%08x), bufsiz=%u.\n",
                    inHost()->nhi.toString(), inHost()->now(), sock, mysocket->state, bufsiz));
   // initiate the receive; it's possible we received nothing at this stage
   mysocket->bytes_completed = mysocket->session->recv(bufsiz, buffer);
   if(mysocket->bytes_completed < 0)
   {
     caller->failure();
     return;
   }
   // if initially the message has been received completely in all, no
   // more waiting is necessary; otherwise, one must wait for the
   // SOCK_EOF or DATA_AVAILABLE (or CONN_RESET) signal to get the true
   // number of bytes that have completed the transmission
   if(mysocket->bytes_completed < bufsiz)
   {
     caller->next_stage = &SocketMaster::recv1;
     block_till(sock, Socket::SOCK_EOF|Socket::DATA_AVAILABLE|Socket::CONN_RESET, false, caller);
   }
   else
   {
     SOCK_DUMP(printf("[host=\"%s\"] %ld: send(), socket=%d (state=%08x), received all %u bytes, immediately.\n",
                      inHost()->nhi.toString(), inHost()->now(), sock, mysocket->state, bufsiz));
     caller->retval = bufsiz;
     caller->success();
   }
 }
void s3f::s3fnet::SocketMaster::close (int sock, BSocketContinuation * caller)
Terminate the connection Close the connection and invalidate the socket.
The success method of the continuation will be called on success.
Parameters
sock the socket id
caller the blocking socket continuation
Definition at line 802 of file socket_master.cc.
References block_till(), bound_socks, close1(), s3f::s3fnet::Socket::CONN_CLOSED, s3f::s3fnet::Socket::CONN_RESET, s3f::s3fnet::SocketSession::connected(), s3f::s3fnet::Socket::die_slowly(), s3f::s3fnet::SocketSession::disconnect(), s3f::s3fnet::BSocketContinuation::failure(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::Socket::is_active(), s3f::s3fnet::BSocketContinuation::next_stage, Entity::now(), s3f::s3fnet::Socket::reinit(), s3f::s3fnet::Socket::release(), S3FNET_MAP(), s3f::s3fnet::Socket::session, s3f::s3fnet::Socket::SESSION_RELEASED, SOCK_DUMP, s3f::s3fnet::Socket::state, and s3f::s3fnet::BSocketContinuation::success().
Referenced by s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::UDPServerSession::data_sent(), and s3f::s3fnet::TCPServerSession::data_sent().
 {
   assert(caller);
   Socket* mysocket = 0;
   S3FNET_MAP(int, Socket*)::iterator iter = bound_socks.find(sock);
   if(iter != bound_socks.end()) mysocket = (*iter).second;
   if(!mysocket)
   {
     caller->failure();
     return;
   }
   SOCK_DUMP(printf("[host=\"%s\"] %ld: close(), socket=%d (state=%08x).\n",
                    inHost()->nhi.toString(), inHost()->now(), sock, mysocket->state));
   if(mysocket->session && mysocket->session->connected())
   {
     // proceed to disconnect
     mysocket->session->disconnect();
     caller->next_stage = &SocketMaster::close1;
     block_till(sock, Socket::CONN_RESET|Socket::CONN_CLOSED|Socket::SESSION_RELEASED, false, caller);
   }
   else
   {
     SOCK_DUMP(printf("[host=\"%s\"] %ld: close(), socket=%d (state=%08x), not connected (no blocking).\n",
                      inHost()->nhi.toString(), inHost()->now(), sock, mysocket->state));
     mysocket->reinit();
     if(mysocket->is_active()) mysocket->die_slowly();
     else
     {
       // the destructor will call release method---which will detach
       // the socket session from the socket, remove the socket session
       // from the session master, and then reclaim the socket
       // session---before the socket is reclaimed
       mysocket->release();
       bound_socks.erase(sock);
     }
     caller->success();
   }
 }
void s3f::s3fnet::SocketMaster::connect1 (int sock, BSocketContinuation * caller) private
continuations of the method connect1() in the standard socket interface
Definition at line 365 of file socket_master.cc.
References bound_socks, s3f::s3fnet::Socket::CONN_RESET, s3f::s3fnet::Socket::deactivate(), s3f::s3fnet::BSocketContinuation::failure(), s3f::s3fnet::Socket::has_died(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::Socket::is_active(), s3f::s3fnet::Socket::mask, Entity::now(), s3f::s3fnet::Socket::reinit(), s3f::s3fnet::Socket::release(), S3FNET_MAP(), SOCK_DUMP, s3f::s3fnet::Socket::state, and s3f::s3fnet::BSocketContinuation::success().
Referenced by connect().
 {
   assert(caller);
   Socket* mysocket = 0;
   S3FNET_MAP(int, Socket*)::iterator iter = bound_socks.find(sock);
   if(iter != bound_socks.end()) mysocket = (*iter).second;
   if(!mysocket) { caller->failure(); return; }
   mysocket->deactivate();
   mysocket->mask = 0;
   // flip the connect active flag
   mysocket->state &= ~Socket::CONNECT_ACTIVE;
   if(mysocket->has_died() && !mysocket->is_active())
   {
     mysocket->release();
     bound_socks.erase(sock);
     caller->failure();
     return;
   }
   // the socket could have been reset
   if(mysocket->state & Socket::CONN_RESET)
   {
     SOCK_DUMP(printf("[host=\"%s\"] %ld: connect(): socket=%d (state=%08x), reset.\n",
                      inHost()->nhi.toString(), inHost()->now(), sock, mysocket->state));
     mysocket->reinit();
     caller->failure();
     return;
   }
   SOCK_DUMP(printf("[host=\"%s\"] %ld: connect(): socket=%d (state=%08x), continuing.\n",
                    inHost()->nhi.toString(), inHost()->now(), sock, mysocket->state));
   caller->success();
 }
void s3f::s3fnet::SocketMaster::accept1a (int sock, BSocketContinuation * caller) private
continuations of the method accept1a() in the standard socket interface
Definition at line 443 of file socket_master.cc.
References accept2a(), block_till(), bound_socks, s3f::s3fnet::SocketContinuation::chain_continuation, s3f::s3fnet::Socket::CONN_RESET, s3f::s3fnet::Socket::CONNECT_ACTIVE, s3f::s3fnet::Socket::deactivate(), s3f::s3fnet::BSocketContinuation::failure(), s3f::s3fnet::Socket::has_died(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::Socket::is_active(), s3f::s3fnet::Socket::mask, s3f::s3fnet::BSocketContinuation::next_stage, Entity::now(), s3f::s3fnet::Socket::OK_TO_SEND, s3f::s3fnet::Socket::reinit(), s3f::s3fnet::Socket::release(), S3FNET_MAP(), SOCK_DUMP, and s3f::s3fnet::Socket::state.
Referenced by accept().
 {
   assert(caller);
   Socket* mysocket = 0;
   S3FNET_MAP(int, Socket*)::iterator iter = bound_socks.find(sock);
   if(iter != bound_socks.end()) mysocket = (*iter).second;
   if(!mysocket) { caller->failure(); return; }
   mysocket->deactivate();
   mysocket->mask = 0;
   // flip the active connection flag
   mysocket->state &= ~Socket::CONNECT_ACTIVE;
   if(mysocket->has_died() && !mysocket->is_active())
   {
     mysocket->release();
     bound_socks.erase(sock);
     caller->failure();
     return;
   }
   if(mysocket->state & Socket::CONN_RESET)
   {
     SOCK_DUMP(printf("[host=\"%s\"] %ld: accept(): socket=%d (state=%08x), reset.\n",
                      inHost()->nhi.toString(), inHost()->now(), sock, mysocket->state));
     mysocket->reinit();
     caller->failure();
     return;
   }
   SOCK_DUMP(printf("[host=\"%s\"] %ld: accept(), socket=%d (state=%08x), first connection.\n",
                    inHost()->nhi.toString(), inHost()->now(), sock, mysocket->state));
   // notify first connection
   if(caller->chain_continuation)
     ((BSocketContinuation*)caller->chain_continuation)->success();
   // flip the connect active flag
   mysocket->state |= Socket::CONNECT_ACTIVE;
   caller->next_stage = &SocketMaster::accept2a;
   block_till(sock, Socket::OK_TO_SEND|Socket::CONN_RESET, false, caller);
 }
void s3f::s3fnet::SocketMaster::accept1b (int sock, BSocketContinuation * caller) private
continuations of the method accept1b() in the standard socket interface
Definition at line 489 of file socket_master.cc.
References accept2b(), block_till(), bound_socks, s3f::s3fnet::SocketContinuation::chain_continuation, s3f::s3fnet::Socket::CONN_RESET, s3f::s3fnet::Socket::CONNECT_ACTIVE, s3f::s3fnet::Socket::deactivate(), s3f::s3fnet::BSocketContinuation::failure(), s3f::s3fnet::Socket::has_died(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::Socket::is_active(), s3f::s3fnet::Socket::mask, s3f::s3fnet::BSocketContinuation::next_stage, Entity::now(), s3f::s3fnet::Socket::OK_TO_SEND, s3f::s3fnet::Socket::reinit(), s3f::s3fnet::Socket::release(), S3FNET_MAP(), SOCK_DUMP, and s3f::s3fnet::Socket::state.
Referenced by accept().
 {
   assert(caller);
   Socket* mysocket = 0;
   S3FNET_MAP(int, Socket*)::iterator iter = bound_socks.find(sock);
   if(iter != bound_socks.end()) mysocket = (*iter).second;
   if(!mysocket) { caller->failure(); return; }
   mysocket->deactivate();
   mysocket->mask = 0;
   // flip the active connection flag
   mysocket->state &= ~Socket::CONNECT_ACTIVE;
   if(mysocket->has_died() && !mysocket->is_active())
   {
     mysocket->release();
     bound_socks.erase(sock);
     caller->failure();
     return;
   }
   if(mysocket->state & Socket::CONN_RESET)
   {
     SOCK_DUMP(printf("[host=\"%s\"] %ld: accept(): socket=%d (state=%08x), reset.\n",
                      inHost()->nhi.toString(), inHost()->now(), sock, mysocket->state));
     mysocket->reinit();
     caller->failure();
     return;
   }
   SOCK_DUMP(printf("[host=\"%s\"] %ld: accept(), socket=%d (state=%08x), first connection.\n",
                    inHost()->nhi.toString(), inHost()->now(), sock, mysocket->state));
   // notify first connection
   if(caller->chain_continuation)
     ((BSocketContinuation*)caller->chain_continuation)->success();
   // flip the connect active flag
   mysocket->state |= Socket::CONNECT_ACTIVE;
   caller->next_stage = &SocketMaster::accept2b;
   block_till(sock, Socket::OK_TO_SEND|Socket::CONN_RESET, false, caller);
 }
void s3f::s3fnet::SocketMaster::accept2a (int sock, BSocketContinuation * caller) private
continuations of the method accept2a() in the standard socket interface
Definition at line 535 of file socket_master.cc.
References bound_socks, s3f::s3fnet::Socket::CONN_RESET, s3f::s3fnet::SessionMaster::createSession(), s3f::s3fnet::Socket::deactivate(), s3f::s3fnet::BSocketContinuation::failure(), s3f::s3fnet::SocketSession::getSessionMaster(), s3f::s3fnet::Socket::has_died(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::Socket::is_active(), s3f::s3fnet::Socket::mask, Entity::now(), s3f::s3fnet::Socket::reinit(), s3f::s3fnet::Socket::release(), s3f::s3fnet::SocketContinuation::retval, S3FNET_MAKE_PAIR, S3FNET_MAP(), s3f::s3fnet::Socket::session, s3f::s3fnet::SocketSession::setSocketID(), s3f::s3fnet::SocketSession::setSource(), SOCK_DUMP, socket(), s3f::s3fnet::SessionID::src_ip, s3f::s3fnet::SessionID::src_port, s3f::s3fnet::Socket::state, s3f::s3fnet::BSocketContinuation::success(), and unbound_socks.
Referenced by accept1a().
 {
   assert(caller);
   Socket* mysocket = 0;
   S3FNET_MAP(int, Socket*)::iterator iter = bound_socks.find(sock);
   if(iter != bound_socks.end()) mysocket = (*iter).second;
   if(!mysocket) { caller->failure(); return; }
   mysocket->deactivate();
   mysocket->mask = 0;
   // flip the active connection flag
   mysocket->state &= ~Socket::CONNECT_ACTIVE;
   if(mysocket->has_died() && !mysocket->is_active())
   {
     mysocket->release();
     bound_socks.erase(sock);
     caller->failure(); return;
   }
   if(mysocket->state & Socket::CONN_RESET)
   {
     SOCK_DUMP(printf("[host=\"%s\"] %ld: accept(): socket=%d (state=%08x), reset.\n",
                      inHost()->nhi.toString(), inHost()->now(), sock, mysocket->state));
     mysocket->reinit();
     caller->failure(); return;
   }
   SOCK_DUMP(printf("[host=\"%s\"] %ld: accept(), socket=%d (state=%08x), continuing.\n",
                    inHost()->nhi.toString(), inHost()->now(), sock, mysocket->state));
   // create a new session for the original socket
   SocketSession* session = mysocket->session->getSessionMaster()->createSession(sock);
   assert(session);
   if(!session->setSource(mysocket->session->src_ip, mysocket->session->src_port))
   {
     delete session;
     caller->failure();
     return;
   }
   int new_sock = socket(); // unbound at first
   Socket* new_mysocket = new Socket();
   assert(new_mysocket);
   // copy the old socket to the new one and put it in the
   // bound_socks list
   new_mysocket->session = mysocket->session;
   new_mysocket->state   = mysocket->state;
   new_mysocket->session->setSocketID(new_sock);
   unbound_socks.erase(new_sock);
   bound_socks.insert(S3FNET_MAKE_PAIR(new_sock, new_mysocket));
   // assign the newly created session to old socket (old socket
   // remains in bound table) and reset its state
   mysocket->session = session;
   mysocket->reinit();
   caller->retval = new_sock;
   caller->success();
   return;
 }
void s3f::s3fnet::SocketMaster::accept2b (int sock, BSocketContinuation * caller) private
continuations of the method accept2b() in the standard socket interface
Definition at line 600 of file socket_master.cc.
References bound_socks, s3f::s3fnet::Socket::CONN_RESET, s3f::s3fnet::Socket::deactivate(), s3f::s3fnet::BSocketContinuation::failure(), s3f::s3fnet::Socket::has_died(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::Socket::is_active(), s3f::s3fnet::Socket::mask, Entity::now(), s3f::s3fnet::Socket::reinit(), s3f::s3fnet::Socket::release(), s3f::s3fnet::SocketContinuation::retval, S3FNET_MAP(), SOCK_DUMP, s3f::s3fnet::Socket::state, and s3f::s3fnet::BSocketContinuation::success().
Referenced by accept1b().
 {
   assert(caller);
   Socket* mysocket = 0;
   S3FNET_MAP(int, Socket*)::iterator iter = bound_socks.find(sock);
   if(iter != bound_socks.end()) mysocket = (*iter).second;
   if(!mysocket) { caller->failure(); return; }
   mysocket->deactivate();
   mysocket->mask = 0;
   // flip the active connection flag
   mysocket->state &= ~Socket::CONNECT_ACTIVE;
   if(mysocket->has_died() && !mysocket->is_active())
   {
     mysocket->release();
     bound_socks.erase(sock);
     caller->failure(); return;
   }
   if(mysocket->state & Socket::CONN_RESET)
   {
     SOCK_DUMP(printf("[host=\"%s\"] %ld: accept(): socket=%d (state=%08x), reset.\n",
                      inHost()->nhi.toString(), inHost()->now(), sock, mysocket->state));
     mysocket->reinit();
     caller->failure(); return;
   }
   SOCK_DUMP(printf("[host=\"%s\"] %ld: accept(), socket=%d (state=%08x), continuing.\n",
                    inHost()->nhi.toString(), inHost()->now(), sock, mysocket->state));
   caller->retval = sock;
   caller->success();
 }
void s3f::s3fnet::SocketMaster::send1 (int sock, BSocketContinuation * caller) private
continuations of the method send1() in the standard socket interface
Definition at line 679 of file socket_master.cc.
References bound_socks, s3f::s3fnet::Socket::bytes_completed, s3f::s3fnet::Socket::CONN_RESET, s3f::s3fnet::Socket::deactivate(), s3f::s3fnet::BSocketContinuation::failure(), s3f::s3fnet::Socket::has_died(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::Socket::is_active(), s3f::s3fnet::Socket::mask, Entity::now(), s3f::s3fnet::Socket::reinit(), s3f::s3fnet::Socket::release(), s3f::s3fnet::SocketContinuation::retval, S3FNET_MAP(), SOCK_DUMP, s3f::s3fnet::Socket::state, and s3f::s3fnet::BSocketContinuation::success().
Referenced by send().
 {
   assert(caller);
   Socket* mysocket = 0;
   S3FNET_MAP(int, Socket*)::iterator iter = bound_socks.find(sock);
   if(iter != bound_socks.end()) mysocket = (*iter).second;
   if(!mysocket) { caller->failure(); return; }
   mysocket->deactivate();
   mysocket->mask = 0;
   if(mysocket->has_died() && !mysocket->is_active())
   {
     mysocket->release();
     bound_socks.erase(sock);
     caller->failure(); return;
   }
   if(mysocket->state & Socket::CONN_RESET)
   {
     SOCK_DUMP(printf("[host=\"%s\"] %ld: send(): socket=%d (state=%08x), reset.\n",
                      inHost()->nhi.toString(), inHost()->now(), sock, mysocket->state));
     mysocket->reinit();
     // we don't bail out here; we need to return the number of bytes
     // sent so far unless nothing's been sent
     if(mysocket->bytes_completed == 0)
     {
       caller->failure(); return;
     }
   }
   SOCK_DUMP(printf("[host=\"%s\"] %ld: send(), socket=%d (state=%08x), sent %u bytes.\n",
                    inHost()->nhi.toString(), inHost()->now(), sock, mysocket->state, mysocket->bytes_completed));
   caller->retval = mysocket->bytes_completed;
   caller->success();
 }
void s3f::s3fnet::SocketMaster::recv1 (int sock, BSocketContinuation * caller) private
continuations of the method recv1() in the standard socket interface
Definition at line 759 of file socket_master.cc.
References bound_socks, s3f::s3fnet::Socket::bytes_completed, s3f::s3fnet::Socket::CONN_RESET, s3f::s3fnet::Socket::deactivate(), s3f::s3fnet::BSocketContinuation::failure(), s3f::s3fnet::Socket::has_died(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::Socket::is_active(), s3f::s3fnet::Socket::mask, Entity::now(), s3f::s3fnet::Socket::reinit(), s3f::s3fnet::Socket::release(), s3f::s3fnet::SocketContinuation::retval, S3FNET_MAP(), SOCK_DUMP, s3f::s3fnet::Socket::SOCK_EOF, s3f::s3fnet::Socket::state, and s3f::s3fnet::BSocketContinuation::success().
Referenced by recv().
 {
   assert(caller);
   Socket* mysocket = 0;
   S3FNET_MAP(int, Socket*)::iterator iter = bound_socks.find(sock);
   if(iter != bound_socks.end()) mysocket = (*iter).second;
   if(!mysocket) { caller->failure(); return; }
   mysocket->deactivate();
   mysocket->mask = 0;
   if(mysocket->has_died() && !mysocket->is_active())
   {
     mysocket->release();
     bound_socks.erase(sock);
     caller->failure(); return;
   }
   if(mysocket->state & Socket::CONN_RESET)
   {
     SOCK_DUMP(printf("[host=\"%s\"] %ld: recv(): socket=%d (state=%08x), reset.\n",
                      inHost()->nhi.toString(), inHost()->now(), sock, mysocket->state));
     mysocket->reinit();
     // we don't bail out here; we need to return the number of bytes
     // received so far
     if(mysocket->bytes_completed == 0)
     {
       caller->failure(); return;
     }
   }
   if((mysocket->state & Socket::SOCK_EOF) && mysocket->bytes_completed == 0)
   {
     caller->failure(); return;
   }
   SOCK_DUMP(printf("[host=\"%s\"] %ld: recv(), socket=%d (state=%08x), received %u bytes.\n",
                    inHost()->nhi.toString(), inHost()->now(), sock, mysocket->state, mysocket->bytes_completed));
   caller->retval = mysocket->bytes_completed;
   caller->success();
 }
void s3f::s3fnet::SocketMaster::close1 (int sock, BSocketContinuation * caller) private
continuations of the method close1() in the standard socket interface
Definition at line 846 of file socket_master.cc.
References bound_socks, s3f::s3fnet::Socket::deactivate(), s3f::s3fnet::Socket::die_slowly(), s3f::s3fnet::BSocketContinuation::failure(), s3f::s3fnet::Socket::has_died(), s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::Socket::is_active(), s3f::s3fnet::Socket::mask, Entity::now(), s3f::s3fnet::Socket::reinit(), s3f::s3fnet::SocketSession::release(), s3f::s3fnet::Socket::release(), S3FNET_MAP(), s3f::s3fnet::Socket::session, s3f::s3fnet::Socket::SESSION_RELEASED, SOCK_DUMP, s3f::s3fnet::Socket::state, and s3f::s3fnet::BSocketContinuation::success().
Referenced by close().
 {
   assert(caller);
   Socket* mysocket = 0;
   S3FNET_MAP(int, Socket*)::iterator iter = bound_socks.find(sock);
   if(iter != bound_socks.end()) mysocket = (*iter).second;
   if(!mysocket) { caller->failure(); return; }
   mysocket->deactivate();
   mysocket->mask = 0;
   SOCK_DUMP(printf("[host=\"%s\"] %ld: close(), socket=%d (state=%08x), continuing.\n",
                    inHost()->nhi.toString(), inHost()->now(), sock, mysocket->state));
   if(mysocket->has_died() && !mysocket->is_active())
   {
     mysocket->release();
     bound_socks.erase(sock);
     caller->failure(); return;
   }
   if(mysocket->session && (mysocket->state & Socket::SESSION_RELEASED))
   {
     mysocket->session->release();
   }
   mysocket->reinit();
   if(mysocket->is_active()) mysocket->die_slowly();
   else
   {
     // the destructor will call release method---which will detach
     // the socket session from the socket, remove the socket session
     // from the session master, and then reclaim the socket
     // session---before the socket is reclaimed
     mysocket->release();
     bound_socks.erase(sock);
   }
   caller->success();
 }
void s3f::s3fnet::SocketMaster::block_till (int sockid, uint32 mask, bool anysignal, BSocketContinuation * caller) private
Checks if we need to block and prepares to do so.
This is a "replacement" of the block_till in the original ssfnet blocking socket master, which actually simulated blocking the simulated process itself instead of using continuations. Here, we basically just set masks.
Parameters
sockid the socket id
mask the mask to wait for
anysignal whether to wake on any signal
caller the blocking socket continuation
Definition at line 306 of file socket_master.cc.
References s3f::s3fnet::Socket::activate(), bound_socks, s3f::s3fnet::Socket::continuation, s3f::s3fnet::ProtocolSession::inHost(), s3f::s3fnet::Socket::mask, s3f::s3fnet::BSocketContinuation::next_stage, Entity::now(), S3FNET_MAP(), SOCK_DUMP, and s3f::s3fnet::Socket::state.
Referenced by accept(), accept1a(), accept1b(), close(), connect(), recv(), and send().
 {
   Socket* mysocket = 0;
   S3FNET_MAP(int, Socket*)::iterator iter = bound_socks.find(sock);
   if(iter != bound_socks.end()) mysocket = (*iter).second;
   if(!mysocket) return;
   SOCK_DUMP(printf("[host=\"%s\"] %ld: block_till(): socket=%d (state=%08x), mask=%08x, any=%d.\n",
                    inHost()->nhi.toString(), inHost()->now(), sock, mysocket->state, mask, anysignal));
   if(!(mask & mysocket->state)) // no match
   {
     if(anysignal) mysocket->mask = 0xffffffff;
     else mysocket->mask = (mask & ~mysocket->state);
     SOCK_DUMP(printf("suspend: mask=%08x, state=%08x.\n", mysocket->mask, mysocket->state));
     mysocket->activate();
     mysocket->continuation = (SocketContinuation*)caller;
   }
   else // no blocking, continue to the next stage
   {
     assert(caller->next_stage);
     void (SocketMaster::*fct)(int, BSocketContinuation*) = caller->next_stage;
     caller->next_stage = 0;
     (this->*fct)(sock, caller);
   }
 }
typedef s3f::s3fnet::SocketMaster::S3FNET_MAP (int , Socket *) protected
Referenced by abort(), accept(), accept1a(), accept1b(), accept2a(), accept2b(), bind(), block_till(), close(), close1(), connect(), connect1(), connected(), control(), eof(), listen(), recv(), recv1(), send(), send1(), and ~SocketMaster().
typedef s3f::s3fnet::SocketMaster::S3FNET_SET (int) protected
Referenced by bind().
int s3f::s3fnet::SocketMaster::push (Activation msg, ProtocolSession * hi_sess, void * extinfo = 0, size_t extinfo_size = 0) private virtual
Push to lower protocol layer.
The push method is not supposed to be called for socket master protocol session; it's defined here to prevent misuse.
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 150 of file socket_master.cc.
References s3f::s3fnet::error_quit().
 {
   error_quit("ERROR: SocketMaster::push() should not be called.\n");
   return 1;
 }
int s3f::s3fnet::SocketMaster::pop (Activation msg, ProtocolSession * lo_sess, void * extinfo = 0, size_t extinfo_size = 0) private virtual
Pop to higher protocol layer.
The pop method is not supposed to be called for socket master protocol session; it's defined here to prevent misuse.
Reimplemented from s3f::s3fnet::ProtocolSession.
Definition at line 156 of file socket_master.cc.
References s3f::s3fnet::error_quit().
 {
   error_quit("ERROR: SocketMaster::pop() should not be called.\n");
   return 1;
 }
void s3f::s3fnet::ProtocolSession::config (s3f::dml::Configuration * cfg) virtual inherited
The config method is used to configure the protocol session from DML description.
It is expected to be called first, right after the ProtocolSession object is created and before the init method is called. A DML configuration should be passed as an argument to the method and it should be the value (a list of attributes) of a 'session' attribute (inside 'graph'). The default behavior of this method is to find out 'name' and 'use' attributes. The derived class should override this method to obtain protocol specific parameters from the DML description. However, the derived class must not forget to call this method in the base class so that the default behavior is carried out. The config method recognizes the following attributes:
name: name of the protocol session (required)
use: protocol class name (required)
It is important to note that the timer still cannot be used at this stage since the owner community hasn't been resolved. It has to wait until after the init method is called.
Reimplemented in s3f::s3fnet::NBTCPServerSession, s3f::s3fnet::IPSession, s3f::s3fnet::OpenFlowSwitchSession, s3f::s3fnet::BTCPClientSession, s3f::s3fnet::NBTCPClientSession, s3f::s3fnet::TCPMaster, s3f::s3fnet::TCPServerSession, s3f::s3fnet::UDPClientSession, s3f::s3fnet::SimplePhy, s3f::s3fnet::UDPServerSession, s3f::s3fnet::OpenVZEventSession, s3f::s3fnet::OpenFlowControllerSession, s3f::s3fnet::TCPClientSession, s3f::s3fnet::DummySession, and s3f::s3fnet::UDPMaster.
Definition at line 21 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::configured(), s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolSession::name, s3f::s3fnet::ProtocolSession::PSESS_CONFIGURED, s3f::s3fnet::sstrdup(), s3f::s3fnet::ProtocolSession::stage, and s3f::s3fnet::ProtocolSession::use.
Referenced by s3f::s3fnet::UDPMaster::config(), s3f::s3fnet::DummySession::config(), s3f::s3fnet::TCPClientSession::config(), s3f::s3fnet::OpenFlowControllerSession::config(), s3f::s3fnet::OpenVZEventSession::config(), s3f::s3fnet::UDPServerSession::config(), s3f::s3fnet::SimplePhy::config(), s3f::s3fnet::UDPClientSession::config(), s3f::s3fnet::TCPServerSession::config(), s3f::s3fnet::TCPMaster::config(), s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::NBTCPClientSession::config(), s3f::s3fnet::BTCPClientSession::config(), s3f::s3fnet::OpenFlowSwitchSession::config(), s3f::s3fnet::IPSession::config(), s3f::s3fnet::NBTCPServerSession::config(), and s3f::s3fnet::ProtocolGraph::config_session().
 {
   if(configured())
     error_quit("ERROR: duplicate calls to ProtocolSession::config(): "
                "session name is \"%s\".\n", name);
   else stage = PSESS_CONFIGURED;
   char* myname = (char*)cfg->findSingle("name");
   if(myname && s3f::dml::dmlConfig::isConf(myname))
     error_quit("ERROR: ProtocolSession::config(), invalid NAME attribute.\n");
   if(myname) name = sstrdup(myname);
   else name = 0; // cannot do assertion because it may happen for a "default" interface
   char* myuse  = (char*)cfg->findSingle("use");
   if(myuse && s3f::dml::dmlConfig::isConf(myuse))
     error_quit("ERROR: ProtocolSession::config(), invalid USE attribute.\n");
   if(myuse)  use = sstrdup(myuse);
   else use = 0; // cannot do assertion because it may happen for a "default" interface
 }
void s3f::s3fnet::ProtocolSession::wrapup () virtual inherited
The method is used to wrap up the protocol session.
It is called when the simulation finishes. It is designed to give user a chance to report simulation statistics. The default behavior is doing nothing. Subclass may override this method for protocol specific dealings. Note that there is no specific order in which wrapup is called for protocol sessions in a protocol graph.
Definition at line 59 of file protocol_session.cc.
References s3f::s3fnet::error_quit(), s3f::s3fnet::ProtocolSession::initialized(), s3f::s3fnet::ProtocolSession::name, s3f::s3fnet::ProtocolSession::PSESS_WRAPPED_UP, s3f::s3fnet::ProtocolSession::stage, and s3f::s3fnet::ProtocolSession::wrapped_up().
 {
   // Make sure this init function at the base class should be called
   // by the derived function!
   if(!initialized())
     error_quit("ERROR: ProtocolSession \"%s\" wrapup() called before init(), "
                "forgot to call base class's init() in your derived class?\n", name);
   else if(wrapped_up())
     error_quit("ERROR: duplicate calls to ProtocolSession::wrapup(): "
                "session name is \"%s\".\n", name);
   else stage = PSESS_WRAPPED_UP;
 }
int s3f::s3fnet::ProtocolSession::pushdown (Activation msg, ProtocolSession * hi_sess, void * extinfo = 0, size_t extinfo_size = 0) inherited
The original push method is divided into pushdown() and push().
The pushdown method is the generic part of the code, which is reserved for modeling the handling of messages transferred between protocol layers.
See Also
ProtocolSession::push method for details.
Definition at line 72 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::push().
Referenced by s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), s3f::s3fnet::IPSession::control(), s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), s3f::s3fnet::OpenFlowSwitchSession::OutputControl(), s3f::s3fnet::OpenFlowSwitchSession::OutputPacket(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::UDPMaster::push(), s3f::s3fnet::TCPMaster::push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::send(), and s3f::s3fnet::TCPSession::send_data().
 {
   return push(msg, hi_sess, extinfo, extinfo_size);
 }
int s3f::s3fnet::ProtocolSession::popup (Activation msg, ProtocolSession * lo_sess, void * extinfo = 0, size_t extinfo_size = 0) inherited
The original pop method is divided into popup() and pop().
The popup method is the generic part of the code, which is reserved for modeling the handling of messages transferred between protocol layers.
See Also
ProtocolSession::pop method for details.
Definition at line 77 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::pop().
Referenced by s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::IPSession::push(), and s3f::s3fnet::SimplePhy::receivePacket().
 {
   return pop(msg, lo_sess, extinfo, extinfo_size);
 }
ProtocolGraph* s3f::s3fnet::ProtocolSession::inGraph () inline inherited
The method returns the protocol graph in which this protocol session resides.
Definition at line 178 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::ingraph.
Referenced by s3f::s3fnet::SimplePhy::config(), s3f::s3fnet::SimplePhy::control(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::SimpleMac::init(), s3f::s3fnet::SimplePhy::init(), s3f::s3fnet::RedQueue::init(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::SimplePhy::push(), s3f::s3fnet::SimplePhy::receivePacket(), s3f::s3fnet::SimplePhy::sendPacket(), s3f::s3fnet::SimpleMac::SimpleMac(), s3f::s3fnet::SimplePhy::SimplePhy(), s3f::s3fnet::SimpleMac::~SimpleMac(), and s3f::s3fnet::SimplePhy::~SimplePhy().
 { return ingraph; }
Host * s3f::s3fnet::ProtocolSession::inHost () virtual inherited
Return a pointer to the host owning this protocol session.
Reimplemented in s3f::s3fnet::NicProtocolSession.
Definition at line 118 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::ingraph.
Referenced by s3f::s3fnet::UDPSession::abort(), abort(), s3f::s3fnet::NBSocketMaster::abort(), accept(), s3f::s3fnet::NBSocketMaster::accept(), accept1a(), accept1b(), accept2a(), accept2b(), s3f::s3fnet::OpenFlowSwitchSession::AddFlow(), s3f::s3fnet::TCPSession::backoff_timeout(), bind(), s3f::s3fnet::NBSocketMaster::bind(), block_till(), s3f::s3fnet::NBSocketMaster::block_till(), s3f::s3fnet::BTCPClientSession::BTCPClientSession(), s3f::s3fnet::OpenFlowSwitchSession::BufferFromPacket(), s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::UDPServerSession::client_connected(), close(), s3f::s3fnet::NBSocketMaster::close(), close1(), s3f::s3fnet::NBSocketMaster::close1(), s3f::s3fnet::UDPMaster::config(), s3f::s3fnet::DummySession::config(), s3f::s3fnet::TCPClientSession::config(), s3f::s3fnet::UDPServerSession::config(), s3f::s3fnet::UDPClientSession::config(), s3f::s3fnet::TCPServerSession::config(), s3f::s3fnet::TCPMaster::config(), s3f::s3fnet::NBTCPClientSession::config(), s3f::s3fnet::BTCPClientSession::config(), s3f::s3fnet::IPSession::config(), s3f::s3fnet::NBTCPServerSession::config(), s3f::s3fnet::UDPSession::connect(), connect(), s3f::s3fnet::NBSocketMaster::connect(), connect1(), s3f::s3fnet::NBSocketMaster::connect1(), connected(), s3f::s3fnet::NBSocketMaster::connected(), s3f::s3fnet::UDPMaster::control(), control(), s3f::s3fnet::NBSocketMaster::control(), s3f::s3fnet::IPSession::control(), s3f::s3fnet::TCPMaster::createSession(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::UDPServerSession::data_sent(), s3f::s3fnet::TCPServerSession::data_sent(), s3f::s3fnet::UDPSession::disconnect(), s3f::s3fnet::TCPMaster::enableFastTimeout(), eof(), s3f::s3fnet::NBSocketMaster::eof(), s3f::s3fnet::UDPClientSessionContinuation::failure(), s3f::s3fnet::UDPServerSessionContinuation::failure(), s3f::s3fnet::TCPServerSessionContinuation::failure(), s3f::s3fnet::TCPClientSessionContinuation::failure(), s3f::s3fnet::BTCPClientSessionContinuation::failure(), s3f::s3fnet::TCPMaster::fast_timer_callback_body(), s3f::s3fnet::Stats::FlowStatsDump(), s3f::s3fnet::OpenFlowSwitchSession::FlowTableLookup(), s3f::s3fnet::IPSession::get_parent_by_protocol(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::ProtocolSession::getNow(), s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator(), s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::OpenFlowSwitchSession::HandleControlInput(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), s3f::s3fnet::DummySession::init(), s3f::s3fnet::UDPMaster::init(), s3f::s3fnet::OpenFlowControllerSession::init(), s3f::s3fnet::OpenVZEventSession::init(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPServerSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::TCPServerSession::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::OpenFlowSwitchSession::init(), s3f::s3fnet::NBTCPClientSession::init(), s3f::s3fnet::BTCPClientSession::init(), init(), s3f::s3fnet::IPSession::init(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::NBSocketMaster::init(), s3f::s3fnet::NBTCPServerSession::init(), s3f::s3fnet::TCPSession::init_state_closed(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::IPSession::IPSession(), s3f::s3fnet::UDPSession::listen(), listen(), s3f::s3fnet::NBSocketMaster::listen(), s3f::s3fnet::IPSession::load_forwarding_table(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), s3f::s3fnet::OpenFlowSwitchSession::ModFlow(), s3f::s3fnet::NBSocketMaster::NBSocketMaster(), s3f::s3fnet::NBTCPClientSession::NBTCPClientSession(), s3f::s3fnet::NBTCPServerSession::NBTCPServerSession(), s3f::s3fnet::NBTCPClientSession::non_blocking_loop(), s3f::s3fnet::NBTCPServerSession::non_blocking_loop(), s3f::s3fnet::OpenFlowSwitchSession::OutputControl(), s3f::s3fnet::OpenFlowSwitchSession::OutputPacket(), s3f::s3fnet::OpenFlowSwitchSession::OutputPort(), s3f::s3fnet::OpenFlowControllerSession::pop(), s3f::s3fnet::UDPMaster::pop(), s3f::s3fnet::OpenVZEventSession::pop(), s3f::s3fnet::OpenFlowSwitchSession::pop(), s3f::s3fnet::TCPMaster::pop(), s3f::s3fnet::IPSession::pop(), s3f::s3fnet::LearningController::process_recv_packet(), s3f::s3fnet::UDPMaster::push(), s3f::s3fnet::TCPMaster::push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::receive(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::LearningControllerSession::ReceiveFromSwitch(), s3f::s3fnet::OpenFlowSwitchSession::ReceivePacketOut(), s3f::s3fnet::OpenFlowSwitchSession::ReceivePortMod(), s3f::s3fnet::OpenFlowSwitchSession::ReceiveStatsRequest(), recv(), s3f::s3fnet::NBSocketMaster::recv(), recv1(), s3f::s3fnet::NBSocketMaster::recv1(), s3f::s3fnet::UDPServerSession::request_received(), s3f::s3fnet::TCPServerSession::request_received(), s3f::s3fnet::UDPClientSession::request_sent(), s3f::s3fnet::TCPClientSession::request_sent(), s3f::s3fnet::NBTCPClientSessionContinuation::resume(), s3f::s3fnet::NBTCPServerSessionContinuation::resume(), s3f::s3fnet::OpenFlowSwitchSession::RunThroughFlowTable(), s3f::s3fnet::UDPSession::send(), send(), s3f::s3fnet::NBSocketMaster::send(), send1(), s3f::s3fnet::NBSocketMaster::send1(), s3f::s3fnet::TCPSession::send_data(), s3f::s3fnet::OpenFlowSwitchSession::SendFlowExpired(), s3f::s3fnet::OpenFlowSwitchSession::SendOpenflowBuffer(), s3f::s3fnet::OpenFlowSwitchSession::SendPortStatus(), s3f::s3fnet::UDPClientSession::server_connected(), s3f::s3fnet::TCPClientSession::server_connected(), s3f::s3fnet::BTCPClientSession::server_connected(), s3f::s3fnet::UDPServerSession::session_closed(), s3f::s3fnet::UDPClientSession::session_closed(), s3f::s3fnet::TCPClientSession::session_closed(), s3f::s3fnet::TCPServerSession::session_closed(), s3f::s3fnet::BTCPClientSession::session_closed(), s3f::s3fnet::TCPMaster::setConnected(), s3f::s3fnet::OpenFlowSwitchSession::SetController(), s3f::s3fnet::TCPMaster::setIdle(), s3f::s3fnet::TCPMaster::setListening(), s3f::s3fnet::UDPSession::setSource(), s3f::s3fnet::TCPMaster::slow_timer_callback_body(), s3f::s3fnet::TCPSession::slowTimeoutHandling(), socket(), s3f::s3fnet::NBSocketMaster::socket(), SocketMaster(), s3f::s3fnet::UDPServerSession::start_on(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPServerSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), s3f::s3fnet::NBTCPClientSession::start_on(), s3f::s3fnet::BTCPClientSession::start_on(), s3f::s3fnet::NBTCPServerSession::start_on(), s3f::s3fnet::NBTCPServerSessionContinuation::success(), s3f::s3fnet::TCPClientSession::TCPClientSession(), s3f::s3fnet::TCPMaster::TCPMaster(), s3f::s3fnet::TCPServerSession::TCPServerSession(), s3f::s3fnet::TCPSession::TCPSession(), s3f::s3fnet::UDPClientSession::timeout(), s3f::s3fnet::TCPClientSession::timeout(), s3f::s3fnet::BTCPClientSession::timeout(), s3f::s3fnet::UDPClientSession::UDPClientSession(), s3f::s3fnet::UDPMaster::UDPMaster(), s3f::s3fnet::UDPServerSession::UDPServerSession(), s3f::s3fnet::UDPSession::UDPSession(), s3f::s3fnet::TCPSession::update_timeout(), s3f::s3fnet::IPSession::verify_local_ip_address(), and s3f::s3fnet::UDPSession::wake_app().
 {
   return dynamic_cast<Host*>(ingraph);
 }
Random::RNG* s3f::s3fnet::ProtocolSession::getRandom () inline inherited
The method returns a pointer to the random number generator.
Definition at line 200 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::sess_rng.
Referenced by s3f::s3fnet::DroptailQueue::calibrate(), s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::DummySession::init(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), and s3f::s3fnet::NetworkInterface::receivePacket().
 { return sess_rng;}
ltime_t s3f::s3fnet::ProtocolSession::getNow () inherited
The method returns the current simulation time.
To be safe, please do NOT call this function after initialization and before wrapup phase. That is, it is unsafe to call this method in the constructor, destructor, config, init, and wrapup methods. The time service is carried out by the host's owner community. This method just directs the call to the community. It's given here for convenience.
Definition at line 123 of file protocol_session.cc.
References s3f::s3fnet::ProtocolSession::inHost(), and Entity::now().
Referenced by s3f::s3fnet::DroptailQueue::calibrate(), s3f::s3fnet::RedQueue::calibrate(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::TCPMaster::enableFastTimeout(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::TCPMaster::fast_timer_callback_body(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::TCPSession::now(), s3f::s3fnet::OpenVZEventSession::pop(), s3f::s3fnet::TCPMaster::slow_timer_callback_body(), socket(), s3f::s3fnet::NBSocketMaster::socket(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), and s3f::s3fnet::BTCPClientSession::start_on().
 {
   return inHost()->now();
 }
char * s3f::s3fnet::ProtocolSession::getNowWithThousandSeparator () inherited
For printing the current simulation time in a better readable format.
Definition at line 128 of file protocol_session.cc.
References s3f::s3fnet::Host::getNowWithThousandSeparator(), and s3f::s3fnet::ProtocolSession::inHost().
Referenced by s3f::s3fnet::UDPSession::abort(), s3f::s3fnet::DummySession::callback_body(), s3f::s3fnet::OpenVZEventSession::callback_body(), s3f::s3fnet::UDPSession::clear_app_state(), s3f::s3fnet::UDPSession::connect(), s3f::s3fnet::TCPMaster::createSession(), s3f::s3fnet::UDPClientSession::data_received(), s3f::s3fnet::TCPClientSession::data_received(), s3f::s3fnet::BTCPClientSession::data_received(), s3f::s3fnet::UDPServerSession::data_sent(), s3f::s3fnet::TCPServerSession::data_sent(), s3f::s3fnet::UDPSession::disconnect(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::IPSession::handle_pop_local_pkt(), s3f::s3fnet::IPSession::handle_pop_pkt(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::UDPSession::listen(), s3f::s3fnet::UDPClientSession::main_proc(), s3f::s3fnet::TCPClientSession::main_proc(), s3f::s3fnet::BTCPClientSession::main_proc(), s3f::s3fnet::DummySession::pop(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::OpenVZEventSession::pop(), s3f::s3fnet::UDPMaster::pop(), s3f::s3fnet::TCPMaster::pop(), s3f::s3fnet::IPSession::pop(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::UDPMaster::push(), s3f::s3fnet::SimplePhy::push(), s3f::s3fnet::TCPMaster::push(), s3f::s3fnet::IPSession::push(), s3f::s3fnet::UDPSession::receive(), s3f::s3fnet::TCPSession::receive(), s3f::s3fnet::SimplePhy::receivePacket(), s3f::s3fnet::UDPServerSession::request_received(), s3f::s3fnet::TCPServerSession::request_received(), s3f::s3fnet::UDPClientSession::request_sent(), s3f::s3fnet::TCPClientSession::request_sent(), s3f::s3fnet::UDPSession::send(), s3f::s3fnet::TCPSession::send_data(), s3f::s3fnet::SimplePhy::sendPacket(), s3f::s3fnet::UDPClientSession::server_connected(), s3f::s3fnet::TCPClientSession::server_connected(), s3f::s3fnet::BTCPClientSession::server_connected(), s3f::s3fnet::UDPServerSession::session_closed(), s3f::s3fnet::UDPClientSession::session_closed(), s3f::s3fnet::TCPClientSession::session_closed(), s3f::s3fnet::TCPServerSession::session_closed(), s3f::s3fnet::BTCPClientSession::session_closed(), s3f::s3fnet::TCPMaster::setConnected(), s3f::s3fnet::TCPMaster::setIdle(), s3f::s3fnet::TCPMaster::setListening(), s3f::s3fnet::UDPSession::setSource(), s3f::s3fnet::TCPSession::slowTimeoutHandling(), s3f::s3fnet::UDPServerSession::start_on(), s3f::s3fnet::UDPClientSession::start_on(), s3f::s3fnet::TCPServerSession::start_on(), s3f::s3fnet::TCPClientSession::start_on(), s3f::s3fnet::BTCPClientSession::start_on(), s3f::s3fnet::TCPSession::TCPSession(), s3f::s3fnet::UDPClientSession::timeout(), s3f::s3fnet::TCPClientSession::timeout(), s3f::s3fnet::BTCPClientSession::timeout(), s3f::s3fnet::UDPSession::UDPSession(), s3f::s3fnet::TCPSession::update_timeout(), and s3f::s3fnet::UDPSession::wake_app().
 {
         return inHost()->getNowWithThousandSeparator();
 }
int s3f::s3fnet::ProtocolSession::configured () inline inherited
This method returns true if the protocol session has been configured.
This method is used to make sure we configure the protocol session before initializing it.
Definition at line 221 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_CONFIGURED, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::config(), and s3f::s3fnet::ProtocolSession::init().
 { return stage >= PSESS_CONFIGURED; }
int s3f::s3fnet::ProtocolSession::initialized () inline inherited
This method returns true if the protocol session has been initialized.
This can be used to sequence calls to the init method of protocol sessions. For example, if protocol session A requires protocol session B to be initialized before A can be initialized, A's init method can call B's init method as long as B's initialized() returns true. The system does not enforce any ordering in its calls the init methods of all protocol sessions declared in the dml configuration.
Definition at line 233 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_INITIALIZED, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::init(), and s3f::s3fnet::ProtocolSession::wrapup().
 { return stage >= PSESS_INITIALIZED; }
int s3f::s3fnet::ProtocolSession::wrapped_up () inline inherited
This method returns true if the protocol session has been wrapped up.
This can be used to sequence calls to the wrapup method of protocol sessions. For example, if protocol session A requires protocol session B to be wrapped up before A can be wrapped up, A's wrapup method can call B's wrapup method as long as B's wrapped_up() returns true. The system does not enforce any ordering in its calls the wrapup methods of all protocol sessions declared in the dml configuration.
Definition at line 245 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PSESS_WRAPPED_UP, and s3f::s3fnet::ProtocolSession::stage.
Referenced by s3f::s3fnet::ProtocolSession::wrapup().
 { return stage >= PSESS_WRAPPED_UP; }
virtual int s3f::s3fnet::ProtocolSession::instantiation_type () inline protected virtual inherited
This method controls how protocol instances can coexist with one another.
It returns one of the following:
PROT_UNIQUE_INSTANCE (default): allows only one instance for each type of protocol per protocol stack;
PROT_MULTIPLE_INSTANCES: allows multiple instances of the same implementation for each type of protocol per protocol stack;
PROT_MULTIPLE_IMPLEMENTATIONS: allows multiple instances from different implementations of the same protocol to exist on the protocol stack.
Reimplemented in s3f::s3fnet::BTCPClientSession, and s3f::s3fnet::TCPClientSession.
Definition at line 269 of file protocol_session.h.
References s3f::s3fnet::ProtocolSession::PROT_UNIQUE_INSTANCE.
Referenced by s3f::s3fnet::ProtocolGraph::insert_session().
 { return PROT_UNIQUE_INSTANCE; }
Member Data Documentation
int s3f::s3fnet::SocketMaster::new_sockid protected
The next available socket id.
Definition at line 276 of file socket_master.h.
Referenced by socket().
SOCK_MAP s3f::s3fnet::SocketMaster::bound_socks protected
A map from a socket id to a bound socket.
Definition at line 282 of file socket_master.h.
Referenced by abort(), accept(), accept1a(), accept1b(), accept2a(), accept2b(), bind(), block_till(), close(), close1(), connect(), connect1(), connected(), control(), eof(), listen(), recv(), recv1(), send(), send1(), socket(), and ~SocketMaster().
SOCK_SET s3f::s3fnet::SocketMaster::unbound_socks protected
A set of unbound socket ids.
Definition at line 285 of file socket_master.h.
Referenced by accept2a(), bind(), and socket().
char* s3f::s3fnet::ProtocolSession::name inherited
Symbolic name of the protocol this session implements.
The name of the protocol is derived from the DML 'name' attribute. It must not be NULL once the protocol session is configured.
Definition at line 63 of file protocol_session.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::SimpleMac::init(), s3f::s3fnet::UDPMaster::init(), s3f::s3fnet::SimplePhy::init(), s3f::s3fnet::TCPMaster::init(), init(), s3f::s3fnet::IPSession::init(), s3f::s3fnet::NBSocketMaster::init(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::ProtocolGraph::insert_session(), s3f::s3fnet::ProtocolSession::wrapup(), and s3f::s3fnet::ProtocolSession::~ProtocolSession().
float s3f::s3fnet::ProtocolSession::version inherited
Version number of this protocol implemenntation, represented as a floating point number (e.g., 1.23).
Definition at line 69 of file protocol_session.h.
char* s3f::s3fnet::ProtocolSession::use inherited
Name of the protocol class from which this protocol session is instantiated.
The protocol class must be registered with the Protocols class so that we will be able to instantiate an object from the class. (C++ does not support self-reflection). The class name must not be NULL once the protocol session is configured.
Definition at line 79 of file protocol_session.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::ProtocolGraph::insert_session(), and s3f::s3fnet::ProtocolSession::~ProtocolSession().
ProtocolGraph* s3f::s3fnet::ProtocolSession::ingraph protected inherited
Points to the protocol graph.
Definition at line 335 of file protocol_session.h.
Referenced by s3f::s3fnet::NicProtocolSession::getNetworkInterface(), s3f::s3fnet::ProtocolSession::inGraph(), and s3f::s3fnet::ProtocolSession::inHost().
Random::RNG* s3f::s3fnet::ProtocolSession::sess_rng protected inherited
Pointer to a random number generator.
Definition at line 338 of file protocol_session.h.
Referenced by s3f::s3fnet::ProtocolSession::getRandom(), and s3f::s3fnet::ProtocolSession::init().
int s3f::s3fnet::ProtocolSession::stage protected inherited
This variable indicates the current stage of this protocol session.
Each protocol session will go through four staged: PSESS_CREATED, PSESS_CONFIGURED, PSESS_INITIALIZED, and then PSESS_WRAPPED_UP.
Definition at line 346 of file protocol_session.h.
Referenced by s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::ProtocolSession::configured(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::ProtocolSession::initialized(), s3f::s3fnet::ProtocolSession::wrapped_up(), and s3f::s3fnet::ProtocolSession::wrapup().
The documentation for this class was generated from the following files:
socket_master.h
socket_master.cc