S3F: s3f::s3fnet::trie4::Trie4 Class Reference
s3f::s3fnet::trie4::Trie4 Class Reference
A data structure for forwarding tables.
#include <trie4.h>
Classes
class iterator
Public Types
enum TrieType {
ORIGINAL = 0, SIMPLE = 1, PREFIX = 2, UNORDERED_PREFIX = 3,
ARRAY_BACKED = 4, ARRAY_BACKED_PREFIX = 5, ARRAY_BACKED_UNORDERED_PREFIX = 6
}
Enum containing Trie implementations.
Public Member Functions
Trie4 (int array_version=-1)
The constructor.
virtual ~Trie4 ()
The destructor.
virtual TrieData * insert (TRIEBITSTRING key, int nBits, TrieData *data, bool replace)
Inserts a new (key, data) pair.
virtual TrieData * remove (TRIEBITSTRING key, int nBits)
Removes a key from the Trie.
virtual TrieData * lookup (TRIEBITSTRING key)
Finds a key in the Trie.
virtual TrieData * getDefault ()
Get the default Route.
virtual int size ()
Return the number of items in the trie.
iterator begin ()
iterator & end ()
Public Attributes
iterator last
Last item in iterator.
Protected Member Functions
TrieNode * search (TRIEBITSTRING key, int len, TrieNode **failedNode, int *failedbitpos)
Helper function for the insert and lookup methods.
void create (TrieNode *theroot, TRIEBITSTRING key, int nBits, TrieData *data)
Creates a node from the root.
Static Protected Member Functions
static void deallocate (TrieNode *theroot)
Deallocate the trie recursively.
Protected Attributes
TrieNode * root
The root of the trie.
int nElements
Number of data elements stored in the trie.
TrieDataArray * mData
Data array that nodes index into.
Detailed Description
A data structure for forwarding tables.
This class directly extends Trie1 adding coalescing of duplicate RouteInfo structs into an array. The index into the array (vs the actual pointer) is now stored in the Trie nodes. This class is intended primarily for testing purposes as the neccessity of a base-class pointer-cast to TrieDataArray adds at least one extra unnecessary memory access.
NOTE: If CIDR addresses are used, they must be ordered from longest mask lengths to shortest to prevent DUPLICATE_ROUTE replacement. Example order: ip1, ip2/31, ..., ip100/16, ..., ip1000/1 CIDR addresses are also only guaranteed to work for static routing.
Definition at line 49 of file trie4.h.
Member Enumeration Documentation
enum s3f::s3fnet::Trie::TrieType inherited
Enum containing Trie implementations.
Enumerator
ORIGINAL
Very first s3fnet Trie implementation.
SIMPLE
Identical to ORIGINAL with minor fixes/enhancements.
PREFIX
Stores values at minimum depth instead of depth equal to their bit-length (ie depth 32 for an ipv4 address).
UNORDERED_PREFIX
Like PREFIX but can take CIDR-format IP address as input in any order.
ARRAY_BACKED
Trie that stores indices into an array in its nodes (vs data IN the nodes).
ARRAY_BACKED_PREFIX
ARRAY_BACKED_UNORDERED_PREFIX
PREFIX with array-backing (ARRAY_BACKED).
Definition at line 112 of file trie.h.
                       {
                 ORIGINAL = 0,
                 SIMPLE = 1,
                 PREFIX = 2,
                 UNORDERED_PREFIX = 3,
                 ARRAY_BACKED = 4,
                 ARRAY_BACKED_PREFIX = 5,
                 ARRAY_BACKED_UNORDERED_PREFIX = 6
         };
Constructor & Destructor Documentation
s3f::s3fnet::trie4::Trie4::Trie4 (int array_version = -1)
The constructor.
Definition at line 65 of file trie4.cc.
References DEFAULT_ARRAY_VERSION, mData, s3f::s3fnet::TrieDataArray::NAIVE, root, s3f::s3fnet::TrieDataArray::UNCOALESCED, and s3f::s3fnet::TrieDataArray::UNCOALESCED_MAP.
                               : nElements(0), last(this) {
         root = new TrieNode();
         assert(root);
         if(array_version == -1) {
                 array_version = DEFAULT_ARRAY_VERSION;
         }
   // TODO: Make TrieDataArray configurable via dml (based on version)
   avstart:
         switch(array_version) {
         case TrieDataArray::UNCOALESCED:
                 mData = (TrieDataArray*)new tda0::TrieDataArray0();
                 break;
         case TrieDataArray::UNCOALESCED_MAP:
                 mData = (TrieDataArray*)new tda1::TrieDataArray1();
                 break;
         case TrieDataArray::NAIVE:
                 mData = (TrieDataArray*)new tda2::TrieDataArray2();
                 break;
         default:
                 fprintf(stderr, "Invalid TrieDataArray version (%d). Using default (%d).",array_version,
                                 DEFAULT_ARRAY_VERSION);
                 array_version = DEFAULT_ARRAY_VERSION;
                 goto avstart;
         }
         assert(mData);
 }
s3f::s3fnet::trie4::Trie4::~Trie4 () virtual
The destructor.
Definition at line 96 of file trie4.cc.
References deallocate(), mData, nElements, and root.
 {
   deallocate(root);
   delete mData;
   nElements = 0;
 }
Member Function Documentation
TrieData * s3f::s3fnet::trie4::Trie4::insert (TRIEBITSTRING key, int nBits, TrieData * data, bool replace) virtual
Inserts a new (key, data) pair.
Adds a new (key, data) pair to the Trie. If the key already exists, and if the replace flag is set, we will replace the old data with the new one and return the old data. If the replace flag is not set, the old data remains in the trie and the new data is returned. If the key does not exist in trie, the data will be inserted and the return value is 0.
Parameters
key the key to insert
nBits bits of the key to consider (useful for CIDR)
data the TrieData object to add
replace whether to replace an existing value with the same key
Returns
NULL on success, otherwise the TrieData object we attempted to insert (so reference is not lost)
Implements s3f::s3fnet::Trie.
Definition at line 106 of file trie4.cc.
References s3f::s3fnet::TrieDataArray::addElement(), create(), s3f::s3fnet::trie4::TrieNode::index, mData, nElements, REMOVE, s3f::s3fnet::TrieDataArray::removeElement(), and search().
{
   TrieNode *fail = 0;
   int bitpos = 0;
   TrieNode* match = search(key, nBits, &fail, &bitpos);
   // Does the key already exist in our trie?
   // If so, replace the data if replace flag is true.
   if(match) {
     if(!replace) return data;
     TrieData* temp = mData->removeElement(match->index,true);
     match->index = mData->addElement(data);
     return temp;
   }
   // Create all the necessary nodes for the unmatched bits
   // after fail and insert the data.
   create(fail, REMOVE(bitpos, key), nBits-bitpos, data);
   nElements++;
   return 0;
 }
TrieData * s3f::s3fnet::trie4::Trie4::remove (TRIEBITSTRING key, int nBits) virtual
Removes a key from the Trie.
Remove the key from the trie, if it exists, and returns the data corresponding to the removed key. If the key is not in the trie, return NULL.
Parameters
key the key to remove
nBits bits of the key to consider
Returns
the data correspoding to the key on success, otherwise NULL
Implements s3f::s3fnet::Trie.
Definition at line 166 of file trie4.cc.
References s3f::s3fnet::trie4::TrieNode::children, s3f::s3fnet::trie4::TrieNode::index, mData, nElements, s3f::s3fnet::TrieDataArray::removeElement(), and search().
{
   TrieNode* ptr;
   TrieData* olddata;
   TrieNode* parent;
   int index;
   ptr = search(key, nBits, &parent, &index);
   if(!ptr) return 0;
   olddata = mData->removeElement(ptr->index,true);
   ptr->index = UINT_MAX;
   nElements--;
   if(ptr->children[0] == 0 && ptr->children[1] == 0) {
         delete parent->children[index];
         parent->children[index] = 0;
   }
   return olddata;
 }
TrieData * s3f::s3fnet::trie4::Trie4::lookup (TRIEBITSTRING key) virtual
Finds a key in the Trie.
Perform a longest-matching prefix search for the key and if found, places the data in pData. Otherwise, pData is NULL.
Parameters
key the key to lookup
Returns
the data matching the key on success, otherwise NULL
Implements s3f::s3fnet::Trie.
Definition at line 139 of file trie4.cc.
References s3f::s3fnet::trie4::TrieNode::children, s3f::s3fnet::TrieDataArray::getElement(), s3f::s3fnet::trie4::TrieNode::index, mData, root, and s3f::s3fnet::trie4::TRIE_BIT_MASK.
 {
   // If this Trie exists to call 'lookup', root has already been asserted as non-null
   TrieNode* cur = root->children[(key & TRIE_BIT_MASK)?1:0];
   TrieData* pData;
   if(root->index != UINT_MAX) {
         pData = mData->getElement(root->index); // handles default-route case
   } else {
         pData = 0;
   }
   while(cur) {
     if(cur->index != UINT_MAX) {
                 pData = mData->getElement(cur->index);
         }
         key <<= 1;
     cur = cur->children[(key & TRIE_BIT_MASK)?1:0];
   }
   return pData;
 }
TrieData * s3f::s3fnet::trie4::Trie4::getDefault () virtual
Get the default Route.
Returns
an instance of the default route as a TrieData object
Implements s3f::s3fnet::Trie.
Definition at line 186 of file trie4.cc.
References s3f::s3fnet::TrieDataArray::getElement(), s3f::s3fnet::trie4::TrieNode::index, mData, and root.
{
         if(root) return mData->getElement(root->index);
         return 0;
 }
virtual int s3f::s3fnet::trie4::Trie4::size () inline virtual
Return the number of items in the trie.
Returns
the size of the Trie (generally the number of elements contained)
Implements s3f::s3fnet::Trie.
Definition at line 104 of file trie4.h.
References nElements.
 { return nElements; }
TrieNode * s3f::s3fnet::trie4::Trie4::search (TRIEBITSTRING key, int len, TrieNode ** failedNode, int * failedbitpos) protected
Helper function for the insert and lookup methods.
This function will search the trie for the key and if found, return a pointer to the TrieNode. If not found, it will return NULL, and set failedNode to the TrieNode where the search fails and failedbitpos to the bit position that failed.
Parameters
key the key for insert/lookup
len the bits to consider of the key
failedNode a TrieNode reference address to write the address of the last node traversed before failure
failedbitpos an integer address to write the bit position of the last traversal before failure
Returns
the TrieNode found, NULL otherwise
Definition at line 199 of file trie4.cc.
References s3f::s3fnet::trie4::TrieNode::children, GETBIT, s3f::s3fnet::trie4::TrieNode::index, root, and TRIE_KEY_SIZE.
Referenced by insert(), and remove().
 {
   // TODO: Optimize this function
   TrieNode* cur, *lastcur, *parent;
   TrieNode* match = 0;
   int bitpos, curbit, parentbit;
   if(len > TRIE_KEY_SIZE(key)) {
         len = TRIE_KEY_SIZE(key);
   }
   // Go through the bits starting from the MSB and traverse
   // the tree. Remember the last match.
   for(bitpos = 0, lastcur = cur = root;
       cur && bitpos < len;
       cur = cur->children[curbit], bitpos++) {
     if(cur->index != UINT_MAX) {
                 parent = lastcur;
                 parentbit = GETBIT(bitpos-1,key);
                 match = cur;
         }
     lastcur = cur;
     curbit = GETBIT(bitpos, key);
   }
   if(cur && cur->index != UINT_MAX) {
         match = cur;
         if(failedNode && failedbitpos) {
                 // we have a match on the last node, parent is lastcur
                 *failedNode = lastcur;
                 *failedbitpos = GETBIT(bitpos-1,key);
         }
   } else if(failedNode && failedbitpos) {
         // if there is a match
         if(match) {
                 *failedNode = parent;
                 *failedbitpos = parentbit;
         } else { // no match
                 if(cur) {
                   *failedbitpos = bitpos;
                   *failedNode = cur;
                 } else {
                   *failedbitpos = bitpos - 1;
                   *failedNode = lastcur;
                 }
         }
   }
   return match;
 }
void s3f::s3fnet::trie4::Trie4::create (TrieNode * theroot, TRIEBITSTRING key, int nBits, TrieData * data) protected
Creates a node from the root.
Static helper function for the insert method. Creates nBits nodes for the key starting at TrieNode theroot.
Parameters
theroot the root entry to start from
key the key to create a node for
nBits the bits to consider
data the data to store
Definition at line 256 of file trie4.cc.
References s3f::s3fnet::TrieDataArray::addElement(), s3f::s3fnet::trie4::TrieNode::children, GETBIT, and mData.
Referenced by insert().
 {
   TrieNode* ptr;
   for(int i=0; i < nBits; i++, theroot = ptr) {
         assert(theroot->children[GETBIT(i, key)] == 0);
     ptr = theroot->children[GETBIT(i, key)] = new TrieNode();
     assert(ptr);
   }
   theroot->index = mData->addElement(data);
 }
void s3f::s3fnet::trie4::Trie4::deallocate (TrieNode * theroot) static protected
Deallocate the trie recursively.
Parameters
theroot the root entry of the Trie to free
Definition at line 272 of file trie4.cc.
References s3f::s3fnet::trie4::TrieNode::children, and s3f::s3fnet::trie4::TRIE_KEY_SPAN.
Referenced by ~Trie4().
 {
   if(theroot == 0) return;
   // deallocate all the children
   for(int i = 0; i < TRIE_KEY_SPAN; i++)
     deallocate(theroot->children[i]);
   delete theroot;
 }
Trie4::iterator s3f::s3fnet::trie4::Trie4::begin ()
Definition at line 447 of file trie4.cc.
{
   iterator first(this); // create iterator
   ++first; // find first element
   return first; // return by copy
 }
iterator& s3f::s3fnet::trie4::Trie4::end () inline
Definition at line 297 of file trie4.h.
References last.
 { return last; }
Member Data Documentation
TrieNode* s3f::s3fnet::trie4::Trie4::root protected
The root of the trie.
Definition at line 141 of file trie4.h.
Referenced by getDefault(), lookup(), search(), Trie4(), and ~Trie4().
int s3f::s3fnet::trie4::Trie4::nElements protected
Number of data elements stored in the trie.
Definition at line 144 of file trie4.h.
Referenced by insert(), remove(), size(), and ~Trie4().
TrieDataArray* s3f::s3fnet::trie4::Trie4::mData protected
Data array that nodes index into.
Base class is located in trie.h but this will store a derived class.
Definition at line 150 of file trie4.h.
Referenced by create(), getDefault(), insert(), lookup(), remove(), Trie4(), and ~Trie4().
iterator s3f::s3fnet::trie4::Trie4::last
Last item in iterator.
Definition at line 286 of file trie4.h.
Referenced by end().
The documentation for this class was generated from the following files:
trie4.h
trie4.cc