S3F: interface.cc File Reference
interface.cc File Reference
S3F Interface class methods.
#include <s3f.h>
Functions
unsigned long get_wall_time ()
Wall time clock is in microseconds.
void * proxy_function (void *timeline_ptr)
Detailed Description
S3F Interface class methods.
authors : David Nicol, Dong (Kevin) Jin
Definition in file interface.cc.
Function Documentation
unsigned long get_wall_time ()
Wall time clock is in microseconds.
It's the best precision we can get from gettimeofday function.
Definition at line 29 of file interface.cc.
Referenced by Interface::advance_body(), and Interface::Interface().
 {
         struct timeval tv;
         gettimeofday(&tv, 0);
         return (unsigned long)(tv.tv_sec*1e6+tv.tv_usec);
 }
void* proxy_function (void * timeline_ptr)
Definition at line 37 of file interface.cc.
Referenced by Interface::Interface().
{
         return static_cast<Timeline *>(timeline_ptr)->thread_function();
 }