S3F: s3f::s3fnet Namespace Reference
s3f::s3fnet Namespace Reference
Network Simulator developed based on the S3F Scalable Simulation Framework.
Namespaces
routecache0
routecache1
routecache2
trie0
trie1
trie2
trie3
trie4
tda0
tda1
tda2
Classes
class NameService
Global name resolution service.
class CidrBlock
A block of IP addresses.
class DmlObject
An abstract base class for all DML identifiable objects.
class DroptailQueue
A FIFO queue used inside a network interface.
class RouteInfo
A route entry of a forwarding table.
class DMLRouteInfo
ROUTE and NHI_ROUTE attributes from DML.
class RouteCache
Base class for any routing caches.
class ForwardingTable
The forwarding table.
class Host
A host or router or switch.
class IPPrefix
IP prefix, such as 10.10.0.0/16.
class Link
A link that connects interfaces.
class Mac48Address
MAC address (48 bit IEEE addresses)
struct sniff_ethernet
Ethernet header.
struct sniff_ip
IP header.
struct sniff_arp
ARP header.
struct sniff_tcp
TCP header.
struct sniff_udp
UDP header.
class Net
A network.
class NetAccessory
Extra options associated with a net.
class NetworkInterface
A network interface.
class Nhi
The NHI address used in DML.
class NicQueue
A base class for implementation of queues in an NIC.
class NicQueues
A list of NIC queues.
class RedQueue
A simple RED queue used inside a network interface.
class Traffic
Specification of traffic in DML.
class TrafficPattern
A traffic pattern in the traffic specification.
class TrafficServerData
Contain information about a server.
class DataChunk
List of data chunks to be carried by a protocol message.
class DataMessage
A generic protocol message carrying a payload as a continuous byte stream or a list of data chunks.
class LowestProtocolSession
The lowest protocol session in the protocol stack.
class NicProtocolSession
A protocol session in the protocol stack of a network interface.
class MACOptionToAbove
The auxiliary object pop up together with the packet from MAC layer to upper layer.
class PHYOptionToAbove
The auxiliary object pop up together with the packet from PHY layer to upper layer.
class ProtocolGraph
A stack of protocol sessions.
class ProtocolMessage
Protocol message through the protocol stack.
class ProtocolSession
A protocol layer on the protocol stack.
class ProtocolCallbackActivation
Storing data for the waitFor()'s callback function in a protocol session.
class Protocols
Managing protocols.
class DummyMessage
Message for the dummy protocol (sending hello message to the specific destination).
class DummySession
A dummy protocol session, sending hello messages to specified peers.
class IPPushOption
Parameters for protocol messages pushing down to IP.
class IPOptionToBelow
Parameters for IP messages pushing down.
class IPOptionToAbove
Parameters for IP messages popping up.
class IPPushRequest
Push request received from lower layers.
class IPMessage
IP header.
class IPSession
The Internet protocol session.
class Controller
An interface for a non-entity-based OpenFlow controller.
class DropController
A controller that builds a flow for each received packet to drop all packets it matches (this demonstrates the flow table's basic implementation).
class LearningController
Demonstration of a Learning controller.
class OpenFlowControllerSession
An interface for an entity-based OpenFlow controller.
class LearningControllerSession
Demonstration of a Learning controller.
struct Port
Port and its metadata.
class Stats
struct Action
Class for handling flow table actions.
struct VPortAction
Class for handling virtual port table actions.
struct EricssonAction
Class for handling Ericsson Vendor-defined actions.
struct StatsDumpCallback
Callback for a stats dump request.
struct SwitchPacketMetadata
Packet Metadata, allows us to track the packet's metadata as it passes through the switch.
class OpenFlowMessage
Message between OpenFlow controller and OpenFlow switch, for both directions.
class OpenFlowSwitchSession
An OpenFlow switch that switches multiple LAN segments via an OpenFlow-compatible flow table.
class OpenVZEventSession
A protocol layer to interact with the associated OpenVZ-based VE.
class OpenVZEventSessionCallbackActivation
Storing the data for the callback function.
class OpenVZMessage
Protocol message for the OpenVZEventSession.
class SimpleMac
A simple MAC layer protocol.
class SimpleMacMessage
Protocol message for the simple MAC layer.
class SimplePhy
A simple PHY layer protocol.
class NBSocketContinuation
Continuation used by the non-blocking socket interface.
class NBSocketMaster
The socket master protocol session.
class BSocketContinuation
Continuation used by the non-blocking socket interface.
class SocketMaster
The socket master protocol session.
class SocketContinuation
Continuation used by the socket interface.
class SessionID
An application session.
struct SessionCmp
A structure used to compare two session ids. Returns true is sess_1 is less than sess_2.
class SocketSession
The socket session.
class SocketSignal
Signals to and from a socket.
class Socket
The socket information.
class SessionMaster
Base class for protocol session masters.
class BTCPClientSessionContinuation
class BTCPClientSession
The super-lightweight TCP client test protocol session.
class BTCPClientSessionCallbackActivation
Class to start client actions at the correct time(s)
class NBTCPClientSessionContinuation
class NBTCPClientSession
class NBTCPClientSessionCallbackActivation
Class to start client actions at the correct time(s)
class NBTCPServerSessionContinuation
class FileSender
Class to send a file Sends a file to multiple potential receivers in a non-blocking fashion, iterating over each open connection and sending some bytes on each pass (usually triggered by callback from the continuation).
class NBTCPServerSession
class NBTCPServerSessionCallbackActivation
Class to start server actions at the correct time(s)
class TCPClientSessionContinuation
The continuation used in TCP client.
class TCPClientSession
The TCP client test protocol session.
class TCPClientSessionCallbackActivation
Stores the data for the callback function.
class TCPServerSessionContinuation
The continuation used in tcp server.
class TCPServerSession
The TCP server test protocol session.
class TCPServerSessionCallbackActivation
Stores the data for the callback function.
class TCPBlock
A consecutive block of sequence numbers.
class TCPBlockList
A list of blocks of consecutive sequence numbers.
class TCPMaster
The TCP master.
class TCPMessage
TCP header.
class TCPSegment
A TCP segment received by the TCP receiver.
class TCPRecvWindow
The sliding window for TCP receiver.
class TCPSeqWindow
Implements the sliding window in TCP.
class TCPSession
The TCP session.
class TCPSendWindow
The sliding window for TCP sender.
class UDPClientSessionContinuation
The continuation used in UDP client.
class UDPClientSession
The UDP client test protocol session.
class UDPClientSessionCallbackActivation
Storing the data for the callback function this case, the UDPClientSession object and the UDPClientSessionContinuation object are stored.
class UDPServerSessionContinuation
The continuation used in UDP server.
class UDPServerSession
The UDP server test protocol session.
class UDPServerSessionCallbackActivation
storing the data for the callback function this case, the UDPServerSession object and the UDPServerSessionContinuation object are stored.
class UDPMaster
The UDP master.
class UDPMessage
UDP header.
class UDPSession
The UDP session.
class SimInterface
The S3FNet simulation interface class.
class TrieData
A generic data type for data stored in trie.
class Trie
Base class for Trie implementations.
class TrieDataArray
Abstract base class for storing coalesced TrieData sets.
Typedefs
typedef unsigned int IPADDR
IP address should be a 32-bit unsigned integer.
typedef char int8
8-bit character type
typedef unsigned char uint8
8-bit unsigned character type
typedef unsigned char byte
8-bit unsigned character type
typedef short int16
16-bit integer type (short)
typedef unsigned short uint16
16-bit unsigned integer type (unsigned short)
typedef int int32
32-bit integer type
typedef unsigned int uint32
32-bit unsigned integer type
typedef long long int int64
64-bit integer type
typedef unsigned long long int uint64
64-bit unsigned integer type
typedef unsigned int word
typedef void general_data
typedef unsigned long ulong
typedef unsigned int uint
typedef uint64 MACADDR
For convenience, we use a 64-bit unsigned long integer to denote the MAC address and use simple type casting to mimic the function of ARP.
typedef void(* ErrorHandler)(int syserr, const char *msg, va_list ap)
An error handler is a function that consists of three arguments: the first indicates whether the error is caused by a system call or not, the second argument is the format string (like the one in printf), and the last one is an argument list for the format string.
typedef string S3FNET_STRING
std::string in shared memory.
typedef pair< int, int > S3FNET_INT_PAIR
A pair of integers.
typedef uint32 TRIEBITSTRING
The key type for the trie.
Enumerations
enum { IPADDR_NEXTHOP_IGNORED = 0xFFFFFFFF, IPADDR_NEXTHOP_UNSPECIFIED = 0xFFFFFFFE, IPADDR_INADDR_ANY = 0xFFFFFFFF }
Reserved IP addresses for internal use.
enum {
NET_ACCESSORY_IS_AS_BOUNDARY = 1, NET_ACCESSORY_AS_NUMBER = 2, NET_ACCESSORY_AREA_NUMBER = 3, NET_ACCESSORY_TRAFFIC = 4,
NET_ACCESSORY_QUEUE_MONITORS = 5, NET_ACCESSORY_UNSPECIFIED = 1000
}
only TRAFFIC is in use
enum {
NET_CTRL_IS_AS_BOUNDARY = 1, NET_CTRL_GET_AS_NUMBER = 2, NET_CTRL_GET_AREA_NUMBER = 3, NET_CTRL_GET_TRAFFIC = 4,
NET_CTRL_GET_QUEUE_MONITORS = 5, AS_NUMBER_UNSPECIFIED = -1, AREA_NUMBER_UNSPECIFIED = 0
}
control message and types and responses
enum NicQueueCtrlCmd { NIC_QUEUE_ROUTE_DOWN = 0 }
The control command types for the NIC queue.
enum OPENFLOW_CONTROLLER_MODEL { NO_OF_CONTROLLER = 0, OF_LEARNING_SWITCH_CONTROLLER = 1, OF_DROP_CONTROLLER = 2, OF_LEARNING_SWITCH_CONTROLLER_ENTITY = 3 }
Model of OpenFlow controller.
enum S3FNetProtocolType {
S3FNET_PROTOCOL_TYPE_INVALID = 0, S3FNET_PROTOCOL_TYPE_ICMP = 1, S3FNET_PROTOCOL_TYPE_IPV4 = 4, S3FNET_PROTOCOL_TYPE_TCP = 6,
S3FNET_PROTOCOL_TYPE_UDP = 17, S3FNET_PROTOCOL_TYPE_OSPF = 89, S3FNET_PROTOCOL_TYPE_SOCKET = 200, S3FNET_PROTOCOL_TYPE_SIMPLE_PHY = 201,
S3FNET_PROTOCOL_TYPE_SIMPLE_MAC = 202, S3FNET_PROTOCOL_TYPE_OPAQUE_DATA = 203, S3FNET_PROTOCOL_TYPE_TCPTEST_CLIENT = 221, S3FNET_PROTOCOL_TYPE_TCPTEST_SERVER = 222,
S3FNET_PROTOCOL_TYPE_TCPTEST_BLOCKING_CLIENT = 223, S3FNET_PROTOCOL_TYPE_TCPTEST_BLOCKING_SERVER = 224, S3FNET_PROTOCOL_TYPE_TCPTEST_NON_BLOCKING_CLIENT = 225, S3FNET_PROTOCOL_TYPE_TCPTEST_NON_BLOCKING_SERVER = 226,
S3FNET_PROTOCOL_TYPE_UDPTEST_CLIENT = 227, S3FNET_PROTOCOL_TYPE_UDPTEST_SERVER = 228, S3FNET_PROTOCOL_TYPE_COMMAND = 238, S3FNET_PROTOCOL_TYPE_DUMMY = 254,
S3FNET_PROTOCOL_TYPE_OPENVZ_EVENT = 240, S3FNET_PROTOCOL_TYPE_OPENFLOW_SWITCH = 241, S3FNET_PROTOCOL_TYPE_OPENFLOW_CONTROLLER = 242
}
Protocol type (or protocol number) is used both by protocol sessions and protocol messages to uniquely identify different protocol layers.
enum ProtocolSessionCtrlTypes {
PSESS_CTRL_SESSION_IS_LOWEST = 1, PSESS_CTRL_SESSION_GET_INTERFACE = 2, PSESS_CTRL_SESSION_SET_PARENT = 3, PSESS_CTRL_SESSION_SET_CHILD = 4,
PHY_CTRL_GET_BITRATE = 21, PHY_CTRL_GET_BUFFER_SIZE = 22, PHY_CTRL_GET_LATENCY = 23, PHY_CTRL_GET_JITTER_RANGE = 24,
PHY_CTRL_GET_QUEUE = 25, IP_CTRL_VERIFY_TARGET_IP_ADDRESS = 40, IP_CTRL_VERIFY_LOCAL_IP_ADDRESS = 41, IP_CTRL_GET_FORWARDING_TABLE = 42,
IP_CTRL_LOAD_FORWARDING_TABLE = 43, IP_CTRL_INSERT_ROUTE = 44, IP_CTRL_DELETE_ROUTE = 45, IP_CTRL_INSERT_DMLROUTE = 46,
IP_CTRL_ADD_INTERCEPT_SESSION = 47, IP_CTRL_PUSH_REQUEST = 48, IP_CTRL_ADD_FIB_LISTENER = 49, IP_CTRL_FIB_ADDROUTE = 50,
IP_CTRL_FIB_DELROUTE = 51, UDP_CTRL_GET_MAX_DATAGRAM_SIZE = 71, SOCK_CTRL_CLEAR_SIGNAL = 81, SOCK_CTRL_SET_SIGNAL = 82,
SOCK_CTRL_DETACH_SESSION = 83, SOCK_CTRL_REINIT = 84, SOCK_CTRL_GET_APP_SESSION = 85, DUMMY_CTRL_COMMAND1 = 1512,
DUMMY_CTRL_COMMAND2 = 1513, OPENFLOW_SWITCH_CTRL_COMMAND1 = 200, OPENFLOW_SWITCH_CTRL_COMMAND2 = 201, OPENFLOW_CONTROLLER_CTRL_COMMAND1 = 202,
OPENFLOW_CONTROLLER_CTRL_COMMAND2 = 203
}
General control types.
Functions
S3FNET_REGISTER_QUEUE (DroptailQueue, DROPTAIL_QUEUE_NAME)
typedef S3FNET_SET (ProtocolSession *) S3FNET_FIB_PROTO_SET
typedef S3FNET_MAP (int, NetworkInterface *) S3FNET_HOST_IFACE_MAP
bool operator== (const IPPrefix &ip1, const IPPrefix &ip2)
static char AsciiToLowCase (char c)
std::ostream & operator<< (std::ostream &os, const Mac48Address &address)
std::ostream & operator<< (std::ostream &os, const Mac48Address *address)
static uint8_t AsInt (std::string v)
std::istream & operator>> (std::istream &is, Mac48Address &address)
std::istream & operator>> (std::istream &is, Mac48Address *address)
bool operator== (const Mac48Address &a, const Mac48Address &b)
bool operator!= (const Mac48Address &a, const Mac48Address &b)
bool operator< (const Mac48Address &a, const Mac48Address &b)
typedef S3FNET_VECTOR (IPADDR) S3FNET_IFACE_IPADDR_VECTOR
bool operator== (Nhi &n1, Nhi &n2)
S3FNET_REGISTER_QUEUE (RedQueue, RED_QUEUE_NAME)
typedef S3FNET_VECTOR (TrafficServerData *) TRAFFIC_SERVERDATA_VECTOR
S3FNET_REGISTER_MESSAGE (DataMessage, S3FNET_PROTOCOL_TYPE_OPAQUE_DATA)
typedef S3FNET_MAP (S3FNET_STRING, ProtocolSession *) S3FNET_GRAPH_PROTONAME_MAP
typedef S3FNET_MAP (int, ProtocolSession *) S3FNET_GRAPH_PROTONUM_MAP
typedef S3FNET_VECTOR (ProtocolSession *) S3FNET_GRAPH_PSESS_VECTOR
S3FNET_REGISTER_MESSAGE (DummyMessage, S3FNET_PROTOCOL_TYPE_DUMMY)
S3FNET_REGISTER_PROTOCOL (DummySession, DUMMY_PROTOCOL_CLASSNAME)
S3FNET_REGISTER_MESSAGE (IPMessage, S3FNET_PROTOCOL_TYPE_IPV4)
S3FNET_REGISTER_PROTOCOL (IPSession, IP_PROTOCOL_CLASSNAME)
S3FNET_REGISTER_PROTOCOL (OpenFlowControllerSession, OF_CONTROLLER_PROTOCOL_CLASSNAME)
S3FNET_REGISTER_PROTOCOL (LearningControllerSession, OF_CONTROLLER_LEARNING_SWITCH_PROTOCOL_CLASSNAME)
int Stats_FlowDumpCallback (sw_flow *flow, void *state)
int Stats_AggregateDumpCallback (sw_flow *flow, void *state)
void ExecuteActions (OpenFlowSwitchSession *swtch, uint64_t packet_uid, ofpbuf *buffer, sw_flow_key *key, const ofp_action_header *actions, size_t actions_len, int ignore_no_fwd)
Executes a list of flow table actions.
uint16_t ValidateActions (const sw_flow_key *key, const ofp_action_header *actions, size_t actions_len)
Validates a list of flow table actions.
void ExecuteVPortActions (OpenFlowSwitchSession *swtch, uint64_t packet_uid, ofpbuf *buffer, sw_flow_key *key, const ofp_action_header *actions, size_t actions_len)
Executes a list of virtual port table entry actions.
uint16_t ValidateVPortActions (const ofp_action_header *actions, size_t actions_len)
Validates a list of virtual port table entry actions.
void ExecuteVendor (ofpbuf *buffer, const sw_flow_key *key, const ofp_action_header *ah)
Executes a vendor-defined action.
uint16_t ValidateVendor (const sw_flow_key *key, const ofp_action_header *ah, uint16_t len)
Validates a vendor-defined action.
S3FNET_REGISTER_MESSAGE (OpenFlowMessage, S3FNET_PROTOCOL_TYPE_OPENFLOW_CONTROLLER)
S3FNET_REGISTER_PROTOCOL (OpenFlowSwitchSession, OF_SWITCH_PROTOCOL_CLASSNAME)
static uint64_t GenerateId ()
S3FNET_REGISTER_PROTOCOL (OpenVZEventSession, OPENVZ_EVENT_PROTOCOL_CLASSNAME)
S3FNET_REGISTER_MESSAGE (OpenVZMessage, S3FNET_PROTOCOL_TYPE_OPENVZ_EVENT)
S3FNET_REGISTER_PROTOCOL (SimpleMac, SIMPLE_MAC_PROTOCOL_CLASSNAME)
S3FNET_REGISTER_MESSAGE (SimpleMacMessage, S3FNET_PROTOCOL_TYPE_SIMPLE_MAC)
S3FNET_REGISTER_PROTOCOL (SimplePhy, SIMPLE_PHY_PROTOCOL_CLASSNAME)
S3FNET_REGISTER_PROTOCOL (NBSocketMaster,"S3F.OS.Socket.nbSocketMaster")
S3FNET_REGISTER_PROTOCOL (SocketMaster,"S3F.OS.Socket.socketMaster")
S3FNET_REGISTER_PROTOCOL (BTCPClientSession,"S3F.OS.TCP.test.BTCPClient")
S3FNET_REGISTER_PROTOCOL (NBTCPClientSession,"S3F.OS.TCP.test.NBTCPClient")
S3FNET_REGISTER_PROTOCOL (NBTCPServerSession,"S3F.OS.TCP.test.NBTCPServer")
S3FNET_REGISTER_PROTOCOL (TCPClientSession,"S3F.OS.TCP.test.TCPClient")
S3FNET_REGISTER_PROTOCOL (TCPServerSession,"S3F.OS.TCP.test.TCPServer")
S3FNET_REGISTER_PROTOCOL_WITH_ALIAS (TCPMaster,"S3F.OS.TCP","S3F.OS.TCP.tcpSessionMaster")
static char * legit_nhi (char *nhistr)
S3FNET_REGISTER_MESSAGE (TCPMessage, S3FNET_PROTOCOL_TYPE_TCP)
S3FNET_REGISTER_PROTOCOL (UDPClientSession,"S3F.OS.UDP.test.UDPClient")
S3FNET_REGISTER_PROTOCOL (UDPServerSession,"S3F.OS.UDP.test.UDPServer")
S3FNET_REGISTER_PROTOCOL_WITH_ALIAS (UDPMaster,"S3F.OS.UDP","S3F.OS.UDP.udpSessionMaster")
S3FNET_REGISTER_MESSAGE (UDPMessage, S3FNET_PROTOCOL_TYPE_UDP)
static void show_usage (char *prognam)
static void strsub (S3FNET_STRING &cp, S3FNET_STRING oldstr, S3FNET_STRING newstr, int num_times=-1)
void sigproc (int arg)
static void default_errhandler (int syserr, const char *fmt, va_list ap)
ErrorHandler set_errhandler (ErrorHandler h)
Set the error handler, which is a user-defined error handling function, and return the old handler (NULL if undefined previously).
void syserr_quit (const char *,...)
This function is called when there's a fatal error related to a system call.
void syserr_dump (const char *,...)
This function is called when there's a fatal error related to a system call.
void syserr_retn (const char *,...)
This function is called when there's a non-fatal error related to a system call.
void error_quit (const char *,...)
This function is called when there's a fatal error unrelated to a system call.
void error_dump (const char *,...)
This function is called when there's a fatal error unrelated to a system call.
void error_retn (const char *,...)
This function is called when there's a non-fatal error unrelated to a system call.
typedef S3FNET_VECTOR (S3FNET_STRING) S3FNET_STRING_VECTOR
A vector of strings.
typedef S3FNET_VECTOR (void *) S3FNET_POINTER_VECTOR
A vector of pointers.
typedef S3FNET_MAP (int, void *) S3FNET_INT2PTR_MAP
A map from an integer to a pointer.
typedef S3FNET_SET (long) S3FNET_LONG_SET
A set of long integers.
typedef S3FNET_VECTOR (long) S3FNET_LONG_VECTOR
A vector of long integers.
char * sstrdup (const char *s)
Make a duplicate string in shared memory.
Variables
static int tcp_backoff []
SimInterface * sim_inf
static ErrorHandler errhandler = default_errhandler
Detailed Description
Network Simulator developed based on the S3F Scalable Simulation Framework.
Typedef Documentation
s3f::s3fnet::IPADDR
IP address should be a 32-bit unsigned integer.
Definition at line 20 of file ip_prefix.h.
typedef char s3f::s3fnet::int8
8-bit character type
Definition at line 29 of file s3fnet.h.
typedef unsigned char s3f::s3fnet::uint8
8-bit unsigned character type
Definition at line 30 of file s3fnet.h.
typedef unsigned char s3f::s3fnet::byte
8-bit unsigned character type
Definition at line 31 of file s3fnet.h.
typedef short s3f::s3fnet::int16
16-bit integer type (short)
Definition at line 32 of file s3fnet.h.
typedef unsigned short s3f::s3fnet::uint16
16-bit unsigned integer type (unsigned short)
Definition at line 33 of file s3fnet.h.
typedef int s3f::s3fnet::int32
32-bit integer type
Definition at line 34 of file s3fnet.h.
typedef unsigned int s3f::s3fnet::uint32
32-bit unsigned integer type
Definition at line 35 of file s3fnet.h.
typedef long long int s3f::s3fnet::int64
64-bit integer type
Definition at line 36 of file s3fnet.h.
typedef unsigned long long int s3f::s3fnet::uint64
64-bit unsigned integer type
Definition at line 37 of file s3fnet.h.
typedef unsigned int s3f::s3fnet::word
Definition at line 38 of file s3fnet.h.
typedef void s3f::s3fnet::general_data
Definition at line 39 of file s3fnet.h.
typedef unsigned long s3f::s3fnet::ulong
Definition at line 40 of file s3fnet.h.
typedef unsigned int s3f::s3fnet::uint
Definition at line 41 of file s3fnet.h.
s3f::s3fnet::MACADDR
For convenience, we use a 64-bit unsigned long integer to denote the MAC address and use simple type casting to mimic the function of ARP.
Definition at line 57 of file s3fnet.h.
typedef void(* s3f::s3fnet::ErrorHandler)(int syserr, const char *msg, va_list ap)
An error handler is a function that consists of three arguments: the first indicates whether the error is caused by a system call or not, the second argument is the format string (like the one in printf), and the last one is an argument list for the format string.
Definition at line 23 of file errhandle.h.
typedef string s3f::s3fnet::S3FNET_STRING
std::string in shared memory.
Definition at line 26 of file shstl.h.
typedef pair<int,int > s3f::s3fnet::S3FNET_INT_PAIR
A pair of integers.
Definition at line 73 of file shstl.h.
typedef uint32 s3f::s3fnet::TRIEBITSTRING
The key type for the trie.
This typedef can be changed (along with a few macros in trie.cc) to support tries of strings.
NOTE: For integers, TRIEBITSTRING must guarantee exactly TRIE_KEY_SIZE bits for proper function
Definition at line 39 of file trie.h.
Enumeration Type Documentation
anonymous enum
Reserved IP addresses for internal use.
In any IP address assignment schemes, these IP addresses should never be assigned to any network interface.
Enumerator
IPADDR_NEXTHOP_IGNORED
When any interface has received a packet with this next hop address, the other side will not check the next hop address to decide whether to report to the upper layer.
In other words, a packet with this next hop address will always be popped up.
IPADDR_NEXTHOP_UNSPECIFIED
When the route information carries this special next hop address, the next hop address will be set to the destination IP address.
IPADDR_INADDR_ANY
When the upper layer wants to send a packet out, it may ignore the source IP address.
Instead, this IP address will be used. The IP layer will substitute it with the IP address of the outgoing network interface.
Definition at line 51 of file ip_prefix.h.
      {
   IPADDR_NEXTHOP_IGNORED     = 0xFFFFFFFF,
   IPADDR_NEXTHOP_UNSPECIFIED = 0xFFFFFFFE,
   IPADDR_INADDR_ANY          = 0xFFFFFFFF
 };
anonymous enum
only TRAFFIC is in use
Enumerator
NET_ACCESSORY_IS_AS_BOUNDARY
NET_ACCESSORY_AS_NUMBER
NET_ACCESSORY_AREA_NUMBER
NET_ACCESSORY_TRAFFIC
NET_ACCESSORY_QUEUE_MONITORS
NET_ACCESSORY_UNSPECIFIED
Definition at line 121 of file net.h.
      {
         NET_ACCESSORY_IS_AS_BOUNDARY    = 1,
         NET_ACCESSORY_AS_NUMBER = 2,
         NET_ACCESSORY_AREA_NUMBER       = 3,
         NET_ACCESSORY_TRAFFIC           = 4,
         NET_ACCESSORY_QUEUE_MONITORS    = 5,
         NET_ACCESSORY_UNSPECIFIED       = 1000
 };
anonymous enum
control message and types and responses
Enumerator
NET_CTRL_IS_AS_BOUNDARY
NET_CTRL_GET_AS_NUMBER
NET_CTRL_GET_AREA_NUMBER
NET_CTRL_GET_TRAFFIC
NET_CTRL_GET_QUEUE_MONITORS
AS_NUMBER_UNSPECIFIED
AREA_NUMBER_UNSPECIFIED
Definition at line 131 of file net.h.
      {
         NET_CTRL_IS_AS_BOUNDARY = 1,
         NET_CTRL_GET_AS_NUMBER  = 2,
         NET_CTRL_GET_AREA_NUMBER        = 3,
         NET_CTRL_GET_TRAFFIC            = 4,
         NET_CTRL_GET_QUEUE_MONITORS     = 5,
         AS_NUMBER_UNSPECIFIED           = -1,
         AREA_NUMBER_UNSPECIFIED = 0,
 };
enum s3f::s3fnet::NicQueueCtrlCmd
The control command types for the NIC queue.
Enumerator
NIC_QUEUE_ROUTE_DOWN
Tear down flows with a list of destinations.
Definition at line 25 of file nic_queue.h.
                      {
   NIC_QUEUE_ROUTE_DOWN  = 0,
 };
enum s3f::s3fnet::OPENFLOW_CONTROLLER_MODEL
Model of OpenFlow controller.
Ending wit h_ENTITY means entity-based controller, otherwise non-entity-based controller.
Enumerator
NO_OF_CONTROLLER
OF_LEARNING_SWITCH_CONTROLLER
OF_DROP_CONTROLLER
OF_LEARNING_SWITCH_CONTROLLER_ENTITY
Definition at line 94 of file openflow_interface.h.
 {
         NO_OF_CONTROLLER = 0,
         OF_LEARNING_SWITCH_CONTROLLER = 1,
         OF_DROP_CONTROLLER = 2,
         OF_LEARNING_SWITCH_CONTROLLER_ENTITY = 3,
 };
enum s3f::s3fnet::S3FNetProtocolType
Protocol type (or protocol number) is used both by protocol sessions and protocol messages to uniquely identify different protocol layers.
The IP layer uses this number to distinguish upper-layer protocols. All protocol implemented are listed here.
Enumerator
S3FNET_PROTOCOL_TYPE_INVALID
Reserved type, which should not be used by any protocol.
S3FNET_PROTOCOL_TYPE_ICMP
The Internet Control Message Protocol (ICMP) for ping.
S3FNET_PROTOCOL_TYPE_IPV4
The Internet Protocol (IP) version 4.
S3FNET_PROTOCOL_TYPE_TCP
The Transport Control Protocol (TCP).
S3FNET_PROTOCOL_TYPE_UDP
The User Datagram Protocol (UDP).
S3FNET_PROTOCOL_TYPE_OSPF
The Open Shortest Path First (OSPF) protocol.
S3FNET_PROTOCOL_TYPE_SOCKET
The Socket protocol.
S3FNET_PROTOCOL_TYPE_SIMPLE_PHY
A simple physical layer protocol.
S3FNET_PROTOCOL_TYPE_SIMPLE_MAC
A simple MAC layer protocol.
S3FNET_PROTOCOL_TYPE_OPAQUE_DATA
This protocol type is used only by the DataMessage class (for an opaque payload).
The protocol does not represent any protocols in the real world.
S3FNET_PROTOCOL_TYPE_TCPTEST_CLIENT
A client-side protocol for testing the TCP model.
S3FNET_PROTOCOL_TYPE_TCPTEST_SERVER
A server-side protocol for testing the TCP model.
S3FNET_PROTOCOL_TYPE_TCPTEST_BLOCKING_CLIENT
A client-side protocol for testing the TCP model with blocking socket.
S3FNET_PROTOCOL_TYPE_TCPTEST_BLOCKING_SERVER
A server-side protocol for testing the TCP model with blocking socket.
S3FNET_PROTOCOL_TYPE_TCPTEST_NON_BLOCKING_CLIENT
A client-side protocol for testing the TCP model with non-blocking socket.
S3FNET_PROTOCOL_TYPE_TCPTEST_NON_BLOCKING_SERVER
A server-side protocol for testing the TCP model with non-blocking socket.
S3FNET_PROTOCOL_TYPE_UDPTEST_CLIENT
A client-side protocol for testing the UDP model.
S3FNET_PROTOCOL_TYPE_UDPTEST_SERVER
A server-side protocol for testing the UDP model.
S3FNET_PROTOCOL_TYPE_COMMAND
A protocol for communicating with the database for sending and receiving commands.
S3FNET_PROTOCOL_TYPE_DUMMY
A dummy protocol.
S3FNET_PROTOCOL_TYPE_OPENVZ_EVENT
An OpenVZ event input protocol.
S3FNET_PROTOCOL_TYPE_OPENFLOW_SWITCH
An OpenFlow switch protocol.
S3FNET_PROTOCOL_TYPE_OPENFLOW_CONTROLLER
An OpenFlow switch protocol.
Definition at line 110 of file s3fnet.h.
{
   S3FNET_PROTOCOL_TYPE_INVALID = 0,
   /* Full implementation of real network protocols. */
   S3FNET_PROTOCOL_TYPE_ICMP = 1,
   S3FNET_PROTOCOL_TYPE_IPV4 = 4,
   S3FNET_PROTOCOL_TYPE_TCP =  6,
   S3FNET_PROTOCOL_TYPE_UDP =  17,
   S3FNET_PROTOCOL_TYPE_OSPF = 89,
   S3FNET_PROTOCOL_TYPE_SOCKET = 200,
   S3FNET_PROTOCOL_TYPE_SIMPLE_PHY = 201,
   S3FNET_PROTOCOL_TYPE_SIMPLE_MAC = 202,
   S3FNET_PROTOCOL_TYPE_OPAQUE_DATA = 203,
   S3FNET_PROTOCOL_TYPE_TCPTEST_CLIENT = 221,
   S3FNET_PROTOCOL_TYPE_TCPTEST_SERVER = 222,
   S3FNET_PROTOCOL_TYPE_TCPTEST_BLOCKING_CLIENT = 223,
   S3FNET_PROTOCOL_TYPE_TCPTEST_BLOCKING_SERVER = 224,
   S3FNET_PROTOCOL_TYPE_TCPTEST_NON_BLOCKING_CLIENT = 225,
   S3FNET_PROTOCOL_TYPE_TCPTEST_NON_BLOCKING_SERVER = 226,
   S3FNET_PROTOCOL_TYPE_UDPTEST_CLIENT = 227,
   S3FNET_PROTOCOL_TYPE_UDPTEST_SERVER = 228,
   S3FNET_PROTOCOL_TYPE_COMMAND = 238,
   S3FNET_PROTOCOL_TYPE_DUMMY = 254,
   S3FNET_PROTOCOL_TYPE_OPENVZ_EVENT = 240,
   S3FNET_PROTOCOL_TYPE_OPENFLOW_SWITCH = 241,
   S3FNET_PROTOCOL_TYPE_OPENFLOW_CONTROLLER = 242,
 };
enum s3f::s3fnet::ProtocolSessionCtrlTypes
General control types.
User defined control types should use numbers greater than 1000. The numbers below are reserved.
Enumerator
PSESS_CTRL_SESSION_IS_LOWEST
Check if the protocol is at the bottom of the protocol stack.
The ctrlmsg argument in this case is a pointer to a boolean value (of type bool), which is supplied by the caller for the callee to return value. The ProtocolSession class implements the default by returning the value false, since by default a protocol session is not the lowest in the protocol stack. The LowestProtocolSession class overrides this method and returns true for this control type. All protocol sessions that consider themselves functioning as the lowest protocol session (such as SimplePhy) should simply derive from the LowestProtocolSession class so that this control type is handled appropriately.
PSESS_CTRL_SESSION_GET_INTERFACE
Get the owner network interface if this protocol session belongs to a network interface (such as SimpleMac and SimplePhy).
A pointer to an Interface object shall be returned through the ctrlmsg argument to the control method. The ProtocolSession class implements the default by returning an NULL, indicating a protocol session by default is not in a network interface. The NicProtocolSession class overrides the control method and returns the owner network interface. All protocol sessions that consider themselves functioning within a network interface (such as SimpleMac and SimplePhy) should derive from the NicProtocolSession class so that this control type is handled appropriately.
PSESS_CTRL_SESSION_SET_PARENT
Set the protocol session above the current one.
This control type is applicable to a protocol session that belongs to a network interface (such as SimpleMac and SimplePhy). In the ProtocolSession class, this control type is simply ignored. The NicProtocolSession class overrides the control method and establishes the connection among protocol sessions within the network interface. All protocol sessions that consider themselves functioning within a network interface (such as SimpleMac and SimplePhy) should derive from the NicProtocolSession class so that this control type is handled appropriately.
PSESS_CTRL_SESSION_SET_CHILD
Set the protocol session above the current one.
This control type is applicable to a protocol session that belongs to a network interface (such as SimpleMac and SimplePhy). In the ProtocolSession class, this control type is simply ignored. The NicProtocolSession class overrides the control method and establishes the connection among protocol sessions within the network interface. All protocol sessions that consider themselves functioning within a network interface (such as SimpleMac and SimplePhy) should derive from the NicProtocolSession class so that this control type is handled appropriately.
PHY_CTRL_GET_BITRATE
Get the bitrate of the physical medium in bits per second.
The ctrlmsg argument to the control method should be a pointer to a double floating point number. The control method always returns a zero for this control type.
PHY_CTRL_GET_BUFFER_SIZE
Get the buffer size in bytes.
The ctrlmsg argument to the control method should be a pointer to a long integer. The control method always returns a zero for this control type.
PHY_CTRL_GET_LATENCY
Get the latency of the network interface in seconds.
The ctrlmsg argument to the control method should be a pointer to a floating point number. The control method always returns a zero for this control type.
PHY_CTRL_GET_JITTER_RANGE
Get the jitter range of the network interface.
The ctrlmsg argument to the control method should be a pointer to a floating point number. A jitter should be between 0 and 1: 0 means no jitter (the default), and 1 means maximum jitter (as large as the time to send the packet). The control method always returns a zero for this control type.
PHY_CTRL_GET_QUEUE
Get the network queue.
The ctrlmsg argument to the control method should be a pointer to a pointer of NicQueue type. The control method always returns a zero for this control type.
IP_CTRL_VERIFY_TARGET_IP_ADDRESS
Check whether a given ip address is acceptable by local ip.
IP_CTRL_VERIFY_LOCAL_IP_ADDRESS
Check whether a given ip address is local.
IP_CTRL_GET_FORWARDING_TABLE
Get the forwarding table on the host.
IP_CTRL_LOAD_FORWARDING_TABLE
Load forwarding table from DML.
IP_CTRL_INSERT_ROUTE
Insert a new route.
IP_CTRL_DELETE_ROUTE
Insert a new route.
IP_CTRL_INSERT_DMLROUTE
Insert a new dml route.
IP_CTRL_ADD_INTERCEPT_SESSION
Add an intercepting session to support packet capturing.
IP_CTRL_PUSH_REQUEST
Push a protocol message down through IP (same as through the pushdown() method).
IP_CTRL_ADD_FIB_LISTENER
Inform FIB listener protocol sessions of routes being added.
IP_CTRL_FIB_ADDROUTE
Inform FIB listener protocol sessions of routes being added.
IP_CTRL_FIB_DELROUTE
Inform FIB listener protocol sessions of routes being deleted.
UDP_CTRL_GET_MAX_DATAGRAM_SIZE
SOCK_CTRL_CLEAR_SIGNAL
SOCK_CTRL_SET_SIGNAL
SOCK_CTRL_DETACH_SESSION
SOCK_CTRL_REINIT
SOCK_CTRL_GET_APP_SESSION
DUMMY_CTRL_COMMAND1
DUMMY_CTRL_COMMAND2
OPENFLOW_SWITCH_CTRL_COMMAND1
OPENFLOW_SWITCH_CTRL_COMMAND2
OPENFLOW_CONTROLLER_CTRL_COMMAND1
OPENFLOW_CONTROLLER_CTRL_COMMAND2
Definition at line 191 of file s3fnet.h.
{
   /*
    * control commands for a generic protocol session
    */
   PSESS_CTRL_SESSION_IS_LOWEST  = 1,
   PSESS_CTRL_SESSION_GET_INTERFACE = 2,
   PSESS_CTRL_SESSION_SET_PARENT = 3,
   PSESS_CTRL_SESSION_SET_CHILD  = 4,
   /*
    * control commands for the (simple) PHY layer
    */
   PHY_CTRL_GET_BITRATE          = 21,
   PHY_CTRL_GET_BUFFER_SIZE      = 22,
   PHY_CTRL_GET_LATENCY          = 23,
   PHY_CTRL_GET_JITTER_RANGE     = 24,
   PHY_CTRL_GET_QUEUE            = 25,
   /*
    * control commands for IP
    */
   IP_CTRL_VERIFY_TARGET_IP_ADDRESS = 40,
   IP_CTRL_VERIFY_LOCAL_IP_ADDRESS = 41,
   IP_CTRL_GET_FORWARDING_TABLE  = 42,
   IP_CTRL_LOAD_FORWARDING_TABLE = 43,
   IP_CTRL_INSERT_ROUTE          = 44,
   IP_CTRL_DELETE_ROUTE          = 45,
   IP_CTRL_INSERT_DMLROUTE       = 46,
   IP_CTRL_ADD_INTERCEPT_SESSION = 47,
   IP_CTRL_PUSH_REQUEST          = 48,
   IP_CTRL_ADD_FIB_LISTENER      = 49,
   IP_CTRL_FIB_ADDROUTE          = 50,
   IP_CTRL_FIB_DELROUTE          = 51,
   /*
    * control commands for UDP
    */
   UDP_CTRL_GET_MAX_DATAGRAM_SIZE = 71,
   /*
    * control commands for Socket session
    */
   SOCK_CTRL_CLEAR_SIGNAL        = 81,
   SOCK_CTRL_SET_SIGNAL          = 82,
   SOCK_CTRL_DETACH_SESSION      = 83,
   SOCK_CTRL_REINIT                      = 84,
   SOCK_CTRL_GET_APP_SESSION     = 85,
   /*
    * dummy protocol control commands
    */
   DUMMY_CTRL_COMMAND1           = 1512,
   DUMMY_CTRL_COMMAND2           = 1513,
   /*
    * openflow switch protocol control commands //not in use yet
    */
   OPENFLOW_SWITCH_CTRL_COMMAND1         = 200,
   OPENFLOW_SWITCH_CTRL_COMMAND2         = 201,
   /*
    * openflow controller protocol control commands //not in use yet
    */
   OPENFLOW_CONTROLLER_CTRL_COMMAND1             = 202,
   OPENFLOW_CONTROLLER_CTRL_COMMAND2             = 203,
 };
Function Documentation
s3f::s3fnet::S3FNET_REGISTER_QUEUE (DroptailQueue , DROPTAIL_QUEUE_NAME)
typedef s3f::s3fnet::S3FNET_SET (ProtocolSession *)
typedef s3f::s3fnet::S3FNET_MAP (int , NetworkInterface *)
bool s3f::s3fnet::operator== (const IPPrefix & ip1, const IPPrefix & ip2)
Definition at line 163 of file ip_prefix.cc.
References s3f::s3fnet::IPPrefix::addr, s3f::s3fnet::IPPrefix::len, and s3f::s3fnet::IPPrefix::masks.
 {
   return (ip1.len == ip2.len) &&
     ((ip1.addr & IPPrefix::masks[ip1.len]) ==
      (ip2.addr & IPPrefix::masks[ip2.len]));
 }
static char s3f::s3fnet::AsciiToLowCase (char c) static
Definition at line 25 of file mac48_address.cc.
References ASCII_a, ASCII_A, ASCII_z, and ASCII_Z.
Referenced by s3f::s3fnet::Mac48Address::Mac48Address().
 {
         if (c >= ASCII_a && c <= ASCII_z) {
                 return c;
         } else if (c >= ASCII_A && c <= ASCII_Z) {
                 return c + (ASCII_a - ASCII_A);
         } else {
                 return c;
         }
 }
std::ostream & s3f::s3fnet::operator<< (std::ostream & os, const Mac48Address & address)
Definition at line 134 of file mac48_address.cc.
References s3f::s3fnet::Mac48Address::CopyTo().
 {
         uint8_t ad[6];
         address.CopyTo (ad);
         os.setf (std::ios::hex, std::ios::basefield);
         os.fill ('0');
         for (uint8_t i=0; i < 5; i++)
         {
                 os << std::setw (2) << (uint32_t)ad[i] << ":";
         }
         // Final byte not suffixed by ":"
         os << std::setw (2) << (uint32_t)ad[5];
         os.setf (std::ios::dec, std::ios::basefield);
         os.fill (' ');
         return os;
 }
std::ostream & s3f::s3fnet::operator<< (std::ostream & os, const Mac48Address * address)
Definition at line 152 of file mac48_address.cc.
References s3f::s3fnet::Mac48Address::CopyTo().
 {
         uint8_t ad[6];
         address->CopyTo (ad);
         os.setf (std::ios::hex, std::ios::basefield);
         os.fill ('0');
         for (uint8_t i=0; i < 5; i++)
         {
                 os << std::setw (2) << (uint32_t)ad[i] << ":";
         }
         // Final byte not suffixed by ":"
         os << std::setw (2) << (uint32_t)ad[5];
         os.setf (std::ios::dec, std::ios::basefield);
         os.fill (' ');
         return os;
 }
static uint8_t s3f::s3fnet::AsInt (std::string v) static
Definition at line 170 of file mac48_address.cc.
Referenced by operator>>().
 {
         std::istringstream iss;
         iss.str (v);
         uint32_t retval;
         iss >> std::hex >> retval >> std::dec;
         return retval;
 }
std::istream & s3f::s3fnet::operator>> (std::istream & is, Mac48Address & address)
Definition at line 179 of file mac48_address.cc.
References AsInt(), and s3f::s3fnet::Mac48Address::m_address.
 {
         std::string v;
         is >> v;
         std::string::size_type col = 0;
         for (uint8_t i = 0; i < 6; ++i)
         {
                 std::string tmp;
                 std::string::size_type next;
                 next = v.find (":", col);
                 if (next == std::string::npos)
                 {
                         tmp = v.substr (col, v.size ()-col);
                         address.m_address[i] = AsInt (tmp);
                         break;
                 }
                 else
                 {
                         tmp = v.substr (col, next-col);
                         address.m_address[i] = AsInt (tmp);
                         col = next + 1;
                 }
         }
         return is;
 }
std::istream & s3f::s3fnet::operator>> (std::istream & is, Mac48Address * address)
Definition at line 206 of file mac48_address.cc.
References AsInt(), and s3f::s3fnet::Mac48Address::m_address.
 {
         std::string v;
         is >> v;
         std::string::size_type col = 0;
         for (uint8_t i = 0; i < 6; ++i)
         {
                 std::string tmp;
                 std::string::size_type next;
                 next = v.find (":", col);
                 if (next == std::string::npos)
                 {
                         tmp = v.substr (col, v.size ()-col);
                         address->m_address[i] = AsInt (tmp);
                         break;
                 }
                 else
                 {
                         tmp = v.substr (col, next-col);
                         address->m_address[i] = AsInt (tmp);
                         col = next + 1;
                 }
         }
         return is;
 }
bool s3f::s3fnet::operator== (const Mac48Address & a, const Mac48Address & b) inline
Definition at line 99 of file mac48_address.h.
References s3f::s3fnet::Mac48Address::m_address.
                 {
         return memcmp (a.m_address, b.m_address, 6) == 0;
                 }
bool s3f::s3fnet::operator!= (const Mac48Address & a, const Mac48Address & b) inline
Definition at line 103 of file mac48_address.h.
References s3f::s3fnet::Mac48Address::m_address.
                 {
         return memcmp (a.m_address, b.m_address, 6) != 0;
                 }
bool s3f::s3fnet::operator< (const Mac48Address & a, const Mac48Address & b) inline
Definition at line 107 of file mac48_address.h.
References s3f::s3fnet::Mac48Address::m_address.
 {
         return memcmp (a.m_address, b.m_address, 6) < 0;
 }
typedef s3f::s3fnet::S3FNET_VECTOR (IPADDR)
Referenced by s3f::s3fnet::UDPClientSession::get_random_server(), s3f::s3fnet::NBTCPClientSession::get_random_server(), s3f::s3fnet::TCPClientSession::get_random_server(), s3f::s3fnet::BTCPClientSession::get_random_server(), s3f::s3fnet::Protocols::newInstance(), s3f::s3fnet::Net::nhi2obj(), and s3f::s3fnet::Protocols::registerProtocol().
bool s3f::s3fnet::operator== (Nhi & n1, Nhi & n2)
Definition at line 53 of file nhi.cc.
References s3f::s3fnet::Nhi::ids, and s3f::s3fnet::Nhi::start.
 {
   int len, len2;
   len = n1.ids.size() - n1.start;
   len2 = n2.ids.size() - n2.start;
   if(len != len2)
     return false;
   for(int i=0; i < len; i++)
     if(n1.ids[n1.start + i] != n2.ids[n2.start + i])
       return false;
   return true;
 }
s3f::s3fnet::S3FNET_REGISTER_QUEUE (RedQueue , RED_QUEUE_NAME)
typedef s3f::s3fnet::S3FNET_VECTOR (TrafficServerData *)
s3f::s3fnet::S3FNET_REGISTER_MESSAGE (DataMessage , S3FNET_PROTOCOL_TYPE_OPAQUE_DATA)
typedef s3f::s3fnet::S3FNET_MAP (S3FNET_STRING , ProtocolSession *)
typedef s3f::s3fnet::S3FNET_MAP (int , ProtocolSession *)
typedef s3f::s3fnet::S3FNET_VECTOR (ProtocolSession *)
s3f::s3fnet::S3FNET_REGISTER_MESSAGE (DummyMessage , S3FNET_PROTOCOL_TYPE_DUMMY)
s3f::s3fnet::S3FNET_REGISTER_PROTOCOL (DummySession , DUMMY_PROTOCOL_CLASSNAME)
s3f::s3fnet::S3FNET_REGISTER_MESSAGE (IPMessage , S3FNET_PROTOCOL_TYPE_IPV4)
s3f::s3fnet::S3FNET_REGISTER_PROTOCOL (IPSession , IP_PROTOCOL_CLASSNAME)
s3f::s3fnet::S3FNET_REGISTER_PROTOCOL (OpenFlowControllerSession , OF_CONTROLLER_PROTOCOL_CLASSNAME)
s3f::s3fnet::S3FNET_REGISTER_PROTOCOL (LearningControllerSession , OF_CONTROLLER_LEARNING_SWITCH_PROTOCOL_CLASSNAME)
int s3f::s3fnet::Stats_FlowDumpCallback (sw_flow * flow, void * state)
Definition at line 152 of file openflow_interface.cc.
References s3f::s3fnet::Stats::FlowStatsState::buffer, MAX_FLOW_STATS_BYTES, s3f::s3fnet::Stats::FlowStatsState::now, and s3f::s3fnet::Stats::FlowStatsState::table_idx.
 {
   Stats::FlowStatsState *s = (Stats::FlowStatsState*)state;
   // Fill Flow Stats
   ofp_flow_stats *ofs;
   int length = sizeof *ofs + flow->sf_acts->actions_len;
   ofs = (ofp_flow_stats*)ofpbuf_put_zeros (s->buffer, length);
   ofs->length          = htons (length);
   ofs->table_id        = s->table_idx;
   ofs->match.wildcards = htonl (flow->key.wildcards);
   ofs->match.in_port   = flow->key.flow.in_port;
   memcpy (ofs->match.dl_src, flow->key.flow.dl_src, ETH_ADDR_LEN);
   memcpy (ofs->match.dl_dst, flow->key.flow.dl_dst, ETH_ADDR_LEN);
   ofs->match.dl_vlan   = flow->key.flow.dl_vlan;
   ofs->match.dl_type   = flow->key.flow.dl_type;
   ofs->match.nw_src    = flow->key.flow.nw_src;
   ofs->match.nw_dst    = flow->key.flow.nw_dst;
   ofs->match.nw_proto  = flow->key.flow.nw_proto;
   ofs->match.tp_src    = flow->key.flow.tp_src;
   ofs->match.tp_dst    = flow->key.flow.tp_dst;
   ofs->duration        = htonl (s->now - flow->created);
   ofs->priority        = htons (flow->priority);
   ofs->idle_timeout    = htons (flow->idle_timeout);
   ofs->hard_timeout    = htons (flow->hard_timeout);
   ofs->packet_count    = htonll (flow->packet_count);
   ofs->byte_count      = htonll (flow->byte_count);
   memcpy (ofs->actions, flow->sf_acts->actions, flow->sf_acts->actions_len);
   return s->buffer->size >= MAX_FLOW_STATS_BYTES;
 }
int s3f::s3fnet::Stats_AggregateDumpCallback (sw_flow * flow, void * state)
Definition at line 215 of file openflow_interface.cc.
 {
   ofp_aggregate_stats_reply *s = (ofp_aggregate_stats_reply*)state;
   s->packet_count += flow->packet_count;
   s->byte_count += flow->byte_count;
   s->flow_count++;
   return 0;
 }
void s3f::s3fnet::ExecuteActions (OpenFlowSwitchSession * swtch, uint64_t packet_uid, ofpbuf * buffer, sw_flow_key * key, const ofp_action_header * actions, size_t actions_len, int ignore_no_fwd)
Executes a list of flow table actions.
Parameters
swtch OpenFlowSwitchSession these actions are being executed on.
packet_uid Packet UID; used to fetch the packet and its metadata.
buffer The Packet OpenFlow buffer.
key The matching key for the flow tied to this list of actions.
actions A buffer of actions.
actions_len Length of actions buffer.
ignore_no_fwd If true, during port forwarding actions, ports that are set to not forward are forced to forward.
Definition at line 623 of file openflow_interface.cc.
References s3f::s3fnet::OpenFlowSwitchSession::DoOutput(), s3f::s3fnet::Action::Execute(), ExecuteVendor(), s3f::s3fnet::Action::IsValidType(), and OF_IFACE_DUMP.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::AddFlow(), s3f::s3fnet::OpenFlowSwitchSession::FlowTableLookup(), s3f::s3fnet::OpenFlowSwitchSession::ModFlow(), and s3f::s3fnet::OpenFlowSwitchSession::ReceivePacketOut().
 {
   /* Every output action needs a separate clone of 'buffer', but the common
    * case is just a single output action, so that doing a clone and then
    * freeing the original buffer is wasteful.  So the following code is
    * slightly obscure just to avoid that. */
   int prev_port;
   size_t max_len = 0;     // Initialze to make compiler happy
   uint16_t in_port = key->flow.in_port; // ntohs(key->flow.in_port);
   uint8_t *p = (uint8_t *)actions;
   prev_port = -1;
   if (actions_len == 0)
     {
           OF_IFACE_DUMP (cout << "No actions set to this flow. Dropping packet." << endl);
       return;
     }
   /* The action list was already validated, so we can be a bit looser
    * in our sanity-checking. */
   while (actions_len > 0)
     {
       ofp_action_header *ah = (ofp_action_header *)p;
       size_t len = htons (ah->len);
       if (prev_port != -1)
         {
           swtch->DoOutput (packet_uid, in_port, max_len, prev_port, ignore_no_fwd);
           prev_port = -1;
         }
       if (ah->type == htons (OFPAT_OUTPUT))
         {
           ofp_action_output *oa = (ofp_action_output *)p;
           // port is now 32-bits
           prev_port = oa->port; // ntohl(oa->port);
           max_len = ntohs (oa->max_len);
         }
       else
         {
           uint16_t type = ntohs (ah->type);
           if (Action::IsValidType ((ofp_action_type)type)) // Execute a built-in OpenFlow action against 'buffer'.
             {
               Action::Execute ((ofp_action_type)type, buffer, key, ah);
             }
           else if (type == OFPAT_VENDOR)
             {
               ExecuteVendor (buffer, key, ah);
             }
         }
       p += len;
       actions_len -= len;
     }
   if (prev_port != -1)
     {
       swtch->DoOutput (packet_uid, in_port, max_len, prev_port, ignore_no_fwd);
     }
 }
uint16_t s3f::s3fnet::ValidateActions (const sw_flow_key * key, const ofp_action_header * actions, size_t actions_len)
Validates a list of flow table actions.
Parameters
key The matching key for the flow tied to this list of actions.
actions A buffer of actions.
actions_len Length of actions buffer.
Returns
If the action list validates, ACT_VALIDATION_OK is returned. Otherwise, a code for the OFPET_BAD_ACTION error type is returned.
Definition at line 687 of file openflow_interface.cc.
References s3f::s3fnet::Action::IsValidType(), s3f::s3fnet::Action::Validate(), and ValidateVendor().
Referenced by s3f::s3fnet::OpenFlowSwitchSession::AddFlow(), s3f::s3fnet::OpenFlowSwitchSession::ModFlow(), and s3f::s3fnet::OpenFlowSwitchSession::ReceivePacketOut().
 {
   uint8_t *p = (uint8_t *)actions;
   int err;
   while (actions_len >= sizeof(ofp_action_header))
     {
       ofp_action_header *ah = (ofp_action_header *)p;
       size_t len = ntohs (ah->len);
       uint16_t type;
       /* Make there's enough remaining data for the specified length
         * and that the action length is a multiple of 64 bits. */
       if ((actions_len < len) || (len % 8) != 0)
         {
           return OFPBAC_BAD_LEN;
         }
       type = ntohs (ah->type);
       if (Action::IsValidType ((ofp_action_type)type)) // Validate built-in OpenFlow actions.
         {
           err = Action::Validate ((ofp_action_type)type, len, key, ah);
           if (err != ACT_VALIDATION_OK)
             {
               return err;
             }
         }
       else if (type == OFPAT_VENDOR)
         {
           err = ValidateVendor (key, ah, len);
           if (err != ACT_VALIDATION_OK)
             {
               return err;
             }
         }
       else
         {
           return OFPBAC_BAD_TYPE;
         }
       p += len;
       actions_len -= len;
     }
   // Check if there's any trailing garbage.
   if (actions_len != 0)
     {
       return OFPBAC_BAD_LEN;
     }
   return ACT_VALIDATION_OK;
 }
void s3f::s3fnet::ExecuteVPortActions (OpenFlowSwitchSession * swtch, uint64_t packet_uid, ofpbuf * buffer, sw_flow_key * key, const ofp_action_header * actions, size_t actions_len)
Executes a list of virtual port table entry actions.
Parameters
swtch OpenFlowSwitchSession these actions are being executed on.
packet_uid Packet UID; used to fetch the packet and its metadata.
buffer The Packet OpenFlow buffer.
key The matching key for the flow tied to this list of actions.
actions A buffer of actions.
actions_len Length of actions buffer.
Definition at line 740 of file openflow_interface.cc.
References s3f::s3fnet::OpenFlowSwitchSession::DoOutput(), and s3f::s3fnet::VPortAction::Execute().
Referenced by s3f::s3fnet::OpenFlowSwitchSession::RunThroughVPortTable().
 {
   /* Every output action needs a separate clone of 'buffer', but the common
    * case is just a single output action, so that doing a clone and then
    * freeing the original buffer is wasteful.  So the following code is
    * slightly obscure just to avoid that. */
   int prev_port;
   size_t max_len = 0;     // Initialize to make compiler happy
   //uint16_t in_port = ntohs (key->flow.in_port);
   uint16_t in_port = key->flow.in_port;
   uint8_t *p = (uint8_t *)actions;
   uint16_t type;
   ofp_action_output *oa;
   prev_port = -1;
   /* The action list was already validated, so we can be a bit looser
    * in our sanity-checking. */
   while (actions_len > 0)
     {
       ofp_action_header *ah = (ofp_action_header *)p;
       size_t len = htons (ah->len);
       if (prev_port != -1)
         {
           swtch->DoOutput (packet_uid, in_port, max_len, prev_port, false);
           prev_port = -1;
         }
       if (ah->type == htons (OFPAT_OUTPUT))
         {
           oa = (ofp_action_output *)p;
           prev_port = ntohl (oa->port);
           max_len = ntohs (oa->max_len);
         }
       else
         {
           type = ah->type; // ntohs(ah->type);
           VPortAction::Execute ((ofp_vport_action_type)type, buffer, key, ah);
         }
       p += len;
       actions_len -= len;
     }
   if (prev_port != -1)
     {
       swtch->DoOutput (packet_uid, in_port, max_len, prev_port, false);
     }
 }
uint16_t s3f::s3fnet::ValidateVPortActions (const ofp_action_header * actions, size_t actions_len)
Validates a list of virtual port table entry actions.
Parameters
actions A buffer of actions.
actions_len Length of actions buffer.
Returns
If the action list validates, ACT_VALIDATION_OK is returned. Otherwise, a code for the OFPET_BAD_ACTION error type is returned.
Definition at line 789 of file openflow_interface.cc.
References s3f::s3fnet::VPortAction::IsValidType(), and s3f::s3fnet::VPortAction::Validate().
Referenced by s3f::s3fnet::OpenFlowSwitchSession::AddVPort().
 {
   uint8_t *p = (uint8_t *)actions;
   int err;
   while (actions_len >= sizeof(ofp_action_header))
     {
       ofp_action_header *ah = (ofp_action_header *)p;
       size_t len = ntohs (ah->len);
       uint16_t type;
       /* Make there's enough remaining data for the specified length
         * and that the action length is a multiple of 64 bits. */
       if ((actions_len < len) || (len % 8) != 0)
         {
           return OFPBAC_BAD_LEN;
         }
       type = ntohs (ah->type);
       if (VPortAction::IsValidType ((ofp_vport_action_type)type)) // Validate "built-in" OpenFlow port table actions.
         {
           err = VPortAction::Validate ((ofp_vport_action_type)type, len, ah);
           if (err != ACT_VALIDATION_OK)
             {
               return err;
             }
         }
       else
         {
           return OFPBAC_BAD_TYPE;
         }
       p += len;
       actions_len -= len;
     }
   // Check if there's any trailing garbage.
   if (actions_len != 0)
     {
       return OFPBAC_BAD_LEN;
     }
   return ACT_VALIDATION_OK;
 }
void s3f::s3fnet::ExecuteVendor (ofpbuf * buffer, const sw_flow_key * key, const ofp_action_header * ah)
Executes a vendor-defined action.
Parameters
buffer The Packet OpenFlow buffer.
key The matching key for the flow tied to this list of actions.
ah Header of the action.
Definition at line 834 of file openflow_interface.cc.
References s3f::s3fnet::EricssonAction::Execute(), and OF_IFACE_DUMP.
Referenced by ExecuteActions().
 {
   ofp_action_vendor_header *avh = (ofp_action_vendor_header *)ah;
   switch (ntohl (avh->vendor))
     {
     case NX_VENDOR_ID:
       // Nothing to execute yet.
       break;
     case ER_VENDOR_ID:
       {
         const er_action_header *erah = (const er_action_header *)avh;
         EricssonAction::Execute ((er_action_type)ntohs (erah->subtype), buffer, key, erah);
         break;
       }
     default:
       // This should not be possible due to prior validation.
       OF_IFACE_DUMP (cout << "attempt to execute action with unknown vendor: " << ntohl (avh->vendor) << endl);
       break;
     }
 }
uint16_t s3f::s3fnet::ValidateVendor (const sw_flow_key * key, const ofp_action_header * ah, uint16_t len)
Validates a vendor-defined action.
Parameters
key The matching key for the flow tied to this list of actions.
ah Header of the action.
len Length of the action.
Returns
If the action list validates, ACT_VALIDATION_OK is returned. Otherwise, a code for the OFPET_BAD_ACTION error type is returned.
Definition at line 856 of file openflow_interface.cc.
References s3f::s3fnet::EricssonAction::Validate().
Referenced by ValidateActions().
 {
   ofp_action_vendor_header *avh;
   int ret = ACT_VALIDATION_OK;
   if (len < sizeof(ofp_action_vendor_header))
     {
       return OFPBAC_BAD_LEN;
     }
   avh = (ofp_action_vendor_header *)ah;
   switch (ntohl (avh->vendor))
     {
     case NX_VENDOR_ID:   // Validate Nicara OpenFlow actions.
       ret = OFPBAC_BAD_VENDOR_TYPE;   // Nothing to validate yet.
       break;
     case ER_VENDOR_ID:   // Validate Ericsson OpenFlow actions.
       {
         const er_action_header *erah = (const er_action_header *)avh;
         ret = EricssonAction::Validate ((er_action_type)ntohs (erah->subtype), len);
         break;
       }
     default:
       return OFPBAC_BAD_VENDOR;
     }
   return ret;
 }
s3f::s3fnet::S3FNET_REGISTER_MESSAGE (OpenFlowMessage , S3FNET_PROTOCOL_TYPE_OPENFLOW_CONTROLLER)
s3f::s3fnet::S3FNET_REGISTER_PROTOCOL (OpenFlowSwitchSession , OF_SWITCH_PROTOCOL_CLASSNAME)
static uint64_t s3f::s3fnet::GenerateId () static
Definition at line 58 of file openflow_switch_session.cc.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::OpenFlowSwitchSession().
 {
         uint8_t ea[ETH_ADDR_LEN];
         eth_addr_random (ea);
         return eth_addr_to_uint64 (ea);
 }
s3f::s3fnet::S3FNET_REGISTER_PROTOCOL (OpenVZEventSession , OPENVZ_EVENT_PROTOCOL_CLASSNAME)
s3f::s3fnet::S3FNET_REGISTER_MESSAGE (OpenVZMessage , S3FNET_PROTOCOL_TYPE_OPENVZ_EVENT)
s3f::s3fnet::S3FNET_REGISTER_PROTOCOL (SimpleMac , SIMPLE_MAC_PROTOCOL_CLASSNAME)
s3f::s3fnet::S3FNET_REGISTER_MESSAGE (SimpleMacMessage , S3FNET_PROTOCOL_TYPE_SIMPLE_MAC)
s3f::s3fnet::S3FNET_REGISTER_PROTOCOL (SimplePhy , SIMPLE_PHY_PROTOCOL_CLASSNAME)
s3f::s3fnet::S3FNET_REGISTER_PROTOCOL (NBSocketMaster , "S3F.OS.Socket.nbSocketMaster")
s3f::s3fnet::S3FNET_REGISTER_PROTOCOL (SocketMaster , "S3F.OS.Socket.socketMaster")
s3f::s3fnet::S3FNET_REGISTER_PROTOCOL (BTCPClientSession , "S3F.OS.TCP.test.BTCPClient")
s3f::s3fnet::S3FNET_REGISTER_PROTOCOL (NBTCPClientSession , "S3F.OS.TCP.test.NBTCPClient")
s3f::s3fnet::S3FNET_REGISTER_PROTOCOL (NBTCPServerSession , "S3F.OS.TCP.test.NBTCPServer")
s3f::s3fnet::S3FNET_REGISTER_PROTOCOL (TCPClientSession , "S3F.OS.TCP.test.TCPClient")
s3f::s3fnet::S3FNET_REGISTER_PROTOCOL (TCPServerSession , "S3F.OS.TCP.test.TCPServer")
s3f::s3fnet::S3FNET_REGISTER_PROTOCOL_WITH_ALIAS (TCPMaster , "S3F.OS.TCP" , "S3F.OS.TCP.tcpSessionMaster")
static char* s3f::s3fnet::legit_nhi (char * nhistr) static
Definition at line 30 of file tcp_master.cc.
 {
   if(nhistr)
   {
     char* ret = nhistr;
     while(*nhistr)
     {
       if(*nhistr == ':') *nhistr = '.';
       nhistr++;
     }
     return ret;
   } else return 0;
 }
s3f::s3fnet::S3FNET_REGISTER_MESSAGE (TCPMessage , S3FNET_PROTOCOL_TYPE_TCP)
s3f::s3fnet::S3FNET_REGISTER_PROTOCOL (UDPClientSession , "S3F.OS.UDP.test.UDPClient")
s3f::s3fnet::S3FNET_REGISTER_PROTOCOL (UDPServerSession , "S3F.OS.UDP.test.UDPServer")
s3f::s3fnet::S3FNET_REGISTER_PROTOCOL_WITH_ALIAS (UDPMaster , "S3F.OS.UDP" , "S3F.OS.UDP.udpSessionMaster")
s3f::s3fnet::S3FNET_REGISTER_MESSAGE (UDPMessage , S3FNET_PROTOCOL_TYPE_UDP)
static void s3f::s3fnet::show_usage (char * prognam) static
Definition at line 28 of file s3fnet.cc.
Referenced by main().
 {
   fprintf(stderr, "USAGE: %s [S3FNET-OPTIONS] <dml-file> [<dml-file> ...]\n", prognam);
   fprintf(stderr, "  S3FNET-OPTIONS are command-line arguments for the network simulator.\n");
   fprintf(stderr, "  Available S3FNET-OPTIONS:\n");
   fprintf(stderr, "    -h: show this message\n");
   fprintf(stderr, "    -q: quiet mode (no system messages)\n");
   fprintf(stderr, "  <dml-file> [<dml-file>...]: a list of DML files that altogether define\n"
           "    the network model (including intermediate DMLs created by utility programs).\n");
   fprintf(stderr, "  e.g., %s test.dml test-env.dml test-rt.dml \n", prognam);
   fprintf(stderr, "  Refer to s3fnet/test for more examples. \n");
 }
static void s3f::s3fnet::strsub (S3FNET_STRING & cp, S3FNET_STRING oldstr, S3FNET_STRING newstr, int num_times = -1) static
Definition at line 41 of file s3fnet.cc.
 {
   int startpos = 0;
   for(int i=0; i!=num_times; i++)
   {
     int loc = cp.find(oldstr, startpos);
     if(loc >= 0)
     {
       cp.replace(loc, oldstr.length(), newstr);
       startpos = loc + newstr.length();
     }
     else
         break;
   }
 }
void s3f::s3fnet::sigproc (int arg)
Definition at line 57 of file s3fnet.cc.
References Interface::get_timeline_interface(), sim_inf, and TimelineInterface::user_force_stop.
Referenced by main().
 {
         if (sim_inf->get_timeline_interface()->user_force_stop) exit(0);
         sim_inf->get_timeline_interface()->user_force_stop = true;
         printf("\ntrying to stop, press ctrl+c again to force exit\n");
 }
static void s3f::s3fnet::default_errhandler (int syserr, const char * fmt, va_list ap) static
Definition at line 27 of file errhandle.cc.
References S3FNET_ERRHANDLE_PRTFMT_BUFSIZ.
 {
    // Stack memory instead of heap memory is desired here as the error
    // could come from the memory system. However, this could lead to
    // buffer overflow problem if not dealt with carefully. We must
    // truncate the error message if there's a buffer overflow.
   char buf[S3FNET_ERRHANDLE_PRTFMT_BUFSIZ];
   if(fmt) {
     // We must save the error number in case it's overwritten by
     // other system calls in this routine.
     int errno_save = errno;
     // Write the message to the buffer.
     vsnprintf(buf, S3FNET_ERRHANDLE_PRTFMT_BUFSIZ, fmt, ap);
     buf[S3FNET_ERRHANDLE_PRTFMT_BUFSIZ-1] = 0; // safety
     int offset = strlen(buf);
     // Append system error messages if this is related to a system
     // call. Applicable only if there's enough buffer space.
     if(syserr && offset < S3FNET_ERRHANDLE_PRTFMT_BUFSIZ-1) {
       snprintf(buf+offset, S3FNET_ERRHANDLE_PRTFMT_BUFSIZ-1-offset,
                ": %s", strerror(errno_save));
       buf[S3FNET_ERRHANDLE_PRTFMT_BUFSIZ-1] = 0; // safety
       offset = strlen(buf);
     }
     // We add a newline at the end of the message. So, no need to add
     // a newline in the format string!
     if(offset < S3FNET_ERRHANDLE_PRTFMT_BUFSIZ-1)
       strcat(buf, "\n");
     // Flush all file streams, including stdout, so that regular
     // messages are printed out before the error message.
     fflush(0);
     // Print out error message to stderr.
     fputs(buf, stderr);
     // Flush one more time.
     fflush(0);
   }
 }
ErrorHandler s3f::s3fnet::set_errhandler (ErrorHandler h)
Set the error handler, which is a user-defined error handling function, and return the old handler (NULL if undefined previously).
Definition at line 89 of file errhandle.cc.
References errhandler.
 {
   ErrorHandler hd = errhandler;
   errhandler = h;
   return hd;
 }
void s3f::s3fnet::syserr_quit (const char * , ...)
This function is called when there's a fatal error related to a system call.
It's different from the syserr_dump function: this function does not dump core. The function simply prints the error message and terminates the program.
Definition at line 96 of file errhandle.cc.
References errhandler.
 {
   if(errhandler) {
     va_list ap;
     va_start(ap, fmt);
     (*errhandler)(1, fmt, ap);
     va_end(ap);
   }
   exit(1);
 }
void s3f::s3fnet::syserr_dump (const char * , ...)
This function is called when there's a fatal error related to a system call.
The function prints the error message, dumps the core, and then terminates the program.
Definition at line 107 of file errhandle.cc.
References errhandler.
 {
   if(errhandler) {
     va_list ap;
     va_start(ap, fmt);
     (*errhandler)(1, fmt, ap);
     va_end(ap);
   }
   abort(); // will dump core
 }
void s3f::s3fnet::syserr_retn (const char * , ...)
This function is called when there's a non-fatal error related to a system call.
The function simply prints the message and returns immediately. It can be used to print a warning message.
Definition at line 118 of file errhandle.cc.
References errhandler.
 {
   if(errhandler) {
     va_list ap;
     va_start(ap, fmt);
     (*errhandler)(1, fmt, ap);
     va_end(ap);
   }
 }
void s3f::s3fnet::error_quit (const char * , ...)
This function is called when there's a fatal error unrelated to a system call.
It's different from the error_dump function: this function does not dump core. The function simply prints the error message and terminates the program.
Definition at line 128 of file errhandle.cc.
References errhandler.
Referenced by s3f::s3fnet::CidrBlock::addSubCidrBlock(), s3f::s3fnet::Controller::AddSwitch(), s3f::s3fnet::OpenFlowControllerSession::AddSwitch(), s3f::s3fnet::NetworkInterface::attach_to_link(), s3f::s3fnet::UDPMaster::config(), s3f::s3fnet::Link::config(), s3f::s3fnet::DummySession::config(), s3f::s3fnet::TCPClientSession::config(), s3f::s3fnet::OpenVZEventSession::config(), s3f::s3fnet::UDPServerSession::config(), s3f::s3fnet::SimplePhy::config(), s3f::s3fnet::UDPClientSession::config(), s3f::s3fnet::RedQueue::config(), s3f::s3fnet::TCPServerSession::config(), s3f::s3fnet::TCPMaster::config(), s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Traffic::config(), s3f::s3fnet::NBTCPClientSession::config(), s3f::s3fnet::BTCPClientSession::config(), s3f::s3fnet::Host::config(), s3f::s3fnet::OpenFlowSwitchSession::config(), s3f::s3fnet::ProtocolGraph::config(), s3f::s3fnet::RouteInfo::config(), s3f::s3fnet::IPSession::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::TrafficPattern::config(), s3f::s3fnet::NameService::config(), s3f::s3fnet::NBTCPServerSession::config(), s3f::s3fnet::DMLRouteInfo::config(), s3f::s3fnet::Net::config(), s3f::s3fnet::Net::config_host(), s3f::s3fnet::NameService::config_hosts(), s3f::s3fnet::Net::config_net(), s3f::s3fnet::NameService::config_net_cidr(), s3f::s3fnet::NameService::config_nhi_addr(), s3f::s3fnet::ProtocolGraph::config_session(), s3f::s3fnet::Net::config_top_net(), s3f::s3fnet::NameService::config_topnet_cidr(), s3f::s3fnet::TrafficPattern::configure_servers(), s3f::s3fnet::Link::connect(), s3f::s3fnet::ProtocolSession::control(), s3f::s3fnet::IPSession::control(), s3f::s3fnet::Net::control(), s3f::s3fnet::DroptailQueue::enqueue(), s3f::s3fnet::RedQueue::enqueue(), s3f::s3fnet::Net::finish_config_top_net(), s3f::s3fnet::Net::getIdrangeLimits(), s3f::s3fnet::Host::getNetworkLayerProtocol(), s3f::s3fnet::NetworkInterface::handle_openflow_message_to_controller(), s3f::s3fnet::LearningControllerSession::HandleInquiryMessageFromOFSwitch(), s3f::s3fnet::SimpleMac::init(), s3f::s3fnet::DummySession::init(), s3f::s3fnet::UDPMaster::init(), s3f::s3fnet::OpenVZEventSession::init(), s3f::s3fnet::SimplePhy::init(), s3f::s3fnet::RedQueue::init(), s3f::s3fnet::TCPClientSession::init(), s3f::s3fnet::UDPServerSession::init(), s3f::s3fnet::NetworkInterface::init(), s3f::s3fnet::UDPClientSession::init(), s3f::s3fnet::TCPServerSession::init(), s3f::s3fnet::TCPMaster::init(), s3f::s3fnet::NBTCPClientSession::init(), s3f::s3fnet::BTCPClientSession::init(), s3f::s3fnet::SocketMaster::init(), s3f::s3fnet::IPSession::init(), s3f::s3fnet::ProtocolSession::init(), s3f::s3fnet::NBSocketMaster::init(), s3f::s3fnet::NBTCPServerSession::init(), s3f::s3fnet::OpenVZEventSession::injectEvent(), s3f::s3fnet::ProtocolGraph::insert_session(), s3f::s3fnet::Host::listen(), s3f::s3fnet::IPSession::load_forwarding_table(), s3f::s3fnet::Net::load_fwdtable(), main(), s3f::s3fnet::Net::Net(), s3f::s3fnet::OpenFlowSwitchSession::OpenFlowSwitchSession(), s3f::s3fnet::DummySession::pop(), s3f::s3fnet::OpenFlowControllerSession::pop(), s3f::s3fnet::SimpleMac::pop(), s3f::s3fnet::OpenFlowSwitchSession::pop(), s3f::s3fnet::UDPServerSession::pop(), s3f::s3fnet::UDPClientSession::pop(), s3f::s3fnet::NBTCPClientSession::pop(), s3f::s3fnet::TCPServerSession::pop(), s3f::s3fnet::TCPClientSession::pop(), s3f::s3fnet::BTCPClientSession::pop(), s3f::s3fnet::NBTCPServerSession::pop(), s3f::s3fnet::SocketMaster::pop(), s3f::s3fnet::ProtocolSession::pop(), s3f::s3fnet::NBSocketMaster::pop(), s3f::s3fnet::TCPSession::process_ACK(), s3f::s3fnet::LearningController::process_recv_packet(), s3f::s3fnet::DummySession::push(), s3f::s3fnet::OpenFlowControllerSession::push(), s3f::s3fnet::SimpleMac::push(), s3f::s3fnet::OpenVZEventSession::push(), s3f::s3fnet::OpenFlowSwitchSession::push(), s3f::s3fnet::UDPServerSession::push(), s3f::s3fnet::UDPClientSession::push(), s3f::s3fnet::NBTCPClientSession::push(), s3f::s3fnet::TCPServerSession::push(), s3f::s3fnet::TCPClientSession::push(), s3f::s3fnet::BTCPClientSession::push(), s3f::s3fnet::NBTCPServerSession::push(), s3f::s3fnet::SocketMaster::push(), s3f::s3fnet::ProtocolSession::push(), s3f::s3fnet::NBSocketMaster::push(), s3f::s3fnet::Nhi::readNhiRange(), s3f::s3fnet::LearningControllerSession::ReceiveFromSwitch(), s3f::s3fnet::SimplePhy::receivePacket(), s3f::s3fnet::NetworkInterface::receivePacket(), s3f::s3fnet::OpenFlowSwitchSession::ReceiveStatsRequest(), s3f::s3fnet::Net::register_host(), s3f::s3fnet::Net::register_interface(), s3f::s3fnet::ProtocolMessage::registerMessage(), s3f::s3fnet::OpenFlowSwitchSession::RunThroughVPortTable(), s3f::s3fnet::TCPSession::sender_send_sack(), s3f::s3fnet::Controller::SendToSwitch(), s3f::s3fnet::Host::set_network_layer_protocol(), s3f::s3fnet::OpenFlowSwitchSession::SetController(), s3f::s3fnet::Nhi::setRelativeTo(), s3f::s3fnet::TCPSendWindow::TCPSendWindow(), s3f::s3fnet::TCPSession::timeout_resend(), and s3f::s3fnet::ProtocolSession::wrapup().
 {
   if(errhandler) {
     va_list ap;
     va_start(ap, fmt);
     (*errhandler)(0, fmt, ap);
     va_end(ap);
   }
   exit(1);
 }
void s3f::s3fnet::error_dump (const char * , ...)
This function is called when there's a fatal error unrelated to a system call.
The function prints the error message, dumps the core, and then terminates the program.
Definition at line 139 of file errhandle.cc.
References errhandler.
 {
   if(errhandler) {
     va_list ap;
     va_start(ap, fmt);
     (*errhandler)(0, fmt, ap);
     va_end(ap);
   }
   abort(); // will dump core
 }
void s3f::s3fnet::error_retn (const char * , ...)
This function is called when there's a non-fatal error unrelated to a system call.
The function simply prints the message and returns immediately. It can be used to print a warning message.
Definition at line 149 of file errhandle.cc.
References errhandler.
Referenced by s3f::s3fnet::ProtocolMessage::carryPayload(), s3f::s3fnet::SocketMaster::control(), s3f::s3fnet::NBSocketMaster::control(), s3f::s3fnet::Host::init(), s3f::s3fnet::RouteInfo::resolve(), and s3f::s3fnet::DMLRouteInfo::resolve().
 {
   if(errhandler) {
     va_list ap;
     va_start(ap, fmt);
     (*errhandler)(0, fmt, ap);
     va_end(ap);
   }
 }
typedef s3f::s3fnet::S3FNET_VECTOR (S3FNET_STRING)
A vector of strings.
typedef s3f::s3fnet::S3FNET_VECTOR (void *)
A vector of pointers.
typedef s3f::s3fnet::S3FNET_MAP (int , void *)
A map from an integer to a pointer.
typedef s3f::s3fnet::S3FNET_SET (long)
A set of long integers.
typedef s3f::s3fnet::S3FNET_VECTOR (long)
A vector of long integers.
char* s3f::s3fnet::sstrdup (const char * s) inline
Make a duplicate string in shared memory.
Definition at line 91 of file shstl.h.
Referenced by s3f::s3fnet::NetworkInterface::config(), s3f::s3fnet::Host::config(), s3f::s3fnet::ProtocolGraph::config(), s3f::s3fnet::ProtocolSession::config(), s3f::s3fnet::DMLRouteInfo::config(), s3f::s3fnet::TrafficPattern::configure_servers(), and main().
{
   if(!s) return 0;
   char* x = new char[strlen(s)+1]; // overloaded new operator
   strcpy(x, s);
   return x;
 }
Variable Documentation
int s3f::s3fnet::tcp_backoff[] static
Initial value:
=
  { 1, 2, 4, 8, 16, 32, 64, 64, 64, 64, 64, 64, 64 }
Definition at line 26 of file tcp_timer.cc.
Referenced by s3f::s3fnet::TCPSession::backoff_timeout().
SimInterface* s3f::s3fnet::sim_inf
Definition at line 26 of file s3fnet.cc.
Referenced by main(), and sigproc().
ErrorHandler s3f::s3fnet::errhandler = default_errhandler static
Definition at line 86 of file errhandle.cc.
Referenced by error_dump(), error_quit(), error_retn(), set_errhandler(), syserr_dump(), syserr_quit(), and syserr_retn().