S3F: openflow_interface.h File Reference
openflow_interface.h File Reference
Interfaces for interaction among openflow switches and controllers, as well as interacting with openflow library.
#include <errno.h>
#include <limits>
#include "openflow/openflow.h"
#include "openflow/nicira-ext.h"
#include "openflow/ericsson-ext.h"
#include "openflow/private/csum.h"
#include "openflow/private/poll-loop.h"
#include "openflow/private/rconn.h"
#include "openflow/private/stp.h"
#include "openflow/private/vconn.h"
#include "openflow/private/xtoxll.h"
#include "openflow/private/chain.h"
#include "openflow/private/table.h"
#include "openflow/private/datapath.h"
#include "openflow/private/dp_act.h"
#include "openflow/private/pt_act.h"
Classes
struct s3f::s3fnet::Port
Port and its metadata.
class s3f::s3fnet::Stats
struct s3f::s3fnet::Stats::FlowStatsState
State of the FlowStats request/reply.
struct s3f::s3fnet::Stats::PortStatsState
State of the PortStats request/reply.
struct s3f::s3fnet::Action
Class for handling flow table actions.
struct s3f::s3fnet::VPortAction
Class for handling virtual port table actions.
struct s3f::s3fnet::EricssonAction
Class for handling Ericsson Vendor-defined actions.
struct s3f::s3fnet::StatsDumpCallback
Callback for a stats dump request.
struct s3f::s3fnet::SwitchPacketMetadata
Packet Metadata, allows us to track the packet's metadata as it passes through the switch.
Namespaces
s3f
S3F Scalable Simulation Framework.
s3f::s3fnet
Network Simulator developed based on the S3F Scalable Simulation Framework.
Macros
#define private _private
#define delete _delete
#define list List
#define OFP_SUPPORTED_CAPABILITIES
#define OFP_SUPPORTED_ACTIONS
#define OFP_SUPPORTED_VPORT_TABLE_ACTIONS
#define PKT_BUFFER_BITS 8
#define N_PKT_BUFFERS (1 << PKT_BUFFER_BITS)
#define PKT_BUFFER_MASK (N_PKT_BUFFERS - 1)
#define PKT_COOKIE_BITS (32 - PKT_BUFFER_BITS)
Enumerations
enum s3f::s3fnet::OPENFLOW_CONTROLLER_MODEL { s3f::s3fnet::NO_OF_CONTROLLER = 0, s3f::s3fnet::OF_LEARNING_SWITCH_CONTROLLER = 1, s3f::s3fnet::OF_DROP_CONTROLLER = 2, s3f::s3fnet::OF_LEARNING_SWITCH_CONTROLLER_ENTITY = 3 }
Model of OpenFlow controller.
Functions
uint32_t save_buffer (ofpbuf *)
ofpbuf * retrieve_buffer (uint32_t id)
void discard_buffer (uint32_t id)
void set_vlan_vid (ofpbuf *buffer, sw_flow_key *key, const ofp_action_header *ah)
void set_vlan_pcp (ofpbuf *buffer, sw_flow_key *key, const ofp_action_header *ah)
void strip_vlan (ofpbuf *buffer, sw_flow_key *key, const ofp_action_header *ah)
void set_dl_addr (ofpbuf *buffer, sw_flow_key *key, const ofp_action_header *ah)
void set_nw_addr (ofpbuf *buffer, sw_flow_key *key, const ofp_action_header *ah)
void set_tp_port (ofpbuf *buffer, sw_flow_key *key, const ofp_action_header *ah)
void set_mpls_label (ofpbuf *buffer, sw_flow_key *key, const ofp_action_header *ah)
void set_mpls_exp (ofpbuf *buffer, sw_flow_key *key, const ofp_action_header *ah)
void update_checksums (ofpbuf *buffer, const sw_flow_key *key, uint32_t old_word, uint32_t new_word)
void s3f::s3fnet::ExecuteActions (OpenFlowSwitchSession *swtch, uint64_t packet_uid, ofpbuf *buffer, sw_flow_key *key, const ofp_action_header *actions, size_t actions_len, int ignore_no_fwd)
Executes a list of flow table actions.
uint16_t s3f::s3fnet::ValidateActions (const sw_flow_key *key, const ofp_action_header *actions, size_t actions_len)
Validates a list of flow table actions.
void s3f::s3fnet::ExecuteVPortActions (OpenFlowSwitchSession *swtch, uint64_t packet_uid, ofpbuf *buffer, sw_flow_key *key, const ofp_action_header *actions, size_t actions_len)
Executes a list of virtual port table entry actions.
uint16_t s3f::s3fnet::ValidateVPortActions (const ofp_action_header *actions, size_t actions_len)
Validates a list of virtual port table entry actions.
void s3f::s3fnet::ExecuteVendor (ofpbuf *buffer, const sw_flow_key *key, const ofp_action_header *ah)
Executes a vendor-defined action.
uint16_t s3f::s3fnet::ValidateVendor (const sw_flow_key *key, const ofp_action_header *ah, uint16_t len)
Validates a vendor-defined action.
Detailed Description
Interfaces for interaction among openflow switches and controllers, as well as interacting with openflow library.
authors : Dong (Kevin) Jin
Definition in file openflow_interface.h.
Macro Definition Documentation
#define private _private
Definition at line 22 of file openflow_interface.h.
#define delete _delete
Definition at line 23 of file openflow_interface.h.
#define list List
Definition at line 24 of file openflow_interface.h.
#define OFP_SUPPORTED_CAPABILITIES
Value:
(OFPC_FLOW_STATS            \
                                     | OFPC_TABLE_STATS         \
                                     | OFPC_PORT_STATS          \
                                     | OFPC_MULTI_PHY_TX        \
                                     | OFPC_VPORT_TABLE)
Definition at line 59 of file openflow_interface.h.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::SendFeaturesReply().
#define OFP_SUPPORTED_ACTIONS
Value:
((1 << OFPAT_OUTPUT)             \
                                | (1 << OFPAT_SET_VLAN_VID)     \
                                | (1 << OFPAT_SET_VLAN_PCP)     \
                                | (1 << OFPAT_STRIP_VLAN)       \
                                | (1 << OFPAT_SET_DL_SRC)       \
                                | (1 << OFPAT_SET_DL_DST)       \
                                | (1 << OFPAT_SET_NW_SRC)       \
                                | (1 << OFPAT_SET_NW_DST)       \
                                | (1 << OFPAT_SET_TP_SRC)       \
                                | (1 << OFPAT_SET_TP_DST)       \
                                | (1 << OFPAT_SET_MPLS_LABEL)   \
                                | (1 << OFPAT_SET_MPLS_EXP) )
Definition at line 66 of file openflow_interface.h.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::SendFeaturesReply().
#define OFP_SUPPORTED_VPORT_TABLE_ACTIONS
Value:
((1 << OFPPAT_OUTPUT)                \
                                            | (1 << OFPPAT_POP_MPLS)            \
                                            | (1 << OFPPAT_PUSH_MPLS)           \
                                            | (1 << OFPPAT_SET_MPLS_LABEL)      \
                                            | (1 << OFPPAT_SET_MPLS_EXP) )      \
Definition at line 79 of file openflow_interface.h.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::SendVPortTableFeatures().
#define PKT_BUFFER_BITS 8
Definition at line 399 of file openflow_interface.h.
#define N_PKT_BUFFERS (1 << PKT_BUFFER_BITS)
Definition at line 400 of file openflow_interface.h.
Referenced by s3f::s3fnet::OpenFlowSwitchSession::SendFeaturesReply().
#define PKT_BUFFER_MASK (N_PKT_BUFFERS - 1)
Definition at line 401 of file openflow_interface.h.
#define PKT_COOKIE_BITS (32 - PKT_BUFFER_BITS)
Definition at line 402 of file openflow_interface.h.
Function Documentation
uint32_t save_buffer (ofpbuf *)
Referenced by s3f::s3fnet::OpenFlowSwitchSession::pop().
ofpbuf* retrieve_buffer (uint32_t id)
Referenced by s3f::s3fnet::OpenFlowSwitchSession::AddFlow(), s3f::s3fnet::OpenFlowSwitchSession::ModFlow(), and s3f::s3fnet::OpenFlowSwitchSession::ReceivePacketOut().
void discard_buffer (uint32_t id)
Referenced by s3f::s3fnet::OpenFlowSwitchSession::AddFlow(), s3f::s3fnet::OpenFlowSwitchSession::FlowTableLookup(), s3f::s3fnet::OpenFlowSwitchSession::HandleControlInput(), and s3f::s3fnet::OpenFlowSwitchSession::ModFlow().
void set_vlan_vid (ofpbuf * buffer, sw_flow_key * key, const ofp_action_header * ah)
Referenced by s3f::s3fnet::Action::Execute().
void set_vlan_pcp (ofpbuf * buffer, sw_flow_key * key, const ofp_action_header * ah)
Referenced by s3f::s3fnet::Action::Execute().
void strip_vlan (ofpbuf * buffer, sw_flow_key * key, const ofp_action_header * ah)
Referenced by s3f::s3fnet::Action::Execute().
void set_dl_addr (ofpbuf * buffer, sw_flow_key * key, const ofp_action_header * ah)
Referenced by s3f::s3fnet::Action::Execute().
void set_nw_addr (ofpbuf * buffer, sw_flow_key * key, const ofp_action_header * ah)
Referenced by s3f::s3fnet::Action::Execute().
void set_tp_port (ofpbuf * buffer, sw_flow_key * key, const ofp_action_header * ah)
Referenced by s3f::s3fnet::Action::Execute().
void set_mpls_label (ofpbuf * buffer, sw_flow_key * key, const ofp_action_header * ah)
Referenced by s3f::s3fnet::Action::Execute().
void set_mpls_exp (ofpbuf * buffer, sw_flow_key * key, const ofp_action_header * ah)
Referenced by s3f::s3fnet::Action::Execute().
void update_checksums (ofpbuf * buffer, const sw_flow_key * key, uint32_t old_word, uint32_t new_word)