S3F: phold_node.cc File Reference
phold_node.cc File Reference
phold model for given topological graph
#include <stdio.h>
#include <stdlib.h>
#include <s3f.h>
#include "phold_node.h"
Macros
#define TRANSFER_DELAY 5
Functions
int main (int argc, char **argv)
Variables
pHold_Node ** nodes
Detailed Description
phold model for given topological graph
Definition in file phold_node.cc.
Macro Definition Documentation
#define TRANSFER_DELAY 5
Definition at line 12 of file phold_node.cc.
Referenced by pHold_Node::init().
Function Documentation
int main (int argc, char ** argv)
Definition at line 193 of file phold_node.cc.
References Interface::advance(), MyInterface::BuildModel(), Interface::InitModel(), Interface::runtime_measurements(), and STOP_BEFORE_TIME.
{
         ltime_t clock;
         if(argc != 4) {
                 printf("usage: phold num_nodes num_threads sim-time\n");
                 exit(-1);
         }
         int num_nodes   = atoi(argv[1]);
         int num_threads = atoi(argv[2]);
         long sim_time   = atoi(argv[3]);
         vector<string> inputs;
         // create num_threads timelines, microsecond time scale
         MyInterface myi( num_threads, 6 );
         // make a clique of nodes
         myi.BuildModel( num_nodes, num_threads, inputs );
         // initialize the entities
         myi.InitModel();
         // Run it for 10000 units, in ten window increments
         for(int i=1; i<=10; i++) {
                 cout << "enter window " << i << endl;
                 clock = myi.advance(STOP_BEFORE_TIME, sim_time);
                 cout << "completed window, advanced time to " << clock << endl;
         }
         myi.runtime_measurements();
 }
Variable Documentation
pHold_Node** nodes
Definition at line 65 of file phold_node.cc.