S3F: s3fnet.cc File Reference
s3fnet.cc File Reference
Main function in S3FNet.
#include "s3fnet.h"
#include <ctype.h>
#include <unistd.h>
#include "net/net.h"
#include "util/errhandle.h"
#include <signal.h>
#include "simctrl/simctrl.h"
Namespaces
s3f
S3F Scalable Simulation Framework.
s3f::s3fnet
Network Simulator developed based on the S3F Scalable Simulation Framework.
Macros
#define MAIN_DUMP(x)
Functions
static void s3f::s3fnet::show_usage (char *prognam)
static void s3f::s3fnet::strsub (S3FNET_STRING &cp, S3FNET_STRING oldstr, S3FNET_STRING newstr, int num_times=-1)
void s3f::s3fnet::sigproc (int arg)
int main (int argc, char **argv)
Variables
SimInterface * s3f::s3fnet::sim_inf
Detailed Description
Main function in S3FNet.
authors : Dong (Kevin) Jin
Definition in file s3fnet.cc.
Macro Definition Documentation
#define MAIN_DUMP (x)
Definition at line 23 of file s3fnet.cc.
Referenced by s3f::s3fnet::SimInterface::BuildModel(), and main().
Function Documentation
int main (int argc, char ** argv)
Definition at line 103 of file s3fnet.cc.
References Interface::advance(), s3f::s3fnet::SimInterface::BuildModel(), s3f::s3fnet::error_quit(), MAIN_DUMP, Interface::runtime_measurements(), s3f::s3fnet::show_usage(), s3f::s3fnet::sigproc(), s3f::s3fnet::sim_inf, s3f::s3fnet::sstrdup(), and STOP_BEFORE_TIME.
 {
   bool showuse = false;
   bool silent = false;
   for(;;)
   {
     int c = getopt(argc, argv, "hq");
     if(c == -1) break;
     switch(c)
     {
         case 'h': showuse = true; break;
         case 'q': silent = true; break;
         case '?': break;
     }
   }
   if(showuse)
   {
     show_usage(argv[0]);
     return -1;
   }
   if(argc < optind+1)
   {
     fprintf(stderr, "ERROR: incorrect command-line arguments!\n\n");
     show_usage(argv[0]);
     return -1;
   }
   MAIN_DUMP(printf("parsing dml files.\n"));
   char** dmlfiles = new char*[argc-optind+1];
   for(int i=optind; i<argc; i++)
   {
     S3FNET_STRING mystr(argv[i]);
     dmlfiles[i-optind] = sstrdup(mystr.c_str());
     //printf("=> %s\n", mystr.c_str());
   }
   dmlfiles[argc-optind] = 0;
   s3f::dml::dmlConfig* dml_cfg = new s3f::dml::dmlConfig(dmlfiles);
   if(silent == false)
   {
     if(argc == optind+1)
     {
         printf("Input DML file: %s\n", dmlfiles[0]);
     }
     else
     {
       printf("Input DML files:\n");
       for(int k=0; dmlfiles[k]; k++)
       {
           printf("  %s\n", dmlfiles[k]);
       }
     }
   }
   for(int j=0; dmlfiles[j]; j++)
   {
           delete[] dmlfiles[j];
   }
   delete[] dmlfiles;
   //main body
   ltime_t clock;
   char* str;
   int total_timeline;
   int tick_per_second;
   ltime_t sim_single_run_time;
   int seed;
   bool isOpenVZEmu;
   int openvz_emulation_type; // 0 - EMULATION_LOCAL; 1 - EMULATION_DISTRIBUTED
   int of_controller_type; // 0 - non-entity-based controller; 1 - entity-based controller
   int of_controller_model; // refer to enum OPENFLOW_CONTROLLER_MODEL in openflow_interface.h
   // parse DML inputs
   str = (char*)dml_cfg->findSingle("total_timeline");
   if(!str) total_timeline = 1; //default is one timeline
   else
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: invalid total_timeline attribute.\n");
     total_timeline = atoi(str);
     if(total_timeline < 1)
       error_quit("ERROR: total_timeline attribute must be a positive integer.\n");
   }
   str = (char*)dml_cfg->findSingle("tick_per_second");
   if(!str) tick_per_second = 0; //default smallest unit is second
   else
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: invalid tick_per_second attribute.\n");
     tick_per_second = atoi(str);
     if(tick_per_second < 0)
       error_quit("ERROR: tick_per_second attribute must be a non-negative integer.\n");
   }
   double run_time_double;
   str = (char*)dml_cfg->findSingle("run_time");
   if(!str)
   {
       error_quit("ERROR: no run_time attribute in DML to specify how long to run the simulation.\n");
   }
   else
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: invalid run_time attribute.\n");
     run_time_double = atof(str);
     if(run_time_double <= 0)
     {
         error_quit("ERROR: run_time attribute must be greater than 0.\n");
     }
   }
   sim_single_run_time = long(run_time_double * pow(10.0, tick_per_second) );
   str = (char*)dml_cfg->findSingle("seed");
   if(!str) seed = 0; //default seed
   else
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: invalid seed attribute.\n");
     seed = atoi(str);
     if(seed < 0)
       error_quit("ERROR: seed attribute must be a non-negative integer.\n");
   }
   str = (char*)dml_cfg->findSingle("enable_openvz_emulation");
   if(str)
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: invalid enable_openvz_emulation attribute.\n");
     if(!strcasecmp(str, "true")) isOpenVZEmu = true;
     else isOpenVZEmu = false;
   }
   else isOpenVZEmu = false;
 #ifndef OPENVZ_EMULATION
   if (isOpenVZEmu == true)
           error_quit("ERROR: isOpenVZEmu is set to true in DML, but OPENVZ_EMULATION is not defined.\n");
 #endif
   str = (char*)dml_cfg->findSingle("openvz_emulation_type");
   if(!str) openvz_emulation_type = 0;
   else
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: invalid openvz_emulation_type attribute.\n");
     openvz_emulation_type = atoi(str);
     if(openvz_emulation_type != 0 && openvz_emulation_type != 1)
       error_quit("ERROR: openvz_emulation_type attribute must be 0 (EMULATION_LOCAL) or 1 (EMULATION_DISTRIBUTED).\n");
   }
   str = (char*)dml_cfg->findSingle("simulated_openflow_controller_type");
   if(!str) of_controller_type = 0;
   else
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: invalid simulated_openflow_controller_type attribute.\n");
     of_controller_type = atoi(str);
     if(of_controller_type != 0 && of_controller_type != 1)
       error_quit("ERROR: simulated_openflow_controller_type attribute must be 0 (NON-ENTITY-BASED CONTROLLER) or 1 (ENTITY-BASED CONTROLLER).\n");
   }
   str = (char*)dml_cfg->findSingle("simulated_openflow_controller_model");
   if(!str) of_controller_model = 0;
   else
   {
     if(s3f::dml::dmlConfig::isConf(str))
       error_quit("ERROR: invalid simulated_openflow_controller_model attribute.\n");
     of_controller_model = atoi(str);
     if(of_controller_model < 0)
       error_quit("ERROR: simulated_openflow_controller_model attribute must be a non-negative integer.\n");
   }
   MAIN_DUMP(printf("total_timeline = %d, tick_per_second= %d, "
                   "run_time = %ld, seed = %d, enable_openvz_emulation = %d, "
                   "openvz_emulation_type = %d, simulated_openflow_controller_type = %d,"
                   "simulated_openflow_controller_model = %d \n",
                   total_timeline, tick_per_second, sim_single_run_time,
                   seed, isOpenVZEmu, openvz_emulation_type, of_controller_type, of_controller_model));
   signal(SIGINT, sigproc);
   /* Generate the first random number stream according the seed value.
    * Seed i means that we use the ith random number stream as the first one. */
   for (int i=0; i<seed; i++)
   {
           Random::RNG* rng = new Random::RNG();
           if(rng) delete rng;
   }
   //create total timelines and timescale
   sim_inf = new SimInterface( total_timeline, tick_per_second, isOpenVZEmu, openvz_emulation_type, of_controller_type, of_controller_model );
   //build, configure and initialize the simulation model
   sim_inf->BuildModel( dml_cfg );
    // run it some window increments
   int num_epoch = 1; //number of epoch to run, currently epoch is set to 1
   for(int i=1; i<=num_epoch; i++)
   {
     cout << "enter epoch window " << i << endl;
     clock = sim_inf->advance(STOP_BEFORE_TIME, sim_single_run_time);
     cout << "completed epoch window, advanced time to " << clock << endl;
   }
   cout << "Finished" << endl;
   // simulation runtime speed measurement
   sim_inf->runtime_measurements();
   // delete may cause a segmentation fault, flush buffers
   fflush(stdout);
   delete sim_inf;
   return 0;
 }