S3F: s3f::s3fnet::VPortAction Struct Reference
s3f::s3fnet::VPortAction Struct Reference
Class for handling virtual port table actions.
#include <openflow_interface.h>
Static Public Member Functions
static bool IsValidType (ofp_vport_action_type type)
static uint16_t Validate (ofp_vport_action_type type, size_t len, const ofp_action_header *ah)
Validates the action on whether its data is valid or not.
static void Execute (ofp_vport_action_type type, ofpbuf *buffer, const sw_flow_key *key, const ofp_action_header *ah)
Executes the action.
Detailed Description
Class for handling virtual port table actions.
Definition at line 243 of file openflow_interface.h.
Member Function Documentation
bool s3f::s3fnet::VPortAction::IsValidType (ofp_vport_action_type type) static
Parameters
type Type of virtual port table Action.
Returns
true if the provided type is a type of virtual port table action.
Definition at line 491 of file openflow_interface.cc.
Referenced by s3f::s3fnet::ValidateVPortActions().
 {
   switch (type)
     {
     case OFPPAT_POP_MPLS:
     case OFPPAT_PUSH_MPLS:
     case OFPPAT_SET_MPLS_LABEL:
     case OFPPAT_SET_MPLS_EXP:
       return true;
     default:
       return false;
     }
 }
uint16_t s3f::s3fnet::VPortAction::Validate (ofp_vport_action_type type, size_t len, const ofp_action_header * ah) static
Validates the action on whether its data is valid or not.
Parameters
type Type of action to validate.
len Length of the action data.
ah Action's data header.
Returns
ACT_VALIDATION_OK if the action checks out, otherwise an error type.
Definition at line 505 of file openflow_interface.cc.
Referenced by s3f::s3fnet::ValidateVPortActions().
 {
   size_t size = 0;
   switch (type)
     {
     case OFPPAT_POP_MPLS:
       size = sizeof(ofp_vport_action_pop_mpls);
       break;
     case OFPPAT_PUSH_MPLS:
       size = sizeof(ofp_vport_action_push_mpls);
       break;
     case OFPPAT_SET_MPLS_LABEL:
       size = sizeof(ofp_vport_action_set_mpls_label);
       break;
     case OFPPAT_SET_MPLS_EXP:
       size = sizeof(ofp_vport_action_set_mpls_exp);
       break;
     default:
       break;
     }
   if (len != size)
     {
       return OFPBAC_BAD_LEN;
     }
   return ACT_VALIDATION_OK;
 }
void s3f::s3fnet::VPortAction::Execute (ofp_vport_action_type type, ofpbuf * buffer, const sw_flow_key * key, const ofp_action_header * ah) static
Executes the action.
Parameters
type Type of action to execute.
buffer Buffer of the Packet if it's needed for the action.
key Matching key for the flow that is tied to this action.
ah Action's data header.
Definition at line 534 of file openflow_interface.cc.
Referenced by s3f::s3fnet::ExecuteVPortActions().
 {
   switch (type)
     {
     case OFPPAT_POP_MPLS:
       {
         ofp_vport_action_pop_mpls *opapm = (ofp_vport_action_pop_mpls *)ah;
         pop_mpls_act (0, buffer, key, &opapm->apm);
         break;
       }
     case OFPPAT_PUSH_MPLS:
       {
         ofp_vport_action_push_mpls *opapm = (ofp_vport_action_push_mpls *)ah;
         push_mpls_act (0, buffer, key, &opapm->apm);
         break;
       }
     case OFPPAT_SET_MPLS_LABEL:
       {
         ofp_vport_action_set_mpls_label *oparml = (ofp_vport_action_set_mpls_label *)ah;
         set_mpls_label_act (buffer, key, oparml->label_out);
         break;
       }
     case OFPPAT_SET_MPLS_EXP:
       {
         ofp_vport_action_set_mpls_exp *oparme = (ofp_vport_action_set_mpls_exp *)ah;
         set_mpls_exp_act (buffer, key, oparme->exp);
         break;
       }
     default:
       break;
     }
 }
The documentation for this struct was generated from the following files:
openflow_interface.h
openflow_interface.cc