S3F: s3f::s3fnet::Action Struct Reference
s3f::s3fnet::Action Struct Reference
Class for handling flow table actions.
#include <openflow_interface.h>
Static Public Member Functions
static bool IsValidType (ofp_action_type type)
static uint16_t Validate (ofp_action_type type, size_t len, const sw_flow_key *key, const ofp_action_header *ah)
Validates the action on whether its data is valid or not.
static void Execute (ofp_action_type type, ofpbuf *buffer, sw_flow_key *key, const ofp_action_header *ah)
Executes the action.
Detailed Description
Class for handling flow table actions.
Definition at line 210 of file openflow_interface.h.
Member Function Documentation
bool s3f::s3fnet::Action::IsValidType (ofp_action_type type) static
Parameters
type Type of Flow Table Action.
Returns
true if the provided type is a type of flow table action.
Definition at line 368 of file openflow_interface.cc.
Referenced by s3f::s3fnet::ExecuteActions(), and s3f::s3fnet::ValidateActions().
 {
   switch (type)
     {
     case OFPAT_OUTPUT:
     case OFPAT_SET_VLAN_VID:
     case OFPAT_SET_VLAN_PCP:
     case OFPAT_STRIP_VLAN:
     case OFPAT_SET_DL_SRC:
     case OFPAT_SET_DL_DST:
     case OFPAT_SET_NW_SRC:
     case OFPAT_SET_NW_DST:
     case OFPAT_SET_TP_SRC:
     case OFPAT_SET_TP_DST:
     case OFPAT_SET_MPLS_LABEL:
     case OFPAT_SET_MPLS_EXP:
       return true;
     default:
       return false;
     }
 }
uint16_t s3f::s3fnet::Action::Validate (ofp_action_type type, size_t len, const sw_flow_key * key, const ofp_action_header * ah) static
Validates the action on whether its data is valid or not.
Parameters
type Type of action to validate.
len Length of the action data.
key Matching key for the flow that is tied to this action.
ah Action's data header.
Returns
ACT_VALIDATION_OK if the action checks out, otherwise an error type.
Definition at line 390 of file openflow_interface.cc.
Referenced by s3f::s3fnet::ValidateActions().
 {
   size_t size = 0;
   switch (type)
     {
     case OFPAT_OUTPUT:
       {
         if (len != sizeof(ofp_action_output))
           {
             return OFPBAC_BAD_LEN;
           }
         ofp_action_output *oa = (ofp_action_output *)ah;
         // To prevent loops, make sure there's no action to send to the OFP_TABLE virtual port.
         // port is now 32-bit
         if (oa->port == OFPP_NONE || oa->port == key->flow.in_port) // htonl(OFPP_NONE);
           { // if (oa->port == htons(OFPP_NONE) || oa->port == key->flow.in_port)
             return OFPBAC_BAD_OUT_PORT;
           }
         return ACT_VALIDATION_OK;
       }
     case OFPAT_SET_VLAN_VID:
       size = sizeof(ofp_action_vlan_vid);
       break;
     case OFPAT_SET_VLAN_PCP:
       size = sizeof(ofp_action_vlan_pcp);
       break;
     case OFPAT_STRIP_VLAN:
       size = sizeof(ofp_action_header);
       break;
     case OFPAT_SET_DL_SRC:
     case OFPAT_SET_DL_DST:
       size = sizeof(ofp_action_dl_addr);
       break;
     case OFPAT_SET_NW_SRC:
     case OFPAT_SET_NW_DST:
       size = sizeof(ofp_action_nw_addr);
       break;
     case OFPAT_SET_TP_SRC:
     case OFPAT_SET_TP_DST:
       size = sizeof(ofp_action_tp_port);
       break;
     case OFPAT_SET_MPLS_LABEL:
       size = sizeof(ofp_action_mpls_label);
       break;
     case OFPAT_SET_MPLS_EXP:
       size = sizeof(ofp_action_mpls_exp);
       break;
     default:
       break;
     }
   if (len != size)
     {
       return OFPBAC_BAD_LEN;
     }
   return ACT_VALIDATION_OK;
 }
void s3f::s3fnet::Action::Execute (ofp_action_type type, ofpbuf * buffer, sw_flow_key * key, const ofp_action_header * ah) static
Executes the action.
Parameters
type Type of action to execute.
buffer Buffer of the Packet if it's needed for the action.
key Matching key for the flow that is tied to this action.
ah Action's data header.
Definition at line 453 of file openflow_interface.cc.
References set_dl_addr(), set_mpls_exp(), set_mpls_label(), set_nw_addr(), set_tp_port(), set_vlan_pcp(), set_vlan_vid(), and strip_vlan().
Referenced by s3f::s3fnet::ExecuteActions().
 {
   switch (type)
     {
     case OFPAT_OUTPUT:
       break;
     case OFPAT_SET_VLAN_VID:
       set_vlan_vid (buffer, key, ah);
       break;
     case OFPAT_SET_VLAN_PCP:
       set_vlan_pcp (buffer, key, ah);
       break;
     case OFPAT_STRIP_VLAN:
       strip_vlan (buffer, key, ah);
       break;
     case OFPAT_SET_DL_SRC:
     case OFPAT_SET_DL_DST:
       set_dl_addr (buffer, key, ah);
       break;
     case OFPAT_SET_NW_SRC:
     case OFPAT_SET_NW_DST:
       set_nw_addr (buffer, key, ah);
       break;
     case OFPAT_SET_TP_SRC:
     case OFPAT_SET_TP_DST:
       set_tp_port (buffer, key, ah);
       break;
     case OFPAT_SET_MPLS_LABEL:
       set_mpls_label (buffer, key, ah);
       break;
     case OFPAT_SET_MPLS_EXP:
       set_mpls_exp (buffer, key, ah);
       break;
     default:
       break;
     }
 }
The documentation for this struct was generated from the following files:
openflow_interface.h
openflow_interface.cc