S3F: vtime_syscall.cc File Reference
vtime_syscall.cc File Reference
source file for the virtual time system calls
#include <simctrl/vtime_syscall.h>
#include <sys/syscall.h>
#include <unistd.h>
Functions
long vtime_getenable (envid_t ctid, int *enable)
long vtime_setenable (envid_t ctid, int enable)
long vtime_getvtimeve (int *size, envid_t *list)
long vtime_getclock (envid_t ctid, struct timeval *tv)
long vtime_setclock (envid_t ctid, struct timeval *tv)
long vtime_setbarrier (envid_t ctid, struct timeval *tv)
long vtime_getvestatus (int *size, vtime_vestatus_t *list)
long vtime_releaseve (int size, int *list)
long vtime_gettraplist (envid_t ctid, int *size, struct vtime_trap *list)
long vtime_releasetrap (envid_t ctid, int size, int *flag)
long vtime_firetimer (pid_t pid)
Detailed Description
source file for the virtual time system calls
authors : Yuhao Zheng
Definition in file vtime_syscall.cc.
Function Documentation
long vtime_getenable (envid_t ctid, int * enable)
Definition at line 12 of file vtime_syscall.cc.
 {
         return syscall(__NR_vtime_getenable, ctid, enable);
 }
long vtime_setenable (envid_t ctid, int enable)
Definition at line 18 of file vtime_syscall.cc.
Referenced by SSimCtrl::emu_done(), SSimCtrl::emu_init(), SSimCtrl::emu_reset(), VESlave::slave_gotmsg_fini(), and VESlave::slave_gotmsg_init().
 {
         return syscall(__NR_vtime_setenable, ctid, enable);
 }
long vtime_getvtimeve (int * size, envid_t * list)
Definition at line 24 of file vtime_syscall.cc.
Referenced by SSimCtrl::emu_init(), VESlave::slave_gotmsg_init(), and VESlave::slave_mainloop().
 {
         return syscall(__NR_vtime_getvtimeve, size, list);
 }
long vtime_getclock (envid_t ctid, struct timeval * tv)
Definition at line 30 of file vtime_syscall.cc.
Referenced by SSimCtrl::emu_cycle(), and VESlave::slave_gotmsg_cycle().
 {
         return syscall(__NR_vtime_getclock, ctid, tv);
 }
long vtime_setclock (envid_t ctid, struct timeval * tv)
Definition at line 36 of file vtime_syscall.cc.
Referenced by SSimCtrl::emu_cycle(), SSimCtrl::emu_init(), VESlave::slave_gotmsg_cycle(), and VESlave::slave_gotmsg_init().
 {
         return syscall(__NR_vtime_setclock, ctid, tv);
 }
long vtime_setbarrier (envid_t ctid, struct timeval * tv)
Definition at line 42 of file vtime_syscall.cc.
Referenced by SSimCtrl::emu_cycle(), and VESlave::slave_gotmsg_cycle().
 {
         return syscall(__NR_vtime_setbarrier, ctid, tv);
 }
long vtime_getvestatus (int * size, vtime_vestatus_t * list)
Definition at line 48 of file vtime_syscall.cc.
Referenced by SSimCtrl::emu_cycle(), and VESlave::slave_gotmsg_cycle().
 {
         return syscall(__NR_vtime_getvestatus, size, list);
 }
long vtime_releaseve (int size, int * list)
Definition at line 54 of file vtime_syscall.cc.
Referenced by SSimCtrl::emu_cycle(), and VESlave::slave_gotmsg_cycle().
 {
         return syscall(__NR_vtime_releaseve, size, list);
 }
long vtime_gettraplist (envid_t ctid, int * size, struct vtime_trap * list)
Definition at line 60 of file vtime_syscall.cc.
Referenced by SSimCtrl::emu_cycle(), and VESlave::slave_gotmsg_cycle().
 {
         return syscall(__NR_vtime_gettraplist, ctid, size, list);
 }
long vtime_releasetrap (envid_t ctid, int size, int * flag)
Definition at line 66 of file vtime_syscall.cc.
Referenced by SSimCtrl::emu_cycle(), and VESlave::slave_gotmsg_cycle().
 {
         return syscall(__NR_vtime_releasetrap, ctid, size, flag);
 }
long vtime_firetimer (pid_t pid)
Definition at line 72 of file vtime_syscall.cc.
Referenced by SSimCtrl::emu_cycle(), and VESlave::slave_gotmsg_cycle().
 {
         return syscall(__NR_vtime_firetimer, pid);
 }